import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE DEUTERONOMY WALK 14b — THE COMPILE OF CHAPTER 16, LEAN (2026-09-23): THE TYPES BY SCRIPT, part A, after the probe's FAIL print (7b's lesson 2; Q43 FAIL):
# event_vocabulary +5 (the FIVE own-day lines — passover_at_the_place_declared 16:1-8, weeks_and_booths_declared 16:9-15, three_pilgrimages_declared 16:16-17,
# judges_in_every_gate_commanded 16:18-20, asherah_and_pillar_barred 16:21-22 — STATUTE by form at the counter's day (40, 11, 1), NO marker; NO case kind — the
# lean form has no bench scene); effect_vocabulary +15 (seven STATUSES, eight BLOCKS — the names the design set from the spine's rows) and ONE ROW AMENDED for
# the reuse (bribe_barred — Exodus 23:8's block, its FIRST entry on israel_people at 16:19). Every value the shelf's own words; the `he` FOUND in the verse
# (PHRASE — one hit or the script refuses); the fifteen names ASSERTED ABSENT before (the holes). add_types_ch15.py's form (its helpers exec'd by content
# markers from the forms folder). RUN FROM THE REPO ROOT.
import re, sqlite3, yaml, subprocess
ROOT = _ROOT
SRC12 = open(f'{ROOT}/World/step9/forms_deuteronomy_walk/add_types_ch12.py', encoding='utf-8').read()
_a = SRC12.index('db = sqlite3.connect(f"file:{ROOT}/Data/tanakh.sqlite?mode=ro", uri=True)'); _b = SRC12.index("unit = open(f'{ROOT}/logic/units/deu_12_place_name.yaml'")
exec(SRC12[_a:_b])   # the helpers: words, pv, pl, PV, LV, PHRASE, q, HE, WIT (10b's form, by content markers)
unit = open(f'{ROOT}/logic/units/deu_16_festivals_judges.yaml', encoding='utf-8').read()
CL = sorted(set(re.findall(r'DV16-\d+', unit))); ST = sorted({int(x) for x in re.findall(r'STEP_Dt_16_(\d+)', unit)})
assert len(CL) == 8 and ST[0] == 1 and ST[-1] == 22, (CL, ST[:3], ST[-1])
led = open(f'{ROOT}/logic/oral_triage/deu_16_reeh_shoftim_2026-09-23.md', encoding='utf-8').read()
N_SRC = len(re.findall(r'^- (?:Onkelos|Sifrei)', led, re.M)); assert N_SRC == 136, N_SRC
CORPUS = f"deu_16_festivals_judges (STEP_Dt_16_1 through STEP_Dt_16_22; claims {CL[0]} through {CL[-1]})"
SUB = "submitted by cold_run_festivals_judges.py [subjects: %s] (the narrative scene, THE DEUTERONOMY WALK 14b — LEAN); re-submitted on the sequential tape by cold_run_sequence.py; consumed by law_festivals_judges (cold_run_festivals_judges.py) -> %s"
INK = "Deut 16:1-22; Onkelos Deut 16:1-22 (the export's chapter 16 the DB's — twenty-two verses in both numberings); the Sifrei on Deuteronomy ON THE CHAPTER — piskaot 127-146 (the spine whole, 111 rows; nineteen heads in verse order and 135 headless, folded in by position) with the three rows elsewhere citing the chapter (52:4, 147:2, 281:1); THE LEAN PASS (owner-ruled 2026-09-23): no docket — the exam the eight Mishnah rows the spine cites in its own Hebrew (Berakhot 1:5, Pesachim 3:7, Beitzah 1:1, Sukkah 1:4, Chagigah 1:1, 1:2, 1:4, 1:5), logic/oral_triage/deu_16_reeh_shoftim_exam_2026-09-23.md; the full process owed"
D, X, N_, L_, G_ = 'Deut', 'Exod', 'Num', 'Lev', 'Gen'
KINDS = [
 ("passover_at_the_place_declared", "statute",
  "the Passover at the place declared — 'OBSERVE THE MONTH OF AVIV AND KEEP THE PASSOVER to the LORD your God, for in the month of Aviv the LORD your God brought you out of Egypt by night; and you shall sacrifice the Passover to the LORD your God, flock and herd, in the place which the LORD will choose to make His name dwell there; you shall eat no leaven with it; seven days you shall eat unleavened bread with it, the bread of affliction … no leaven shall be seen with you in all your border seven days, nor shall any of the flesh which you sacrifice the first day at evening remain all night until the morning; you may not sacrifice the Passover within any of your gates … but at the place … at evening, at the going down of the sun, the season of your going out of Egypt; and you shall cook it and eat it in the place … and in the morning you shall turn and go to your tents; six days you shall eat unleavened bread, and on the seventh day a solemn assembly to the LORD your God: you shall do no work' (Deut 16:1-8) — THE PLACE ADDED TO THE PASSOVER (the formula's six seats in the chapter): the line writes passover_at_the_place_commanded (a STATUS), passover_in_the_gates_barred, leaven_with_the_passover_barred and flesh_till_morning_barred (BLOCKS) and seventh_day_assembly_commanded (a STATUS) on israel_people; the intercalation (the Sifrei 127:1), the name (128:1), the herd the festival offering (129:6), the ban's sixth hour (130:1), the two measures (131:3 — Mishnah Beitzah 1:1), the party of one (132:1), the three phrases (133:2), the lodging (134:2-3), six and seven (135:1-2), the intermediate days handed to the sages (135:3) — the parameters and the data rows; the Passover's own procedure by CALL (pesach, moadim, musafim, calendar, erection)",
  HE(D, 16, 1, 8, "observe the month of Aviv and keep the Passover"), WIT(D, 16, 1, 8) + WIT(X, 34, 18, 18) + WIT(X, 13, 6, 7) + WIT(X, 12, 8, 10) + WIT(L_, 23, 5, 8), INK, CORPUS,
  SUB % ("moses (to israel)", "passover_at_the_place_commanded and seventh_day_assembly_commanded on israel_people (STATUSES — the place the chapter's addition; the intermediate days' work a parameter), passover_in_the_gates_barred, leaven_with_the_passover_barred and flesh_till_morning_barred (BLOCKS); at the counter's day (40, 11, 1), no marker"), ["the_month", "the_place", "the_leaven", "the_night", "the_gates", "the_clock", "the_morning", "the_seventh"]),
 ("weeks_and_booths_declared", "statute",
  "the feasts of weeks and of booths declared — 'SEVEN WEEKS YOU SHALL COUNT FOR YOURSELF: from the time the sickle is first put to the standing grain you shall begin to count seven weeks; and you shall keep the feast of weeks to the LORD your God with the measure of the freewill offering of your hand … and you shall rejoice before the LORD your God, you and your son and your daughter, your manservant and your maidservant, the Levite in your gates, the sojourner, the fatherless and the widow in your midst, in the place … and you shall remember that you were a slave in Egypt; THE FEAST OF BOOTHS YOU SHALL KEEP SEVEN DAYS, when you gather in from your threshing floor and your winepress; and you shall rejoice in your feast … seven days you shall keep a feast to the LORD your God in the place which the LORD will choose, for the LORD your God will bless you in all your produce and in all the work of your hands, and you shall be altogether joyful' (Deut 16:9-15) — THE PLACE ADDED TO THE TWO FEASTS: the line writes weeks_at_the_place_commanded and booths_at_the_place_commanded (STATUSES) on israel_people; the omer's three rules and the reaping by night (136:3, 136:8), the freewill measure (137:3), the pilgrimage's three commandments (138:3), the household (16:11 = 16:14), the vegetables' tithe year (140:6), the booth's ownership (140:4), the roofing (Mishnah Sukkah 1:4), the compensation (142:1), the joy's offering (Mishnah Chagigah 1:4) — the parameters and the data rows; the omer's count and the booths' seven by CALL (moadim, musafim); the rejoicing by CALL (place_name); the slave remembered by CALL (covenant_at_horeb)",
  HE(D, 16, 9, 15, "seven weeks you shall count for yourself"), WIT(D, 16, 9, 15) + WIT(L_, 23, 15, 16) + WIT(L_, 23, 34, 36) + WIT(L_, 23, 42, 42) + WIT(D, 12, 12, 12) + WIT(D, 5, 15, 15), INK, CORPUS,
  SUB % ("moses (to israel)", "weeks_at_the_place_commanded and booths_at_the_place_commanded on israel_people (STATUSES — the place the chapter's addition; the count from the sickle, the seven days' compensation parameters); at the counter's day (40, 11, 1), no marker"), ["the_sickle", "the_feast_of_weeks", "the_rejoicing", "the_slave_remembered", "the_booths", "the_gathering", "the_seven_days"]),
 ("three_pilgrimages_declared", "statute",
  "the three pilgrimages declared — 'THREE TIMES A YEAR ALL YOUR MALES SHALL APPEAR before the LORD your God in the place which He will choose: at the feast of unleavened bread, at the feast of weeks and at the feast of booths; and none shall appear before the LORD empty; each man as the gift of his hand, according to the blessing of the LORD your God which He has given you' (Deut 16:16-17) — THE PLACE ADDED TO THE PILGRIMAGE (Exodus 23:14-17 and 34:23 the twins, 2 Chronicles 8:13 the run's case): the line writes three_pilgrimages_commanded (a STATUS) and empty_appearance_barred (a BLOCK) on israel_people; who appears (Mishnah Chagigah 1:1), the two amounts (1:2), the gift of the hand (1:5), the order of the names the delay's clock (143:7), the guard of the land (52:4) — the parameters and the data rows; the appearing owed and the appearance gift by CALL (calendar, erection)",
  HE(D, 16, 16, 17, "three times a year all your males shall appear"), WIT(D, 16, 16, 17) + WIT(X, 23, 14, 17) + WIT(X, 34, 20, 20) + WIT(X, 34, 23, 24), INK, CORPUS,
  SUB % ("moses (to israel)", "three_pilgrimages_commanded on israel_people (a STATUS — the exempt list and the minor's two arms a parameter), empty_appearance_barred (a BLOCK — the two amounts and the gift of the hand parameters); at the counter's day (40, 11, 1), no marker"), ["the_three_times", "the_males", "the_empty", "the_gift_of_the_hand"]),
 ("judges_in_every_gate_commanded", "statute",
  "the judges in every gate commanded — 'JUDGES AND OFFICERS YOU SHALL SET FOR YOURSELF IN ALL YOUR GATES which the LORD your God gives you, tribe by tribe, and they shall judge the people with righteous judgment; you shall not wrest judgment, you shall not respect persons, and you shall not take a bribe, for the bribe blinds the eyes of the wise and perverts the words of the righteous; justice, justice you shall pursue, that you may live and inherit the land which the LORD your God gives you' (Deut 16:18-20) — THE COURTS IN EVERY GATE (Exodus 18:21-25's founding and Deut 1:16-17's charge on the tape the references, never a second write): the line writes judges_and_officers_commanded and justice_pursuit_commanded (STATUSES), judgment_wresting_barred and person_respecting_barred (BLOCKS) and bribe_barred (Exodus 23:8's block — ITS FIRST ENTRY ON ANY ENTITY, DB7's declaration) on israel_people; the three tiers (144:1-5), the acquittal final (144:12 — Mishnah Sanhedrin 4:1) parameters; the court's sizes, the two faces and the bribe by CALL (exodus_story, opening_speech, ordinances, holiness, second_tablets)",
  HE(D, 16, 18, 20, "judges and officers you shall set for yourself in all your gates"), WIT(D, 16, 18, 20) + WIT(X, 23, 6, 8) + WIT(L_, 19, 15, 15) + WIT(D, 1, 16, 17) + WIT(X, 18, 21, 21) + WIT(X, 18, 25, 25), INK, CORPUS,
  SUB % ("moses (to israel)", "judges_and_officers_commanded and justice_pursuit_commanded on israel_people (STATUSES — the three tiers and the acquittal final parameters), judgment_wresting_barred and person_respecting_barred (BLOCKS), bribe_barred REUSED — its first entry anywhere (Exodus 23:8's block declared, never written before); at the counter's day (40, 11, 1), no marker"), ["the_judges_and_officers", "the_gates_and_the_tribes", "the_wresting", "the_faces", "the_bribe", "the_justice"]),
 ("asherah_and_pillar_barred", "statute",
  "the asherah and the pillar barred — 'YOU SHALL NOT PLANT FOR YOURSELF AN ASHERAH OF ANY TREE BESIDE THE ALTAR of the LORD your God which you shall make for yourself; and you shall not set up for yourself a pillar, which the LORD your God hates' (Deut 16:21-22) — the asherah beside the altar (the Sifrei 145:1-3's a fortiori; Exodus 34:13, Deut 7:5 and 12:3 the demolition's kin by CALL) and THE PILLAR HATED (146:1 'loved by the fathers, hated by the sons' — the tape's own entries on Jacob's pillars the fathers' love: the law's reason a change of state read from the world): the line writes asherah_beside_the_altar_barred and pillar_barred (BLOCKS) on israel_people; Leviticus 26:1's pillar by CALL (journeys)",
  HE(D, 16, 21, 22, "you shall not plant for yourself an asherah of any tree beside the altar"), WIT(D, 16, 21, 22) + WIT(X, 34, 13, 13) + WIT(D, 7, 5, 5) + WIT(D, 12, 3, 3) + WIT(L_, 26, 1, 1), INK, CORPUS,
  SUB % ("moses (to israel)", "asherah_beside_the_altar_barred and pillar_barred on israel_people (BLOCKS — the pillars' change of state a data row read from the tape's own entries); at the counter's day (40, 11, 1), no marker"), ["the_asherah", "the_pillar"]),
]
path = f"{ROOT}/World/step9/event_vocabulary.yaml"
text = open(path, encoding='utf-8').read()
have = yaml.safe_load(text)['events']
HOLEK = sorted(k for k in have if any(t in k for t in ('passover_at_the_place', 'weeks_and_booths', 'three_pilgrimages', 'judges_in_every_gate', 'asherah_and_pillar')))
assert HOLEK == [] or HOLEK == sorted(k[0] for k in KINDS), HOLEK   # the five kinds absent before this sitting — or this sitting's own five, written by the first run (idempotent)
out = []
for name, form, en, he, wit, ink, corpus, tape, fields in KINDS:
    if name in have: continue
    out.append(f"  {name}:\n    en: {q(en)}\n    he: {q(he)}\n    form: {form}\n    witness: [{', '.join(q(w) for w in wit)}]\n    ink: {q(ink)}\n    corpus: {q(corpus)}\n    tape: {q(tape)}\n    fields: [{', '.join(q(f) for f in fields)}]\n")
if out:
    i = text.index('\nnarrative_verbs:\n')
    text = text[:i] + '\n' + ''.join(out).rstrip('\n') + text[i:]
    open(path, 'w', encoding='utf-8').write(text)
after = yaml.safe_load(open(path, encoding='utf-8'))
assert all(k[0] in after['events'] for k in KINDS)
print('kinds: %d added of %d, registry %d; the ledger sources %d' % (len(out), len(KINDS), len(after['events']), N_SRC))
# ---- FIFTEEN new effects (the shelf's own words for their names and values, the `he` FOUND in the verse); the kin's effects asserted present; THE FIFTEEN NAMES ASSERTED ABSENT before (the holes) ----
path = f"{ROOT}/World/step9/effect_vocabulary.yaml"
text = open(path, encoding='utf-8').read()
fx = yaml.safe_load(text)['effects']
for e in ('accepted', 'exempt', 'lashes', 'barred_from_it', 'bribe_barred', 'appearance_owed', 'appearance_gift_owed', 'counts_omer', 'dwells_in_booths', 'burn_remainder', 'courts_established', 'judges_charged', 'judgment_perverted', 'place_chosen_required', 'rejoicing_before_the_lord_commanded', 'pilgrim_land_guarded', 'pillar_anointed', 'pillar_raised', 'passover_in_its_time', 'commanded'):
    assert e in fx, e
assert fx['bribe_barred']['ledger_op'] == 'block' and fx['appearance_owed']['ledger_op'] == 'heaven' and fx['appearance_gift_owed']['ledger_op'] == 'debit' and fx['counts_omer']['ledger_op'] == 'timer' and fx['dwells_in_booths']['ledger_op'] == 'timer' and fx['judgment_perverted']['ledger_op'] == 'heaven', 'the kin ops as the recon read them'
OWN15 = ('passover_at_the_place_commanded', 'passover_in_the_gates_barred', 'leaven_with_the_passover_barred', 'flesh_till_morning_barred', 'seventh_day_assembly_commanded', 'weeks_at_the_place_commanded', 'booths_at_the_place_commanded', 'three_pilgrimages_commanded', 'empty_appearance_barred', 'judges_and_officers_commanded', 'judgment_wresting_barred', 'person_respecting_barred', 'justice_pursuit_commanded', 'asherah_beside_the_altar_barred', 'pillar_barred')
HOLE0 = sorted(k for k in fx if any(t in k for t in ('passover_at_the', 'passover_in_the_gates', 'leaven_with', 'flesh_till', 'seventh_day_assembly', 'weeks_at', 'booths_at', 'three_pilgrim', 'empty_appearance', 'judges_and_officers', 'judgment_wrest', 'person_respect', 'justice_pursuit', 'asherah', 'pillar_barred')))
print('the registry\'s effects naming the chapter\'s fifteen before this sitting:', HOLE0)
assert not any(k in fx for k in OWN15) and HOLE0 == [], HOLE0   # THE HOLES — the fifteen names absent before this sitting (the recon measured them absent)
HE_PLACE = PHRASE(D, 16, 6, ['תזבח', 'את', 'הפסח', 'בערב']); HE_GATES = PHRASE(D, 16, 5, ['לא', 'תוכל', 'לזבח', 'את', 'הפסח', 'באחד', 'שעריך']); HE_LEAVEN = PHRASE(D, 16, 3, ['לא', 'תאכל', 'עליו', 'חמץ']); HE_FLESH = PHRASE(D, 16, 4, ['ולא', 'ילין', 'מן', 'הבשר'])
HE_SEVENTH = PHRASE(D, 16, 8, ['וביום', 'השביעי', 'עצרת', 'ליהוה', 'אלהיך', 'לא', 'תעשה', 'מלאכה']); HE_WEEKS = PHRASE(D, 16, 10, ['ועשית', 'חג', 'שבעות', 'ליהוה', 'אלהיך']); HE_BOOTHS = PHRASE(D, 16, 13, ['חג', 'הסכת', 'תעשה', 'לך', 'שבעת', 'ימים'])
HE_THREE = PHRASE(D, 16, 16, ['שלוש', 'פעמים', 'בשנה', 'יראה', 'כל', 'זכורך']); HE_EMPTY = PHRASE(D, 16, 16, ['ולא', 'יראה', 'את', 'פני', 'יהוה', 'ריקם']); HE_JUDGES = PHRASE(D, 16, 18, ['שפטים', 'ושטרים', 'תתן', 'לך', 'בכל', 'שעריך'])
HE_WREST = PHRASE(D, 16, 19, ['לא', 'תטה', 'משפט']); HE_FACES = PHRASE(D, 16, 19, ['לא', 'תכיר', 'פנים']); HE_BRIBE = PHRASE(D, 16, 19, ['ולא', 'תקח', 'שחד']); HE_JUSTICE = PHRASE(D, 16, 20, ['צדק', 'צדק', 'תרדף'])
HE_ASHERAH = PHRASE(D, 16, 21, ['לא', 'תטע', 'לך', 'אשרה', 'כל', 'עץ', 'אצל', 'מזבח']); HE_PILLAR = PHRASE(D, 16, 22, ['ולא', 'תקים', 'לך', 'מצבה'])
EX = "cold_run_festivals_judges.py (%s; the line %s) — THE LEAN PASS: the exam the Mishnah rows the spine cites (deu_16_reeh_shoftim_exam_2026-09-23.md)"
W14 = 'THE DEUTERONOMY WALK 14b (2026-09-23)'
NEW = [
 ('passover_at_the_place_commanded', 'status', "the Passover at the place commanded — the STATUS the line passover_at_the_place_declared writes on Israel: 'you shall sacrifice the Passover to the LORD your God, flock and herd, IN THE PLACE which the LORD will choose to make His name dwell there' (16:2), 'but at the place … you shall sacrifice the Passover AT EVENING, AT THE GOING DOWN OF THE SUN, the season of your going out of Egypt; and you shall cook it and eat it in the place … and in the morning you shall turn and go to your tents' (16:6-7) — THE PLACE ADDED TO THE PASSOVER (place_chosen_required's formula at six seats in the chapter, by CALL; chapter 12's status UNMOVED); the name (the Sifrei 128:1-2 — pesach.paschal_procedure('for_its_sake') by CALL), the herd the festival offering (129:6 — Onkelos writing the same), the three phrases of the clock (133:2 — the calendar's day slots between_the_evenings / sunset / night; the eating until midnight by CALL), the cooking read as roasting (134:1 — 2 Chronicles 35:13 the run's case; 'roasted only' by CALL), the lodging night (134:2-3), the intercalation a parameter (127:1 — the calendar's rows for the count era; the exodus era's Aviv OWED)", HE_PLACE + " (you shall sacrifice the Passover at evening — Deut 16:6)", "Deut 16:1-2, 16:6-7, 12:5 (place_name by CALL); Exodus 12:6-9 (pesach by CALL), 34:18, 34:25 (erection by CALL), 23:15 (calendar by CALL); Leviticus 23:5 (moadim by CALL); Numbers 9:2-3 (pesach_sheni by CALL), 28:16 (musafim by CALL); 2 Chronicles 35:13; Onkelos 16:1-2, 16:6 ('the Passover from the sons of the flock, and the holy slaughterings from the oxen'; the Shekhinah at the place); the Sifrei on Deuteronomy 127:1-129:6, 132:1-134:3; Mishnah Berakhot 1:5, Pesachim 3:7 (the exam)", CORPUS, EX % ("F1 the_passover_at_the_place — the_intercalation, the_passovers_name, the_flock_and_the_herd, the_place, the_three_phrases, the_cooking, the_lodging_night", "passover_at_the_place_declared")),
 ('passover_in_the_gates_barred', 'block', "the Passover in the gates barred — the BLOCK the line passover_at_the_place_declared writes on Israel: 'YOU MAY NOT SACRIFICE THE PASSOVER WITHIN ANY OF YOUR GATES which the LORD your God gives you' (16:5) — 'you may not' one of the three true prohibitions of eating and slaughter outside the place (the Sifrei 147:2 with 12:17 and 17:1 — the order of offerings no prohibition); 'for one' read as the party's size, a dispute (132:1 — R. Judah: the Passover slaughtered for an individual; the party of one a DATA row); the gates' bar 12:17's by CALL (place_name — holy_things_in_the_gates_barred UNMOVED)", HE_GATES + " (you may not sacrifice the Passover within one of your gates — Deut 16:5)", "Deut 16:5, 12:17 (place_name by CALL), 17:1 (ahead); Onkelos 16:5 ('you have no permission'); the Sifrei on Deuteronomy 132:1-2, 147:2 (reread whole); Mishnah Pesachim 8:7 (the party — owed to the full process)", CORPUS, EX % ("F1 the_passover_at_the_place — the_gates_bar, the_party_of_one", "passover_at_the_place_declared")),
 ('leaven_with_the_passover_barred', 'block', "leaven with the Passover barred — the BLOCK the line passover_at_the_place_declared writes on Israel: 'YOU SHALL NOT EAT LEAVEN WITH IT; seven days you shall eat unleavened bread with it, the bread of affliction' (16:3), 'no leaven shall be seen with you in all your border seven days' (16:4 — Exodus 13:7's six tokens shared in order) — THE BAN'S ONSET FROM THE SIXTH HOUR of the fourteenth (the Sifrei 130:1 — R. Judah: 'with it' the slaughter's time; moadim.passover()['slaughter_window'] after_midday by CALL: a clock datum the_leaven_bans_onset); the bread of affliction narrows the kind (130:3 — scalded bread and cakes out); THE TWO MEASURES (131:3 — Mishnah Beitzah 1:1 cited in the spine's Hebrew: Shammai leavening an olive and leaven a date, Hillel both an olive — both arms a DATA row); the leaven remembered on the road (Mishnah Pesachim 3:7 — return and remove, or nullify in the heart: three arms); the nights remembered (Mishnah Berakhot 1:5 — 'all the days of your life')", HE_LEAVEN + " (you shall not eat leaven with it — Deut 16:3)", "Deut 16:3-4; Exodus 12:15-20, 13:3-7 (pesach.leaven_machine by CALL — the window 14th evening to 21st evening), 23:15, 34:18 (calendar, erection by CALL), 23:18, 34:25 (the offering over leaven — erection.repeats by CALL); Leviticus 23:5-6 (moadim by CALL); Onkelos 16:3-4 ('leaven' חמיר the book's one seat at 16:4); the Sifrei on Deuteronomy 130:1-131:3; Mishnah Beitzah 1:1, Pesachim 3:7, Berakhot 1:5 (the exam — read whole)", CORPUS, EX % ("F1 the_passover_at_the_place — the_leaven_bans_onset, the_bread_of_affliction, the_two_measures, the_leaven_on_the_road, the_night_remembered", "passover_at_the_place_declared")),
 ('flesh_till_morning_barred', 'block', "the flesh till morning barred — the BLOCK the line passover_at_the_place_declared writes on Israel: 'nor shall any of the flesh which you sacrifice the first day at evening REMAIN ALL NIGHT UNTIL THE MORNING' (16:4) — Exodus 12:10's 'let nothing of it remain until morning' and 34:25's 'the sacrifice of the feast of the Passover shall not remain until the morning' the twins (Exodus 34:25's two tokens shared): the remainder burned (pesach.paschal_procedure('leftover') 'burn on the 16th' by CALL — burn_remainder the tape's one entry on aaron-and-sons, the offerings' law), the fourteenth's festival offering the shelf's reading of the second seat (erection.repeats by CALL); the night's flesh the Passover's own night (the eating until midnight by CALL)", HE_FLESH + " (none of the flesh shall remain overnight — Deut 16:4)", "Deut 16:4; Exodus 12:10 (pesach by CALL — burn_remainder), 23:18, 34:25 (erection.repeats, calendar.offering_windows by CALL); Onkelos 16:4; the Sifrei on Deuteronomy 131:4-5", CORPUS, EX % ("F1 the_passover_at_the_place — the_nights_flesh", "passover_at_the_place_declared")),
 ('seventh_day_assembly_commanded', 'status', "the seventh day's assembly commanded — the STATUS the line passover_at_the_place_declared writes on Israel: 'SIX DAYS YOU SHALL EAT UNLEAVENED BREAD, AND ON THE SEVENTH DAY A SOLEMN ASSEMBLY to the LORD your God: you shall do no work' (16:8) — SIX against Exodus 13:6's SEVEN (the diff two tokens: the seventh day's unleavened bread optional after the first night, the Sifrei 135:1-2 — a DATA row the_six_and_the_seven); 'solemn assembly' the Torah's three seats (Leviticus 23:36's eighth day, Numbers 29:35 — the headless piska 135's own citation); THE SEVENTH RESTRAINED FROM ALL WORK, THE SIXTH NOT — 'Scripture handed it to the sages to say which day is forbidden and which permitted, which work forbidden and which permitted' (135:3): THE INTERMEDIATE DAYS' WORK A PARAMETER Scripture gives the sages to fill — the code/data law's seat named in the Hebrew; the work class by CALL (moadim.work_class('passover_7') servile_only; musafim.pesach_shavuot('the_seventh'))", HE_SEVENTH + " (and on the seventh day a solemn assembly to the LORD your God, you shall do no work — Deut 16:8)", "Deut 16:8; Exodus 12:16, 13:6 (pesach by CALL); Leviticus 23:6-8 (moadim by CALL — the work class), 23:36; Numbers 28:25 (musafim by CALL), 29:35 (the headless row's citation); Onkelos 16:8 ('gathering' for the assembly); the Sifrei on Deuteronomy 135:1-3 (the headless piska, folded in by position); Mishnah Moed Katan (the sages' table — owed to the full process)", CORPUS, EX % ("F1 the_passover_at_the_place — the_six_and_the_seven, the_seventh_days_assembly", "passover_at_the_place_declared")),
 ('weeks_at_the_place_commanded', 'status', "the feast of weeks at the place commanded — the STATUS the line weeks_and_booths_declared writes on Israel: 'SEVEN WEEKS YOU SHALL COUNT FOR YOURSELF: from the time the sickle is first put to the standing grain you shall begin to count seven weeks; and you shall keep the feast of weeks to the LORD your God with the measure of the freewill offering of your hand … and you shall rejoice before the LORD your God … in the place' (16:9-11) — THE COUNT FROM THE SICKLE (sharing nothing in order with Leviticus 23:15-16's 'morrow of the sabbath … fifty days'; Onkelos supplies 'the omer of the waving'): the omer's three rules standing, first, sickle (the Sifrei 136:3), REAPING AND COUNTING BY NIGHT, BRINGING BY DAY (136:8 — the count's start the night after the first day; moadim.omer()['morrow_reading'] festival and ['count_length'] 49 by CALL, omer_day 1/16 the registry's; counts_omer the moadim engine's timer UNMOVED on the tape); the freewill measure (137:3 — the tithe admitted); the pilgrimage's three commandments — the festival offering, the appearance, rejoicing (138:3); the rejoicing and the household by CALL (place_name — rejoicing_before_the_lord_commanded UNMOVED; the nine members 16:11 = 16:14); the slave remembered (16:12 — 5:15's clause by CALL to covenant_at_horeb, 15:15's twin)", HE_WEEKS + " (and you shall keep the feast of weeks to the LORD your God — Deut 16:10)", "Deut 16:9-12, 12:12 (place_name by CALL), 5:15 (covenant_at_horeb by CALL), 23:26 (the sickle's other seat, ahead); Exodus 23:16, 34:22 (calendar, erection by CALL — the feast of the harvest, the first fruits of the wheat); Leviticus 23:15-21 (moadim by CALL — the omer, the two loaves); Numbers 28:26 (musafim by CALL — the day of the firstfruits); Onkelos 16:9 ('the omer of the waving'); the Sifrei on Deuteronomy 136:1-139:2; Mishnah Menachot 10:3, 10:8-9 (owed to the full process)", CORPUS, EX % ("F2 the_weeks_from_the_sickle — the_sickles_three_rules, the_reaping_by_night, the_freewill_measure, the_three_commandments_of_the_pilgrimage, the_rejoicing_and_the_household, the_slave_remembered", "weeks_and_booths_declared")),
 ('booths_at_the_place_commanded', 'status', "the feast of booths at the place commanded — the STATUS the line weeks_and_booths_declared writes on Israel: 'THE FEAST OF BOOTHS YOU SHALL KEEP SEVEN DAYS, when you gather in from your threshing floor and your winepress; and you shall rejoice in your feast … seven days you shall keep a feast to the LORD your God IN THE PLACE which the LORD will choose, for the LORD your God will bless you in all your produce and in all the work of your hands, and you shall be altogether joyful' (16:13-15) — THE PLACE ADDED TO THE BOOTHS ('the feast of booths' spelled defective at 16:13 alone in the Bible); the gathering the vegetables' tithe year (the Sifrei 140:6); the booth's ownership a dispute (140:4 — R. Eliezer each man's, the sages all Israel in one booth); THE ROOFING (Mishnah Sukkah 1:4 cited in the spine's Hebrew — what is not susceptible to impurity and grows from the ground roofs: a PARAMETER); the seven days by CALL (moadim.sukkot()['length'] 7, dwells_in_booths the moadim engine's timer UNMOVED; musafim.sukkot('the_dates')); THE COMPENSATION (142:1 — the festival offering missed on the first day brought any day of the seven: a PARAMETER the_compensation_window; Shavuot's seven by Deut 16:16's own analogy — musafim.pesach_shavuot('redress_days') by CALL); THE JOY'S OFFERING (141:2, 142:6 — Mishnah Chagigah 1:4 cited in the spine's Hebrew: vows and freewill offerings serve, birds and meal offerings not)", HE_BOOTHS + " (the feast of booths you shall keep for yourself seven days — Deut 16:13)", "Deut 16:13-15, 31:10-11 (the assembly's feast, ahead); Exodus 23:16, 34:22 (calendar, erection by CALL — the feast of ingathering at the year's end and turn); Leviticus 23:34-36, 23:39-43 (moadim by CALL); Numbers 29:12-38 (musafim by CALL); Onkelos 16:13, 16:16 ('the feast of huts'); the Sifrei on Deuteronomy 140:1-142:7; Mishnah Sukkah 1:4, Chagigah 1:4 (the exam — read whole)", CORPUS, EX % ("F3 the_feast_of_booths — the_gathering, the_booths_ownership, the_roofing, the_seven_days, the_compensation, the_joys_offering, altogether_joyful", "weeks_and_booths_declared")),
 ('three_pilgrimages_commanded', 'status', "the three pilgrimages commanded — the STATUS the line three_pilgrimages_declared writes on Israel: 'THREE TIMES A YEAR ALL YOUR MALES SHALL APPEAR before the LORD your God in the place which He will choose: at the feast of unleavened bread, at the feast of weeks and at the feast of booths' (16:16) — Exodus 23:14-17 and 34:23 the twins with the place added ('three times' spelled full here; 2 Chronicles 8:13 the one other verse with the three names in this order — the run's case): the appearing owed by CALL (calendar.pilgrimage — the able male owes the three appearings; appearance_owed the calendar's heaven entry on its case world, NONE on the tape UNMOVED); WHO APPEARS — Mishnah Chagigah 1:1 cited in the spine's Hebrew: all obligated except the deaf-mute, the imbecile, the minor, the tumtum, the hermaphrodite, women, unfreed slaves, the lame, the blind, the sick, the old and one who cannot ascend on foot; THE MINOR two houses — a PARAMETER the_exempt_from_appearing; the order of the three names the delay's clock (the Sifrei 143:7 — 23:22's vow ahead); the guard of the land (52:4 — Exodus 34:24 by CALL to erection.repeats)", HE_THREE + " (three times a year all your males shall appear — Deut 16:16)", "Deut 16:16, 31:11; Exodus 23:14, 23:17 (calendar by CALL), 34:23-24 (erection by CALL); 2 Chronicles 8:13 (the run's case); Onkelos 16:16 ('three times in the year', 'shall be seen'); the Sifrei on Deuteronomy 143:1-7, 52:4 (reread whole); Mishnah Chagigah 1:1 (the exam — read whole)", CORPUS, EX % ("F4 the_three_pilgrimages — the_three_times, who_appears, the_order_of_the_names, the_guard_of_the_land", "three_pilgrimages_declared")),
 ('empty_appearance_barred', 'block', "the empty appearance barred — the BLOCK the line three_pilgrimages_declared writes on Israel: 'AND NONE SHALL APPEAR BEFORE THE LORD EMPTY; each man as the gift of his hand, according to the blessing of the LORD your God which He has given you' (16:16-17) — the clause's third seat after Exodus 23:15 and 34:20 ('empty' at one seat in this form; the singular 'shall appear'): THE APPEARANCE OFFERING by CALL (erection.repeats — 'empty'/'empty' the standing liability, Bekhorot 51b; appearance_gift_owed the erection's debit on its case world, NONE on the tape UNMOVED); THE TWO AMOUNTS (the Sifrei 143:8 — Mishnah Chagigah 1:2: Shammai the appearance two silver and the festival offering a ma'ah, Hillel the reverse: a PARAMETER with both arms); THE GIFT OF THE HAND (143:9 — Mishnah Chagigah 1:5 cited in the spine's Hebrew: many eaters and little property, much property and few eaters, both few, both many — a PARAMETER with the four cases)", HE_EMPTY + " (and none shall appear before the LORD empty — Deut 16:16)", "Deut 16:16-17, 12:15 ('according to the blessing' — the six tokens shared); Exodus 23:15, 34:20 (erection.repeats, calendar by CALL — the clause moved between the two seats), 34:23; Onkelos 16:16-17 ('empty' one seat); the Sifrei on Deuteronomy 143:8-9; Mishnah Chagigah 1:2, 1:5 (the exam — read whole)", CORPUS, EX % ("F4 the_three_pilgrimages — not_empty, the_two_amounts, the_gift_of_the_hand", "three_pilgrimages_declared")),
 ('judges_and_officers_commanded', 'status', "judges and officers commanded — the STATUS the line judges_in_every_gate_commanded writes on Israel: 'JUDGES AND OFFICERS YOU SHALL SET FOR YOURSELF IN ALL YOUR GATES which the LORD your God gives you, tribe by tribe, and they shall judge the people with righteous judgment' (16:18) — THE COURT FOR ALL ISRAEL from 'for yourself' (the Sifrei 144:1), every tribe's and every city's court (144:2-4), 'in all your gates' the small court compared to the great — judges and executes (144:5): THE THREE TIERS A PARAMETER the_three_tiers with the sizes by CALL (exodus_story.jethro('sanhedrin_sizes') (71, 23); ordinances.courts('twenty_three')); Exodus 18:21-25's founding on the tape (courts_established ONE on israel_people, valued the four denominations and 78,600) and Deut 1:16-17's charge (judges_charged ONE on the_court) the references, never a second write; the qualified judge by CALL (opening_speech — the qualities, the charge); 'judges and officers' the one seat of the pair in the Bible, the participles the register's only three", HE_JUDGES + " (judges and officers you shall set for yourself in all your gates — Deut 16:18)", "Deut 16:18, 1:16-17 (opening_speech by CALL — judges_charged), 17:8-13 (the high court, ahead); Exodus 18:21-26 (exodus_story by CALL — courts_established); Numbers 11:16 (the seventy); Onkelos 16:18 ('judges and punishers'); the Sifrei on Deuteronomy 144:1-11; Mishnah Sanhedrin 1:1-6 (by CALL — owed to the full process)", CORPUS, EX % ("F5 the_judges_in_every_gate — the_court_for_all_israel, the_gates_and_the_tribes, the_qualified_judge", "judges_in_every_gate_commanded")),
 ('judgment_wresting_barred', 'block', "the wresting of judgment barred — the BLOCK the line judges_in_every_gate_commanded writes on Israel: 'YOU SHALL NOT WREST JUDGMENT' (16:19) — Exodus 23:6's 'you shall not wrest the judgment of your poor' and 24:17's sojourner (the three seats of the phrase; 281:1 on 24:17 read whole — two prohibitions for the sojourner, three for the fatherless sojourner) with Leviticus 19:15's 'you shall do no wrong in judgment' (the judge's five effects — judgment_perverted the holiness engine's heaven entry, by CALL); ordinances.courts('poor_not_glorified') and holiness.conduct('no_favor') by CALL", HE_WREST + " (you shall not wrest judgment — Deut 16:19)", "Deut 16:19, 24:17 (ahead; the Sifrei 281:1 read whole), 27:19; Exodus 23:6 (ordinances by CALL), 23:2-3; Leviticus 19:15 (holiness by CALL); Onkelos 16:19; the Sifrei on Deuteronomy 144:6-8", CORPUS, EX % ("F5 the_judges_in_every_gate — wrest_no_judgment", "judges_in_every_gate_commanded")),
 ('person_respecting_barred', 'block', "the respecting of persons barred — the BLOCK the line judges_in_every_gate_commanded writes on Israel: 'YOU SHALL NOT RESPECT PERSONS' (16:19 — 'recognize faces') — Deut 1:17's 'you shall not respect persons in judgment' (the charge's clause, judges_charged on the_court by CALL to opening_speech('no_faces') — befriend / estrange disputed) and Leviticus 19:15's two faces, the poor's and the great's (holiness.conduct('no_favor') by CALL); 10:17's 'who lifts no face' the declaration about God (second_tablets by CALL); the Sifrei 144:9-10 — the appointer who sets a judge over the community for his wealth", HE_FACES + " (you shall not respect persons — Deut 16:19)", "Deut 16:19, 1:17 (opening_speech by CALL), 10:17 (second_tablets by CALL); Leviticus 19:15 (holiness by CALL); Onkelos 16:19; the Sifrei on Deuteronomy 144:9-10", CORPUS, EX % ("F5 the_judges_in_every_gate — respect_no_person", "judges_in_every_gate_commanded")),
 ('justice_pursuit_commanded', 'status', "the pursuit of justice commanded — the STATUS the line judges_in_every_gate_commanded writes on Israel: 'JUSTICE, JUSTICE YOU SHALL PURSUE, that you may live and inherit the land which the LORD your God gives you' (16:20) — the one seat of the doubled word in the Bible: THE ACQUITTAL FINAL (the Sifrei 144:12 — one who left the court acquitted is not brought back to conviction; Mishnah Sanhedrin 4:1 by CALL to ordinances.courts('one_vs_two') — money cases tilt by one either way, capital cases by one for merit and two for liability, reversed for merit not for liability: a PARAMETER the_acquittal_final); 'that you may live and inherit' the ground (the appointment of fit judges keeps Israel alive and settles them on their land — 144:13); the true judgment truly by CALL (opening_speech('judge_righteously'))", HE_JUSTICE + " (justice, justice you shall pursue — Deut 16:20)", "Deut 16:20, 4:1, 8:1 (the ground's twins); Exodus 23:2, 23:7 (ordinances by CALL — the majority, the innocent); Leviticus 19:15 (holiness by CALL); Onkelos 16:20 ('truth, truth you shall be pursuing'); the Sifrei on Deuteronomy 144:12-13; Mishnah Sanhedrin 4:1 (by CALL — owed to the full process)", CORPUS, EX % ("F5 the_judges_in_every_gate — justice_justice, that_you_may_live", "judges_in_every_gate_commanded")),
 ('asherah_beside_the_altar_barred', 'block', "the asherah beside the altar barred — the BLOCK the line asherah_and_pillar_barred writes on Israel: 'YOU SHALL NOT PLANT FOR YOURSELF AN ASHERAH OF ANY TREE BESIDE THE ALTAR of the LORD your God which you shall make for yourself' (16:21) — the asherah bare here and at Exodus 34:13 alone (7:5 and 12:3 'their asherim' — the demolition's kin by CALL: erection, seven_nations, place_name); the Sifrei 145:1-3 — the planting's own prohibition and the a fortiori the spine reads (145:3 reread whole from chapter 12's sitting); 'any tree' (145:4 — even a house of wood beside the altar in the shelf's reading — a DATA row); the asherah's shade and wood by CALL (seven_nations — the sitter barred, the wood-burner lashed); Mishnah Avodah Zarah 3:5's reason — a hand made it (erection.covenant by CALL)", HE_ASHERAH + " (you shall not plant for yourself an asherah of any tree beside the altar — Deut 16:21)", "Deut 16:21, 7:5 (seven_nations by CALL), 12:3 (place_name by CALL); Exodus 34:13 (erection by CALL), 20:21-23 (the altar's own law — ordinances.altar by CALL); Onkelos 16:21 ('asherah' one seat in the book); the Sifrei on Deuteronomy 145:1-4; Mishnah Avodah Zarah 3:5-8 (by CALL — owed to the full process)", CORPUS, EX % ("F6 the_asherah_and_the_pillar — the_asherah_beside_the_altar, any_tree", "asherah_and_pillar_barred")),
 ('pillar_barred', 'block', "the pillar barred — the BLOCK the line asherah_and_pillar_barred writes on Israel: 'AND YOU SHALL NOT SET UP FOR YOURSELF A PILLAR, WHICH THE LORD YOUR GOD HATES' (16:22) — THE PILLAR LOVED BY THE FATHERS AND HATED BY THE SONS (the Sifrei 146:1): the tape's own entries the fathers' love — pillar_anointed TWO on the_pillar_of_bethel (Genesis 28:18, 35:14) and pillar_raised ONE on the_pillar_of_gilead (31:45), Jacob's — THE LAW'S REASON A CHANGE OF STATE ON THE TAPE, read by the cell from the world's ledgers (a DATA row the_pillars_change_of_state); Leviticus 26:1's 'you shall not raise up for yourselves a pillar' the twin (journeys.the_command by CALL — the figured stones at 33:52); the pillar at eleven Torah seats (Jacob's six, Sinai's, the ban's); Onkelos 'a pillar' (the word kept)", HE_PILLAR + " (and you shall not set up for yourself a pillar — Deut 16:22)", "Deut 16:22, 12:31 (the shared 'hates'), 7:5, 12:3; Genesis 28:18, 31:45, 35:14, 35:20 (the tape's pillars — pillar_anointed, pillar_raised); Exodus 24:4 (Sinai's twelve), 34:13; Leviticus 26:1 (journeys by CALL — the figured stones); Numbers 33:52; Onkelos 16:22; the Sifrei on Deuteronomy 146:1", CORPUS, EX % ("F6 the_asherah_and_the_pillar — the_pillar_hated", "asherah_and_pillar_barred")),
]
added = 0
for name, op, en, he, ink, corpus, exam in NEW:
    if name in fx: continue
    text = text.rstrip('\n') + '\n' + f"  {name}:\n    en: {q(en)}\n    he: {q(he)}\n    ledger_op: {op}   # {W14}: chapter 16's compile, LEAN — {name}, the name and the value from the spine's rows and the eight Mishnah rows\n    ink: {q(ink)}\n    corpus: {q(corpus)}\n    exam: {q(exam)}\n"
    added += 1
# ---- THE ONE REUSED ROW AMENDED with the chapter's seat — bribe_barred's FIRST entry on any entity (DB7's declaration; its ink names Deut 16:19 already) ----
def amend(name, field, addition):
    global text
    i = text.index(f'\n  {name}:\n'); j = text.index(f'\n    {field}: ', i); k = text.index('\n', j + 1)
    line = text[j + 1:k]; assert line.endswith('"') and line.count('"') >= 2, (name, field, line[-40:])
    assert W14 not in line, (name, field, 'already amended')
    text = text[:k - 1] + addition.replace('"', '\\"') + text[k - 1:]
amend('bribe_barred', 'ink', "; %s: Deut 16:19 THE FIRST WRITE — the line judges_in_every_gate_commanded writes bribe_barred on israel_people at the counter's day (40, 11, 1): %s (and you shall not take a bribe — Deut 16:19); the Sifrei 144:11; DB7's 'NEVER written on any entity' 0 -> 1 (the one stale literal, retyped before the tape); even to judge truly (Ketubot 105a:10 — second_tablets by CALL)" % (W14, HE_BRIBE))
amend('bribe_barred', 'exam', "; %s: cold_run_festivals_judges.py (F5 the_judges_in_every_gate — take_no_bribe; the first entry written on the tape kind judges_in_every_gate_commanded)" % W14)
open(path, 'w', encoding='utf-8').write(text)
fx = yaml.safe_load(open(path, encoding='utf-8'))['effects']
assert all(n in fx for n, *_ in NEW) and fx['passover_at_the_place_commanded']['ledger_op'] == 'status' and fx['pillar_barred']['ledger_op'] == 'block' and fx['justice_pursuit_commanded']['ledger_op'] == 'status' and sum(1 for n, op, *_ in NEW if op == 'block') == 8 and sum(1 for n, op, *_ in NEW if op == 'status') == 7
assert W14 in fx['bribe_barred']['ink'] and 'cold_run_festivals_judges.py' in fx['bribe_barred']['exam'], 'the bribe amended'
print('effects: %d added (registry %d); bribe_barred amended; the he found in the verses: %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s' % (added, len(fx), HE_PLACE, HE_GATES, HE_LEAVEN, HE_FLESH, HE_SEVENTH, HE_WEEKS, HE_BOOTHS, HE_THREE, HE_EMPTY, HE_JUDGES, HE_WREST, HE_FACES, HE_BRIBE, HE_JUSTICE, HE_ASHERAH, HE_PILLAR))
