# ---- TWELVE new effects (the shelf's own words for their names and values, the `he` FOUND in the verse); the kin's effects asserted present; THE TWELVE NAMES ASSERTED ABSENT before (the holes) ----
path = f"{ROOT}/World/step9/effect_vocabulary.yaml"
text = open(path, encoding='utf-8').read()
fx = yaml.safe_load(text)['effects']
for e in ('accepted', 'exempt', 'lashes', 'barred_from_it', 'goes_free', 'released', 'consecrated_firstborn', 'jubilee_release', 'pledge_returned_by_sunset', 'interest_barred', 'land_release', 'sabbath_debt', 'goes_out_in_the_jubilee', 'wage_due_by_morning', 'blessings_for_hearing', 'cry_heard', 'bears_sin', 'holy_things_in_the_gates_barred', 'profane_slaughter_permitted', 'treasured_people', 'love_owed', 'redeem_or_break'):
    assert e in fx, e
assert fx['blessings_for_hearing']['ledger_op'] == 'heaven' and fx['cry_heard']['ledger_op'] == 'heaven' and fx['bears_sin']['ledger_op'] == 'status' and fx['holy_things_in_the_gates_barred']['ledger_op'] == 'block' and fx['consecrated_firstborn']['ledger_op'] == 'status' and fx['goes_free']['ledger_op'] == 'status' and fx['jubilee_release']['ledger_op'] == 'timer', (fx['blessings_for_hearing']['ledger_op'], fx['cry_heard']['ledger_op'], fx['bears_sin']['ledger_op'], fx['holy_things_in_the_gates_barred']['ledger_op'])
OWN12 = ('debt_release_owed', 'exaction_barred', 'hand_opening_commanded', 'hand_shutting_barred', 'base_thought_barred', 'work_of_the_hand_blessed', 'furnishing_commanded', 'empty_sending_barred', 'severance_gift_owed', 'serves_for_ever', 'firstling_sanctification_commanded', 'firstling_work_and_shearing_barred')
HOLE0 = sorted(k for k in fx if any(t in k for t in ('debt_release', 'exaction', 'hand_open', 'hand_shut', 'base_thought', 'work_of_the_hand', 'furnish', 'empty_send', 'severance', 'serves_for', 'firstling_sanctif', 'firstling_work', 'shearing')))
print('the registry\'s effects naming the debts\' release, the exaction, the hand, the base thought, the furnishing, the empty sending, the severance, the for-ever service, the firstling\'s sanctification or its work and shearing before this sitting:', HOLE0)
assert not any(k in fx for k in OWN12) and all(k not in OWN12 for k in HOLE0), (HOLE0,)   # THE HOLES — the twelve names absent before this sitting (the design measured them absent at sitting 13's tree)
HE_REL = PHRASE(D, 15, 1, ['תעשה', 'שמטה']); HE_EXACT = PHRASE(D, 15, 2, ['לא', 'יגש', 'את', 'רעהו', 'ואת', 'אחיו']); HE_OPEN = PHRASE(D, 15, 8, ['פתח', 'תפתח', 'את', 'ידך', 'לו'])
HE_SHUT = PHRASE(D, 15, 7, ['לא', 'תאמץ', 'את', 'לבבך', 'ולא', 'תקפץ', 'את', 'ידך']); HE_BASE = PHRASE(D, 15, 9, ['השמר', 'לך', 'פן', 'יהיה', 'דבר', 'עם', 'לבבך', 'בליעל']); HE_WORK = PHRASE(D, 15, 10, ['יברכך', 'יהוה', 'אלהיך', 'בכל', 'מעשך', 'ובכל', 'משלח', 'ידך'])
HE_FURN = PHRASE(D, 15, 14, ['העניק', 'תעניק', 'לו', 'מצאנך', 'ומגרנך', 'ומיקבך']); HE_EMPTY = PHRASE(D, 15, 13, ['לא', 'תשלחנו', 'ריקם']); HE_SEV = PHRASE(D, 15, 14, ['אשר', 'ברכך', 'יהוה', 'אלהיך', 'תתן', 'לו'])
HE_EVER = PHRASE(D, 15, 17, ['והיה', 'לך', 'עבד', 'עולם']); HE_SANC = PHRASE(D, 15, 19, ['הזכר', 'תקדיש', 'ליהוה', 'אלהיך']); HE_SHEAR = PHRASE(D, 15, 19, ['לא', 'תעבד', 'בבכר', 'שורך', 'ולא', 'תגז', 'בכור', 'צאנך'])
HE_BLESS = PHRASE(D, 15, 5, ['אם', 'שמוע', 'תשמע', 'בקול', 'יהוה', 'אלהיך']); HE_CRY = PHRASE(D, 15, 9, ['וקרא', 'עליך', 'אל', 'יהוה']); HE_SIN = PHRASE(D, 15, 9, ['והיה', 'בך', 'חטא']); HE_GATES = PHRASE(D, 15, 20, ['לפני', 'יהוה', 'אלהיך', 'תאכלנו', 'שנה', 'בשנה', 'במקום'])
EX = "cold_run_release_firstborn.py (%s; the exam kind release_firstborn_case; the line %s)"
NEW = [
 ('debt_release_owed', 'status',
  "the debts' release owed — the STATUS the line release_law_declared writes on Israel: 'AT THE END OF SEVEN YEARS YOU SHALL MAKE A RELEASE; and this is the manner of the release: every creditor shall release what he lent his neighbor' (15:1-2) — THE RELEASE AN EFFECT ON THE DEBTS AT THE SEVENTH YEAR'S END, its value THE RELEASE DATE a CLOCK DATUM read from the cycle by CALL (yovel.cycle — the year whose class is sabbath_of_the_land; 'END' is the year's end by I2 with 31:10 at the Sifrei 111:1; Rosh Hashanah 8b:8-12 the sabbatical's new year, Arakhin 28b:7 the release at its end; the running world before the entry 'no count'); ONE CALENDAR for the whole world (111:3-7 — the two paradigms deadlocked, the analogy 'seven years'/'seven years' breaks the deadlock; R. Yose the Galilean's 'the year of release draws near' 111:8, 117:4); THE ONSET after the conquest and the division (111:9-11; 41:3; Arakhin 32b:10 the count renewed at Ezra's return) and THE TERRITORY in the Land and outside (112:11 'to the LORD' — Kiddushin 38b:1-4; when the jubilee is not in force the money's release stands by the Sages' decree, Gittin 36a:13-36b:1, Moed Katan 2b:17); THE OBJECT loans only — not theft, deposit, wage or shop credit unless made a standing debt (112:5-7; Mishnah Sheviit 10:1-2; Tosefta Sheviit 8:5-7), the pledge-loan and the notes handed to the court not released (113:2; Sheviit 10:2), what cannot yet be exacted not released (Makkot 3b:4; Bava Batra 145b:2); THE MANNER 'I release it' (112:1; Sheviit 10:8; Gittin 37b:1-2 — the creditor may lift his eyes until 'nevertheless'), the oath released by the same word (Shevuot 49a:2); THE TWO YEARS' POWERS (112:2-4 — the seventh year releases the loan, the jubilee frees the slave); HILLEL'S PROZBUL A PARAMETER FROM THE ANSWER SHEET (113:3; Sheviit 10:3-4 the writ's text; Gittin 36a:11-37b:8 — the reason 15:9, the ground rabbinic against rabbinic, the land condition and the perforated pot, the writ by speech, the orphans' exemption, the presumption 'I had one and lost it')",
  HE_REL + " (you shall make a release — Deut 15:1)",
  "Deut 15:1-3, 15:9, 31:10 (I2 'end'/'end'); Exodus 23:10-11 (calendar.sabbatical by CALL — the land's release); Leviticus 25:1-13 (yovel.cycle, yovel.sabbatical, yovel.jubilee by CALL); Exodus 22:24 (ordinances.loan by CALL — the creditor); Deut 23:21 (the foreigner's interest ahead); Jeremiah 34:14 (the run's case); Onkelos 15:1-3 ('the master of the claim', 'shall not claim'); the Sifrei on Deuteronomy 111:1-113:3; Mishnah Sheviit 10:1-9; Tosefta Sheviit 8:1-11; Babylonian Talmud Gittin 36a:11-37b:8; Kiddushin 38b:1-4; Arakhin 28b:7, 32b:10-33a:4; Rosh Hashanah 8b:8-12, 9a:1; Makkot 3a:15-3b:14; Moed Katan 2b:17; Shevuot 49a:2; Shabbat 148b:12; Bava Batra 145b:2",
  CORPUS, EX % ("F1 the_release — the_release_at_the_years_end, the_one_calendar, the_onset, the_territory, the_object, the_manner, the_two_years_powers, the_pledge_loan, the_prozbul", "release_law_declared")),
 ('exaction_barred', 'block',
  "the exaction barred — the BLOCK the line release_law_declared writes on Israel: 'HE SHALL NOT EXACT IT OF HIS NEIGHBOR AND HIS BROTHER, because the LORD's release has been proclaimed; the foreigner you may exact' (15:2-3) — 'he shall not exact' TO PUT HIM UNDER A PROHIBITION (the Sifrei 112:8): the dunning creditor's negative command, the release's block; 'his neighbor' and 'his brother' TWO EXCLUSIONS (112:9-10 — the foreigner outside the bar, the resident alien with the brother); 'THE FOREIGNER YOU MAY EXACT' A POSITIVE COMMAND (113:1 — the same noun's rule at 23:21's interest ahead; yovel.interest_scope('foreigner') by CALL: the foreigner charged, the brother not); Onkelos 'shall not claim' (יתבע — the verb of the claim, not the approach); the creditor who exacts in the eighth year transgresses (Mishnah Sheviit 10:8 the debtor who pays anyway thanked; Makkot 3b:7-10 the stipulation against the release void in its form, valid as the debtor's waiver)",
  HE_EXACT + " (he shall not exact it of his neighbor and his brother — Deut 15:2)",
  "Deut 15:2-3, 23:21 (the foreigner's interest ahead — the same noun); Exodus 22:24 ('as a creditor' — ordinances.loan by CALL); Leviticus 25:35-37 (yovel.interest, yovel.interest_scope by CALL); Onkelos 15:2-3; the Sifrei on Deuteronomy 112:8-10, 113:1; Mishnah Sheviit 10:8; Babylonian Talmud Makkot 3b:7-10; Gittin 37b:1-2",
  CORPUS, EX % ("F1 the_release — the_exaction, the_two_exclusions, the_foreigner", "release_law_declared")),
 ('hand_opening_commanded', 'status',
  "the hand's opening commanded — the STATUS the line hand_opening_commanded writes on Israel: 'OPEN, YOU SHALL OPEN YOUR HAND TO HIM, and lend, you shall lend him sufficient for his need … open, you shall open your hand to your brother, to your poor and to your needy in your land' (15:8, 15:11) — the doublings read REPEAT WITHOUT LIMIT, a hundred times (the Sifrei 116:12, 117:6; Bava Metzia 31b:7-12 the doubled verbs unconditional: 'open' to another city's poor, 'give' a small gift, 'lend' the one with means who will not use them; Ketubot 67b:11 the same); THE OBLIGATION TO LEND — lending_is_obligation the ordinances' cell by CALL (22:24's 'if money you lend' read as obligation FROM 15:8's 'you shall surely lend'); THE RANKS OF THE POOR A PRECEDENCE PARAMETER the_needy_ranks (116:4-8 — not others; the hungrier; the father's brother before the mother's; the city before another city; the Land before outside it; the door-to-door beggar owed nothing from the fund — Bava Metzia 71a:3-4 'the poor of your city first', the ladder ordinances.loan(priority_ladder) by CALL); THE MEASURE OF NEED the_measure_of_need (116:15-18 — 'sufficient for his need': not to enrich him, even a horse and a slave, Hillel's horse, the litra of meat, the wife by 'for him'; Mishnah Peah 8:7-9 the poor man's ration; Ketubot 67b:2-12 the house, the bed and the table, the two who refuse); THE PLEDGE A DISPUTE the_pledge_dispute (116:14 — R. Judah and the Sages; Bava Metzia 31b); the gift dressed as a loan (116:13); the secret gift (117:7 — Mishnah Shekalim 5:6 the chamber of the silent); THE FOUR GRADES OF THE GIVER (117:8); the three nouns three measures (118:3); THE WORDS OF THE SCRIBES at 'hear, you shall hear' (115:1) and the light as the weighty (115:2); the needy's condition the state variable (114:1, 118:1); the people's blessing on the work of the hand the ground (15:10)",
  HE_OPEN + " (open, you shall open your hand to him — Deut 15:8)",
  "Deut 15:7-11, 24:14-15 (the hireling ahead — holiness.wage by CALL); Exodus 22:24 (ordinances.loan by CALL — lending_is_obligation, priority_ladder); Leviticus 25:35 (yovel.support_duty by CALL); Leviticus 19:9-10 (holiness.gifts — poor_defined by CALL); Deut 14:28-29 (food_tithe.the_third_year — the_four_in_want by CALL); Onkelos 15:7-11 ('sufficient for his need' כמסת חסרוניה); the Sifrei on Deuteronomy 115:1-118:3; Mishnah Peah 8:7-9; Mishnah Shekalim 5:6; Babylonian Talmud Bava Metzia 31b:7-12, 71a:3-4; Ketubot 67b:2-18; Taanit 21a:2-4",
  CORPUS, EX % ("F3 the_hand_opened — the_doubled_verbs, the_lending_obligation, the_needy_ranks, the_measure_of_need, the_pledge_dispute, the_gift_as_a_loan, the_secret_gift, the_four_grades; F2 the_needy_and_the_blessing — the_scribes_words", "hand_opening_commanded")),
 ('hand_shutting_barred', 'block',
  "the hand's shutting barred — the BLOCK the line hand_opening_commanded writes on Israel: 'YOU SHALL NOT HARDEN YOUR HEART NOR SHUT YOUR HAND from your needy brother' (15:7) — TWO VERBS, THE HEART'S STATE BEFORE THE HAND'S (the Sifrei 116:10-11: 'harden your heart' — there are those who grieve whether to give or not; 'shut your hand' — those who stretch out the hand and close it); the verb 'shut' ONE seat in the Torah of seven in the Bible, 'harden your heart' Sihon's hardening (2:30) the book's other seat; beware and lest two prohibitions beside it (117:2); the one who shuts his hand before the seventh year's release the exam's person (15:9's base thought the second block)",
  HE_SHUT + " (you shall not harden your heart nor shut your hand — Deut 15:7)",
  "Deut 15:7, 2:30 (Sihon's heart hardened — the book's other seat); Exodus 22:24; Onkelos 15:7 ('shut' תקפץ); the Sifrei on Deuteronomy 116:10-11, 117:2; Babylonian Talmud Bava Metzia 31b:7-12; Ketubot 67b:11",
  CORPUS, EX % ("F3 the_hand_opened — the_heart_before_the_hand", "hand_opening_commanded")),
 ('base_thought_barred', 'block',
  "the base thought barred — the BLOCK the line hand_opening_commanded writes on Israel: 'BEWARE LEST THERE BE A BASE THOUGHT IN YOUR HEART, saying: the seventh year, the year of release, is near — and your eye be evil against your needy brother and you give him nothing' (15:9) — 'BEWARE' and 'LEST' two prohibitions (the Sifrei 117:2); 'BASE' (בליעל, belial) WITHOUT A YOKE (117:1 — E30, the word's parts: 'without a yoke'); READ AS IDOLATRY BY I2 WITH 13:14 (117:3 — 'base' is said here and 'base' of the sons of Belial who lead a city astray: whoever shuts his eyes from charity is as an idolater — THE TRANSFER taught by the Sifrei, the labeled edge to seducers' Belial DATA row; the Torah's two seats of the word: 13:14 and here); Hillel's reason for the prozbul this verse (Gittin 36a:11); THE CRY A HASTENER AND THE SIN UNCONDITIONAL (117:5 with 279:4 word for word: cry_heard and bears_sin REUSED — 'and he cry to the LORD against you and it be sin in you', 24:15's hireling seven tokens in order); Onkelos 'in wickedness' (ברשע — 13:14's sons of Belial rendered by the same word)",
  HE_BASE + " (beware lest there be a base thought in your heart — Deut 15:9)",
  "Deut 15:9, 13:14 (the sons of Belial — seducers by CALL, the TRANSFER taught by the Sifrei 117:3), 24:15 (the hireling's cry ahead — 'and it be sin in you'); Exodus 22:22-23 (the pledged poor man's cry — cry_heard's first seat); Onkelos 15:9 ('in wickedness'); the Sifrei on Deuteronomy 117:1-5; Babylonian Talmud Gittin 36a:11; Makkot 3b:11-14 (the thirty days from the doubled name); Bava Metzia 31b",
  CORPUS, EX % ("F3 the_hand_opened — the_base_thought, the_cry_and_the_sin", "hand_opening_commanded")),
 ('work_of_the_hand_blessed', 'heaven',
  "the work of the hand blessed — the HEAVEN entry the lines hand_opening_commanded and hebrew_slave_law_declared write on Israel: 'for because of this thing THE LORD YOUR GOD WILL BLESS YOU IN ALL YOUR WORK AND IN ALL YOU PUT YOUR HAND TO' (15:10) and 'and the LORD your God will bless you in all that you do' (15:18) — the blessing beside every money loss (the Sifrei 123:3): the gift to the needy (15:10 — 14:29's twin 'in all the work of your hand', six tokens in order; the Sifrei 117:9-10: even if he said 'I will give' and did not give, even if he gave and it was lost — the blessing on the resolve) and the slave sent away free (15:18 — 'double the hire of a hireling he has served you six years'); TWO ENTRIES on Israel at the chapter's own day, the first the tape's (14:29's line wrote none — the registry held no name: measured at the types step); Onkelos 15:10 'because of this word'",
  HE_WORK + " (the LORD your God will bless you in all your work and in all you put your hand to — Deut 15:10)",
  "Deut 15:10, 15:18, 14:29 (the twin — food_tithe.the_third_year by CALL), 2:7, 30:9 (the clause's other seats), 28:8, 28:20 (ahead); Onkelos 15:10, 15:18; the Sifrei on Deuteronomy 117:9-10, 123:3; Babylonian Talmud Bava Metzia 31b:7-12",
  CORPUS, EX % ("F3 the_hand_opened — the_blessing_on_the_work; F5 the_awl_and_the_double_hire — the_blessing_beside_the_loss", "hand_opening_commanded and hebrew_slave_law_declared")),
 ('furnishing_commanded', 'status',
  "the furnishing commanded — the STATUS the line hebrew_slave_law_declared writes on Israel: 'FURNISH, YOU SHALL FURNISH HIM from your flock, your threshing floor and your winepress; of that with which the LORD your God has blessed you, you shall give him' (15:14) — THE THREE SENDINGS THE GIFT'S CASES from the verb said three times (the Sifrei 119:1 — 'when you send him away free', 'you shall not send him away empty', 'when you send him': the self-redeemer out), NOT TO HIS HEIRS (119:3 — 'to him'; Kiddushin 15a:7, 16b:16 not his creditor, not the self-seller 15a:6; the sendings extended by 'you shall not send' and 'when you send' 16b:19, 'from you' excluding the fugitive and the one who deducts 16b:20 with R. Meir's arm 16b:17), ONLY WHAT RESEMBLES THE PARTICULAR — fit for a blessing or bearing young, A DISPUTE the_gift_feature (119:4 — I6's shape; Kiddushin 17a:16-17b:1: money out for R. Shimon, mules out for R. Eliezer ben Yaakov), 'grant, you shall grant' in any case (17b:2) against R. Elazar ben Azarya's plain reading ('the Torah speaks in the language of men' 17b:3), THE MEASURE the blessing (119:5 — Kiddushin 17a:5-14: five selas of each kind by 'empty'/'empty' with the firstborn, thirty by 'giving'/'giving' with the gored slave, fifty by the valuations and 'poverty'/'poverty'; 'grasped too much, grasped nothing' 17a:12): severance_gift_owed the DEBIT the case writes on the master toward the slave, its amount A PARAMETER the_severance_gift by CALL to erection.repeats(five_selas_to_the_severance_gift); EGYPT THE MODEL OF THE GIFT (120:1 — the exodus's 'not empty' 3:21, wealth_promised on the tape; the two spoils in two verses); the maidservant's gift to her father while he lives (16b:11-13), her brothers excluded (16b:14); Onkelos 'set apart, you shall set apart' (אפרשא תפרש)",
  HE_FURN + " (furnish, you shall furnish him from your flock, your threshing floor and your winepress — Deut 15:14)",
  "Deut 15:13-14, 16:13 ('your floor and your press' — Sukkot's twin); Exodus 3:21-22, 12:35-36 (the exodus's 'not empty' — exodus_story by CALL; wealth_promised on the tape); Exodus 21:32 (the gored slave's thirty — 'giving'/'giving'); Leviticus 27:1-8 (the valuations' fifty — yovel.valuation by CALL); Numbers 18:16 (the firstborn's five — 'empty'/'empty'); Onkelos 15:13-14; the Sifrei on Deuteronomy 119:1-5, 120:1; Mishnah Kiddushin 1:2; Tosefta Kiddushin 1:5; Babylonian Talmud Kiddushin 14b:9-11, 15a:6-7, 16b:11-20, 17a:5-17b:3",
  CORPUS, EX % ("F4 the_hebrew_slave — the_three_sendings, the_gifts_persons, the_gift_feature, the_severance_gift, egypt_the_model", "hebrew_slave_law_declared")),
 ('empty_sending_barred', 'block',
  "the empty sending barred — the BLOCK the line hebrew_slave_law_declared writes on Israel: 'and when you send him away free from you, YOU SHALL NOT SEND HIM AWAY EMPTY' (15:13) — the gift's negative command beside its positive (15:14); 'empty' sixteen in the Bible, the Torah's six — the exodus's 'you shall not go out empty' (Exodus 3:21), the festivals' 'not empty' (23:15, 34:20; 16:16 ahead), Jacob's wage, Ruth; the master who sends the slave away empty transgresses (Kiddushin 16b:19 — the sendings extended by 'you shall not send' and 'when you send'); the self-redeemer, the fugitive and the one who deducts outside the gift (119:1; Kiddushin 16b:17-20); 15:12's 'you shall send him away free' the send's first seat, 15:13's the second and 15:18's the third (the verb three times — 119:1)",
  HE_EMPTY + " (you shall not send him away empty — Deut 15:13)",
  "Deut 15:12-13, 15:18, 16:16 (ahead — 'not empty' at the festivals); Exodus 3:21 (exodus_story by CALL), 23:15, 34:20 (erection.repeats by CALL); Genesis 31:42; Ruth 1:21, 3:17; Onkelos 15:13 ('empty' ריקן); the Sifrei on Deuteronomy 119:1; Babylonian Talmud Kiddushin 16b:17-20",
  CORPUS, EX % ("F4 the_hebrew_slave — the_empty_sending", "hebrew_slave_law_declared")),
 ('severance_gift_owed', 'debit',
  "the severance gift owed — the DEBIT the exam's case writes on the master toward the slave at the sending (the case kind release_firstborn_case through F4 the_hebrew_slave): 'of that with which the LORD your God has blessed you, YOU SHALL GIVE HIM' (15:14) — ITS AMOUNT A PARAMETER the_severance_gift, THREE ARMS WITH THEIR GROUNDS (Kiddushin 17a:5-14 — R. Meir five selas of each kind, fifteen in all, by 'empty'/'empty' with the firstborn 17a:7-8; R. Judah thirty by 'giving'/'giving' with the gored slave 17a:10; R. Simeon fifty by the valuations and 'poverty'/'poverty' 17a:13-14; the selection rule 'grasped too much, grasped nothing' 17a:12; R. Meir's total not less 17a:6) — erection.repeats('five_selas_to_the_severance_gift') the cell already pricing it by CALL; THE PERSONS: to him and not his heirs (15a:7), not the self-seller (15a:6), not his creditor (Tutai 16b:16), the fugitive and the deducter excluded (16b:17-20); THE FEATURE the category of blessing (119:4; 17a:16-17b:1); the debit CLOSED at the giving in the case's own world, never on the tape (the master who gives thirty selas the exam's person; the one who sends him empty the block's)",
  HE_SEV + " (of that with which the LORD your God has blessed you, you shall give him — Deut 15:14)",
  "Deut 15:13-14; Exodus 21:32 (the gored slave's thirty shekels); Numbers 18:16 (the firstborn's five shekels — ordinances.gifts, korach.the_gifts by CALL); Leviticus 27:3 (the valuation's fifty — yovel.valuation by CALL); Onkelos 15:14; the Sifrei on Deuteronomy 119:3-5; Tosefta Kiddushin 1:5; Babylonian Talmud Kiddushin 15a:6-7, 16b:16-20, 17a:5-17b:3",
  CORPUS, EX % ("F4 the_hebrew_slave — the_severance_gift, the_gifts_persons; the case's write at the runner's own scene", "hebrew_slave_law_declared (the case kind release_firstborn_case)")),
 ('serves_for_ever', 'status',
  "the pierced slave serves for ever — the STATUS the exam's case writes on the pierced slave (the case kind release_firstborn_case through F5 the_awl_and_the_double_hire): 'then you shall take an awl and put it through his ear into the door, and HE SHALL BE YOUR SERVANT FOR EVER' (15:17) — 'FOR EVER' THE MASTER'S LIFETIME (the Sifrei 122:8 — I2 named in the Hebrew on the word at 15:17 and Exodus 21:6; Kiddushin 15a:21-22, 21b:4: the master's lifetime, the jubilee's forever); THE JUBILEE FREES EVEN HIM — jubilee_release ON FILE by CALL to yovel ('the timer that overrides even the pierced slave's forever'; Kiddushin 15a:19-20 the two verses both needed); THE PIERCED SERVES NO HEIR (Kiddushin 17b:4-13 — the son stands in his father's place for the designation and the field; Bava Metzia 71a:14); THE MAIDSERVANT NEVER PIERCED (Kiddushin 15a:3, 15a:5, 15a:18 'man' — 122:9's 'likewise' reaches the gift, not the awl: the DISAGREES row against Exodus 21:7 RESOLVED AS DATA; 17b:10-12 R. Padda's two conclusions from 'you shall DO'); THE RITE'S CONDITIONS: two sayings at the term's end (121:1-2; Kiddushin 22a:3-6), the mutual love and the master's house (121:3; 22a:7-8), illness in either bars the rite (121:4; 22a:9 both ill an open dilemma), THE AWL any tool or metal A DISPUTE (122:1 — Kiddushin 21b:5-11: R. Yosei son of R. Yehuda's amplification-restriction against Rabbi's general-particular-general; 'THE awl' the large awl), R. ISHMAEL'S THREE CIRCUMVENTIONS a DATA row (the blood's dust, the divorce's writ, the awl), NO JUDGES, NO DOORPOST, 'INTO THE DOOR' (122:3 — Exodus 21:6 by CALL; 22b:1-3 through the ear until the door, the door upright and attached), THE UPPER RIGHT EAR by the labeled TRANSFER from the leper's (122:5-6 — 'ear'/'ear' with Leviticus 14:14; Kiddushin 15a:1, 21b:7, 21b:12: through the cartilage, a priest-slave not pierced lest he be blemished — Bekhorot 37b:12-14); Onkelos 'a serving servant for ever' (עבד פלח לעלם)",
  HE_EVER + " (and he shall be your servant for ever — Deut 15:17)",
  "Deut 15:16-17; Exodus 21:5-6 (mishpatim by CALL — the term clock, slave_pierced the kind on file; 'to the judges', 'the door or the doorpost'), 21:7 (the DISAGREES row — mishpatim_3.maidservant by CALL); Leviticus 25:10, 25:40-41 (yovel.jubilee, yovel.hebrew_slave by CALL — jubilee_release); Leviticus 14:14 (metzora.eighth by CALL — the TRANSFER 'ear'/'ear'); Leviticus 21:17-23 (priesthood.blemish by CALL — the priest's ear); Onkelos 15:16-17; the Sifrei on Deuteronomy 121:1-122:9; Mishnah Kiddushin 1:2; Tosefta Kiddushin 1:5; Babylonian Talmud Kiddushin 15a:1-22, 17b:4-13, 21b:4-22b:5; Bekhorot 37b:10-14; Bava Metzia 71a:14; Arakhin 33a:2-4",
  CORPUS, EX % ("F5 the_awl_and_the_double_hire — the_two_sayings, the_awl_timing, the_awl_tool, the_three_circumventions, the_judges_and_the_door, the_ear, the_for_ever, the_maidservant_never_pierced; the case's write at the runner's own scene", "hebrew_slave_law_declared (the case kind release_firstborn_case)")),
 ('firstling_sanctification_commanded', 'status',
  "the firstling's sanctification commanded — the STATUS the line firstling_law_declared writes on Israel: 'EVERY FIRSTLING MALE that is born of your herd and of your flock YOU SHALL SANCTIFY TO THE LORD YOUR GOD' (15:19) — its value the_sanctify_for_value A PARAMETER: 'YOU SHALL SANCTIFY' AGAINST LEVITICUS 27:26's 'NO MAN SHALL SANCTIFY IT' UPHELD BY DIVIDING THE SPHERES (the Sifrei 124:4 — Mishnah Arakhin 8:7 inside the spine: you sanctify it for its value, never for the altar; Arakhin 29a:20 the two verses at the answer sheet, Nazir 4b:11 sanctified by word though holy from birth; Temurah's consecrate cell by CALL — its probe list carrying 15:19 as the IMPORT against 27:26; the DISAGREES row RESOLVED AS DATA); CONSECRATED FROM THE WOMB — consecrated_firstborn REUSED by CALL (Exodus 13:2's and Numbers 18:17's status written at birth: ordinances.firstling, korach.the_gifts opens_the_womb; 'males' the detail of Exodus 13:2 — Bekhorot 19a:4; the sex's edge 41b:8, 42a:11); its year and the blemished from 'every' (124:1); THE CAESAREAN OUT (124:2 — Mishnah Bekhorot 2:9: not a firstling; the caesarean by I2 'birth'/'birth' Niddah 40a:14); the consecrated by a refuted a fortiori then the verse (124:3 — I1); 'YOUR' TWO WAYS A DISPUTE (124:5 — the owner's or the priest's: the firstling's flesh the priest's by Numbers 18:18; THE TWO FILES READING THE CLOSING VERSE OPPOSITE WAYS 124:6); THE DOUBT TABLE and THE PERSONS (Mishnah Bekhorot 2:6-8; Tosefta Bekhorot 1:1, 2:1-7 — the gentile's finger); the firstling from outside the Land (Bekhorot 53b; food_tithe by CALL); the firstling sanctified by word the exam's person accepted, the one who sanctifies it for the altar barred",
  HE_SANC + " (the male you shall sanctify to the LORD your God — Deut 15:19)",
  "Deut 15:19, 14:23 (food_tithe.the_second_tithe by CALL), 12:17-18 (place_name by CALL); Exodus 13:2, 13:12, 22:29, 34:19 (ordinances.firstling, erection.repeats by CALL); Numbers 18:15-18 (korach.the_gifts by CALL); Leviticus 27:26 (temurah.consecrate by CALL — 'no man shall sanctify'); Genesis 4:4 (Abel's firstlings — first_offerings_brought on the tape, primeval by CALL); Onkelos 15:19; the Sifrei on Deuteronomy 124:1-6; Mishnah Arakhin 8:7; Mishnah Bekhorot 1:1-2, 2:6-9; Mishnah Temurah 3:5; Tosefta Bekhorot 1:1, 2:1-7, 3:2; Babylonian Talmud Arakhin 29a:20; Nazir 4b:11; Bekhorot 19a:4, 41b:8, 42a:11, 53b:5; Niddah 40a:14; Temurah 21b:9",
  CORPUS, EX % ("F6 the_firstling — the_sanctify_for_value, consecrated_from_the_womb, the_caesarean, the_your_two_ways, the_files_disagree, the_doubt_table", "firstling_law_declared")),
 ('firstling_work_and_shearing_barred', 'block',
  "the firstling's work and shearing barred — the BLOCK the line firstling_law_declared writes on Israel: 'YOU SHALL DO NO WORK WITH THE FIRSTLING OF YOUR OX NOR SHEAR THE FIRSTLING OF YOUR FLOCK' (15:19) — the two bars crossed by four a fortiori arguments and closed by the verse (the Sifrei 124:6); Bekhorot 25a-28b at the docket: PLUCKING IS NOT SHEARING (Rav, 25a:1-16 — the cleaver's clearing by hand, not by a tool that looks like shearing; plucked to show a blemish from the outset), THE SHED HAIR OF THE BLEMISHED FIRSTLING (Mishnah Bekhorot 3:4 at 25a:17-25b:2 — Akavya ben Mahalalel and the Rabbis; Rava's three disputes 26a:6-7; THE RULING AS R. YEHUDA from Eduyot 5:6, 26a:8; the Rabbis' DECREE lest one delay the slaughter to gather wool 25b:5), the ban's definition a DATA row; 'your ox … your flock' the partnership's arm (Bekhorot 9b:13), the neck's hair plucked not shorn (24b:5; Mishnah 3:3), the sanction gated on certainty (41b:2), the ban borrowed by the first shearing and read over both kinds (Chullin 135a:9, 135b:13, 136b:18, 137a:4), the blemished consecrated's lashes (Tosefta Bekhorot 2:3), the herd's tithe 'under the rod' by CALL to temurah.tithe; the one who plucks the firstling's hair by hand accepted, the one who shears it lashed",
  HE_SHEAR + " (you shall do no work with the firstling of your ox nor shear the firstling of your flock — Deut 15:19)",
  "Deut 15:19, 21:3 (the heifer 'not worked' — the twin ahead); Leviticus 27:32 (temurah.tithe by CALL — 'under the rod'); Numbers 18:17 (korach.the_gifts by CALL); Onkelos 15:19; the Sifrei on Deuteronomy 124:6; Mishnah Bekhorot 3:3-4; Mishnah Eduyot 5:6; Tosefta Bekhorot 1:6, 2:3; Babylonian Talmud Bekhorot 9b:13, 24b:5, 25a:1-26b:5, 41b:2; Chullin 135a:9-137a:4; Temurah 11b:15",
  CORPUS, EX % ("F6 the_firstling — the_work_and_the_shearing, the_plucking, the_shed_hair", "firstling_law_declared")),
]
added = 0
for name, op, en, he, ink, corpus, exam in NEW:
    if name in fx: continue
    text = text.rstrip('\n') + '\n' + f"  {name}:\n    en: {q(en)}\n    he: {q(he)}\n    ledger_op: {op}   # THE DEUTERONOMY WALK 13b (2026-09-23): chapter 15's compile — {name}, the name and the value from the docket's rows\n    ink: {q(ink)}\n    corpus: {q(corpus)}\n    exam: {q(exam)}\n"
    added += 1
# ---- THE FOUR REUSED ROWS AMENDED with the chapter's seat (a second entry on israel_people at the chapter's own day — 8b's lesson) ----
def amend(name, field, addition):
    global text
    i = text.index(f'\n  {name}:\n'); j = text.index(f'\n    {field}: ', i); k = text.index('\n', j + 1)
    line = text[j + 1:k]; assert line.endswith('"') and line.count('"') >= 2, (name, field, line[-40:])
    assert 'THE DEUTERONOMY WALK 13b' not in line, (name, field, 'already amended')   # the full marker (11b's lesson 9 — a bare '13b' would match a folio)
    text = text[:k - 1] + addition.replace('"', '\\"') + text[k - 1:]
amend('blessings_for_hearing', 'ink', "; THE DEUTERONOMY WALK 13b (2026-09-23): Deut 15:5 THE REUSE — the chapter's line release_law_declared writes A SECOND ENTRY on israel_people at the counter's day (40, 11, 1): the release's blessing conditional on the hearing — " + HE_BLESS + " (if only you diligently hearken to the voice of the LORD your God — Deut 15:5); 28:1's header fourteen of seventeen in order, 11:13's second paragraph the same form (the Sifrei 114:1-115:2 — the blessing only in the Land, the conquest first; 'hear, you shall hear' the words of the scribes); 8b's lesson: a reused effect is a second entry on the same ledger (CQ6's, DC6's, Q21's and Q30's ONE retyped TWO)")
amend('blessings_for_hearing', 'exam', "; THE DEUTERONOMY WALK 13b (2026-09-23): cold_run_release_firstborn.py (F2 the_needy_and_the_blessing — the_hearkening; the reuse's second entry written on the tape kind release_law_declared)")
amend('cry_heard', 'ink', "; THE DEUTERONOMY WALK 13b (2026-09-23): Deut 15:9 THE REUSE — the chapter's line hand_opening_commanded writes A SECOND ENTRY on israel_people at the counter's day (40, 11, 1): the needy brother's cry against the shut hand — " + HE_CRY + " (and he cry to the LORD against you — Deut 15:9); the Sifrei 117:5 with 279:4 word for word (24:15's hireling seven tokens in order): THE CRY A HASTENER, the sin unconditional; Exodus 22:22's cry the first seat; 8b's lesson: a second entry on the same ledger (no count literal held ONE — the grep decided)")
amend('cry_heard', 'exam', "; THE DEUTERONOMY WALK 13b (2026-09-23): cold_run_release_firstborn.py (F3 the_hand_opened — the_cry_and_the_sin; the reuse's second entry written on the tape kind hand_opening_commanded)")
amend('bears_sin', 'ink', "; THE DEUTERONOMY WALK 13b (2026-09-23): Deut 15:9 THE REUSE — the chapter's line hand_opening_commanded writes AN ENTRY on israel_people at the counter's day (40, 11, 1): 'and it be sin in you' — " + HE_SIN + " (and it be sin in you — Deut 15:9); the book's three (15:9 the needy's cry, 23:22 the vow, 24:15 the hireling's cry — the Sifrei 117:5, 279:4): THE SIN UNCONDITIONAL, whether he cries or not; the divine ledger's status; 8b's lesson: a reused effect's entry on the same ledger (the running world held none before — the count read at the design's probes)")
amend('bears_sin', 'exam', "; THE DEUTERONOMY WALK 13b (2026-09-23): cold_run_release_firstborn.py (F3 the_hand_opened — the_cry_and_the_sin; the entry written on the tape kind hand_opening_commanded)")
amend('holy_things_in_the_gates_barred', 'ink', "; THE DEUTERONOMY WALK 13b (2026-09-23): Deut 15:20 THE REUSE — the chapter's line firstling_law_declared writes A SECOND ENTRY on israel_people at the counter's day (40, 11, 1): the firstling eaten before the LORD at the place, not in the gates — " + HE_GATES + " (before the LORD your God you shall eat it year by year in the place — Deut 15:20); 12:17-18's block at its second seat (the formula's fourth seat in this form; the blemished firstling the exception at 15:22 — 'within your gates you shall eat it', the third seat of 12:15's clause); the Sifrei 125:1; Bekhorot 27b:3-28a:11; 8b's lesson: a second entry on the same ledger (DD2's, DF5's, Q32's and Q39's ONE retyped TWO; the blocks counted 5 -> 6)")
amend('holy_things_in_the_gates_barred', 'exam', "; THE DEUTERONOMY WALK 13b (2026-09-23): cold_run_release_firstborn.py (F6 the_firstling — before_the_lord_at_the_place; the reuse's second entry written on the tape kind firstling_law_declared)")
open(path, 'w', encoding='utf-8').write(text)
fx = yaml.safe_load(open(path, encoding='utf-8'))['effects']
assert all(n in fx for n, *_ in NEW) and fx['debt_release_owed']['ledger_op'] == 'status' and fx['exaction_barred']['ledger_op'] == 'block' and fx['work_of_the_hand_blessed']['ledger_op'] == 'heaven' and fx['severance_gift_owed']['ledger_op'] == 'debit' and fx['serves_for_ever']['ledger_op'] == 'status' and fx['firstling_work_and_shearing_barred']['ledger_op'] == 'block'
assert all('THE DEUTERONOMY WALK 13b' in fx[e]['ink'] and 'cold_run_release_firstborn.py' in fx[e]['exam'] for e in ('blessings_for_hearing', 'cry_heard', 'bears_sin', 'holy_things_in_the_gates_barred')), 'the four reuses amended'
print('effects: %d added (registry %d); blessings_for_hearing, cry_heard, bears_sin, holy_things_in_the_gates_barred amended; the he found in the verses: %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s' % (added, len(fx), HE_REL, HE_EXACT, HE_OPEN, HE_SHUT, HE_BASE, HE_WORK, HE_FURN, HE_EMPTY, HE_SEV, HE_EVER, HE_SANC, HE_SHEAR))
