# THE SIFREI ROWS OUTSIDE THE SPINE CITING CHAPTER 12 (THE DEUTERONOMY WALK sitting 10 — CHAPTER 12, 2026-09-20; the one run): the union of both files'
# citations beyond piskaot 59-81 is seven rows — ALL read WHOLE in both files (ch12_ink.OUTSIDE; one read before at sitting 1 and reread whole here; none
# excluded). The cuts by ch12_ink.SP_; the middah where the row argues by one (checked). Chapter 11's form (ch11_rows_outside.py).
from ch12_ink import *
SO = {}
def orow(p, r, verdict, prose): SO[(p, r)] = (verdict, prose)

orow(2, 2, 'MATERIAL', f'"ELEVEN DAYS" (1:2) — HAD ISRAEL MERITED, IN ELEVEN DAYS THEY WOULD HAVE ENTERED; SINCE THEY CORRUPTED THEIR DEEDS, FORTY DAYS BECAME FORTY YEARS (NUMBERS 14:34). R. JUDAH: IN THREE DAYS — "THE ARK … WENT THREE DAYS TO SEEK OUT A REST FOR THEM" (NUMBERS 10:33), AND REST IS THE LAND OF ISRAEL: "FOR YOU HAVE NOT YET COME TO THE REST AND THE INHERITANCE" (12:9). R. BENAIAH: IN ONE DAY (EXODUS 13:4-5); ABBA YOSE BEN HANAN: AS SOON AS THEIR FEET LEFT THE SEA — "GO UP, POSSESS" (1:21). The row on 1:2 ({SP_(2, 2, "ואין", "מנוחה", "אלא", "ארץ", "ישראל")} "and rest is nothing but the Land of Israel"): 12:9\'s "rest" read as the Land itself — the third reading beside Shiloh and Jerusalem (66:2); the range citation "(שמות יג ד-ה)" ("Exodus 13:4-5") invisible to the regex (chapter 8\'s lesson). Read before at sitting 1, REREAD WHOLE here.')
orow(106, 5, 'MATERIAL', f'OTHERS SAY: MIGHT A FIRSTLING WHOSE YEAR PASSED INTO THE NEXT BE DISQUALIFIED LIKE OTHER DISQUALIFIED HOLY THINGS? "AND YOU SHALL EAT BEFORE THE LORD YOUR GOD" (14:23) — IF TO TEACH THAT THE FIRSTLING IS EATEN WITHIN THE WALL, IT IS SAID (15:20); IF THAT THE SECOND TITHE IS EATEN WITHIN THE WALL, IT IS SAID: "YOU MAY NOT EAT WITHIN YOUR GATES" (12:17); THEN WHY? THE FIRSTLING COMPARED TO THE SECOND TITHE — AS THE TITHE IS EATEN FROM YEAR TO YEAR, SO THE FIRSTLING. The row on 14:23 ({SP_(106, 5, "מקיש", "בכור", "למעשר", "שני")} "it compares the firstling to the second tithe"): 12:17 cited as the seat of the second tithe\'s wall (Tosefta Sanhedrin 3:6 — the English); the juxtaposition named by the row. Fresh.')
orow(138, 1, 'CONTEXT', f'"AND YOU SHALL REJOICE" (16:11) — REJOICING HERE AND AT 27:7: PEACE OFFERINGS. The row on 16:11 ({SP_(138, 1, "נאמרה", "כאן", "שמחה")} "rejoicing is said here"): I2 (checked) — 64:2\'s analogy said at the Feast of Weeks; the English adds "(Dt.12:7)" to the Hebrew\'s 27:7 alone. Fresh.')
orow(145, 3, 'MATERIAL', f'"YOU SHALL NOT PLANT FOR YOURSELF AN ASHERAH" (16:21) — THE TORAH SAID "THEIR ASHERIM YOU SHALL BURN IN FIRE" (12:3): A FORTIORI THAT ONE NOT PLANT; AND WHENCE THAT ONE NOT MAINTAIN IT? "YOU SHALL NOT PLANT FOR YOURSELF" — IN ANY CASE. The row on 16:21 ({SP_(145, 3, "קל", "וחומר", "שלא", "יטע")} "an a fortiori that he not plant"): I1 (checked) from 12:3\'s burning to 16:21\'s planting — the a fortiori shows the plain reading redundant, the verse assigned to maintaining (72:9\'s method). Fresh.')
orow(147, 2, 'MATERIAL', f'MIGHT ONE WHO OFFERS HOLY THINGS OUT OF ORDER — A BURNT OFFERING BEFORE A SIN OFFERING, THE PASSOVER BEFORE THE DAILY, THE ADDITIONAL BEFORE THE DAILY — TRANSGRESS A PROHIBITION? "YOU MAY NOT EAT WITHIN YOUR GATES THE TITHE OF YOUR GRAIN, WINE AND OIL" (12:17), "YOU MAY NOT SLAUGHTER THE PASSOVER IN ONE OF YOUR GATES" (16:5), "YOU SHALL NOT SLAUGHTER AN OX OR SHEEP WITH A BLEMISH" (17:1) — FOR THESE HE TRANSGRESSES, NOT FOR THE ORDER. The row on 17:1 ({SP_(147, 2, "ואין", "מקדים", "קדשים", "זה", "לזה", "עובר", "בלא", "תעשה")} "and one who puts holy things before one another does not transgress a prohibition"): 12:17 the first of three named prohibitions against an unwritten one — the order of offerings (Mishnah Zevachim 10:1-2 — the English) no prohibition. Fresh.')
orow(179, 2, 'MATERIAL', f'"AND YOU SHALL DISPOSSESS THEM AND DWELL IN THEIR CITIES AND HOUSES" (19:1) — MIGHT YOU NOT BE PERMITTED TO ADD TO THE BUILDING? "AND DWELL IN THEIR LAND" (12:29) — WHEREVER YOU WISH TO BUILD, BUILD. The row on 19:1 ({SP_(179, 2, "כל", "מקום", "שאתה", "רוצה", "לבנות", "בנה")} "wherever you wish to build, build"): 80:3 from 19:1\'s side; THE ENGLISH\'S WRONG CHAPTER — "(Dt.13:29)" for 12:29, the Hebrew\'s citation right (asserted). Fresh.')
orow(286, 16, 'MATERIAL', f'R. SHIMON SON OF RABBI: "ONLY BE STEADFAST NOT TO EAT THE BLOOD" (12:23) — IF THE BLOOD, FROM WHICH A MAN\'S SOUL RECOILS, ONE WHO ABSTAINS RECEIVES A GOOD REWARD, THEN ROBBERY AND FORBIDDEN UNIONS, WHICH A MAN\'S SOUL CRAVES AND COVETS — ONE WHO ABSTAINS HOW MUCH MORE MERITS FOR HIMSELF AND HIS GENERATIONS TO THE END OF ALL GENERATIONS. The row on 25:1 ({SP_(286, 16, "גזל", "ועריות", "שנפשו", "של", "אדם", "מתאוה", "להם")} "robbery and forbidden unions, which a man\'s soul craves"): I1 (checked) — Mishnah Makkot 3:15\'s argument (76:2, 76:9) with the reward\'s generations (79:2\'s phrase). Fresh.')

assert sorted(SO) == sorted(OUTSIDE) == sorted(FRESH), sorted(SO)
