import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# DEUTERONOMY CHAPTER 13, THE READING (THE DEUTERONOMY WALK sitting 11, 2026-09-21; the owner: "Go" after the reread that followed 10b's compaction;
# ONE RUN + ITS TAIL under the cost rules A-B-C): THE SECOND MEASUREMENT PASS — every candidate ink fact PRINTED from the Tanakh DB, the store and the
# shelf's bytes, so that ch13_ink.py's asserts are typed FROM THE PRINT. THE KIN FOUND BY COMPUTATION (every verse against the whole Bible by shared tokens,
# the closest re-scored in order) beside THE LAW KIN NAMED (4:2's adding and diminishing, 18:20's false prophet, 17:2-7's idolater and the hand first, 8:2's
# testing, 10:20's four verbs, 7:16's unpitying eye, the stoning at Leviticus 20 and 24, the ban at Leviticus 27 and Joshua 6-8, the fierce anger at Numbers
# 25 and Joshua 7, the oath's formula); the phrase censuses over the whole DB; the parser on the chapter's one number verse (13:13 'in one of your cities');
# Onkelos's renderings' seats over the book; the English's bracketed supplements; the store's gloss families and the written/read pair at 13:16; the prior
# reads on the kin; the register's finder on the chapter. Chapter 12's helpers and register block by asserted substitutions (derive_ch13_measure1.py); the
# sections chapter 13's own. Nothing asserted.
import json, os, re, html, sqlite3, subprocess, unicodedata, sys, io, contextlib
from collections import Counter
ROOT = _ROOT
sys.path.insert(0, f'{ROOT}/World/step9')
def clean(s): return re.sub(r'<[^>]+>', '', html.unescape(s))
def plain(w): return ''.join(c for c in w if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
def pointed(w): return ''.join(c for c in w if c != '/' and not (0x0591 <= ord(c) <= 0x05AF))
def NF(s): return unicodedata.normalize('NFC', s)
db = sqlite3.connect(f'file:{ROOT}/Data/tanakh.sqlite?mode=ro', uri=True)
rows = db.execute("SELECT v.book, v.chapter, v.verse, w.he, w.morph, w.lemma, w.wtype FROM words w JOIN verses v ON w.verse_id=v.id ORDER BY v.id, w.idx").fetchall()
by = {}
for b, c, v, he, m, lem, wt in rows: by.setdefault((b, c, v), []).append((plain(he), m, he, lem, wt))
T = ('Gen', 'Exod', 'Lev', 'Num', 'Deut')
def words(b, c, v): return [x for x, _, _, _, _ in by[(b, c, v)]]
def wm(b, c, v): return [(x, m) for x, m, _, _, _ in by[(b, c, v)]]
def base(l): return (l or '').split('/')[-1].strip()
def hits(sub, books=None, exact=True): return sorted({f'{b} {c}:{v}' for (b, c, v), ws in by.items() if (books is None or b in books) and any((x == sub) if exact else (sub in x) for x, _, _, _, _ in ws)})
def U(*toks, books=None): return sorted({f'{b} {c}:{v}' for (b, c, v), ws in by.items() if books is None or b in books for x, _, _, _, _ in ws if x in toks})
def phrase(seq, books=None):
    out = []
    for (b, c, v), ws in by.items():
        if books is not None and b not in books: continue
        w = [x for x, _, _, _, _ in ws]
        if any(w[i:i + len(seq)] == list(seq) for i in range(len(w) - len(seq) + 1)): out.append(f'{b} {c}:{v}')
    return sorted(out)
def P(*seq, books=None): return phrase(list(seq), books)
def LEMT(lem, books=None): return [(f'{b} {c}:{v}', x, m) for (b, c, v), ws in by.items() if (books is None or b in books) for x, m, _, l, _ in ws if base(l) == lem]
def LEMV(lem, books=None): return sorted({s for s, _, _ in LEMT(lem, books)})
def lemma_of(b, c, v, tok): return [base(l) for x, _, _, l, _ in by[(b, c, v)] if x == tok]
def PT(b, c, v, tok): return [NF(pointed(r)) for x, _, r, _, _ in by[(b, c, v)] if x == tok]
def FAM(sub, books=None): return sorted({f'{b} {c}:{v}' for (b, c, v), ws in by.items() if (books is None or b in books) for x, _, _, _, _ in ws if sub in x})
def SEAT(s): b, cv = s.split(); c, v = map(int, cv.split(':')); return (b, c, v)
def DIFF(a, b_):
    A, B = words(*a), words(*b_)
    import difflib
    sm = difflib.SequenceMatcher(a=A, b=B)
    out = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == 'equal': out.append('=' + ' '.join(A[i1:i2]))
        else: out.append(f'[{tag}: {" ".join(A[i1:i2])!r} -> {" ".join(B[j1:j2])!r}]')
    return f'{a[0]} {a[1]}:{a[2]} ({len(A)}) vs {b_[0]} {b_[1]}:{b_[2]} ({len(B)}): ' + ' '.join(out)
onk = json.load(open(f'{ROOT}/Data/sefaria_export/Onkelos_Deuteronomy/en.json', encoding='utf-8'))['text']
onk_he = json.load(open(f'{ROOT}/Data/sefaria_export/Onkelos_Deuteronomy/he.json', encoding='utf-8'))['text']
def arm(c, v): return [plain(x).strip('.:') for x in clean(onk_he[c - 1][v - 1]).rstrip(':').split()]
def onk_seats(sub): return [(c + 1, v + 1) for c in range(34) for v in range(len(onk_he[c])) if sub in ' '.join(arm(c + 1, v + 1))]
def onk_tok(tok): return [(c + 1, v + 1) for c in range(34) for v in range(len(onk_he[c])) if tok in arm(c + 1, v + 1)]
CH = 13
VC = dict(db.execute("SELECT chapter, COUNT(*) FROM verses WHERE book='Deut' GROUP BY chapter").fetchall())
NV = VC[CH]
EXP2DB = {e: [e] for e in range(1, NV + 1)}   # typed from ch13_dump0's A0 print: 19 = 19, the identity, cost 10 (chapter 5 the book's one split)
DB2EXP = {d: e for e, ds in EXP2DB.items() for d in ds}
def L(label, val): print(f'  {label}: {val}')
V13 = lambda v: words('Deut', 13, v)

print('==== A. THE KIN FOUND BY COMPUTATION — every verse of the chapter against every verse of the Bible: the shared DISTINCT tokens outside a stop list of particles and the Name (the count), the top eight by that count in the Bible\'s order, the three closest re-scored IN ORDER by SequenceMatcher; then THE LAW KIN NAMED AND DIFFED IN FULL (the closest two per verse)')
import difflib
STOP = set('את ואת אשר כל וכל על ועל אל ואל לא ולא כי אם יהוה אלהיך אלהיכם לך לכם בו שם שמה גם מן ממך עד הוא היא אתם אתה אנכי אני לו לה בכל כאשר כן הימים היום אלה האלה בארץ הארץ אשר ואם או פן ופן'.split())
ORD = {k: i for i, k in enumerate(by)}
TOK = {k: set(words(*k)) - STOP for k in by}
def SH(a, b_): return sum(s for _, _, s in difflib.SequenceMatcher(a=words(*a), b=words(*b_)).get_matching_blocks())
D13 = lambda v: ('Deut', CH, v)
KINC = {}
for v in range(1, NV + 1):
    me = D13(v); t = TOK[me]
    sc = sorted(((len(t & TOK[k]), k) for k in by if k != me and len(t & TOK[k]) >= 2), key=lambda x: (-x[0], ORD[x[1]]))[:8]
    KINC[v] = [(f'{k[0]} {k[1]}:{k[2]}', n, SH(me, k) if i < 3 else None) for i, (n, k) in enumerate(sc)]
    L(f'{CH}:{v} ({len(t)} distinct non-stop tokens of {len(words(*me))})', KINC[v])
LAWKIN = [((13, 1), [('Deut', 4, 2), ('Deut', 8, 1), ('Deut', 5, 1), ('Deut', 6, 1), ('Deut', 11, 32), ('Deut', 12, 28), ('Deut', 28, 14), ('Josh', 1, 7), ('Prov', 30, 6), ('Eccl', 3, 14)]),
 ((13, 2), [('Deut', 18, 15), ('Deut', 18, 20), ('Deut', 18, 22), ('Num', 12, 6), ('Jer', 23, 25), ('Jer', 23, 32), ('Jer', 27, 9), ('Jer', 29, 8), ('Gen', 37, 19), ('Zech', 10, 2), ('Deut', 34, 11), ('Exod', 7, 3)]),
 ((13, 3), [('Deut', 11, 28), ('Deut', 13, 7), ('Deut', 13, 14), ('Deut', 28, 64), ('Deut', 29, 25), ('Deut', 6, 14), ('Deut', 8, 19), ('Exod', 32, 4), ('Exod', 32, 8), ('Judg', 2, 12), ('Judg', 2, 19), ('Jer', 7, 9), ('Jer', 25, 6), ('1Kgs', 11, 10)]),
 ((13, 4), [('Deut', 8, 2), ('Deut', 8, 16), ('Gen', 22, 1), ('Exod', 15, 25), ('Exod', 16, 4), ('Exod', 20, 17), ('Deut', 6, 5), ('Deut', 11, 13), ('Deut', 10, 12), ('Deut', 30, 6), ('Judg', 2, 22), ('Judg', 3, 4), ('2Chr', 32, 31)]),
 ((13, 5), [('Deut', 10, 20), ('Deut', 6, 13), ('Deut', 11, 22), ('Deut', 4, 4), ('Deut', 30, 20), ('Deut', 10, 12), ('Josh', 22, 5), ('Josh', 23, 8), ('2Kgs', 23, 3), ('2Kgs', 18, 6), ('Deut', 5, 33), ('Deut', 8, 6)]),
 ((13, 6), [('Deut', 18, 20), ('Deut', 19, 16), ('Deut', 17, 7), ('Deut', 17, 12), ('Deut', 19, 19), ('Deut', 21, 21), ('Deut', 22, 21), ('Deut', 22, 22), ('Deut', 22, 24), ('Deut', 24, 7), ('Deut', 7, 8), ('Deut', 9, 26), ('Deut', 15, 15), ('Deut', 21, 8), ('Deut', 24, 18), ('Deut', 5, 6), ('Jer', 28, 16), ('Isa', 1, 5), ('Deut', 4, 19), ('Deut', 30, 17), ('Deut', 9, 12), ('Deut', 9, 16), ('Deut', 11, 28), ('Deut', 31, 29), ('Judg', 2, 17), ('Exod', 32, 8)]),
 ((13, 7), [('Deut', 28, 54), ('Deut', 28, 56), ('Deut', 27, 15), ('Deut', 27, 24), ('Deut', 28, 57), ('Deut', 28, 36), ('Deut', 28, 64), ('Gen', 27, 29), ('Gen', 43, 29), ('Judg', 8, 19), ('Ps', 50, 20), ('1Sam', 18, 1), ('1Sam', 18, 3), ('1Sam', 20, 17), ('1Kgs', 21, 25), ('1Sam', 26, 19), ('Deut', 13, 3), ('Deut', 13, 14)]),
 ((13, 8), [('Deut', 6, 14), ('Deut', 28, 64), ('Deut', 30, 4), ('Deut', 4, 32), ('Jer', 12, 12), ('Jer', 25, 33), ('Judg', 2, 12), ('Ps', 19, 7), ('Isa', 5, 26), ('Isa', 42, 10)]),
 ((13, 9), [('Deut', 7, 16), ('Deut', 19, 13), ('Deut', 19, 21), ('Deut', 25, 12), ('Deut', 7, 2), ('Lev', 19, 16), ('Lev', 19, 18), ('Exod', 23, 5), ('Deut', 2, 30), ('Deut', 10, 10), ('Deut', 23, 6), ('Deut', 25, 7), ('Deut', 29, 19), ('1Sam', 15, 3), ('1Sam', 15, 9), ('Exod', 2, 6), ('Ezek', 5, 11), ('Ezek', 7, 4), ('Ezek', 9, 5), ('Ezek', 9, 10)]),
 ((13, 10), [('Deut', 17, 7), ('Deut', 17, 12), ('Deut', 21, 21), ('Deut', 22, 21), ('Deut', 22, 24), ('Lev', 20, 2), ('Lev', 24, 14), ('Lev', 24, 16), ('Lev', 24, 23), ('Num', 15, 35), ('Num', 15, 36), ('Deut', 13, 11), ('Judg', 20, 13), ('1Kgs', 21, 10), ('1Kgs', 21, 13), ('Exod', 21, 12), ('Exod', 21, 15), ('Exod', 21, 16), ('Exod', 21, 17), ('Exod', 22, 18), ('Exod', 22, 19)]),
 ((13, 11), [('Deut', 17, 5), ('Deut', 21, 21), ('Deut', 22, 21), ('Deut', 22, 24), ('Lev', 20, 2), ('Lev', 20, 27), ('Lev', 24, 14), ('Lev', 24, 16), ('Lev', 24, 23), ('Num', 15, 35), ('Num', 15, 36), ('Josh', 7, 25), ('1Kgs', 21, 13), ('Deut', 5, 6), ('Deut', 6, 12), ('Deut', 8, 14), ('Deut', 13, 6), ('Exod', 13, 3), ('Exod', 13, 14), ('Exod', 20, 2), ('Judg', 6, 8), ('Jer', 34, 13), ('Mic', 6, 4), ('Deut', 4, 19), ('Deut', 30, 17)]),
 ((13, 12), [('Deut', 17, 13), ('Deut', 19, 20), ('Deut', 21, 21), ('Deut', 13, 1), ('Deut', 4, 2), ('Deut', 5, 22), ('Deut', 5, 25), ('Deut', 19, 9), ('Deut', 20, 8), ('Deut', 3, 26), ('Deut', 31, 12), ('Deut', 31, 13), ('Josh', 7, 12), ('1Sam', 12, 24), ('Neh', 9, 10)]),
 ((13, 13), [('Deut', 17, 2), ('Deut', 19, 1), ('Deut', 21, 1), ('Deut', 16, 5), ('Deut', 23, 17), ('Deut', 12, 10), ('Deut', 12, 14), ('Deut', 12, 15), ('Deut', 12, 21), ('Deut', 15, 7), ('Deut', 17, 8), ('Deut', 24, 14), ('Deut', 26, 1), ('Gen', 11, 31), ('Gen', 36, 7), ('Josh', 20, 4), ('Judg', 20, 4)]),
 ((13, 14), [('Deut', 15, 9), ('Judg', 19, 22), ('Judg', 20, 13), ('1Sam', 1, 16), ('1Sam', 2, 12), ('1Sam', 10, 27), ('1Sam', 25, 17), ('1Sam', 25, 25), ('1Sam', 30, 22), ('2Sam', 16, 7), ('2Sam', 20, 1), ('2Sam', 23, 6), ('1Kgs', 21, 10), ('1Kgs', 21, 13), ('Nah', 1, 11), ('Nah', 2, 1), ('Prov', 6, 12), ('Prov', 16, 27), ('Prov', 19, 28), ('Job', 34, 18), ('2Chr', 13, 7), ('Deut', 13, 3), ('Deut', 13, 7), ('Deut', 4, 19), ('Deut', 30, 17), ('2Kgs', 17, 21), ('2Chr', 21, 11), ('Prov', 7, 21), ('Deut', 22, 1)]),
 ((13, 15), [('Deut', 17, 4), ('Deut', 19, 18), ('Deut', 9, 21), ('Deut', 27, 8), ('Deut', 12, 30), ('Deut', 12, 31), ('Deut', 17, 1), ('Deut', 18, 12), ('Deut', 22, 21), ('Deut', 24, 4), ('Judg', 20, 6), ('Judg', 20, 10), ('Judg', 19, 30), ('Josh', 22, 16), ('Josh', 22, 20), ('Josh', 7, 15), ('Gen', 34, 7), ('Lev', 20, 13), ('Ezek', 16, 50), ('Ezek', 18, 12), ('Ezek', 22, 11), ('Mal', 2, 11), ('Jer', 44, 4), ('Judg', 6, 29)]),
 ((13, 16), [('Deut', 20, 13), ('Deut', 20, 16), ('Deut', 20, 17), ('Deut', 7, 2), ('Deut', 2, 34), ('Deut', 3, 6), ('Josh', 6, 21), ('Josh', 8, 24), ('Josh', 8, 26), ('Josh', 10, 28), ('Josh', 10, 30), ('Josh', 10, 32), ('Josh', 10, 35), ('Josh', 10, 37), ('Josh', 10, 39), ('Josh', 11, 11), ('Josh', 11, 12), ('Josh', 11, 14), ('Judg', 1, 8), ('Judg', 1, 25), ('Judg', 18, 27), ('Judg', 20, 37), ('Judg', 20, 48), ('Judg', 21, 10), ('1Sam', 15, 3), ('1Sam', 15, 8), ('1Sam', 22, 19), ('Num', 21, 2), ('Num', 21, 3), ('Lev', 27, 28), ('Lev', 27, 29), ('Exod', 22, 19), ('Deut', 13, 18), ('Deut', 13, 17), ('Josh', 7, 1), ('Josh', 7, 11), ('Josh', 7, 12), ('Josh', 7, 13), ('Josh', 7, 15), ('Josh', 22, 20)]),
 ((13, 17), [('Josh', 8, 28), ('Josh', 6, 24), ('Josh', 6, 26), ('Josh', 8, 19), ('Josh', 8, 20), ('Josh', 8, 21), ('Josh', 11, 11), ('Josh', 11, 13), ('Judg', 20, 40), ('Judg', 18, 27), ('1Kgs', 16, 34), ('Jer', 49, 2), ('Jer', 30, 18), ('Lev', 6, 15), ('Lev', 6, 16), ('Deut', 33, 10), ('1Sam', 7, 9), ('Ps', 51, 21), ('Isa', 25, 2), ('Isa', 17, 1), ('Ezek', 26, 14), ('Num', 31, 10), ('Num', 31, 11), ('Num', 31, 12), ('Deut', 20, 14), ('Deut', 2, 35), ('Deut', 3, 7), ('Josh', 8, 2), ('Josh', 8, 27), ('Josh', 11, 14), ('Judg', 5, 30), ('Isa', 10, 6), ('Gen', 49, 27), ('Ezra', 10, 9), ('Neh', 8, 1), ('Neh', 8, 3), ('Neh', 8, 16), ('2Chr', 29, 4), ('2Chr', 32, 6), ('Judg', 19, 15), ('Judg', 19, 17), ('Judg', 19, 20)]),
 ((13, 18), [('Josh', 7, 1), ('Josh', 7, 11), ('Josh', 7, 12), ('Josh', 7, 13), ('Josh', 7, 15), ('Josh', 7, 26), ('Josh', 22, 20), ('Josh', 6, 18), ('1Sam', 15, 21), ('1Chr', 2, 7), ('Num', 25, 4), ('Exod', 32, 12), ('2Chr', 29, 10), ('2Chr', 30, 8), ('Jon', 3, 9), ('Num', 32, 14), ('Deut', 29, 23), ('Deut', 29, 26), ('Gen', 43, 14), ('1Kgs', 8, 50), ('Ps', 106, 46), ('Deut', 30, 3), ('Deut', 7, 12), ('Deut', 8, 18), ('Deut', 9, 5), ('Deut', 11, 9), ('Deut', 11, 21), ('Deut', 19, 8), ('Deut', 26, 3), ('Deut', 26, 15), ('Deut', 27, 3), ('Deut', 28, 11), ('Deut', 29, 12), ('Deut', 30, 20), ('Deut', 31, 20), ('Deut', 1, 8), ('Deut', 6, 10), ('Deut', 6, 3), ('Deut', 1, 11), ('Deut', 7, 13), ('Deut', 30, 5), ('Deut', 30, 16), ('Deut', 8, 1), ('Gen', 22, 17), ('Gen', 26, 4), ('Gen', 26, 24), ('Deut', 13, 5), ('Deut', 4, 4), ('Deut', 10, 20), ('Deut', 11, 22), ('Deut', 30, 20)]),
 ((13, 19), [('Deut', 15, 5), ('Deut', 28, 1), ('Deut', 28, 2), ('Deut', 28, 15), ('Deut', 30, 10), ('Deut', 6, 18), ('Deut', 12, 25), ('Deut', 12, 28), ('Deut', 21, 9), ('Exod', 15, 26), ('1Kgs', 11, 38), ('Deut', 8, 20), ('Deut', 27, 10), ('Deut', 30, 8), ('Deut', 4, 40), ('Deut', 8, 1), ('Deut', 11, 8), ('Deut', 11, 22), ('Deut', 15, 5), ('Deut', 19, 9), ('Deut', 27, 1), ('Deut', 28, 13), ('Deut', 30, 2), ('Deut', 30, 16)]),
]
print('  --- THE LAW KIN (named; scored by SequenceMatcher in order; the two closest diffed in full; a name absent from the DB printed as MISSING)')
for (c, v), kin in LAWKIN:
    kin = [k for k in dict.fromkeys(kin)]
    missing = [k for k in kin if k not in by]
    scored = sorted(((SH(('Deut', c, v), k), k) for k in kin if k in by), key=lambda t: -t[0])
    L(f'{c}:{v} law kin', [(f'{k[0]} {k[1]}:{k[2]}', s) for s, k in scored] + (['MISSING ' + str(m) for m in missing]))
    for s, k in scored[:2]: print('     ' + DIFF(('Deut', c, v), k))
print('==== B. THE PHRASE CENSUSES over the whole DB (Torah where marked; the book where marked)')
DT = ('Deut',)
L('"all the word that I command you" (את כל הדבר אשר אנכי מצוה אתכם) / "all the commandment that I command you" (כל המצוה אשר אנכי מצוך) seats in the book / "you shall keep to do" plural without the nun (תשמרו לעשות) seats / 4:2 and 8:1 tokens', (P('את', 'כל', 'הדבר', 'אשר', 'אנכי', 'מצוה'), P('כל', 'המצוה', 'אשר', 'אנכי', 'מצוך', books=DT), P('תשמרו', 'לעשות'), words('Deut', 4, 2), words('Deut', 8, 1)))
L('"you shall not add to it nor take from it" (לא תסף עליו ולא תגרע ממנו) / 4:2\'s plural (לא תספו … ולא תגרעו) / "add" יסף hiphil second person seats (3254) in the book / "take away" גרע (1639) every seat / Proverbs 30:6 and Ecclesiastes 3:14 tokens', (P('לא', 'תסף', 'עליו', 'ולא', 'תגרע', 'ממנו'), P('לא', 'תספו'), P('ולא', 'תגרעו'), [(s, x, m) for s, x, m in LEMT('3254', books=DT)], [(s, x, m) for s, x, m in LEMT('1639')], words('Prov', 30, 6), words('Eccl', 3, 14)))
L('THE ROOT OF ADDING TWICE IN THE CHAPTER — יסף at 13:1 (add to the word) and 13:12 (do again the evil): every 3254 token in the chapter / "they shall not do again" (ולא יוספו לעשות) every seat', ([(s, x, m) for s, x, m in LEMT('3254', books=DT) if s.startswith('Deut 13:')], P('ולא', 'יוספו', 'לעשות')))
L('"if there arises among you a prophet" (כי יקום בקרבך נביא) / "a prophet from among you" (נביא מקרבך) / "a prophet or a dreamer of a dream" (נביא או חלם חלום) / "a dreamer of a dream" (חלם חלום) every seat / "dreams" חלום the noun (2472) seats in the book / the verb 2492 b seats', (P('כי', 'יקום', 'בקרבך', 'נביא'), P('נביא', 'מקרבך'), P('נביא', 'או', 'חלם', 'חלום'), P('חלם', 'חלום'), U('חלום', 'החלום', 'חלם', 'חולם', 'חלמות', 'החלמות', 'חלמת', books=DT), [(s, x, m) for s, x, m in LEMT('2492 b')]))
L('"a sign or a wonder" (אות או מופת) / "sign and wonder" pairs (אות ומופת / אתות ומפתים / אותות ומופתים / האתות והמפתים) every seat / "the sign and the wonder" (האות והמופת) / "the sign … comes to pass" (ובא האות) / 18:22\'s "the word comes not to pass" tokens', (P('אות', 'או', 'מופת'), U('מופת', 'ומופת', 'מופתים', 'ומופתים', 'מפתים', 'ומפתים', 'המופת', 'והמופת', 'המפתים', 'והמפתים', 'ומפתיו', 'ומופתיו', 'מפתי', 'למופת', 'מופתי', 'ומפתי', 'מופתו'), P('האות', 'והמופת'), P('ובא', 'האות'), words('Deut', 18, 22)))
L('"LET US GO AFTER OTHER GODS" (נלכה אחרי אלהים אחרים) / "let us go and serve other gods" (נלכה ונעבדה אלהים אחרים) every seat / "let us go" נלכה (the cohortative) seats in the Torah / "other gods" (אלהים אחרים) count in the chapter and in the book and in the Bible / "which you have not known" (אשר לא ידעת / ידעתם) with "gods" every seat', (P('נלכה', 'אחרי', 'אלהים', 'אחרים'), P('נלכה', 'ונעבדה', 'אלהים', 'אחרים'), U('נלכה', books=T), len([s for s in P('אלהים', 'אחרים') if s.startswith('Deut 13:')]), len(P('אלהים', 'אחרים', books=DT)), len(P('אלהים', 'אחרים')), P('אלהים', 'אחרים', 'אשר', 'לא', 'ידעת'), P('אלהים', 'אחרים', 'אשר', 'לא', 'ידעתם'), P('אשר', 'לא', 'ידעת', 'אתה', 'ואבתיך')))
L('"and let us serve them" (ונעבדם) / "you shall not hearken to the words of that prophet" (לא תשמע אל דברי הנביא ההוא) / "the dreamer of that dream" (חלם החלום ההוא) / "that prophet" (הנביא ההוא) seats', (U('ונעבדם'), P('לא', 'תשמע', 'אל', 'דברי', 'הנביא', 'ההוא'), P('חלם', 'החלום', 'ההוא'), P('הנביא', 'ההוא')))
L('"FOR THE LORD YOUR GOD IS TESTING YOU" (כי מנסה יהוה אלהיכם אתכם) / נסה piel (5254) with God the subject — every seat in the Bible (the tokens and their verses) / "to know whether" (לדעת הישכם / לדעת את אשר) seats / "whether you are" הישכם every seat', (P('כי', 'מנסה', 'יהוה', 'אלהיכם', 'אתכם'), [(s, x, m) for s, x, m in LEMT('5254')], P('לדעת', 'הישכם'), U('הישכם', 'הישך', 'היש')))
L('"love the LORD your God with all your heart and with all your soul" plural (בכל לבבכם ובכל נפשכם) / singular (בכל לבבך ובכל נפשך) every seat / "love" the participle plural אהבים with the Name (אהבים את יהוה) seats / 6:5 and 11:13 tokens', (P('בכל', 'לבבכם', 'ובכל', 'נפשכם'), P('בכל', 'לבבך', 'ובכל', 'נפשך'), P('אהבים', 'את', 'יהוה'), words('Deut', 6, 5), words('Deut', 11, 13)))
L('THE SIX VERBS OF 13:5 — "after the LORD your God you shall walk" (אחרי יהוה אלהיכם תלכו) / "walk after the LORD" forms (אחרי יהוה … תלכו / הלך) / "Him you shall fear" (ואתו תיראו) / "His commandments keep" (ואת מצותיו תשמרו) / "His voice obey" (ובקלו תשמעו) / "Him serve" (ואתו תעבדו) / "to Him cleave" (ובו תדבקון) — every seat of each / 10:20 and 6:13 and 11:22 tokens', (P('אחרי', 'יהוה', 'אלהיכם', 'תלכו'), P('ואתו', 'תיראו'), P('ואת', 'מצותיו', 'תשמרו'), P('ובקלו', 'תשמעו'), P('ואתו', 'תעבדו'), U('תדבקון', 'תדבק', 'תדבקו'), words('Deut', 10, 20), words('Deut', 6, 13), words('Deut', 11, 22)))
L('"CLEAVE" דבק (1692) — every seat in the book (the chapter\'s two: 13:5 to Him, 13:18 the devoted thing to your hand) / "nothing shall cleave to your hand of the devoted thing" (ולא ידבק בידך מאומה מן החרם) / Joshua 6:18 and 7:1 tokens', ([(s, x, m) for s, x, m in LEMT('1692', books=DT)], P('ולא', 'ידבק', 'בידך', 'מאומה', 'מן', 'החרם'), words('Josh', 6, 18), words('Josh', 7, 1)))
L('"shall be put to death" (יומת) the hophal — the chapter\'s seats and the book\'s count / "for he has spoken rebellion against the LORD" (כי דבר סרה על יהוה) / "rebellion" סרה (5627) every seat / 19:16\'s "to testify against him rebellion" (לענות בו סרה)', ([v for v in range(1, NV + 1) if 'יומת' in V13(v)], len(U('יומת', books=DT)), P('כי', 'דבר', 'סרה', 'על', 'יהוה'), [(s, x) for s, x, _ in LEMT('5627')], P('לענות', 'בו', 'סרה')))
L('THE EXODUS FORMULA WITH REDEEMING — "who brought you out of the land of Egypt and redeemed you from the house of bondage" (המוציא אתכם מארץ מצרים והפדך מבית עבדים) / "redeemed you from the house of bondage" (והפדך מבית עבדים / פדך מבית עבדים) every seat / פדה (6299) seats in the book / "who brought you out of the land of Egypt, out of the house of bondage" singular (המוציאך מארץ מצרים מבית עבדים) every seat — 5:6\'s preamble / "from the house of bondage" (מבית עבדים) count in the Bible', (P('המוציא', 'אתכם', 'מארץ', 'מצרים', 'והפדך', 'מבית', 'עבדים'), P('מבית', 'עבדים'), U('והפדך', 'פדך', 'ופדך'), [(s, x, m) for s, x, m in LEMT('6299', books=DT)], P('המוציאך', 'מארץ', 'מצרים', 'מבית', 'עבדים'), len(P('מבית', 'עבדים'))))
L('"TO THRUST YOU FROM THE WAY" — נדח hiphil (5080) every seat in the book (the chapter\'s three: 13:6, 11, 14) and the whole Bible\'s count / "to thrust you from the way which the LORD your God commanded you to walk in" (להדיחך מן הדרך אשר צוך יהוה אלהיך ללכת בה) / "the way which the LORD your God commanded you" (הדרך אשר צוך / צוה יהוה אלהיך) seats / "to thrust you from the LORD" (להדיחך מעל יהוה)', ([(s, x, m) for s, x, m in LEMT('5080', books=DT)], len(LEMT('5080')), P('להדיחך', 'מן', 'הדרך'), P('הדרך', 'אשר', 'צוך', 'יהוה', 'אלהיך'), P('הדרך', 'אשר', 'צוה', 'יהוה', 'אלהיכם'), P('להדיחך', 'מעל', 'יהוה')))
L('"AND YOU SHALL PURGE THE EVIL FROM YOUR MIDST" (ובערת הרע מקרבך) — every seat in the Bible IN ORDER (13:6 the first?) / "purge the evil" any suffix (ובערת הרע / ובערתם הרע / ובערת … מקרבך / מישראל) / בער piel (1197 a) seats in the book', (P('ובערת', 'הרע', 'מקרבך'), P('ובערת', 'הרע'), P('ובערתם', 'הרע'), U('ובערת', 'ובערתם', 'תבער', 'תבערו', books=DT), [(s, x, m) for s, x, m in LEMT('1197 a', books=DT)]))
L('"IF YOUR BROTHER, THE SON OF YOUR MOTHER, ENTICES YOU" (כי יסיתך אחיך בן אמך) / סות hiphil (5496) every seat in the Bible (13:7 the Torah\'s one?) / "your brother the son of your mother" (אחיך בן אמך) every seat / "the wife of your bosom" (אשת חיקך) and "the bosom" חיק with wife (חיקך / חיקו אשת) seats / "your friend who is as your own soul" (רעך אשר כנפשך) / "as your own soul" (כנפשך / כנפשו) seats', (P('כי', 'יסיתך', 'אחיך', 'בן', 'אמך'), [(s, x, m) for s, x, m in LEMT('5496')], P('אחיך', 'בן', 'אמך'), P('אשת', 'חיקך'), P('חיק', 'אשת'), P('אשת', 'חיקו'), P('רעך', 'אשר', 'כנפשך'), U('כנפשך', 'כנפשו')))
L('"in secret" (בסתר) seats in the book / "you and your fathers" (אתה ואבתיך) every seat / "from the gods of the peoples round about you" (מאלהי העמים אשר סביבתיכם) / 6:14\'s form (מאלהי העמים אשר סביבותיכם) — the two spellings / "near to you or far from you" (הקרבים אליך או הרחקים ממך) / "from one end of the earth to the other" (מקצה הארץ ועד קצה הארץ) every seat', (U('בסתר', books=DT), P('אתה', 'ואבתיך'), P('מאלהי', 'העמים', 'אשר', 'סביבתיכם'), P('מאלהי', 'העמים', 'אשר', 'סביבותיכם'), words('Deut', 6, 14), P('הקרבים', 'אליך', 'או', 'הרחקים', 'ממך'), P('מקצה', 'הארץ', 'ועד', 'קצה', 'הארץ')))
L('THE FIVE PROHIBITIONS OF 13:9 — "you shall not consent to him" (לא תאבה לו) / אבה (14) seats in the book / "nor hearken to him" (ולא תשמע אליו) / "NOR SHALL YOUR EYE PITY HIM" (ולא תחוס עינך עליו) — "your eye shall not pity" (לא תחוס עינך) every seat in the Bible / "nor spare" (ולא תחמל) — חמל (2550) seats in the Torah / "nor conceal him" (ולא תכסה עליו) — "cover upon" (כסה על) seats', (P('לא', 'תאבה', 'לו'), [(s, x, m) for s, x, m in LEMT('14', books=DT)], P('ולא', 'תשמע', 'אליו'), P('לא', 'תחוס', 'עינך'), P('ולא', 'תחוס', 'עינך'), [(s, x, m) for s, x, m in LEMT('2550', books=T)], P('ולא', 'תכסה', 'עליו'), P('תכסה', 'עליו')))
L('"KILL, YOU SHALL KILL HIM" (הרג תהרגנו) — the infinitive absolute / הרג with the infinitive absolute forms (הרג תהרג / הרג יהרג) seats / "YOUR HAND SHALL BE FIRST UPON HIM TO PUT HIM TO DEATH, AND THE HAND OF ALL THE PEOPLE AFTERWARD" (ידך תהיה בו בראשונה להמיתו ויד כל העם באחרנה) / 17:7\'s form (יד העדים תהיה בו בראשנה להמיתו ויד כל העם באחרנה) — the two verses\' tokens / "the hand of all the people" (ויד כל העם) every seat / "at first" בראשונה and "afterward" באחרנה seats in the Torah', (P('הרג', 'תהרגנו'), P('הרג', 'תהרג'), P('הרג', 'יהרג'), P('ידך', 'תהיה', 'בו', 'בראשונה'), P('תהיה', 'בו', 'בראשנה', 'להמיתו'), words('Deut', 17, 7), P('ויד', 'כל', 'העם'), U('בראשונה', 'בראשנה', books=T), U('באחרנה', 'באחרונה', books=T)))
L('"AND YOU SHALL STONE HIM WITH STONES THAT HE DIE" (וסקלתו באבנים ומת) every seat / "stone with stones" forms (וסקלתו באבנים / וסקלתם באבנים / באבנים ומת / ירגמו … באבנים) — every seat in the Bible / סקל (5619) seats in the Torah / רגם (7275) seats in the Torah / "for he sought to thrust you" (כי בקש להדיחך)', (P('וסקלתו', 'באבנים', 'ומת'), P('וסקלתם', 'באבנים'), P('באבנים', 'ומת'), P('באבנים', 'ומתו'), [(s, x, m) for s, x, m in LEMT('5619', books=T)], [(s, x, m) for s, x, m in LEMT('7275', books=T)], P('כי', 'בקש', 'להדיחך')))
L('"AND ALL ISRAEL SHALL HEAR AND FEAR" (וכל ישראל ישמעו ויראון) — every seat / "shall hear and fear" forms (ישמעו ויראו / ישמעו ויראון) every seat / "and shall not do again" (ולא יוספו לעשות / ולא יספו לעשות) every seat / "such an evil thing" (כדבר הרע הזה) every seat / "Israel" (3478) tokens in the chapter', (P('וכל', 'ישראל', 'ישמעו', 'ויראון'), P('ישמעו', 'ויראו'), P('ישמעו', 'ויראון'), P('ולא', 'יוספו', 'לעשות'), P('ולא', 'יספו', 'לעשות'), P('כדבר', 'הרע', 'הזה'), [(s, x) for s, x, _ in LEMT('3478', books=DT) if s.startswith('Deut 13:')]))
L('"IF YOU HEAR IN ONE OF YOUR CITIES" (כי תשמע באחת עריך) — THE NUMBER VERSE / "in one of your cities" (באחת עריך) every seat / "in one of your gates" (באחד שעריך) every seat / "which the LORD your God gives you to dwell there" (אשר יהוה אלהיך נתן לך לשבת שם) / "to dwell there" (לשבת שם) seats in the Torah / "saying" (לאמר) seats in the chapter and the count in the book', (P('כי', 'תשמע', 'באחת', 'עריך'), P('באחת', 'עריך'), P('באחד', 'שעריך'), P('אשר', 'יהוה', 'אלהיך', 'נתן', 'לך', 'לשבת', 'שם'), P('לשבת', 'שם', books=T), [v for v in range(1, NV + 1) if 'לאמר' in V13(v)], len(U('לאמר', books=DT))))
L('"MEN, SONS OF BELIAL, HAVE GONE OUT FROM YOUR MIDST" (יצאו אנשים בני בליעל מקרבך) / "sons of Belial" (בני בליעל) every seat / בליעל (1100) every seat in the Bible (the Torah\'s two: 13:14, 15:9) / "and have drawn away the inhabitants of their city" (וידיחו את ישבי עירם) — THE ONE NARRATIVE VERB / "the inhabitants of their city" (ישבי עירם) / "the inhabitants of that city" (ישבי העיר ההוא)', (P('יצאו', 'אנשים', 'בני', 'בליעל'), P('בני', 'בליעל'), [(s, x) for s, x, _ in LEMT('1100')], P('וידיחו', 'את', 'ישבי', 'עירם'), P('ישבי', 'עירם'), P('ישבי', 'העיר', 'ההוא')))
L('"THEN YOU SHALL INQUIRE AND SEARCH AND ASK DILIGENTLY" (ודרשת וחקרת ושאלת היטב) / "diligently" היטב (3190 the infinitive absolute as adverb) every seat in the book / "and you shall inquire diligently" (ודרשת היטב) every seat / "and the judges shall inquire diligently" (ודרשו השפטים היטב) / "AND BEHOLD IT IS TRUE, THE THING IS CERTAIN" (והנה אמת נכון הדבר) every seat / "such abomination has been done in your midst" (נעשתה התועבה הזאת בקרבך) every seat / 17:4 tokens', (P('ודרשת', 'וחקרת', 'ושאלת', 'היטב'), U('היטב', books=DT), P('ודרשת', 'היטב'), P('ודרשו', 'השפטים', 'היטב'), P('והנה', 'אמת', 'נכון', 'הדבר'), P('נעשתה', 'התועבה', 'הזאת', 'בקרבך'), P('נעשתה', 'התועבה', 'הזאת'), words('Deut', 17, 4)))
L('"SMITE, YOU SHALL SMITE THE INHABITANTS OF THAT CITY WITH THE EDGE OF THE SWORD" (הכה תכה את ישבי העיר ההוא לפי חרב) / "with the edge of the sword" (לפי חרב) seats in the Torah and the count in the Bible / "smite, you shall smite" (הכה תכה) every seat / "DEVOTING IT AND ALL THAT IS IN IT AND ITS CATTLE" (החרם אתה ואת כל אשר בה ואת בהמתה) / "devote" חרם hiphil (2763 a) seats in the Torah / "the devoted thing" the noun (2764 a) seats in the Torah / Joshua 6:21 and 8:26 and 1 Samuel 15:3 tokens', (P('הכה', 'תכה', 'את', 'ישבי', 'העיר', 'ההוא', 'לפי', 'חרב'), P('לפי', 'חרב', books=T), len(P('לפי', 'חרב')), P('הכה', 'תכה'), P('החרם', 'אתה', 'ואת', 'כל', 'אשר', 'בה'), [(s, x, m) for s, x, m in LEMT('2763 a', books=T)], [(s, x, m) for s, x, m in LEMT('2764 a', books=T)], words('Josh', 6, 21), words('Josh', 8, 26), words('1Sam', 15, 3)))
L('THE WRITTEN/READ PAIR AT 13:16 — "that city" with the masculine ההוא written for the feminine ההיא: the DB\'s tokens with wtype at 13:16 / every ההוא token in the chapter with its verse / the feminine pronoun ההיא tokens in the Torah (the read form written out) / העיר ההוא (the masculine written with the feminine noun) seats in the Torah', ([(x, m, wt) for x, m, _, _, wt in by[('Deut', 13, 16)]], [(v, x) for v in range(1, NV + 1) for x in V13(v) if x in ('ההוא', 'ההיא')], U('ההיא', books=T), P('העיר', 'ההוא', books=T), P('העיר', 'ההיא')))
L('"AND ALL ITS SPOIL YOU SHALL GATHER INTO THE MIDST OF ITS STREET" (ואת כל שללה תקבץ אל תוך רחבה) / "its spoil" (שללה) every seat / "its street" רחב the noun (7339) seats in the Torah / "and burn with fire the city and all its spoil" (ושרפת באש את העיר ואת כל שללה) / "WHOLLY TO THE LORD" (כליל ליהוה) — כליל (3632) every seat in the Bible / "a heap forever" (תל עולם) every seat / "it shall not be built again" (לא תבנה עוד) every seat / Joshua 8:28 and 6:26 tokens', (P('ואת', 'כל', 'שללה', 'תקבץ'), U('שללה'), [(s, x) for s, x, _ in LEMT('7339', books=T)], P('ושרפת', 'באש', 'את', 'העיר'), P('כליל', 'ליהוה'), [(s, x, m) for s, x, m in LEMT('3632')], P('תל', 'עולם'), P('לא', 'תבנה', 'עוד'), words('Josh', 8, 28), words('Josh', 6, 26)))
L('"THAT THE LORD MAY TURN FROM THE FIERCENESS OF HIS ANGER" (למען ישוב יהוה מחרון אפו) / "turn from the fierceness of his anger" forms (ישוב … מחרון אפו / וישב יהוה מחרון אפו / שוב מחרון אפך) every seat / "the fierceness of the LORD\'s anger" (חרון אף יהוה) count in the Bible / Numbers 25:4 and Joshua 7:26 and Exodus 32:12 tokens', (P('למען', 'ישוב', 'יהוה', 'מחרון', 'אפו'), P('מחרון', 'אפו'), P('מחרון', 'אפך'), P('מחרון', 'אף'), len(P('חרון', 'אף', 'יהוה')), words('Num', 25, 4), words('Josh', 7, 26), words('Exod', 32, 12)))
L('"AND GIVE YOU MERCY AND HAVE MERCY ON YOU AND MULTIPLY YOU" (ונתן לך רחמים ורחמך והרבך) / "give … mercy" (ונתן לך רחמים / ויתן לכם רחמים / ונתנם לרחמים) every seat / רחם piel (7355) seats in the book / "and multiply you" (והרבך) every seat / "AS HE SWORE TO YOUR FATHERS" (כאשר נשבע לאבתיך) — every seat in the book — THE AS_WHEN FORM OF THE OATH / "as He swore" (כאשר נשבע) count in the book / "which He swore to your fathers" (אשר נשבע לאבתיך) count in the book', (P('ונתן', 'לך', 'רחמים', 'ורחמך', 'והרבך'), P('לך', 'רחמים'), P('לכם', 'רחמים'), P('ונתנם', 'לרחמים'), [(s, x, m) for s, x, m in LEMT('7355', books=DT)], U('והרבך'), P('כאשר', 'נשבע', 'לאבתיך', books=DT), len(P('כאשר', 'נשבע', books=DT)), len(P('אשר', 'נשבע', 'לאבתיך', books=DT))))
L('"WHEN YOU HEARKEN TO THE VOICE OF THE LORD YOUR GOD" (כי תשמע בקול יהוה אלהיך) every seat / "to keep all His commandments which I command you today" (לשמר את כל מצותיו אשר אנכי מצוך היום) every seat / "TO DO WHAT IS RIGHT IN THE EYES OF THE LORD" (לעשות הישר בעיני יהוה) every seat / "the right in the eyes of the LORD" (הישר בעיני יהוה) count in the book and the Bible / 12:25 and 12:28 and 6:18 tokens', (P('כי', 'תשמע', 'בקול', 'יהוה', 'אלהיך'), P('לשמר', 'את', 'כל', 'מצותיו', 'אשר', 'אנכי', 'מצוך', 'היום'), P('לעשות', 'הישר', 'בעיני', 'יהוה'), len(P('הישר', 'בעיני', 'יהוה', books=DT)), len(P('הישר', 'בעיני', 'יהוה')), words('Deut', 12, 25), words('Deut', 12, 28), words('Deut', 6, 18)))
L('"abomination" (תועבה 8441) seats in the chapter / "in your midst" (בקרבך) seats in the chapter and the count in the book / "from your midst" (מקרבך) seats in the chapter / "the evil" (הרע) tokens in the chapter / "the way" (הדרך) seats in the chapter', ([s for s, _, _ in LEMT('8441', books=DT) if s.startswith('Deut 13:')], [v for v in range(1, NV + 1) if 'בקרבך' in V13(v)], len(U('בקרבך', books=DT)), [v for v in range(1, NV + 1) if 'מקרבך' in V13(v)], [(v, x) for v in range(1, NV + 1) for x in V13(v) if x in ('הרע', 'רע', 'הרעה')], [v for v in range(1, NV + 1) if 'הדרך' in V13(v)]))
L('THE THREE INFINITIVE ABSOLUTES (13:10 kill, 13:16 smite, 13:16 devote) — every HV.a token in the chapter with its morph / the infinitive absolutes of the book (count) / the three "when" cases — כי opening a verse in the chapter (verse-initial כי) / "or" (או) tokens in the chapter (the count) and per verse', ([(v, x, m) for v in range(1, NV + 1) for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.match(r'^H(?:C/)?V.a$', m)], len([1 for (b, c, v), ws in by.items() if b == 'Deut' for x, m, _, _, _ in ws if m and re.match(r'^H(?:C/)?V.a$', m)]), [v for v in range(1, NV + 1) if V13(v)[0] == 'כי'], sum(1 for v in range(1, NV + 1) for x in V13(v) if x == 'או'), {v: V13(v).count('או') for v in range(1, NV + 1) if 'או' in V13(v)}))
L('THE NAME bare tokens per verse and the count / "the LORD your God" singular (יהוה אלהיך) and plural (יהוה אלהיכם) per verse / "to the LORD" (ליהוה) seats in the chapter / "Egypt" and "Israel" seats', ({v: sum(1 for x in V13(v) if x == 'יהוה') for v in range(1, NV + 1) if 'יהוה' in V13(v)}, sum(1 for v in range(1, NV + 1) for x in V13(v) if x == 'יהוה'), [v for v in range(1, NV + 1) if any(V13(v)[i:i + 2] == ['יהוה', 'אלהיך'] for i in range(len(V13(v)) - 1))], [v for v in range(1, NV + 1) if any(V13(v)[i:i + 2] == ['יהוה', 'אלהיכם'] for i in range(len(V13(v)) - 1))], [v for v in range(1, NV + 1) if 'ליהוה' in V13(v)], [(v, x) for v in range(1, NV + 1) for x in V13(v) if x in ('מצרים', 'ישראל')]))
L('THE CHAPTER\'S OWN WORDS (per-verse seats): "prophet" (5030) / "dream" (2472) / "sign" (226) / "wonder" (4159) / "hear" (8085) / "serve" (5647) / "go" (3212) / "know" (3045) / "die" (4191) / "kill" (2026) / "stone" (5619) / "city" (5892 b) / "hand" (3027) / "people" (5971 a) / "sword" (2719) / "fire" (784) / "devote" (2763 a) and "the devoted thing" (2764 a) / "fear" (3372) / "commandment" (4687) / "way" (1870)', {lab: [s for s, _, _ in LEMT(lem, books=DT) if s.startswith('Deut 13:')] for lab, lem in (('prophet', '5030'), ('dream', '2472'), ('sign', '226'), ('wonder', '4159'), ('hear', '8085'), ('serve', '5647'), ('go', '3212'), ('know', '3045'), ('die', '4191'), ('kill', '2026'), ('stone', '5619'), ('city', '5892 b'), ('hand', '3027'), ('people', '5971 a'), ('sword', '2719'), ('fire', '784'), ('devote-v', '2763 a'), ('devoted-n', '2764 a'), ('fear', '3372'), ('commandment', '4687'), ('way', '1870'))})
L('THE FRAME OF THE CHAPTER — 13:1 against 4:2, 8:1, 12:28, 5:1, 6:1 (the tokens shared) and 13:19 against 12:25, 12:28, 15:5, 28:1 / the book\'s "that I command you today" forms (אשר אנכי מצוך היום) count', ((SH(D13(1), ('Deut', 4, 2)), SH(D13(1), ('Deut', 8, 1)), SH(D13(1), ('Deut', 12, 28)), SH(D13(1), ('Deut', 5, 1)), SH(D13(1), ('Deut', 6, 1))), (SH(D13(19), ('Deut', 12, 25)), SH(D13(19), ('Deut', 12, 28)), SH(D13(19), ('Deut', 15, 5)), SH(D13(19), ('Deut', 28, 1))), len(P('אשר', 'אנכי', 'מצוך', 'היום', books=DT))))
L('THE MORPHOLOGY TAGGER\'S "Np" SUBSTRING — the tokens the dump\'s name regex matched by substring ("Np" inside a niphal perfect): every token of the chapter whose morph CONTAINS "Np" against those whose morph STARTS "HNp"', ([(v, x, m) for v in range(1, NV + 1) for x, m, _, _, _ in by[('Deut', 13, v)] if m and 'Np' in m], [(v, x) for v in range(1, NV + 1) for x, m, _, _, _ in by[('Deut', 13, v)] if m and m.startswith('HNp')]))
print('==== C. THE PARSER — the number verses of the chapter and of the kin (the engine\'s ink_numbers / ink_ordinals; the marked tokens)')
with contextlib.redirect_stdout(io.StringIO()):
    import cold_run_sequence as CS
PARSE = {v: (CS.ink_numbers(CS.verse_words('Deut', CH, v)), CS.ink_ordinals(CS.verse_words('Deut', CH, v)), [t for t in CS.verse_words('Deut', CH, v) if t[-1] in '#~^%@|*']) for v in range(1, NV + 1)}
L('the chapter\'s verses with a number, an ordinal or a marked token', {v: p for v, p in PARSE.items() if p[0] or p[1] or p[2]})
L('13:13 and 13:18 as the engine reads them (13:18\'s "swore" is no number — the dump\'s bare check matched the seven inside the oath\'s root)', (CS.verse_words('Deut', CH, 13), CS.verse_words('Deut', CH, 18)))
KINK = [('Deut', 17, 6), ('Deut', 19, 15), ('Deut', 17, 7), ('Deut', 17, 2), ('Deut', 4, 2), ('Deut', 6, 14), ('Deut', 10, 20), ('Lev', 20, 2), ('Lev', 24, 14), ('Lev', 24, 16), ('Lev', 27, 28), ('Lev', 27, 29), ('Num', 15, 30), ('Num', 15, 35), ('Exod', 22, 19), ('Deut', 7, 2), ('Deut', 7, 26), ('Josh', 6, 21), ('Josh', 7, 1), ('Josh', 8, 28), ('Deut', 13, 13), ('Deut', 12, 14)]
L('the kin\'s numbers (ink_numbers on the kin verses)', {k: CS.ink_numbers(CS.verse_words(*k)) for k in KINK if k in by})
L('"one" (אחד / אחת / באחת / באחד) tokens in the chapter and the engine\'s reading of "in one of your cities"', ([(v, x) for v in range(1, NV + 1) for x in V13(v) if x in ('אחד', 'באחד', 'אחת', 'באחת')], PARSE[13]))
L('the starred or marked tokens over the book at the chapter\'s number word — every באחת / באחד the engine marks', sorted({(b, c, v, t) for (b, c, v) in by if b == 'Deut' for t in CS.verse_words(b, c, v) if t.startswith('באח') and t[-1] in '#~^%@|*'}))
print('==== D. THE REGISTER — the second-person number by verse (2mp count, 2ms count), the first person, the verb forms, the written/read pair')
NUM = {v: (sum(1 for _, m, _, _, _ in by[('Deut', 13, v)] if m and '2mp' in m), sum(1 for _, m, _, _, _ in by[('Deut', 13, v)] if m and '2ms' in m)) for v in range(1, NV + 1)}
L('2mp / 2ms per verse', NUM); L('singular-only verses', [v for v, (p, s) in NUM.items() if s and not p]); L('plural-only', [v for v, (p, s) in NUM.items() if p and not s]); L('both', [v for v, (p, s) in NUM.items() if p and s]); L('neither', [v for v, (p, s) in NUM.items() if not p and not s])
L('the plural tokens in the mixed and plural verses', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and '2mp' in m] for v in range(1, NV + 1) if NUM[v][0]})
L('first-person plural (1cp) per verse', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and '1cp' in m] for v in range(1, NV + 1) if any(m and '1cp' in m for _, m, _, _, _ in by[('Deut', 13, v)])}); L('first-person singular (1cs)', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and '1cs' in m] for v in range(1, NV + 1) if any(m and '1cs' in m for _, m, _, _, _ in by[('Deut', 13, v)])})
L('imperatives (any stem: HV.v / HV..v) per verse', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.match(r'^HV.?.?v', m)] for v in range(1, NV + 1) if any(m and re.match(r'^HV.?.?v', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('infinitive absolutes (HV.a)', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.match(r'^H(?:C/)?V.a$', m)] for v in range(1, NV + 1) if any(m and re.match(r'^H(?:C/)?V.a$', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('consecutive perfects (V.q) per verse — the law\'s form', {v: [x for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.search(r'^HC/V.q', m)] for v in range(1, NV + 1) if any(m and re.search(r'^HC/V.q', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('imperfect second person (V.i2) per verse', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.search(r'^H(?:Ti/)?V.i2', m)] for v in range(1, NV + 1) if any(m and re.search(r'^H(?:Ti/)?V.i2', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('narrative (wayyiqtol, V.w) per verse', {v: [x for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.search(r'^HC/V.w', m)] for v in range(1, NV + 1) if any(m and re.search(r'^HC/V.w', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('participles (V.r) per verse', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.search(r'^H(?:C/|R/|Td/|C/R/)?V.r', m)] for v in range(1, NV + 1) if any(m and re.search(r'^H(?:C/|R/|Td/|C/R/)?V.r', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('the article + participle chain (HTd/V.r) — "who brought you out … who led you … who fed you"', [(v, x) for v in range(1, NV + 1) for x, m, _, _, _ in by[('Deut', 13, v)] if m and m.startswith('HTd/V') and 'r' in m[6:8]])
L('perfects (V.p) per verse', {v: [(x, m) for x, m, _, _, _ in by[('Deut', 13, v)] if m and re.match(r'^H(?:C/)?V.p', m)] for v in range(1, NV + 1) if any(m and re.match(r'^H(?:C/)?V.p', m) for _, m, _, _, _ in by[('Deut', 13, v)])})
L('prohibitions לא + imperfect', {v: [(by[('Deut', 13, v)][i + 1][0], by[('Deut', 13, v)][i + 1][1]) for i, (x, _, _, _, _) in enumerate(by[('Deut', 13, v)][:-1]) if x in ('לא', 'ולא') and by[('Deut', 13, v)][i + 1][1] and by[('Deut', 13, v)][i + 1][1].startswith('HV')] for v in range(1, NV + 1) if any(x in ('לא', 'ולא') for x, _, _, _, _ in by[('Deut', 13, v)])})
L('"not" (לא / ולא) seats per verse', {v: [x for x in V13(v) if x in ('לא', 'ולא')] for v in range(1, NV + 1) if any(x in ('לא', 'ולא') for x in V13(v))})
L('case tokens per verse', {f'13:{v}': [x for x in V13(v) if x in ('כי', 'אם', 'ואם', 'או', 'פן')] for v in range(1, NV + 1) if any(x in ('כי', 'אם', 'ואם', 'או', 'פן') for x in V13(v))}); L('"saying" (לאמר) seats', [v for v in range(1, NV + 1) if 'לאמר' in V13(v)]); L('divine frames (ויאמר/וידבר יהוה)', [v for v in range(1, NV + 1) if any(V13(v)[i] in ('ויאמר', 'וידבר') and V13(v)[i + 1] == 'יהוה' for i in range(len(V13(v)) - 1))])
L('"so that" (למען) seats per verse', {v: [x for x in V13(v) if x in ('למען', 'ולמען')] for v in range(1, NV + 1) if any(x in ('למען', 'ולמען') for x in V13(v))}); L('"so that" count in chapter 13 and in Deuteronomy', (sum(1 for v in range(1, NV + 1) for x in V13(v) if x in ('למען', 'ולמען')), len(U('למען', 'ולמען', books=('Deut',)))))
L('tokens per verse', {v: len(V13(v)) for v in range(1, NV + 1)}); L('the chapter\'s tokens and letters', (sum(len(V13(v)) for v in range(1, NV + 1)), sum(len(x) for v in range(1, NV + 1) for x in V13(v))))
L('wtype values in chapter 13', Counter(wt for v in range(1, NV + 1) for _, _, _, _, wt in by[('Deut', 13, v)])); L('the ketiv token(s) of chapter 13', [(v, x, m, wt) for v in range(1, NV + 1) for x, m, _, _, wt in by[('Deut', 13, v)] if wt])




print('==== E. ONKELOS — the renderings\' seats over the book (the export\'s verse numbers; the export\'s chapter 13 = the DB\'s, the identity)')
L('"THE FEAR OF" (דחלת) SUPPLIED — 13:5 "after the fear of the LORD your God you shall walk … and to His fear you shall cleave" and 13:11 "from the fear of the LORD" rendered / every דחלת seat in the book / "the fear of the LORD" (דחלתא דיי) seats', (arm(13, 5), arm(13, 11)[:8], onk_seats('דחלת'), onk_seats('דחלתא דיי')))
L('"ACCEPT" (תקבל / תקבלון) for "hear / hearken" — the chapter\'s seats (13:4, 5, 9, 19) and every קבל seat in the book / "the Word" (מימר) the chapter\'s seats (13:5 "accept His Word", 13:19 "accept the Word of the LORD") and every מימר seat in the book', ([(c, v) for c, v in onk_seats('תקבל') if c == 13], onk_seats('תקבל'), [(c, v) for c, v in onk_seats('מימר') if c == 13], onk_seats('מימר')))
L('"THE ERRORS OF THE PEOPLES" (טעות עממיא) for "other gods" — the chapter\'s seats (13:3, 7, 8, 14) and every seat in the book / "errors" (טעות) count in the book', ([(c, v) for c, v in onk_seats('טעות עממיא') if c == 13], onk_seats('טעות עממיא'), len(onk_seats('טעות'))))
L('"BEFORE HIM" (קדמוהי) for "Him you shall serve" at 13:5 and "before the LORD" (קדם יי) for "to the LORD" at 13:17 (the whole offering) / the chapter\'s קדם seats / "a fabrication" (סטיא) for "rebellion" — every seat / "the wife of your covenant" (אתת קימך) for "the wife of your bosom" — every קימך seat / "sons of wickedness" (בני רשעא) for "sons of Belial" — every seat', ([(c, v) for c, v in onk_seats('קדם') if c == 13], arm(13, 17)[-12:], onk_seats('סטיא'), onk_seats('אתת קימך'), onk_seats('קימך'), onk_seats('בני רשעא')))
L('"SHALL BE KILLED" (יתקטל) for "shall be put to death" — every seat in the book / "you shall kill him" (תקטלניה) / "stone him" (ותרגמניה) — every רגמ seat / "he incites you" (ימלכנך) — the root מלך "counsel" seats / "redeemed you" (פרקך) seats', (onk_seats('יתקטל'), onk_seats('תקטלניה'), onk_seats('רגמ'), onk_seats('ימלכנך'), onk_seats('מלכנ'), onk_seats('פרקך')))
L('"BY THE WORD OF THE SWORD" (לפתגם דחרב) for "with the edge of the sword" — every seat / "wholly" (גמיר) at 13:17 and "devote" (גמר) at 13:16 — every גמ(י)ר seat / "a ruined mound" (תל חריב) at 13:17 — every seat / "He swore" (קיים) at 13:18 — every קיים seat in the book', (onk_seats('לפתגם דחרב'), onk_seats('גמיר'), onk_seats('גמר'), onk_seats('תל חריב'), onk_seats('קיים')))
L('"true, the thing is certain" (קשטא כון פתגמא) at 13:15 / "and you shall seek and examine and ask well" (ותתבע ותבדוק ותשאל יאות) — the three Aramaic verbs\' seats / "in the first" (בקדמיתא) and "afterward" (בבתריתא) at 13:10 / "and they shall fear" (וידחלון) at 13:12', (arm(13, 15), onk_seats('ותבדוק'), onk_seats('יאות'), arm(13, 10), arm(13, 12)))
L('"the Memra" (מימר) in the chapter / the parenthesized supplements in the Aramaic export for chapter 13 / "the Shekhinah" (שכנת) in the chapter — none expected', ([(c, v) for c, v in onk_seats('מימר') if c == 13], [(13, v + 1, clean(onk_he[12][v])) for v in range(len(onk_he[12])) if '(' in clean(onk_he[12][v])], [(c, v) for c, v in onk_seats('שכנת') if c == 13]))
L('the Aramaic of 13:1 (the header), 13:2 (the prophet), 13:7 (the inciter), 13:16 (the city)', (arm(13, 1), arm(13, 2), arm(13, 7), arm(13, 16)))
print('==== F. THE ENGLISH\'S BRACKETS (the translator\'s supplements) per verse of chapter 13')
BR = {v: re.findall(r'\[([^\]]+)\]', clean(onk[CH - 1][v - 1])) for v in range(1, NV + 1)}
L('bracket count per verse and the total', ({v: len(b) for v, b in BR.items() if b}, sum(len(b) for b in BR.values()))); L('the bracketed strings by verse', {v: b for v, b in BR.items() if b}); L('parenthesis rows in the English', [v for v in range(1, NV + 1) if '(' in clean(onk[CH - 1][v - 1])])
print('==== G. THE STORE\'S GLOSS FAMILIES (every gloss of chapter 13\'s tokens censused over the whole store: the tokens carrying it, with counts; the glosses ALREADY rewritten by the by-gloss overrides listed apart)')
store = sqlite3.connect(f'file:{ROOT}/torah_grok.SNAPSHOT-main-51801ca.sqlite?mode=ro', uri=True)
SG = {}
for c_, v_, i_, hp, g in store.execute("SELECT v.chapter, v.verse, w.idx, w.he_plain, w.gloss FROM words w JOIN verses v ON w.verse_id=v.id WHERE v.book='Deut' AND v.chapter=? ORDER BY v.id, w.idx", (CH,)):
    SG.setdefault((c_, v_), []).append((i_, hp.replace('/', ''), g))
ALLG = {}
for hp, g in store.execute("SELECT w.he_plain, w.gloss FROM words w"): ALLG.setdefault(g, Counter())[hp.replace('/', '')] += 1
CHG = sorted({g for k in SG for _, _, g in SG[k]})
import yaml
OVY = yaml.safe_load(open(f'{ROOT}/logic/glosses/word_gloss_overrides.yaml', encoding='utf-8'))
BG = OVY.get('by_gloss', OVY.get('gloss', {})) if isinstance(OVY, dict) else {}
L('distinct glosses in the chapter / already in the by-gloss overrides', (len(CHG), len([g for g in CHG if g in BG])))
L('the chapter\'s glosses ALREADY in the by-gloss overrides (gloss -> rewrite)', {g: BG[g] for g in CHG if g in BG})
for g in CHG:
    if g in BG: continue
    fam = ALLG.get(g, Counter()); print(f'  {g!r}: {sum(fam.values())} tokens in {len(fam)} words — {fam.most_common(4)} | in the chapter: {sorted({(k[1], hp) for k in SG for _, hp, gg in SG[k] if gg == g})[:6]}')
L('the store\'s "?" glosses in the chapter (verse, idx, token)', [(k[1], i_, hp) for k in sorted(SG) for i_, hp, g in SG[k] if g == '?'])
L('THE STORE AGAINST THE DB AT 13:16 — the store\'s tokens (idx, token, gloss) and the DB\'s tokens with wtype: the written/read pair', ([(i_, hp, g) for i_, hp, g in SG[(13, 16)]], [(x, wt) for x, _, _, _, wt in by[('Deut', 13, 16)]], sum(len(SG[k]) for k in SG), sum(len(by[('Deut', 13, v)]) for v in range(1, NV + 1))))
L('the overrides file\'s top-level keys and sizes', {k: (len(v) if hasattr(v, '__len__') else v) for k, v in OVY.items()} if isinstance(OVY, dict) else type(OVY))
print('==== H. THE PRIOR READS — the kin\'s ledgers and their Onkelos rows on the kin verses (computed from the ledgers themselves); THE REGISTER\'S FINDER on the chapter')
TRI = f'{ROOT}/logic/oral_triage'
LED = {f: open(f'{TRI}/{f}', encoding='utf-8').read() for f in os.listdir(TRI) if f.endswith('.md') and os.path.isfile(f'{TRI}/{f}')}
def kinrows(f, pat): return len(re.findall(r'^- Onkelos ' + pat, LED[f], re.M))
for pref in ('exo_22', 'exo_32', 'lev_20', 'lev_24', 'lev_27', 'num_15', 'num_25', 'deu_04', 'deu_06', 'deu_07', 'deu_08', 'deu_10', 'deu_11', 'deu_12', 'gen_22', 'gen_37', 'exo_16', 'exo_20', 'exo_13', 'num_12', 'num_21', 'jos_', 'jdg_', 'sam_', 'kgs_'):
    fs = sorted(f for f in LED if f.startswith(pref))
    print(f'  {pref}*: {[(f, len(re.findall(r"^- Onkelos ", LED[f], re.M))) for f in fs]}')
L('the sacrifice to other gods (Exodus 22:19) Onkelos rows by ledger / the calf\'s "these are your gods" (Exodus 32:1-8) rows by ledger', ([(f, kinrows(f, r'Exod 22:19\b')) for f in LED if kinrows(f, r'Exod 22:19\b')], [(f, kinrows(f, r'Exod 32:[1-8]\b')) for f in LED if kinrows(f, r'Exod 32:[1-8]\b')]))
L('the stoning by the people (Leviticus 20:2, 20:27) and by the witnesses (Leviticus 24:14-16, 24:23) Onkelos rows by ledger / the wood-gatherer stoned (Numbers 15:35-36) / the high hand (Numbers 15:30-31)', ([(f, kinrows(f, r'Lev 20:(?:2|27)\b')) for f in LED if kinrows(f, r'Lev 20:(?:2|27)\b')], [(f, kinrows(f, r'Lev 24:(?:1[4-6]|23)\b')) for f in LED if kinrows(f, r'Lev 24:(?:1[4-6]|23)\b')], [(f, kinrows(f, r'Num 15:3[56]\b')) for f in LED if kinrows(f, r'Num 15:3[56]\b')], [(f, kinrows(f, r'Num 15:3[01]\b')) for f in LED if kinrows(f, r'Num 15:3[01]\b')]))
L('the devoted thing (Leviticus 27:28-29) Onkelos rows by ledger / the ban and the devoted thing in the house (Deuteronomy 7:2, 7:16, 7:25-26) / the fierce anger turned (Numbers 25:4) / Hormah\'s vow (Numbers 21:2-3)', ([(f, kinrows(f, r'Lev 27:2[89]\b')) for f in LED if kinrows(f, r'Lev 27:2[89]\b')], [(f, kinrows(f, r'Deut 7:(?:2|16|25|26)\b')) for f in LED if kinrows(f, r'Deut 7:(?:2|16|25|26)\b')], [(f, kinrows(f, r'Num 25:4\b')) for f in LED if kinrows(f, r'Num 25:4\b')], [(f, kinrows(f, r'Num 21:[23]\b')) for f in LED if kinrows(f, r'Num 21:[23]\b')]))
L('the testing (Genesis 22:1; Exodus 15:25, 16:4, 20:17; Deuteronomy 8:2, 8:16) Onkelos rows by ledger / the signs and wonders (Deuteronomy 4:34, 6:22, 7:19) / "not add nor diminish" (Deuteronomy 4:2) / the peoples round about (6:14) / the six verbs\' kin (6:13, 10:20, 11:22) / "which you have not known" (11:28) / the right in His eyes (12:25, 12:28)', ([(f, kinrows(f, r'(?:Gen 22:1|Exod 15:25|Exod 16:4|Exod 20:17|Deut 8:(?:2|16))\b')) for f in LED if kinrows(f, r'(?:Gen 22:1|Exod 15:25|Exod 16:4|Exod 20:17|Deut 8:(?:2|16))\b')], [(f, kinrows(f, r'Deut (?:4:34|6:22|7:19)\b')) for f in LED if kinrows(f, r'Deut (?:4:34|6:22|7:19)\b')], [(f, kinrows(f, r'Deut 4:2\b')) for f in LED if kinrows(f, r'Deut 4:2\b')], [(f, kinrows(f, r'Deut 6:14\b')) for f in LED if kinrows(f, r'Deut 6:14\b')], [(f, kinrows(f, r'Deut (?:6:13|10:20|11:22)\b')) for f in LED if kinrows(f, r'Deut (?:6:13|10:20|11:22)\b')], [(f, kinrows(f, r'Deut 11:28\b')) for f in LED if kinrows(f, r'Deut 11:28\b')], [(f, kinrows(f, r'Deut 12:2[58]\b')) for f in LED if kinrows(f, r'Deut 12:2[58]\b')]))
L('the dreamer (Genesis 37:5-11, 19-20; Numbers 12:6) Onkelos rows by ledger / the Decalogue\'s preamble (Exodus 20:2; Deuteronomy 5:6) / the exodus with redeeming (Deuteronomy 7:8, 9:26)', ([(f, kinrows(f, r'(?:Gen 37:(?:[5-9]|1[01]|19|20)|Num 12:6)\b')) for f in LED if kinrows(f, r'(?:Gen 37:(?:[5-9]|1[01]|19|20)|Num 12:6)\b')], [(f, kinrows(f, r'(?:Exod 20:2|Deut 5:6)\b')) for f in LED if kinrows(f, r'(?:Exod 20:2|Deut 5:6)\b')], [(f, kinrows(f, r'Deut (?:7:8|9:26)\b')) for f in LED if kinrows(f, r'Deut (?:7:8|9:26)\b')]))
L('NEVER READ AHEAD — ledgers with an Onkelos row of Deuteronomy 14-20 (expected none) / any Onkelos row of Joshua, Judges, Samuel or Kings anywhere (expected none)', ([(f, kinrows(f, r'Deut (?:1[4-9]|20):')) for f in LED if kinrows(f, r'Deut (?:1[4-9]|20):')], [(f, kinrows(f, r'(?:Josh|Judg|1Sam|2Sam|1Kgs|2Kgs) ')) for f in LED if kinrows(f, r'(?:Josh|Judg|1Sam|2Sam|1Kgs|2Kgs) ')]))
L('the ledgers naming a verse of chapter 13 (strict, both book forms)', sorted((f, sorted(set(re.findall(r'Deut(?:eronomy)? 13:\d+', t)))) for f, t in LED.items() if re.search(r'Deut(?:eronomy)? 13:\d+', t)))
PRIOR = sorted({(f, int(a), int(b)) for f, t in LED.items() for a, b in re.findall(r'Sifrei Devarim (\d+):(\d+)', t)})
L('prior Sifrei reads among piskaot 82-96 (ledger, piska, row) and the count', ([(f, p, r) for f, p, r in PRIOR if 82 <= p <= 96], len([(f, p, r) for f, p, r in PRIOR if 82 <= p <= 96]), len(PRIOR)))
L('prior reads among the outside rows 117:3, 149:1, 149:2, 189:1, 190:7, 190:8', [(f, p, r) for f, p, r in PRIOR if (p, r) in [(117, 3), (149, 1), (149, 2), (189, 1), (190, 7), (190, 8)]])
try:
    with contextlib.redirect_stdout(io.StringIO()):
        import register_census as RC
        ink = RC.read_ink()
    L('THE FINDER — the receipt lines the register gate finds in chapter 13 (both forms with the Name)', [k for k in RC.receipts(ink) if k[0] == 'Deut' and k[1] == 13])
    L('THE FINDER — the footers/headers and the register headers in chapter 13', ([x for x in RC.footers(ink) if x[0][0] == 'Deut' and x[0][1] == 13], [x for x in RC.register_headers(ink) if x[0][0] == 'Deut' and x[0][1] == 13]))
    L('THE FINDER — the receipts in the book so far (chapters 1-13)', [k for k in RC.receipts(ink) if k[0] == 'Deut' and k[1] <= 13])
except Exception as e: print('  THE FINDER could not be run here:', repr(e)[:300])
