#!/usr/bin/env python3
# DEUTERONOMY 13:1-19 — THE HEADER'S SEAL, THE PROPHET AND THE TEST, THE INCITER, THE CITY HEARD OF, THE INQUIRY AND THE SWORD, THE WHOLE OFFERING, THE HEAP AND
# THE MERCY, THE FOOTER — THE SEDUCERS' ONE SENTENCE SAID THREE TIMES; THE READBACK'S FORMS ON FILE, NO NEW FORM (THE DEUTERONOMY WALK sitting 11b, 2026-09-21;
# World/step9/DEUTERONOMY_WALK.md "Sitting 11b"; the state doc's #203). THE CODE'S FOUR HOLES compiled at the counter's day (40, 11, 1), FOUR own-day lines, NO
# marker: the header's seal (13:1 — A REUSE: adding_barred's second entry, 4:2's twin in the singular), the prophet's test and the false prophet's death (13:2-6 —
# false_prophet_hearing_barred a BLOCK with the_signs_status a PARAMETER, tested_by_the_lord a STATUS, cleaving_commanded REUSED for the six verbs; the death
# the case's — the_prophets_death a PARAMETER: stoning / strangling, the answer sheet's arm; evil_purged_from_the_midst NAMED at THE PURGE FORMULA'S FIRST SEAT OF
# NINE), the inciter's law (13:7-12 — pity_barred REUSED with the five prohibitions against the standing duties and the court's rule inverted; israel_hears_and_fears
# THE FORMULA'S FIRST SEAT OF FOUR with the_execution_timing a PARAMETER; the entrapment, the fifteen utterances, the hand first, the stoning's rite by CALL), the
# condemned city's law (13:13-19 — condemned_city_inquiry_required a STATUS: the seducers' parameters from one noun, Jerusalem excluded, the venue, THE SEVEN
# INTERROGATIONS with the_inquiries a PARAMETER; devoted_thing_cleaving_barred a BLOCK: the benefit ban's source and reach; the case's city_devoted — the sword,
# the property table, Heaven's spoil, the heap forever with Jericho and Hiel; the footer the condition, no write). THE KIN'S CELLS BY CALL (twenty runners); THE
# TAPE'S LINES BY KIND (the calf, the testing, the cloud, the stonings, Hormah, Peor, the not-adding, the cleaving, the nations devoted). Six cells and the table;
# every token probed (zero-report law); effects on every cell (the effects law); the DATA rows the docket added. The daemon law_seducers given_at Deut 13:1,
# installed_by boot (the Deuteronomy daemons' form). Reading ledger: logic/oral_triage/deu_13_reeh_2026-09-21.md; the exam's docket: deu_13_reeh_exam_2026-09-21.md
# (565 rows — 409 READ WHOLE in one run, 156 carried with their ledgers' own verdicts: LAW 127 / DERIVATION 103 / DISPUTE 88 / CONTEXT 111 / OUTSIDE 136).

# ---- THE HONEST-PAIRING GUARD ----------------------------------------------------------------------------
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..'))   # THE PORTABLE REPO: the repo root from this file's own place
from compile_guards import check_honest_pairing as _chp
_P = _os.path.abspath(__file__)
GUARDED = _chp(_P, 'CASES', 2)
assert GUARDED == 0, ("the guard counted %d expectations, the tripwire holds 0" % GUARDED)   # RETYPED after the generator (the cells' asks summed)
print('guard: %d expectations checked, every one a literal from the answer sheet [honest-pairing guard satisfied]' % GUARDED)
import sqlite3, sys, io, re, contextlib, collections, unicodedata, yaml
from collections import Counter
import effects_layer as FX
import world_engine as WE
import cold_run_obey_horeb as OH               # THE EDGE: seducers -> obey_horeb CALL, reference (13:1's seal 4:2's law in the singular — add_nothing, diminish_nothing, add_beside, add_out_of_its_time; adding_barred REUSED; add_nothing_commanded 4:1 on the tape)
import cold_run_covenant_at_horeb as CH       # THE EDGE: seducers -> covenant_at_horeb CALL, reference (13:3, 7, 14's 'other gods' the second word's object; 13:6, 11's exodus formula the preamble's 5:6)
import cold_run_hear_o_israel as HI           # THE EDGE: seducers -> hear_o_israel CALL, reference (13:4's testing against 6:16's test_barred; 13:5's six verbs against 6:13's three; 13:8's gods round about 6:14's; 13:19's right 6:18's)
import cold_run_seven_nations as SN           # THE EDGE: seducers -> seven_nations CALL, reference (13:9's pity 7:16's — pity_barred REUSED; 13:16's devoting 7:2's ban; 13:18's devoted thing 7:26's house_abomination_barred; the oath and the redeeming 7:8's)
import cold_run_good_land as GL               # THE EDGE: seducers -> good_land CALL, reference (13:4's testing 8:2 and 8:16's forty years — 'to know')
import cold_run_not_righteousness as NR       # THE EDGE: seducers -> not_righteousness CALL, reference (13:6's redeeming 9:26's; the calf 13:3's run case; the fathers' merit 7b's parameter at 13:18)
import cold_run_second_tablets as ST          # THE EDGE: seducers -> second_tablets CALL, reference (13:5's six verbs 10:20's four — cleaving_commanded REUSED; Sotah 14a's attributes)
import cold_run_blessing_and_curse as BC      # THE EDGE: seducers -> blessing_and_curse CALL, reference (13:3 and 13:14's 'other gods which you have not known' 11:28's; 13:4's heart and soul 11:13's; 13:19's 'if you hearken')
import cold_run_place_name as PN              # THE EDGE: seducers -> place_name CALL, reference (13:13's [1] 12:14's form; 13:19's right 12:25 and 12:28's; the tape's last Deuteronomy 12 line the four new lines' predecessor)
import cold_run_ordinances as OR              # THE EDGE: seducers -> ordinances CALL, reference (13:16's devoting Exodus 22:19's ban at its first seat; 13:9's inverted rule the court's ordinary one; the four services)
import cold_run_erection as ER                # THE EDGE: seducers -> erection CALL, reference (13:3's formula the calf's — calf_made Exod 32:4 on the tape; 13:5's first verb the cloud — cloud_lifted)
import cold_run_sanctions as SA               # THE EDGE: seducers -> sanctions CALL, reference (13:6's death the four deaths' census — the strangled; 13:10's people who stone at Molech; the forewarning)
import cold_run_lev24 as L24                  # THE EDGE: seducers -> lev24 CALL, reference (13:10's hand first Leviticus 24:14's hands laid; the blasphemer's stoning — stoned_as_commanded Lev 24:23 on the tape)
import cold_run_mekoshesh as MK               # THE EDGE: seducers -> mekoshesh CALL, reference (13:11's stoning's rite THE WOOD-GATHERER'S CELL — the stones and the stone; stoned_as_commanded Num 15:36 on the tape)
import cold_run_temurah as TM                 # THE EDGE: seducers -> temurah CALL, reference (13:16's devoting Leviticus 27:28-29's devoted thing — the person put to death, the thing most holy)
import cold_run_chukat as CK                  # THE EDGE: seducers -> chukat CALL, reference (13:16's devoting Numbers 21:2-3's Hormah — the ban performed, cherem_vowed closed, destroyed on the king of Arad)
import cold_run_balak as BK                   # THE EDGE: seducers -> balak CALL, reference (13:18's anger Peor's — hanging_commanded Num 25:4 on the tape; the anger keyed to idolatry)
import cold_run_beha as BH                    # THE EDGE: seducers -> beha CALL, reference (13:2's dream Numbers 12:6-8's channel; 13:5's cloud the march's — cloud_lifted Num 10:11)
import cold_run_mamre as MM                   # THE EDGE: seducers -> mamre CALL, reference (13:4's testing Genesis 22:1's first seat — tested on the tape; Isaac at Moriah on the prophet's presumption)
import cold_run_holiness as HO                # THE EDGE: seducers -> holiness CALL, reference (13:9's five prohibitions against Leviticus 19:16 and 19:18's standing duties — the neighbor's blood, the great rule)

HERE = _os.path.dirname(_os.path.abspath(__file__))
# ONE copy of the numeral parser: the sequence runner's INK block executed here (the stitcher's way — no import edge)
_SRC = open(_os.path.join(HERE, 'cold_run_sequence.py'), encoding='utf-8').read()
_INK = {'re': re, 'sqlite3': sqlite3, 'os': _os, 'WE': WE}
_INK['_ROOT'] = _ROOT   # THE PORTABLE REPO (2026-09-15): the INK block reads the store through the root; the exec'd namespace must carry it
exec(_SRC.split('# ==== INK BEGIN')[1].split('# ==== INK END ====')[0].split('\n', 1)[1], _INK)
ink_numbers, ink_ordinals, verse_words = _INK['ink_numbers'], _INK['ink_ordinals'], _INK['verse_words']

db = sqlite3.connect((_ROOT + '/Data/tanakh.sqlite'))
def plain(w): return ''.join(c for c in w if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
def pointed(w): return ''.join(c for c in w if c != '/' and not (0x0591 <= ord(c) <= 0x05AF))
def NF(s): return unicodedata.normalize('NFC', s)
_rows = db.execute("SELECT v.book, v.chapter, v.verse, w.he, w.morph, w.lemma, w.wtype FROM words w JOIN verses v ON w.verse_id=v.id ORDER BY v.id, w.idx").fetchall()
by, byp, byl, byw, byraw = {}, {}, {}, {}, {}
for _b, _c, _v, _he, _m, _lem, _wt in _rows:
    by.setdefault((_b, _c, _v), []).append((plain(_he), _m)); byp.setdefault((_b, _c, _v), []).append(pointed(_he)); byl.setdefault((_b, _c, _v), []).append((_lem or '').split('/')[-1].strip()); byw.setdefault((_b, _c, _v), []).append(_wt); byraw.setdefault((_b, _c, _v), []).append(_lem or '')
T = ('Gen', 'Exod', 'Lev', 'Num', 'Deut')
def words(b, c, v): return [x for x, _ in by[(b, c, v)]]
def morphs(b, c, v): return [m for _, m in by[(b, c, v)]]
def wm(b, c, v): return list(zip(words(b, c, v), morphs(b, c, v)))
def hits(sub, books=None, exact=False): return sorted({f'{b} {c}:{v}' for (b, c, v), ws in by.items() if (books is None or b in books) and any((x == sub) if exact else (sub in x) for x, _ in ws)})
def phrase(seq, books=T):
    out_ = []
    for (b, c, v), ws in by.items():
        if books is not None and b not in books: continue
        w = [x for x, _ in ws]
        if any(w[i:i + len(seq)] == list(seq) for i in range(len(w) - len(seq) + 1)): out_.append(f'{b} {c}:{v}')
    return sorted(out_)
def P(*seq, books=None): return phrase(list(seq), books)
def S_(*x): return sorted(x)
def U(*toks, books=None): return sorted(set(s for t in toks for s in hits(t, books, True)))
def LEMT(lem, books=None): return [(f'{b} {c}:{v}', x, m) for (b, c, v), ws in by.items() if (books is None or b in books) for (x, m), l in zip(ws, byl[(b, c, v)]) if l == lem]
def LEMV(lem, books=None): return sorted({s for s, _, _ in LEMT(lem, books)})
def lemma_of(b, c, v, tok): return [l for (x, m), l in zip(by[(b, c, v)], byl[(b, c, v)]) if x == tok]
def W13(v): return words('Deut', 13, v)
def PT(b, c, v, tok): return [NF(x) for x in byp[(b, c, v)] if plain(x) == tok]
def SEAT(s): b, cv = s.split(); c, v = map(int, cv.split(':')); return (b, c, v)
def DIFF(a, b_):
    import difflib
    A, B = words(*a), words(*b_)
    return [(op, A[i1:i2], B[j1:j2]) for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, A, B).get_opcodes() if op != 'equal']
def SHARED(a, b_):
    import difflib
    A, B = words(*a), words(*b_)
    m = difflib.SequenceMatcher(None, A, B).find_longest_match(0, len(A), 0, len(B))
    return A[m.a:m.a + m.size]
def SHN(a, b_):
    import difflib
    A, B = words(*a), words(*b_)
    return sum(i2 - i1 for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, A, B).get_opcodes() if op == 'equal')
def LEN(b, c, v): return len(words(b, c, v))
def verse_text(ch, vs, book='Deut'): return ' '.join(words(book, ch, vs))
D13 = lambda v: ('Deut', 13, v)
NEG = ('לא', 'ולא')   # (not; and not)
NAME = ('יהוה', 'ליהוה', 'ויהוה', 'ביהוה', 'מיהוה')   # (the LORD; to the LORD; and the LORD; in the LORD; from the LORD)
import difflib
def SH(a, b_): return sum(s for _, _, s in difflib.SequenceMatcher(a=words(*a), b=words(*b_)).get_matching_blocks())
NV = len({v for (b, c, v) in by if b == 'Deut' and c == 13}); assert NV == 19, NV   # nineteen verses in the DB's numbering (the English's 12:32 the Hebrew's 13:1)

P_ = []   # the provenance trail of the case being run
def ink(ref, note):  P_.append(('INK',  'Deut %s — %s' % (ref, note) if not ref[:1].isupper() else '%s — %s' % (ref, note)))
def move(src, note): P_.append(('MOVE', '%s — %s' % (src, note)))
def dat(note):       P_.append(('DATA', note))
def hyp(note):       P_.append(('HYP',  note))     # THE LINK REVIEW LAW: a hypothesis — no teacher; counted apart, never as compiled
def out(verdict, effects):
    """verdict + registry-validated effects (the engine contract)"""
    FX.validate([e for e in effects if e != FX.NONE])
    return verdict, effects, list(P_)

# ---- THE INK, computed (the parser and the tokens; the reading's facts the expectations — every assert PROVEN at the reading, ch13_ink.py — COPIED from the reading's instrument by content markers in three blocks; the store-bound asserts left to the reading) ----
SPAN = [(13, v) for v in range(1, 20)]
def MARKS(c, v): return [t for t in verse_words('Deut', c, v) if t[-1] in '#~^%@|*']
def N(b, c, v): return ink_numbers(verse_words(b, c, v))
NUMS = {v: ink_numbers(verse_words('Deut', 13, v)) for v in range(1, 20)}
ORDS = {v: ink_ordinals(verse_words('Deut', 13, v)) for v in range(1, 20)}
PARSED = {(13, v): n for v, n in NUMS.items() if n}
KINNUM = {k: ink_numbers(verse_words(*k)) for k in [('Deut', 17, 6), ('Deut', 19, 15), ('Deut', 17, 7), ('Deut', 17, 2), ('Deut', 12, 14), ('Lev', 24, 16), ('Exod', 22, 19)]}
TOKN = sum(len(W13(v)) for v in range(1, 20)); LETN = sum(len(x) for v in range(1, 20) for x in W13(v))
print('THE INK (printed before it is asserted): PARSED %s, ORDS %s, MARKS %s, TOKN %d, LETN %d, KINNUM %s' % (PARSED, {v: o for v, o in ORDS.items() if o}, {v: MARKS(13, v) for v in range(1, 20) if MARKS(13, v)}, TOKN, LETN, KINNUM))
assert PARSED == {(13, 13): [1]} and all(o == [] for o in ORDS.values()) and not any(MARKS(13, v) for v in range(1, 20)) and TOKN == 328 and NUMS[18] == [], (PARSED, ORDS, TOKN)   # ONE NUMBER VERSE (13:13 "in one of your cities" [1]), no ordinal, NO starred token; 328 tokens (measured at the reading); 13:18's "swore" no number
assert KINNUM == {('Deut', 17, 6): [2, 3, 1], ('Deut', 19, 15): [1, 2, 3], ('Deut', 17, 7): [], ('Deut', 17, 2): [1], ('Deut', 12, 14): [1], ('Lev', 24, 16): [], ('Exod', 22, 19): []}, KINNUM   # the reading's parser facts on the kin
# THE KIN FOUND BY COMPUTATION (the measure's A section, recomputed here so the asserts read the same instrument): the shared distinct tokens outside the stop list, the top eight, the three closest re-scored in order
STOP = set(('את ואת אשר כל וכל על ועל אל ואל '   # (the object marker, and-it, which, all, on, to — the particles)
            'לא ולא כי אם יהוה אלהיך אלהיכם '   # (not, for, if; the LORD, your God)
            'לך לכם בו שם שמה גם מן ממך עד '   # (to you, in it, there, also, from, until)
            'הוא היא אתם אתה אנכי אני לו לה '   # (he, she, you, I, to him, to her)
            'בכל כאשר כן הימים היום אלה האלה '   # (in all, as, so, the days, today, these)
            'בארץ הארץ אשר ואם או פן ופן').split())   # (in the land, the land, which, and if, or, lest) — the stopword set glossed piece by piece (the lint's ninety-character window)
ORD = {k: i for i, k in enumerate(by)}
TOK = {k: set(words(*k)) - STOP for k in by}
KINC = {}
for _v in range(1, NV + 1):
    _me = D13(_v); _t = TOK[_me]
    _sc = sorted(((len(_t & TOK[k]), k) for k in by if k != _me and len(_t & TOK[k]) >= 2), key=lambda x: (-x[0], ORD[x[1]]))[:8]
    KINC[_v] = [(f'{k[0]} {k[1]}:{k[2]}', n, SH(_me, k) if i < 3 else None) for i, (n, k) in enumerate(_sc)]
# ---- THE PHRASES, censused over the whole DB (the measure's B print) ----
DT = ('Deut',)
assert P('את', 'כל', 'הדבר', 'אשר', 'אנכי', 'מצוה') == ['Deut 13:1'] and P('כל', 'המצוה', 'אשר', 'אנכי', 'מצוך', books=DT) == ['Deut 11:8', 'Deut 8:1'] and P('תשמרו', 'לעשות') == ['Deut 13:1', 'Deut 24:8'] and SH(D13(1), ('Deut', 4, 2)) == 7   # THE HEADER — "all the word that I command you" ONE seat; 4:2's plural "you shall not add … nor take" its twin (seven tokens in order)
assert P('לא', 'תסף', 'עליו', 'ולא', 'תגרע', 'ממנו') == ['Deut 13:1'] and P('לא', 'תספו') == ['Deut 4:2'] and P('ולא', 'תגרעו') == ['Deut 4:2'] and [(s, x, m) for s, x, m in LEMT('3254', books=DT) if s.startswith('Deut 13:')] == [('Deut 13:1', 'תסף', 'HVhi2ms'), ('Deut 13:12', 'יוספו', 'HVhi3mp')] and len(LEMT('1639')) == 22 and [s for s, _, _ in LEMT('1639', books=T)] == ['Deut 4:2', 'Deut 13:1', 'Exod 5:8', 'Exod 5:11', 'Exod 5:19', 'Exod 21:10', 'Lev 27:18', 'Num 9:7', 'Num 27:4', 'Num 36:3', 'Num 36:3', 'Num 36:4']   # THE ROOT OF ADDING TWICE — to the word (13:1) and to the deed (13:12 "they shall not do again"); "take away" the Torah's twelve, the law's two
assert P('ולא', 'יוספו', 'לעשות') == ['Deut 13:12'] and P('ולא', 'יספו', 'לעשות') == ['Deut 19:20'] and P('כדבר', 'הרע', 'הזה') == ['Deut 13:12', 'Deut 19:20'] and P('ישמעו', 'ויראו') == ['Deut 17:13', 'Deut 19:20', 'Deut 21:21'] and P('ישמעו', 'ויראון') == ['Deut 13:12'] and P('וכל', 'ישראל', 'ישמעו', 'ויראון') == ['Deut 13:12'] and KINC[12][:1] == [('Deut 19:20', 6, 7)]   # "ALL ISRAEL SHALL HEAR AND FEAR" — the formula's four seats in the Bible, 13:12 THE FIRST and the one with the paragogic nun (19:20 the false witness's, 17:13 the rebellious elder's, 21:21 the rebellious son's)
assert P('כי', 'יקום', 'בקרבך', 'נביא') == ['Deut 13:2'] and P('נביא', 'מקרבך') == ['Deut 18:15'] and P('חלם', 'חלום') == ['Deut 13:2'] and U('חלום', 'החלום', 'חלם', 'חולם', 'חלמות', 'החלמות', 'חלמת', books=DT) == ['Deut 13:2', 'Deut 13:4', 'Deut 13:6'] and len(LEMT('2492 b')) == 28 and [(s, x) for s, x, _ in LEMT('2492 b', books=DT)] == [('Deut 13:2', 'חלם'), ('Deut 13:4', 'חולם'), ('Deut 13:6', 'חלם')]   # THE DREAMER — the noun's and the verb's only seats in the book are the chapter's three (Joseph's, Pharaoh's and Jeremiah's dreamers the kin; Numbers 12:6 the dream as God's speech)
assert P('אות', 'או', 'מופת') == ['Deut 13:2'] and P('האות', 'והמופת') == ['Deut 13:3'] and P('ובא', 'האות') == ['Deut 13:3'] and len(U('מופת', 'ומופת', 'מופתים', 'ומופתים', 'מפתים', 'ומפתים', 'המופת', 'והמופת', 'המפתים', 'והמפתים', 'ומפתיו', 'ומופתיו', 'מפתי', 'למופת', 'מופתי', 'ומפתי', 'מופתו')) == 25 and KINC[2] == [('1Kgs 13:3', 2, 2)]   # THE SIGN OR THE WONDER — "or" the chapter's; the one verse of the Bible sharing two tokens with 13:2 is the man of God's sign at Jeroboam's altar (1 Kings 13:3)
assert P('נלכה', 'אחרי', 'אלהים', 'אחרים') == ['Deut 13:3'] and P('נלכה', 'ונעבדה', 'אלהים', 'אחרים') == ['Deut 13:14', 'Deut 13:7'] and U('נלכה', books=T) == ['Deut 13:14', 'Deut 13:3', 'Deut 13:7', 'Exod 3:18', 'Exod 5:17', 'Exod 5:3', 'Exod 5:8', 'Gen 22:5', 'Gen 37:17'] and len([s for s in P('אלהים', 'אחרים') if s.startswith('Deut 13:')]) == 3 and len(P('אלהים', 'אחרים', books=DT)) == 17 and len(P('אלהים', 'אחרים')) == 46   # THE SEDUCER'S FORMULA — "let us go" the cohortative at the three seducers (13:3, 7, 14; Moses' "let us go" to Pharaoh and Abraham's to the lads its Torah kin); "other gods" three in the chapter, seventeen in the book, forty-six in the Bible
assert P('אלהים', 'אחרים', 'אשר', 'לא', 'ידעת') == ['Deut 13:7', 'Deut 28:64'] and P('אלהים', 'אחרים', 'אשר', 'לא', 'ידעתם') == ['Deut 11:28', 'Deut 13:14', 'Deut 13:3', 'Jer 7:9'] and P('אשר', 'לא', 'ידעת', 'אתה', 'ואבתיך') == ['Deut 13:7', 'Deut 28:36', 'Deut 28:64'] and U('ונעבדם') == ['Deut 13:3'] and P('הנביא', 'ההוא') == ['Deut 13:4', 'Deut 18:20', 'Ezek 14:9'] and P('חלם', 'החלום', 'ההוא') == ['Deut 13:6']   # "WHICH YOU HAVE NOT KNOWN" — 11:28's clause said back three times; "you and your fathers" the exile's (28:36, 64)
assert P('כי', 'מנסה', 'יהוה', 'אלהיכם', 'אתכם') == ['Deut 13:4'] and len(LEMT('5254')) == 36 and [(s, x) for s, x, _ in LEMT('5254', books=DT)] == [('Deut 4:34', 'הנסה'), ('Deut 6:16', 'תנסו'), ('Deut 6:16', 'נסיתם'), ('Deut 8:2', 'לנסתך'), ('Deut 8:16', 'נסתך'), ('Deut 13:4', 'מנסה'), ('Deut 28:56', 'נסתה'), ('Deut 33:8', 'נסיתו')] and P('לדעת', 'הישכם') == ['Deut 13:4'] and len(U('הישכם', 'הישך', 'היש')) == 20 and 'נסה' in words('Gen', 22, 1)   # THE TESTING — the verb's eight seats in the book, the chapter's the participle "is testing"; 8:2 and 8:16 the wilderness's, Genesis 22:1 the first
assert P('בכל', 'לבבכם', 'ובכל', 'נפשכם') == ['Deut 11:13', 'Deut 13:4', 'Josh 22:5', 'Josh 23:14'] and len(P('בכל', 'לבבך', 'ובכל', 'נפשך')) == 7 and P('אהבים', 'את', 'יהוה') == ['Deut 13:4'] and KINC[4][:2] == [('Deut 11:13', 4, 9), ('Josh 22:5', 4, 8)]   # "WITH ALL YOUR HEART AND SOUL" plural — 11:13's clause (the second paragraph's), the closest kin nine tokens in order; the participle "who love the LORD" ONE seat
assert P('אחרי', 'יהוה', 'אלהיכם', 'תלכו') == ['Deut 13:5'] and P('ואתו', 'תיראו') == ['Deut 13:5'] and P('ואת', 'מצותיו', 'תשמרו') == ['Deut 13:5'] and P('ובקלו', 'תשמעו') == ['Deut 13:5'] and P('ואתו', 'תעבדו') == ['Deut 13:5'] and [(s, x, m) for s, x, m in LEMT('1692', books=DT)] == [('Deut 10:20', 'תדבק', 'HVqi2ms'), ('Deut 11:22', 'ולדבקה', 'HC/R/Vqc'), ('Deut 13:5', 'תדבקון', 'HVqi2mp/Sn'), ('Deut 13:18', 'ידבק', 'HVqi3ms'), ('Deut 28:21', 'ידבק', 'HVhi3ms'), ('Deut 28:60', 'ודבקו', 'HC/Vqq3cp'), ('Deut 30:20', 'ולדבקה', 'HC/R/Vqc')] and SH(D13(5), ('Deut', 10, 20)) == 2 and SH(D13(5), ('Josh', 22, 5)) == 3   # THE SIX VERBS OF 13:5 — each clause ONE seat; 10:20's four (fear, serve, cleave, swear) and 6:13's three the kin; "cleave" seven in the book — the chapter's two: to Him (13:5) and the devoted thing to your hand (13:18)
assert P('ולא', 'ידבק', 'בידך', 'מאומה', 'מן', 'החרם') == ['Deut 13:18'] and words('Josh', 7, 1)[:6] == ['וימעלו', 'בני', 'ישראל', 'מעל', 'בחרם', 'ויקח'] and words('Josh', 7, 1)[-7:-5] == ['מן', 'החרם'] and words('Josh', 6, 18)[:6] == ['ורק', 'אתם', 'שמרו', 'מן', 'החרם', 'פן']   # THE DEVOTED THING IN THE HAND — Joshua's warning (6:18) and Achan's "of the devoted thing" (7:1) the run's own case of 13:18
assert [v for v in range(1, NV + 1) if 'יומת' in W13(v)] == [6] and P('כי', 'דבר', 'סרה', 'על', 'יהוה') == ['Deut 13:6'] and [(s, x) for s, x, _ in LEMT('5627')] == [('Deut 13:6', 'סרה'), ('Deut 19:16', 'סרה'), ('Isa 1:5', 'סרה'), ('Isa 14:6', 'סרה'), ('Isa 31:6', 'סרה'), ('Isa 59:13', 'וסרה'), ('Jer 28:16', 'סרה'), ('Jer 29:32', 'סרה')] and P('לענות', 'בו', 'סרה') == ['Deut 19:16']   # "REBELLION" — the noun's two Torah seats (13:6; 19:16 the false witness's, read by the prophet's at 189:1 with Jeremiah 28:16 — Hananiah the false prophet)
assert P('המוציא', 'אתכם', 'מארץ', 'מצרים', 'והפדך', 'מבית', 'עבדים') == ['Deut 13:6'] and U('והפדך', 'פדך', 'ופדך') == ['Deut 13:6', 'Job 5:20'] and [(s, x) for s, x, _ in LEMT('6299', books=DT)] == [('Deut 7:8', 'ויפדך'), ('Deut 9:26', 'פדית'), ('Deut 13:6', 'והפדך'), ('Deut 15:15', 'ויפדך'), ('Deut 21:8', 'פדית'), ('Deut 24:18', 'ויפדך')] and P('המוציאך', 'מארץ', 'מצרים', 'מבית', 'עבדים') == ['Deut 13:11', 'Deut 8:14'] and len(P('מבית', 'עבדים')) == 12 and SH(D13(11), ('Deut', 5, 6)) == 6 and KINC[6][:1] == [('Josh 24:17', 6, 9)]   # THE EXODUS FORMULA — with "who redeemed you" at 13:6 (the participle's one seat; the verb's six in the book), the Decalogue's preamble at 13:11 (six tokens in order with 5:6); Joshua's farewell the closest verse to 13:6
assert [(s, x) for s, x, _ in LEMT('5080', books=DT)] == [('Deut 4:19', 'ונדחת'), ('Deut 13:6', 'להדיחך'), ('Deut 13:11', 'להדיחך'), ('Deut 13:14', 'וידיחו'), ('Deut 19:5', 'ונדחה'), ('Deut 20:19', 'לנדח'), ('Deut 22:1', 'נדחים'), ('Deut 30:1', 'הדיחך'), ('Deut 30:4', 'נדחך'), ('Deut 30:17', 'ונדחת')] and len(LEMT('5080')) == 51 and P('להדיחך', 'מן', 'הדרך') == ['Deut 13:6'] and P('הדרך', 'אשר', 'צוך', 'יהוה', 'אלהיך') == ['Deut 13:6'] and P('הדרך', 'אשר', 'צוה', 'יהוה', 'אלהיכם') == ['Deut 5:33'] and P('להדיחך', 'מעל', 'יהוה') == ['Deut 13:11']   # THE CHAPTER'S VERB — "thrust away" three times (13:6, 11 the seducers' aim; 13:14 the city's, THE ONE NARRATIVE FORM); 4:19 the host's drawing and 30:17 the heart's the kin; the axe head, the felling and the strayed ox its other senses
assert P('ובערת', 'הרע', 'מקרבך') == ['Deut 13:6', 'Deut 17:7', 'Deut 19:19', 'Deut 21:21', 'Deut 22:21', 'Deut 22:24', 'Deut 24:7'] and P('ובערת', 'הרע') == ['Deut 13:6', 'Deut 17:12', 'Deut 17:7', 'Deut 19:19', 'Deut 21:21', 'Deut 22:21', 'Deut 22:22', 'Deut 22:24', 'Deut 24:7'] and P('ובערתם', 'הרע') == [] and [s for s, x, _ in LEMT('1197 a', books=DT) if x == 'ובערת'] == ['Deut 13:6', 'Deut 17:7', 'Deut 17:12', 'Deut 19:13', 'Deut 19:19', 'Deut 21:21', 'Deut 22:21', 'Deut 22:22', 'Deut 22:24', 'Deut 24:7']   # "AND YOU SHALL PURGE THE EVIL FROM YOUR MIDST" — NINE seats in the Bible, all in the book, 13:6 THE FIRST (seven "from your midst", two "from Israel"); "and you shall purge" ten with the innocent blood's (19:13, 21:9 the heifer)
assert P('כי', 'יסיתך', 'אחיך', 'בן', 'אמך') == ['Deut 13:7'] and [s for s, _, _ in LEMT('5496', books=T)] == ['Deut 13:7'] and len(LEMT('5496')) == 18 and P('אחיך', 'בן', 'אמך') == ['Deut 13:7'] and P('אשת', 'חיקך') == ['Deut 13:7'] and P('רעך', 'אשר', 'כנפשך') == ['Deut 13:7'] and U('כנפשך', 'כנפשו') == ['1Sam 18:1', '1Sam 18:3', 'Deut 13:7', 'Deut 23:25'] and 'הסתה' in words('1Kgs', 21, 25) and 'הסיתך' in words('1Sam', 26, 19)   # THE INCITER — "entice" the Torah's ONE token (eighteen in the Bible: Jezebel who incited Ahab, 87:1's citation; "if the LORD has incited you", 87:2's); "the wife of your bosom", "your friend who is as your own soul" one seat each (Jonathan's love the kin)
assert U('בסתר', books=DT) == ['Deut 13:7', 'Deut 27:15', 'Deut 27:24', 'Deut 28:57'] and P('אתה', 'ואבתיך') == ['Deut 13:7', 'Deut 28:36', 'Deut 28:64'] and P('מאלהי', 'העמים', 'אשר', 'סביבתיכם') == ['Deut 13:8'] and P('מאלהי', 'העמים', 'אשר', 'סביבותיכם') == ['Deut 6:14'] and P('הקרבים', 'אליך', 'או', 'הרחקים', 'ממך') == ['Deut 13:8'] and P('מקצה', 'הארץ', 'ועד', 'קצה', 'הארץ') == ['Deut 13:8', 'Deut 28:64', 'Jer 25:33'] and KINC[8][:1] == [('Deut 28:64', 4, 6)]   # "THE GODS OF THE PEOPLES ROUND ABOUT YOU" — 6:14's clause with the defective spelling here; "from one end of the earth to the other" 28:64's exile; "in secret" the curses' word (27:15, 24)
assert P('לא', 'תאבה', 'לו') == ['Deut 13:9'] and len(LEMT('14', books=DT)) == 7 and P('ולא', 'תשמע', 'אליו') == ['Deut 13:9'] and P('לא', 'תחוס', 'עינך') == ['Deut 19:13', 'Deut 25:12'] and P('ולא', 'תחוס', 'עינך') == ['Deut 13:9', 'Deut 19:21'] and [(s, x) for s, x, _ in LEMT('2550', books=T)] == [('Deut 13:9', 'תחמל'), ('Exod 2:6', 'ותחמל')] and P('ולא', 'תכסה', 'עליו') == ['Deut 13:9'] and 'תחמל' in words('1Sam', 15, 3) and KINC[9][:2] == [('1Kgs 20:8', 3, 1), ('Deut 19:13', 3, 4)]   # THE FIVE PROHIBITIONS — "your eye shall not pity" the book's five with 7:16's defective form (the manslayer, the false witness, the woman's hand); "spare" the Torah's two — Pharaoh's daughter spared the child, Saul told not to spare Amalek with the chapter's word; "consent" the book's seven
assert P('הרג', 'תהרגנו') == ['Deut 13:10'] and P('ידך', 'תהיה', 'בו', 'בראשונה') == ['Deut 13:10'] and P('תהיה', 'בו', 'בראשנה', 'להמיתו') == ['Deut 17:7'] and P('ויד', 'כל', 'העם') == ['Deut 13:10', 'Deut 17:7'] and U('בראשונה', 'בראשנה', books=T) == ['Deut 13:10', 'Deut 17:7', 'Gen 13:4', 'Num 10:13', 'Num 10:14'] and U('באחרנה', 'באחרונה', books=T) == ['Deut 13:10', 'Deut 17:7'] and KINC[10][:1] == [('Deut 17:7', 5, 7)] and words('Deut', 17, 7)[:2] == ['יד', 'העדים']   # THE HAND FIRST — 17:7's "the hand of the witnesses" said here of the incited: "your hand" (seven tokens in order; "afterward" the Torah's two seats, both this clause's); "kill, you shall kill him" ONE
assert P('וסקלתו', 'באבנים', 'ומת') == ['Deut 13:11'] and P('באבנים', 'ומת') == ['Deut 13:11', 'Deut 21:21'] and P('באבנים', 'ומתו') == ['Deut 17:5', 'Deut 22:24'] and [s for s, _, _ in LEMT('5619', books=DT)] == ['Deut 13:11', 'Deut 17:5', 'Deut 22:21', 'Deut 22:24'] and [s for s, _, _ in LEMT('7275', books=DT)] == ['Deut 21:21'] and [s for s, _, _ in LEMT('7275', books=('Lev', 'Num'))] == ['Lev 20:2', 'Lev 20:27', 'Lev 24:14', 'Lev 24:16', 'Lev 24:16', 'Lev 24:23', 'Num 14:10', 'Num 15:35', 'Num 15:36'] and P('כי', 'בקש', 'להדיחך') == ['Deut 13:11'] and KINC[11][:3] == [('Deut 8:14', 5, 7), ('Deut 13:6', 5, 4), ('Deut 5:6', 4, 6)]   # TWO VERBS OF STONING — Deuteronomy's (סקל — "stone") at 13:11, 17:5, 22:21, 24 against Leviticus's and Numbers' (רגם — "stone") at Molech's giver, the necromancer, the blasphemer and the wood-gatherer; 21:21 alone holds both
assert P('כי', 'תשמע', 'באחת', 'עריך') == ['Deut 13:13'] and P('באחד', 'שעריך') == ['Deut 15:7', 'Deut 16:5', 'Deut 17:2', 'Deut 23:17'] and P('לשבת', 'שם', books=T) == ['Deut 13:13'] and [v for v in range(1, NV + 1) if 'לאמר' in W13(v)] == [3, 7, 13, 14] and len(U('לאמר', books=DT)) == 40 and KINC[13][0][1] == 2   # THE NUMBER VERSE — "in one of your cities" ONE (the gates' form four); "to dwell there" the Torah's one seat; "saying" the seducers' four; no verse of the Bible shares three non-stop tokens with 13:13
assert P('יצאו', 'אנשים', 'בני', 'בליעל') == ['Deut 13:14'] and P('בני', 'בליעל') == ['1Kgs 21:10', '1Kgs 21:13', '1Sam 2:12', '2Chr 13:7', 'Deut 13:14', 'Judg 19:22', 'Judg 20:13'] and len(LEMT('1100')) == 27 and [s for s, _, _ in LEMT('1100', books=T)] == ['Deut 13:14', 'Deut 15:9'] and P('וידיחו', 'את', 'ישבי', 'עירם') == ['Deut 13:14'] and P('ישבי', 'העיר', 'ההוא') == ['Deut 13:16'] and KINC[14][:1] == [('1Kgs 21:10', 5, 5)]   # SONS OF BELIAL — the Torah's two (13:14; 15:9's "a word of Belial" in the heart, 117:3's analogy); Naboth's false witnesses the closest verse in the Bible (1 Kings 21:10), Gibeah's men and Eli's sons the others
assert P('ודרשת', 'וחקרת', 'ושאלת', 'היטב') == ['Deut 13:15'] and U('היטב', books=DT) == ['Deut 13:15', 'Deut 17:4', 'Deut 19:18', 'Deut 27:8', 'Deut 9:21'] and P('והנה', 'אמת', 'נכון', 'הדבר') == ['Deut 13:15', 'Deut 17:4'] and P('נעשתה', 'התועבה', 'הזאת', 'בקרבך') == ['Deut 13:15'] and P('נעשתה', 'התועבה', 'הזאת') == ['Deut 13:15', 'Deut 17:4'] and KINC[15][:1] == [('Deut 17:4', 9, 9)] and words('Deut', 17, 4)[-1] == 'בישראל'   # THE INQUIRY — "diligently" five seats in the book (the calf ground "well" at 9:21 and the stones' plaster at 27:8 among them; 149:1 and 190:7's analogy on the word — Mishnah Sanhedrin 5:1's seven investigations); 17:4 the twin (nine of twelve tokens in order; "in Israel" for "in your midst")
assert P('הכה', 'תכה') == ['Deut 13:16'] and P('לפי', 'חרב', books=T) == ['Deut 13:16', 'Deut 20:13', 'Exod 17:13', 'Gen 34:26', 'Num 21:24'] and len(P('לפי', 'חרב')) == 32 and P('החרם', 'אתה', 'ואת', 'כל', 'אשר', 'בה') == ['Deut 13:16'] and [(s, x) for s, x, _ in LEMT('2763 a', books=T)] == [('Deut 2:34', 'ונחרם'), ('Deut 3:6', 'ונחרם'), ('Deut 3:6', 'החרם'), ('Deut 7:2', 'החרם'), ('Deut 7:2', 'תחרים'), ('Deut 13:16', 'החרם'), ('Deut 20:17', 'החרם'), ('Deut 20:17', 'תחרימם'), ('Exod 22:19', 'יחרם'), ('Lev 27:28', 'יחרם'), ('Lev 27:29', 'יחרם'), ('Num 21:2', 'והחרמתי'), ('Num 21:3', 'ויחרם')] and [s for s, _, _ in LEMT('2764 a', books=T)] == ['Deut 7:26', 'Deut 7:26', 'Deut 13:18', 'Lev 27:21', 'Lev 27:28', 'Lev 27:28', 'Lev 27:29', 'Num 18:14'] and KINC[16][:1] == [('Josh 10:28', 5, 8)]   # THE SWORD AND THE BAN — "smite, you shall smite" ONE; "with the edge of the sword" the Torah's five (Amalek's, Shechem's, Sihon's); the ban's verb thirteen in the Torah (Exodus 22:19's sacrificer to other gods the first, "shall be devoted"), the noun eight (7:26's house, 13:18's hand); Joshua's Makkedah the closest verse (eight tokens in order)
assert P('ואת', 'כל', 'שללה', 'תקבץ') == ['Deut 13:17'] and U('שללה') == ['Deut 13:17', 'Deut 20:14', 'Ezek 29:19', 'Josh 8:2'] and [(s, x) for s, x, _ in LEMT('7339', books=T)] == [('Deut 13:17', 'רחבה'), ('Gen 19:2', 'ברחוב')] and P('כליל', 'ליהוה') == ['1Sam 7:9', 'Deut 13:17'] and len(LEMT('3632')) == 15 and [s for s, _, _ in LEMT('3632', books=T)] == ['Deut 13:17', 'Deut 33:10', 'Exod 28:31', 'Exod 39:22', 'Lev 6:15', 'Lev 6:16', 'Num 4:6'] and P('תל', 'עולם') == ['Deut 13:17', 'Josh 8:28'] and P('לא', 'תבנה', 'עוד') == ['Deut 13:17', 'Ezek 26:14'] and words('Josh', 8, 28)[:6] == ['וישרף', 'יהושע', 'את', 'העי', 'וישימה', 'תל'] and KINC[17][:1] == [('Ezek 5:4', 4, 5)]   # THE WHOLE OFFERING AND THE HEAP — "wholly to the LORD" 13:17 and Samuel's lamb (1 Samuel 7:9); the word the priest's meal offering's (Leviticus 6:15-16 "wholly burned") and the robe's "all of blue"; "its street" the Torah's one (Lot's square the other); "a heap forever" Ai's (Joshua 8:28 — the run's case); "shall not be built again" Tyre's (Ezekiel 26:14); Ai's spoil taken (8:2) against the chapter's burned
assert P('למען', 'ישוב', 'יהוה', 'מחרון', 'אפו') == ['Deut 13:18'] and P('מחרון', 'אפו') == ['2Kgs 23:26', 'Deut 13:18', 'Jonah 3:9', 'Josh 7:26'] and P('מחרון', 'אפך') == ['Exod 32:12', 'Ps 85:4'] and len(P('חרון', 'אף', 'יהוה')) == 7 and words('Josh', 7, 26)[8:12] == ['וישב', 'יהוה', 'מחרון', 'אפו'] and words('Num', 25, 4)[-5:] == ['וישב', 'חרון', 'אף', 'יהוה', 'מישראל'] and 'מחרון' in words('Exod', 32, 12)   # THE FIERCE ANGER TURNED — Achan's valley (Joshua 7:26) says the chapter's words back over the devoted thing; Peor's (Numbers 25:4) and Moses' at the calf (Exodus 32:12) the kin
assert P('ונתן', 'לך', 'רחמים', 'ורחמך', 'והרבך') == ['Deut 13:18'] and P('לכם', 'רחמים') == ['Gen 43:14', 'Jer 42:12'] and [(s, x) for s, x, _ in LEMT('7355', books=DT)] == [('Deut 13:18', 'ורחמך'), ('Deut 30:3', 'ורחמך')] and U('והרבך') == ['Deut 13:18', 'Deut 30:5', 'Deut 7:13'] and P('כאשר', 'נשבע', 'לאבתיך', books=DT) == ['Deut 13:18', 'Deut 19:8'] and len(P('כאשר', 'נשבע', books=DT)) == 4 and len(P('אשר', 'נשבע', 'לאבתיך', books=DT)) == 4 and KINC[18][:3] == [('Deut 6:18', 3, 3), ('Deut 7:13', 3, 3), ('Deut 8:18', 3, 3)]   # THE MERCY AND THE OATH — "give you mercy" Jacob's word for the brothers before Joseph (Genesis 43:14); "and have mercy on you" 13:18 and the return's (30:3); "AS HE SWORE TO YOUR FATHERS" the AS_WHEN form, 13:18 and 19:8 (the border enlarged) — a run citation of the oath for the compile's census
assert P('כי', 'תשמע', 'בקול', 'יהוה', 'אלהיך') == ['Deut 13:19', 'Deut 28:2', 'Deut 30:10'] and P('לשמר', 'את', 'כל', 'מצותיו', 'אשר', 'אנכי', 'מצוך', 'היום') == ['Deut 13:19'] and P('לעשות', 'הישר', 'בעיני', 'יהוה') == ['1Kgs 22:43', '2Chr 20:32', 'Deut 13:19'] and len(P('הישר', 'בעיני', 'יהוה', books=DT)) == 3 and len(P('הישר', 'בעיני', 'יהוה')) == 21 and KINC[19][:3] == [('Deut 28:1', 6, 14), ('Deut 28:15', 6, 12), ('Deut 15:5', 5, 11)] and len(P('אשר', 'אנכי', 'מצוך', 'היום', books=DT)) == 18   # THE FOOTER — "when you hearken to the voice of the LORD your God" the blessing's and the curse's opening (28:1, 28:15 — fourteen and twelve tokens in order), "to do the right in the eyes of the LORD" Jehoshaphat's measure (1 Kings 22:43; the Kings' phrase twenty-one in the Bible, three in the book)
assert [s for s, _, _ in LEMT('8441', books=DT) if s.startswith('Deut 13:')] == ['Deut 13:15'] and [v for v in range(1, NV + 1) if 'בקרבך' in W13(v)] == [2, 12, 15] and len(U('בקרבך', books=DT)) == 11 and [v for v in range(1, NV + 1) if 'מקרבך' in W13(v)] == [6, 14] and [(v, x) for v in range(1, NV + 1) for x in W13(v) if x in ('הרע', 'רע', 'הרעה')] == [(6, 'הרע'), (12, 'הרע')] and [v for v in range(1, NV + 1) if 'הדרך' in W13(v)] == [6]
assert [(v, x, m) for v in range(1, NV + 1) for x, m in by[('Deut', 13, v)] if m and re.match(r'^H(?:C/)?V.a$', m)] == [(10, 'הרג', 'HVqa'), (15, 'היטב', 'HVha'), (16, 'הכה', 'HVha'), (16, 'החרם', 'HVha')] and [v for v in range(1, NV + 1) if W13(v)[0] == 'כי'] == [2, 7, 10, 13, 19] and sum(1 for v in range(1, NV + 1) for x in W13(v) if x == 'או') == 9 and {v: W13(v).count('או') for v in range(1, NV + 1) if 'או' in W13(v)} == {2: 2, 4: 1, 6: 1, 7: 4, 8: 1}   # FOUR INFINITIVE ABSOLUTES (the design's count was three — "diligently" is one by its morph); three cases opened by "when" (2, 7, 13) and "for" at 10 and 19; "or" nine, four in the inciters' list
assert {v: sum(1 for x in W13(v) if x == 'יהוה') for v in range(1, NV + 1) if 'יהוה' in W13(v)} == {4: 2, 5: 1, 6: 2, 11: 1, 13: 1, 18: 1, 19: 2} and sum(1 for v in range(1, NV + 1) for x in W13(v) if x == 'יהוה') == 10 and [v for v in range(1, NV + 1) if any(W13(v)[i:i + 2] == ['יהוה', 'אלהיך'] for i in range(len(W13(v)) - 1))] == [6, 11, 13, 19] and [v for v in range(1, NV + 1) if any(W13(v)[i:i + 2] == ['יהוה', 'אלהיכם'] for i in range(len(W13(v)) - 1))] == [4, 5, 6] and [v for v in range(1, NV + 1) if 'ליהוה' in W13(v)] == [17]
assert [(v, x) for v in range(1, NV + 1) for x, m in by[('Deut', 13, v)] if m and m.startswith('HNp')] == [(4, 'יהוה'), (4, 'יהוה'), (5, 'יהוה'), (6, 'יהוה'), (6, 'מצרים'), (6, 'יהוה'), (11, 'יהוה'), (11, 'מצרים'), (12, 'ישראל'), (13, 'יהוה'), (18, 'יהוה'), (19, 'יהוה'), (19, 'יהוה')] and [(v, x) for v in range(1, NV + 1) for x, m in by[('Deut', 13, v)] if m and 'Np' in m and not m.startswith('HNp') and m != 'HR/Np'] == [(15, 'נעשתה'), (18, 'נשבע')]   # THE NAME ten bare tokens and "to the LORD" once; Israel named ONCE (13:12), Egypt twice, Moses never; THE TAGGER'S SUBSTRING — the dump's name test matched two niphal perfects by the letters "Np" inside "VNp" (an instrument's slip, retyped as a prefix test)
assert (SH(D13(1), ('Deut', 4, 2)), SH(D13(1), ('Deut', 8, 1)), SH(D13(1), ('Deut', 12, 28))) == (7, 4, 4) and (SH(D13(19), ('Deut', 12, 25)), SH(D13(19), ('Deut', 12, 28)), SH(D13(19), ('Deut', 15, 5)), SH(D13(19), ('Deut', 28, 1))) == (4, 8, 11, 14)
# THE KIN FOUND BY COMPUTATION — the A print's closest verses asserted (the count of shared distinct tokens, the tokens in order); 13:3, 13:7, 13:14 each other's closest kin — the three seducers' one formula
assert KINC[1][:1] == [('Deut 4:2', 4, 7)] and KINC[3][:3] == [('Deut 13:14', 5, 7), ('Deut 11:28', 4, 7), ('Deut 13:7', 4, 7)] and KINC[7][:3] == [('Deut 13:14', 5, 7), ('Deut 13:3', 4, 7), ('Deut 28:36', 4, 6)] and KINC[5][:1] == [('1Kgs 1:6', 2, 1)]
# ---- THE REGISTER (the D print), computed on the morphology ----
NUM = {v: (sum(1 for _, m in by[('Deut', 13, v)] if m and '2mp' in m), sum(1 for _, m in by[('Deut', 13, v)] if m and '2ms' in m)) for v in range(1, NV + 1)}
assert NUM == {1: (2, 2), 2: (0, 2), 3: (0, 2), 4: (6, 1), 5: (7, 0), 6: (2, 6), 7: (0, 11), 8: (1, 2), 9: (0, 5), 10: (0, 2), 11: (0, 4), 12: (0, 1), 13: (0, 4), 14: (1, 1), 15: (0, 4), 16: (0, 1), 17: (0, 3), 18: (0, 5), 19: (0, 4)}, NUM
SG_ONLY = [v for v in range(1, NV + 1) if NUM[v][1] and not NUM[v][0]]; PL_ONLY = [v for v in range(1, NV + 1) if NUM[v][0] and not NUM[v][1]]; BOTH = [v for v in range(1, NV + 1) if NUM[v][0] and NUM[v][1]]; NEITHER = [v for v in range(1, NV + 1) if not NUM[v][0] and not NUM[v][1]]
assert SG_ONLY == [2, 3, 7, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19] and PL_ONLY == [5] and BOTH == [1, 4, 6, 8, 14] and NEITHER == []   # THE REGISTER: singular but for the prophet's case (13:4-6 plural and mixed — "the LORD your God is testing YOU (pl.)"; 13:5's six verbs all plural) and the header (13:1 both); 13:8's "round about you (pl.)"; 13:14's plural the seducers' own speech
CP1 = {v: [(x, m) for x, m in by[('Deut', 13, v)] if m and '1cp' in m] for v in range(1, NV + 1) if any(m and '1cp' in m for _, m in by[('Deut', 13, v)])}
assert CP1 == {3: [('נלכה', 'HVqh1cp'), ('ונעבדם', 'HC/VHi1cp/Sp3mp')], 7: [('נלכה', 'HVqh1cp'), ('ונעבדה', 'HC/Vqh1cp')], 14: [('נלכה', 'HVqh1cp'), ('ונעבדה', 'HC/Vqh1cp')]} and [(v, x) for v in range(1, NV + 1) for x, m in by[('Deut', 13, v)] if m and '1cs' in m] == [(1, 'אנכי'), (19, 'אנכי')]   # THE FIRST PERSON: the seducers' "let us go" (the cohortative) three times, "and let us serve" three — the only "we" in the chapter is the tempter's; Moses' "I" at the header and the footer
assert {v: [(x, m) for x, m in by[('Deut', 13, v)] if m and re.match(r'^HV.?.?v', m)] for v in range(1, NV + 1) if any(m and re.match(r'^HV.?.?v', m) for _, m in by[('Deut', 13, v)])} == {}   # NO IMPERATIVE in the chapter
WEQ = {v: [x for x, m in by[('Deut', 13, v)] if m and re.search(r'^HC/V.q', m)] for v in range(1, NV + 1) if any(m and re.search(r'^HC/V.q', m) for _, m in by[('Deut', 13, v)])}
assert WEQ == {2: ['ונתן'], 3: ['ובא'], 6: ['ובערת'], 11: ['וסקלתו', 'ומת'], 15: ['ודרשת', 'וחקרת', 'ושאלת'], 17: ['ושרפת', 'והיתה'], 18: ['ונתן', 'ורחמך', 'והרבך']} and sum(len(v) for v in WEQ.values()) == 13
WAYY = {v: [x for x, m in by[('Deut', 13, v)] if m and re.search(r'^HC/V.w', m)] for v in range(1, NV + 1) if any(m and re.search(r'^HC/V.w', m) for _, m in by[('Deut', 13, v)])}
assert WAYY == {14: ['וידיחו']}   # THE ONE NARRATIVE FORM — inside the third case's report ("men have gone out … and have drawn away")
PTC = {v: [(x, m) for x, m in by[('Deut', 13, v)] if m and re.search(r'^H(?:C/|R/|Td/|C/R/)?V.r', m)] for v in range(1, NV + 1) if any(m and re.search(r'^H(?:C/|R/|Td/|C/R/)?V.r', m) for _, m in by[('Deut', 13, v)])}
assert PTC == {1: [('מצוה', 'HVprmsa')], 2: [('חלם', 'HVqrmsc')], 4: [('חולם', 'HVqrmsc'), ('מנסה', 'HVprmsa'), ('אהבים', 'HVqrmpa')], 6: [('חלם', 'HVqrmsc'), ('המוציא', 'HTd/Vhrmsa')], 11: [('המוציאך', 'HTd/Vhrmsc/Sp2ms')], 13: [('נתן', 'HVqrmsa')], 14: [('ישבי', 'HVqrmpc')], 15: [('נכון', 'HVNrmsa')], 16: [('ישבי', 'HVqrmpc')], 19: [('מצוך', 'HVprmsc/Sp2ms')]} and sum(len(v) for v in PTC.values()) == 13
assert [(v, x) for v in range(1, NV + 1) for x, m in by[('Deut', 13, v)] if m and m.startswith('HTd/V') and 'r' in m[6:8]] == [(6, 'המוציא'), (11, 'המוציאך')]
PERF = {v: [(x, m) for x, m in by[('Deut', 13, v)] if m and re.match(r'^H(?:C/)?V.p', m)] for v in range(1, NV + 1) if any(m and re.match(r'^H(?:C/)?V.p', m) for _, m in by[('Deut', 13, v)])}
assert PERF == {3: [('דבר', 'HVpp3ms'), ('ידעתם', 'HVqp2ms/Sp3mp')], 6: [('דבר', 'HVpp3ms'), ('צוך', 'HVpp3ms/Sp2ms')], 7: [('ידעת', 'HVqp2ms')], 11: [('בקש', 'HVpp3ms')], 14: [('יצאו', 'HVqp3cp'), ('ידעתם', 'HVqp2mp')], 15: [('נעשתה', 'HVNp3fs')], 18: [('נשבע', 'HVNp3ms')]}
PROH = {v: [(by[('Deut', 13, v)][i + 1][0], by[('Deut', 13, v)][i + 1][1]) for i, (x, _) in enumerate(by[('Deut', 13, v)][:-1]) if x in ('לא', 'ולא') and by[('Deut', 13, v)][i + 1][1] and by[('Deut', 13, v)][i + 1][1].startswith('HV')] for v in range(1, NV + 1) if any(x in ('לא', 'ולא') for x, _ in by[('Deut', 13, v)])}
assert PROH == {1: [('תסף', 'HVhi2ms'), ('תגרע', 'HVqi2ms')], 3: [('ידעתם', 'HVqp2ms/Sp3mp')], 4: [('תשמע', 'HVqi2ms')], 7: [('ידעת', 'HVqp2ms')], 9: [('תאבה', 'HVqi2ms'), ('תשמע', 'HVqi2ms'), ('תחוס', 'HVqi3fs'), ('תחמל', 'HVqi2ms'), ('תכסה', 'HVpi2ms')], 12: [('יוספו', 'HVhi3mp')], 14: [('ידעתם', 'HVqp2mp')], 17: [('תבנה', 'HVNi3fs')], 18: [('ידבק', 'HVqi3ms')]}   # THE PROHIBITIONS: the second person's seven (1 twice, 4, 9 four) and the third person's four (the eye, the city, the people, the devoted thing); the "not" of "have not known" a perfect
assert {v: [x for x in W13(v) if x in ('לא', 'ולא')] for v in range(1, NV + 1) if any(x in ('לא', 'ולא') for x in W13(v))} == {1: ['לא', 'ולא'], 3: ['לא'], 4: ['לא'], 7: ['לא'], 9: ['לא', 'ולא', 'ולא', 'ולא', 'ולא'], 12: ['ולא'], 14: ['לא'], 17: ['לא'], 18: ['ולא']}
assert {f'13:{v}': [x for x in W13(v) if x in ('כי', 'אם', 'ואם', 'או', 'פן')] for v in range(1, NV + 1) if any(x in ('כי', 'אם', 'ואם', 'או', 'פן') for x in W13(v))} == {'13:2': ['כי', 'או', 'או'], '13:4': ['או', 'כי'], '13:6': ['או', 'כי'], '13:7': ['כי', 'או', 'או', 'או', 'או'], '13:8': ['או'], '13:10': ['כי'], '13:11': ['כי'], '13:13': ['כי'], '13:19': ['כי']}   # NO "if" (אם) IN THE CHAPTER — the three cases open on "when" (כי), the branches on "or"
assert [v for v in range(1, NV + 1) if any(W13(v)[i] in ('ויאמר', 'וידבר') and W13(v)[i + 1] == 'יהוה' for i in range(len(W13(v)) - 1))] == [] and {v: [x for x in W13(v) if x in ('למען', 'ולמען')] for v in range(1, NV + 1) if any(x in ('למען', 'ולמען') for x in W13(v))} == {18: ['למען']} and len(U('למען', 'ולמען', books=DT)) == 43
assert {v: len(W13(v)) for v in range(1, NV + 1)} == {1: 16, 2: 12, 3: 15, 4: 26, 5: 15, 6: 32, 7: 27, 8: 14, 9: 15, 10: 12, 11: 14, 12: 11, 13: 12, 14: 17, 15: 12, 16: 18, 17: 23, 18: 19, 19: 18} and sum(len(W13(v)) for v in range(1, NV + 1)) == 328 and sum(len(x) for v in range(1, NV + 1) for x in W13(v)) == 1269

# ---- THE COUNTER'S DAY AND THE FOUR PARAMETERS (a bare world on the exodus epoch; no clock walk this chapter — no marker, no stretch) ----
with contextlib.redirect_stdout(io.StringIO()):
    _WC = WE.World(era='the counter\'s day — chapter 13 on a bare world (the exodus epoch)', epoch='exodus')
_EX = _WC.clock.eras['exodus']
def DAY(y, m, d): return _WC.clock.day_in('exodus', y, m, d)
def DATE(day): return _EX.date(day)
COUNTER = DAY(40, 11, 1)
SIGNS = WE.CAL_PARAMS['the_signs_status']['value']; DEATH = WE.CAL_PARAMS['the_prophets_death']['value']; TIMING = WE.CAL_PARAMS['the_execution_timing']['value']; INQ = WE.CAL_PARAMS['the_inquiries']['value']   # THE FOUR PARAMETERS read (exercised_by seducers) — never a constant in the code: the disputes recorded, the table the cell reads as data
CLOCK = {'counter': DATE(COUNTER), 'signs_arms': sorted(SIGNS), 'death_arms': sorted(DEATH), 'timing_arms': sorted(TIMING), 'inquiry_keys': sorted(INQ), 'no_marker': True}
assert CLOCK == {'counter': (40, 11, 1), 'signs_arms': ['r_akiva', 'r_yosei_hagelili', 'the_hearing'], 'death_arms': ['stoning', 'strangling', 'the_default'], 'timing_arms': ['r_akiva', 'r_yehuda', 'the_formula'], 'inquiry_keys': ['diligently_free', 'the_clock_datum', 'the_congruence', 'the_examinations', 'the_order', 'the_seven', 'the_tolerance', 'the_voiding'], 'no_marker': True}, CLOCK
assert SIGNS['r_yosei_hagelili'].startswith('THE DOMINION') and SIGNS['r_akiva'].startswith('THE FALLEN PROPHET') and DEATH['strangling'].startswith('R. Shimon') and DEATH['the_default'].startswith("the answer sheet's") and TIMING['r_akiva'].startswith('KEPT TO THE FESTIVAL') and INQ['the_seven'].startswith('the seven-year cycle') and INQ['the_congruence'].startswith("'THE THING CERTAIN'"), (SIGNS, DEATH, TIMING, INQ)

# ---- THE ONE DATABASE SCANNED (the holes' ground — nothing names the false prophet's hearing, the LORD's testing, Israel's hearing and fearing, the condemned city's inquiry or the devoted thing's cleaving on Israel before this sitting; the three reused effects on israel_people alone) ----
_WDB = _os.path.join(_ROOT, 'World', 'journal', 'data', 'world.sqlite')
def ledger_scan(entity, pattern):
    """the effects on an entity in the one database whose name or value matches the pattern — None where the database is not built (a fresh clone before build_world)"""
    if not _os.path.exists(_WDB): return None
    c_ = sqlite3.connect('file:%s?mode=ro' % _WDB, uri=True)
    rx = re.compile(pattern, re.I)
    return sorted({e for e, v in c_.execute("SELECT DISTINCT effect, value FROM run_ledger WHERE entity=?", (entity,)).fetchall() if rx.search('%s %s' % (e, v if v is not None else ''))})
def effect_scan(effect):
    """the entities holding an effect in the one database — None where the database is not built"""
    if not _os.path.exists(_WDB): return None
    c_ = sqlite3.connect('file:%s?mode=ro' % _WDB, uri=True)
    return sorted({e for (e,) in c_.execute("SELECT DISTINCT entity FROM run_ledger WHERE effect=?", (effect,)).fetchall()})
OWN5 = ('false_prophet_hearing_barred', 'tested_by_the_lord', 'israel_hears_and_fears', 'condemned_city_inquiry_required', 'devoted_thing_cleaving_barred')
SEDUCER_WORDS = r"\b(false_prophet\w*|tested_by_the_lord|hears_and_fears|condemned_city\w*|devoted_thing\w*|evil_purged\w*|city_devoted)\b"
_ss = ledger_scan('israel_people', SEDUCER_WORDS); SEDUCERS_SCAN = None if _ss is None else [e for e in _ss if e not in OWN5]   # this sitting's own five excluded once the fold carries them
_rs = [effect_scan(e) for e in ('adding_barred', 'cleaving_commanded', 'pity_barred')]; REUSE_SCAN = None if any(r is None for r in _rs) else _rs
del _ss, _rs   # 9b's lesson: the raw scans are the database's state at import — the derived lists are equal on the cached and the full load
_FXV = yaml.safe_load(open(_os.path.join(HERE, 'effect_vocabulary.yaml'), encoding='utf-8'))['effects']
assert SEDUCERS_SCAN in ([], None), SEDUCERS_SCAN   # THE HOLES' GROUND — nothing on Israel named the five before this sitting (DE4)
assert REUSE_SCAN in ([['israel_people'], ['israel_people'], ['israel_people']], None), REUSE_SCAN   # the three reused effects on israel_people alone before the second entries
assert all(k in _FXV for k in OWN5 + ('evil_purged_from_the_midst', 'city_devoted')) and _FXV['adding_barred']['ledger_op'] == 'block' and all('THE DEUTERONOMY WALK 11b' in _FXV[e]['ink'] for e in ('adding_barred', 'cleaving_commanded', 'pity_barred')), 'the seven on the registry; the three reuses amended (add_types_ch13.py)'
INF_ABS = [(v, x) for v in range(1, 20) for x, m in by[('Deut', 13, v)] if m and re.match(r'^H(?:C/)?V.a$', m)]
STONING_DEUT = [s for s, _, _ in LEMT('5619', books=DT)]; STONING_LEVNUM = [s for s, _, _ in LEMT('7275', books=('Lev', 'Num'))]; STONING_BOTH = [s for s, _, _ in LEMT('7275', books=DT)]
PURGE_SEATS = P('ובערת', 'הרע')   # (and you shall purge the evil) — the formula's seats on the DB
assert len(INF_ABS) == 4 and STONING_DEUT == ['Deut 13:11', 'Deut 17:5', 'Deut 22:21', 'Deut 22:24'] and STONING_BOTH == ['Deut 21:21'] and len(STONING_LEVNUM) == 9 and len(PURGE_SEATS) == 9 and PURGE_SEATS[0] == 'Deut 13:6', (INF_ABS, STONING_DEUT, STONING_LEVNUM, STONING_BOTH, PURGE_SEATS)

# ---- THE CALLEES' FACTS (every edge live at the cells that consume them; the values asserted from the callees' own print — ch13_callees.out, read before any assert was typed; the older runners' cells take q and return a dict, the Deuteronomy runners' take (case, data) and return a tuple, temurah's takes a string, lev24's a default parameter — the print settled each form) ----
def V(x):
    """a cell's verdict whatever its form — the dict's v (or verdict), the tuple's first member"""
    return x.get('v', x.get('verdict', x)) if isinstance(x, dict) else (x[0] if isinstance(x, tuple) else x)
def FOUND(r):
    """a kin cell CALLED and answering — a tuple (verdict, effects, trail) whose verdict is in span, or a dict with its value"""
    if isinstance(r, dict): return 'v' in r or 'verdict' in r
    return isinstance(r, tuple) and isinstance(r[0], str) and not r[0].startswith('no verdict')
OH_ADD = OH.the_exhortation({'ask': 'add_nothing'}, OH.DATA); OH_DIM = OH.the_exhortation({'ask': 'diminish_nothing'}, OH.DATA); OH_BESIDE = OH.the_exhortation({'ask': 'add_beside'}, OH.DATA); OH_TIME = OH.the_exhortation({'ask': 'add_out_of_its_time'}, OH.DATA)
CH_OTHER = CH.the_second_word({'ask': 'no_other_gods'}, CH.DATA); CH_FIRST = CH.the_first_tablet({'ask': 'the_first_word'}, CH.DATA)
HI_TEST = HI.the_test_and_the_right({'ask': 'you_shall_not_test'}, HI.DATA); HI_RIGHT = HI.the_test_and_the_right({'ask': 'the_right_and_the_good'}, HI.DATA); HI_FEAR = HI.the_gift_and_the_warning({'ask': 'fear_serve_swear'}, HI.DATA); HI_GODS = HI.the_gift_and_the_warning({'ask': 'no_other_gods'}, HI.DATA)
SN_PITY = SN.because_you_hear({'ask': 'consume_no_pity'}, SN.DATA); SN_BAN = SN.the_seven_nations({'ask': 'the_ban'}, SN.DATA); SN_COND = SN.the_seven_nations({'ask': 'the_bans_condition'}, SN.DATA); SN_WOOD = SN.the_seven_nations({'ask': 'the_asherah_wood'}, SN.DATA)
SN_DEVLIKE = SN.the_images_and_the_devoted({'ask': 'devoted_like_it'}, SN.DATA); SN_HOUSE = SN.the_images_and_the_devoted({'ask': 'into_your_house'}, SN.DATA); SN_SNARED = SN.the_images_and_the_devoted({'ask': 'lest_snared'}, SN.DATA); SN_OATH = SN.the_holy_people({'ask': 'the_oath'}, SN.DATA); SN_REDEEMED = SN.the_holy_people({'ask': 'brought_out_redeemed'}, SN.DATA)
GL_TEST = GL.the_way_of_forty_years({'ask': 'the_test'}, GL.DATA); GL_HUMBLE = GL.the_way_of_forty_years({'ask': 'the_humbling'}, GL.DATA)
NR_INTER = NR.the_intercession({'ask': 'do_not_destroy_your_people'}, NR.DATA); NR_MERIT = NR.the_intercession({'ask': 'remember_your_servants'}, NR.DATA); NR_CALF = NR.the_calf_retold({'ask': 'gods_word_verbatim'}, NR.DATA)
ST_FOUR = ST.the_god_of_gods_and_the_stranger({'ask': 'fear_serve_cleave_swear'}, ST.DATA); ST_SCHOLARS = ST.the_god_of_gods_and_the_stranger({'ask': 'cleave_to_the_scholars'}, ST.DATA); ST_ATTR = ST.the_stations_and_the_death({'ask': 'walk_after_his_attributes'}, ST.DATA)
BC_CURSE = BC.the_blessing_and_the_curse({'ask': 'the_curse_if'}, BC.DATA); BC_HEARKEN = BC.the_second_paragraph({'ask': 'if_you_hearken'}, BC.DATA)
PN_ONE = PN.the_place_chosen({'ask': 'in_one_of_your_tribes'}, PN.DATA); PN_RIGHT = PN.the_border_enlarged_and_the_altar({'ask': 'the_good_and_the_right'}, PN.DATA); PN_INQ = PN.the_nations_cut_off_and_the_abomination({'ask': 'lest_you_inquire_after_their_gods'}, PN.DATA)
OR_IDOL = OR.capital('idolater_row'); OR_DEV = OR.capital('devoted_seats'); OR_SERV = OR.capital('service_architecture'); OR_ACQ = OR.courts('asymmetry'); OR_CIRC = OR.courts('circumstantial'); OR_DISS = OR.courts('dissenter'); OR_SIDE = OR.courts('begin_from_side'); OR_ENEMY = OR.courts('enemy_ox')
ER_FOUR = ER.calf('four_verbs'); ER_BOW = ER.calf('bow_likened'); ER_JOURN = ER.cloud('journeys'); ER_LIFT = ER.cloud('first_lifting')
SA_STONED = SA.census('stoned'); SA_STRANG = SA.census('strangled'); SA_BURNED = SA.census('burned'); SA_LASHES = SA.census('lashes'); SA_KARET = SA.census('karet_count'); SA_WHO = SA.molech('who_stones'); SA_FAM = SA.molech('family'); SA_CONC = SA.molech('concealed'); SA_WARNED = SA.frame('court_warned'); SA_KPERS = SA.frame('karet_persons'); SA_ORDERS = SA.severity('orders')
L24_TALION = L24.talion()
MK_STONES = MK.capital_procedure({'ask': 'stones_and_a_stone'}, MK.DATA); MK_STONING = MK.capital_procedure({'ask': 'stoning', 'died_at': 'the_first_stone'}, MK.DATA); MK_WARN = MK.capital_procedure({'ask': 'warning'}, MK.DATA); MK_VENUE = MK.capital_procedure({'ask': 'venue'}, MK.DATA); MK_HANG = MK.capital_procedure({'ask': 'hanging'}, MK.DATA); MK_MODE = MK.capital_procedure({'ask': 'mode'}, MK.DATA); MK_CUST = MK.capital_procedure({'ask': 'custody'}, MK.DATA); MK_BURIAL = MK.capital_procedure({'ask': 'burial'}, MK.DATA); MK_CONF = MK.capital_procedure({'ask': 'confession'}, MK.DATA)
TM_DEV = TM.devote('person'); TM_STATUS = TM.devote('status')
CK_CHEREM = CK.arad_and_the_serpent({'ask': 'cherem_law'}, CK.DATA); CK_HORMAH = CK.arad_and_the_serpent({'ask': 'hormah'}, CK.DATA)
BK_ANGER = BK.peor({'ask': 'anger_third'}, BK.DATA); BK_HANG = BK.peor({'ask': 'hang_before_the_sun'}, BK.DATA)
BH_DREAMS = BH.miriam({'ask': 'dreams'}, BH.DATA); BH_DIBBUR = BH.miriam({'ask': 'dibbur'}, BH.DATA); BH_CLOUD = BH.march({'ask': 'cloud_and_trumpets'}, BH.DATA); BH_ORDER = BH.march({'ask': 'order'}, BH.DATA)
MM_MORIAH = MM.moriah('test_verb_seats'); MM_TRIALS = MM.moriah('ten_trials_sheet')
HO_RULE = HO.conduct('great_rule'); HO_HATE = HO.conduct('hate'); HO_GRUDGE = HO.conduct('grudge'); HO_BLOOD = HO.conduct('blood', case='knows_testimony'); HO_SECRECY = HO.conduct('secrecy')
# the values asserted from the callees' print (ch13_callees.out — read before any assert was typed)
assert OH_ADD[0].startswith('you shall not add (4:2)') and OH_ADD[1] == ['accepted'] and OH_DIM[0].startswith('nor diminish (4:2)') and OH_BESIDE[0].startswith('an addition placed beside') and OH_TIME[1] == ['exempt'], (OH_ADD[:2], OH_DIM[0][:30], OH_BESIDE[0][:30], OH_TIME[1])
assert CH_OTHER[0].startswith('no other gods before me (5:7)') and CH_FIRST[0].startswith('the first word (5:6)') and HI_TEST[0].startswith('you shall not test (6:16)') and HI_RIGHT[0].startswith('the right and the good (6:18)') and HI_FEAR[0].startswith('fear, serve, swear (6:13)') and HI_GODS[0].startswith('no other gods (6:14)'), (CH_OTHER[0][:40], CH_FIRST[0][:30], HI_TEST[0][:30], HI_RIGHT[0][:30], HI_FEAR[0][:30], HI_GODS[0][:30])
assert SN_PITY[0].startswith('consume without pity (7:16)') and SN_WOOD[1] == ['lashes'] and SN_BAN[0].startswith('the ban (7:2)') and SN_COND[1] == ['exempt'] and SN_DEVLIKE[0].startswith('devoted like it (7:26)') and SN_HOUSE[0].startswith('the abomination into the house (7:26)') and SN_SNARED[0].startswith('lest snared (7:25)') and SN_OATH[0].startswith('the oath (7:8)') and SN_REDEEMED[0].startswith('brought out and redeemed (7:8)'), (SN_PITY[0][:30], SN_WOOD[1], SN_BAN[0][:20], SN_COND[1], SN_DEVLIKE[0][:30], SN_HOUSE[0][:40], SN_SNARED[0][:20], SN_OATH[0][:20], SN_REDEEMED[0][:30])
assert GL_TEST[0].startswith('the test (8:2)') and GL_HUMBLE[0].startswith('the humbling (8:2-3, 8:16)') and NR_INTER[0].startswith('do not destroy Your people (9:26)') and NR_MERIT[0].startswith('remember Your servants (9:27)') and NR_CALF[0].startswith("God's word (9:12-13)"), (GL_TEST[0][:30], GL_HUMBLE[0][:30], NR_INTER[0][:40], NR_MERIT[0][:40], NR_CALF[0][:30])
assert ST_FOUR[0].startswith('fear, serve, cleave, swear (10:20)') and ST_SCHOLARS[0].startswith('cleave to the scholars (Ketubot 111b:6-8)') and ST_ATTR[0].startswith('walk after His attributes (Sotah 14a:3-4)') and BC_CURSE[0].startswith('the curse if (11:28)') and BC_HEARKEN[0].startswith('if you hearken (11:13)'), (ST_FOUR[0][:40], ST_SCHOLARS[0][:40], ST_ATTR[0][:40], BC_CURSE[0][:30], BC_HEARKEN[0][:30])
assert PN_ONE[0].startswith('in one of your tribes (12:14)') and PN_RIGHT[0].startswith('the good and the right (12:28)') and PN_INQ[0].startswith('lest you inquire after their gods (12:30)'), (PN_ONE[0][:40], PN_RIGHT[0][:40], PN_INQ[0][:40])
assert OR_IDOL['v'] == 'serves_sacrifices_incense_libation_bows_accepts_says' and OR_DEV['v'] == 4 and OR_SERV['v'] == 'temple_services_for_any_idol' and OR_ACQ['v'] == 'acquit_by_one_convict_by_two' and OR_CIRC['v'] == 'no_execution_without_witnesses' and OR_DISS['v'] == 'bound_and_silent' and OR_SIDE['v'] == 'capital_from_the_side' and OR_ENEMY['v'] == 'return_it', (OR_IDOL['v'], OR_DEV['v'], OR_SERV['v'], OR_ACQ['v'], OR_CIRC['v'], OR_DISS['v'], OR_SIDE['v'], OR_ENEMY['v'])
assert len(ER_FOUR['v']) == 4 and ER_BOW['v'] == 'bowing_likened_to_sacrificing' and ER_JOURN['v'][0] == 6 and ER_LIFT['v'] == '20_iyar_year_2', (ER_FOUR['v'], ER_BOW['v'], ER_JOURN['v'][0], ER_LIFT['v'])
assert len(SA_STONED['v']) == 9 and SA_STRANG['v'] == ["a man's wife"] and SA_BURNED['v'] == ['a woman and her mother'] and len(SA_LASHES['v']) == 7 and SA_KARET['v'] == 20 and SA_WHO['v'] == 'the_people_of_the_land' and SA_FAM['v'] == 'afflictions_not_karet' and SA_CONC['v'] == 'karet_by_Heaven_and_his_family' and SA_WARNED['v'] == 'the_court_warned_over_the_charge' and SA_KPERS['v'] == 'man_and_woman_the_doers_not_the_approach' and SA_ORDERS['v']['sages'] == ['stoning', 'burning', 'killing', 'strangling'], (len(SA_STONED['v']), SA_STRANG['v'], SA_BURNED['v'], len(SA_LASHES['v']), SA_KARET['v'], SA_WHO['v'], SA_FAM['v'], SA_CONC['v'], SA_WARNED['v'], SA_KPERS['v'], SA_ORDERS['v'])
assert L24_TALION['verdict'] == 'PAY-MONEY' and MK_STONES[0].startswith('both verses fulfilled') and MK_STONING[0].startswith('stoned by all the people') and MK_STONING[1] == ['stoned'] and MK_WARN[1] == ['exempt'] and MK_VENUE[0].startswith('outside the court') and MK_HANG[0].startswith('not hanged') and MK_MODE[0].startswith('stoning') and MK_CUST[0].startswith('confined') and MK_BURIAL[1] == ['buried'] and MK_CONF[1] == ['confessed'], (L24_TALION['verdict'], MK_STONES[0][:30], MK_STONING[:2], MK_WARN[1], MK_VENUE[0][:20], MK_HANG[0][:12], MK_MODE[0][:10], MK_CUST[0][:10], MK_BURIAL[1], MK_CONF[1])
assert TM_DEV['v'] == 'put_to_death_not_ransomed' and TM_STATUS['v'] == 'most_holy_not_sold_not_redeemed' and CK_CHEREM[1] == ['destroyed'] and CK_HORMAH[1] == ['hormah_named'] and BK_ANGER[1] == ['mark_of_anger', 'plague_struck'] and BK_HANG[1] == ['commanded'], (TM_DEV['v'], TM_STATUS['v'], CK_CHEREM[1], CK_HORMAH[1], BK_ANGER[1], BK_HANG[1])
assert BH_DREAMS[0] == 'the prophets in dreams; Moses mouth to mouth, not in riddles' and BH_DIBBUR[0].startswith('harsh speech') and BH_CLOUD[0] == 'both kept — the cloud and the trumpets' and BH_ORDER[0].startswith('judah, reuben') and MM_MORIAH['v'] == 1 and MM_TRIALS['v'] == 10, (BH_DREAMS[0], BH_DIBBUR[0][:20], BH_CLOUD[0], BH_ORDER[0][:20], MM_MORIAH['v'], MM_TRIALS['v'])
assert HO_RULE['v'] == ['R._Akiva_love_your_neighbor', 'ben_Azzai_the_book_of_the_generations_of_man'] and HO_HATE['v'] == 'in_the_heart_only_is_the_ban' and HO_GRUDGE['v'] == 'lend_with_the_barb_I_am_not_like_you' and HO_BLOOD['v'] == 'may_not_stay_silent' and HO_SECRECY['v'] == 'the_leaving_judge_may_not_reveal_the_vote', (HO_RULE['v'], HO_HATE['v'], HO_GRUDGE['v'], HO_BLOOD['v'], HO_SECRECY['v'])
assert all(FOUND(r) for r in (OH_ADD, OH_DIM, OH_BESIDE, OH_TIME, CH_OTHER, CH_FIRST, HI_TEST, HI_RIGHT, HI_FEAR, HI_GODS, SN_PITY, SN_BAN, SN_COND, SN_WOOD, SN_DEVLIKE, SN_HOUSE, SN_SNARED, SN_OATH, SN_REDEEMED, GL_TEST, GL_HUMBLE, NR_INTER, NR_MERIT, NR_CALF, ST_FOUR, ST_SCHOLARS, ST_ATTR, BC_CURSE, BC_HEARKEN, PN_ONE, PN_RIGHT, PN_INQ, OR_IDOL, OR_DEV, OR_SERV, OR_ACQ, OR_CIRC, OR_DISS, OR_SIDE, OR_ENEMY, ER_FOUR, ER_BOW, ER_JOURN, ER_LIFT, SA_STONED, SA_STRANG, SA_BURNED, SA_LASHES, SA_KARET, SA_WHO, SA_FAM, SA_CONC, SA_WARNED, SA_KPERS, SA_ORDERS, L24_TALION, MK_STONES, MK_STONING, MK_WARN, MK_VENUE, MK_HANG, MK_MODE, MK_CUST, MK_BURIAL, MK_CONF, TM_DEV, TM_STATUS, CK_CHEREM, CK_HORMAH, BK_ANGER, BK_HANG, BH_DREAMS, BH_DIBBUR, BH_CLOUD, BH_ORDER, MM_MORIAH, MM_TRIALS, HO_RULE, HO_HATE, HO_GRUDGE, HO_BLOOD, HO_SECRECY)), 'a kin cell answered out of span'
