

# ---- THE READBACK — THE FORMS ON FILE, NO NEW FORM (THE LOOP's step 6): T4 rows graded against the cells that compile their kin by CALL (cell, cell_found), T1 REFERENCE
# ROWS against the tape's lines by kind and first verse (tape_kind, tape_verse), never a second write; EIGHT rows SUPPLIED AS LAWS — 13:4, 13:12, 13:15, 13:18 WITH THEIR
# WRITES (the code's holes, each a law's first seat), 13:2, 13:7, 13:13 the lines' own first seats, 13:6 the case's (a SUPPLIED row may carry its kin's reference — the
# chapter's rows all have kin: the design's form, 11b); the pointer row 13:18 (pointer=); NO state row, no hole, no open row, no stretch, no retrograde row ----
GRADES = ('VERBATIM', 'VARIANT', 'TURNED', 'SHORTENED', 'EXPANDED', 'SUPPLIED', 'DISAGREES')
def rb(verses, told, grade, why, tape_kind=None, tape_verse=None, cell=None, cell_found=None, entry='', open_=False, write=None, state=False, pointer=None):
    assert grade in GRADES, grade
    assert not state, ("no state row this chapter — the chapter law from its first word to its last", verses)
    assert write is None or (isinstance(write, str) and write), ("a write is a registry name or None", verses)
    if grade == 'SUPPLIED': assert entry, ("a SUPPLIED row names what supplies it", verses)
    if tape_kind: assert tape_verse, verses
    if cell: assert cell_found is not None, verses
    return {'verses': verses, 'told': told, 'grade': grade, 'why': why, 'tape_kind': tape_kind, 'tape_verse': tape_verse, 'cell': cell, 'cell_found': cell_found, 'entry': entry, 'open': open_, 'write': write, 'state': state, 'pointer': pointer, 'stretch': False}
READBACK = [
    rb('Deut 13:1', "all the word that I command you, it you shall keep to do; you shall not add to it nor take from it", 'VERBATIM', "VERBATIM IN KIND — 4:2's 'you shall not add to the word which I command you, nor diminish from it' said again in the singular on 'all the word' (the only two seats; seven tokens in order): add_nothing_commanded (4:1) on the tape; THE LINE word_sealed REUSING adding_barred — a second entry (OH.the_exhortation by CALL)", tape_kind='add_nothing_commanded', tape_verse='Deut 4:1', cell='obey_horeb.the_exhortation', cell_found=FOUND(OH_ADD), entry='the tape: add_nothing_commanded Deut 4:1 (israel); the cell 4:2 add_nothing / diminish_nothing'),
    rb('Deut 13:2', "when a prophet arises among you, or a dreamer of a dream, and gives you a sign or a wonder", 'SUPPLIED', "SUPPLIED AS A LAW — the false prophet's law at its FIRST SEAT: THE LINE prophet_test_declared (the kin by CALL — the dream the prophets' channel, Numbers 12:6-8, beha.miriam; 18:15's 'from among you' the true prophet ahead); the sign in the heavens and the wonder on the earth (83:4-5)", cell='beha.miriam', cell_found=FOUND(BH_DREAMS), entry="THE LINE prophet_test_declared (13:2-6) at the counter's day — the first seat; Numbers 12:6-8 by CALL (BH.miriam 'dreams'); Sifrei Bamidbar 103"),
    rb('Deut 13:3', "and the sign and the wonder come to pass … saying: let us go after other gods which you have not known, and let us serve them", 'VARIANT', "VARIANT — THE SEDUCER'S ONE FORMULA: 'these are your gods' at the calf (calf_made Exod 32:4 on the tape — the run's case) turned into 'let us go after other gods' (the second word's object by CALL — CH.the_second_word; 11:28's 'other gods which you have not known' — BC by CALL); 13:3, 13:7, 13:14 each other's closest kin", tape_kind='calf_made', tape_verse='Exod 32:4', cell='covenant_at_horeb.the_second_word', cell_found=FOUND(CH_OTHER), entry="the tape: calf_made Exod 32:4 (aaron); the cell 5:7 no_other_gods; ER.calf('four_verbs', 'bow_likened') by CALL"),
    rb('Deut 13:4', "you shall not hearken to the words of that prophet … for the LORD your God is testing you, to know whether you love the LORD your God with all your heart and with all your soul", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITES — false_prophet_hearing_barred (a BLOCK — the sign real and the hearing barred, the_signs_status a parameter) and tested_by_the_lord (a STATUS — the participle's one seat): the testing's first seat Genesis 22:1's tested on the tape (MM.moriah by CALL), 8:2 and 8:16 by CALL (GL), 6:16's test_barred the mirror (HI); 11:13's plural heart and soul the closest kin", tape_kind='tested', tape_verse='Gen 22:1', cell='mamre.moriah', cell_found=FOUND(MM_MORIAH), entry="THE WRITES false_prophet_hearing_barred and tested_by_the_lord on israel_people at the counter's day; the tape: tested Gen 22:1 (abraham)", write='false_prophet_hearing_barred'),
    rb('Deut 13:5', "after the LORD your God you shall walk, and Him you shall fear, and His commandments you shall keep, and His voice you shall obey, and Him you shall serve, and to Him you shall cleave", 'EXPANDED', "EXPANDED — 10:20's four verbs (cleaving_commanded on the tape) made six; 6:13's three by CALL (HI.the_gift_and_the_warning); 85:1 the first verb the cloud (cloud_lifted Num 10:11 — a run citation inside a law), 85:4 'His voice' the prophets' (Yevamot 90b:5); Sotah 14a's attributes (ST by CALL): cleaving_commanded REUSED — a second entry", tape_kind='cleaving_commanded', tape_verse='Deut 10:20', cell='second_tablets.the_god_of_gods_and_the_stranger', cell_found=FOUND(ST_FOUR), entry="the tape: cleaving_commanded Deut 10:20 (israel); cloud_lifted Num 10:11 (israel — 85:1's cloud); the cells 10:20 fear_serve_cleave_swear, walk_after_his_attributes; 6:13 fear_serve_swear"),
    rb('Deut 13:6', "and that prophet or that dreamer of the dream shall be put to death, for he spoke rebellion against the LORD your God who brought you out of the land of Egypt and redeemed you from the house of bondage, to thrust you from the way … and you shall purge the evil from your midst", 'SUPPLIED', "SUPPLIED AS A LAW — THE CASE'S: the false prophet's death by the parameter the_prophets_death (stoning / strangling — Mishnah Sanhedrin 11:1 the answer sheet's arm) written as put_to_death on the exam's person, and evil_purged_from_the_midst — THE PURGE FORMULA'S FIRST SEAT OF NINE; the exodus formula with redeeming — 5:6's preamble (CH.the_first_tablet by CALL), 9:26's redeeming (NR by CALL), 7:8's (SN); the four deaths' census (SA.census by CALL)", cell='covenant_at_horeb.the_first_tablet', cell_found=FOUND(CH_FIRST), entry="THE CASE'S WRITES put_to_death and evil_purged_from_the_midst (the exam's false prophet — never on the tape); the cells 5:6 the_first_word, 9:26 do_not_destroy_your_people, the census strangled"),
    rb('Deut 13:7', "when your brother, the son of your mother, or your son or your daughter or the wife of your bosom or your friend who is as your own soul entices you in secret, saying: let us go and serve other gods which you have not known, you nor your fathers", 'SUPPLIED', "SUPPLIED AS A LAW — the inciter's law at its FIRST SEAT: THE LINE inciter_law_declared; 'entice' the Torah's one token (two senses, 87:1-2); the inclusion table 87:4-11; the seducers' formula the second word's object by CALL", cell='covenant_at_horeb.the_second_word', cell_found=FOUND(CH_OTHER), entry="THE LINE inciter_law_declared (13:7-12) at the counter's day — the first seat; the cell 5:7 no_other_gods"),
    rb('Deut 13:8', "of the gods of the peoples round about you, near to you or far from you, from one end of the earth to the other", 'VERBATIM', "VERBATIM IN KIND by CALL — 6:14's 'of the gods of the peoples round about you' (spelled plene there, defective here — a DATA row: HI.the_gift_and_the_warning 'no_other_gods'); 88:1-2 THE HEADLESS PISKA — the near teach the far, the far the sun and the moon; 28:64's exile ahead", cell='hear_o_israel.the_gift_and_the_warning', cell_found=FOUND(HI_GODS), entry="the cell 6:14 no_other_gods (other_gods_barred stands from the giving); 13:8 defective against 6:14 plene"),
    rb('Deut 13:9', "you shall not consent to him nor hearken to him, nor shall your eye pity him, nor shall you spare nor conceal him", 'EXPANDED', "EXPANDED by CALL — 7:16's 'your eye shall not pity them' (SN.because_you_hear) on a second object with four more prohibitions, each against a standing duty (Leviticus 19:18, 19:16 — HO.conduct; Exodus 23:5 — OR.courts): pity_barred REUSED — a second entry; THE COURT'S RULE INVERTED (89:6-7 — OR.courts by CALL, Sanhedrin 33b:7)", cell='seven_nations.because_you_hear', cell_found=FOUND(SN_PITY), entry="the cell 7:16 consume_no_pity (pity_barred on Israel); the duties HO.conduct('great_rule', 'blood'), OR.courts('enemy_ox', 'asymmetry')"),
    rb('Deut 13:10', "but kill, you shall kill him; your hand shall be on him first to put him to death, and the hand of all the people afterward", 'VARIANT', "VARIANT by CALL — the wood-gatherer's cell (MK.capital_procedure — the venue, the warning, the stones) and the blasphemer's (L24; Leviticus 24:14's hands laid — sentence_declared's field on the tape) made the enticed's own hand first (89:8); 17:7's twin ahead; Leviticus 20:2's people who stone (SA.molech 'who_stones')", cell='mekoshesh.capital_procedure', cell_found=FOUND(MK_STONES), entry="the cells: mekoshesh stones_and_a_stone / venue / warning; lev24 talion; sanctions.molech who_stones; the tape: sentence_declared Lev 24:13 (hands_laid True)"),
    rb('Deut 13:11', "and you shall stone him with stones that he die, for he sought to thrust you from the LORD your God who brought you out of the land of Egypt, out of the house of bondage", 'VARIANT', "VARIANT — stoned_as_commanded (Lev 24:23; Num 15:36 on the tape — the rite performed twice) made the inciter's sentence: the stones and the stone (90:1 — MK.capital_procedure by CALL, the cell holds the rite); 5:6's six tokens in order (CH by CALL); the two verbs of stoning a DATA row", tape_kind='stoned_as_commanded', tape_verse='Lev 24:23', cell='mekoshesh.capital_procedure', cell_found=FOUND(MK_STONING), entry="the tape: stoned_as_commanded Lev 24:23 (the-son-of-shelomith), Num 15:36 (the-wood-gatherer); the cell stoning (died_at)"),
    rb('Deut 13:12', "and all Israel shall hear and fear, and shall not do again such an evil thing as this in your midst", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — israel_hears_and_fears (a STATUS on Israel): THE FORMULA'S FIRST SEAT OF FOUR (13:12 with the paragogic nun; 17:13, 19:20, 21:21 ahead); the_execution_timing a PARAMETER (91:1-2; Mishnah Sanhedrin 11:4); no tape line, no kin cell — the formula's own first seat", entry="THE WRITE israel_hears_and_fears on israel_people at the counter's day — the formula's first seat (the DB's four seats)", write='israel_hears_and_fears'),
    rb('Deut 13:13', "when you hear in one of your cities which the LORD your God gives you to dwell there, saying", 'SUPPLIED', "SUPPLIED AS A LAW — the condemned city's law at its FIRST SEAT: THE LINE condemned_city_law_declared; 'in one of your cities' [1] the chapter's one number verse (12:14's form by CALL — PN.the_place_chosen); 'to dwell there' the Torah's one seat — Jerusalem excluded (92:5; Bava Kamma 82b)", cell='place_name.the_place_chosen', cell_found=FOUND(PN_ONE), entry="THE LINE condemned_city_law_declared (13:13-19) at the counter's day — the first seat; the cell 12:14 in_one_of_your_tribes ([1])"),
    rb('Deut 13:14', "men, sons of Belial, have gone out from your midst and have drawn away the inhabitants of their city, saying: let us go and serve other gods which you have not known", 'VARIANT', "VARIANT by CALL — THE ONE NARRATIVE VERB inside the report; the seducers' one formula (the second word's object — CH.the_second_word); the parameters from one noun (111b:14-15 — 93:1-5); 'sons of Belial' the Torah's two (117:3 with 15:9; Naboth's witnesses the closest verse); 'you (pl.) knew' against 13:3's 'you knew them' — the same letters two ways", cell='covenant_at_horeb.the_second_word', cell_found=FOUND(CH_OTHER), entry="the cell 5:7 no_other_gods; the kin by computation 13:3 and 13:7; 1 Kings 21:10 the run's"),
    rb('Deut 13:15', "then you shall inquire and search and ask diligently; and behold, if it is true, the thing certain, that this abomination was done in your midst", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — condemned_city_inquiry_required (a STATUS on Israel) with THE PARAMETER the_inquiries (the seven interrogations from the three verses' terms pooled — 13:15, 17:4, 19:18; 'certain' the congruence rule; Mishnah Sanhedrin 5:1-2; Sanhedrin 40a-41a): 17:4 the twin ahead (nine of twelve tokens in order); no tape line, no kin cell — the first seat", entry="THE WRITE condemned_city_inquiry_required on israel_people at the counter's day; the_inquiries read from calendar_parameters.yaml", write='condemned_city_inquiry_required'),
    rb('Deut 13:16', "smite, you shall smite the inhabitants of that city with the edge of the sword, devoting it and all that is in it and its cattle with the edge of the sword", 'EXPANDED', "EXPANDED — canaanites_devoted_hormah_named (Num 21:3 on the tape — THE BAN PERFORMED: the DEBIT cherem_vowed closed, destroyed on the king of Arad) made the condemned city's devoting with the sword's manner (Bava Metzia 31b:3), the property table (112a:10) and the children disputed (94:3); the ban's seats by CALL — Exodus 22:19 (OR.capital), Leviticus 27:28-29 (TM.devote), Numbers 21:2-3 (CK), 7:2 (SN): THE CASE'S city_devoted", tape_kind='canaanites_devoted_hormah_named', tape_verse='Num 21:3', cell='chukat.arad_and_the_serpent', cell_found=FOUND(CK_CHEREM), entry="the tape: canaanites_devoted_hormah_named Num 21:3 (israel); the cells cherem_law, devoted_seats, devote('person'), the_ban; the ketiv at 13:16 in the store"),
    rb('Deut 13:17', "and all its spoil you shall gather into the midst of its street, and burn with fire the city and all its spoil wholly to the LORD your God; and it shall be a heap forever, it shall not be built again", 'VARIANT', "VARIANT by CALL — the ban's law (SN.the_seven_nations 'the_ban' — 7:2's debit open) and the devoted thing's (TM.devote) made the whole offering (111b:12 — 'wholly' as the whole offering's credit; Samuel's lamb the one kin), Heaven's spoil (112b:1-113a:2; Temurah 8a:9) and the heap forever (113a:4-6 — I4; Jericho and Hiel the run's case outside the tape); 'its street' the Torah's one", cell='seven_nations.the_seven_nations', cell_found=FOUND(SN_BAN), entry="the cells 7:2 the_ban / the_bans_condition; temurah devote('person', 'status'); Joshua 6:26, 8:28; 1 Kings 16:34; 1 Samuel 7:9 the run's"),
    rb('Deut 13:18', "and nothing of the devoted thing shall cleave to your hand, that the LORD may turn from the fierceness of His anger and give you mercy, and have mercy on you and multiply you, as He swore to your fathers", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — devoted_thing_cleaving_barred (a BLOCK on Israel — the benefit ban's source and reach; 7:26's house_abomination_barred the kin by CALL, SN.the_images_and_the_devoted); the anger keyed to idolatry's presence — hanging_commanded (Num 25:4) on the tape, Achan's valley the run's; the mercy two-armed a DATA row; THE POINTER 'as He swore to your fathers' — the oath's AS_WHEN form (SN.the_holy_people 'the_oath' by CALL; the fathers' merit NR by CALL)", tape_kind='hanging_commanded', tape_verse='Num 25:4', cell='seven_nations.the_images_and_the_devoted', cell_found=FOUND(SN_HOUSE), entry="THE WRITE devoted_thing_cleaving_barred on israel_people at the counter's day; the tape: hanging_commanded Num 25:4 (moses); the cells 7:26 into_your_house / devoted_like_it, the_oath", write='devoted_thing_cleaving_barred', pointer='Deut 13:18'),
    rb('Deut 13:19', "when you hearken to the voice of the LORD your God, to keep all His commandments which I command you today, to do the right in the eyes of the LORD your God", 'VERBATIM', "VERBATIM IN KIND by CALL — 12:25 and 12:28's 'the right in the eyes of the LORD' (PN.the_border_enlarged_and_the_altar) and 6:18's pair (HI.the_test_and_the_right); 11:13's 'if you hearken' (BC.the_second_paragraph): the footer the laws' condition — NO line, NO write; 28:1 and 28:15 ahead; Jehoshaphat's measure (1 Kings 22:43) the run's", cell='place_name.the_border_enlarged_and_the_altar', cell_found=FOUND(PN_RIGHT), entry="the cells 12:28 the_good_and_the_right, 6:18 the_right_and_the_good, 11:13 if_you_hearken; no line, no write"),
]
RB_GRADES = collections.Counter(r['grade'] for r in READBACK)
print('THE READBACK (the census, printed before it is asserted): rows %d, grades %s, on the tape %d, by CALL %d, SUPPLIED %s, writes %s, pointer %s' % (len(READBACK), dict(RB_GRADES), sum(1 for r in READBACK if r['tape_kind']), sum(1 for r in READBACK if r['cell']), [r['verses'] for r in READBACK if r['grade'] == 'SUPPLIED'], [r['write'] for r in READBACK if r['write']], [r['verses'] for r in READBACK if r['pointer']]))
assert len(READBACK) == 19 and RB_GRADES == collections.Counter({'VERBATIM': 3, 'VARIANT': 5, 'EXPANDED': 3, 'SUPPLIED': 8}) and not any(r['open'] for r in READBACK) and not any(r['stretch'] for r in READBACK) and not any(r['state'] for r in READBACK), (len(READBACK), RB_GRADES)
assert sum(1 for r in READBACK if r['tape_kind']) == 7 and sum(1 for r in READBACK if r['cell']) == 17 and all(r['cell_found'] for r in READBACK if r['cell']) and [r['verses'] for r in READBACK if r['grade'] == 'SUPPLIED'] == ['Deut 13:2', 'Deut 13:4', 'Deut 13:6', 'Deut 13:7', 'Deut 13:12', 'Deut 13:13', 'Deut 13:15', 'Deut 13:18'] and [r['write'] for r in READBACK if r['write']] == ['false_prophet_hearing_barred', 'israel_hears_and_fears', 'condemned_city_inquiry_required', 'devoted_thing_cleaving_barred'] and [r['verses'] for r in READBACK if r['pointer']] == ['Deut 13:18'], ([r['verses'] for r in READBACK if r['tape_kind']], [r['verses'] for r in READBACK if r['cell']], [(r['verses'], r['cell_found']) for r in READBACK if r['cell']])
assert [r['verses'] for r in READBACK] == ['Deut 13:%d' % v for v in range(1, 20)], 'one row per verse, in order'
HOLES = []      # no hole this chapter in the readback's sense — no act told only here; the code's FOUR holes COMPILED (the lines)
OPEN_ROWS = []  # no open disagreement in the readback — the four disputes PARAMETERS (calendar_parameters.yaml), the self-drawn city an OPEN DILEMMA of the shelf recorded as a DATA row, not an open row of a retold act

# ---- THE DATA ROWS (the docket's finds and the reading's; the counts printed before they are asserted) ----
_REG_IDS = {e['id'] for e in yaml.safe_load(open(_os.path.join(_ROOT, 'logic', 'corpus', 'entity_registry.yaml'), encoding='utf-8'))['entities']}
DATA = {
    'the_readback': {'value': READBACK, 'holes': HOLES, 'open_rows': OPEN_ROWS, 'settings': {'the_form': "THE READBACK'S FORMS ON FILE, NO NEW FORM (THE LOOP.md step 6; THE DEUTERONOMY WALK 11b, 2026-09-21): T4 rows graded against the cells that compile their kin by CALL (seventeen), T1 reference rows against the tape's lines by kind and first verse (seven — some rows both); EIGHT rows SUPPLIED AS LAWS — four with their writes (13:4, 13:12, 13:15, 13:18), three the lines' own first seats (13:2, 13:7, 13:13), 13:6 the case's; the pointer row 13:18; no state row, no stretch, no retrograde row"}},
    'the_counter_and_the_parameters': {'value': CLOCK, 'settings': {'the_day': "the four own-day lines at the counter's day (40, 11, 1) after the tape's last Deuteronomy 12 line (nations_cut_off_warned) — NO marker, no clock walk, no stretch; the four parameters read from calendar_parameters.yaml (exercised_by seducers)"}},
    'the_signs_status': {'value': SIGNS, 'settings': {'the_source': "calendar_parameters.yaml the_signs_status — R. Yosei HaGelili's dominion (the Sifrei 84:1; Sanhedrin 90a:10) / R. Akiva's fallen prophet (84:2; 90a:11 — Hananiah); either arm the hearing barred (F2 the_signs_status)"}},
    'the_prophets_death': {'value': DEATH, 'settings': {'the_source': "calendar_parameters.yaml the_prophets_death — stoning (the Sifrei 86:6, 90:2 by I2 on 'thrust'; Sanhedrin 89b:15-19) / strangling (R. Shimon; Mishnah Sanhedrin 11:1 — the answer sheet's arm; 89b:20-21); the case's put_to_death carries the mode (F2 the_prophets_death)"}},
    'the_execution_timing': {'value': TIMING, 'settings': {'the_source': "calendar_parameters.yaml the_execution_timing — kept to the Festival (R. Akiva; Mishnah Sanhedrin 11:4; Tosefta 11:3) / at once with the notice (R. Yehuda) — the Sifrei 91:1-2 (F3 the_execution_timing)"}},
    'the_inquiries': {'value': INQ, 'settings': {'the_source': "calendar_parameters.yaml the_inquiries — the seven, the examinations, the voiding, the tolerance, the congruence, 'diligently' free, the order, the clock datum (Mishnah Sanhedrin 5:1-2; Sanhedrin 40a-41a; the Sifrei 93:6-9): a table the cell reads as data (F4 the_seven_interrogations, the_congruence_rule)"}},
    'the_three_grains': {'value': {'the_word': "the priests' blessing (the Sifrei 82:5; Rosh Hashanah 28b:10-13 carried)", 'the_count': "the four species (1, 1, 3, 2) from the verse's own numbers — Sukkah 34b:3-4; the strings' minimum — Menachot 41b:12-42a:2", 'the_rite': "the mixed bloods — Mishnah Zevachim 8:10, Zevachim 80a:1-4, 81a:1-4: the active graver than the passive", 'the_counts': (1, 1, 3, 2)}, 'settings': {'the_source': "the Sifrei 82:3-5 (F1 the_three_grains)"}},
    'the_six_verbs': {'value': {'the_counts': (6, 4, 3), 'the_seats': "13:5 six, 10:20 four (cleaving_commanded on the tape), 6:13 three (HI by CALL)", 'the_first_verb': "the cloud (85:1 — cloud_lifted Num 10:11 a run citation inside a law)", 'his_voice': "the prophets' (85:4 — Yevamot 90b:5)"}, 'settings': {'the_source': "the Sifrei 85:1-6 (F2 the_six_verbs)"}},
    'the_false_prophets_table': {'value': {'the_essence': 'strangled, all agree (90a:2)', 'the_part': 'exempt, all agree (90a:2, 90a:5)', 'the_hour': 'heeded (90a:2 — Elijah at Carmel, Yevamot 90b:5-6)', 'idolatry_a_day': 'liable, all agree (90a:6)'}, 'settings': {'the_source': "Sanhedrin 90a:2-6; Mishnah Sanhedrin 11:5-6 (F2 the_false_prophets_table)"}},
    'the_sign_and_the_presumption': {'value': {'the_sign': 'the prophet gives a sign (89b:6 — Micah gave none)', 'the_presumed': 'one already presumed a prophet needs no sign (89b:6-7 — Isaac at Moriah, Israel at Carmel)', 'the_definition': '13:2 the definition of a prophet (Horayot 13a:12)'}, 'settings': {'the_source': "Sanhedrin 89b:6-7 (F2 the_established_prophet)"}},
    'the_purge_formulas_seats': {'value': {'the_seats': PURGE_SEATS, 'the_count': len(PURGE_SEATS), 'the_first': 'Deut 13:6', 'the_homographs': ['purge_deadline (the leaven)', 'purge_commanded (Jacob — Genesis 35:2)']}, 'settings': {'the_source': "the DB (DE8); the Sifrei 86:10 — the doer removed (F2 the_evil_purged; RB the_purge_formulas_nine_seats)"}},
    'the_inciters_kin': {'value': {'the_table': ['the brother by the father', "the mother's son", 'the son and the daughter of any kind', 'the betrothed and the married', 'the convert', "the father in 'as your own soul'"], 'the_son_against_the_father': 'the agent permitted (Sanhedrin 85b:2)'}, 'settings': {'the_source': "the Sifrei 87:4-11 (F3 the_inciters_kin)"}},
    'the_entrapment': {'value': {'the_stage': 'a candle lit in an inner room, the witnesses in the dark outer room (67a:5, 67a:13)', 'the_question': "'say what you said to me in seclusion'", 'the_two_answers': "retracts — good; 'it is our duty' — stoned", 'no_forewarning': 'spoken to two — no forewarning needed (67a:4)', 'the_only_case': 'no hidden witnesses for any liable to death except the inciter (67a:3, 67a:12)'}, 'settings': {'the_source': "Mishnah Sanhedrin 7:10 at Sanhedrin 67a (F3 the_entrapment)"}},
    'the_fifteen_utterances': {'value': {'the_forms': ['I shall worship', 'I shall go and worship', 'let us go and worship'], 'the_services': ['worship', 'sacrifice', 'incense', 'libation', 'bowing'], 'the_counts': (3, 5, 15), 'the_honors_not_capital': 'embracing, kissing, sweeping the prohibition alone (Mishnah 7:6 — 91:4)'}, 'settings': {'the_source': "Sanhedrin 67a:6; the Sifrei 91:3 (F3 the_fifteen_utterances)"}},
    'the_five_prohibitions': {'value': {'consent': "against 'love your neighbor as yourself' (89:1 — Leviticus 19:18)", 'hearken': "against the enemy's ass (89:2 — Exodus 23:5)", 'pity': "7:16's clause reused (pity_barred's second entry)", 'spare': "against 'you shall not stand by your neighbor's blood' (89:3 — Leviticus 19:16)", 'conceal': 'the defense and the silence barred (89:4-5)', 'the_negations': 5}, 'settings': {'the_source': "the Sifrei 89:1-5 (F3 the_five_prohibitions)"}},
    'the_courts_rule_inverted': {'value': {'the_ordinary_rule': "the acquitted not retried, the deliberation opened for acquittal, no death by a majority of one (Mishnah 4:1; 40a:9-14 — OR.courts('asymmetry') = %s)" % (V(OR_ACQ),), 'the_inversion': "convicted not brought back to acquit, acquitted brought back to convict (89:6-7; 33b:7 — 13:9 and 13:10 the two sources)", 'the_consent_alone': "the enticed who says 'I will' liable (61b:3-11)"}, 'settings': {'the_source': "Sanhedrin 33b:7, 36b:5, 43a:21, 61b, 63b:7, 85b:2 (F3 the_courts_rule_inverted)"}},
    'the_hand_first': {'value': {'the_seats': "13:10 the enticed's hand, 17:7 the witnesses' (the two seats of 'first' and 'afterward' on a hand)", 'the_rule': "the enticed's own commandment, any man's after (89:8)"}, 'settings': {'the_source': "the Sifrei 89:8 (F3 the_hand_first)"}},
    'the_two_verbs_of_stoning': {'value': {'deuteronomy': STONING_DEUT, 'leviticus_and_numbers': STONING_LEVNUM, 'both': STONING_BOTH}, 'settings': {'the_source': "the DB's lemmas (DE8; RB the_two_verbs_of_stoning)"}},
    'the_seducers_formula': {'value': {'the_kin': {3: KINC[3][:1], 7: KINC[7][:1], 14: KINC[14][:1]}, 'the_three': "13:3 the prophet, 13:7 the brother, 13:14 the city — one sentence said three times; 13:3 and 13:7 each nearest 13:14, 13:14 nearest Naboth's witnesses (1 Kings 21:10) then 13:3 and 13:7 (RETYPED from the tape's first run — DE8)"}, 'settings': {'the_source': "the kin by computation (DE8; RB the_seducers_one_formula)"}},
    'the_seducers_parameters': {'value': {'gone_out': 'themselves, not agents', 'men': 'two at least; not women, not children', 'belial': 'without a yoke', 'from_your_midst': 'not the border', 'their_city': "not another's", 'saying': 'witnesses and forewarning for each', 'the_stringency': 'individuals stoned and their property spared; the multitude by the sword and their property destroyed (111b:7)'}, 'settings': {'the_source': "Sanhedrin 111b:14-15; the Sifrei 93:1-5; Mishnah Sanhedrin 10:4 (F4 the_seducers_parameters)"}},
    'the_majoritys_procedure': {'value': {'the_arms': ['imprison each and judge', 'stone each until half, then the rest by the sword', 'multiply the courts'], 'the_venue': 'the Great Sanhedrin from 17:5 (112a:6)', 'the_threshold': 'thirty days an inhabitant (112a:7-8)', 'the_self_drawn_city': 'the open dilemma (112a:2-3)'}, 'settings': {'the_source': "Sanhedrin 112a:2-9 (F4 the_majoritys_procedure)"}},
    'the_seven_inquiries': {'value': {'the_counts': (7, 3, 11, 1), 'the_three_verses': ['Deut 13:15', 'Deut 17:4', 'Deut 19:18'], 'the_eighth': "R. Abbahu's (40b:11-14)", 'diligently_free': 'I2 with the freeness rider (40b:4-6)'}, 'settings': {'the_source': "Sanhedrin 40a:15, 40b:1-14 (F4 the_seven_interrogations)"}},
    'the_congruence_rule': {'value': {'voids': 'the sword against the club (41a:18); the scarf, the sandal (41a:19-20)', 'stands': 'black garments against white (41a:18)', 'the_tolerance': {'days': 1, 'hours': 1}, 'i_do_not_know': 'voids an interrogation, not an examination; a contradiction both (40a:4)'}, 'settings': {'the_source': "Sanhedrin 40a:4-7, 41a:18-20; Mishnah Sanhedrin 5:2 (F4 the_congruence_rule)"}},
    'the_property_table': {'value': {'righteous_inside': 'lost', 'righteous_outside': 'spared', 'wicked_inside': 'lost', 'wicked_outside': 'lost', 'the_caravans': 'save the city (111b:8)', 'the_edges': 'the deposits, the joint animal, the wig, the carcass (112a:11-17)'}, 'settings': {'the_source': "Sanhedrin 112a:10; Mishnah Sanhedrin 10:5; the Sifrei 94:4-5, 95:1 (F4 the_property_table)"}},
    'the_sword': {'value': {'the_mode': 'decapitation (Sanhedrin 52b:12 — Mishnah 9:1)', 'by_any_means': 'if you cannot, by any death you can (Bava Metzia 31b:3)', 'the_children': 'disputed (94:3 — Abba Hanan from 24:16)'}, 'settings': {'the_source': "Bava Metzia 31b:3; Sanhedrin 52b:12; the Sifrei 94:1-3 (F4 the_sword)"}},
    'the_heavens_spoil': {'value': {'most_sacred': 'die', 'temple_maintenance': 'redeemed', 'heave_offering': 'decays', 'second_tithe_and_scrolls': 'interred', 'r_shimons_exclusions': "'its cattle' the firstborn and the animal tithe; 'its spoil' the tithe money (112b:1; Temurah 8a:9)"}, 'settings': {'the_source': "Sanhedrin 112b:1-113a:2; Mishnah Sanhedrin 10:6; Temurah 8a:9 (F5 heavens_spoil)"}},
    'the_heap_forever': {'value': {'r_yosei_hagelili': 'not even gardens and orchards (I4 refused under R. Avin\'s rule)', 'r_akiva': "not built again as it was (I4 applied)", 'jericho': "Joshua 6:26's oath; Hiel (1 Kings 16:34) — not under another name, not another city so named (113a:7-8)", 'the_trees': 'detached forbidden, attached permitted (113a:7)'}, 'settings': {'the_source': "Sanhedrin 111b:13, 113a:4-10; the Sifrei 95:6-7, 96:1 (F5 the_heap_forever)"}},
    'the_benefit_ban': {'value': {'the_source': 'the stores adorned with roses (Avodah Zarah 12b:7)', 'the_reach': 'the whole animal (34b:15); the pedestal (Tosefta 7:5); the warning (Pesachim 48a:5); any amount (Mishnah Shabbat 9:6); never nullified (50a:10)', 'the_citron': 'of a condemned city unfit (Sukkah 34b:8 — Mishnah Sukkah 3:5)', 'the_lashes': "the Asherah's wood in the plow (Makkot 22a:9, 22a:2)", 'the_salt_sea': "the benefit's value cast in (the Sifrei 96:2; Mishnah Avodah Zarah 3:9)"}, 'settings': {'the_source': "F5 nothing_shall_cleave, the_citron_of_a_condemned_city, the_devoted_things_lashes"}},
    'the_anger_keyed': {'value': {'the_condition': "as long as idolatry is in the world, fierce anger is in the world (96:3; Mishnah 10:6; 113b:2-3)", 'the_seats': "'from the fierceness of His anger' the Bible's four — Joshua 7:26 Achan's valley says the words back; Numbers 25:4 Peor's on the tape"}, 'settings': {'the_source': "the Sifrei 96:3; Sanhedrin 111b:13, 113b:2-3 (F5 the_anger_keyed_to_idolatry)"}},
    'the_mercy_two_armed': {'value': {'the_arms': "whoever has mercy on creatures is shown mercy from Heaven; whoever has none is shown none (96:4; Shabbat 151b:14)", 'the_three_marks': 'the merciful, the bashful, the doers of kindness (Yevamot 79a:3)', 'no_write': True}, 'settings': {'the_source': "the Sifrei 96:4; Shabbat 151b:14; Yevamot 79a:3; Beitzah 32b:4; Tosefta Sotah 10:1 (F5 the_mercy_two_armed) — a promise's arm, not a law's"}},
    'the_footer': {'value': {'no_line': True, 'no_write': True, 'the_condition': "'when you hearken … to do the right' folded into condemned_city_law_declared's value", 'the_kin': "12:25, 28 (PN by CALL); 6:18 (HI by CALL); 11:13 (BC by CALL); 28:1 and 28:15 ahead", 'the_light_as_the_weighty': "82:1 / 96:7 — the header's sentence at the footer; Avot 2:1"}, 'settings': {'the_source': "the Sifrei 96:6-8 (F6)"}},
    'the_parsers_one': {'value': {'deut_13_13': NUMS[13], 'deut_12_14': KINNUM[('Deut', 12, 14)], 'deut_17_2': KINNUM[('Deut', 17, 2)], 'deut_13_18_swore': NUMS[18]}, 'settings': {'the_source': "the parser measured at the reading — ONE number verse (13:13 [1]), no ordinal, no starred token; 13:18's 'swore' no number (F4 one_city_at_a_time)"}},
    'the_ketiv_at_13_16': {'value': {'the_store': 329, 'the_db': 328, 'the_token': "'that city' — the written and the read form of the pronoun (the store carries both)"}, 'settings': {'the_source': "the reading (the store's glosses — sitting 11); a DATA row, the runner reads the DB alone"}},
    'the_registrys_homographs': {'value': {'the_heap_on_the_registry': 'the_heap' in _REG_IDS, 'ahuzzath_on_the_registry': 'ahuzzath' in _REG_IDS, 'the_cities_around_shechem_on_the_registry': 'the_cities_around_shechem' in _REG_IDS, 'the_names': "the-heap Laban's (Genesis 31), the-friend Abimelech's (Genesis 26), the-cities Shechem's (Genesis 35): FALSE if the census matches them; purge_commanded Jacob's, purge_deadline the leaven's"}, 'settings': {'the_source': "the design's measurement (the registry map for the chapter's tokens)"}},
    'the_capital_courts_end': {'value': {'the_datum': 'forty years before the destruction the Sanhedrin exiled from the Chamber of Hewn Stone (41a:25)', 'a_marker': False}, 'settings': {'the_source': "Sanhedrin 41a:25 (F4 the_law_as_a_study_text) — a clock datum, not a marker"}},
    'the_law_as_a_study_text': {'value': {'never_was': 'a condemned city never was and never will be — examine and take a reward (Tosefta Sanhedrin 14:1)', 'one_mezuzah': "a city with one mezuzah never one (Sanhedrin 71a:17, 113a:3 — 12:4's 'you shall not do so')"}, 'settings': {'the_source': "Tosefta Sanhedrin 14:1 (the English machine-translated past its head — read whole at the docket)"}},
    'moses_unnamed': {'value': [v for v in range(1, 20) for x in W13(v) if x == 'משה'], 'settings': {'the_source': "the chapter names Moses never, Israel once (13:12)"}},
    'the_register_seats': {'value': {'no_receipt': True, 'no_header': True, 'no_footer': True, 'the_12_1_footer': "its declaration REMOVED at this compile — the block holds law_seducers given_at Deut 13:1, the class DAEMONS (green) at BOTH the block's seats — the header 12:1 and the footer 28:69, its declaration removed at the tail on the chain's first-pass demand: DECLARED 100 -> 98 (the gate's print)", 'as_when': "13:18's 'as He swore to your fathers' the oath's AS_WHEN form — the pointer row"}, 'settings': {'the_source': "the reading's finder (sitting 11); add_types_ch13.py (the register file)"}},
    'the_scans': {'value': {'seducers_scan': SEDUCERS_SCAN, 'reuse_scan': REUSE_SCAN}, 'settings': {'the_source': "the one database at import — the five new names absent on Israel before this daemon's lines (DE4); the three reused effects on israel_people alone before"}},
}
print('THE DATA ROWS (printed before they are asserted):', len(DATA), sorted(DATA)[:8], '…')
assert len(DATA) == 39, len(DATA)   # READ FROM THE PRINT (the fast checker's first pass)
assert DATA['the_purge_formulas_seats']['value']['the_count'] == 9 and DATA['the_two_verbs_of_stoning']['value']['both'] == ['Deut 21:21'] and DATA['the_parsers_one']['value']['deut_13_13'] == [1] and DATA['the_parsers_one']['value']['deut_13_18_swore'] == [] and DATA['moses_unnamed']['value'] == [] and all(DATA['the_registrys_homographs']['value'][k] for k in ('the_heap_on_the_registry', 'ahuzzath_on_the_registry', 'the_cities_around_shechem_on_the_registry')), (DATA['the_purge_formulas_seats']['value'], DATA['the_two_verbs_of_stoning']['value'], DATA['the_parsers_one']['value'])


# =====================================================================
# Motion 3 — THE WRAP: the daemon law_seducers (given_at Deut 13:1, installed_by boot — the Deuteronomy daemons' form)
# =====================================================================
def law_seducers(event, world):
    """Deut 13:1-19 (cold_run_seducers.py F1-F6 and the table). given_at Deut 13:1 — 'all the word that I command you, it you shall keep to do', the chapter's
    seal at the counter's day (40, 11, 1), 4:2's twin; installed_by boot (the Deuteronomy daemons' form; THE INSTALL HYPOTHESIS on the table). FOUR TAPE LINES
    of its own, all OWN-DAY, NO marker: word_sealed (13:1 — adding_barred REUSED, a second entry), prophet_test_declared (13:2-6 — false_prophet_hearing_barred
    a BLOCK, tested_by_the_lord a STATUS, cleaving_commanded REUSED), inciter_law_declared (13:7-12 — pity_barred REUSED, israel_hears_and_fears a STATUS) and
    condemned_city_law_declared (13:13-19 — condemned_city_inquiry_required a STATUS, devoted_thing_cleaving_barred a BLOCK). The exam's case kind dispatches to
    the cells in EXPLICIT branches with LITERAL effects per kind (an unnamed effect is a KeyError). No timer; no close; the kin's effects UNMOVED (DE5)."""
    k, src = event['kind'], event['case_source']
    E_ = lambda eff, s, cp=None, amount=None, due=None, law='', value=None: {'effect': eff, 'subject': s, 'counterparty': cp, 'amount': amount, 'due': due, 'value': value if value is not None else True, 'source_law': law, 'case_source': src}
    if k == 'word_sealed':
        return [E_('adding_barred', 'israel_people', value={'the_word': "all the word that I command you, it you shall keep to do; you shall not add to it nor take from it (13:1) — the singular seal on all the word; 4:2 the plural, the only two seats", 'the_reuse': "4:2's BLOCK on Israel (law_obey_horeb's write at 4:1-8's line) REUSED — A SECOND ENTRY on israel_people at the chapter's own day (8b's lesson: a reused effect is a second entry on the same ledger; CC3's ONE retyped TWO)", 'the_three_grains': "the word's (the priests' blessing — 82:5; Rosh Hashanah 28b), the count's (the four species (1, 1, 3, 2) — Sukkah 34b:3-4; the strings — Menachot 41b-42a), the rite's (the mixed bloods — Mishnah Zevachim 8:10, Zevachim 80a-81a)", 'keep_and_do': "'keep' the prohibition, 'do' the command (R. Eliezer son of Jacob — 82:2, 85:3)", 'the_elder': "five compartments made as one spoil, a fifth beside stands alone (Sanhedrin 88b-89a carried)", 'the_day': "the counter's own (40, 11, 1) — page_order, no marker; the chapter's first own-day line"}, law="F1 [INK 13:1 'you shall not add to it nor take from it' — THE REUSE at THE DEUTERONOMY WALK 11b: adding_barred's second entry on Israel at the chapter's own day (DE2, DE4); the three grains from the docket's rows]")]
    if k == 'prophet_test_declared':
        return [E_('false_prophet_hearing_barred', 'israel_people', value={'the_word': "you shall not hearken to the words of that prophet or that dreamer of the dream (13:4) — the sign and the wonder come to pass, saying: let us go after other gods (13:3)", 'the_signs_status': "A PARAMETER — R. Yosei HaGelili's dominion (the sign real; the sun stopped, do not heed — the Sifrei 84:1 at Sanhedrin 90a:10) / R. Akiva's fallen prophet (Hananiah — 84:2 at 90a:11); the sign not examined once idolatry is preached (the Rambam 5:3)", 'the_table': "the essence abolished strangled, the part exempt, the hour heeded (Elijah at Carmel — Yevamot 90b:5-6), idolatry even a day liable (Sanhedrin 90a:2-6; Mishnah Sanhedrin 11:5-6)", 'the_presumption': "the established prophet needs no sign (89b:6-7); 13:2 the definition of a prophet (Horayot 13a:12)", 'the_oven': "the sign not decisive in law (Bava Metzia 59b)", 'the_day': "the counter's own (40, 11, 1) — page_order, no marker"}, law="F2 [INK 13:3-4 'you shall not hearken to the words of that prophet' — THE HEARING BARRED COMPILED at THE DEUTERONOMY WALK 11b: a BLOCK on Israel at the chapter's own day (DE2, DE4); the value from the docket's rows Sanhedrin 89b-90a, Yevamot 90b, the Rambam's Introduction 5:2-3]"),
                E_('tested_by_the_lord', 'israel_people', value={'the_word': "for the LORD your God is testing you, to know whether you love the LORD your God with all your heart and with all your soul (13:4) — the participle's one seat", 'the_seats': "Genesis 22:1's tested the first seat on the tape (mamre.moriah by CALL); 8:2 and 8:16 by CALL (good_land); 6:16's test_barred the mirror by CALL (hear_o_israel); 84:5 the verse whole", 'the_day': "the counter's own (40, 11, 1) — on the same line"}, law="F2 [INK 13:4 'for the LORD your God is testing you' — THE TESTING COMPILED AS A LAW at THE DEUTERONOMY WALK 11b: a STATUS on Israel at the chapter's own day (DE2, DE4); the Sifrei 84:5]"),
                E_('cleaving_commanded', 'israel_people', value={'the_word': "after the LORD your God you shall walk, and Him you shall fear, and His commandments you shall keep, and His voice you shall obey, and Him you shall serve, and to Him you shall cleave (13:5) — SIX verbs after 10:20's four and 6:13's three", 'the_reuse': "10:20's STATUS on Israel (law_second_tablets's write) REUSED — A SECOND ENTRY on israel_people at the chapter's own day (DB2's, DC6's ONE retyped TWO)", 'the_readings': "the first verb the cloud (85:1 — cloud_lifted Num 10:11 a run citation inside a law); His fear (85:2); the prohibition kept (85:3); 'His voice' the prophets' (85:4 — Yevamot 90b:5); His Torah and His sanctuary (85:5); separate from idolatry and cleave (85:6); Sotah 14a's attributes (second_tablets by CALL)", 'the_day': "the counter's own (40, 11, 1) — on the same line"}, law="F2 [INK 13:5 'and to Him you shall cleave' — THE REUSE at THE DEUTERONOMY WALK 11b: cleaving_commanded's second entry on Israel at the chapter's own day (DE2, DE4, DE5); the Sifrei 85:1-6]")]
    if k == 'inciter_law_declared':
        return [E_('pity_barred', 'israel_people', value={'the_word': "you shall not consent to him nor hearken to him, nor shall your eye pity him, nor shall you spare nor conceal him (13:9) — the inciter the second object", 'the_reuse': "7:16's BLOCK on Israel (law_seven_nations's write on the nations) REUSED — A SECOND ENTRY on israel_people at the chapter's own day (CQ6's, DC6's ONE retyped TWO)", 'the_five_prohibitions': "each against a standing duty — the love of the neighbor (89:1, Leviticus 19:18), the enemy's ass (89:2, Exodus 23:5), the pity (7:16), the neighbor's blood (89:3, Leviticus 19:16), the defense and the silence (89:4-5)", 'the_courts_rule_inverted': "convicted not brought back to acquit, acquitted brought back to convict (89:6-7; Sanhedrin 33b:7 with 13:9 and 13:10; 36b:5; 85b:2 the son against his father; 61b:3-11 the consent alone)", 'the_entrapment': "the only capital case with hidden witnesses — the lit room and the dark room (Mishnah 7:10 at Sanhedrin 67a); the fifteen utterances (67a:6 — 91:3); the inciter's kin an inclusion table (87:4-11)", 'the_day': "the counter's own (40, 11, 1) — page_order, no marker"}, law="F3 [INK 13:9 'nor shall your eye pity him' — THE REUSE at THE DEUTERONOMY WALK 11b: pity_barred's second entry on Israel at the chapter's own day (DE2, DE4, DE5); the Sifrei 89:1-7]"),
                E_('israel_hears_and_fears', 'israel_people', value={'the_word': "and all Israel shall hear and fear, and shall not do again such an evil thing as this in your midst (13:12) — THE FORMULA'S FIRST SEAT OF FOUR: 13:12 (the paragogic nun), 17:13, 19:20, 21:21", 'the_execution_timing': "A PARAMETER — kept to the Festival (R. Akiva — 91:1; Mishnah Sanhedrin 11:4; Tosefta 11:3) / at once with the notice (R. Yehuda — 91:2)", 'the_hand_first': "13:10 the enticed's own commandment (89:8); the stoning's rite 13:11 the wood-gatherer's cell (mekoshesh by CALL — 90:1)", 'the_day': "the counter's own (40, 11, 1) — on the same line"}, law="F3 [INK 13:12 'and all Israel shall hear and fear' — THE FORMULA'S FIRST SEAT at THE DEUTERONOMY WALK 11b: a STATUS on Israel at the chapter's own day (DE2, DE4, DE6); the Sifrei 91:1-2, Mishnah Sanhedrin 11:4]")]
    if k == 'condemned_city_law_declared':
        return [E_('condemned_city_inquiry_required', 'israel_people', value={'the_word': "when you hear in one of your cities … then you shall inquire and search and ask diligently; and behold, if it is true, the thing certain (13:13-15)", 'the_seducers_parameters': "from one noun — themselves not agents, two at least, men not women or children, without a yoke, not the border, their own city, witnesses and forewarning for each (Sanhedrin 111b:14-15; the Sifrei 93:1-5; Mishnah Sanhedrin 10:4)", 'one_city': "one at a time, two allowed, not three (92:3; Tosefta Sanhedrin 14:1); the court of seventy-one (Mishnah 1:5)", 'jerusalem': "cannot become one — 'to dwell there', not apportioned to a tribe (92:5; Bava Kamma 82b:4, 8)", 'the_majority': "a parameter's three arms (112a:4-5); the venue the Great Sanhedrin (112a:6); thirty days an inhabitant (112a:7-8); the self-drawn city the open dilemma (112a:2-3)", 'the_inquiries': "A PARAMETER — the seven interrogations from the three verses' terms pooled, the examinations, 'I do not know', the tolerance, 'certain' the congruence rule, 'diligently' free (I2), the eighth (Mishnah Sanhedrin 5:1-2; Sanhedrin 40a-41a)", 'the_study_text': "a condemned city never was and never will be — examine and take a reward (Tosefta Sanhedrin 14:1); one mezuzah (71a:17)", 'the_day': "the counter's own (40, 11, 1) — page_order, no marker; the chapter's last own-day line"}, law="F4 [INK 13:15 'then you shall inquire and search and ask diligently' — THE INQUIRY COMPILED at THE DEUTERONOMY WALK 11b: a STATUS on Israel at the chapter's own day (DE2, DE4); the value from the docket's rows Sanhedrin 40a-41a, 111b-112a, Bava Kamma 82b, Tosefta Sanhedrin 14]"),
                E_('devoted_thing_cleaving_barred', 'israel_people', value={'the_word': "and nothing of the devoted thing shall cleave to your hand, that the LORD may turn from the fierceness of His anger and give you mercy (13:18)", 'the_benefit_ban': "the stores with roses (Avodah Zarah 12b:7), the whole animal (34b:15), the pedestal (Tosefta 7:5), the warning (Pesachim 48a:5), any amount (Mishnah Shabbat 9:6), never nullified (50a:10); the Salt Sea (96:2; Mishnah Avodah Zarah 3:9)", 'the_citron': "of a condemned city unfit (Sukkah 34b:8 — Mishnah Sukkah 3:5)", 'the_lashes': "the Asherah's wood in the plow (Makkot 22a:9, 22a:2)", 'the_kin': "7:26's house_abomination_barred by CALL (seven_nations.the_images_and_the_devoted)", 'the_anger': "keyed to idolatry's presence (96:3; Mishnah 10:6; 113b:2-3) — Achan's valley, Peor's hanging_commanded on the tape", 'the_mercy': "two-armed — a DATA row, no write (96:4; Shabbat 151b:14)", 'the_oath': "'as He swore to your fathers' the oath's AS_WHEN form — the pointer row (the fathers' merit by CALL)", 'the_footer': "13:19 the condition — no line, no write", 'the_day': "the counter's own (40, 11, 1) — on the same line"}, law="F5 [INK 13:18 'nothing of the devoted thing shall cleave to your hand' — THE BENEFIT BAN COMPILED at THE DEUTERONOMY WALK 11b: a BLOCK on Israel at the chapter's own day (DE2, DE4); the value from the docket's rows Avodah Zarah 12b-50a, Sukkah 34b, Makkot 22a, the Sifrei 96]")]
    if k == 'seducers_case':
        fn = {'header': the_header, 'prophet': the_prophet_and_the_test, 'inciter': the_inciter, 'city': the_city_heard_of_the_inquiry_and_the_sword, 'whole': the_whole_offering_the_heap_and_the_mercy, 'footer': the_footer, 'readback': the_readback}[event['cell']]
        v, e, _ = fn({'ask': event['ask']}, DATA); L = '%s [%s]' % ({'header': 'F1', 'prophet': 'F2', 'inciter': 'F3', 'city': 'F4', 'whole': 'F5', 'footer': 'F6', 'readback': 'RB'}[event['cell']], event['ask']); s_ = event['person']
        W = {'accepted': E_('accepted', s_, value=v, law=L), 'exempt': E_('exempt', s_, value=v, law=L), 'lashes': E_('lashes', s_, value=v, law=L), 'stoned': E_('stoned', s_, value=v, law=L), 'put_to_death': E_('put_to_death', s_, value=v, law=L), 'evil_purged_from_the_midst': E_('evil_purged_from_the_midst', s_, value=v, law=L), 'city_devoted': E_('city_devoted', s_, value=v, law=L)}
        return [W[x] for x in e if x != FX.NONE]
    return []


LINES = [
    ('Deut 13:1 — all the word that I command you, it you shall keep to do; you shall not add to it nor take from it',),
    ('Deut 13:2-6 — when a prophet arises among you, or a dreamer of a dream, and gives you a sign or a wonder … saying: let us go after other gods which you have not known, and let us serve them — you shall not hearken to the words of that prophet or that dreamer of the dream, for the LORD your God is testing you …; after the LORD your God you shall walk, and Him you shall fear, and His commandments you shall keep, and His voice you shall obey, and Him you shall serve, and to Him you shall cleave; and that prophet or that dreamer of the dream shall be put to death, for he spoke rebellion against the LORD your God … and you shall purge the evil from your midst',),
    ('Deut 13:7-12 — when your brother, the son of your mother, or your son or your daughter or the wife of your bosom or your friend who is as your own soul entices you in secret, saying: let us go and serve other gods … you shall not consent to him nor hearken to him, nor shall your eye pity him, nor shall you spare nor conceal him; but kill, you shall kill him; your hand shall be on him first to put him to death, and the hand of all the people afterward; and you shall stone him with stones that he die … and all Israel shall hear and fear, and shall not do again such an evil thing as this in your midst',),
    ('Deut 13:13-19 — when you hear in one of your cities which the LORD your God gives you to dwell there, saying: men, sons of Belial, have gone out from your midst and have drawn away the inhabitants of their city … then you shall inquire and search and ask diligently; and behold, if it is true, the thing certain … smite, you shall smite the inhabitants of that city with the edge of the sword, devoting it and all that is in it …; and all its spoil you shall gather into the midst of its street, and burn with fire the city and all its spoil wholly to the LORD your God; and it shall be a heap forever …; and nothing of the devoted thing shall cleave to your hand, that the LORD may turn from the fierceness of His anger and give you mercy … as He swore to your fathers — when you hearken to the voice of the LORD your God … to do the right in the eyes of the LORD your God',),
]
CLOSES = "none — no close this chapter: the two new blocks (false_prophet_hearing_barred, devoted_thing_cleaving_barred) and the three new statuses (tested_by_the_lord, israel_hears_and_fears, condemned_city_inquiry_required) have no closer; the three reuses (adding_barred, cleaving_commanded, pity_barred) second entries on Israel; no debit (the ban's already open to Joshua); the kin's effects unmoved (other_gods_barred, test_barred, house_abomination_barred, cherem_vowed closed, destroyed, stoned — the readback references, no second write); the case's writes (put_to_death, stoned, evil_purged_from_the_midst, city_devoted) at the exam only"

PERSONS = [
    ('the-priest-who-adds-a-blessing', 'header', 'the_three_grains', "the Sifrei 82:5; Rosh Hashanah 28b:10-13 (carried); Sukkah 34b:3-4 — the exam's row the_three_grains"),
    ('the-one-who-keeps-the-prohibitions-and-neglects-the-commands', 'header', 'keep_and_do', "the Sifrei 82:2, 85:3 — the exam's row keep_and_do"),
    ('the-elder-who-rules-five-compartments', 'header', 'the_elders_not_adding', "Sanhedrin 88b:14-89a:2 (carried); Mishnah Sanhedrin 11:3 — the exam's row the_elders_not_adding"),
    ('the-one-who-completes-his-festival-offerings-on-another-day', 'header', 'the_festivals_days', "Chagigah 8b:11 — the exam's row the_festivals_days"),
    ('the-dreamer-of-a-dream', 'prophet', 'the_prophet_and_the_dreamer', "Numbers 12:6-8 by CALL; Sanhedrin 89b:6-7; the Sifrei 83:1-2 — the exam's row the_prophet_and_the_dreamer"),
    ('the-prophet-whose-sign-comes-to-pass-and-preaches-nothing-against-the-torah', 'prophet', 'the_sign_and_the_wonder', "the Sifrei 83:4-5; 1 Kings 13:3 — the exam's row the_sign_and_the_wonder"),
    ('the-prophet-who-keeps-part-and-voids-part', 'prophet', 'the_false_prophets_table', "Sanhedrin 90a:2, 90a:5 — the exam's row the_false_prophets_table"),
    ('the-prophet-with-a-true-sign-who-preaches-idolatry-for-a-day', 'prophet', 'the_prophets_death', "Sanhedrin 89b:15-21, 90a:6; Mishnah Sanhedrin 11:1; the Rambam's Introduction 5:2 — the exam's row the_prophets_death"),
    ('the-one-who-denies-the-redeemers-claim', 'prophet', 'the_exodus_formula_with_redeeming', "the Sifrei 86:4-5, 90:3 — the exam's row the_exodus_formula_with_redeeming"),
    ('the-prophet-who-spoke-under-duress', 'prophet', 'the_exemptions', "the Sifrei 86:1-2 — the exam's row the_exemptions"),
    ('elijah-at-carmel', 'prophet', 'elijah_at_carmel', "Yevamot 90b:5-6; Sanhedrin 90a:2; the Sifrei 85:4 — the exam's row elijah_at_carmel"),
    ('the-sage-who-rules-by-the-carob-tree', 'prophet', 'the_oven_of_akhnai', "Bava Metzia 59b — the exam's row the_oven_of_akhnai"),
    ('the-presumed-prophet-who-gives-no-sign', 'prophet', 'the_established_prophet', "Sanhedrin 89b:6-7; Horayot 13a:12 — the exam's row the_established_prophet"),
    ('the-son-who-strikes-his-inciting-father', 'inciter', 'the_inciters_kin', "the Sifrei 87:4-11; Sanhedrin 85b:2 — the exam's row the_inciters_kin"),
    ('the-one-enticed-in-error', 'inciter', 'entice_two_senses', "the Sifrei 87:1-2; Kiddushin 80b:6 — the exam's row entice_two_senses"),
    ('the-inciter-who-retracts-before-the-fence', 'inciter', 'the_entrapment', "Mishnah Sanhedrin 7:10 at Sanhedrin 67a:5 — the exam's row the_entrapment"),
    ('the-inciter-who-says-i-shall-go-and-burn-incense', 'inciter', 'the_fifteen_utterances', "Sanhedrin 67a:6; the Sifrei 91:3 — the exam's row the_fifteen_utterances"),
    ('the-enticed-who-did-not-consent', 'inciter', 'the_courts_rule_inverted', "Sanhedrin 61b:3-11; 33b:7 — the exam's row the_courts_rule_inverted"),
    ('the-enticed-who-lets-another-cast-the-first-stone', 'inciter', 'the_hand_first', "the Sifrei 89:8 — the exam's row the_hand_first"),
    ('the-inciter-who-says-it-is-our-duty', 'inciter', 'the_stoning_rite', "Sanhedrin 67a:5; the Sifrei 90:1-2; Sifrei Bamidbar 114 — the exam's row the_stoning_rite"),
    ('the-court-that-condemns-three-cities-at-once', 'city', 'one_city_at_a_time', "the Sifrei 92:3; Tosefta Sanhedrin 14:1; Mishnah Sanhedrin 1:5 — the exam's row one_city_at_a_time"),
    ('the-inhabitants-of-jerusalem-drawn-away', 'city', 'to_dwell_there_jerusalem', "Bava Kamma 82b:4, 8; the Sifrei 92:5 — the exam's row to_dwell_there_jerusalem"),
    ('the-inhabitant-of-thirty-days-drawn-away', 'city', 'the_majoritys_procedure', "Sanhedrin 112a:4-8 — the exam's row the_majoritys_procedure"),
    ('the-witnesses-of-the-sword-and-the-club', 'city', 'the_congruence_rule', "Sanhedrin 41a:18-20; Mishnah Sanhedrin 5:2 — the exam's row the_congruence_rule"),
    ('the-inhabitant-who-cannot-be-beheaded', 'city', 'the_sword', "Bava Metzia 31b:3; Sanhedrin 52b:12 — the exam's row the_sword"),
    ('the-righteous-mans-deposit-outside-the-city', 'city', 'the_property_table', "Sanhedrin 112a:10-17; Mishnah Sanhedrin 10:5 — the exam's row the_property_table"),
    ('the-condemned-city', 'city', 'the_devoting', "Exodus 22:19, Leviticus 27:28-29, Numbers 21:2-3, Deut 7:2 by CALL — the exam's row the_devoting"),
    ('the-one-who-turns-his-eyes-from-the-poor', 'city', 'belial_and_naboth', "the Sifrei 117:3; Bava Batra 10a:10 — the exam's row belial_and_naboth"),
    ('the-one-who-examines-the-law-and-takes-a-reward', 'city', 'the_law_as_a_study_text', "Tosefta Sanhedrin 14:1 — the exam's row the_law_as_a_study_text"),
    ('the-one-who-burns-the-spoil-outside-the-street', 'whole', 'the_whole_offering', "Mishnah Sanhedrin 10:6; Sanhedrin 111b:10-12 — the exam's row the_whole_offering"),
    ('the-one-who-redeems-the-citys-temple-maintenance-animal', 'whole', 'heavens_spoil', "Sanhedrin 112b:1; Temurah 8a:9 — the exam's row heavens_spoil"),
    ('the-one-who-rebuilds-jericho-under-its-name', 'whole', 'the_heap_forever', "Sanhedrin 113a:4-10; the Sifrei 95:6-7, 96:1 — the exam's row the_heap_forever"),
    ('the-one-who-takes-a-citron-of-a-condemned-city', 'whole', 'the_citron_of_a_condemned_city', "Sukkah 34b:8; Mishnah Sukkah 3:5 — the exam's row the_citron_of_a_condemned_city"),
    ('the-one-who-plows-with-the-asherahs-wood', 'whole', 'the_devoted_things_lashes', "Makkot 22a:9, 22a:2 (carried) — the exam's row the_devoted_things_lashes"),
    ('the-one-who-keeps-the-devoted-thing-while-the-anger-stands', 'whole', 'the_anger_keyed_to_idolatry', "the Sifrei 96:3; Sanhedrin 113b:2-3 — the exam's row the_anger_keyed_to_idolatry"),
    ('the-merciful-man', 'whole', 'the_mercy_two_armed', "the Sifrei 96:4; Shabbat 151b:14 — the exam's row the_mercy_two_armed"),
    ('the-one-who-pleads-the-fathers-merit', 'whole', 'as_he_swore_to_your_fathers', "the Sifrei 96:5 — the exam's row as_he_swore_to_your_fathers"),
    ('the-one-who-does-the-little', 'footer', 'the_footer_the_condition', "the Sifrei 96:6-8 — the exam's row the_footer_the_condition"),
    ('the-one-who-weighs-the-commandments', 'footer', 'the_light_as_the_weighty', "the Sifrei 82:1, 96:7; Avot 2:1 — the exam's row the_light_as_the_weighty"),
    ('the-scholar-who-reads-the-table', 'readback', 'the_table', "THE LOOP.md step 6 — the exam's row the_table"),
]


def scene():
    """THE SCENE — the exam's rows replayed on the world engine (the exodus epoch): the exam's persons through seducers_case — forty persons: SIX EXEMPT
    (the prophet who keeps part and voids part — Sanhedrin 90a:5; the prophet who spoke under duress — the Sifrei 86:1; Elijah at Carmel — Yevamot 90b:5-6; the
    inciter who retracts before the fence — Sanhedrin 67a:5; the enticed who did not consent — 61b; the inhabitants of Jerusalem drawn away — Bava Kamma 82b),
    ONE LASHED (the one who plows with the Asherah's wood — Makkot 22a:9), the false prophet PUT TO DEATH with the evil purged (the parameter's default arm),
    the inciter STONED with the evil purged, the inhabitant put to death by the sword, THE CONDEMNED CITY DEVOTED (city_devoted — a destroy effect), the rest
    accepted on the shelf's arms. No timer; no close."""
    with contextlib.redirect_stdout(io.StringIO()):
        w = WE.World(era='Deut 13:1-19: chapter 13 on the shelf — Sanhedrin, Zevachim, Sukkah, Menachot, Rosh Hashanah, Eruvin, Avodah Zarah, Bava Metzia, Yevamot, Shabbat, Bava Kamma, Makkot, Temurah, Chagigah, Kiddushin, Horayot on the engine (the exodus epoch)', epoch='exodus')
        w.laws = [law_seducers]
        w.advance(w.clock.day_in('exodus', 40, 11, 1))
        # THE DAEMON GATE READS LITERAL SUBMITS ONLY — the forty persons typed out from PERSONS (ch13_scene_gen.py wrote these lines from the list; frozen here)
        w.submit({'kind': 'seducers_case', 'subject': 'the-priest-who-adds-a-blessing', 'person': 'the-priest-who-adds-a-blessing', 'cell': 'header', 'ask': 'the_three_grains', 'case_source': "the Sifrei 82:5; Rosh Hashanah 28b:10-13 (carried); Sukkah 34b:3-4 — the exam's row the_three_grains"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-keeps-the-prohibitions-and-neglects-the-commands', 'person': 'the-one-who-keeps-the-prohibitions-and-neglects-the-commands', 'cell': 'header', 'ask': 'keep_and_do', 'case_source': "the Sifrei 82:2, 85:3 — the exam's row keep_and_do"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-elder-who-rules-five-compartments', 'person': 'the-elder-who-rules-five-compartments', 'cell': 'header', 'ask': 'the_elders_not_adding', 'case_source': "Sanhedrin 88b:14-89a:2 (carried); Mishnah Sanhedrin 11:3 — the exam's row the_elders_not_adding"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-completes-his-festival-offerings-on-another-day', 'person': 'the-one-who-completes-his-festival-offerings-on-another-day', 'cell': 'header', 'ask': 'the_festivals_days', 'case_source': "Chagigah 8b:11 — the exam's row the_festivals_days"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-dreamer-of-a-dream', 'person': 'the-dreamer-of-a-dream', 'cell': 'prophet', 'ask': 'the_prophet_and_the_dreamer', 'case_source': "Numbers 12:6-8 by CALL; Sanhedrin 89b:6-7; the Sifrei 83:1-2 — the exam's row the_prophet_and_the_dreamer"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-prophet-whose-sign-comes-to-pass-and-preaches-nothing-against-the-torah', 'person': 'the-prophet-whose-sign-comes-to-pass-and-preaches-nothing-against-the-torah', 'cell': 'prophet', 'ask': 'the_sign_and_the_wonder', 'case_source': "the Sifrei 83:4-5; 1 Kings 13:3 — the exam's row the_sign_and_the_wonder"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-prophet-who-keeps-part-and-voids-part', 'person': 'the-prophet-who-keeps-part-and-voids-part', 'cell': 'prophet', 'ask': 'the_false_prophets_table', 'case_source': "Sanhedrin 90a:2, 90a:5 — the exam's row the_false_prophets_table"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-prophet-with-a-true-sign-who-preaches-idolatry-for-a-day', 'person': 'the-prophet-with-a-true-sign-who-preaches-idolatry-for-a-day', 'cell': 'prophet', 'ask': 'the_prophets_death', 'case_source': "Sanhedrin 89b:15-21, 90a:6; Mishnah Sanhedrin 11:1; the Rambam's Introduction 5:2 — the exam's row the_prophets_death"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-denies-the-redeemers-claim', 'person': 'the-one-who-denies-the-redeemers-claim', 'cell': 'prophet', 'ask': 'the_exodus_formula_with_redeeming', 'case_source': "the Sifrei 86:4-5, 90:3 — the exam's row the_exodus_formula_with_redeeming"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-prophet-who-spoke-under-duress', 'person': 'the-prophet-who-spoke-under-duress', 'cell': 'prophet', 'ask': 'the_exemptions', 'case_source': "the Sifrei 86:1-2 — the exam's row the_exemptions"})
        w.submit({'kind': 'seducers_case', 'subject': 'elijah-at-carmel', 'person': 'elijah-at-carmel', 'cell': 'prophet', 'ask': 'elijah_at_carmel', 'case_source': "Yevamot 90b:5-6; Sanhedrin 90a:2; the Sifrei 85:4 — the exam's row elijah_at_carmel"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-sage-who-rules-by-the-carob-tree', 'person': 'the-sage-who-rules-by-the-carob-tree', 'cell': 'prophet', 'ask': 'the_oven_of_akhnai', 'case_source': "Bava Metzia 59b — the exam's row the_oven_of_akhnai"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-presumed-prophet-who-gives-no-sign', 'person': 'the-presumed-prophet-who-gives-no-sign', 'cell': 'prophet', 'ask': 'the_established_prophet', 'case_source': "Sanhedrin 89b:6-7; Horayot 13a:12 — the exam's row the_established_prophet"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-son-who-strikes-his-inciting-father', 'person': 'the-son-who-strikes-his-inciting-father', 'cell': 'inciter', 'ask': 'the_inciters_kin', 'case_source': "the Sifrei 87:4-11; Sanhedrin 85b:2 — the exam's row the_inciters_kin"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-enticed-in-error', 'person': 'the-one-enticed-in-error', 'cell': 'inciter', 'ask': 'entice_two_senses', 'case_source': "the Sifrei 87:1-2; Kiddushin 80b:6 — the exam's row entice_two_senses"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-inciter-who-retracts-before-the-fence', 'person': 'the-inciter-who-retracts-before-the-fence', 'cell': 'inciter', 'ask': 'the_entrapment', 'case_source': "Mishnah Sanhedrin 7:10 at Sanhedrin 67a:5 — the exam's row the_entrapment"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-inciter-who-says-i-shall-go-and-burn-incense', 'person': 'the-inciter-who-says-i-shall-go-and-burn-incense', 'cell': 'inciter', 'ask': 'the_fifteen_utterances', 'case_source': "Sanhedrin 67a:6; the Sifrei 91:3 — the exam's row the_fifteen_utterances"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-enticed-who-did-not-consent', 'person': 'the-enticed-who-did-not-consent', 'cell': 'inciter', 'ask': 'the_courts_rule_inverted', 'case_source': "Sanhedrin 61b:3-11; 33b:7 — the exam's row the_courts_rule_inverted"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-enticed-who-lets-another-cast-the-first-stone', 'person': 'the-enticed-who-lets-another-cast-the-first-stone', 'cell': 'inciter', 'ask': 'the_hand_first', 'case_source': "the Sifrei 89:8 — the exam's row the_hand_first"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-inciter-who-says-it-is-our-duty', 'person': 'the-inciter-who-says-it-is-our-duty', 'cell': 'inciter', 'ask': 'the_stoning_rite', 'case_source': "Sanhedrin 67a:5; the Sifrei 90:1-2; Sifrei Bamidbar 114 — the exam's row the_stoning_rite"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-court-that-condemns-three-cities-at-once', 'person': 'the-court-that-condemns-three-cities-at-once', 'cell': 'city', 'ask': 'one_city_at_a_time', 'case_source': "the Sifrei 92:3; Tosefta Sanhedrin 14:1; Mishnah Sanhedrin 1:5 — the exam's row one_city_at_a_time"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-inhabitants-of-jerusalem-drawn-away', 'person': 'the-inhabitants-of-jerusalem-drawn-away', 'cell': 'city', 'ask': 'to_dwell_there_jerusalem', 'case_source': "Bava Kamma 82b:4, 8; the Sifrei 92:5 — the exam's row to_dwell_there_jerusalem"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-inhabitant-of-thirty-days-drawn-away', 'person': 'the-inhabitant-of-thirty-days-drawn-away', 'cell': 'city', 'ask': 'the_majoritys_procedure', 'case_source': "Sanhedrin 112a:4-8 — the exam's row the_majoritys_procedure"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-witnesses-of-the-sword-and-the-club', 'person': 'the-witnesses-of-the-sword-and-the-club', 'cell': 'city', 'ask': 'the_congruence_rule', 'case_source': "Sanhedrin 41a:18-20; Mishnah Sanhedrin 5:2 — the exam's row the_congruence_rule"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-inhabitant-who-cannot-be-beheaded', 'person': 'the-inhabitant-who-cannot-be-beheaded', 'cell': 'city', 'ask': 'the_sword', 'case_source': "Bava Metzia 31b:3; Sanhedrin 52b:12 — the exam's row the_sword"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-righteous-mans-deposit-outside-the-city', 'person': 'the-righteous-mans-deposit-outside-the-city', 'cell': 'city', 'ask': 'the_property_table', 'case_source': "Sanhedrin 112a:10-17; Mishnah Sanhedrin 10:5 — the exam's row the_property_table"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-condemned-city', 'person': 'the-condemned-city', 'cell': 'city', 'ask': 'the_devoting', 'case_source': "Exodus 22:19, Leviticus 27:28-29, Numbers 21:2-3, Deut 7:2 by CALL — the exam's row the_devoting"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-turns-his-eyes-from-the-poor', 'person': 'the-one-who-turns-his-eyes-from-the-poor', 'cell': 'city', 'ask': 'belial_and_naboth', 'case_source': "the Sifrei 117:3; Bava Batra 10a:10 — the exam's row belial_and_naboth"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-examines-the-law-and-takes-a-reward', 'person': 'the-one-who-examines-the-law-and-takes-a-reward', 'cell': 'city', 'ask': 'the_law_as_a_study_text', 'case_source': "Tosefta Sanhedrin 14:1 — the exam's row the_law_as_a_study_text"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-burns-the-spoil-outside-the-street', 'person': 'the-one-who-burns-the-spoil-outside-the-street', 'cell': 'whole', 'ask': 'the_whole_offering', 'case_source': "Mishnah Sanhedrin 10:6; Sanhedrin 111b:10-12 — the exam's row the_whole_offering"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-redeems-the-citys-temple-maintenance-animal', 'person': 'the-one-who-redeems-the-citys-temple-maintenance-animal', 'cell': 'whole', 'ask': 'heavens_spoil', 'case_source': "Sanhedrin 112b:1; Temurah 8a:9 — the exam's row heavens_spoil"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-rebuilds-jericho-under-its-name', 'person': 'the-one-who-rebuilds-jericho-under-its-name', 'cell': 'whole', 'ask': 'the_heap_forever', 'case_source': "Sanhedrin 113a:4-10; the Sifrei 95:6-7, 96:1 — the exam's row the_heap_forever"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-takes-a-citron-of-a-condemned-city', 'person': 'the-one-who-takes-a-citron-of-a-condemned-city', 'cell': 'whole', 'ask': 'the_citron_of_a_condemned_city', 'case_source': "Sukkah 34b:8; Mishnah Sukkah 3:5 — the exam's row the_citron_of_a_condemned_city"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-plows-with-the-asherahs-wood', 'person': 'the-one-who-plows-with-the-asherahs-wood', 'cell': 'whole', 'ask': 'the_devoted_things_lashes', 'case_source': "Makkot 22a:9, 22a:2 (carried) — the exam's row the_devoted_things_lashes"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-keeps-the-devoted-thing-while-the-anger-stands', 'person': 'the-one-who-keeps-the-devoted-thing-while-the-anger-stands', 'cell': 'whole', 'ask': 'the_anger_keyed_to_idolatry', 'case_source': "the Sifrei 96:3; Sanhedrin 113b:2-3 — the exam's row the_anger_keyed_to_idolatry"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-merciful-man', 'person': 'the-merciful-man', 'cell': 'whole', 'ask': 'the_mercy_two_armed', 'case_source': "the Sifrei 96:4; Shabbat 151b:14 — the exam's row the_mercy_two_armed"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-pleads-the-fathers-merit', 'person': 'the-one-who-pleads-the-fathers-merit', 'cell': 'whole', 'ask': 'as_he_swore_to_your_fathers', 'case_source': "the Sifrei 96:5 — the exam's row as_he_swore_to_your_fathers"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-does-the-little', 'person': 'the-one-who-does-the-little', 'cell': 'footer', 'ask': 'the_footer_the_condition', 'case_source': "the Sifrei 96:6-8 — the exam's row the_footer_the_condition"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-one-who-weighs-the-commandments', 'person': 'the-one-who-weighs-the-commandments', 'cell': 'footer', 'ask': 'the_light_as_the_weighty', 'case_source': "the Sifrei 82:1, 96:7; Avot 2:1 — the exam's row the_light_as_the_weighty"})
        w.submit({'kind': 'seducers_case', 'subject': 'the-scholar-who-reads-the-table', 'person': 'the-scholar-who-reads-the-table', 'cell': 'readback', 'ask': 'the_table', 'case_source': "THE LOOP.md step 6 — the exam's row the_table"})
    n = lambda eid, eff: len([e for e in w.entity(eid).ledger if e['effect'] == eff])
    SEVEN = ('accepted', 'exempt', 'lashes', 'stoned', 'put_to_death', 'evil_purged_from_the_midst', 'city_devoted')
    tset = len([l for l in w.log if l[0] == 'TIMER-SET']); tfire = len([l for l in w.log if l[0] == 'TIMER-FIRE']); tcan = len([l for l in w.log if l[0] == 'TIMER-CANCEL'])
    closes = len([e for ent in w.entities.values() for e in ent.ledger if e.get('closed_by')])
    return (tuple(sum(n(p, eff) for eff in SEVEN) for p, _, _, _ in PERSONS), tuple(n(p, 'exempt') for p in ('the-prophet-who-keeps-part-and-voids-part', 'the-prophet-who-spoke-under-duress', 'elijah-at-carmel', 'the-inciter-who-retracts-before-the-fence', 'the-enticed-who-did-not-consent', 'the-inhabitants-of-jerusalem-drawn-away')), sum(n(p, 'lashes') for p, _, _, _ in PERSONS), sum(n(p, 'stoned') for p, _, _, _ in PERSONS), sum(n(p, 'put_to_death') for p, _, _, _ in PERSONS), sum(n(p, 'evil_purged_from_the_midst') for p, _, _, _ in PERSONS), n('the-condemned-city', 'city_devoted'), (tset, tfire, tcan, len(w.timers)), len(w.entities), closes), w
SCENE, _W = scene()
print('THE SCENE (printed before it is asserted):', SCENE)
# THE PREDICTION (typed before the first run — the design's arithmetic): every exam person written once (the false prophet and the inciter TWICE — the death and the
# purge); the six exempt arms ONE each; ONE lashes; stoned 1, put_to_death 2, evil_purged 2, city_devoted 1; no timer; ENTITIES the forty persons; CLOSES 0.
SCENE_PREDICTED = (tuple(2 if p in ('the-prophet-with-a-true-sign-who-preaches-idolatry-for-a-day', 'the-inciter-who-says-it-is-our-duty') else 1 for p, _, _, _ in PERSONS), (1,) * 6, 1, 1, 2, 2, 1, (0, 0, 0, 0), 40, 0)
assert SCENE == SCENE_PREDICTED, ('THE DEUTERONOMY WALK 11b: the scene moved from its prediction', SCENE, SCENE_PREDICTED)


def narrative():
    """THE DEUTERONOMY WALK 11b (2026-09-21): the chapter's own laws AS HISTORY — FOUR own-day lines with no marker (the code's four holes compiled at the
    counter's day (40, 11, 1): word_sealed, prophet_test_declared, inciter_law_declared, condemned_city_law_declared) on a world with this runner's daemon: 8 writes
    (all on Israel — five new, three reuses), no timer, ONE entity (Israel — the written-on party; a line's subject makes no entity, 7b's lesson), the counter at
    (11, 1), no close, no row, no dated line. Recorded by the sequential run's recorder and stitched onto the tape after the last Deuteronomy 12 line. Not a graded
    cell: the tuple below is a tripwire typed from the design."""
    with contextlib.redirect_stdout(io.StringIO()):
        w = WE.World(era='Deut 13:1-19 on the tape — the word sealed, the prophet tested, the inciter\'s law, the condemned city\'s law at the counter\'s own day, no marker (the exodus epoch)', epoch='exodus')
        w.laws = [law_seducers]
        w.advance(w.clock.day_in('exodus', 40, 11, 1))
        # THE DAEMON GATE READS LITERAL SUBMITS ONLY — the four lines typed out; no marker; no field named `until`, `days` or `due`
        w.submit({'kind': 'word_sealed', 'subject': 'israel', 'the_word': 'all the word that I command you, it you shall keep to do (13:1) — 4:2\'s twin in the singular', 'the_seal': "you shall not add to it nor take from it (13:1) — adding_barred REUSED, a second entry; the three grains (82:3-5)", 'case_source': LINES[0][0]})
        w.submit({'kind': 'prophet_test_declared', 'subject': 'israel', 'the_prophet': 'when a prophet arises among you, or a dreamer of a dream (13:2) — the definition of a prophet', 'the_sign': "a sign or a wonder that comes to pass (13:2-3) — real by the parameter's first arm, the hearing barred anyway (13:4)", 'the_test': 'for the LORD your God is testing you (13:4) — the participle\'s one seat', 'the_six_verbs': 'walk, fear, keep, obey, serve, cleave (13:5) — 10:20\'s four made six; cleaving_commanded REUSED', 'the_death': "that prophet shall be put to death (13:6) — the mode a parameter (stoning / strangling); the evil purged from the midst — the formula's first seat", 'case_source': LINES[1][0]})
        w.submit({'kind': 'inciter_law_declared', 'subject': 'israel', 'the_inciter': 'when your brother, the son of your mother … entices you in secret (13:7) — the Torah\'s one token of the root', 'the_kin': "the brother, the son, the daughter, the wife of your bosom, the friend as your own soul (13:7) — the inclusion table (87:4-11)", 'the_five_prohibitions': 'not consent, not hearken, not pity, not spare, not conceal (13:9) — pity_barred REUSED; the court\'s rule inverted', 'the_hand_first': 'your hand first, the hand of all the people afterward (13:10)', 'the_stoning': "stone him with stones that he die (13:11) — the wood-gatherer's rite by CALL", 'the_hearing': 'all Israel shall hear and fear (13:12) — the formula\'s first seat of four; the timing a parameter', 'case_source': LINES[2][0]})
        w.submit({'kind': 'condemned_city_law_declared', 'subject': 'israel', 'the_city': 'when you hear in one of your cities … to dwell there (13:13) — one city at a time; Jerusalem never', 'the_seducers': "men, sons of Belial, have gone out from your midst and have drawn away the inhabitants of their city (13:14) — the parameters from one noun", 'the_inquiry': 'inquire and search and ask diligently; true and certain (13:15) — the seven interrogations, a parameter', 'the_sword': 'smite, you shall smite with the edge of the sword (13:16) — decapitation, by any means; the children disputed', 'the_whole_offering': "devote it and all in it; gather its spoil into its street; burn it wholly to the LORD (13:16-17) — the property table's four cells; Heaven's spoil", 'the_heap': 'a heap forever, not built again (13:17) — Jericho and Hiel the run\'s', 'the_devoted_thing': "nothing of the devoted thing shall cleave to your hand (13:18) — the benefit ban; the anger keyed to idolatry; the mercy two-armed; as He swore to your fathers", 'the_footer': 'when you hearken … to do the right in the eyes of the LORD (13:19) — the condition, no line, no write', 'case_source': LINES[3][0]})
    writes = len([l for l in w.log if l[0] == 'WRITE'])
    closes = len([e for ent in w.entities.values() for e in ent.ledger if e.get('closed_by')])
    rows = len([l for l in w.log if l[0] == 'ROW'])
    dated = len([l for l in w.log if l[0] == 'EVENT' and l[2].get('dated') is not None])
    return (writes, len([l for l in w.log if l[0] == 'TIMER-SET']), len(w.entities), w.clock.eras['exodus'].date(w.clock.day)[1:], closes, rows, len(w.tables['population']), dated), w


NARRATIVE, _WN = narrative()
print('THE NARRATIVE (printed before it is asserted):', NARRATIVE, [e['effect'] for e in _WN.entity('israel_people').ledger])
NARRATIVE_PREDICTED = (8, 0, 1, (11, 1), 0, 0, 0, 0)   # DEUTERONOMY_WALK.md "Sitting 11b": 8 writes, no timer, ONE entity (Israel — the written-on party), the counter's day (11, 1), no close, no row, no population row, no dated line
assert NARRATIVE == NARRATIVE_PREDICTED, ('THE DEUTERONOMY WALK 11b: the chapter\'s narrative moved from its prediction', NARRATIVE, NARRATIVE_PREDICTED)
_is = _WN.entity('israel_people').ledger
assert [e['effect'] for e in _is] == ['adding_barred', 'false_prophet_hearing_barred', 'tested_by_the_lord', 'cleaving_commanded', 'pity_barred', 'israel_hears_and_fears', 'condemned_city_inquiry_required', 'devoted_thing_cleaving_barred'] and all(e.get('dated') is None for e in _is), [(e['effect'], e.get('dated')) for e in _is]   # the eight on Israel at the counter's day — five new, three reuses
_ev = [l for l in _WN.log if l[0] == 'EVENT']
assert [l[2]['kind'] for l in _ev] == ['word_sealed', 'prophet_test_declared', 'inciter_law_declared', 'condemned_city_law_declared'] and all(l[2].get('dated') is None for l in _ev) and not [l for l in _WN.log if l[0] == 'MARKER'], [(l[2]['kind'], l[2].get('dated')) for l in _ev]
