# =====================================================================
# Motion 1 — THE CELLS (F4-F7) and THE TABLE (RB): every token probed; effects on every cell; the docket's crowns as exam rows
# =====================================================================
def the_carcass_and_the_kid(case, data):
    """F4 — Deut 14:21 — THE LINE carcass_and_kid_declared writing carcass_eating_barred (a BLOCK — the ban's seat named by the sanctions engine itself; 'any carcass' the torn included, the torn's slaughter purifying; the carcass by fitness for a resident alien); THE PARAMETER the_carcass_table (R. Meir / R. Yehuda; the precedence); the sale clause the paradigm of a permitted benefit; the sanction a dispute carried by CALL; the custom's bar; THE KID — NO NEW WRITE: the third seat's gain the assignment (calendar.kid_in_milk by CALL; the three readings at Kiddushin 57b:9; the fowl out; the stomach's milk)"""
    del P_[:]
    ask = case['ask']
    if ask == 'any_carcass_the_torn':
        ink('14:21', '"YOU SHALL NOT EAT ANY CARCASS" — the clause %s; "carcass" in Deuteronomy %s (14:8, 14:21, 21:23, 28:26); the carcass\'s three kin verses share %d and %d tokens (Leviticus 17:15; Exodus 22:30); "torn" at its four seats %s' % (P('לא', 'תאכלו', 'כל', 'נבלה'), [s for s, x, _ in LEMT('5038', books=T) if s.startswith('Deut')], SH(D14(21), ('Lev', 17, 15)), SH(D14(21), ('Exod', 22, 30)), V(OR_SEATS)))
        move('the Sifrei 104:1 (read whole at the reading); Mishnah Chullin 4:4 at Chullin 72b:1-7 (read whole at the docket); cold_run_sanctions (CALL) — SA.carcass(slaughtered) = %s, (impure_species) = %s; cold_run_ordinances (CALL) — OR.torn(cannot_live) = %s' % (V(SA_SLAUGHTERED), V(SA_SPECIES), V(OR_LIVE)), "'ANY CARCASS' — the torn included (104:1): 'any' brings in the torn animal that died; THE TORN'S SLAUGHTER PURIFIES — a torn animal slaughtered has no carcass impurity (Mishnah Chullin 4:4 at 72b:1-7; sanctions.carcass 'slaughtered' by CALL — R. Yehuda: 'carcass' excludes the slaughtered; the impure species by CALL: a species that has a torn-state is meant); THE BAN'S SEAT NAMED BY THE SANCTIONS ENGINE ITSELF — its lashed cell reads 'the ban is Deut 14:21 / Exod 22:30'; Leviticus 17:15 writes the impurity, not the ban")
        dat('THE WRITE carcass_eating_barred — a BLOCK on israel_people at the counter\'s day %s (DF2, DF4): the ban with no effect of its own before this sitting (the sanctions engine names 14:21; the one database on Israel %r); the readback row 14:21 EXPANDED WITH ITS WRITE (the kin by CALL — sanctions.carcass, ordinances.torn, priesthood.holy_food, calendar.kid_in_milk); the torn\'s slaughter a DATA row' % (CLOCK['counter'], FOOD_SCAN))
        return out("any carcass, the torn (14:21) — 'you shall not eat any carcass' the ban's own seat (the sanctions engine's lashed cell names it): THE WRITE carcass_eating_barred — a BLOCK on Israel at the chapter's own day; 'any' the torn included (the Sifrei 104:1), the torn's slaughter purifying (Mishnah Chullin 4:4 at 72b); the readback row 14:21 EXPANDED with its write", ['carcass_eating_barred'])
    if ask == 'the_eater_of_the_torn':
        ink('14:21', '"any carcass" — Exodus 22:30\'s "to the dog you shall throw it" %s' % (words('Exod', 22, 30)[-4:],))
        move('cold_run_ordinances (CALL) — OR.torn(lashes) = %s (fx %s); OR.torn(to_the_dog) = %s; Mishnah Makkot 3:2 (the link row)' % (V(OR_LASH), OR_LASH['fx'], V(OR_DOG)), "THE EATER OF THE TORN FLOGGED — Mishnah Makkot 3:2: the eaters of carcass and terefah (torn) among the flogged (ordinances.torn by CALL: lashed); the torn to the dog — benefit permitted (OR.torn 'to_the_dog': as the dog, so any benefit)")
        dat('the exam\'s person the eater of the torn — LASHES (Makkot 3:2; OR.torn by CALL); the torn to the dog the transfer (torn_flesh_to_dogs — the ordinances runner\'s)')
        return out("the eater of the torn (14:21) — among the flogged (Mishnah Makkot 3:2; OR.torn by CALL): lashes; the torn thrown to the dog, its benefit permitted", ['lashes', 'torn_flesh_to_dogs'])
    if ask == 'the_carcass_by_fitness':
        ink('14:21', '"to the sojourner in your gates you may give it that he eat it" — %s (one seat); "the sojourner in your gates" %s' % (P('לגר', 'אשר', 'בשעריך', 'תתננה', 'ואכלה'), P('לגר', 'אשר', 'בשעריך')))
        move('Avodah Zarah 67b:8; Bekhorot 23b:2; Chullin 71a:19 (read whole at the docket); cold_run_sanctions (CALL) — SA.carcass(minimum) = %s' % (V(SA_MIN),), "THE CARCASS DEFINED BY FITNESS FOR A RESIDENT ALIEN — what is fit for the alien is called a carcass; what is unfit for him (putrid from the outset) is not a carcass and does not defile (Avodah Zarah 67b:8; Bekhorot 23b:2; Chullin 71a:19 — R. Shimon ben Lakish); the measure an olive (SA.carcass 'minimum' by CALL)")
        dat('the carcass by fitness a DATA row (the_carcass_by_fitness — Avodah Zarah 67b:8; Bekhorot 23b:2; Chullin 71a:19); the exam\'s person the eater of the putrid carcass — EXEMPT (not a carcass)')
        return out("the carcass by fitness (14:21) — a carcass is what is fit for a resident alien; the putrid, unfit for him, is no carcass (Avodah Zarah 67b:8; Bekhorot 23b:2; Chullin 71a:19): the eater of the putrid carcass exempt", ['exempt'])
    if ask == 'the_four_cell_table':
        ink('14:21', '"to the SOJOURNER in your gates you may GIVE it … or SELL it to a FOREIGNER" — the two verbs over the two persons; "or" %s' % ([x for x in W14(21) if x == 'או'],))
        move('Pesachim 21b:7-8 (read whole at the docket); the Sifrei 104:5-6 (read whole at the reading); the parameter the_carcass_table = %s' % (sorted(CARC),), "THE FOUR-CELL TABLE A PARAMETER — R. Meir: BOTH TO BOTH (given or sold to the resident alien, given or sold to the gentile; the verse states the ordinary cases — 21b:7); R. Yehuda: AS WRITTEN — giving to the alien, selling to the gentile ('since it distinguished, the words are as written' — 21b:8); the Sifrei 104:5-6 the same two arms: recorded, not resolved")
        dat('THE PARAMETER the_carcass_table on file (DF6 — two arms and the precedence: %s); the exam\'s person the one who sells the carcass to the resident alien — accepted (R. Meir\'s arm; R. Yehuda\'s recorded)' % (sorted(CARC),))
        return out("the four-cell table (14:21) — giving and selling over the resident alien and the foreigner: R. Meir both to both / R. Yehuda as written (Pesachim 21b:7-8; the Sifrei 104:5-6): THE PARAMETER the_carcass_table; the one who sells the carcass to the resident alien accepted on R. Meir's arm", ['accepted'])
    if ask == 'the_precedence':
        ink('14:21', '"you may give it that he eat it, OR sell it to a foreigner" — the giving written first; "for you are a holy people" said again %s' % (P('כי', 'עם', 'קדוש', 'אתה', 'ליהוה', 'אלהיך'),))
        move('Pesachim 21b:9 (read whole at the docket); the Sifrei 104:2; cold_run_sanctions (CALL) — SA.carcass(who) = %s; cold_run_holiness (CALL) — HO.gifts(recipients) = %s' % (V(SA_WHO), V(HO_RECIP)), "GIVING TO THE RESIDENT ALIEN COMES FIRST — R. Meir's 'or' (21b:9): you are commanded to sustain the resident alien ('that he may live with you', Leviticus 25:35) and not the gentile — THE RESIDENT ALIEN SUSTAINED: 104:2's first person defined (Onkelos 'the uncircumcised sojourner'); the same person outside 17:15's carcass impurity ('the citizen and the convert', SA by CALL) and outside the gifts (HO.gifts 'recipients' — the poor and the convert, not the resident alien)")
        dat('the precedence a DATA row (the_precedence — Pesachim 21b:9, departure (h) the table\'s third clause); the exam\'s person the one who gives the carcass to the resident alien before the gentile — accepted')
        return out("the precedence (14:21) — giving to the resident alien first, for you are commanded to sustain him (Pesachim 21b:9; Leviticus 25:35): the resident alien of 104:2 defined — sustained, outside the carcass's impurity (SA.carcass 'who' by CALL) and outside the gifts (HO.gifts by CALL); the one who gives him the carcass first accepted", ['accepted'])
    if ask == 'the_sale_clause':
        ink('14:21', '"or SELL it to a foreigner" — the infinitive absolute "sell" %s (the tagger\'s reading of מכר at 14:21 with "tithe" at 14:22)' % (INF_ABS,))
        move('Kiddushin 56b:10; Pesachim 21b:6, 21b:10-11 (read whole at the docket)', "THE SALE CLAUSE THE PARADIGM OF A PERMITTED BENEFIT — R. Abbahu's rule: wherever 'you shall not eat' is written, eating and benefit are barred UNLESS the verse specifies, as here ('sell it to a foreigner' — Pesachim 21b:6, 21b:10-11); the carcass's benefit permitted from its own clause (Kiddushin 56b:10); the torn's from 'to the dog' (Exodus 22:30 — R. Yehuda's torn, 21b:11)")
        dat('the sale clause a DATA row (the_sale_clause — Pesachim 21b:6, 21b:10-11; Kiddushin 56b:10); the exam\'s person the one who benefits from the carcass — accepted (the benefit permitted)')
        return out("the sale clause (14:21) — the paradigm of a permitted benefit: R. Abbahu's rule, eating barred bars benefit unless the verse specifies, as here (Pesachim 21b:6, 21b:10-11; Kiddushin 56b:10): the one who benefits from the carcass accepted", ['accepted'])
    if ask == 'the_sanction':
        ink('14:21', '"you shall not eat any carcass" — the negation at 14:21 %s' % ([x for x in W14(21) if x in NEG],))
        move('cold_run_sanctions (CALL) — SA.carcass(lashes_for_eating) = %s (fx %s; its why names Deut 14:21: %s); Yoma 36b:1 (read whole at the docket); Mishnah Makkot 3:2' % (V(SA_LASH), SA_LASH['fx'], 'Deut 14:21' in SA_LASH['why']), "THE SANCTION CARRIED BY CALL — the sanctions engine's lashed cell: 'Makkot 3:2 — the eater of carcass and torn: the ban is Deut 14:21 / Exod 22:30' (sanctions.carcass 'lashes_for_eating' — departure (e)); THE DISPUTE at Yoma 36b:1 — the eater of a carcass among the transgressions the confession names (R. Meir's arm / the Sages'); the lashes the case's")
        dat('the sanction a DATA row (the_sanction — Yoma 36b:1 a dispute; SA.carcass by CALL the lashes); the exam\'s person the eater of the carcass — LASHES (Makkot 3:2)')
        return out("the sanction (14:21) — the eater of the carcass flogged (Mishnah Makkot 3:2 — sanctions.carcass 'lashes_for_eating' by CALL, its cell naming Deut 14:21 as the ban's seat); the confession's dispute at Yoma 36b:1: lashes", ['lashes'])
    if ask == 'the_customs_bar':
        ink('14:21', '"for you are a holy people to the LORD your God" — the clause\'s three seats %s (14:2, 14:21, 7:6)' % (HOLY_PEOPLE,))
        move('the Sifrei 104:7 (read whole at the reading); Pesachim 50b:1, 50b:11, 51a:10-11 (read whole at the docket)', "THE CUSTOM'S BAR — 'sanctify yourself in what is permitted to you' (104:7); the fathers' custom binds the sons (Pesachim 50b:1 — the people of Beishan and the Sidon-Tyre road; 50b:11); its direction the Land over Babylonia (51a:10-11 — one who goes from a place that forbids to a place that permits keeps the stringency): a bar beside the law, not the law's arm")
        dat('the custom\'s bar a DATA row (the_customs_bar — Pesachim 50b:1, 50b:11, 51a:10-11; 104:7); the exam\'s person the son who keeps his fathers\' custom — accepted (bound)')
        return out("the custom's bar (14:21) — 'sanctify yourself in the permitted' (the Sifrei 104:7); the fathers' custom binds the sons, its direction the Land over Babylonia (Pesachim 50b:1-11, 51a:10-11): the son who keeps his fathers' custom accepted", ['accepted'])
    if ask == 'the_kids_three_readings':
        ink('14:21', '"YOU SHALL NOT BOIL A KID IN ITS MOTHER\'S MILK" — the clause at its three seats %s; 34:26 = 23:19 token for token %s; "kid" in the Torah %d seats' % (KID_SEATS, V(ER_KID), len([s for s, _, _ in LEMT('1423', books=T)])))
        move('Kiddushin 57b:9 (read whole at the docket); the Sifrei 104:8 (read whole at the reading); Mishnah Chullin 8:4; cold_run_calendar (CALL) — CA.kid_in_milk(cook) = %s, (eat) = %s, (benefit) = %s; cold_run_erection (CALL) — ER.repeats(kid_by_call) = %s' % (CA_COOK[:2], CA_EAT[:2], CA_BENEFIT[:2], V(ER_KIDCALL)), "THE THIRD SEAT'S GAIN IS THE ASSIGNMENT — the school of R. Yishmael: written three times, one for eating, one for benefit, one for cooking (Kiddushin 57b:9; Mishnah Chullin 8:4; the Sifrei 104:8 the three covenants); kid_boiled_in_milk the case kind ON FILE (the census machine-verified the three seats at the calendar's compile) and calendar.kid_in_milk THE CELL — barred on all three by CALL; NO NEW WRITE")
        dat('the kid\'s three readings a DATA row (the_kids_three_readings — the three seats on the DB, DF8; Kiddushin 57b:9); the readback row 14:21 the kid\'s kin by CALL (CA, ER — 34:26 the second seat); the exam\'s person the one who cooks a kid in its mother\'s milk — barred_from_it')
        return out("the kid's three readings (14:21) — written three times (14:21, 23:19, 34:26 — the DB's own count): one for eating, one for benefit, one for cooking (Kiddushin 57b:9; Mishnah Chullin 8:4); calendar.kid_in_milk by CALL barred on all three, NO new write: the one who cooks a kid in its mother's milk barred from it", ['barred_from_it'])
    if ask == 'the_benefit_counter_arm':
        ink('14:21', '"a kid in its mother\'s milk" — the eating from 12:24\'s clause (76:7): "you shall not eat it" at 12:23-25 %s' % (P('לא', 'תאכלנו', books=DT),))
        move('Kiddushin 57b:10; Bekhorot 10a:2; Menachot 101b:6 (read whole at the docket); Chullin 115b:1-3 (carried from chapter 12\'s docket — 76:7, I1)', "THE BENEFIT COUNTER-ARM THREE TIMES — R. Shimon ben Yehuda in R. Shimon's name: meat in milk permitted in benefit, by 'holy men you shall be to Me' (Exodus 22:30) read with 'a holy people' here (57b:10; Bekhorot 10a:2; Menachot 101b:6); the majority bars the benefit from the third seat (Kiddushin 57b:9); THE EATING from 12:24's 'you shall not eat it' (76:7 — I1; Chullin 115b) — the ruling the cell's (CA.kid_in_milk 'benefit' barred), the counter-arm recorded")
        dat('the benefit counter-arm a DATA row (the_benefit_counter_arm — 57b:10; Bekhorot 10a:2; Menachot 101b:6); the exam\'s person the one who benefits from meat cooked in milk — barred_from_it (the ruling; the counter-arm recorded)')
        return out("the benefit counter-arm (14:21) — R. Shimon ben Yehuda permits the benefit by 'holy men' (Kiddushin 57b:10; Bekhorot 10a:2; Menachot 101b:6); the ruling bars it from the third seat (CA.kid_in_milk by CALL): the one who benefits from meat in milk barred from it, the counter-arm recorded", ['barred_from_it'])
    if ask == 'the_fowl_out':
        ink('14:21', '"in its MOTHER\'S milk" — the mother\'s milk excludes the fowl (104:10); "milk" (בחלב) at 14:21 %s' % ([x for x in W14(21) if x == 'בחלב'],))
        move('the Sifrei 104:9-10 (read whole at the reading); Shabbat 130a:11; Chullin 116b:16 (read whole at the docket); Mishnah Chullin 8:4; Yevamot 14a:8', "THE FOWL OUT — 'its mother's milk' excludes the fowl, which has no mother's milk (104:10; Mishnah Chullin 8:4 — R. Akiva: the wild beast and the fowl not by Torah law); R. Yosei HaGelili's locale ate fowl in milk (Shabbat 130a:11; Yevamot 14a:8 — no factions); THE STOMACH'S MILK a secretion, not food — cheese curdled with it permitted (116b:16); R. Akiva's three exclusions (104:9 — the wild beast, the fowl, the unclean)")
        dat('the fowl out a DATA row (the_fowl_out — 104:9-10; Shabbat 130a:11; the stomach\'s milk 116b:16); the exam\'s person the one who cooks fowl in milk — EXEMPT by Torah law (the Sages\' bar recorded)')
        return out("the fowl out (14:21) — 'its mother's milk' excludes the fowl (the Sifrei 104:10; Mishnah Chullin 8:4 — R. Akiva); R. Yosei HaGelili's locale ate it (Shabbat 130a:11); the stomach's milk a secretion (Chullin 116b:16): the one who cooks fowl in milk exempt by Torah law", ['exempt'])
    if ask == 'the_priest_and_the_carcass':
        ink('14:21', '"you shall not eat any carcass" — Leviticus 22:8\'s "a carcass or a torn thing he shall not eat" %s (the priest\'s seat)' % (words('Lev', 22, 8)[:4],))
        move('cold_run_priesthood (CALL) — PR.holy_food(measures) = %s; cold_run_sanctions (CALL) — SA.carcass(effect) = %s' % (str(V(PR_MEAS))[:80], V(SA_EFFECT)), "THE PRIEST AND THE CARCASS — 22:8's 'a carcass or a torn thing he shall not eat, to defile himself by it' the priest's seat (priesthood.holy_food by CALL — the carcass among the measures 'by or a man'); 17:15's impurity for the eater — washes, bathes, impure until evening (SA.carcass 'effect' by CALL): the impurity Leviticus's, the ban Deuteronomy's")
        dat('the priest and the carcass a DATA row (the_priest_and_the_carcass — 22:8 by CALL; 17:15\'s impurity by CALL); the exam\'s person the priest who eats the carcass of a clean bird — impure_until_evening (17:15; 22:8)')
        return out("the priest and the carcass (14:21) — 22:8's priest by CALL (PR.holy_food), 17:15's impurity by CALL (SA.carcass 'effect' — washes, bathes, impure until evening): the priest who eats the carcass of a clean bird impure until evening", ['impure_until_evening'])
    return out('no verdict in span', [FX.NONE])


def the_second_tithe(case, data):
    """F5 — Deut 14:22-23 — THE LINE second_tithe_declared writing second_tithe_owed (a STATUS — NAMED THE SECOND by the shelf, 105:2; the liabilities from the verse's clauses; three conditions for the eating: the wall with its two capacities, the House standing, the year passed no bar; THE EXILE'S ARM — rot / bury; Heaven's property as ruled); the firstling at 14:23 by CALL; 'learn to fear' the ground"""
    del P_[:]
    ask = case['ask']
    if ask == 'named_the_second':
        ink('14:22', '"TITHE, YOU SHALL TITHE all the yield of your seed" — the doubled verb %s (the infinitive absolute "tithe" %s; the starred token at 14:22 %s); the tithe noun\'s Torah seats %d (Genesis 14:20 the first); Numbers 18:21\'s "all the tithe in Israel"' % (P('עשר', 'תעשר'), INF_ABS[1], MARKS(14, 22), len(TITHE_TOKENS)))
        move('the Sifrei 105:2 (read whole at the reading); cold_run_korach (CALL) — KO.the_tithe(tithe_recipient) = %s (fx %s); KO.the_tithe(tithe_to_levites) = %s; cold_run_place_name (CALL) — PN.the_profane_slaughter_the_blood_and_the_gates(the_two_tithes) = %s; the tape (the recon): portion_declared at Num 18:20 (the-levites), tithe_of_the_tithe_commanded at Num 18:25' % (str(V(KO_RECIP))[:60], KO_RECIP[1], str(V(KO_LEVITES))[:50], str(V(PN_TWO))[:60]), "NAMED THE SECOND BY THE SHELF — 'tithe, you shall tithe': this is the second tithe (105:2 — the first is the Levite's, Numbers 18:21-24 by CALL: tithe_granted on the Levites UNMOVED); chapter 12's 'the two tithes' cell (PN by CALL) already holds the pair; the second tithe eaten by its owner before the LORD (14:23), the first given away: THE WRITE second_tithe_owed — a STATUS on Israel, the second tithe's first seat")
        dat('THE WRITE second_tithe_owed — a NEW STATUS on israel_people at the counter\'s day %s (DF2, DF4; the one database on Israel %r); tithe_granted ONE on the Levites UNMOVED (DF5); the readback row 14:22 SUPPLIED AS A LAW WITH THE WRITE (the kin by CALL — korach, temurah; tithe_given Gen 14:20 and vowed Gen 28:20 by kind)' % (CLOCK['counter'], FOOD_SCAN))
        return out("named the second (14:22) — 'tithe, you shall tithe' the second tithe at its first seat (the Sifrei 105:2; the first the Levite's — KO.the_tithe by CALL, tithe_granted unmoved; PN's two tithes by CALL): THE WRITE second_tithe_owed — a STATUS on Israel at the chapter's own day; the readback row 14:22 SUPPLIED AS A LAW with its write", ['second_tithe_owed'])
    if ask == 'the_liabilities':
        ink('14:22', '"all the yield of your SEED that comes out of THE FIELD year by year" — "the yield of your seed" %s; "that comes out" the participle %s; "year by year" %s' % (P('את', 'כל', 'תבואת', 'זרעך'), [(x, m) for x, m in by[('Deut', 14, 22)] if x == 'היצא'], P('שנה', 'שנה')))
        move('the Sifrei 105:1-19 (read whole at the reading); Mishnah Maasrot 1:1, 1:3, 2:4, 4:5-6 (read whole at the docket); cold_run_korach (CALL) — KO.the_tithe(liable_produce) = %s; KO.the_tithe(thresholds) = %s' % (str(V(KO_LIABLE))[:70], str(V(KO_THRESH))[:70]), "THE LIABILITIES FROM THE VERSE'S CLAUSES — 'the yield of your seed' what grows from seed (not mushrooms), 'the field' what goes out to the field, 'year by year' (105:1-19): food, guarded, grown from the ground (Mishnah Maasrot 1:1 — KO by CALL), the seasons of liability (1:3, 2:4), the casual meal before the work is finished exempt (1:5-8; 4:5-6 — the thresholds: the pile smoothed, the wine skimmed, the oil dripped, KO 'thresholds' by CALL)")
        dat('the liabilities a DATA row (the_liabilities — Mishnah Maasrot 1:1, 1:3, 2:4, 4:5-6; korach.the_tithe by CALL); the exam\'s person the one who eats a casual snack before the pile is smoothed — EXEMPT (Maasrot 1:5)')
        return out("the liabilities (14:22) — the yield of your seed, the field, year by year: food, guarded, grown from the ground (the Sifrei 105:1-19; Mishnah Maasrot 1:1 — KO.the_tithe by CALL), the thresholds the pile smoothed (KO 'thresholds'): the one who eats a casual snack before the pile is smoothed exempt", ['exempt'])
    if ask == 'year_by_year':
        ink('14:22', '"year by year" — the doubled noun %s; the tithes\' new year the parameter: %s' % (P('שנה', 'שנה'), sorted(NEWYEAR)))
        move('the Sifrei 105:16-19 (read whole at the reading); Rosh Hashanah 12a:6-9, 12b:9-11 (read whole at the docket); the parameter the_tithes_new_year = %s' % (sorted(NEWYEAR),), "'YEAR BY YEAR' — no tithing from one year's produce for another's (105:16-19; Mishnah Terumot 1:5's rule for the tithe); THE TITHES' NEW YEAR Tishri 1 (Rosh Hashanah 12a:6-9 — 'tithes' plural), the first third the year's mark (12b:9-11), the tree's the fifteenth of Shevat: the parameter the_tithes_new_year")
        dat('year by year a DATA row (year_by_year — the parameter\'s keys %s); the exam\'s person the one who tithes from the new for the old — barred_from_it (no tithe across the years)' % (sorted(NEWYEAR),))
        return out("year by year (14:22) — no tithing from one year's produce for another's (the Sifrei 105:16-19); the tithes' new year Tishri 1 with the first third (Rosh Hashanah 12a:6-9, 12b:9-11 — THE PARAMETER the_tithes_new_year): the one who tithes from the new for the old barred from it", ['barred_from_it'])
    if ask == 'the_wall_two_capacities':
        ink('14:23', '"and you shall eat BEFORE THE LORD YOUR GOD in the place which He will choose to make His name dwell there" — the place formula %d seats in the book; "to make His name dwell there" %s' % (len(PLACE_FORMULA), P('לשכן', 'שמו', 'שם')))
        move('the Sifrei 106:3 (read whole at the reading — I1, checked in MIDDOT.md); Mishnah Zevachim 5:8; Mishnah Maaser Sheni 3:5-7; Makkot 20a:7 and 20a:3; Chullin 68b:13 (read whole at the docket); cold_run_place_name (CALL) — PN.the_profane_slaughter_the_blood_and_the_gates(the_lashes_outside_the_wall) = %s' % (str(V(PN_WALL))[:70],), "THE WALL WITH ITS TWO CAPACITIES — the second tithe eaten within the wall of Jerusalem (106:3 — I1 from the lesser holies; Mishnah Zevachim 5:8; Maaser Sheni 3:5-7); Rabba: THE WALL FOR EATING TORAH LAW, FOR ADMISSION RABBINIC (Makkot 20a:7); the third set of lashes outside (20a:3; Mishnah Makkot 3:3 — PN by CALL); the tithe that left and returned permitted (Chullin 68b:13)")
        dat('the wall\'s two capacities a DATA row (the_wall_two_capacities — Makkot 20a:7; Maaser Sheni 3:5-7); the exam\'s person the one who eats the second tithe outside the wall — LASHES (Mishnah Makkot 3:3)')
        return out("the wall's two capacities (14:23) — within the wall of Jerusalem (the Sifrei 106:3; Mishnah Zevachim 5:8): for eating Torah law, for admission rabbinic (Makkot 20a:7; PN by CALL): the one who eats the second tithe outside the wall lashed", ['lashes'])
    if ask == 'the_house_standing':
        ink('14:23', '"the tithe of your grain, your wine and your oil, AND THE FIRSTLINGS of your herd and your flock" — the pair with 12:17 %s; the shared run with 12:17 %d' % (P('ובכרת', 'בקרך', 'וצאנך'), KINC[23][0][2]))
        move('the Sifrei 106:4 (read whole at the reading — the juxtaposition named, no code); Temurah 21a:17 (read whole at the docket); cold_run_korach (CALL) — KO.the_gifts(firstborn_without_altar) = %s' % (str(V(KO_NOALTAR))[:60],), "THE HOUSE STANDING — the second tithe eaten only while the House stands, from its JUXTAPOSITION with the firstling (106:4 — 'the verse compares', no code): the firstling's flesh as its blood, only while the altar stands (Temurah 21a:17; KO.the_gifts 'firstborn_without_altar' by CALL — Makkot 19a); Tosefta Sanhedrin 3:6 through the Sifrei's note (the export empty)")
        dat('the House standing a DATA row (the_house_standing — 106:4 the juxtaposition; Temurah 21a:17); the exam\'s person the one who eats the second tithe in Jerusalem with no Temple standing — barred_from_it')
        return out("the House standing (14:23) — the second tithe eaten only while the House stands, from its juxtaposition with the firstling (the Sifrei 106:4; Temurah 21a:17; KO.the_gifts by CALL): the one who eats it in Jerusalem with no Temple standing barred from it", ['barred_from_it'])
    if ask == 'the_year_passed':
        ink('14:23', '"that you may learn to fear the LORD your God ALL THE DAYS" — "all the days" %s' % ([x for x in W14(23) if x in ('כל', 'הימים')],))
        move('the Sifrei 106:5 (read whole at the reading — reread whole at chapter 12\'s sitting); Zevachim 29b:2 (read whole at the docket)', "THE YEAR PASSED NO BAR — a firstling whose year passed is still brought and eaten (106:5; Zevachim 29b:2 — 'all the days': the second tithe and the firstling not disqualified by the passing of their year)")
        dat('the year passed a DATA row (the_year_passed — 106:5; Zevachim 29b:2); the exam\'s person the one who brings the second tithe after its year — accepted')
        return out("the year passed (14:23) — 'all the days': no bar from the passing of the year (the Sifrei 106:5; Zevachim 29b:2): the one who brings the second tithe after its year accepted", ['accepted'])
    if ask == 'the_exiles_arm':
        ink('14:23', '"in the place which He will choose" — the place\'s seats %d; no place without the House' % (len(PLACE_FORMULA),))
        move('Mishnah Maaser Sheni 1:5-6 (read whole at the docket); cold_run_place_name (CALL) — PN.the_place_chosen(the_stations_six_rows) = %s' % (str(V(PN_STATIONS))[:60],), "THE EXILE'S ARM — with no Temple: the second tithe's produce left to rot, the animal bought with its money buried with its hide (Mishnah Maaser Sheni 1:5-6) — THE THIRD STATE, as chapter 12's slaughter law had (departure (d)); the eras table by CALL (the stations' six rows — Shiloh and Jerusalem)")
        dat('the exile\'s arm a DATA row (the_exiles_arm — Maaser Sheni 1:5-6; the eras table by CALL); the exam\'s person the one in exile who buries the second tithe\'s animal with its hide — accepted')
        return out("the exile's arm (14:23) — no Temple: the produce left to rot, the animal buried with its hide (Mishnah Maaser Sheni 1:5-6; the eras table by CALL): the one in exile who buries it with its hide accepted", ['accepted'])
    if ask == 'heavens_property':
        ink('14:23', '"and you shall eat before the LORD your God" — the eating verb in the chapter %d seats' % (sum(1 for v in range(1, 30) for x in W14(v) if x in ('תאכלו', 'תאכל', 'ואכלת')),))
        move('Kiddushin 54b:1-16 (read whole at the docket); Mishnah Maaser Sheni 1:1 (read whole at the docket)', "THE SECOND TITHE HEAVEN'S PROPERTY AS RULED — R. Meir: the second tithe is Heaven's, the Sages: the owner's; the halakha (the ruling) per R. Meir from the preferred tractate (Kiddushin 54b:4); Maaser Sheni 1:1's four bars — not sold, not pledged, not exchanged, not weighed against (the owner eats, does not own)")
        dat('Heaven\'s property a DATA row (heavens_property — Kiddushin 54b:4; Maaser Sheni 1:1); the exam\'s person the one who sells the second tithe — barred_from_it')
        return out("Heaven's property (14:23) — the second tithe Heaven's as ruled (Kiddushin 54b:4 — per R. Meir); not sold, not pledged, not exchanged, not weighed against (Mishnah Maaser Sheni 1:1): the one who sells the second tithe barred from it", ['barred_from_it'])
    if ask == 'the_firstling':
        ink('14:23', '"the firstlings of your herd and your flock" — the pair %s (12:17, 14:23)' % (P('ובכרת', 'בקרך', 'וצאנך'),))
        move('cold_run_ordinances (CALL) — OR.firstling(eighth_and_onward) = %s; cold_run_korach (CALL) — KO.the_gifts(clean_firstborn) = %s; KO.the_gifts(firstborn_eating_window) = %s; Bekhorot 34a:1-35a:22 (read whole at the docket)' % (V(OR_EIGHTH), str(V(KO_CLEAN))[:50], str(V(KO_WINDOW))[:40]), "THE FIRSTLING AT 14:23 BY CALL — the ox, the sheep, the goat not redeemed, holy (Numbers 18:17 — KO.the_gifts 'clean_firstborn'); given on the eighth day and onward (Exodus 22:29 — OR.firstling); eaten two days and a night (KO 'firstborn_eating_window'); THE BLEMISH — Bekhorot 34a-35a: the blemish made by a gentile or by accident permits, one made on purpose does not (Mishnah Bekhorot 5:3)")
        dat('the firstling a DATA row (the_firstling — by CALL: ordinances.firstling, korach.the_gifts; Bekhorot 34a-35a); the exam\'s person the priest who eats the firstling within its window — accepted')
        return out("the firstling (14:23) — holy, not redeemed, given on the eighth day, eaten two days and a night (OR.firstling, KO.the_gifts by CALL; Bekhorot 34a-35a the blemish): the priest who eats the firstling within its window accepted", ['accepted'])
    if ask == 'the_firstling_from_outside':
        ink('14:23', '"the firstlings of your herd and your flock" — "your" herd; the Land\'s' % ())
        move('the Sifrei 106:2 (read whole at the reading); Temurah 21b:3 (read whole at the docket); Tosefta Sanhedrin 3:5 through the Sifrei\'s note (the export empty)', "THE FIRSTLING FROM OUTSIDE THE LAND NOT BROUGHT — a firstling from outside the Land, if it came, is offered; it is not brought from there (106:2; Temurah 21b:3 — R. Yishmael's arm and the Rabbis'); 15:19-23 ahead by CALL when it comes")
        dat('the firstling from outside a DATA row (the_firstling_from_outside — 106:2; Temurah 21b:3); the exam\'s person the one who brings a firstling from Babylonia — EXEMPT (not brought)')
        return out("the firstling from outside (14:23) — not brought from outside the Land (the Sifrei 106:2; Temurah 21b:3): the one who brings a firstling from Babylonia exempt", ['exempt'])
    if ask == 'learn_to_fear':
        ink('14:23', '"THAT YOU MAY LEARN TO FEAR the LORD your God all the days" — the clause %s (one seat); "to fear the LORD" in the book %s' % (P('למען', 'תלמד', 'ליראה', 'את', 'יהוה', 'אלהיך'), P('ליראה', 'את', 'יהוה')))
        move('the Sifrei 106:6 (read whole at the reading); Kiddushin 54b (the link rows)', "'LEARN TO FEAR' — the second tithe eaten in Jerusalem teaches fear: one who stays there sees the priests at their service and the Levites at their song and turns to the fear of Heaven (106:6 — the study); the STATUS's ground — the effect second_tithe_owed carries the clause")
        dat('learn to fear a DATA row (learn_to_fear — 106:6; the effect\'s ground); the exam\'s person the one who eats the tithe in Jerusalem and learns — accepted')
        return out("learn to fear (14:23) — the eating in Jerusalem teaches fear (the Sifrei 106:6): the status's ground; the one who eats the tithe in Jerusalem and learns accepted", ['accepted'])
    return out('no verdict in span', [FX.NONE])


def the_far_place_the_money_the_rejoicing_and_the_levite(case, data):
    """F6 — Deut 14:24-27 — the far place of place not time (12:21's clause by CALL); THE PARAMETER the_moneys_form (R. Yishmael the blank / R. Akiva the imprint; THE POSSESSION CLAUSE); the three moneys; THE CLASS FROM THE FOUR NAMED by general-particular-general (Nazir 35b:3 — the chapter's verse the source of the method); the containers; THE REJOICING (rejoicing_before_the_lord_commanded REUSED — a second entry); THE LEVITE (levite_forsaking_barred REUSED — the ladder of four)"""
    del P_[:]
    ask = case['ask']
    if ask == 'the_far_place':
        ink('14:24', '"AND WHEN THE WAY IS TOO LONG for you, so that you cannot carry it, because the place is too far from you which the LORD your God will choose" — "the way is too long" %s; "the place is too far" %s (12:21, 14:24); the shared run with 12:21 %d; THE ONE "and when" of the chapter %s' % (P('וכי', 'ירבה', 'ממך', 'הדרך'), P('כי', 'ירחק', 'ממך', 'המקום'), TWIN['14:24 vs 12:21'], [x for x in W14(24) if x in ('כי', 'וכי')]))
        move('the Sifrei 107:1-3 (read whole at the reading); cold_run_place_name (CALL) — PN.the_border_enlarged_and_the_altar(too_far) = %s' % (str(V(PN_FAR))[:70],), "THE FAR PLACE — of PLACE not time, ANY distance (even one stride outside the wall — 12:21's cell by CALL: 'when the place is too far from you'), THE RICH TOO (107:1-3 — 'when the LORD blesses you': the redemption for the one who has much); 14:24's twelve tokens with 12:21 in order")
        dat('the far place a DATA row (the_far_place — 107:1-3; 12:21\'s clause by CALL; the one "and when"); the readback row 14:24 VARIANT by CALL; the exam\'s person the rich man whose way is too long — accepted (he redeems)')
        return out("the far place (14:24) — of place not time, any distance, the rich too (the Sifrei 107:1-3; 12:21's clause by CALL — PN.the_border_enlarged_and_the_altar 'too_far'): the rich man whose way is too long accepted", ['accepted'])
    if ask == 'the_moneys_form':
        ink('14:25', '"then you shall turn it into MONEY, and BIND UP the money in your hand" — "turn it into money" %s; "bind up the money in your hand" %s; the binding verb\'s kin Genesis 42:35, 2 Kings 5:23 %s' % (P('ונתתה', 'בכסף'), P('וצרת', 'הכסף', 'בידך'), 'Gen 42:35' in U('וצרת', 'צרור', 'ויצר', 'צררו', 'צרר', 'ויצרו')))
        move('Bava Metzia 47b:5 (read whole at the docket); Mishnah Eduyot 3:2; the Sifrei 107:4 (read whole at the reading — I1); the parameter the_moneys_form = %s' % (sorted(MONEY),), "THE MONEY'S FORM A PARAMETER — R. Yishmael: THE BLANK bound in the hand redeems (a coin without an imprint — Bava Metzia 47b:5); R. Akiva: THE IMPRINT — 'money' with a form, coined (47b:5; Mishnah Eduyot 3:2 — R. Dosa permits the blank, the Sages do not); the coined arm THE ANSWER SHEET'S (Maaser Sheni 1:2), applied five times outside the chapter (Berakhot 47b:10, Eruvin 31b:12, Pesachim 35b:15, Shabbat 128a:3, Bekhorot 51a:6)")
        dat('THE PARAMETER the_moneys_form on file (DF6 — %s); the readback row 14:25 SUPPLIED (the money\'s first seat); the exam\'s person the one who redeems the second tithe with a blank coin — barred_from_it (the answer sheet\'s arm; R. Yishmael\'s recorded)' % (sorted(MONEY),))
        return out("the money's form (14:25) — the blank (R. Yishmael) / the imprint (R. Akiva) at Bava Metzia 47b:5; Mishnah Eduyot 3:2: THE PARAMETER the_moneys_form, the coined arm the answer sheet's; the one who redeems with a blank coin barred from it, R. Yishmael's arm recorded", ['barred_from_it'])
    if ask == 'the_possession':
        ink('14:25', '"and bind up the money IN YOUR HAND" — "in your hand" %s' % ([x for x in W14(25) if x == 'בידך'],))
        move('Mishnah Maaser Sheni 1:2; Bava Kamma 98a:4; Bekhorot 50b:5; Kiddushin 11b:3 (read whole at the docket); the Sifrei 107:5', "THE POSSESSION CLAUSE — 'in your hand': the second tithe is redeemed with money that is coined, current and IN ONE'S POSSESSION (Mishnah Maaser Sheni 1:2); not with money fallen into the sea (Bava Kamma 98a:4); any coinage (Bekhorot 50b:5; Kiddushin 11b:3) — the parameter's third clause (departure (c))")
        dat('the possession a DATA row (the_possession — Maaser Sheni 1:2; Bava Kamma 98a:4); the exam\'s person the one who redeems with money fallen into the sea — barred_from_it')
        return out("the possession (14:25) — 'in your hand': coined, current, in one's possession (Mishnah Maaser Sheni 1:2); not the money in the sea (Bava Kamma 98a:4): the one who redeems with money fallen into the sea barred from it", ['barred_from_it'])
    if ask == 'the_three_moneys':
        ink('14:25-26', '"the money" three times %d in 14:25-26' % (sum(1 for v in (25, 26) for x in W14(v) if x in ('הכסף', 'בכסף')),))
        move('the Sifrei 107:7 (read whole at the reading — I1, checked in MIDDOT.md); Mishnah Maaser Sheni 3:10 (read whole at the docket)', "THREE MONEYS THE LAW'S TABLE — the second tithe's money, the doubtfully-tithed's, the redemption's (107:7 — a fortiori from the tithe itself; Mishnah Maaser Sheni 3:10: what is bought with the tithe's money holds the tithe's sanctity)")
        dat('the three moneys a DATA row (the_three_moneys — 107:7; Maaser Sheni 3:10); the exam\'s person the scholar who counts the three moneys — accepted')
        return out("the three moneys (14:25-26) — the tithe's, the doubtful's, the redemption's (the Sifrei 107:7; Mishnah Maaser Sheni 3:10): the scholar who counts the three moneys accepted", ['accepted'])
    if ask == 'the_class_from_the_four':
        ink('14:26', '"and you shall spend the money FOR WHATEVER YOUR SOUL DESIRES, for cattle or sheep, for wine or strong drink, OR WHATEVER YOUR SOUL ASKS OF YOU" — the general, the four named, the general; "for cattle or sheep, for wine or strong drink" %s; "strong drink" in the Torah %s' % (P('בבקר', 'ובצאן', 'וביין', 'ובשכר'), [(s, x) for s, x, _ in LEMT('7941', books=T)]))
        move('the Sifrei 107:8-11 (read whole at the reading — I6, checked in MIDDOT.md); Bava Kamma 54b:20, 63a:6; NAZIR 35b:3; Eruvin 26b:18, 27b:14; Mishnah Eruvin 3:1; Mishnah Maaser Sheni 1:5, 1:7, 2:1 (read whole at the docket)', "THE CLASS FROM THE FOUR NAMED BY GENERAL-PARTICULAR-GENERAL — 'whatever your soul desires' the general, 'cattle, sheep, wine, strong drink' the particulars, 'whatever your soul asks' the general: only what is like the particulars — fruit from fruit, growing from the ground, whose keeping is by the land (107:8-11; Bava Kamma 54b:20; NAZIR 35b:3 — THE CHAPTER'S VERSE THE SOURCE OF THE METHOD: where the Torah teaches general-particular-general, this is it; the rival amplification-restriction at Eruvin 27b:14); WATER AND SALT OUT (Eruvin 26b:18; Mishnah Eruvin 3:1; Maaser Sheni 1:5, 1:7, 2:1 — not bought with the tithe's money): departure (a) — I6, not the paradigm")
        dat('the class from the four a DATA row (the_class_from_the_four — I6 at Nazir 35b:3, the chapter\'s verse the source of the method; water and salt out); the readback row 14:26 EXPANDED (the reuse; PN by CALL); the exam\'s person the one who buys water and salt with the tithe\'s money — barred_from_it')
        return out("the class from the four (14:26) — general, particular, general: fruit from fruit, growing from the ground, kept by the land (the Sifrei 107:8-11; Bava Kamma 54b:20; NAZIR 35b:3 — the chapter's verse the source of the method): water and salt out (Eruvin 26b:18; Maaser Sheni 1:5); the one who buys water and salt with the tithe's money barred from it", ['barred_from_it'])
    if ask == 'the_containers':
        ink('14:26', '"for wine or strong drink" — the wine and its jar; "and you shall eat there before the LORD your God" %s' % (P('ואכלת', 'שם', 'לפני', 'יהוה', 'אלהיך'),))
        move('the Sifrei 107:12-15 (read whole at the reading); Eruvin 27b:3 (Ben Bag Bag); Mishnah Maaser Sheni 1:3-4, 3:12-13; Mishnah Chullin 1:7 (read whole at the docket)', "THE CONTAINERS — one who buys wine in its jars: the jar is profane where the wine is sold with it (Maaser Sheni 3:12-13); the beast's hide, the bird's feathers profane (1:3-4); Ben Bag Bag on the four names — 'cattle' with its hide, 'sheep' with its fleece, 'wine' with its jar, 'strong drink' after it has fermented (Eruvin 27b:3; 107:12-15); Chullin 1:7's unfermented drink the pair")
        dat('the containers a DATA row (the_containers — Eruvin 27b:3; Maaser Sheni 1:3-4, 3:12-13); the exam\'s person the one who buys wine in its jars — accepted (the jar profane)')
        return out("the containers (14:26) — cattle with its hide, sheep with its fleece, wine with its jar, strong drink fermented (Eruvin 27b:3 — Ben Bag Bag; Mishnah Maaser Sheni 1:3-4, 3:12-13): the one who buys wine in its jars accepted", ['accepted'])
    if ask == 'the_rejoicing':
        ink('14:26', '"and you shall eat there before the LORD your God AND REJOICE, YOU AND YOUR HOUSEHOLD" — "rejoice, you and your household" %s (one seat); "you shall rejoice" in the book %s (12:7, 12:12, 12:18 before; 16:11, 16:14, 26:11, 27:7 ahead)' % (P('ושמחת', 'אתה', 'וביתך'), REJOICE))
        move('the Sifrei 107:16 (read whole at the reading — I2 with 27:7 ahead, checked in MIDDOT.md); cold_run_place_name (CALL) — PN.the_place_chosen(eat_there_and_rejoice) = %s; PN.the_place_chosen(the_womans_rejoicing) = %s; the tape (the recon): place_chosen_declared at Deut 12:5 (israel — FOUND by kind and first verse)' % (str(V(PN_REJOICE))[:60], str(V(PN_WOMAN))[:60]), "THE REJOICING REUSED — 12:7's status on Israel (law_place_name's write) written A SECOND TIME at the second tithe's eating (14:26 'rejoice, you and your household'): 107:16 — 'rejoice' here and 'rejoice' at 27:7 with the peace offerings — the rejoicing is with peace offerings (I2 ahead, recorded); the woman's rejoicing chapter 12's two-arm parameter by CALL; 8b's lesson: a reused effect is a second entry on the same ledger (DD2's and Q32's ONE retyped TWO)")
        dat('THE REUSE rejoicing_before_the_lord_commanded — a SECOND ENTRY on israel_people at the counter\'s day %s on the line second_tithe_declared (DF2; REUSE_SCAN %r); the readback row 14:26 EXPANDED in kind (place_chosen_declared Deut 12:5) with the cell by CALL' % (CLOCK['counter'], REUSE_SCAN))
        return out("the rejoicing (14:26) — 'rejoice, you and your household' at the second tithe's eating: rejoicing_before_the_lord_commanded REUSED — a second entry on Israel (12:7's the first; PN.the_place_chosen by CALL); the peace offerings by I2 with 27:7 ahead (the Sifrei 107:16)", ['rejoicing_before_the_lord_commanded'])
    if ask == 'the_levites_ladder':
        ink('14:27', '"AND THE LEVITE who is in your gates, YOU SHALL NOT FORSAKE HIM, for he has no portion or inheritance with you" — "the Levite who is in your gates" %s (12:18, 14:27, 16:11); "he has no portion or inheritance with you" %s (14:27, 14:29); "portion and inheritance" the Bible\'s %d; the shared run with 12:19 %d (no token — the reuse by the law, not the words)' % (P('והלוי', 'אשר', 'בשעריך'), P('כי', 'אין', 'לו', 'חלק', 'ונחלה', 'עמך'), len(PORTION), SH(D14(27), ('Deut', 12, 19))))
        move('the Sifrei 108:1 (read whole at the reading); cold_run_place_name (CALL) — PN.the_profane_slaughter_the_blood_and_the_gates(lest_you_forsake_the_levite) = %s; PN(the_levites_scope) = %s; cold_run_second_tablets (CALL) — ST.the_levites_separated(levi_has_no_portion) = %s; cold_run_korach (CALL) — KO.the_tithe(no_inheritance) = %s; the tape (the recon): portion_declared at Num 18:20 (the-levites)' % (str(V(PN_LEVITE))[:50], str(V(PN_SCOPE))[:50], str(V(ST_PORTION))[:50], str(V(KO_NOINH))[:50]), "THE LADDER OF FOUR — 'you shall not forsake him' a status with four sources: 10:9 (the Levites separated — ST by CALL), 12:12 and 12:19 (PN by CALL — 'all your days' even in sabbaticals, 'on your land' not in the exile), Numbers 18:20-24 (KO by CALL — portion_declared on the tape; inheritance_barred and tithe_granted the Levites' entries UNMOVED), 14:29 the fourth (108:1); levite_forsaking_barred REUSED — 12:19's block on Israel written A SECOND TIME at 14:27 (a second entry; DD2's and Q32's ONE retyped TWO, the blocks 4 -> 5)")
        dat('THE REUSE levite_forsaking_barred — a SECOND ENTRY on israel_people at the counter\'s day %s on the line second_tithe_declared (DF2; REUSE_SCAN %r); tithe_granted and inheritance_barred ONE each on the Levites UNMOVED (DF5); the readback row 14:27 VERBATIM in kind (portion_declared Num 18:20) with the cells by CALL' % (CLOCK['counter'], REUSE_SCAN))
        return out("the Levite's ladder (14:27) — 'you shall not forsake him' with four sources (10:9, 12:12, 12:19, Numbers 18:20-24 by CALL — ST, PN, KO; 14:29 the fourth; the Sifrei 108:1): levite_forsaking_barred REUSED — a second entry on Israel (12:19's the first)", ['levite_forsaking_barred'])
    if ask == 'shiloh_and_the_house':
        ink('14:25', '"and go to THE PLACE which the LORD your God will choose" — the formula %s (one seat with "go"); the place formula in the book %d' % (P('והלכת', 'אל', 'המקום', 'אשר', 'יבחר', 'יהוה', 'אלהיך', 'בו'), len(PLACE_FORMULA)))
        move('the Sifrei 107:6 (read whole at the reading); cold_run_place_name (CALL) — PN.the_place_chosen(the_place_which_the_lord_will_choose) = %s; PN.the_place_chosen(the_stations_six_rows) = %s' % (str(V(PN_PLACE))[:60], str(V(PN_STATIONS))[:60]), "SHILOH AND THE ETERNAL HOUSE — 'the place which He will choose' is Shiloh and the House of Eternity (107:6): THE ERAS TABLE BY CALL (the stations' six rows — chapter 12's cell reads them, this chapter reads the cell); the formula's fourth and fifth seats here (14:23-25)")
        dat('Shiloh and the House a DATA row (shiloh_and_the_house — 107:6; the eras table by CALL); the readback rows 14:23 and 14:25 the formula\'s seats by CALL; the exam\'s person the one who brings the tithe to Shiloh in its era — accepted')
        return out("Shiloh and the House (14:25) — the place which He will choose: Shiloh and the House of Eternity (the Sifrei 107:6; the eras table by CALL — PN.the_place_chosen): the one who brings the tithe to Shiloh in its era accepted", ['accepted'])
    return out('no verdict in span', [FX.NONE])


def the_third_year(case, data):
    """F7 — Deut 14:28-29 — THE LINE third_year_tithe_declared writing poor_tithe_owed (a STATUS — one tithe not two, the Levite never interrupted); THE PARAMETER the_removal_date (the eve of the last festival day of Passover of the fourth and the seventh year; the years by CALL to the cycle); THE PARAMETER the_tithes_new_year (Tishri 1, the first third, Shevat 15); the gifts exempt; the four in want and their measures; the uses barred; the sojourner two persons; Ezra's penalty; the courtyard from 'your gates'; the animal tithe now"""
    del P_[:]
    ask = case['ask']
    if ask == 'one_tithe_not_two':
        ink('14:28', '"AT THE END OF THREE YEARS you shall bring out all the tithe of your yield in that year" — "at the end of three years" %s (2 Kings 18:10 Samaria\'s fall the one kin); the parser\'s [3] %s and the starred token %s; "the tithe of your yield" %s (14:28, 26:12)' % (THREE_YEARS, PARSED[(14, 28)], MARKS(14, 28), P('מעשר', 'תבואתך')))
        move('the Sifrei 109:5, 109:10-11 (read whole at the reading); Rosh Hashanah 12b:1-5 (read whole at the docket); cold_run_korach (CALL) — KO.the_tithe(third_year) = %s; the tape (the recon): portion_declared at Num 18:20' % (str(V(KO_THIRD))[:60],), "ONE TITHE NOT TWO — in the third and the sixth year the poor man's tithe REPLACES the second (109:5, 109:10-11; Rosh Hashanah 12b:1-2 — the second year into the third, 'the year of THE tithe'); THE LEVITE NEVER INTERRUPTED — the first tithe every year: R. Yehuda from 14:29's Levite, R. Eliezer ben Yaakov from the inheritance's juxtaposition (12b:4-5; KO.the_tithe 'third_year' by CALL — already a move there)")
        dat('THE WRITE poor_tithe_owed — a NEW STATUS on israel_people at the counter\'s day %s (DF2, DF4; the one database on Israel %r); the readback row 14:28 SUPPLIED AS A LAW WITH THE WRITE (the kin by CALL — yovel, korach); the Levite\'s first tithe unmoved' % (CLOCK['counter'], FOOD_SCAN))
        return out("one tithe not two (14:28) — the poor man's tithe replaces the second in the third and the sixth year (the Sifrei 109:5, 109:10-11; Rosh Hashanah 12b:1-5), the Levite never interrupted (KO.the_tithe by CALL): THE WRITE poor_tithe_owed — a STATUS on Israel at the chapter's own day; the readback row 14:28 SUPPLIED AS A LAW with its write", ['poor_tithe_owed'])
    if ask == 'the_levite_never_interrupted':
        ink('14:29', '"AND THE LEVITE, because he has no portion or inheritance with you" — "and the Levite shall come" %s (one seat); the clause of 14:27 said again %s' % (P('ובא', 'הלוי'), P('כי', 'אין', 'לו', 'חלק', 'ונחלה', 'עמך')))
        move('Rosh Hashanah 12b:4 (read whole at the docket); cold_run_korach (CALL) — KO.the_tithe(tithe_to_levites) = %s' % (str(V(KO_LEVITES))[:60],), "THE LEVITE NEVER INTERRUPTED — the first tithe is separated every year, the third included: R. Yehuda from 'and the Levite … shall come' (14:29 — he comes for what is his), R. Eliezer ben Yaakov from the juxtaposition to an inheritance ('as an inheritance does not cease, so the first tithe' — 12b:4; KO by CALL: the Levite serves, the Levite takes)")
        dat('the Levite never interrupted a DATA row (the_levite_never_interrupted — Rosh Hashanah 12b:4); the exam\'s person the Levite in the third year — accepted (his first tithe)')
        return out("the Levite never interrupted (14:29) — the first tithe every year, the third too (Rosh Hashanah 12b:4 — R. Yehuda from 'and the Levite shall come', R. Eliezer ben Yaakov from the inheritance): the Levite in the third year accepted", ['accepted'])
    if ask == 'the_removal_date':
        ink('14:28', '"at the END of three years" — "at the end" in the book %s (15:1, 31:10 the seven years\' twins: "at the end of seven years" %s)' % (U('מקצה', 'מקץ', books=DT), SEVEN_YEARS))
        move('the Sifrei 109:1-3 (read whole at the reading — I2 with 31:10, checked in MIDDOT.md); Mishnah Maaser Sheni 5:6 (read whole at the docket); cold_run_korach (CALL) — KO.the_tithe(removal) = %s; the parameter the_removal_date = %s; the calendar\'s keys passover_1 %s, passover_7 %s' % (str(V(KO_REMOVAL))[:70], sorted(REMOVAL), FEST['passover_1'], FEST['passover_7']), "THE REMOVAL'S DATE A CLOCK DATUM — 'at the end of three years' read with 31:10's 'at the end of seven years, at the festival' (I2): the eve of the last festival day of Passover of the fourth and the seventh year the time of removal (Mishnah Maaser Sheni 5:6; 109:1-3); KO.the_tithe 'removal' the first tithe's side; the date rendered by the calendar's own keys (passover_7's eve), never a constant; 26:12 ahead the confession's seat")
        dat('THE PARAMETER the_removal_date on file (DF6 — %s; the eve\'s key passover_7 the calendar\'s); the exam\'s person the one who removes the tithes on the eve of the last festival day of Passover of the fourth year — accepted' % (sorted(REMOVAL),))
        return out("the removal's date (14:28) — the eve of the last festival day of Passover of the fourth and the seventh year (Mishnah Maaser Sheni 5:6; the Sifrei 109:1-3 — I2 with 31:10): THE PARAMETER the_removal_date, the date the calendar's own key; the one who removes the tithes on that eve accepted", ['accepted'])
    if ask == 'the_seventh_year_by_the_cycle':
        ink('14:28', '"in that year" — the third of the count; the kin\'s numbers by the parser: 15:1 %s, 31:10 %s, Exodus 23:10 %s' % (KINNUM[('Deut', 15, 1)], KINNUM[('Deut', 31, 10)], KINNUM[('Exod', 23, 10)]))
        move('the Sifrei 109:4 (read whole at the reading); cold_run_yovel (CALL) — YO.cycle(3) = %s, YO.cycle(6) = %s, YO.cycle(7) = %s, YO.cycle(50) = %s; cold_run_calendar (CALL) — CA.sabbatical(timer) = %s' % (V(YO_C3), V(YO_C6), V(YO_C7), V(YO_C50), CA_TIMER[0]), "THE YEARS BY CALL TO THE CYCLE — the third and the sixth of the count work years (the poor man's tithe's), the seventh THE SABBATH OF THE LAND (yovel.cycle by CALL: no tithe — the seventh year's produce ownerless, 109:4; Exodus 23:10-11 through its spine — calendar.sabbatical 'land released in year 7'); THE CELL READS THE COUNT'S YEAR FROM THE CYCLE, never a constant; on the bare world before the entry the count not begun (the running world's count read at the tape)")
        dat('the seventh year by the cycle a DATA row (the_seventh_year_by_the_cycle — YO.cycle(3, 6, 7, 50) by CALL; CA.sabbatical); the exam\'s person the one who would tithe the seventh year\'s produce — EXEMPT (no tithe in the sabbath of the land)')
        return out("the seventh year by the cycle (14:28) — the third and the sixth work years, the seventh the sabbath of the land (YO.cycle by CALL; CA.sabbatical 'land released in year 7'; the Sifrei 109:4): the one who would tithe the seventh year's produce exempt", ['exempt'])
    if ask == 'the_tithes_new_year':
        ink('14:28', '"in that year" — the year\'s bound; the tithes\' new year the parameter %s; the calendar\'s key rosh_hashanah %s' % (sorted(NEWYEAR), FEST['rosh_hashanah']))
        move('the Sifrei 109:8 (read whole at the reading); Rosh Hashanah 12a:6-9, 12b:9-11, 13a:3-13 (read whole at the docket); Mishnah Rosh Hashanah 1:1; Bekhorot 53b:5', "THE TITHES' NEW YEAR A CLOCK DATUM — Tishri 1 for the tithes (Mishnah Rosh Hashanah 1:1's four new years; 12a:6-9 'tithes' plural — the animal's and the grain's); THE FIRST THIRD — produce that reached a third of its growth before Tishri 1 belongs to the year that closed (12b:9-11; 13a:3 from 31:10's festival of gathering; Joshua's omer (the sheaf) 13a:7-13 — departure (i)); the vegetables by the picking (109:8); the tree's the fifteenth of Shevat")
        dat('THE PARAMETER the_tithes_new_year on file (DF6 — %s; the key rosh_hashanah the calendar\'s); the exam\'s person the one who tithes grain that reached a third before Tishri as the old year\'s — accepted' % (sorted(NEWYEAR),))
        return out("the tithes' new year (14:28) — Tishri 1 with the first third beside it, the tree's the fifteenth of Shevat (Rosh Hashanah 12a:6-9, 12b:9-11, 13a:3; Mishnah Rosh Hashanah 1:1): THE PARAMETER the_tithes_new_year; the one who tithes by the first third accepted", ['accepted'])
    if ask == 'the_gifts_exempt':
        ink('14:28-29', '"and lay it up WITHIN YOUR GATES … the sojourner and the fatherless and the widow who are in your gates" — "in your gates" at 14:28-29 %s; the corner\'s clause 24:19\'s "for the sojourner, the fatherless and the widow" %s' % ([v for v in (28, 29) if 'בשעריך' in W14(v)], P('לגר', 'ליתום', 'ולאלמנה')))
        move('the Sifrei 109:12 (read whole at the reading); cold_run_holiness (CALL) — HO.gifts(recipients) = %s; HO.gifts(window_end) = %s; HO.gifts(copy_23_22) = %s; HO.GIFTS_IMPORT = %s; cold_run_moadim (CALL) — MO.law_moadim(harvest_reaped) -> %s' % (V(HO_RECIP), V(HO_WINDOW), V(HO_COPY), HO_IMPORT, MO_HARVEST[0]['effect']), "THE GIFTS EXEMPT FROM THE TITHE — the gleanings, the forgotten sheaf and the corner owe no tithe (109:12; Leviticus 19:9-10 by CALL — left_for_the_poor the effect; Mishnah Peah 1:6 the window until the smoothing — HO 'window_end'); THE LEVITICUS RUNNER'S IMPORT TABLE ALREADY POINTS AT 14:28 (GIFTS_IMPORT's poor_tithe — the reverse edge on file); 23:22 the Emor copy without the vineyard (HO 'copy_23_22'); the moadim daemon's harvest branch by CALL (the new grain until the omer — 23:14)")
        dat('the gifts exempt a DATA row (the_gifts_exempt — 109:12; HO.gifts by CALL; GIFTS_IMPORT names 14:28); the readback row 14:29 EXPANDED (holiness.gifts, second_tablets by CALL; stranger_love_commanded Deut 10:17 by kind); the exam\'s person the owner who leaves the corner and does not tithe it — left_for_the_poor')
        return out("the gifts exempt (14:28-29) — the corner, the gleanings and the forgotten sheaf owe no tithe (the Sifrei 109:12; HO.gifts by CALL — the window until the smoothing; the import table names 14:28): the owner who leaves the corner and does not tithe it — left for the poor", ['left_for_the_poor'])
    if ask == 'the_four_in_want':
        ink('14:29', '"and the Levite … and the sojourner and the fatherless and the widow who are in your gates SHALL COME AND EAT AND BE SATISFIED" — "the sojourner and the fatherless and the widow" %s (14:29, 16:11, 16:14 — the formula\'s first seat); "shall eat and be satisfied" %s (one seat); the shared run with 14:27 %d, with 24:19 %d' % (FOUR_AT_GATE, P('ואכלו', 'ושבעו'), TWIN['14:29 vs 14:27'], TWIN['14:29 vs 24:19']))
        move('the Sifrei 110:1-2 (read whole at the reading — I3, checked in MIDDOT.md); cold_run_second_tablets (CALL) — ST.the_god_of_gods_and_the_stranger(the_orphan_and_the_widow) = %s; ST(and_you_shall_love_the_stranger) = %s; the tape (the recon): stranger_love_commanded at Deut 10:17 (israel — FOUND by kind and first verse)' % (str(V(ST_ORPHAN))[:60], str(V(ST_LOVE))[:60]), "THE FOUR IN WANT — the Levite, the sojourner, the fatherless and the widow: 'sons of the covenant' the paradigm (110:1-2 — I3: the Levite named first, the others read by his paradigm — members of the covenant in want); 10:18's 'the fatherless and the widow' and 'loves the stranger' by CALL (love_owed on Israel ONE UNMOVED); 24:19's clause ahead (seven tokens in order)")
        dat('the four in want a DATA row (the_four_in_want — 110:1-2 I3; the formula\'s first seat; 14:29 = 14:27 six, 24:19 seven); love_owed ONE UNMOVED (DF5); the exam\'s person the widow at the gate — accepted')
        return out("the four in want (14:29) — the Levite, the sojourner, the fatherless and the widow shall come and eat and be satisfied (the Sifrei 110:1-2 — I3; ST by CALL, stranger_love_commanded Deut 10:17 by kind): the widow at the gate accepted", ['accepted'])
    if ask == 'the_measures':
        ink('14:29', '"and be satisfied" — "sufficient for his lack" the measure\'s word ahead (15:8)' % ())
        move('Mishnah Peah 8:5-6; Tosefta Peah 4:2, 4:8-10 (read whole at the docket); cold_run_holiness (CALL) — HO.gifts(poor_defined) = %s' % (V(HO_POOR),), "THE MEASURES AT THE THRESHING FLOOR — not less than half a kav (a measure) of wheat, a kav of barley, a kav and a half of spelt, a kav of dried figs … (Mishnah Peah 8:5); the wanderer's loaf, the lodging and the Sabbath's three meals (8:7; Tosefta Peah 4:8-9); 'sufficient for his lack' — even a horse to ride and a servant to run before him (Tosefta 4:10); 'in the years of the poor man's tithe' (4:2); who is poor — two hundred zuz (Peah 8:8 — HO 'poor_defined' by CALL)")
        dat('the measures a DATA row (the_measures — Mishnah Peah 8:5-6; Tosefta Peah 4:2, 4:8-10); the exam\'s person the poor man given half a kav of wheat at the threshing floor — accepted')
        return out("the measures (14:29) — not less than half a kav of wheat, a kav of barley at the threshing floor (Mishnah Peah 8:5-6; Tosefta Peah 4:2, 4:8-10 — 'sufficient for his lack'; HO.gifts by CALL who is poor): the poor man given half a kav of wheat accepted", ['accepted'])
    if ask == 'the_uses_barred':
        ink('14:29', '"shall come and eat and be satisfied" — eating, the tithe\'s use' % ())
        move('Tosefta Peah 4:16 (read whole at the docket); Yevamot 86a:4', "THE POOR MAN'S TITHE'S USES BARRED — no debt paid from it, no ransom, no wedding gift, no charity from it (Tosefta Peah 4:16 — it is given to eat); its non-separation makes untithed produce (Yevamot 86a:4)")
        dat('the uses barred a DATA row (the_uses_barred — Tosefta Peah 4:16; Yevamot 86a:4); the exam\'s person the poor man who pays a debt from the poor man\'s tithe — barred_from_it')
        return out("the uses barred (14:29) — no debt, no ransom, no wedding gift, no charity from the poor man's tithe (Tosefta Peah 4:16); its non-separation makes untithed produce (Yevamot 86a:4): the poor man who pays a debt from it barred from it", ['barred_from_it'])
    if ask == 'the_convert_at_the_gate':
        ink('14:29', '"and the SOJOURNER (הגר)" — the noun at 14:21 and 14:29; Onkelos 14:29 "the convert" against 14:21 "the uncircumcised sojourner" (the store, read at the reading)' % ())
        move('the Sifrei 110:2 (read whole at the reading); Yevamot 47b:1-19, 86a-86b (read whole at the docket); cold_run_second_tablets (CALL) — ST.the_god_of_gods_and_the_stranger(the_converts_intake) = %s; cold_run_holiness (CALL) — HO.gifts(recipients) = %s' % (str(V(ST_INTAKE))[:60], V(HO_RECIP)), "THE SOJOURNER TWO PERSONS — 14:29's sojourner is the CONVERT (Onkelos; 110:2 — 'the sojourner' among the four in want, a son of the covenant), 14:21's the RESIDENT ALIEN (Onkelos 'the uncircumcised'): THE CELL READS THE NOUN BY ITS SEAT, no parameter; the convert's intake (Yevamot 47a-b — ST by CALL) and the convert among the gifts' recipients (HO by CALL — 'the poor and the convert, not the resident alien')")
        dat('the sojourner two persons a DATA row (the_sojourner_two_persons — 110:2; Onkelos at the two seats; Yevamot 47b, 86a-b); the exam\'s person the convert at the gate — accepted (eats the poor man\'s tithe)')
        return out("the convert at the gate (14:29) — 14:29's sojourner the convert (Onkelos; the Sifrei 110:2), a son of the covenant among the four in want (Yevamot 47b; ST, HO by CALL): the convert at the gate accepted", ['accepted'])
    if ask == 'the_resident_alien_at_the_gate':
        ink('14:21, 14:29', '"to the sojourner in your gates you may give it" (14:21) against "the sojourner … who are in your gates" (14:29) — "in your gates" at both %s' % ([v for v in (21, 27, 28, 29) if 'בשעריך' in W14(v)],))
        move('Pesachim 21b:9 (the resident alien sustained); cold_run_sanctions (CALL) — SA.carcass(who) = %s; cold_run_holiness (CALL) — HO.gifts(recipients) = %s' % (V(SA_WHO), V(HO_RECIP)), "THE RESIDENT ALIEN AT THE GATE — 14:21's person eats the carcass (sustained — Pesachim 21b:9), not the poor man's tithe: outside 'the citizen and the convert' (SA.carcass 'who' by CALL) and outside the gifts' recipients (HO.gifts by CALL — not the resident alien): the two persons by their seats")
        dat('the exam\'s person the resident alien at the gate — EXEMPT from the poor man\'s tithe (14:21\'s person, not 14:29\'s)')
        return out("the resident alien at the gate (14:21, 14:29) — 14:21's person, sustained with the carcass, not among the four in want (SA.carcass 'who', HO.gifts 'recipients' by CALL): the resident alien at the gate exempt from the poor man's tithe", ['exempt'])
    if ask == 'ezras_penalty':
        ink('14:29', '"and the Levite" — the first tithe\'s recipient; Numbers 18:21\'s "to the sons of Levi"' % ())
        move('Yevamot 86a:1, 86a:14, 86b:4-7 (read whole at the docket); cold_run_korach (CALL) — KO.the_tithe(tithe_recipient) = %s; KO.the_tithe(recipients) = %s' % (str(V(KO_RECIP))[:70], str(V(KO_RECIPS))[:60]), "THE FIRST TITHE'S RECIPIENT DISPUTED AND EZRA'S PENALTY ON THE LEVITES — R. Akiva: the Levite alone; R. Elazar ben Azarya: the priest too (Yevamot 86a:1, 86a:14); Ezra penalized the Levites who did not come up with him — the first tithe to the priests (86b:4-7; KO.the_tithe 'tithe_recipient' by CALL — 'the priest too, Ezra's penalty'); the poor man's tithe to the poor, or to priests as poor (86b)")
        dat('Ezra\'s penalty a DATA row (ezras_penalty — Yevamot 86a:1, 86a:14, 86b:4-7; KO by CALL); the exam\'s person the priest who takes the first tithe after Ezra — accepted')
        return out("Ezra's penalty (14:29) — the first tithe's recipient disputed (Yevamot 86a:1, 86a:14), Ezra's penalty on the Levites who did not come up (86b:4-7; KO.the_tithe by CALL): the priest who takes the first tithe after Ezra accepted", ['accepted'])
    if ask == 'the_courtyard_from_your_gates':
        ink('14:29', '"who are IN YOUR GATES shall come and eat" — "in your gates" at 14:29 %s' % ('בשעריך' in W14(29),))
        move('Bava Metzia 88a:1-2 (read whole at the docket); cold_run_korach (CALL) — KO.the_tithe(thresholds) = %s' % (str(V(KO_THRESH))[:70],), "THE LIABILITY BY THE HOUSE OR THE COURTYARD FROM 14:29'S OWN PHRASE — 'in your gates': produce that entered through the courtyard's gate is liable to the tithe (Bava Metzia 88a:1-2 — R. Yannai: untithed produce is not liable until it sees the front of the house, from 26:13's 'I have removed the holy from the house'; R. Yochanan: even the courtyard, from 'in your gates'); the thresholds the pile smoothed (KO 'thresholds' by CALL — departure (g): korach's cell carries the courtyard's arm)")
        dat('the courtyard from "your gates" a DATA row (the_courtyard_from_your_gates — Bava Metzia 88a:1-2; departure (g)); the exam\'s person the one whose produce entered the courtyard through its gate — accepted (liable)')
        return out("the courtyard from 'your gates' (14:29) — the liability by the house (R. Yannai) or the courtyard (R. Yochanan, from 'in your gates') — Bava Metzia 88a:1-2; KO.the_tithe 'thresholds' by CALL: the one whose produce entered the courtyard through its gate accepted as liable", ['accepted'])
    if ask == 'the_animal_tithe_now':
        ink('14:23', '"the firstlings of your herd and your flock" — the herd\'s tithe Leviticus 27:32\'s' % ())
        move('Bekhorot 53b:5 (read whole at the docket); Mishnah Bekhorot 9:1, 9:7; cold_run_temurah (CALL) — TM.tithe(took_ten_of_a_hundred) = %s; TM.tithe(procedure) = %s; cold_run_yovel (CALL) — YO.tithe_naming = %s' % (V(TM_TEN), V(TM_PROC), YO_NAMING), "NO ANIMAL TITHE NOW BY DECREE — the Sages decreed against the animal tithe in the present (Bekhorot 53b:5 — lest one eat it blemished as it is), the cattle tithe's answer sheet with THE TENTH AN ORDINAL (Mishnah Bekhorot 9:1, 9:7; temurah.tithe by CALL — took ten of a hundred: not a tithe; the naming's error yovel.tithe_naming by CALL): a DATA row for temurah's cell (departure (j)), not this runner's law")
        dat('the animal tithe now a DATA row (the_animal_tithe_now — Bekhorot 53b:5; Mishnah Bekhorot 9; TM.tithe, YO.tithe_naming by CALL); the exam\'s person the herdsman today — EXEMPT (the decree)')
        return out("the animal tithe now (14:23) — decreed away in the present (Bekhorot 53b:5); the tenth an ordinal (Mishnah Bekhorot 9:7 — TM.tithe by CALL), the naming's error (YO.tithe_naming): the herdsman today exempt", ['exempt'])
    return out('no verdict in span', [FX.NONE])


def the_readback(case, data):
    """THE TABLE — THE READBACK (THE LOOP's step 6 — the forms on file, no new form): the table's census; the supplied rows (14:1, 14:3, 14:22, 14:28 WITH THEIR WRITES; 14:5, 14:11, 14:20, 14:25 the chapter's own gains) and 14:21 EXPANDED with its write; no pointer row; no retrograde row (no act told only here — measured); the twin diffed on the DB; the verses no one cites"""
    del P_[:]
    ask = case['ask']
    if ask == 'the_table':
        ink('14:1-29', 'twenty-nine verses, twenty-nine rows — one per verse; THE CHAPTER IS LAW FROM ITS FIRST WORD TO ITS LAST — no imperative, no first person, no narrative verb, the one "and when" at 14:24; the register plural for the food laws, singular for the tithe, 14:21 both %s' % (([v for v, (p, s) in NUM.items() if p and not s], [v for v, (p, s) in NUM.items() if s and not p], [v for v, (p, s) in NUM.items() if p and s]),))
        move('THE LOOP.md step 6 — the readback\'s forms T1-T6 on file', "chapter 14 takes the forms already on file: T4 the laws' form — every row graded against the cell that compiles its kin, by CALL (%d rows — every row has kin, 11b's lesson 8); T1 reference rows against the tape's lines by kind and first verse (%d rows); EIGHT rows SUPPLIED — four AS LAWS WITH THEIR WRITES (the code's holes compiled at the chapter's own day), 14:5 the ten named, 14:11 and 14:20 the permission Leviticus lacks, 14:25 the money's first seat; 14:21 EXPANDED with its write; no pointer, no state row, no stretch, no retrograde row — the grades %s" % (sum(1 for r in READBACK if r['cell']), sum(1 for r in READBACK if r['tape_kind']), dict(sorted(RB_GRADES.items()))))
        dat('every reference row\'s entry FOUND (the tape lines by kind and first verse; every kin cell answering) — asserted on the module; no hole, no open row, no stretch, no retrograde row, no state row')
        return out("the table — twenty-nine rows, one per verse: the grades %s; %d on the tape by kind and first verse, %d in the kin's cells by CALL, %d SUPPLIED (four with their writes) and 14:21 EXPANDED with its write; no pointer row, no hole, no open row, no stretch, no state row, no retrograde row" % (dict(sorted(RB_GRADES.items())), sum(1 for r in READBACK if r['tape_kind']), sum(1 for r in READBACK if r['cell']), sum(1 for r in READBACK if r['grade'] == 'SUPPLIED')), ['accepted'])
    if ask == 'the_supplied_rows':
        ink('14:1, 14:3, 14:22, 14:28', 'the four law rows SUPPLIED WITH THEIR WRITES — cuttings_for_the_dead_barred, abomination_eating_barred, second_tithe_owed, poor_tithe_owed; 14:21 EXPANDED with carcass_eating_barred (the writes %s); 14:5, 14:11, 14:20, 14:25 SUPPLIED as the chapter\'s own gains' % ([r['write'] for r in READBACK if r['write']],))
        move("THE LOOP.md step 6 — the SUPPLIED-with-a-write form (9b's lesson 6; 10b's and 11b's law rows the precedent)", "the code's holes compiled at the chapter's own day (40, 11, 1): the writes on Israel at the five lines — four readback rows SUPPLIED AS LAWS with their writes and 14:21 EXPANDED with its write (the ban's seat the sanctions engine names, the kin's cells by CALL); the four other SUPPLIED rows the chapter's gains over the twin (the ten named, the permission twice, the money's form)")
        dat('the SUPPLIED rows %s; the rows with writes %s; no state row this chapter (the chapter law from its first word)' % ([r['verses'] for r in READBACK if r['grade'] == 'SUPPLIED'], [(r['verses'], r['write']) for r in READBACK if r['write']]))
        return out("the supplied rows — 14:1, 14:3, 14:22, 14:28 with their writes (cuttings_for_the_dead_barred, abomination_eating_barred, second_tithe_owed, poor_tithe_owed); 14:21 EXPANDED with carcass_eating_barred; 14:5, 14:11, 14:20, 14:25 the chapter's own gains — eight SUPPLIED rows, the code's five holes compiled at the chapter's own day", ['accepted'])
    if ask == 'no_pointer_row':
        ink('14:1-29', 'no receipt with the Name, no header, no footer, no "as … commanded" in the chapter (the register\'s finder at the reading); the pointer rows %s' % ([r['verses'] for r in READBACK if r['pointer']],))
        move("the dependency census (RUN B's gate — the census decides): no AS_WHEN form in the chapter; the place formula's seats (14:23-25) the cell's own by CALL — no pointer predicted; the priesthood -> holiness_b edge on file names Deut 14:1 already (a teacher's seat before the compile)", "no pointer row — the register's finder found no receipt, no header, no footer (DECLARED 98 UNMOVED — the block's two declarations gone at 11b, law_food_tithe inside the same block)")
        dat('no pointer row; the register: NO seat in chapter 14 — DECLARED 98 UNMOVED (DF7)')
        return out("no pointer row — no receipt, no header, no footer, no 'as … commanded' in the chapter; the register unmoved (DECLARED 98); the priesthood -> holiness_b edge naming 14:1 a teacher's seat before the compile", ['accepted'])
    if ask == 'no_retrograde_row':
        ink('14:1-29', 'no act told only here — the chapter law from its first word to its last: no narrative verb %s; every act the chapter cites has a line (Abram\'s tenth, Jacob\'s vow, Noah\'s altar, the treasured people, the Levites\' portion, the nations devoted, the stranger loved, the place chosen, the profane slaughter) — measured at the design' % ([v for v in range(1, 30) if any(m and re.search(r'V.w', m) for _, m in by[('Deut', 14, v)])],))
        move("THE LOOP.md step 6 — the retelling rules (a retrograde marker for an act told only in the retelling; none here)", "NO retrograde marker, NO act told only here, NO T2 row, NO state row, NO stretch — the five own-day lines at the counter's day (40, 11, 1), markers 172 UNMOVED")
        dat('no retrograde row; markers UNMOVED (the_counter_and_the_parameters: no_marker %s)' % (CLOCK['no_marker'],))
        return out("no retrograde row — no act told only here (no narrative verb in the chapter); the five own-day lines at the counter's day, no marker, markers 172 unmoved", ['accepted'])
    if ask == 'the_twin_diffed':
        ink('14:6-15', 'THE TWIN DIFFED on the DB — 14:6 vs 11:3 %d (with "two"), 14:7 vs 11:4 %d (11:4-6 folded), 14:8 vs 11:7 %d, 14:9 vs 11:9 %d (twelve of twelve), 14:15 vs 11:16 %d and to the letter %s; 14:2 vs 7:6 %d; 14:24 vs 12:21 %d; 14:29 vs 24:19 %d and vs 14:27 %d; 14:21 vs 23:19 %d' % (TWIN['14:6 vs 11:3'], TWIN['14:7 vs 11:4'], TWIN['14:8 vs 11:7'], TWIN['14:9 vs 11:9'], TWIN['14:15 vs 11:16'], TWIN['14:15 == 11:16'], TWIN['14:2 vs 7:6'], TWIN['14:24 vs 12:21'], TWIN['14:29 vs 24:19'], TWIN['14:29 vs 14:27'], TWIN['14:21 vs 23:19']))
        move('the reading (sitting 12 — the twin diffed verse by verse, the reading\'s lesson 6; the ink block by CALL); Chullin 63a:17-63b:2 (the Gemara\'s own count)', "THE TWIN DIFFED — Deuteronomy 14 against Leviticus 11 verse by verse: 14:15 = 11:16 to the letter, 14:6 = 11:3 with 'two', 14:7 folds 11:4-6, 14:9 twelve of 11:9's twelve, the ra'ah's resh against the da'ah's dalet; the Gemara counts the same lists (twenty, twenty-one, twenty-four): the reading's diff confirmed by the shelf's own arithmetic (DF8)")
        dat('the twin diffed a DATA row on the DB (the_twin_diffed — DF8: %s)' % (TWIN,))
        return out("the twin diffed — 14:15 = 11:16 to the letter (%d shared), 14:6 = 11:3 with 'two' (%d), 14:7 folds 11:4-6 (%d with 11:4), 14:9 twelve of 11:9's twelve; 14:2 = 7:6 %d of nineteen; 14:24 holds 12:21's %d; 14:29 has 24:19's %d and 14:27's %d (the DB's own counts; Chullin 63a:17-63b:2 the Gemara's)" % (TWIN['14:15 vs 11:16'], TWIN['14:6 vs 11:3'], TWIN['14:7 vs 11:4'], TWIN['14:2 vs 7:6'], TWIN['14:24 vs 12:21'], TWIN['14:29 vs 24:19'], TWIN['14:29 vs 14:27']), ['accepted'])
    if ask == 'the_verses_no_one_cites':
        ink('14:9, 14:14-18', 'the verses NO ROW OF THE DOCKET CITES — computed on the ledger: %s (14:9 the water\'s permission, 14:14-18 the birds\' names)' % (UNCITED,))
        move('the docket deu_14_reeh_exam_2026-09-21.md (991 rows — the CITE INDEX; the uncited computed by write_ch14_docket.py); Chullin 66b:6-7 (14:9 read through its twin); Chullin 63a:17-63b:2 (the names counted, not cited)', "THE VERSES NO ONE CITES — 14:9 (the water's permission: read through its twin, Chullin 66b:6-7 — vessels, pits, ditches and caves) and 14:14-18 (the birds' names: the Gemara counts the lists at Leviticus's seat and explains the ra'ah alone): the docket's own arithmetic — a DATA row, no law")
        dat('the verses no one cites a DATA row (the_verses_no_one_cites — %s, computed on the docket)' % (UNCITED,))
        return out("the verses no one cites — %s: 14:9 read through its twin (Chullin 66b:6-7), 14:14-18 the birds' names counted at Leviticus's seat (63a:17-63b:2); the docket's own arithmetic" % (UNCITED,), ['accepted'])
    return out('no verdict in span', [FX.NONE])

