#!/usr/bin/env python3
# DEUTERONOMY 14:1-29 — THE SONS AND THE CUTTINGS, THE FOOD LAW (THE BEASTS, THE WATER, THE BIRDS — THE TWIN CHAPTER LEVITICUS 11 BY CALL), THE CARCASS AND THE
# KID, THE SECOND TITHE WITH THE FAR PLACE, THE MONEY, THE REJOICING AND THE LEVITE, THE THIRD YEAR'S TITHE; THE READBACK'S FORMS ON FILE, NO NEW FORM (THE
# DEUTERONOMY WALK sitting 12b, 2026-09-22; World/step9/DEUTERONOMY_WALK.md "Sitting 12b"; the state doc's #205). THE CODE'S FIVE HOLES compiled at the counter's
# day (40, 11, 1), FIVE own-day lines, NO marker: the sons and the cuttings (14:1-2 — cuttings_for_the_dead_barred a BLOCK: the cut and the factions from one word,
# the baldness by the analogy run both ways with the priests'), the food law (14:3-20 — abomination_eating_barred a BLOCK over the twin chapter's classifier by
# CALL; the ten named and no more, the four closed by 'it', the fetus from 14:6's own words; the_birds_signs a PARAMETER in three layers — the code/data separation
# law's own case), the carcass and the kid (14:21 — carcass_eating_barred a BLOCK, the ban's seat named by the sanctions engine itself; the_carcass_table a PARAMETER
# with the precedence; the kid NO NEW WRITE — the third seat's gain the assignment, calendar.kid_in_milk by CALL), the second tithe (14:22-27 — second_tithe_owed
# a STATUS: the liabilities, the wall's two capacities, the House standing, the exile's arm; the_moneys_form a PARAMETER with the possession clause; the class
# from the four named by general-particular-general — Nazir 35b:3 the chapter's verse the source of the method; rejoicing_before_the_lord_commanded and
# levite_forsaking_barred REUSED — second entries), the third year (14:28-29 — poor_tithe_owed a STATUS: one tithe not two, the Levite never interrupted;
# the_removal_date and the_tithes_new_year CLOCK DATA, the count's year by CALL to the cycle). THE KIN'S CELLS BY CALL (eighteen runners); THE TAPE'S LINES BY
# KIND (Abram's tenth, Jacob's vow, Noah's altar, the treasured people, the Levites' portion, the nations devoted, the stranger loved, the place chosen, the
# profane slaughter). Seven cells and the table; every token probed (zero-report law); effects on every cell (the effects law); the DATA rows the docket added.
# The daemon law_food_tithe given_at Deut 14:1, installed_by boot (the Deuteronomy daemons' form). Reading ledger: logic/oral_triage/deu_14_reeh_2026-09-21.md;
# the exam's docket: deu_14_reeh_exam_2026-09-21.md (991 rows — 771 READ WHOLE in two runs, 220 carried with their ledgers' own verdicts: LAW 188 / DERIVATION 394
# / DISPUTE 117 / CONTEXT 109 / OUTSIDE 183).

# ---- THE HONEST-PAIRING GUARD ----------------------------------------------------------------------------
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..'))   # THE PORTABLE REPO: the repo root from this file's own place
from compile_guards import check_honest_pairing as _chp
_P = _os.path.abspath(__file__)
GUARDED = _chp(_P, 'CASES', 2)
assert GUARDED == 0, ("the guard counted %d expectations, the tripwire holds 0" % GUARDED)   # RETYPED after the generator (the cells' asks summed)
print('guard: %d expectations checked, every one a literal from the answer sheet [honest-pairing guard satisfied]' % GUARDED)
import sqlite3, sys, io, re, contextlib, collections, unicodedata, yaml
from collections import Counter
import effects_layer as FX
import world_engine as WE
import cold_run_shemini as SHM                 # THE EDGE: food_tithe -> shemini CALL, reference (14:3-20 THE TWIN CHAPTER'S CLASSIFIER — the beasts' two signs, the water's two, the birds by name; the four the classifier's own exception rows; 14:8's carcass touched)
import cold_run_sanctions as SA                # THE EDGE: food_tithe -> sanctions CALL, reference (14:21's carcass ban named by the sanctions engine's own lashed cell — 'the ban is Deut 14:21 / Exod 22:30'; the lashes by CALL)
import cold_run_calendar as CA                 # THE EDGE: food_tithe -> calendar CALL, reference (14:21's kid the third seat — cook, eat, benefit; 14:28's seventh year the sabbatical's timer)
import cold_run_erection as ER                 # THE EDGE: food_tithe -> erection CALL, reference (34:26 the kid's second seat across files)
import cold_run_ordinances as OR               # THE EDGE: food_tithe -> ordinances CALL, reference (Exodus 22:30's torn — to the dogs; 14:23's firstlings)
import cold_run_priesthood as PR               # THE EDGE: food_tithe -> priesthood CALL, reference (21:5's baldness per spot and the whole head — the analogy both ways; 22:8's priest and the carcass)
import cold_run_holiness as HO                 # THE EDGE: food_tithe -> holiness CALL, reference (19:9-10's gifts — left_for_the_poor; GIFTS_IMPORT names 14:28 already)
import cold_run_holiness_b as HB               # THE EDGE: food_tithe -> holiness_b CALL, reference (19:27-28's cuttings for a soul — 14:1's kin)
import cold_run_moadim as MO                   # THE EDGE: food_tithe -> moadim CALL, reference (23:22's harvest left for the poor and the stranger)
import cold_run_temurah as TM                  # THE EDGE: food_tithe -> temurah CALL, reference (27:32's tenth an ordinal; the cattle tithe's answer sheet; no animal tithe now by decree)
import cold_run_korach as KO                   # THE EDGE: food_tithe -> korach CALL, reference (Numbers 18's first tithe — the second named against it; the Levites' portion; the courtyard's liability)
import cold_run_yovel as YO                    # THE EDGE: food_tithe -> yovel CALL, reference (the sabbatical cycle — the third and the sixth year the poor man's, the seventh exempt)
import cold_run_seven_nations as SN            # THE EDGE: food_tithe -> seven_nations CALL, reference (7:6's holy people — 14:2 and 14:21's clause; treasured_people unmoved)
import cold_run_second_tablets as ST           # THE EDGE: food_tithe -> second_tablets CALL, reference (10:9's Levites separated; 10:18's stranger, fatherless and widow)
import cold_run_place_name as PN               # THE EDGE: food_tithe -> place_name CALL, reference (12:5-14's place chosen — the formula's fourth and fifth seats; 12:15-19's gates; 12:21's far clause; the two reuses)
import cold_run_primeval as PV                 # THE EDGE: food_tithe -> primeval CALL, reference (Genesis 14:20's tithe_given — Abram's tenth; 8:20's clean beasts)
import cold_run_mamre as MM                    # THE EDGE: food_tithe -> mamre CALL, reference (Genesis 28:20-22's vowed — Jacob's tithe, the debit open)
import cold_run_seducers as SE                 # THE EDGE: food_tithe -> seducers CALL, reference (13:1's word sealed — the block's header; the tape's last Deuteronomy 13 line the five new lines' predecessor)

HERE = _os.path.dirname(_os.path.abspath(__file__))
# ONE copy of the numeral parser: the sequence runner's INK block executed here (the stitcher's way — no import edge)
_SRC = open(_os.path.join(HERE, 'cold_run_sequence.py'), encoding='utf-8').read()
_INK = {'re': re, 'sqlite3': sqlite3, 'os': _os, 'WE': WE}
_INK['_ROOT'] = _ROOT   # THE PORTABLE REPO (2026-09-15): the INK block reads the store through the root; the exec'd namespace must carry it
exec(_SRC.split('# ==== INK BEGIN')[1].split('# ==== INK END ====')[0].split('\n', 1)[1], _INK)
ink_numbers, ink_ordinals, verse_words = _INK['ink_numbers'], _INK['ink_ordinals'], _INK['verse_words']

db = sqlite3.connect((_ROOT + '/Data/tanakh.sqlite'))
def plain(w): return ''.join(c for c in w if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
def pointed(w): return ''.join(c for c in w if c != '/' and not (0x0591 <= ord(c) <= 0x05AF))
def NF(s): return unicodedata.normalize('NFC', s)
_rows = db.execute("SELECT v.book, v.chapter, v.verse, w.he, w.morph, w.lemma, w.wtype FROM words w JOIN verses v ON w.verse_id=v.id ORDER BY v.id, w.idx").fetchall()
by, byp, byl, byw, byraw = {}, {}, {}, {}, {}
for _b, _c, _v, _he, _m, _lem, _wt in _rows:
    by.setdefault((_b, _c, _v), []).append((plain(_he), _m)); byp.setdefault((_b, _c, _v), []).append(pointed(_he)); byl.setdefault((_b, _c, _v), []).append((_lem or '').split('/')[-1].strip()); byw.setdefault((_b, _c, _v), []).append(_wt); byraw.setdefault((_b, _c, _v), []).append(_lem or '')
T = ('Gen', 'Exod', 'Lev', 'Num', 'Deut')
def words(b, c, v): return [x for x, _ in by[(b, c, v)]]
def morphs(b, c, v): return [m for _, m in by[(b, c, v)]]
def wm(b, c, v): return list(zip(words(b, c, v), morphs(b, c, v)))
def hits(sub, books=None, exact=False): return sorted({f'{b} {c}:{v}' for (b, c, v), ws in by.items() if (books is None or b in books) and any((x == sub) if exact else (sub in x) for x, _ in ws)})
def phrase(seq, books=T):
    out_ = []
    for (b, c, v), ws in by.items():
        if books is not None and b not in books: continue
        w = [x for x, _ in ws]
        if any(w[i:i + len(seq)] == list(seq) for i in range(len(w) - len(seq) + 1)): out_.append(f'{b} {c}:{v}')
    return sorted(out_)
def P(*seq, books=None): return phrase(list(seq), books)
def S_(*x): return sorted(x)
def U(*toks, books=None): return sorted(set(s for t in toks for s in hits(t, books, True)))
def LEMT(lem, books=None): return [(f'{b} {c}:{v}', x, m) for (b, c, v), ws in by.items() if (books is None or b in books) for (x, m), l in zip(ws, byl[(b, c, v)]) if l == lem]
def LEMV(lem, books=None): return sorted({s for s, _, _ in LEMT(lem, books)})
def lemma_of(b, c, v, tok): return [l for (x, m), l in zip(by[(b, c, v)], byl[(b, c, v)]) if x == tok]
def W14(v): return words('Deut', 14, v)
def PT(b, c, v, tok): return [NF(x) for x in byp[(b, c, v)] if plain(x) == tok]
def SEAT(s): b, cv = s.split(); c, v = map(int, cv.split(':')); return (b, c, v)
def DIFF(a, b_):
    import difflib
    A, B = words(*a), words(*b_)
    return [(op, A[i1:i2], B[j1:j2]) for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, A, B).get_opcodes() if op != 'equal']
def SHARED(a, b_):
    import difflib
    A, B = words(*a), words(*b_)
    m = difflib.SequenceMatcher(None, A, B).find_longest_match(0, len(A), 0, len(B))
    return A[m.a:m.a + m.size]
def SHN(a, b_):
    import difflib
    A, B = words(*a), words(*b_)
    return sum(i2 - i1 for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, A, B).get_opcodes() if op == 'equal')
def LEN(b, c, v): return len(words(b, c, v))
def verse_text(ch, vs, book='Deut'): return ' '.join(words(book, ch, vs))
D14 = lambda v: ('Deut', 14, v)
NEG = ('לא', 'ולא')   # (not; and not)
NAME = ('יהוה', 'ליהוה', 'ויהוה', 'ביהוה', 'מיהוה')   # (the LORD; to the LORD; and the LORD; in the LORD; from the LORD)
import difflib
def SH(a, b_): return sum(s for _, _, s in difflib.SequenceMatcher(a=words(*a), b=words(*b_)).get_matching_blocks())   # the reading's shared-run measure (the shemini module is SHM)
NV = len({v for (b, c, v) in by if b == 'Deut' and c == 14}); assert NV == 29, NV   # twenty-nine verses in both numberings

P_ = []   # the provenance trail of the case being run
def ink(ref, note):  P_.append(('INK',  'Deut %s — %s' % (ref, note) if not ref[:1].isupper() else '%s — %s' % (ref, note)))
def move(src, note): P_.append(('MOVE', '%s — %s' % (src, note)))
def dat(note):       P_.append(('DATA', note))
def hyp(note):       P_.append(('HYP',  note))     # THE LINK REVIEW LAW: a hypothesis — no teacher; counted apart, never as compiled
def out(verdict, effects):
    """verdict + registry-validated effects (the engine contract)"""
    FX.validate([e for e in effects if e != FX.NONE])
    return verdict, effects, list(P_)

# ---- THE INK, computed (the parser and the tokens; the reading's facts the expectations — every assert PROVEN at the reading, ch14_ink.py — COPIED from the reading's instrument by content markers in three blocks; the store-, shelf- and Onkelos-bound asserts left to the reading; the parser's facts typed from the ink's own asserts) ----
SPAN = [(14, v) for v in range(1, 30)]
def MARKS(c, v): return [t for t in verse_words('Deut', c, v) if t[-1] in '#~^%@|*']
def N(b, c, v): return ink_numbers(verse_words(b, c, v))
NUMS = {v: ink_numbers(verse_words('Deut', 14, v)) for v in range(1, 30)}
ORDS = {v: ink_ordinals(verse_words('Deut', 14, v)) for v in range(1, 30)}
PARSED = {(14, v): n for v, n in NUMS.items() if n}
KINNUM = {k: ink_numbers(verse_words(*k)) for k in [('Deut', 15, 1), ('Deut', 31, 10), ('Exod', 23, 10), ('Lev', 11, 3), ('Lev', 27, 30), ('Num', 18, 21), ('Deut', 26, 12), ('Deut', 12, 17)]}
STARRED = sorted({(c, v, t) for (b, c, v) in by if b == 'Deut' for t in verse_words(b, c, v) if (t.startswith('מעשר') or t.startswith('עשר') or t.startswith('תעשר')) and t[-1] in '#~^%@|*'})
TOKN = sum(len(W14(v)) for v in range(1, 30)); LETN = sum(len(x) for v in range(1, 30) for x in W14(v))
print('THE INK (printed before it is asserted): PARSED %s, ORDS %s, MARKS %s, TOKN %d, LETN %d, KINNUM %s, STARRED %s' % (PARSED, {v: o for v, o in ORDS.items() if o}, {v: MARKS(14, v) for v in range(1, 30) if MARKS(14, v)}, TOKN, LETN, KINNUM, STARRED))
assert PARSED == {(14, 6): [2], (14, 28): [3]} and all(o == [] for o in ORDS.values()) and {v: MARKS(14, v) for v in range(1, 30) if MARKS(14, v)} == {6: ['שתי^'], 22: ['עשר*'], 23: ['מעשר*'], 28: ['שנים*', 'מעשר*']} and TOKN == 351, (PARSED, ORDS, TOKN)   # TWO NUMBER VERSES (14:6 "two hoofs" [2], 14:28 "three years" [3]); THE STARRED TITHE TOKENS at 14:22, 23, 28 (the number word "ten" inside "tithe", marked, no number read); 351 tokens (measured at the reading)
assert KINNUM[('Deut', 15, 1)] == [7] and KINNUM[('Deut', 31, 10)] == [7] and KINNUM[('Exod', 23, 10)] == [6] and KINNUM[('Lev', 11, 3)] == [] and KINNUM[('Lev', 27, 30)] == [] and KINNUM[('Num', 18, 21)] == [], KINNUM   # the reading's parser facts on the kin (15:1's and 31:10's seven, Exodus 23:10's six; the others no number)
assert [(c, v) for c, v, _ in STARRED] == [(12, 17), (14, 22), (14, 23), (14, 28), (26, 12)] or [(c, v) for c, v, _ in STARRED][:4] == [(12, 17), (14, 22), (14, 23), (14, 28)], STARRED   # the starred tithe tokens in the book — 14:22, 23, 28 the chapter's three (12:17 and 26:12 the book's others)
# THE KIN FOUND BY COMPUTATION (the measure's A section, recomputed here so the asserts read the same instrument): the shared distinct tokens outside the stop list, the top eight, the three closest re-scored in order
STOP = set(('את ואת אשר כל וכל על ועל אל ואל '   # (the object marker, and-it, which, all, on, to — the particles)
            'לא ולא כי אם יהוה אלהיך אלהיכם '   # (not, for, if; the LORD, your God)
            'לך לכם בו שם שמה גם מן ממך עד '   # (to you, in it, there, also, from, until)
            'הוא היא אתם אתה אנכי אני לו לה '   # (he, she, you, I, to him, to her)
            'בכל כאשר כן הימים היום אלה האלה '   # (in all, as, so, the days, today, these)
            'בארץ הארץ אשר ואם או פן ופן '   # (in the land, the land, which, and if, or, lest)
            'ואת זה וזה הם המה').split())   # (and-it, this, and this, they, they) — the stopword set glossed piece by piece (the lint's ninety-character window)
ORD = {k: i for i, k in enumerate(by)}
TOK = {k: set(words(*k)) - STOP for k in by}
KINC = {}
for _v in range(1, NV + 1):
    _me = D14(_v); _t = TOK[_me]
    _sc = sorted(((len(_t & TOK[k]), k) for k in by if k != _me and len(_t & TOK[k]) >= 2), key=lambda x: (-x[0], ORD[x[1]]))[:8]
    KINC[_v] = [(f'{k[0]} {k[1]}:{k[2]}', n, SH(_me, k) if i < 3 else None) for i, (n, k) in enumerate(_sc)]
DT = ('Deut',)   # the measure's name for the book alone (the ink's helpers carry T, the Torah)
# ---- THE TWO DIVISIONS AND THE VERSES ----
assert sum(len(W14(v)) for v in range(1, 30)) == 351 and {v: len(W14(v)) for v in (1, 2, 7, 21, 23, 24, 26, 29)} == {1: 12, 2: 19, 7: 26, 21: 23, 23: 25, 24: 23, 26: 22, 29: 24}
# ---- THE INK FACTS (the B print) — THE CHILDREN AND THE CUTS (14:1-2) ----
assert P('בנים', 'אתם', 'ליהוה') == ['Deut 14:1'] and P('בני', 'בכרי') == ['Exod 4:22'] and P('לא', 'תתגדדו') == ['Deut 14:1']   # "you are children of the LORD" ONE seat; "My son, My firstborn" Exodus 4:22
assert [s for s, x, m in LEMT('1413')] == ['1Kgs 18:28', 'Deut 14:1', 'Jer 5:7', 'Jer 16:6', 'Jer 41:5', 'Jer 47:5', 'Mic 4:14', 'Ps 94:21'] and [s for s, x, m in LEMT('1413') if m.startswith('HVr') or m.startswith('HC/Vrw')] == ['1Kgs 18:28', 'Deut 14:1', 'Jer 5:7', 'Jer 16:6', 'Jer 47:5', 'Mic 4:14']   # "cut yourselves" — the Torah's ONE seat; Baal's prophets at Carmel the run's case (1 Kings 18:28)
assert P('קרחה', 'בין', 'עיניכם') == ['Deut 14:1'] and len(LEMT('7144')) == 11 and [s for s, _, _ in LEMT('7144', books=T)] == ['Deut 14:1', 'Lev 21:5'] and P('בין', 'עיניכם') == ['Deut 11:18', 'Deut 14:1'] and P('בין', 'עיניך') == ['Deut 6:8', 'Exod 13:16', 'Exod 13:9'] and U('למת') == ['Deut 14:1', 'Deut 26:14', 'Jer 22:10']   # "baldness" the Torah's two (the priests' 21:5 and this); "between your eyes" THE FRONTLETS' PHRASE (6:8, 11:18; Exodus 13:9, 16) — its fifth seat here; "for the dead" the Torah's two (26:14 ahead)
assert P('ושרט', 'לנפש') == ['Lev 19:28'] and P('קרחה', 'בראשם') == ['Lev 21:5'] and [s for s, _, _ in LEMT('8295')] == ['Lev 21:5', 'Zech 12:3', 'Zech 12:3']   # Leviticus 19:28's cut "for a soul" and 21:5's priests — the kin by CALL
assert P('כי', 'עם', 'קדוש', 'אתה', 'ליהוה', 'אלהיך') == ['Deut 14:2', 'Deut 14:21', 'Deut 7:6'] and P('עם', 'קדוש') == ['Deut 14:2', 'Deut 14:21', 'Deut 7:6'] and P('ובך', 'בחר', 'יהוה') == ['Deut 14:2'] and P('להיות', 'לו', 'לעם', 'סגלה') == ['Deut 14:2', 'Deut 26:18', 'Deut 7:6'] and P('מכל', 'העמים', 'אשר', 'על', 'פני', 'האדמה') == ['Deut 14:2', 'Deut 7:6']   # "a holy people" THREE seats in the Bible — 7:6, 14:2, 14:21: the chapter holds two; 14:2 IS 7:6 with the Name's second "your God" dropped (18 of 19 tokens in order)
assert [s for s, _, _ in LEMT('5459')] == ['1Chr 29:3', 'Deut 7:6', 'Deut 14:2', 'Deut 26:18', 'Eccl 2:8', 'Exod 19:5', 'Mal 3:17', 'Ps 135:4'] and SH(D14(2), ('Deut', 7, 6)) == 18 and SH(D14(2), D14(21)) == 6 and SH(D14(21), ('Deut', 7, 6)) == 6   # "treasure" eight in the Bible, Exodus 19:5 the first; Psalm 135:4 the shelf's own citation at 97:3
# ---- THE ABOMINATION AND THE TEN BEASTS (14:3-5) ----
assert P('לא', 'תאכל', 'כל', 'תועבה') == ['Deut 14:3'] and [s for s, x in [(s, x) for s, x, _ in LEMT('8441', books=DT)] if s.startswith('Deut 14:')] == ['Deut 14:3'] and len(LEMT('8441', books=DT)) == 17 and P('תועבת', 'יהוה', 'אלהיך') == ['Deut 17:1', 'Deut 22:5', 'Deut 23:19', 'Deut 25:16', 'Deut 7:25']   # "abomination" the chapter's one of the book's seventeen; 17:1's blemished offering the twin the shelf reads (99:2)
assert [s for s, _, _ in LEMT('8262')] == ['Deut 7:26', 'Deut 7:26', 'Lev 11:11', 'Lev 11:13', 'Lev 11:43', 'Lev 20:25', 'Ps 22:25'] and len(LEMT('8263')) == 11 and [s for s, _, _ in LEMT('8263') if s.startswith('Lev 11:')] == ['Lev 11:10', 'Lev 11:11', 'Lev 11:12', 'Lev 11:13', 'Lev 11:20', 'Lev 11:23', 'Lev 11:41', 'Lev 11:42']   # Leviticus 11's word is "detestable" (eight seats), this chapter's "abomination" and "unclean" — THE TWIN CHAPTER'S VOCABULARY DIFFERS
assert P('זאת', 'הבהמה', 'אשר', 'תאכלו') == ['Deut 14:4'] and P('זאת', 'החיה', 'אשר', 'תאכלו') == ['Lev 11:2'] and [v for v in range(1, 30) if W14(v)[0] == 'זאת'] == [4] and [v for v in range(1, 30) if W14(v)[0] in ('אלה', 'ואלה', 'וזאת', 'זה', 'וזה')] == [12]   # "this is the beast" against Leviticus 11:2's "this is the living thing" — the list's header; "and this is what you shall not eat" at 14:12 the birds' header
assert P('שור', 'שה', 'כשבים', 'ושה', 'עזים') == ['Deut 14:4'] and P('איל', 'וצבי') == ['Deut 14:5'] and P('כצבי', 'וכאיל') == ['Deut 12:15', 'Deut 15:22'] and U('יחמור', 'ויחמור') == ['1Kgs 5:3', 'Deut 14:5'] and U('אקו', 'ואקו') == ['Deut 14:5'] and U('זמר', 'וזמר') == ['Deut 14:5'] and U('תאו', 'ותאו', 'תוא', 'כתוא') == ['Deut 14:5', 'Ezek 40:21', 'Ezek 40:29', 'Ezek 40:33', 'Ezek 40:36', 'Isa 51:20'] and 'Gen 36:21' in U('דישן', 'ודישן', 'דישון')   # THE SEVEN WILD: the roebuck at Solomon's table (1 Kings 5:3), the wild goat and the mountain-sheep hapax, the antelope Isaiah's net (its letters Ezekiel 40's cells — a homograph), the pygarg a Horite's name (Genesis 36) — THE TEN NAMED HERE AND NOT IN LEVITICUS 11
assert SH(D14(5), ('1Kgs', 5, 3)) == 2 and KINC[5] == [('1Kgs 5:3', 2, 2)] and KINC[4][0] == ('Lev 11:2', 3, 3) and KINC[2][0] == ('Deut 7:6', 11, 18) and KINC[3] == [] and KINC[11] == [] and KINC[17] == [] and KINC[18] == []   # THE KIN BY COMPUTATION: 14:5's one kin in the Bible is Solomon's daily provision; 14:3, 11, 17, 18 have none
# ---- THE TWO SIGNS AND THE FOUR EXCEPTIONS (14:6-8) — LEVITICUS 11 DIFFED ----
assert P('מפרסת', 'פרסה', 'ושסעת', 'שסע') == ['Deut 14:6', 'Lev 11:3'] and P('שתי', 'פרסות') == ['Deut 14:6'] and U('השסועה', 'שסועה') == ['Deut 14:7'] and P('מפרסת', 'פרסה') == ['Deut 14:6', 'Lev 11:26', 'Lev 11:3'] and P('מעלת', 'גרה') == ['Deut 14:6', 'Lev 11:3', 'Lev 11:6'] and P('ממעלי', 'הגרה') == ['Deut 14:7', 'Lev 11:4']   # "two hoofs" ONE seat (the number the parser reads); "the cleft one" ONE seat (14:7 — the shelf's creature, Chullin 60b at the exam)
assert SH(D14(6), ('Lev', 11, 3)) == 9 and SH(D14(7), ('Lev', 11, 4)) == 16 and SH(D14(8), ('Lev', 11, 7)) == 10 and SH(D14(9), ('Lev', 11, 9)) == 12 and SH(D14(15), ('Lev', 11, 16)) == 10 and W14(15) == words('Lev', 11, 16)   # THE TWIN CHAPTER: 14:6 is 11:3 with "two hoofs" for "hoofs"; 14:7 folds 11:4-6's three into one; 14:15 IS 11:16 to the letter
assert P('הגמל', 'ואת', 'הארנבת', 'ואת', 'השפן') == ['Deut 14:7'] and U('החזיר', 'חזיר') == ['Deut 14:8', 'Isa 65:4', 'Isa 66:17', 'Isa 66:3', 'Lev 11:7', 'Neh 10:21', 'Prov 11:22', 'Ps 80:14'] and P('טמא', 'הוא', 'לכם') == ['Deut 14:10', 'Deut 14:19', 'Deut 14:8', 'Lev 11:38', 'Lev 11:4', 'Lev 11:5', 'Lev 11:7'] and P('טמאים', 'הם', 'לכם') == ['Deut 14:7', 'Lev 11:26', 'Lev 11:27', 'Lev 11:8'] and P('מבשרם', 'לא', 'תאכלו', 'ובנבלתם', 'לא', 'תגעו') == ['Deut 14:8', 'Lev 11:8']   # the three chewers in one verse; the swine the Torah's two; "of their flesh … their carcass" 11:8's clause verbatim
# ---- THE WATER, THE BIRDS, THE SWARMING FOWL (14:9-20) ----
assert P('סנפיר', 'וקשקשת') == ['Deut 14:10', 'Deut 14:9', 'Lev 11:10', 'Lev 11:12', 'Lev 11:9'] and P('כל', 'צפור', 'טהרה', 'תאכלו') == ['Deut 14:11'] and P('כל', 'עוף', 'טהור', 'תאכלו') == ['Deut 14:20'] and P('וזה', 'אשר', 'לא', 'תאכלו', 'מהם') == ['Deut 14:12'] and P('ואת', 'אלה', 'תשקצו', 'מן', 'העוף') == ['Lev 11:13']   # the two frames of the birds' list — "every clean bird" before, "every clean fowl" after: THE PERMITTED BIRDS HAVE NO SIGN IN THE INK (the exam's four signs from the shelf)
assert U('והראה') == ['Deut 14:13', 'Eccl 2:24', 'Lev 13:49'] and U('והדאה', 'הדאה', 'דאה', 'דיה', 'והדיה', 'הדיה') == ['Deut 14:13', 'Lev 11:14'] and W14(13) == ['והראה', 'ואת', 'האיה', 'והדיה', 'למינה'] and words('Lev', 11, 14) == ['ואת', 'הדאה', 'ואת', 'האיה', 'למינה']   # THE RA'AH AND THE DA'AH — resh for dalet, one letter (the bird's letters are the verb "see" at Leviticus 13:49 and Ecclesiastes 2:24 — the shelf's own reading of the name, a homograph in the ink); 14:13's three names against 11:14's two: the dayyah added
assert sum(1 for v in range(12, 19) for x in W14(v) if x.startswith('למינ')) == 4 and sum(1 for v in range(13, 20) for x in words('Lev', 11, v) if x.startswith('למינ')) == 4 and W14(16) == ['את', 'הכוס', 'ואת', 'הינשוף', 'והתנשמת'] and words('Lev', 11, 17) == ['ואת', 'הכוס', 'ואת', 'השלך', 'ואת', 'הינשוף'] and W14(17) == ['והקאת', 'ואת', 'הרחמה', 'ואת', 'השלך']   # the order of the names differs at 14:16-17 (the shalach moved, the tinshemet moved, the racham spelled rachamah)
assert P('וכל', 'שרץ', 'העוף', 'טמא', 'הוא', 'לכם') == ['Deut 14:19'] and P('שרץ', 'העוף') == ['Deut 14:19', 'Lev 11:20', 'Lev 11:21', 'Lev 11:23'] and [(x, m) for x, m in by[('Deut', 14, 19)] if x == 'יאכלו'] == [('יאכלו', 'HVNi3mp')] and 'הארבה' in words('Lev', 11, 22) and not any('ארבה' in x for v in range(1, 30) for x in W14(v))   # "they shall not be eaten" the chapter's one third-person form; LEVITICUS 11:21-22'S LOCUSTS ARE NOT IN THIS CHAPTER (the exam's question — Chullin 65a)
assert SH(D14(11), D14(20)) == 2 and P('כל', 'אשר', 'לו', 'סנפיר', 'וקשקשת') == ['Deut 14:9', 'Lev 11:9'] and len([1 for v in range(1, 48) for x in words('Lev', 11, v) if x in ('שקץ', 'ושקץ')]) == 8
# ---- THE CARCASS, THE SOJOURNER AND THE KID (14:21) ----
assert P('לא', 'תאכלו', 'כל', 'נבלה') == ['Deut 14:21'] and [s for s, x in [(s, x) for s, x, _ in LEMT('5038', books=T)] if s.startswith('Deut')] == ['Deut 14:8', 'Deut 14:21', 'Deut 21:23', 'Deut 28:26'] and P('לגר', 'אשר', 'בשעריך', 'תתננה', 'ואכלה') == ['Deut 14:21'] and P('לגר', 'אשר', 'בשעריך') == ['Deut 14:21'] and P('הגר', 'אשר', 'בשעריך') == [] and U('לנכרי') == ['Deut 14:21', 'Deut 23:21']   # "to the sojourner within your gates" ONE seat; "to a foreigner" the Torah's two (23:21's interest ahead)
assert words('Lev', 17, 15)[:5] == ['וכל', 'נפש', 'אשר', 'תאכל', 'נבלה'] and words('Exod', 22, 30)[-4:] == ['תאכלו', 'לכלב', 'תשלכון', 'אתו'] and words('Lev', 22, 8)[:4] == ['נבלה', 'וטרפה', 'לא', 'יאכל'] and SH(D14(21), ('Lev', 17, 15)) == 1 and SH(D14(21), ('Exod', 22, 30)) == 2   # the carcass's three kin verses — none shares a clause with 14:21: THE CARCASS GIVEN, NOT CAST TO THE DOG
assert P('לא', 'תבשל', 'גדי', 'בחלב', 'אמו') == ['Deut 14:21', 'Exod 23:19', 'Exod 34:26'] and words('Exod', 23, 19) == words('Exod', 34, 26) and SH(D14(21), ('Exod', 23, 19)) == 6 and [s for s, _, _ in LEMT('1423', books=T)] == ['Deut 14:21', 'Exod 23:19', 'Exod 34:26', 'Gen 27:9', 'Gen 27:16', 'Gen 38:17', 'Gen 38:20', 'Gen 38:23'] and [v for v in range(1, 30) if 'קדוש' in W14(v)] == [2, 21]   # THE KID IN ITS MOTHER'S MILK — the third and last seat (Exodus 23:19 and 34:26 identical verses); "a holy people" twice in the chapter, the clause before it
assert [(v, x, m) for v in range(1, 30) for x, m in by[('Deut', 14, v)] if m and re.match(r'^H(?:C/)?V.a$', m)] == [(21, 'מכר', 'HVqa'), (22, 'עשר', 'HVpa')]   # THE INFINITIVE ABSOLUTES: "sell" at 14:21 (the tagger's reading of מכר) and "tithe" at 14:22
# ---- THE TITHE AND THE PLACE (14:22-23) ----
assert P('עשר', 'תעשר') == ['Deut 14:22'] and [(s, x) for s, x, _ in LEMT('6237')] == [('1Sam 8:15', 'יעשר'), ('1Sam 8:17', 'יעשר'), ('Deut 14:22', 'עשר'), ('Deut 14:22', 'תעשר'), ('Deut 26:12', 'לעשר'), ('Gen 28:22', 'עשר'), ('Gen 28:22', 'אעשרנו'), ('Neh 10:38', 'המעשרים'), ('Neh 10:39', 'בעשר')] and P('את', 'כל', 'תבואת', 'זרעך') == ['Deut 14:22'] and P('היצא', 'השדה', 'שנה', 'שנה') == ['Deut 14:22'] and P('שנה', 'שנה') == ['Deut 14:22']   # "TITHE, YOU SHALL TITHE" — the verb's doubling ONE seat, Jacob's vow (Genesis 28:22) the form's first seat and the king's tithe (1 Samuel 8) the run's; "year by year" ONE seat (the shelf: not from one year on another)
assert [(s, x) for s, x, _ in LEMT('4643', books=T)][:8] == [('Deut 12:6', 'מעשרתיכם'), ('Deut 12:11', 'מעשרתיכם'), ('Deut 12:17', 'מעשר'), ('Deut 14:23', 'מעשר'), ('Deut 14:28', 'מעשר'), ('Deut 26:12', 'מעשר'), ('Deut 26:12', 'המעשר'), ('Gen 14:20', 'מעשר')] and len(LEMT('4643', books=T)) == 17   # "the tithe" the Torah's seventeen tokens — Abraham's, Leviticus 27's, Numbers 18's, chapter 12's, this chapter's two, 26:12's two
assert P('במקום', 'אשר', 'יבחר', books=DT) == ['Deut 12:14', 'Deut 12:18', 'Deut 14:23', 'Deut 15:20', 'Deut 16:11', 'Deut 16:15', 'Deut 16:16', 'Deut 16:2', 'Deut 16:7', 'Deut 23:17', 'Deut 31:11'] and P('לשכן', 'שמו', 'שם') == ['Deut 12:11', 'Deut 14:23', 'Deut 16:11', 'Deut 16:2', 'Deut 16:6', 'Deut 26:2'] and P('לשום', 'שמו', 'שם') == ['Deut 12:21', 'Deut 14:24'] and P('ואכלת', 'לפני', 'יהוה', 'אלהיך') == ['Deut 14:23']   # THE PLACE FORMULA at its fourth and fifth seats (14:23 "to cause His name to dwell", 14:24 "to put His name") — chapter 12's two forms both reused
assert P('מעשר', 'דגנך', 'תירשך', 'ויצהרך') == ['Deut 14:23'] and P('דגנך', 'ותירשך', 'ויצהרך') == ['Deut 11:14', 'Deut 12:17', 'Deut 7:13'] and P('דגנך', 'תירשך', 'ויצהרך') == ['Deut 14:23', 'Deut 18:4'] and P('ובכרת', 'בקרך', 'וצאנך') == ['Deut 12:17', 'Deut 14:23'] and SH(D14(23), ('Deut', 12, 17)) == 6   # 12:17's list said again with the firstlings — the second tithe and the firstling eaten at the place
assert P('למען', 'תלמד', 'ליראה', 'את', 'יהוה', 'אלהיך') == ['Deut 14:23'] and P('ליראה', 'את', 'יהוה') == ['Deut 10:12', 'Deut 14:23', 'Deut 17:19', 'Deut 31:13', 'Deut 6:24'] and KINC[23][0] == ('Deut 12:17', 6, 6) and KINC[23][1] == ('Deut 16:11', 5, 9)   # "learn to fear" — 4:10's and 17:19's kin; the closest verse in order 16:11's rejoicing
# ---- THE WAY, THE MONEY AND THE REJOICING (14:24-26) ----
assert P('וכי', 'ירבה', 'ממך', 'הדרך') == ['Deut 14:24'] and P('ירבה', 'הדרך') == ['Deut 19:6'] and P('כי', 'ירחק', 'ממך', 'המקום') == ['Deut 12:21', 'Deut 14:24'] and P('כי', 'יברכך', 'יהוה', 'אלהיך') == ['Deut 14:24', 'Deut 16:15'] and [x for x in W14(24) if x in ('כי', 'וכי')] == ['וכי', 'כי', 'כי', 'כי'] and SH(D14(24), ('Deut', 12, 21)) == 12   # THE WAY TOO LONG — 19:6's refuge road the twin; "the place too far" 12:21's clause verbatim (twelve tokens in order): THE FAR PLACE RELEASES THE FLESH THERE AND THE MONEY HERE; four "when/for/because" in one verse
assert P('ונתתה', 'בכסף') == ['Deut 14:25'] and P('וצרת', 'הכסף', 'בידך') == ['Deut 14:25'] and 'Gen 42:35' in U('וצרת', 'צרור', 'ויצר', 'צררו', 'צרר', 'ויצרו') and '2Kgs 5:23' in U('וצרת', 'צרור', 'ויצר', 'צררו', 'צרר', 'ויצרו') and P('והלכת', 'אל', 'המקום', 'אשר', 'יבחר', 'יהוה', 'אלהיך', 'בו') == ['Deut 14:25']   # "bind up the money in your hand" ONE seat (the bundles of Genesis 42:35, Naaman's two talents); THE REDEMPTION INTO MONEY — the shelf's silver with a form (Mishnah Maaser Sheni at the exam)
assert P('בכל', 'אשר', 'תאוה', 'נפשך') == ['1Kgs 11:37', '2Sam 3:21', 'Deut 14:26'] and P('בכל', 'אות', 'נפשך') == ['Deut 12:15', 'Deut 12:20', 'Deut 12:21'] and P('בבקר', 'ובצאן', 'וביין', 'ובשכר') == ['Deut 14:26'] and [(s, x) for s, x, _ in LEMT('7941', books=T)] == [('Deut 14:26', 'ובשכר'), ('Deut 29:5', 'ושכר'), ('Lev 10:9', 'ושכר'), ('Num 6:3', 'ושכר'), ('Num 6:3', 'שכר'), ('Num 28:7', 'שכר')] and P('ובכל', 'אשר', 'תשאלך', 'נפשך') == ['Deut 14:26']   # "whatever your soul desires" — chapter 12's noun three times, this chapter's verb once (Jeroboam's and Abner's the Prophets' two); "strong drink" the Torah's six — the priests' bar, the Nazirite's, the libation's, and HERE PERMITTED
assert P('ושמחת', 'אתה', 'וביתך') == ['Deut 14:26'] and U('ושמחת', 'ושמחתם', books=DT) == ['Deut 12:12', 'Deut 12:18', 'Deut 12:7', 'Deut 14:26', 'Deut 16:11', 'Deut 16:14', 'Deut 26:11', 'Deut 27:7'] and P('ואכלת', 'שם', 'לפני', 'יהוה', 'אלהיך') == ['Deut 14:26'] and KINC[26][0] == ('Deut 27:7', 3, 5)   # "rejoice, you and your household" ONE seat — the book's eight rejoicings, 12:7's "you and your households" the first
# ---- THE LEVITE, THE THIRD YEAR AND THE FOUR (14:27-29) ----
assert P('והלוי', 'אשר', 'בשעריך', 'לא', 'תעזבנו') == ['Deut 14:27'] and P('הלוי', 'אשר', 'בשעריך') == [] and P('והלוי', 'אשר', 'בשעריך') == ['Deut 12:18', 'Deut 14:27', 'Deut 16:11'] and words('Deut', 12, 19) == ['השמר', 'לך', 'פן', 'תעזב', 'את', 'הלוי', 'כל', 'ימיך', 'על', 'אדמתך'] and SH(D14(27), ('Deut', 12, 19)) == 0 and SH(D14(27), ('Deut', 12, 12)) == 7   # 12:19's "lest you forsake the Levite" said again in a new form (no token in order); 12:12's "no portion nor inheritance" the clause reused
assert P('כי', 'אין', 'לו', 'חלק', 'ונחלה', 'עמך') == ['Deut 14:27', 'Deut 14:29'] and P('חלק', 'ונחלה') == ['Deut 10:9', 'Deut 12:12', 'Deut 14:27', 'Deut 14:29', 'Deut 18:1', 'Gen 31:14'] and P('אין', 'לו', 'חלק', 'ונחלה') == ['Deut 12:12', 'Deut 14:27', 'Deut 14:29']   # "portion and inheritance" the Bible's six — Rachel and Leah's the first (Genesis 31:14), the Levite's five (10:9, 12:12, 14:27, 14:29, 18:1)
assert P('מקצה', 'שלש', 'שנים') == ['2Kgs 18:10', 'Deut 14:28'] and U('מקצה', 'מקץ', books=DT) == ['Deut 13:8', 'Deut 14:28', 'Deut 15:1', 'Deut 28:49', 'Deut 28:64', 'Deut 31:10', 'Deut 9:11'] and P('מקץ', 'שבע', 'שנים') == ['Deut 15:1', 'Deut 31:10', 'Jer 34:14'] and P('מעשר', 'תבואתך') == ['Deut 14:28', 'Deut 26:12'] and P('בשנה', 'ההוא') == ['Deut 14:28', 'Gen 26:12', 'Gen 47:17'] and U('והנחת', 'והנחתו', books=DT) == ['Deut 14:28', 'Deut 26:10']   # "AT THE END OF THREE YEARS" — Samaria's fall (2 Kings 18:10) the phrase's one kin; 15:1's "at the end of seven" ahead; "the tithe of your produce" 26:12's clause — THE THIRD YEAR'S TITHE, 26:12 its confession
assert words('Deut', 26, 12) == ['כי', 'תכלה', 'לעשר', 'את', 'כל', 'מעשר', 'תבואתך', 'בשנה', 'השלישת', 'שנת', 'המעשר', 'ונתתה', 'ללוי', 'לגר', 'ליתום', 'ולאלמנה', 'ואכלו', 'בשעריך', 'ושבעו'] and SH(D14(28), ('Deut', 26, 12)) == 6 and KINC[28][0] == ('Deut 26:12', 4, 6)
assert P('והגר', 'והיתום', 'והאלמנה') == ['Deut 14:29', 'Deut 16:11', 'Deut 16:14'] and P('לגר', 'ליתום', 'ולאלמנה') == ['Deut 24:19', 'Deut 24:20', 'Deut 24:21', 'Deut 26:12'] and P('ואכלו', 'ושבעו') == ['Deut 14:29'] and P('ובא', 'הלוי') == ['Deut 14:29']   # THE FOUR AT THE GATE — the formula's first seat (16:11, 16:14 ahead; 24:19-21 and 26:12 the "to" form); "eat and be satisfied" ONE seat in this form
assert P('למען', 'יברכך', 'יהוה', 'אלהיך', 'בכל', 'מעשה', 'ידך') == ['Deut 14:29'] and P('בכל', 'מעשה', 'ידך', books=DT) == ['Deut 14:29', 'Deut 2:7', 'Deut 30:9'] and P('בכל', 'מעשה', 'ידיך', books=DT) == ['Deut 24:19'] and SH(D14(29), ('Deut', 24, 19)) == 7 and KINC[29][0] == ('Deut 14:27', 5, 6)   # "that the LORD may bless you in all the work of your hand" — 24:19's forgotten sheaf the twin (seven tokens in order); 2:7's the first
# ---- THE REGISTER (the D print) ----
NUM = {v: (sum(1 for _, m in by[('Deut', 14, v)] if m and '2mp' in m), sum(1 for _, m in by[('Deut', 14, v)] if m and '2ms' in m)) for v in range(1, 30)}
assert [v for v, (p, s) in NUM.items() if s and not p] == [2, 3, 22, 23, 24, 25, 26, 27, 28, 29] and [v for v, (p, s) in NUM.items() if p and not s] == [1, 4, 6, 7, 8, 9, 10, 11, 12, 19, 20] and [v for v, (p, s) in NUM.items() if p and s] == [21] and [v for v, (p, s) in NUM.items() if not p and not s] == [5, 13, 14, 15, 16, 17, 18]   # THE REGISTER SPLITS THE CHAPTER IN TWO — the food laws PLURAL (14:1, 4-20), the tithe SINGULAR (14:22-29), 14:2-3 singular and 14:21 both (the carcass plural, the sojourner and the kid singular)
assert NUM[1] == (5, 0) and NUM[21] == (1, 5) and NUM[23] == (0, 9) and NUM[26] == (0, 9)
assert [v for v in range(1, 30) if any(m and re.search(r'1c[sp]', m) and m.startswith('HV') for _, m in by[('Deut', 14, v)])] == [] and [v for v in range(1, 30) if any(m and re.search(r'^HV..v', m) for _, m in by[('Deut', 14, v)])] == [] and [v for v in range(1, 30) if any(m and re.search(r'V.w', m) for _, m in by[('Deut', 14, v)])] == [] and [v for v in range(1, 30) if 'לאמר' in W14(v)] == []   # no first person, no imperative, no narrative verb, no "saying", no divine frame — MOSES' VOICE ALONE, and Moses never named
assert {v: [x for x in W14(v) if x in ('כי', 'וכי', 'אם', 'ואם', 'או', 'פן', 'ופן')] for v in range(1, 30) if any(x in ('כי', 'וכי', 'אם', 'ואם', 'או', 'פן', 'ופן') for x in W14(v))} == {2: ['כי'], 7: ['כי'], 8: ['כי'], 21: ['או', 'כי'], 24: ['וכי', 'כי', 'כי', 'כי'], 27: ['כי'], 29: ['כי']} and [v for v in range(1, 30) if W14(v)[0] in ('כי', 'וכי')] == [2, 24]   # NO "IF" IN THE CHAPTER — the one case on "when" (14:24 the way too long); the eight כי the reasons ("for")
assert {v: sum(1 for x in W14(v) if x in ('לא', 'ולא')) for v in range(1, 30) if any(x in ('לא', 'ולא') for x in W14(v))} == {1: 2, 3: 1, 7: 2, 8: 3, 10: 1, 12: 1, 19: 1, 21: 2, 24: 1, 27: 1} and sum(1 for v in range(1, 30) for x in W14(v) if x in ('תאכלו', 'תאכל', 'ואכלת')) == 14   # fifteen negations in ten verses; "you shall eat" fourteen times
assert {v: [x for x in W14(v) if x in ('טמא', 'טמאים', 'הטמא')] for v in range(1, 30) if any(x in ('טמא', 'טמאים', 'הטמא') for x in W14(v))} == {7: ['טמאים'], 8: ['טמא'], 10: ['טמא'], 19: ['טמא']} and {v: [x for x in W14(v) if x in ('טהור', 'טהרה')] for v in range(1, 30) if any(x in ('טהור', 'טהרה') for x in W14(v))} == {11: ['טהרה'], 20: ['טהור']} and [v for v in range(1, 30) if 'בשעריך' in W14(v)] == [21, 27, 28, 29] and len(U('בשעריך', books=DT)) == 16
assert [v for v in range(1, 30) if 'ליהוה' in W14(v)] == [1, 2, 21] and sum(1 for v in range(1, 30) for x in W14(v) if x == 'יהוה') == 8 and [v for v in range(1, 30) if any(W14(v)[i:i + 2] == ['יהוה', 'אלהיך'] for i in range(len(W14(v)) - 1))] == [23, 24, 25, 26, 29] and [(v, x) for v in range(1, 30) for x in W14(v) if x in ('משה', 'ישראל', 'מצרים')] == []   # THE NAME eleven tokens; "the LORD your God" singular five times, plural never; Israel, Egypt, Moses never named
assert {v: [x for x, m in by[('Deut', 14, v)] if m and re.search(r'V.q', m)] for v in (23, 25, 26, 28, 29)} == {23: ['ואכלת'], 25: ['ונתתה', 'וצרת', 'והלכת'], 26: ['ונתתה', 'ואכלת', 'ושמחת'], 28: ['והנחת'], 29: ['ובא', 'ואכלו', 'ושבעו']} and [(x, m) for x, m in by[('Deut', 14, 22)] if x == 'היצא'] == [('היצא', 'HTd/Vqrmsa')]   # the law's consecutive perfects in the tithe's half alone; "that comes forth" the one article-participle

# ---- THE COUNTER'S DAY AND THE FIVE PARAMETERS (a bare world on the exodus epoch; no clock walk this chapter — no marker, no stretch; the calendar's own keys read for the clock data) ----
with contextlib.redirect_stdout(io.StringIO()):
    _WC = WE.World(era='the counter\'s day — chapter 14 on a bare world (the exodus epoch)', epoch='exodus')
_EX = _WC.clock.eras['exodus']
def DAY(y, m, d): return _WC.clock.day_in('exodus', y, m, d)
def DATE(day): return _EX.date(day)
COUNTER = DAY(40, 11, 1)
BIRDS = WE.CAL_PARAMS['the_birds_signs']['value']; CARC = WE.CAL_PARAMS['the_carcass_table']['value']; MONEY = WE.CAL_PARAMS['the_moneys_form']['value']; REMOVAL = WE.CAL_PARAMS['the_removal_date']['value']; NEWYEAR = WE.CAL_PARAMS['the_tithes_new_year']['value']   # THE FIVE PARAMETERS read (exercised_by food_tithe) — never a constant in the code: the disputes recorded, the clock data the calendar's
FEST = WE.CAL_PARAMS['festival_dates']['value']
CLOCK = {'counter': DATE(COUNTER), 'birds_layers': sorted(BIRDS), 'carcass_arms': sorted(CARC), 'money_arms': sorted(MONEY), 'removal_keys': sorted(REMOVAL), 'new_year_keys': sorted(NEWYEAR), 'the_removal_eve_key': 'passover_7', 'the_tithes_new_year_key': 'rosh_hashanah', 'no_marker': True}
assert CLOCK == {'counter': (40, 11, 1), 'birds_layers': ['the_four_signs', 'the_lists', 'the_ruling', 'the_tradition'], 'carcass_arms': ['r_meir', 'r_yehuda', 'the_carcass_defined', 'the_customs_bar', 'the_precedence', 'the_sanction'], 'money_arms': ['r_akiva', 'r_yishmael', 'the_possession', 'the_three_moneys'], 'removal_keys': ['one_tithe_not_two', 'the_eve', 'the_uses', 'the_years'], 'new_year_keys': ['shevat_15', 'the_first_third', 'tishri_1', 'year_by_year'], 'the_removal_eve_key': 'passover_7', 'the_tithes_new_year_key': 'rosh_hashanah', 'no_marker': True}, CLOCK
assert BIRDS['the_four_signs'].startswith('an extra toe') and BIRDS['the_ruling'].startswith('ONE SIGN AND NO CLAWING') and BIRDS['the_tradition'].startswith('A CLEAN BIRD IS EATEN BY TRADITION') and CARC['r_meir'].startswith('BOTH TO BOTH') and CARC['r_yehuda'].startswith('AS WRITTEN') and CARC['the_precedence'].startswith('GIVING TO THE RESIDENT ALIEN COMES FIRST') and MONEY['r_yishmael'].startswith('THE BLANK') and MONEY['r_akiva'].startswith('THE IMPRINT') and MONEY['the_possession'].startswith('IN ONE') and REMOVAL['the_eve'].startswith('THE EVE OF THE LAST FESTIVAL DAY OF PASSOVER') and REMOVAL['one_tithe_not_two'].startswith('the poor man') and NEWYEAR['tishri_1'].startswith('THE FIRST OF TISHRI') and NEWYEAR['the_first_third'].startswith('THE FIRST THIRD') and NEWYEAR['shevat_15'].startswith('THE FIFTEENTH OF SHEVAT'), (BIRDS, CARC, MONEY, REMOVAL, NEWYEAR)
assert FEST['passover_7'] == {'from': 'passover_1', 'plus': 6} and FEST['passover_1'] == {'month': 1, 'day': 15} and FEST['rosh_hashanah'] == {'month': 7, 'day': 1}, FEST   # the removal's eve the calendar's own key (the seventh day of Passover, the eve before it); the tithes' new year the calendar's key — read, never typed

# ---- THE ONE DATABASE SCANNED (the holes' ground — nothing names the cuttings for the dead, the abomination's eating, the carcass's eating, the second tithe or the poor man's tithe on Israel before this sitting; the two reused effects on israel_people alone) ----
_WDB = _os.path.join(_ROOT, 'World', 'journal', 'data', 'world.sqlite')
def ledger_scan(entity, pattern):
    """the effects on an entity in the one database whose name or value matches the pattern — None where the database is not built (a fresh clone before build_world)"""
    if not _os.path.exists(_WDB): return None
    c_ = sqlite3.connect('file:%s?mode=ro' % _WDB, uri=True)
    rx = re.compile(pattern, re.I)
    return sorted({e for e, v in c_.execute("SELECT DISTINCT effect, value FROM run_ledger WHERE entity=?", (entity,)).fetchall() if rx.search('%s %s' % (e, v if v is not None else ''))})
def effect_scan(effect):
    """the entities holding an effect in the one database — None where the database is not built"""
    if not _os.path.exists(_WDB): return None
    c_ = sqlite3.connect('file:%s?mode=ro' % _WDB, uri=True)
    return sorted({e for (e,) in c_.execute("SELECT DISTINCT entity FROM run_ledger WHERE effect=?", (effect,)).fetchall()})
OWN5 = ('cuttings_for_the_dead_barred', 'abomination_eating_barred', 'carcass_eating_barred', 'second_tithe_owed', 'poor_tithe_owed')
FOOD_WORDS = r"\b(cuttings_for_the_dead\w*|abomination_eating\w*|carcass_eating\w*|second_tithe\w*|poor_tithe\w*)\b"
_fs = ledger_scan('israel_people', FOOD_WORDS); FOOD_SCAN = None if _fs is None else [e for e in _fs if e not in OWN5]   # this sitting's own five excluded once the fold carries them
_rs = [effect_scan(e) for e in ('rejoicing_before_the_lord_commanded', 'levite_forsaking_barred')]; REUSE_SCAN = None if any(r is None for r in _rs) else _rs
del _fs, _rs   # 9b's lesson: the raw scans are the database's state at import — the derived lists are equal on the cached and the full load
_FXV = yaml.safe_load(open(_os.path.join(HERE, 'effect_vocabulary.yaml'), encoding='utf-8'))['effects']
assert FOOD_SCAN in ([], None), FOOD_SCAN   # THE HOLES' GROUND — nothing on Israel named the five before this sitting (DF4)
assert REUSE_SCAN in ([['israel_people'], ['israel_people']], None), REUSE_SCAN   # the two reused effects on israel_people alone before the second entries
assert all(k in _FXV for k in OWN5) and _FXV['cuttings_for_the_dead_barred']['ledger_op'] == 'block' and _FXV['second_tithe_owed']['ledger_op'] == 'status' and all('THE DEUTERONOMY WALK 12b' in _FXV[e]['ink'] for e in ('rejoicing_before_the_lord_commanded', 'levite_forsaking_barred')), 'the five on the registry; the two reuses amended (add_types_ch14.py)'
# THE DB'S OWN SEATS for the DATA rows (every one computed here — the ink block above proves them at the reading's grain)
INF_ABS = [(v, x) for v in range(1, 30) for x, m in by[('Deut', 14, v)] if m and re.match(r'^H(?:C/)?V.a$', m)]
KID_SEATS = P('לא', 'תבשל', 'גדי', 'בחלב', 'אמו'); HOLY_PEOPLE = P('כי', 'עם', 'קדוש', 'אתה', 'ליהוה', 'אלהיך'); PORTION = P('חלק', 'ונחלה'); FOUR_AT_GATE = P('והגר', 'והיתום', 'והאלמנה')
PLACE_FORMULA = P('במקום', 'אשר', 'יבחר', books=DT); TITHE_TOKENS = [(s, x) for s, x, _ in LEMT('4643', books=T)]; REJOICE = U('ושמחת', 'ושמחתם', books=DT); THREE_YEARS = P('מקצה', 'שלש', 'שנים'); SEVEN_YEARS = P('מקץ', 'שבע', 'שנים')
TWIN = {'14:6 vs 11:3': SH(D14(6), ('Lev', 11, 3)), '14:7 vs 11:4': SH(D14(7), ('Lev', 11, 4)), '14:8 vs 11:7': SH(D14(8), ('Lev', 11, 7)), '14:9 vs 11:9': SH(D14(9), ('Lev', 11, 9)), '14:15 vs 11:16': SH(D14(15), ('Lev', 11, 16)), '14:15 == 11:16': W14(15) == words('Lev', 11, 16), '14:2 vs 7:6': SH(D14(2), ('Deut', 7, 6)), '14:24 vs 12:21': SH(D14(24), ('Deut', 12, 21)), '14:29 vs 24:19': SH(D14(29), ('Deut', 24, 19)), '14:29 vs 14:27': SH(D14(29), D14(27)), '14:21 vs 23:19': SH(D14(21), ('Exod', 23, 19))}
print('THE DB\'S OWN SEATS (printed before they are asserted): INF_ABS %s; the kid %s; the holy people %s; portion and inheritance %d; the four at the gate %s; the place formula %d; the tithe tokens %d; rejoice %d; three years %s; seven years %s; TWIN %s' % (INF_ABS, KID_SEATS, HOLY_PEOPLE, len(PORTION), FOUR_AT_GATE, len(PLACE_FORMULA), len(TITHE_TOKENS), len(REJOICE), THREE_YEARS, SEVEN_YEARS, TWIN))
assert INF_ABS == [(21, 'מכר'), (22, 'עשר')] and KID_SEATS == ['Deut 14:21', 'Exod 23:19', 'Exod 34:26'] and HOLY_PEOPLE == ['Deut 14:2', 'Deut 14:21', 'Deut 7:6'] and len(PORTION) == 6 and FOUR_AT_GATE == ['Deut 14:29', 'Deut 16:11', 'Deut 16:14'] and len(PLACE_FORMULA) == 11 and len(TITHE_TOKENS) == 17 and len(REJOICE) == 8 and THREE_YEARS == ['2Kgs 18:10', 'Deut 14:28'] and SEVEN_YEARS == ['Deut 15:1', 'Deut 31:10', 'Jer 34:14'], (INF_ABS, KID_SEATS, HOLY_PEOPLE, PORTION, FOUR_AT_GATE, PLACE_FORMULA, TITHE_TOKENS, REJOICE, THREE_YEARS, SEVEN_YEARS)
assert TWIN['14:6 vs 11:3'] == 9 and TWIN['14:7 vs 11:4'] == 16 and TWIN['14:8 vs 11:7'] == 10 and TWIN['14:9 vs 11:9'] == 12 and TWIN['14:15 vs 11:16'] == 10 and TWIN['14:15 == 11:16'] is True and TWIN['14:2 vs 7:6'] == 18 and TWIN['14:29 vs 24:19'] == 7 and TWIN['14:29 vs 14:27'] == 6 and TWIN['14:21 vs 23:19'] == 6, TWIN   # the twin diffed on the DB (DF8) — 14:15 = 11:16 to the letter; 14:2 = 7:6 eighteen of nineteen; 14:24's twelve with 12:21 read from the print

# ---- THE CALLEES' FACTS (every edge live at the cells that consume them; the values asserted from the callees' own print — ch14_callees.out, read before any assert was typed; the older runners' cells take q (or a dict, or a string case) and return a dict, the Deuteronomy runners' take (case, data) and return a tuple, the classifier a dict of signs, yovel's cycle a year, temurah's tithe a string case — the print settled each form) ----
def V(x):
    """a cell's verdict whatever its form — the dict's v (or verdict), the tuple's first member"""
    return x.get('v', x.get('verdict', x)) if isinstance(x, dict) else (x[0] if isinstance(x, tuple) else x)
def FOUND(r):
    """a kin cell CALLED and answering — a tuple (verdict, effects, trail) whose verdict is in span, or a dict with its value"""
    if isinstance(r, dict): return 'v' in r or 'verdict' in r
    return isinstance(r, tuple) and isinstance(r[0], str) and not r[0].startswith('no verdict') and r[0] != 'no_case'
SHM_PURE = SHM.classify({'clazz': 'land', 'hoof': True, 'cud': True}); SHM_CAMEL = SHM.classify({'clazz': 'land', 'hoof': False, 'cud': True, 'name': 'camel'}); SHM_HARE = SHM.classify({'clazz': 'land', 'hoof': False, 'cud': True, 'name': 'hare'}); SHM_CONEY = SHM.classify({'clazz': 'land', 'hoof': False, 'cud': True, 'name': 'coney'}); SHM_SWINE = SHM.classify({'clazz': 'land', 'hoof': True, 'cud': False, 'name': 'swine'})
SHM_FISH = SHM.classify({'clazz': 'water', 'fin': True, 'scale': True}); SHM_NOFIN = SHM.classify({'clazz': 'water', 'fin': False, 'scale': True}); SHM_NOSCALE = SHM.classify({'clazz': 'water', 'fin': True, 'scale': False})
SHM_EAGLE = SHM.classify({'clazz': 'bird', 'named_in_list': True}); SHM_CLAWER = SHM.classify({'clazz': 'bird', 'claws_and_eats': True}); SHM_DOVE = SHM.classify({'clazz': 'bird', 'extra_toe': True, 'crop': True, 'peelable_gizzard': True}); SHM_UNKNOWN = SHM.classify({'clazz': 'bird'})
SHM_LOCUST = SHM.classify({'clazz': 'locust', 'four_legs': True, 'four_wings': True, 'jumping_joints': True, 'wings_cover_most': True}); SHM_TOUCH = SHM.touch_effect('touch_carcass'); SHM_CARRY = SHM.touch_effect('carry_carcass')
SA_LASH = SA.carcass('lashes_for_eating'); SA_WHO = SA.carcass('who'); SA_SLAUGHTERED = SA.carcass('slaughtered'); SA_EFFECT = SA.carcass('effect'); SA_MIN = SA.carcass('minimum'); SA_SPECIES = SA.carcass('impure_species'); SA_PINCH = SA.carcass('pinching')
CA_COOK = CA.kid_in_milk({'ask': 'cook'}, CA.DATA); CA_EAT = CA.kid_in_milk({'ask': 'eat'}, CA.DATA); CA_BENEFIT = CA.kid_in_milk({'ask': 'benefit'}, CA.DATA); CA_TIMER = CA.sabbatical({'ask': 'timer'}, CA.DATA); CA_HOME = CA.sabbatical({'ask': 'home_engine'}, CA.DATA)
ER_KID = ER.repeats('kid_identical'); ER_KIDCALL = ER.repeats('kid_by_call'); ER_SEH = ER.repeats('seh_class'); ER_KELAL = ER.repeats('kelal_prat')
OR_DOG = OR.torn('to_the_dog'); OR_LASH = OR.torn('lashes'); OR_LIVE = OR.torn('cannot_live'); OR_SEATS = OR.torn('torn_seats'); OR_FIELD = OR.torn('field_common_case'); OR_EIGHTH = OR.firstling('eighth_and_onward'); OR_TIMER = OR.firstling('two_seats_one_timer')
PR_MARKS = PR.family('marks'); PR_CORNERS = PR.family('corners'); PR_GASH = PR.family('gash_multiplier'); PR_MEAS = PR.holy_food('measures'); PR_STRANGER = PR.holy_food('stranger'); PR_TEVUL = PR.holy_food('tithe_tevul_yom')
HO_RECIP = HO.gifts('recipients'); HO_KINDS = HO.gifts('kinds'); HO_WINDOW = HO.gifts('window_end'); HO_POOR = HO.gifts('poor_defined'); HO_COPY = HO.gifts('copy_23_22'); HO_IMPL = HO.gifts('implication_tithes'); HO_IMPORT = HO.GIFTS_IMPORT
HB_GASH = HB.body('gash_for_dead'); HB_CORNERS = HB.body('corners_count'); HB_ONCE = HB.body('all_at_once'); HB_TOKEN = HB.body('corner_token')
MO_HARVEST = MO.law_moadim({'kind': 'harvest_reaped', 'reaper': 'the-reaper', 'case_source': 'Lev 23:14, 23:22 — the new grain until the omer; the corner and the gleanings (the copy of 19:9-10)'}, None)   # the moadim daemon's own branch for the kind (no cell of its own for 23:22 — the corner's copy is holiness.gifts('copy_23_22')); the world unused on that branch
TM_TEN = TM.tithe('took_ten_of_a_hundred'); TM_PROC = TM.tithe('procedure'); TM_LAND = TM.tithe('land_tithe_status'); TM_HERD = TM.tithe('herd_with_flock'); TM_REDEEM = TM.redeem('unfit_animal')
KO_LIABLE = KO.the_tithe({'ask': 'liable_produce'}, KO.DATA); KO_REMOVAL = KO.the_tithe({'ask': 'removal'}, KO.DATA); KO_THIRD = KO.the_tithe({'ask': 'third_year'}, KO.DATA); KO_THRESH = KO.the_tithe({'ask': 'thresholds'}, KO.DATA); KO_RECIP = KO.the_tithe({'ask': 'tithe_recipient'}, KO.DATA); KO_RECIPS = KO.the_tithe({'ask': 'recipients'}, KO.DATA)
KO_NOINH = KO.the_tithe({'ask': 'no_inheritance'}, KO.DATA); KO_EVERY = KO.the_tithe({'ask': 'every_place'}, KO.DATA); KO_LEVITES = KO.the_tithe({'ask': 'tithe_to_levites'}, KO.DATA); KO_CONF = KO.the_tithe({'ask': 'confession'}, KO.DATA); KO_MOURN = KO.the_tithe({'ask': 'mourner'}, KO.DATA)
KO_CLEAN = KO.the_gifts({'ask': 'clean_firstborn'}, KO.DATA); KO_NOALTAR = KO.the_gifts({'ask': 'firstborn_without_altar'}, KO.DATA); KO_WINDOW = KO.the_gifts({'ask': 'firstborn_eating_window'}, KO.DATA)
YO_C3 = YO.cycle(3); YO_C6 = YO.cycle(6); YO_C7 = YO.cycle(7); YO_C50 = YO.cycle(50); YO_SAB = YO.sabbatical(); YO_NAMING = YO.tithe_naming({9: 'tenth', 10: 'ninth', 11: 'tenth'})
SN_HOLY = SN.the_holy_people({'ask': 'holy_people'}, SN.DATA); SN_CHOSE = SN.the_holy_people({'ask': 'chose_you'}, SN.DATA); SN_OATH = SN.the_holy_people({'ask': 'the_oath'}, SN.DATA); SN_REDEEMED = SN.the_holy_people({'ask': 'brought_out_redeemed'}, SN.DATA)
ST_PORTION = ST.the_levites_separated({'ask': 'levi_has_no_portion'}, ST.DATA); ST_SPOKE = ST.the_levites_separated({'ask': 'as_the_lord_spoke_to_him'}, ST.DATA); ST_LOVE = ST.the_god_of_gods_and_the_stranger({'ask': 'and_you_shall_love_the_stranger'}, ST.DATA); ST_ORPHAN = ST.the_god_of_gods_and_the_stranger({'ask': 'the_orphan_and_the_widow'}, ST.DATA); ST_INTAKE = ST.the_god_of_gods_and_the_stranger({'ask': 'the_converts_intake'}, ST.DATA)
PN_PLACE = PN.the_place_chosen({'ask': 'the_place_which_the_lord_will_choose'}, PN.DATA); PN_REJOICE = PN.the_place_chosen({'ask': 'eat_there_and_rejoice'}, PN.DATA); PN_STATIONS = PN.the_place_chosen({'ask': 'the_stations_six_rows'}, PN.DATA); PN_WOMAN = PN.the_place_chosen({'ask': 'the_womans_rejoicing'}, PN.DATA)
PN_LEVITE = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'lest_you_forsake_the_levite'}, PN.DATA); PN_TWO = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_two_tithes'}, PN.DATA); PN_WALL = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_lashes_outside_the_wall'}, PN.DATA); PN_GATES = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'you_may_not_eat_within_your_gates'}, PN.DATA); PN_SCOPE = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_levites_scope'}, PN.DATA)
PN_FAR = PN.the_border_enlarged_and_the_altar({'ask': 'too_far'}, PN.DATA); PN_GAZELLE = PN.the_border_enlarged_and_the_altar({'ask': 'as_the_gazelle_and_the_hart'}, PN.DATA); PN_MILK = PN.the_border_enlarged_and_the_altar({'ask': 'flesh_in_milk'}, PN.DATA); PN_CIVIL = PN.the_border_enlarged_and_the_altar({'ask': 'the_civility'}, PN.DATA)
PV_ALTARS = PV.exit('altar_seats'); PV_CLEAN = PV.ark('clean_by_call'); PV_TITHE = PV.war('tithe_by_call'); PV_HAND = PV.war('raised_hand'); PV_SALEM = PV.war('salem')
MM_TITHE = MM.bethel('tithe_by_call'); MM_PHRASE = MM.bethel('tithe_phrase_seats'); MM_CAP = MM.bethel('charity_cap_verse'); MM_COMMIT = MM.bethel('vow_commitments')
SE_SEAL = SE.the_header({'ask': 'the_headers_seal'}, SE.DATA)
# the values asserted from the callees' print (ch14_callees.out — read before any assert was typed)
assert SHM_PURE[0] == 'pure' and SHM_CAMEL[0] == 'impure' and SHM_HARE[0] == 'impure' and SHM_CONEY[0] == 'impure' and SHM_SWINE[0] == 'impure' and SHM_FISH[0] == 'pure' and SHM_NOFIN[0] == 'impure' and SHM_NOSCALE[0] == 'impure', (SHM_PURE[0], SHM_CAMEL[0], SHM_SWINE[0], SHM_FISH[0], SHM_NOFIN[0])   # THE TWIN CHAPTER'S CLASSIFIER — the four the pincer of the exceptions; the water's keys 'fin' and 'scale' (the print's dict form with 'fins' returned impure: the source read)
assert SHM_EAGLE[0] == 'impure' and SHM_CLAWER[0] == 'impure' and SHM_DOVE[0] == 'pure' and SHM_UNKNOWN[0] == 'unresolved_check_tradition' and SHM_LOCUST[0] == 'pure' and SHM_TOUCH[0] == 'impure_until_evening' and SHM_CARRY[0] == 'wash_and_evening', (SHM_EAGLE[0], SHM_CLAWER[0], SHM_DOVE[0], SHM_UNKNOWN[0], SHM_LOCUST[0], SHM_TOUCH[0])   # the birds a blacklist, the signs the Sages' layer (the classifier's own label 'S'), the tradition's arm 'unresolved_check_tradition'
assert SA_LASH['v'] == 'lashed' and SA_LASH['fx'] == ['lashes'] and 'Deut 14:21' in SA_LASH['why'] and SA_WHO['v'] == 'citizen_and_convert_not_the_resident_alien' and SA_SLAUGHTERED['v'] == 'excluded' and SA_EFFECT['v'] == 'washes_garments_bathes_impure_until_evening_then_pure' and SA_MIN['v'] == 'olive' and SA_SPECIES['v'] == ['excluded_sages_carcass_AND_torn', 'excluded_R._Yehuda'] and SA_PINCH['v'] == ['purifies_R._Meir', 'does_not_R._Yosei_dayo'], (SA_LASH, SA_WHO['v'], SA_SLAUGHTERED['v'])
assert CA_COOK[:2] == ('barred', ['barred_from_it']) and CA_EAT[:2] == ('barred', ['barred_from_it']) and CA_BENEFIT[:2] == ('barred', ['barred_from_it']) and CA_TIMER[:2] == ('land released in year 7', ['land_release']) and CA_HOME[0].startswith('the same release'), (CA_COOK[:2], CA_TIMER[:2], CA_HOME[0][:30])
assert ER_KID['v'] is True and ER_KIDCALL['v'] == {'cook': 'barred', 'eat': 'barred', 'benefit': 'barred'} and ER_SEH['v'] == 'sheep_or_goat_any_sex_age_blemish' and ER_KELAL['v'] == ['שור', 'ושה', 'חמור'], (ER_KID['v'], ER_KIDCALL['v'], ER_SEH['v'], ER_KELAL['v'])   # (ox, and sheep, donkey — 34:19-20's particulars)
assert OR_DOG['v'] == 'benefit_permitted' and OR_LASH['v'] == 'lashed' and OR_LASH['fx'] == ['lashes'] and OR_LIVE['v'] == 'whatever_cannot_live_is_terefah' and OR_SEATS['v'] == 4 and OR_FIELD['v'] == 'the_common_case_house_included' and OR_EIGHTH['v'] == 'on_the_eighth_day_and_onward' and OR_TIMER['v'] == {'exod_22_29': 'on_the_eighth_day', 'lev_22_27': 'from_the_eighth_day_onward'}, (OR_DOG['v'], OR_LASH['v'], OR_LIVE['v'], OR_SEATS['v'], OR_EIGHTH['v'])
assert PR_MARKS['v'] == {'baldness': 'per_spot_whole_head', 'beard': 'per_corner', 'gash': 'per_gash_for_the_dead'} and PR_CORNERS['v'] == {'head': 2, 'beard': 5} and PR_GASH['v'] == 5 and PR_MEAS['v']['carcass'] == 'by_or_a_man' and PR_STRANGER['v']['who'] == 'levite_and_israelite_by_EVERY_stranger' and PR_TEVUL['v'] == {'israelites_tithe': 'as_tevul_yom', 'aaron_and_sons_terumah': 'at_sunset'}, (PR_MARKS['v'], PR_CORNERS['v'], PR_GASH['v'], PR_MEAS['v'].get('carcass'))
assert HO_RECIP['v'] == 'the_poor_and_the_convert_not_the_resident_alien' and HO_KINDS['v'] == ['corner', 'fallen_grapes', 'gleanings', 'small_clusters'] and HO_WINDOW['v'] == 'until_the_smoothing' and HO_POOR['v'] == 'takes' and HO_COPY['v'] == 'the_Emor_copy_omits_the_vineyard' and HO_IMPL['v'] == 'corner_implies_tithes_not_the_reverse' and HO_IMPORT == {'forgotten_sheaf': 'Deut 24:19', 'forgotten_olive': 'Deut 24:20', 'poor_tithe': 'Deut 14:28'}, (HO_RECIP['v'], HO_KINDS['v'], HO_WINDOW['v'], HO_IMPORT)
assert HB_GASH['v'] == 'for_the_dead_only' and HB_CORNERS['v'] == {'head': 2, 'beard': 5} and HB_ONCE['v'] == 'one_liability_R._Elazar' and HB_TOKEN['v'] == [9, 27], (HB_GASH['v'], HB_CORNERS['v'], HB_ONCE['v'], HB_TOKEN['v'])
assert isinstance(MO_HARVEST, list) and len(MO_HARVEST) == 1 and MO_HARVEST[0]['effect'] == 'barred_from_it' and MO_HARVEST[0].get('value') == 'new_grain_until_the_omer', MO_HARVEST
assert TM_TEN['v'] == 'not_a_tithe' and TM_PROC['v'] == 'counted_under_the_rod_the_tenth_holy' and TM_LAND['v'] == 'holy_to_the_LORD' and TM_HERD['v'] == 'not_tithed_together' and TM_REDEEM['v'] == 'valuation_plus_fifth', (TM_TEN['v'], TM_PROC['v'], TM_LAND['v'], TM_HERD['v'], TM_REDEEM['v'])
assert KO_LIABLE[0].startswith('food, guarded, grown from the land') and KO_REMOVAL[0].startswith('the removal on Passover eve of the fourth and seventh years') and KO_THIRD[0].startswith('the first tithe every year') and KO_THRESH[0].startswith('the pile evened') and KO_RECIP[0].startswith('the Levite (18:21, 18:26') and KO_RECIP[1] == ['tithe_granted'] and KO_RECIPS[0].startswith('the Levite, the priest'), (KO_LIABLE[0][:40], KO_REMOVAL[0][:40], KO_THIRD[0][:40], KO_THRESH[0][:30], KO_RECIP[:2], KO_RECIPS[0][:30])
assert KO_NOINH[0].startswith('in their land you shall not inherit') and KO_EVERY[0].startswith('in every place') and KO_LEVITES[0].startswith('all the tithe in Israel') and KO_CONF[0].startswith('given to the Levite = the first tithe') and KO_MOURN[0].startswith('from it free for the mourner') and KO_CLEAN[0].startswith('the firstborn of an ox, a sheep, a goat you shall not redeem') and KO_NOALTAR[0].startswith('the flesh as the blood') and KO_WINDOW[0].startswith('two days and a night'), (KO_NOINH[0][:40], KO_EVERY[0][:30], KO_LEVITES[0][:30], KO_CONF[0][:40], KO_MOURN[0][:30], KO_CLEAN[0][:40], KO_NOALTAR[0][:30], KO_WINDOW[0][:30])
assert YO_C3['v'] == 'work_year' and YO_C6['v'] == 'work_year' and YO_C7['v'] == 'sabbath_of_the_land' and YO_C50['v'] == 'jubilee' and 'torah_labors' in YO_SAB and YO_SAB['torah_labors']['v'] == 4 and YO_NAMING == {9: 'sanctified_eaten_blemished', 10: 'tithe', 11: 'shelamim'}, (YO_C3['v'], YO_C7['v'], YO_C50['v'], YO_SAB.get('torah_labors', {}).get('v'), YO_NAMING)
assert SN_HOLY[0].startswith('a holy people (7:6)') and SN_CHOSE[0].startswith('chose you (7:6-7)') and SN_OATH[0].startswith('the oath (7:8)') and SN_REDEEMED[0].startswith('brought out and redeemed (7:8)'), (SN_HOLY[0][:30], SN_CHOSE[0][:30], SN_OATH[0][:30], SN_REDEEMED[0][:40])
assert ST_PORTION[0].startswith('Levi has no portion (10:9)') and ST_SPOKE[0].startswith('as the LORD your God spoke to him (10:9)') and ST_LOVE[0].startswith('and you shall love the stranger (10:19)') and ST_ORPHAN[0].startswith('the orphan and the widow (10:18)') and ST_INTAKE[0].startswith("the convert's intake (Yevamot 47a:13-47b:15)"), (ST_PORTION[0][:40], ST_SPOKE[0][:40], ST_LOVE[0][:40], ST_ORPHAN[0][:40], ST_INTAKE[0][:40])
assert PN_PLACE[0].startswith('the place which the LORD will choose (12:5)') and PN_REJOICE[0].startswith('eat there and rejoice (12:7)') and PN_STATIONS[0].startswith("the stations' six rows (12:9-11)") and PN_WOMAN[0].startswith("the woman's rejoicing (12:7, 12:12, 12:18)") and PN_LEVITE[0].startswith('lest you forsake the Levite (12:19)') and PN_TWO[0].startswith('the two tithes (12:17)') and PN_WALL[0].startswith('the lashes outside the wall (12:17)') and PN_GATES[0].startswith('you may not eat within your gates (12:17)') and PN_SCOPE[0].startswith("the Levite's scope (12:19)"), (PN_PLACE[0][:40], PN_REJOICE[0][:40], PN_STATIONS[0][:40], PN_WOMAN[0][:40], PN_LEVITE[0][:40], PN_TWO[0][:30], PN_WALL[0][:40], PN_GATES[0][:40], PN_SCOPE[0][:30])
assert PN_FAR[0].startswith('too far (12:21)') and PN_GAZELLE[0].startswith('as the gazelle and the hart (12:22)') and PN_MILK[0].startswith('flesh in milk (12:25)') and PN_CIVIL[0].startswith('the civility (12:21)'), (PN_FAR[0][:30], PN_GAZELLE[0][:40], PN_MILK[0][:30], PN_CIVIL[0][:30])
assert PV_ALTARS['v'] == [(8, 20), (12, 7), (12, 8), (13, 18)] and PV_CLEAN['v'] == 'pure' and PV_TITHE['v'] == 'holy_to_the_LORD' and PV_HAND['v'] == ('terumah', 'an_oath') and PV_SALEM['v'] == 'salem_is_jerusalem', (PV_ALTARS['v'], PV_CLEAN['v'], PV_TITHE['v'], PV_HAND['v'], PV_SALEM['v'])
assert MM_TITHE['v'] == 'holy_to_the_LORD' and MM_PHRASE['v'] == 1 and MM_CAP['v'] == 'Gen 28:22' and MM_COMMIT['v'] == 3 and SE_SEAL[0].startswith("the header's seal (13:1)"), (MM_TITHE['v'], MM_PHRASE['v'], MM_CAP['v'], MM_COMMIT['v'], SE_SEAL[0][:30])
assert all(FOUND(r) for r in (SA_LASH, SA_WHO, CA_COOK, CA_EAT, CA_BENEFIT, CA_TIMER, ER_KID, ER_SEH, OR_DOG, OR_LASH, OR_LIVE, OR_EIGHTH, PR_MARKS, PR_CORNERS, PR_MEAS, HO_RECIP, HO_KINDS, HO_COPY, HB_GASH, HB_CORNERS, TM_TEN, TM_PROC, TM_LAND, KO_LIABLE, KO_REMOVAL, KO_THIRD, KO_RECIP, KO_NOINH, KO_CLEAN, YO_C3, YO_C7, SN_HOLY, SN_CHOSE, ST_PORTION, ST_LOVE, PN_PLACE, PN_REJOICE, PN_LEVITE, PN_FAR, PV_ALTARS, PV_CLEAN, PV_TITHE, MM_TITHE, MM_PHRASE, SE_SEAL)), 'every kin cell CALLED and answering'
