# ---- THE DISPLAY PATCH PREDICTED (the G print — the store's gloss families over the whole store; sitting 11's form, ch13_ink_body_c.py): BY GLOSS where every token of the gloss is the one word (or one family read the same at every seat), BY REFERENCE where the family is mixed ----
GLOSS_FAMILY = {'and-claw': [('ופרסה', 4)], 'and-from-break-in-pieces': [('וממפריסי', 2)], 'from-go-up': [('ממעלי', 2)], 'and-gazelle': [('וזמר', 1)], 'and-splendor': [('וצבי', 1)], 'and-kind-of-deer': [('ויחמור', 1)], 'and-leaper': [('ודישן', 1)], 'and-slender': [('ואקו', 1)], 'and-species-of-antelope': [('ותאו', 1)], 'stag': [('איל', 1)],
                'and-in-flabby-thing-them/their': [('ובנבלתם', 2)], 'flabby-thing': [('נבלה', 4)], 'and-in-intoxicant': [('ובשכר', 1)], 'and-in-wine': [('וביין', 1)], 'claw': [('פרסה', 7), ('פרסת', 1), ('פרסות', 1)], 'foul-in-a-religious-sense': [('טמא', 33), ('טמאים', 8), ('טמאה', 7)], 'little-bird': [('צפור', 4), ('צפרים', 2)], 'flying-creature': [('עוף', 9)], 'the-flying-creature': [('העוף', 12)],
                'and-the-claw': [('והפרס', 1)], 'and-the-sea-eagle': [('והעזניה', 1)], 'and-the-bird-of-prey': [('והראה', 1)], 'the-screamer': [('האיה', 2)], 'and-the-falcon': [('והדיה', 1)], 'the-ostrich-(probably-from-its-a': [('היענה', 2)], 'the-species-of-unclean-bird': [('התחמס', 2)], 'the-gull': [('השחף', 2)], 'the-flower': [('הנץ', 2)], 'the-unclean--bird': [('הינשוף', 2)], 'and-the-hard-breather': [('והתנשמת', 2)], 'the-kind-of-vulture-suffix': [('הרחמה', 1)], 'the-bird-of-prey': [('השלך', 2)], 'and-the-kind--bird': [('והחסידה', 1)], 'and-the-unclean-bird': [('והאנפה', 1)],
                'to-kind-her/its': [('למינה', 10)], 'to-kind-him/its': [('למינהו', 14), ('למינו', 4)], 'to-sojourner': [('לגר', 6)], 'to-strange': [('לנכרי', 2)], 'income': [('תבואת', 5)], 'income-you/your': [('תבואתך', 3)], 'must-you/your': [('תירשך', 2)], 'the-way/road': [('הדרך', 20)], 'and-house-you/your': [('וביתך', 3)], 'and-the-bereaved-person': [('והיתום', 3)], 'the-species-of-rockrabbit': [('השפן', 2)], 'the-split': [('השסועה', 1)], 'the-hog': [('החזיר', 2)], 'from-flesh-them/their': [('מבשרם', 3)], 'swarming-creature': [('שרץ', 8)]}
GT = {g: store.execute("SELECT REPLACE(w.he_plain,'/',''), COUNT(*) FROM words w WHERE w.gloss=? GROUP BY 1 ORDER BY 2 DESC, 1", (g,)).fetchall() for g in GLOSS_FAMILY}
assert all(sorted(GT[g]) == sorted(v) for g, v in GLOSS_FAMILY.items()), [(g, GT[g]) for g, v in GLOSS_FAMILY.items() if sorted(GT[g]) != sorted(v)]
# BY GLOSS — the beasts' and the birds' names (each ONE word in the store), the hoof and the cud's chewers, the carcass, the wine and the strong drink, the fowl, the kinds, the sojourner and the foreigner, the yield and the produce, the way, the household, the fatherless, the unclean (forty-eight tokens, three forms of one word)
OVERRIDE_GLOSS = [('and-claw', 'and-hoof'), ('and-from-break-in-pieces', 'and-of-those-that-part'), ('from-go-up', 'of-those-that-chew'), ('and-gazelle', 'and-the-mountain-sheep'), ('and-splendor', 'and-the-gazelle'), ('and-kind-of-deer', 'and-the-roebuck'), ('and-leaper', 'and-the-pygarg'), ('and-slender', 'and-the-wild-goat'), ('and-species-of-antelope', 'and-the-antelope'), ('stag', 'the-hart'),
                  ('and-in-flabby-thing-them/their', 'and-their-carcass'), ('flabby-thing', 'carcass'), ('and-in-intoxicant', 'and-on-strong-drink'), ('and-in-wine', 'and-on-wine'), ('claw', 'hoof'), ('foul-in-a-religious-sense', 'unclean'), ('little-bird', 'bird'), ('flying-creature', 'fowl'), ('the-flying-creature', 'the-fowl'),
                  ('and-the-claw', 'and-the-ossifrage'), ('and-the-sea-eagle', 'and-the-osprey'), ('and-the-bird-of-prey', 'and-the-glede'), ('the-screamer', 'the-kite'), ('and-the-falcon', 'and-the-vulture'), ('the-ostrich-(probably-from-its-a', 'the-ostrich'), ('the-species-of-unclean-bird', 'the-night-hawk'), ('the-gull', 'the-sea-mew'), ('the-flower', 'the-hawk'), ('the-unclean--bird', 'the-great-owl'), ('and-the-hard-breather', 'and-the-horned-owl'), ('the-kind-of-vulture-suffix', 'the-carrion-vulture'), ('the-bird-of-prey', 'the-cormorant'), ('and-the-kind--bird', 'and-the-stork'), ('and-the-unclean-bird', 'and-the-heron'),
                  ('to-kind-her/its', 'after-its-kind'), ('to-kind-him/its', 'after-its-kind'), ('to-sojourner', 'to-the-sojourner'), ('to-strange', 'to-a-foreigner'), ('income', 'the-yield-of'), ('income-you/your', 'your-produce'), ('must-you/your', 'your-wine'), ('the-way/road', 'the-way'), ('and-house-you/your', 'and-your-household'), ('and-the-bereaved-person', 'and-the-fatherless'), ('the-species-of-rockrabbit', 'the-rock-badger'), ('the-split', 'the-cleft-one'), ('the-hog', 'the-swine'), ('from-flesh-them/their', 'of-their-flesh'), ('swarming-creature', 'swarming-thing')]
# BY REFERENCE — the family mixed (a homograph: "cup" for the little owl, "smoothness" for the portion, "morning" for the herd, "flower" kept for the hawk by gloss; "for" against "that" and "when"; a verb read two ways; a noun singular and plural): the seat named
OVERRIDE_REF_SPEC = [(1, 'בנים', 'children', 0), (1, 'תתגדדו', 'cut-yourselves', 0), (1, 'תשימו', 'you-shall-make', 0), (1, 'למת', 'for-the-dead', 0),
                     (2, 'כי', 'for', 0), (2, 'עם', 'a-people', 0), (2, 'קדוש', 'holy', 0), (2, 'ובך', 'and-you', 0), (2, 'לו', 'for-Himself', 0), (2, 'לעם', 'as-a-people', 0), (2, 'העמים', 'the-peoples', 0), (2, 'על', 'upon', 0), (2, 'פני', 'the-face-of', 0), (2, 'האדמה', 'the-earth', 0),
                     (3, 'תאכל', 'you-shall-eat', 0), (3, 'כל', 'any', 0),
                     (4, 'הבהמה', 'the-beast', 0), (4, 'תאכלו', 'you-shall-eat', 0), (4, 'שור', 'the-ox', 0), (4, 'שה', 'the-sheep-of', 0), (4, 'כשבים', 'lambs', 0), (4, 'ושה', 'and-the-sheep-of', 0), (4, 'עזים', 'goats', 0),
                     (6, 'וכל', 'and-every', 0), (6, 'בהמה', 'beast', 0), (6, 'מפרסת', 'that-parts', 0), (6, 'ושסעת', 'and-cleaves', 0), (6, 'שסע', 'the-cleft', 0), (6, 'מעלת', 'chewing', 0), (6, 'בבהמה', 'among-the-beasts', 0), (6, 'אתה', 'it', 0), (6, 'תאכלו', 'you-shall-eat', 0),
                     (7, 'אך', 'but', 0), (7, 'תאכלו', 'you-shall-eat', 0), (7, 'הפרסה', 'the-hoof', 0), (7, 'כי', 'for', 0), (7, 'מעלה', 'chew', 0), (7, 'הפריסו', 'they-part', 0), (7, 'לכם', 'to-you', 0),
                     (8, 'כי', 'for', 0), (8, 'מפריס', 'parts', 0), (8, 'הוא', 'it', 0), (8, 'הוא', 'it', 1), (8, 'לכם', 'to-you', 0), (8, 'תאכלו', 'you-shall-eat', 0), (8, 'תגעו', 'you-shall-touch', 0),
                     (9, 'תאכלו', 'you-shall-eat', 0), (9, 'תאכלו', 'you-shall-eat', 1), (9, 'במים', 'in-the-waters', 0), (9, 'לו', 'to-it', 0), (9, 'וקשקשת', 'and-scales', 0),
                     (10, 'וקשקשת', 'and-scales', 0), (10, 'תאכלו', 'you-shall-eat', 0), (10, 'הוא', 'it', 0), (10, 'לכם', 'to-you', 0), (10, 'לו', 'to-it', 0),
                     (11, 'כל', 'every', 0), (11, 'טהרה', 'clean', 0), (11, 'תאכלו', 'you-shall-eat', 0),
                     (12, 'תאכלו', 'you-shall-eat', 0), (12, 'מהם', 'of-them', 0),
                     (14, 'כל', 'every', 0), (15, 'בת', 'the-daughter-of', 0), (16, 'הכוס', 'the-little-owl', 0),
                     (19, 'וכל', 'and-every', 0), (19, 'הוא', 'it', 0), (19, 'לכם', 'to-you', 0), (19, 'יאכלו', 'they-shall-be-eaten', 0),
                     (20, 'כל', 'every', 0), (20, 'טהור', 'clean', 0), (20, 'תאכלו', 'you-shall-eat', 0),
                     (21, 'תאכלו', 'you-shall-eat', 0), (21, 'כל', 'any', 0), (21, 'תתננה', 'you-shall-give-it', 0), (21, 'ואכלה', 'that-he-may-eat-it', 0), (21, 'מכר', 'sell-it', 0), (21, 'כי', 'for', 0), (21, 'עם', 'a-people', 0), (21, 'קדוש', 'holy', 0), (21, 'תבשל', 'you-shall-boil', 0), (21, 'גדי', 'a-kid', 0), (21, 'בחלב', 'in-the-milk-of', 0), (21, 'אמו', 'its-mother', 0),
                     (22, 'תעשר', 'you-shall-tithe', 0), (22, 'היצא', 'that-comes-forth-from', 0), (22, 'שנה', 'year', 0), (22, 'שנה', 'by-year', 1),
                     (23, 'לפני', 'before', 0), (23, 'שמו', 'His-name', 0), (23, 'מעשר', 'the-tithe-of', 0), (23, 'הימים', 'the-days', 0),
                     (24, 'וכי', 'and-when', 0), (24, 'ירבה', 'is-too-long', 0), (24, 'תוכל', 'you-are-able', 0), (24, 'שאתו', 'to-carry-it', 0), (24, 'כי', 'because', 1), (24, 'ירחק', 'is-too-far', 0), (24, 'שמו', 'His-name', 0), (24, 'כי', 'because', 2), (24, 'יברכך', 'will-bless-you', 0),
                     (25, 'ונתתה', 'and-you-shall-turn-it', 0), (25, 'בכסף', 'into-money', 0), (25, 'וצרת', 'and-bind-up', 0), (25, 'הכסף', 'the-money', 0), (25, 'והלכת', 'and-go', 0), (25, 'בו', 'in-it', 0),
                     (26, 'ונתתה', 'and-you-shall-bestow', 0), (26, 'הכסף', 'the-money', 0), (26, 'בכל', 'on-whatever', 0), (26, 'תאוה', 'desires', 0), (26, 'בבקר', 'on-oxen', 0), (26, 'ובצאן', 'and-on-sheep', 0), (26, 'ובכל', 'and-on-whatever', 0), (26, 'לפני', 'before', 0),
                     (27, 'תעזבנו', 'you-shall-forsake-him', 0), (27, 'כי', 'for', 0), (27, 'חלק', 'portion', 0), (27, 'עמך', 'with-you', 0),
                     (28, 'מקצה', 'at-the-end-of', 0), (28, 'תוציא', 'you-shall-bring-out', 0), (28, 'מעשר', 'the-tithe-of', 0), (28, 'בשנה', 'in-the-year', 0), (28, 'והנחת', 'and-lay-it-up', 0),
                     (29, 'ובא', 'and-shall-come', 0), (29, 'כי', 'for', 0), (29, 'חלק', 'portion', 0), (29, 'עמך', 'with-you', 0), (29, 'יברכך', 'may-bless-you', 0), (29, 'מעשה', 'the-work-of', 0), (29, 'ידך', 'your-hand', 0), (29, 'תעשה', 'you-do', 0)]
OVERRIDE_REF3 = [(f'Deut.14.{v}:{sidx(14, v, tok, nth)}', new, tok) for v, tok, new, nth in OVERRIDE_REF_SPEC]
OVERRIDE_REF = [(k, v) for k, v, _ in OVERRIDE_REF3]
assert len(OVERRIDE_REF) == len({k for k, _ in OVERRIDE_REF}) == len(OVERRIDE_REF_SPEC) and len(OVERRIDE_GLOSS) == len({k for k, _ in OVERRIDE_GLOSS}) and all(g in GLOSS_FAMILY for g, _ in OVERRIDE_GLOSS) and all(sg(14, v, tok, nth) is not None for v, tok, _, nth in OVERRIDE_REF_SPEC)
assert all(sg(14, v, tok, nth) != new for v, tok, new, nth in OVERRIDE_REF_SPEC), [(v, tok) for v, tok, new, nth in OVERRIDE_REF_SPEC if sg(14, v, tok, nth) == new]   # no row rewrites a gloss to itself
print('THE DISPLAY PATCH PREDICTED — by gloss', len(OVERRIDE_GLOSS), 'by reference', len(OVERRIDE_REF))
# the chapter's glosses ALREADY rewritten by the by-gloss overrides (the G print's twenty-five)
ALREADY = {'God-you/your': 'your-God', 'God-you/your (pl)': 'your-God', 'and-brighten-up': 'and-rejoice', 'and-firstling-of-man': 'and-the-firstlings-of', 'and-flock-you/your': 'and-your-flock', 'and-oil-you/your': 'and-your-oil', 'and-sate': 'and-be-satisfied', 'eye-you/your (pl)': 'your-eyes', 'from-you/your': 'from-you', 'goad': 'teach', 'herd-you/your': 'your-herd', 'in-gate-you/your': 'within-your-gates', 'in-hand-you/your': 'in-your-hand', 'in-place': 'in-the-place', 'increase-you/your': 'your-grain', 'inquire-you/your': 'asks-you', 'living-being-you/your': 'your-soul', 'particle-of-affirmation': 'only', 'seed-you/your': 'your-seed', 'something-disgusting': 'abomination', 'the-he/it': 'that', 'to-put/set': 'to-put', 'to-reside': 'to-make-dwell', 'try': 'choose', 'wealth': 'treasure'}
assert len(ALREADY) == 25 and sorted(ALREADY) == sorted(g for g in CHG if g in BG and g not in dict(OVERRIDE_GLOSS)) and all(BG[g] == ALREADY[g] for g in ALREADY)
OV = open(f'{ROOT}/logic/glosses/word_gloss_overrides.yaml', encoding='utf-8').read()
MARK = 'THE DEUTERONOMY WALK sitting 12 (2026-09-21, Deuteronomy 14)'
PATCHED = MARK in OV
assert all(f'"{k}": "{v}"' in OV for k, v in ALREADY.items()) and all(f'"{k}": ' not in OV for k, _ in OVERRIDE_GLOSS if not PATCHED) and (PATCHED or '"Deut.14.' not in OV), [k for k, _ in OVERRIDE_GLOSS if f'"{k}": ' in OV]
if PATCHED: assert all(f'"{k}": "{v}"' in OV for k, v in OVERRIDE_REF) and all(f'"{k}": "{v}"' in OV for k, v in OVERRIDE_GLOSS), [k for k, v in OVERRIDE_REF + OVERRIDE_GLOSS if f'"{k}": "{v}"' not in OV][:6]
assert OV.count('  "Deut.13.19:15": "in-the-eyes-of"') == 1 and 'THE DEUTERONOMY WALK sitting 11 (2026-09-21, Deuteronomy 13)' in OV   # sitting 11's anchors, the patch's own
FAIL_ALL = list(FAIL)
