# THE ONKELOS ROWS of Deuteronomy 15:1-11 (THE DEUTERONOMY WALK sitting 13 — CHAPTER 15, 2026-09-22; RUN B1, THE FIRST HALF): the release, the manner, the
# foreigner, the needy and the blessing, the hearing, the lending and the ruling, the hand not shut, the hand opened, the base thought, the gift, the needy
# who never cease. The Aramaic and the Hebrew CUT by consonants in GLOSSED PIECES of at most seven tokens (ch15_ink.HP / AP — the lint's ninety-character
# window). The export's chapter 15 = the DB's (twenty-three rows, the identity — asserted). EVERY ROW READ WHOLE (the whole-row rule; ch15_onkelos.txt).
# ⚠ THE INSTRUMENT FACT (#206): the Aramaic "needy" carries a presentation-form letter the piece cutter does not fold — the pieces on 15:4, 7 and 11 cut
# beside that word, its seats asserted in the ink through NFKC. Chapter 14's form (ch14_rows_onkelos_a.py).
from ch15_ink import *
R = {}
def row(c, v, verdict, prose): R[(c, v)] = (verdict, prose)

row(15, 1, 'MATERIAL', f'AT THE END OF SEVEN YEARS YOU SHALL MAKE A RELEASE. {HP(15, 1, (("מקץ", "שבע", "שנים"), "at the end of seven years — three in the Bible: here, 31:10, Jeremiah 34:14"), (("תעשה", "שמטה"), "you shall make a release — the noun\'s five tokens, all in this book"))} {AP(15, 1, (("מסוף", "שבע", "שנין"), "from the end of seven years"), (("תעבד", "שמטתא"), "you shall make the shemitah — the Hebrew noun kept as Aramaic at its five seats"))} THE HEAD: 111:1\'s end by analogy with 31:10; 111:3-7\'s one calendar; 111:9-11\'s wilderness and territory; 109:3\'s end read as Booths.')
row(15, 2, 'MATERIAL', f'AND THIS IS THE MANNER OF THE RELEASE: EVERY CREDITOR SHALL RELEASE THAT WHICH HE LENT TO HIS NEIGHBOR; HE SHALL NOT EXACT IT OF HIS NEIGHBOR AND HIS BROTHER, FOR A RELEASE HAS BEEN PROCLAIMED TO THE LORD. {HP(15, 2, (("וזה", "דבר", "השמטה"), "and this is the manner of the release — 19:4\'s manslayer the form\'s kin"), (("שמוט", "כל", "בעל", "משה", "ידו"), "release, every creditor — the infinitive absolute, the first of the chapter\'s eight"), (("לא", "יגש", "את", "רעהו", "ואת", "אחיו"), "he shall not exact of his neighbor and his brother — the creditor\'s verb, thirteen in the Bible"))} {AP(15, 2, (("כל", "גבר", "מרי", "רשו"), "every man MASTER OF THE CLAIM — the creditor\'s Aramaic"), (("לא", "יתבע"), "he shall not CLAIM — exact rendered claim"), (("קרא", "שמטתא", "קדם", "יי"), "proclaimed shemitah BEFORE the LORD"))} THE PROCEDURE: 112:1\'s word said (the Mishnah in the spine); 112:2-4\'s two years; 112:5-7\'s loans only; 112:8-11\'s bar, the two exclusions, the territory; 113:2-3\'s pledge and prozbul.')
row(15, 3, 'MATERIAL', f'THE FOREIGNER YOU MAY EXACT; BUT WHAT IS YOURS WITH YOUR BROTHER YOUR HAND SHALL RELEASE. {HP(15, 3, (("את", "הנכרי", "תגש"), "the foreigner you may exact — the book\'s five foreigners"), (("את", "אחיך", "תשמט", "ידך"), "with your brother your hand shall release"))} {AP(15, 3, (("מן", "בר", "עממין", "תתבע"), "from A SON OF THE NATIONS you shall claim — the foreigner\'s rendering at its four seats"), (("תשמט", "ידך"), "your hand shall release"))} THE FOREIGNER: 113:1\'s positive command; 113:2\'s "in your hand"; 113:3\'s "your hand" against the court\'s.')
row(15, 4, 'MATERIAL', f'HOWBEIT THERE SHALL BE NO NEEDY AMONG YOU, FOR THE LORD WILL SURELY BLESS YOU IN THE LAND WHICH THE LORD YOUR GOD GIVES YOU FOR AN INHERITANCE TO POSSESS IT. {HP(15, 4, (("אפס", "כי", "לא", "יהיה", "בך", "אביון"), "howbeit there shall be no needy among you — against 15:11, three tokens shared"), (("כי", "ברך", "יברכך", "יהוה", "בארץ"), "for bless, He will bless you in the land — the doubling\'s one seat"))} {AP(15, 4, (("לחוד", "ארי", "לא", "יהי", "בך"), "ONLY, for there shall not be among you — howbeit rendered only"), (("ברכא", "יברכנך", "יי", "בארעא"), "bless, He will bless you in the land"))} THE NEEDY: 114:1\'s two verses by condition; 114:2\'s blessing only in the Land; 114:3\'s conquest.')
row(15, 5, 'MATERIAL', f'ONLY IF YOU DILIGENTLY HEARKEN TO THE VOICE OF THE LORD YOUR GOD, TO OBSERVE TO DO ALL THIS COMMANDMENT WHICH I COMMAND YOU THIS DAY. {HP(15, 5, (("רק", "אם", "שמוע", "תשמע", "בקול"), "only if hear, you shall hear the voice — the chapter\'s one if"), (("לשמר", "לעשות", "את", "כל", "המצוה", "הזאת"), "to keep to do all this commandment"))} {AP(15, 5, (("קבלא", "תקבל", "למימרא", "דיי"), "RECEIVE, YOU SHALL RECEIVE THE MEMRA of the LORD — the Memra\'s first of three seats in the chapter; 11:13 and 28:1 the form\'s others"), (("די", "אנא", "מפקדך", "יומא", "דין"), "which I command you this day"))} THE CONDITION: 115:1\'s hearing that grows and the scribes\' words; 115:2\'s light and weighty.')
row(15, 6, 'MATERIAL', f'FOR THE LORD YOUR GOD HAS BLESSED YOU AS HE SPOKE TO YOU; AND YOU SHALL LEND TO MANY NATIONS BUT YOU SHALL NOT BORROW, AND YOU SHALL RULE OVER MANY NATIONS BUT THEY SHALL NOT RULE OVER YOU. {HP(15, 6, (("ברכך", "כאשר", "דבר", "לך"), "has blessed you as He spoke to you — the receipt\'s shape, four in the book, no receipt by the finder"), (("והעבטת", "גוים", "רבים", "ואתה", "לא", "תעבט"), "you shall lend to many nations and not borrow — 28:12\'s twin with the other verb"))} {AP(15, 6, (("כמא", "די", "מליל", "לך"), "as He spoke to you — the Aramaic at its four seats"), (("ותוזף", "לעממין", "סגיאין"), "you shall lend to many nations — the verb 28:12 shares"), (("ואת", "לא", "תזוף"), "and you shall not borrow"))} THE BLESSING: 116:1\'s "what did He speak" — 28:3, a verse ahead; 116:2\'s sela and shekel; 116:3\'s Adoni-bezek.')
row(15, 7, 'MATERIAL', f'IF THERE BE AMONG YOU A NEEDY ONE, ONE OF YOUR BROTHERS, WITHIN ONE OF YOUR GATES IN YOUR LAND WHICH THE LORD YOUR GOD GIVES YOU, YOU SHALL NOT HARDEN YOUR HEART NOR SHUT YOUR HAND FROM YOUR NEEDY BROTHER. {HP(15, 7, (("כי", "יהיה", "בך", "אביון", "מאחד", "אחיך"), "if there be among you a needy one of one of your brothers — the parser\'s one"), (("באחד", "שעריך", "בארצך"), "within one of your gates in your land — the formula\'s first seat of four"), (("לא", "תאמץ", "את", "לבבך"), "you shall not harden your heart — Sihon\'s verb"), (("ולא", "תקפץ", "את", "ידך"), "nor shut your hand — the verb\'s one seat in the Torah"))} {AP(15, 7, (("חד", "מאחיך", "בחדא", "מקרויך"), "one of your brothers in one of your CITIES — gates rendered cities"), (("לא", "תתקף", "ית", "לבך"), "you shall not make strong your heart"), (("ולא", "תקפץ", "ית", "ידך"), "nor shut your hand — the root kept"))} THE RANKS: 116:4-9\'s precedence (not others; the hungrier; the father\'s brother; the city; the Land; everywhere); 116:10-11\'s two states; 355:9\'s Moses.')
row(15, 8, 'MATERIAL', f'BUT YOU SHALL SURELY OPEN YOUR HAND TO HIM AND SURELY LEND HIM SUFFICIENT FOR HIS NEED, THAT WHICH HE LACKS. {HP(15, 8, (("כי", "פתח", "תפתח", "את", "ידך", "לו"), "for open, you shall open your hand to him — the first of two, the Psalm\'s the form\'s other"), (("והעבט", "תעביטנו"), "and lend, you shall lend him — the pledge-verb\'s seat"), (("די", "מחסרו", "אשר", "יחסר", "לו"), "sufficient for his need that he lacks — need the Torah\'s one seat"))} {AP(15, 8, (("אלא", "מפתח", "תפתח", "ית", "ידך", "ליה"), "RATHER, open, you shall open your hand to him — the Aramaic adds rather"), (("ואוזפא", "תוזפניה"), "and lend, you shall lend him"), (("כמסת", "חסרוניה"), "according to the measure of his lack"))} THE HAND: 116:12-14\'s hundred times, the words, the pledge dispute; 116:15-18\'s bound, the horse, Hillel, the wife.')
row(15, 9, 'MATERIAL', f'BEWARE LEST THERE BE A BASE THOUGHT IN YOUR HEART, SAYING "THE SEVENTH YEAR, THE YEAR OF RELEASE, DRAWS NEAR", AND YOUR EYE BE EVIL AGAINST YOUR NEEDY BROTHER AND YOU GIVE HIM NOTHING, AND HE CRY AGAINST YOU TO THE LORD AND IT BE SIN IN YOU. {HP(15, 9, (("השמר", "לך", "פן", "יהיה", "דבר"), "beware lest there be a thing — the chapter\'s one imperative"), (("עם", "לבבך", "בליעל", "לאמר"), "with your heart, base, saying — the Torah\'s two seats of base"), (("קרבה", "שנת", "השבע", "שנת", "השמטה"), "the seventh year, the year of release, draws near — the ordinal"), (("וקרא", "עליך", "אל", "יהוה", "והיה", "בך", "חטא"), "and he cry against you to the LORD and it be sin in you — 24:15\'s seven tokens"))} {AP(15, 9, (("אסתמר", "לך", "דילמא"), "guard yourself lest"), (("עם", "לבך", "ברשע", "למימר"), "with your heart IN WICKEDNESS — base rendered wickedness, 13:14\'s word"), (("ויקרי", "עלך", "קדם", "יי"), "and he cry against you before the LORD"), (("ויהי", "בך", "חובא"), "and there be in you GUILT — sin rendered guilt at its four"))} THE WARNING: 117:1\'s yoke, 117:2\'s two prohibitions, 117:3\'s idolatry by analogy, 117:4\'s calendar, 117:5\'s cry; 279:4\'s twin; 111:8; 113:3\'s prozbul from this verse.')
row(15, 10, 'MATERIAL', f'YOU SHALL SURELY GIVE HIM, AND YOUR HEART SHALL NOT BE GRIEVED WHEN YOU GIVE HIM, BECAUSE FOR THIS THING THE LORD YOUR GOD WILL BLESS YOU IN ALL YOUR WORK AND IN ALL YOU PUT YOUR HAND TO. {HP(15, 10, (("נתון", "תתן", "לו"), "give, you shall give him — Jephthah\'s the form\'s other"), (("ולא", "ירע", "לבבך", "בתתך", "לו"), "and your heart shall not be grieved — Elkanah\'s the kin"), (("כי", "בגלל", "הדבר", "הזה"), "because for this thing — ONE seat"), (("ובכל", "משלח", "ידך"), "and in all you put your hand to — the book\'s six"))} {AP(15, 10, (("מתן", "תתן", "ליה"), "give, you shall give him"), (("ולא", "יבאש", "לבך"), "and your heart shall not be evil — 15:9\'s verb again"), (("ובכל", "אושטות", "ידך"), "and in all THE STRETCHING OUT of your hand"))} THE GIFT: 117:6\'s hundred times; 117:7\'s secret chamber; 117:8\'s four grades.')
row(15, 11, 'MATERIAL', f'FOR THE NEEDY SHALL NEVER CEASE OUT OF THE LAND; THEREFORE I COMMAND YOU, SAYING: YOU SHALL SURELY OPEN YOUR HAND TO YOUR BROTHER, TO YOUR POOR AND TO YOUR NEEDY IN YOUR LAND. {HP(15, 11, (("כי", "לא", "יחדל", "אביון", "מקרב", "הארץ"), "for the needy shall not cease from the midst of the land — against 15:4"), (("על", "כן", "אנכי", "מצוך", "לאמר"), "therefore I command you, saying — the book\'s five, Moses\' I"), (("לאחיך", "לעניך", "ולאבינך", "בארצך"), "to your brother, your poor, your needy in your land"))} {AP(15, 11, (("ארי", "לא", "יפסוק"), "for he shall not CEASE — the Aramaic\'s own verb"), (("אנא", "מפקדך", "למימר"), "I command you, saying"), (("לאחוך", "לעניך"), "to your brother, your poor — the needy beside it"))} THE DEFAULT: 118:1\'s two verses upheld; 118:2\'s counsel; 118:3\'s three nouns three measures.')
print('the Onkelos rows 15:1-11 typed:', len(R), '| the cuts\' misses:', FAIL)
