# ---- THE DISPLAY PATCH PREDICTED (the G print of ch15_measure1.out — the store's gloss families over the whole store; sitting 12's form, ch14_ink_body_c.py): BY GLOSS where every token of the gloss is the one word (or one family read the same at every seat), BY REFERENCE where the family is mixed; the counts PRINTED here and typed into the patch script from the print ----
GLOSS_FAMILY = {'remission': [('שמטה', 2)], 'the-remission': [('השמטה', 3)], 'fling-down': [('שמוט', 1), ('תשמט', 1)], 'debt': [('משה', 1)], 'the-strange': [('הנכרי', 1)], 'destitute': [('אביון', 3), ('אביני', 1)], 'the-destitute': [('האביון', 2)], 'and-to-destitute-you/your': [('ולאבינך', 1)], 'to-depressed-you/your': [('לעניך', 1)],
                'draw-together': [('תקפץ', 1)], 'exempt': [('חפשי', 4)], 'emptily': [('ריקם', 6)], 'and-in-something-swinging': [('ובדלת', 1)], 'man-at-wages--by-the-day': [('שכיר', 5)], 'stain': [('מום', 14)], 'in-associate-him/its': [('ברעהו', 1)], 'brother-him/its': [('אחיו', 94)], 'in-broadness.-i.e.--the-ear-him/its': [('באזנו', 1)], 'to-maidservant-you/your': [('לאמתך', 1)],
                'and-from-threshing-floor-you/your': [('ומגרנך', 1)], 'and-from-trough-you/your': [('ומיקבך', 2)], 'from-flock-you/your': [('מצאנך', 1)], 'and-in-flock-you/your': [('ובצאנך', 1)], 'in-herd-you/your': [('בבקרך', 1)], 'bullock-you/your': [('שורך', 3)], 'flock-you/your': [('צאנך', 11)], 'in-firstborn': [('בבכר', 1)],
                'in-eye-you/your': [('בעיניך', 19), ('בעינך', 1)], 'heart-you/your': [('לבבך', 20), ('לבך', 1)], 'in-earth-you/your': [('בארצך', 9)], 'from-brother-you/your': [('מאחיך', 3)], 'to-brother-you/your': [('לאחיך', 6)], 'in-brother-you/your': [('באחיך', 1)], 'deficiency-him/its': [('מחסרו', 1)], 'enough': [('די', 4)], 'in-circumstance': [('בגלל', 2)], 'and-meaning-accession': [('ואף', 7)],
                'in-set-you/your': [('בתתך', 1)], 'and-in-years': [('ובשנה', 4)], 'the-seven': [('השבע', 1)], 'slaughter-an-animal-him/its': [('תזבחהו', 1), ('תזבחנו', 1)], 'crime': [('חטא', 11)], 'to-say': [('לאמר', 305), ('לאמור', 1)], 'in-send-you/your': [('בשלחך', 1)]}
GT = {g: store.execute("SELECT REPLACE(w.he_plain,'/',''), COUNT(*) FROM words w WHERE w.gloss=? GROUP BY 1 ORDER BY 2 DESC, 1", (g,)).fetchall() for g in GLOSS_FAMILY}
assert all(sorted(GT[g]) == sorted(v) for g, v in GLOSS_FAMILY.items()), [(g, GT[g]) for g, v in GLOSS_FAMILY.items() if sorted(GT[g]) != sorted(v)]
# BY GLOSS — the release and its verb, the loan, the foreigner, the needy and the poor, the shut hand, the free man, empty, the door, the hireling, the blemish, the neighbor and the brother, the ear, the maidservant, the floor and the press, the flock and the herd and the ox, the firstling, the eyes, the heart, the land, the need, the sin, "saying"
OVERRIDE_GLOSS = [('remission', 'release'), ('the-remission', 'the-release'), ('fling-down', 'release'), ('debt', 'the-loan-of'), ('the-strange', 'the-foreigner'), ('destitute', 'needy'), ('the-destitute', 'the-needy'), ('and-to-destitute-you/your', 'and-to-your-needy'), ('to-depressed-you/your', 'to-your-poor'),
                  ('draw-together', 'shut'), ('exempt', 'free'), ('emptily', 'empty'), ('and-in-something-swinging', 'and-into-the-door'), ('man-at-wages--by-the-day', 'a-hireling'), ('stain', 'blemish'), ('in-associate-him/its', 'to-his-neighbor'), ('brother-him/its', 'his-brother'), ('in-broadness.-i.e.--the-ear-him/its', 'through-his-ear'), ('to-maidservant-you/your', 'to-your-maidservant'),
                  ('and-from-threshing-floor-you/your', 'and-from-your-threshing-floor'), ('and-from-trough-you/your', 'and-from-your-winepress'), ('from-flock-you/your', 'from-your-flock'), ('and-in-flock-you/your', 'and-in-your-flock'), ('in-herd-you/your', 'in-your-herd'), ('bullock-you/your', 'your-ox'), ('flock-you/your', 'your-flock'), ('in-firstborn', 'with-the-firstling-of'),
                  ('in-eye-you/your', 'in-your-eyes'), ('heart-you/your', 'your-heart'), ('in-earth-you/your', 'in-your-land'), ('from-brother-you/your', 'from-your-brother'), ('to-brother-you/your', 'to-your-brother'), ('in-brother-you/your', 'against-your-brother'), ('deficiency-him/its', 'his-need'), ('enough', 'sufficient-for'), ('in-circumstance', 'because-of'), ('and-meaning-accession', 'and-also'),
                  ('in-set-you/your', 'when-you-give'), ('and-in-years', 'and-in-the-year'), ('the-seven', 'the-seventh'), ('slaughter-an-animal-him/its', 'you-shall-sacrifice-it'), ('crime', 'sin'), ('to-say', 'saying'), ('in-send-you/your', 'when-you-let-go')]
# BY REFERENCE — the family mixed (a homograph or a form read two ways: "drive" the taskmasters and the creditor, "cessation" the ends of the earth, "pawn" Judah's pledge, "collar" Joseph's, "the-Eberite" the Hebrews and the woman, "repetition" the copy of the law, "cut-off" the shearing, "that" against "for", "if", "but" and "because"; a verb's person or tense; a noun singular and plural; the three "?" of Moses' "I"): the seat named
OVERRIDE_REF_SPEC = [(1, 'מקץ', 'at-the-end-of', 0), (1, 'תעשה', 'you-shall-make', 0),
                     (2, 'דבר', 'the-manner-of', 0), (2, 'כל', 'every', 0), (2, 'בעל', 'creditor', 0), (2, 'ידו', 'his-hand', 0), (2, 'ישה', 'lends', 0), (2, 'יגש', 'exact', 0), (2, 'כי', 'for', 0), (2, 'קרא', 'has-been-proclaimed', 0),
                     (3, 'תגש', 'you-may-exact', 0), (3, 'יהיה', 'is', 0), (3, 'לך', 'yours', 0), (3, 'ידך', 'your-hand', 0),
                     (4, 'אפס', 'howbeit', 0), (4, 'יהיה', 'there-shall-be', 0), (4, 'בך', 'among-you', 0), (4, 'כי', 'for', 1), (4, 'יברכך', 'He-will-bless-you', 0), (4, 'בארץ', 'in-the-land', 0), (4, 'נתן', 'gives', 0), (4, 'לך', 'you', 0), (4, 'נחלה', 'for-an-inheritance', 0),
                     (5, 'שמוע', 'hearken', 0), (5, 'תשמע', 'you-shall-hearken', 0), (5, 'בקול', 'to-the-voice-of', 0), (5, 'לשמר', 'to-keep', 0), (5, 'לעשות', 'to-do', 0), (5, 'הזאת', 'this', 0), (5, 'אנכי', 'I', 0), (5, 'מצוך', 'command-you', 0), (5, 'היום', 'today', 0),
                     (6, 'כי', 'for', 0), (6, 'ברכך', 'has-blessed-you', 0), (6, 'דבר', 'He-spoke', 0), (6, 'לך', 'to-you', 0), (6, 'והעבטת', 'and-you-shall-lend', 0), (6, 'גוים', 'nations', 0), (6, 'רבים', 'many', 0), (6, 'תעבט', 'borrow', 0), (6, 'ומשלת', 'and-you-shall-rule', 0), (6, 'בגוים', 'over-nations', 0), (6, 'רבים', 'many', 1), (6, 'ובך', 'and-over-you', 0), (6, 'ימשלו', 'they-shall-rule', 0),
                     (7, 'כי', 'if', 0), (7, 'יהיה', 'there-be', 0), (7, 'בך', 'among-you', 0), (7, 'מאחד', 'of-one-of', 0), (7, 'נתן', 'gives', 0), (7, 'לך', 'you', 0), (7, 'תאמץ', 'you-shall-harden', 0), (7, 'ידך', 'your-hand', 0),
                     (8, 'כי', 'but', 0), (8, 'פתח', 'open', 0), (8, 'תפתח', 'you-shall-open', 0), (8, 'ידך', 'your-hand', 0), (8, 'לו', 'to-him', 0), (8, 'והעבט', 'and-lend', 0), (8, 'תעביטנו', 'you-shall-lend-him', 0), (8, 'יחסר', 'he-lacks', 0), (8, 'לו', 'to-him', 1),
                     (9, 'השמר', 'beware', 0), (9, 'לך', 'to-yourself', 0), (9, 'יהיה', 'there-be', 0), (9, 'דבר', 'a-thought', 0), (9, 'קרבה', 'draws-near', 0), (9, 'שנת', 'the-year-of', 0), (9, 'שנת', 'the-year-of', 1), (9, 'ורעה', 'and-be-evil', 0), (9, 'עינך', 'your-eye', 0), (9, 'תתן', 'give', 0), (9, 'לו', 'to-him', 0), (9, 'וקרא', 'and-he-cry', 0), (9, 'עליך', 'against-you', 0), (9, 'והיה', 'and-it-be', 0), (9, 'בך', 'in-you', 0),
                     (10, 'נתון', 'give', 0), (10, 'תתן', 'you-shall-give', 0), (10, 'לו', 'to-him', 0), (10, 'ירע', 'be-grieved', 0), (10, 'לו', 'to-him', 1), (10, 'כי', 'because', 0), (10, 'הדבר', 'thing', 0), (10, 'הזה', 'this', 0), (10, 'יברכך', 'will-bless-you', 0), (10, 'מעשך', 'your-work', 0), (10, 'ידך', 'your-hand', 0),
                     (11, 'כי', 'for', 0), (11, 'יחדל', 'shall-cease', 0), (11, 'הארץ', 'the-land', 0), (11, 'אנכי', 'I', 0), (11, 'מצוך', 'command-you', 0), (11, 'פתח', 'open', 0), (11, 'תפתח', 'you-shall-open', 0), (11, 'ידך', 'your-hand', 0),
                     (12, 'כי', 'if', 0), (12, 'ימכר', 'be-sold', 0), (12, 'לך', 'to-you', 0), (12, 'העברי', 'the-Hebrew-man', 0), (12, 'העבריה', 'the-Hebrew-woman', 0), (12, 'ועבדך', 'and-he-shall-serve-you', 0), (12, 'תשלחנו', 'you-shall-let-him-go', 0),
                     (13, 'וכי', 'and-when', 0), (13, 'תשלחנו', 'you-let-him-go', 0), (13, 'תשלחנו', 'you-shall-let-him-go', 1),
                     (14, 'העניק', 'furnish', 0), (14, 'תעניק', 'you-shall-furnish', 0), (14, 'לו', 'him', 0), (14, 'ברכך', 'has-blessed-you', 0), (14, 'תתן', 'you-shall-give', 0), (14, 'לו', 'to-him', 1),
                     (15, 'עבד', 'a-slave', 0), (15, 'היית', 'you-were', 0), (15, 'בארץ', 'in-the-land-of', 0), (15, 'אנכי', 'I', 0), (15, 'מצוך', 'command-you', 0), (15, 'הדבר', 'thing', 0), (15, 'הזה', 'this', 0), (15, 'היום', 'today', 0),
                     (16, 'והיה', 'and-it-shall-be', 0), (16, 'כי', 'if', 0), (16, 'יאמר', 'he-says', 0), (16, 'אליך', 'to-you', 0), (16, 'אצא', 'I-will-go-out', 0), (16, 'כי', 'because', 1), (16, 'אהבך', 'he-loves-you', 0), (16, 'ביתך', 'your-house', 0), (16, 'כי', 'because', 2), (16, 'טוב', 'it-is-well', 0), (16, 'לו', 'with-him', 0), (16, 'עמך', 'with-you', 0),
                     (17, 'ולקחת', 'and-you-shall-take', 0), (17, 'ונתתה', 'and-put-it', 0), (17, 'והיה', 'and-he-shall-be', 0), (17, 'לך', 'to-you', 0), (17, 'עבד', 'a-servant', 0), (17, 'תעשה', 'you-shall-do', 0),
                     (18, 'יקשה', 'let-it-seem-hard', 0), (18, 'אתו', 'him', 0), (18, 'כי', 'for', 0), (18, 'משנה', 'double', 0), (18, 'שכר', 'the-hire-of', 0), (18, 'עבדך', 'he-has-served-you', 0), (18, 'וברכך', 'and-will-bless-you', 0), (18, 'תעשה', 'you-do', 0),
                     (19, 'כל', 'every', 0), (19, 'הבכור', 'the-firstling', 0), (19, 'יולד', 'is-born', 0), (19, 'תקדיש', 'you-shall-sanctify', 0), (19, 'תעבד', 'you-shall-work', 0), (19, 'תגז', 'you-shall-shear', 0), (19, 'בכור', 'the-firstling-of', 0),
                     (20, 'לפני', 'before', 0), (20, 'תאכלנו', 'you-shall-eat-it', 0), (20, 'שנה', 'year', 0), (20, 'בשנה', 'by-year', 0),
                     (21, 'וכי', 'and-if', 0), (21, 'יהיה', 'there-be', 0), (21, 'בו', 'in-it', 0), (21, 'כל', 'any', 0), (21, 'רע', 'evil', 0),
                     (22, 'תאכלנו', 'you-shall-eat-it', 0),
                     (23, 'דמו', 'its-blood', 0), (23, 'תאכל', 'you-shall-eat', 0), (23, 'על', 'upon', 0), (23, 'הארץ', 'the-ground', 0), (23, 'תשפכנו', 'you-shall-pour-it', 0)]
OVERRIDE_REF3 = [(f'Deut.15.{v}:{sidx(15, v, tok, nth)}', new, tok) for v, tok, new, nth in OVERRIDE_REF_SPEC]
OVERRIDE_REF = [(k, v) for k, v, _ in OVERRIDE_REF3]
assert len(OVERRIDE_REF) == len({k for k, _ in OVERRIDE_REF}) == len(OVERRIDE_REF_SPEC) and len(OVERRIDE_GLOSS) == len({k for k, _ in OVERRIDE_GLOSS}) and all(g in GLOSS_FAMILY for g, _ in OVERRIDE_GLOSS) and all(sg(15, v, tok, nth) is not None for v, tok, _, nth in OVERRIDE_REF_SPEC)
assert all(sg(15, v, tok, nth) != new for v, tok, new, nth in OVERRIDE_REF_SPEC), [(v, tok) for v, tok, new, nth in OVERRIDE_REF_SPEC if sg(15, v, tok, nth) == new]   # no row rewrites a gloss to itself
assert all(sg(15, v, tok, nth) not in dict(OVERRIDE_GLOSS) for v, tok, _, nth in OVERRIDE_REF_SPEC), [(v, tok, sg(15, v, tok, nth)) for v, tok, _, nth in OVERRIDE_REF_SPEC if sg(15, v, tok, nth) in dict(OVERRIDE_GLOSS)]   # a seat patched by gloss is not patched again by reference
print('THE DISPLAY PATCH PREDICTED — by gloss', len(OVERRIDE_GLOSS), 'by reference', len(OVERRIDE_REF))
# the chapter's glosses ALREADY rewritten by the by-gloss overrides (the G print's twenty-five; "?" mapped to the empty string there)
ALREADY = {'?': '', 'God-you/your': 'your-God', 'and-house-you/your': 'and-your-household', 'and-like-stag': 'and-as-the-hart', 'and-mark': 'and-remember', 'and-sever-you/your': 'and-redeemed-you', 'and-the-pure': 'and-the-clean', 'associate-him/its': 'his-neighbor', 'brother-you/your': 'your-brother', 'from-nearest-part': 'from-the-midst-of', 'from-with-you/your': 'from-you', 'gate-you/your': 'your-gates', 'in-gate-you/your': 'within-your-gates', 'in-one': 'in-one-of', 'in-place': 'in-the-place', 'leanness': 'only', 'like-as/which': 'as', 'like-splendor': 'as-the-gazelle', 'like-waters': 'like-water', 'sending-out': 'the-undertaking-of', 'the-foul-in-a-religious-sense': 'the-unclean', 'to-possess/inherit-her/its': 'to-possess-it', 'try': 'choose', 'unit': 'together', 'without-profit': 'Belial'}
assert len(ALREADY) == 25 and sorted(ALREADY) == sorted(g for g in CHG if g in BG and g not in dict(OVERRIDE_GLOSS)) and all(BG[g] == ALREADY[g] for g in ALREADY), sorted(set(g for g in CHG if g in BG and g not in dict(OVERRIDE_GLOSS)) ^ set(ALREADY))
OV = open(f'{ROOT}/logic/glosses/word_gloss_overrides.yaml', encoding='utf-8').read()
assert all(f'"{k}": "{v}"' in OV for k, v in ALREADY.items() if v) and all(f'"{k}": ' not in OV for k, _ in OVERRIDE_GLOSS if not PATCHED) and (PATCHED or '"Deut.15.' not in OV), [k for k, _ in OVERRIDE_GLOSS if f'"{k}": ' in OV]
if PATCHED: assert all(f'"{k}": "{v}"' in OV for k, v in OVERRIDE_REF) and all(f'"{k}": "{v}"' in OV for k, v in OVERRIDE_GLOSS), [k for k, v in OVERRIDE_REF + OVERRIDE_GLOSS if f'"{k}": "{v}"' not in OV][:6]
assert OV.count('  "Deut.14.29:23": "you-do"') == 1 and 'THE DEUTERONOMY WALK sitting 12 (2026-09-21, Deuteronomy 14)' in OV   # sitting 12's anchors, the patch's own
print('THE INK OF CHAPTER 15 WITH ITS PATCH BLOCK — PATCHED:', PATCHED, '| the cuts\' misses:', FAIL_ALL)
