# THE DEUTERONOMY WALK 13b — THE EXAM DOCKET OF CHAPTER 15, part H (D2a): KIDDUSHIN 14b-22b WHOLE, THE SECOND HALF — the folios 18a, 18b, 19a, 19b, 20a, 20b, 21a,
# 21b, 22a, 22b with their own link rows (the maidservant's sale, designation and second sale; the thief's sale; the board 'with you'; the redemption's price and
# the walled cities' houses (outside); the awl's tools, the upper ear and the priest-slave; the two sayings; the slave's family fed; the ear's homily; Mishnah
# Kiddushin 1:3's Canaanite slave (outside)). The credited rows CARRIED, the unresolved credited rows READ WHOLE in ch15_docket_U.py, the uncredited READ WHOLE HERE
# (ch15_uncred_d2k_00.txt's tail, ch15_uncred_d2k_01.txt, ch15_uncred_d2k_02.txt). The verdicts and the cells as in part G; every middah code checked in
# logic/MIDDOT.md before it was typed (I1, I2, I6); the amplification-restriction named as the rival method, no code. 12b's form; the selection by folio computed.
from ch15_docket_common import R, build_set, apply_whole, CREDITED_SPEC, D2_UNIQUE, KIND_FIRST, long_range
from ch15_docket_U import OWN_U
FOL = {'18a', '18b', '19a', '19b', '20a', '20b', '21a', '21b', '22a', '22b'}
def _sel(a): return long_range(a) == 'Kiddushin 14b-22b' and a.split(' ')[1].split(':')[0] in FOL
OWN = [
 # THE LINK ROWS (the dump's 74-78)
 ('Kiddushin 20a:14', 'LAW', "Abaye: the verses read leniently — the Merciful One is lenient with the slave's welfare: 'because he fares well with you' (15:16), with you in food and in drink: F5 — the board (15:16's 'with you'); the redemption's leniency (20a:9-12) hangs on it."),
 ('Kiddushin 21b:5', 'DISPUTE', "'an awl' — and a thorn, a needle, an auger, a stylus? 'AND YOU SHALL TAKE the awl' (15:17) includes anything taken in the hand — R. Yosei son of R. Yehuda: F5 — the_awl_tool's first arm (122:1); the exam's arm."),
 ('Kiddushin 21b:8', 'DERIVATION', "Rabbi by GENERAL-PARTICULAR-GENERAL (I6): 'you shall take' general, 'the awl' particular, 'through his ear and into the door' general — like the particular: METAL: F5 — the_awl_tool's second arm's method (122:1's dispute at its Bavli seat)."),
 ('Kiddushin 22a:8', 'LAW', "he loves the master and not the reverse — not pierced ('because he fares well WITH YOU' — good for both); the master loves him and not he — not pierced ('because he loves you'); he ill, the master not — not pierced ('fares well'); the master ill — not pierced ('with you'): F5 — 121:3 and 121:4 at their Bavli seat (the mutual love; illness in either bars the rite); the exam's rows."),
 # 18a — THE TWO TABLES; THE THIEF'S SALE; THE MAIDSERVANT REDEEMED AGAINST THE WILL
 ('Kiddushin 18a:1', 'CONTEXT', "conceived before her conversion, born after — returned to him (17b:19's resolution)."),
 ('Kiddushin 18a:3', 'OUTSIDE', "Rav Chiyya bar Avin's and Rava's sources for the gentile's inheritance — an exposition against a verse."),
 ('Kiddushin 18a:4', 'OUTSIDE', "Abraham's honor — the convert's inheritance."),
 ('Kiddushin 18a:5', 'LAW', "the baraita — the slave's own: six years, the jubilee, the master's death; the maidservant's own: the signs, not sold twice, redeemed against the will: F4 — the_exits_tables (118:5's DATA row at its Bavli seat); the exam's table."),
 ('Kiddushin 18a:6', 'LAW', "against the Mishnah's 'one more' — Rav Sheshet: the baraita where the master designated her (she is his wife, not freed by the slave's ways): F4 — the exits table's condition (mishpatim_3.maidservant(designation) by CALL)."),
 ('Kiddushin 18a:10', 'DERIVATION', "Abaye: 'for his theft' even many thefts — one victim (not sold twice) against two victims (sold again): F4 — the court's sale's second sale (a DATA row)."),
 ('Kiddushin 18a:11', 'DISPUTE', "stole a thousand, worth five hundred — sold and sold again; stole five hundred, worth a thousand — not sold; R. Eliezer: sold only when exactly equal: F4 — the court's sale's condition, two arms."),
 ('Kiddushin 18a:12', 'DERIVATION', "Rava: R. Eliezer's triumph — 'he is sold' wholly and not in part; 'for his theft' and not for part of it."),
 ('Kiddushin 18a:13', 'CONTEXT', "'redeemed against the will' — Rava's reading (the master's) refused by Abaye: a pearl for a shard."),
 ('Kiddushin 18a:14', 'LAW', "Abaye: against the FATHER's will, for the family's flaw — the court presses him; the slave's family not pressed (he would sell himself again): F4 — the maidservant's redemption (mishpatim_3.maidservant(redemption) by CALL); a DATA row."),
 ('Kiddushin 18a:15', 'LAW', "the maidservant not sold twice — R. Shimon: not into slavery after slavery, as not after marriage: F4 — the maidservant's exits (118:5's 'not sold twice')."),
 # 18b-19a — THE SECOND SALE'S VERSE; THE DESIGNATION
 ('Kiddushin 18b:1', 'DISPUTE', "'bevigdo vah' (\"since he dealt deceitfully with her\", Exodus 21:8) — R. Akiva: his garment spread over her (designated: no further sale); R. Eliezer: dealt deceitfully — sold once, not again: F4 — a DATA row (the second sale's ground)."),
 ('Kiddushin 18b:2', 'DISPUTE', "the written form against the reading — R. Eliezer the spelling ('betrayal'), R. Akiva the vocalization ('garment'), R. Shimon both: a DATA row of the method; the maidservant's second sale barred both ways."),
 ('Kiddushin 18b:3', 'CONTEXT', "Rabba bar Avuh's dilemma — designation a marriage or a betrothal (her estate, the priest's burial, her vows)."),
 ('Kiddushin 18b:4', 'CONTEXT', "the proof from 'bevigdo vah' (\"his garment over her\") — betrothal only, else no later designation by the father."),
 ('Kiddushin 18b:5', 'CONTEXT', "Rav Nachman bar Yitzchak: the baraita speaks of an ordinary betrothal — no proof."),
 ('Kiddushin 18b:6', 'DISPUTE', "the sale to relatives forbidden to her — barred (no designation possible); in R. Eliezer's name allowed (designation optional); agreed for the High Priest's widow and the common priest's divorcee: F4 — the maidservant's sale's persons (a DATA row)."),
 ('Kiddushin 18b:7', 'CONTEXT', "the widow's case — betrothed by her father and widowed? then no sale after marriage."),
 ('Kiddushin 18b:8', 'CONTEXT', "R. Yitzchak: widowed from a designation's betrothal — R. Yosei son of R. Yehuda's second money."),
 ('Kiddushin 18b:9', 'CONTEXT', "the other horn — betrothal by her differs from betrothal by her father."),
 ('Kiddushin 18b:10', 'CONTEXT', "one betrothal differs from another; one marriage from another? (19a:1)."),
 ('Kiddushin 19a:1', 'CONTEXT', "in both marriages she leaves the father's authority — no second sale."),
 ('Kiddushin 19a:5', 'CONTEXT', "the minor son's designation — Rav Ashi: the verse's minor is a levir of nine years and a day whose act counts."),
 ('Kiddushin 19a:6', 'CONTEXT', "the levir's wife fit by Torah law, yet not a married woman — the verse needed."),
 ('Kiddushin 19a:11', 'LAW', "R. Yosei son of R. Yehuda: designation only if a peruta's work remains in the day — the sale's money not given for betrothal: F4 — the designation's timing (mishpatim_3.maidservant(designation) by CALL); the arm."),
 ('Kiddushin 19a:12', 'DERIVATION', "Rav Nachman bar Yitzchak: 'who did not designate her, then he shall let her be redeemed' (Exodus 21:8) — designation while she can be redeemed, a Torah edict: a juxtaposition, no code."),
 ('Kiddushin 19a:13', 'OUTSIDE', "Rav Nachman: a father tells his minor daughter to accept her own betrothal — the betrothal's law, derived from the maidservant."),
 ('Kiddushin 19a:14', 'OUTSIDE', "the same — the daughter her own agent."),
 ('Kiddushin 19a:15', 'OUTSIDE', "betrothal with a loan on collateral — the betrothal's law."),
 ('Kiddushin 19b:1', 'OUTSIDE', "the same — the remaining service a loan, she the collateral."),
 ('Kiddushin 19b:2', 'LAW', "how designation is done — before two witnesses 'you are betrothed to me', even at the six years' end near sunset; then a wife's treatment, not a slave's; R. Yosei's peruta: F4 — the designation's form (a DATA row; mishpatim_3.maidservant(designation) by CALL)."),
 ('Kiddushin 19b:3', 'CONTEXT', "the parable of 'from now after thirty days' — whose opinion?"),
 ('Kiddushin 19b:4', 'CONTEXT', "not R. Yosei son of R. Yehuda's — his betrothal begins at the designation."),
 ('Kiddushin 19b:5', 'CONTEXT', "Rav Acha son of Rava: the Rabbis' — a retroactive betrothal from the sale."),
 ('Kiddushin 19b:6', 'CONTEXT', "the parable's lesson — 'from now' must have been said at the sale."),
 ('Kiddushin 19b:7', 'DISPUTE', "the father who sells her and then betroths her to another — R. Yosei son of R. Yehuda: he mocks the master, she is the second's; the Rabbis: the master may designate: F4 — a DATA row."),
 ('Kiddushin 19b:8', 'CONTEXT', "the parable 'after thirty days' — the second's."),
 ('Kiddushin 19b:9', 'CONTEXT', "not the Rabbis'."),
 ('Kiddushin 19b:10', 'CONTEXT', "Rav Acha son of Rava: R. Yosei's."),
 ('Kiddushin 19b:11', 'CONTEXT', "the parable's lesson — even 'after thirty days' at the sale would not hold against the father's betrothal."),
 ('Kiddushin 19b:12', 'DISPUTE', "the sale on condition of no designation — R. Meir: the condition stands; the Rabbis: he may designate, the condition against the Torah void: F4 — a DATA row (the maidservant's stipulation)."),
 ('Kiddushin 19b:13', 'CONTEXT', "R. Meir's own rule — a betrothal's condition against food, clothing and conjugal rights void: the contradiction (19b:14 answers)."),
 ('Kiddushin 19b:15', 'DERIVATION', "the Rabbis' use of 'as a maidservant' (Exodus 21:7) — sold to people of flawed lineage (a mamzer — one born of a forbidden union)."),
 ('Kiddushin 19b:16', 'DERIVATION', "the a fortiori from betrothal refuted — the father betroths even a young woman but sells only a minor: the verse needed."),
 # 20a — THE SALE TO RELATIVES; THE BODY; THE REDEMPTION'S PRICE; THE BOARD; THE LADDER
 ('Kiddushin 20a:1', 'DERIVATION', "R. Eliezer's 'as a maidservant' — to relatives, even his father."),
 ('Kiddushin 20a:2', 'DERIVATION', "the refutation — the flawed lineage admits a designation, the relatives none: the verse needed."),
 ('Kiddushin 20a:4', 'DISPUTE', "two baraitot — to his father yes and to his son no; to neither: whose?"),
 ('Kiddushin 20a:5', 'CONTEXT', "the Rabbis' — where a designation is possible (the father's other son, her uncle) the sale stands."),
 ('Kiddushin 20a:7', 'DERIVATION', "Rava: 'with his body he shall leave' (Exodus 21:3) — not released by a lost limb, nor paid its value and released: F4 — the Hebrew slave not freed by injury (mishpatim_2.slave_maimed the Canaanite's by CALL — the Hebrew excluded)."),
 ('Kiddushin 20a:8', 'DISPUTE', "R. Eliezer ben Yaakov: 'alone in, alone out' — the Canaanite maidservant only for one who has a wife and children: F5 — the night's service's condition (a DATA row)."),
 ('Kiddushin 20a:9', 'LAW', "sold for a hundred and worth two hundred — redeemed on a hundred: 'out of the money that he was bought for' (Leviticus 25:51): F4 — the deduction's price (redeemed_by_deduction by CALL to mishpatim; yovel.hebrew_slave)."),
 ('Kiddushin 20a:10', 'LAW', "sold for two hundred and worth a hundred — on a hundred: 'according to his years' (Leviticus 25:52): the lower always: F4 — the deduction's price."),
 ('Kiddushin 20a:11', 'DERIVATION', "the gentile's sale lenient in its redemption — the source's own case."),
 ('Kiddushin 20a:12', 'DERIVATION', "I2 'hired worker' / 'hired worker' (Leviticus 25:40; 25:53) — the Jew's sale the same price rule: F4 — the deduction's price for both sales."),
 ('Kiddushin 20a:13', 'CONTEXT', "Abaye's ben Azzai — why read the two verses leniently and not strictly?"),
 ('Kiddushin 20a:15', 'LAW', "the board — not fine bread against coarse, aged wine against new, soft bedding against straw; 'one who acquires a Hebrew slave acquires a master': F5 — 'with you' (15:16) the board (Arakhin 30b:2's twin; 22a:10 the baraita whole); the exam's row."),
 ('Kiddushin 20a:16', 'CONTEXT', "the objection — lenient in food, strict in redemption? R. Yosei son of R. Chanina on the sabbatical's hint (the ladder of Leviticus 25)."),
 ('Kiddushin 20a:17', 'OUTSIDE', "the ladder — trade in sabbatical produce, then the movables sold (Leviticus 25:13-14 juxtaposed): Leviticus 25's homiletic ladder."),
 ('Kiddushin 20a:18', 'OUTSIDE', "then the fields (25:25), then the house (25:29)."),
 ('Kiddushin 20a:19', 'OUTSIDE', "Rav Huna: a sin repeated becomes as permitted — the ladder's wording."),
 ('Kiddushin 20a:21', 'CONTEXT', "the ladder's rungs — interest (Leviticus 25:35-36), then the self-sale (25:39): the self-seller's cause named in the homily."),
 ('Kiddushin 20a:22', 'CONTEXT', "sold to a stranger — the resident alien, the gentile, 'an offshoot of a stranger's family' the idol's temple (20b:1)."),
 # 20b-21a — THE REDEMPTION'S SHAPE; THE WALLED CITIES' HOUSES (outside); THE REDEEMERS
 ('Kiddushin 20b:1', 'CONTEXT', "sold to serve an idol's temple — his sins brought him there: strict in his redemption? asked."),
 ('Kiddushin 20b:2', 'DERIVATION', "the school of R. Yishmael: 'after he is sold he shall be redeemed' (Leviticus 25:48) — no stone thrown after the fallen: F4 — the redemption a duty (21b:1)."),
 ('Kiddushin 20b:3', 'CONTEXT', "redeem him from assimilation, yet strict in the price? — asked."),
 ('Kiddushin 20b:4', 'DERIVATION', "Rav Nachman bar Yitzchak: 'many of the years' and 'few of the years' (Leviticus 25:51-52) — his value risen or fallen, the lower reckoning: F4 — the deduction's price's ground."),
 ('Kiddushin 20b:5', 'DERIVATION', "the alternative (years served, years left) put."),
 ('Kiddushin 20b:6', 'DERIVATION', "'OF the years' decides — the value's change; Rav Yosef: 'expounded like Sinai'."),
 ('Kiddushin 20b:7', 'CONTEXT', "the mnemonic; Rav Huna bar Chinnana's dilemma — the gentile's slave partly redeemed?"),
 ('Kiddushin 20b:8', 'DERIVATION', "I2 'his redemption' / 'his redemption' (Leviticus 25:52; 25:26 the ancestral field) — no partial redemption; or only where it is a leniency: F4 — the redemption's shape (20b:9's Rav Sheshet)."),
 ('Kiddushin 20b:10', 'CONTEXT', "Abaye: the partial redemption's leniency case (a hundred, half paid, then two hundred)."),
 ('Kiddushin 20b:11', 'CONTEXT', "the lower reckoning squared with the case — risen before the sale, fallen, risen again."),
 ('Kiddushin 20b:12', 'CONTEXT', "the stringency case (two hundred, half paid, then a hundred) — the hundred a deposit."),
 ('Kiddushin 20b:13', 'OUTSIDE', "the walled city's house partly redeemed? (Leviticus 25:29) — the houses' law."),
 ('Kiddushin 20b:14', 'OUTSIDE', "the field's 'sufficient means' (Leviticus 25:26) not written of the house."),
 ('Kiddushin 20b:15', 'OUTSIDE', "R. Shimon: 'redeem, he shall redeem' (Leviticus 27:19) — borrow and redeem, redeem in part."),
 ('Kiddushin 20b:16', 'OUTSIDE', "the seller's power enhanced (the field returns), so diminished (no loan, no part)."),
 ('Kiddushin 20b:17', 'OUTSIDE', "the consecrator's power diminished (the field to the priests), so enhanced."),
 ('Kiddushin 20b:18', 'OUTSIDE', "the house's seller diminished (a year), so enhanced."),
 ('Kiddushin 20b:19', 'OUTSIDE', "the objecting baraita — Leviticus 27:19's borrow-and-redeem."),
 ('Kiddushin 20b:20', 'OUTSIDE', "its a fortiori (I1) from the field's seller to the consecrator."),
 ('Kiddushin 20b:21', 'OUTSIDE', "refuted — the seller cannot redeem at once (two years); the consecrator can."),
 ('Kiddushin 20b:22', 'OUTSIDE', "the walled house proves — redeemable at once yet no loan, no part; Rav Sheshet: no difficulty (21a:1)."),
 ('Kiddushin 21a:1', 'OUTSIDE', "the Rabbis against R. Shimon."),
 ('Kiddushin 21a:2', 'OUTSIDE', "the two baraitot on the walled house — the Rabbis and R. Shimon."),
 ('Kiddushin 21a:3', 'OUTSIDE', "the mnemonic of the three pairs."),
 ('Kiddushin 21a:4', 'OUTSIDE', "Rav Acha son of Rava: the house's seller cannot redeem forever, the consecrator can."),
 ('Kiddushin 21a:5', 'OUTSIDE', "Rav Acha Sava: the common factor of the field and the house."),
 ('Kiddushin 21a:6', 'OUTSIDE', "the derivation reverts — the common factor: no loan, no part."),
 ('Kiddushin 21a:7', 'OUTSIDE', "Mar Zutra: the common factor's flaw — neither redeems in the second year."),
 ('Kiddushin 21a:8', 'CONTEXT', "Ravina: the gentile's slave proves — he redeems in the second year, yet no loan and no part: the slave's redemption's shape named as the proof (20b:9)."),
 ('Kiddushin 21a:9', 'OUTSIDE', "the walled house redeemed by relatives? — the analogy 'his redemption' / 'his redemption' (Leviticus 25:29; 25:26)."),
 ('Kiddushin 21a:10', 'OUTSIDE', "Rav Sheshet: not by relatives."),
 ('Kiddushin 21a:11', 'DERIVATION', "'in all your ancestral land you shall grant redemption' (Leviticus 25:24) — to include houses and A HEBREW SLAVE: which houses, which slave asked (21a:20 the gentile's)."),
 ('Kiddushin 21a:12', 'OUTSIDE', "the open-area houses already 'reckoned with the field' (Leviticus 25:31) — the verse makes redemption an obligation (R. Eliezer)."),
 ('Kiddushin 21a:13', 'OUTSIDE', "R. Yehoshua: the field's redemption optional — 'if a man has no redeemer' (Leviticus 25:26)."),
 ('Kiddushin 21a:14', 'OUTSIDE', "R. Eliezer: an obligation from 25:24."),
 ('Kiddushin 21a:15', 'OUTSIDE', "'in all' for the walled houses, else what? — a difficulty."),
 ('Kiddushin 21a:16', 'DERIVATION', "'may redeem him' three times (Leviticus 25:48-49) — every redemption in its order: himself, a brother, an uncle; houses and the slave? — no: the open houses and the field: F4 — the redeemers' order for the gentile's slave (a DATA row)."),
 ('Kiddushin 21a:17', 'CONTEXT', "Rav Nachman bar Yitzchak: the nearer relative first — the field and the open houses too."),
 ('Kiddushin 21a:18', 'DISPUTE', "the dilemma's seat — a Hebrew slave sold to a JEW redeemed by relatives? per Rabbi no (the gentile's too is 'by six years'): F4 — the Jew's sale's redeemers, an OPEN dilemma (a DATA row)."),
 ('Kiddushin 21a:19', 'DISPUTE', "per the Rabbis — the analogy 'hired worker' / 'hired worker' (relatives for both) against 'may redeem HIM' restricting to the gentile's: the two arms."),
 ('Kiddushin 21a:20', 'DERIVATION', "the baraita's 'in all' — the gentile's slave, says the rejection."),
 ('Kiddushin 21a:21', 'DERIVATION', "the gentile's slave already explicit (Leviticus 25:49) — 21b:1 answers."),
 # 21b-22b — THE OBLIGATION; THE AWL'S TOOLS AND THE EAR; THE PRIEST-SLAVE; THE CAPTIVE (outside); THE TWO SAYINGS; THE FAMILY FED; THE HOMILIES; THE CANAANITE SLAVE (outside)
 ('Kiddushin 21b:1', 'LAW', "the gentile's slave's redemption an OBLIGATION even per R. Yehoshua — lest he be assimilated: F4 — the redemption's duty (20b:2's school of R. Yishmael); a DATA row."),
 ('Kiddushin 21b:2', 'CONTEXT', "the second baraita ('may redeem him' thrice) — the same answer: the open houses and the field; Rav Nachman bar Yitzchak's order."),
 ('Kiddushin 21b:6', 'DISPUTE', "Rabbi: metal only — like the awl; or 'the awl' includes the large awl: F5 — the_awl_tool's second arm (122:1; 21b:8's I6)."),
 ('Kiddushin 21b:7', 'DISPUTE', "Yudan the Distinguished: the lobe alone; the Rabbis: the upper ear through the cartilage — a priest-slave is not pierced at all lest he be blemished (a pierced lobe is no blemish): F5 — the_ear (122:5-6's upper ear at its Kiddushin seat; Bekhorot 37b:12-14 its twin); the exam's row."),
 ('Kiddushin 21b:9', 'DERIVATION', "R. Yosei son of R. Yehuda by amplification, restriction, amplification — 'you shall take' amplifies, 'the awl' restricts, 'through his ear and into the door' amplifies: everything but one: F5 — the_awl_tool's first arm's method (the rival to I6, no code)."),
 ('Kiddushin 21b:10', 'DERIVATION', "what is excluded — a corrosive substance, the most unlike the awl: F5 — the_awl_tool's first arm's edge."),
 ('Kiddushin 21b:12', 'DERIVATION', "Rabba bar Rav Sheila: 'and he shall return to his own family' (Leviticus 25:41) — to his family's standing: a priest-slave not blemished by the piercing: F5 — the_ear's ground (the priest-slave; priesthood.blemish by CALL)."),
 ('Kiddushin 21b:13', 'DISPUTE', "the priest-slave given a Canaanite maidservant? — a novelty for all, or priests different (their added commands): Rav permits, Shmuel forbids: F5 — the night's service for a priest (a DATA row; 21b:16 Rav Nachman's proof)."),
 ('Kiddushin 21b:14', 'DISPUTE', "the dilemma's two horns and the two masters — Rav permits, Shmuel forbids."),
 ('Kiddushin 21b:15', 'DERIVATION', "Rav Nachman to Rav Anan: the proof from 'the Rabbis say a priest-slave is not pierced' (21b:16 explains)."),
 ('Kiddushin 21b:17', 'OUTSIDE', "the beautiful captive (Deuteronomy 21:11-12) for a priest — Rav permits, Shmuel forbids: chapter 21's law."),
 ('Kiddushin 21b:18', 'OUTSIDE', "the first act permitted to all — the evil inclination's concession."),
 ('Kiddushin 21b:19', 'OUTSIDE', "the second act — Rav: permitted; Shmuel: a convert is unfit for a priest."),
 ('Kiddushin 21b:20', 'OUTSIDE', "the other version — the first act in dispute; 'bring her home' and 'see among the captives' read together."),
 ('Kiddushin 21b:21', 'OUTSIDE', "the baraita on the captive — 'sees', 'a woman', 'beautiful': the concession."),
 ('Kiddushin 22a:1', 'OUTSIDE', "'dying animals slaughtered' — the concession's reason; 'for her' one, not two."),
 ('Kiddushin 22a:2', 'OUTSIDE', "'take her', 'to you as a wife', 'bring her home' — not during the war."),
 ('Kiddushin 22a:4', 'LAW', "said at the end and not at the beginning — not pierced: 'if the slave shall say' while a slave: F5 — the_awl_timing (121:1's two sayings, 121:2's two times); the exam's row."),
 ('Kiddushin 22a:6', 'LAW', "Rava: 'the beginning of six' is the last peruta's start, 'the end' its end — the window of the saying: F5 — the_awl_timing's window (a DATA row)."),
 ('Kiddushin 22a:9', 'CONTEXT', "Rav Beivai bar Abaye: both ill — 'with you' (alike) or 'fares well' (good for both)? the dilemma stands: F5 — 121:4's open edge."),
 ('Kiddushin 22a:10', 'LAW', "'because he fares well with you' — the baraita whole: with you in food and drink, not fine bread against coarse, aged wine against new, soft bedding against straw; 'acquires a master for himself': F5 — the board (20a:15); the exam's row."),
 ('Kiddushin 22a:12', 'LAW', "the children fed (they cannot work) and the wife fed (she will not beg) — each clause needed: F4 — the slave's family's board by CALL to mishpatim's F1 (22a:11's R. Shimon)."),
 ('Kiddushin 22a:13', 'LAW', "the converse — the wife too ashamed to beg, the children not: both rulings needed: F4 — the family's board."),
 ('Kiddushin 22a:14', 'CONTEXT', "'the Sages taught:' — the heading alone (the baraita of 22a:15 credited from the reading's own docket)."),
 ('Kiddushin 22b:4', 'CONTEXT', "R. Yochanan ben Zakkai's homily — the ear that heard 'to Me the children of Israel are slaves' (Leviticus 25:55) and took a master: pierced; the piercing's reason, no rule."),
 ('Kiddushin 22b:5', 'CONTEXT', "R. Shimon son of Rabbi's homily — the door and the doorpost, witnesses of the Passover in Egypt: pierced before them; the reason, no rule."),
 ('Kiddushin 22b:6', 'OUTSIDE', "MISHNAH KIDDUSHIN 1:3 — the Canaanite slave acquired by money, document, possession; freed by others' money or his own bill (R. Meir / the Rabbis): another law."),
 ('Kiddushin 22b:7', 'OUTSIDE', "the Canaanite's modes from 'you shall bequeath them … as an ancestral inheritance' (Leviticus 25:46) — as a field."),
 ('Kiddushin 22b:8', 'OUTSIDE', "not returned at the jubilee — 'your slaves forever' (Leviticus 25:46)."),
 ('Kiddushin 22b:9', 'OUTSIDE', "symbolic exchange — the Canaanite's acquisition."),
 ('Kiddushin 22b:10', 'OUTSIDE', "Shmuel: pulling — taken by force, not called."),
 ('Kiddushin 22b:11', 'OUTSIDE', "why the Mishnah and the baraita omit pulling."),
 ('Kiddushin 22b:12', 'OUTSIDE', "an animal by passing — the hoof, the hair, the saddle."),
 ('Kiddushin 22b:13', 'OUTSIDE', "an animal by pulling — called and it comes."),
 ('Kiddushin 22b:14', 'OUTSIDE', "a slave walks by his own will; Rav Ashi: a minor slave as an animal."),
 ('Kiddushin 22b:15', 'OUTSIDE', "Tosefta 1:5 — possession: the shoe removed, the garments carried, the bath, the anointing; R. Shimon's lifting."),
 ('Kiddushin 22b:16', 'OUTSIDE', "Rav Ashi: the slave lifting the master acquires; R. Shimon: lifting either way."),
 ('Kiddushin 22b:17', 'OUTSIDE', "the Canaanite maidservant by intercourse? — both benefit, no acquisition."),
 ('Kiddushin 22b:19', 'OUTSIDE', "R. Yehuda from India's slave and Mar Zutra's shoes — the dead convert's slave acquired."),
]
SPEC = CREDITED_SPEC + OWN_U + OWN
ROWS = build_set(SPEC, [a for a in D2_UNIQUE if _sel(a)])
WHOLE = {}
ROWS, WHOLE_STATS = apply_whole(ROWS, WHOLE)
