
# ---- THE CALLEES' FACTS (every edge live at the cells that consume them; the values asserted from the callees' own print — ch15_callees.out, read before any assert was typed; the older runners' cells take q (or a string case, or positional data) and return a dict, the Deuteronomy runners' take (case, data) and return a tuple; yovel's clock cells take the design's values; mishpatim's F1 is a TABLE (EFFECTS, PROBES) and its daemon — no cell; temurah's tithe a string case; the print settled each form) ----
def V(x):
    """a cell's verdict whatever its form — the dict's v (or verdict), the tuple's first member"""
    return x.get('v', x.get('verdict', x)) if isinstance(x, dict) else (x[0] if isinstance(x, tuple) else x)
def FOUND(r):
    """a kin cell CALLED and answering — a tuple (verdict, effects, trail) whose verdict is in span, or a dict with its value"""
    if isinstance(r, dict): return 'v' in r or 'verdict' in r
    return isinstance(r, tuple) and isinstance(r[0], str) and not r[0].startswith('no verdict') and r[0] != 'no_case'
YO_C1 = YO.cycle(1); YO_C6 = YO.cycle(6); YO_C7 = YO.cycle(7); YO_C14 = YO.cycle(14); YO_C49 = YO.cycle(49); YO_C50 = YO.cycle(50); YO_JUB = YO.jubilee(); YO_SAB = YO.sabbatical(); YO_INT = YO.interest()
YO_BROTHER = YO.interest_scope('brother'); YO_FOREIGNER = YO.interest_scope('foreigner'); YO_SLAVE = YO.hebrew_slave('israelite', 60, 20, 6); YO_SLAVE_G = YO.hebrew_slave('gentile', 60, 20, 6); YO_OUT = YO.going_out(); YO_VAL_M = YO.valuation('male', 30); YO_VAL_F = YO.valuation('female', 30)
YO_SUPPORT = YO.support_duty('faltering'); YO_SALE = YO.sale_manner('slave_sale'); YO_GENTILE = YO.gentile_slave()
CA_TIMER = CA.sabbatical({'ask': 'timer'}, CA.DATA); CA_HOME = CA.sabbatical({'ask': 'home_engine'}, CA.DATA); CA_SCOPE = CA.sabbatical({'ask': 'work_scope'}, CA.DATA)
MP_F1 = [r for r in MP.EFFECTS if r[0].startswith('slave-release')]; MP_PROBES = [p for p in MP.PROBES if p[2:5] in (('Exod', 21, 2), ('Exod', 21, 8), ('Lev', 25, 10))]; MP_WRAP = MP.wrap_cells[0][1]
M2_SRC = inspect.getsource(M2.law_mishpatim_2)
M3_EXITS = M3.maidservant('exits'); M3_TWO = M3.maidservant('the_two_exits'); M3_REDEEM = M3.maidservant('redemption'); M3_DESIG = M3.maidservant('designation'); M3_SELLS = M3.maidservant('who_sells'); M3_THREE = M3.maidservant('the_three'); M3_THESE = M3.maidservant('these_three'); M3_FOREIGN = M3.maidservant('foreign_sale')
OR_IM = OR.loan('im_obligation'); OR_LADDER = OR.loan('priority_ladder'); OR_SUNSET = OR.loan('pledge_sunset'); OR_FOREIGN = OR.loan('foreigner'); OR_MANNER = OR.loan('creditor_manner'); OR_FIVE = OR.loan('five_prohibitions'); OR_COURT = OR.loan('court_only'); OR_WIDOW = OR.loan('widow_not_pledged'); OR_INTEREST = OR.loan('interest_spec'); OR_BITE = OR.loan('bite_noun')
OR_EIGHTH = OR.firstling('eighth_and_onward'); OR_MOTHER = OR.firstling('with_its_mother'); OR_TIMER = OR.firstling('two_seats_one_timer'); OR_DONKEY = OR.firstling('donkey_by_call'); OR_SELA = OR.gifts('five_sela'); OR_SON = OR.gifts('firstborn_son'); OR_CAES = OR.gifts('caesarean'); OR_THIRTY = OR.gifts('thirty_days')
ER_EMPTY = ER.repeats('empty_exported'); ER_EMPTY2 = ER.repeats('empty_two_seats'); ER_SEH = ER.repeats('seh_class'); ER_STANDS = ER.repeats('empty_where_it_stands'); ER_ORDER = ER.repeats('order_of_clauses'); ER_TIPADEH = ER.repeats('tipadeh'); ER_KID = ER.repeats('kid_identical')
KO_WOMB = KO.the_gifts({'ask': 'opens_the_womb'}, KO.DATA); KO_CLEAN = KO.the_gifts({'ask': 'clean_firstborn'}, KO.DATA); KO_WINDOW = KO.the_gifts({'ask': 'firstborn_eating_window'}, KO.DATA); KO_EATERS = KO.the_gifts({'ask': 'firstborn_eaters'}, KO.DATA); KO_BLEM = KO.the_gifts({'ask': 'blemished_firstborn'}, KO.DATA); KO_KEEP = KO.the_gifts({'ask': 'blemished_keeping'}, KO.DATA)
KO_EXPERT = KO.the_gifts({'ask': 'blemish_expert'}, KO.DATA); KO_NOALTAR = KO.the_gifts({'ask': 'firstborn_without_altar'}, KO.DATA); KO_SALE = KO.the_gifts({'ask': 'firstborn_sale'}, KO.DATA); KO_SUSPECT = KO.the_gifts({'ask': 'suspect_firstborn'}, KO.DATA); KO_UNCLEAN = KO.the_gifts({'ask': 'unclean_firstborn_scope'}, KO.DATA); KO_TWINS = KO.the_gifts({'ask': 'twins'}, KO.DATA)
TM_FB = TM.consecrate('firstborn'); TM_FBV = TM.consecrate('firstborn_for_value'); TM_FIT = TM.consecrate('fit_animal'); TM_TEN = TM.tithe('took_ten_of_a_hundred'); TM_HERD = TM.tithe('herd_with_flock'); TM_TRICK = TM.firstborn_trick(); TM_ATITHE = TM.redeem('animal_tithe')
PR_TABLE = PR.acceptable('firstling_table'); PR_BLOOD = PR.acceptable('blemished_blood'); PR_LIMB = PR.acceptable('blemished_limb'); PR_PASSING = PR.acceptable('passing_blemish'); PR_WORKED = PR.acceptable('worked_with'); PR_HEADS = PR.acceptable('beast_heads'); PR_EIGHTH = PR.acceptable('eighth_day'); PR_BALD = PR.blemish('bald'); PR_UNFITS = PR.blemish('beast_unfits_in_man'); PR_TOKENS = PR.blemish('blemish_tokens'); PR_EATS = PR.blemish('eats')
PN_PLACE = PN.the_place_chosen({'ask': 'the_place_which_the_lord_will_choose'}, PN.DATA); PN_REJOICE = PN.the_place_chosen({'ask': 'eat_there_and_rejoice'}, PN.DATA); PN_WOMAN = PN.the_place_chosen({'ask': 'the_womans_rejoicing'}, PN.DATA)
PN_GATES = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'you_may_not_eat_within_your_gates'}, PN.DATA); PN_BLEMISHED = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_blemished_consecrated'}, PN.DATA); PN_WATER = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_blood_like_water'}, PN.DATA); PN_UNCLEAN = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_unclean_and_the_clean'}, PN.DATA); PN_EATERS = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_eaters'}, PN.DATA); PN_BEFORE = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'before_the_lord_you_shall_eat_it'}, PN.DATA); PN_TWO = PN.the_profane_slaughter_the_blood_and_the_gates({'ask': 'the_two_tithes'}, PN.DATA)
PN_GAZELLE = PN.the_border_enlarged_and_the_altar({'ask': 'as_the_gazelle_and_the_hart'}, PN.DATA); PN_LIFE = PN.the_border_enlarged_and_the_altar({'ask': 'the_blood_is_the_life'}, PN.DATA); PN_CLASSES = PN.the_border_enlarged_and_the_altar({'ask': 'the_bloods_classes'}, PN.DATA); PN_RITE = PN.the_border_enlarged_and_the_altar({'ask': 'the_rite_of_slaughter'}, PN.DATA)
SA_BAN = SA.blood('ban'); SA_LASH = SA.blood('lashes'); SA_WHICH = SA.blood('which_blood'); SA_OWN = SA.blood('karet_own_eating'); SA_CONVERT = SA.blood('convert'); SA_ATONES = SA.blood('atones'); SA_HUNTED = SA.covering('hunted_of_any_kind'); SA_CONSEC = SA.covering('consecrated'); SA_FOOT = SA.covering('not_with_the_foot'); SA_FAILED = SA.covering('failed_slaughter'); SA_WARNED = SA.frame('court_warned')
HO_POOR = HO.gifts('poor_defined'); HO_RECIP = HO.gifts('recipients'); HO_KINDS = HO.gifts('kinds'); HO_WINDOW = HO.gifts('window_end'); HO_NAMED = HO.gifts('for_named_poor'); HO_HIRE = HO.wage('hire_kinds'); HO_MORNING = HO.wage('first_morning'); HO_ALIEN = HO.wage('resident_alien'); HO_OPPRESS = HO.wage('oppression_class'); HO_INKIND = HO.wage('in_kind')
FT_FOUR = FT.the_third_year({'ask': 'the_four_in_want'}, FT.DATA); FT_CYCLE = FT.the_third_year({'ask': 'the_seventh_year_by_the_cycle'}, FT.DATA); FT_MEAS = FT.the_third_year({'ask': 'the_measures'}, FT.DATA); FT_REMOVAL = FT.the_third_year({'ask': 'the_removal_date'}, FT.DATA); FT_YEAR = FT.the_second_tithe({'ask': 'the_year_passed'}, FT.DATA); FT_FIRSTLING = FT.the_second_tithe({'ask': 'the_firstling'}, FT.DATA); FT_OUTSIDE = FT.the_second_tithe({'ask': 'the_firstling_from_outside'}, FT.DATA)
CH_FOURTH = CH.the_first_tablet({'ask': 'the_fourth_word'}, CH.DATA); CH_GROUNDS = CH.the_first_tablet({'ask': 'the_two_grounds'}, CH.DATA); CH_KEEP = CH.the_first_tablet({'ask': 'keep_and_remember'}, CH.DATA)
BC_HEARKEN = BC.the_second_paragraph({'ask': 'if_you_hearken'}, BC.DATA); BC_HEED = BC.the_second_paragraph({'ask': 'take_heed_lest'}, BC.DATA); BC_KEEP = BC.the_blessing_and_the_curse({'ask': 'keep_to_do'}, BC.DATA)
ES_SENT = ES.night('sent_formula'); ES_WAGE = ES.night('wage'); ES_GARMENTS = ES.night('garments'); ES_REFUSAL = ES.bricks('refusal'); ES_DECREES = ES.oppression('three_decrees'); ES_RIGOR = ES.oppression('rigor_seats')
PV_FIRSTLING = PV.cain('firstling_by_call'); PV_FAT = PV.cain('fat_by_call'); PV_DAYS = PV.cain('abel_days'); PV_REFUSE = PV.cain('refuse')
GL_SEATS = GL.receipt_seats(15); GL_NORECEIPT = GL.the_frame({'ask': 'no_receipt'}, GL.DATA); GL_HEEL = GL.the_testimony({'ask': 'the_heel'}, GL.DATA)
SE_ENTICE = SE.the_inciter({'ask': 'entice_two_senses'}, SE.DATA); SE_SEAL = SE.the_header({'ask': 'the_headers_seal'}, SE.DATA); SE_BELIAL_PARAM = SE.DATA['the_seducers_parameters']['value']['belial']
_se_src = inspect.getsource(SE.the_city_heard_of_the_inquiry_and_the_sword); _se_asks = sorted(set(re.findall(r"if ask == '([a-z_0-9]+)'", _se_src))); _se_belial = [a for a in _se_asks if 'belial' in a or 'base' in a]
SE_BELIAL = SE.the_city_heard_of_the_inquiry_and_the_sword({'ask': _se_belial[0]}, SE.DATA) if _se_belial else ('no belial ask in the city cell: %s' % _se_asks, [], [])
MZ_MEMBERS = MZ.eighth('members'); MZ_OIL = MZ.eighth('oil_on_blood'); MZ_PREC = MZ.eighth('precedence'); MZ_ALTAR = MZ.eighth('altar_before_members')
print('THE CALLEES (printed before they are asserted): the Belial ask in the city cell %s -> %s; the release on the bare world %s; the firstling\'s year %s days; MP F1 %s; M2 slave_maimed %s' % (_se_belial, str(V(SE_BELIAL))[:90], CLOCK['the_release_on_the_bare_world'], CLOCK['the_firstlings_year_days'], [r[0] for r in MP_F1], ('released' in M2_SRC and 'goes_free' in M2_SRC)))
# the values asserted from the callees' print (ch15_callees.out — read before any assert was typed)
assert YO_C1['v'] == 'work_year' and YO_C6['v'] == 'work_year' and YO_C7['v'] == 'sabbath_of_the_land' and YO_C14['v'] == 'sabbath_of_the_land' and YO_C49['v'] == 'sabbath_of_the_land' and YO_C50['v'] == 'jubilee' and YO_JUB['cycle_length']['v'] == 49 and YO_JUB['jubilee_year']['v'] == 50 and YO_JUB['release_day']['v'] == 'tenth_of_seventh_month_yom_kippur' and YO_SAB['torah_labors']['v'] == 4 and YO_INT['both_nouns']['v'] == 'barred', (YO_C7['v'], YO_C50['v'], YO_JUB['cycle_length']['v'], YO_JUB['release_day']['v'])   # THE CYCLE — the seventh year's class sabbath_of_the_land (7, 14, 49), the fiftieth the jubilee; the jubilee's release day Yom Kippur
assert YO_BROTHER['v'] == 'barred' and YO_FOREIGNER['v'] == 'permitted' and YO_SLAVE['status']['v'] == 'hireling_resident' and YO_SLAVE['slave_work']['v'] == 'barred' and YO_SLAVE['rigor']['v'] == 'barred' and str(YO_SLAVE['exit']['v']).startswith('at_jubilee') and YO_OUT['v'] == 'to_the_priests' and YO_VAL_M['v'] == 50 and YO_VAL_F['v'] == 30 and YO_SUPPORT['v'] == 'uphold_before_he_falls' and YO_SALE['v'] == 'permitted' and YO_GENTILE['term']['v'] == 'forever', (YO_BROTHER['v'], YO_FOREIGNER['v'], YO_SLAVE['status']['v'], YO_SLAVE['exit']['v'], YO_VAL_M['v'], YO_SUPPORT['v'])   # the brother barred, the foreigner permitted (23:21 by import); the sold brother a hireling-resident, out at the jubilee; the valuation's fifty (the severance gift's third arm)
assert CA_TIMER[:2] == ('land released in year 7', ['land_release']) and CA_HOME[0].startswith('the same release') and CA_SCOPE[0] == 'hoeing barred in the seventh', (CA_TIMER[:2], CA_HOME[0][:30], CA_SCOPE[0])
assert [r[0] for r in MP_F1] == ['slave-release: FREE-YEAR-7', 'slave-release: DEDUCT', 'slave-release: FREE-AT-JUBILEE'] and [r[1] for r in MP_F1] == [['term_clock', 'goes_free'], ['pays', 'goes_free'], ['jubilee_release', 'goes_free']] and ('six', 8337, 'Exod', 21, 2) in MP_PROBES and ('jubilee', 3104, 'Lev', 25, 10) in MP_PROBES and MP_WRAP[:4] == (1, 1, 1, 1) and 'released' in M2_SRC and 'goes_free' in M2_SRC, (MP_F1, MP_PROBES, MP_WRAP[:6])   # THE SLAVE'S TERM CLOCK IS EXODUS 21'S — the F1 table's three rows (the year-7 timer, the deduction, the jubilee's override), the wrap's scene the answer sheet's; mishpatim_2's slave_maimed branch writes released and goes_free
assert M3_EXITS['v'] == ['years', 'jubilee', 'deduction', 'signs'] and M3_TWO['v'] == {'free': 'maturity', 'without_money': 'youth'} and M3_REDEEM['v'] == 'against_his_will' and M3_DESIG['v'] == 'betrothal_with_her_consent' and M3_SELLS['v'] == 'the_father_alone' and M3_THREE['v'] == ['food', 'clothing', 'conjugal_right'] and M3_THESE['v'] == ['designate_for_himself', 'designate_for_his_son', 'redeem'] and M3_FOREIGN['v'] == 'barred_a_warning_to_the_court', (M3_EXITS['v'], M3_TWO['v'], M3_REDEEM['v'])   # THE MAIDSERVANT'S EXITS — years, the jubilee, the deduction, the signs (Mishnah Kiddushin 1:2); redeemed against his will (Kiddushin 18a:5 — the cell citing Deut 15:12 already)
assert OR_IM['v'] == 'lending_is_obligation' and OR_LADDER['v'] == ['my_people_before_gentile', 'poor_before_rich', 'your_poor_before_your_city', 'your_city_before_another'] and OR_SUNSET['v'] == 'until_the_sun_sets' and OR_FOREIGN['v'] == 'permitted' and OR_MANNER['v'] == 'not_seen_at_all_times' and len(OR_FIVE['v']) == 5 and OR_COURT['v'] == 'only_through_the_court_outside_you_stand' and OR_WIDOW['v'] == 'never_pledged_rich_or_poor' and OR_INTEREST['v'] == 'barred' and OR_BITE['v'] == 4, (OR_IM['v'], OR_LADDER['v'], OR_SUNSET['v'])   # THE ORDINANCES' LOAN CELL NAMES 15:8 — lending_is_obligation; the priority ladder the ranks' first form; the pledge's sunset
assert OR_EIGHTH['v'] == 'on_the_eighth_day_and_onward' and OR_MOTHER['v'] == 'with_not_under' and OR_TIMER['v'] == {'exod_22_29': 'on_the_eighth_day', 'lev_22_27': 'from_the_eighth_day_onward'} and OR_DONKEY['v'] == 'redeem with a lamb, else break the neck' and OR_SELA['v'] == 'five_sela_tyrian_maneh' and OR_SON['v'] == 'redeem (five sela — fetched constant)' and OR_CAES['v'] == 'not consecrated' and OR_THIRTY['v'] == 'day_thirty_is_the_edge', (OR_EIGHTH['v'], OR_SELA['v'], OR_CAES['v'])
assert ER_EMPTY['v'] == 'five_selas_to_the_severance_gift' and ER_EMPTY2['v'] == [('Exod', 23, 15), ('Exod', 34, 20)] and ER_SEH['v'] == 'sheep_or_goat_any_sex_age_blemish' and ER_STANDS['v'] == 'standing_liability_like_the_appearance_offering' and ER_ORDER['v'] == 'redeem_then_appear' and ER_TIPADEH['v'] == 'he_redeems_himself_sons_not_daughters' and ER_KID['v'] is True, (ER_EMPTY['v'], ER_EMPTY2['v'], ER_SEH['v'])   # THE SEVERANCE GIFT ALREADY PRICED — the erection's cell 'empty_exported' (its ASK, not 'five_selas_to_the_severance_gift' — that is its VALUE: the print settled the name)
assert KO_WOMB[0].startswith('all that opens the womb') and KO_WOMB[1] == ['consecrated_firstborn'] and KO_CLEAN[0].startswith('the firstborn of an ox, a sheep, a goat you shall not redeem') and KO_WINDOW[0].startswith('two days and a night') and KO_WINDOW[1] == ['due_to_priest'] and KO_EATERS[0].startswith('Beit Shammai: priests only') and KO_BLEM[0].startswith('to the priest — it shall be yours repeated') and KO_KEEP[0].startswith('a blemish within the year — kept the twelve months; after the year — thirty days') and KO_EXPERT[0].startswith("the court's expert exempt, a non-expert pays") and KO_NOALTAR[0].startswith('the flesh as the blood') and KO_SALE[0].startswith('not redeemed, but sold') and KO_SUSPECT[0].startswith('no meat nor untanned hides') and KO_UNCLEAN[0].startswith('the ass alone') and KO_UNCLEAN[1] == ['redeem_or_break'] and KO_TWINS[1] == ['pays'], (KO_WOMB[:2], KO_WINDOW[:2], KO_KEEP[0][:60])   # consecrated_firstborn the korach cell's own effect at opens_the_womb; the window two days and a night; the blemished kept the twelve months, thirty days after the year (Mishnah Bekhorot 4:1-2); the expert (4:4-5)
assert TM_FB['v'] == 'cannot_be_sanctified_to_the_altar' and TM_FBV['v'] == 'value_consecration_yes' and TM_FBV['fx'] == ['consecrated'] and TM_FIT['v'] == 'holy_altar' and TM_TEN['v'] == 'not_a_tithe' and TM_HERD['v'] == 'not_tithed_together' and TM_TRICK['v'] == 'what_is_in_her_womb_if_male_an_olah' and TM_ATITHE['v'] == 'not_redeemed', (TM_FB['v'], TM_FBV['v'], TM_TEN['v'], TM_HERD['v'])   # 27:26's bar and its resolution — for VALUE yes (R. Yishmael, Arakhin 8:7): the cell whose probe list carries 15:19 as its IMPORT; the tithe cells take a STRING case (the dict form returned no_case — the print)
assert PR_TABLE['v'] == {'slaughter_on': 'the_permanent_blemishes', 'not_on': 'the_passing_the_old_the_sick_the_foul_the_sinned_with_the_killer_the_doubtful_sex', 'disqualified_consecrated': 'redeemed_on_the_same'} and PR_BLOOD['v'] == 'poured_to_the_channel' and PR_LIMB['v']['sages'] == 'to_the_burning_place' and PR_PASSING['v'] == 'included' and PR_WORKED['v'] == 'permitted' and PR_HEADS['v'] == ['blind', 'broken', 'charutz', 'wart', 'garav', 'yalefet'] and PR_EIGHTH['v']['here'] == 'from_the_eighth_day_onward' and PR_BALD['v'] == 'no_hair_line_ear_to_ear' and PR_UNFITS['v'] == {'it_and_its_young': 'fit', 'terefah': 'fit', 'caesarean': 'fit'} and PR_TOKENS['v'] == {'lev_21': 5, 'lev_22': 3} and PR_EATS['v']['most_holy'] == 'eats', (PR_TABLE['v'], PR_HEADS['v'], PR_BALD['v'])   # ONE LIST SERVES THE FIRSTLING — Mishnah Bekhorot 6:11-12's closing rule: slaughtered on the permanent blemishes, not on the passing; the six class heads of 22:22
assert PN_PLACE[0].startswith('the place which the LORD will choose (12:5)') and PN_REJOICE[0].startswith('eat there and rejoice (12:7)') and PN_WOMAN[0].startswith("the woman's rejoicing (12:7, 12:12, 12:18)") and PN_GATES[0].startswith('you may not eat within your gates (12:17)') and PN_BLEMISHED[0].startswith('the blemished consecrated (12:15)') and PN_WATER[0].startswith('the blood like water (12:16, 12:24)') and PN_UNCLEAN[0].startswith('the unclean and the clean (12:15)') and PN_EATERS[0].startswith('the eaters (12:15)') and PN_BEFORE[0].startswith('before the LORD you shall eat it (12:18)') and PN_TWO[0].startswith('the two tithes (12:17)') and PN_GAZELLE[0].startswith('as the gazelle and the hart (12:22)') and PN_LIFE[0].startswith('the blood is the life (12:23)') and PN_CLASSES[0].startswith("the blood's classes (12:16, 12:23)") and PN_RITE[0].startswith('the rite of slaughter (12:21)'), (PN_PLACE[0][:40], PN_GATES[0][:40], PN_BLEMISHED[0][:40], PN_WATER[0][:40])   # chapter 12's cells by CALL — the place formula, the gates' bar (holy_things_in_the_gates_barred REUSED here), the blemished consecrated's release, the blood like water, the unclean and the clean, as the gazelle and the hart
assert SA_BAN['v'] == 'karet' and SA_BAN['fx'] == ['face_set_against', 'karet_cut_off'] and SA_LASH['v'] == 'lashed_when_warned' and SA_WHICH['v'] == ['sages_lifeblood_only', 'R._Yehuda_any_blood'] and SA_OWN['v'] == 'karet_rides_only_ones_own_eating' and SA_CONVERT['v'] == 'convert_bound_as_the_citizen' and SA_ATONES['v'].startswith('one_gift_atones') and SA_HUNTED['v'] == 'bought_inherited_gifted_self_trapped_all_covered' and SA_CONSEC['v'] == 'no_covering' and SA_FOOT['v'] == 'not_with_the_foot_the_pourer_covers' and SA_FAILED['v'] == 'exempt' and SA_WARNED['v'] == 'the_court_warned_over_the_charge', (SA_BAN['v'], SA_LASH['v'], SA_WHICH['v'], SA_HUNTED['v'])   # THE BLOOD'S BAN Leviticus 17's — karet, lashed when warned (the witnesses' warning gating the penalty, 126:3); the hunted covered, the consecrated not (the contrast at 15:23)
assert HO_POOR['v'] == 'takes' and HO_RECIP['v'] == 'the_poor_and_the_convert_not_the_resident_alien' and HO_KINDS['v'] == ['corner', 'fallen_grapes', 'gleanings', 'small_clusters'] and HO_WINDOW['v'] == 'until_the_smoothing' and HO_NAMED['v'] == ['R._Eliezer_acquired', 'sages_to_the_first_poor_found'] and HO_HIRE['v'] == ['man', 'beast', 'tools', 'land'] and HO_MORNING['v'] == 'the_first_morning_only' and HO_ALIEN['v'] == 'under_on_his_day_not_under_until_morning' and HO_OPPRESS['v'] == 'the_money_class_the_wage_withholder' and HO_INKIND['v'] == 'not_heeded', (HO_POOR['v'], HO_RECIP['v'], HO_HIRE['v'])   # the poor defined (Peah 8:8 — two hundred less a dinar takes), the hireling's wage (the hire's kinds; 24:14's resident alien by import)
assert FT_FOUR[0].startswith('the four in want (14:29)') and FT_CYCLE[0].startswith('the seventh year by the cycle (14:28)') and FT_CYCLE[1] == ['exempt'] and FT_MEAS[0].startswith('the measures (14:29)') and FT_REMOVAL[0].startswith("the removal's date (14:28)") and FT_YEAR[0].startswith('the year passed (14:23)') and FT_FIRSTLING[0].startswith('the firstling (14:23)') and FT_OUTSIDE[0].startswith('the firstling from outside (14:23)') and FT_OUTSIDE[1] == ['exempt'], (FT_FOUR[0][:30], FT_CYCLE[:2], FT_YEAR[0][:30], FT_OUTSIDE[:2])   # chapter 14's cells by CALL — the four at the gate, the count's year by the cycle, the year passed no bar (106:5's cell on file), the firstling from outside not brought
assert CH_FOURTH[0].startswith('the fourth word (5:12-15)') and CH_GROUNDS[0].startswith('the two grounds (5:15)') and CH_KEEP[0].startswith('keep and remember (5:12)') and BC_HEARKEN[0].startswith('if you hearken (11:13)') and BC_HEED[0].startswith('take heed lest (11:16)') and BC_KEEP[0].startswith('keep to do (11:32)'), (CH_FOURTH[0][:30], CH_GROUNDS[0][:30], BC_HEARKEN[0][:30])   # 5:15's memory clause (the fourth word's two grounds — the exodus); 11:13's conditional in the same form
assert ES_SENT['v'] == 'the_mouth_that_said_i_will_not_send' and ES_SENT['fx'] == ['sent_out'] and ES_WAGE['v'] == (600000, 430) and ES_GARMENTS['v'] == 'dearer_than_silver_and_gold' and ES_REFUSAL['v'] == 'i_do_not_know_the_lord' and ES_REFUSAL['fx'] == ['release_demanded'] and ES_DECREES['v'] == 3 and ES_RIGOR['v'] == [(1, 13), (1, 14)], (ES_SENT['v'], ES_WAGE['v'], ES_REFUSAL['v'])   # THE RELEASE DEMANDED AND CLOSED — the debit open on Pharaoh until 12:31 (sent_out the close on the tape); the spoil the slaves' wage (Sanhedrin 91a) — Egypt the model of the gift (120:1)
assert PV_FIRSTLING['v'] == 'cannot_be_sanctified_to_the_altar' and PV_FAT['v'] == ['parts', 'pointer_4_10'] and PV_DAYS['v'] == 50 and PV_REFUSE['v'] == ('from_the_refuse', 'the_firstlings'), (PV_FIRSTLING['v'], PV_FAT['v'], PV_DAYS['v'])   # Abel's firstlings by CALL — the institution by name at Genesis 4:4 (first_offerings_brought on the tape); the primeval cell already calling temurah's firstborn
assert GL_SEATS == [] and GL_NORECEIPT[0].startswith('no receipt (8:1-20)') and GL_HEEL[0].startswith('because (8:20)'), (GL_SEATS, GL_NORECEIPT[0][:30])   # NO RECEIPT SEAT AT CHAPTER 15 by the good-land runner's finder — 15:6's 'as He spoke to you' outside the forms by one token (the reading's measurement repeated)
assert SE_ENTICE[0].startswith('entice, two senses (13:7)') and SE_SEAL[0].startswith("the header's seal (13:1)") and SE_BELIAL_PARAM == 'without a yoke' and FOUND(SE_BELIAL), (SE_ENTICE[0][:30], SE_BELIAL_PARAM, str(V(SE_BELIAL))[:80])   # 'base' without a yoke the seducers' own parameter (13:14 — E30); the city cell's Belial ask found by its source (the transfer's exemplar), its verdict read at the runner
assert MZ_MEMBERS['v'] == 'right_ear_ridge_right_thumb_right_toe' and MZ_OIL['v'] == 'on_the_place_of_the_blood' and MZ_PREC['v'] == "chatat first, except the leper's asham" and MZ_ALTAR['v'] == 'altar_first', (MZ_MEMBERS['v'], MZ_OIL['v'])   # THE LEPER'S RIGHT EAR by CALL — the ridge of the right ear (14:14): the awl's ear by the labeled transfer (the Sifrei 122:5-6; Kiddushin 15a:1)
assert all(FOUND(r) for r in (YO_C7, YO_BROTHER, YO_SLAVE['status'], YO_OUT, CA_TIMER, M3_EXITS, OR_IM, OR_LADDER, OR_EIGHTH, ER_EMPTY, KO_WOMB, KO_WINDOW, TM_FBV, PR_TABLE, PN_PLACE, PN_GATES, PN_WATER, PN_GAZELLE, SA_BAN, SA_HUNTED, HO_POOR, HO_HIRE, FT_FOUR, FT_YEAR, CH_FOURTH, BC_HEARKEN, ES_SENT, PV_FIRSTLING, GL_NORECEIPT, SE_ENTICE, MZ_MEMBERS)), 'every kin cell CALLED and answering'
