def the_hand_opened(case, data):
    """F3 — Deut 15:7-11 — THE LINE hand_opening_commanded writing hand_opening_commanded (a STATUS — 'open, you shall open' repeat without limit; lending_is_obligation by CALL), hand_shutting_barred and base_thought_barred (BLOCKS), work_of_the_hand_blessed (a HEAVEN entry — 14:29's twin); cry_heard and bears_sin REUSED at 15:9; the ranks a PRECEDENCE PARAMETER (the ordinances' ladder by CALL), the measure of need, the pledge dispute; Belial's word the labeled TRANSFER from 13:14"""
    del P_[:]
    ask = case['ask']
    if ask == 'the_needy_ranks':
        ink('15:7', '"if there be a needy man among you, ONE OF YOUR BROTHERS, within ONE OF YOUR GATES, in your land" — "one of your brothers" %s (one seat), "within one of your gates" %s (the formula\'s first seat of four), "in your land which the LORD your God gives you" %s; the parser\'s [1] at 15:7 %s' % (P('מאחד', 'אחיך'), P('באחד', 'שעריך', books=DT), P('בארצך', 'אשר', 'יהוה', 'אלהיך', 'נתן', 'לך'), PARSED[(15, 7)]))
        move('the Sifrei 116:4-8 (read whole at the reading); Bava Metzia 71a:3-4 (read whole at the docket); cold_run_ordinances (CALL) — OR.loan(priority_ladder) = %s' % (V(OR_LADDER),), "THE RANKS OF THE POOR A PRECEDENCE PARAMETER — 'among you' not others (116:4); 'one of your brothers' the hungrier, the father's brother before the mother's (116:5-6); 'within one of your gates' the city before another city (116:7); 'in your land' the Land before outside it, the door-to-door beggar owed nothing from the fund (116:8); Bava Metzia 71a:3-4 'the poor of your city first' and the Jew before the gentile even at a loss — THE LADDER ordinances.loan(priority_ladder) ALREADY HOLDS by CALL (my people before a gentile, the poor before the rich, your poor before your city's, your city's before another's)")
        dat('THE PRECEDENCE PARAMETER the_needy_ranks (the ladder by CALL; the Sifrei\'s five rungs; the door-to-door beggar); the exam\'s person the one who lends first to the poor of his own city — accepted')
        return out("the needy's ranks (15:7) — 'among you', 'one of your brothers', 'one of your gates', 'in your land': not others, the hungrier, the father's brother, the city, the Land (the Sifrei 116:4-8; Bava Metzia 71a:3-4 the poor of your city first): THE PRECEDENCE PARAMETER the_needy_ranks — ordinances.loan(priority_ladder) by CALL; the one who lends first to the poor of his own city accepted", ['accepted'])
    if ask == 'the_heart_before_the_hand':
        ink('15:7', '"you shall not HARDEN your heart nor SHUT your hand from your needy brother" — "harden your heart" %s (Sihon\'s 2:30 the book\'s other seat, %d tokens shared); "shut" the verb\'s ONE seat in the Torah of %d in the Bible %s; the negations at 15:7 %s' % (P('לא', 'תאמץ', 'את', 'לבבך'), SH(D15(7), ('Deut', 2, 30)), len(LEMT('7092')), [s for s, _, _ in LEMT('7092')], [x for x in W15(7) if x in NEG]))
        move('the Sifrei 116:10-11, 117:2 (read whole at the reading); Bava Metzia 31b:7-12, Ketubot 67b:11 (read whole at the docket)', "THE HEART'S STATE BEFORE THE HAND'S — 'harden your heart': there are those who grieve whether to give or not; 'shut your hand': those who stretch out the hand and close it (116:10-11): TWO VERBS ONE BLOCK hand_shutting_barred; 'beware' and 'lest' two prohibitions beside it (117:2); the verb 'shut' the Torah's one seat (Isaiah 52:15, Job, the Psalms the others); 'harden your heart' Sihon's hardening the book's other seat, Zedekiah's the run's (2 Chronicles 36:13)")
        dat('THE WRITE hand_shutting_barred — a BLOCK on israel_people at the counter\'s day (DG2): the two verbs one block; the exam\'s person the one who shuts his hand from his needy brother — barred from it')
        return out("the heart before the hand (15:7) — 'you shall not harden your heart nor shut your hand': the grieving heart and the closing hand two verbs (the Sifrei 116:10-11): THE WRITE hand_shutting_barred, a BLOCK on Israel at the chapter's own day; the one who shuts his hand from his needy brother barred from it", ['hand_shutting_barred'])
    if ask == 'the_doubled_verbs':
        ink('15:8, 15:11', '"OPEN, YOU SHALL OPEN your hand to him, and LEND, YOU SHALL LEND him" — "open, you shall open" %s (twice in the chapter; the Psalm\'s "You open Your hand" %s the form\'s other seat), "lend, you shall lend" %s (one seat); the eight infinitive absolutes %s' % (P('פתח', 'תפתח'), P('פותח', 'את', 'ידך'), P('והעבט', 'תעביטנו'), [(v, x) for v, x in INF_ABS]))
        move('the Sifrei 116:12, 117:6 (read whole at the reading); Bava Metzia 31b:7-12, Ketubot 67b:11 (read whole at the docket)', "OPEN AND GIVE A HUNDRED TIMES — the doublings read REPEAT WITHOUT LIMIT: 'open, you shall open' even a hundred times (116:12), 'give, you shall give' even a hundred times (117:6); THE DOUBLED VERBS UNCONDITIONAL (Bava Metzia 31b:7-12 — 'open, you shall open' to another city's poor, 'give, you shall give' a small gift, 'furnish, you shall furnish' though the house was not blessed, 'lend, you shall lend' the one with means who will not use them; R. Elazar ben Azarya and R. Shimon: 'the Torah speaks in the language of men' — the dissenting arms; Ketubot 67b:11 the same)")
        dat('THE WRITE hand_opening_commanded — a STATUS on israel_people at the counter\'s day (DG2): "open, you shall open" repeat without limit; the doubled verbs\' two arms a DATA row (the_doubled_verbs); the exam\'s person the one who opens his hand a hundred times — accepted')
        return out("the doubled verbs (15:8, 15:11) — 'open, you shall open', 'lend, you shall lend', 'give, you shall give' read REPEAT WITHOUT LIMIT, even a hundred times (the Sifrei 116:12, 117:6; Bava Metzia 31b:7-12 the doubled verbs unconditional against 'the Torah speaks in the language of men'): THE WRITE hand_opening_commanded, a STATUS on Israel at the chapter's own day; the one who opens his hand a hundred times accepted", ['hand_opening_commanded'])
    if ask == 'the_lending_obligation':
        ink('15:8', '"lend, you shall lend him SUFFICIENT FOR HIS NEED which he lacks" — the pledge-verb\'s four tokens in the chapter %s (15:6 twice, 15:8 twice); 22:24\'s "if money you lend" the ordinances\' seat' % ([(s, x) for s, x in PLEDGE_VERB if s.startswith('Deut 15')],))
        move('the Sifrei 116:12 (read whole at the reading); Ketubot 67b:11, Bava Metzia 31b:12 (read whole at the docket); cold_run_ordinances (CALL) — OR.loan(im_obligation) = %s; OR.loan(interest_spec) = %s' % (V(OR_IM), V(OR_INTEREST)), "THE OBLIGATION TO LEND — THE ORDINANCES' CELL NAMES THIS VERSE: 'if money you lend My people' (Exodus 22:24) — 'if' here is OBLIGATION, PROVEN FROM 15:8's 'you shall surely lend' (the Mekhilta; lending_is_obligation the cell's verdict by CALL — one of three obligatory if-clauses); Ketubot 67b:11 the one with means who will not use them lent to as a loan; the interest barred by the same cell (Leviticus 25:36-37 by import)")
        dat('the lending obligation a DATA row (the_lending_obligation — the ordinances\' cell lending_is_obligation by CALL, the edge live; the reverse edge on file); the exam\'s person the rich man who will not use his own money, lent to — accepted')
        return out("the lending obligation (15:8) — 'lend, you shall lend him': 22:24's 'if money you lend' read as OBLIGATION from this verse (the Mekhilta — ordinances.loan(im_obligation) by CALL: lending_is_obligation, the cell that names 15:8; Ketubot 67b:11): the rich man who will not use his own money lent to accepted", ['accepted'])
    if ask == 'the_measure_of_need':
        ink('15:8', '"SUFFICIENT FOR HIS NEED which he lacks" — "sufficient" the Torah\'s eight seats %s; "need" the Torah\'s ONE seat of %d in the Bible %s (the Levite\'s host at Gibeah the run\'s, Judges 19:20)' % ([(s, x) for s, x, _ in LEMT('1767', books=T)], len(LEMT('4270')), [s for s, _, _ in LEMT('4270')][:4]))
        move('the Sifrei 116:15-18 (read whole at the reading); Mishnah Peah 8:7-9, Ketubot 67b:2-12 (read whole at the docket); cold_run_holiness (CALL) — HO.gifts(poor_defined) = %s' % (V(HO_POOR),), "THE MEASURE OF NEED — 'sufficient for his need': you are not commanded to enrich him (116:15); 'which he lacks': even a horse and a slave (116:16 — Hillel's horse and the servant who ran before him, Ketubot 67b:2-3); the litra of meat (67b:4); 'for him' — the wife (116:18); Mishnah Peah 8:7-9 the poor man's ration and the fund's rule (the wanderer's loaf, the lodging, the three meals; two hundred zuz the line — holiness.gifts(poor_defined) by CALL: takes); THE TWO WHO REFUSE — the loan turned gift and the gift collected from the estate (67b:8-12); the secret givers (67b:12-18)")
        dat('THE PARAMETER the_measure_of_need (116:15-18; Peah 8:7-9; Ketubot 67b — the house, the bed and the table, the wife by "for him", Hillel\'s horse); the exam\'s person the fallen rich man given a horse to ride — accepted')
        return out("the measure of need (15:8) — 'sufficient for his need which he lacks': not to enrich him, even a horse and a slave, Hillel's horse, the litra of meat, the wife by 'for him' (the Sifrei 116:15-18; Mishnah Peah 8:7-9; Ketubot 67b:2-12; holiness.gifts by CALL): THE PARAMETER the_measure_of_need; the fallen rich man given a horse to ride accepted", ['accepted'])
    if ask == 'the_pledge_dispute':
        ink('15:8', '"lend, you shall lend him" — the loan\'s verb "pledge" (עבט) the chapter\'s own word %s against 28:12\'s "lend" (לוה) %s' % ([x for x in W15(8) if 'עבט' in x], words('Deut', 28, 12)[-6:]))
        move('the Sifrei 116:14 (read whole at the reading); Bava Metzia 31b:7-12 (read whole at the docket); cold_run_ordinances (CALL) — OR.loan(court_only) = %s; OR.loan(widow_not_pledged) = %s' % (V(OR_COURT), V(OR_WIDOW)), "THE PLEDGE A DISPUTE — 'lend, you shall lend him': if he has no means, give him as a gift; if he has means and will not use them, lend him ON A PLEDGE — R. Judah's arm; the Sages: give him as a gift without a pledge? (116:14 — the two arms read; Bava Metzia 31b the doubled verb 'lend' the one with means); the pledge's own law by CALL (the court's entry, the widow never pledged)")
        dat('THE PARAMETER the_pledge_dispute (116:14 — R. Judah and the Sages, two arms; the pledge\'s law by CALL); the exam\'s person the one who lends on a pledge to the needy who has means — accepted on R. Judah\'s arm, the Sages\' recorded')
        return out("the pledge dispute (15:8) — the one with means who will not use them lent to on a pledge (R. Judah) or given without one (the Sages) — the Sifrei 116:14; Bava Metzia 31b:12: THE PARAMETER the_pledge_dispute, two arms; the one who lends on a pledge to the needy who has means accepted on R. Judah's arm", ['accepted'])
    if ask == 'the_gift_as_a_loan':
        ink('15:8', '"lend, you shall lend him" — the same doubled verb; "give, you shall give him" at 15:10 %s (Jephthah\'s vow the form\'s other seat)' % (P('נתון', 'תתן'),))
        move('the Sifrei 116:13 (read whole at the reading); Ketubot 67b:8-9 (read whole at the docket)', "THE GIFT DRESSED AS A LOAN — one who will not take a gift is given it in the form of a loan (116:13; Ketubot 67b:8-9 — the one who refuses a gift: given as a loan and it turns a gift; the one who refuses a loan: given as a gift and collected from his estate)")
        dat('the gift as a loan a DATA row (the_gift_as_a_loan — 116:13; Ketubot 67b:8-9); the exam\'s person the one who gives the proud needy a gift in the form of a loan — accepted')
        return out("the gift as a loan (15:8) — the one who will not take a gift is given it as a loan (the Sifrei 116:13; Ketubot 67b:8-9 the two who refuse): the one who gives the proud needy a gift dressed as a loan accepted", ['accepted'])
    if ask == 'the_base_thought':
        ink('15:9', '"BEWARE lest there be a BASE thought in your heart, saying: the seventh year, the year of release, draws near" — "beware lest" at its sixth seat in the book of nine %s; "base" (בליעל) the Torah\'s TWO %s; "the seventh year, the year of release" %s (one seat); the imperative "beware" the chapter\'s one %s; the ordinal [7] at 15:9 %s' % (P('השמר', 'לך', 'פן', books=DT), BASE, P('שנת', 'השבע', 'שנת', 'השמטה'), [(x, m) for v in (9,) for x, m in by[('Deut', 15, v)] if m and re.match(r'^HV.?.?v', m)], ORDS[9]))
        move('the Sifrei 117:1-3 (read whole at the reading); Gittin 36a:11 (read whole at the docket); cold_run_seducers (CALL — THE TRANSFER taught by the Sifrei 117:3, labeled) — SE.DATA the_seducers_parameters[belial] = %r; SE.the_city_heard_of_the_inquiry_and_the_sword(%s) = %s' % (SE_BELIAL_PARAM, _se_belial, str(V(SE_BELIAL))[:70]), "'BASE' WITHOUT A YOKE (117:1 — E30, checked in MIDDOT.md: the word's parts 'without a yoke' — the yoke of heaven thrown off); READ AS IDOLATRY BY I2 WITH 13:14 (117:3, checked in MIDDOT.md — 'base' is said here and 'base' is said of the sons of Belial who lead a city astray: whoever shuts his eyes from charity is as an idolater — THE TRANSFER taught by the Sifrei, the exemplar 13:14's sons of Belial, the seducers' cell by CALL: a labeled edge); 'beware' and 'lest' two prohibitions (117:2); Hillel's reason for the prozbul this verse (Gittin 36a:11); Onkelos 'in wickedness' (ברשע — 13:14's sons of Belial rendered by the same word)")
        dat('THE WRITE base_thought_barred — a BLOCK on israel_people at the counter\'s day (DG2); the transfer\'s edge release_firstborn -> seducers labeled with its teacher (the Sifrei 117:3); the exam\'s person the one who refuses a loan because the seventh year is near — barred from it')
        return out("the base thought (15:9) — 'beware lest a base thought': 'base' without a yoke (the Sifrei 117:1 — E30), read as idolatry by I2 with 13:14's sons of Belial (117:3 — the TRANSFER taught by the Sifrei, seducers by CALL, labeled); Hillel's reason for the prozbul (Gittin 36a:11): THE WRITE base_thought_barred, a BLOCK on Israel at the chapter's own day; the one who refuses a loan because the seventh year is near barred from it", ['base_thought_barred'])
    if ask == 'the_cry_and_the_sin':
        ink('15:9', '"and he CRY to the LORD against you, and it BE SIN in you" — "and it be sin in you" THREE in the book %s (the needy\'s cry, the vow 23:22, the hireling\'s cry 24:15); 24:15\'s clause %s, the shared run %d; Exodus 22:22\'s doubled cry %s; the Name alone at 15:9 (not "your God") %s' % (SIN_IN_YOU, words('Deut', 24, 15)[-6:], TWIN['15:9 vs 24:15'], words('Exod', 22, 22)[6:12], [v for v in range(1, 24) if 'יהוה' in W15(v) and not any(W15(v)[i:i + 2] == ['יהוה', 'אלהיך'] for i in range(len(W15(v)) - 1))]))
        move('the Sifrei 117:5 with 279:4 word for word (read whole at the reading); cold_run_ordinances (CALL) — OR.loan(creditor_manner) = %s; the one database: cry_heard on israel_people before this daemon\'s lines %s, bears_sin %s' % (V(OR_MANNER), REUSE_SCAN[1] if REUSE_SCAN else None, REUSE_SCAN[2] if REUSE_SCAN else None), "THE CRY A HASTENER AND THE SIN UNCONDITIONAL — 'and he cry to the LORD against you': might it be a commandment not to cry? 'and it be sin in you' — whether he cries or not; 'and he cry' — I hasten to punish through the one who cries more than through the one who does not (117:5; 279:4 the hireling's cry WORD FOR WORD — 24:15 seven tokens in order); cry_heard REUSED (the HEAVEN entry of the pledged poor man's cry, Exodus 22:22-23's — the ordinances' line on the tape, cry_went_up Exod 2:23 the cry's first seat) and bears_sin REUSED (the STATUS 'it be sin in you' — the divine ledger; the running world held none): second entries on Israel at the chapter's own day")
        dat('THE TWO REUSES cry_heard and bears_sin — entries on israel_people on the line hand_opening_commanded (DG2 — the before-counts read from the one database by source: cry_heard ONE, bears_sin NONE); the readback row 15:9 SUPPLIED with base_thought_barred, the cry by kind (cry_went_up Exod 2:23); the exam\'s person the needy who cries to the LORD against the shut hand — accepted, the sin in the refuser whether he cries or not')
        return out("the cry and the sin (15:9) — 'and he cry to the LORD against you and it be sin in you': the cry a hastener, the sin unconditional (the Sifrei 117:5 with 279:4 word for word — 24:15's hireling seven tokens in order): cry_heard and bears_sin REUSED — entries on Israel at the chapter's own day (Exodus 22:22's cry the first seat); the needy who cries against the shut hand accepted", ['accepted'])
    if ask == 'the_secret_gift':
        ink('15:10', '"GIVE, YOU SHALL GIVE him, and your heart shall not grieve when you give him" — "give, you shall give" %s (Jephthah\'s vow the other seat); "your heart grieved" %s (Elkanah\'s to Hannah); "give" eight tokens in six verses %s' % (P('נתון', 'תתן'), P('ירע', 'לבבך'), {v: [x for x in W15(v) if x in ('תתן', 'נתן', 'ונתתה', 'בתתך', 'נתון', 'תתנו')] for v in range(1, 24) if any(x in ('תתן', 'נתן', 'ונתתה', 'בתתך', 'נתון', 'תתנו') for x in W15(v))}))
        move('the Sifrei 117:6-8 (read whole at the reading); Mishnah Shekalim 5:6 (inside the spine and at the docket); Ketubot 67b:12-18 (read whole at the docket)', "THE SECRET GIFT — 'and your heart shall not grieve when you give him': Mishnah Shekalim 5:6 inside the spine — THE CHAMBER OF THE SILENT, where the sin-fearing put in secret and the poor of good family are sustained in secret (117:7); THE FOUR GRADES OF THE GIVER (117:8 — gives and wishes others to give, gives and wishes others not to, does not give and wishes others to, neither: a DATA row); the secret givers of Ketubot 67b:12-18 (Mar Ukva's coin in the door's socket)")
        dat('the secret gift a DATA row (the_secret_gift — Shekalim 5:6\'s chamber of the silent; Ketubot 67b:12-18); THE FOUR GRADES a DATA row (the_four_grades — 117:8); the exam\'s person the one who gives in secret in the chamber of the silent — accepted')
        return out("the secret gift (15:10) — 'give, you shall give him and your heart shall not grieve': the chamber of the silent (Mishnah Shekalim 5:6 inside the spine — the Sifrei 117:7), the secret givers (Ketubot 67b:12-18); the four grades of the giver (117:8): the one who gives in secret in the chamber of the silent accepted", ['accepted'])
    if ask == 'the_blessing_on_the_work':
        ink('15:10', '"for BECAUSE OF THIS THING the LORD your God will BLESS YOU IN ALL YOUR WORK AND IN ALL YOU PUT YOUR HAND TO" — "because of this thing" %s (one seat); "all that you put your hand to" the book\'s six %s; 14:29\'s twin "in all the work of your hand" %s, the shared run %d; the six blessings in five verses %s' % (P('בגלל', 'הדבר', 'הזה'), U('משלח', books=DT), P('בכל', 'מעשה', 'ידך', books=DT), TWIN['15:10 vs 14:29'], {v: [x for x in W15(v) if x in ('ברך', 'יברכך', 'ברכך', 'וברכך')] for v in range(1, 24) if any(x in ('ברך', 'יברכך', 'ברכך', 'וברכך') for x in W15(v))}))
        move('the Sifrei 117:9-10 (read whole at the reading); cold_run_food_tithe (CALL) — FT.the_third_year(the_four_in_want) = %s; the one database: work_of_the_hand_blessed anywhere before this sitting %s (14:29\'s line wrote none — the registry held no name at the types step)' % (str(V(FT_FOUR))[:40], HOLE_SCAN), "THE BLESSING ON THE WORK OF THE HAND — 'because of this thing': even if he said 'I will give' and did not give, even if he gave and it was lost, the blessing on the resolve (117:9-10); 'in all your work and in all you put your hand to' 14:29's twin (six tokens in order — the third year's tithe on the tape, third_year_tithe_declared, food_tithe by CALL): work_of_the_hand_blessed A NEW HEAVEN ENTRY at 15:10, its second seat at 15:18 (the blessing beside every money loss, 123:3); 14:29's line wrote no such name — measured at the types step, the design's 'or three' the one arm")
        dat('THE WRITE work_of_the_hand_blessed — a HEAVEN entry on israel_people at the counter\'s day (DG2 — TWO: 15:10\'s on the line hand_opening_commanded and 15:18\'s on hebrew_slave_law_declared); the readback row 15:10 SUPPLIED with the write, 14:29\'s line by kind; the exam\'s person the one who resolved to give and lost the coin — blessed on the resolve: accepted')
        return out("the blessing on the work (15:10) — 'because of this thing the LORD will bless you in all your work': even the resolve that was not fulfilled (the Sifrei 117:9-10); 14:29's twin six tokens in order (food_tithe by CALL, the tape's third_year_tithe_declared): THE WRITE work_of_the_hand_blessed, a HEAVEN entry on Israel — twice, 15:10 and 15:18; the one who resolved to give and lost the coin accepted", ['work_of_the_hand_blessed'])
    if ask == 'the_needy_never_cease':
        ink('15:11', '"for the needy shall NEVER CEASE from the midst of the land; THEREFORE I COMMAND YOU, saying: open, you shall open your hand to your brother, to your poor and to your needy, in your land" — "therefore I command you" five in the book %s (twice in this chapter); "from the midst of the land" %s (one seat); "your poor" %s (Hagar\'s "your affliction" the homograph); the three nouns %s' % (P('על', 'כן', 'אנכי', 'מצוך', books=DT), P('מקרב', 'הארץ'), U('עניך', 'לעניך'), W15(11)[-4:]))
        move('the Sifrei 118:1-3 (read whole at the reading)', "THE DEFAULT ARM — 'the needy shall never cease': the state variable's second arm (118:1 with 114:1 — when you do not do His will); 'therefore I command you, saying' — counsel for your good (118:2); 'to your brother, to your poor, to your needy' — THREE NOUNS THREE MEASURES (118:3: to whom you give, how you give, how much); 'in your land' the Land before outside it (116:8 again)")
        dat('the needy never cease — the state variable\'s default arm (the_needy_condition, F2); the three nouns three measures a DATA row (the_three_nouns — 118:3); the exam\'s person the one who opens his hand to his brother, his poor and his needy in the Land — accepted')
        return out("the needy never cease (15:11) — the state variable's default arm (the Sifrei 118:1 with 114:1); 'therefore I command you' counsel for your good (118:2); the three nouns three measures — to whom, how, how much (118:3): the one who opens his hand to his brother, his poor and his needy accepted", ['accepted'])
    return out('no verdict in span', [FX.NONE])


