# THE SIFREI ROWS OUTSIDE THE SPINE CITING CHAPTER 15 — THE SECOND HALF (THE DEUTERONOMY WALK sitting 13 — CHAPTER 15, 2026-09-22; RUN B2): six of the ten
# outside rows (ch15_ink.OUTSIDE) — 71:6, 71:7, 71:8 on 12:15 (READ BEFORE at chapter 12's sitting), 106:5 on 14:23 (READ BEFORE at chapters 12 and 14 —
# its THIRD read), 147:3 and 147:4 on 17:1 (fresh) — ALL read WHOLE in both files (the whole-row rule); the prior reads REREAD WHOLE and marked; none
# excluded. The cuts by ch15_ink.SP_; the middot checked before typed (I1, I2). RUN B1's form (ch15_rows_outside_a.py).
from ch15_ink import *
SO = {}
def orow(p, r, verdict, prose): SO[(p, r)] = (verdict, prose)

orow(71, 6, 'MATERIAL', f'WHENCE THAT [THE CONSECRATED] ARE SLAUGHTERED ONLY FOR A PERMANENT BLEMISH? YOU SAY, IT IS AN A FORTIORI: IF THE FIRSTLING, WHICH DOES NOT APPLY TO EVERY OFFSPRING AND GOES OUT TO COMMON USE WITHOUT REDEMPTION, IS SLAUGHTERED ONLY FOR A PERMANENT BLEMISH — THE CONSECRATED, WHICH APPLY TO EVERY OFFSPRING AND GO OUT ONLY BY REDEMPTION, IS IT NOT LOGICAL? NO: IF YOU SAID IT OF THE FIRSTLING, WHOSE HOLINESS IS FROM THE WOMB AND FALLS ON A PERMANENT BLEMISH … THE TEACHING SAYS "WHICH HE HAS GIVEN YOU IN ALL YOUR GATES" (12:15): "YOUR GATES", "YOUR GATES" FOR AN ANALOGY — AS "YOUR GATES" SAID THERE (15:22) IS SLAUGHTERED ONLY FOR A PERMANENT BLEMISH, SO "YOUR GATES" SAID HERE. The row on 12:15 ({SP_(71, 6, "אלא", "על", "מום", "קבוע")} "only for a permanent blemish"; {SP_(71, 6, "שעריך", "שעריך", "לגזרה", "שוה")} "your gates, your gates, for an analogy"): I1 (checked) REFUTED BY THE WOMB\'S HOLINESS, THEN I2 (checked) NAMED IN THE HEBREW on "your gates" at 12:15 and 15:22 — THE FIRSTLING\'S PERMANENT BLEMISH (15:21-22) LENT TO ALL THE CONSECRATED (12:15) by the word; 124:3 runs the same refuted a fortiori for the shearing and the work; the English\'s note "see 124:2". REREAD WHOLE (chapter 12\'s sitting, deu_12_reeh).')
orow(71, 7, 'MATERIAL', f'"THE UNCLEAN SHALL EAT" (12:15) — I HAVE ONLY THE UNCLEAN; THE CLEAN, WHENCE? "TOGETHER THEY SHALL EAT IT" (15:22; 12:22) — IT TELLS THAT BOTH EAT FROM ONE DISH. The row on 12:15 ({SP_(71, 7, "טהור", "מנין")} "the clean, whence"; {SP_(71, 7, "מתוך", "קערה", "אחת")} "from one dish"): "TOGETHER" READ AS ONE DISH — the clause "the unclean and the clean together" at its third seat (asserted: 12:15, 12:22, 15:22), the blemished firstling common flesh shared by the unclean and the clean. REREAD WHOLE (chapter 12\'s sitting, deu_12_reeh).')
orow(71, 8, 'MATERIAL', f'MIGHT EVEN THE HEAVE-OFFERING BE EATEN FROM ONE DISH? THE TEACHING SAYS "TOGETHER THEY SHALL EAT IT" — THIS IS EATEN FROM ONE DISH, AND THE HEAVE-OFFERING IS NOT EATEN FROM ONE DISH. The row on 12:15 ({SP_(71, 8, "אף", "תרומה")} "even the heave-offering"; {SP_(71, 8, "ואין", "תרומה", "נאכלת")} "and the heave-offering is not eaten"): THE PRONOUN\'S LIMIT — "it" the blemished firstling, the priest\'s heave-offering outside the one dish (Leviticus 22:1-16\'s holy food the kin\'s ledger by name). REREAD WHOLE (chapter 12\'s sitting, deu_12_reeh).')
orow(106, 5, 'MATERIAL', f'OTHERS SAY: MIGHT A FIRSTLING WHOSE TIME PASSED FROM ONE YEAR TO THE NEXT BE DISQUALIFIED LIKE THE DISQUALIFIED CONSECRATED? THE TEACHING SAYS "AND YOU SHALL EAT BEFORE THE LORD YOUR GOD" (14:23). IF TO TEACH THAT THE FIRSTLING IS EATEN WITHIN THE WALL — NO NEED, FOR IT IS ALREADY SAID "BEFORE THE LORD YOUR GOD YOU SHALL EAT IT" (15:20); IF OF THE SECOND TITHE — NO NEED, FOR IT IS ALREADY SAID "YOU MAY NOT EAT WITHIN YOUR GATES" (12:17). THEN WHY "AND YOU SHALL EAT BEFORE THE LORD YOUR GOD"? THE VERSE COMPARES THE FIRSTLING TO THE SECOND TITHE: AS THE SECOND TITHE IS EATEN FROM ONE YEAR TO THE NEXT, SO THE FIRSTLING. The row on 14:23 ({SP_(106, 5, "מקיש", "בכור", "למעשר", "שני")} "the verse compares the firstling to the second tithe"; {SP_(106, 5, "משנה", "לחברתה")} "from one year to the next"): THE YEAR PASSED NO BAR — the redundancy of 14:23 against 15:20 and 12:17 makes 14:23 a comparison (the juxtaposition, the shelf\'s own word without a code): the firstling eaten after its year like the second tithe (125:1\'s two days the edge case, Tosefta Sanhedrin 3:6 the English\'s note); 15:20 the clause cited. REREAD WHOLE — ITS THIRD READ (chapter 12\'s sitting, deu_12_reeh; chapter 14\'s, deu_14_reeh).')
orow(147, 3, 'MATERIAL', f'"IN WHICH THERE IS A BLEMISH" (17:1) — I HAVE ONLY ONE BORN UNBLEMISHED THAT BECAME BLEMISHED; ONE BORN BLEMISHED FROM ITS MOTHER\'S WOMB, WHENCE? "ANY EVIL THING". The row on 17:1 ({SP_(147, 3, "נולד", "בעל", "מום", "ממעי", "אמו")} "one born blemished from its mother\'s womb"; {SP_(147, 3, "כל", "דבר", "רע")} "any evil thing"): 126:1\'s FIRST CLAUSE AT THE TWIN VERSE — the words "any evil thing" are 17:1\'s own (asserted: 15:21 has "any evil blemish", 17:1 "any evil thing", six tokens in order) and THE ENGLISH CITES 15:21 FOR THEM (the union\'s reason; its note misreads the variant); NEVER READ AHEAD — 17:1 waits for its sitting, the row recorded here from its citation. Fresh.')
orow(147, 4, 'MATERIAL', f'WHENCE THE SCABBED, THE WARTED AND THE ONE WITH TUMORS? "A BLEMISH, ANY EVIL THING". WHENCE THE OLD, THE SICK AND THE FOUL? "AN OX OR A SHEEP … ANY EVIL THING". The row on 17:1 ({SP_(147, 4, "בעל", "גרב")} "the scabbed"; {SP_(147, 4, "לזקן", "וחולה", "ומזהם")} "the old, the sick and the foul"): 126:1\'s SECOND CLAUSE AT THE TWIN VERSE — the acquired blemishes and the conditions of age from two phrases of 17:1 where 126:1 takes both from one (Mishnah Bekhorot 6:12 the English\'s note; the English cites 15:21 twice and 17:1 once); NEVER READ AHEAD. Fresh.')
print('the outside rows of the second half typed:', len(SO), '| the cuts\' misses:', FAIL)
