def the_firstling(case, data):
    """F6 — Deut 15:19-20 — CONSECRATED FROM THE WOMB (consecrated_firstborn REUSED by CALL to korach and ordinances), SANCTIFIED FOR ITS VALUE against Leviticus 27:26 (temurah.consecrate by CALL — the DISAGREES row resolved as data); THE LINE firstling_law_declared writing firstling_sanctification_commanded (a STATUS) and firstling_work_and_shearing_barred (a BLOCK); THE FIRSTLING'S YEAR A CLOCK DATUM with its two-day edge; the blemished's thirty days; the tending term 'given only to the Sages'; before the LORD at the place — holy_things_in_the_gates_barred REUSED"""
    del P_[:]
    ask = case['ask']
    if ask == 'consecrated_from_the_womb':
        ink('15:19', '"EVERY FIRSTLING that is BORN of your herd and of your flock, THE MALE, you shall sanctify" — "firstling" three tokens here of the book\'s eight %s; Exodus 13:2 "sanctify to Me every firstborn, the opener of every womb" %s; 34:19 "every opener of the womb is Mine … you shall sanctify the males" %s; Numbers 18:17 "the firstling of an ox … you shall not redeem, they are holy" %s' % ([(s, x) for s, x, _ in LEMT('1060', books=DT) if s.startswith('Deut 15')], words('Exod', 13, 2)[:7], words('Exod', 34, 19)[:6], words('Num', 18, 17)[:10]))
        move('the Sifrei 124:1 (read whole at the reading); Bekhorot 19a:4, 41b:8, 42a:11 (read whole at the docket); cold_run_korach (CALL) — KO.the_gifts(opens_the_womb) = %s (fx %s), (clean_firstborn) = %s; cold_run_ordinances (CALL) — OR.firstling(eighth_and_onward) = %s, (two_seats_one_timer) = %s; the one database: consecrated_firstborn anywhere on the tape\'s world NONE (the case worlds\' own)' % (str(V(KO_WOMB))[:60], KO_WOMB[1], str(V(KO_CLEAN))[:50], V(OR_EIGHTH), V(OR_TIMER)), "CONSECRATED FROM THE WOMB — consecrated_firstborn REUSED BY CALL: the consecration is Exodus 13:2's and Numbers 18:17's (the status 'written at birth' — korach.the_gifts(opens_the_womb) writes it; ordinances.firstling the eighth day and the seven with its mother), NOT THIS VERSE'S: 'the male' the detail of Exodus 13:2 (Bekhorot 19a:4; the sex's edge 41b:8, 42a:11); its year and the blemished from 'every' (124:1 — 'every firstling': within its year and after, unblemished and blemished)")
        dat('consecrated_firstborn REUSED at the case (the exam\'s firstling written on at its birth by the korach cell\'s own effect — never on the tape); the exam\'s person the firstling male born of the herd — consecrated from the womb')
        return out("consecrated from the womb (15:19) — the consecration Exodus 13:2's and Numbers 18:17's by CALL (korach.the_gifts opens_the_womb — consecrated_firstborn the status written at birth; ordinances.firstling the eighth day), not this verse's; 'the male' Exodus 13:2's detail (Bekhorot 19a:4): the firstling male born of the herd consecrated from the womb", ['consecrated_firstborn'])
    if ask == 'the_sanctify_for_value':
        ink('15:19', '"the male YOU SHALL SANCTIFY to the LORD your God" — "the male you shall sanctify" %s (one seat); Leviticus 27:26 "but a firstling … NO MAN SHALL SANCTIFY IT; whether ox or sheep, it is the LORD\'s" %s; the sanctify-verb\'s sixteen seats hold 27:26 %s' % (P('הזכר', 'תקדיש'), words('Lev', 27, 26), 'Lev 27:26' in U('תקדיש', 'יקדיש', 'הקדיש', 'תקדישו', 'יקדישו')))
        move('the Sifrei 124:4 (read whole at the reading); Mishnah Arakhin 8:7 (inside the spine and at the docket); Arakhin 29a:20, Nazir 4b:11 (read whole at the docket); cold_run_temurah (CALL) — TM.consecrate(firstborn_for_value) = %s (fx %s), TM.consecrate(firstborn) = %s' % (V(TM_FBV), TM_FBV['fx'], V(TM_FB)), "'YOU SHALL SANCTIFY' AGAINST 'NO MAN SHALL SANCTIFY' UPHELD BY DIVIDING THE SPHERES — Mishnah Arakhin 8:7 inside the spine (124:4): you sanctify it for its VALUE, never for the altar (R. Yishmael — the two verses at the answer sheet, Arakhin 29a:20; sanctified by word though holy from birth, Nazir 4b:11); TEMURAH'S CELL ALREADY CARRIES 15:19 AS ITS IMPORT against 27:26 (temurah.consecrate('firstborn_for_value') by CALL: value_consecration_yes — 'the two verses: you SHALL sanctify and no man shall sanctify: R. Yishmael resolves them'); THE READBACK'S DISAGREES ROW 15:19 RESOLVED AS DATA (the row stays OPEN as the design wrote it, the resolution the parameter)")
        dat('THE WRITE firstling_sanctification_commanded — a STATUS on israel_people at the counter\'s day (DG2), its value THE PARAMETER the_sanctify_for_value (Arakhin 8:7 — the declaration a mitzvah, the value the Temple treasury\'s); the exam\'s person the owner who declares "this firstling is holy" — accepted, for its value')
        return out("sanctify for value (15:19) — 'you shall sanctify' against Leviticus 27:26's 'no man shall sanctify' upheld by dividing the spheres: for its value, never for the altar (the Sifrei 124:4; Mishnah Arakhin 8:7; Arakhin 29a:20; temurah.consecrate by CALL — value_consecration_yes): THE WRITE firstling_sanctification_commanded, a STATUS on Israel at the chapter's own day; the owner who declares 'this firstling is holy' accepted — for its value", ['firstling_sanctification_commanded'])
    if ask == 'the_altars_bar':
        ink('15:19', '"you shall sanctify to the LORD your God" — "to the LORD" at 15:2, 19, 21 %s; 27:26\'s "it is the LORD\'s" %s' % ([v for v in range(1, 24) if 'ליהוה' in W15(v)], words('Lev', 27, 26)[-2:]))
        move('the Sifrei 124:3-4 (read whole at the reading); Arakhin 29a:20 (read whole at the docket); cold_run_temurah (CALL) — TM.consecrate(firstborn) = %s, TM.firstborn_trick() = %s; cold_run_primeval (CALL) — PV.cain(firstling_by_call) = %s' % (V(TM_FB), V(TM_TRICK), V(PV_FIRSTLING)), "THE ALTAR'S BAR — 'no man shall sanctify it' (Leviticus 27:26 by CALL: cannot_be_sanctified_to_the_altar — the firstling is the LORD's already; the primeval runner already calling it for Abel's firstlings); THE CONSECRATED BY A REFUTED A FORTIORI THEN THE VERSE (124:3 — I1, checked in MIDDOT.md; 71:6's form): might the firstling be sanctified as another offering? the verse; the trick of the womb (temurah.firstborn_trick — 'what is in her womb, if male, an olah' before it is born a firstling)")
        dat('the altar\'s bar a DATA row (the_altars_bar — 27:26 by CALL; 124:3 the refuted a fortiori; the womb\'s trick); the exam\'s person the one who sanctifies the firstling as a burnt offering — barred from it')
        return out("the altar's bar (15:19) — 'no man shall sanctify it' (Leviticus 27:26 by CALL to temurah.consecrate — cannot be sanctified to the altar, it is the LORD's already); the consecrated by a refuted a fortiori then the verse (the Sifrei 124:3 — I1): the one who sanctifies the firstling as a burnt offering barred from it", ['barred_from_it'])
    if ask == 'the_caesarean':
        ink('15:19', '"every firstling that is BORN" — "born" %s; Exodus 13:2\'s "opener of the womb" %s' % ([x for x in W15(19) if x == 'יולד'], words('Exod', 13, 2)[4:6]))
        move('the Sifrei 124:2 (read whole at the reading); Mishnah Bekhorot 2:9 (read whole at the docket); Niddah 40a:14, Tosefta Bekhorot 3:2 (read whole at the docket); cold_run_ordinances (CALL) — OR.gifts(caesarean) = %s; cold_run_priesthood (CALL) — PR.blemish(beast_unfits_in_man) caesarean = %s' % (V(OR_CAES), V(PR_UNFITS).get('caesarean')), "THE CAESAREAN OUT — 'that is born': to the exclusion of the one born by the wall (124:2); Mishnah Bekhorot 2:9 the caesarean and the one born after it neither a firstling (the caesarean by I2 'birth'/'birth', Niddah 40a:14; Tosefta Bekhorot 3:2); the ordinances' cell by CALL (not consecrated — the Passover engine's predicate 'opener of the womb')")
        dat('THE PARAMETER the_caesarean (124:2; Mishnah Bekhorot 2:9 — not a firstling; OR.gifts by CALL); the exam\'s person the caesarean firstling — exempt')
        return out("the caesarean (15:19) — 'that is born' excludes the one born by the wall (the Sifrei 124:2; Mishnah Bekhorot 2:9 — neither it nor the one after it a firstling; ordinances.gifts by CALL: not consecrated): THE PARAMETER the_caesarean; the caesarean firstling exempt", ['exempt'])
    if ask == 'the_your_two_ways':
        ink('15:20', '"before the LORD your God YOU shall eat it year by year … YOU AND YOUR HOUSEHOLD" — "you and your household" %s (14:26\'s twin); Numbers 18:18 gives the flesh to the priest %s; Onkelos "the people of your house"' % (P('אתה', 'וביתך', books=DT), words('Num', 18, 18)))
        move('the Sifrei 124:5-6 (read whole at the reading); Bekhorot 32b-33a (credited by address — firstborn_eaters); cold_run_korach (CALL) — KO.the_gifts(firstborn_eaters) = %s, (firstborn_portions) fx %s' % (str(V(KO_EATERS))[:70], KO_WINDOW[1]), "'YOUR' TWO WAYS A DISPUTE — 'you shall eat it': the owner's, or the priest's? (124:5 — 'you and your household' 14:26's twin; the firstling's flesh the priest's by Numbers 18:18 'their flesh shall be yours as the wave-breast' — korach.the_gifts(firstborn_eaters) by CALL: Beit Shammai priests only, Beit Hillel the blemished to any); THE TWO BARS CROSSED BY FOUR A FORTIORI ARGUMENTS AND THE TWO FILES READING THE CLOSING VERSE OPPOSITE WAYS (124:6 — a DISPUTE of the two files the_files_disagree, for the exam)")
        dat('THE PARAMETER the_your_two_ways (124:5 — the owner\'s or the priest\'s; the flesh the priest\'s by Numbers 18:18 by CALL); THE PARAMETER the_files_disagree (124:6 — the two files opposite ways); the exam\'s person the owner who eats the unblemished firstling\'s flesh — barred from it (the priest\'s by Numbers 18:18)')
        return out("'your' two ways (15:20) — 'you shall eat it, you and your household': the owner's or the priest's (the Sifrei 124:5); the flesh the priest's by Numbers 18:18 (korach.the_gifts by CALL); the two files reading the closing verse opposite ways (124:6): THE PARAMETERS the_your_two_ways, the_files_disagree; the owner who eats the unblemished firstling's flesh barred from it", ['barred_from_it'])
    if ask == 'the_work_and_the_shearing':
        ink('15:19', '"YOU SHALL DO NO WORK with the firstling of your ox NOR SHEAR the firstling of your flock" — "you shall do no work with the firstling of your ox" %s (one seat; 21:3\'s heifer "not worked" %s the twin); "shear" the verb\'s seats %s (this the book\'s one — Jacob\'s Laban, Judah\'s sheepshearers, Nabal\'s, Isaiah 53:7); the two negations at 15:19' % (P('לא', 'תעבד', 'בבכר', 'שורך'), P('לא', 'עבד', 'בה'), [s for s in GZZ if s.startswith(('Deut', 'Gen', '1Sam 25:2', 'Isa'))]))
        move('the Sifrei 124:6 (read whole at the reading); Bekhorot 9b:13, 24b:5, 41b:2 (read whole at the docket); Chullin 135a:9, 135b:13, 136b:18, 137a:4, Temurah 11b:15, Tosefta Bekhorot 1:6, 2:3 (read whole at the docket); cold_run_temurah (CALL) — TM.tithe(herd_with_flock) = %s' % (V(TM_HERD),), "THE WORK AND THE SHEARING A BLOCK — the two bars crossed by four a fortiori arguments and closed by the verse (124:6); 'your ox … your flock' the partnership's arm (Bekhorot 9b:13); the neck's hair plucked not shorn (24b:5; Mishnah 3:3); THE SANCTION GATED ON CERTAINTY (41b:2); the ban borrowed by the first shearing and read over both kinds (Chullin 135a:9-137a:4); the blemished consecrated's lashes (Tosefta Bekhorot 2:3 — with R. Shimon's arm 1:6); the herd's tithe 'under the rod' by CALL (temurah.tithe — not tithed together)")
        dat('THE WRITE firstling_work_and_shearing_barred — a BLOCK on israel_people at the counter\'s day (DG2); the exam\'s person the one who shears the firstling — barred from it (the lashes gated on certainty, 41b:2)')
        return out("the work and the shearing (15:19) — 'you shall do no work … nor shear': the two bars closed by the verse (the Sifrei 124:6); the partnership's arm, the sanction gated on certainty (Bekhorot 9b:13, 41b:2), the ban read over both kinds (Chullin 135a-137a): THE WRITE firstling_work_and_shearing_barred, a BLOCK on Israel at the chapter's own day; the one who shears the firstling barred from it", ['firstling_work_and_shearing_barred'])
    if ask == 'the_plucking':
        ink('15:19', '"nor SHEAR the firstling of your flock" — "shear" (גזז) the ban\'s verb %s; Onkelos "you shall not shear" (תגוז) one seat' % ([x for x in W15(19) if 'תגז' in x],))
        move('Bekhorot 25a:1-16 (read whole at the docket)', "PLUCKING IS NOT SHEARING — Rav (Bekhorot 25a:1-16): the cleaver's clearing by hand, not by a tool that looks like shearing (25a:13); plucked to show a blemish from the outset (25a:14-16); the red heifer's black-tipped hairs (25a:8-12): THE BAN'S DEFINITION A DATA ROW beside 15:19's block")
        dat('the plucking a DATA row (the_plucking — Bekhorot 25a:1-16: plucking is not shearing; by hand to show the blemish); the exam\'s person the one who plucks the firstling\'s hair by hand to show its blemish — accepted')
        return out("the plucking (15:19) — plucking is not shearing: the cleaver's clearing by hand, not by a tool that looks like shearing; plucked to show a blemish from the outset (Bekhorot 25a:1-16 — Rav): the one who plucks the firstling's hair by hand to show its blemish accepted", ['accepted'])
    if ask == 'the_shed_hair':
        ink('15:19', '"the firstling of your flock" — the flock\'s wool the ban\'s object; "your flock" at 15:14 and 15:19 %s' % ([(v, x) for v in (14, 19) for x in W15(v) if 'צאנ' in x],))
        move('Mishnah Bekhorot 3:4 at 25a:17-25b:2, Bekhorot 25b:5, 26a:6-8, 26a:15, 26b:5 (read whole at the docket); Mishnah Eduyot 5:6 (the ruling\'s seat)', "THE SHED HAIR OF THE BLEMISHED FIRSTLING — Mishnah Bekhorot 3:4: the wool that fell from it and the wool it shed at its death — Akavya ben Mahalalel permits, the Rabbis forbid (25a:17-25b:2); Rava's THREE DISPUTES on where they differ (26a:6-7); THE RULING AS R. YEHUDA from Eduyot 5:6 (26a:8); the Rabbis' DECREE lest one delay the slaughter to gather wool — the ban's guard (25b:5), the offerings that do not atone (26a:15); the dangling wool defined two ways (26b:5)")
        dat('the shed hair a DATA row (the_shed_hair — Mishnah Bekhorot 3:4; Rava\'s three disputes; the ruling as R. Yehuda; the decree the ban\'s guard); the exam\'s person the one who uses the wool the blemished firstling shed, after its slaughter — accepted (R. Yehuda), barred before (the decree)')
        return out("the shed hair (15:19) — the wool the blemished firstling shed: Akavya permits, the Rabbis forbid (Mishnah Bekhorot 3:4 at 25a:17-25b:2), the ruling as R. Yehuda (26a:8 from Eduyot 5:6), the Rabbis' decree lest one delay the slaughter (25b:5): the one who uses the wool the blemished firstling shed, after its slaughter, accepted", ['accepted'])
    if ask == 'the_firstlings_year':
        ink('15:20', '"before the LORD your God you shall eat it YEAR BY YEAR" — "year by year" (שנה בשנה) the Torah\'s two %s (Leviticus 25:53\'s hireling the other; 14:22\'s "year year" %s another form); "you shall eat it year by year" %s (one seat); the firstling\'s year by the clock %d days' % ([s for s in YEAR_BY_YEAR if s.startswith(('Deut', 'Lev'))], P('שנה', 'שנה'), P('תאכלנו', 'שנה', 'בשנה'), CLOCK['the_firstlings_year_days']))
        move('the Sifrei 125:1 (read whole at the reading); Bekhorot 27b:3-28a:11 (read whole at the docket); Mishnah Bekhorot 4:1 (read whole at the docket); cold_run_korach (CALL) — KO.the_gifts(firstborn_eating_window) = %s (fx %s), (blemished_keeping) = %s; cold_run_food_tithe (CALL) — FT.the_second_tithe(the_year_passed) = %s' % (str(V(KO_WINDOW))[:50], KO_WINDOW[1], str(V(KO_KEEP))[:80], str(V(FT_YEAR))[:40]), "THE FIRSTLING'S YEAR A CLOCK DATUM — 'year by year': TWO DAYS ACROSS THE YEAR'S EDGE (125:1 — the last day of its year and the first of the next both 'year by year'; Bekhorot 27b:5 the school of Rav — as a peace offering; 28a:1 not from 'the breast and the thigh'); THE FIRSTLING'S OWN YEAR FROM ITS BIRTH (27b:3-6 — 'a year in a year', 'a lamb in its first year' Leviticus 12:6); the eating window twelve months by the clock's own count (the_firstlings_year — %d days by the calendar, read from the print), the flesh's two days and a night by CALL (korach's window — the peace offering's row); the year passed no bar (106:5 — food_tithe's cell on file by CALL)" % (CLOCK['the_firstlings_year_days'],))
        dat('THE CLOCK DATUM the_firstlings_year (calendar_parameters.yaml — its own year, the two-day edge, the blemished, the tending term, the exile\'s arm); the year\'s days by the clock %d (DG6 — read, never typed); the exam\'s person the priest who eats the firstling on the first day of its second year — accepted (year by year)' % (CLOCK['the_firstlings_year_days'],))
        return out("the firstling's year (15:20) — 'year by year': its own year from its birth, two days and a night across the year's edge (the Sifrei 125:1; Bekhorot 27b:3-28a:1; Mishnah Bekhorot 4:1), the window by the clock's own count, the flesh's two days by CALL to korach: THE CLOCK DATUM the_firstlings_year; the priest who eats the firstling on the first day of its second year accepted", ['accepted'])
    if ask == 'the_blemished_thirty_days':
        ink('15:20-21', '"you shall eat it year by year … and if there be any blemish in it" — the blemished after the year the Mishnah\'s thirty days; "blemish" twice at 15:21 %s' % ([x for x in W15(21) if x == 'מום'],))
        move('Mishnah Bekhorot 4:1-2 (read whole at the docket); Bekhorot 28a:3-4, 28a:7-11 (read whole at the docket); cold_run_korach (CALL) — KO.the_gifts(blemished_keeping) = %s, (blemished_firstborn) = %s' % (str(V(KO_KEEP))[:80], str(V(KO_BLEM))[:60]), "THE BLEMISHED THIRTY DAYS AFTER THE YEAR — Mishnah Bekhorot 4:1: the unblemished within its year, the blemished thirty days after (korach's cell by CALL: 'a blemish within the year — kept the twelve months; after the year — thirty days'); THE THIRTY DAYS FOR THE LOST ITEM'S RETURN (28a:7-9); R. Elazar's thirty-from-the-blemish CONCLUSIVELY REFUTED (28a:11 — 28a:10's link row the refuted arm); THE BLEMISHED GIVEN TO THE PRIEST from 'it shall be yours' and 'their flesh' (28a:3-4 — 'stated nowhere else in the Torah')")
        dat('the blemished thirty days a DATA row (the_blemished_thirty_days — Mishnah Bekhorot 4:1-2; 28a:7-11; R. Elazar\'s arm refuted); the exam\'s person the priest who keeps the blemished firstling beyond thirty days after its year — barred from it')
        return out("the blemished thirty days (15:20-21) — the blemished firstling thirty days after its year (Mishnah Bekhorot 4:1-2; Bekhorot 28a:7-9 the lost item's thirty; R. Elazar's thirty-from-the-blemish refuted 28a:11; korach.the_gifts by CALL); the blemished the priest's from 'it shall be yours' (28a:3-4): the priest who keeps the blemished firstling beyond thirty days after its year barred from it", ['barred_from_it'])
    if ask == 'the_tending_term':
        ink('15:19', '"of your herd and of your flock" — the two kinds; Exodus 22:29 "seven days it shall be with its mother, on the eighth day you shall give it to Me" %s, the parser\'s [7] %s' % (words('Exod', 22, 29)[4:13], KINNUM[('Exod', 22, 29)]))
        move('Mishnah Bekhorot 4:1 at 26b:8; Bekhorot 26b:11-17 (read whole at the docket); cold_run_ordinances (CALL) — OR.firstling(eighth_and_onward) = %s, (with_its_mother) = %s, OR.gifts(thirty_days) = %s' % (V(OR_EIGHTH), V(OR_MOTHER), V(OR_THIRTY)), "THE TENDING TERM — thirty days the small animal, fifty the large (Mishnah Bekhorot 4:1 at 26b:8); FROM EXODUS 22:28-29's JUXTAPOSITION (26b:11-16): 'THE INTERPRETATION OF THE VERSE WAS GIVEN ONLY TO THE SAGES' — the oral number inside the verse, the code/data separation law's seat (the eighth day and onward by CALL — ordinances.firstling; the firstborn son's thirty by CALL); the priest who asks within the term looks like a paid helper at the threshing floor (26b:17)")
        dat('THE PARAMETER the_tending_term (in the_firstlings_year\'s row — thirty and fifty days, "given only to the Sages"; 26b:11-17); the exam\'s person the priest who asks for the small firstling within its thirty days — barred from it')
        return out("the tending term (15:19) — thirty days the small, fifty the large, the owner tends it (Mishnah Bekhorot 4:1 at 26b:8; from Exodus 22:28-29's juxtaposition, 26b:11-16 — 'the interpretation of the verse was given only to the Sages'; ordinances.firstling by CALL): the priest who asks for the small firstling within its thirty days barred from it", ['barred_from_it'])
    if ask == 'before_the_lord_at_the_place':
        ink('15:20', '"BEFORE THE LORD your God you shall eat it … IN THE PLACE which the LORD will choose" — the place formula at its fourth seat in this form %s (eleven in the book with 14:23\'s); "before the LORD your God you shall eat it" %s (12:18 the other); 12:18\'s clause the closest %d of %d; the Aramaic without the Shekhinah here' % ([s for s in PLACE_FORMULA if s in ('Deut 12:14', 'Deut 12:18', 'Deut 15:20', 'Deut 16:2')], P('לפני', 'יהוה', 'אלהיך', 'תאכלנו'), TWIN['15:20 vs 12:18'], len(W15(20))))
        move('the Sifrei 125:1 (read whole at the reading); cold_run_place_name (CALL) — PN.the_place_chosen(the_place_which_the_lord_will_choose) = %s; PN.the_profane_slaughter_the_blood_and_the_gates(you_may_not_eat_within_your_gates) = %s, (before_the_lord_you_shall_eat_it) = %s; the one database: holy_things_in_the_gates_barred on israel_people before this daemon\'s lines %s' % (str(V(PN_PLACE))[:50], str(V(PN_GATES))[:60], str(V(PN_BEFORE))[:50], REUSE_SCAN[3] if REUSE_SCAN else None), "BEFORE THE LORD AT THE PLACE — the formula's fourth seat in this form by CALL to place_name.the_place_chosen (12:14, 12:18 before; 16:2-16 ahead); 12:17-18's BLOCK holy_things_in_the_gates_barred REUSED — 'you may not eat within your gates … the firstlings of your herd and of your flock' (12:17) at its second seat: A SECOND ENTRY on israel_people at the chapter's own day (DD2's, DF5's, Q32's, Q39's ONE retyped TWO; the blocks 5 -> 6); 'before the LORD you shall eat it' 12:18's clause (nine of twelve in order); the firstling from outside the Land (Bekhorot 53b — food_tithe by CALL)")
        dat('THE REUSE holy_things_in_the_gates_barred — a second entry on israel_people on the line firstling_law_declared (DG2 — the before-count ONE read from the one database by source); the readback row 15:20 EXPANDED (profane_slaughter_permitted Deut 12:15 by kind; Numbers 18:18); the exam\'s person the owner who eats the unblemished firstling in his gates — barred from it')
        return out("before the LORD at the place (15:20) — the place formula's fourth seat by CALL (place_name.the_place_chosen); 12:17-18's bar on the firstling in the gates REUSED — holy_things_in_the_gates_barred a second entry on Israel at the chapter's own day (12:18's clause nine of twelve in order): the owner who eats the unblemished firstling in his gates barred from it", ['barred_from_it'])
    if ask == 'the_exiles_arm':
        ink('15:20', '"in the place which the LORD will choose" — no place, no Temple: the exile\'s state; 14:23\'s tithe and 12:15\'s slaughter had a third state' % ())
        move('Bekhorot 28a:6 (read whole at the docket); cold_run_korach (CALL) — KO.the_gifts(firstborn_without_altar) = %s; cold_run_food_tithe (CALL) — FT.the_second_tithe(the_firstling_from_outside) = %s' % (str(V(KO_NOALTAR))[:60], str(V(FT_OUTSIDE))[:50]), "THE EXILE'S ARM — no Temple: the firstling kept two or three years until a showable blemish (Bekhorot 28a:6); the flesh as the blood — eaten only while the altar stands (korach's cell by CALL); the firstling from outside the Land not brought (Bekhorot 53b; food_tithe's cell by CALL): the third state as chapter 12's slaughter law and 14:23's tithe had")
        dat('the exile\'s arm in the_firstlings_year\'s row (28a:6 — kept until a showable blemish); the exam\'s person the priest in the exile who keeps the firstling until a showable blemish — accepted')
        return out("the exile's arm (15:20) — no Temple: the firstling kept two or three years until a showable blemish (Bekhorot 28a:6); the flesh eaten only while the altar stands (korach.the_gifts by CALL); the firstling from outside the Land not brought (Bekhorot 53b; food_tithe by CALL): the priest in the exile who keeps the firstling until a showable blemish accepted", ['accepted'])
    if ask == 'the_firstling_from_outside':
        ink('15:19', '"of your herd and of your flock" — the Land\'s herds; 14:23\'s "the firstlings of your herd and your flock" %s' % (P('ובכרת', 'בקרך', 'וצאנך'),))
        move('Bekhorot 53b:5 (read whole at the docket); cold_run_food_tithe (CALL) — FT.the_second_tithe(the_firstling_from_outside) = %s (fx %s); cold_run_temurah (CALL) — TM.tithe(took_ten_of_a_hundred) = %s' % (str(V(FT_OUTSIDE))[:50], FT_OUTSIDE[1], V(TM_TEN)), "THE FIRSTLING FROM OUTSIDE THE LAND not brought (the Sifrei 106:2 at chapter 14; Temurah 21b:3 — food_tithe's cell by CALL: exempt); NO ANIMAL TITHE NOW BY DECREE (Bekhorot 53b:5 — temurah's DATA row, the tenth an ordinal)")
        dat('the firstling from outside a DATA row (the_firstling_from_outside — food_tithe by CALL; Bekhorot 53b:5); the exam\'s person the one who brings a firstling from Babylonia — exempt')
        return out("the firstling from outside (15:19) — not brought from outside the Land (food_tithe.the_second_tithe by CALL — the Sifrei 106:2; Temurah 21b:3); no animal tithe now by decree (Bekhorot 53b:5): the one who brings a firstling from Babylonia exempt", ['exempt'])
    return out('no verdict in span', [FX.NONE])


