

# ---- THE READBACK — THE FORMS ON FILE, NO NEW FORM (THE LOOP's step 6): T4 rows graded against the cells that compile their kin by CALL (cell, cell_found — every
# row has kin), T1 REFERENCE ROWS against the tape's lines by kind and first verse (tape_kind, tape_verse), never a second write; TEN rows SUPPLIED with their writes
# (the code's holes compiled at the chapter's own day — the place added to the feasts and the pilgrimage, the courts, the pillar); no pointer row (the register
# empty), no state row, no open row (the twins' departures resolved by the spine or recorded with both arms), no stretch, no retrograde row (no narrative verb) ----
GRADES = ('VERBATIM', 'VARIANT', 'TURNED', 'SHORTENED', 'EXPANDED', 'SUPPLIED', 'DISAGREES')
def FOUND(r): return r not in (None, '', 'no verdict in span', 'no_case')
def rb(verses, told, grade, why, tape_kind=None, tape_verse=None, cell=None, cell_found=None, entry='', open_=False, write=None, state=False, pointer=None):
    assert grade in GRADES, grade
    assert write is None or (isinstance(write, str) and write), ("a write is a registry name or None", verses)
    if grade == 'SUPPLIED': assert entry, ("a SUPPLIED row names what supplies it", verses)
    if grade == 'DISAGREES': assert open_, ("a DISAGREES row is open", verses)
    if tape_kind: assert tape_verse, verses
    if cell: assert cell_found is not None, verses
    if pointer: assert pointer.get('referent') and pointer.get('grade') == 'H', ("a pointer row names its referent and carries the H flag", verses)
    return {'verses': verses, 'told': told, 'grade': grade, 'why': why, 'tape_kind': tape_kind, 'tape_verse': tape_verse, 'cell': cell, 'cell_found': cell_found, 'entry': entry, 'open': open_, 'write': write, 'state': state, 'pointer': pointer, 'stretch': False}
READBACK = [
    rb('Deut 16:1', "observe the month of Aviv and keep the Passover to the LORD your God, for in the month of Aviv the LORD your God brought you out of Egypt by night", 'VARIANT', "VARIANT by CALL — Exodus 34:18's 'in the month of Aviv' the closest kin (seven in order), the night's clause new (Onkelos gives it a subject — 'He did miracles for you at night'); the intercalation read out of 'observe' (127:1 — a PARAMETER); the Passover kept on the tape at Num 9:5 the reference", tape_kind='passover_kept', tape_verse='Num 9:5', cell='pesach.paschal_procedure', cell_found=FOUND(PS_NAME), entry="the tape: passover_kept Num 9:5 (israel — passover_in_its_time); the cell for_its_sake; THE PARAMETER the_intercalation"),
    rb('Deut 16:2', "and you shall sacrifice the Passover to the LORD your God, flock and herd, in the place which the LORD will choose to make His name dwell there", 'EXPANDED', "EXPANDED by CALL — Exodus 12:5's lamb of the sheep or goats expanded to 'flock and herd': the herd THE FESTIVAL OFFERING (129:6 — Onkelos writing the same); the place added (place_name.the_place_chosen by CALL)", cell='place_name.the_place_chosen', cell_found=FOUND(PN_PLACE), entry="the place formula's first seat in the chapter; the herd the festival offering (erection.repeats by CALL)"),
    rb('Deut 16:3', "you shall eat no leaven with it; seven days you shall eat unleavened bread with it, the bread of affliction, for in haste you went out of Egypt, that you may remember the day of your going out all the days of your life", 'VARIANT', "VARIANT WITH ITS WRITE — Exodus 12:15's and 13:6-7's leaven law with three additions: 'with it' (the ban's sixth hour — 130:1), 'the bread of affliction' (130:3), 'all the days of your life' (Mishnah Berakhot 1:5 the exam row); THE LINE passover_at_the_place_declared writing leaven_with_the_passover_barred (a BLOCK)", cell='moadim.passover', cell_found=FOUND(MO_WINDOW), entry="THE WRITE leaven_with_the_passover_barred on israel_people at the counter's day; the slaughter window by CALL", write='leaven_with_the_passover_barred'),
    rb('Deut 16:4', "no leaven shall be seen with you in all your border seven days, nor shall any of the flesh which you sacrifice the first day at evening remain all night until the morning", 'VARIANT', "VARIANT WITH ITS WRITE — Exodus 13:7's six tokens in order with one word changed (leavening agent for leaven — the two measures, Mishnah Beitzah 1:1), and Exodus 12:10's and 34:25's overnight flesh; THE LINE writing flesh_till_morning_barred (a BLOCK)", cell='pesach.paschal_procedure', cell_found=FOUND(PS_LEFT), entry="THE WRITE flesh_till_morning_barred on israel_people at the counter's day; the remainder burned by CALL (pesach leftover); the fat overnight by CALL (calendar)", write='flesh_till_morning_barred'),
    rb('Deut 16:5', "you may not sacrifice the Passover within any of your gates which the LORD your God gives you", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — no seat in Exodus 12 for the gates' bar (the Passover of Egypt on the doorposts); 12:17's gates by CALL the nearest; one of the three true prohibitions (147:2); THE LINE writing passover_in_the_gates_barred (a BLOCK)", cell='place_name.the_profane_slaughter_the_blood_and_the_gates', cell_found=FOUND(PN_GATES), entry="THE WRITE passover_in_the_gates_barred on israel_people at the counter's day; 12:17's block by CALL (holy_things_in_the_gates_barred UNMOVED)", write='passover_in_the_gates_barred'),
    rb('Deut 16:6', "but at the place which the LORD your God will choose to make His name dwell there, you shall sacrifice the Passover at evening, at the going down of the sun, the season of your going out of Egypt", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — THE PLACE ADDED TO THE PASSOVER (no seat in Exodus 12 or Leviticus 23 for the place; 'between the evenings' nowhere here — the three phrases 133:2 the clock's slots); THE LINE writing passover_at_the_place_commanded (a STATUS)", cell='place_name.the_place_chosen', cell_found=FOUND(PN_PLACE), entry="THE WRITE passover_at_the_place_commanded on israel_people at the counter's day; the place by CALL (place_chosen_required UNMOVED); the eating until midnight by CALL (pesach)", write='passover_at_the_place_commanded'),
    rb('Deut 16:7', "and you shall cook it and eat it in the place which the LORD your God will choose, and in the morning you shall turn and go to your tents", 'VARIANT', "VARIANT by CALL — 'you shall cook' against Exodus 12:9's 'nor boiled in water': cooking is roasting (134:1; 2 Chronicles 35:13 the run's case — the spine resolves it, not DISAGREES); the lodging night (134:2-3) a DATA row; roasted only by CALL", cell='pesach.paschal_procedure', cell_found=FOUND(PS_PREP), entry="the cell preparation 'roasted only'; the lodging night the_lodging_night"),
    rb('Deut 16:8', "six days you shall eat unleavened bread, and on the seventh day a solemn assembly to the LORD your God: you shall do no work", 'VARIANT', "VARIANT WITH ITS WRITE — SIX against Exodus 13:6's SEVEN (the diff two tokens; the seventh's unleavened bread optional — 135:1-2), 'a solemn assembly' Leviticus 23:36's word at the Passover's seventh; the intermediate days handed to the sages (135:3 — A PARAMETER); THE LINE writing seventh_day_assembly_commanded (a STATUS)", cell='moadim.work_class', cell_found=FOUND(MO_WORK7), entry="THE WRITE seventh_day_assembly_commanded on israel_people at the counter's day; the work class by CALL (servile_only); THE PARAMETER the_intermediate_days_work", write='seventh_day_assembly_commanded'),
    rb('Deut 16:9', "seven weeks you shall count for yourself: from the time the sickle is first put to the standing grain you shall begin to count seven weeks", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — the count from THE SICKLE shares nothing in order with Leviticus 23:15-16's 'morrow of the sabbath … fifty days' (the sickle's two Bible seats): the omer's three rules and the reaping by night (136:3, 136:8); the morrow the festival and the count forty-nine by CALL; THE LINE weeks_and_booths_declared writing weeks_at_the_place_commanded (a STATUS)", cell='moadim.omer', cell_found=FOUND(MO_MORROW), entry="THE WRITE weeks_at_the_place_commanded on israel_people at the counter's day; the omer by CALL (counts_omer the moadim engine's timer UNMOVED); omer_day the registry's", write='weeks_at_the_place_commanded'),
    rb('Deut 16:10', "and you shall keep the feast of weeks to the LORD your God with the measure of the freewill offering of your hand which you shall give, as the LORD your God has blessed you", 'SUPPLIED', "SUPPLIED — 'the measure of the freewill offering of your hand' no seat in Leviticus 23 (the two loaves and the animals there): the tithe admitted for the surplus (137:3); Shavuot's seven days of redress by Deut 16:16's own analogy (musafim by CALL)", cell='musafim.pesach_shavuot', cell_found=FOUND(MU_REDRESS), entry="the cell redress_days (the callee names this chapter); the freewill measure a DATA row"),
    rb('Deut 16:11', "and you shall rejoice before the LORD your God, you and your son and your daughter, your manservant and your maidservant, the Levite in your gates, the sojourner, the fatherless and the widow in your midst, in the place which the LORD your God will choose to make His name dwell there", 'VARIANT', "VARIANT by CALL — 12:18's household (thirteen in order) with the sojourner, the fatherless and the widow added (the four against the four — 138:4-6); the rejoicing chapter 12's STATUS by CALL, REFERENCED not reused (rejoicing_before_the_lord_commanded TWO on Israel UNMOVED); the three commandments of the pilgrimage (138:3)", tape_kind='place_chosen_declared', tape_verse='Deut 12:5', cell='place_name.the_place_chosen', cell_found=FOUND(PN_REJOICE), entry="the tape: place_chosen_declared Deut 12:5 (israel — rejoicing_before_the_lord_commanded's first entry); the cell eat_there_and_rejoice"),
    rb('Deut 16:12', "and you shall remember that you were a slave in Egypt, and you shall keep and do these statutes", 'VERBATIM', "VERBATIM in kind by CALL — 5:15's 'remember that you were a slave' (the book's five seats; 24:18's six in order the closest), the redemption's condition (139:1-2); no write", cell='covenant_at_horeb.the_first_tablet', cell_found=FOUND(CH_KEEP), entry="the cell keep_and_remember (the Sabbath word's memory clause); 15:15's twin"),
    rb('Deut 16:13', "the feast of booths you shall keep seven days, when you gather in from your threshing floor and your winepress", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — the gathering clause new (Leviticus 23:34 dates the feast; Exodus 23:16 and 34:22 the ingathering at the year's end): the vegetables' tithe year (140:6), the booth's ownership (140:4), the roofing (Mishnah Sukkah 1:4); THE LINE writing booths_at_the_place_commanded (a STATUS)", cell='moadim.sukkot', cell_found=FOUND(MO_SUK_LEN), entry="THE WRITE booths_at_the_place_commanded on israel_people at the counter's day; the seven days by CALL (dwells_in_booths the moadim engine's timer UNMOVED); THE PARAMETER the_roofing", write='booths_at_the_place_commanded'),
    rb('Deut 16:14', "and you shall rejoice in your feast, you and your son and your daughter, your manservant and your maidservant, the Levite, the sojourner, the fatherless and the widow in your gates", 'VARIANT', "VARIANT by CALL — 16:11's household verbatim (eleven in order; the nine members identical) with 'in your feast' for 'before the LORD' (the joy's offering — 141:2, Mishnah Chagigah 1:4); the rejoicing chapter 12's and 14's by reference (second_tithe_declared's reuse at 14:26 on the tape)", tape_kind='second_tithe_declared', tape_verse='Deut 14:22', cell='place_name.the_place_chosen', cell_found=FOUND(PN_HOUSE), entry="the tape: second_tithe_declared Deut 14:22 (israel — the rejoicing's second entry); the cell your_households"),
    rb('Deut 16:15', "seven days you shall keep a feast to the LORD your God in the place which the LORD will choose, for the LORD your God will bless you in all your produce and in all the work of your hands, and you shall be altogether joyful", 'SUPPLIED', "SUPPLIED — 'seven days … in the place' the compensation window (142:1 — the whole pilgrimage compensates for the first day, A PARAMETER); 'altogether joyful' the eighth day included (142:7); the place formula's fourth seat in the chapter; the write on 16:13's line", cell='musafim.sukkot', cell_found=FOUND(MU_SUK_DATES), entry="the cell the_dates (Leviticus 23 by call); THE PARAMETER the_compensation_window"),
    rb('Deut 16:16', "three times a year all your males shall appear before the LORD your God in the place which He will choose: at the feast of unleavened bread, at the feast of weeks and at the feast of booths; and none shall appear before the LORD empty", 'VARIANT', "VARIANT WITH ITS WRITE — Exodus 34:23's eight in order and 23:17's seven with the place added and the three names spelled out (2 Chronicles 8:13 the one other); 'three' spelled full; the appearing owed by CALL (calendar); who appears Mishnah Chagigah 1:1; THE LINE three_pilgrimages_declared writing three_pilgrimages_commanded (a STATUS) and empty_appearance_barred (a BLOCK — the clause's third seat)", cell='calendar.pilgrimage', cell_found=FOUND(CA_MALE), entry="THE WRITE three_pilgrimages_commanded on israel_people at the counter's day (empty_appearance_barred on the same line); the able male owes the three appearings by CALL (appearance_owed NONE on the tape UNMOVED)", write='three_pilgrimages_commanded'),
    rb('Deut 16:17', "each man as the gift of his hand, according to the blessing of the LORD your God which He has given you", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — the measure clause new (Exodus 23:15 and 34:20 say 'empty' alone): Mishnah Chagigah 1:5's four cases and 1:2's two amounts (143:8-9 — PARAMETERS); 12:15's 'according to the blessing' six in order; the appearance offering's standing liability by CALL (erection); THE LINE writing empty_appearance_barred (a BLOCK)", cell='erection.repeats', cell_found=FOUND(ER_STAND), entry="THE WRITE empty_appearance_barred on israel_people at the counter's day; the standing liability by CALL (appearance_gift_owed NONE on the tape UNMOVED); THE PARAMETERS the_two_amounts, the_gift_of_the_hand", write='empty_appearance_barred'),
    rb('Deut 16:18', "judges and officers you shall set for yourself in all your gates which the LORD your God gives you, tribe by tribe, and they shall judge the people with righteous judgment", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — the courts in every gate by the tribes a new command (1:16's charge two in order, Exodus 18:21's founding one): the three tiers (144:1-5 — A PARAMETER with Mishnah Sanhedrin 1's sizes by CALL); Exodus 18:25's courts_established and 1:16's judges_charged on the tape the references; THE LINE judges_in_every_gate_commanded writing judges_and_officers_commanded (a STATUS)", tape_kind='judges_charged', tape_verse='Deut 1:16', cell='exodus_story.jethro', cell_found=FOUND(ES_SIZES), entry="THE WRITE judges_and_officers_commanded on israel_people at the counter's day; the tape: judges_charged Deut 1:16 (the court) and courts_established Exod 18:25's line (israel); the sizes by CALL", write='judges_and_officers_commanded'),
    rb('Deut 16:19', "you shall not wrest judgment, you shall not respect persons, and you shall not take a bribe, for the bribe blinds the eyes of the wise and perverts the words of the righteous", 'VARIANT', "VARIANT WITH ITS WRITES — Exodus 23:8's seven in order with 'the wise' for 'the open-eyed' and 'you shall not wrest judgment' (Exodus 23:6, 24:17 the three seats), 'you shall not respect persons' (1:17's clause; Leviticus 19:15's two faces); THE LINE writing judgment_wresting_barred and person_respecting_barred (BLOCKS) and bribe_barred — Exodus 23:8's block, ITS FIRST ENTRY ANYWHERE (DB7's declaration; the ordinances' cell by CALL)", tape_kind='judges_charged', tape_verse='Deut 1:16', cell='ordinances.courts', cell_found=FOUND(OR_ABS), entry="THE WRITES judgment_wresting_barred, person_respecting_barred (new BLOCKS) and bribe_barred (the first entry) on israel_people at the counter's day; the tape: judges_charged Deut 1:16 (the court — 'you shall not respect persons in judgment'); the cells by CALL (ordinances, holiness, second_tablets, opening_speech)", write='bribe_barred'),
    rb('Deut 16:20', "justice, justice you shall pursue, that you may live and inherit the land which the LORD your God gives you", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — the doubled word's one seat: the acquittal final (144:12 — A PARAMETER with Mishnah Sanhedrin 4:1 by CALL); 4:1's 'that you may live' six in order the ground's twin; THE LINE writing justice_pursuit_commanded (a STATUS)", cell='ordinances.courts', cell_found=FOUND(OR_ONE_TWO), entry="THE WRITE justice_pursuit_commanded on israel_people at the counter's day; THE PARAMETER the_acquittal_final (the tilts by CALL)", write='justice_pursuit_commanded'),
    rb('Deut 16:21', "you shall not plant for yourself an asherah of any tree beside the altar of the LORD your God which you shall make for yourself", 'EXPANDED', "EXPANDED WITH ITS WRITE — Exodus 34:13's 'their asherim you shall cut down' (7:5, 12:3 the demolition's kin — nothing shared in order) expanded to the planting beside the altar (145:1-3 the a fortiori; 'any tree' 145:4); Mishnah Avodah Zarah 3:5's reason by CALL (erection); THE LINE asherah_and_pillar_barred writing asherah_beside_the_altar_barred (a BLOCK)", cell='erection.covenant', cell_found=FOUND(ER_MADE), entry="THE WRITE asherah_beside_the_altar_barred on israel_people at the counter's day; the shade and the wood by CALL (seven_nations), the three asherim by CALL (place_name)", write='asherah_beside_the_altar_barred'),
    rb('Deut 16:22', "and you shall not set up for yourself a pillar, which the LORD your God hates", 'SUPPLIED', "SUPPLIED AS A LAW WITH ITS WRITE — the pillar's ban new in Deuteronomy (Leviticus 26:1's 'you shall not raise up a pillar' by CALL through journeys; 12:31's 'hates' two in order): LOVED BY THE FATHERS, HATED BY THE SONS (146:1) — the tape's own entries Jacob's (pillar_anointed on Bethel's twice, pillar_raised on Gilead's once): THE LAW'S REASON A CHANGE OF STATE ON THE TAPE; THE LINE writing pillar_barred (a BLOCK)", cell='journeys.the_command', cell_found=FOUND(JR_THREE), entry="THE WRITE pillar_barred on israel_people at the counter's day; the pillars' entries read from the one database (the_pillars_change_of_state); Leviticus 26:1 by CALL", write='pillar_barred'),
]
RB_GRADES = collections.Counter(r['grade'] for r in READBACK)
print('THE READBACK (printed before it is asserted): rows %d, grades %s, on the tape %d, by CALL %d, supplied %d, with writes %d' % (len(READBACK), dict(RB_GRADES), sum(1 for r in READBACK if r['tape_kind']), sum(1 for r in READBACK if r['cell']), sum(1 for r in READBACK if r['grade'] == 'SUPPLIED'), sum(1 for r in READBACK if r['write'])))
assert len(READBACK) == 22 and [r['verses'] for r in READBACK] == ['Deut 16:%d' % v for v in range(1, 23)] and all(r['cell_found'] for r in READBACK if r['cell']) and not any(r['pointer'] or r['state'] or r['open'] or r['stretch'] for r in READBACK), 'twenty-two rows one per verse, every cell found, no pointer, no state, no open, no stretch row'
HOLES = []      # no hole this chapter in the readback's sense — no act told only here; the code's holes COMPILED (the lines)
OPEN_ROWS = []  # no DISAGREES row — the cooking and six-and-seven resolved by the spine, the two houses' disputes recorded as data with both arms
_EXAM = open(_os.path.join(_ROOT, 'logic', 'oral_triage', 'deu_16_reeh_shoftim_exam_2026-09-23.md'), encoding='utf-8').read()
EXAM_ROWS = re.findall(r'^- Mishnah ([A-Za-z ]+ \d+:\d+) — LAW\.', _EXAM, re.M)
assert EXAM_ROWS == ['Berakhot 1:5', 'Pesachim 3:7', 'Beitzah 1:1', 'Sukkah 1:4', 'Chagigah 1:1', 'Chagigah 1:2', 'Chagigah 1:4', 'Chagigah 1:5'] and 'segments read 0' in _EXAM, EXAM_ROWS   # THE LEAN EXAM'S EIGHT ROWS (the file's own lines), no segment read

# ---- THE DATA ROWS (the eight Mishnah rows' and the spine's; THE PARAMETERS — none in calendar_parameters.yaml this chapter, every one here; the counts printed before they are asserted) ----
PARAMETERS = ['the_intercalation', 'the_passovers_name', 'the_flock_and_the_herd', 'the_night_remembered', 'the_leaven_bans_onset', 'the_bread_of_affliction', 'the_leaven_on_the_road', 'the_two_measures', 'the_party_of_one', 'the_three_phrases', 'the_lodging_night', 'the_six_and_the_seven', 'the_intermediate_days_work', 'the_sickles_three_rules', 'the_reaping_by_night', 'the_freewill_measure', 'the_three_commandments_of_the_pilgrimage', 'the_vegetables_tithe_year', 'the_booths_ownership', 'the_roofing', 'the_compensation_window', 'the_joys_offering', 'the_exempt_from_appearing', 'the_two_amounts', 'the_gift_of_the_hand', 'the_delays_clock', 'the_three_tiers', 'the_acquittal_final', 'the_pillars_change_of_state']   # twenty-nine — the count printed by the runner and asserted at DH4, never in the design
def _p(value, source, arms=None): return {'value': value, 'settings': {'the_source': source, 'a_parameter': True, 'the_arms': arms}}
DATA = {
    'the_readback': {'value': READBACK, 'holes': HOLES, 'open_rows': OPEN_ROWS, 'settings': {'the_form': "THE READBACK'S FORMS ON FILE, NO NEW FORM (THE LOOP.md step 6; THE DEUTERONOMY WALK 14b, 2026-09-23 — LEAN): T4 rows graded against the cells that compile their kin by CALL (twenty-two — every row has kin), T1 reference rows against the tape's lines by kind and first verse; TEN rows SUPPLIED with their writes; no pointer, no state, no open, no stretch, no retrograde row"}},
    'the_counter_and_the_parameters': {'value': CLOCK, 'settings': {'the_day': "the five own-day lines at the counter's day (40, 11, 1) after the tape's last Deuteronomy 15 line (firstling_law_declared) — NO marker, no clock walk, no stretch; no clock datum added (the festivals' dates, the omer's day and the intercalation on file for the count era)"}},
    'the_twin_diffed': {'value': TWIN, 'settings': {'the_ground': "the shared runs on the DB — the reading's kin asserts read again (DH4)"}},
    'the_parsers_eight_and_the_two_ordinals': {'value': {'deut_16_%d' % v: PARSE[v][0] for v in NUMV} | {'the_ordinals': {v: PARSE[v][1] for v in ORDV}, 'the_marks': {v: PARSE[v][2] for v in STARV}}, 'settings': {'the_instrument': "cold_run_sequence.ink_numbers / ink_ordinals (the reading's parser assert)"}},
    'the_intercalation': _p({'the_rows': CLOCK['leap'], 'the_threshold': CLOCK['threshold'], 'the_grounds': CLOCK['grounds'], 'exercised_by': CLOCK['leap_by'], 'the_exodus_eras_aviv': 'OWED — the running tape never intercalates (the debt line)'}, "the Sifrei 127:1; calendar_parameters.yaml intercalated_month, intercalation_grounds, intercalation_threshold_days (Sanhedrin 12b:8, 11b:5, 13a:4) — F1 the_intercalation", ['the_count_era', 'the_exodus_era_owed']),
    'the_passovers_name': _p({'for_its_name': PS_NAME, 'the_four_services': 'slaughter, receiving, carrying, sprinkling take the name; the roasting and the rinsing do not (128:2)'}, "the Sifrei 128:1-2; pesach.paschal_procedure('for_its_sake') by CALL — F1 the_passovers_name"),
    'the_flock_and_the_herd': _p({'flock': 'the Passover', 'herd': 'the festival offering (129:6; Onkelos concurring)', 'the_fourteenths_chagigah': ER_CHAG}, "the Sifrei 129:6; Onkelos 16:2; erection.repeats('chagigah_overnight') by CALL — F1 the_flock_and_the_herd"),
    'the_night_remembered': _p({'ben_zoma': "'all' adds the nights — the exodus mentioned at night", 'the_sages': "'all' adds the days of the Messiah"}, "Mishnah Berakhot 1:5 (the exam row read whole); the Sifrei 130:4 — F1 the_night_remembered", ['the_nights', 'the_days_of_the_messiah']),
    'the_leaven_bans_onset': _p({'the_onset': 'from the sixth hour of the fourteenth — with the Passover\'s slaughter (130:1, R. Judah)', 'the_slaughter_window': MO_WINDOW, 'the_window': CA_MATZAH}, "the Sifrei 130:1; moadim.passover()['slaughter_window'] and pesach.leaven_machine by CALL — F1 the_leaven_bans_onset"),
    'the_bread_of_affliction': _p({'excluded': 'scalded bread and cakes (130:3)'}, "the Sifrei 130:2-3 — F1 the_bread_of_affliction"),
    'the_leaven_on_the_road': _p({'time_to_return': 'return and remove', 'no_time': 'nullify in the heart', 'to_save': 'nullify in the heart', 'optional_residence': 'return at once'}, "Mishnah Pesachim 3:7 (the exam row read whole) — F1 the_leaven_on_the_road", ['return', 'nullify', 'return_at_once']),
    'the_two_measures': _p({'shammai': 'leavening agent an olive, leaven a date', 'hillel': 'both an olive'}, "Mishnah Beitzah 1:1 (the exam row read whole; cited in the spine's Hebrew at 131:3) — F1 the_two_measures", ['shammai', 'hillel']),
    'the_party_of_one': _p({'r_judah': "'for one' the party's size — the Passover for an individual barred", 'the_sages': "'one of your gates' the gate"}, "the Sifrei 132:1 — F1 the_party_of_one (Mishnah Pesachim 8:7 owed)", ['the_party', 'the_gate']),
    'the_three_phrases': _p({'r_akiva': 'at evening slaughter, at sunset eat, until the season of the going out', 'the_other_word': 'the season for the slaughter, the sunset for the roasting, the evening for the eating', 'the_eatings_end': PS_EAT, 'the_slots': ['between_the_evenings', 'sunset', 'night']}, "the Sifrei 133:2; calendar_parameters.yaml day_slots; pesach.paschal_procedure('eating_time') by CALL — F1 the_three_phrases", ['till_morning', 'until_midnight']),
    'the_lodging_night': _p({'the_night': 'the pilgrim lodges the night of the first day at the place (134:2)', 'the_morning': 'the day after the festival he goes to his tents (134:3)'}, "the Sifrei 134:2-3 — F1 the_lodging_night"),
    'the_six_and_the_seven': _p({'the_first_night': 'obligatory (Exodus 12:18)', 'the_rest': 'optional — the seventh went out to teach on the whole (135:1-2)'}, "the Sifrei 135:1-2 (the headless piska) — F1 the_six_and_the_seven"),
    'the_intermediate_days_work': _p({'the_seventh': 'restrained from all work', 'the_sixth': 'not restrained from all work', 'the_sages_table': "'Scripture handed it only to the sages' — which day, which work: EMPTY in the code (Mishnah Moed Katan owed)", 'the_class': MO_WORK7}, "the Sifrei 135:3; moadim.work_class('passover_7') by CALL — F1 the_seventh_days_assembly"),
    'the_sickles_three_rules': _p({'standing': 'that it all be standing', 'first': 'the first of all that is reaped', 'sickle': 'reaped only with a sickle'}, "the Sifrei 136:3 — F2 the_sickles_three_rules (Mishnah Menachot 10:8-9 owed)"),
    'the_reaping_by_night': _p({'reaping_and_counting': 'by night', 'bringing': 'by day', 'omer_day': CLOCK['omer_day'], 'the_morrow': MO_MORROW, 'the_count': MO_COUNT}, "the Sifrei 136:8; moadim.omer() by CALL; omer_day the registry's — F2 the_reaping_by_night"),
    'the_freewill_measure': _p({'the_tithe_admitted': 'as the LORD has blessed you (137:3)'}, "the Sifrei 137:3 — F2 the_freewill_measure"),
    'the_three_commandments_of_the_pilgrimage': _p({'the_three': ['the festival offering', 'the appearance', 'rejoicing']}, "the Sifrei 138:3 (R. Yose the Galilean) — F2 the_three_commandments_of_the_pilgrimage"),
    'the_vegetables_tithe_year': _p({'the_floor_and_the_press': "grow on the past year's water", 'vegetables': 'went out (140:6)'}, "the Sifrei 140:6 — F3 the_gathering (Mishnah Rosh Hashanah 1:1 owed)"),
    'the_booths_ownership': _p({'r_eliezer': "each man's — 'you shall make for yourself'", 'the_sages': "all Israel in one booth — 'all the native-born shall dwell in booths'"}, "the Sifrei 140:4 — F3 the_booths_ownership (Mishnah Sukkah 3 owed)", ['each_mans', 'shared']),
    'the_roofing': _p({'unfit': 'the trellised vine, gourd and ivy unless cut or outnumbered', 'the_principle': 'what is susceptible to impurity or grows not from the ground roofs nothing; what is not susceptible and grows from the ground roofs'}, "Mishnah Sukkah 1:4 (the exam row read whole; cited at 140:3) — F3 the_roofing"),
    'the_compensation_window': _p({'the_window': 'seven days — the whole pilgrimage compensates for the first day (142:1)', 'shavuot': MU_REDRESS}, "the Sifrei 142:1; musafim.pesach_shavuot('redress_days') by CALL — F3 the_compensation (Mishnah Chagigah 1:6 owed)"),
    'the_joys_offering': _p({'israel': 'vows, freewill offerings, the cattle tithe', 'the_priests': 'sin and guilt offerings, the firstborn, the breast and the thigh', 'not': 'birds, meal offerings'}, "Mishnah Chagigah 1:4 (the exam row read whole; cited in the spine's Hebrew at 142:6) — F3 the_joys_offering"),
    'the_exempt_from_appearing': _p({'exempt': ['the deaf-mute', 'the imbecile', 'the minor', 'the tumtum', 'the hermaphrodite', 'women', 'unfreed slaves', 'the lame', 'the blind', 'the sick', 'the old', 'one who cannot ascend on foot'], 'the_minor': {'shammai': "cannot ride on his father's shoulders", 'hillel': "cannot hold his father's hand and ascend — 'three regalim' at the feet"}, 'the_calendars_arms': (CA_WOMAN, CA_LAME, CA_EYE)}, "Mishnah Chagigah 1:1 (the exam row read whole; the Sifrei 143:3-5); calendar.pilgrimage by CALL — F4 who_appears", ['shammai', 'hillel']),
    'the_two_amounts': _p({'shammai': "the appearance two silver, the festival offering a ma'ah", 'hillel': "the appearance a ma'ah, the festival offering two silver", 'the_erections_pair': ER_AMOUNTS}, "Mishnah Chagigah 1:2 (the exam row read whole; the Sifrei 143:8); erection.repeats('appearance_amounts') by CALL — F4 the_two_amounts", ['shammai', 'hillel']),
    'the_gift_of_the_hand': _p({'many_eaters_little_property': 'many peace offerings, few burnt', 'much_property_few_eaters': 'many burnt, few peace', 'both_few': "the ma'ah and the two silver", 'both_many': "each man as the gift of his hand"}, "Mishnah Chagigah 1:5 (the exam row read whole; cited in the spine's Hebrew at 143:9) — F4 the_gift_of_the_hand"),
    'the_delays_clock': _p({'the_clock': 'three feasts in order from the vow (143:7 — 23:22 ahead)', 'the_case': '2 Chronicles 8:13 the one other verse with the three names in order'}, "the Sifrei 143:7 — F4 the_order_of_the_names (Mishnah Rosh Hashanah 1:1 owed)"),
    'the_three_tiers': _p({'for_all_israel': ES_SIZES[0], 'the_tribe_and_the_city': ES_SIZES[1], 'money': 3, 'the_small_as_the_great': 'judges and executes (144:5)'}, "the Sifrei 144:1-5; exodus_story.jethro('sanhedrin_sizes') and ordinances.courts('twenty_three') by CALL — F5 the_three_tiers"),
    'the_acquittal_final': _p({'the_rule': 'one who left the court acquitted is not returned to conviction (144:12)', 'the_tilts': OR_ONE_TWO, 'the_asymmetry': OR_ASYM}, "the Sifrei 144:12; ordinances.courts('one_vs_two', 'asymmetry') by CALL (Mishnah Sanhedrin 4:1) — F5 justice_justice"),
    'the_pillars_change_of_state': _p({'loved_by_the_fathers': {'pillar_anointed': PILLAR_SCAN[0], 'pillar_raised': PILLAR_SCAN[1]}, 'hated_by_the_sons': 'Deut 16:22 — the block at this verse', 'the_reason': 'a change of state on the tape (146:1)'}, "the Sifrei 146:1; the one database's entries on Jacob's pillars — F6 the_pillar_hated"),
}
assert all(p in DATA for p in PARAMETERS) and len(PARAMETERS) == 29 and len(DATA) == 33, (len(PARAMETERS), len(DATA))
ASK_LABELS = {
    'the_intercalation': "the Sifrei 127:1; the registry's intercalation rows (the count era)", 'the_passovers_name': "the Sifrei 128:1-2; pesach by CALL", 'the_flock_and_the_herd': "the Sifrei 129:6; Onkelos; erection by CALL", 'the_night_remembered': "MISHNAH BERAKHOT 1:5 — the exam row; the Sifrei 130:4", 'the_leaven_bans_onset': "THE WRITE leaven_with_the_passover_barred; the Sifrei 130:1; moadim by CALL", 'the_bread_of_affliction': "the Sifrei 130:3", 'the_leaven_on_the_road': "MISHNAH PESACHIM 3:7 — the exam row; pesach by CALL", 'the_two_measures': "MISHNAH BEITZAH 1:1 — the exam row; the Sifrei 131:3", 'the_nights_flesh': "THE WRITE flesh_till_morning_barred; the Sifrei 131:4-5; pesach and erection by CALL", 'the_gates_bar': "THE WRITE passover_in_the_gates_barred; the Sifrei 132:1, 147:2; place_name by CALL", 'the_party_of_one': "the Sifrei 132:1 — a dispute", 'the_place': "THE WRITE passover_at_the_place_commanded; the Sifrei 129:1-5; place_name by CALL", 'the_three_phrases': "the Sifrei 133:2; the calendar's slots; pesach by CALL", 'the_cooking': "the Sifrei 134:1; 2 Chronicles 35:13; pesach by CALL", 'the_lodging_night': "the Sifrei 134:2-3", 'the_six_and_the_seven': "the Sifrei 135:1-2 (the headless piska)", 'the_seventh_days_assembly': "THE WRITE seventh_day_assembly_commanded; the Sifrei 135:3; moadim and musafim by CALL",
    'the_sickles_three_rules': "the Sifrei 136:3; moadim by CALL", 'the_reaping_by_night': "THE WRITE weeks_at_the_place_commanded; the Sifrei 136:8; omer_day the registry's", 'the_freewill_measure': "the Sifrei 137:3", 'the_three_commandments_of_the_pilgrimage': "the Sifrei 138:3", 'the_rejoicing_and_the_household': "the Sifrei 138:4-6; place_name by CALL", 'the_slave_remembered': "the Sifrei 139:1-2; covenant_at_horeb by CALL",
    'the_gathering': "the Sifrei 140:6", 'the_booths_ownership': "the Sifrei 140:4 — a dispute", 'the_roofing': "MISHNAH SUKKAH 1:4 — the exam row", 'the_seven_days': "THE WRITE booths_at_the_place_commanded; the Sifrei 142:1-5; moadim and musafim by CALL", 'the_compensation': "the Sifrei 142:1; musafim by CALL", 'the_joys_offering': "MISHNAH CHAGIGAH 1:4 — the exam row; the Sifrei 141:2, 142:6", 'altogether_joyful': "the Sifrei 142:7",
    'the_three_times': "THE WRITE three_pilgrimages_commanded; the Sifrei 143:1-2; calendar by CALL", 'who_appears': "MISHNAH CHAGIGAH 1:1 — the exam row; the Sifrei 143:3-5; calendar by CALL", 'the_order_of_the_names': "the Sifrei 143:7; 2 Chronicles 8:13", 'not_empty': "THE WRITE empty_appearance_barred; the Sifrei 143:8; erection by CALL", 'the_two_amounts': "MISHNAH CHAGIGAH 1:2 — the exam row; erection by CALL", 'the_gift_of_the_hand': "MISHNAH CHAGIGAH 1:5 — the exam row; the Sifrei 143:9", 'the_guard_of_the_land': "the Sifrei 52:4 (the outside row); erection by CALL",
    'the_court_for_all_israel': "THE WRITE judges_and_officers_commanded; the Sifrei 144:1; exodus_story by CALL", 'the_three_tiers': "the Sifrei 144:2-5; ordinances and opening_speech by CALL", 'the_qualified_judge': "the Sifrei 144:6-11; opening_speech by CALL", 'wrest_no_judgment': "THE WRITE judgment_wresting_barred; the Sifrei 144:8, 281:1; ordinances and holiness by CALL", 'respect_no_person': "THE WRITE person_respecting_barred; the Sifrei 144:9-10; opening_speech, second_tablets and holiness by CALL", 'take_no_bribe': "THE WRITE bribe_barred (its first entry); the Sifrei 144:11; ordinances, second_tablets and holiness by CALL", 'justice_justice': "THE WRITE justice_pursuit_commanded; the Sifrei 144:12; ordinances by CALL (Mishnah Sanhedrin 4:1)", 'that_you_may_live': "the Sifrei 144:13",
    'the_asherah_beside_the_altar': "THE WRITE asherah_beside_the_altar_barred; the Sifrei 145:1-3; erection, seven_nations and place_name by CALL", 'any_tree': "the Sifrei 145:4", 'the_pillar_hated': "THE WRITE pillar_barred; the Sifrei 146:1; the tape's own entries; journeys by CALL",
    'the_table': "the readback's forms on file", 'the_supplied_rows': "the readback's supplied rows", 'no_pointer_no_state_no_open': "the register empty on the chapter", 'the_twin_diffed': "the DB's shared runs", 'no_retrograde_row': "THE LOOP step 6's retelling rules",
}


# =====================================================================
# Motion 3 — THE WRAP: the daemon law_festivals_judges (given_at Deut 16:1, installed_by boot — the Deuteronomy daemons' form)
# =====================================================================
def law_festivals_judges(event, world):
    """Deut 16:1-22 (cold_run_festivals_judges.py F1-F6 and the table). given_at Deut 16:1 — 'observe the month of Aviv and keep the Passover', the chapter's first
    verse at the counter's day (40, 11, 1); installed_by boot (the Deuteronomy daemons' form; THE INSTALL HYPOTHESIS on the table). FIVE TAPE LINES of its own, all
    OWN-DAY, NO marker: passover_at_the_place_declared (16:1-8 — two STATUSES, three BLOCKS), weeks_and_booths_declared (16:9-15 — two STATUSES),
    three_pilgrimages_declared (16:16-17 — a STATUS, a BLOCK), judges_in_every_gate_commanded (16:18-20 — two STATUSES, two BLOCKS, bribe_barred REUSED — its first
    entry anywhere), asherah_and_pillar_barred (16:21-22 — two BLOCKS). LITERAL effects per kind (an unnamed effect is a KeyError); no case kind (the lean form — no
    bench scene); no timer on the tape (the festivals' timers the moadim engine's on its case world); no close; the kin's effects UNMOVED (DH4)."""
    k, src = event['kind'], event['case_source']
    E_ = lambda eff, s, cp=None, amount=None, due=None, law='', value=None: {'effect': eff, 'subject': s, 'counterparty': cp, 'amount': amount, 'due': due, 'value': value if value is not None else True, 'source_law': law, 'case_source': src}
    if k == 'passover_at_the_place_declared':
        return [E_('passover_at_the_place_commanded', 'israel_people', value={'the_word': "you shall sacrifice the Passover … in the place which the LORD will choose (16:2, 6-7)", 'the_place': "chapter 12's formula at six seats — the chapter's addition (place_chosen_required UNMOVED, by CALL)", 'the_name': "for the name of the Passover (128:1-2 — pesach by CALL)", 'the_three_phrases': "the slaughter at evening, the roasting at sunset, the eating by night — a DATA row on the calendar's slots (133:2)", 'the_cooking_and_the_lodging': "cooking is roasting (134:1); the night's lodging (134:2-3)", 'the_intercalation': "A PARAMETER — the registry's rows for the count era; the exodus era's Aviv OWED (127:1)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F1 [INK 16:2, 16:6-7 'in the place which the LORD will choose' — THE PASSOVER AT THE PLACE compiled at THE DEUTERONOMY WALK 14b (LEAN); the Sifrei 127-129, 132-134]"),
                E_('passover_in_the_gates_barred', 'israel_people', value={'the_word': "you may not sacrifice the Passover within any of your gates (16:5)", 'the_block': "one of the three true prohibitions (147:2); 'for one' the party's size a dispute (132:1)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F1 [INK 16:5 'you may not sacrifice the Passover within one of your gates' — compiled at THE DEUTERONOMY WALK 14b; the Sifrei 132:1, 147:2]"),
                E_('leaven_with_the_passover_barred', 'israel_people', value={'the_word': "you shall not eat leaven with it (16:3); no leavening agent shall be seen with you in all your border seven days (16:4)", 'the_onset': "from the sixth hour of the fourteenth — with the slaughter (130:1; the moadim engine's window after_midday by CALL)", 'the_two_measures': "Shammai an olive and a date, Hillel an olive — Mishnah Beitzah 1:1 (131:3), a DATA row", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F1 [INK 16:3 'you shall not eat leaven with it' — THE LEAVEN'S SIXTH HOUR compiled at THE DEUTERONOMY WALK 14b; the Sifrei 130:1-131:3; Mishnah Beitzah 1:1, Pesachim 3:7, Berakhot 1:5]"),
                E_('flesh_till_morning_barred', 'israel_people', value={'the_word': "nor shall any of the flesh … remain all night until the morning (16:4)", 'the_block': "Exodus 12:10's and 34:25's twins; the remainder burned on the sixteenth (pesach by CALL); all night on the altar (erection by CALL)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F1 [INK 16:4 'nor shall any of the flesh remain until the morning' — compiled at THE DEUTERONOMY WALK 14b; the Sifrei 131:4-5]"),
                E_('seventh_day_assembly_commanded', 'israel_people', value={'the_word': "six days you shall eat unleavened bread, and on the seventh day a solemn assembly to the LORD your God: you shall do no work (16:8)", 'six_and_seven': "the seventh's unleavened bread optional, so all but the first night (135:1-2) — a DATA row", 'the_intermediate_days': "A PARAMETER — 'Scripture handed it only to the sages' (135:3); the seventh's class servile_only by CALL (moadim.work_class)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F1 [INK 16:8 'on the seventh day a solemn assembly' — THE SEVENTH DAY'S ASSEMBLY AND THE SAGES' TABLE compiled at THE DEUTERONOMY WALK 14b; the Sifrei 135:1-3 (the headless piska)]")]
    if k == 'weeks_and_booths_declared':
        return [E_('weeks_at_the_place_commanded', 'israel_people', value={'the_word': "seven weeks you shall count for yourself from the time the sickle is first put to the standing grain … and you shall keep the feast of weeks … and you shall rejoice before the LORD your God … in the place (16:9-11)", 'the_count': "reaping and counting by night, bringing by day (136:8); the morrow the festival, forty-nine by CALL (moadim.omer — counts_omer the engine's timer UNMOVED); omer_day 1/16 the registry's", 'the_three_rules': "standing, first, sickle (136:3)", 'the_measure_and_the_joy': "the freewill measure (137:3); the three commandments of the pilgrimage (138:3); the household by CALL (place_name — rejoicing_before_the_lord_commanded UNMOVED)", 'the_slave_remembered': "5:15 verbatim in kind by CALL (covenant_at_horeb)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F2 [INK 16:9-11 'seven weeks you shall count … the feast of weeks … in the place' — THE WEEKS FROM THE SICKLE compiled at THE DEUTERONOMY WALK 14b; the Sifrei 136-139]"),
                E_('booths_at_the_place_commanded', 'israel_people', value={'the_word': "the feast of booths you shall keep seven days when you gather in … seven days you shall keep a feast to the LORD your God in the place (16:13-15)", 'the_seven_days': "Leviticus 23's by CALL (moadim.sukkot — dwells_in_booths the engine's timer UNMOVED; musafim the dates)", 'the_roofing': "A PARAMETER — Mishnah Sukkah 1:4", 'the_compensation': "A PARAMETER — the whole pilgrimage compensates for the first day (142:1)", 'the_joys_offering': "vows and freewill offerings serve, birds and meal offerings not — Mishnah Chagigah 1:4 (141:2, 142:6), a DATA row", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F3 [INK 16:13-15 'the feast of booths … seven days … in the place' — THE BOOTHS AT THE PLACE compiled at THE DEUTERONOMY WALK 14b; the Sifrei 140-142]")]
    if k == 'three_pilgrimages_declared':
        return [E_('three_pilgrimages_commanded', 'israel_people', value={'the_word': "three times a year all your males shall appear before the LORD your God in the place which He will choose (16:16)", 'the_appearing': "the able male owes the three appearings by CALL (calendar.pilgrimage — appearance_owed NONE on the tape UNMOVED)", 'who_appears': "A PARAMETER — Mishnah Chagigah 1:1's twelve exempt, the minor two houses", 'the_order_of_the_names': "the delay's clock (143:7); 2 Chronicles 8:13 the run's case", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F4 [INK 16:16 'three times a year all your males shall appear' — THE THREE PILGRIMAGES AT THE PLACE compiled at THE DEUTERONOMY WALK 14b; the Sifrei 143:1-7, 52:4; Mishnah Chagigah 1:1]"),
                E_('empty_appearance_barred', 'israel_people', value={'the_word': "and none shall appear before the LORD empty; each man as the gift of his hand (16:16-17)", 'the_block': "the clause's third seat (Exodus 23:15, 34:20); the standing liability by CALL (erection — appearance_gift_owed NONE on the tape UNMOVED)", 'the_two_amounts_and_the_gift': "PARAMETERS — Mishnah Chagigah 1:2 (Shammai / Hillel) and 1:5 (the four cases)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F4 [INK 16:16-17 'none shall appear before the LORD empty; each man as the gift of his hand' — compiled at THE DEUTERONOMY WALK 14b; the Sifrei 143:8-9; Mishnah Chagigah 1:2, 1:5]")]
    if k == 'judges_in_every_gate_commanded':
        return [E_('judges_and_officers_commanded', 'israel_people', value={'the_word': "judges and officers you shall set for yourself in all your gates … tribe by tribe, and they shall judge the people with righteous judgment (16:18)", 'the_three_tiers': "A PARAMETER — the court for all Israel, the tribe's, the city's; the small as the great (144:1-5); the sizes by CALL (exodus_story, ordinances)", 'the_references': "courts_established (Exodus 18:25's line) and judges_charged (1:16's) on the tape — never a second write", 'the_qualified_judge': "the fit appointed; the appointer for wealth as if he planted an asherah (144:6-11)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F5 [INK 16:18 'judges and officers you shall set for yourself in all your gates' — THE COURTS IN EVERY GATE compiled at THE DEUTERONOMY WALK 14b; the Sifrei 144:1-11]"),
                E_('judgment_wresting_barred', 'israel_people', value={'the_word': "you shall not wrest judgment (16:19)", 'the_block': "Exodus 23:6's and 24:17's twins (281:1); Leviticus 19:15's five effects by CALL (holiness)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F5 [INK 16:19 'you shall not wrest judgment' — compiled at THE DEUTERONOMY WALK 14b; the Sifrei 144:8, 281:1]"),
                E_('person_respecting_barred', 'israel_people', value={'the_word': "you shall not respect persons (16:19)", 'the_block': "the judge who seats one and stands the other (144:9); 1:17's clause by CALL (opening_speech); Leviticus 19:15's two faces by CALL (holiness)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F5 [INK 16:19 'you shall not respect persons' — compiled at THE DEUTERONOMY WALK 14b; the Sifrei 144:9-10]"),
                E_('bribe_barred', 'israel_people', value={'the_word': "and you shall not take a bribe, for the bribe blinds the eyes of the wise and perverts the words of the righteous (16:19)", 'the_reuse': "Exodus 23:8's BLOCK declared at the ordinances' cell and NEVER WRITTEN on any entity (DB7) — ITS FIRST ENTRY here at the chapter's own day (DB7's 'NEVER' 0 -> 1 retyped before the tape)", 'even_to_judge_truly': "the Mekhilta (ordinances by CALL); the permitted fee for evident loss (second_tablets by CALL); the bribed judge's eyes dim (holiness by CALL)", 'the_day': "the counter's own (40, 11, 1) — on the same line"}, law="F5 [INK 16:19 'and you shall not take a bribe' — THE BRIBE'S BLOCK WRITTEN FOR THE FIRST TIME at THE DEUTERONOMY WALK 14b; the Sifrei 144:11; Exodus 23:8]"),
                E_('justice_pursuit_commanded', 'israel_people', value={'the_word': "justice, justice you shall pursue, that you may live and inherit the land (16:20)", 'the_acquittal_final': "A PARAMETER — one who left the court acquitted is not returned to conviction (144:12); the tilts by CALL (ordinances — Mishnah Sanhedrin 4:1)", 'the_ground': "fit judges keep Israel alive and settled on their land (144:13)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F5 [INK 16:20 'justice, justice you shall pursue' — THE ACQUITTAL FINAL compiled at THE DEUTERONOMY WALK 14b; the Sifrei 144:12-13]")]
    if k == 'asherah_and_pillar_barred':
        return [E_('asherah_beside_the_altar_barred', 'israel_people', value={'the_word': "you shall not plant for yourself an asherah of any tree beside the altar of the LORD your God (16:21)", 'the_block': "the planting barred and the a fortiori (145:1-3); 'any tree' even a wooden house (145:4); a hand made it (Mishnah Avodah Zarah 3:5 — erection by CALL); the shade and the wood (seven_nations by CALL); the three asherim (place_name by CALL)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F6 [INK 16:21 'you shall not plant for yourself an asherah … beside the altar' — compiled at THE DEUTERONOMY WALK 14b; the Sifrei 145:1-4]"),
                E_('pillar_barred', 'israel_people', value={'the_word': "and you shall not set up for yourself a pillar, which the LORD your God hates (16:22)", 'loved_by_the_fathers': "the tape's own entries — pillar_anointed on the pillar of Bethel twice, pillar_raised on the pillar of Gilead once, Jacob's (146:1)", 'hated_by_the_sons': "the block at this verse — THE LAW'S REASON A CHANGE OF STATE ON THE TAPE; Leviticus 26:1 by CALL (journeys)", 'the_day': "the counter's own (40, 11, 1) — no marker"}, law="F6 [INK 16:22 'you shall not set up for yourself a pillar, which the LORD your God hates' — THE PILLAR HATED compiled at THE DEUTERONOMY WALK 14b; the Sifrei 146:1]")]
    return []


LINES = [
    ('Deut 16:1-8 — observe the month of Aviv and keep the Passover to the LORD your God, for in the month of Aviv the LORD your God brought you out of Egypt by night; and you shall sacrifice the Passover to the LORD your God, flock and herd, in the place which the LORD will choose to make His name dwell there; you shall eat no leaven with it; seven days you shall eat unleavened bread with it, the bread of affliction … no leaven shall be seen with you in all your border seven days, nor shall any of the flesh which you sacrifice the first day at evening remain all night until the morning; you may not sacrifice the Passover within any of your gates … but at the place … at evening, at the going down of the sun, the season of your going out of Egypt; and you shall cook it and eat it in the place … and in the morning you shall turn and go to your tents; six days you shall eat unleavened bread, and on the seventh day a solemn assembly to the LORD your God: you shall do no work',),
    ('Deut 16:9-15 — seven weeks you shall count for yourself: from the time the sickle is first put to the standing grain you shall begin to count seven weeks; and you shall keep the feast of weeks to the LORD your God with the measure of the freewill offering of your hand … and you shall rejoice before the LORD your God, you and your son and your daughter, your manservant and your maidservant, the Levite in your gates, the sojourner, the fatherless and the widow in your midst, in the place … and you shall remember that you were a slave in Egypt; the feast of booths you shall keep seven days, when you gather in from your threshing floor and your winepress; and you shall rejoice in your feast … seven days you shall keep a feast to the LORD your God in the place which the LORD will choose, for the LORD your God will bless you in all your produce and in all the work of your hands, and you shall be altogether joyful',),
    ('Deut 16:16-17 — three times a year all your males shall appear before the LORD your God in the place which He will choose: at the feast of unleavened bread, at the feast of weeks and at the feast of booths; and none shall appear before the LORD empty; each man as the gift of his hand, according to the blessing of the LORD your God which He has given you',),
    ('Deut 16:18-20 — judges and officers you shall set for yourself in all your gates which the LORD your God gives you, tribe by tribe, and they shall judge the people with righteous judgment; you shall not wrest judgment, you shall not respect persons, and you shall not take a bribe, for the bribe blinds the eyes of the wise and perverts the words of the righteous; justice, justice you shall pursue, that you may live and inherit the land which the LORD your God gives you',),
    ('Deut 16:21-22 — you shall not plant for yourself an asherah of any tree beside the altar of the LORD your God which you shall make for yourself; and you shall not set up for yourself a pillar, which the LORD your God hates',),
]
CLOSES = "none — no close this chapter on the tape: the eight new blocks (passover_in_the_gates_barred, leaven_with_the_passover_barred, flesh_till_morning_barred, empty_appearance_barred, judgment_wresting_barred, person_respecting_barred, asherah_beside_the_altar_barred, pillar_barred), the seven new statuses (passover_at_the_place_commanded, seventh_day_assembly_commanded, weeks_at_the_place_commanded, booths_at_the_place_commanded, three_pilgrimages_commanded, judges_and_officers_commanded, justice_pursuit_commanded) and the bribe's first entry have no closer; no debit; the kin's effects unmoved (place_chosen_required, rejoicing_before_the_lord_commanded, holy_things_in_the_gates_barred, courts_established, judges_charged, appearance_owed, appearance_gift_owed, counts_omer, dwells_in_booths, burn_remainder, judgment_perverted, the pillars' entries — the readback references, no second write); no case kind, no bench scene (the lean form)"


def narrative():
    """THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): the chapter's own laws AS HISTORY — FIVE own-day lines with no marker (passover_at_the_place_declared,
    weeks_and_booths_declared, three_pilgrimages_declared, judges_in_every_gate_commanded, asherah_and_pillar_barred at the counter's day (40, 11, 1)) on a world with
    this runner's daemon: 16 writes (all on Israel — fifteen new, the bribe's first), no timer, ONE entity (Israel — the written-on party; a line's subject makes no
    entity, 7b's lesson), the counter at (11, 1), no close, no row, no dated line. Recorded by the sequential run's recorder and stitched onto the tape after the
    last Deuteronomy 15 line. Not a graded cell: the tuple below is a tripwire typed from the design (the writes' count READ from this print — the design's sixteen a prediction)."""
    with contextlib.redirect_stdout(io.StringIO()):
        w = WE.World(era='Deut 16:1-22 on the tape — the Passover at the place, the weeks and the booths, the three pilgrimages, the judges in every gate, the asherah and the pillar at the counter\'s own day, no marker (the exodus epoch)', epoch='exodus')
        w.laws = [law_festivals_judges]
        w.advance(w.clock.day_in('exodus', 40, 11, 1))
        # THE DAEMON GATE READS LITERAL SUBMITS ONLY — the five lines typed out; no marker; no field named `until`, `days` or `due`
        w.submit({'kind': 'passover_at_the_place_declared', 'subject': 'israel', 'the_month': 'observe the month of Aviv and keep the Passover (16:1) — the intercalation a parameter', 'the_place': 'sacrifice the Passover, flock and herd, in the place (16:2) — the herd the festival offering; the place the chapter\'s addition', 'the_leaven': 'no leaven with it; seven days unleavened bread, the bread of affliction (16:3) — the ban from the sixth hour; the two measures', 'the_night': 'no leavening agent seen seven days; none of the flesh till morning (16:4)', 'the_gates': 'you may not sacrifice the Passover within your gates (16:5) — one of the three true prohibitions', 'the_clock': 'at evening, at the going down of the sun, the season of your going out (16:6) — the three phrases', 'the_morning': 'cook it and eat it there; in the morning turn to your tents (16:7) — cooking is roasting; the lodging night', 'the_seventh': 'six days unleavened bread; on the seventh a solemn assembly, no work (16:8) — the intermediate days the sages\' table', 'case_source': LINES[0][0]})
        w.submit({'kind': 'weeks_and_booths_declared', 'subject': 'israel', 'the_sickle': 'seven weeks from the sickle\'s first cut on the standing grain (16:9) — reaping and counting by night', 'the_feast_of_weeks': 'the feast of weeks with the measure of your hand\'s freewill gift (16:10)', 'the_rejoicing': 'rejoice before the LORD with the household at the place (16:11) — chapter 12\'s law by call', 'the_slave_remembered': 'remember that you were a slave in Egypt (16:12) — 5:15 verbatim in kind', 'the_booths': 'the feast of booths seven days (16:13) — the roofing the answer sheet\'s', 'the_gathering': 'when you gather in from your threshing floor and your winepress (16:13) — the vegetables out', 'the_seven_days': 'seven days at the place; altogether joyful (16:15) — the compensation window', 'case_source': LINES[1][0]})
        w.submit({'kind': 'three_pilgrimages_declared', 'subject': 'israel', 'the_three_times': 'three times a year at the place — unleavened bread, weeks, booths (16:16) — the order the delay\'s clock', 'the_males': 'all your males shall appear (16:16) — Chagigah 1:1\'s exempt', 'the_empty': 'none shall appear empty (16:16) — the appearance offering; the two amounts', 'the_gift_of_the_hand': 'each man as the gift of his hand, according to the blessing (16:17) — the four cases', 'case_source': LINES[2][0]})
        w.submit({'kind': 'judges_in_every_gate_commanded', 'subject': 'israel', 'the_judges_and_officers': 'judges and officers you shall set for yourself (16:18) — the court for all Israel', 'the_gates_and_the_tribes': 'in all your gates, tribe by tribe (16:18) — the three tiers', 'the_wresting': 'you shall not wrest judgment (16:19)', 'the_faces': 'you shall not respect persons (16:19)', 'the_bribe': 'you shall not take a bribe (16:19) — Exodus 23:8\'s block written for the first time', 'the_justice': 'justice, justice you shall pursue, that you may live and inherit (16:20) — the acquittal final', 'case_source': LINES[3][0]})
        w.submit({'kind': 'asherah_and_pillar_barred', 'subject': 'israel', 'the_asherah': 'no asherah of any tree beside the altar (16:21) — the a fortiori', 'the_pillar': 'no pillar, which the LORD your God hates (16:22) — loved by the fathers, hated by the sons', 'case_source': LINES[4][0]})
    writes = len([l for l in w.log if l[0] == 'WRITE'])
    closes = len([e for ent in w.entities.values() for e in ent.ledger if e.get('closed_by')])
    rows = len([l for l in w.log if l[0] == 'ROW'])
    dated = len([l for l in w.log if l[0] == 'EVENT' and l[2].get('dated') is not None])
    return (writes, len([l for l in w.log if l[0] == 'TIMER-SET']), len(w.entities), w.clock.eras['exodus'].date(w.clock.day)[1:], closes, rows, len(w.tables['population']), dated), w


NARRATIVE, _WN = narrative()
print('THE NARRATIVE (printed before it is asserted):', NARRATIVE, [e['effect'] for e in _WN.entity('israel_people').ledger])
NARRATIVE_PREDICTED = (16, 0, 1, (11, 1), 0, 0, 0, 0)   # DEUTERONOMY_WALK.md "Sitting 14b": 16 writes (the design's sixteen a prediction — READ FROM THE PRINT), no timer, ONE entity (Israel — the written-on party), the counter's day (11, 1), no close, no row, no population row, no dated line
assert NARRATIVE == NARRATIVE_PREDICTED, ('THE DEUTERONOMY WALK 14b: the chapter\'s narrative moved from its prediction', NARRATIVE, NARRATIVE_PREDICTED)
_is = _WN.entity('israel_people').ledger
assert [e['effect'] for e in _is] == ['passover_at_the_place_commanded', 'passover_in_the_gates_barred', 'leaven_with_the_passover_barred', 'flesh_till_morning_barred', 'seventh_day_assembly_commanded', 'weeks_at_the_place_commanded', 'booths_at_the_place_commanded', 'three_pilgrimages_commanded', 'empty_appearance_barred', 'judges_and_officers_commanded', 'judgment_wresting_barred', 'person_respecting_barred', 'bribe_barred', 'justice_pursuit_commanded', 'asherah_beside_the_altar_barred', 'pillar_barred'] and all(e.get('dated') is None for e in _is), [(e['effect'], e.get('dated')) for e in _is]   # the sixteen on Israel at the counter's day — fifteen new, the bribe's first
_ev = [l for l in _WN.log if l[0] == 'EVENT']
assert [l[2]['kind'] for l in _ev] == ['passover_at_the_place_declared', 'weeks_and_booths_declared', 'three_pilgrimages_declared', 'judges_in_every_gate_commanded', 'asherah_and_pillar_barred'] and all(l[2].get('dated') is None for l in _ev) and not [l for l in _WN.log if l[0] == 'MARKER'], [(l[2]['kind'], l[2].get('dated')) for l in _ev]
