# THE ONKELOS ROWS of Deuteronomy 16:1-11 (THE DEUTERONOMY WALK sitting 14 — CHAPTER 16, LEAN, 2026-09-23): the month of Aviv and the night, the Passover at
# the place, the leaven and the bread of affliction, the leaven out of sight and the night's flesh, not in your gates, the evening at the place, the cooking
# and the morning, six days and the seventh, the weeks from the sickle, the feast of weeks, the rejoicing. The Aramaic and the Hebrew CUT by consonants in
# GLOSSED PIECES of at most seven tokens (ch16_ink.HP / AP — the lint's ninety-character window). The export's chapter 16 = the DB's (twenty-two rows, the
# identity — asserted). EVERY ROW READ WHOLE (the whole-row rule; ch16_onkelos.txt). Chapter 15's form (ch15_rows_onkelos_a.py).
from ch16_ink import *
R = {}
def row(c, v, verdict, prose): R[(c, v)] = (verdict, prose)

row(16, 1, 'MATERIAL', f'OBSERVE THE MONTH OF AVIV AND KEEP THE PASSOVER TO THE LORD YOUR GOD, FOR IN THE MONTH OF AVIV THE LORD YOUR GOD BROUGHT YOU OUT OF EGYPT BY NIGHT. {HP(16, 1, (("שמור", "את", "חדש", "האביב"), "observe the month of Aviv — the Bible\'s three seats; the infinitive absolute the chapter\'s first word"), (("הוציאך", "יהוה", "אלהיך", "ממצרים", "לילה"), "the LORD your God brought you out of Egypt by night"))} {AP(16, 1, (("טר", "ית", "ירחא", "דאביבא"), "keep the month of Aviv"), (("ועבד", "לך", "נסין", "בליליא"), "AND HE DID MIRACLES FOR YOU BY NIGHT — the addition, one seat in the book"))} THE NIGHT: 128:5\'s redemption by night and exodus by day; 127:1-3\'s intercalation from \'observe\'. Fresh.')
row(16, 2, 'MATERIAL', f'AND YOU SHALL SACRIFICE THE PASSOVER TO THE LORD YOUR GOD, FLOCK AND HERD, IN THE PLACE WHICH THE LORD WILL CHOOSE TO MAKE HIS NAME DWELL THERE. {HP(16, 2, (("וזבחת", "פסח", "ליהוה", "אלהיך", "צאן", "ובקר"), "and you shall sacrifice the Passover to the LORD your God, flock and herd"), (("במקום", "אשר", "יבחר", "יהוה", "לשכן", "שמו", "שם"), "in the place which the LORD will choose to make His name dwell there — the first of six"))} {AP(16, 2, (("מן", "בני", "ענא", "ונכסת", "קודשיא", "מן", "תורי"), "FROM THE SONS OF THE FLOCK, AND THE HOLY SLAUGHTERINGS FROM THE OXEN — the law written: the herd the festival offering"), (("לאשראה", "שכנתיה", "תמן"), "to make His Shekhinah dwell there"))} THE HERD: 129:6\'s chagigah; 129:7\'s Shiloh and the Abode; 128:1 / 129:1\'s name. Fresh.')
row(16, 3, 'MATERIAL', f'YOU SHALL EAT NO LEAVEN WITH IT; SEVEN DAYS YOU SHALL EAT UNLEAVENED BREAD WITH IT, THE BREAD OF AFFLICTION — FOR IN HASTE YOU WENT OUT OF THE LAND OF EGYPT — THAT YOU MAY REMEMBER THE DAY OF YOUR GOING OUT ALL THE DAYS OF YOUR LIFE. {HP(16, 3, (("לא", "תאכל", "עליו", "חמץ"), "you shall eat no leaven with it"), (("מצות", "לחם", "עני"), "unleavened bread, the bread of affliction — one seat"), (("כי", "בחפזון", "יצאת"), "for in haste you went out — three in the Bible"), (("כל", "ימי", "חייך"), "all the days of your life"))} {AP(16, 3, (("לא", "תיכול", "עלוהי", "חמיע"), "you shall not eat leaven on it"), (("פטיר", "לחם", "עני"), "unleavened, bread of affliction — the noun kept"), (("בבהילו", "נפקתא"), "in haste you went out"))} THE BREAD: 130:1-2\'s onset dispute; 130:3-4\'s kinds; 130:6\'s haste Egypt\'s; 130:7\'s nights. Fresh.')
row(16, 4, 'MATERIAL', f'NO LEAVEN SHALL BE SEEN TO YOU IN ALL YOUR BORDER SEVEN DAYS, AND NONE OF THE FLESH YOU SACRIFICE AT EVENING ON THE FIRST DAY SHALL REMAIN OVERNIGHT UNTIL MORNING. {HP(16, 4, (("ולא", "יראה", "לך", "שאר", "בכל", "גבלך"), "no leaven shall be seen to you in all your border — Exodus 13:7\'s six words"), (("ולא", "ילין", "מן", "הבשר"), "and none of the flesh shall remain overnight — Exodus 34:25\'s clause"), (("ביום", "הראשון", "לבקר"), "on the first day until morning — the ordinal [1]"))} {AP(16, 4, (("ולא", "יתחזי", "לך", "חמיר"), "and no SOURDOUGH shall be seen to you — the word\'s one seat"), (("ולא", "יבית", "מן", "בסרא"), "and none of the flesh shall pass the night"))} THE LEAVEN: 131:1\'s three exclusions; 131:2\'s nullifying; 131:3\'s two measures; 131:4-5\'s Passover and its chagigah. Fresh.')
row(16, 5, 'MATERIAL', f'YOU MAY NOT SACRIFICE THE PASSOVER WITHIN ONE OF YOUR GATES WHICH THE LORD YOUR GOD GIVES YOU. {HP(16, 5, (("לא", "תוכל", "לזבח", "את", "הפסח"), "you may not sacrifice the Passover"), (("באחד", "שעריך"), "within one of your gates — the formula\'s second seat, the parser\'s [1]"))} {AP(16, 5, (("לית", "לך", "רשו", "למכס"), "YOU HAVE NO PERMISSION to slaughter — the rendering at four seats"), (("בחדא", "מקרויך"), "in one of your CITIES — gates rendered cities"))} THE GATE: 132:1-2\'s party of one; 132:3\'s majority; 132:4\'s eras; 147:2\'s prohibition among three (the outside row). Fresh.')
row(16, 6, 'MATERIAL', f'BUT AT THE PLACE WHICH THE LORD YOUR GOD WILL CHOOSE TO MAKE HIS NAME DWELL, THERE YOU SHALL SACRIFICE THE PASSOVER AT EVENING, AT THE GOING DOWN OF THE SUN, THE SEASON OF YOUR GOING OUT OF EGYPT. {HP(16, 6, (("כי", "אם", "אל", "המקום"), "but at the place — the chapter\'s one \'but only\'"), (("בערב", "כבוא", "השמש", "מועד", "צאתך", "ממצרים"), "at evening, at the going down of the sun, the season of your going out — the three times; \'between the evenings\' nowhere"))} {AP(16, 6, (("אלהן", "לאתרא"), "BUT to the place"), (("ברמשא", "כמעל", "שמשא", "זמן", "מפקך"), "at evening, at the sun\'s entering, the time of your going out"))} THE THREE TIMES: 133:1\'s slaughter, eating, burning; 133:2\'s eating\'s end and the other word. Fresh.')
row(16, 7, 'MATERIAL', f'AND YOU SHALL COOK AND EAT IT IN THE PLACE WHICH THE LORD YOUR GOD WILL CHOOSE, AND YOU SHALL TURN IN THE MORNING AND GO TO YOUR TENTS. {HP(16, 7, (("ובשלת", "ואכלת", "במקום"), "and you shall cook and eat in the place — the verb against Exodus 12:9\'s \'boiled in water\'"), (("ופנית", "בבקר", "והלכת", "לאהליך"), "and you shall turn in the morning and go to your tents"))} {AP(16, 7, (("ותבשל", "ותיכול", "באתרא"), "and you shall cook and eat in the place — the verb kept"), (("ותהך", "לקרוך"), "and go to your CITIES — tents rendered cities"))} THE MORNING: 134:1\'s roast returned; 134:2-3\'s overnight stay; 134:4\'s minor Passover. Fresh.')
row(16, 8, 'MATERIAL', f'SIX DAYS YOU SHALL EAT UNLEAVENED BREAD, AND ON THE SEVENTH DAY A SOLEMN ASSEMBLY TO THE LORD YOUR GOD; YOU SHALL DO NO WORK. {HP(16, 8, (("ששת", "ימים", "תאכל", "מצות"), "six days you shall eat unleavened bread — the one seat; Exodus 13:6\'s seven"), (("וביום", "השביעי", "עצרת", "ליהוה"), "and on the seventh day a solemn assembly to the LORD — the Torah\'s three"), (("לא", "תעשה", "מלאכה"), "you shall do no work — the sabbath\'s form, 16:8\'s closest kin"))} {AP(16, 8, (("שתא", "יומין", "תיכול", "פטירא"), "six days you shall eat unleavened bread"), (("כנש", "קדם", "יי"), "a GATHERING before the LORD — assembly rendered gathering, ten seats"))} SIX AND SEVEN: 134:5\'s new and old grain; 135:1\'s half and half; 135:2-3\'s intermediate days given to the sages. Fresh.')
row(16, 9, 'MATERIAL', f'SEVEN WEEKS YOU SHALL COUNT FOR YOURSELF; FROM WHEN THE SICKLE BEGINS ON THE STANDING GRAIN YOU SHALL BEGIN TO COUNT SEVEN WEEKS. {HP(16, 9, (("שבעה", "שבעת", "תספר", "לך"), "seven weeks you shall count for yourself — the one seat; the starred token"), (("מהחל", "חרמש", "בקמה"), "from when the sickle begins on the standing grain — the sickle\'s two seats"), (("שבעה", "שבעות"), "seven weeks — spelled full the second time"))} {AP(16, 9, (("מדשריות", "מגלא", "בחצד", "עומרא", "דארמותא"), "FROM WHEN THE SICKLE BEGINS ON THE HARVEST OF THE OMER OF THE WAVING — Leviticus\'s words supplied"), (("תשרי", "לממני"), "you shall begin to count"))} THE COUNT: 136:1\'s court and each man; 136:2-3\'s three rules; 136:4-8\'s night and day; the verse without a kin in the Bible (asserted). Fresh.')
row(16, 10, 'MATERIAL', f'AND YOU SHALL KEEP THE FEAST OF WEEKS TO THE LORD YOUR GOD WITH THE MEASURE OF THE FREEWILL OFFERING OF YOUR HAND WHICH YOU GIVE, AS THE LORD YOUR GOD HAS BLESSED YOU. {HP(16, 10, (("ועשית", "חג", "שבעות", "ליהוה"), "and you shall keep the feast of weeks to the LORD — the Bible\'s two"), (("מסת", "נדבת", "ידך"), "the measure of the freewill offering of your hand"), (("כאשר", "יברכך", "יהוה"), "as the LORD has blessed you"))} {AP(16, 10, (("ותעבד", "חגא", "דשבועיא"), "and you shall make the feast of weeks"), (("מסת", "נדבת", "ידך"), "the measure of your hand\'s gift — the Hebrew kept"))} THE FEAST: 137:1\'s no harvest condition; 137:2-3\'s unconsecrated and the tithe. Fresh.')
row(16, 11, 'MATERIAL', f'AND YOU SHALL REJOICE BEFORE THE LORD YOUR GOD — YOU, YOUR SON AND YOUR DAUGHTER, YOUR MANSERVANT AND YOUR MAIDSERVANT, THE LEVITE WITHIN YOUR GATES, THE SOJOURNER, THE FATHERLESS AND THE WIDOW IN YOUR MIDST — IN THE PLACE WHICH THE LORD YOUR GOD WILL CHOOSE TO MAKE HIS NAME DWELL THERE. {HP(16, 11, (("ושמחת", "לפני", "יהוה", "אלהיך"), "and you shall rejoice before the LORD your God — the book\'s eight"), (("אתה", "ובנך", "ובתך", "ועבדך", "ואמתך", "והלוי"), "you, your son, your daughter, your manservant, your maidservant, the Levite — 12:18\'s six"), (("והגר", "והיתום", "והאלמנה"), "the sojourner, the fatherless and the widow — the nine\'s last three"))} {AP(16, 11, (("ותחדי", "קדם", "יי"), "and you shall rejoice before the LORD"), (("וגיורא", "ויתמא", "וארמלא"), "the sojourner, the fatherless and the widow"))} THE JOY: 138:1\'s peace offerings by analogy (REREAD); 138:2\'s precedence; 138:3-8\'s three commandments. Fresh.')
print('the Onkelos rows 16:1-11 typed:', len(R), '| the cuts\' misses:', FAIL)
