#!/usr/bin/env python3
# THE DEUTERONOMY WALK sitting 14 — CHAPTER 16 (LEAN, 2026-09-23): THE LEAN MEASURE — the facts the ink will assert, PRINTED first (every number read from its
# print, never typed): the kin by computation, the twin laws diffed, the festival and court formulas' seats over the Torah and the Bible, Onkelos's additions and
# renderings over the book, the frames and the register on the morphology, the prior reads. No phrase censuses beyond the chapter's own questions (the lean
# form). Imports the ink's helpers (ch16_ink.py assembled without a body). RUN FROM THE REPO ROOT with PYTHONPATH the scratchpad.
from ch16_ink import *
print('==== A. THE KIN BY COMPUTATION (every verse against every verse of the Bible; the closest three re-scored in order)')
for v in range(1, NV + 1): print(f'  16:{v}:', KINC[v])
print('==== B. THE TWINS DIFFED (shared tokens in order / the diff)')
PAIRS = [((16, 1), ('Exod', 13, 4)), ((16, 1), ('Exod', 23, 15)), ((16, 1), ('Exod', 34, 18)), ((16, 1), ('Exod', 12, 42)), ((16, 2), ('Exod', 12, 5)), ((16, 2), ('Exod', 12, 21)), ((16, 3), ('Exod', 12, 11)), ((16, 3), ('Exod', 13, 3)), ((16, 3), ('Exod', 13, 6)), ((16, 3), ('Exod', 12, 15)),
         ((16, 4), ('Exod', 13, 7)), ((16, 4), ('Exod', 12, 10)), ((16, 4), ('Exod', 23, 18)), ((16, 4), ('Exod', 34, 25)), ((16, 5), ('Deut', 12, 17)), ((16, 6), ('Exod', 12, 6)), ((16, 6), ('Lev', 23, 5)), ((16, 6), ('Num', 9, 3)), ((16, 7), ('Exod', 12, 8)), ((16, 7), ('Exod', 12, 9)), ((16, 8), ('Exod', 12, 16)), ((16, 8), ('Lev', 23, 8)), ((16, 8), ('Exod', 13, 6)), ((16, 8), ('Num', 28, 25)),
         ((16, 9), ('Lev', 23, 15)), ((16, 9), ('Lev', 23, 16)), ((16, 10), ('Exod', 23, 16)), ((16, 10), ('Exod', 34, 22)), ((16, 10), ('Num', 28, 26)), ((16, 11), ('Deut', 12, 12)), ((16, 11), ('Deut', 12, 18)), ((16, 11), ('Deut', 14, 26)), ((16, 11), ('Deut', 16, 14)), ((16, 12), ('Deut', 5, 15)), ((16, 12), ('Deut', 15, 15)), ((16, 12), ('Deut', 24, 18)), ((16, 12), ('Deut', 24, 22)),
         ((16, 13), ('Lev', 23, 34)), ((16, 13), ('Exod', 23, 16)), ((16, 13), ('Lev', 23, 39)), ((16, 14), ('Deut', 16, 11)), ((16, 15), ('Lev', 23, 41)), ((16, 15), ('Lev', 23, 40)), ((16, 16), ('Exod', 23, 17)), ((16, 16), ('Exod', 34, 23)), ((16, 16), ('Exod', 23, 14)), ((16, 16), ('Exod', 23, 15)), ((16, 16), ('Exod', 34, 20)), ((16, 17), ('Deut', 12, 15)),
         ((16, 18), ('Deut', 1, 16)), ((16, 18), ('Exod', 18, 21)), ((16, 18), ('Exod', 18, 25)), ((16, 19), ('Exod', 23, 8)), ((16, 19), ('Exod', 23, 6)), ((16, 19), ('Deut', 1, 17)), ((16, 19), ('Lev', 19, 15)), ((16, 19), ('Deut', 24, 17)), ((16, 19), ('Deut', 27, 19)), ((16, 20), ('Deut', 8, 1)), ((16, 20), ('Deut', 4, 1)), ((16, 21), ('Deut', 7, 5)), ((16, 21), ('Deut', 12, 3)), ((16, 21), ('Exod', 34, 13)), ((16, 22), ('Lev', 26, 1)), ((16, 22), ('Deut', 12, 31)), ((16, 22), ('Exod', 23, 24))]
for a, b in PAIRS:
    A = ('Deut',) + a
    print(f'  {a[0]}:{a[1]} vs {b[0]} {b[1]}:{b[2]}: shared in order {SHN(A, b)} of {len(words(*A))}/{len(words(*b))}; longest run {SHARED(A, b)}; diff {DIFF(A, b)[:6]}')
print('==== C. THE FORMULAS OVER THE TORAH AND THE BIBLE (phrase seats by consonants)')
Q = [('the month of Aviv', ('חדש', 'האביב')), ('Passover token (Torah, exact)', None), ('seven days (Torah)', ('שבעת', 'ימים')), ('the place which He will choose (book)', ('במקום', 'אשר', 'יבחר')), ('to make His name dwell there', ('לשכן', 'שמו', 'שם')), ('bread of affliction', ('לחם', 'עני')), ('in haste', None), ('at the going down of the sun', ('כבוא', 'השמש')), ('six days you shall eat', ('ששת', 'ימים', 'תאכל')), ('solemn assembly token', None), ('seven weeks', ('שבעה', 'שבעת')), ('sickle token', None), ('feast of weeks', ('חג', 'שבעות')), ('and you shall rejoice (book)', None), ('the feast of booths (chag ha-sukkot, both spellings)', None), ('three times in the year', ('שלוש', 'פעמים', 'בשנה')), ('all your males shall appear', ('יראה', 'כל', 'זכורך')), ('appear before the LORD empty', ('פני', 'יהוה', 'ריקם')), ('judges and officers', ('שפטים', 'ושטרים')), ('in all your gates (book)', ('בכל', 'שעריך')), ('you shall not wrest judgment', ('לא', 'תטה', 'משפט')), ('respect persons (both numbers)', None), ('a bribe blinds', None), ('justice justice', ('צדק', 'צדק')), ('that you may live and inherit', ('למען', 'תחיה', 'וירשת')), ('asherah token (Torah)', None), ('pillar token (Torah)', None), ('which the LORD your God hates', ('אשר', 'שנא', 'יהוה'))]
for name, seq in Q:
    if seq: print(f'  {name}: Torah {P(*seq, books=T)} | Bible {P(*seq, books=None)}')
print('  Passover token (Torah, exact):', U('פסח', 'הפסח', books=T), '| the Bible count', len(U('פסח', 'הפסח', books=None)))
print('  in haste:', hits('בחפזון'), '| solemn assembly:', hits('עצרת', T), '| sickle:', hits('חרמש'), '| asherah (Torah):', U('אשרה', 'אשריו', 'אשרים', 'אשרהם', books=T), '| pillar (Torah):', U('מצבה', 'מצבת', 'מצבתם', 'מצבתיהם', books=T))
print('  and you shall rejoice (book):', U('ושמחת', 'ושמחתם', books=('Deut',)), '| rejoice tokens in the chapter:', [(v, x) for v in range(1, NV + 1) for x in W16(v) if x.startswith('ושמח') or x == 'שמח'])
print('  the feast of booths:', P('חג', 'הסכת', books=None), P('חג', 'הסכות', books=None), P('ובחג', 'הסכות', books=None), '| the feast of unleavened bread:', P('חג', 'המצות', books=None), P('בחג', 'המצות', books=None))
print('  respect persons:', P('לא', 'תכיר', 'פנים', books=None), P('לא', 'תכירו', 'פנים', books=None), '| a bribe blinds:', P('השחד', 'יעור', books=None), '| bribe tokens (Torah):', U('שחד', 'השחד', 'ושחד', books=T))
print('  the household list at 16:11 == 16:14 (the nine tokens from "you"):', [x for x in W16(11) if x in ('אתה', 'ובנך', 'ובתך', 'ועבדך', 'ואמתך', 'והלוי', 'והגר', 'והיתום', 'והאלמנה')], [x for x in W16(14) if x in ('אתה', 'ובנך', 'ובתך', 'ועבדך', 'ואמתך', 'והלוי', 'והגר', 'והיתום', 'והאלמנה')], '| 12:12 and 12:18:', [x for x in words('Deut', 12, 12) if x.startswith('ו') and x[1:] in ('בניכם', 'בנתיכם', 'עבדיכם', 'אמהתיכם', 'הלוי')], [x for x in words('Deut', 12, 18) if x in ('אתה', 'ובנך', 'ובתך', 'ועבדך', 'ואמתך', 'והלוי')])
print('  "the place" formula in the chapter:', [(v, i) for v in range(1, NV + 1) for i, x in enumerate(W16(v)) if x in ('במקום', 'המקום') and W16(v)[i + 1] == 'אשר' and W16(v)[i + 2] == 'יבחר'], '| "your gates" in the chapter:', [(v, x) for v in range(1, NV + 1) for x in W16(v) if 'שעריך' in x])
print('  "seven" tokens per verse:', {v: [x for x in W16(v) if x in ('שבעת', 'שבעה', 'שבעות', 'השבעות', 'שבע')] for v in range(1, NV + 1) if any(x in ('שבעת', 'שבעה', 'שבעות', 'השבעות', 'שבע') for x in W16(v))}, '| "remember" tokens:', [(v, x) for v in range(1, NV + 1) for x in W16(v) if x in ('תזכר', 'וזכרת')], '| "Egypt" tokens:', [(v, x) for v in range(1, NV + 1) for x in W16(v) if 'מצרים' in x])
print('  the wise vs the open-eyed: 16:19', [x for x in W16(19) if x in ('חכמים', 'פקחים')], 'Exodus 23:8', [x for x in words('Exod', 23, 8) if x in ('חכמים', 'פקחים')], '| "boil" tokens (Torah):', U('ובשלת', 'בשל', 'מבשל', 'תבשל', 'ובשל', books=T), '| 2 Chr 35:13 tokens:', [x for x in words('2Chr', 35, 13)][:6])
print('==== D. ONKELOS OVER THE BOOK (the plain Aramaic of every export row through NFKC; EXPORT verse numbers)')
def ARM(c, v): return [plain(unicodedata.normalize('NFKC', x)).strip('.:') for x in clean(onk_he[c - 1][v - 1]).rstrip(':').split()]
def SEATS(sub): return [(c + 1, v + 1) for c in range(34) for v in range(len(onk_he[c])) if sub in ' '.join(ARM(c + 1, v + 1))]
for name, sub in [('and He did miracles for you (the addition at 16:1)', 'ועבד לך נסין'), ('miracles token', 'נסין'), ('the Shekhinah', 'שכנתיה'), ('before the LORD', 'קדם יי'), ('holy slaughterings (the chagigah at 16:2)', 'נכסת קודשיא'), ('you have no permission (16:5)', 'לית לך רשו'), ('the omer of the waving (16:9)', 'עומרא דארמותא'), ('assembly (16:8)', 'כנש'), ('your cities (for gates)', 'קרויך'), ('judges and officers (16:18)', 'דינין ופרענין'), ('upright words (16:19)', 'פתגמין תריצין'), ('the Memra', 'מימר'), ('a pillar (16:22)', 'קמא'), ('an asherah', 'אשרת'), ('sourdough (16:4)', 'חמיר'), ('the sun\'s entering (16:6)', 'כמעל שמשא'), ('the huts (16:13)', 'מטליא'), ('empty (16:16)', 'ריקנון')]:
    s = SEATS(sub); print(f'  {name}: {len(s)} {s[:24]}')
print('  16:1 Aramaic:', ARM(16, 1)); print('  16:2 Aramaic:', ARM(16, 2)); print('  16:9 Aramaic:', ARM(16, 9)); print('  16:20 Aramaic:', ARM(16, 20))
print('==== E. THE FRAMES AND THE REGISTER (computed on the morphology)')
MO = {v: [(x, m) for x, m in by[('Deut', 16, v)]] for v in range(1, NV + 1)}
print('  2mp/2ms per verse:', {v: (sum(1 for _, m in MO[v] if m and '2mp' in m), sum(1 for _, m in MO[v] if m and '2ms' in m)) for v in range(1, NV + 1)})
print('  infinitive absolutes:', [(v, x) for v in range(1, NV + 1) for x, m in MO[v] if m and re.search(r'V[a-zA-Z]a$', m)], '| wayyiqtol forms:', [(v, x) for v in range(1, NV + 1) for x, m in MO[v] if m and re.search(r'V[a-zA-Z]w', m)], '| imperatives:', [(v, x) for v in range(1, NV + 1) for x, m in MO[v] if m and re.search(r'V[a-zA-Z]v', m)], '| first person:', [(v, x) for v in range(1, NV + 1) for x, m in MO[v] if m and '1c' in m], '| participles:', [(v, x) for v in range(1, NV + 1) for x, m in MO[v] if m and re.search(r'V[a-zA-Z]r', m)])
print('  negations per verse:', {v: sum(1 for x in W16(v) if x in ('לא', 'ולא')) for v in range(1, NV + 1) if any(x in ('לא', 'ולא') for x in W16(v))}, '| verses opening with ki/im:', [v for v in range(1, NV + 1) if W16(v)[0] in ('כי', 'וכי', 'אם')], '| "saying":', [v for v in range(1, NV + 1) if 'לאמר' in W16(v)], '| "so that" (למען):', [v for v in range(1, NV + 1) if 'למען' in W16(v)])
print('  the Name bare / with lamed / "your God" pairs:', sum(1 for v in range(1, NV + 1) for x in W16(v) if x == 'יהוה'), sum(1 for v in range(1, NV + 1) for x in W16(v) if x == 'ליהוה'), [v for v in range(1, NV + 1) if any(a == 'יהוה' and b == 'אלהיך' for a, b in zip(W16(v), W16(v)[1:]))], '| verses without the Name:', [v for v in range(1, NV + 1) if not any('יהוה' in x for x in W16(v))])
with contextlib.redirect_stdout(io.StringIO()):
    import register_census as RC
    _ink = RC.read_ink()
print('  the register on Deut 16 — receipts:', [k for k in RC.receipts(_ink) if k[0] == 'Deut' and k[1] == 16], '| footers:', [x for x in RC.footers(_ink) if x[0][0] == 'Deut' and x[0][1] == 16], '| headers:', [x for x in RC.register_headers(_ink) if x[0][0] == 'Deut' and x[0][1] == 16], '| receipts in the book so far:', [k for k in RC.receipts(_ink) if k[0] == 'Deut' and k[1] <= 16], '| count lines:', ([k for k in RC.count_lines(_ink) if k[0] == 'Deut' and k[1] == 16] if hasattr(RC, 'count_lines') else 'n/a'))
print('==== F. THE PRIOR READS (computed from the ledgers)')
TRI = f'{ROOT}/logic/oral_triage'
LED = {f: open(f'{TRI}/{f}', encoding='utf-8').read() for f in os.listdir(TRI) if f.endswith('.md') and os.path.isfile(f'{TRI}/{f}')}
SPINE_PRIOR = sorted({(f, int(a), int(b)) for f, t in LED.items() for a, b in re.findall(r'Sifrei Devarim (\d+):(\d+)', t) if int(a) in PISKAOT})
OUT_PRIOR = sorted({(f, int(a), int(b)) for f, t in LED.items() for a, b in re.findall(r'Sifrei Devarim (\d+):(\d+)', t) if (int(a), int(b)) in OUTSIDE})
print('  spine rows read before:', SPINE_PRIOR, '| outside rows read before:', OUT_PRIOR)
print('  ledgers with an Onkelos row of Deut 16-34 or the Prophets (never read ahead — expected none):', sorted(f for f, t in LED.items() if re.search(r'^- Onkelos (?:Deut (?:1[6-9]|2\d|3\d)|Josh|Judg|1Sam|2Sam|1Kgs|2Kgs|Isa|Jer|Ezek):', t, re.M)))
KIN = [(f, len(re.findall(r'^- Onkelos ' + pat, LED[f], re.M))) for f, pat in [('lev_23_festivals_2026-09-05.md', r'Lev 23:'), ('num_28_pesach_shavuot_2026-09-11.md', r'Num 28:'), ('num_29_fall_festivals_2026-09-11.md', r'Num 29:'), ('num_09_pesach_cloud_2026-09-09.md', r'Num 9:'), ('exo_23_justice_calendar_2026-09-01.md', r'Exod 23:'), ('exo_34_second_tablets_2026-09-01.md', r'Exod 34:'), ('lev_19_kedoshim_2026-09-05.md', r'Lev 19:'), ('lev_26_blessings_curses_2026-09-05.md', r'Lev 26:'), ('deu_01_03_devarim_2026-09-15.md', r'Deut 1:'), ('deu_07_vaetchanan_ekev_2026-09-17.md', r'Deut 7:'), ('deu_12_reeh_2026-09-20.md', r'Deut 12:'), ('deu_05_vaetchanan_2026-09-16.md', r'Deut 5:'), ('deu_15_reeh_2026-09-22.md', r'Deut 15:')] if f in LED]
print('  the kin ledgers\' Onkelos row counts:', KIN, '| Exodus 12-13 and 18 ledgers with Onkelos rows:', sorted(f for f, t in LED.items() if re.search(r'^- Onkelos Exod (?:12|13|18):', t, re.M)))
print('  the store mismatches:', STORE_MISMATCH, '| token count:', sum(len(W16(v)) for v in range(1, NV + 1)), '| distinct glosses:', len({g for k in SG for _, _, g in SG[k]}), '| "?" glosses:', [(c, v, hp) for (c, v) in SG for _, hp, g in SG[(c, v)] if g == '?'])
print('THE LEAN MEASURE PRINTED')
