#!/usr/bin/env python3
# THE DEUTERONOMY WALK sitting 15 — CHAPTERS 17-18 (LEAN, 2026-09-24): THE LEAN MEASURE — the facts the ink will assert, PRINTED first (every number read from
# its print, never typed): the kin by computation for the forty-two verses, the twin laws diffed, the formulas' seats over the Torah and the Bible, Onkelos's
# additions and renderings over the book, the frames and the register on the morphology, the prior reads. Sitting 14's form (ch16_measure_lean.py) over two
# chapters. Imports the ink's helpers (ch17_ink.py assembled without a body). RUN FROM THE REPO ROOT with PYTHONPATH the scratchpad.
from ch17_ink import *
print('==== A. THE KIN BY COMPUTATION (every verse against every verse of the Bible; the closest three re-scored in order)')
for c, v in SPAN: print(f'  {c}:{v}:', KINC[(c, v)])
print('==== B. THE TWINS DIFFED (shared tokens in order / the diff)')
PAIRS = [((17, 1), ('Lev', 22, 20)), ((17, 1), ('Lev', 22, 21)), ((17, 1), ('Deut', 15, 21)), ((17, 1), ('Lev', 22, 25)), ((17, 1), ('Deut', 12, 31)),
         ((17, 2), ('Deut', 13, 7)), ((17, 2), ('Deut', 13, 13)), ((17, 2), ('Deut', 13, 14)), ((17, 2), ('Deut', 29, 17)), ((17, 2), ('Deut', 24, 7)), ((17, 3), ('Deut', 4, 19)), ((17, 3), ('Deut', 13, 7)), ((17, 3), ('Deut', 29, 25)), ((17, 3), ('Deut', 13, 3)), ((17, 3), ('Deut', 8, 19)), ((17, 3), ('Deut', 11, 16)),
         ((17, 4), ('Deut', 13, 15)), ((17, 4), ('Deut', 19, 18)), ((17, 5), ('Deut', 13, 11)), ((17, 5), ('Deut', 22, 24)), ((17, 5), ('Deut', 21, 19)), ((17, 5), ('Deut', 22, 21)), ((17, 5), ('Lev', 24, 14)), ((17, 6), ('Deut', 19, 15)), ((17, 6), ('Num', 35, 30)), ((17, 7), ('Deut', 13, 10)), ((17, 7), ('Deut', 13, 6)), ((17, 7), ('Deut', 19, 19)), ((17, 7), ('Deut', 21, 21)), ((17, 7), ('Deut', 22, 21)), ((17, 7), ('Deut', 24, 7)),
         ((17, 8), ('Exod', 18, 22)), ((17, 8), ('Exod', 18, 26)), ((17, 8), ('Deut', 1, 17)), ((17, 8), ('Deut', 21, 5)), ((17, 8), ('Deut', 12, 5)), ((17, 9), ('Deut', 19, 17)), ((17, 9), ('Deut', 26, 3)), ((17, 9), ('Deut', 21, 5)), ((17, 10), ('Deut', 17, 11)), ((17, 11), ('Deut', 5, 29)), ((17, 11), ('Deut', 28, 14)), ((17, 11), ('Deut', 17, 20)), ((17, 11), ('Josh', 1, 7)), ((17, 12), ('Deut', 1, 43)), ((17, 12), ('Deut', 18, 20)), ((17, 12), ('Deut', 18, 22)), ((17, 12), ('Deut', 18, 5)), ((17, 13), ('Deut', 13, 12)), ((17, 13), ('Deut', 19, 20)), ((17, 13), ('Deut', 21, 21)),
         ((17, 14), ('1Sam', 8, 5)), ((17, 14), ('1Sam', 8, 20)), ((17, 14), ('1Sam', 12, 12)), ((17, 14), ('Deut', 26, 1)), ((17, 14), ('Deut', 12, 29)), ((17, 15), ('1Sam', 10, 24)), ((17, 15), ('Deut', 23, 21)), ((17, 15), ('Deut', 15, 3)), ((17, 15), ('1Sam', 16, 12)), ((17, 16), ('1Kgs', 10, 26)), ((17, 16), ('1Kgs', 10, 28)), ((17, 16), ('Deut', 28, 68)), ((17, 16), ('Exod', 14, 13)), ((17, 16), ('Isa', 31, 1)), ((17, 17), ('1Kgs', 11, 3)), ((17, 17), ('1Kgs', 11, 4)), ((17, 17), ('1Kgs', 10, 27)), ((17, 17), ('Deut', 8, 13)),
         ((17, 18), ('Josh', 8, 32)), ((17, 18), ('Deut', 31, 9)), ((17, 18), ('Deut', 31, 26)), ((17, 18), ('2Kgs', 11, 12)), ((17, 19), ('Deut', 31, 11)), ((17, 19), ('Deut', 31, 12)), ((17, 19), ('Deut', 31, 13)), ((17, 19), ('Deut', 6, 2)), ((17, 19), ('Deut', 4, 10)), ((17, 19), ('Josh', 1, 8)), ((17, 20), ('Deut', 8, 14)), ((17, 20), ('Deut', 5, 29)), ((17, 20), ('Deut', 4, 40)), ((17, 20), ('1Kgs', 3, 14)), ((17, 20), ('Deut', 28, 14)),
         ((18, 1), ('Num', 18, 20)), ((18, 1), ('Num', 18, 23)), ((18, 1), ('Deut', 10, 9)), ((18, 1), ('Deut', 12, 12)), ((18, 1), ('Deut', 14, 27)), ((18, 1), ('Deut', 14, 29)), ((18, 1), ('Josh', 13, 14)), ((18, 1), ('Josh', 18, 7)), ((18, 2), ('Num', 18, 20)), ((18, 2), ('Deut', 10, 9)), ((18, 2), ('Josh', 13, 33)),
         ((18, 3), ('Lev', 7, 32)), ((18, 3), ('Lev', 7, 34)), ((18, 3), ('Num', 18, 18)), ((18, 3), ('1Sam', 2, 13)), ((18, 3), ('Exod', 29, 27)), ((18, 4), ('Num', 18, 12)), ((18, 4), ('Deut', 14, 23)), ((18, 4), ('Deut', 12, 17)), ((18, 4), ('Exod', 23, 19)), ((18, 4), ('Num', 15, 20)), ((18, 4), ('Ezek', 44, 30)), ((18, 5), ('Deut', 10, 8)), ((18, 5), ('Deut', 21, 5)), ((18, 5), ('Deut', 18, 7)), ((18, 5), ('1Chr', 15, 2)), ((18, 5), ('Num', 16, 5)),
         ((18, 6), ('Deut', 12, 15)), ((18, 6), ('Deut', 12, 20)), ((18, 6), ('Deut', 12, 21)), ((18, 6), ('Deut', 12, 18)), ((18, 6), ('Deut', 14, 27)), ((18, 6), ('Judg', 17, 7)), ((18, 6), ('Judg', 17, 8)), ((18, 7), ('Deut', 10, 8)), ((18, 7), ('Deut', 21, 5)), ((18, 8), ('2Chr', 31, 15)), ((18, 8), ('2Kgs', 11, 5)),
         ((18, 9), ('Deut', 12, 29)), ((18, 9), ('Deut', 12, 30)), ((18, 9), ('Deut', 12, 31)), ((18, 9), ('Deut', 20, 18)), ((18, 9), ('Deut', 9, 4)), ((18, 9), ('Lev', 18, 3)), ((18, 9), ('Lev', 20, 23)), ((18, 10), ('Deut', 12, 31)), ((18, 10), ('Lev', 18, 21)), ((18, 10), ('Lev', 20, 2)), ((18, 10), ('Lev', 19, 26)), ((18, 10), ('2Kgs', 17, 17)), ((18, 10), ('2Kgs', 21, 6)), ((18, 10), ('Exod', 22, 17)), ((18, 11), ('Lev', 19, 31)), ((18, 11), ('Lev', 20, 6)), ((18, 11), ('Lev', 20, 27)), ((18, 11), ('1Sam', 28, 7)), ((18, 11), ('2Kgs', 21, 6)), ((18, 11), ('2Kgs', 23, 24)), ((18, 11), ('Isa', 8, 19)),
         ((18, 12), ('Deut', 12, 31)), ((18, 12), ('Deut', 9, 4)), ((18, 12), ('Deut', 9, 5)), ((18, 12), ('Deut', 22, 5)), ((18, 12), ('Deut', 25, 16)), ((18, 12), ('Lev', 18, 24)), ((18, 12), ('Lev', 20, 23)), ((18, 13), ('Gen', 6, 9)), ((18, 13), ('Gen', 17, 1)), ((18, 13), ('Ps', 15, 2)), ((18, 13), ('1Kgs', 8, 61)), ((18, 13), ('2Sam', 22, 24)), ((18, 14), ('Deut', 9, 5)), ((18, 14), ('Deut', 12, 29)), ((18, 14), ('Deut', 18, 10)), ((18, 14), ('Deut', 18, 9)),
         ((18, 15), ('Deut', 18, 18)), ((18, 15), ('Deut', 34, 10)), ((18, 15), ('Deut', 13, 2)), ((18, 15), ('Deut', 5, 24)), ((18, 15), ('Num', 12, 6)), ((18, 15), ('Deut', 17, 15)), ((18, 16), ('Deut', 5, 22)), ((18, 16), ('Deut', 5, 23)), ((18, 16), ('Deut', 5, 24)), ((18, 16), ('Deut', 5, 25)), ((18, 16), ('Deut', 9, 10)), ((18, 16), ('Deut', 10, 4)), ((18, 16), ('Exod', 20, 16)), ((18, 16), ('Deut', 4, 33)), ((18, 17), ('Deut', 5, 25)), ((18, 17), ('Deut', 1, 14)),
         ((18, 18), ('Deut', 18, 15)), ((18, 18), ('Deut', 34, 10)), ((18, 18), ('Exod', 4, 15)), ((18, 18), ('Exod', 4, 12)), ((18, 18), ('Num', 22, 38)), ((18, 18), ('Num', 23, 5)), ((18, 18), ('Num', 23, 12)), ((18, 18), ('Num', 23, 16)), ((18, 18), ('Jer', 1, 9)), ((18, 18), ('Isa', 51, 16)), ((18, 18), ('Isa', 59, 21)), ((18, 19), ('Gen', 9, 5)), ((18, 19), ('Gen', 42, 22)), ((18, 19), ('Josh', 1, 18)), ((18, 19), ('Deut', 13, 4)),
         ((18, 20), ('Deut', 13, 2)), ((18, 20), ('Deut', 13, 6)), ((18, 20), ('Deut', 18, 22)), ((18, 20), ('Jer', 14, 14)), ((18, 20), ('Jer', 14, 15)), ((18, 20), ('Jer', 23, 32)), ((18, 20), ('Jer', 28, 16)), ((18, 20), ('Jer', 29, 9)), ((18, 21), ('Deut', 18, 22)), ((18, 21), ('Deut', 12, 30)), ((18, 22), ('Deut', 13, 2)), ((18, 22), ('Deut', 13, 3)), ((18, 22), ('Jer', 28, 9)), ((18, 22), ('Ezek', 33, 33)), ((18, 22), ('1Kgs', 22, 28)), ((18, 22), ('Deut', 1, 17)), ((18, 22), ('Deut', 18, 20))]
for a, b in PAIRS:
    A = ('Deut',) + a
    if b not in by: print(f'  {a[0]}:{a[1]} vs {b[0]} {b[1]}:{b[2]}: NOT IN THE DB'); continue
    print(f'  {a[0]}:{a[1]} vs {b[0]} {b[1]}:{b[2]}: shared in order {SHN(A, b)} of {len(words(*A))}/{len(words(*b))}; longest run {SHARED(A, b)}; diff {DIFF(A, b)[:6]}')
print('==== C. THE FORMULAS OVER THE TORAH AND THE BIBLE (phrase seats by consonants)')
Q = [('purge the evil from your midst', ('ובערת', 'הרע', 'מקרבך')), ('purge the evil from Israel', ('ובערת', 'הרע', 'מישראל')), ('the priests the Levites', ('הכהנים', 'הלוים')), ('the priests the sons of Levi', ('הכהנים', 'בני', 'לוי')), ('in those days (the judge/priest)', ('בימים', 'ההם')), ('right or left (both spellings)', ('ימין', 'ושמאל')), ('right or left (full)', ('ימין', 'ושמאול')),
     ('two witnesses or three', ('שנים', 'עדים', 'או', 'שלשה')), ('by the mouth of two witnesses', ('פי', 'שנים', 'עדים')), ('one witness', ('עד', 'אחד')), ('hear and fear', ('ישמעו', 'ויראו')), ('the place which He will choose (book)', ('המקום', 'אשר', 'יבחר')), ('a king like all the nations', ('מלך', 'ככל', 'הגוים')), ('from among your brothers', ('מקרב', 'אחיך')), ('a copy of this law', ('משנה', 'התורה')), ('this law (book)', ('התורה', 'הזאת')), ('all the days of his life', ('כל', 'ימי', 'חייו')), ('to fear the LORD (infinitive, book)', ('ליראה', 'את', 'יהוה')), ('prolong days on his kingdom', ('יאריך', 'ימים')), ('heart lifted', ('רום', 'לבבו')),
     ('portion and inheritance', ('חלק', 'ונחלה')), ('the fire offerings of the LORD', ('אשי', 'יהוה')), ('the LORD is his inheritance', ('יהוה', 'הוא', 'נחלתו')), ('the first of the fleece', ('ראשית', 'גז')), ('your grain, wine and oil', ('דגנך', 'תירשך', 'ויצהרך')), ('to stand to minister in the name', ('לעמד', 'לשרת', 'בשם')), ('to minister in the name of the LORD', ('לשרת', 'בשם', 'יהוה')), ('with all the desire of his soul', ('בכל', 'אות', 'נפשו')), ('with all the desire of your soul', ('בכל', 'אות', 'נפשך')), ('portion as portion', ('חלק', 'כחלק')),
     ('the abominations of the nations', ('כתועבת', 'הגוים')), ('an abomination of the LORD', ('תועבת', 'יהוה')), ('passes his son and daughter through fire', ('מעביר', 'בנו', 'ובתו', 'באש')), ('whole with', ('תמים', 'תהיה')), ('a prophet from your midst like me', ('נביא', 'מקרבך', 'מאחיך', 'כמני')), ('I will raise up a prophet', ('נביא', 'אקים')), ('the day of the assembly (book)', ('ביום', 'הקהל')), ('this great fire', ('האש', 'הגדלה', 'הזאת')), ('My words in his mouth', ('דברי', 'בפיו')), ('My words in your mouth', ('דברי', 'בפיך')), ('the prophet shall die', ('ומת', 'הנביא', 'ההוא')), ('in the name of other gods', ('בשם', 'אלהים', 'אחרים')), ('you shall not fear him', ('לא', 'תגור', 'ממנו')),
     ('blemish, any evil thing', ('מום', 'כל', 'דבר', 'רע')), ('the sun or the moon', ('ולשמש', 'או', 'לירח')), ('the host of heaven', ('צבא', 'השמים')), ('which I have not commanded', ('אשר', 'לא', 'צויתי')), ('between blood and blood', ('בין', 'דם', 'לדם')), ('stroke and stroke', ('נגע', 'לנגע')), ('matters of dispute', ('דברי', 'ריבת')), ('inquire well (two words)', ('ודרשת', 'היטב')), ('inquire, search, ask well (13:15)', ('ודרשת', 'וחקרת', 'ושאלת', 'היטב')), ('the hand of the witnesses first', ('יד', 'העדים', 'תהיה', 'בו', 'בראשנה')), ('your hand first (13:10)', ('ידך', 'תהיה', 'בו', 'בראשונה')), ('and he shall read in it', ('וקרא', 'בו')), ('multiply horses', ('ירבה', 'לו', 'סוסים')), ('multiply wives', ('ירבה', 'לו', 'נשים')), ('silver and gold … multiply', ('וכסף', 'וזהב', 'לא', 'ירבה')), ('the king whom the LORD will choose', ('מלך', 'אשר', 'יבחר', 'יהוה')), ('a foreigner who is not your brother', ('איש', 'נכרי', 'אשר', 'לא', 'אחיך'))]
for name, seq in Q: print(f'  {name}: Torah {P(*seq, books=T)} | Bible {P(*seq, books=None)}')
print('  the purge formula tokens (Torah):', U('ובערת', 'תבערו', 'ובערתם', books=T), '| "the judge" (book):', U('השפט', 'השופט', books=('Deut',)), '| "the priest" singular (book):', U('הכהן', books=('Deut',)), '| "prophet" tokens (book):', U('נביא', 'הנביא', 'נביאים', books=('Deut',)))
print('  "the diviners" tokens over the Bible — kosem:', U('קסם', 'קסמים', 'קוסם', 'קסמים', books=None), '| meonen:', U('מעונן', 'מעננים', 'מעונן', 'תעוננו', books=None), '| menachesh:', U('ומנחש', 'מנחש', 'תנחשו', books=None), '| mekhashef:', U('ומכשף', 'מכשף', 'מכשפה', 'מכשפים', books=None), '| chover chaver:', U('וחבר', 'חבר', books=None)[:12], '| ov:', U('אוב', 'אבות', 'האבות', books=None), '| yidoni:', U('וידעני', 'ידעני', 'ידענים', 'והידענים', books=None), '| doresh el ha-metim:', P('אל', 'המתים', books=None))
print('  "foreigner" tokens (Torah):', U('נכרי', 'הנכרי', 'לנכרי', books=T), '| "horses" (Torah):', U('סוס', 'סוסים', 'סוסיו', 'וסוסים', 'סוסי', books=T), '| "king" tokens in the two chapters:', [(c, v, x) for c, v in SPAN for x in W(c, v) if x in ('מלך', 'המלך', 'מלכא')], '| "abomination" tokens (book):', U('תועבת', 'תועבה', 'התועבה', 'התועבת', 'כתועבת', books=('Deut',)))
print('  "presumptuously" (zadon) tokens (Bible):', U('בזדון', 'זדון', 'זדונו', books=None), '| "presume" verbs (Bible):', U('יזיד', 'יזידון', 'הזיד', 'זדו', 'ותזדו', books=None), '| "require" (adrosh):', U('אדרש', 'אדרוש', books=None), '| "to require it of him" phrase:', P('אדרש', 'מעמו', books=None))
print('  "the shoulder" (zeroa) tokens (Bible):', U('הזרע', 'זרוע', 'הזרוע', 'זרע', books=None)[:16], '| "the cheeks":', U('והלחיים', 'הלחיים', 'לחיים', books=None), '| "the maw":', U('והקבה', 'הקבה', 'קבה', books=None), '| "fleece":', U('גז', 'הגז', 'גזי', 'גזז', books=None), '| "the first" (reshit) in the book:', U('ראשית', 'וראשית', 'מראשית', books=('Deut',)))
print('  "the witnesses" tokens (Torah):', U('עדים', 'העדים', 'עד', 'העד', books=T), '| the Sanhedrin verse 17:6 vs 19:15 vs Numbers 35:30 shared runs:', SHARED(('Deut', 17, 6), ('Deut', 19, 15)), SHARED(('Deut', 17, 6), ('Num', 35, 30)))
print('  the two chapters\' "not" clauses and the openings:', {f'{c}:{v}': [x for x in W(c, v) if x in ('לא', 'ולא')] for c, v in SPAN if any(x in ('לא', 'ולא') for x in W(c, v))}, '| verses opening with ki/im/rak/akh:', [f'{c}:{v}' for c, v in SPAN if W(c, v)[0] in ('כי', 'וכי', 'אם', 'רק', 'אך')])
print('  "Egypt" tokens:', [(c, v, x) for c, v in SPAN for x in W(c, v) if 'מצרים' in x or x == 'מצרימה'], '| "Horeb":', [(c, v, x) for c, v in SPAN for x in W(c, v) if 'חרב' in x], '| "Israel":', [(c, v, x) for c, v in SPAN for x in W(c, v) if 'ישראל' in x], '| "Levi/Levite":', [(c, v, x) for c, v in SPAN for x in W(c, v) if 'לוי' in x], '| "your gates":', [(c, v, x) for c, v in SPAN for x in W(c, v) if 'שעריך' in x], '| "the place":', [(c, v, i) for c, v in SPAN for i, x in enumerate(W(c, v)) if x in ('במקום', 'המקום') and W(c, v)[i + 1] == 'אשר' and W(c, v)[i + 2] == 'יבחר'])
print('  the kin diffs of the king\'s three prohibitions against Solomon — 1 Kings 10:26 tokens:', words('1Kgs', 10, 26), '| 1 Kings 11:3:', words('1Kgs', 11, 3), '| 1 Kings 11:4:', words('1Kgs', 11, 4)[:12], '| 1 Samuel 8:5:', words('1Sam', 8, 5))
print('  18:15/18:18 "like me"/"like you" tokens:', [x for x in W(18, 15) if x.startswith('כמ')], [x for x in W(18, 18) if x.startswith('כמ')], '| 34:10 tokens:', words('Deut', 34, 10), '| 13:2 tokens:', words('Deut', 13, 2)[:9])
print('==== D. ONKELOS OVER THE BOOK (the plain Aramaic of every export row through NFKC; EXPORT verse numbers)')
def ARM(c, v): return [plain(unicodedata.normalize('NFKC', x)).strip('.:()') for x in clean(onk_he[c - 1][v - 1]).rstrip(':').split()]
def SEATS(sub): return [(c + 1, v + 1) for c in range(34) for v in range(len(onk_he[c])) if sub in ' '.join(ARM(c + 1, v + 1))]
for name, sub in [('you have no permission (17:15)', 'לית לך רשו'), ('the Memra — "by the memra of" (17:6, 10, 11)', 'על מימר'), ('the Memra of the LORD', 'מימרא דיי'), ('My Memra (18:19)', 'מימרי'), ('Memra tokens (any)', 'מימר'), ('the gate of your court (17:5)', 'בית דינך'), ('the idols of the nations (17:3, 18:9, 18:20)', 'טעות עממיא'), ('distanced — for abomination (17:1, 18:12)', 'מרחק'), ('the plague of confinement (17:8)', 'מכתש סגירו'), ('the one liable to death (17:6)', 'דחיב קטול'), ('the DOER of evil (17:7, 17:12)', 'עבד דביש'), ('your cities (for gates)', 'קרויך'), ('the copy (17:18)', 'פתשגן'), ('the offerings of the LORD (18:1 — for fire offerings)', 'קרבניא דיי'), ('the gifts He gave him (18:2 — the addition)', 'מתנן דיהב ליה'), ('what is fit for the priests (18:3)', 'דחזי לכהניא'), ('the watch that comes on the Sabbath (18:8 — the addition)', 'ממטרתא'), ('as the fathers ordained (18:8)', 'אתקינו אבהתא'), ('in prayer (18:7, bracketed)', 'בצלו'), ('in the fear of the LORD (18:13)', 'בדחלתא דיי'), ('the words of My prophecy (18:18)', 'פתגמי נבואתי'), ('prophecy token', 'נבוא'), ('you shall accept (18:15)', 'תקבלון'), ('in wickedness — for presumptuously (17:12, 18:22)', 'ברשע'), ('acts wickedly — for presumes (18:20)', 'ירשע'), ('do not fear (18:22)', 'תדחל'), ('the Shekhinah', 'שכנתיה'), ('before the LORD', 'קדם יי'), ('the charmer (18:11)', 'רטין'), ('Ov as bidin (18:11)', 'בדין'), ('yidoni as zekhuru (18:11)', 'זכורו'), ('the scroll (17:18)', 'ספרא'), ('the great court / Sanhedrin', 'סנהדרין'), ('the judge (dayyana)', 'דינא'), ('a foreigner (17:15)', 'נוכרי'), ('the fourth stomach (18:3)', 'קבתא'), ('the Torah (oraita) tokens', 'אוריתא')]:
    s = SEATS(sub); print(f'  {name}: {len(s)} {s[:26]}')
for c, v in ((17, 5), (17, 6), (17, 7), (17, 12), (18, 2), (18, 7), (18, 8), (18, 13), (18, 18), (18, 19)): print(f'  {c}:{v} Aramaic:', ARM(c, v))
print('==== E. THE FRAMES AND THE REGISTER (computed on the morphology)')
MO = {(c, v): [(x, m) for x, m in by[('Deut', c, v)]] for c, v in SPAN}
print('  2mp/2ms per verse:', {f'{c}:{v}': (sum(1 for _, m in MO[(c, v)] if m and '2mp' in m), sum(1 for _, m in MO[(c, v)] if m and '2ms' in m)) for c, v in SPAN})
print('  infinitive absolutes:', [(c, v, x) for c, v in SPAN for x, m in MO[(c, v)] if m and re.search(r'V[a-zA-Z]a$', m)], '| wayyiqtol forms:', [(c, v, x) for c, v in SPAN for x, m in MO[(c, v)] if m and re.search(r'V[a-zA-Z]w', m)], '| imperatives:', [(c, v, x) for c, v in SPAN for x, m in MO[(c, v)] if m and re.search(r'V[a-zA-Z]v', m)], '| first person:', [(c, v, x, m) for c, v in SPAN for x, m in MO[(c, v)] if m and '1c' in m and m.startswith('HV')], '| participles:', [(c, v, x) for c, v in SPAN for x, m in MO[(c, v)] if m and re.search(r'V[a-zA-Z]r', m)])
print('  negations per verse:', {f'{c}:{v}': sum(1 for x in W(c, v) if x in ('לא', 'ולא')) for c, v in SPAN if any(x in ('לא', 'ולא') for x in W(c, v))}, '| "saying":', [f'{c}:{v}' for c, v in SPAN if 'לאמר' in W(c, v)], '| "so that" (למען):', [f'{c}:{v}' for c, v in SPAN if 'למען' in W(c, v)], '| "lest/that not" (לבלתי):', [f'{c}:{v}' for c, v in SPAN if any(x in ('לבלתי', 'ולבלתי') for x in W(c, v))])
for c in CHS:
    print(f'  chapter {c}: the Name bare / with lamed / "your God" pairs:', sum(1 for v in range(1, NV[c] + 1) for x in W(c, v) if x == 'יהוה'), sum(1 for v in range(1, NV[c] + 1) for x in W(c, v) if x == 'ליהוה'), [v for v in range(1, NV[c] + 1) if any(a == 'יהוה' and b == 'אלהיך' for a, b in zip(W(c, v), W(c, v)[1:]))], '| verses without the Name:', [v for v in range(1, NV[c] + 1) if not any('יהוה' in x for x in W(c, v))], '| "his God"/"my God":', [(v, x) for v in range(1, NV[c] + 1) for x in W(c, v) if x in ('אלהיו', 'אלהי')])
with contextlib.redirect_stdout(io.StringIO()):
    import register_census as RC
    _ink = RC.read_ink()
print('  the register on Deut 17-18 — receipts:', [k for k in RC.receipts(_ink) if k[0] == 'Deut' and k[1] in CHS], '| footers:', [x for x in RC.footers(_ink) if x[0][0] == 'Deut' and x[0][1] in CHS], '| headers:', [x for x in RC.register_headers(_ink) if x[0][0] == 'Deut' and x[0][1] in CHS], '| receipts in the book so far:', [k for k in RC.receipts(_ink) if k[0] == 'Deut' and k[1] <= 18], '| count lines:', ([k for k in RC.count_lines(_ink) if k[0] == 'Deut' and k[1] in CHS] if hasattr(RC, 'count_lines') else 'n/a'))
print('  THE PARSER on the two chapters:', {f'{c}:{v}': (CS_N, CS_O) for c, v, CS_N, CS_O in []})
with contextlib.redirect_stdout(io.StringIO()):
    import cold_run_sequence as CS
PARSE = {}
for c, v in SPAN:
    vw = CS.verse_words('Deut', c, v); n, o = CS.ink_numbers(vw), CS.ink_ordinals(vw); marked = [t for t in vw if t[-1] in '#~^%@|*']
    if n or o or marked: PARSE[(c, v)] = (n, o, marked)
print('  the parser\'s hits:', PARSE, '| 18:6 tokens as the parser sees them:', CS.verse_words('Deut', 18, 6)[:6], '| 17:2:', CS.verse_words('Deut', 17, 2)[:6])
print('==== F. THE PRIOR READS (computed from the ledgers)')
TRI = f'{ROOT}/logic/oral_triage'
LED = {f: open(f'{TRI}/{f}', encoding='utf-8').read() for f in os.listdir(TRI) if f.endswith('.md') and os.path.isfile(f'{TRI}/{f}') and f != os.path.basename(OUT)}
SPINE_PRIOR = sorted({(f, int(a), int(b)) for f, t in LED.items() for a, b in re.findall(r'Sifrei Devarim (\d+):(\d+)', t) if int(a) in PISKAOT})
OUT_PRIOR = sorted({(f, int(a), int(b)) for f, t in LED.items() for a, b in re.findall(r'Sifrei Devarim (\d+):(\d+)', t) if (int(a), int(b)) in OUTSIDE})
print('  spine rows read before:', SPINE_PRIOR, '| outside rows read before:', OUT_PRIOR)
print('  ledgers with an Onkelos row of Deut 17-34 or the Prophets (never read ahead — expected none):', sorted(f for f, t in LED.items() if re.search(r'^- Onkelos (?:Deut (?:1[7-9]|2\d|3\d)|Josh|Judg|1Sam|2Sam|1Kgs|2Kgs|Isa|Jer|Ezek):', t, re.M)))
KIN = [(f, len(re.findall(r'^- Onkelos ' + pat, LED[f], re.M))) for f, pat in [('deu_01_03_devarim_2026-09-15.md', r'Deut 1:'), ('deu_04_vaetchanan_2026-09-16.md', r'Deut 4:'), ('deu_05_vaetchanan_2026-09-16.md', r'Deut 5:'), ('deu_10_ekev_2026-09-19.md', r'Deut 10:'), ('deu_12_reeh_2026-09-20.md', r'Deut 12:'), ('deu_13_reeh_2026-09-21.md', r'Deut 13:'), ('deu_14_reeh_2026-09-21.md', r'Deut 14:'), ('deu_15_reeh_2026-09-22.md', r'Deut 15:'), ('lev_22_holy_food_offerings_2026-09-05.md', r'Lev 22:'), ('num_35_refuge_cities_2026-09-13.md', r'Num 35:'), ('num_18_priest_levite_dues_2026-09-10.md', r'Num 18:'), ('lev_07_fat_blood_dues_2026-09-03.md', r'Lev 7:'), ('lev_07_shelamim_types_2026-09-03.md', r'Lev 7:'), ('lev_07_asham_procedure_2026-09-03.md', r'Lev 7:'), ('lev_19_kedoshim_2026-09-05.md', r'Lev 19:'), ('lev_20_sanctions_2026-09-05.md', r'Lev 20:'), ('exo_22_property_social_2026-09-01.md', r'Exod 22:'), ('num_22_balak_bilam_call_2026-09-11.md', r'Num 22:'), ('num_23_oracles_1_2_2026-09-11.md', r'Num 23:')] if f in LED]
print('  the kin ledgers\' Onkelos row counts:', KIN, '| Exodus 18 / Exodus 20 ledgers with Onkelos rows (expected none — read through their spines in the law era):', sorted(f for f, t in LED.items() if re.search(r'^- Onkelos Exod (?:18|20):', t, re.M)))
print('  the store mismatches:', STORE_MISMATCH, '| token counts:', {c: sum(len(W(c, v)) for v in range(1, NV[c] + 1)) for c in CHS}, '| distinct glosses:', {c: len({g for (cc, v) in SG if cc == c for _, _, g in SG[(cc, v)]}) for c in CHS}, '| "?" glosses:', [(c, v, hp) for (c, v) in SG for _, hp, g in SG[(c, v)] if g == '?'])
print('THE LEAN MEASURE PRINTED')
