# THE SIFREI ROWS OF PISKAOT 147-149 (THE DEUTERONOMY WALK sitting 15 — CHAPTERS 17-18, LEAN, 2026-09-24): the blemish a prohibition, the order of offerings none,
# the blemish born and the blemish grown, the disqualified classes, the slaughtered not the slaughterer (147); "found" means witnesses, the gate where he was
# found, the seducers stoned, the man or the woman, the five names, the server and the bower, the host of heaven apportioned, "which I have not commanded"
# three words (148); the seven investigations, the probes, the sojourner and the woman, the gate again, the coerced, the stones (149). Every row READ WHOLE in
# both files (the whole-row rule); the prior reads REREAD WHOLE and marked; the cuts by ch17_ink.SP_ (the misses collected). Sitting 14's form.
from ch17_ink import *
S = {}
def srow(p, r, verdict, prose): S[(p, r)] = (verdict, prose)

srow(147, 1, 'MATERIAL', f'"YOU SHALL NOT SACRIFICE TO THE LORD YOUR GOD AN OX OR A SHEEP" (17:1) — R. JUDAH: MIGHT ONE WHO SLAUGHTERS A SIN OFFERING IN THE SOUTH TRANSGRESS A PROHIBITION? THE TEACHING SAYS "WHICH HAS A BLEMISH" — FOR THE BLEMISH HE TRANSGRESSES, NOT FOR THE SOUTH; THE SAGES: EVEN THE SOUTH. The head row of piska 147 ({SP_(147, 1, "השוחט", "חטאת", "בדרום")} "one who slaughters a sin offering in the south"; {SP_(147, 1, "על", "מום", "עובר", "בלא", "תעשה")} "for a blemish he transgresses a prohibition"): 17:1\'s prohibition ATTACHED TO THE BLEMISH ALONE by R. Judah and widened to the wrong place by the sages — the compile\'s cell a transgression keyed on the animal\'s state, the slaughter\'s place a dispute. Fresh.')
srow(147, 2, 'MATERIAL', f'MIGHT ONE WHO PUTS OFFERINGS BEFORE ONE ANOTHER — A BURNT OFFERING BEFORE A SIN OFFERING, A PASSOVER BEFORE THE DAILY, THE ADDITIONAL BEFORE THE DAILY — TRANSGRESS? THE TEACHING SAYS 12:17, 16:5, 17:1 — FOR THESE HE TRANSGRESSES; THE ORDER IS NO PROHIBITION. ({SP_(147, 2, "המקדים", "קדשים", "זה", "לזה")} "one who puts offerings before one another"; {SP_(147, 2, "ואין", "מקדים", "קדשים", "זה", "לזה", "עובר")} "and one who puts offerings before one another does not transgress"): the three "you may not" verses the true prohibitions, the sequence a rule without one (Mishnah Zevachim 10:1-2, Pesachim 5:1 the English\'s notes) — the compile\'s order parameter; read at chapter 12 for 12:17 and at chapter 16 for 16:5, now at its own head verse. REREAD WHOLE (chapters 12 and 16, deu_12_reeh and deu_16_reeh_shoftim).')
srow(147, 3, 'MATERIAL', f'"WHICH HAS A BLEMISH" — ONLY ONE BORN WHOLE AND MADE BLEMISHED; ONE BORN BLEMISHED FROM ITS MOTHER\'S WOMB — WHENCE? THE TEACHING SAYS "ANY EVIL THING". ({SP_(147, 3, "שנולד", "תם", "ונעשה", "בעל", "מום")} "that was born whole and became blemished"; {SP_(147, 3, "ממעי", "אמו")} "from its mother\'s womb"): THE CONGENITAL BLEMISH INCLUDED by "any evil thing" (the Sifrei reads "thing" where the verse of 15:21 reads "blemish" — the English\'s note) — the blemish\'s class a state whatever its onset (Bekhorot 6). REREAD WHOLE (chapter 15, deu_15_reeh).')
srow(147, 4, 'MATERIAL', f'WHENCE THE SCABBED, THE WARTED, THE LICHENED? "A BLEMISH, ANY EVIL THING". WHENCE THE OLD, THE SICK, THE FOUL? "AN OX OR A SHEEP … ANY EVIL THING". ({SP_(147, 4, "בעל", "גרב", "בעל", "יבלת", "ובעל", "חזזית")} "the scabbed, the warted and the lichened"; {SP_(147, 4, "לזקן", "וחולה", "ומזהם")} "the old, the sick and the foul"): the blemish\'s list widened past Leviticus 22:22-24 by the phrase "any evil thing" — two more classes for the compile\'s disqualification set (126:1\'s twin at 15:21). REREAD WHOLE (chapter 15, deu_15_reeh).')
srow(147, 5, 'MATERIAL', f'WHENCE THAT OFFERINGS SLAUGHTERED OUTSIDE THEIR TIME OR PLACE TRANSGRESS A PROHIBITION? "THING" — WHAT DEPENDS ON A THING. ({SP_(147, 5, "חוץ", "לזמנם", "וחוץ", "למקומם")} "outside their time and outside their place"; {SP_(147, 5, "דבר", "שתלוי", "בדבר")} "a thing that depends on a thing"): the intention-disqualifications (Zevachim 2:3 — pigul and the wrong place) hung on the one word "thing": the compile\'s offering states extended from the body to the act. Fresh.')
srow(147, 6, 'MATERIAL', f'WHENCE THE MOUNTER AND THE MOUNTED, THE SET-ASIDE AND THE WORSHIPPED? "IT IS AN ABOMINATION TO THE LORD YOUR GOD". WHENCE THE HARLOT\'S HIRE, THE DOG\'S PRICE, THE MIXED, THE TORN, THE CAESAREAN? "FOR IT IS AN ABOMINATION". R. JUDAH: IT IS AN ABOMINATION, ITS OFFSPRING IS NOT. ({SP_(147, 6, "לרובע", "ונרבע", "ומוקצה", "ונעבד")} "the mounter, the mounted, the set-aside and the worshipped"; {SP_(147, 6, "היא", "תועבה", "ואין", "הולד", "תועבה")} "it is an abomination and the offspring is not"): NINE DISQUALIFIED CLASSES from the one word "abomination" said twice (Temurah 6:1-3 the answer sheet; 261:2\'s dog\'s price the same word from 23:19) — the compile\'s set; the offspring\'s status a dispute. Fresh.')
srow(147, 7, 'MATERIAL', f'R. SIMEON: SINCE THE MOUNTER AND THE MOUNTED ARE DISQUALIFIED AMONG BEASTS, MIGHT THE MAN BE TOO? THE TEACHING SAYS "IT" — OF THE SACRIFICE I SPOKE, NOT OF THE SACRIFICER. ({SP_(147, 7, "בזבח", "דברתי", "ולא", "דברתי", "בזובח")} "of the sacrifice I spoke, and not of the sacrificer"): the disqualification on the animal, never on the offerer — the compile\'s effect\'s subject fixed by the pronoun "it". Fresh.')
srow(148, 1, 'MATERIAL', f'"WHEN THERE IS FOUND" (17:2) — BY WITNESSES; FROM 19:15\'S "BY THE MOUTH OF TWO WITNESSES OR THREE SHALL A MATTER STAND" A BUILDING FROM A FATHER: WHEREVER "FOUND" IS SAID, TWO OR THREE WITNESSES. The head row of piska 148 ({SP_(148, 1, "כי", "ימצא", "בעדים")} "when there is found — by witnesses"; {SP_(148, 1, "זה", "בנין", "אב")} "this is a building from a father"): "FOUND" A TERM OF EVIDENCE — the verb keyed to the witnesses\' number by 19:15 (ahead — never read ahead; the row recorded from its citation): the compile\'s trial condition, the two witnesses of 17:6 read into 17:2\'s first word. Fresh.')
srow(148, 2, 'MATERIAL', f'"IN YOUR MIDST, IN ONE OF YOUR GATES" — WHY? SINCE 17:5 SAYS "BRING THEM OUT TO YOUR GATES", I MIGHT HEAR THE GATE WHERE THEY WERE FOUND OR THE GATE WHERE THEY WERE JUDGED: "YOUR GATES" "YOUR GATES" AN ANALOGY BY THE SHARED WORD — THE GATE WHERE THEY WERE FOUND, NOT WHERE THEY WERE JUDGED. ({SP_(148, 2, "שער", "שנמצאו", "בו")} "the gate where they were found"; {SP_(148, 2, "ולא", "שער", "שנדונו", "בו")} "and not the gate where they were judged"): THE PLACE OF EXECUTION THE CITY OF THE CRIME, not of the court (Sanhedrin 6 the sheet; 149:4 the twin analogy) — the compile\'s stoning at the finding\'s gate: a place parameter on the tape\'s population. Fresh.')
srow(148, 3, 'MATERIAL', f'SINCE THE LED-ASTRAY DIE BY THE SWORD, MIGHT THE SEDUCERS TOO? THE TEACHING SAYS "THE MAN OR THE WOMAN … STONE THEM". ({SP_(148, 3, "שהנדחים", "בסיף")} "that the led-astray die by the sword"; {SP_(148, 3, "יכול", "אף", "המדיחים")} "might the seducers too"): the seducers of a city (13:16\'s sword for the seduced) STONED by 17:5 — chapter 13\'s cells given their penalty here: the compile\'s seducer effect read across the two chapters. Fresh.')
srow(148, 4, 'MATERIAL', f'SINCE A CITY IS NOT MADE A CITY LED ASTRAY BY ONE WITNESS NOR BY A WOMAN, MIGHT THEY BE EXEMPT? THE TEACHING SAYS "A MAN OR A WOMAN". ({SP_(148, 4, "לא", "על", "פי", "אחד", "ולא", "על", "פי", "אשה")} "not by the mouth of one nor by the mouth of a woman"): the single seducer\'s liability where the city\'s needs more — the individual\'s case keyed on "a man or a woman"; a woman\'s testimony refused (190:3 reads it from 17:6\'s "two"). Fresh.')
srow(148, 5, 'CONTEXT', f'"WHO DOES EVIL IN THE EYES OF THE LORD YOUR GOD, TRANSGRESSING HIS COVENANT" — CALLED FIVE NAMES: BANNED, ABOMINATION, HATED, DETESTED, PERVERSE; THE PLACE CALLS HIM FIVE: EVIL, COVENANT-BREAKER, BLASPHEMER, PROVOKER, REBEL; AND HE CAUSES FIVE: DEFILES THE LAND, PROFANES THE NAME, REMOVES THE SHEKHINAH, FELLS ISRAEL BY THE SWORD, EXILES THEM. ({SP_(148, 5, "קרוי", "חמשה", "שמות")} "called five names"; {SP_(148, 5, "ומסלק", "את", "השכינה")} "and removes the Shekhinah"): the idolater\'s fifteen words (Sifra Kedoshim 4:1\'s parallel) — the five effects the compile\'s ledger vocabulary already carries (the land, the Name, the Presence, the sword, the exile). Fresh.')
srow(148, 6, 'MATERIAL', f'ONLY THIS ONE? THE SERVER — WHENCE? "AND GOES AND SERVES OTHER GODS" (17:3); THE BOWER? "AND BOWS TO THEM, TO THE SUN OR THE MOON OR ALL THE HOST OF HEAVEN WHICH I HAVE NOT COMMANDED". ({SP_(148, 6, "עובד", "מנין")} "the server — whence"; {SP_(148, 6, "אף", "המשתחוה")} "even the bower"): the three acts — the transgressor, the server, the bower — each a liable act (17:3\'s three narrative-form verbs, asserted): the compile\'s three triggers. Fresh.')
srow(148, 7, 'MATERIAL', f'"TO SERVE THEM" (28:14) — TO INCLUDE THE ASSOCIATOR. ({SP_(148, 7, "להביא", "את", "המשתף")} "to include the associator"): one who joins the Name with another\'s — liable under 28:14\'s clause (ahead — the row recorded from its citation; never read ahead): the compile\'s idolatry effect widened to the partnered worship. Fresh.')
srow(148, 8, 'MATERIAL', f'R. YOSE THE GALILEAN: FROM 4:19\'S "WHICH THE LORD YOUR GOD APPORTIONED TO ALL THE PEOPLES" MIGHT HE HAVE APPORTIONED THEM TO THE NATIONS? THE TEACHING SAYS 29:25 "GODS THEY DID NOT KNOW AND HE HAD NOT APPORTIONED THEM". ({SP_(148, 8, "יכול", "שחלקם", "לאמות")} "might He have apportioned them to the nations"): the host of heaven APPORTIONED AS LIGHTS, NOT AS GODS — 4:19 read against 29:25 (the row read at chapter 4 for 4:19; 29:25 ahead): the compile\'s heavenly bodies a created kind, the nations\' worship of them unlicensed. REREAD WHOLE (chapter 4, deu_04_vaetchanan).')
srow(148, 9, 'CONTEXT', f'R. YOSE: MY SON ELAZAR SAYS THREE THINGS OF JEREMIAH 19:5 — "WHICH I COMMANDED NOT": IN THE TORAH; "NOR SPOKE": IN THE TEN WORDS; "NOR CAME INTO MY HEART": THAT A MAN SHOULD OFFER HIS SON ON THE ALTAR. ({SP_(148, 9, "בתורה")} "in the Torah"; {SP_(148, 9, "בעשרת", "הדברות")} "in the Ten Words"): 17:3\'s "which I have not commanded" (three seats in the Bible — here, Jeremiah 19:5, 7:31, asserted) read through Jeremiah\'s three clauses; the child-offering the Prophets\' case, 18:10\'s fire ahead. Fresh.')
srow(148, 10, 'CONTEXT', f'OTHERS: "WHICH I COMMANDED NOT" — JEPHTHAH; "NOR SPOKE" — MESHA KING OF MOAB; "NOR CAME INTO MY HEART" — THAT ABRAHAM SHOULD OFFER HIS SON ON THE ALTAR. ({SP_(148, 10, "על", "יפתח")} "of Jephthah"; {SP_(148, 10, "על", "מישע", "מלך", "מואב")} "of Mesha king of Moab"): the three clauses three cases — Jephthah\'s daughter, Mesha\'s son, Isaac (the tape\'s own Genesis 22 line): the binding never commanded, the compile\'s reading of the akedah\'s outcome. Fresh.')
srow(149, 1, 'MATERIAL', f'"AND IT IS TOLD YOU AND YOU HEAR AND INQUIRE WELL" (17:4), AND 13:15 SAYS "INQUIRE, SEARCH, ASK WELL" — "WELL" "WELL" AN ANALOGY: THEY EXAMINE HIM WITH SEVEN INVESTIGATIONS. INVESTIGATIONS ONLY? PROBES — WHENCE? "AND BEHOLD IT IS TRUE, THE THING IS CERTAIN". The head row of piska 149 ({SP_(149, 1, "היטב", "היטב", "לגזרה", "שוה")} "well, well — an analogy by the shared word"; {SP_(149, 1, "בשבע", "חקירות")} "with seven investigations"): THE SEVEN INVESTIGATIONS (Sanhedrin 5:1 — the sabbatical cycle, the year, the month, the day, the day of the week, the hour, the place) from the shared "well" of 13:15 and 17:4 (nine of thirteen tokens in order, asserted); the probes from "true and certain" — the compile\'s inquiry a fixed questionnaire (93:6 and 190:7 the twins). REREAD WHOLE (chapter 13, deu_13_reeh).')
srow(149, 2, 'MATERIAL', f'IF PROBES ARE INCLUDED, WHY SAY INVESTIGATIONS? INVESTIGATIONS — ONE SAID "I DO NOT KNOW", THEIR TESTIMONY VOID; PROBES — ONE SAID "I DO NOT KNOW", EVEN TWO, THE TESTIMONY STANDS; IN BOTH, WHEN THEY CONTRADICT EACH OTHER THE TESTIMONY IS VOID. ({SP_(149, 2, "עדותם", "בטלה")} "their testimony is void"; {SP_(149, 2, "עדותם", "קימת")} "their testimony stands"): THE TWO GRADES OF QUESTION with two outcomes for "I do not know" (Sanhedrin 5:1-2 the answer sheet) — the compile\'s testimony verdict a two-tier table. REREAD WHOLE (chapter 13, deu_13_reeh).')
srow(149, 3, 'MATERIAL', f'"IN ISRAEL" — ONLY ISRAEL; SOJOURNERS, WOMEN AND SLAVES — WHENCE? "BRING OUT THAT MAN OR THAT WOMAN" (17:5). ({SP_(149, 3, "גרים", "ונשים", "ועבדים", "מנין")} "sojourners, women and slaves — whence"): the accused\'s classes widened by "the man or the woman" — the compile\'s trial over the tape\'s whole population, not the native male alone. Fresh.')
srow(149, 4, 'MATERIAL', f'"TO YOUR GATES" (17:5) — I MIGHT HEAR THE GATE WHERE THEY WERE FOUND OR WHERE THEY WERE JUDGED: "YOUR GATES" "YOUR GATES" AN ANALOGY WITH 17:2 — WHERE THEY WERE FOUND, NOT WHERE THEY WERE JUDGED. ({SP_(149, 4, "נאמר", "כאן", "שעריך", "ונאמר", "להלן")} "said here your gates and said there"): 148:2\'s analogy run the other way (the English\'s note "virtually identical") — the place of the stoning settled twice, the same parameter. Fresh.')
srow(149, 5, 'MATERIAL', f'"THAT MAN" — NOT THE COERCED, NOT THE UNWITTING, NOT THE MISLED. ({SP_(149, 5, "ולא", "אנוס", "ולא", "שוגג", "ולא", "מטעה")} "and not the coerced, and not the unwitting, and not the misled"): three exclusions from the pronoun "that" — the compile\'s liability conditions (intent, knowledge, freedom; 155:8 the same three for the rebel). Fresh.')
srow(149, 6, 'MATERIAL', f'"THAT WOMAN" — NOT THE COERCED, NOT THE UNWITTING, NOT THE MISLED. ({SP_(149, 6, "ולא", "אנוסה", "ולא", "שוגגת", "ולא", "מוטעת")} "and not the coerced, the unwitting, the misled (fem.)"): the same three for the woman — the exclusions carried by each pronoun. Fresh.')
srow(149, 7, 'MATERIAL', f'"STONE THEM WITH STONES" — MANY STONES? LEVITICUS 20:27 SAYS "WITH A STONE"; ONE STONE? HERE "STONES": IF HE DID NOT DIE BY THE FIRST, LET HIM DIE BY THE SECOND. ({SP_(149, 7, "יכול", "באבנים", "מרבות")} "might it be with many stones"; {SP_(149, 7, "לא", "מת", "בראשונה", "ימות", "בשניה")} "if he did not die by the first, let him die by the second"): THE STONING\'S PROCEDURE from the two numbers (the singular of the medium\'s verse, the plural here — Sanhedrin 6:4): the compile\'s execution cell iterates. Fresh.')
print('the rows typed:', len(S), '| the cuts\' misses:', FAIL)
