# THE SIFREI ROWS OF PISKAOT 172-178 (THE DEUTERONOMY WALK sitting 15 — CHAPTERS 17-18, LEAN, 2026-09-24): the charmer of snake and scorpion, the medium from the
# armpit, the familiar spirit from the mouth, stoning for them and a warning for the asker, the necromancer and the skull (172); liable for one of them, the
# Canaanites warned, R. Eliezer's pity, whole and the portion, whole conditioned (173); the dispossession's reward, they have oracles and you have the Torah
# (174); the prophet from the land and the brothers, Jeremiah to the nations, obey him even against a commandment for the hour (175); Horeb's request earned
# the prophets, the words in his mouth and not face to face, the Holy Spirit, no interpreter, first things first (176); the six deaths — three by Heaven,
# three by the court (177); strangulation, Jeremiah against Hananiah and the test, no fear in prosecuting (178). Every row READ WHOLE in both files.
from ch17_ink import *
S = {}
def srow(p, r, verdict, prose): S[(p, r)] = (verdict, prose)

srow(172, 1, 'MATERIAL', f'"AND A CHARMER OF CHARMS" (18:11) — ONE WHO CHARMS MUCH AND ONE WHO CHARMS LITTLE ALIKE; ONE WHO CHARMS THE SNAKE AND THE SCORPION ALIKE. The head row of piska 172 ({SP_(172, 1, "ואחד", "חובר", "את", "הנחש", "ואת", "העקרב")} "and one who charms the snake and the scorpion alike"): the sixth agent noun — the charmer of beasts (the word\'s consonants "joined" elsewhere, the census\'s homographs): the compile\'s charm effect per act, any creature. Fresh.')
srow(172, 2, 'MATERIAL', f'(MISHNAH SANHEDRIN 7:7) "AND ONE WHO ASKS A GHOST" — THIS IS THE PYTHON WHO SPEAKS FROM HIS ARMPIT. ({SP_(172, 2, "זה", "פיתום", "המדבר", "משחיו")} "this is the python who speaks from his armpit"): THE MISHNAH CITED IN THE HEBREW ITSELF — the ghost-asker the ventriloquist (Leviticus 20:27\'s medium, the kin; ONKELOS "bidin" — a word the census finds seven times as other things, the homograph): the compile\'s medium defined by his method. Fresh.')
srow(172, 3, 'MATERIAL', f'"A FAMILIAR SPIRIT" — ONE WHO SPEAKS WITH HIS MOUTH. ({SP_(172, 3, "המדבר", "בפיו")} "one who speaks with his mouth"): the eighth agent noun — the "knower" (Leviticus 20:27\'s pair, asserted) by his mouth; ONKELOS "zekhuru" one seat (asserted). Fresh.')
srow(172, 4, 'MATERIAL', f'THEY THEMSELVES ARE STONED, AND THE ONE WHO ASKS THEM IS UNDER A WARNING. ({SP_(172, 4, "הם", "עצמם", "בסקילה")} "they themselves are by stoning"; {SP_(172, 4, "והנשאל", "בהם", "באזהרה")} "and the one asked of them is under a warning"): THE TWO PENALTIES — stoning for the medium and the spirit (Leviticus 20:27), a bare prohibition for the client (Sanhedrin 7:7; the row without a citation): the compile\'s two effects on two subjects. Fresh.')
srow(172, 5, 'MATERIAL', f'"AND ONE WHO INQUIRES OF THE DEAD" — ONE WHO RAISES BY HIS MEMBER AND ONE WHO ASKS A SKULL ALIKE; THE DIFFERENCE? THE RAISER — IT DOES NOT RISE IN ITS WAY AND IS NOT ASKED ON THE SABBATH; THE SKULL — IT RISES IN ITS WAY AND IS ASKED ON THE SABBATH. ({SP_(172, 5, "אחד", "המעלה", "בזכורו", "ואחד", "הנשאל", "בגלגלת")} "one who raises by his member and one who asks a skull alike"; {SP_(172, 5, "ונשאל", "בשבת")} "and is asked on the Sabbath"): THE NECROMANCER\'S TWO METHODS and their Sabbath difference (the English\'s three renderings of the first) — "of the dead" three seats in the Bible (here, Isaiah 8:19, Ecclesiastes 9:3, asserted): the compile\'s ninth bar two-armed. Fresh.')
srow(173, 1, 'MATERIAL', f'"FOR AN ABOMINATION TO THE LORD IS EVERYONE WHO DOES THESE" (18:12) — MIGHT HE NOT BE LIABLE UNTIL HE TRANSGRESSES ALL? "EVERYONE WHO DOES THESE" — EVEN ONE OF THEM. The head row of piska 173 ({SP_(173, 1, "עד", "שיעבור", "על", "כלם")} "until he transgresses all of them"; {SP_(173, 1, "אפלו", "על", "אחת", "מהם")} "even for one of them"): THE LIST DISJUNCTIVE — each of the nine its own liability ("an abomination of the LORD" the Torah\'s eight, asserted): the compile\'s nine effects independent. Fresh.')
srow(173, 2, 'CONTEXT', f'"AND BECAUSE OF THESE ABOMINATIONS THE LORD YOUR GOD DISPOSSESSES THEM" — R. SIMEON: TEACHES THAT THE CANAANITES WERE WARNED OF ALL THESE, FOR NONE IS PUNISHED UNLESS WARNED. WHEN R. ELIEZER REACHED THIS VERSE HE SAID: A PITY ON US! IF ONE WHO CLINGS TO UNCLEANNESS HAS A SPIRIT OF UNCLEANNESS REST ON HIM, ONE WHO CLINGS TO THE SHEKHINAH — IS IT NOT LOGIC THAT THE HOLY SPIRIT REST ON HIM? AND WHAT CAUSED IT? "YOUR SINS SEPARATED YOU FROM YOUR GOD" (ISAIAH 59:2). ({SP_(173, 2, "שהוזהרו", "כנענים", "על", "כל", "המעשים", "האלו")} "that the Canaanites were warned of all these deeds"; {SP_(173, 2, "חבל", "עלינו")} "a pity on us"): THE NATIONS WARNED — the warning-before-punishment rule extended to the Canaanites (Tosefta Avodah Zarah 8:6; the nations\' ledger carries the bar): R. Eliezer\'s a fortiori (I1, checked in MIDDOT.md) from the unclean spirit to the holy: the compile\'s dispossession effect grounded on a warned bar. Fresh.')
srow(173, 3, 'MATERIAL', f'"WHOLE SHALL YOU BE WITH THE LORD YOUR GOD" (18:13) — WHEN YOU ARE WHOLE, YOUR PORTION IS WITH THE LORD YOUR GOD; SO DAVID SAID "I WALK IN MY WHOLENESS — REDEEM ME" (PSALM 26:11), "IN MY WHOLENESS YOU UPHELD ME" (41:13). ({SP_(173, 3, "כשאתה", "תם", "חלקך", "עם", "ה", "אלהיך")} "when you are whole, your portion is with the LORD your God"): "WHOLE" as "innocent" (the assonance the English\'s note) and "with" as one\'s portion — ONKELOS "in the fear of the LORD" (two seats: 4:4, here, asserted): the compile\'s wholeness a state on Israel\'s ledger the diviners\' bar keeps; 18:13 the verse the psalms echo (one token shared with Noah\'s and Abraham\'s "whole", asserted). Fresh.')
srow(173, 4, 'MATERIAL', f'"WHOLE SHALL YOU BE WITH THE LORD YOUR GOD" — IF YOU DID ALL SAID IN THE MATTER, YOU ARE WHOLE TO THE LORD YOUR GOD. ({SP_(173, 4, "אם", "עשית", "כל", "האמור", "בענין")} "if you did all that is said in the matter"): the trope again (156:1, 160:1, 162:3) — wholeness CONDITIONED on the whole passage: the state\'s condition the nine bars kept. Fresh.')
srow(174, 1, 'MATERIAL', f'"FOR THESE NATIONS WHICH YOU DISPOSSESS" (18:14) — DO THE COMMANDMENT SAID IN THE MATTER, FOR BY ITS REWARD YOU DISPOSSESS THESE NATIONS. The head row of piska 174 ({SP_(174, 1, "שבשכרה", "אתה", "יורש", "את", "הגוים", "האלה")} "for by its reward you dispossess these nations"): the entry formula\'s fourth seat — the dispossession the bar\'s reward (9:5\'s "for the wickedness of these nations" the kin, five tokens shared, asserted). Fresh.')
srow(174, 2, 'MATERIAL', f'"TO SOOTHSAYERS AND TO DIVINERS THEY HEARKEN" — LEST YOU SAY: THEY HAVE SOMETHING TO ASK AND I HAVE NOT? "BUT YOU — NOT SO: THE LORD YOUR GOD HAS GIVEN YOU". "GIVEN YOU" — TO YOU IT WAS GIVEN, AND YOU LEAVE THE WORDS OF TORAH AND BUSY YOURSELF WITH ITS NULLIFYING? ({SP_(174, 2, "להם", "יש", "במה", "להשאל", "ולי", "אין", "לי")} "they have something to ask and I have not"; {SP_(174, 2, "לך", "נתנה")} "to you it was given"): THE TORAH THE ORACLE ISRAEL HAS — "not so has the LORD your God given you" read as the given thing (the English\'s note: an insertion out of sequence): the nations\' oracles against the given Torah — the compile\'s Israel asks the Torah\'s daemon, not the diviners\'; 18:15\'s prophet the next verse\'s answer. Fresh.')
srow(175, 1, 'MATERIAL', f'"A PROPHET FROM YOUR MIDST" (18:15) — AND NOT FROM OUTSIDE THE LAND; "OF YOUR BROTHERS" — NOT FROM OTHERS; "THE LORD YOUR GOD WILL RAISE UP FOR YOU" — NOT FOR THE NATIONS. THEN HOW "A PROPHET TO THE NATIONS I MADE YOU" (JEREMIAH 1:5)? ONE WHO BEHAVES LIKE THE NATIONS. The head row of piska 175 ({SP_(175, 1, "ולא", "מחוצה", "לארץ")} "and not from outside the land"; {SP_(175, 1, "ולא", "לגוים")} "and not for the nations"; {SP_(175, 1, "בנוהג", "מנהג", "גוים")} "one who behaves in the nations\' way"): THE PROPHET\'S THREE CONDITIONS THE KING\'S (157:4-5\'s "from among, your brothers" — the same two words, the same two exclusions; "a prophet from your midst like me" one seat, asserted) — and Jeremiah\'s commission resolved: the compile\'s prophet daemon\'s subject an Israelite of the land, its audience Israel. Fresh.')
srow(175, 2, 'MATERIAL', f'"TO HIM YOU SHALL HEARKEN" — EVEN IF HE TELLS YOU TO TRANSGRESS ONE OF THE COMMANDMENTS SAID IN THE TORAH, LIKE ELIJAH ON MOUNT CARMEL — FOR THE HOUR — OBEY HIM. ({SP_(175, 2, "עבר", "על", "אחת", "מן", "המצוות")} "transgress one of the commandments"; {SP_(175, 2, "לפי", "שעה", "שמע", "לו")} "for the hour — obey him"): THE PROPHET OVERRIDES A COMMANDMENT FOR THE HOUR (Elijah\'s altar outside the place — 1 Kings 18 the run\'s case; Yevamot 90b the segment if a cell needs it): "you (pl.) shall hearken" (the verse\'s one plural, asserted); ONKELOS "you shall accept": the compile\'s prophet effect a temporary override of the place\'s bar — a parameter with a duration. Fresh.')
srow(176, 1, 'MATERIAL', f'"ACCORDING TO ALL YOU ASKED OF THE LORD YOUR GOD AT HOREB" (18:16) — BY THIS THEY MERITED THAT PROPHETS STAND FOR THEM: "LET ME NOT HEAR AGAIN THE VOICE OF THE LORD MY GOD". The head row of piska 176 ({SP_(176, 1, "בזו", "זכו", "שיעמדו", "להם", "נביאים")} "by this they merited that prophets stand for them"): THE REQUEST AT HOREB THE PROPHETS\' CAUSE — 18:16 retells 5:25 (four tokens in order "to hear the voice of the LORD", asserted; "the day of the assembly" the book\'s three): a REFERENCE row to the tape\'s Deuteronomy 5 lines (the readback\'s grain): the compile\'s prophet daemon installed by the people\'s own word. Fresh.')
srow(176, 2, 'MATERIAL', f'"AND THE LORD SAID TO ME: THEY HAVE DONE WELL IN WHAT THEY SPOKE" (18:17) — THEY MATCHED MY MIND: "A PROPHET I WILL RAISE UP FOR THEM" (18:18). YOU LEARN THAT BY THE REWARD OF THE FEAR THEY FEARED, THEY MERITED PROPHETS. ({SP_(176, 2, "כונו", "לדעתי")} "they matched My mind"; {SP_(176, 2, "שבשכר", "יראה", "שיראו")} "that by the reward of the fear they feared"): "they have done well" (18:17 with 5:28, five in order, asserted) — the one divine frame of the two chapters (asserted) inside Moses\' retelling; the fear rewarded (Mekhilta Bachodesh 9): the prophet an effect of Horeb\'s fear on the tape. Fresh.')
srow(176, 3, 'MATERIAL', f'"AND I WILL PUT MY WORDS IN HIS MOUTH" (18:18) — MY WORDS I PUT IN HIS MOUTH, BUT I DO NOT SPEAK WITH HIM FACE TO FACE. ANOTHER WORD: FROM HERE ON, KNOW HOW THE HOLY SPIRIT IS PUT IN THE PROPHETS\' MOUTH. ({SP_(176, 3, "אבל", "איני", "מדבר", "עמו", "פנים", "בפנים")} "but I do not speak with him face to face"; {SP_(176, 3, "היאך", "רוח", "הקדש", "נתנת", "בפי", "הנביאים")} "how the Holy Spirit is put in the prophets\' mouth"): "LIKE YOU" WITH ONE DIFFERENCE — the words in the mouth, not face to face (34:10\'s "whom the LORD knew face to face", asserted; "My words in his mouth" one seat, "in your mouth" Jeremiah 1:9\'s); ONKELOS "the words of My PROPHECY" (the book\'s one "prophecy", asserted): the compile\'s prophet a channel, Moses the exception — the mode a parameter. Fresh.')
srow(176, 4, 'MATERIAL', f'"AND HE SHALL SPEAK TO THEM" — NOT TO SEAT AN INTERPRETER. ({SP_(176, 4, "שלא", "להושיב", "את", "התורגמן")} "not to seat the interpreter"): the prophet speaks directly — no interpreter (the sages\' own office beside the reader) between him and the people. Fresh.')
srow(176, 5, 'MATERIAL', f'"ALL THAT I COMMAND HIM" — HE SAYS THE FIRST FIRST AND THE LAST LAST. ({SP_(176, 5, "אומר", "על", "ראשון", "ראשון", "ועל", "אחרון", "אחרון")} "he says on the first, first, and on the last, last"): the prophet\'s ORDER (Avot 5:7\'s trait of the wise) — the message delivered in its sequence: the compile\'s prophet output ordered. Fresh.')
srow(177, 1, 'MATERIAL', f'"AND THE MAN WHO DOES NOT HEARKEN TO MY WORDS" (18:19) — THREE DIE BY HEAVEN\'S HAND: WHO SUPPRESSES HIS PROPHECY, LIKE JONAH; WHO WAIVES A PROPHET\'S WORDS, LIKE MICAH\'S FELLOW; A PROPHET WHO TRANSGRESSES HIS OWN WORDS, LIKE IDDO. AND THREE BY THE COURT: WHO PROPHESIES WHAT HE DID NOT HEAR, LIKE ZEDEKIAH BEN CHENAANAH; WHAT WAS NOT SAID TO HIM, LIKE HANANIAH BEN AZZUR — WHO HEARD JEREMIAH IN THE UPPER MARKET AND PROPHESIED IT IN THE LOWER; AND WHO PROPHESIES IN THE NAME OF IDOLATRY — EVEN IF HE MATCHED THE LAW, TO DECLARE THE UNCLEAN UNCLEAN AND THE CLEAN CLEAN. The one row of piska 177 ({SP_(177, 1, "שלשה", "מיתתם", "בידי", "שמים")} "three — their death by the hand of Heaven"; {SP_(177, 1, "ושלשה", "מיתתם", "בבית", "דין")} "and three — their death in court"; {SP_(177, 1, "אפלו", "כון", "את", "ההלכה")} "even if he matched the law"): THE SIX DEATHS OF THE PROPHET\'S LAW — three by Heaven from 18:19 ("I will require it" — ONKELOS "My Memra will require", asserted), three by the court from 18:20 (Sanhedrin 11:5-6, Tosefta 14:14-15): Jonah, Micah\'s fellow, Iddo, Zedekiah, Hananiah — the Prophets\' cases, never rows; the sixth ABSOLUTE — the idol\'s prophet dies even speaking the true law (the code/data law\'s mirror: the source, not the content, graded): the compile\'s prophet daemon\'s six verdicts. Fresh.')
srow(178, 1, 'MATERIAL', f'"BUT THE PROPHET WHO PRESUMES TO SPEAK A WORD IN MY NAME … SHALL DIE" (18:20) — AN UNSPECIFIED DEATH SAID IN THE TORAH IS STRANGULATION. The head row of piska 178 ({SP_(178, 1, "בסתם", "מיתה", "האמורה", "בתורה", "בחנק")} "an unspecified death said in the Torah — by strangulation"): 155:7\'s default for the false prophet — the rebel elder and the false prophet the same death by the same rule ("the prophet shall die" one seat, asserted; ONKELOS "acts wickedly" for "presumes", one seat): the compile\'s execution default reused. Fresh.')
srow(178, 2, 'MATERIAL', f'"AND IF YOU SAY, HOW SHALL WE KNOW THE WORD" (18:21) — YOU WILL SAY IT: JEREMIAH SAID "THE VESSELS OF THE HOUSE GO TO BABYLON" (27:22) AND HANANIAH "THE VESSELS RETURN FROM BABYLON" (27:16) — WHOM SHALL I HEED? THE TEACHING SAYS (18:22) "WHAT THE PROPHET SPEAKS IN THE LORD\'S NAME AND IT IS NOT AND COMES NOT, THAT IS THE WORD THE LORD HAS NOT SPOKEN". WHICH WORD DID THE PLACE SPEAK? THE ONE HE SAYS AND IT COMES. "PRESUMPTUOUSLY THE PROPHET SPOKE IT" — FOR PRESUMPTION HE IS LIABLE, NOT FOR ERROR. ({SP_(178, 2, "עתידים", "אתם", "לומר", "איכה", "נדע", "הדבר")} "you will one day say, how shall we know the word"; {SP_(178, 2, "ואיני", "יודע", "למי", "אשמע")} "and I do not know whom to heed"; {SP_(178, 2, "זה", "שאומר", "ובא")} "the one he says and it comes"): THE TEST OF THE WORD BY ITS COMING — Jeremiah against Hananiah the run\'s case (18:22 shares three tokens with Jeremiah 28:9, asserted): A LAW WHOSE VERDICT WAITS ON THE TAPE\'S FUTURE — the prophet\'s word graded when its event arrives (the readback\'s question, THE_LOOP step 6); "presumptuously" 155:3\'s condition again (the noun\'s two Torah seats, asserted): the compile\'s prophet cell a deferred verdict with an intent condition. Fresh.')
srow(178, 3, 'MATERIAL', f'"YOU SHALL NOT FEAR HIM" — DO NOT HOLD YOURSELF BACK FROM ARGUING HIS GUILT. ({SP_(178, 3, "אל", "תמנע", "עצמך", "מללמד", "עליו", "חובה")} "do not hold yourself back from arguing his guilt"): the last clause a duty on the WITNESS — the fear of the prophet no bar to prosecuting him (one seat; 150:2-3\'s bars on arguing guilt the contrast): the compile\'s prosecution effect unblocked. Fresh.')
print('the rows typed:', len(S), '| the cuts\' misses:', FAIL)
