# THE SIFREI ROWS OF PISKAOT 179-183 (THE DEUTERONOMY WALK sitting 16 — CHAPTERS 19-21, LEAN, 2026-09-24): the nations cut off by your merit, build where you
# will (179); cities not fortresses, for yourself not for others, within the land not on the border, highways, the two rows of the vineyard, the trans-Jordan,
# no exile from city to city (180); the killer honored, the pursuer and the avenger, the hot heart, "there" three times, "his neighbor" three times, R. Judah's
# yesterday two and the day before three (181); the forest a place of free access, wood-chopping optional (182); the tree that fell, the iron from the wood
# being split, the stone and the head, the avenger's commandment, the court warned (183 — HEADLESS, read whole from the export). Every row READ WHOLE in both
# files (the whole-row rule); the prior reads REREAD WHOLE and marked; the cuts by ch19_ink.SP_ (the misses collected). Sitting 15's form.
from ch19_ink import *
S = {}
def srow(p, r, verdict, prose): S[(p, r)] = (verdict, prose)

srow(179, 1, 'MATERIAL', f'"WHEN THE LORD YOUR GOD CUTS OFF THE NATIONS" (19:1) — BY YOUR MERIT. The head row of piska 179 ({SP_(179, 1, "בזכותך")} "by your merit"): the conquest\'s condition read out of 19:1\'s opening — the compile\'s entry status carries the merit as its ground (9:4-6\'s "not for your righteousness" the twin the spine leaves aside). Fresh.')
srow(179, 2, 'MATERIAL', f'"AND YOU INHERIT THEM AND DWELL IN THEIR CITIES AND HOUSES" — MIGHT YOU NOT BE FREE TO ADD TO THE BUILDING? THE TEACHING SAYS 12:29 "AND DWELL IN THEIR LAND" — WHEREVER YOU WISH TO BUILD, BUILD. ({SP_(179, 2, "להוסיף", "על", "הבנין")} "to add to the building"; {SP_(179, 2, "בנה")} "build!"): the same row as 80:3 on 12:29 read the other way — the dwelling in their cities no bar on building. REREAD WHOLE (chapter 12, deu_12_reeh).')
srow(180, 1, 'MATERIAL', f'"THREE CITIES" (19:2) — CITIES, NOT FORTRESSES; CITIES, NOT GREAT TOWNS; CITIES, NOT VILLAGES. ({SP_(180, 1, "ערים", "ולא", "טירים")} "cities and not fortresses"; {SP_(180, 1, "ערים", "ולא", "כפרים")} "cities and not villages"): the refuge city\'s CLASS — a middle size, walled but not a metropolis (Makkot 10a the Talmud\'s reasons, not opened) — the compile\'s parameter on the city\'s kind. Fresh.')
srow(180, 2, 'MATERIAL', f'"SEPARATE FOR YOURSELF" — AND NOT FOR OTHERS. ({SP_(180, 2, "ולא", "לאחרים")} "and not for others"): the cities Israel\'s — the sojourner-killer\'s case decided at 181:5 (the resident alien excluded) — the compile\'s scope parameter. Fresh.')
srow(180, 3, 'MATERIAL', f'"IN THE MIDST OF YOUR LAND" — AND NOT ON THE BORDER. ({SP_(180, 3, "ולא", "בספר")} "and not on the frontier"): the placement inside the land (the frontier\'s cities excluded — Makkot 2:4\'s "on the border" is not opened). Fresh.')
srow(180, 4, 'MATERIAL', f'"WHICH THE LORD YOUR GOD GIVES YOU TO INHERIT" — WHAT YOU WILL INHERIT, CONQUER. ({SP_(180, 4, "מה", "שתירש", "תכבש")} "what you inherit, you conquer"): the gift formula\'s clause read as the conquest\'s duty — the same line at 12:29\'s twin. Fresh.')
srow(180, 5, 'MATERIAL', f'"PREPARE FOR YOURSELF THE WAY" (19:3) — PREPARE HIGHWAYS THAT LEAD STRAIGHT INTO IT. ({SP_(180, 5, "סטרטיאות")} "highways (the Greek strata)"): THE ROADS to the refuge cities an obligation on the public — Makkot 10b\'s signposts, not opened; the compile\'s effect on the land (the way prepared). Fresh.')
srow(180, 6, 'MATERIAL', f'"AND DIVIDE THE BORDER OF YOUR LAND INTO THREE" — NOT SCATTERED BUT ALIGNED, LIKE TWO ROWS IN A VINEYARD. ({SP_(180, 6, "מכונות")} "aligned"; {SP_(180, 6, "כשתי", "שורות", "שבכרם")} "like two rows in the vineyard"): 19:3\'s "divide into three" (the parser reads [3]) is a GEOMETRY — the three cities at equal thirds, the six in two rows (Makkot 9b, not opened) — the compile\'s placement rule. Fresh.')
srow(180, 7, 'MATERIAL', f'"WHICH THE LORD YOUR GOD GIVES YOU TO INHERIT" — TO INCLUDE THE OTHER SIDE OF THE JORDAN. ({SP_(180, 7, "לרבות", "עבר", "הירדן")} "to include the other side of the Jordan"): the three beyond the Jordan (4:41-43, Moses\' own — already on the tape) inside the law\'s "your land"; the compile\'s status on the trans-Jordan. Fresh.')
srow(180, 8, 'MATERIAL', f'"THAT EVERY MANSLAYER MAY FLEE THERE" — THAT HE BE NOT EXILED FROM CITY TO CITY. ({SP_(180, 8, "גולה", "מעיר", "לעיר")} "exiled from city to city"): the refuge FINAL — one city holds him (183:4 and 259:5 repeat it; Makkot 2:8 the answer sheet at 181:1); the compile\'s effect: the killer\'s status set once. Fresh.')
srow(181, 1, 'MATERIAL', f'"AND THIS IS THE MATTER OF THE MANSLAYER" (19:4) — FROM HERE YOU SAY (MAKKOT 2:8): A MANSLAYER WHO IS EXILED FROM CITY TO A CITY OF REFUGE — the Mishnah cited BY NAME in the Hebrew ({SP_(181, 1, "רוצח", "שגולה", "מעיר", "לעיר", "מקלט")} "a manslayer exiled from a city to a city of refuge"): THE FIRST EXAM ROW (Makkot 2:8 — the killer honored by the city must say "I am a killer"; the English supplies the Mishnah\'s bulk in brackets); the compile\'s case on the refuge\'s honor. Fresh.')
srow(181, 2, 'MATERIAL', f'"LEST THE AVENGER OF BLOOD PURSUE THE MANSLAYER" (19:6) — I HAVE ONLY THE PURSUER WHO IS THE AVENGER; A PURSUER NOT THE AVENGER, AN AVENGER NOT PURSUING, NEITHER — THE TEACHING SAYS "MANSLAYER, MANSLAYER" TO INCLUDE. ({SP_(181, 2, "רודף", "ולא", "גואל")} "a pursuer and not an avenger"; {SP_(181, 2, "רצח", "רצח", "רבה")} "manslayer, manslayer — an inclusion"): the doubled noun at 19:4 and 19:6 an INCLUSION (the middah of the repeated word) — the killer protected from any pursuer; the compile\'s pursuer parameter widened. Fresh.')
srow(181, 3, 'MATERIAL', f'"FOR HIS HEART IS HOT" — I HAVE ONLY ONE WHOSE HEART IS HOT; THE FATHER FOR THE SON AND THE SON FOR THE FATHER? "MANSLAYER, MANSLAYER" INCLUDES. ({SP_(181, 3, "חמות", "הלב")} "heat of the heart"; {SP_(181, 3, "האב", "את", "הבן", "והבן", "את", "האב")} "the father for the son and the son for the father"): the avenger\'s state of mind no condition on the refuge — the same inclusion a second time. Fresh.')
srow(181, 4, 'MATERIAL', f'WHY "THERE, THERE, THERE" THREE TIMES (NUMBERS 35:6, 11, 15)? THERE HIS DWELLING, THERE HIS DEATH, THERE HIS BURIAL. ({SP_(181, 4, "שם", "תהא", "דירתו")} "there shall be his dwelling"; {SP_(181, 4, "שם", "תהא", "קבורתו")} "there shall be his burial"): Numbers 35\'s three "there"s read at Deuteronomy\'s law — Makkot 2:7 (the English\'s note): the killer\'s dwelling, death and burial in the city; the compile\'s status until the high priest\'s death (Numbers 35:25 — the refuge runner\'s own timer). Fresh.')
srow(181, 5, 'MATERIAL', f'WHY "HIS NEIGHBOR" THREE TIMES? TO EXCLUDE OTHERS; TO EXCLUDE THE RESIDENT ALIEN; THE TORAH ALREADY CALLED HIM NEIGHBOR — "WHO STRIKES HIS NEIGHBOR UNKNOWINGLY, NOT HATING HIM": IF HE HATED HIM, HE IS NOT EXILED. ({SP_(181, 5, "פרט", "לאחרים")} "to exclude others"; {SP_(181, 5, "פרט", "לגר", "תושב")} "to exclude the resident alien"; {SP_(181, 5, "אם", "שונא", "לו", "אינו", "גולה")} "if he hates him he is not exiled"): the refuge\'s PERSONS (Makkot 2:3 the English\'s note) and the hatred bar — the compile\'s two parameters (the killer\'s class; the prior hatred). Fresh.')
srow(181, 6, 'MATERIAL', f'"FROM YESTERDAY AND THE DAY BEFORE" — R. JUDAH: YESTERDAY, TWO; THE DAY BEFORE, THREE. ({SP_(181, 6, "תמול", "שנים")} "yesterday — two"; {SP_(181, 6, "שלשם", "שלשה")} "the day before — three"): THE CLOCK OF PRIOR HATRED — three days (the goring ox\'s phrase at Exodus 21:29, the measure\'s find: one clock for the beast\'s warning and the man\'s enmity) — the compile\'s parameter in days. Fresh.')
srow(182, 1, 'MATERIAL', f'"WHO COMES WITH HIS NEIGHBOR INTO THE FOREST" (19:5) — AS THE FOREST IS A PLACE THE INJURED AND THE INJURER MAY BOTH ENTER, SO ANY SUCH PLACE; THE HOUSEHOLDER\'S COURTYARD EXCLUDED. ({SP_(182, 1, "רשות", "לנזק", "ולמזיק")} "permission for the injured and the injurer"; {SP_(182, 1, "יצאת", "חצר", "של", "בעל", "הבית")} "the householder\'s courtyard is excluded"): THE PLACE\'S CLASS — free access to both (Makkot 2:2 the English\'s note; Bava Kamma\'s "domain" law reused) — the compile\'s parameter on where the unwitting killing counts. Fresh.')
srow(182, 2, 'MATERIAL', f'"TO CHOP WOOD" — ABBA SAUL: AS WOOD-CHOPPING IS OPTIONAL, SO ANY OPTIONAL ACT; THE FATHER BEATING HIS SON, THE MASTER HIS DISCIPLE, THE COURT\'S AGENT ARE EXCLUDED. ({SP_(182, 2, "מה", "חטיבת", "עצים", "רשות")} "as wood-chopping is optional"; {SP_(182, 2, "ושליח", "בית", "דין")} "and the court\'s agent"): THE ACT\'S CLASS — a commanded act\'s accident is no refuge case (Makkot 2:2) — the compile\'s parameter on the act (optional / commanded). Fresh.')
srow(183, 1, 'MATERIAL', f'"AND HIS HAND SLIPS WITH THE AX TO CUT THE TREE" — FROM HERE: HE MEANT TO CUT THE TREE AND IT FELL ON A MAN AND KILLED HIM — HE IS EXILED. The headless piska\'s first row ({SP_(183, 1, "נתכון", "לקוץ", "את", "האילן")} "he intended to cut the tree"; {SP_(183, 1, "הרי", "זה", "גולה")} "this one is exiled"): the falling tree the unwitting case — the compile\'s first exemplar of "unknowingly". Fresh.')
srow(183, 2, 'MATERIAL', f'"AND THE IRON SLIPS FROM THE WOOD" — THE WOOD BEING SPLIT; RABBI: FROM THE WOOD THAT IS SPLIT. ({SP_(183, 2, "המבקע")} "the splitting one (the handle)"; {SP_(183, 2, "מן", "העץ", "המתבקע")} "from the wood that is being split"): THE TWO READINGS OF "THE WOOD" — the handle or the log (Makkot 7b\'s dispute, not opened): the compile\'s dispute flag on the iron\'s source (the verdict "exiled" either way at the Sifrei; the Mishnah\'s split a data row). Fresh.')
srow(183, 3, 'MATERIAL', f'"AND FINDS" — ONE ALREADY THERE. FROM HERE R. ELIEZER B. JACOB: IF AFTER THE STONE LEFT HIS HAND THE OTHER PUT OUT HIS HEAD AND RECEIVED IT — HE IS EXEMPT. ({SP_(183, 3, "ומצא", "במצוי")} "and finds — one already present"; {SP_(183, 3, "הרי", "זה", "פטור")} "this one is exempt"): the victim who ENTERS the blow\'s path after the throw — no exile (Makkot 2:2 the English\'s note; 8a\'s bar) — the compile\'s timing parameter (the victim present at the release). Fresh.')
srow(183, 4, 'MATERIAL', f'"HE SHALL FLEE TO ONE OF THESE CITIES AND LIVE" — THAT HE BE NOT EXILED FROM CITY TO CITY. ({SP_(183, 4, "גולה", "מעיר", "לעיר")} "exiled from city to city"): 180:8\'s rule at its second seat, "and live" the ground (a repeat the English marks — the same teaching on 19:3 and 19:5). Fresh.')
srow(183, 5, 'MATERIAL', f'"LEST THE AVENGER OF BLOOD PURSUE THE MANSLAYER" (19:6) — A COMMANDMENT IN THE AVENGER\'S HAND TO PURSUE. ({SP_(183, 5, "מצוה", "ביד", "גואל", "הדם", "לרדף")} "a commandment in the avenger\'s hand to pursue"): THE AVENGER\'S PURSUIT A DUTY, not a permission (Makkot 2:7 / 12a the dispute, not opened) — the compile\'s avenger an ACTOR with a commanded act. Fresh.')
srow(183, 6, 'MATERIAL', f'"FOR HIS HEART IS HOT — AND HE HATED HIM NOT" — IF HE HATED HIM, HE IS NOT EXILED. ({SP_(183, 6, "הא", "אם", "שונא", "אינו", "גולה")} "so if he hated him he is not exiled"): the hatred bar at 19:6 as at 19:4 (181:5) — the killer who hated is handed to the avenger (19:11-12), no refuge. Fresh.')
srow(183, 7, 'MATERIAL', f'"FROM YESTERDAY AND THE DAY BEFORE" — THIS IS WHAT R. JUDAH SAYS: YESTERDAY TWO, THE DAY BEFORE THREE. ({SP_(183, 7, "תמול", "שנים")} "yesterday — two"; {SP_(183, 7, "שלשום", "שלשה")} "the day before — three"): 181:6\'s clock at 19:6\'s seat (the full spelling shilshom here, the defective at 19:4 — the ink\'s two spellings). Fresh.')
srow(183, 8, 'MATERIAL', f'"THEREFORE I COMMAND YOU, SAYING" (19:7) — TO WARN THE COURT ABOUT THIS. ({SP_(183, 8, "להזהיר", "בית", "דין", "על", "כך")} "to warn the court about this"): "saying" (the one at 19:7) read as the COURT\'S charge — the three cities the court\'s duty to separate (186:1 the same form for the innocent blood); the compile\'s addressee the court. Fresh.')
