# THE SIFREI ROWS OF PISKAOT 205-210 (THE DEUTERONOMY WALK sitting 16 — CHAPTERS 19-21, LEAN, 2026-09-24; RUN 2): the slain one found and the rite's
# cessation when murderers multiplied (Sotah 9:9 in the spine's own Hebrew), slain not strangled, on the ground not buried, fallen not hanged, in the field
# not floating, beyond the Jordan, R. Elazar against R. Yose b. R. Judah, known and unknown, R. Akiva's court that saw, the elders two and the judges two
# (five or three), the measuring from the slain to the cities, the head and the body, the border and the gentile city (205); the nearest of the near, two
# cities and Jerusalem, the elders of that city, the heifer's age, rinsing by elders and atonement by priests, the yoke (206); the obligation of that city's
# elders, the rough valley, the cleaver from behind, the place barred from sowing and working, the beheading learned to the firstling ass, the valley even if
# not rough (207); the priests the sons of Levi — the blemished included, the blessing standing like the service, disputes and plagues by day and not by kin,
# one priest sees the plague (208); all the elders even a hundred, the washing in the valley (209); the holy tongue, our hands did not shed, the priests say,
# the living and the dead, the redemption's condition, the Holy Spirit's answer, purge the evildoers (210). Every row READ WHOLE; the prior read REREAD WHOLE
# and marked (208:1 at chapters 17-18); the cuts by ch19_ink.SP_. Sitting 15's form.
from ch19_ink import *
S = {}
def srow(p, r, verdict, prose): S[(p, r)] = (verdict, prose)

srow(205, 1, 'MATERIAL', f'"WHEN ONE IS FOUND SLAIN" (21:1) — AND NOT AT A TIME WHEN IT IS COMMON. FROM HERE THEY SAID (SOTAH 9:9): WHEN MURDERERS MULTIPLIED THE BROKEN-NECKED HEIFER CEASED — WHEN ELAZAR B. DINAI CAME, AND TECHINAH B. PERISHAH; HE WAS CALLED "SON OF THE MURDERER". ({SP_(205, 1, "ולא", "בשעה", "שמצוי")} "and not at a time when it is common"; {SP_(205, 1, "מכן", "אמרו", "סוטה")} "from here they said (Sotah)"; {SP_(205, 1, "משרבו", "הרצחנים", "בטלה", "עגלה", "ערופה")} "when murderers multiplied the broken-necked heifer ceased"): THE RITE\'S CESSATION IS THE MISHNAH INSIDE THE SPINE by tractate name (the third such row of the three chapters) — a run citation for the compile (the rite\'s condition "not known" fails when killers are known); Sotah 9:9 the answer sheet\'s last row. Fresh.')
srow(205, 2, 'MATERIAL', f'"SLAIN" — AND NOT STRANGLED; "SLAIN" — AND NOT STILL WRITHING. ({SP_(205, 2, "חלל", "ולא", "חנוק")} "slain and not strangled"; {SP_(205, 2, "ולא", "מפרפר")} "and not writhing"): THE VICTIM\'S CLASS — a stabbed corpse, not a strangled one and not a dying one (Sotah 9:2\'s list) — the compile\'s first condition on the rite. Fresh.')
srow(205, 3, 'MATERIAL', f'"ON THE GROUND" — AND NOT BURIED UNDER A HEAP. ({SP_(205, 3, "באדמה", "ולא", "טמון", "בגל")} "on the ground and not hidden in a heap"): the second condition. Fresh.')
srow(205, 4, 'MATERIAL', f'"FALLEN" — AND NOT HANGING ON A TREE. ({SP_(205, 4, "נפל", "ולא", "תלוי", "באילן")} "fallen and not hanging on a tree"): the third condition (the hanged of 21:22 the chapter\'s other tree). Fresh.')
srow(205, 5, 'MATERIAL', f'"IN THE FIELD" — AND NOT FLOATING ON THE FACE OF THE WATER. ({SP_(205, 5, "בשדה", "ולא", "צף", "על", "פני", "המים")} "in the field and not floating on the face of the water"): the fourth condition — Sotah 9:2 the answer sheet (the English\'s "=M. Sotah 9:2"). Fresh.')
srow(205, 6, 'MATERIAL', f'"WHICH THE LORD YOUR GOD GIVES YOU" — TO INCLUDE BEYOND THE JORDAN. ({SP_(205, 6, "לרבות", "עבר", "הירדן")} "to include beyond the Jordan"): THE RITE\'S TERRITORY includes the two and a half tribes\' land (the gift formula read as inclusion — 4:41-43\'s cities the same land) — the compile\'s territory parameter. Fresh.')
srow(205, 7, 'MATERIAL', f'R. ELAZAR SAYS: FOR ALL OF THEM THEY BROKE THE NECK. R. YOSE B. R. JUDAH SAID TO HIM: IF HE WAS ONLY STRANGLED AND CAST IN THE FIELD, WOULD THEY BREAK THE NECK? RATHER, FOR ALL OF THEM — IF HE WAS SLAIN. ({SP_(205, 7, "בכלם", "היו", "עורפים")} "for all of them they broke the neck"; {SP_(205, 7, "אלא", "בכלם", "אם", "היה", "חלל", "עורפים")} "rather, for all of them if he was slain they break the neck"): the dispute over the four exclusions — R. Elazar takes the four as illustrations, R. Yose keeps "slain" as the one condition and lets the other three fall (the row without a citation in either file); the compile keeps the four (Sotah 9:2) and notes the dissent. Fresh.')
srow(205, 8, 'MATERIAL', f'"IT IS NOT KNOWN WHO STRUCK HIM" — BUT IF IT IS KNOWN WHO STRUCK HIM, EVEN IF ONE OF THEM SAW HIM, THEY DID NOT BREAK THE NECK. ({SP_(205, 8, "הא", "אם", "נודע", "מי", "הכהו")} "but if it is known who struck him"; {SP_(205, 8, "ואפלו", "אחד", "מהן", "ראהו")} "and even if one of them saw him"; {SP_(205, 8, "לא", "היו", "עורפים")} "they did not break the neck"): THE UNKNOWN KILLER IS THE RITE\'S GATE — one witness (even one, who cannot convict) cancels the rite (Sotah 9:1\'s scope) — the compile\'s condition read from the verse\'s own clause. Fresh.')
srow(205, 9, 'MATERIAL', f'R. AKIVA SAYS: WHENCE THAT IF THE COURT SAW HIM KILL AND DID NOT RECOGNIZE HIM, THEY DID NOT BREAK THE NECK? "AND THEY SHALL ANSWER AND SAY: OUR HANDS HAVE NOT SHED THIS BLOOD" (21:7). ({SP_(205, 9, "ראוהו", "בית", "דין", "שהרג")} "the court saw him kill"; {SP_(205, 9, "ולא", "היו", "מכירים", "אותו")} "and did not recognize him"): the court\'s own sight cancels the rite though the killer is unidentified — the declaration "our eyes did not see" read as a condition the court must be able to swear (the English: Tosefta Sotah 9:2). Fresh.')
srow(205, 10, 'MATERIAL', f'"AND YOUR ELDERS SHALL GO OUT" (21:2) — "YOUR ELDERS" TWO, "AND YOUR JUDGES" TWO; A COURT IS NOT EVEN, THEY ADD ONE MORE: FIVE — R. JUDAH\'S WORDS. R. SHIMON SAYS: "YOUR ELDERS AND YOUR JUDGES" TWO, ADD ONE: THREE. ({SP_(205, 10, "זקניך", "שנים", "ושפטיך", "שנים")} "your elders two, and your judges two"; {SP_(205, 10, "אין", "בית", "דין", "שקול")} "a court is not even"; {SP_(205, 10, "הרי", "כאן", "חמשה")} "here are five"; {SP_(205, 10, "הרי", "כאן", "שלשה")} "here are three"): THE MEASURING COURT\'S SIZE — five (R. Judah) or three (R. Shimon), both from the plural and the odd-court rule (Sotah 9:1 the answer sheet, the great court\'s delegation) — the compile\'s court-size parameter with the dispute. Fresh.')
srow(205, 11, 'MATERIAL', f'"AND THEY SHALL MEASURE TO THE CITIES" — FROM THE SLAIN TO THE CITIES, NOT FROM THE CITIES TO THE SLAIN. THE HEAD IN ONE PLACE AND THE BODY IN ANOTHER: THE HEAD TO THE BODY (R. ELIEZER), THE BODY TO THE HEAD (R. AKIVA). FOUND NEAR THE BORDER, OR A CITY WITH GENTILES, OR A CITY WITHOUT A COURT — THEY DID NOT MEASURE. ({SP_(205, 11, "מן", "החלל", "אל", "הערים")} "from the slain to the cities"; {SP_(205, 11, "מוליכים", "את", "הראש", "אצל", "הגוף")} "they bring the head to the body"; {SP_(205, 11, "נמצא", "סמוך", "לספר")} "found near the border"; {SP_(205, 11, "לא", "היו", "מודדים")} "they did not measure"): THE MEASURE\'S ORIGIN AND THE THREE CITIES THAT DO NOT COUNT (Sotah 9:3-4 with Tosefta Sotah 9:1) — the compile\'s measuring cell: the origin the corpse (the navel per the Mishnah, not in this row), the candidate cities Israelite courts only. Fresh.')
srow(206, 1, 'MATERIAL', f'"AND IT SHALL BE THE CITY NEAREST" (21:3) — THE NEAREST OF THE NEAR. FROM HERE THEY SAID (SOTAH 9:2): FOUND EXACTLY BETWEEN TWO CITIES — BOTH BRING TWO HEIFERS (R. ELIEZER); THE SAGES: ONE CITY BRINGS, TWO CITIES DO NOT BRING TWO, AND JERUSALEM BRINGS NO BROKEN-NECKED HEIFER. ({SP_(206, 1, "הקרובה", "שבקרובות")} "the nearest of the near"; {SP_(206, 1, "נמצא", "מכון", "בין", "שתי", "עיירות")} "found exactly between two cities"; {SP_(206, 1, "עיר", "אחת", "מביאה")} "one city brings"; {SP_(206, 1, "ואין", "ירושלם", "מביאה", "עגלה", "ערופה")} "and Jerusalem brings no broken-necked heifer"): THE TIE CASE AND JERUSALEM\'S EXEMPTION — the Mishnah cited in the spine\'s Hebrew a second time (Sotah 9:2) — the compile\'s tie rule (the sages) and the city without a tribal portion excluded. Fresh.')
srow(206, 2, 'MATERIAL', f'"AND THE ELDERS OF THAT CITY SHALL TAKE" — AND NOT THE ELDERS OF JERUSALEM. ({SP_(206, 2, "ולא", "זקני", "ירושלם")} "and not the elders of Jerusalem"): Jerusalem\'s exemption restated on the elders. Fresh.')
srow(206, 3, 'MATERIAL', f'"A HEIFER OF THE HERD" — R. ELIEZER: A HEIFER IN ITS FIRST YEAR, A COW IN ITS SECOND; THE SAGES: A HEIFER IN ITS SECOND, A COW IN ITS THIRD OR FOURTH. ANOTHER READING: A HEIFER OF THE HERD — TWO TRAITS: TWO YEARS OLD AND OF THE HERD. ({SP_(206, 3, "עגלה", "בת", "שנתה", "ופרה", "בת", "שתים")} "a heifer of its first year and a cow of two"; {SP_(206, 3, "עגלה", "בת", "שתים", "ופרה", "בת", "שלש", "ובת", "ארבע")} "a heifer of two, a cow of three or four"; {SP_(206, 3, "שיהא", "בה", "שני", "דרכים")} "that it have two ways"): THE HEIFER\'S AGE beside the red cow\'s (Parah 1:1 the answer sheet — the English) — the compile\'s age parameter, the sages\' two years. Fresh.')
srow(206, 4, 'MATERIAL', f'ANOTHER READING: WASHING BY THE ELDERS AND ATONEMENT BY THE PRIESTS. ({SP_(206, 4, "רחיצה", "בזקנים", "וכפרה", "בכהנים")} "washing by the elders and atonement by the priests"): THE TWO ACTORS OF THE RITE\'S CLOSE — the elders wash (21:6), the priests say "atone" (21:8; Onkelos writes their name into the verse) — the compile\'s two speakers. Fresh.')
srow(206, 5, 'MATERIAL', f'"WHICH HAS NOT BEEN WORKED" — ANY WORK; WHENCE A YOKE? "WHICH HAS NOT DRAWN IN A YOKE". ({SP_(206, 5, "כל", "עבודה")} "any work"; {SP_(206, 5, "מנין", "בעול")} "whence a yoke"): the heifer\'s two disqualifiers, work of any kind and the yoke drawn (the red cow\'s twin condition, Numbers 19:2) — the compile\'s heifer conditions. Fresh.')
srow(207, 1, 'MATERIAL', f'"AND THE ELDERS OF THAT CITY SHALL BRING DOWN" (21:4) — THE OBLIGATION IS ON THE ELDERS OF THAT CITY. ({SP_(207, 1, "מצוה", "בזקני", "העיר", "ההיא")} "the obligation is on the elders of that city"): the nearest city\'s elders the rite\'s actors (not the measuring court). Fresh.')
srow(207, 2, 'MATERIAL', f'"TO A ROUGH VALLEY" — AS IT SOUNDS, HARD; YET EVEN IF NOT ROUGH, IT IS FIT. ({SP_(207, 2, "כמשמעו", "קשה")} "as it sounds, hard"; {SP_(207, 2, "שאינו", "איתן", "כשר")} "if it is not rough it is fit"): THE VALLEY\'S HARDNESS A PREFERENCE, NOT A CONDITION (Sotah 9:5\'s dispute in the background) — the compile\'s note. Fresh.')
srow(207, 3, 'MATERIAL', f'THEY BREAK ITS NECK WITH A CLEAVER FROM BEHIND, AND ITS PLACE IS FORBIDDEN FOR SOWING AND WORKING. MIGHT COMBING FLAX AND CUTTING STONES THERE BE FORBIDDEN? "WHICH IS NOT WORKED AND NOT SOWN" — SOWING WAS IN THE RULE AND WENT OUT TO TEACH: WORK OF THE SOIL, NOT THESE. ({SP_(207, 3, "עורפים", "אותה", "בקופיץ", "מאחוריה")} "they break its neck with a cleaver from behind"; {SP_(207, 3, "ומקומה", "אסור", "מלזרוע", "ומלעבוד")} "and its place is forbidden for sowing and working"; {SP_(207, 3, "לסרוק", "שם", "פשתן")} "to comb flax there"; {SP_(207, 3, "שהיא", "עבודת", "קרקע")} "which is work of the soil"): THE MANNER AND THE PLACE\'S BAN — the cleaver from behind (Sotah 9:5), the ground barred from soil-work only (the particular that went out teaches the class — the walk\'s middah) — the compile\'s manner and the place\'s status. Fresh.')
srow(207, 4, 'MATERIAL', f'"AND THEY SHALL BREAK ITS NECK THERE" — NECK-BREAKING IS SAID HERE AND SAID THERE (EXODUS 13:13): AS HERE — A CLEAVER FROM BEHIND, BURIAL, FORBIDDEN FOR BENEFIT — SO THERE. ({SP_(207, 4, "נאמר", "כאן", "עריפה", "ונאמר", "להלן")} "neck-breaking is said here and said there"; {SP_(207, 4, "וקוברה", "ואסורה", "בהניה")} "and buries it, and it is forbidden for benefit"): THE FIRSTLING ASS LEARNS FROM THE HEIFER by the shared word (the ink\'s eight seats of the root: the heifer twice, the ass twice) — a REFERENCE teacher in the spine for the two rites\' one manner; the compile\'s heifer cell writes burial and the benefit ban. Fresh.')
srow(207, 5, 'MATERIAL', f'"IN THE VALLEY" — EVEN IF IT IS NOT ROUGH. ({SP_(207, 5, "בנחל", "אף", "על", "פי", "שאינו", "איתן")} "in the valley, even if it is not rough"): 207:2 restated on the second "valley". Fresh.')
srow(208, 1, 'MATERIAL', f'"AND THE PRIESTS THE SONS OF LEVI SHALL COME NEAR" (21:5) — FROM "AND HE SHALL SERVE IN THE NAME OF THE LORD" (18:7) I HAVE ONLY THE UNBLEMISHED; THE BLEMISHED WHENCE? "THE SONS OF LEVI". "FOR THE LORD CHOSE THEM TO SERVE HIM AND TO BLESS" — THE PRIESTLY BLESSING IS NOT FIT IN THE BLEMISHED. ({SP_(208, 1, "אין", "לי", "אלא", "תמימים")} "I have only the unblemished"; {SP_(208, 1, "בעלי", "מומים", "מנין")} "the blemished whence"; {SP_(208, 1, "מגיד", "שאין", "ברכת", "כהנים", "כשרה", "בבעלי", "מומים")} "it tells that the priests\' blessing is not fit in the blemished"): THE BLEMISHED PRIEST STANDS AT THE HEIFER BUT NOT AT THE BLESSING — the row read at 18:7 for the priest\'s standing; the compile\'s presence condition (any son of Levi) with the blessing\'s exclusion. REREAD WHOLE (chapters 17-18, deu_17_18_shoftim).')
srow(208, 2, 'MATERIAL', f'"TO SERVE HIM AND TO BLESS IN THE NAME OF THE LORD" — THE BLESSING IS LIKENED TO THE SERVICE: AS THE SERVICE STANDING, SO THE BLESSING STANDING. ({SP_(208, 2, "מקיש", "ברכה", "לשרות")} "it likens the blessing to the service"; {SP_(208, 2, "מה", "שרות", "בעמידה", "אף", "ברכה", "בעמידה")} "as the service standing, so the blessing standing"): the standing posture of the blessing by the verse\'s pairing (Sotah 38a\'s source) — the compile\'s note on the priests\' posture. Fresh.')
srow(208, 3, 'MATERIAL', f'"AND BY THEIR WORD SHALL EVERY DISPUTE AND EVERY PLAGUE BE" — DISPUTES LIKENED TO PLAGUES: PLAGUES BY DAY, SO DISPUTES BY DAY; DISPUTES NOT BY RELATIVES, SO PLAGUES NOT BY RELATIVES. ({SP_(208, 3, "מקיש", "ריבים", "לנגעים")} "it likens disputes to plagues"; {SP_(208, 3, "מה", "נגעים", "ביום", "אף", "ריבים", "ביום")} "as plagues by day, so disputes by day"; {SP_(208, 3, "שלא", "בקרובים")} "not by relatives"): THE VERSE\'S PAIR TEACHES BOTH WAYS — the courts\' daytime (Sanhedrin 4:1) and the plague-examiner\'s non-kinship (Negaim 2:5) from one clause — the compile\'s two parameters, the daytime already the courts\' (17:8\'s "every plague of confinement" the Onkelos word). Fresh.')
srow(208, 4, 'MATERIAL', f'OR: AS DISPUTES BY THREE, SO PLAGUES BY THREE? IT IS REASONABLE — IF HIS MONEY BY THREE, HIS BODY NOT BY THREE? "OR TO ONE OF HIS SONS THE PRIESTS" (LEVITICUS 13:2) — ONE PRIEST SEES THE PLAGUES. ({SP_(208, 4, "אם", "ממונו", "בשלשה", "גופו")} "if his money by three, his body"; {SP_(208, 4, "שכהן", "אחד", "רואה", "את", "הנגעים")} "that one priest sees the plagues"): the analogy stopped by the explicit verse — one priest suffices for the plague — the compile\'s examiner-count parameter (Leviticus 13:2 the teacher). Fresh.')
srow(209, 1, 'MATERIAL', f'"AND ALL THE ELDERS OF THAT CITY" (21:6) — EVEN IF THEY ARE A HUNDRED. SINCE WE SAID THREE AND FIVE, MIGHT IT BE SO HERE? "ALL THE ELDERS OF THAT CITY" — EVEN A HUNDRED. ({SP_(209, 1, "ואפלו", "הם", "מאה")} "and even if they are a hundred"; {SP_(209, 1, "שלשה", "וחמשה")} "three and five"): THE WASHERS ARE ALL THE CITY\'S ELDERS, unlike the measurers\' three or five (205:10) — the compile\'s two bodies distinguished. Fresh.')
srow(209, 2, 'MATERIAL', f'"THEY SHALL WASH THEIR HANDS OVER THE BROKEN-NECKED HEIFER IN THE VALLEY" — OVER THE PLACE OF ITS NECK-BREAKING. MIGHT THEY GO UP FROM THE VALLEY AND SPEAK? "IN THE VALLEY" — THEIR ANSWERING AND SAYING IN THE VALLEY. ({SP_(209, 2, "על", "מקום", "עריפתה", "של", "עגלה")} "over the place of the heifer\'s neck-breaking"; {SP_(209, 2, "שתהא", "עניתם", "ואמירתם", "בנחל")} "that their answering and saying be in the valley"): the washing and the declaration both at the spot — the compile\'s place condition for the rite\'s close. Fresh.')
srow(210, 1, 'MATERIAL', f'"AND THEY SHALL ANSWER AND SAY" (21:7) — IN THE HOLY TONGUE. ({SP_(210, 1, "בלשון", "הקדש")} "in the holy tongue"): THE DECLARATION\'S LANGUAGE (Sotah 7:2 lists it among the Hebrew-only recitals; the English\'s Sifrei Numbers 39 parallel) — the compile\'s language parameter. Fresh.')
srow(210, 2, 'MATERIAL', f'"OUR HANDS HAVE NOT SHED" — WOULD IT ENTER OUR MINDS THAT THE COURT\'S ELDERS ARE SHEDDERS OF BLOOD? RATHER: HE DID NOT COME TO OUR HANDS AND WE SENT HIM OFF WITHOUT FOOD, WE DID NOT SEE HIM AND LEAVE HIM WITHOUT ESCORT. ({SP_(210, 2, "שזקני", "בית", "דין", "שופכי", "דמים", "הם")} "that the court\'s elders are shedders of blood"; {SP_(210, 2, "ופטרנוהו", "בלא", "מזונות")} "and sent him off without food"; {SP_(210, 2, "והנחנוהו", "בלא", "לויה")} "and left him without escort"): THE DECLARATION\'S MEANING — the elders swear to provisions and escort, not to innocence of the killing (Sotah 9:6 the answer sheet) — the compile\'s declaration text. Fresh.')
srow(210, 3, 'MATERIAL', f'"THE PRIESTS SAY: ATONE FOR YOUR PEOPLE ISRAEL" (21:8). ({SP_(210, 3, "הכהנים", "אומרים", "כפר", "לעמך", "ישראל")} "the priests say: atone for your people Israel"): THE SUBJECTLESS "ATONE" GIVEN ITS SPEAKER — the spine says it as Onkelos writes it into the verse (the ink\'s find 4; Sotah 9:6) — the compile\'s second speaker. Fresh.')
srow(210, 4, 'MATERIAL', f'WHEN IT SAYS "WHOM YOU REDEEMED, LORD" — THIS ATONEMENT ATONES FOR THOSE WHO WENT OUT OF EGYPT. ({SP_(210, 4, "שכפרה", "זו", "מכפרת", "על", "יוצאי", "מצרים")} "that this atonement atones for those who went out of Egypt"): the redemption clause reaches back to the exodus generation — a narrative reach of the rite. Fresh.')
srow(210, 5, 'MATERIAL', f'"ATONE FOR YOUR PEOPLE" — THESE ARE THE LIVING. ({SP_(210, 5, "אלו", "החיים")} "these are the living"): the two clauses two objects. Fresh.')
srow(210, 6, 'MATERIAL', f'"WHOM YOU REDEEMED" — THESE ARE THE DEAD; IT TELLS THAT THE DEAD NEED ATONEMENT. WE LEARN THAT THE SHEDDER OF BLOOD SINS BACK TO THOSE WHO WENT OUT OF EGYPT. ({SP_(210, 6, "אלו", "המתים")} "these are the dead"; {SP_(210, 6, "שהמתים", "צריכים", "כפרה")} "that the dead need atonement"; {SP_(210, 6, "ששופך", "דמים", "חוטא", "עד", "יוצאי", "מצרים")} "that the shedder of blood sins back to those who went out of Egypt"): the dead atoned for — a theology of the verse, a narrative reach. Fresh.')
srow(210, 7, 'MATERIAL', f'"WHOM YOU REDEEMED" — ON THIS CONDITION YOU REDEEMED US, THAT THERE BE NO SHEDDERS OF BLOOD AMONG US. ANOTHER READING: ON THIS CONDITION, THAT IF WE SIN YOU ATONE FOR US. ({SP_(210, 7, "על", "מנת", "כן", "פדיתנו")} "on this condition you redeemed us"; {SP_(210, 7, "שלא", "יהיו", "בינינו", "שופכי", "דמים")} "that there be no shedders of blood among us"; {SP_(210, 7, "שאם", "נחטא", "אתה", "מכפר", "עלינו")} "that if we sin you atone for us"): the redemption\'s two conditions — the theology of the priests\' plea. Fresh.')
srow(210, 8, 'MATERIAL', f'AND THE HOLY SPIRIT SAYS: WHENEVER YOU DO THUS, THE BLOOD IS ATONED FOR YOU. ({SP_(210, 8, "ורוח", "הקדש", "אומרת")} "and the Holy Spirit says"; {SP_(210, 8, "כל", "זמן", "שתעשו", "ככה")} "whenever you do thus"; {SP_(210, 8, "הדם", "מתכפר", "לכם")} "the blood is atoned for you"): THE VERSE\'S LAST CLAUSE IS THE ANSWER, NOT THE PRIESTS\' WORDS (Sotah 9:6: "they need not say it — the Holy Spirit announces it") — the compile\'s atonement effect written by the rite\'s completion (the row with no citation in either file). Fresh.')
srow(210, 9, 'MATERIAL', f'"AND YOU SHALL PURGE" (21:9) — PURGE THE DOERS OF EVIL FROM ISRAEL. ({SP_(210, 9, "בער", "עושי", "הרעות", "מישראל")} "purge the doers of evil from Israel"): THE PURGE FORMULA\'S THIRD FORM, "the innocent blood", read as persons once more (the ink\'s find 3; Onkelos "the shedders") — the compile\'s effect at the rite\'s end. Fresh.')
