# THE SIFREI ROWS OF PISKAOT 216-218 (THE DEUTERONOMY WALK sitting 16 — CHAPTERS 19-21, LEAN, 2026-09-24; RUN 2): inheritances fall by day, the expected and
# the held, the father cannot make a firstborn, the head and most of the body, the hated's firstborn (216); recognized to others and the father believed,
# double of one share not of the whole (the two arguments and the day's verse), Jacob's extra portion and Reuben's right to Joseph, not the expected, the
# man's strength not the woman's, the right through judges (217); a man's son not a woman's, not a daughter, not a grown man and the minor exempt, stubborn
# twice and rebellious, judged by his end and not on the Sabbath, the three pairs, R. Josiah's three pardons, the lamp and the analogy to gluttony and theft,
# lashes before three (218). Every row READ WHOLE; the cuts by ch19_ink.SP_. Sitting 15's form.
from ch19_ink import *
S = {}
def srow(p, r, verdict, prose): S[(p, r)] = (verdict, prose)

srow(216, 1, 'MATERIAL', f'"AND IT SHALL BE ON THE DAY HE GIVES HIS SONS TO INHERIT" (21:16) — BY DAY THEY LET INHERITANCES FALL, NOT BY NIGHT. ({SP_(216, 1, "ביום", "מפילים", "נחלות", "ואין", "מפילים", "נחלות", "בלילה")} "by day they let inheritances fall and not by night"): THE INHERITANCE\'S CLOCK — the estate\'s division a daytime act (Bava Batra 113b: the judges\' act, hence by day — 217:8) — the compile\'s daytime condition. Fresh.')
srow(216, 2, 'MATERIAL', f'"THAT WHICH HE HAS" — THE SON TAKES IN THE EXPECTED AS IN THE HELD. ({SP_(216, 2, "שהבן", "נוטל", "בראוי", "כבמחזק")} "that the son takes in the expected as in the held"): the ordinary son\'s share covers what is due to the estate; the firstborn\'s does not (217:6 — Bekhorot 8:9 the answer sheet) — the compile\'s two estates (held, expected). Fresh.')
srow(216, 3, 'MATERIAL', f'"HE CANNOT MAKE FIRSTBORN" — HE HAS NO RIGHT TO; MIGHT IT BE THAT IF HE DID, IT IS DONE? "HE CANNOT" — IF HE DID, IT IS NOT DONE. ({SP_(216, 3, "שאינו", "רשי", "לבכר")} "that he is not permitted to make firstborn"; {SP_(216, 3, "הא", "אם", "בכר", "אינו", "מבכר")} "but if he did, it is not made firstborn"): THE FATHER\'S TRANSFER VOID — not merely forbidden (Bava Batra 8:5: "my firstborn son shall not take double" — his words are nothing) — the compile\'s invalid-act verdict. Fresh.')
srow(216, 4, 'MATERIAL', f'"THE SON OF THE LOVED" — ONCE HIS HEAD AND MOST OF HIM CAME OUT ALIVE, HE EXEMPTS THE ONE AFTER HIM FROM THE FIRSTBORN\'S RIGHT. ({SP_(216, 4, "כיון", "שיצא", "ראשו", "ורבו", "בחיים")} "once his head and most of him came out alive"; {SP_(216, 4, "פוטר", "את", "הבא", "אחריו", "מן", "הבכורה")} "he exempts the one after him from the firstborn\'s right"): THE FIRSTBORN\'S MOMENT — the head and most of the body alive (Niddah 3:5\'s birth definition; Bekhorot 8:1 on the inheritance\'s firstborn "the first of his strength" even by a different mother) — the compile\'s birth event. Fresh.')
srow(216, 5, 'MATERIAL', f'"BEFORE THE SON OF THE HATED, THE FIRSTBORN" — EVEN THOUGH THE FIRSTBORN SON IS THE HATED WIFE\'S. ({SP_(216, 5, "אף", "על", "פי", "שבן", "הבכור", "לשנואה")} "even though the firstborn son is the hated one\'s"): the bar holds against the father\'s preference. Fresh.')
srow(217, 1, 'MATERIAL', f'"FOR THE FIRSTBORN, THE SON OF THE HATED, HE SHALL RECOGNIZE" (21:17) — MAKE HIM RECOGNIZED TO OTHERS: A MAN IS BELIEVED TO SAY "THIS IS MY FIRSTBORN SON". R. JUDAH: AS HE IS BELIEVED FOR THAT, SO TO SAY "THIS IS A DIVORCEE\'S SON, THIS A HALUTZAH\'S SON"; THE SAGES: HE IS NOT BELIEVED. ({SP_(217, 1, "יכירנו", "לאחרים")} "he shall make him recognized to others"; {SP_(217, 1, "שנאמן", "אדם", "לומר", "זה", "בני", "בכור")} "that a man is believed to say: this is my firstborn son"; {SP_(217, 1, "זה", "בן", "גרושה", "וזה", "בן", "חלוצה")} "this is a divorcee\'s son and this a released widow\'s son"; {SP_(217, 1, "וחכמים", "אומרים", "אינו", "נאמן")} "and the sages say: he is not believed"): THE FATHER\'S WORD ON THE FIRSTBORN CREDITED — the recognition a testimony (Bava Batra 8:6; Kiddushin 78b the dispute on the disqualified son) — the compile\'s witness parameter: the father for the firstborn, disputed for disqualification. Fresh.')
srow(217, 2, 'MATERIAL', f'"TO GIVE HIM DOUBLE" — DOUBLE OF ONE, OR DOUBLE OF ALL THE PROPERTY? YOU REASON: HE INHERITS WITH ONE AND WITH FIVE; WITH ONE — DOUBLE OF HIM; SO WITH FIVE — DOUBLE OF ONE OF THEM. ({SP_(217, 2, "פי", "שנים", "בו")} "double of him"; {SP_(217, 2, "או", "פי", "שנים", "בכל", "הנכסים")} "or double of all the property"; {SP_(217, 2, "הואיל", "ונוחל", "עם", "אחד", "ונוחל", "עם", "חמשה")} "since he inherits with one and inherits with five"; {SP_(217, 2, "פי", "שנים", "באחד", "מהם")} "double of one of them"): THE DOUBLE\'S BASE — one brother\'s share, not the estate\'s half (the two-brother case ambiguous; the six-brother case decides) — the compile\'s arithmetic: the estate over (n + 1) shares, the firstborn two. Fresh.')
srow(217, 3, 'MATERIAL', f'OR GO THIS WAY: WITH ONE — DOUBLE OF ALL THE PROPERTY; SO WITH FIVE — DOUBLE OF ALL? "ON THE DAY HE GIVES HIS SONS TO INHERIT" — THE VERSE MULTIPLIED INHERITANCE FOR THE SONS. ({SP_(217, 3, "כלך", "לדרך", "זו")} "go this way"; {SP_(217, 3, "פי", "שנים", "בכל", "הנכסים")} "double of all the property"; {SP_(217, 3, "רבה", "נחלה", "לבנים")} "it multiplied inheritance for the sons"): the counter-argument (half the estate) refuted by 21:16\'s plural — the sons\' inheritance widened, the firstborn\'s not. Fresh.')
srow(217, 4, 'MATERIAL', f'AFTER WE LEARNED THAT IT MULTIPLIED INHERITANCE FOR THE SONS, JUDGE ONLY BY THE FIRST REASONING: DOUBLE OF ONE OF THEM. AND SO IT SAYS: "I HAVE GIVEN YOU ONE PORTION ABOVE YOUR BROTHERS" (GENESIS 48:22), "REUBEN THE FIRSTBORN … HIS BIRTHRIGHT WAS GIVEN TO THE SONS OF JOSEPH" AND "THE BIRTHRIGHT WAS JOSEPH\'S" (1 CHRONICLES 5:1-2). ({SP_(217, 4, "אחר", "שלמדנו", "שרבה", "נחלה", "לבנים")} "after we learned that it multiplied inheritance for the sons"; {SP_(217, 4, "כדין", "הראשון")} "as the first reasoning"; {SP_(217, 4, "שכם", "אחד", "על", "אחיך")} "one portion above your brothers"; {SP_(217, 4, "והבכורה", "ליוסף")} "and the birthright was Joseph\'s"): JACOB\'S GIFT TO JOSEPH THE MEASURE — one extra portion (Shechem the homograph), the birthright moved from Reuben (the tape\'s Genesis 48-49 lines the readback\'s REFERENCE) — the compile\'s base confirmed by the narrative. Fresh.')
srow(217, 5, 'MATERIAL', f'SINCE THE BIRTHRIGHT WAS JOSEPH\'S AND THE BIRTHRIGHT IS FOR THE GENERATIONS: AS JOSEPH\'S WAS DOUBLE OF ONE, SO THE GENERATIONS\' IS DOUBLE OF ONE OF THEM. ({SP_(217, 5, "שהבכורה", "ליוסף", "ובכורה", "לדורות")} "that the birthright was Joseph\'s and a birthright for the generations"; {SP_(217, 5, "פי", "שנים", "באחד", "מהם")} "double of one of them"): the analogy from Joseph\'s two tribes (two portions among twelve, not half the land) — a TRANSFER taught by the spine (Genesis 48:22 → the firstborn\'s law) — the compile\'s arithmetic sealed. Fresh.')
srow(217, 6, 'MATERIAL', f'"OF ALL THAT IS FOUND TO HIM" — THE FIRSTBORN DOES NOT TAKE IN THE EXPECTED AS IN THE HELD. ({SP_(217, 6, "שאין", "הבכור", "נוטל", "בראוי", "כבמוחזק")} "that the firstborn does not take in the expected as in the held"): THE DOUBLE ONLY OF THE HELD ESTATE — "found to him" excludes debts due and inheritances to come (Bekhorot 8:9 the answer sheet; the export spells the word with a vav here and without at 216:2) — the compile\'s estate-class condition. Fresh.')
srow(217, 7, 'MATERIAL', f'"FOR HE IS THE FIRST OF HIS STRENGTH" — AND NOT THE FIRST OF A WOMAN\'S STRENGTH. ({SP_(217, 7, "ולא", "ראשית", "אונה", "של", "אשה")} "and not the first of a woman\'s strength"): THE INHERITANCE\'S FIRSTBORN IS THE FATHER\'S FIRST, the womb\'s firstborn the priest\'s (Bekhorot 8:1: firstborn for inheritance and not for the priest, and the reverse — the answer sheet\'s two firstborns) — the compile\'s two counters (the father\'s first son; the mother\'s womb-opener already Exodus 13\'s). Fresh.')
srow(217, 8, 'MATERIAL', f'"HIS IS THE RIGHT OF THE FIRSTBORN" — THE FIRSTBORN\'S RIGHT GOES OUT THROUGH JUDGES. ({SP_(217, 8, "שהבכורה", "יוצאה", "בדינים")} "that the firstborn\'s right goes out through judges"): the division a judicial act (mishpat the word — 216:1\'s daytime follows) — the compile\'s court parameter on the division. Fresh.')
srow(218, 1, 'MATERIAL', f'"WHEN A MAN HAS A SON" (21:18) — AND NOT WHEN A WOMAN HAS A SON. ({SP_(218, 1, "ולא", "כשיהיה", "בן", "לאשה")} "and not when a woman has a son"): both parents needed (219:1, 219:3) — the compile\'s first condition on the rebellious son. Fresh.')
srow(218, 2, 'MATERIAL', f'"A SON" — AND NOT A DAUGHTER. ({SP_(218, 2, "בן", "ולא", "בת")} "a son and not a daughter"): the sex condition (Sanhedrin 8:1). Fresh.')
srow(218, 3, 'MATERIAL', f'"A SON" — AND NOT A MAN; A MINOR IS EXEMPT, FOR HE HAS NOT COME UNDER THE COMMANDMENTS. ({SP_(218, 3, "ולא", "איש")} "and not a man"; {SP_(218, 3, "קטן", "פטור", "שלא", "בא", "לכלל", "מצוות")} "a minor is exempt, for he has not come into the class of the commandments"): THE WINDOW — after the minor, before the man (Sanhedrin 8:1: from two hairs until the beard rounds, three months — the answer sheet\'s measure) — the compile\'s age window parameter. Fresh.')
srow(218, 4, 'MATERIAL', f'"STUBBORN" — TWICE; "AND REBELLIOUS" — A FOOL. ANOTHER READING: "STUBBORN" — A HERETIC, WHO TEACHES HIMSELF ANOTHER WAY. ({SP_(218, 4, "סורר", "שתי", "פעמים")} "stubborn: two times"; {SP_(218, 4, "ומורה", "שוטה")} "and rebellious: a fool"; {SP_(218, 4, "סורר", "מין", "שמורה", "לעצמו", "דרך", "אחרת")} "stubborn: a heretic who teaches himself another way"): the two words — the repetition (two offenses: the warning and the second act, 219:4) and the character — the compile\'s count of offenses two. Fresh.')
srow(218, 5, 'MATERIAL', f'ANOTHER READING: BECAUSE HE ATE HIS FATHER\'S MONEY, SHALL HE DIE? RATHER HE IS JUDGED BY HIS END: BETTER HE DIE INNOCENT THAN DIE GUILTY. HIS FATHER DESIRED A BEAUTIFUL CAPTIVE AND BROUGHT SATAN INTO HIS HOUSE — A STUBBORN AND REBELLIOUS SON, WHOSE END IS A STRANGE DEATH. "WHEN A MAN HAS A SIN OF A DEATH SENTENCE AND IS PUT TO DEATH" (21:22) — NOT ON THE SABBATH AND NOT ON FESTIVALS. ({SP_(218, 5, "נדון", "על", "שם", "סופו")} "he is judged on account of his end"; {SP_(218, 5, "מוטב", "ימות", "זכאי", "ואל", "ימות", "חיב")} "better he die innocent than die guilty"; {SP_(218, 5, "חשק", "יפת", "תאר", "והכניס", "שטן", "לתוך", "ביתו")} "desired a beautiful captive and brought Satan into his house"; {SP_(218, 5, "לא", "בשבת", "ולא", "בימים", "טובים")} "not on the Sabbath and not on festivals"): JUDGED BY HIS END (Sanhedrin 8:5 the answer sheet) — the chapter\'s chain the captive → the hated wife → the rebellious son → the hanged (the spine reads the four laws as one story); the execution\'s calendar bar (no death on the Sabbath or a festival — the courts\' clock) — the compile\'s rationale row and its calendar condition. Fresh.')
srow(218, 6, 'CONTEXT', f'ANOTHER READING: "STUBBORN" AGAINST HIS FATHER\'S WORDS, "REBELLIOUS" AGAINST HIS MOTHER\'S; AGAINST THE TORAH\'S WORDS AND THE PROPHETS\'; AGAINST THE WITNESSES\' WORDS AND THE JUDGES\'. ({SP_(218, 6, "סורר", "על", "דברי", "אביו", "ומורה", "על", "דברי", "אמו")} "stubborn against his father\'s words, rebellious against his mother\'s"; {SP_(218, 6, "על", "דברי", "תורה", "ומורה", "על", "דברי", "הנביאים")} "against the Torah\'s words, rebellious against the Prophets\'"; {SP_(218, 6, "על", "דברי", "עדים", "ומורה", "על", "דברי", "דינים")} "against the witnesses\' words, rebellious against the judges\'"): the three pairs homiletic — no rule. Fresh.')
srow(218, 7, 'MATERIAL', f'R. JOSIAH SAID: THREE THINGS ZEIRA TOLD ME FROM THE MEN OF JERUSALEM — A SOTAH (THE SUSPECTED WIFE), IF HER HUSBAND WISHES TO PARDON HER HE PARDONS; A STUBBORN AND REBELLIOUS SON, IF HIS FATHER AND MOTHER WISH TO PARDON HIM THEY PARDON; A REBELLIOUS ELDER AGAINST THE COURT, IF HIS COLLEAGUES WISH TO PARDON HIM THEY PARDON. ({SP_(218, 7, "שלשה", "דברים", "סח", "לי", "זעירא")} "three things Zeira told me"; {SP_(218, 7, "סוטה", "אם", "רצה", "בעלה", "למחול", "לה", "מוחל")} "a sotah: if her husband wishes to pardon her he pardons"; {SP_(218, 7, "אם", "רצו", "אביו", "ואמו", "למחול", "לו", "מוחלים")} "if his father and mother wish to pardon him they pardon"; {SP_(218, 7, "זקן", "ממרא", "על", "פי", "בית", "דין")} "an elder rebellious against the court"): THE PARENTS\' PARDON — the son\'s case rests on the parents\' will (Sanhedrin 8:4 "if they wished to pardon him they pardon" — the answer sheet) — the compile\'s consent parameter; the sotah\'s and the elder\'s the tradition\'s siblings (17:12\'s elder, chapters 17-18). Fresh.')
srow(218, 8, 'MATERIAL', f'WHEN I CAME AND LAID THE WORDS BEFORE R. JUDAH B. BETEIRA, ON TWO HE AGREED AND ON ONE HE DID NOT: ON THE SOTAH AND THE REBELLIOUS SON HE AGREED; ON THE REBELLIOUS ELDER HE DID NOT, FOR HE RAISES DISPUTE IN ISRAEL. ({SP_(218, 8, "על", "שנים", "הודה", "לי", "ועל", "אחד", "לא", "הודה", "לי")} "on two he agreed with me and on one he did not"; {SP_(218, 8, "מפני", "שהיה", "מעמיד", "מחלוקת", "בישראל")} "because he raises dispute in Israel"): the elder\'s pardon denied (Sanhedrin 11:2 in the background) — the son\'s pardon stands; the compile\'s parameter confirmed for the son, the elder\'s case chapters 17-18\'s. Fresh.')
srow(218, 9, 'MATERIAL', f'"HE DOES NOT HEED HIS FATHER\'S VOICE OR HIS MOTHER\'S VOICE" — EVEN IF THEY TOLD HIM TO LIGHT THE LAMP AND HE DID NOT? "HE DOES NOT HEED — HE DOES NOT HEED" (21:18, 21:20): AN ANALOGY — AS THERE A GLUTTON AND A DRUNKARD, SO HERE; AS THERE UNTIL HE STEALS FROM HIS FATHER AND HIS MOTHER, SO HERE. ({SP_(218, 9, "להדליק", "את", "הנר", "ולא", "הדליק")} "to light the lamp and he did not light"; {SP_(218, 9, "לגזרה", "שוה")} "for an analogy of equal words"; {SP_(218, 9, "זולל", "וסובא")} "a glutton and a drunkard"; {SP_(218, 9, "עד", "שיגנוב", "משל", "אביו", "ומשל", "אמו")} "until he steals from his father\'s and from his mother\'s"): THE DISOBEDIENCE DEFINED BY THE PARENTS\' OWN SPEECH — gluttony bought with stolen money (Sanhedrin 8:3 the answer sheet: until he eats a tartemar of meat and drinks half a log of wine, stolen from his father) — the compile\'s act condition (theft + the measures). Fresh.')
srow(218, 10, 'MATERIAL', f'"AND THEY CHASTISE HIM" — WITH LASHES. ({SP_(218, 10, "ויסרו", "אתו", "במכות")} "and they chastise him with lashes"): the first sentence lashes (Sanhedrin 8:4 the warning and the flogging) — the compile\'s first verdict. Fresh.')
srow(218, 11, 'MATERIAL', f'"AND HE DOES NOT HEED THEM" — THEY FLOG HIM BEFORE THREE. ({SP_(218, 11, "שמלקים", "אותו", "בפני", "שלשה")} "that they flog him before three"): the flogging by a court of three, the stoning by twenty-three (219:4) — the compile\'s two courts. Fresh.')
