
# =====================================================================
# THE CELLS OF CHAPTER 23 — F5 the father's wife and the assembly (23:1-9), F6 the camp (23:10-15), F7 the slave, the hire and the interest (23:16-21), F8 the vows and the laborer (23:22-26)
# =====================================================================
def the_fathers_wife_and_the_assembly(case, data):
    """F5 — Deut 23:1-9 — ONE LINE fathers_wife_assembly_declared writing fathers_wife_barred and ammon_moab_peace_barred (BLOCKS), crushed_barred_from_assembly, forbidden_union_offspring_barred, ammon_moab_barred_forever and edom_egypt_third_generation_admitted (STATUSES); Leviticus 18:8's father's wife by CALL (sanctions), the crushed by CALL (priesthood — Leviticus 22:24), the mamzer's definition by CALL (family), Balak's hire and the curse turned by CALL (balak), the peace call by CALL (refuge_war_family); Yevamot 8:2, 4:13, 8:3 the exam rows"""
    del P_[:]
    ask = case['ask']
    if ask == 'his_fathers_wife_and_his_fathers_skirt':
        ink('23:1', "'A MAN SHALL NOT TAKE HIS FATHER'S WIFE, and shall not uncover HIS FATHER'S SKIRT' — 23:1 shares %d tokens with Leviticus 18:8 (the restatements that share no words with their kin — the reading's find); the Name absent from 23:1 (%s the verses of chapter 23 without it)" % (TWIN['23:1 vs Lev 18:8'], [v for v in range(1, 27) if not any('יהוה' in x for x in W23(v))][:6]))
        move("the Sifrei 246:1 (read whole at the reading); cold_run_sanctions (CALL) — SA.grade(fathers_wife) = %s, SA.grade(brothers_wife) = %s" % (SA_FW[0], SA_BW[0]), "'his father's wife' — even after his father's death (246:1); Leviticus 18:8's seat — the Leviticus cell grades the father's wife 'release_or_levirate' with 'no ban — Deut 25:5's ordinary case [IMPORT]': the Leviticus runner named THIS chapter's levirate at its own compile; 'his father's skirt' — the widow awaiting the levir of his father (246:1 — the_fathers_skirt)")
        dat("THE WRITE fathers_wife_barred — a BLOCK on israel_people at the chapters' own day (DK2); the_fathers_skirt a DATA row (the widow awaiting his father's levir — 246:1); the exam's person who takes his father's widow after the father's death — barred")
        return out("his father's wife and his father's skirt (23:1) — even after his death; the skirt the widow awaiting his father's levir; Leviticus 18:8's seat, its cell naming 25:5 forward (the Sifrei 246:1; sanctions' %s by CALL): THE WRITE fathers_wife_barred, a BLOCK on Israel at the chapters' own day; the taker of his father's widow barred" % (SA_FW[0],), ['fathers_wife_barred'])
    if ask == 'the_crushed_and_the_cut':
        ink('23:2', "'HE THAT IS CRUSHED OR CUT SHALL NOT ENTER THE ASSEMBLY OF THE LORD' — 'the assembly of the LORD' at %s (four seats in this chapter and Micah 2:5); Onkelos 'shall not be fit' at 23:2 and 23:3; 23:2 shares %d tokens with Leviticus 21:20 and %d with Leviticus 22:24" % (P('בקהל', 'יהוה', books=None), TWIN['23:2 vs Lev 21:20'], TWIN['23:2 vs Lev 22:24']))
        move("the Sifrei 247:1-5 (read whole at the reading); MISHNAH YEVAMOT 8:2 (the exam row, read whole); cold_run_priesthood (CALL) — PR.acceptable(castration) read (humans %s)" % (PR_CASTR[0]['humans'],), "who is crushed — whoever's testicles are crushed, even one; cut — whoever's member is cut; if a hair's breadth of the corona remains — fit (Yevamot 8:2 — the exam row; 247:1-2); permitted to a convert and a freed slave, barred from the assembly alone (247:3); the crushed by heaven — permitted, the excluded one crushed by man (247:4-5 — the_crushed_by_heaven); Leviticus 22:24's crushed beast and the human 'even one' (priesthood's cell by CALL — the revocalization 'in you')")
        dat("THE WRITE crushed_barred_from_assembly — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_crushed_measure (even one testicle; a hair's breadth of the corona fit — Yevamot 8:2); the_crushed_by_heaven a DATA row (247:4-5); the exam's person crushed by a sickness from heaven — permitted to the assembly")
        return out("the crushed and the cut (23:2) — even one testicle; a hair's breadth of the corona fit; permitted to a convert, barred from the assembly; by heaven permitted (the Sifrei 247:1-5; Mishnah Yevamot 8:2; priesthood's castration by CALL): THE WRITE crushed_barred_from_assembly, a STATUS on Israel at the chapters' own day; the crushed by heaven permitted", ['crushed_barred_from_assembly'])
    if ask == 'the_mamzer':
        ink('23:3', "'A MAMZER (one born of a forbidden union) SHALL NOT ENTER THE ASSEMBLY OF THE LORD, even THE TENTH generation shall not enter' — the ordinal %s at 23:3 and 23:4 (the parser's tenth twice); 'mamzer' at %s (Zechariah 9:6 the other); 23:3 shares %d tokens with 23:4 (%s)" % (PARSE[(23, 3)][1], P('ממזר', books=None), TWIN['23:3 vs 23:4'], SHARED(DV(23, 3), DV(23, 4))))
        move("the Sifrei 248:1-5, 249:4 (read whole at the reading); MISHNAH YEVAMOT 4:13 (the exam row, read whole); cold_run_family (CALL) — FA.levirate(mamzer_definition) = %s; MIDDOT.md I2 (the verbal analogy)" % (FA_MAMZER[0],), "who is a mamzer? R. Akiva: any prohibited kin under a negative commandment; Shimon the Temanite: any union under karet (excision) by Heaven — THE RULING; R. Yehoshua: any union under a court death (Yevamot 4:13 — THREE ARMS; the Genesis cell applies the definition to Judah's act and returns 'not a mamzer' — Perez and Zerah pre-Sinai); 'even the tenth generation' — for ever, by the verbal analogy with Ammon's 'tenth generation … for ever' (248:5, 249:4 — I2); the mamzeret too — males and females alike (Yevamot 8:3's last clause)")
        dat("THE WRITE forbidden_union_offspring_barred — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_mamzers_definition (Yevamot 4:13 — three arms, the Temanite's the ruling); the exam's person born of a union under a negative commandment alone — R. Akiva's mamzer, the ruling's not")
        return out("the mamzer (23:3) — R. Akiva's, the Temanite's (the ruling), R. Yehoshua's: three arms; the tenth generation for ever by Ammon's analogy; the mamzeret too (the Sifrei 248:1-5, 249:4; Mishnah Yevamot 4:13; family's %s by CALL): THE WRITE forbidden_union_offspring_barred, a STATUS on Israel at the chapters' own day; the child of a negative-commandment union not the ruling's mamzer" % (FA_MAMZER[0][1],), ['forbidden_union_offspring_barred'])
    if ask == 'ammon_and_moab_for_ever':
        ink('23:4-5', "'AN AMMONITE OR A MOABITE SHALL NOT ENTER THE ASSEMBLY OF THE LORD, even the tenth generation shall not enter for them into the assembly of the LORD FOR EVER, because they met you not with bread and water in the way when you came out of Egypt, and because he HIRED against you Balaam son of Beor from Pethor of Aram-naharaim to curse you' — 'for ever' at %s in the Torah (23:4 among them); 'in the way when you came out of Egypt' at %s — the three remembrances' one phrase (the reading's find 2); the closest kin of 23:5 %s (Nehemiah's recital)" % (P('עד', 'עולם', books=T), P('בדרך', 'בצאתכם', 'ממצרים', books=T), KINC[(23, 5)][0]))
        move("the Sifrei 249:1-4, 250:1-5 (read whole at the reading); MISHNAH YEVAMOT 8:3 (the exam row, read whole); cold_run_balak (CALL) — BK.the_call(honor_promised) = %s" % (BK_HONOR[1],), "'an Ammonite or a Moabite' — the Ammonite and not the Ammonitess, the Moabite and not the Moabitess: the females permitted at once (Yevamot 8:3 — the exam row; 249:1); 'because they met you not with bread and water' — it is the way of men to go out to meet with bread and water, not of women (250:1 — the way of the world); 'because he hired against you Balaam' — Balak's counsel by Micah 6:5 (250:3); the hire — 'his house full of silver and gold', the honor promised and revoked (balak's honor_owed by CALL — the tape's own act)")
        dat("THE WRITE ammon_moab_barred_forever — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_ammonite_females (Yevamot 8:3 — the females permitted at once; TRADITION OVER ARGUMENT at 253:2); the exam's person the Moabitess who enters the assembly — permitted at once (Ruth the run's citation ahead)")
        return out("Ammon and Moab for ever (23:4-5) — the Ammonite and not the Ammonitess, the Moabite and not the Moabitess; the way of men to meet with bread and water; the hire of Balaam the tape's own act (the Sifrei 249:1-250:5; Mishnah Yevamot 8:3; balak's %s by CALL): THE WRITE ammon_moab_barred_forever, a STATUS on Israel at the chapters' own day; the Moabitess permitted at once" % (BK_HONOR[1][0],), ['ammon_moab_barred_forever'])
    if ask == 'the_curse_turned_to_a_blessing':
        ink('23:6', "'and the LORD your God would not hear Balaam, and THE LORD YOUR GOD TURNED THE CURSE INTO A BLESSING FOR YOU, because the LORD your God loved you' — the wayyiqtol (the narrative verb form) 'and He turned' at 23:6 (%s the five of the four chapters) a REMEMBRANCE, not an act: the tape's balak_sent_for_balaam (Numbers 22:5-6) through balaam_and_balak_parted (24:25) the readback's REFERENCES" % ([(c, v, x) for c, v in SPAN for x, m in MO[(c, v)] if m and re.search(r'V[a-zA-Z]w', m)],))
        move("the Sifrei 250:4-5 (read whole at the reading); cold_run_balak (CALL) — BK.the_call(cursing_barred) = %s ('a block never closed; Deut 23:6 the run'), BK.the_call(curse_roots) read" % (BK_CURSE[1],), "'the LORD would not hear Balaam' — the curse never spoken: three curse-roots, twenty tokens, and no curse (balak's curse_roots by CALL — 'no curse spoken (22:12; Deut 23:6)'); 'and turned the curse into a blessing' — the four parables the tape's own lines (Numbers 23-24 — the readback's references, never a second act); 'because the LORD your God loved you' — the heaven of the tape's own act; THE RUN IS HERE: the Numbers cell named 'Deut 23:6 the run' at its own compile — this verse the retelling that closes its sentence (cursing_barred ONE on balaam UNMOVED — SCANS %s)" % (SCANS['cursing_barred'],))
        dat("the_curse_turned a DATA row (the retelling of Numbers 22-24 — a REFERENCE row, no write; the block cursing_barred on Balaam never closed, the run this verse's); the exam's person who reads 23:6 as a new act of turning — the tape's own act at Numbers 23-24, told here")
        return out("the curse turned to a blessing (23:6) — Balaam unheard, no curse spoken, the four parables the tape's own act; because He loved you; the Numbers cell's 'Deut 23:6 the run' closed here as a remembrance (the Sifrei 250:4-5; balak's %s by CALL): no write, a reference row" % (BK_CURSE[1][0],), ['accepted'])
    if ask == 'you_shall_not_seek_their_peace':
        ink('23:7', "'YOU SHALL NOT SEEK THEIR PEACE nor their good all your days for ever' — no verse of the Bible shares two of its words (KINC %s); 23:7 shares %d tokens with 20:10 (the peace call) and 23:4 %d with 2:9 (Moab spared)" % (KINC[(23, 7)], TWIN['23:7 vs 20:10'], TWIN['23:4 vs 2:9']))
        move("the Sifrei 251:1-3 (read whole at the reading; 251:1 REREAD from chapters 19-21); cold_run_refuge_war_family (CALL) — the peace call 20:10's (peace_call_commanded ONE on israel_people — SCANS %s)" % (SCANS['peace_call_commanded'],), "'you shall not seek their peace' — from 'you shall call to it for peace' (20:10) I might think these too: the verse says 'you shall not seek their peace' (251:1 — the peace call barred for Ammon and Moab, the Sifrei rereading the siege's law); 'nor their good' — from 'he shall dwell with you … where it is good for him' (23:17) I might think these too — 'nor their good' (251:2); Moab spared as a nation at 2:9 (the tape's moab_spared_commanded — the readback's REFERENCE: spared from war, barred from the assembly)")
        dat("THE WRITE ammon_moab_peace_barred — a BLOCK on israel_people at the chapters' own day (DK2); the_peace_calls_exception a DATA row (20:10's call withheld from Ammon and Moab — 251:1; 2:9's sparing the reference); the exam's person the besieger of an Ammonite city who calls to it for peace — barred from the call")
        return out("you shall not seek their peace (23:7) — 20:10's peace call withheld from Ammon and Moab, 23:17's good withheld; Moab spared as a nation and barred from the assembly (the Sifrei 251:1-3; refuge_war_family's peace call the reference): THE WRITE ammon_moab_peace_barred, a BLOCK on Israel at the chapters' own day; the besieger's peace call to Ammon barred", ['ammon_moab_peace_barred'])
    if ask == 'edom_and_egypt_the_third_generation':
        ink('23:8-9', "'YOU SHALL NOT ABHOR AN EDOMITE, FOR HE IS YOUR BROTHER; you shall not abhor an Egyptian, for you were a sojourner in his land; the sons born to them, THE THIRD GENERATION SHALL ENTER the assembly of the LORD' — the ordinal %s at 23:9 (the third); 'your brother' at 23:8 among the four chapters' ten brother-tokens (%s)" % (PARSE[(23, 9)][1], [(c, v) for c, v in SPAN for x in W(c, v) if x == 'אחיך']))
        move("the Sifrei 252:1-2, 253:1-3 (read whole at the reading); MISHNAH YEVAMOT 8:3 (the exam row — the second clause); MIDDOT.md I1 (a fortiori)", "'you shall not abhor an Edomite' — though he came against you with the sword (Numbers 20:18-21 — the tape's edom_refused); 'an Egyptian' — though they drowned your sons in the river (252:1-2); 'the third generation shall enter' — the third, not the first and the second (253:1); R. Shimon's a fortiori — if the females of Ammon and Moab are permitted at once, the females of Edom and Egypt the more so — REFUSED BY THE TRADITION: 'if it is a tradition we accept it; if an argument, there is an answer' (253:2 — TRADITION OVER ARGUMENT, the reading's find; Yevamot 8:3's second clause)")
        dat("THE WRITE edom_egypt_third_generation_admitted — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_third_generation (a COUNT — the parser's third at 23:9; the first and the second barred); the_tradition_over_argument a DATA row (253:2); the exam's person the Egyptian convert's grandchild — the third generation, admitted")
        return out("Edom and Egypt the third generation (23:8-9) — the brother with the sword, the host who drowned your sons: not abhorred; the third generation enters, the first and the second not; R. Shimon's a fortiori on the females refused — tradition over argument (the Sifrei 252:1-253:3; Mishnah Yevamot 8:3): THE WRITE edom_egypt_third_generation_admitted, a STATUS on Israel at the chapters' own day; the Egyptian's grandchild admitted", ['edom_egypt_third_generation_admitted'])
    return 'no verdict in span', [], list(P_)


def the_camp(case, data):
    """F6 — Deut 23:10-15 — ONE LINE camp_holiness_declared writing camp_evil_thing_guarded, nocturnal_unclean_exit_commanded, camp_latrine_commanded and camp_holiness_required (STATUSES); Numbers 5:1-4's three camps by CALL (naso — THE NIGHT'S CHANCE NOT IN ITS SPAN: this chapter's own law), the Shema by the vat by CALL (hear_o_israel); Berakhot 3:5 and Zavim 2:3 the exam rows"""
    del P_[:]
    ask = case['ask']
    if ask == 'when_the_camp_goes_out':
        ink('23:10', "'WHEN THE CAMP GOES OUT AGAINST YOUR ENEMIES, YOU SHALL KEEP YOURSELF FROM EVERY EVIL THING' — 'against your enemies' 20:1's and 21:10's opening (the war chapters' three); the Name absent from 23:10 (%s)" % ([v for v in range(10, 16) if not any('יהוה' in x for x in W23(v))],))
        move("the Sifrei 254:1-4 (read whole at the reading); cold_run_refuge_war_family (CALL) — 20:1's 'against your enemies, not your brothers' (RW.the_priests_speech read)", "'against your enemies' — not against your brothers (254:1 — the siege's rule); 'you shall keep yourself from every evil thing' — the three cardinal sins as 'the evil thing': idolatry, forbidden unions, bloodshed — the Presence removed by lewdness (254:2-3 — the reading's find 9: a HEAVEN reading, no new entry); 254:4's 'chapter 25' the translator's error (the reading's find 3)")
        dat("THE WRITE camp_evil_thing_guarded — a STATUS on israel_people at the chapters' own day (DK2); the_evil_thing a DATA row (the three cardinal sins — 254:2-3; the Presence's removal a heaven reading, no entry); the exam's person the soldier who guards himself from the three in the camp — accepted")
        return out("when the camp goes out (23:10) — against your enemies, not your brothers; the evil thing the three cardinal sins, the Presence removed by lewdness (the Sifrei 254:1-4; refuge_war_family's rule by CALL): THE WRITE camp_evil_thing_guarded, a STATUS on Israel at the chapters' own day; the guarded soldier accepted", ['camp_evil_thing_guarded'])
    if ask == 'the_nights_chance':
        ink('23:11', "'When there is among you a man who is NOT CLEAN BY A CHANCE OF THE NIGHT, HE SHALL GO OUT OF THE CAMP, he shall not come into the midst of the camp' — 'outside the camp' at %d seats of the Torah (23:11-13 among them); 23:11 shares %d tokens with Leviticus 15:16 (the emission) and %d with Numbers 5:2 (the three sent out)" % (len(P('מחוץ', 'למחנה', books=T)), TWIN['23:11 vs Lev 15:16'], TWIN['23:11 vs Num 5:2']))
        move("the Sifrei 255:1-3 (read whole at the reading); cold_run_naso (CALL) — NS.camp_purity(who_is_sent, what=seed_emitter) = %s, NS.camp_purity(ladder, who=leper) = %s, (zav) = %s, (corpse_unclean) = %s" % (NS_EMITTER[0], NS_LEPER[0], NS_ZAV[0], NS_CORPSE[0]), "'a chance of the night' — the emission, Leviticus 15:16's seed_emitted the tape's kind; the usual case named, the day's chance the same (255:3 — the reading's find); 'he shall go out of the camp' — the camp of the Presence (255:2): the three camps' ladder — the leper out of all three, the zav out of two, the corpse-unclean out of one (naso's ladder by CALL); THE EMITTER NOT IN NUMBERS 5'S SPAN — 'no verdict in span' by CALL: THE NIGHT'S CHANCE IS THIS CHAPTER'S OWN LAW, the emitter's camp the answer sheet's parameter (the zav's two by the ladder)")
        dat("THE WRITE nocturnal_unclean_exit_commanded — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_emitters_camp (out of the camp of the Presence — 255:2; the ladder's step by the sheet); sent_outside_the_camp TWO on the tape THE REFERENCES (SCANS %s); the exam's person the emitter who stays in the camp of Levi — accepted, the Presence's camp alone barred him" % (SCANS['sent_outside_the_camp'],))
        return out("the night's chance (23:11) — the emission, the usual case named; out of the camp of the Presence by the three camps' ladder; NOT IN NUMBERS 5'S SPAN — this chapter's own law (the Sifrei 255:1-3; naso's %s and the ladder by CALL): THE WRITE nocturnal_unclean_exit_commanded, a STATUS on Israel at the chapters' own day; the emitter in the camp of Levi accepted" % (NS_EMITTER[0],), ['nocturnal_unclean_exit_commanded'])
    if ask == 'toward_evening_he_bathes':
        ink('23:12', "'and TOWARD EVENING HE SHALL BATHE IN WATER, and when the sun sets he shall come into the midst of the camp' — the sunset the day's boundary (Onkelos 'when the sun sets'); 'when the sun sets' the pledge's clock too (24:13)")
        move("the Sifrei 256:1-2 (read whole at the reading); MISHNAH BERAKHOT 3:5 and ZAVIM 2:3 (the exam rows, read whole)", "'toward evening he shall bathe' — the immersion by day, the entry at sunset: he immerses and waits for the sun (256:2 — the sunset a CLOCK parameter); the emitter who recalls at the prayer shortens it; the immersion before sunrise for the reading; four cubits from the filth (Berakhot 3:5 — the exam row); the emitter does not become a zav (one with a discharge) for twenty-four hours — R. Yose: that day (Zavim 2:3 — the exam row, TWO ARMS)")
        dat("THE PARAMETERS the_sunset (a clock parameter — the entry when the sun sets, no timer at a line) and the_twenty_four_hours (Zavim 2:3 — the sages' day and night, R. Yose's day: two arms); the exam's person the emitter who immersed at noon and enters the camp at sunset — accepted")
        return out("toward evening he bathes (23:12) — the immersion by day, the entry at sunset; the emitter at prayer shortens; twenty-four hours before he becomes a zav, R. Yose that day (the Sifrei 256:1-2; Mishnah Berakhot 3:5, Zavim 2:3): the emitter who immersed at noon enters at sunset", ['accepted'])
    if ask == 'a_place_outside_the_camp_and_a_spade':
        ink('23:13-14', "'And you shall have A PLACE (a hand) OUTSIDE THE CAMP and go out there; and you shall have A SPADE AMONG YOUR WEAPONS, and when you sit down outside you shall dig with it and turn back and cover what comes from you' — 'a hand' the place (1 Samuel 15:12's hand — the Amalek chapter cited before F16); Onkelos 'a prepared place' and 'on your weapons' (the same Aramaic noun — the reading's find 4)")
        move("the Sifrei 257:1-3 (read whole at the reading); Onkelos 23:13-14", "'a hand' — a place, as 'and behold he set him up a hand' (1 Samuel 15:12 — 257:1: the spine citing Saul's monument at Amalek's war, F16's chapter ahead); 'outside the camp' — the camp of Israel too; 'a spade among your weapons' — a peg on your gear, Onkelos 'on your weapons': the same noun for the gear and the arms (257:3); 'and cover what comes from you' — the covering the camp's holiness (257:2)")
        dat("THE WRITE camp_latrine_commanded — a STATUS on israel_people at the chapters' own day (DK2); the_hand_is_a_place a DATA row (257:1 — 1 Samuel 15:12 cited); the exam's person who relieves himself inside the camp without covering — barred from it")
        return out("a place outside the camp and a spade (23:13-14) — a hand is a place, Saul's monument the spine's witness; the spade on the gear, Onkelos on the weapons; the covering the holiness (the Sifrei 257:1-3; Onkelos): THE WRITE camp_latrine_commanded, a STATUS on Israel at the chapters' own day; the uncovering in the camp barred", ['camp_latrine_commanded'])
    if ask == 'for_the_lord_walks_in_your_camp':
        ink('23:15', "'For THE LORD YOUR GOD WALKS IN THE MIDST OF YOUR CAMP to deliver you and to give your enemies before you; AND YOUR CAMP SHALL BE HOLY, that He see no unseemly thing in you and turn away from you' — 'an unseemly thing' at %s (24:1's ground the twin); Onkelos 'His Shekhinah (indwelling presence) walks' and 'His Memra (word) turns from doing you good' (the reading's find 15); 23:15 shares %d tokens with Leviticus 26:12 (the walking God)" % (P('ערות', 'דבר', books=T), TWIN['23:15 vs Lev 26:12']))
        move("the Sifrei 258:1-4 (read whole at the reading; 258:1 REREAD from chapter 6); cold_run_hear_o_israel (CALL) — HI.the_four_duties(the_seven) = %s (the reader's exemptions read)" % (HI_SEVEN[1],), "'the LORD walks in your camp' — the Presence's presence a condition: the camp holy that He not turn away (258:2-3 — the_presence_condition); 'your camp shall be holy' — the Shema not read by the launderers' vat, by filth, by the unclean (258:1 — the Shema's cell reread from chapter 6, hear_o_israel by CALL); 'that He see no unseemly thing in you' — the exposure and the filth; 'and turn away from you' — Onkelos 'His Memra turn from doing you good' (258:4)")
        dat("THE WRITE camp_holiness_required — a STATUS on israel_people at the chapters' own day (DK2); the_presence_condition a DATA row (the Shekhinah walks, the Memra turns — a HEAVEN reading, no entry); the exam's person who reads the Shema by the launderers' vat — barred from it")
        return out("for the LORD walks in your camp (23:15) — the Presence a condition, the camp holy that He not turn; the Shema not read by the vat; His Shekhinah walks, His Memra turns (the Sifrei 258:1-4; Onkelos; hear_o_israel's %s by CALL): THE WRITE camp_holiness_required, a STATUS on Israel at the chapters' own day; the reader by the vat barred" % (HI_SEVEN[1][0],), ['camp_holiness_required'])
    return 'no verdict in span', [], list(P_)


def the_slave_the_hire_and_the_interest(case, data):
    """F7 — Deut 23:16-21 — ONE LINE slave_hire_interest_declared writing escaped_slave_return_barred, slave_oppression_barred, cult_prostitution_barred, harlots_hire_dogs_price_barred and interest_to_brother_barred (BLOCKS) and interest_to_foreigner_permitted (a STATUS); the wronging by CALL (ordinances — Exodus 22:20), the cult harlot's Sinai seat and the harlot's definition by CALL (family, priesthood), the abomination's shared word by CALL (courts_prophet — 17:1), the interest by CALL (yovel — THE IMPORT EDGE M-07 naming 23:21; ordinances — Exodus 22:24's five prohibitions); Temurah 6:2-3 and Bava Metzia 5:10 the exam rows"""
    del P_[:]
    ask = case['ask']
    if ask == 'the_slave_who_escapes_to_you':
        ink('23:16-17', "'YOU SHALL NOT DELIVER A SLAVE TO HIS MASTER who escapes to you from his master; he shall dwell with you in your midst in the place he chooses IN ONE OF YOUR GATES where it is good for him; YOU SHALL NOT OPPRESS HIM' — 'in one of your gates' at %s (15:7, 16:5, 17:2 the book's others); the parser %s at 23:17 (the one); Onkelos 'a slave of the nations' (259:8); 23:17 shares %d tokens with Exodus 22:20" % (P('באחד', 'שעריך', books=T), PARSE[(23, 17)][0], TWIN['23:17 vs Exod 22:20']))
        move("the Sifrei 259:1-8 (read whole at the reading; 259:5 REREAD from chapters 19-21); cold_run_ordinances (CALL) — OR.stranger(words_vs_money) = %s; cold_run_place_name (CALL) — the place a REFERENCE only (PN.the_nations_cut_off_and_the_abomination read: %s)" % (OR_WORDS[0], PN_INQ[1]), "'a slave who escapes to you' — from outside the land to the land (259:1-2); R. Judah — the gentile's slave who fled to Israel (259:3 — the slave's flight a data row); 'in the place he chooses in one of your gates' — the gate is NOT Jerusalem: the good of the slave, not the sanctuary's city (259:5 — the Sifrei rereading 'the place' against 12:5's place: place_name's the_place a reference only); 'a slave' — Onkelos 'a slave of the nations', the second reading written in (259:8); 'you shall not oppress him' — with words: wronging is words, oppression is money (Exodus 22:20's pair — ordinances' 'yesterday_an_idolater_banned' by CALL); 'he shall dwell with you' — the slave's residence (259:6-7)")
        dat("THE WRITES escaped_slave_return_barred and slave_oppression_barred — BLOCKS on israel_people at the chapters' own day (DK2); the_slaves_flight a DATA row (from abroad to the land; R. Judah's gentile's slave — 259:1-3); the_slaves_residence a DATA row (his own gate, not the place — 259:5-7); the exam's person who reminds the escaped slave of his yesterday — barred, the wronging by words")
        return out("the slave who escapes to you (23:16-17) — from abroad to the land, R. Judah's gentile's slave; his gate his own, not Jerusalem; Onkelos a slave of the nations; not wronged with words (the Sifrei 259:1-8; ordinances' %s by CALL; place_name's place a reference): THE WRITES escaped_slave_return_barred and slave_oppression_barred, BLOCKS on Israel at the chapters' own day; the reminder of his yesterday barred" % (OR_WORDS[0],), ['escaped_slave_return_barred', 'slave_oppression_barred'])
    if ask == 'no_cult_harlot_of_the_daughters_of_israel':
        ink('23:18', "'THERE SHALL BE NO CULT HARLOT (kedeshah) OF THE DAUGHTERS OF ISRAEL, and no cult prostitute (kadesh) of the sons of Israel' — 'Israel' twice in the verse (%s the four chapters' nine); 23:18 shares %d tokens with Genesis 38:21 (Tamar's word — the tape's own); Onkelos 'a woman of Israel to a slave man', 'a man of Israel a slave woman' (the reading's find 4)" % ([(c, v) for c, v in SPAN for x in W(c, v) if 'ישראל' in x], TWIN['23:18 vs Gen 38:21']))
        move("the Sifrei 260:1-2 (read whole at the reading); cold_run_family (CALL) — FA.levirate(kedesha) = %s ('the noun's Sinai seat Deut 23:18 — uncompiled'); cold_run_priesthood (CALL) — PR.family(zonah) = %s" % (FA_KEDESHA[0], PR_ZONAH[0]['sages']), "'a cult harlot' — Genesis 38:21-22's word for Tamar, the Adullamite's — THE SINAI SEAT THE GENESIS CELL NAMED 'UNCOMPILED', COMPILED HERE (family's kedesha by CALL: four of its seven Bible seats in Genesis 38 and here); the harlot's definition the priests' law's — the convert, the freed slavewoman, illicit intercourse (Leviticus 21:7 — priesthood's zonah by CALL); Onkelos — 'a woman of the daughters of Israel shall not be to a slave man, and a man of the sons of Israel shall not take a slave woman': the marriage with slaves, THE OTHER WAY — the translation narrowing where the spine widens (260:1-2 — the reading's find 4: the_harlots_definition two arms)")
        dat("THE WRITE cult_prostitution_barred — a BLOCK on israel_people at the chapters' own day (DK2); THE PARAMETER the_harlots_definition (the spine's harlot by the priests' definition; Onkelos's marriage with slaves — two arms); the exam's person the daughter of Israel given to a slave man — Onkelos's arm barred, the spine's not this verse")
        return out("no cult harlot of the daughters of Israel (23:18) — Tamar's word at its Sinai seat, the Genesis cell's 'uncompiled' compiled here; the harlot by the priests' definition; Onkelos the marriage with slaves — two arms (the Sifrei 260:1-2; family's %s and priesthood's %s by CALL): THE WRITE cult_prostitution_barred, a BLOCK on Israel at the chapters' own day; the daughter given to a slave Onkelos's arm" % (FA_KEDESHA[0], PR_ZONAH[0]['sages'][0]), ['cult_prostitution_barred'])
    if ask == 'the_harlots_hire_and_the_dogs_price':
        ink('23:19', "'YOU SHALL NOT BRING THE HIRE OF A HARLOT OR THE PRICE OF A DOG into the house of the LORD your God for any vow, for AN ABOMINATION TO THE LORD YOUR GOD are BOTH OF THEM' — 'the hire of a harlot' at %s (Micah 1:7 the other); the parser %s at 23:19 ('both of them' starred); 'both of them' at %s (22:22's adulterers the twin); 23:19 shares %d tokens with 17:1 (the blemished sacrifice's abomination — the same word); Onkelos 'the house of the sanctuary'" % (P('אתנן', 'זונה', books=None), PARSE[(23, 19)][0], P('גם', 'שניהם', books=T), TWIN['23:19 vs 17:1']))
        move("the Sifrei 261:1-6 (read whole at the reading; 261:2 REREAD from chapters 17-18); MISHNAH TEMURAH 6:2, 6:3 (the exam rows, read whole); cold_run_courts_prophet (CALL) — CP.the_blemished_sacrifice(the_mounter_and_the_harlots_hire) = %s" % (CP_HIRE[1],), "what is a harlot's hire? he said to a harlot 'here is this lamb as your fee' — even a hundred, all forbidden; the maidservant to a slave — Rabbi forbids, the sages permit (Temurah 6:2 — TWO ARMS); what is a dog's price? 'here is this lamb in place of a dog'; two partners, one took ten and the other nine and a dog — the nine permitted, the dog's forbidden; a DOG'S HIRE and a HARLOT'S PRICE permitted — 'both of them' two and not four; their offspring permitted — 'them' and not their offspring (Temurah 6:3 — the two exclusions); 'an abomination' — 17:1's word: nine disqualified by 'abomination', the offspring not (261:2 — courts_prophet's cell by CALL: '23:19 the shared word — 99:2, 261:2'); 'for any vow' — even the hundred lambs (261:1); 'the house of the LORD' — Onkelos 'the house of the sanctuary' (the reading's find 15)")
        dat("THE WRITE harlots_hire_dogs_price_barred — a BLOCK on israel_people at the chapters' own day (DK2); THE PARAMETER the_hires_scope (Temurah 6:2-3 — the hire even a hundred, the maidservant disputed; two and not four, them and not their offspring); the_hundred_lambs a DATA row (261:1); the exam's person who brings the offspring of a harlot's hire for a vow — permitted, 'them' and not their offspring")
        return out("the harlot's hire and the dog's price (23:19) — the lamb as a fee even a hundred, the maidservant disputed; the lamb for a dog, the partners' nine and a dog; a dog's hire and a harlot's price permitted — two not four, them not their offspring; the abomination 17:1's word (the Sifrei 261:1-6; Mishnah Temurah 6:2-3; courts_prophet's %s by CALL): THE WRITE harlots_hire_dogs_price_barred, a BLOCK on Israel at the chapters' own day; the hire's offspring permitted" % (CP_HIRE[1][0],), ['harlots_hire_dogs_price_barred'])
    if ask == 'interest_to_your_brother':
        ink('23:20', "'YOU SHALL NOT LEND ON INTEREST TO YOUR BROTHER — interest of silver, interest of food, interest of anything that is lent on interest' — the bite noun (neshekh) three times in the verse and at %d Torah seats (Exodus 22:24, Leviticus 25:36, this, and Numbers 21:9's biting serpents — the homograph); Onkelos 'interest' (ribbit) three times; 23:20 shares %d tokens with Exodus 22:24 and %d with Leviticus 25:36" % (OR_BITE[0], TWIN['23:20 vs Exod 22:24'], TWIN['23:20 vs Lev 25:36']))
        move("the Sifrei 262:1-3 (read whole at the reading); MISHNAH BAVA METZIA 5:10 (the exam row, read whole); cold_run_ordinances (CALL) — OR.loan(bite_noun) = %s seats, OR.loan(five_prohibitions) = %d, OR.loan(who_transgresses) = %s; cold_run_yovel (CALL) — YV.interest() both nouns %s, definitions %s" % (OR_BITE[0], len(OR_FIVE[0]), OR_WHO[0], YV_INT['both_nouns'][0], YV_INT['definitions'][0]), "'you shall not lend on interest' — the BORROWER warned: the lender by 'you shall not give' and 'do not take' (Leviticus 25:36-37), 'as a creditor' and 'interest' (Exodus 22:24), 'before the blind' (Leviticus 19:14) — five prohibitions (262:1 — Bava Metzia 5:11 by the Exodus cell); the lender, the borrower, the guarantor, the witnesses transgress (ordinances' who_transgresses by CALL); 'interest of silver, interest of food' — the money's bite and the produce's increase, both nouns barred (yovel's interest by CALL — the definitions 'money_bite_vs_produce_increase'); the verbal interest, the pre-paid and the delayed — R. Shimon: even words are interest (Bava Metzia 5:10 — the exam row); the 'bite' of Numbers 21:9 the root's homograph — the serpents' verb, no edge (ordinances' four seats)")
        dat("THE WRITE interest_to_brother_barred — a BLOCK on israel_people at the chapters' own day (DK2); THE PARAMETER the_interests_kinds (Bava Metzia 5:10 — the pre-paid, the delayed, R. Shimon's verbal interest); interest_barred Leviticus 25:36's ZERO on the running world (SCANS %s) — the jubilee's block never written on a person, the reference; the exam's person the borrower who pays a bite of silver — transgresses with his lender" % (SCANS['interest_barred'],))
        return out("interest to your brother (23:20) — the borrower warned beside the lender's five prohibitions; the lender, the borrower, the guarantor, the witnesses; the money's bite and the produce's increase; the verbal interest R. Shimon's (the Sifrei 262:1-3; Mishnah Bava Metzia 5:10; ordinances' %d seats and yovel's %s by CALL): THE WRITE interest_to_brother_barred, a BLOCK on Israel at the chapters' own day; the borrower who pays the bite transgresses" % (OR_BITE[0], YV_INT['definitions'][0]), ['interest_to_brother_barred'])
    if ask == 'to_the_foreigner_you_may_lend':
        ink('23:21', "'TO THE FOREIGNER YOU MAY LEND ON INTEREST, but to your brother you shall not lend on interest, THAT THE LORD YOUR GOD MAY BLESS YOU in all you put your hand to in the land which you are entering to possess' — 'in all you put your hand to' 15:10's and 15:18's blessing (work_of_the_hand_blessed TWO on israel_people — SCANS %s); 23:21 shares %d tokens with Leviticus 25:37" % (SCANS['work_of_the_hand_blessed'], TWIN['23:21 vs Lev 25:37']))
        move("the Sifrei 263:1-4 (read whole at the reading); cold_run_yovel (CALL) — YV.interest_scope(foreigner) = %s ('IMPORT EDGE (M-07): to the foreigner you may lend at interest, to your brother not — Deut 23:21'), YV.interest_scope(brother) = %s; cold_run_ordinances (CALL) — OR.loan(foreigner) = %s ('Deut 23:21 by import')" % (YV_FOREIGN[0], YV_BROTHER[0], OR_FOREIGN[0]), "'to the foreigner you may lend on interest' — a positive command (R. Meir's arm) or a permission — TWO ARMS (263:1-2 — the_foreigners_interest); THE LEVITICUS CELL'S IMPORT EDGE M-07 NAMES THIS VERSE: yovel.interest_scope('foreigner') read 23:21 forward at its own compile, and the Exodus cell's 'permitted' by the same import — THE EDGE PAID IN THE REVERSE DIRECTION, this runner calling yovel for the definitions; 'that the LORD may bless you' — the blessing's third seat after 15:10 and 15:18, THE TAPE'S REFERENCE, no third write (263:3-4)")
        dat("THE WRITE interest_to_foreigner_permitted — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_foreigners_interest (a command or a permission — 263:1-2, two arms); work_of_the_hand_blessed the reference, never a third write; the exam's person who lends to a foreigner at interest — permitted (R. Meir: commanded)")
        return out("to the foreigner you may lend (23:21) — a command or a permission, two arms; the Leviticus cell's import edge M-07 naming this verse, paid in reverse; the blessing 15:10's, no third write (the Sifrei 263:1-4; yovel's %s and ordinances' %s by CALL): THE WRITE interest_to_foreigner_permitted, a STATUS on Israel at the chapters' own day; the lender to the foreigner permitted" % (YV_FOREIGN[0], OR_FOREIGN[0]), ['interest_to_foreigner_permitted'])
    return 'no verdict in span', [], list(P_)


def the_vows_and_the_laborer(case, data):
    """F8 — Deut 23:22-26 — TWO LINES: vows_law_declared (23:22-24) writing vow_delay_barred (a BLOCK), vow_refraining_permitted and lips_utterance_binding (STATUSES); laborer_vineyard_grain_declared (23:25-26) writing laborer_eating_permitted (a STATUS), laborer_vessel_barred and sickle_swinging_barred (BLOCKS); Numbers 30's cells by CALL (vows), the feasts' deadline by CALL (musafim), the sin formula's first seat by CALL (release_firstborn — 15:9); Rosh Hashanah 1:1 the exam row; the laborer's eating OWED to the docket (Bava Metzia 7)"""
    del P_[:]
    ask = case['ask']
    if ask == 'when_you_vow_a_vow_delay_not':
        ink('23:22', "'WHEN YOU VOW A VOW TO THE LORD YOUR GOD, YOU SHALL NOT DELAY TO PAY IT, for the LORD your God will surely require it of you, AND IT SHALL BE SIN IN YOU' — 'sin in you' at %s (15:9 the first, this the second, 24:15 the third); the doubled 'require' (the infinitive absolute at 23:22); 23:22 shares %d tokens with 15:9 and %d with Ecclesiastes 5:3" % (P('והיה', 'בך', 'חטא', books=T), TWIN['23:22 vs 15:9'], TWIN['23:22 vs Eccl 5:3']))
        move("the Sifrei 264:1-7 (read whole at the reading); MISHNAH ROSH HASHANAH 1:1 (the exam row, read whole); cold_run_vows (CALL) — VW.the_man(delay_clocks) = %s, VW.the_man(sin_in_you) = %s; cold_run_musafim (CALL) — MU.DATA[vow_deadline] read; cold_run_release_firstborn (CALL) — RF.DATA[the_cry_and_the_sin] read (bears_sin ONE on israel_people — SCANS %s)" % (VW_DELAY[0], VW_SIN[0], SCANS['bears_sin']), "'you shall not delay to pay it' — three feasts: the delay counted on the feasts' cycle (264:2 — vows' 'two dues — the positive at the first festival, the prohibition at the third; charity now' by CALL); the first of Nisan the New Year for the feasts' order (Rosh Hashanah 1:1 — the exam row: the delay's clock the feasts' cycle from Nisan, musafim's deadline row read); 'the LORD will surely require it' — the offering and the wife unmoved, the sin on the vower alone (vows' sin_in_you by CALL); 'it shall be sin in you' — 15:9's formula at its SECOND seat: bears_sin ONE on israel_people THE TAPE'S REFERENCE, never a second write (264:6-7; Numbers 30's vows_law_spoken the readback's reference)")
        dat("THE WRITE vow_delay_barred — a BLOCK on israel_people at the chapters' own day (DK2); THE PARAMETER the_delays_clock (three feasts from Nisan — Rosh Hashanah 1:1, vows' two dues); bears_sin the reference at its second seat; the exam's person who lets three feasts pass with his vow unpaid — the delay's prohibition transgressed")
        return out("when you vow a vow delay not (23:22) — three feasts from Nisan the clock, two dues; the sin on the vower alone; sin in you 15:9's formula at its second seat (the Sifrei 264:1-7; Mishnah Rosh Hashanah 1:1; vows' %s and musafim's deadline by CALL): THE WRITE vow_delay_barred, a BLOCK on Israel at the chapters' own day; the vower past three feasts transgresses" % (VW_DELAY[1][0],), ['vow_delay_barred'])
    if ask == 'if_you_refrain_from_vowing':
        ink('23:23', "'But IF YOU REFRAIN FROM VOWING, there shall be no sin in you' — 'sin in you' negated: the formula's four seats in the book %s (this the one negation)" % (P('בך', 'חטא', books=T),))
        move("the Sifrei 265:1-3 (read whole at the reading); cold_run_vows (CALL) — VW.the_man(vower_a_sinner) = %s" % (VW_SINNER[0],), "'if you refrain from vowing' — better that you do not vow at all than that you vow and do not pay: 'it is better that you do not vow' (Ecclesiastes 5:4 cited at 265:1); the vower called a sinner (vows' 'the vower called a sinner — the vow's standing on the shelf' by CALL); R. Meir — better than both, he who does not vow at all (265:2-3)")
        dat("THE WRITE vow_refraining_permitted — a STATUS on israel_people at the chapters' own day (DK2); the_vowers_standing a DATA row (the vower a sinner — Ecclesiastes 5:4; R. Meir's better-than-both); the exam's person who brings his offering without a vow — accepted, no sin in him")
        return out("if you refrain from vowing (23:23) — better not to vow at all; the vower called a sinner; R. Meir's better than both (the Sifrei 265:1-3; vows' %s by CALL): THE WRITE vow_refraining_permitted, a STATUS on Israel at the chapters' own day; the offerer without a vow accepted" % (VW_SINNER[1][0],), ['vow_refraining_permitted'])
    if ask == 'what_goes_out_of_your_lips':
        ink('23:24', "'WHAT GOES OUT OF YOUR LIPS YOU SHALL KEEP AND DO, as you vowed to the LORD your God, A FREEWILL OFFERING which you spoke with your mouth' — 'to the LORD' at 23:22 and 23:24 (the two of chapter 23's prefixed Name); the vow and the gift the two nouns")
        move("the Sifrei 266:1-4 (read whole at the reading); cold_run_vows (CALL) — VW.the_man(lips_or_heart) = %s, VW.the_man(vow_vs_gift) = %s" % (VW_LIPS[0], VW_GIFT[0]), "'what goes out of your lips' — the lips required: the heart's vow the Sifrei's arm, recorded (266:1 — vows' lips_or_heart by CALL); 'you shall keep' — a prohibition; 'and do' — a positive command (266:2); 'as you vowed' — a vow; 'a freewill offering' — a gift: the vow's debit persists past its object, the gift's dies with it (266:3 — vows' vow_vs_gift by CALL; Nedarim 1:1 by the English — the vow's substitutes); 'which you spoke with your mouth' — the utterance the bond (266:4)")
        dat("THE WRITE lips_utterance_binding — a STATUS on israel_people at the chapters' own day (DK2); the_vow_and_the_gift a DATA row (the vow's debit and the gift's — 266:3); the exam's person who vowed in his heart alone — the lips' arm not bound, the Sifrei's arm recorded")
        return out("what goes out of your lips (23:24) — the lips required, the heart's vow recorded; keep a prohibition, do a command; the vow's debit persists, the gift's dies with its object (the Sifrei 266:1-4; vows' %s by CALL): THE WRITE lips_utterance_binding, a STATUS on Israel at the chapters' own day; the heart's vower not bound by the lips" % (VW_GIFT[1][0],), ['lips_utterance_binding'])
    if ask == 'when_you_come_into_your_neighbors_vineyard':
        ink('23:25', "'When you come into your neighbor's vineyard, YOU MAY EAT GRAPES TO YOUR FILL as you desire, but INTO YOUR VESSEL YOU SHALL NOT PUT' — 'your neighbor' at 23:25 and 23:26 (%s the four chapters' five); Onkelos 'when you are HIRED' at 23:25 and 23:26 (the reading's find 4 — the spine's reading written into the verse)" % ([(c, v) for c, v in SPAN for x in W(c, v) if x in ('רעך', 'רעהו', 'לרעך', 'ברעהו')],))
        move("the Sifrei 266:1 (read whole at the reading — 266 heads on 23:25); Onkelos 23:25-26; Bava Metzia 7:2-8 by the English (the laborer's eating — OWED to the docket, the lean pass)", "'when you come into your neighbor's vineyard' — as a hired man: Onkelos 'when you are hired', the laborer and not the passerby (266:1; the Sifrei's reading Onkelos writes in); 'you may eat grapes to your fill' — the laborer eats of what he works at, of the attached at the end of its work (Bava Metzia 7:2-8 — the rows named in the English, NOT READ: the parameter OWED to the docket); 'into your vessel you shall not put' — the eating at the work, not the carrying home (266:1)")
        dat("THE WRITES laborer_eating_permitted (a STATUS) and laborer_vessel_barred (a BLOCK) on israel_people at the chapters' own day (DK2); THE PARAMETER the_laborers_eating OWED to the docket (Bava Metzia 7 by the English — the lean pass's debt line); the exam's person the passerby who eats of the vineyard — barred, no hire in him")
        return out("when you come into your neighbor's vineyard (23:25) — as a hired man, Onkelos's 'when you are hired'; the laborer eats to his fill at the work, nothing into his vessel; the eating's measures Bava Metzia 7's, owed to the docket (the Sifrei 266:1; Onkelos): THE WRITES laborer_eating_permitted and laborer_vessel_barred on Israel at the chapters' own day; the passerby barred", ['laborer_eating_permitted', 'laborer_vessel_barred'])
    if ask == 'the_standing_grain_and_the_sickle':
        ink('23:26', "'When you come into your neighbor's standing grain, YOU MAY PLUCK EARS WITH YOUR HAND, but A SICKLE YOU SHALL NOT SWING over your neighbor's standing grain' — 'a sickle' the same noun in Onkelos (the reading's find 4); the sickle 16:9's (the omer's count from the sickle) the book's other seat")
        move("the Sifrei 267:1-4 (read whole at the reading); Onkelos 23:26", "'when you come into your neighbor's standing grain' — the hired man again (267:1); 'you may pluck ears with your hand' — with the hand, not with a tool (267:2); 'a sickle you shall not swing' — the sickle the time of the reaping: while the sickle is in the standing grain, the laborer eats; Onkelos 'a sickle' the same noun (267:3 — the_sickles_time); 'your neighbor's standing grain' — not the sanctuary's (267:4)")
        dat("THE WRITE sickle_swinging_barred — a BLOCK on israel_people at the chapters' own day (DK2); the_sickles_time a DATA row (the reaping's time — 267:2-3); the exam's person the laborer who swings a sickle for his own eating — barred, the hand alone")
        return out("the standing grain and the sickle (23:26) — the hired man plucks with his hand; the sickle the reaping's time, not the laborer's tool; Onkelos the same noun (the Sifrei 267:1-4): THE WRITE sickle_swinging_barred, a BLOCK on Israel at the chapters' own day; the laborer's sickle barred", ['sickle_swinging_barred'])
    return 'no verdict in span', [], list(P_)
