import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place

# ---- THE CALLEES' FACTS (every edge live at the cells that consume them; the values asserted from the callees' own prints — ch22_callees.out, ch22_callees2.out, ch22_callees3.out, read BEFORE any assert was typed; 10b's lesson 2; the asks that need a case field — naso's ladder and who_is_sent, mekoshesh's stoning — asked with their fields as the third pass asked them) ----
def V(x): return x[0] if isinstance(x, tuple) else x
def Q(c): return (c.get('v'), c.get('p'), c.get('fx'), str(c.get('why', ''))) if isinstance(c, dict) else tuple(c)   # the (v, p, fx, why) cells — the dict's four keys as a tuple
def DD(m): return getattr(m, 'DATA', {})
# ordinances — Exodus 22-23's lost thing, the fallen ass, the pledge, the interest, the stranger (the Exodus cells READ THESE CHAPTERS FORWARD: the [IMPORT] marks)
OR_OX = Q(OR.courts('enemy_ox')); OR_STRAY = Q(OR.courts('straying')); OR_RET2 = Q(OR.courts('return_doubled')); OR_DECEIVER = Q(OR.courts('deceiver')); OR_WITH = Q(OR.courts('with_him')); OR_UNLOAD = Q(OR.courts('unload_load')); OR_MEASURE = Q(OR.courts('measure')); OR_COMMON = Q(OR.courts('common_case_animals')); OR_RIS = Q(OR.courts('ris')); OR_FATHER = Q(OR.courts('father_says_no'))
assert OR_OX[0] == 'return_it' and OR_OX[2] == ['restores'] and 'Deut 22:1-4 restates [IMPORT]' in OR_OX[3] and OR_STRAY[0] == 'outside_the_boundary' and OR_RET2[0] == 'even_four_and_five_times' and 'Deut 22:1' in OR_RET2[3] and OR_DECEIVER[0] == 'examine_the_claimant' and OR_WITH[0] == 'owner_idle_exempts' and OR_WITH[2] == ['unloading_owed'] and OR_UNLOAD[0] == 'unloading_torah_loading_disputed' and OR_MEASURE[0] == 'a_load_it_can_bear' and OR_COMMON[0] == 'ox_or_donkey_names_the_common_case' and OR_RIS[0] == 'one_in_seven_and_a_half_of_a_mil' and OR_RIS[1] == 'DATA' and OR_FATHER[0] == 'do_not_listen', (OR_OX[:3], OR_STRAY[0], OR_RET2[0], OR_DECEIVER[0], OR_WITH[:3], OR_UNLOAD[0], OR_MEASURE[0], OR_COMMON[0], OR_RIS[:2], OR_FATHER[0])
OR_BITE = Q(OR.loan('bite_noun')); OR_FOREIGN = Q(OR.loan('foreigner')); OR_COURT = Q(OR.loan('court_only')); OR_WIDOW = Q(OR.loan('widow_not_pledged')); OR_DAYNIGHT = Q(OR.loan('day_night_garments')); OR_SUNSET = Q(OR.loan('pledge_sunset')); OR_FIVE = Q(OR.loan('five_prohibitions')); OR_WHO = Q(OR.loan('who_transgresses')); OR_WORDS = Q(OR.stranger('words_vs_money'))
assert OR_BITE[0] == 4 and OR_BITE[2] == ['interest_barred'] and 'Deut' in OR_BITE[3] and 'Num' in OR_BITE[3] and OR_FOREIGN[0] == 'permitted' and 'Deut 23:21 by import' in OR_FOREIGN[3] and OR_COURT[0] == 'only_through_the_court_outside_you_stand' and 'Deut 24:11 [IMPORT]' in OR_COURT[3] and OR_WIDOW[0] == 'never_pledged_rich_or_poor' and 'Deut 24:17 [IMPORT]' in OR_WIDOW[3] and 'Deut 24:6' in OR_WIDOW[3] and OR_DAYNIGHT[0] == 'day_garment_by_day_night_garment_by_night' and "Deut 24:13" in OR_DAYNIGHT[3] and OR_SUNSET[0] == 'until_the_sun_sets' and OR_SUNSET[2] == ['pledge_returned_by_sunset'] and len(OR_FIVE[0]) == 5 and OR_WHO[0] == ['lender', 'borrower', 'guarantor', 'witnesses'] and OR_WORDS[0] == 'yesterday_an_idolater_banned', (OR_BITE[:3], OR_FOREIGN[0], OR_COURT[0], OR_WIDOW[0], OR_DAYNIGHT[0], OR_SUNSET[:3], OR_FIVE[0], OR_WHO[0], OR_WORDS[0])
# mishpatim_2 and mishpatim — the seducer's fifty a POINTER to 22:29; the strivers' humiliation an IMPORT from 25:11-12
assert ('fifty', 2572, 'Deut', 22, 29) in M2.PROBES and ('dowry', 4119, 'Exod', 22, 16) in M2.PROBES, M2.PROBES[:3]
M2_SEDUCER = [e for e in M2.EFFECTS if e[0].startswith('seducer:')]; assert [e[0] for e in M2_SEDUCER] == ['seducer: FINE to the father', 'seducer: FETCH-50 (the pointer)', 'seducer: payments TABLE'] and M2_SEDUCER[0][1] == ['gives_fixed_sum'] and M2_SEDUCER[2][1] == ['pays'], M2_SEDUCER
MI_SRC = inspect.getsource(MI.law_mishpatim); assert "F4 HUMILIATION [IMPORT Deut 25:11-12]" in MI_SRC and "'pays'" in MI_SRC, MI_SRC[:200]   # the Exodus cell's humiliation carries this chapter's verse
# holiness and holiness_b — Leviticus 19's gifts, wage, judgment; the mixtures ROUTED here; the lashing procedure
HO_KINDS = Q(HO.gifts('kinds')); HO_OLELET = Q(HO.gifts('olelet')); HO_PERET = Q(HO.gifts('peret')); HO_EDGES = Q(HO.gifts('olelet_edges')); HO_ALIEN = Q(HO.wage('resident_alien')); HO_OPPR = Q(HO.wage('oppression_class')); HO_HIRE = Q(HO.wage('hire_kinds')); HO_MORNING = Q(HO.wage('first_morning')); HO_FIVE = Q(HO.conduct('five_effects')); HO_EQUAL = Q(HO.conduct('equal_treatment'))
assert HO_KINDS[0] == ['corner', 'fallen_grapes', 'gleanings', 'small_clusters'] and HO_KINDS[2] == ['left_for_the_poor'] and "Deut 24:19-20's [IMPORT]" in HO_KINDS[3] and HO_OLELET[0] == 'small_cluster_the_poor' and HO_PERET[0] == 'what_falls_at_the_cutting' and isinstance(HO_EDGES[0], dict) and HO_ALIEN[0] == 'under_on_his_day_not_under_until_morning' and 'Deut 24:14' in HO_ALIEN[3] and '[IMPORT]' in HO_ALIEN[3] and HO_OPPR[0] == 'the_money_class_the_wage_withholder' and HO_HIRE[0] == ['man', 'beast', 'tools', 'land'] and HO_MORNING[0] == 'the_first_morning_only' and HO_MORNING[2] == ['wage_due_by_morning'] and len(HO_FIVE[0]) == 5 and HO_FIVE[2] == ['judgment_perverted'] and len(HO_EQUAL[0]) == 2, (HO_KINDS[:3], HO_ALIEN[0], HO_OPPR[0], HO_HIRE[0], HO_MORNING[:3], HO_FIVE[0])
HB_VINE = Q(HB.mixtures('vineyard')); HB_PLOW = Q(HB.mixtures('plowing')); HB_MAT = Q(HB.mixtures('materials')); HB_DEF = Q(HB.mixtures('shaatnez_defined')); HB_WEAR = Q(HB.mixtures('wearing_vs_covering')); HB_CLASS = Q(HB.mixtures('class_table')); HB_MULE = Q(HB.mixtures('mule_kind')); HB_LASH = Q(HB.maidservant('lashing_procedure'))
assert HB_VINE[0] == 'routed_Deut_22_9' and HB_VINE[1] == 'IMPORT' and HB_PLOW[0] == 'routed_Deut_22_10' and HB_MAT[0] == 'wool_and_linen_only' and 'Deut 22:11' in HB_MAT[3] and HB_DEF[0] == ['carded', 'spun', 'woven'] and HB_WEAR[0]['wear'] == 'banned' and isinstance(HB_CLASS[0], dict) and HB_MULE[0] == 'follows_the_mother_R._Yehuda' and "Deut 22:10" in HB_MULE[3] and HB_LASH[0] == 'reader_reads_died_under_hand_exempt_extra_strap_exile' and HB_LASH[2] == ['lashes'], (HB_VINE[:2], HB_PLOW[0], HB_MAT[0], HB_DEF[0], HB_MULE[0], HB_LASH[:3])
# sanctions — Leviticus 18-20's grades, the strangled and the lashed, the levirate's fifteen and the bonds, the excision discharged
SA_FW = Q(SA.grade('fathers_wife')); SA_BW = Q(SA.grade('brothers_wife')); SA_MW = Q(SA.grade('married_woman')); SA_STRANGLED = Q(SA.census('strangled')); SA_LASHES = Q(SA.census('lashes')); SA_FIFTEEN = Q(SA.levirate('fifteen')); SA_SIX = Q(SA.levirate('six')); SA_COUNT = Q(SA.levirate('count')); SA_NIW = Q(SA.levirate('not_in_world')); SA_RIVAL = Q(SA.levirate('rival_chain')); SA_HOUSES = Q(SA.levirate('houses')); SA_TWO = Q(SA.cowives('two_bonds')); SA_DISCH = Q(SA.frame('lashes_discharge_karet')); SA_SIT = Q(SA.frame('sit_and_abstain'))
assert SA_FW[0] == 'release_or_levirate' and "Deut 25:5's ordinary case [IMPORT]" in SA_FW[3] and SA_BW[0] == 'release_or_levirate' and SA_MW[0] == 'neither_release_nor_levirate' and SA_MW[2] == ['exempt'] and SA_STRANGLED[0] == ["a man's wife"] and SA_STRANGLED[2] == ['put_to_death'] and len(SA_LASHES[0]) == 7 and SA_LASHES[2] == ['lashes'] and "Deut 25:2-3's [IMPORT]" in SA_LASHES[3] and len(SA_FIFTEEN[0]) == 15 and 'his daughter-in-law' in SA_FIFTEEN[0] and 'the wife of a brother not in his world' in SA_FIFTEEN[0] and len(SA_SIX[0]) == 6 and SA_COUNT[0] == (15, 6) and SA_NIW[0] == 'exempt_and_her_rival_exempt' and 'Deut 25:5' in SA_NIW[3] and SA_RIVAL[0] == 'rival_of_rival_exempt_even_a_hundred' and SA_HOUSES[0] == ['Beit_Shammai_permit_the_rivals', 'Beit_Hillel_forbid'] and SA_TWO[0] == 'release_not_levirate_one_levir_not_two' and '(Deut 25:5) [IMPORT]' in SA_TWO[3] and SA_DISCH[0] == ['discharged_R._Chananya_b._Gamliel'] and 'Deut 25:3 [IMPORT]' in SA_DISCH[3] and SA_SIT[0] == 'rewarded_as_one_who_did_a_commandment', (SA_FW[0], SA_MW[:3], SA_STRANGLED[:3], len(SA_LASHES[0]), len(SA_FIFTEEN[0]), SA_COUNT[0], SA_NIW[0], SA_TWO[0], SA_DISCH[0])
# priesthood — the harlot's definition, the released widow, the crushed
PR_ZONAH = Q(PR.family('zonah')); PR_CHAL = Q(PR.family('chalutzah')); PR_CASTR = Q(PR.acceptable('castration'))
assert PR_ZONAH[0]['sages'] == ['the_convert', 'the_freed_slavewoman', 'illicit_intercourse'] and PR_ZONAH[2] == ['profaned_seed'] and len(PR_CHAL[0]) == 4 and PR_CHAL[0][0] == 'barred_by_a_fortiori_from_the_divorcee' and PR_CASTR[0]['humans'] == 'by_revocalization_and_in_you' and PR_CASTR[2] == ['lashes'] and 'Yevamot 8:2' in PR_CASTR[3], (PR_ZONAH[0], PR_CHAL[0][:2], PR_CASTR[0].get('humans'))
# yovel — the interest's two nouns, THE IMPORT EDGE M-07 naming 23:21
YV_INT = {k: Q(v) for k, v in YV.interest().items()}; YV_FOREIGN = Q(YV.interest_scope('foreigner')); YV_BROTHER = Q(YV.interest_scope('brother'))
assert YV_INT['both_nouns'][0] == 'barred' and YV_INT['definitions'][0] == 'money_bite_vs_produce_increase' and YV_FOREIGN[0] == 'permitted' and 'IMPORT EDGE (M-07)' in YV_FOREIGN[3] and 'Deut 23:21' in YV_FOREIGN[3] and YV_BROTHER[0] == 'barred' and YV_BROTHER[2] == ['interest_barred'], (YV_INT['both_nouns'][0], YV_FOREIGN[:2], YV_BROTHER[:3])
# vows and musafim — the delay's clocks, the sin on the vower, the lips, the vow and the gift; the levirate widow's vow; the feasts' deadline
VW_DELAY = VW.the_man({'ask': 'delay_clocks'}, VW.DATA)[:2]; VW_SIN = VW.the_man({'ask': 'sin_in_you'}, VW.DATA)[:2]; VW_LIPS = VW.the_man({'ask': 'lips_or_heart'}, VW.DATA)[:2]; VW_GIFT = VW.the_man({'ask': 'vow_vs_gift'}, VW.DATA)[:2]; VW_SINNER = VW.the_man({'ask': 'vower_a_sinner'}, VW.DATA)[:2]; VW_WIDOW = VW.the_widow({'ask': 'levirate'}, VW.DATA)[:2]
assert VW_DELAY[0].startswith('two dues — the positive at the first festival, the prohibition at the third') and VW_DELAY[1] == ['commanded'] and VW_SIN[0].startswith("the delay's sin on the vower alone") and VW_SIN[1] == ['accepted'] and VW_LIPS[0].startswith('the lips required') and VW_GIFT[0].startswith("the vow's debit persists past its object") and VW_GIFT[1] == ['vow_bound'] and VW_SINNER[0].startswith('the vower called a sinner') and VW_WIDOW[0].startswith('awaiting the brother-in-law') and VW_WIDOW[1] == ['vow_bound'], (VW_DELAY, VW_SIN[0][:40], VW_GIFT[1], VW_WIDOW)
MU_DEADLINE = MU.DATA['vow_deadline']; assert MU_DEADLINE, 'the feasts\' deadline row'
# naso, negaim, metzora, beha — the three camps' ladder (the emitter's camp NOT in Numbers 5's span), the tracks, the right members, Miriam
NS_LEPER = NS.camp_purity({'ask': 'ladder', 'who': 'leper'}, NS.DATA)[:2]; NS_ZAV = NS.camp_purity({'ask': 'ladder', 'who': 'zav'}, NS.DATA)[:2]; NS_CORPSE = NS.camp_purity({'ask': 'ladder', 'who': 'corpse_unclean'}, NS.DATA)[:2]; NS_EMITTER = NS.camp_purity({'ask': 'who_is_sent', 'what': 'seed_emitter'}, NS.DATA)[:2]; NS_CLASSES = NS.camp_purity({'ask': 'classes'}, NS.DATA)[:2]
assert NS_LEPER[0] == 'out of all three camps (Israel, Levi, the Presence)' and NS_ZAV[0] == 'out of two (Levi and the Presence)' and NS_CORPSE[0] == 'out of one (the Presence)' and NS_LEPER[1] == ['sent_outside_the_camp'] and NS_EMITTER[0] == 'no verdict in span' and NS_CLASSES[0] == 'the leper, the zav, the corpse-unclean — three classes', (NS_LEPER, NS_ZAV, NS_CORPSE, NS_EMITTER, NS_CLASSES)   # THE NIGHT'S CHANCE IS THIS CHAPTER'S OWN LAW
NG_SKIN = NG.standing_verdict('skin'); NG_HOUSE = NG.standing_verdict('house'); assert NG_SKIN == 'RELEASED' and NG_HOUSE == 'PULL-SCRAPE-PLASTER', (NG_SKIN, NG_HOUSE)
MT_MEMBERS = Q(MT.eighth('members')); assert MT_MEMBERS[0] == 'right_ear_ridge_right_thumb_right_toe' and '14:14' in MT_MEMBERS[3], MT_MEMBERS[:2]
BH_REMEMBER = BH.miriam({'ask': 'remember_miriam'}, BH.DATA)[:2]; BH_KIN = BH.miriam({'ask': 'kin_rule'}, BH.DATA)[:2]; BH_DECLARED = BH.miriam({'ask': 'who_declared'}, BH.DATA)[:2]
assert BH_REMEMBER == ('the paradigm of evil speech (Deut 24:9)', ['evil_speech_spoken']) and BH_KIN[0].endswith('only a priest declares') and BH_KIN[1] == ['stricken_with_leprosy'] and BH_DECLARED[1] == ['stricken_with_leprosy'], (BH_REMEMBER, BH_KIN, BH_DECLARED)
# balak and exodus_story — the hire and the curse turned (the block never closed — THE RUN IS HERE); Amalek's blotting a heaven entry open to this chapter
BK_CURSE = BK.the_call({'ask': 'cursing_barred'}, BK.DATA)[:2]; BK_HONOR = BK.the_call({'ask': 'honor_promised'}, BK.DATA)[:2]; BK_ROOTS = BK.the_call({'ask': 'curse_roots'}, BK.DATA)[:2]
assert BK_CURSE[0].startswith("cursing barred — 'you shall not curse the people, for it is blessed' (22:12): a block never closed; Deut 23:6 the run") and BK_CURSE[1] == ['cursing_barred'] and BK_HONOR[1] == ['honor_owed'] and 'Deut 23:6' in BK_ROOTS[0], (BK_CURSE[0][:60], BK_HONOR, BK_ROOTS[0][:80])
ES_BLOT = Q(ES.amalek('blotting')); ES_WEAK = Q(ES.amalek('weakened_seat'))
assert ES_BLOT[0] == 'open_to_deuteronomy_and_samuel' and ES_BLOT[2] == ['amalek_to_be_blotted'] and "Deut 25:19's command and 1 Sam 15's run are book-bound" in ES_BLOT[3] and ES_WEAK[0] == 1 and ES_WEAK[2] == ['amalek_weakened'], (ES_BLOT[:3], ES_WEAK[:3])
# family, zelophehad, joseph, primeval — Genesis 38's levirate READ FORWARD to this chapter; the clause that opens two institutions; the folly and the bride-price; Hagar's word and the muzzled beasts
FA_CMD = Q(FA.levirate('the_command')); FA_SEED = Q(FA.levirate('seed_vs_name')); FA_NAME = Q(FA.levirate('name_is_inheritance')); FA_RUTH = Q(FA.levirate('name_on_inheritance_ruth')); FA_NOSON = Q(FA.levirate('no_son_clause')); FA_NOSHOE = Q(FA.levirate('no_release_form')); FA_KEDESHA = Q(FA.levirate('kedesha')); FA_WAIT = Q(FA.levirate('widow_waiting')); FA_MAMZER = Q(FA.levirate('mamzer_definition')); FA_ORDER = Q(FA.levirate('order_of_sons')); FA_SCOPE = Q(FA.levirate('kin_scope_narrowed')); FA_15 = Q(FA.levirate('fifteen_by_call')); FA_NAAR = Q(FA.commission('naar_ketiv'))
assert FA_CMD[0] == 3 and "['Deut 25:5', 'Deut 25:7', 'Deut 25:9', 'Gen 38:8', 'Ruth 1:15']" in FA_CMD[3] and FA_SEED[0] == ((1, 2), [(5, 0), (6, 1), (7, 1)]) and FA_NAME[0] == (1, 1) and 'Deut 25:6' in FA_NAME[3] and FA_RUTH[0] == ['Ruth 4:5', 'Ruth 4:10'] and FA_NOSON[0] == ['Deut 25:5', 'Num 27:8'] and FA_NOSHOE[0] == (False, ['1Sam 9:9', 'Ruth 4:7']) and FA_NOSHOE[2] == ['waits_for_the_levir'] and FA_KEDESHA[0] == [(21, 2), (22, 1)] and 'Deut 23:18' in FA_KEDESHA[3] and FA_WAIT[0] == (3, 'her_acts_stand') and FA_MAMZER[0] == ['R_Akiva_any_prohibited_kin', 'Shimon_the_Temanite_karet_the_ruling', 'R_Yehoshua_court_death'] and FA_ORDER[0] == (True, True, True, True, True) and FA_SCOPE[0] == 'kinsman_pre_sinai_brother_at_sinai' and FA_15[0] == ((15, 6), True) and FA_NAAR[0] == (5, 0) and FA_NAAR[2] == ['consent_given'], (FA_CMD[:2], FA_SEED[0], FA_NAME[0], FA_NOSON[0], FA_NOSHOE[0], FA_KEDESHA[0], FA_WAIT[0], FA_MAMZER[0][:1], FA_ORDER[0], FA_15[0], FA_NAAR[0])
ZL_DILEMMA = ZL.the_daughters({'ask': 'levirate_dilemma'}, ZL.DATA)[:2]; ZL_NAME = ZL.the_daughters({'ask': 'name_is_inheritance'}, ZL.DATA)[:2]; ZL_CHILD = ZL.the_daughters({'ask': 'child_of_any_kind'}, ZL.DATA)[:2]
assert ZL_DILEMMA[0].endswith('as offspring they exempt their mother (Deut 25:5) — no bond') and ZL_DILEMMA[1] == ['holding_owed', 'exempt'] and ZL_NAME[0].endswith("the levirate's word (Deut 25:6) read from 48:6") and ZL_CHILD == ('bound — no child, a brother in the world', ['levirate_owed']), (ZL_DILEMMA, ZL_NAME, ZL_CHILD)
JO_FOLLY = Q(JO.dinah('outrage_phrase')); JO_MOHAR = Q(JO.dinah('mohar_by_call')); JO_SHEET = Q(JO.dinah('seducer_sheet'))
assert JO_FOLLY[0] == 'not_done_in_israel' and JO_FOLLY[2] == ['outrage_in_israel'] and JO_MOHAR[0] == ('FETCH-50', 4) and "Deut 22:29's fifty" in JO_MOHAR[3] and JO_SHEET[0] == ('three', 'four'), (JO_FOLLY[:3], JO_MOHAR[0], JO_SHEET[0])
PV_HAGAR = Q(PV.hagar('affliction_reading')); PV_MUZZLED = Q(PV.separation('muzzled'))
assert PV_HAGAR[0] == 'not_obliged_for_her_good_or_ill' and PV_HAGAR[2] == ['afflicted'] and PV_MUZZLED[0] == 'abrahams_beasts_muzzled_lots_not' and PV_MUZZLED[2] == ['strife_between_herdsmen'] and '13:7' in PV_MUZZLED[3], (PV_HAGAR[:3], PV_MUZZLED[:3])
# mekoshesh and seducers — the stoning rite, the hand first, the purge formula's nine seats
MK_STONING = MK.capital_procedure({'ask': 'stoning', 'died_at': 'the stoning house'}, MK.DATA)[:2]; MK_BURIAL = MK.capital_procedure({'ask': 'burial'}, MK.DATA)[:2]
assert MK_STONING == ("stoned by all the people with stones — the witnesses' hand first", ['stoned']) and MK_BURIAL[1] == ['buried'], (MK_STONING, MK_BURIAL)
SE_NINE = SE.the_readback({'ask': 'the_purge_formulas_nine_seats'}, SE.DATA)[:2]; SE_HAND = SE.the_inciter({'ask': 'the_hand_first'}, SE.DATA)[:2]; SE_RITE = SE.the_inciter({'ask': 'the_stoning_rite'}, SE.DATA)[:2]; SE_TWO = SE.the_readback({'ask': 'the_two_verbs_of_stoning'}, SE.DATA)[:2]
assert SE_NINE[0].startswith("the purge formula's nine seats — 9 on the DB, all in the book, 13:6 the first") and SE_NINE[1] == ['accepted'] and SE_HAND[1] == ['accepted'] and SE_RITE[1] == ['stoned', 'evil_purged_from_the_midst'] and SE_TWO[1] == ['accepted'], (SE_NINE[0][:60], SE_HAND[1], SE_RITE[1])
# refuge_war_family, courts_prophet, festivals_judges, second_tablets, release_firstborn, covenant_at_horeb, seven_nations, place_name, hear_o_israel, lev24 — the book's own cells
RW_TALION = RW.the_landmark_and_the_witnesses({'ask': 'the_talion_in_be'}, RW.DATA)[:2]; RW_ONE = RW.the_landmark_and_the_witnesses({'ask': 'one_witness_for_any_iniquity'}, RW.DATA)[:2]; RW_VIOLENT = RW.the_landmark_and_the_witnesses({'ask': 'the_violent_witness_and_the_woman'}, RW.DATA)[:2]; RW_PLOTTED = RW.the_landmark_and_the_witnesses({'ask': 'as_he_plotted'}, RW.DATA)[:2]; RW_FOUR = RW.the_priests_speech({'ask': 'the_four_exemptions'}, RW.DATA)[:2]; RW_RELEASE = RW.the_captive({'ask': 'if_you_delight_not_in_her'}, RW.DATA)[:2]
assert RW_TALION[1] == ['talion_pity_barred', 'pays'] and "lev24's PAY-MONEY by CALL" in RW_TALION[0] and RW_ONE[1] == ['two_or_three_witnesses_required'] and RW_VIOLENT[1] == ['exempt'] and RW_PLOTTED[0] != 'no verdict in span' and RW_FOUR[1] == ['officers_exemptions_commanded'] and 'Sotah 8:2' in RW_FOUR[0] and RW_RELEASE[1] == ['captive_release_commanded', 'captive_sale_barred'] and 'divorce document' in RW_RELEASE[0], (RW_TALION[1], RW_ONE[1], RW_VIOLENT[1], RW_FOUR[1], RW_RELEASE[1])
CP_HIRE = CP.the_blemished_sacrifice({'ask': 'the_mounter_and_the_harlots_hire'}, CP.DATA)[:2]
assert CP_HIRE[1] == ['barred_from_it'] and '23:19 the shared word' in CP_HIRE[0] and '261:2' in CP_HIRE[0], CP_HIRE
FJ_WREST = FJ.the_judges_in_every_gate({'ask': 'wrest_no_judgment'}, FJ.DATA)[:2]; FJ_TIERS = FJ.the_judges_in_every_gate({'ask': 'the_three_tiers'}, FJ.DATA)[:2]
assert FJ_WREST[1] == ['judgment_wresting_barred'] and "24:17's twins" in FJ_WREST[0] and FJ_TIERS[0] != 'no verdict in span', (FJ_WREST, FJ_TIERS[0][:60])
ST_ORPHAN = ST.the_god_of_gods_and_the_stranger({'ask': 'the_orphan_and_the_widow'}, ST.DATA)[:2]; ST_LOVE = ST.the_god_of_gods_and_the_stranger({'ask': 'and_you_shall_love_the_stranger'}, ST.DATA)[:2]
assert ST_ORPHAN[1] == ['accepted'] and "Exodus 22:21's pair" in ST_ORPHAN[0] and ST_LOVE[1] == ['love_owed'], (ST_ORPHAN, ST_LOVE[1])
RF_CRY = RF.DATA['the_cry_and_the_sin']; assert RF_CRY and 'value' in RF_CRY, list(RF_CRY)[:3]
CH_KEEP = CH.the_first_tablet({'ask': 'keep_and_remember'}, CH.DATA)[:2]; CH_OXASS = CH.the_first_tablet({'ask': 'the_ox_and_the_ass'}, CH.DATA)[:2]; CH_GROUNDS = CH.the_first_tablet({'ask': 'the_two_grounds'}, CH.DATA)[:2]; CH_REWARD = CH.DATA['the_reward_clause']
assert CH_KEEP[0].startswith('keep and remember (5:12) — one utterance') and CH_KEEP[1] == ['accepted'] and CH_OXASS[0].startswith('the ox and the ass (5:14) — every animal by the verbal analogy') and CH_GROUNDS[0].startswith('the two grounds (5:15)') and CH_REWARD, (CH_KEEP[0][:40], CH_OXASS[0][:40], CH_GROUNDS[0][:40])
SN_ABOM = SN.the_images_and_the_devoted({'ask': 'abomination_to_the_lord'}, SN.DATA)[:2]
assert SN_ABOM[0].startswith("an abomination to the LORD (7:25) — the book's phrase at its first seat") and SN_ABOM[1] == ['accepted'], SN_ABOM
PN_INQ = PN.the_nations_cut_off_and_the_abomination({'ask': 'lest_you_inquire_after_their_gods'}, PN.DATA)[:2]; assert PN_INQ[1] == ['foreign_rite_inquiry_barred'], PN_INQ
HI_SEVEN = HI.the_four_duties({'ask': 'the_seven'}, HI.DATA)[:2]; assert HI_SEVEN[0].startswith('the seven (6:8-9) — the head, the arm, four fringes, the mezuzah') and HI_SEVEN[1] == ['accepted'], HI_SEVEN
L24_HAND = L24.talion('hand'); assert L24_HAND['verdict'] == 'PAY-MONEY' and L24_HAND['blemish'] == 'hand' and L24_HAND['effect'] == 'substitution', L24_HAND
GL_R = [GL.receipt_seats(c) for c in (22, 23, 24, 25)]; assert GL_R == [[], [], [], []], GL_R   # NO receipt in the four chapters — the finder's own count
print('THE CALLEES (printed after they are asserted): OR %s; M2 %s; HO %s; HB %s; SA %s; PR %s; YV %s; VW %s; NS %s; NG %s; MT %s; BH %s; BK %s; ES %s; FA %s; ZL %s; JO %s; PV %s; MK %s; SE %s; RW %s; CP %s; FJ %s; ST %s; CH %s; SN %s; PN %s; HI %s; L24 %s; GL %s' % (OR_OX[0], M2_SEDUCER[1][0], HO_KINDS[0][:2], HB_VINE[0], SA_COUNT[0], PR_ZONAH[0]['sages'][:1], YV_FOREIGN[0], VW_DELAY[1], NS_EMITTER[0], NG_SKIN, MT_MEMBERS[0][:20], BH_REMEMBER[1], BK_CURSE[1], ES_BLOT[0], FA_NOSON[0], ZL_CHILD[1], JO_MOHAR[0], PV_MUZZLED[0][:20], MK_STONING[1], SE_NINE[1], RW_TALION[1], CP_HIRE[1], FJ_WREST[1], ST_LOVE[1], CH_KEEP[1], SN_ABOM[1], PN_INQ[1], HI_SEVEN[1], L24_HAND['verdict'], GL_R))
