

def the_pledge_and_the_wage(case, data):
    """F11 — Deut 24:10-15 — ONE LINE pledge_wage_declared writing poor_mans_pledge_return_commanded and hireling_wage_same_day_commanded (STATUSES), pledge_entry_barred and hireling_oppression_barred (BLOCKS) and righteousness_before_the_lord (a HEAVEN entry); Exodus 22:25-26's pledge by CALL (ordinances — the Exodus cell READ 24:11 and 24:13 FORWARD), Leviticus 19:13's wage by CALL (holiness — 24:14 forward), 15:9's cry and sin by CALL (release_firstborn); Bava Metzia 9:13 the exam row"""
    del P_[:]
    ask = case['ask']
    if ask == 'when_you_lend_your_neighbor_any_loan':
        ink('24:10-11', "'When you lend your neighbor any loan, YOU SHALL NOT GO INTO HIS HOUSE TO TAKE HIS PLEDGE; OUTSIDE YOU SHALL STAND, and the man to whom you lend shall bring out the pledge to you outside' — no verse of the Bible shares two of 24:10's words (KINC %s); the pledge's six seats in Onkelos (%s)" % (KINC[(24, 10)], [(24, 6), (24, 10), (24, 11), (24, 12), (24, 13), (24, 17)]))
        move("the Sifrei 276:1-3 (read whole at the reading); MISHNAH BAVA METZIA 9:13 (the exam row, read whole); cold_run_ordinances (CALL) — OR.loan(court_only) = %s ('outside you shall stand (Deut 24:11 [IMPORT])')" % (OR_COURT[0],), "'you shall not go into his house to take his pledge' — only through the court's agent: he who lends his fellow takes a pledge only by the court, and does not enter his house to take it — 'outside you shall stand' (Bava Metzia 9:13 — the exam row; 276:1-2); if he had two vessels, he takes one and leaves one; he returns the pillow by night and the plow by day; if he died he does not return to his heirs; Rabban Shimon b. Gamliel — even to himself he returns only until thirty days, and from thirty days he sells them by the court (9:13); THE EXODUS CELL READ 24:11 FORWARD — its 'court_only' carries this verse in its why (ordinances by CALL); 'the man to whom you lend' — the borrower brings it out (276:3)")
        dat("THE WRITE pledge_entry_barred — a BLOCK on israel_people at the chapters' own day (DK2); the_courts_agent a DATA row (Bava Metzia 9:13 — the court alone, two vessels one taken one left, the heirs not returned, thirty days then the sale); the exam's person the creditor who enters the borrower's house for the pledge — barred, outside he stands")
        return out("when you lend your neighbor any loan (24:10-11) — the pledge by the court's agent alone, outside he stands; two vessels one taken one left; the Exodus cell read 24:11 forward (the Sifrei 276:1-3; Mishnah Bava Metzia 9:13; ordinances' %s by CALL): THE WRITE pledge_entry_barred, a BLOCK on Israel at the chapters' own day; the creditor at the door barred" % (OR_COURT[0],), ['pledge_entry_barred'])
    if ask == 'the_poor_mans_pledge_at_sunset':
        ink('24:12-13', "'And if he is a poor man, you shall not sleep with his pledge: RETURN, YOU SHALL RETURN HIM THE PLEDGE WHEN THE SUN SETS, that he sleep in his garment and bless you; AND IT SHALL BE RIGHTEOUSNESS TO YOU BEFORE THE LORD YOUR GOD' — the doubled 'return' at 24:13 (22:1's form); 24:13 shares %d token with Exodus 22:25 (the sunset's clause); Onkelos 'merit' (zekhuta) for righteousness (the reading's find 15)" % (TWIN['24:13 vs Exod 22:25'],))
        move("the Sifrei 277:1-5 (read whole at the reading); cold_run_ordinances (CALL) — OR.loan(day_night_garments) = %s ('paired with Deut 24:13's sunset return'), OR.loan(pledge_sunset) = %s" % (OR_DAYNIGHT[0], OR_SUNSET[0]), "'you shall not sleep with his pledge' — the night's vessel returned for the night, the day's for the day: a blanket at night, a plow by day (277:1-3 — the reading's find 7; the Exodus cell's 'day_garment_by_day_night_garment_by_night' PAIRED with this verse by its own why); 'return it to him when the sun sets' — the sunset a CLOCK parameter, Exodus 22:25's 'until the sun sets' the Sinai seat (pledge_returned_by_sunset ZERO on the running world — SCANS %s: the Exodus timer never set on a person, the reference); 'and it shall be righteousness to you before the LORD' — righteousness before the throne: Psalm 85:14 cited (277:5 — the reading's find 9: THE HEAVEN ENTRY; Onkelos 'merit')" % (SCANS['pledge_returned_by_sunset'],))
        dat("THE WRITES poor_mans_pledge_return_commanded (a STATUS) and righteousness_before_the_lord (a HEAVEN entry — Psalm 85:14 by the spine) on israel_people at the chapters' own day (DK2); THE PARAMETER the_sunset_return (a clock parameter, no timer at a line); the_vessels_by_time a DATA row (the blanket at night, the plow by day — 277:3); the exam's person the creditor who returns the plow by day and holds it by night — the day's vessel returned in its time, accepted")
        return out("the poor man's pledge at sunset (24:12-13) — the night's vessel for the night, the day's for the day; returned when the sun sets, the Exodus timer's clause paired here; righteousness before the throne, Onkelos merit (the Sifrei 277:1-5; ordinances' %s and %s by CALL): THE WRITES poor_mans_pledge_return_commanded and righteousness_before_the_lord on Israel at the chapters' own day; the plow by day accepted" % (OR_DAYNIGHT[0], OR_SUNSET[0]), ['poor_mans_pledge_return_commanded', 'righteousness_before_the_lord'])
    if ask == 'you_shall_not_oppress_a_hired_man':
        ink('24:14', "'YOU SHALL NOT OPPRESS A HIRED MAN, POOR AND NEEDY, of your brothers or of your sojourner in your land in your gates' — 'poor and needy' at %s in the Torah, once (the reading's find 16; %d seats in the Bible); 24:14 shares %d tokens with Leviticus 19:13" % (P('עני', 'ואביון', books=T), len(P('עני', 'ואביון', books=None)), TWIN['24:14 vs Lev 19:13']))
        move("the Sifrei 278:1-3 (read whole at the reading); cold_run_holiness (CALL) — HO.wage(oppression_class) = %s, HO.wage(hire_kinds) = %s, HO.wage(resident_alien) = %s ('Deut 24:14 of your convert [IMPORT] yes; 19:13 your NEIGHBOR no')" % (HO_OPPR[0], HO_HIRE[0], HO_ALIEN[0]), "'you shall not oppress a hired man' — four prohibitions for one withheld wage: 'oppress not' and 'rob not' (Leviticus 19:13), 'the wage shall not stay overnight' (19:13), 'on his day you shall give' (24:15) — the reading's find 8 (278:1); oppression the money class (holiness' 'the_money_class_the_wage_withholder' by CALL); the hire of man, beast, tools, land (holiness' hire_kinds by CALL — Bava Metzia 9:12); 'of your brothers or of your sojourner' — THE LEVITICUS CELL READ THIS VERSE FORWARD: the resident alien under 'on his day', not under 'until morning' — 'Deut 24:14 of your convert [IMPORT] yes' in its own why (278:2-3; Bava Metzia 9:12 by the English); wage_due_by_morning ZERO on the running world — the reference (SCANS %s)" % (SCANS['wage_due_by_morning'],))
        dat("THE WRITE hireling_oppression_barred — a BLOCK on israel_people at the chapters' own day (DK2); the_four_prohibitions a DATA row (278:1 — the reading's find 8); the_resident_alien a DATA row (under on his day, not until morning — the Leviticus cell's forward reading); the exam's person the employer who withholds his sojourner's wage past the night — under this verse's 'on his day', not Leviticus's 'until morning'")
        return out("you shall not oppress a hired man (24:14) — poor and needy once in the Torah; four prohibitions for one withheld wage; the money class; the sojourner under this verse's clause — the Leviticus cell read 24:14 forward (the Sifrei 278:1-3; holiness' %s and %s by CALL): THE WRITE hireling_oppression_barred, a BLOCK on Israel at the chapters' own day; the sojourner's wage under on his day" % (HO_OPPR[0], HO_ALIEN[0]), ['hireling_oppression_barred'])
    if ask == 'on_his_day_you_shall_give_his_wage':
        ink('24:15', "'ON HIS DAY YOU SHALL GIVE HIS WAGE, and the sun shall not set on it, for he is poor and lifts his soul to it, lest he cry against you to the LORD AND IT BE SIN IN YOU' — 'sin in you' the formula's THIRD seat (%s); 24:15 shares %d tokens with 15:9 (%s the shared run — the reading's kin: 279:4 REREAD from chapter 15)" % (P('והיה', 'בך', 'חטא', books=T), TWIN['24:15 vs 15:9'], SHARED(DV(24, 15), DV(15, 9))))
        move("the Sifrei 279:1-4 (read whole at the reading; 279:4 REREAD from chapter 15); cold_run_holiness (CALL) — HO.wage(first_morning) = %s; cold_run_release_firstborn (CALL) — RF.DATA[the_cry_and_the_sin] read (cry_heard TWO and bears_sin ONE on israel_people — SCANS %s, %s)" % (HO_MORNING[0], SCANS['cry_heard'], SCANS['bears_sin']), "'on his day you shall give his wage' — THE WAGE'S TWO WINDOWS: the night's wage all the day, the day's wage all the night — 'and the sun shall not set on it' the day's laborer's clause, 'until morning' (Leviticus 19:13) the night's (279:1 — the reading's find 7; holiness' 'the_first_morning_only' by CALL); 'for he is poor and lifts his soul to it' — he climbed the ladder and hung from the tree and gave himself over to death for his wage (279:2); 'lest he cry against you to the LORD' — 15:9's cry: cry_heard TWO on israel_people THE TAPE'S REFERENCE, no third write; 'and it be sin in you' — the formula's third seat, bears_sin 15:9's THE REFERENCE (279:4 — release_firstborn's DATA row read: 'word_for_word: 279:4 (24:15 seven in order)')")
        dat("THE WRITE hireling_wage_same_day_commanded — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETER the_wages_windows (the day's wage all the night, the night's all the day — 279:1); cry_heard and bears_sin the references, never a third write; the exam's person the employer who pays the day laborer at midnight — within the window, accepted")
        return out("on his day you shall give his wage (24:15) — the two windows: the day's wage all the night, the night's all the day; he hung from the tree for it; the cry and the sin 15:9's, references (the Sifrei 279:1-4; holiness' %s and release_firstborn's row by CALL): THE WRITE hireling_wage_same_day_commanded, a STATUS on Israel at the chapters' own day; the payment at midnight accepted" % (HO_MORNING[0],), ['hireling_wage_same_day_commanded'])
    return 'no verdict in span', [], list(P_)


def fathers_and_sons_the_stranger_and_the_gleanings(case, data):
    """F12 — Deut 24:16-22 — ONE LINE fathers_sons_stranger_gleanings_declared writing stranger_orphan_justice_commanded and forgotten_sheaf_commanded (STATUSES), fathers_for_sons_death_barred, widows_garment_pledge_barred, olive_second_beating_barred and vineyard_gleaning_barred (BLOCKS); the witnesses' law by CALL (refuge_war_family — 19:15), the courts by CALL (festivals_judges — 16:19), the widow's garment by CALL (ordinances — the Exodus cell's forward reading), the orphan and the widow by CALL (second_tablets — 10:18), the slave refrain by CALL (release_firstborn — 15:15; covenant_at_horeb — the exodus ground), Leviticus 19:9-10's gifts by CALL (holiness — the Leviticus cell READ 24:19-20 FORWARD); Sanhedrin 3:4, Peah 4:6, 6:6, 7:2 the exam rows; 2 Kings 14:6 THE POINTER AHEAD owed"""
    del P_[:]
    ask = case['ask']
    if ask == 'fathers_shall_not_die_for_sons':
        ink('24:16', "'FATHERS SHALL NOT BE PUT TO DEATH FOR SONS, and sons shall not be put to death for fathers; EACH SHALL BE PUT TO DEATH IN HIS OWN SIN' — 2 KINGS 14:6 QUOTES THE VERSE WHOLE: %d of 24:16's %d tokens in order (%s the shared run; 'as written in the book of the law of Moses' — the reading's find 1); the closest kin %s; 2 Chronicles 25:4 the twin recital (%d)" % (TWIN['24:16 vs 2Kgs 14:6'], len(words('Deut', 24, 16)), SHARED(DV(24, 16), ('2Kgs', 14, 6)), KINC[(24, 16)][0], TWIN['24:16 vs 2Chr 25:4']))
        move("the Sifrei 280:1-3 (read whole at the reading); Onkelos 24:16 'by the mouth of sons'; MISHNAH SANHEDRIN 3:4 (the exam row, read whole); cold_run_refuge_war_family (CALL) — RW.the_landmark_and_the_witnesses(one_witness_for_any_iniquity) = %s, (the_violent_witness_and_the_woman) = %s" % (RW_ONE[1], RW_VIOLENT[1]), "'fathers shall not be put to death FOR sons' — BY THE MOUTH OF SONS: by the testimony of sons, and sons not by the testimony of fathers — Onkelos writes the spine in ('by the mouth of sons', the reading's find 4); the relatives disqualified: his father, his brother, his father's brother, his mother's brother, his sister's husband, his father's sister's husband, his mother's sister's husband, his mother's husband, his father-in-law, his wife's sister's husband — they, their sons and their sons-in-law; the stepson alone; R. Yose — this is R. Akiva's version, the first version: his uncle and his cousin and all fit to inherit him; a relative who became unrelated fit, R. Judah: if he has sons from her not fit (Sanhedrin 3:4 — the exam row); 'each shall be put to death in his own sin' — the fathers die in their own sin and the sons in theirs (280:2-3); THE RUN CITATION AHEAD — Amaziah spared the murderers' sons 'as written in the book of the law of Moses' (2 Kings 14:6): A POINTER ROW OWED under the debt line; 19:15's witnesses' law the kin (refuge_war_family by CALL)")
        dat("THE WRITE fathers_for_sons_death_barred — a BLOCK on israel_people at the chapters' own day (DK2); THE PARAMETER the_relatives_disqualified (Sanhedrin 3:4 — the list, R. Akiva's version, the relative who became unrelated); the pointer 24:16 -> 2 Kings 14:6 OWED (no pointer row this sitting — the lean pass's debt line); the exam's person the father who testifies against his son — disqualified, the son not put to death by his mouth")
        return out("fathers shall not die for sons (24:16) — by the mouth of sons, Onkelos writing the spine in; the relatives disqualified, the stepson alone; each in his own sin; 2 Kings 14:6 quotes the verse whole — the run ahead, a pointer owed (the Sifrei 280:1-3; Mishnah Sanhedrin 3:4; refuge_war_family's %s by CALL): THE WRITE fathers_for_sons_death_barred, a BLOCK on Israel at the chapters' own day; the father's testimony against his son disqualified" % (RW_ONE[1][0],), ['fathers_for_sons_death_barred'])
    if ask == 'the_strangers_and_the_orphans_justice':
        ink('24:17', "'YOU SHALL NOT WREST THE JUDGMENT OF A SOJOURNER OR AN ORPHAN, and YOU SHALL NOT TAKE THE WIDOW'S GARMENT IN PLEDGE' — 'wrest judgment' at %s (Exodus 23:6, 16:19, this — the twins; 24:17 shares %d tokens with 16:19 and %d with Exodus 23:6, %s the shared run); 'for the sojourner, the orphan and the widow' at %s (24:19-21 and 26:12)" % (P('לא', 'תטה', 'משפט', books=None), TWIN['24:17 vs 16:19'], TWIN['24:17 vs Exod 23:6'], SHARED(DV(24, 17), DV(16, 19)), P('לגר', 'ליתום', 'ולאלמנה', books=T)))
        move("the Sifrei 281:1-3 (read whole at the reading; 281:1 REREAD from chapter 16); cold_run_festivals_judges (CALL) — FJ.the_judges_in_every_gate(wrest_no_judgment) = %s ('Exodus 23:6's and 24:17's twins'); cold_run_ordinances (CALL) — OR.loan(widow_not_pledged) = %s ('Deut 24:17 [IMPORT]'); cold_run_second_tablets (CALL) — ST.the_god_of_gods_and_the_stranger(the_orphan_and_the_widow) = %s" % (FJ_WREST[1], OR_WIDOW[0], ST_ORPHAN[1]), "'you shall not wrest the judgment of a sojourner or an orphan' — 16:19's cell: the wresting barred at its second Deuteronomy seat — two for the sojourner, three for the sojourner-orphan (281:1-2 — the reading's find 8; judgment_wresting_barred ONE on israel_people THE TAPE'S REFERENCE, SCANS %s — no second write; festivals_judges by CALL); 'and you shall not take the widow's garment in pledge' — a widow, rich or poor, is not pledged (Bava Metzia 9:13 — the Exodus cell READ 24:17 FORWARD, 'Deut 24:17 [IMPORT]' in its why; 281:3 cites nothing — the reading's twenty-one); 10:18's orphan and widow Exodus 22:21's pair (second_tablets by CALL)" % (SCANS['judgment_wresting_barred'],))
        dat("THE WRITES stranger_orphan_justice_commanded (a STATUS) and widows_garment_pledge_barred (a BLOCK) on israel_people at the chapters' own day (DK2); the_prohibitions_count a DATA row (two for the sojourner, three for the sojourner-orphan — 281:1-2); judgment_wresting_barred the reference; the exam's person the creditor who pledges a rich widow's garment — barred, rich or poor")
        return out("the stranger's and the orphan's justice (24:17) — 16:19's wresting at its second seat, two and three prohibitions; the widow's garment never pledged, rich or poor — the Exodus cell read 24:17 forward (the Sifrei 281:1-3; festivals_judges' %s, ordinances' %s and second_tablets' pair by CALL): THE WRITES stranger_orphan_justice_commanded and widows_garment_pledge_barred on Israel at the chapters' own day; the rich widow's garment barred" % (FJ_WREST[1][0], OR_WIDOW[0]), ['stranger_orphan_justice_commanded', 'widows_garment_pledge_barred'])
    if ask == 'remember_that_you_were_a_slave':
        ink('24:18, 24:22', "'AND YOU SHALL REMEMBER THAT YOU WERE A SLAVE IN EGYPT, and the LORD your God redeemed you from there; therefore I command you to do this thing' — 24:18 shares %d of its %d tokens in order with 15:15 (the slave refrain — the reading's find 3), 24:22 %d with 15:15, 24:18 %d with 24:22 (%s the shared run); 'I' (anokhi) the store's '?' gloss patched at sitting 17" % (TWIN['24:18 vs 15:15'], len(words('Deut', 24, 18)), TWIN['24:22 vs 15:15'], TWIN['24:18 vs 24:22'], SHARED(DV(24, 18), DV(24, 22))))
        move("the Sifrei 282:1 (read whole at the reading); cold_run_release_firstborn (CALL) — 15:15's refrain (the tape's hebrew_slave_law_declared the readback's REFERENCE); cold_run_covenant_at_horeb (CALL) — CH.the_first_tablet(the_two_grounds) = %s" % (CH_GROUNDS[1],), "'and you shall remember that you were a slave in Egypt' — the refrain: 'I redeemed you on this condition, that you keep My commandments' (282:1 — 15:15's line the reference: the Hebrew slave's law with fourteen of seventeen words shared); the exodus ground of the Sabbath's second tablet (5:15 — covenant_at_horeb's two grounds by CALL: the creation and the exodus); 'therefore I command you to do this thing' — the refrain's tail at 24:18 and 24:22 verbatim (eight tokens shared)")
        dat("the_slave_refrain a DATA row (24:18 and 24:22 REFERENCE rows against 15:12-18's line hebrew_slave_law_declared — a retelling, no write; the exodus ground by CALL); the exam's person who reads 24:18 as a new act of redemption — the tape's own act, remembered")
        return out("remember that you were a slave (24:18, 24:22) — the refrain of 15:15, fourteen of seventeen words; the exodus ground of the Sabbath; therefore I command you — the tail verbatim twice (the Sifrei 282:1; release_firstborn's line and covenant_at_horeb's %s by CALL): reference rows, no write" % (CH_GROUNDS[1][0],), ['accepted'])
    if ask == 'the_forgotten_sheaf':
        ink('24:19', "'When you reap your harvest in your field AND FORGET A SHEAF IN THE FIELD, YOU SHALL NOT TURN BACK TO TAKE IT: for the sojourner, the orphan and the widow it shall be, that the LORD your God may bless you in all the work of your hands' — 'in all the work of your hands' the blessing's form (work_of_the_hand_blessed TWO on israel_people — SCANS %s; 15:10, 15:18); 24:19 shares %d tokens with 14:29 (the third-year tithe's blessing) and %d with Leviticus 19:9; 282:1's English carries 282:2's text (the export's misplacement — the reading's find 2)" % (SCANS['work_of_the_hand_blessed'], TWIN['24:19 vs 14:29'], TWIN['24:19 vs Lev 19:9']))
        move("the Sifrei 282:1-4, 283:1-6 (read whole at the reading — 283 headless, the forgotten sheaf); MISHNAH PEAH 4:6 and 6:6 (the exam rows, read whole — 6:6 CITED IN THE HEBREW at 283:4); cold_run_holiness (CALL) — HO.gifts(kinds) = %s ('the forgotten sheaf and olive are Deut 24:19-20's [IMPORT]')" % (HO_KINDS[0],), "'and forget a sheaf' — the forgetting only at the binding: a gentile who reaped his field and then converted is exempt from the gleanings, the forgotten sheaf and the corner; R. Judah binds him for the forgotten sheaf, since the forgotten applies at the binding (Peah 4:6 — the exam row; the_forgettings_hour); 'a sheaf' — and not the stack; two — not three: two sheaves forgotten, three not; two heaps of olives and carobs forgotten, three not (283:1-3); a sheaf of two seahs is not forgotten; two sheaves of two seahs — Rabban Gamliel: the owner's, the sages: the poor's; Rabban Gamliel argued from one to two, the sages answered 'if one sheaf that is like a stack, will you say so of two sheaves that are like heaps?' (Peah 6:6 = 283:4 — TWO ARMS; the burden of proof at 283:5 — the reading's find 5); THE LEVITICUS CELL READ THIS VERSE FORWARD — Leviticus 19:9-10's four gift-nouns, 'the forgotten sheaf and olive are Deut 24:19-20's [IMPORT]' (holiness' kinds by CALL; left_for_the_poor ZERO on the running world — SCANS %s, the reference)" % (SCANS['left_for_the_poor'],))
        dat("THE WRITE forgotten_sheaf_commanded — a STATUS on israel_people at the chapters' own day (DK2); THE PARAMETERS the_forgettings_hour (Peah 4:6 — at the binding, R. Judah's arm) and the_two_seahs (Peah 6:6 — Rabban Gamliel's and the sages' two arms); left_for_the_poor the reference; the exam's person who forgot a sheaf of two seahs — not forgotten, the owner's")
        return out("the forgotten sheaf (24:19) — the forgetting at the binding, the convert's exemption R. Judah's dispute; two not three; the sheaf of two seahs not forgotten, two such sheaves Rabban Gamliel's and the sages' two arms; the Leviticus cell read this verse forward (the Sifrei 282:1-283:6; Mishnah Peah 4:6, 6:6 in the spine's own Hebrew; holiness' %s by CALL): THE WRITE forgotten_sheaf_commanded, a STATUS on Israel at the chapters' own day; the two-seah sheaf the owner's" % (HO_KINDS[0][2],), ['forgotten_sheaf_commanded'])
    if ask == 'the_olive_and_the_vineyard':
        ink('24:20-21', "'When you beat your olive tree, YOU SHALL NOT GO OVER THE BOUGHS AFTER YOU … When you gather your vineyard, YOU SHALL NOT GLEAN AFTER YOU: for the sojourner, the orphan and the widow it shall be' — 24:21 shares %d tokens with Leviticus 19:10 (the gleaning's Sinai seat); Onkelos pali (search out) for the boughs — one Aramaic root for the purge's 24:7 and the boughs (the reading's find 12)" % (TWIN['24:21 vs Lev 19:10'],))
        move("the Sifrei 284:1-6, 285:1-4 (read whole at the reading); MISHNAH PEAH 7:2 (the exam row, read whole); cold_run_holiness (CALL) — HO.gifts(olelet) = %s, HO.gifts(peret) = %s, HO.gifts(olelet_edges) read; MIDDOT.md I2 (the verbal analogy)" % (HO_OLELET[0], HO_PERET[0]), "'you shall not go over the boughs after you' — the second beating barred, the first the owner's (284:1-2); an olive tree that has a name in the field, even the one at the end of the rows, is not forgotten; the olive of two seahs not forgotten — the two seahs carried from the sheaf by the shared words (284:6 and 285:4 — I2); R. Meir — the beating-rod's forgetting (Peah 7:2 — the exam row; the_olives_forgetting); the shoulder and the pendant (285:2 — the reading's find 8); Proverbs 22:28 cited (284:3); 'you shall not glean after you' — Leviticus 19:10's small clusters and fallen grapes (holiness' olelet and peret by CALL: no shoulder and no pendant a small cluster, what falls by the cutting the fallen grapes); 'for the sojourner, the orphan and the widow' — the three (285:3)")
        dat("THE WRITES olive_second_beating_barred and vineyard_gleaning_barred — BLOCKS on israel_people at the chapters' own day (DK2); THE PARAMETER the_olives_forgetting (Peah 7:2 — the named tree, the two seahs, R. Meir's rod); the_vineyards_gleaning a DATA row (Leviticus 19:10's two nouns by CALL); the exam's person who beats his olive tree a second time — barred, the boughs the poor's")
        return out("the olive and the vineyard (24:20-21) — the second beating barred, the named tree not forgotten, the two seahs by analogy, R. Meir's rod; the gleaning Leviticus 19:10's small clusters and fallen grapes; for the three (the Sifrei 284:1-285:4; Mishnah Peah 7:2; holiness' %s and %s by CALL): THE WRITES olive_second_beating_barred and vineyard_gleaning_barred, BLOCKS on Israel at the chapters' own day; the second beating barred" % (HO_OLELET[0], HO_PERET[0]), ['olive_second_beating_barred', 'vineyard_gleaning_barred'])
    return 'no verdict in span', [], list(P_)
