#!/usr/bin/env python3
# THE DEUTERONOMY WALK sitting 18 — CHAPTERS 26-28 (LEAN, 2026-09-26): chapter 28's ONKELOS rows TYPED, SECOND SLICE 28:24-46 (the rain dust, the defeat one way
# and seven, the carcass cast out, the boil of Egypt and the hemorrhoids (the ketiv/qere seat), madness, the wife another lies with (the second ketiv/qere seat),
# the ox, the ass, the flock, the sons, the king exiled, the proverb, the locust, the worm, the olives dropped, the captivity, the uncircumcised sojourner rising,
# the lender the head; the curses pursue, a sign and a wonder). The Aramaic and the Hebrew CUT by consonants in GLOSSED PIECES of at most seven tokens
# (ch26_ink.HP / AP); the DB's ketiv the Hebrew's tokens. EVERY ROW READ WHOLE (ch28_onkelos.txt). Sitting 17's form.
from ch26_ink import *
R = {}
def row(c, v, verdict, prose): R[(c, v)] = (verdict, prose)

row(28, 24, 'MATERIAL', f'THE LORD SHALL MAKE THE RAIN OF YOUR LAND POWDER AND DUST; FROM THE HEAVENS IT COMES DOWN ON YOU UNTIL YOU ARE DESTROYED. {HP(28, 24, (("יתן", "יהוה", "את", "מטר", "ארצך", "אבק", "ועפר"), "the LORD shall make your land\'s rain powder and dust — 28:12\'s rain inverted"))} {AP(28, 24, (("אבקא", "ועפרא", "מן", "שמיא", "יחות"), "powder and dust from the heavens shall come down"))} THE RAIN\'S CURSE ARM (DV28B-02). Fresh.')
row(28, 25, 'MATERIAL', f'THE LORD SHALL MAKE YOU SMITTEN BEFORE YOUR ENEMIES: ONE WAY YOU GO OUT, SEVEN WAYS YOU FLEE; A HORROR TO ALL THE KINGDOMS OF THE EARTH. {HP(28, 25, (("יתנך", "יהוה", "נגף", "לפני", "איביך"), "the LORD shall make you smitten before your enemies — 28:7 inverted"), (("בדרך", "אחד", "תצא", "אליו", "ובשבעה", "דרכים", "תנוס"), "one way you go out, seven ways you flee — the parser\'s [1, 7] again"), (("והיית", "לזעוה", "לכל", "ממלכות", "הארץ"), "a horror to all the kingdoms of the earth"))} {AP(28, 25, (("תביר", "קדם", "סנאך"), "BROKEN before your HATERS (sana\'akh) — the enemy\'s second Aramaic word"), (("ותהי", "לזיע"), "and you shall be a trembling (zia)"))} Fresh.')
row(28, 26, 'MATERIAL', f'YOUR CARCASS SHALL BE FOOD FOR EVERY BIRD OF THE HEAVENS AND BEAST OF THE EARTH, AND NONE FRIGHTENS THEM AWAY. {HP(28, 26, (("והיתה", "נבלתך", "למאכל", "לכל", "עוף", "השמים"), "your carcass food for every bird of the heavens — Jeremiah 7:33\'s seven in order the closest kin (the Prophets\' seat, not read)"), (("ואין", "מחריד"), "and none frightens them away"))} {AP(28, 26, (("נבלתך", "משגרא", "למיכל"), "your carcass CAST OUT (meshagra) for food — Onkelos adds the casting"), (("ולית", "דמניד"), "and none makes them move"))} 21:23\'S BURIAL THE CONTRAST — the body left. Fresh.')
row(28, 27, 'MATERIAL', f'THE LORD SHALL SMITE YOU WITH THE BOIL OF EGYPT, THE HEMORRHOIDS, THE SCAB AND THE ITCH, OF WHICH YOU CANNOT BE HEALED. {HP(28, 27, (("יככה", "יהוה", "בשחין", "מצרים"), "the LORD shall smite you with the boil of Egypt — Exodus 9:9\'s plague returned (28:60)"), (("ובעפלים", "ובגרב", "ובחרס"), "the hemorrhoids (the KETIV afalim — the store\'s qere techorim beside it, the one-token mismatch 12 vs 11), the scab and the itch"))} {AP(28, 27, (("ובטחורין",), "and with HEMORRHOIDS (techorin) — the Aramaic reads the QERE"), (("ובחריס", "יביש"), "and the DRY itch — Onkelos adds \'dry\'"), (("לא", "תכול", "לאתסאה"), "you cannot be healed"))} THE FIRST KETIV/QERE SEAT — Onkelos follows the read form. Fresh.')
row(28, 28, 'MATERIAL', f'THE LORD SHALL SMITE YOU WITH MADNESS, BLINDNESS AND ASTONISHMENT OF HEART. {HP(28, 28, (("יככה", "יהוה", "בשגעון", "ובעורון", "ובתמהון", "לבב"), "the LORD shall smite you with madness, blindness and astonishment of heart — no kin by tokens (the ink\'s four)"))} {AP(28, 28, (("בטפשותא", "ובסמיותא", "ובשעממות", "לבא"), "with FOOLISHNESS (tafshuta), blindness and DESOLATION of heart (sha\'amemut — the word alone in the book)"))} Fresh.')
row(28, 29, 'MATERIAL', f'YOU SHALL GROPE AT NOON AS THE BLIND GROPES IN THE DARK AND NOT PROSPER; ONLY OPPRESSED AND ROBBED ALL THE DAYS, AND NONE SAVES. {HP(28, 29, (("והיית", "ממשש", "בצהרים", "כאשר", "ימשש", "העור", "באפלה"), "you shall grope at noon as the blind gropes in the dark — 27:18\'s blind the image"), (("עשוק", "וגזול", "כל", "הימים", "ואין", "מושיע"), "oppressed and robbed all the days, and none saves — 28:31\'s \'none saves\' again"))} {AP(28, 29, (("ממשש", "בטהרא"), "groping at noon (tihara)"), (("עשיק", "ואניס"), "oppressed and FORCED (anis) — \'robbed\' as violence"), (("ולית", "דפריק"), "and none REDEEMS (parik)"))} Fresh.')
row(28, 30, 'MATERIAL', f'YOU BETROTH A WIFE AND ANOTHER MAN LIES WITH HER; BUILD A HOUSE AND DWELL NOT IN IT; PLANT A VINEYARD AND USE NOT ITS FRUIT. {HP(28, 30, (("אשה", "תארש", "ואיש", "אחר", "ישגלנה"), "you betroth a wife and another man lies with her — the KETIV yishgalenna, the store\'s qere yishkavenna beside (the second mismatch, 15 vs 14); 20:7\'s exemption inverted"), (("בית", "תבנה", "ולא", "תשב", "בו"), "build a house and dwell not in it — 20:5"), (("כרם", "תטע", "ולא", "תחללנו"), "plant a vineyard and use not its fruit — 20:6\'s \'made common\'"))} {AP(28, 30, (("ישכבנה",), "LIES WITH HER (yishkevinnah) — Onkelos reads the QERE"), (("כרמא", "תצוב", "ולא", "תחלניה"), "plant a vineyard and not redeem it"))} THE WAR CHAPTER\'S THREE EXEMPTIONS ARE THE CURSE\'S (the ink\'s find 2); the second ketiv/qere seat. Fresh.')
row(28, 31, 'MATERIAL', f'YOUR OX SLAUGHTERED BEFORE YOUR EYES AND YOU EAT NOT OF IT; YOUR ASS ROBBED BEFORE YOU AND NOT RETURNED; YOUR FLOCK GIVEN TO YOUR ENEMIES, AND NONE SAVES. {HP(28, 31, (("שורך", "טבוח", "לעיניך", "ולא", "תאכל", "ממנו"), "your ox slaughtered before your eyes and you eat not of it"), (("חמרך", "גזול", "מלפניך"), "your ass robbed before you"), (("צאנך", "נתנות", "לאיביך"), "your flock given to your enemies — 22:1-4\'s ox and ass returned the contrast"))} {AP(28, 31, (("תורך", "יהי", "נכס"), "your ox shall be slain"), (("מסירין", "לבעלי", "דבבך"), "HANDED OVER to your enemies"), (("ולית", "לך", "פריק"), "and you have no redeemer"))} Fresh.')
row(28, 32, 'MATERIAL', f'YOUR SONS AND DAUGHTERS GIVEN TO ANOTHER PEOPLE; YOUR EYES SEE AND FAIL FOR THEM ALL DAY, AND NO POWER IN YOUR HAND. {HP(28, 32, (("בניך", "ובנתיך", "נתנים", "לעם", "אחר"), "your sons and daughters given to another people — 28:41\'s captivity"), (("ועיניך", "ראות", "וכלות", "אליהם"), "your eyes see and fail for them"), (("ואין", "לאל", "ידך"), "and no power in your hand — Genesis 31:29\'s idiom"))} {AP(28, 32, (("ויסופן", "בגללהן"), "and END because of them — \'fail\' rendered \'come to an end\'"), (("ולית", "חילא", "בידך"), "and no strength in your hand"))} Fresh.')
row(28, 33, 'MATERIAL', f'THE FRUIT OF YOUR GROUND AND ALL YOUR TOIL A PEOPLE YOU KNOW NOT EATS; ONLY OPPRESSED AND CRUSHED ALL THE DAYS. {HP(28, 33, (("פרי", "אדמתך", "וכל", "יגיעך", "יאכל", "עם"), "the fruit of your ground and all your toil a people eats — 28:51\'s far nation"), (("אשר", "לא", "ידעת"), "which you have not known — 28:36\'s, 28:64\'s formula"), (("עשוק", "ורצוץ", "כל", "הימים"), "oppressed and crushed all the days"))} {AP(28, 33, (("וכל", "לאותך"), "and all your toil (le\'utakh)"), (("עשיק", "ורעיע"), "oppressed and SHATTERED (re\'ia)"))} Fresh.')
row(28, 34, 'MATERIAL', f'YOU SHALL BE MAD FROM THE SIGHT OF YOUR EYES. {HP(28, 34, (("והיית", "משגע", "ממראה", "עיניך", "אשר", "תראה"), "mad from the sight of your eyes — 28:67\'s \'sight of your eyes\' again; 28:28\'s madness"))} {AP(28, 34, (("משתטיה", "מחזו", "עיניך"), "DERANGED (mishtatei) from the vision of your eyes"))} Fresh.')
row(28, 35, 'MATERIAL', f'THE LORD SHALL SMITE YOU WITH A SORE BOIL ON THE KNEES AND LEGS, OF WHICH YOU CANNOT BE HEALED, FROM THE SOLE OF YOUR FOOT TO YOUR CROWN. {HP(28, 35, (("יככה", "יהוה", "בשחין", "רע", "על", "הברכים", "ועל"), "the LORD shall smite you with a sore boil on the knees and legs — Job 2:7\'s sole to crown the kin (not read)"), (("מכף", "רגלך", "ועד", "קדקדך"), "from the sole of your foot to your crown — 28:65\'s \'sole of your foot\'"))} {AP(28, 35, (("בשחנא", "בישא"), "with an evil boil"), (("מפרסת", "רגלך", "ועד", "מוחך"), "from the sole of your foot to your BRAIN (mochakh) — the crown rendered the brain"))} Fresh.')
row(28, 36, 'MATERIAL', f'THE LORD SHALL LEAD YOU AND YOUR KING WHOM YOU SET UP TO A NATION YOU NOR YOUR FATHERS HAVE KNOWN, AND THERE YOU SERVE OTHER GODS, WOOD AND STONE. {HP(28, 36, (("יולך", "יהוה", "אתך", "ואת", "מלכך", "אשר", "תקים"), "the LORD shall lead you and your king whom you set up — 17:14-15\'s king, named again"), (("אשר", "לא", "ידעת", "אתה", "ואבתיך"), "which you nor your fathers have known — 28:64\'s eight in order"), (("ועבדת", "שם", "אלהים", "אחרים", "עץ", "ואבן"), "serve there other gods, wood and stone — 4:28, 28:64, 29:16"))} {AP(28, 36, (("יגלי", "יי", "יתך"), "the LORD shall EXILE you (yaglei) — \'lead\' read as exile"), (("לעממיא", "פלחי", "טעותא", "אעא", "ואבנא"), "TO PEOPLES WORSHIPPING ERRORS of wood and stone — the service rendered as serving the idolaters, not the idols"))} THE KING IN THE CURSE (DV28B-04). Fresh.')
row(28, 37, 'MATERIAL', f'YOU SHALL BE AN ASTONISHMENT, A PROVERB AND A BYWORD AMONG ALL THE PEOPLES WHERE THE LORD DRIVES YOU. {HP(28, 37, (("והיית", "לשמה", "למשל", "ולשנינה"), "an astonishment, a proverb and a byword — 1 Kings 9:7\'s and Jeremiah 24:9\'s (not read)"), (("בכל", "העמים", "אשר", "ינהגך", "יהוה", "שמה"), "among all the peoples where the LORD drives you"))} {AP(28, 37, (("לצדו", "למתל", "ולשועי"), "a DESOLATION (tzadu), a parable and a TALE (shu\'ei)"))} Fresh.')
row(28, 38, 'MATERIAL', f'MUCH SEED YOU CARRY TO THE FIELD AND LITTLE YOU GATHER, FOR THE LOCUST CONSUMES IT. {HP(28, 38, (("זרע", "רב", "תוציא", "השדה", "ומעט", "תאסף"), "much seed to the field and little gathered — 28:39-42 the harvests failed"), (("כי", "יחסלנו", "הארבה"), "for the locust consumes it — chasal once in the Torah"))} {AP(28, 38, (("בר", "זרע", "סגי"), "much seed grain (bar zera)"), (("יחסלניה", "גובא"), "the LOCUST (goba) consumes it"))} THE HARVESTS FAILED (DV28B-05). Fresh.')
row(28, 39, 'MATERIAL', f'VINEYARDS YOU PLANT AND WORK, AND DRINK NO WINE NOR GATHER, FOR THE WORM EATS IT. {HP(28, 39, (("כרמים", "תטע", "ועבדת", "ויין", "לא", "תשתה"), "plant vineyards and work them and drink no wine — 20:6, 28:30 the vineyard\'s third seat"), (("ולא", "תאגר", "כי", "תאכלנו", "התלעת"), "nor gather, for the worm eats it — no kin by tokens"))} {AP(28, 39, (("וחמרא", "לא", "תשתי"), "and drink no wine"), (("תיכלניה", "תלעתא"), "the worm eats it"))} Fresh.')
row(28, 40, 'MATERIAL', f'OLIVES YOU HAVE IN ALL YOUR BORDER, AND NO OIL TO ANOINT, FOR YOUR OLIVE CASTS ITS FRUIT. {HP(28, 40, (("זיתים", "יהיו", "לך", "בכל", "גבולך", "ושמן", "לא"), "olives in all your border and no oil to anoint — the third of the land\'s three (grain, wine, oil; 28:51)"), (("כי", "ישל", "זיתך"), "for your olive casts its fruit — yishal once"))} {AP(28, 40, (("ומשחא", "לא", "תסוך"), "and oil you shall not anoint"), (("יתרון", "זיתיך"), "your olives shall DROP (yitrun)"))} Fresh.')
row(28, 41, 'MATERIAL', f'SONS AND DAUGHTERS YOU BEGET, AND THEY ARE NOT YOURS, FOR THEY GO INTO CAPTIVITY. {HP(28, 41, (("בנים", "ובנות", "תוליד", "ולא", "יהיו", "לך"), "sons and daughters you beget, and they are not yours"), (("כי", "ילכו", "בשבי"), "for they go into captivity — 28:32\'s giving named"))} {AP(28, 41, (("ארי", "יהכון", "בשביא"), "for they go into captivity (shivya)"))} Fresh.')
row(28, 42, 'MATERIAL', f'ALL YOUR TREES AND THE FRUIT OF YOUR GROUND THE LOCUST POSSESSES. {HP(28, 42, (("כל", "עצך", "ופרי", "אדמתך", "יירש", "הצלצל"), "all your trees and the fruit of your ground the locust possesses — tzelatzal once in the Torah; \'possess\' the inheritance\'s verb turned"))} {AP(28, 42, (("כל", "אילנך", "ואבא", "דארעך"), "all your trees and your land\'s fruit"), (("יחסנניה", "סקאה"), "the LOCUST (saka\'a) shall INHERIT it (yachsenineih) — the possession\'s own root"))} Fresh.')
row(28, 43, 'MATERIAL', f'THE STRANGER IN YOUR MIDST RISES ABOVE YOU HIGHER AND HIGHER, AND YOU GO DOWN LOWER AND LOWER. {HP(28, 43, (("הגר", "אשר", "בקרבך", "יעלה", "עליך", "מעלה", "מעלה"), "the stranger in your midst rises above you higher and higher — 28:13\'s \'above\' inverted"), (("ואתה", "תרד", "מטה", "מטה"), "and you go down lower and lower"))} {AP(28, 43, (("תותב", "ערל", "די", "בינך"), "THE UNCIRCUMCISED SOJOURNER (totav arel) among you — Onkelos names the stranger\'s kind: the alien, not the convert (chapter 14\'s one noun, two sojourners)"), (("לעלא", "לעלא"), "higher and higher"))} Fresh.')
row(28, 44, 'MATERIAL', f'HE LENDS TO YOU AND YOU LEND NOT TO HIM; HE IS THE HEAD AND YOU THE TAIL. {HP(28, 44, (("הוא", "ילוך", "ואתה", "לא", "תלונו"), "he lends to you and you lend not to him — 28:12\'s and 15:6\'s lending inverted"), (("הוא", "יהיה", "לראש", "ואתה", "תהיה", "לזנב"), "he the head and you the tail — 28:13 inverted"))} {AP(28, 44, (("הוא", "יוזפנך"), "he shall lend to you"), (("לתקיף", "ואת", "תהי", "לחלש"), "strong, and you weak — head and tail as power again"))} THE CURSES\' FIRST HALF CLOSES (DV28B-05). Fresh.')
row(28, 45, 'MATERIAL', f'ALL THESE CURSES SHALL COME ON YOU, PURSUE YOU AND OVERTAKE YOU UNTIL YOU ARE DESTROYED, BECAUSE YOU DID NOT HEARKEN. {HP(28, 45, (("ובאו", "עליך", "כל", "הקללות", "האלה", "ורדפוך", "והשיגוך"), "all these curses come on you, pursue and overtake you — 28:15 with \'pursue\' added"), (("כי", "לא", "שמעת", "בקול", "יהוה", "אלהיך"), "because you did not hearken — the condition restated in the past"))} {AP(28, 45, (("וירדפנך", "וידבקנך"), "pursue you and cleave to you"), (("ארי", "לא", "קבלתא", "למימרא", "דיי"), "because you did not receive the Memra"))} THE SECOND HALF OPENS (DV28C-01). Fresh.')
row(28, 46, 'MATERIAL', f'THEY SHALL BE ON YOU A SIGN AND A WONDER, AND ON YOUR SEED FOREVER. {HP(28, 46, (("והיו", "בך", "לאות", "ולמופת"), "a sign and a wonder on you — 4:34\'s, 6:22\'s, 7:19\'s signs turned on Israel"), (("ובזרעך", "עד", "עולם"), "and on your seed forever"))} {AP(28, 46, (("לאת", "ולמופת"), "a sign and a wonder"), (("ובבניך", "עד", "עלם"), "and on your SONS (benakh) forever — the seed rendered sons"))} Fresh.')
