# F10 THE CURSES OF THE SIEGE AND THE EXILE
E['curses_pursue_until_destroyed'] = ("the curses pursue until destroyed — the HEAVEN entry the line curses_pursue_iron_yoke_declared writes on Israel: 'AND ALL THESE CURSES SHALL COME UPON YOU AND PURSUE YOU AND OVERTAKE YOU UNTIL YOU ARE DESTROYED, because you did not hearken to the voice of the LORD your God to keep His commandments and His statutes which He commanded you; and they shall be upon you for a sign and a wonder, and upon your seed for ever' (28:45-46) — the state's arm restated ('not hearken to the voice' 28:15, 45, 62 — good_land.the_testimony by CALL); 'because you did not serve the LORD your God with joy' (28:47) THE GROUND — a DATA note and no effect: the rejoicing commanded (26:11, 27:7) its mirror; Onkelos plain", "and all these curses shall come upon you and pursue you and overtake you until you are destroyed", "Deut 28:45-47, 28:15 (this runner's own line — the condition), 8:19-20 (good_land — the testimony); Onkelos 28:45-47", 'all_these_curses_pursue_you_until_you_are_destroyed')
E['iron_yoke_on_neck'] = ("an iron yoke on the neck — the HEAVEN entry the line curses_pursue_iron_yoke_declared writes on Israel: 'and He shall put AN IRON YOKE UPON YOUR NECK until He has destroyed you' (28:48) — Leviticus 26:13's 'I broke the bars of your yoke' INVERTED to an iron yoke (tochacha.covenant by CALL — the blessing branch's terms; the twin diffed); Jeremiah 28:14's iron yoke the Prophets' seat (not read); Onkelos plain", "and He shall put an iron yoke upon your neck", "Deut 28:48; Leviticus 26:13 (tochacha — the yoke broken, inverted); Onkelos 28:48", 'serve_your_enemies_in_hunger_thirst_nakedness_and_want_an_iron_yoke')
E['enemies_served_in_want'] = ("the enemies served in want — the HEAVEN entry the line curses_pursue_iron_yoke_declared writes on Israel: 'YOU SHALL SERVE YOUR ENEMIES whom the LORD shall send against you, IN HUNGER AND IN THIRST AND IN NAKEDNESS AND IN WANT OF ALL THINGS' (28:48) — the Sifrei 42:8 THE LABOR'S THIRD STATE: one's own work (R. Ishmael's way of the world), others' work for one (R. Simeon — Isaiah 61:5), ONE'S WORK FOR OTHERS 'you shall serve your enemies' — the_labors_third_state a PARAMETER; 28:47's service without joy the ground; Onkelos plain", "in hunger and in thirst and in nakedness and in want of all things", "Deut 28:47-48, 11:14 (42:8's seat — blessing_and_curse); Onkelos 28:48; the Sifrei on Deuteronomy 42:8", 'serve_your_enemies_in_hunger_thirst_nakedness_and_want_an_iron_yoke')
E['eagle_nation_devours'] = ("the eagle nation devours — the HEAVEN entry the line eagle_nation_siege_declared writes on Israel: 'THE LORD WILL BRING A NATION AGAINST YOU FROM AFAR, FROM THE END OF THE EARTH, AS THE EAGLE FLIES, a nation whose tongue you shall not understand, a nation of fierce countenance which shall not regard the old nor favor the young; and IT SHALL EAT THE FRUIT OF YOUR BEAST AND THE FRUIT OF YOUR GROUND until you are destroyed, and shall leave you no grain, wine or oil, the increase of your cattle or the young of your flock' (28:49-51) — 'as the eagle flies' the eagle's three seats in the book (14:12, 28:49, 32:11); 7:13's list undone (seven_nations by CALL — blessings_for_hearing's row '28:51 forward'); Onkelos plain", "the LORD will bring a nation against you from afar, from the end of the earth, as the eagle flies", "Deut 28:49-51, 7:13 (seven_nations — the list undone), 14:12 (food_tithe — the eagle's first seat); Onkelos 28:49-51", 'a_nation_from_the_end_of_the_earth_as_the_eagle_flies')
E['siege_in_all_gates_walls_fall'] = ("the siege in all the gates until the walls fall — the HEAVEN entry the line eagle_nation_siege_declared writes on Israel: 'AND IT SHALL BESIEGE YOU IN ALL YOUR GATES UNTIL YOUR HIGH AND FORTIFIED WALLS FALL in which you trusted, in all your land; and it shall besiege you in all your gates in all your land which the LORD your God has given you' (28:52) — Leviticus 26:25's 'gathered into your cities … the pestilence' (tochacha.cascade(3) by CALL — the fourth gate); the siege law of 20:19-20 the tape's (siege_law_declared — the readback row TURNED: Israel the besieged); Onkelos plain", "and it shall besiege you in all your gates until your high and fortified walls fall", "Deut 28:52, 20:19-20 (refuge_war_family — the siege law, turned); Leviticus 26:25 (tochacha — the gathered cities); Onkelos 28:52", 'besieges_you_in_all_your_gates_until_the_high_walls_fall')
E['sons_flesh_eaten_in_siege'] = ("the sons' flesh eaten in the siege — the HEAVEN entry the line sons_flesh_siege_declared writes on Israel: 'AND YOU SHALL EAT THE FRUIT OF YOUR OWN WOMB, THE FLESH OF YOUR SONS AND YOUR DAUGHTERS whom the LORD your God has given you, in the siege and in the distress with which your enemy shall distress you' (28:53), the tender man and the delicate woman grudging their children (28:54-57) — Leviticus 26:29's 'you shall eat the flesh of your sons and daughters' the twin (tochacha by CALL); the siege formula six in order at 28:53, 55, 57 (Jeremiah 19:9 the fourth seat — a pointer ahead OWED, not read); 'the wife of his bosom' Onkelos 'the wife of his covenant' (13:7 the same), 'the afterbirth' Onkelos 'the little children'; 28:55's 'one of them' a distributive, no count (the reading's parser); 'in secret' the book's fourth (28:57)", "and you shall eat the fruit of your own womb, the flesh of your sons and your daughters", "Deut 28:53-57, 13:7 (seducers — 'the wife of your bosom', in secret); Leviticus 26:29 (tochacha — the twin); Onkelos 28:53-57; Jeremiah 19:9 (a pointer ahead OWED, not read)", 'you_eat_the_fruit_of_your_own_womb_in_the_siege_and_the_distress')
E['plagues_made_wonderful'] = ("the plagues made wonderful — the HEAVEN entry the line plagues_scattered_declared writes on Israel: 'IF YOU WILL NOT KEEP TO DO ALL THE WORDS OF THIS LAW WRITTEN IN THIS BOOK, to fear this glorious and awesome Name, the LORD your God, THE LORD WILL MAKE YOUR PLAGUES WONDERFUL and the plagues of your seed, great plagues and lasting, sore sicknesses and lasting' (28:58-59) — 'written in this book' the prefixed seat (the reading's lesson 3), 17:19's copy (courts_prophet by CALL — law_copy_commanded the tape's); 28:59 no kin at all by shared tokens (the reading's find 1); 'every sickness and every plague not written in the book of this law' (28:61); Onkelos plain", "the LORD will make your plagues wonderful and the plagues of your seed", "Deut 28:58-59, 28:61, 17:19 (courts_prophet — the copy of the law), 27:26 (this runner's own line — the words of this law); Onkelos 28:58-59", 'if_you_keep_not_all_the_words_of_this_law_written_in_this_book')
E['diseases_of_egypt_returned'] = ("the diseases of Egypt returned — the HEAVEN entry the line plagues_scattered_declared writes on Israel: 'AND HE WILL BRING BACK UPON YOU ALL THE DISEASES OF EGYPT which you feared, and they shall cleave to you' (28:60) — Exodus 15:26's healer's promise TURNED (exodus_story by CALL — healer_promised the tape's: 'I will put none of the diseases on you which I put on the Egyptians'); 7:15's 'laid on those who hate you' turned back (seven_nations('the_diseases') by CALL — '28:60 forward'); 28:27's boil of Egypt the first return", "and He will bring back upon you all the diseases of Egypt", "Deut 28:60, 7:15 (seven_nations — the diseases), 28:27 (this runner's own line); Exodus 15:26 (exodus_story — the healer's promise, turned); Onkelos 28:60", 'plagues_made_wonderful_the_diseases_of_egypt_returned')
E['few_in_number_left'] = ("left few in number — the HEAVEN entry the line plagues_scattered_declared writes on Israel: 'AND YOU SHALL BE LEFT FEW IN NUMBER, whereas you were as the stars of heaven for multitude, because you did not hearken to the voice of the LORD your God' (28:62), 'and as the LORD rejoiced over you to do you good and to multiply you, so the LORD will rejoice over you to destroy you and to bring you to nought' (28:63) — 'few in number' 26:5's own echo: the recital's descent and the exile's remnant one phrase (the seventy — second_tablets('seventy_persons') and joseph by CALL; seed_as_stars THREE the tape's — Genesis 15:5, primeval by CALL); THE FALSE SIX'S GUARD at 28:63 — the parser reads 'rejoiced' as SIX (the numeral and the verb share their consonants), the Onkelos store's 'rejoiced' (chadi in the Aramaic) settles it (a DATA row the_false_six); 30:9's twin ahead; 'to destroy you' 26:5's Laban's verb turned on Israel", "and you shall be left few in number", "Deut 28:62-63, 26:5 (this runner's own line — few in number), 10:22 (second_tablets — the seventy); Genesis 15:5 (primeval — the stars), 46:27 (joseph — the seventy); Onkelos 28:62-63", 'left_few_in_number_as_he_rejoiced_so_he_rejoices_to_destroy')
E['scattered_among_all_peoples'] = ("scattered among all peoples — the HEAVEN entry the line plagues_scattered_declared writes on Israel: 'AND THE LORD WILL SCATTER YOU AMONG ALL PEOPLES, from the end of the earth to the end of the earth' (28:64) — Leviticus 26:33's scattering (tochacha.cascade(4) by CALL — the fifth gate's land_desolate and scattered_among_nations ZERO on the running world UNMOVED: this line writes its own heaven entry, the Leviticus transfer never fired); 4:27's 'the LORD will scatter you among the peoples' (obey_horeb.the_exile_case('perish_and_scatter') by CALL); 28:37's 'among all the peoples' the seat", "and the LORD will scatter you among all peoples, from the end of the earth to the end of the earth", "Deut 28:64, 4:27 (obey_horeb — the scattering), 28:37 (this runner's own line); Leviticus 26:33 (tochacha — the fifth gate, the reference); Onkelos 28:64", 'scattered_among_all_peoples_to_serve_wood_and_stone')
E['serving_wood_and_stone_among_nations'] = ("serving wood and stone among the nations — the HEAVEN entry the line plagues_scattered_declared writes on Israel: 'and there YOU SHALL SERVE OTHER GODS which you have not known, you nor your fathers, WOOD AND STONE' (28:64) — 4:28's 'there you shall serve gods, the work of men's hands, wood and stone' (obey_horeb.the_exile_case('serve_wood_and_stone') by CALL — '28:36 and 28:64 forward'); 'which you have not known, you nor your fathers' 28:36 and 28:64 eight in order; Onkelos 'peoples worshipping errors'", "and there you shall serve other gods which you have not known, you nor your fathers, wood and stone", "Deut 28:64, 4:28 (obey_horeb — wood and stone, the reference), 28:36 (this runner's own line); Onkelos 28:64", 'scattered_among_all_peoples_to_serve_wood_and_stone')
E['trembling_heart_no_rest'] = ("a trembling heart and no rest — the HEAVEN entry the line trembling_ships_covenant_declared writes on Israel: 'and among those nations YOU SHALL FIND NO REST, AND THERE SHALL BE NO REST FOR THE SOLE OF YOUR FOOT; and THE LORD WILL GIVE YOU THERE A TREMBLING HEART, failing eyes and a languishing soul' (28:65) — Leviticus 26:36's 'the sound of a driven leaf shall chase them' the twin (tochacha by CALL); Isaiah 34:14's rest the Prophets' seat (a pointer ahead OWED, not read); Onkelos plain", "and the LORD will give you there a trembling heart", "Deut 28:65; Leviticus 26:36 (tochacha — the faint heart, the twin); Onkelos 28:65; Isaiah 34:14 (a pointer ahead OWED, not read)", 'no_rest_for_the_sole_of_your_foot_a_trembling_heart')
E['life_hanging_in_doubt'] = ("the life hanging in doubt — the HEAVEN entry the line trembling_ships_covenant_declared writes on Israel: 'AND YOUR LIFE SHALL HANG IN DOUBT BEFORE YOU, and you shall fear night and day and have no assurance of your life; in the morning you shall say: would it were evening, and in the evening you shall say: would it were morning, for the fear of your heart which you shall fear and the sight of your eyes which you shall see' (28:66-67) — 28:34's 'mad from the sight of your eyes' the pair; Onkelos plain", "and your life shall hang in doubt before you", "Deut 28:66-67, 28:34 (this runner's own line); Onkelos 28:66-67", 'your_life_hangs_in_doubt_morning_and_evening')
E['returned_to_egypt_in_ships'] = ("returned to Egypt in ships — the HEAVEN entry the line trembling_ships_covenant_declared writes on Israel: 'AND THE LORD WILL BRING YOU BACK TO EGYPT IN SHIPS, BY THE WAY OF WHICH I SAID TO YOU: YOU SHALL NOT SEE IT AGAIN' (28:68) — THE RUN CITATION OF 17:16 (courts_prophet.the_king('the_three_limits_for_himself') by CALL — return_to_egypt_barred ONE on Israel UNMOVED, the king's block the tape's; the fifth AS_WHEN pointer RUN_CITATION reference; the readback's second POINTER ROW, a receipt under the retelling rules); 'in ships' Onkelos's word; the reading's crown 'the ships' AS I SAID on 17:16'", "and the LORD will bring you back to Egypt in ships", "Deut 28:68, 17:16 (courts_prophet — the return to Egypt barred, the run citation); Onkelos 28:68", 'back_to_egypt_in_ships_sold_and_none_buys')
E['sold_and_none_buys'] = ("sold and none buys — the HEAVEN entry the line trembling_ships_covenant_declared writes on Israel: 'and there YOU SHALL BE SOLD TO YOUR ENEMIES for bondmen and bondwomen, AND NONE SHALL BUY' (28:68) — 15:12's Hebrew slave sold INVERTED (release_firstborn.the_hebrew_slave by CALL — the readback row TURNED: the brother sold and released, the exile sold and unbought); Leviticus 26:38's perishing among the nations the kin (tochacha by CALL); Onkelos plain", "and there you shall be sold to your enemies for bondmen and bondwomen, and none shall buy", "Deut 28:68, 15:12 (release_firstborn — the Hebrew slave sold, inverted); Leviticus 26:38 (tochacha); Onkelos 28:68", 'back_to_egypt_in_ships_sold_and_none_buys')
E['covenant_words_in_moab_declared'] = ("the words of the covenant in Moab declared — the STATUS the line trembling_ships_covenant_declared writes on Israel: 'THESE ARE THE WORDS OF THE COVENANT WHICH THE LORD COMMANDED MOSES TO CUT WITH THE CHILDREN OF ISRAEL IN THE LAND OF MOAB, BESIDES THE COVENANT He cut with them at Horeb' (28:69) — THE REGISTER'S FOOTER (the stamp moab): the block (12:1, 28:69] of the statutes' declaration closes, its class DAEMONS computed by the census (eight daemons inside after this sitting), the register file untouched; the Sifrei 104:8's THREE COVENANTS — Horeb, the plains of Moab, Gerizim and Ebal (the kid's three prohibitions the count's ground); covenant_cut THREE and entered_the_covenant THREE UNMOVED (covenant_blood_thrown Exodus 24:8 and covenant_declared 4:10 the tape's — the readback row's references); Exodus 34:28's 'the words of the covenant' the Torah's other seat (second_tablets by CALL); 1 Kings 8:9 the tablets' seat ahead (a pointer OWED, not read); 29:1 (sitting 19's) opens Moses' recital", "these are the words of the covenant which the LORD commanded Moses", "Deut 28:69, 12:1 (the register's block), 4:10 (obey_horeb — the covenant declared), 5:2 (covenant_at_horeb); Exodus 24:8 (the covenant's blood), 34:28 (second_tablets — the words of the covenant); Onkelos 28:69; the Sifrei on Deuteronomy 104:8", 'these_are_the_words_of_the_covenant_in_the_land_of_moab_besides_horeb')
assert len(E) == 91 and set(E) == set(OWN91), (len(E), set(OWN91) - set(E), set(E) - set(OWN91))
# THE ROWS built from the spec's lines: (name, op, en, he with its gloss, ink, corpus, exam)
CELLN = {k: v for k, v in S.CELLS.items()}
# the he's seat is the verse PHRASE found it in — read from the phrase table's own call above (the verse typed beside the tokens), never a second typing
HV = {}
for l in open(__file__, encoding='utf-8').read().split('\n'):
    for m in re.finditer(r"H\['([a-z_]+)'\] = PHRASE\(D, (2[678]), (\d+), ", l): HV[m.group(1)] = (m.group(2), m.group(3))
assert len(HV) == 91 and set(HV) == set(OWN91)
NEW = []
for kind, first, rng, claim, cell, fields, effs, reuses in S.LINES:
    c_, lo_, hi_ = RNG(rng)
    for name, op in effs:
        en, gloss, ink, ask = E[name]
        assert ask in fields, (name, ask, fields)
        assert int(HV[name][0]) == c_ and lo_ <= int(HV[name][1]) <= hi_, (name, HV[name], rng)   # the phrase's verse inside its line's range
        NEW.append((name, op, en, "%s (%s — Deut %s:%s)" % (H[name], gloss, HV[name][0], HV[name][1]), ink, CORPUS, EX % (cell, CELLN[cell], ask, kind)))
assert len(NEW) == 91 and [n for n, *_ in NEW] == list(OWN91), (len(NEW), [n for n, *_ in NEW][:3])
assert all(H[n] in he for n, op, en, he, *_ in NEW), 'every he from the phrase table'
added = 0
for name, op, en, he, ink, corpus, exam in NEW:
    if name in fx: continue
    text = text.rstrip('\n') + '\n' + f"  {name}:\n    en: {q(en)}\n    he: {q(he)}\n    ledger_op: {op}   # {W18}: chapters 26-28's compile, LEAN — {name}, the name and the value from the spine's rows, Onkelos and the twenty-six Mishnah rows\n    ink: {q(ink)}\n    corpus: {q(corpus)}\n    exam: {q(exam)}\n"
    added += 1
# ---- THE FOUR REUSED ROWS AMENDED with their further seats (13b's and 14b's precedent — a reused effect is a further entry on the same ledger; the row names its new seat, its value untouched) ----
SEATS = {'rejoicing_before_the_lord_commanded': [('third_seat', "%s — the STATUS REUSED at Deut 26:11 by law_firstfruits_ebal_curses on israel_people (the line first_fruits_declared: 'and you shall rejoice in all the good … you and the Levite and the stranger in your midst' — the Sifrei 301:35-37, every kind of joy; food_tithe's reuse the precedent); the rows 12:7, 12:12, 12:18 the first seat, 14:26 the second" % W18),
                                                  ('fourth_seat', "%s — the STATUS REUSED at Deut 27:7 by law_firstfruits_ebal_curses on israel_people (the line stones_altar_declared: 'and you shall sacrifice peace offerings and eat there and rejoice before the LORD your God' — THE SOURCE SEAT of rejoicing = peace offerings, the Sifrei 64:2, 69:1, 107:16, 138:1 borrowing it by I2); the fourth entry at the definition's own seat" % W18)],
         'poor_tithe_owed': [('second_seat', "%s — the STATUS REUSED at Deut 26:12 by law_firstfruits_ebal_curses on israel_people (the line tithe_confession_declared: 'when you have finished tithing all the tithe of your yield in the third year, the year of the tithe, and have given it to the Levite, the stranger, the orphan and the widow' — the Sifrei 302:1, 303:1-4; one tithe not two, 109:5); the row 14:28-29 above the first seat" % W18)],
         'blessings_for_hearing': [('third_seat', "%s — the conditional HEAVEN entry REUSED at Deut 28:1 by law_firstfruits_ebal_curses on israel_people (the line blessings_condition_declared: 'if you diligently hearken to the voice of the LORD your God … all these blessings shall come upon you' — 15:5's fourteen of seventeen in order, 7:12's 'because you hear'; THE STATE ROW's first arm with 28:15 its negation sixteen in order); the rows 7:12 the first seat, 15:5 the second" % W18)],
         'rain_in_its_season': [('second_seat', "%s — the conditional HEAVEN entry REUSED at Deut 28:12 by law_firstfruits_ebal_curses on israel_people (the line heavens_treasure_lending_declared: 'the LORD will open to you His good treasure, the heavens, to give the rain of your land in its season' — the rain state's blessing seat, the Sifrei 40:12 with 11:17 the shutting; 306:6 'open' is widen); the row 11:14 above the first seat" % W18)]}
assert sorted(SEATS) == sorted(S.REUSE_BEFORE) and sum(len(v) for v in SEATS.values()) == 5 == len(S.REUSES)
amended = 0
for name, seats in SEATS.items():
    i = text.index(f'\n  {name}:\n'); j = i + 1
    while True:
        j = text.find('\n  ', j + 1)
        if j < 0 or (j + 3 < len(text) and text[j + 3] not in ' \n' and text[j + 2] == ' '): break
    row = text[i:j] if j > 0 else text[i:]
    if W18 in row: continue
    ins = ''.join(f'    {k}: {q(v)}\n' for k, v in seats)
    text = text[:i] + row.rstrip('\n') + '\n' + ins + (text[j + 1:] if j > 0 else '')
    amended += len(seats)
if not CHECK:
    open(path, 'w', encoding='utf-8').write(text)
fx = yaml.safe_load(open(path, encoding='utf-8'))['effects']
assert CHECK or (all(n in fx for n, *_ in NEW) and fx['tithe_in_mourning_barred']['ledger_op'] == 'block' and fx['blessed_in_city_and_field']['ledger_op'] == 'heaven' and fx['first_fruits_basket_commanded']['ledger_op'] == 'status' and fx['covenant_words_in_moab_declared']['ledger_op'] == 'status')
assert CHECK or (fx['rejoicing_before_the_lord_commanded'].get('third_seat') and fx['rejoicing_before_the_lord_commanded'].get('fourth_seat') and fx['poor_tithe_owed'].get('second_seat') and fx['blessings_for_hearing'].get('third_seat') and fx['rain_in_its_season'].get('second_seat')), 'the reused rows amended'
C = S.counts()
assert sum(1 for n, op, *_ in NEW if op == 'block') == 5 == C['ops']['block'] and sum(1 for n, op, *_ in NEW if op == 'status') == 33 == C['ops']['status'] and sum(1 for n, op, *_ in NEW if op == 'heaven') == 53 == C['ops']['heaven'], (sum(1 for n, op, *_ in NEW if op == 'block'), sum(1 for n, op, *_ in NEW if op == 'status'), sum(1 for n, op, *_ in NEW if op == 'heaven'))
print('effects: %d %s (registry %d); the reused rows amended with %d seats (%s); the he found in the verses: %s' % (added, 'to add' if CHECK else 'added', len(fx), amended, 'to amend' if CHECK else 'amended', ' | '.join('%s=%s' % (k, v) for k, v in H.items())))
