

# =====================================================================
# THE CELLS OF CHAPTERS 30-31:8 — F6 the return and the gathering (30:1-5), F7 the heart circumcised (30:6-10), F8 the commandment near (30:11-14), F9 life and death (30:15-20), F10 the charge and the crossing (31:1-8 — THE MARKER'S CHAPTER OPENS)
# =====================================================================
D1 = "Moses' last day (40, 12, 7) — after THE ONE MARKER at 31:1 (the number's verse 31:2)"
def the_return_and_the_gathering(case, data):
    """F6 — Deut 30:1-5 — ONE LINE return_and_gathering_declared (STATUTE) writing return_to_the_lord_the_condition (a STATUS) and captivity_returned_on_return, gathered_from_all_the_peoples, gathered_from_the_end_of_heaven, brought_into_the_fathers_land_again and multiplied_above_the_fathers (HEAVEN entries, conditional on the return); the exile case's recovery arm told fully (obey_horeb by CALL — '30:2's kin'); the pair set (blessing_and_curse by CALL); Leviticus 26:40-42's confession the twin (tochacha by CALL)"""
    del P_[:]
    ask = case['ask']
    if ask == 'when_all_these_things_come_and_you_take_it_to_heart':
        ink('30:1', "'and it shall be, WHEN ALL THESE THINGS COME UPON YOU, the blessing and the curse which I have set before you, AND YOU TAKE IT TO HEART among all the nations where the LORD your God has driven you' — 'the blessing and the curse' %s (twice in the Torah and Joshua 8:34); 'driven' the hiphil" % (P('הברכה', 'והקללה', books=None),))
        move("cold_run_blessing_and_curse (CALL) — BC.the_blessing_and_the_curse(see_i_set_before_you) = %s (11:26's pair; blessing_and_curse_set ONE before this sitting); cold_run_obey_horeb (CALL) — OH.DATA the_exile_case arms %s" % (BC_SEE[0][:50], OH_CASE['value']['arms'][5:8]), "THE CASE'S HEAD — the exile case's third arm (4:29-31 the first telling of the return): the readback rows 30:1-3 REFERENCE rows against the exile case's line; no write of its own")
        dat("no write — the head; THE LINE return_and_gathering_declared's first verse 30:1 — the readback row SUPPLIED with the line's six writes")
        return out("when all these things come and you take it to heart (30:1) — the pair set (11:26 by CALL) come upon you among the nations: the exile case's third arm, 4:29-31's return told fully (obey_horeb — %s); the head of the return, no write of its own" % (OH_CASE['value']['arms'][6],), ['accepted'])
    if ask == 'return_to_the_lord_and_hearken_with_all_your_heart':
        ink('30:2', "'AND YOU RETURN TO THE LORD YOUR GOD AND HEARKEN TO HIS VOICE according to all that I command you this day, you and your children, with all your heart and with all your soul' — 4:30's SIX IN ORDER (the twin diffed %d); the return's root seven times in the chapter" % (TWIN['30:2 vs 4:30'],))
        move("cold_run_obey_horeb (CALL) — OH.the_exile_case(in_your_distress_return) = %s; cold_run_tochacha (CALL) — TC.covenant(T, T, T) = %s (Leviticus 26:40-42's confession and remembering the recovery branch's predicates); cold_run_hear_o_israel (CALL) — HI.the_creed(with_all_your_heart) = %s" % (OH_RETURN[0][:50], TC_COV_T['v'], HI_HEART[0][:40]), "THE WRITE return_to_the_lord_the_condition — a STATUS on Israel (DM2): the condition named, the return not yet done — no act on the tape, the world's later run")
        dat("THE WRITE return_to_the_lord_the_condition, a STATUS on israel_people at %s; the readback row 30:2 REFERENCE against the exile case's arm (4:30) by CALL" % D0)
        return out("return to the LORD and hearken with all your heart (30:2) — 4:30's six in order (%d shared), the exile case's third arm (obey_horeb — %s); the return the chapter's root seven times: THE WRITE return_to_the_lord_the_condition, a STATUS on Israel — the condition named, the return not yet done" % (TWIN['30:2 vs 4:30'], OH_RETURN[0][:30]), ['return_to_the_lord_the_condition'])
    if ask == 'the_lord_returns_your_captivity_and_has_compassion':
        ink('30:3', "'then THE LORD YOUR GOD WILL RETURN YOUR CAPTIVITY AND HAVE COMPASSION UPON YOU, and will return and GATHER YOU FROM ALL THE PEOPLES where the LORD your God has scattered you' — Onkelos 'the captives of your exile'; 'return your captivity' Jeremiah's and Psalm 126's phrase (the seats cited, never read)")
        move("cold_run_obey_horeb (CALL) — OH.the_exile_case(the_merciful_god) = %s (4:31); OH.the_exile_case(perish_and_scatter) = %s (4:27's scattering); cold_run_firstfruits_ebal_curses (CALL) — 28:64's scattered_among_all_peoples ONE" % (OH_MERCY[0][:40], OH_PERISH[0][:50]), "THE WRITES captivity_returned_on_return and gathered_from_all_the_peoples — conditional HEAVEN entries (DM2): the LORD's acts conditional on the return")
        dat("THE WRITES captivity_returned_on_return and gathered_from_all_the_peoples, HEAVEN entries (conditional) on israel_people at %s; the readback row 30:3 REFERENCE against the exile case's mercy and scattering by CALL" % D0)
        return out("the LORD returns your captivity and has compassion, and gathers you from all the peoples (30:3) — the merciful God of 4:31 (obey_horeb — %s), the scattering of 4:27 and 28:64 undone: THE WRITES captivity_returned_on_return and gathered_from_all_the_peoples, conditional HEAVEN entries" % (OH_MERCY[0][:30],), ['captivity_returned_on_return', 'gathered_from_all_the_peoples'])
    if ask == 'gathered_from_all_the_peoples_even_from_the_end_of_heaven':
        ink('30:4', "'IF YOUR OUTCASTS BE AT THE END OF HEAVEN, from there the LORD your God will gather you and from there fetch you' — 'the end of heaven' %s (Nehemiah 1:9 the Writings' seat cited, never read — Nehemiah's prayer the run's own reading); 'if' the chapter's first (%s)" % (P('בקצה', 'השמים', books=None), [(c, v) for c, v in SPAN if 'אם' in W(c, v) or 'ואם' in W(c, v)][0]))
        move("the reading's formula (the end of heaven at 30:4 and Nehemiah 1:9 alone); the outcasts' niphal patched 'your-outcasts' at the reading's tail", "THE WRITE gathered_from_the_end_of_heaven — a conditional HEAVEN entry (DM2): the gathering's reach unbounded")
        dat("THE WRITE gathered_from_the_end_of_heaven, a HEAVEN entry (conditional) on israel_people at %s; the readback row 30:4 SUPPLIED — the pointer AHEAD to Nehemiah 1:9 OWED" % D0)
        return out("gathered even from the end of heaven (30:4) — the reach unbounded, the phrase at 30:4 and Nehemiah 1:9 alone (the run's own reading, owed): THE WRITE gathered_from_the_end_of_heaven, a conditional HEAVEN entry", ['gathered_from_the_end_of_heaven'])
    if ask == 'brought_into_the_fathers_land_and_multiplied_above_them':
        ink('30:5', "'and THE LORD YOUR GOD WILL BRING YOU INTO THE LAND WHICH YOUR FATHERS POSSESSED, and you shall possess it; and HE WILL DO YOU GOOD AND MULTIPLY YOU ABOVE YOUR FATHERS' — 30:5 WITH NO KIN AT ALL by shared tokens (KINC %s — the reading's find)" % (KINC[(30, 5)],))
        move("cold_run_good_land (CALL) — GL.the_way_of_forty_years(keep_walk_fear) read (8:1's live and multiply the kin); seed_as_stars THREE UNMOVED (Genesis 15:5 — the fathers' own promise referenced)", "THE WRITES brought_into_the_fathers_land_again and multiplied_above_the_fathers — conditional HEAVEN entries (DM2): the return's promises on one ledger, each opened conditional")
        dat("THE WRITES brought_into_the_fathers_land_again and multiplied_above_the_fathers, HEAVEN entries (conditional) on israel_people at %s; the readback row 30:5 SUPPLIED (no kin)" % D0)
        return out("brought into the fathers' land and multiplied above them (30:5) — the verse with no kin by shared tokens; the growth beyond 8:1's and the stars' promise referenced: THE WRITES brought_into_the_fathers_land_again and multiplied_above_the_fathers, conditional HEAVEN entries", ['brought_into_the_fathers_land_again', 'multiplied_above_the_fathers'])
    return 'no verdict in span', [], list(P_)


def the_heart_circumcised(case, data):
    """F7 — Deut 30:6-10 — ONE LINE heart_circumcised_declared (STATUTE) writing heart_circumcised_by_the_lord, curses_put_on_the_enemies, abounding_in_fruit_of_body_cattle_ground and rejoiced_over_as_over_the_fathers (HEAVEN entries) and return_and_hearken_and_do_commanded (a STATUS); 10:16's command made the LORD's act (second_tablets by CALL); THE FALSE SIX A SECOND TIME at 30:9 (firstfruits_ebal_curses' DATA — the guard); 'as He rejoiced' a comparative, the pointer FALSE"""
    del P_[:]
    ask = case['ask']
    if ask == 'the_lord_circumcises_your_heart_to_love_him':
        ink('30:6', "'and THE LORD YOUR GOD WILL CIRCUMCISE YOUR HEART and the heart of your seed, to love the LORD your God with all your heart and with all your soul, that you may live' — 10:16's command 'circumcise the foreskin of your heart' here the LORD's act; 6:5's pair (the twin diffed %d)" % (TWIN['30:6 vs 6:5'],))
        move("cold_run_second_tablets (CALL) — 10:16's heart_circumcision_commanded ONE UNMOVED (its ink names '30:6 the passive form'; ST.the_levites_separated read); cold_run_hear_o_israel (CALL) — HI.the_creed(with_all_your_heart) = %s; Onkelos 30:6 'the folly of your heart removed' (the reading's crown — Onkelos writes the meaning)" % (HI_HEART[0][:50],), "THE WRITE heart_circumcised_by_the_lord — a conditional HEAVEN entry (DM2): the command's fulfilment by Heaven")
        dat("THE WRITE heart_circumcised_by_the_lord, a HEAVEN entry (conditional) on israel_people at %s; THE LINE heart_circumcised_declared's first verse — the readback row 30:6 SUPPLIED and REFERENCE against heart_circumcision_commanded (10:16)" % D0)
        return out("the LORD circumcises your heart to love Him (30:6) — 10:16's command made Heaven's act (Onkelos: the folly of the heart removed), 6:5's heart and soul (%d shared): THE WRITE heart_circumcised_by_the_lord, a conditional HEAVEN entry" % (TWIN['30:6 vs 6:5'],), ['heart_circumcised_by_the_lord'])
    if ask == 'the_curses_put_on_your_enemies_who_pursued_you':
        ink('30:7', "'and THE LORD YOUR GOD WILL PUT ALL THESE CURSES UPON YOUR ENEMIES and on those who hate you, who persecuted you' — chapter 28's curses TURNED on the enemies")
        move("cold_run_firstfruits_ebal_curses (CALL) — FE.DATA the_hearkening_state (the curse arm %s turned); cold_run_seven_nations (CALL) — SN.because_you_hear(the_diseases) = %s (7:15's diseases on those who hate you the precedent)" % (FE_STATE['value']['the_curse_arm'], SN_DIS[0][:40]), "THE WRITE curses_put_on_the_enemies — a conditional HEAVEN entry (DM2); the readback row TURNED")
        dat("THE WRITE curses_put_on_the_enemies, a HEAVEN entry (conditional) on israel_people at %s; the readback row 30:7 TURNED against curses_condition_declared (28:15)" % D0)
        return out("the curses put on your enemies who pursued you (30:7) — chapter 28's curses turned on the enemies, 7:15's diseases the precedent (seven_nations — %s): THE WRITE curses_put_on_the_enemies, a conditional HEAVEN entry" % (SN_DIS[0][:30],), ['curses_put_on_the_enemies'])
    if ask == 'you_return_and_hearken_and_do_all_his_commandments':
        ink('30:8', "'and YOU SHALL RETURN AND HEARKEN TO THE VOICE OF THE LORD and do all His commandments which I command you this day' — the return's second seat, the deed after the heart; Onkelos 'receive the Memra'; 30:10's third seat closes the frame")
        move("cold_run_obey_horeb (CALL) — OH.the_exile_case(seek_and_find) = %s ('30:10's kin'); the return's seven seats in the chapter (30:1, 2, 3 twice, 8, 9, 10)" % (OH_SEEK[0][:50],), "THE WRITE return_and_hearken_and_do_commanded — a STATUS on Israel (DM2); 30:10 a DATA note, no write")
        dat("THE WRITE return_and_hearken_and_do_commanded, a STATUS on israel_people at %s; the readback rows 30:8 SUPPLIED, 30:10 REFERENCE against the exile case's seek and find (4:29)" % D0)
        return out("you return and hearken and do all His commandments (30:8) — the deed after the heart, the return's second seat (4:29's seek and find the kin — %s): THE WRITE return_and_hearken_and_do_commanded, a STATUS on Israel; 30:10 closes the frame on the condition" % (OH_SEEK[0][:30],), ['return_and_hearken_and_do_commanded'])
    if ask == 'abounding_in_the_fruit_of_body_cattle_and_ground':
        ink('30:9', "'and THE LORD YOUR GOD WILL MAKE YOU ABOUND IN ALL THE WORK OF YOUR HAND, in the fruit of your body, in the fruit of your cattle and in the fruit of your ground, for good' — 28:11's THREE FRUITS six in order (the twin diffed %d)" % (TWIN['30:9 vs 28:11'],))
        move("cold_run_firstfruits_ebal_curses (CALL) — FE.the_blessings(plenteous_in_goods_womb_beast_and_ground) = %s (7:13's list the source); 28:12's 'the work of your hand' (work_of_the_hand_blessed the tape's — a reference)" % (FE_FRUITS[0][:50],), "THE WRITE abounding_in_fruit_of_body_cattle_ground — a conditional HEAVEN entry (DM2): the blessing's return")
        dat("THE WRITE abounding_in_fruit_of_body_cattle_ground, a HEAVEN entry (conditional) on israel_people at %s; the readback row 30:9 REFERENCE against heavens_treasure_lending_declared (28:11)" % D0)
        return out("abounding in the fruit of body, cattle and ground (30:9) — 28:11's three fruits six in order (%d shared; firstfruits_ebal_curses — %s): THE WRITE abounding_in_fruit_of_body_cattle_ground, a conditional HEAVEN entry" % (TWIN['30:9 vs 28:11'], FE_FRUITS[0][:30]), ['abounding_in_fruit_of_body_cattle_ground'])
    if ask == 'rejoicing_over_you_as_he_rejoiced_over_your_fathers':
        ink('30:9', "'for THE LORD WILL AGAIN REJOICE OVER YOU FOR GOOD, AS HE REJOICED OVER YOUR FATHERS' — THE FALSE SIX A SECOND TIME: the parser's %s at 30:9 is the verb 'rejoiced' (%s after 'as' — the numeral's consonants); the twin with 28:63 %d shared" % (PARSE[(30, 9)][0], FALSE_SIX, TWIN['30:9 vs 28:63']))
        move("cold_run_firstfruits_ebal_curses (CALL) — FE.DATA the_false_six = %s ('30:9's twin ahead'); the runner's ink assert reads the chapter's numerals without it (Onkelos 30:9 'rejoiced' — chadi — the reading's row)" % (FE_SIX['value']['28:63'][:60],), "THE WRITE rejoiced_over_as_over_the_fathers — a conditional HEAVEN entry (DM2); 'as He rejoiced' A COMPARATIVE — the census's AS_WHEN pointer predicted FALSE (28:63's precedent); a DATA row the_false_six_twice")
        dat("THE WRITE rejoiced_over_as_over_the_fathers, a HEAVEN entry (conditional) on israel_people at %s; THE POINTER Deut 30:9 predicted FALSE (a comparative); the readback row 30:9 REFERENCE against plagues_scattered_declared (28:63 — the false six's first seat)" % D0)
        return out("rejoicing over you as He rejoiced over your fathers (30:9) — the false six a second time: the parser's [6] the verb 'rejoiced', guarded by Onkelos's verb as at 28:63 (firstfruits_ebal_curses — %s): THE WRITE rejoiced_over_as_over_the_fathers, a conditional HEAVEN entry; 'as He rejoiced' a comparative, the pointer FALSE" % (FE_SIX['value']['28:63'][:40],), ['rejoiced_over_as_over_the_fathers'])
    return 'no verdict in span', [], list(P_)


def the_commandment_near(case, data):
    """F8 — Deut 30:11-14 — ONE LINE commandment_near_declared (STATUTE) writing commandment_not_too_hard_nor_far, commandment_not_in_heaven_nor_beyond_the_sea and commandment_in_mouth_and_heart_to_do (STATUSES); THE PROGRAM IS ON EARTH, its judge the court (courts_prophet by CALL — 17:8-11); Bava Metzia 59b and Eruvin 55a OWED to the docket"""
    del P_[:]
    ask = case['ask']
    if ask == 'the_commandment_not_too_hard_nor_far':
        ink('30:11', "'for this commandment which I command you this day IS NOT TOO HARD FOR YOU, NOR IS IT FAR OFF' — 'too hard' (niflet — patched 'too-hard' at the reading's tail); 17:8's hard case the lemma's kin")
        move("cold_run_courts_prophet (CALL) — CP.the_king(the_circle_of_learning_and_the_heart) = %s (17:8-11's court the judge of the hard case; 17:19-20 the circle of learning)" % (CP_CIRCLE[0][:50],), "THE WRITE commandment_not_too_hard_nor_far — a STATUS on Israel (DM2): the commandment's reach declared")
        dat("THE WRITE commandment_not_too_hard_nor_far, a STATUS on israel_people at %s; THE LINE commandment_near_declared's first verse — the readback row 30:11 SUPPLIED" % D0)
        return out("the commandment not too hard nor far (30:11) — the reach declared; 17:8's hard case the lemma's kin, the court its judge (courts_prophet — %s): THE WRITE commandment_not_too_hard_nor_far, a STATUS on Israel" % (CP_CIRCLE[0][:30],), ['commandment_not_too_hard_nor_far'])
    if ask == 'not_in_heaven_nor_beyond_the_sea':
        ink('30:12-13', "'IT IS NOT IN HEAVEN, that you should say: who will go up for us to heaven and bring it to us that we may hear it and do it? nor is it beyond the sea, that you should say: who will cross for us …' — 30:12 and 30:13 each other's kin (the twin diffed %d; 'saying' twice — %s); 'not in heaven' %s" % (TWIN['30:12 vs 30:13'], [f'{c}:{v}' for c, v in SPAN if 'לאמר' in W(c, v)][1:3], P('לא', 'בשמים', 'הוא', books=None)))
        move("Bava Metzia 59b (the oven of Akhnai — the Torah decided by the majority, not by a voice from heaven) and Eruvin 55a (not found in the haughty) OWED to the docket — no row here; cold_run_courts_prophet (CALL) — the high court of 17:8-11 'you shall not turn aside from the word they tell you'", "THE WRITE commandment_not_in_heaven_nor_beyond_the_sea — a STATUS on Israel (DM2): the compile's own boundary — THE PROGRAM IS ON EARTH, its judge the court; 'the end of heaven' 30:4's and 'in heaven' 30:12's the chapter's two heavens (a DATA note)")
        dat("THE WRITE commandment_not_in_heaven_nor_beyond_the_sea, a STATUS on israel_people at %s; the readback rows 30:12-13 REFERENCE against king_law_declared's court (17:8)" % D0)
        return out("not in heaven nor beyond the sea (30:12-13) — the two verses each other's kin (%d shared), the program on earth and its judge the court of 17:8-11 (Bava Metzia 59b owed): THE WRITE commandment_not_in_heaven_nor_beyond_the_sea, a STATUS on Israel" % (TWIN['30:12 vs 30:13'],), ['commandment_not_in_heaven_nor_beyond_the_sea'])
    if ask == 'in_your_mouth_and_in_your_heart_to_do_it':
        ink('30:14', "'but THE WORD IS VERY NEAR TO YOU, IN YOUR MOUTH AND IN YOUR HEART, TO DO IT' — 'in your mouth and in your heart' ONCE in the Bible (%s)" % (P('בפיך', 'ובלבבך', books=None),))
        move("cold_run_hear_o_israel (CALL) — HI.the_creed(hear_o_israel) = %s (6:6-7's words on the heart and in the mouth — the teaching); Onkelos plain" % (HI_HEAR[0][:40],), "THE WRITE commandment_in_mouth_and_heart_to_do — a STATUS on Israel (DM2): the mouth the study, the heart the intent, the deed the end")
        dat("THE WRITE commandment_in_mouth_and_heart_to_do, a STATUS on israel_people at %s; the readback row 30:14 SUPPLIED with the three writes" % D0)
        return out("in your mouth and in your heart, to do it (30:14) — the phrase once in the Bible; the study, the intent and the deed (6:6-7's words the kin — hear_o_israel): THE WRITE commandment_in_mouth_and_heart_to_do, a STATUS on Israel", ['commandment_in_mouth_and_heart_to_do'])
    return 'no verdict in span', [], list(P_)


def life_and_death(case, data):
    """F9 — Deut 30:15-20 — ONE LINE life_and_death_choice_declared (STATUTE) writing life_and_death_set_before_israel and choose_life_commanded (STATUSES) and living_and_multiplying_for_hearkening, perishing_for_turning_away and length_of_days_on_the_land_promised (HEAVEN entries — THE STATE ROW's two arms); heaven_and_earth_witness REUSED at 30:19 (the chain's third seat), blessing_and_curse_set REUSED at 30:19, cleaving_commanded REUSED at 30:20; the kin by CALL (blessing_and_curse — 11:26's form; good_land — walk in His ways, the testimony; obey_horeb — the witnesses, the chain)"""
    del P_[:]
    ask = case['ask']
    if ask == 'see_i_set_before_you_life_and_good_death_and_evil':
        ink('30:15', "'SEE, I HAVE SET BEFORE YOU THIS DAY LIFE AND GOOD, AND DEATH AND EVIL' — 11:26's 'see, I set before you this day a blessing and a curse' the form; 'life and death' ONCE in the Bible (%s); the imperative 'see'" % (P('החיים', 'והמות', books=None),))
        move("cold_run_blessing_and_curse (CALL) — BC.the_blessing_and_the_curse(see_i_set_before_you) = %s ('30:15-20 the run forward' — the cell read these verses ahead); the Sifrei 53:1's parable of the two ways (E26 typed at the reading)" % (BC_SEE[0][:60],), "THE WRITE life_and_death_set_before_israel — a STATUS on Israel (DM2): the pair's second setting with the terms life and death; THE STATE ROW at 30:15-18 with two arms (13b's form — a DATA row the_life_and_death_state naming 11:26-28's pair and 28:1/28:15's as the three settings of one state)")
        dat("THE WRITE life_and_death_set_before_israel, a STATUS on israel_people at %s; THE STATE ROW's head 30:15 — the readback row SUPPLIED and state" % D0)
        return out("see, I have set before you life and good, death and evil (30:15) — 11:26's form with the terms life and death (blessing_and_curse — %s), the phrase once in the Bible: THE WRITE life_and_death_set_before_israel, a STATUS on Israel; THE STATE ROW's head" % (BC_SEE[0][:30],), ['life_and_death_set_before_israel'])
    if ask == 'if_you_love_and_walk_and_keep_you_live_and_multiply':
        ink('30:16', "'in that I command you this day to love the LORD your God, TO WALK IN HIS WAYS and to keep His commandments, His statutes and His judgments, THAT YOU MAY LIVE AND MULTIPLY, and the LORD your God bless you in the land where you go to possess it' — 8:6's 'to walk in His ways', 8:1's 'live and multiply'")
        move("cold_run_good_land (CALL) — GL.the_way_of_forty_years(keep_walk_fear) = %s; blessings_for_hearing THREE UNMOVED (7:12, 15:5, 28:1 — the form)" % (GL_KEEP[0][:60],), "THE WRITE living_and_multiplying_for_hearkening — a conditional HEAVEN entry (DM2): THE STATE ROW's first arm — the pair's own arm, a new name")
        dat("THE WRITE living_and_multiplying_for_hearkening, a HEAVEN entry (conditional) on israel_people at %s; the readback row 30:16 REFERENCE against good_land's 8:1 and 8:6 by CALL" % D0)
        return out("if you love and walk and keep, you live and multiply (30:16) — 8:6's walk in His ways and 8:1's live and multiply (good_land — %s): THE WRITE living_and_multiplying_for_hearkening, a conditional HEAVEN entry — the state row's first arm" % (GL_KEEP[0][:30],), ['living_and_multiplying_for_hearkening'])
    if ask == 'if_your_heart_turns_you_perish_and_not_prolong_days':
        ink('30:17-18', "'but IF YOUR HEART TURNS AWAY and you will not hear, and are drawn away and BOW to other gods AND SERVE them, I DECLARE TO YOU THIS DAY THAT YOU SHALL SURELY PERISH; you shall not prolong your days upon the land' — 'and if' the chapter's second (%s); 'bow and serve' 4:19's order against 8:19's; 30:18 and 4:26 %d shared" % ([(c, v) for c, v in SPAN if 'אם' in W(c, v) or 'ואם' in W(c, v)][1], TWIN['30:18 vs 4:26']))
        move("cold_run_good_land (CALL) — GL.the_testimony(i_testify) = %s; GL.the_testimony(other_gods_serve_bow) = %s (the census of the two orders); cold_run_obey_horeb (CALL) — OH.the_exile_case(perish_and_scatter) = %s (4:26's 'you shall not prolong your days')" % (GL_TESTIFY[0][:50], GL_BOW[0][:40], OH_PERISH[0][:40]), "THE WRITE perishing_for_turning_away — a conditional HEAVEN entry (DM2): THE STATE ROW's second arm (perishing_testified the tape's kind at 8:19)")
        dat("THE WRITE perishing_for_turning_away, a HEAVEN entry (conditional) on israel_people at %s; THE STATE ROW's second arm 30:17 — the readback row REFERENCE against perishing_testified (8:19) and state" % D0)
        return out("if your heart turns you perish and shall not prolong days (30:17-18) — 8:19's testimony and 4:26's not prolonging (good_land — %s; obey_horeb — %s): THE WRITE perishing_for_turning_away, a conditional HEAVEN entry — the state row's second arm" % (GL_TESTIFY[0][:30], OH_PERISH[0][:20]), ['perishing_for_turning_away'])
    if ask == 'heaven_and_earth_called_to_witness_this_day':
        ink('30:19', "'I CALL HEAVEN AND EARTH TO WITNESS against you this day: LIFE AND DEATH I have set before you, THE BLESSING AND THE CURSE' — 'I call to witness' %s; 4:26's first seven words identical (the twin diffed %d)" % (P('העידתי', 'בכם', 'היום', books=T), TWIN['30:19 vs 4:26']))
        move("cold_run_obey_horeb (CALL) — OH.the_exile_case(the_witnesses) = %s; OH.DATA the_witnesses_chain = %s (30:19 the third seat, 31:28 the fourth, 32:1 the fifth — sitting 20's); cold_run_blessing_and_curse (CALL) — 11:26's pair named a second time" % (OH_WIT[0][:50], OH_CHAIN['value']['the_chain']), "heaven_and_earth_witness REUSED — the THIRD entry on Israel (4:26 the first, 8:19's 'I testify' the second); blessing_and_curse_set REUSED — the second entry (11:26's the first); 'life and death' the pair's new names")
        dat("heaven_and_earth_witness REUSED at 30:19 (2 -> 4 over the sitting with 31:28); blessing_and_curse_set REUSED at 30:19 (1 -> 2); the readback row 30:19 REFERENCE against witnesses_called (4:26) — the chain's third seat")
        return out("heaven and earth called to witness this day (30:19) — the chain's third seat (%s; 4:26's seven words identical), life and death the pair's new names: heaven_and_earth_witness REUSED (the third entry) and blessing_and_curse_set REUSED (the second)" % (OH_CHAIN['value']['the_chain'],), ['heaven_and_earth_witness', 'blessing_and_curse_set'])
    if ask == 'choose_life_love_hearken_and_cleave_the_length_of_days':
        ink('30:19-20', "'therefore CHOOSE LIFE, that you may live, you and your seed, to love the LORD your God, to hearken to His voice AND TO CLEAVE TO HIM, for HE IS YOUR LIFE AND THE LENGTH OF YOUR DAYS, that you may dwell in the land which the LORD swore to your fathers, to Abraham, to Isaac and to Jacob, to give them' — the imperative 'choose' (the store's 'try' patched at sitting 16's tail); 'swore' the seven's homograph (%s), no numeral; 30:20 and 1:8 the oath formula" % (SEVENS_HOMOGRAPHS[1],))
        move("the Sifrei 53:1 (the two ways — E26), 306:2 and 306:15 (the outside rows on 30:19 — the witnesses neither reward nor punish, the choice); cold_run_second_tablets (CALL) — 10:20's cleaving_commanded (13:5 the second seat); cold_run_hear_o_israel (CALL) — 6:10's oath of the land (a relative clause, not the AS_WHEN form — no pointer)", "THE WRITES choose_life_commanded (a STATUS — the chapter's one imperative on the pair) and length_of_days_on_the_land_promised (a conditional HEAVEN entry — 30:20's clause the promise's own words); cleaving_commanded REUSED — the THIRD entry (10:20's and 13:5's the first two)")
        dat("THE WRITES choose_life_commanded (a STATUS) and length_of_days_on_the_land_promised (a HEAVEN entry) on israel_people at %s; cleaving_commanded REUSED at 30:20 (2 -> 3); the readback row 30:20 REFERENCE against the cleaving's line (10:20)" % D0)
        return out("choose life, love, hearken and cleave — the length of days (30:19-20) — the chapter's one imperative on the pair (the Sifrei 53:1's two ways), the cleaving's third seat, the oath of the land a relative clause: THE WRITES choose_life_commanded and length_of_days_on_the_land_promised; cleaving_commanded REUSED, the third entry", ['choose_life_commanded', 'length_of_days_on_the_land_promised', 'cleaving_commanded'])
    return 'no verdict in span', [], list(P_)


def the_charge_and_the_crossing(case, data):
    """F10 — Deut 31:1-8 — TWO LINES: crossing_charge_declared (STATUTE, 31:1-6) writing joshua_to_cross_before_israel and be_strong_and_courageous_commanded (STATUSES) and nations_dispossessed_as_sihon_and_og_promised (a HEAVEN entry), fear_not_promised REUSED at 31:6 on Israel; joshua_charged_before_israel (an ACT, 31:7-8) writing joshua_charged_to_bring_israel_in (a STATUS on yehoshua), fear_not_promised REUSED at 31:8 on yehoshua; THE ONE MARKER at 31:1 — 31:2's hundred and twenty, Moses' last day (40, 12, 7): the year the ink's (Exodus 7:7 + 40), the month and the day the answer sheet's (Tosefta Sotah 11:3 read whole; Kiddushin 38a on the kin — exodus_story.birth); the second and third AS_WHEN pointers run citations (opening_speech, chukat by CALL)"""
    del P_[:]
    ask = case['ask']
    if ask == 'moses_went_and_spoke_these_words_to_all_israel':
        ink('31:1', "'AND MOSES WENT AND SPOKE THESE WORDS TO ALL ISRAEL' — THE NARRATIVE PRESENT RETURNS (the book's first since 1:5); Numbers 14:39's 'and Moses spoke these words to all the children of Israel' the kin (the twin diffed %d); 29:1's call %d shared" % (TWIN['31:1 vs Num 14:39'], TWIN['29:1 vs 31:1']))
        move("cold_run_shelach (CALL) — SHL.spies(joshua_name) = %s (Numbers 14:39's Moses' words; 32:44's 'came' against 'went' — the Sifrei 334:1, I13 typed at the reading); Onkelos 31:1 'and Moses went'", "the frame the line's speaker — THE LINE crossing_charge_declared opens at 31:1, THE MARKER placed AT 31:1 for the line's first verse (Genesis 7:1's precedent: the number at 7:4, the position 7:1); no write of its own")
        dat("no write — the frame; THE MARKER at 31:1 (the number's verse 31:2) — the counter's day moves to %s; the readback row 31:1 REFERENCE against speech_opened (1:1)" % (CLOCK['marker'],))
        return out("Moses went and spoke these words to all Israel (31:1) — the narrative present returns (Numbers 14:39 the kin, %d shared; 32:44's 'came' the Sifrei 334:1's I13): the frame of the charge, the marker's position for 31:2's number — Moses' last day %s" % (TWIN['31:1 vs Num 14:39'], CLOCK['marker']), ['accepted'])
    if ask == 'a_hundred_and_twenty_years_old_this_day':
        ink('31:2', "'I AM A HUNDRED AND TWENTY YEARS OLD THIS DAY' — the parser's %s at 31:2; the number's seats %s (34:7 the death's, Genesis 6:3 the reprieve's); THE CLOCK'S ROW" % (PARSE[(31, 2)][0], P('מאה', 'ועשרים', 'שנה', books=None)))
        move("TOSEFTA SOTAH 11:3 (the exam row, read whole) — 'this day' teaches his years were completed to the day; the 7th of Adar computed BACKWARD from Joshua 4:19's tenth of Nisan by the thirty days' weeping (34:8) and the three days (Joshua 1:11); cold_run_chukat (CALL) — CK.edom_and_hor(death_dates) = %s; cold_run_exodus_story (CALL) — ES.birth(birthday) = %s (Kiddushin 38a — born and died on the 7th of Adar; the tape's Exodus 7:7 'Moses was eighty' + the forty years = the hundred and twentieth); cold_run_primeval (CALL) — PV.prologue(reprieve_number) = %s (reprieve_of_a_hundred_and_twenty ONE UNMOVED — a reference, no transfer)" % (CK_DATES[0][:60], ES_BIRTH['v'], PV_120['v']), "THE ONE MARKER — the counter's day moves from 1:3's (40, 11, 1) to (40, 12, 7) for the first time in the book: the year the ink's, the month and the day the answer sheet's; THE PARAMETER the_death_date_of_moses (the calendar's row); a DATA row the_clocks_agreement — the tape's day at the marker against the ink's number, Exodus 7:7's eighty and the kin's two seats of the 7th of Adar")
        dat("THE MARKER at 31:1 (the number's verse 31:2): the day %s, %d days walked from the counter's; THE CALENDAR PARAMETER the_death_date_of_moses on file (exercised_by this runner); no write — the clock's row; the readback row 31:2 REFERENCE against moses_besought (3:23-28 — the bar) and the exodus's Moses eighty" % (CLOCK['marker'], CLOCK['days_walked']))
        return out("a hundred and twenty years old this day (31:2) — the parser's [120]; the year the ink's (Exodus 7:7's eighty + forty), the day the answer sheet's (Tosefta Sotah 11:3 — the 7th of Adar; chukat: %s; Kiddushin 38a on the kin: born and died %s): THE ONE MARKER — the counter moves to %s, %d days walked; the death date a calendar parameter" % (CK_DATES[0][-58:], ES_BIRTH['v'], CLOCK['marker'], CLOCK['days_walked']), ['accepted'])
    if ask == 'i_can_no_more_go_out_and_come_in_you_shall_not_cross':
        ink('31:2', "'I can no more GO OUT AND COME IN; and the LORD has said to me: YOU SHALL NOT CROSS THIS JORDAN' — the leader's phrase (Numbers 27:17's shepherd); 3:27's 'you shall not cross this Jordan' five in order (the twin diffed %d)" % (TWIN['31:2 vs 3:27'],))
        move("cold_run_opening_speech (CALL) — OS.the_commission(the_shepherd) = %s (Numbers 27:17's going out and coming in — plea_made on Moses); OS.the_commission(the_debit) = %s (barred_from_the_land on moses at Numbers 20:12 UNMOVED — the bar's reference; 3:27's plea)" % (OS_SHEP[0][:50], OS_DEBIT[0][:60]), "THE BAR ON MOSES referenced, no second write (barred_from_the_land 2 on the world — Moses' and Aaron's — UNMOVED, DM4); the going out and coming in ended here")
        dat("no write — the bar's reference (moses_besought the tape's kind; plea_made on moses at 3:23-26); barred_from_the_land UNMOVED")
        return out("I can no more go out and come in; you shall not cross this Jordan (31:2) — the shepherd's phrase of Numbers 27:17 ended (opening_speech — %s), 3:27's bar five in order: the bar on Moses referenced, no second write" % (OS_SHEP[0][:30],), ['accepted'])
    if ask == 'the_lord_your_god_crosses_before_you_and_joshua':
        ink('31:3', "'THE LORD YOUR GOD, HE WILL CROSS BEFORE YOU; He will destroy these nations from before you and you shall possess them; JOSHUA, HE SHALL CROSS BEFORE YOU, AS THE LORD HAS SPOKEN' — THE SECOND AS_WHEN POINTER")
        move("cold_run_opening_speech (CALL) — OS.DATA joshuas_charge %s (3:28's 'charge Joshua … he shall cross before this people' — moses_besought's answer; joshua_encouraged the tape's line at 3:21-22); OS.the_commission(the_hand_laid) = %s (Numbers 27:18-23's commission the tape's — invested_office on yehoshua); cold_run_seven_nations (CALL) — 7:1-2's ban and 9:3's 'He will destroy them'" % (OS_JC['value']['plene'], OS_HAND[0][:50]), "THE WRITE joshua_to_cross_before_israel — a STATUS on Israel at the marker's day (DM2): the successor's crossing declared to the people; THE POINTER Deut 31:3 'as the LORD has spoken' predicted RUN_CITATION reference — 3:28 and Numbers 27:18-23 behind on the tape")
        dat("THE WRITE joshua_to_cross_before_israel, a STATUS on israel_people at %s; THE POINTER Deut 31:3 AS_WHEN predicted RUN_CITATION; the readback row 31:3 REFERENCE against joshua_encouraged (3:21-22) and joshua_commissioned (Numbers 27:22-23)" % D1)
        return out("the LORD your God crosses before you, and Joshua, as the LORD has spoken (31:3) — the successor's crossing declared; 3:28's charge and Numbers 27:18-23's commission behind on the tape (opening_speech — %s; the pointer a run citation): THE WRITE joshua_to_cross_before_israel, a STATUS on Israel at Moses' last day" % (OS_HAND[0][:30],), ['joshua_to_cross_before_israel'])
    if ask == 'as_he_did_to_sihon_and_og_so_to_the_nations':
        ink('31:4-5', "'and THE LORD WILL DO TO THEM AS HE DID TO SIHON AND TO OG, the kings of the Amorites, and to their land, which He destroyed; and the LORD will deliver them before you and you shall do to them ACCORDING TO ALL THE COMMANDMENT which I have commanded you' — THE THIRD AS_WHEN POINTER; the ban's law")
        move("cold_run_chukat (CALL) — CK.well_and_kings(joshua_refrain) = %s (the refrain born at 21:35 — kings_smitten on sihon and og the tape's; sihon_smitten_land_possessed, og_came_out_and_fear_not the lines); CK.well_and_kings(og_lore) = %s; cold_run_opening_speech (CALL) — OS.sihon_and_og(the_ban) = %s; cold_run_refuge_war_family (CALL) — 20:16-18's ban; cold_run_seven_nations (CALL) — 7:2's" % (CK_REFRAIN[0][:40], CK_OG[0][:40], OS_BAN[0][:40]), "THE WRITE nations_dispossessed_as_sihon_and_og_promised — a conditional HEAVEN entry at the marker's day (DM2): the promise keyed to the tape's own precedent; THE POINTER Deut 31:4 'as He did' predicted RUN_CITATION reference — the kings' lines the tape's own")
        dat("THE WRITE nations_dispossessed_as_sihon_and_og_promised, a HEAVEN entry (conditional) on israel_people at %s; THE POINTER Deut 31:4 AS_WHEN predicted RUN_CITATION; the readback rows 31:4-5 REFERENCE against sihon_smitten_land_possessed and og_came_out_and_fear_not (Numbers 21:24-35) and war_speech_declared (20:1)" % D1)
        return out("as He did to Sihon and to Og, so to the nations (31:4-5) — the tape's own kings' lines the referent (chukat — %s; the refrain of Joshua's book born at 21:35), the ban's law the commandment: THE WRITE nations_dispossessed_as_sihon_and_og_promised, a conditional HEAVEN entry; the pointer a run citation" % (CK_REFRAIN[0][:30],), ['nations_dispossessed_as_sihon_and_og_promised'])
    if ask == 'be_strong_and_of_good_courage_fear_not_he_will_not_forsake_you':
        ink('31:6', "'BE STRONG AND OF GOOD COURAGE, FEAR NOT NOR BE DISMAYED at them, for the LORD your God, He it is who goes with you; HE WILL NOT FAIL YOU NOR FORSAKE YOU' — THE PLURAL IMPERATIVE (%s — 31:6 alone in the Torah; the singular at 31:7 and 31:23); 31:6 and 31:8 each other's kin (the twin diffed %d)" % (P('חזקו', 'ואמצו', books=T), TWIN['31:6 vs 31:8']))
        move("cold_run_refuge_war_family (CALL) — RW.the_priests_speech(hear_israel_the_fourth) = %s (20:3-4's four fears — the war's fear not); cold_run_obey_horeb (CALL) — OH.the_exile_case(the_merciful_god) = %s (4:31's 'He will not fail you'); 1:21's and 3:22's fear not to Israel (opening_speech by CALL)" % (RW_FEAR[0][:50], OH_MERCY[0][:40]), "THE WRITE be_strong_and_courageous_commanded — a STATUS on Israel at the marker's day (DM2); fear_not_promised REUSED at 31:6 ON ISRAEL — the FIFTH entry on the world, the first on Israel's ledger (Isaac's, Jacob's, Moses' at Numbers 21:33-34 and Joshua's at 3:21-22 before it)")
        dat("THE WRITE be_strong_and_courageous_commanded, a STATUS on israel_people at %s; fear_not_promised REUSED at 31:6 on israel_people (4 -> 6 over the sitting with 31:8); the readback row 31:6 REFERENCE against war_speech_declared (20:1)" % D1)
        return out("be strong and of good courage, fear not, He will not forsake you (31:6) — the plural imperative, the war chapter's fear not (refuge_war_family — %s), 4:31's merciful God: THE WRITE be_strong_and_courageous_commanded, a STATUS on Israel; fear_not_promised REUSED on Israel — the first entry on Israel's ledger" % (RW_FEAR[0][:30],), ['be_strong_and_courageous_commanded', 'fear_not_promised'])
    if ask == 'moses_called_joshua_in_the_sight_of_all_israel':
        ink('31:7', "'AND MOSES CALLED JOSHUA and said to him IN THE SIGHT OF ALL ISRAEL: be strong and of good courage' — THE ACT: the public charge; 31:7 and 31:23 ten shared tokens (the twin diffed %d); the singular imperative %s" % (TWIN['31:7 vs 31:23'], P('חזק', 'ואמץ', books=T)))
        move("cold_run_opening_speech (CALL) — joshua_encouraged the tape's line at 3:21-22 ('I commanded Joshua at that time' — the private charge; OS.DATA joshuas_charge %s); Onkelos 31:7 'you shall bring'" % (OS_JC['value']['seen'],), "THE NEW KIND joshua_charged_before_israel — an ACT of Moses on the counter's new day (the subject moses, the addressee yehoshua before Israel); the frame 'called … and said' the act's own")
        dat("THE LINE joshua_charged_before_israel (an ACT) at %s — the readback row 31:7 SUPPLIED with the line's write and REFERENCE against joshua_encouraged (3:21-22)" % D1)
        return out("Moses called Joshua in the sight of all Israel (31:7) — the public charge after 3:21-22's private one (opening_speech — %s), 31:7 and 31:23 ten tokens shared: THE LINE joshua_charged_before_israel, an ACT of Moses at his last day" % (OS_JC['value']['seen'],), ['accepted'])
    if ask == 'be_strong_you_shall_go_with_this_people_into_the_land':
        ink('31:7', "'for YOU SHALL GO WITH THIS PEOPLE INTO THE LAND which the LORD swore to their fathers to give them, and you shall cause them to inherit it' — seven tokens shared with 10:11 (the twin diffed %d) and Joshua 1:6 (%d — the Prophets' seat cited, never read); 'swore' the seven's homograph (%s)" % (TWIN['31:7 vs 10:11'], TWIN['31:7 vs Josh 1:6'], SEVENS_HOMOGRAPHS[2]))
        move("cold_run_second_tablets (CALL) — ST.the_third_forty_and_the_go(the_charge_forward) = %s; ST.DATA the_charge_to_joshua the shared %s ('THE RUN IS JOSHUA' — the install hypothesis on the table); Onkelos 'you shall bring'" % (ST_CHARGE[0][:60], ST_JOSH['value']['the_shared']), "THE WRITE joshua_charged_to_bring_israel_in — a STATUS ON YEHOSHUA (the entity's fifth entry — oral_law_unwritten, plea_made, invested_office at Numbers 27:22-23, fear_not_promised at 3:21-22 before it) at the marker's day (DM2)")
        dat("THE WRITE joshua_charged_to_bring_israel_in, a STATUS on yehoshua at %s; Joshua 1:6's run a pointer AHEAD owed" % D1)
        return out("be strong, you shall go with this people into the land (31:7) — 10:11's charge forward seven tokens shared (second_tablets — %s) and Joshua 1:6's run (a pointer ahead owed): THE WRITE joshua_charged_to_bring_israel_in, a STATUS on Joshua's own ledger" % (ST_CHARGE[0][:30],), ['joshua_charged_to_bring_israel_in'])
    if ask == 'the_lord_goes_before_you_he_will_not_fail_you':
        ink('31:8', "'and THE LORD, HE IT IS WHO GOES BEFORE YOU; He will be with you; HE WILL NOT FAIL YOU NOR FORSAKE YOU; FEAR NOT NOR BE DISMAYED' — 31:6's words to Israel said to Joshua (the twin diffed %d)" % (TWIN['31:6 vs 31:8'],))
        move("cold_run_opening_speech (CALL) — joshua_encouraged 3:21-22's fear_not_promised on yehoshua the first (3:28 'encourage him' the command's seat); Joshua 1:5-6, 1:9 the run (the Prophets' seats cited, never read)", "fear_not_promised REUSED at 31:8 ON YEHOSHUA — the SIXTH entry on the world, the second on his ledger")
        dat("fear_not_promised REUSED at 31:8 on yehoshua (the sixth on the world); the readback row 31:8 SUPPLIED with the reuse")
        return out("the LORD goes before you, He will not fail you, fear not (31:8) — 31:6's words said to Joshua (%d shared), 3:21-22's first promise to him on the tape: fear_not_promised REUSED on Joshua's ledger — the sixth entry on the world" % (TWIN['31:6 vs 31:8'],), ['fear_not_promised'])
    return 'no verdict in span', [], list(P_)
