import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE DEUTERONOMY WALK 20b — THE COMPILE OF CHAPTER 32, THE SONG, LEAN (2026-09-28): THE TYPES BY SCRIPT, part A, at RUN B's head after the probe's FAIL print (7b's lesson 2; Q49 FAIL 48/49):
# event_vocabulary +16 (the SIXTEEN own-day lines IN THREE FORMS — 14 SPEECHES (the song's twelve stanzas: song_witnesses_called_declared 32:1-4; song_crooked_generation_declared 32:5-6;
# song_nations_divided_lords_portion_declared 32:7-9; song_found_in_the_desert_declared 32:10-12; song_heights_honey_rock_declared 32:13-14; song_jeshurun_fat_kicked_declared 32:15-18;
# song_face_hidden_foolish_nation_declared 32:19-22; song_evils_heaped_declared 32:23-25; song_enemys_boast_declared 32:26-28; song_one_chasing_a_thousand_declared 32:29-33;
# song_vengeance_in_store_declared 32:34-38; song_i_am_he_declared 32:39-43; and the LORD's two to Moses — nebo_summons_die_as_aaron 32:48-50, meribah_trespass_not_go_there_declared 32:51-52),
# 1 ACT (song_spoken_by_moses_and_hoshea 32:44-45) and 1 STATUTE (set_your_heart_no_empty_matter_declared 32:46-47) — EVERY LINE AT MOSES' LAST DAY (40, 12, 7) after 19b's ONE MARKER at 31:1:
# NO MARKER HERE); effect_vocabulary +42 (thirty-two STATUSES, no BLOCK, ten HEAVEN entries on three ledgers — Israel 36, Moses 5, Joshua 1 (the entity yehoshua) — the names the SPEC MODULE
# ch32b_spec.py fixed at the design); THE THREE REUSED ROWS AMENDED with their further seats (heaven_and_earth_witness 32:1 the fifth — the chain's fifth seat; face_hidden_and_forsaken_foretold
# 32:20 the second — the hidden face the third time; length_of_days_on_the_land_promised 32:47 the second; the references never rewritten). Every value the shelf's own words; the `he` FOUND in
# the verse (PHRASE — one hit or the script refuses; the plain tokens typed from the store's own print ch32_store_glosses.txt at RUN B's head); the forty-two names ASSERTED ABSENT before (the
# holes). add_types_ch29_a.py's form (its helpers exec'd by content markers from the forms folder); assembled from four parts; the names READ from the spec module beside this file. RUN FROM THE REPO ROOT.
import re, sqlite3, yaml, subprocess, sys, os
ROOT = _ROOT
SP = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, SP)
import ch32b_spec as S
CHECK = '--check' in sys.argv
SRC12 = open(f'{ROOT}/World/step9/forms_deuteronomy_walk/add_types_ch12.py', encoding='utf-8').read()
_a = SRC12.index('db = sqlite3.connect(f"file:{ROOT}/Data/tanakh.sqlite?mode=ro", uri=True)'); _b = SRC12.index("unit = open(f'{ROOT}/logic/units/deu_12_place_name.yaml'")
exec(SRC12[_a:_b])   # the helpers: words, pv, pl, PV, LV, PHRASE, q, HE, WIT (10b's form, by content markers)
U = {u: open(f'{ROOT}/logic/units/{u}.yaml', encoding='utf-8').read() for u in S.UNITS}
CL = {u: sorted(set(re.findall(S.UNITS[u] + r'-\d+', U[u]))) for u in U}; ST = {u: sorted({int(x) for x in re.findall(r'STEP_Dt_%d_(\d+)' % int(S.UNITS[u][2:4]), U[u])}) for u in U}
assert {u: len(CL[u]) for u in CL} == {'deu_32_haazinu': 12, 'deu_32_song_aftermath': 4}, CL
assert {u: (ST[u][0], ST[u][-1]) for u in ST} == {'deu_32_haazinu': (1, 43), 'deu_32_song_aftermath': (44, 52)}, {u: (ST[u][:2], ST[u][-1]) for u in ST}
led = open(f'{ROOT}/logic/oral_triage/deu_32_haazinu_2026-09-27.md', encoding='utf-8').read()
N_SRC = len(re.findall(r'^- (?:Onkelos|Sifrei)', led, re.M)); N_ONK = len(re.findall(r'^- Onkelos', led, re.M))
N_EX = len(re.findall(r'^- Sifrei Devarim [\d:]+ — EXCLUDED', led, re.M)); assert '**read: 312 of 312 — COMPLETE**' in led, 'the ledger\'s own coverage line'
PISK = [int(p) for p in re.findall(r'^- Sifrei Devarim (\d+):\d+', led, re.M)]
N_SPINE = sum(1 for p in PISK if 306 <= p <= 341); OUTSIDE = sorted({p for p in PISK if not 306 <= p <= 341}); N_OUT = sum(1 for p in PISK if not 306 <= p <= 341)
assert N_SRC == 312 and N_ONK == 52 and N_EX == 0 and N_SPINE == 249 and N_OUT == 11, (N_SRC, N_ONK, N_EX, N_SPINE, N_OUT)   # the counts read from the ledger's own print at RUN B's head
CORPUS = S.CORPUS
SUB = "submitted by cold_run_song_charge_nebo.py [subjects: %s] (the narrative scene, THE DEUTERONOMY WALK 20b — LEAN); re-submitted on the sequential tape by cold_run_sequence.py; consumed by law_song_charge_nebo (cold_run_song_charge_nebo.py) -> %s"
INK = ("Deut 32:1-52; Onkelos Deut 32:1-52 (the export's chapter the DB's; %d rows); the Sifrei on Deuteronomy IN FORCE — piskaot 306-341, the thirty-six piskaot on the song read whole (%d rows, the export's longest piska 306 among them); "
       "the %d rows elsewhere citing the chapter read whole (piskaot %s); the reading's ledger logic/oral_triage/deu_32_haazinu_2026-09-27.md (312 of 312 read, computed)" % (N_ONK, N_SPINE, N_OUT, ', '.join(str(p) for p in OUTSIDE)))
D, X, N_, L_, G_, J_, PS, IS = 'Deut', 'Exod', 'Num', 'Lev', 'Gen', 'Josh', 'Ps', 'Isa'
MOSES = 'moses (the song — to israel; from 32:20 the LORD\'s own words inside it)'; GOD = 'the LORD (to moses)'
DAY1 = "at Moses' last day (40, 12, 7) — 19b's ONE MARKER at 31:1 (the number's verse 31:2); NO MARKER in this chapter, 32:48's selfsame day THAT day"
# THE KINDS' TEXTS — en, the first verse's English (the he found beside it), the kin witnesses, the speaker, the tape clause; the names, verses, forms and fields the spec's
KEN = {}
KEN['song_witnesses_called_declared'] = (
 "the witnesses called and the Rock declared — 'GIVE EAR, O HEAVENS, AND I WILL SPEAK, AND LET THE EARTH HEAR the words of my mouth; MY DOCTRINE SHALL DROP AS THE RAIN, my speech distil as the dew, as the small rain upon the tender grass and as the showers upon the herb; for I WILL PROCLAIM THE NAME OF THE LORD — ASCRIBE GREATNESS TO OUR GOD; THE ROCK, HIS WORK IS PERFECT, for all His ways are justice, a God of faithfulness and without iniquity, just and right is He' (Deut 32:1-4) — the song's opening: the heavens and the earth summoned a fifth time (4:26, 30:19, 31:28, 32:1 — obey_horeb's chain), the court law read into them by the spine thrice, the four rains words of Torah, the Name after twenty-one words and the response (Berakhot 7:1), the Rock rendered the Mighty One (Onkelos); " + DAY1,
 "give ear, O heavens, and I will speak; and let the earth hear the words of my mouth", [WIT(D, 4, 26, 26), WIT(D, 31, 28, 28), WIT(N_, 35, 30, 30), WIT(IS, 1, 2, 2)], MOSES,
 "doctrine_as_rain_and_dew_likened, name_of_the_lord_proclaimed_greatness_ascribed, the_rock_perfect_and_just_declared on israel_people (STATUSES); heaven_and_earth_witness REUSED at 32:1 (the fifth entry — the chain's fifth seat); " + DAY1)
KEN['song_crooked_generation_declared'] = (
 "the crooked generation declared — 'IS CORRUPTION HIS? NO — HIS CHILDREN'S IS THE BLEMISH, A PERVERSE AND CROOKED GENERATION; DO YOU THUS REQUITE THE LORD, O FOOLISH PEOPLE AND UNWISE? IS HE NOT YOUR FATHER WHO ACQUIRED YOU? He made you and established you' (Deut 32:5-6) — the broken syntax made a sentence by Onkelos (they corrupted themselves, the children who served idols); 'a perverse and crooked generation' once in the Bible (Sotah 1:7 — the measure for measure at 308:4); the five acquisitions (Avot 6:10 at 309:6); " + DAY1,
 "is corruption His? no — His children's is the blemish; a perverse and crooked generation", [WIT(D, 14, 1, 1), WIT(X, 15, 16, 16), WIT(G_, 14, 19, 19)], MOSES,
 "generation_crooked_not_his_children, father_who_acquired_you_requited on israel_people (STATUSES); " + DAY1)
KEN['song_nations_divided_lords_portion_declared'] = (
 "the nations divided and the LORD's portion declared — 'REMEMBER THE DAYS OF OLD, consider the years of many generations; ASK YOUR FATHER and he will tell you, YOUR ELDERS and they will say it to you; WHEN THE MOST HIGH GAVE THE NATIONS THEIR INHERITANCE, WHEN HE SEPARATED THE SONS OF MAN, HE SET THE BORDERS OF THE PEOPLES BY THE NUMBER OF THE CHILDREN OF ISRAEL; for THE LORD'S PORTION IS HIS PEOPLE, JACOB THE LOT OF HIS INHERITANCE' (Deut 32:7-9) — the tradition's own warrant (the fathers and the elders the channel); no numeral in the verse, the spine's seventy against Jacob's seventy souls (Genesis 46:27 by CALL); Genesis 11's division the tape's own entries (primeval by CALL — a REFERENCE by the ink's words, the twin a labeled HYPOTHESIS); the portion a NEW status beside the tape's treasured people; " + DAY1,
 "remember the days of old, consider the years of many generations; ask your father and he will tell you, your elders and they will say it to you", [WIT(G_, 11, 8, 8), WIT(G_, 10, 25, 25), WIT(X, 19, 5, 5), WIT(D, 4, 19, 19)], MOSES,
 "days_of_old_remember_commanded, nations_bounds_set_by_number_of_israel, lords_portion_his_people_jacob on israel_people (STATUSES); " + DAY1)
KEN['song_found_in_the_desert_declared'] = (
 "found in the desert declared — 'HE FOUND HIM IN A DESERT LAND, and in the waste, the howling wilderness; HE COMPASSED HIM ABOUT, HE CARED FOR HIM, HE KEPT HIM AS THE APPLE OF HIS EYE; AS AN EAGLE STIRS UP HER NEST, hovers over her young, spreads her wings, takes them, bears them on her pinions — THE LORD ALONE LED HIM, AND THERE WAS NO STRANGE GOD WITH HIM' (Deut 32:10-12) — the desert the Torah's school (Onkelos at its fullest; the Sifrei 313); the tape's own lines RUN CITATIONS by kind (the manna, the water from the rock, the cloud and the well — exodus_story, beha, good_land by CALL); the camp's twelve mil (Tosefta Arakhin 1:4 at 313:9 — a parameter); Exodus 19:4's eagle the twin TAUGHT at 314:3; 'alone' with Numbers 23:9 (balak by CALL); Onkelos's world to come a DATA note; " + DAY1,
 "He found him in a desert land, and in the waste, the howling wilderness; He compassed him about, He cared for him, He kept him as the apple of His eye", [WIT(X, 19, 4, 4), WIT(X, 16, 14, 15), WIT(X, 17, 6, 6), WIT(N_, 23, 9, 9)], MOSES,
 "found_in_the_desert_encircled_and_kept, apple_of_his_eye_kept, as_an_eagle_stirring_its_nest_borne, the_lord_alone_led_no_foreign_god on israel_people (STATUSES); " + DAY1)
KEN['song_heights_honey_rock_declared'] = (
 "the heights and the feast declared — 'HE MADE HIM RIDE ON THE HIGH PLACES OF THE EARTH, and he ate the fruitage of the field; HE MADE HIM SUCK HONEY OUT OF THE CRAG AND OIL OUT OF THE FLINTY ROCK; CURD OF KINE AND MILK OF SHEEP, with FAT OF LAMBS AND RAMS OF BASHAN and he-goats, with the kidney-fat of wheat; and of THE BLOOD OF THE GRAPE YOU DRANK foaming wine' (Deut 32:13-14) — the store's one mismatch (the qere beside the ketiv at 32:13 — the readback row VARIANT); the flint's five seats (good_land's two rocks by CALL); the feast DATED AND DIVIDED by the spine 317:2-6 (the altar's classes and the Torah's forms — Kilayim 3:2 and Peah 3:2 the cases at 317:6); the land's bounty AHEAD of the tape (Joshua's book cited never read — the readback marks it FORWARD); " + DAY1,
 "He made him ride on the high places of the earth, and he ate the fruitage of the field; and He made him suck honey out of the crag and oil out of the flinty rock", [WIT(D, 8, 15, 15), WIT(D, 8, 8, 8), WIT(D, 3, 1, 1)], MOSES,
 "heights_of_the_land_ridden_honey_from_the_rock, feast_of_curd_milk_fat_and_wine_given on israel_people (STATUSES); " + DAY1)
KEN['song_jeshurun_fat_kicked_declared'] = (
 "Jeshurun fat and the demons declared — 'BUT JESHURUN GREW FAT AND KICKED — YOU GREW FAT, YOU GREW THICK, YOU BECAME GROSS — and HE FORSOOK GOD WHO MADE HIM AND CONTEMNED THE ROCK OF HIS SALVATION; THEY ROUSED HIM TO JEALOUSY WITH STRANGE GODS, with abominations they provoked Him; THEY SACRIFICED TO DEMONS, NO-GODS, GODS THEY KNEW NOT, NEW ONES THAT CAME UP OF LATE, which your fathers dreaded not; OF THE ROCK THAT BEGOT YOU YOU WERE UNMINDFUL, AND FORGOT GOD WHO BORE YOU' (Deut 32:15-18) — THE FALSE EIGHT at 32:15 ('you grew fat', shamanta — the parser's eight a verb, guarded: Onkelos 'you prospered', the Sifrei 318:4-5 dated); 31:20's satiety the twin TAUGHT at 318:1 (covenant_return_charge by CALL); Onkelos's rule across the four verses — the fear forgotten, the service forsaken, never God Himself; 'gods they knew not' 29:25's kin, 13:7's inciter (seducers by CALL); " + DAY1,
 "but Jeshurun grew fat and kicked — you grew fat, you grew thick, you became gross — and he forsook God who made him and contemned the Rock of his salvation", [WIT(D, 31, 20, 20), WIT(D, 29, 25, 25), WIT(D, 13, 7, 7), WIT(D, 8, 12, 14)], MOSES,
 "jeshurun_fat_kicked_forsook_god, demons_and_new_gods_sacrificed, rock_that_begot_you_forgotten on israel_people (STATUSES — worded from the Aramaic); " + DAY1)
KEN['song_face_hidden_foolish_nation_declared'] = (
 "the hidden face and the foolish nation declared — 'AND THE LORD SAW AND SPURNED, from the provoking of His sons and His daughters; and He said: I WILL HIDE MY FACE FROM THEM, I WILL SEE WHAT THEIR END SHALL BE, for they are a perverse generation, children in whom is no faithfulness; THEY HAVE ROUSED ME TO JEALOUSY WITH A NO-GOD, provoked Me with their vanities — AND I WILL ROUSE THEM TO JEALOUSY WITH A NO-PEOPLE, WITH A VILE NATION I WILL PROVOKE THEM; FOR A FIRE IS KINDLED IN MY NOSTRIL AND BURNS TO THE DEPTHS OF SHEOL, devours the earth and her produce, sets ablaze the foundations of the mountains' (Deut 32:19-22) — the narrative form opens the song's second movement; THE HIDDEN FACE THE THIRD TIME (31:17, 31:18, 32:20 — Onkelos 'I will remove My Shekhinah', the spine speaking Onkelos's words at 320:3): face_hidden_and_forsaken_foretold REUSED; the measure for measure (32:6's foolish people answered by the foolish nation — 28:49's eagle nation the compiled kin); Onkelos: no fire in God's nostril; " + DAY1,
 "and the LORD saw and spurned, from the provoking of His sons and His daughters", [WIT(D, 31, 17, 18), WIT(D, 28, 49, 49), WIT(D, 8, 16, 16)], MOSES,
 "jealousy_by_no_people_foolish_nation, fire_kindled_to_the_lowest_sheol on israel_people (HEAVEN entries — the song's foretellings); face_hidden_and_forsaken_foretold REUSED at 32:20 (the second entry — the third seat of the hidden face); " + DAY1)
KEN['song_evils_heaped_declared'] = (
 "the evils heaped declared — 'I WILL HEAP EVILS UPON THEM, I WILL SPEND MY ARROWS UPON THEM: THE WASTING OF HUNGER, THE DEVOURING OF THE FIERY BOLT AND BITTER DESTRUCTION; THE TEETH OF BEASTS I WILL SEND UPON THEM, WITH THE VENOM OF CRAWLING THINGS OF THE DUST; WITHOUT THE SWORD SHALL BEREAVE, AND IN THE CHAMBERS TERROR — the young man and the virgin, the suckling with the man of gray hairs' (Deut 32:23-25) — the Sifrei 43:24's outside row (My arrows are spent and they are not spent — the promise inside the curse); Onkelos the arrows plagues (28:59-61's blows on the tape); Leviticus 26:22's beasts the twin BY SENSE (a HYPOTHESIS — tochacha by CALL a REFERENCE by the ink's shared words); THE RULE OF WAR AND FAMINE (321:9 — the sword without, gather within; terror in the chambers, go out: a parameter, Bava Kamma 60b owed); " + DAY1,
 "I will heap evils upon them, I will spend My arrows upon them", [WIT(L_, 26, 22, 22), WIT(L_, 26, 25, 25), WIT(D, 28, 53, 53), WIT(N_, 21, 6, 6)], MOSES,
 "evils_heaped_arrows_spent, hunger_beasts_serpents_sword_terror_sent on israel_people (HEAVEN entries); " + DAY1)
KEN['song_enemys_boast_declared'] = (
 "the enemy's boast declared — 'I SAID: I WOULD MAKE AN END OF THEM, I WOULD MAKE THEIR MEMORY CEASE FROM AMONG MEN — WERE IT NOT THAT I DREADED THE ENEMY'S PROVOCATION, lest their adversaries misjudge, LEST THEY SAY: OUR HAND IS EXALTED, and not the LORD has wrought all this; FOR THEY ARE A NATION VOID OF COUNSEL, AND THERE IS NO UNDERSTANDING IN THEM' (Deut 32:26-28) — THE DECREE NOT CARRIED OUT (a counterfactual — no write of the blotting); 9:28's 'lest they say' the kin (not_righteousness by CALL), Exodus 32:12's and Numbers 14:16's the tape's own arguments (erection, shelach by CALL); the two readings of counsel (322:8-11 — Israel's Torah, the nations' seven commandments: Tosefta Avodah Zarah 9:4 THE CASE, pre_sinai by CALL); Gittin 56b owed; " + DAY1,
 "I said: I would make an end of them, I would make their memory cease from among men", [WIT(D, 9, 28, 28), WIT(X, 32, 12, 12), WIT(N_, 14, 16, 16), WIT(G_, 9, 4, 6)], MOSES,
 "blotting_out_stayed_by_the_enemys_boast on israel_people (a HEAVEN entry — the reason clause the decree's stay), nation_void_of_counsel on israel_people (a STATUS — the spine's first reading, the second recorded); " + DAY1)
KEN['song_one_chasing_a_thousand_declared'] = (
 "one chasing a thousand and the vine of Sodom declared — 'IF THEY WERE WISE THEY WOULD UNDERSTAND THIS, they would discern their latter end; HOW SHOULD ONE CHASE A THOUSAND, AND TWO PUT TEN THOUSAND TO FLIGHT, EXCEPT THEIR ROCK HAD SOLD THEM, AND THE LORD HAD DELIVERED THEM UP? FOR THEIR ROCK IS NOT AS OUR ROCK, AND OUR ENEMIES ARE JUDGES; FOR THEIR VINE IS OF THE VINE OF SODOM, and of the fields of Gomorrah; THEIR GRAPES ARE GRAPES OF GALL, their clusters are bitter; THEIR WINE IS THE VENOM OF SERPENTS, and the cruel poison of asps' (Deut 32:29-33) — THE JOINED THOUSAND at 32:30 (the parser's [1, 1002] — the Sifrei 322:10 reads the four numbers aloud, 322:12 the arithmetic: a proverb, no count; the DATA row); THE STATE ROW at 32:30 (323:5 — the Torah done, one chases a thousand: Leviticus 26:8 and 28:7; undone, the reversal 28:25); THE ENEMY NEITHER WITNESS NOR JUDGE (Numbers 35:23 — Mishnah Sanhedrin 3:5 the case; refuge by CALL); 'judges' Exodus 21:22's pelilim (ordinances by CALL); Sodom the tape's Genesis 19 (mamre by CALL); Sotah 9:9's clusters ceased; " + DAY1,
 "if they were wise they would understand this, they would discern their latter end", [WIT(L_, 26, 8, 8), WIT(D, 28, 7, 7), WIT(D, 28, 25, 25), WIT(N_, 35, 23, 23), WIT(X, 21, 22, 22), WIT(J_, 23, 10, 10)], MOSES,
 "one_chasing_a_thousand_rock_sold_them, vine_of_sodom_gall_grapes on israel_people (STATUSES); THE STATE ROW at 32:30; " + DAY1)
KEN['song_vengeance_in_store_declared'] = (
 "the cup in store and the vengeance declared — 'IS NOT THIS LAID UP IN STORE WITH ME, SEALED UP IN MY TREASURIES? VENGEANCE IS MINE, AND RECOMPENSE, AT THE TIME WHEN THEIR FOOT SHALL SLIP; for the day of their calamity is at hand, and the things to come upon them shall make haste; FOR THE LORD WILL JUDGE HIS PEOPLE, AND REPENT HIMSELF FOR HIS SERVANTS, when He sees that their stay is gone and there is none remaining, shut up or left at large; and He will say: WHERE ARE THEIR GODS, THE ROCK IN WHOM THEY TRUSTED, who ate the fat of their sacrifices and drank the wine of their libation? let them rise up and help you, let them be your protection' (Deut 32:34-38) — Onkelos's day of judgment (the translator's second eschatology, a DATA note); THE FRUIT OF DEEDS (324:2 — Tosefta Peah 1:1-3 THE CASES); the song's first vengeance (the foot's slip the exile in Onkelos); 32:36 quoted whole in Psalm 135:14 (the Writings' seat cited never read); 328's misprinted head (32:38's words under a marker reading 32:35 — the rows seated by their own words); THE NAME PROFANED PUNISHED AT ONCE (328:4 — a rule from the verse, Yoma 86a owed); " + DAY1,
 "is not this laid up in store with Me, sealed up in My treasuries?", [WIT(PS, 135, 14, 14), WIT(D, 28, 59, 61), WIT(N_, 28, 7, 7)], MOSES,
 "vengeance_laid_up_in_store_sealed, lord_judges_his_people_repents_himself on israel_people (HEAVEN entries), where_are_their_gods_asked on israel_people (a STATUS); " + DAY1)
KEN['song_i_am_he_declared'] = (
 "I am He and the land atones declared — 'SEE NOW THAT I, EVEN I, AM HE, AND THERE IS NO GOD WITH ME; I KILL AND I MAKE ALIVE, I HAVE WOUNDED AND I HEAL, AND THERE IS NONE THAT CAN DELIVER OUT OF MY HAND; FOR I LIFT UP MY HAND TO HEAVEN AND SAY: AS I LIVE FOREVER — IF I WHET MY GLITTERING SWORD, and My hand take hold on judgment, I WILL RENDER VENGEANCE TO MY ADVERSARIES, and will recompense those who hate Me; I will make My arrows drunk with blood, My sword shall devour flesh; SING ALOUD, O NATIONS, OF HIS PEOPLE, FOR HE AVENGES THE BLOOD OF HIS SERVANTS, renders vengeance to His adversaries, AND MAKES EXPIATION FOR THE LAND OF HIS PEOPLE' (Deut 32:39-43) — the song's creed (6:4's unity reaffirmed — hear_o_israel by CALL; the seven blank 'I' glosses patched by reference at the reading's tail); no father delivers a son, the soul beyond ransom (329:4 — Exodus 21:30's kofer, ordinances and incense_shekel by CALL); the oath by God's own life; the second and third vengeances; THE LAND ATONES (333:4 — Mishnah Berakhot 1:1 the case: the Shema morning and evening; Numbers 35:33's atonement by the shedder's blood, refuge by CALL); the unit deu_32_haazinu closes; " + DAY1,
 "see now that I, even I, am He, and there is no god with Me; I kill and I make alive, I have wounded and I heal, and there is none that can deliver out of My hand", [WIT(D, 6, 4, 4), WIT(X, 21, 30, 30), WIT(N_, 35, 31, 33), WIT(D, 21, 8, 8)], MOSES,
 "i_i_am_he_no_god_beside_me, i_kill_and_make_alive_none_delivers, hand_lifted_to_heaven_live_forever_sworn on israel_people (STATUSES), sword_whetted_vengeance_rendered, nations_sing_with_his_people_land_atones on israel_people (HEAVEN entries); " + DAY1)
KEN['song_spoken_by_moses_and_hoshea'] = (
 "the song spoken by Moses and Hoshea (an ACT) — 'AND MOSES CAME AND SPOKE ALL THE WORDS OF THIS SONG IN THE EARS OF THE PEOPLE, HE AND HOSHEA THE SON OF NUN; AND WHEN MOSES MADE AN END OF SPEAKING ALL THESE WORDS TO ALL ISRAEL' (Deut 32:44-45) — THE FRAME OPENS (the second unit): the song spoken TWICE — 31:30's speaking on the tape (covenant_return_charge's line by CALL) and 32:44's coming: 334:1 sets 31:1's 'went' against 32:44's 'came' — THE SUCCESSOR'S COMING, a second act (the spine's own move); THE OLD NAME KEPT (334:3 — Hoshea of Numbers 13:16 by CALL to shelach: the same man; Tosefta Berakhot 1:15 on the callee's row); 'in the ears of the people' with Exodus 11:2 and 24:7; Onkelos THIS PRAISE; " + DAY1,
 "and Moses came and spoke all the words of this song in the ears of the people, he and Hoshea the son of Nun", [WIT(D, 31, 30, 30), WIT(D, 31, 1, 1), WIT(N_, 13, 16, 16), WIT(X, 24, 7, 7)], 'moses (with hoshea — to israel)',
 "song_spoken_in_the_ears_of_the_people on israel_people (a STATUS), hoshea_speaks_the_song_beside_moses on yehoshua (a STATUS — his ledger's ninth entry); " + DAY1)
KEN['set_your_heart_no_empty_matter_declared'] = (
 "set your heart, no empty matter declared (the STATUTE) — 'SET YOUR HEART TO ALL THE WORDS WHICH I TESTIFY AGAINST YOU THIS DAY, THAT YOU MAY COMMAND YOUR CHILDREN TO OBSERVE TO DO ALL THE WORDS OF THIS LAW; FOR IT IS NO VAIN THING FOR YOU, BECAUSE IT IS YOUR LIFE, AND THROUGH THIS THING YOU SHALL PROLONG YOUR DAYS ON THE LAND which you cross the Jordan to possess' (Deut 32:46-47) — the charge after the song: 'set your heart' here and Haggai thrice; the witness verb of the chain; 31:12's six words in order (the hakhel's children by CALL); MISHNAH CHAGIGAH 1:8 THE CASE at 335:1 (the mountains by a hair) and MISHNAH PEAH 1:1 INSIDE THE SPINE at 336:2 (the things without measure, the nest added — 18b's own row by CALL); the Sifrei 48:2, 48:10 — the thing you call empty is your life; 11:9's five in order — length_of_days_on_the_land_promised REUSED; " + DAY1,
 "set your heart to all the words which I testify against you this day, that you may command your children to observe to do all the words of this law", [WIT(D, 31, 12, 13), WIT(D, 6, 7, 7), WIT(D, 11, 9, 9), WIT(D, 30, 20, 20)], 'moses (to israel)',
 "set_your_heart_to_these_words_commanded, it_is_your_life_no_empty_matter on israel_people (STATUSES); length_of_days_on_the_land_promised REUSED at 32:47 (the second entry — 30:20's the first); " + DAY1)
KEN['nebo_summons_die_as_aaron'] = (
 "the summons to Nebo, to die as Aaron died (a SPEECH of the LORD) — 'AND THE LORD SPOKE TO MOSES THAT SELFSAME DAY, saying: GO UP INTO THIS MOUNTAIN OF ABARIM, MOUNT NEBO, which is in the land of Moab, that is over against Jericho, AND BEHOLD THE LAND OF CANAAN which I give to the children of Israel for a possession; AND DIE IN THE MOUNT WHERE YOU GO UP, AND BE GATHERED TO YOUR PEOPLE, AS AARON YOUR BROTHER DIED IN MOUNT HOR AND WAS GATHERED TO HIS PEOPLE' (Deut 32:48-50) — the divine frame once in the chapter; 'the selfsame day' the eleventh in the Torah, THE MEASURE'S KIN TAUGHT at 337:1 (the flood's boarding Genesis 7:13, the exodus Exodus 12:41 — primeval, exodus_story by CALL); NO MARKER — the day 19b's (40, 12, 7); Numbers 27:12's five in order, ten tokens shared — THE COMMISSION'S MOUNTAIN (opening_speech by CALL: one mountain, three names; the debit OPEN to 34:1-4); the death commanded, the death itself 34:5's event AHEAD (the three gifts' daemon owed there); AARON'S DEATH THE RECEIPT (339:3 — the tape's Numbers 20:28 by CALL to chukat, journeys, second_tablets; a retelling never writes an act twice); Avot 5:6's twilight creations (Moses' grave); " + DAY1,
 "and the LORD spoke to Moses that selfsame day, saying", [WIT(N_, 27, 12, 14), WIT(N_, 20, 28, 28), WIT(N_, 33, 38, 38), WIT(G_, 7, 13, 13), WIT(X, 12, 41, 41)], GOD,
 "go_up_to_nebo_see_the_land_commanded, die_in_the_mountain_gathered_to_your_people_commanded, as_aaron_died_in_hor_and_was_gathered on moses (STATUSES); " + DAY1)
KEN['meribah_trespass_not_go_there_declared'] = (
 "Meribah's trespass and the seeing declared (a SPEECH of the LORD) — 'BECAUSE YOU TRESPASSED AGAINST ME in the midst of the children of Israel AT THE WATERS OF MERIBATH-KADESH, IN THE WILDERNESS OF ZIN; BECAUSE YOU DID NOT SANCTIFY ME IN THE MIDST OF THE CHILDREN OF ISRAEL — FOR YOU SHALL SEE THE LAND BEFORE YOU, BUT THERE YOU SHALL NOT GO, into the land which I give to the children of Israel' (Deut 32:51-52) — the plural of Numbers 20:12 (Moses and Aaron both); Numbers 27:14's four in order; Meribath-kadesh here, 27:14 and Ezekiel 48:28 alone; THE REASON — Numbers 20:12's sentence read back (chukat.meribah by CALL — barred_from_the_land on Moses OPEN since 20:12, read not rewritten; 340:1 'you caused them' thrice: RUN CITATIONS); 34:4's 'there you shall not cross' AHEAD (341:1 and 357:27 — the four denials; cited never read, READ THEN COMPILE PER PORTION); Onkelos: you dealt falsely with My Word, the strife of Rekem; THE CHAPTER'S CLOSE; " + DAY1,
 "because you trespassed against Me in the midst of the children of Israel at the waters of Meribath-kadesh, in the wilderness of Zin; because you did not sanctify Me in the midst of the children of Israel", [WIT(N_, 20, 12, 13), WIT(N_, 27, 14, 14), WIT(D, 3, 27, 27), WIT(D, 1, 37, 37)], GOD,
 "trespassed_at_meribath_kadesh_not_sanctified on moses (a STATUS — the sentence's second citing), see_the_land_from_afar_not_go_there on moses (a HEAVEN entry — the seeing granted, the entering denied); " + DAY1)
assert set(KEN) == set(S.KINDS) and len(KEN) == 16, set(S.KINDS) ^ set(KEN)
