_FV = dict(FACTS_PRINT)
assert repr(_FV['SC_DEATH'])[:60] == "{'the_command': 'Deut 32:50 — die in the mount and be gather", ('SC_DEATH', repr(_FV['SC_DEATH'])[:100])
assert repr(_FV['SC_RB'])[:60] == "[{'verses': 'Deut 32:1', 'told': 'give ear, O heavens, and I", ('SC_RB', repr(_FV['SC_RB'])[:100])
assert repr(_FV['SC_AARON'])[:60] == "{'the_tape': 'Numbers 20:28 — garments_transferred_and_aaron", ('SC_AARON', repr(_FV['SC_AARON'])[:100])
assert repr(_FV['SC_GOUP'])[:60] == '"go up into this mountain of Abarim, Mount Nebo, and behold ', ('SC_GOUP', repr(_FV['SC_GOUP'])[:100])
assert repr(_FV['SC_NEBO'])[:60] == '"die in the mount where you go up, and be gathered to your p', ('SC_NEBO', repr(_FV['SC_NEBO'])[:100])
assert repr(_FV['SC_ASAARON'])[:60] == '"as Aaron your brother died in Mount Hor and was gathered to', ('SC_ASAARON', repr(_FV['SC_ASAARON'])[:100])
assert repr(_FV['SC_DENIAL'])[:60] == '"you shall see the land before you, but there you shall not ', ('SC_DENIAL', repr(_FV['SC_DENIAL'])[:100])
assert repr(_FV['SC_TABLE'])[:60] == "'the readback table (32:1-52) — 52 rows one per verse, SHORT", ('SC_TABLE', repr(_FV['SC_TABLE'])[:100])
assert repr(_FV['CR_120'])[:60] == '"a hundred and twenty years old this day (31:2) — the parser', ('CR_120', repr(_FV['CR_120'])[:100])
assert repr(_FV['CR_CALLED'])[:60] == '"Moses called Joshua in the sight of all Israel (31:7) — the', ('CR_CALLED', repr(_FV['CR_CALLED'])[:100])
assert repr(_FV['CR_COMM'])[:60] == '"He commissioned Joshua: be strong and of good courage (31:2', ('CR_COMM', repr(_FV['CR_COMM'])[:100])
assert repr(_FV['CR_BRING'])[:60] == '"you shall bring the children of Israel into the land I swor', ('CR_BRING', repr(_FV['CR_BRING'])[:100])
assert repr(_FV['CR_SLEEP'])[:60] == '"you shall sleep with your fathers (31:16) — the death\'s sec', ('CR_SLEEP', repr(_FV['CR_SLEEP'])[:100])
assert repr(_FV['CR_AFTER'])[:60] == '"after my death you will corrupt and turn, evil will befall ', ('CR_AFTER', repr(_FV['CR_AFTER'])[:100])
assert repr(_FV['CR_DEATH'])[:60] == '"THE SEVENTH OF ADAR OF THE FORTIETH YEAR — the year the ink', ('CR_DEATH', repr(_FV['CR_DEATH'])[:100])
assert repr(_FV['CR_GIFTS'])[:60] == '"THREE GIFTS BY THREE MERITS — the well by Miriam\'s, the pil', ('CR_GIFTS', repr(_FV['CR_GIFTS'])[:100])
assert repr(_FV['BL_GRAVE'])[:60] == '{\'the_verse\': \'Deut 33:21\', \'the_teaching\': "Onkelos 33:21 —', ('BL_GRAVE', repr(_FV['BL_GRAVE'])[:100])
assert repr(_FV['BL_CHAIN'])[:60] == "'Moses received the Torah from Sinai and handed it to Joshua", ('BL_CHAIN', repr(_FV['BL_CHAIN'])[:100])
assert repr(_FV['BL_AHEAD'])[:60] == '{\'forward\': ["Deut 34:6 — Moses\' grave in Gad\'s portion (33:', ('BL_AHEAD', repr(_FV['BL_AHEAD'])[:100])
assert repr(_FV['BL_LAW'])[:60] == "'Moses commanded us a law, the inheritance of the congregati", ('BL_LAW', repr(_FV['BL_LAW'])[:100])
assert repr(_FV['BL_PORTION'])[:60] == '"he chose a first part, for there a portion of a ruler was r', ('BL_PORTION', repr(_FV['BL_PORTION'])[:100])
assert repr(_FV['GR_GRAVE'])[:60] == "'reubens_nebo_gads_field'", ('GR_GRAVE', repr(_FV['GR_GRAVE'])[:100])
assert repr(_FV['GR_CEASED'])[:60] == '(40, 5, 15)', ('GR_CEASED', repr(_FV['GR_CEASED'])[:100])
assert repr(_FV['GR_CITY'])[:60] == '"Nebo Reuben\'s (32:37-38) — Moses died in Reuben\'s portion (', ('GR_CITY', repr(_FV['GR_CITY'])[:100])
assert repr(_FV['CK_DATES'])[:60] == "'Aaron (40, 5, 1) by the ink, aged 123; Miriam the tenth of ", ('CK_DATES', repr(_FV['CK_DATES'])[:100])
assert repr(_FV['CK_SUCC'])[:60] == "'the garments to Eleazar and the office with them — Exod 29:", ('CK_SUCC', repr(_FV['CK_SUCC'])[:100])
assert repr(_FV['CK_THIRTY'])[:60] == '"thirty days\' weeping by all the house of Israel — a timer d', ('CK_THIRTY', repr(_FV['CK_THIRTY'])[:100])
assert repr(_FV['CK_AGE'])[:60] == "'Aaron 123 at his death (33:39 — [123])'", ('CK_AGE', repr(_FV['CK_AGE'])[:100])
assert repr(_FV['CK_WELL'])[:60] == '"the well gone at Miriam\'s death, returned by Moses\' and Aar', ('CK_WELL', repr(_FV['CK_WELL'])[:100])
assert repr(_FV['CK_KISS'])[:60] == '\'Miriam too by the kiss — "there" / "there" with Deut 34:5 (', ('CK_KISS', repr(_FV['CK_KISS'])[:100])
assert repr(_FV['CK_BURIAL'])[:60] == '"buried near the death — the woman\'s bier not set down in th', ('CK_BURIAL', repr(_FV['CK_BURIAL'])[:100])
assert repr(_FV['CK_SENT'])[:60] == '"barred from the land — Moses and Aaron; Aaron\'s closed at 2', ('CK_SENT', repr(_FV['CK_SENT'])[:100])
assert repr(_FV['CK_THERE'])[:60] == '\'benefit from a corpse forbidden — "there" / "there" with th', ('CK_THERE', repr(_FV['CK_THERE'])[:100])
assert repr(_FV['CK_WELLD'])[:60] == "'miriams_gone_at_her_death_returned'", ('CK_WELLD', repr(_FV['CK_WELLD'])[:100])
assert repr(_FV['CK_MOURNED'])[:60] == "'the_men_and_the_women'", ('CK_MOURNED', repr(_FV['CK_MOURNED'])[:100])
assert repr(_FV['CK_MANNA'])[:60] == "'light_absorbed_in_the_limbs'", ('CK_MANNA', repr(_FV['CK_MANNA'])[:100])
assert repr(_FV['JR_DATE'])[:60] == '"Aaron died on (40, 5, 1) (33:38) — the tape\'s marker at 20:', ('JR_DATE', repr(_FV['JR_DATE'])[:100])
assert repr(_FV['JR_MOUTH'])[:60] == '"by the mouth of the LORD at the death (33:38) — the kiss (B', ('JR_MOUTH', repr(_FV['JR_MOUTH'])[:100])
assert repr(_FV['JR_ADAR'])[:60] == '"Moses\' seventh of Adar — computed backward from the tenth o', ('JR_ADAR', repr(_FV['JR_ADAR'])[:100])
assert repr(_FV['JR_ANALOGY'])[:60] == '"the fortieth year / the fortieth year — Deuteronomy 1:3\'s b', ('JR_ANALOGY', repr(_FV['JR_ANALOGY'])[:100])
assert repr(_FV['JR_NOWRITE'])[:60] == '"no write for 33:38-40 — the death and the hearing are the t', ('JR_NOWRITE', repr(_FV['JR_NOWRITE'])[:100])
assert repr(_FV['JR_DDATE'])[:60] == '(40, 5, 1)', ('JR_DDATE', repr(_FV['JR_DDATE'])[:100])
assert repr(_FV['JR_AGE'])[:60] == '123', ('JR_AGE', repr(_FV['JR_AGE'])[:100])
assert repr(_FV['ST_WALK'])[:60] == '"walk after His attributes (Sotah 14a:3-4) — \'after the LORD', ('ST_WALK', repr(_FV['ST_WALK'])[:100])
assert repr(_FV['ST_BURIED'])[:60] == '"and he was buried there (10:6) — the Torah\'s one seat; Numb', ('ST_BURIED', repr(_FV['ST_BURIED'])[:100])
assert repr(_FV['ST_PLACE'])[:60] == '"the place of the death — Moserah in the retelling (10:6), M', ('ST_PLACE', repr(_FV['ST_PLACE'])[:100])
assert repr(_FV['ST_FRAG'])[:60] == '"the fragments in the ark (10:2, 10:5) — \'and you shall put ', ('ST_FRAG', repr(_FV['ST_FRAG'])[:100])
assert repr(_FV['ST_R105'])[:60] == '"the receipt 10:5 — \'as the LORD commanded me\' (4:5 the pair', ('ST_R105', repr(_FV['ST_R105'])[:100])
assert repr(_FV['ST_ATTR'])[:60] == '{\'the_row\': "Sotah 14a:3-4 — \'after the LORD your God you sh', ('ST_ATTR', repr(_FV['ST_ATTR'])[:100])
assert repr(_FV['ST_CHARGE'])[:60] == '{\'31_7\': "Moses to Joshua — \'for you shall go with this peop', ('ST_CHARGE', repr(_FV['ST_CHARGE'])[:100])
assert repr(_FV['ZE_RUN'])[:60] == '"given in the sixth book by the mouth of the LORD — the hold', ('ZE_RUN', repr(_FV['ZE_RUN'])[:100])
assert repr(_FV['ZE_EXEC'])[:60] == "'married the sons of their uncles; the inheritance remained ", ('ZE_EXEC', repr(_FV['ZE_EXEC'])[:100])
assert repr(_FV['ZE_REACH'])[:60] == "'this_generation'", ('ZE_REACH', repr(_FV['ZE_REACH'])[:100])
assert repr(_FV['OS_MTN'])[:60] == '"the mountain of Abarim (27:12) — Nebo and Pisgah its other ', ('OS_MTN', repr(_FV['OS_MTN'])[:100])
assert repr(_FV['OS_HAND'])[:60] == '"the hand laid (27:18, 23) — one hand commanded, two laid (t', ('OS_HAND', repr(_FV['OS_HAND'])[:100])
assert repr(_FV['OS_RECEIPT'])[:60] == '"the receipt (27:22-23) — \'as the LORD commanded him\': the c', ('OS_RECEIPT', repr(_FV['OS_RECEIPT'])[:100])
assert repr(_FV['OS_DEBIT'])[:60] == "'the debit (27:12) — see the land from Abarim: commanded on ", ('OS_DEBIT', repr(_FV['OS_DEBIT'])[:100])
assert repr(_FV['OS_PISGAH'])[:60] == '"Pisgah (3:27) — 27:12\'s command read back with Pisgah for A', ('OS_PISGAH', repr(_FV['OS_PISGAH'])[:100])
assert repr(_FV['OS_PEOR'])[:60] == '"Beth-peor (3:29) — the last camp by CALL (22:1; 36:13; Deut', ('OS_PEOR', repr(_FV['OS_PEOR'])[:100])
assert repr(_FV['OS_CMDJ'])[:60] == '"command Joshua (3:28) — the commission read back (Kiddushin', ('OS_CMDJ', repr(_FV['OS_CMDJ'])[:100])
assert repr(_FV['OS_REFUSAL'])[:60] == '"the refusal (3:26) — \'let it suffice you\' the singular\'s on', ('OS_REFUSAL', repr(_FV['OS_REFUSAL'])[:100])
assert repr(_FV['OS_COMM'])[:60] == "{'mountain_names': ['Abarim (27:12; 33:47-48; Deut 32:49)', ", ('OS_COMM', repr(_FV['OS_COMM'])[:100])
assert repr(_FV['BH_GIFTS'])[:60] == "'the well, the cloud, the manna — three gifts by three sheph", ('BH_GIFTS', repr(_FV['BH_GIFTS'])[:100])
assert repr(_FV['BH_FELL'])[:60] == "'by rank — the righteous at their doors, the average outside", ('BH_FELL', repr(_FV['BH_FELL'])[:100])
assert repr(_FV['BH_DIBBUR'])[:60] == "'harsh speech (dibbur)'", ('BH_DIBBUR', repr(_FV['BH_DIBBUR'])[:100])
assert repr(_FV['BH_DEAD'])[:60] == "'the leper among the four as dead'", ('BH_DEAD', repr(_FV['BH_DEAD'])[:100])
assert repr(_FV['BH_MEASURE'])[:60] == '"an hour at the Nile, seven days\' halt — measure for measure', ('BH_MEASURE', repr(_FV['BH_MEASURE'])[:100])
assert repr(_FV['BH_SPIRIT'])[:60] == '"set apart — Moses\' spirit undiminished"', ('BH_SPIRIT', repr(_FV['BH_SPIRIT'])[:100])
assert repr(_FV['BH_CLOUDS'])[:60] == '7', ('BH_CLOUDS', repr(_FV['BH_CLOUDS'])[:100])
assert repr(_FV['NS_TERM'])[:60] == "'30 days'", ('NS_TERM', repr(_FV['NS_TERM'])[:100])
assert repr(_FV['NS_DAYS'])[:60] == '30', ('NS_DAYS', repr(_FV['NS_DAYS'])[:100])
assert repr(_FV['CP_MIDST'])[:60] == '"from your midst, of your brothers (18:15, 18:18) — not from', ('CP_MIDST', repr(_FV['CP_MIDST'])[:100])
assert repr(_FV['CP_WORDS'])[:60] == '"My words in his mouth (18:18) — not face to face, no interp', ('CP_WORDS', repr(_FV['CP_WORDS'])[:100])
assert repr(_FV['CP_TEST'])[:60] == '"the test by the event (18:21-22) — Jeremiah against Hanania', ('CP_TEST', repr(_FV['CP_TEST'])[:100])
assert repr(_FV['CP_ORDER'])[:60] == '{\'not_face_to_face\': "My words in his mouth — the Holy Spiri', ('CP_ORDER', repr(_FV['CP_ORDER'])[:100])
assert repr(_FV['CP_SUCC'])[:60] == "'the son stands in his place — for the king and for every pr", ('CP_SUCC', repr(_FV['CP_SUCC'])[:100])
assert repr(_FV['ER_FACE'])[:60] == '(6, 5)', ('ER_FACE', repr(_FV['ER_FACE'])[:100])
assert repr(_FV['ER_AVOT'])[:60] == "'moses_joshua_elders_prophets_great_assembly'", ('ER_AVOT', repr(_FV['ER_AVOT'])[:100])
assert repr(_FV['ER_BREAK'])[:60] == "'yishar_kochakha'", ('ER_BREAK', repr(_FV['ER_BREAK'])[:100])
assert repr(_FV['ER_RADIANCE'])[:60] == '(3, 3)', ('ER_RADIANCE', repr(_FV['ER_RADIANCE'])[:100])
assert repr(_FV['ER_FRAG'])[:60] == "'both_in_the_ark'", ('ER_FRAG', repr(_FV['ER_FRAG'])[:100])
assert repr(_FV['ER_3DEATHS'])[:60] == "{'sword': 'witnesses_and_warning', 'plague': 'witnesses_no_w", ('ER_3DEATHS', repr(_FV['ER_3DEATHS'])[:100])
assert repr(_FV['ER_PLAGUE'])[:60] == '(5, 31)', ('ER_PLAGUE', repr(_FV['ER_PLAGUE'])[:100])
assert repr(_FV['ES_SIGNS'])[:60] == '3', ('ES_SIGNS', repr(_FV['ES_SIGNS'])[:100])
assert repr(_FV['ES_BELIEVED'])[:60] == '[(4, 31), (14, 31)]', ('ES_BELIEVED', repr(_FV['ES_BELIEVED'])[:100])
assert repr(_FV['ES_TEN'])[:60] == '10', ('ES_TEN', repr(_FV['ES_TEN'])[:100])
assert repr(_FV['ES_SEA'])[:60] == '10', ('ES_SEA', repr(_FV['ES_SEA'])[:100])
assert repr(_FV['ES_BONES'])[:60] == "'moses_merited_the_bones_of_joseph'", ('ES_BONES', repr(_FV['ES_BONES'])[:100])
assert repr(_FV['ES_BIRTH'])[:60] == '(12, 7)', ('ES_BIRTH', repr(_FV['ES_BIRTH'])[:100])
assert repr(_FV['JO_OATH'])[:60] == "'Gen 47:31'", ('JO_OATH', repr(_FV['JO_OATH'])[:100])
assert repr(_FV['JO_CMD'])[:60] == "'law_joseph_47_29'", ('JO_CMD', repr(_FV['JO_CMD'])[:100])
assert repr(_FV['JO_CLOSED'])[:60] == "'Gen 50:13'", ('JO_CLOSED', repr(_FV['JO_CLOSED'])[:100])
assert repr(_FV['JO_BONES'])[:60] == "'Exod 13:19'", ('JO_BONES', repr(_FV['JO_BONES'])[:100])
assert repr(_FV['JO_WITHYOU'])[:60] == "'when_you_go_up'", ('JO_WITHYOU', repr(_FV['JO_WITHYOU'])[:100])
assert repr(_FV['JO_BOTH'])[:60] == "('esau', 'jacob')", ('JO_BOTH', repr(_FV['JO_BOTH'])[:100])
assert repr(_FV['JO_GATHERED'])[:60] == "'law_joseph_35_29'", ('JO_GATHERED', repr(_FV['JO_GATHERED'])[:100])
assert repr(_FV['FA_GATHERED'])[:60] == "['Gen 25:8', 'Gen 25:17', 'Gen 35:29', 'Gen 49:33', 'Gen 49:", ('FA_GATHERED', repr(_FV['FA_GATHERED'])[:100])
assert repr(_FV['FA_BURIED'])[:60] == '(8, False)', ('FA_BURIED', repr(_FV['FA_BURIED'])[:100])
assert repr(_FV['FA_CMD'])[:60] == 'True', ('FA_CMD', repr(_FV['FA_CMD'])[:100])
assert repr(_FV['FA_POSS'])[:60] == "'burial_is_the_first_act'", ('FA_POSS', repr(_FV['FA_POSS'])[:100])
assert repr(_FV['MA_THREE'])[:60] == '3', ('MA_THREE', repr(_FV['MA_THREE'])[:100])
assert repr(_FV['MA_SEED'])[:60] == "'Gen 25:16'", ('MA_SEED', repr(_FV['MA_SEED'])[:100])
assert repr(_FV['MA_PROMISE'])[:60] == "'buried_in_peace'", ('MA_PROMISE', repr(_FV['MA_PROMISE'])[:100])
assert repr(_FV['HI_RECEIPT'])[:60] == '"the receipt (6:25) — \'as he commanded us\' without the Name:', ('HI_RECEIPT', repr(_FV['HI_RECEIPT'])[:100])
assert repr(_FV['HI_OATH'])[:60] == '{\'deut_6_13\': "\'by his name you shall swear\' — a POSITIVE cl', ('HI_OATH', repr(_FV['HI_OATH'])[:100])
assert repr(_FV['HI_NONAME'])[:60] == '{\'deut_6_25\': "\'as he commanded us\' — k/834 + 6680 with the ', ('HI_NONAME', repr(_FV['HI_NONAME'])[:100])
assert repr(_FV['OH_PEOR'])[:60] == '"Baal-peor seen (4:3) — Numbers 25:3-9 READ BACK, SHORTENED:', ('OH_PEOR', repr(_FV['OH_PEOR'])[:100])
assert repr(_FV['OH_CHAIN'])[:60] == "{'this_chapter': 'Deut 4:26', 'the_chain': ['Deut 4:26', 'De", ('OH_CHAIN', repr(_FV['OH_CHAIN'])[:100])
assert repr(_FV['OH_FRAME'])[:60] == "{'deut_4_44_45': 'the_second_speech_s_head', 'write': None}", ('OH_FRAME', repr(_FV['OH_FRAME'])[:100])
assert repr(_FV['SH_NAME'])[:60] == "'Hoshea to Joshua at 13:16 — the new name at 8 seats before ", ('SH_NAME', repr(_FV['SH_NAME'])[:100])
assert repr(_FV['SH_EQUAL'])[:60] == "'equal — Caleb first at 13:6, Joshua at 13:8 (Tosefta Kerito", ('SH_EQUAL', repr(_FV['SH_EQUAL'])[:100])
assert repr(_FV['SH_CEASED'])[:60] == '(40, 5, 15)', ('SH_CEASED', repr(_FV['SH_CEASED'])[:100])
