



# =====================================================================
# THE CELLS OF THE DEATH, III — F5 Joshua and the receipt (34:9), F6 the prophet, the signs and the terror (34:10-12)
# =====================================================================
def joshua_and_the_receipt(case, data):
    """F5 — Deut 34:9 — ONE LINE joshua_full_of_the_spirit_israel_hearkened (ACT) writing spirit_of_wisdom_by_the_hands_laid (a STATUS on Joshua — the ledger yehoshua) and israel_hearkened_to_joshua_as_the_lord_commanded_moses (a STATUS on Israel); THE COMMISSION'S RECEIPT — Numbers 27:18-23 on the tape (zelophehad, opening_speech by CALL — a RUN CITATION), 31:7 and 31:23 (covenant_return_charge by CALL), Hoshea's new name (shelach by CALL); THE REGISTER'S ONE SEAT 'as the LORD commanded Moses' RE-DECLARED from the gate's print; Onkelos 'RECEIVED from him' — Avot 1:1's chain (blessing_of_moses by CALL — the parameter the_chain_of_transmission)"""
    del P_[:]
    ask = case['ask']
    if ask == 'joshua_the_son_of_nun_was_full_of_the_spirit_of_wisdom_for_moses_had_laid_his_hands_upon_him':
        ink('34:9', "'AND JOSHUA THE SON OF NUN WAS FULL OF THE SPIRIT OF WISDOM, FOR MOSES HAD LAID HIS HANDS UPON HIM' — THE COMMISSION'S RECEIPT: Numbers 27:23's 'his hands upon him' (the twin %d — six shared), 27:18's 'the son of Nun' (the twin %d), 31:23's charge (the twin %d); 'the spirit of wisdom' three seats (%s — Exodus 28:3's craftsmen and Isaiah 11:2's shoot, the Prophets' seat cited never read); 'full of the spirit of wisdom' and 'laid his hands upon him' once each in the Bible; 'for' (ki) the chapter's one; 'full' an adjective, 'laid' the perfect (the morph codes)" % (TWIN['34:9 vs Num 27:23'], TWIN['34:9 vs Num 27:18'], TWIN['34:9 vs 31:23'], P(_G('רוח (the spirit of)'), _G('חכמה (wisdom)'), books=None)))
        move("cold_run_zelophehad (CALL) — ZE.the_daughters(the_run) = %s (Numbers 27's runner — the commission 27:18-23 on the tape: invested_office on yehoshua, THE RUN CITATION); cold_run_opening_speech (CALL) — OS.the_commission(the_hand_laid) = %s (one hand commanded, two laid — the Sifrei's reading; OS.the_commission(the_receipt) = %s); cold_run_covenant_return_charge (CALL) — CR.the_tent_and_the_commission(he_commissioned_joshua_be_strong_and_of_good_courage) = %s (31:23's commission at the tent — joshua_commissioned_to_bring_israel_in on yehoshua; 31:7's charge joshua_charged_to_bring_israel_in); cold_run_shelach (CALL) — SH.spies(joshua_name) = %s (Hoshea to Joshua at Numbers 13:16 — the new name kept); cold_run_beha (CALL) — BH.seventy_elders(spirit) = %s (the spirit on the seventy — Joshua's own by the hands)" % (SV(ZE_RUN, 50), SV(OS_HAND, 50), SV(OS_RECEIPT, 40), SV(CR_COMM, 50), SV(SH_NAME, 40), SV(BH_SPIRIT, 40)), "357:38 Joshua's wisdom; Onkelos 'filled with a spirit of wisdom because Moses had rested his hands on him' (semakh — the hands laid — one seat in the book); THE WRITE spirit_of_wisdom_by_the_hands_laid — a STATUS on yehoshua (DP2)")
        dat("THE LINE joshua_full_of_the_spirit_israel_hearkened (an ACT) at %s; THE WRITE spirit_of_wisdom_by_the_hands_laid, a STATUS on yehoshua (the ledger's entries before: invested_office, joshua_charged_to_bring_israel_in, joshua_commissioned_to_bring_israel_in); the readback row 34:9 SUPPLIED with its writes and REFERENCE against the commission by kind (joshua_commissioned at Numbers 27:22) — THE RECEIPT ROW" % D1)
        return out("and Joshua the son of Nun was full of the spirit of wisdom, for Moses had laid his hands upon him (34:9) — THE COMMISSION'S RECEIPT: Numbers 27:18-23 on the tape, six shared with 27:23 (by CALL: %s; the hand laid: %s), 31:7 and 31:23 the charge and the commission: THE WRITE spirit_of_wisdom_by_the_hands_laid, a STATUS on Joshua" % (SV(ZE_RUN, 30), SV(OS_HAND, 30)), ['spirit_of_wisdom_by_the_hands_laid'])
    if ask == 'the_children_of_israel_hearkened_to_him_and_did_as_the_lord_commanded_moses':
        ink('34:9', "'AND THE CHILDREN OF ISRAEL HEARKENED TO HIM, AND DID AS THE LORD COMMANDED MOSES' — THE REGISTER'S ONE SEAT in the chapter: 'as the LORD commanded Moses' the tabernacle's receipt formula — thirty-eight seats in the Torah, this the last (the receipt finder's own count %s — Exodus 12:28's kin computed %s; the twin %d); the register file's seat 'Deut 34:9' declared class NONE at Numbers' close ('Deuteronomy is not on the tape') — RE-DECLARED at this compile to the class the register gate computes (the referent BEHIND on the tape: the commission's own line; 10:5's and 20:17's precedent the class ACT — read from the print, never typed first); 'and they did' the chapter's last narrative verb" % (RECEIPT_SEATS, KINC[(34, 9)][0], TWIN['34:9 vs Exod 12:28']))
        move("cold_run_blessing_of_moses (CALL) — BL.DATA the_chain_of_transmission = %s (MISHNAH AVOT 1:1 THE CASE — Moses received the Torah from Sinai and handed it to Joshua: Onkelos 34:9 'THE CHILDREN OF ISRAEL RECEIVED FROM HIM' — 'hearkened' rendered kabbalah's verb, the chain in the translator's own word; the parameter the_chain_of_transmission read again, 21b's); cold_run_second_tablets (CALL) — ST.the_tablets_and_the_ark(the_receipt_10_5) = %s (the precedent — a receipt whose referent stands behind on the tape, the class the gate computed at 9b); cold_run_hear_o_israel (CALL) — HI.the_sons_question(the_receipt) = %s (6:25's receipt without the Name — the form; 34:9's with it); cold_run_covenant_return_charge (CALL) — CR.the_tent_and_the_commission(you_shall_bring_the_children_of_israel_into_the_land_i_swore) = %s (31:23 — the land the LORD swore: the oath of 34:4 and the commission one charge); 357:39 NO GREATER OBEDIENCE than the children of Israel's to Joshua; the awe at Joshua 4:14 (the Prophets' seat cited never read)" % (SV(BL_CHAIN, 60), SV(ST_R105, 50), SV(HI_RECEIPT, 40), SV(CR_BRING, 40)), "THE WRITE israel_hearkened_to_joshua_as_the_lord_commanded_moses — a STATUS on israel_people (DP2); THE DATA ROW the_receipt_re_declared (the class from the gate's print — register_census.py --strict read alone before the chain); THE PARAMETER the_chain_of_transmission")
        dat("THE WRITE israel_hearkened_to_joshua_as_the_lord_commanded_moses, a STATUS on israel_people at %s; THE RECEIPT ROW 34:9 — the register's seat RE-DECLARED from the gate's print (THE DATA ROW the_receipt_re_declared); THE PARAMETER the_chain_of_transmission — MISHNAH AVOT 1:1 THE CASE (Onkelos's 'received'); the readback row 34:9's second write" % D1)
        return out("and the children of Israel hearkened to him, and did as the LORD commanded Moses (34:9) — the tabernacle's receipt formula at its last Torah seat, the register's one seat re-declared from the gate's print (the referent the commission behind on the tape); Onkelos 'received from him' — Avot 1:1's chain in the translator's verb (by CALL: %s): THE WRITE israel_hearkened_to_joshua_as_the_lord_commanded_moses, a STATUS on Israel" % (SV(BL_CHAIN, 40),), ['israel_hearkened_to_joshua_as_the_lord_commanded_moses'])
    return 'no verdict in span', [], list(P_)

def the_prophet_the_signs_and_the_terror(case, data):
    """F6 — Deut 34:10-12 — ONE LINE no_prophet_like_moses_declared (ACT — the epilogue, 'there arose not' a narrative past) writing no_prophet_like_moses_face_to_face_declared and signs_mighty_hand_great_terror_in_the_sight_of_all_israel_declared (STATUSES on Israel); 18:15's prophet LIKE Moses (courts_prophet by CALL — the parameter the_prophets_bound), 'face to face' Exodus 33:11's (erection by CALL) and Numbers 12:8's 'mouth to mouth' (beha by CALL — the twin by sense); the signs, the plagues and the sea (exodus_story by CALL — RUN CITATIONS); THE TABLETS BROKEN 'before your eyes' (second_tablets, erection by CALL — the Sifrei 357:44, the export's last row); THE BOOK'S EDGE"""
    del P_[:]
    ask = case['ask']
    if ask == 'there_arose_not_a_prophet_since_in_israel_like_moses_whom_the_lord_knew_face_to_face':
        ink('34:10', "'AND THERE AROSE NOT A PROPHET SINCE IN ISRAEL LIKE MOSES, WHOM THE LORD KNEW FACE TO FACE' — 18:15's and 18:18's 'a prophet' (the twins %d, %d — 'like me' promised, none LIKE Moses arisen); 'face to face' three seats in the Torah, five in the Bible (%s — Exodus 33:11's twin %d; Jacob at Peniel, Gideon and Ezekiel cited never read); Numbers 12:8's 'mouth to mouth' shares 'and not' alone (the twin %d — the twin by sense); 'there arose not a prophet', 'like Moses', 'whom the LORD knew' once each in the Bible; 'arose' the epilogue's narrative past; the kin computed %s (the Writings' seat, cited never read)" % (TWIN['34:10 vs 18:15'], TWIN['34:10 vs 18:18'], P(_G('פנים (face)'), _G('אל (to)'), _G('פנים (face)'), books=None), TWIN['34:10 vs Exod 33:11'], TWIN['34:10 vs Num 12:8'], KINC[(34, 10)][0]))
        move("cold_run_courts_prophet (CALL) — CP.the_prophet(from_your_midst_of_your_brothers) = %s and CP.the_prophet(my_words_in_his_mouth) = %s (18:15's and 18:18's prophet LIKE Moses — prophet_like_moses_promised 1 on israel_people the tape's own line; CP.DATA the_prophets_order = %s); 357:40 THE PROPHETS BOUND — 'like me' bounded by three differences: the king's cook who knows the king's expenses (E26, checked in MIDDOT.md), Balaam among the nations (Numbers 24:4, 24:16 on the tape), 5:28's 'stand here by Me' — the parameter the_prophets_bound; cold_run_erection (CALL) — ER.presence(pillar_face) = %s (Exodus 33:11's face to face at the tent of meeting — a RUN CITATION); cold_run_beha (CALL) — BH.miriam(dibbur) = %s (Numbers 12:8's 'mouth to mouth' — the twin by sense); 357:41 the face refused in this world (Exodus 33:20) and shown at death — the dead see" % (SV(CP_MIDST, 50), SV(CP_WORDS, 50), SV(CP_ORDER, 40), SV(ER_FACE, 40), SV(BH_DIBBUR, 40)), "Onkelos 'to whom the LORD was revealed face to face' (the prophet's eleven Aramaic seats — 33:1's prophet of the LORD and 34:10 the last); THE WRITE no_prophet_like_moses_face_to_face_declared — a STATUS on israel_people (DP2); THE PARAMETER the_prophets_bound")
        dat("THE LINE no_prophet_like_moses_declared (an ACT — the epilogue) at %s; THE WRITE no_prophet_like_moses_face_to_face_declared, a STATUS on israel_people; THE PARAMETER the_prophets_bound (357:40's three differences); the readback row 34:10 SUPPLIED with its writes and REFERENCE against the prophet's law by kind (prophet_law_declared at 18:15)" % D1)
        return out("and there arose not a prophet since in Israel like Moses, whom the LORD knew face to face (34:10) — 18:15's prophet LIKE Moses promised and none arisen (by CALL: %s), the prophets bound by three differences (357:40 — a parameter); face to face Exodus 33:11's, mouth to mouth Numbers 12:8's twin by sense: THE WRITE no_prophet_like_moses_face_to_face_declared, a STATUS on Israel" % (SV(CP_MIDST, 40),), ['no_prophet_like_moses_face_to_face_declared'])
    if ask == 'all_the_signs_and_wonders_the_lord_sent_him_to_do_in_the_land_of_egypt_to_pharaoh_his_servants_and_his_land':
        ink('34:11', "'all the signs and the wonders which the LORD sent him to do in the land of Egypt, to Pharaoh, his servants and his land' — Exodus 7:3's 'in the land of Egypt' (the twin %d — the signs and the wonders multiplied); 'to Pharaoh and to all his servants' 29:1's pair (%s — the kin computed %s; the twin %d); Jeremiah 32:20's twin (the Prophets' seat cited never read); the signs plene (the measure's defective spelling found no seat — the instrument's, not the text's)" % (TWIN['34:11 vs Exod 7:3'], P(_G('לפרעה (to Pharaoh)'), _G('ולכל (and to all)'), _G('עבדיו (his servants)'), books=None), KINC[(34, 11)][0], TWIN['34:11 vs 29:1']))
        move("cold_run_exodus_story (CALL) — ES.signs(count) = %s and ES.signs(believed_seats) = %s (the signs in hand — signs_in_hand 1 on moses the tape's own line; a RUN CITATION), ES.plagues(ten) = %s (the ten plagues on the tape — the wonders); 357:42 'all the signs and the wonders' — in the land of Egypt, to Pharaoh, to his servants, to his land: the four degrees" % (SV(ES_SIGNS, 30), SV(ES_BELIEVED, 40), SV(ES_TEN, 30)), "the signs a RUN CITATION of the tape's own Egypt lines — NO WRITE on this ask (the line's second write on the next); the readback row 34:11 REFERENCE against the signs by kind (signs_shown)")
        dat("all the signs and the wonders in the land of Egypt — RUN CITATIONS of the tape's own lines (exodus_story by CALL), no write on this ask; the readback row 34:11 REFERENCE against the signs by kind")
        return out("all the signs and the wonders which the LORD sent him to do in the land of Egypt, to Pharaoh, his servants and his land (34:11) — Exodus 7:3's signs and the ten plagues the tape's own lines (by CALL: %s plagues; the signs %s): run citations, no write on this ask; 29:1's pair" % (SV(ES_TEN, 20), SV(ES_SIGNS, 20)), ['accepted'])
    if ask == 'the_mighty_hand_and_the_great_terror_which_moses_wrought_in_the_sight_of_all_israel':
        ink('34:12', "'AND THE MIGHTY HAND AND THE GREAT TERROR WHICH MOSES WROUGHT IN THE SIGHT OF ALL ISRAEL' — 'the mighty hand' with the article once in the Bible (the formula's other seats say 'a mighty hand' — 4:34, 7:19, 3:24 share the adjective), 'the great terror' once; Exodus 14:31's 'the great hand … which the LORD did' (the twin %d — the sea); 'in the sight of all Israel' 31:7's pair in the Torah (%s); 34:12 with 9:17's tablets broken SHARES NOTHING (the twin %d — the Sifrei's join by sense at 357:44, its own); the kin computed %s" % (TWIN['34:12 vs Exod 14:31'], P(_G('לעיני (in the sight of)'), _G('כל (all)'), _G('ישראל (Israel)'), books=T), TWIN['34:12 vs 9:17'], KINC[(34, 12)][0]))
        move("cold_run_exodus_story (CALL) — ES.sea(ten_at_sea) = %s (the great hand at the sea — 357:43 THE GREAT TERROR the sea's splitting; the mighty hand the firstborn's plague — ES.plagues(ten)); 357:44 RABBI ELAZAR — Sinai, the wilderness and THE TABLETS BROKEN 'before your eyes' (9:17): cold_run_second_tablets (CALL) — ST.the_tablets_and_the_ark(the_fragments_in_the_ark) = %s (the fragments laid in the ark — the breaking's aftermath on the tape), cold_run_erection (CALL) — ER.tablets(breaking_ratified) = %s (the shelf's last teaching APPROVES the breaking — 'well done that you broke them', Shabbat 87a OWED): THE EXPORT'S LAST ROW, the Sifrei ends with the book; Onkelos 'THE GREAT VISION' for the terror (the sights of Egypt — 4:34, 26:8, 34:12); cold_run_covenant_return_charge (CALL) — CR.the_charge_and_the_crossing(moses_called_joshua_in_the_sight_of_all_israel) = %s (31:7's 'in the sight of all Israel' — the pair)" % (SV(ES_SEA, 40), SV(ST_FRAG, 50), SV(ER_BREAK, 50), SV(CR_CALLED, 40)), "THE WRITE signs_mighty_hand_great_terror_in_the_sight_of_all_israel_declared — a STATUS on israel_people (DP2); THE BOOK'S EDGE — the unit deu_34_moses_death's twelve steps close, the Torah's tape ends; the next line the Prophets' (Joshua 1:1 — never read): THE DATA ROW the_books_edge")
        dat("THE WRITE signs_mighty_hand_great_terror_in_the_sight_of_all_israel_declared, a STATUS on israel_people at %s; THE DATA ROW the_books_edge (no footer formula in the chapter — the end of a book is not a footer; the register's print read for any undeclared seat); the readback row 34:12 REFERENCE against the tablets broken by kind (tablets_broken at 9:17) — THE LAST ROW" % D1)
        return out("and the mighty hand and the great terror which Moses wrought in the sight of all Israel (34:12) — the firstborn's plague and the sea (357:42-43; by CALL: %s), THE TABLETS BROKEN before your eyes the Sifrei's last row (357:44 — the breaking approved; the fragments by CALL: %s): THE WRITE signs_mighty_hand_great_terror_in_the_sight_of_all_israel_declared, a STATUS on Israel — THE BOOK'S EDGE, the Torah's tape ends" % (SV(ES_SEA, 30), SV(ST_FRAG, 30)), ['signs_mighty_hand_great_terror_in_the_sight_of_all_israel_declared'])
    return 'no verdict in span', [], list(P_)
