# THE SIFREI ROWS ON CHAPTER 4 (THE DEUTERONOMY WALK sitting 2 — CHAPTER 4, 2026-09-16): the Sifrei on Deuteronomy has NO PISKA on the chapter
# (30 heads on 3:29, 31 on 6:4 — the shelf's silence over 4:1-49 measured on the export's heads), so the "found by position" clause is the whole
# reading of the spine here: EIGHT rows of other piskaot cite chapter 4 (seven Hebrew, eight English — 301:21 the English's alone), each opened in
# BOTH files; two of the eight were read at sitting 1 (30:2 fresh, 37:9 credited) and are CREDITED here with a quick look; the SIX FRESH rows
# verdicted below, the middah named where the row argues by one (logic/MIDDOT.md). The shelf's Hebrew cut by consonants (ch4_ink.SP_). Speed
# ruling (c): CONTEXT terse.
from ch4_ink import *
S = {}
def srow(p, r, verdict, prose): S[(p, r)] = (verdict, prose)

srow(48, 2, 'MATERIAL', f'R. ISHMAEL USED TO SAY: "ONLY TAKE HEED TO YOURSELF AND KEEP YOUR SOUL DILIGENTLY" (4:9) — A PARABLE OF A KING OF FLESH AND BLOOD WHO TRAPPED A BIRD AND GAVE IT TO HIS SERVANT: BE CAREFUL WITH THIS BIRD, IT IS FOR MY SON; IF YOU LOSE IT, DO NOT THINK YOU LOST A BIRD WORTH A PENNY — IT IS AS IF YOU LOST YOUR LIFE. AND SO "IT IS NO EMPTY WORD FOR YOU" (32:47) — THE WORD YOU CALL EMPTY IS YOUR LIFE. The row on 11:22 ({SP_(48, 2, "כאלו", "נפשך", "אבדת")} "as if you had lost your soul"): 4:9\'s "keep your SOUL" read as the soul itself at stake — the verse\'s "your soul" (the store: "living-being-you/your", the one word at all eighteen seats) made the life the words guard; the English\'s footnote sends to Avot de-Rabbi Natan A 24. The middah: the parable (E26, the mashal of the king) on a verse whose "soul" is read whole; the second verse (32:47) joined by its own word "life" — a REFERENCE the Sifrei makes, not a link of ours (LR1). The prior read: none (fresh in both files).')
srow(49, 2, 'MATERIAL', f'"AND TO CLEAVE TO HIM" (11:22) — HOW CAN A MAN GO UP ON HIGH AND CLEAVE TO FIRE? IS IT NOT SAID "FOR THE LORD YOUR GOD IS A CONSUMING FIRE" (4:24), AND "HIS THRONE WAS FLAMES OF FIRE" (DANIEL 7:9)? RATHER, CLEAVE TO THE SAGES AND THEIR DISCIPLES, AND I COUNT IT TO YOU AS IF YOU WENT UP ON HIGH AND TOOK IT — AND NOT IN PEACE, BUT AS IF YOU MADE WAR AND TOOK IT: "YOU WENT UP ON HIGH, YOU TOOK CAPTIVES" (PSALM 68:19). The row on 11:22 ({SP_(49, 2, "הדבק", "בחכמים", "ובתלמידיהם")} "cleave to the sages and to their disciples"): 4:24\'s "consuming fire" cited as the OBJECTION — the cleaving of 4:4 ("you who cleave to the LORD … are all alive") and 11:22 made impossible by 4:24\'s fire, and resolved by the sages; the same objection Ketubot 111b raises on 4:4 itself (the testing shelf — routed). The middah: the contradiction between two verses resolved by a third reading (I13, the two verses that contradict each other until a third decides); "consuming fire" the pair\'s Torah seats 4:24 and 9:3 (computed). Fresh in both files.')
srow(148, 8, 'MATERIAL', f'R. YOSE THE GALILEAN SAYS: FROM WHAT IS SAID "WHICH THE LORD YOUR GOD APPORTIONED TO ALL THE PEOPLES" (4:19) — MIGHT IT MEAN HE APPORTIONED THEM TO THE NATIONS FOR WORSHIP? THE TEACHING SAYS "GODS WHICH THEY KNEW NOT AND WHICH HE HAD NOT APPORTIONED TO THEM" (29:25). The row on 17:2-3 ({SP_(148, 8, "יכול", "שחלקם", "לאמות")} "might it be that he apportioned them to the nations"): the verb "apportioned" at ITS TWO TORAH SEATS — the qal perfect 4:19 and 29:25 (computed: the form five seats in the Bible, the Torah\'s two exactly these) — read against each other, the second denying what the first might grant; ONKELOS AT 4:19 answers the same question by translation ("which the LORD PREPARED for all the peoples" — the apportioning made a provision of light, one seat of the word). The middah: the doubt raised and closed by a second verse of the same word (I2\'s form on the two seats — a REFERENCE by the shared verb the Sifrei itself draws, LR1). Fresh in both files.')
srow(301, 21, 'MATERIAL', f'"AND WITH GREAT TERROR" (26:8) — THIS IS THE REVELATION OF THE SHEKHINAH, AS IT IS WRITTEN "OR HAS A GOD TRIED TO COME AND TAKE HIM A NATION FROM THE MIDST OF A NATION, BY TRIALS, BY SIGNS, BY WONDERS, BY WAR, BY A MIGHTY HAND, BY AN OUTSTRETCHED ARM AND BY GREAT TERRORS, ACCORDING TO ALL THE LORD YOUR GOD DID FOR YOU IN EGYPT BEFORE YOUR EYES" (4:34). The row on 26:8 — the first-fruits\' declaration read word by word, "great terror" glossed by 4:34\'s "great terrors" ({SP_(301, 21, "זו", "גלוי", "שכינה")} "this is the revelation of the Shekhinah"): THE EXPORT\'S THIRD CITATION FORM — the Hebrew row UNPOINTED and abbreviated ("as it is written" in two letters), citing nothing in parentheses; the English "(Devarim 4:34)" with a space (the Hebrew rows of 1-30 cite "(דברים א א)" — "Deuteronomy 1:1" — and the English "(Dt.1:1)" without one; measured); the row is the English\'s alone in the scan. THE PAIR MEASURED: 4:34 "with great terrors" (the plural) and 26:8 "with great terror" (the singular, defective) — the phrase\'s two Bible seats with Jeremiah 32:21 (computed); 4:34\'s arm "outstretched" PLENE where 26:8 writes it defective (the diff). The Passover Haggadah\'s row (Mishnah Pesachim 10:4\'s "expounds from \'a wandering Aramean\'" — the testing shelf, routed). The middah: the gloss of a word by its fuller seat (E7 — the term fixed from another place). Fresh in both files.')
srow(306, 1, 'MATERIAL', f'"GIVE EAR, O HEAVENS, AND I WILL SPEAK" (32:1) — R. MEIR: WHEN ISRAEL WERE WORTHY THEY TESTIFIED AGAINST THEMSELVES (JOSHUA 24:22); THEY CORRUPTED THEMSELVES (HOSEA 12:1) — HE MADE JUDAH AND BENJAMIN TESTIFY (ISAIAH 5:3-4); THEY CORRUPTED (MALACHI 2:11) — HE MADE THE PROPHETS TESTIFY (2 KINGS 17:13); THEY CORRUPTED (2 CHRONICLES 36:16) — HE MADE THE HEAVENS TESTIFY: "I CALL HEAVEN AND EARTH TO WITNESS AGAINST YOU THIS DAY" (4:26); THEY CORRUPTED BEFORE THE HEAVENS (JEREMIAH 7:17-18) — THE EARTH (JEREMIAH 6:19); THE ROADS (6:16); THE NATIONS (6:18); THE MOUNTAINS (MICAH 6:2); THE BEASTS (ISAIAH 1:3); THE BIRDS (JEREMIAH 8:7); THE FISH (JOB 12:8); THE ANT (PROVERBS 6:6-8) — R. SHIMON BEN ELAZAR: SHAMED WAS THE MAN WHO HAD TO LEARN FROM THE ANT, AND DID NOT. The head row of the Song ({SP_(306, 1, "העיד", "בהם", "את", "השמים")} "he made the heavens testify against them"): 4:26\'s witnesses THE THIRD of eleven summoned — "he made testify against them" ELEVEN times in the Hebrew row, "to testify against them" ten in the English (computed); 4:26 is the seat quoted for the heavens, where 30:19 and 31:28 carry the same summons (the three seats of "heaven and earth" as witnesses in the book, computed). The middah: the chain of verses ordered as a history (E32\'s kin — the sequence read as a ladder), each rung a citation; the Torah\'s own 4:26 read as the verse the prophets\' summons fulfilled. Fresh in both files.')
srow(323, 1, 'MATERIAL', f'"IF THEY WERE WISE THEY WOULD UNDERSTAND THIS" (32:29) — HAD ISRAEL LOOKED INTO THE WORDS OF TORAH I GAVE THEM, NO NATION OR KINGDOM WOULD HAVE RULED THEM; AND "THIS" IS NOTHING BUT TORAH, AS IT IS SAID "AND THIS IS THE TORAH WHICH MOSES SET BEFORE THE CHILDREN OF ISRAEL" (4:44). ANOTHER WORD: HAD THEY LOOKED INTO WHAT JACOB THEIR FATHER SAID — ACCEPT THE KINGDOM OF HEAVEN, OUTDO ONE ANOTHER IN THE FEAR OF HEAVEN, DEAL WITH ONE ANOTHER IN LOVINGKINDNESS. The row on 32:29 ({SP_(323, 1, "ואין", "זאת", "אלא", "תורה")} "and \'this\' is nothing but Torah"): 4:44\'s "AND THIS IS THE TORAH" made the definition of the word "this" wherever the Song says it — the frame verse of chapter 4 (one seat of the phrase; "which Moses set before the children of Israel" one seat; computed) read as a lexicon entry. The middah: the word fixed from its defining seat (E7 — "this" from 4:44; the same move the Sifrei makes on "these" elsewhere), stated in the row\'s own formula "nothing but" (the exclusive gloss). Fresh in both files.')

# THE TWO CREDITED ROWS (read at sitting 1 — named in the ledger's head, not read fresh here)
CRED = {(30, 2): '"AND NOW, ISRAEL, HEAR THE STATUTES" (4:1) — YOU ARE NEW, THE PAST IS FORGIVEN: the last row of the plea\'s piska (on 3:29) crosses into 4:1 — the rebuke\'s close as forgiveness, "his right hand stretched out to receive the penitent"; read FRESH at sitting 1 (the deu_01_03 ledger, MATERIAL), its pointer the very verse this reading opens on. Quick look: the row cites 4:1 alone of this chapter.',
        (37, 9): 'HERMON\'S FOUR NAMES — "the Sidonians call Hermon Sirion, the Amorites Senir" (3:9) and "unto Mount SION, which is Hermon" (4:48): four kingdoms quarrelling over the name; "if over the trash-heaps of the mountains of Israel, how much more the praise of the Land" (the row on 11:10, an a-fortiori — I1). Credited at sitting 1 with a quick look; the fourth name is chapter 4\'s (4:48 the one seat of Sion — computed). Quick look again: the row cites 4:48 alone of this chapter.'}
