
# ---- THE CALLEES' FACTS (every edge live at the cells that consume them; the values asserted from the callees' own prints — ch9_callees.out) ----
ER_FORTY = ER.ascent('forty'); ER_17 = ER.ascent('seventeenth_tammuz'); ER_SHEET = ER.ascent('sheet_taanit_4_6'); ER_SIX7 = ER.ascent('six_seventh'); ER_CANON = ER.ascent('canon_channel')
assert ER_FORTY['v'] == 9 and ER_17['v'] == '17_tammuz' and ER_SHEET['v'] == 'tablets_broken_17_tammuz' and ER_SIX7['v'] == (1, 1) and ER_CANON['v'][:2] == ('tablets', 'torah') and ER_17['fx'] == ['tablets_delivered'], (ER_FORTY['v'], ER_17['v'], ER_SHEET['v'], ER_SIX7['v'])
ER_MOLTEN = ER.calf('molten_calf'); ER_STIFF = ER.calf('saru_stiff'); ER_SEIZED = ER.calf('seized'); ER_CHAIR = ER.calf('three_legged'); ER_VAYECHAL = ER.calf('vayechal'); ER_VOW = ER.calf('vow_annulled'); ER_OATH = ER.calf('oath_endures'); ER_RELENT = ER.calf('relent')
assert ER_MOLTEN['v'] == 4 and ER_STIFF['v'] == (3, 6) and ER_SEIZED['v'] == 'moses_seized_him' and ER_CHAIR['v'] == 'one_leg_cannot_stand' and ER_VAYECHAL['v'] == 14 and ER_VOW['v'] == 'annulled_his_vow_by_the_vows_law' and ER_OATH['v'] == 'oath_by_the_name_endures' and ER_RELENT['v'] == (5, 5) and ER_SEIZED['fx'] == ['decree_relented'], (ER_MOLTEN['v'], ER_STIFF['v'], ER_SEIZED['v'], ER_RELENT['v'])
ER_VERBS = ER.calf('four_verbs'); ER_NULL = ER.calf('nullification_dispute'); ER_FOURTH = ER.calf('fourth_verb_decides'); ER_GREAT = ER.calf('great_sin'); ER_INDIV = ER.calf('individual_rule'); ER_SURCHARGE = ER.calf('surcharge'); ER_READING = ER.calf('reading_law'); ER_BOSHESH = ER.calf('boshesh'); ER_CONFESS = ER.calf('confess_specify')
assert ER_VERBS['v'] == ['וישרף', 'ויטחן', 'ויזר', 'וישק'] and ER_NULL['v'] == ('grind_and_scatter', 'becomes_manure') and ER_FOURTH['v'] == 'a_test_not_a_nullification' and ER_GREAT['v'] == 4 and ER_INDIV['v'] == 'him_I_will_blot' and ER_SURCHARGE['v'] == 'one_twenty_fourth' and ER_READING['v'] == 'second_read_not_translated' and ER_BOSHESH['v'] == 'the_sixth_hour_came' and ER_CONFESS['v'] == ('specify', 'do_not_specify'), (ER_VERBS['v'], ER_NULL['v'], ER_FOURTH['v'])
ER_RATIFIED = ER.tablets('breaking_ratified'); ER_FRAGMENTS = ER.tablets('fragments_by_call'); ER_FORMS = ER.tablets('finger_and_forms'); ER_FINGER = ER.craftsmen('finger')
assert ER_RATIFIED['v'] == 'yishar_kochakha' and ER_FRAGMENTS['v'] == 'both_in_the_ark' and ER_FORMS['v'] == {'לחת': 12, 'לוחת': 3, 'הלחת': 9, 'לחות': 2} and ER_FINGER['v'] == 3, (ER_RATIFIED['v'], ER_FRAGMENTS['v'], ER_FORMS['v'])
ES_TRIALS = ES.trials('ten_list'); ES_SIX = ES.trials('count_by_exodus')
assert ES_TRIALS['v'] == ('two_at_the_sea', 'two_at_the_water', 'two_at_the_manna', 'two_at_the_quail', 'one_at_the_calf', 'one_at_paran') and ES_SIX['v'] == 6, (ES_TRIALS['v'], ES_SIX['v'])
BH_EDGE = BH.taberah_and_quail({'ask': 'fire_at_edge'}, BH.DATA); BH_SANK = BH.taberah_and_quail({'ask': 'fire_sank'}, BH.DATA); BH_GRAVES = BH.taberah_and_quail({'ask': 'graves'}, BH.DATA); BH_THREE = BH.march({'ask': 'three_days'}, BH.DATA)
assert BH_EDGE[1] == ['fire_sank'] and BH_SANK[0] == "sank at Moses' prayer" and BH_GRAVES[0].startswith('Kibroth-hattaavah') and BH_GRAVES[1] == ['buried'] and BH_THREE[0].startswith("three days' journey"), (BH_EDGE[:2], BH_SANK[0], BH_GRAVES[:2])
SL_ABILITY = SL.decree({'ask': 'ability'}, SL.DATA); SL_EGYPT = SL.decree({'ask': 'egypt_will_hear'}, SL.DATA); SL_OFFER = SL.decree({'ask': 'offer_second_seat'}, SL.DATA); SL_PARDON = SL.decree({'ask': 'pardon'}, SL.DATA); SL_DAY = SL.decree({'ask': 'day_for_year'}, SL.DATA); SL_GIANTS = SL.spies({'ask': 'giants'}, SL.DATA); SL_FORTY = SL.spies({'ask': 'forty_days'}, SL.DATA)
assert SL_ABILITY[0].startswith('the ability — yekholet') and SL_EGYPT[0].startswith("Moses' Egypt argument") and SL_OFFER[0].startswith("the offer's second seat") and SL_PARDON[1] == ['pardoned'] and SL_DAY[0].startswith('[40, 40]') and SL_GIANTS[0].startswith('Ahiman') and SL_FORTY[0].startswith('40 days'), (SL_ABILITY[0][:40], SL_OFFER[0][:40], SL_PARDON[:2])
OS_MURMUR = OS.the_spies_read_back({'ask': 'the_murmuring'}, OS.DATA); OS_PRESUME = OS.the_spies_read_back({'ask': 'the_presumption'}, OS.DATA)
assert OS_MURMUR[1] == ['accepted'] and OS_MURMUR[0].startswith('the murmuring (1:27-28)') and OS_PRESUME[0].startswith('the presumption (1:41-44)') and len(OS.READBACK) == 42, (OS_MURMUR[0][:40], OS_PRESUME[0][:40])
OH_NATIONS = OH.the_one_god({'ask': 'to_dispossess_nations'}, OH.DATA); OH_LOVED = OH.the_one_god({'ask': 'because_he_loved_your_fathers'}, OH.DATA); OH_FIRE = OH.no_image({'ask': 'consuming_fire_jealous_god'}, OH.DATA); OH_TABLETS = OH.horeb_retold({'ask': 'the_ten_words_and_the_tablets'}, OH.DATA); OH_MERCIFUL = OH.the_exile_case({'ask': 'the_merciful_god'}, OH.DATA)
assert OH_NATIONS[0].startswith('to dispossess nations (4:38)') and '9:1 the kin' in OH_NATIONS[0] and OH_LOVED[0].startswith('because he loved your fathers (4:37)') and OH_FIRE[0].startswith('a consuming fire, a jealous God (4:24)') and OH_TABLETS[1] == ['tablets_delivered'] and OH_MERCIFUL[1] == ['accepted'] and len(OH.READBACK) == 11, (OH_NATIONS[0][:60], OH_TABLETS[:2])
CH_TABLETS = CH.the_voice_and_the_request({'ask': 'the_tablets_given_to_me'}, CH.DATA); CH_FIRST = CH.the_first_tablet({'ask': 'the_first_word'}, CH.DATA)
assert CH_TABLETS[0].startswith('the tablets given to me (5:22) — tablets_given FOUND at (1, 4, 17)') and CH_FIRST[1] == ['accepted'] and len(CH.READBACK) == 21, (CH_TABLETS[0][:70],)
HI_TEST = HI.the_test_and_the_right({'ask': 'you_shall_not_test'}, HI.DATA)
assert HI_TEST[0].startswith('you shall not test (6:16)') and 'Massah' in HI_TEST[0] and len(HI.READBACK) == 7, (HI_TEST[0][:60],)
SN_SEVEN = SN.the_seven_nations({'ask': 'the_seven'}, SN.DATA); SN_BAN = SN.the_seven_nations({'ask': 'the_ban'}, SN.DATA)
assert SN_SEVEN[0].startswith('the seven (7:1)') and SN_BAN[0].startswith('the ban (7:2)') and len(SN.READBACK) == 21, (SN_SEVEN[0][:40], SN_BAN[0][:40])
SD_CALF = SD.day('aaron_chatat_run')
assert SD_CALF['v'] == 'calf' and SD_CALF['fx'] == ['accepted'], SD_CALF
GL_FORTY = GL.the_way_of_forty_years({'ask': 'forty_years'}, GL.DATA)
assert GL_FORTY[0].startswith('forty years (8:2, 8:4)') and len(GL.READBACK) == 18, (GL_FORTY[0][:40],)
print('ER.calf(saru_stiff) =', ER_STIFF['v'], '— the stiff neck a state, no write; ER.calf(fourth_verb_decides) =', ER_FOURTH['v'], '— the fourth verb the retelling drops')

# ---- THE READBACK'S SIXTH FORM — THE RETELLING OF A STRETCH (THE LOOP's step 6; after T1-T5): Moses tells the calf in his own voice — its rows REFERENCE ROWS against
# the tape's lines by kind and first verse (tape_kind, tape_verse) or the kin's cells by CALL (cell, cell_found), never a second write (T1's form); ONE row fills a
# hole WITH A WRITE (9:20 Aaron's peril — T2's form, 3b's: the retrograde line and its status); FOUR rows retell a STRETCH between two markers (the three forties),
# graded against the clock's own arithmetic (stretch: the markers and the days — asserted on the running world at DA4 and in Q22) ----
GRADES = ('VERBATIM', 'VARIANT', 'TURNED', 'SHORTENED', 'EXPANDED', 'SUPPLIED', 'DISAGREES')
def rb(verses, told, grade, why, tape_kind=None, tape_verse=None, cell=None, cell_found=None, entry='', open_=False, stretch=None, write=None):
    assert grade in GRADES, grade
    if grade == 'SUPPLIED':
        assert tape_kind is None and cell is None and isinstance(write, str) and write, ("the sixth form's SUPPLIED row fills a hole WITH A WRITE — no line, no cell, the write named", verses)
    else:
        assert (tape_kind is None) != (cell is None) and write is None, ('one of the tape or the cell; no write on a reference row', verses)
        if cell is not None: assert cell_found is True, ('the kin cell CALLED and found', verses, cell)
    if stretch is not None: assert set(stretch) == {'from', 'to', 'days'} and stretch['days'] == 40, ('a stretch names its two markers and its days', verses, stretch)
    return {'verses': verses, 'told': told, 'tape_kind': tape_kind, 'tape_verse': tape_verse, 'cell': cell, 'cell_found': cell_found, 'entry': entry, 'grade': grade, 'why': why, 'open': open_, 'law': False, 'stretch': stretch, 'write': write}
FIRST_FORTY = {'from': 'Exod 24:18', 'to': 'Exod 32:19', 'days': CLOCK['first_forty']}; SECOND_FORTY = {'from': 'Exod 32:30', 'to': 'Exod 34:4', 'days': CLOCK['second_forty']}
READBACK = [
    rb('Deut 9:1', "nations greater and mightier than you", 'VERBATIM', "VERBATIM IN KIND — 4:38's clause (four tokens shared) and 7:1's 'seven nations greater and mightier than you' said again without the count; the kin's cells the dispossession and the seven", cell="OH.the_one_god('to_dispossess_nations') — 4:38; SN.the_seven_nations('the_seven') — 7:1", cell_found=OH_NATIONS[1] == ['accepted'] and SN_SEVEN[1] == ['accepted'], entry="to dispossess nations (4:38) — the open dispossess debit READ, 9:1 the kin named there; the seven (7:1) — counted by its own verse"),
    rb('Deut 9:1', "cities great and fortified to the heavens", 'VARIANT', "THE SPELLING — 1:28's ובצורת made ובצרת (the same four tokens, one seat each); the hyperbole rule (Chullin 90b:12; Tamid 29a:8; the Sifrei 25:4) reads both; the kin's cell the murmuring — the spies' words in the people's mouths there, Moses' own here", cell="OS.the_spies_read_back('the_murmuring') — 1:28", cell_found=OS_MURMUR[1] == ['accepted'], entry="the murmuring (1:27-28) — 'greater and taller than we' the plain sense of 13:31 (Sotah 35a:7): TURNED there"),
    rb('Deut 9:2', "a people great and tall, the sons of the Anakim … who can stand before the sons of Anak", 'VERBATIM', "VERBATIM IN KIND — 1:28's 'a people great and tall' (the phrase's two seats; five tokens shared) with the giants of Numbers 13:22 (the spies' cell); 'who can stand before' the retelling's own question", cell="SL.spies('giants') — Num 13:22; OS.the_spies_read_back('the_murmuring') — 1:28", cell_found=SL_GIANTS[1] == [FX.NONE] and OS_MURMUR[1] == ['accepted'], entry="the giants (Num 13:22) — Ahiman, Sheshai, Talmai (Sotah 34b:9-10); the murmuring (1:27-28)"),
    rb('Deut 9:3', "a consuming fire", 'VERBATIM', "VERBATIM IN KIND — 4:24's phrase (the Torah's two seats; six tokens shared with 4:24, nine with 31:3's 'he passes over before you'); the fire the dispossessor here, the jealous God there; Onkelos the Memra (the Word) a consuming fire at both", cell="OH.no_image('consuming_fire_jealous_god') — 4:24", cell_found=OH_FIRE[1] == ['accepted'], entry="a consuming fire, a jealous God (4:24) — jealousy at the worshipper, not the idol (Avodah Zarah 54b-55a)"),
    rb('Deut 9:5', "the word which the LORD swore to your fathers, to Abraham, to Isaac and to Jacob", 'VERBATIM', "VERBATIM IN KIND — 7:8's form on the oath's line: sworn_by_himself (Genesis 22:16-18 — 'by myself I have sworn'); the triad's eleven seats; 'swore' the verb's one chapter seat", tape_kind='sworn_by_himself', tape_verse='Gen 22:16', entry="sworn_by_himself — Gen 22:16-18 (subject abraham; mamre.moriah by CALL at 6b); seven_nations.the_holy_people('the_oath') the form"),
    rb('Deut 9:6', "a stiff-necked people", 'VERBATIM', "VERBATIM IN KIND — Exodus 33:3's clause (seven tokens shared); the phrase's six Bible seats all the calf's (32:9, 33:3, 33:5, 34:9; 9:6, 9:13); A STATE IN THE FIRST TELLING — no write, no entry (the one database scanned: %r); the kin's cell counts the seats" % (STIFF_SCAN,), cell="ER.calf('saru_stiff') — Exod 32:9", cell_found=ER_STIFF['v'] == (3, 6), entry="saru_stiff — 'turned quickly' three seats, 'stiff-necked' six: the phrase born at the calf (the erection's count)"),
    rb('Deut 9:7', "from the day you came out of the land of Egypt until you came to this place you have been rebellious with the LORD", 'EXPANDED', "THE WHOLE SPAN MADE ONE REBELLION — the ten trials' list (Arakhin 15a:14: two at the sea, two with water, two with the manna, two with the quail, the calf, Paran) read back as one 'from the day … until this place'; 'remember, do not forget' the one seat; the kin's cell the list", cell="ES.trials('ten_list', 'count_by_exodus') — Num 14:22", cell_found=ES_TRIALS['v'][0] == 'two_at_the_sea' and ES_SIX['v'] == 6, entry="ten_list — Arakhin 15a:14's ten; count_by_exodus — six narrated by Exodus 19 (tested_the_lord)"),
    rb('Deut 9:8', "at Horeb you provoked the LORD, and the LORD was angry with you to destroy you", 'VARIANT', "THE MAKING TOLD AS PROVOKING — Exodus 32:4's 'he made it a molten calf' (calf_made, subject aaron, worshipped False — forbidden from its making, Avodah Zarah 52a:4) becomes 'at Horeb you provoked'; 'was angry' the hithpael's four book seats; the crowns stripped 'from Mount Horeb' (Exodus 33:6 — Shabbat 88a:7) no line", tape_kind='calf_made', tape_verse='Exod 32:4', entry="calf_made — Exod 32:4 (aaron; worshipped False); erection.calf('molten_calf') by CALL — the four seats"),
    rb('Deut 9:9', "when I went up the mountain to receive the tablets of stone, the tablets of the covenant … I stayed on the mountain forty days and forty nights; bread I did not eat and water I did not drink", 'EXPANDED', "THE FIRST FORTY AS A STRETCH — the tape's moses_ascended 'first' (24:18, five tokens shared) with the fasting told IN THE FIRST PERSON (the phrase's two seats both this chapter's; Exodus 34:28's third-person form the second ascent's — Yoma 75b:11 cites 9:9 itself: the fasting's seat this chapter's own, the design's 'supplied from 34:28' corrected); the stretch M['ascent'] (1, 3, 7) → M['breaking'] (1, 4, 17) = 40 by the calendar, Ta'anit 28b:9's 24 + 16", tape_kind='moses_ascended', tape_verse='Exod 24:18', entry="moses_ascended 'first' — Exod 24:18 under the marker M['ascent'] = the seventh of Sivan (Ta'anit 28b); erection.ascent('seventeenth_tammuz', 'sheet_taanit_4_6') by CALL", stretch=FIRST_FORTY),
    rb('Deut 9:10', "the LORD gave me the two tablets of stone written with the finger of God, and on them according to all the words which the LORD spoke with you in the mountain out of the midst of the fire on the day of the assembly", 'VERBATIM', "VERBATIM IN KIND — Exodus 31:18's 'written with the finger of God' (five tokens shared; the phrase's two seats) with 5:22's 'and gave them to me' (5:4's six; 10:4's ten forward); the tape's tablets_given (chapter 4's retrograde line, dated at the breaking); Megillah 19b:5 'all the words'", tape_kind='tablets_given', tape_verse='Deut 4:13', entry="tablets_given — Deut 4:13 (first_telling Exod 31:18; dated (1, 4, 17)); OH.horeb_retold('the_ten_words_and_the_tablets') and CH.the_voice_and_the_request('the_tablets_given_to_me') by CALL"),
    rb('Deut 9:11', "at the end of forty days and forty nights the LORD gave me the two tablets of stone, the tablets of the covenant", 'VERBATIM', "VERBATIM IN KIND — the same line referenced a second time (6b's manna_fell thrice the form): the giving at the stretch's END, the breaking's day (1, 4, 17) — given and broken on one day (Ta'anit 28b:9); 'at the end of forty days' the phrase's three seats; the two spellings of the tablets in one verse (a DATA row)", tape_kind='tablets_given', tape_verse='Deut 4:13', entry="tablets_given — Deut 4:13, dated (1, 4, 17) = the stretch's end", stretch=FIRST_FORTY),
    rb('Deut 9:12', "arise, go down quickly from here, for your people whom you brought out of Egypt have corrupted; they have turned aside quickly from the way which I commanded them; they have made them a molten image", 'VARIANT', "TWO VERSES MADE ONE — Exodus 32:7-8 (nine tokens shared with 32:8, six with 32:7): 'go, get down' made 'arise, go down quickly' (the one seat), 'a molten calf' made 'a molten image'; God's word quoted inside the retelling (the divine frame at 9:12) — 32:7-10 has NO LINE on the tape (speech), the calf's line the reference", tape_kind='calf_made', tape_verse='Exod 32:4', entry="calf_made — Exod 32:4; the calf's cause pleaded and conceded (Berakhot 32a:8, 32a:13)"),
    rb('Deut 9:13', "I have seen this people, and behold, it is a stiff-necked people", 'VERBATIM', "VERBATIM — Exodus 32:9 ELEVEN OF THIRTEEN tokens (the diff 'to me, saying' for 'to Moses'): God's word quoted whole — the closest row of the chapter; the kin's cell the stiff neck's count", cell="ER.calf('saru_stiff') — Exod 32:9", cell_found=ER_STIFF['v'] == (3, 6), entry="saru_stiff — the six seats; the DIFF the two tokens of address"),
    rb('Deut 9:14', "let Me alone, that I may destroy them and blot out their name from under heaven; and I will make of you a nation mightier and more numerous than they", 'VARIANT', "THE OFFER'S THIRD FORM — Exodus 32:10's 'let Me be … I will make of you a great nation' (three tokens shared) and Numbers 14:12's 'greater and mightier than they' (three) made 'mightier and more numerous than they' (the one seat); 'blot out their name from under heaven' supplied; 'let Me alone' a second hapax for 32:10's; the tape's intercession the reference (the seizing, the chair — Berakhot 32a:16-17; every promise fulfilled — 7a:35)", tape_kind='moses_interceded', tape_verse='Exod 32:11', entry="moses_interceded plea relent — Exod 32:11-14 (decree_relented ONE on Israel); erection.calf('seized', 'three_legged') by CALL; shelach.decree('offer_second_seat') the three seats"),
    rb('Deut 9:15', "I turned and came down from the mountain, and the mountain burning with fire, and the two tablets of the covenant on my two hands", 'VARIANT', "THE HANDS AND THE FIRE — Exodus 32:15's 'Moses turned and went down … the two tablets in his hand' (four tokens shared) made 'on my two hands' (the one seat) with 'the mountain burning with fire' added (4:11's, 5:23's phrase); the tape's tablets_broken the line the descent belongs beside", tape_kind='tablets_broken', tape_verse='Exod 32:19', entry="tablets_broken — Exod 32:19 (breaker moses; the seventeenth of Tammuz)"),
    rb('Deut 9:16', "I looked, and behold, you had sinned against the LORD your God: you had made you a molten calf; you had turned aside quickly from the way which the LORD commanded you", 'VARIANT', "THE VISION FORMULA SUPPLIED — 'I looked, and behold' (the prophets' form) before Exodus 32:8's 'turned aside quickly' (four tokens) and 32:4's 'a molten calf' (three); 'the calf which you had made' the making named", tape_kind='calf_made', tape_verse='Exod 32:4', entry="calf_made — Exod 32:4; 'a molten calf' the four seats (erection.calf('molten_calf'))"),
    rb('Deut 9:17', "I took hold of the two tablets and threw them from my two hands and broke them before your eyes", 'EXPANDED', "IN MOSES' OWN WORDS — Exodus 32:19 shares ONE token: 'he threw the tablets from his hand and broke them under the mountain' told as 'I took hold … threw them from my two hands … broke them BEFORE YOUR EYES' (the public breaking added; 'took hold' the lemma's first Torah seat); THE BREAKING APPROVED at three seats (Shabbat 87a:5; Menachot 99b:1; Bava Batra 14b:7 — the kin's cell); Moses' might from these verbs (Nedarim 38a:8)", tape_kind='tablets_broken', tape_verse='Exod 32:19', entry="tablets_broken — Exod 32:19; erection.tablets('breaking_ratified') by CALL = yishar_kochakha; the fragments owed to chapter 10"),
    rb('Deut 9:18', "I fell down before the LORD as at the first, forty days and forty nights; bread I did not eat and water I did not drink, because of all your sin which you sinned", 'EXPANDED', "THE SECOND FORTY AS A STRETCH — Exodus 32:30-31 ('on the morrow … Moses returned to the LORD') has NO forty: the forty days SUPPLIED by the retelling and held by the clock as the stretch M['morrow'] (1, 4, 18) → M['second_ascent'] (1, 5, 29) = 40; the tape's moses_interceded plea blot_me the line the stretch begins with; 'as at the first' the AS_WHEN form (a run citation of 9:9's stretch); 'all your sin' the confession specified (Yoma 86b:14)", tape_kind='moses_interceded', tape_verse='Exod 32:31', entry="moses_interceded plea blot_me — Exod 32:31-33 (blotted_from_the_book ONE on the-sinners; sin_specified True); the marker M['morrow'] at 32:30", stretch=SECOND_FORTY),
    rb('Deut 9:19', "for I was afraid of the anger and the wrath which the LORD was angry with you to destroy you; and the LORD hearkened to me that time also", 'TURNED', "THE RELENTING TOLD AS HEARKENING — Exodus 32:14's 'and the LORD relented of the evil' (one token shared) becomes 'the LORD hearkened to me' (9:19 and 10:10 the phrase's two seats); 'I was afraid of the anger and the wrath' Moses' own fear supplied (Nedarim 32a:4; Bava Batra 9b:7); decree_relented the entry, no second write; Onkelos 'accepted my prayer'", tape_kind='moses_interceded', tape_verse='Exod 32:11', entry="moses_interceded plea relent — Exod 32:11-14: decree_relented ONE on Israel (the entry referenced); erection.calf('relent') the five seats"),
    rb('Deut 9:20', "and with Aaron the LORD was very angry, to destroy him; and I prayed for Aaron also at that time", 'SUPPLIED', "AARON'S PERIL TOLD ONLY HERE — Exodus 32:21-24 (Aaron's report — read and not translated, Mishnah Megillah 4:10) and 32:35 (the plague 'which Aaron made') share one and two tokens; no anger at Aaron, no prayer for him in the first telling: THE TAPE'S HOLE — no line, no cell, the one database scanned (%r); FILLED WITH A WRITE: the act prayed_for_aaron written ONCE at its own day by the RETROGRADE marker at Deut 9:20 (M['aaron_told'] = M['morrow'], (1, 4, 18) — 'at that time' the second forty's ascent; Sanhedrin 102a:5 a time ordained for calamity), the status destruction_halved on aaron (Vayikra Rabbah 10:5 — half the edict withheld, two died and two remained); the stretch ended by the forward marker at 9:21; the retelling of the peril TRANSLATED where the report is not (the asymmetry)" % (AARON_PERIL_SCAN,), entry="none before this sitting — the retrograde line prayed_for_aaron (subject moses, for aaron; dated (1, 4, 18)) and its write destruction_halved (a STATUS on aaron; DA2)", write='destruction_halved'),
    rb('Deut 9:21', "your sin, the calf which you had made, I took and burned it with fire and crushed it, grinding it thoroughly until it was fine as dust; and I threw its dust into the brook that descends from the mountain", 'VARIANT', "THE FOURTH VERB DROPPED — Exodus 32:20's four verbs (burned, ground, scattered on the water, MADE THE CHILDREN OF ISRAEL DRINK; seven tokens shared, 'until it was fine') retold as burning, crushing, grinding (two infinitive absolutes) and the dust into the brook (the one seat; the Kidron's kin) — NO DRINKING: R. Yosei's proof stands on this telling's verbs (Avodah Zarah 44a:1), the Rabbis' answer on the first telling's fourth verb (44a:2 — a test as the sotah's); the tape's calf_destroyed carries purpose to_test from that row", tape_kind='calf_destroyed', tape_verse='Exod 32:20', entry="calf_destroyed — Exod 32:20 + Avodah Zarah 44a:2 (destroyer moses, idol the-calf, purpose to_test); erection.calf('four_verbs', 'fourth_verb_decides', 'nullification_dispute') by CALL"),
    rb('Deut 9:22', "at Taberah", 'VERBATIM', "VERBATIM IN KIND — the tape's fire_of_the_lord_burned (Numbers 11:1-3, name Taberah, 'Moses prayed'; the name's two Bible seats) — the first of three names in one verse, OUT OF THE TAPE'S ORDER (Massah earlier on the tape); NOT AMONG THE TEN TRIALS (Arakhin 15a:14 — a DATA row); fire_sank a STATUS on Israel unmoved", tape_kind='fire_of_the_lord_burned', tape_verse='Num 11:1', entry="fire_of_the_lord_burned — Num 11:1-3 (edge, the proselytes, 'Moses prayed', Taberah); beha.taberah_and_quail('fire_at_edge', 'fire_sank') by CALL; the marker M['taberah'] (Ta'anit 29a:3)"),
    rb('Deut 9:22', "and at Massah", 'VERBATIM', "VERBATIM IN KIND — the tape's named line at Exodus 17:7 ('Massah and Meribah — testing and quarrel', by moses; the name's five Bible seats); 6:16's 'as you tested at Massah' the second reference (hear_o_israel by CALL — test_barred stands); the fourth of the ten trials (Arakhin 15a:20 — Rephidim)", tape_kind='named', tape_verse='Exod 17:7', entry="named — the-place-rephidim 'Massah and Meribah' (Exod 17:7, by moses); rock_struck at 17:6 beside it; HI.the_test_and_the_right('you_shall_not_test') by CALL"),
    rb('Deut 9:22', "and at Kibroth-hattaavah", 'VERBATIM', "VERBATIM IN KIND — the tape's quail_and_plague (Numbers 11:31-35, graves Kibroth-hattaavah; the name defective here and at 33:16-17, plene at 11:34-35); the second quail among the ten trials (Arakhin 15a:14); Onkelos 'the graves of those who asked'", tape_kind='quail_and_plague', tape_verse='Num 11:31', entry="quail_and_plague — Num 11:31-35 (the-lusters; graves Kibroth-hattaavah; hazeroth True); beha.taberah_and_quail('graves') by CALL = the graves of lust (buried)"),
    rb('Deut 9:23', "when the LORD sent you from Kadesh-barnea, saying: go up and possess the land which I have given you", 'VARIANT', "THE SENDING RETOLD AS GOD'S — 1:21's 'go up, take possession' (singular, Moses' word) made 'go up and possess' (plural, the one seat) in the LORD's mouth 'from Kadesh-barnea' (the name's eight seats); the kin's cell the first form's rows on the same acts (the asking, the murmuring, the presumption)", cell="OS.the_spies_read_back('the_murmuring', 'the_presumption') — 1:26-28, 1:41-44", cell_found=OS_MURMUR[1] == ['accepted'] and OS_PRESUME[1] == ['accepted'], entry="the murmuring (1:27-28) TURNED; the presumption (1:41-44) EXPANDED — the first form's rows"),
    rb('Deut 9:23', "you rebelled against the commandment of the LORD your God, and you did not believe Him, nor hearkened to His voice", 'VARIANT', "THE REBELLION IN THREE VERBS — 1:26's 'you rebelled against the commandment of the LORD your God' (five tokens shared) with 'did not believe Him' (the one seat; 1:32's participle) and 'nor hearkened to His voice' (the one seat) added; the tape's congregation_wept (Numbers 14:1-4 — the night, the murmur, the head) the act; the tenth trial that sealed the sentence (Arakhin 15a:10 — 'now ten times'); decree_declared (14:26-35) the sentence unmoved", tape_kind='congregation_wept', tape_verse='Num 14:1', entry="congregation_wept — Num 14:1-4 (israel; 'that night' — the Ninth of Av, Ta'anit 29a:7; slot night); decree_declared at 14:26 the sentence; the marker M['spies_return'] (2, 5, 9)"),
    rb('Deut 9:24', "you have been rebellious with the LORD from the day I knew you", 'VERBATIM', "VERBATIM IN KIND — 9:7's doublet (four tokens shared: 'rebellious you have been with the LORD'); 'from the day I knew you' the one seat for 9:7's 'from the day you came out of Egypt'; the kin's cell the ten trials' span", cell="ES.trials('ten_list') — Num 14:22", cell_found=ES_TRIALS['v'][-1] == 'one_at_paran', entry="ten_list — the calf and Paran the last two of the ten (Arakhin 15a:14)"),
    rb('Deut 9:25', "so I fell down before the LORD the forty days and the forty nights that I fell down, because the LORD had said He would destroy you", 'VERBATIM', "VERBATIM IN KIND — 9:18's doublet with the article ('the forty days and the forty nights' — the Bible's one seat of the form; 'that I fell down' the hithpael's third chapter seat): THE SAME STRETCH told a second time (M['morrow'] → M['second_ascent'] = 40); 'because the LORD had said He would destroy you' (the one seat) the stretch's reason; the prolonging of prayer's proof-text (Berakhot 32b:8; 34a:11); nipul among the ten names (Devarim Rabbah 2:1)", tape_kind='moses_interceded', tape_verse='Exod 32:31', entry="moses_interceded plea blot_me — Exod 32:31-33: the second forty's line; the stretch's dates (1, 4, 18) → (1, 5, 29)", stretch=SECOND_FORTY),
    rb('Deut 9:26', "Lord GOD, do not destroy Your people and Your inheritance, which You redeemed in Your greatness, which You brought out of Egypt with a mighty hand", 'VARIANT', "THE PLEA'S OBJECT CHANGED — Exodus 32:11's 'why does Your wrath burn against Your people whom You brought out of the land of Egypt with great power and a mighty hand' (five tokens shared) made 'do not destroy Your people and Your inheritance which You redeemed' (the one seat; 'Your people and Your inheritance' 9:26, 9:29 and 1 KINGS 8:51 — Solomon quoting this telling at the temple's dedication: the run outside the Torah); the vow annulled (Berakhot 32a:19); Onkelos 'in Your might'", tape_kind='moses_interceded', tape_verse='Exod 32:11', entry="moses_interceded plea relent — Exod 32:11-14 (vayechal; the LORD relented); erection.calf('vayechal', 'vow_annulled') by CALL"),
    rb('Deut 9:27', "remember Your servants, Abraham, Isaac and Jacob; do not turn to the stubbornness of this people, nor to its wickedness, nor to its sin", 'VARIANT', "ISRAEL MADE JACOB — Exodus 32:13's 'remember Abraham, Isaac and ISRAEL Your servants, to whom You swore by Yourself' (three tokens shared: 'to Abraham, to Isaac') made 'remember Your servants Abraham, Isaac and JACOB' ('Your servants' first here, last there; the oath by Yourself dropped) with 'do not turn to the stubbornness' added (the Bible's one seat of the noun); the merit of the fathers pleaded — the three-legged chair (Berakhot 32a:17), the oath by the Name endures (32a:24); a PARAMETER with two arms on the shelf (Shabbat 55a:11 — ceased / stands; the four dates 55a:13-16, 2 Kings 13:23 the last)", tape_kind='moses_interceded', tape_verse='Exod 32:11', entry="moses_interceded plea relent — Exod 32:11-14 (32:13 the fathers' oath); erection.calf('three_legged', 'oath_endures') by CALL"),
    rb('Deut 9:28', "lest the land from which You brought us out say: because the LORD was not able to bring them into the land which He promised them, and because He hated them, He brought them out to kill them in the wilderness", 'VARIANT', "THE TAUNT'S FOURTH FORM — Numbers 14:16's 'because the LORD was not ABLE [the feminine noun] to bring this people into the land which He swore to them, He slaughtered them in the wilderness' (seven tokens shared; the noun kept — Berakhot 32a:27) with Exodus 32:12's 'why should the Egyptians say … to slay them in the mountains' (two) and 1:27's 'in His hatred … to destroy us' — the speaker THE LAND, the hatred from 1:27, the wilderness from Numbers: FOUR FORMS (a DATA row) and THREE SWAPS (Israel/Jacob, the Egyptians/the land, the mountains/the wilderness); the tape's line at Kadesh the reference (its first verse 14:11 — read at the callees' print, the design wrote 14:13)", tape_kind='moses_pleaded_on_the_attributes', tape_verse='Num 14:11', entry="moses_pleaded_on_the_attributes — Num 14:11-19 (offer 'I will make of you a greater nation', argument 'Egypt will hear', the attributes); shelach.decree('ability', 'egypt_will_hear', 'pardon') by CALL"),
    rb('Deut 9:29', "and they are Your people and Your inheritance whom You brought out by Your great power and Your outstretched arm", 'VERBATIM', "VERBATIM IN KIND — Exodus 32:11's 'Your people whom You brought out of the land of Egypt with great power and a mighty hand' said again with 'Your inheritance' and 'Your outstretched arm' (4:34's, 5:15's, 26:8's form; 4:37's 'His great power' by CALL); 'by Your great power' 9:29 alone defective — NEHEMIAH 1:10 and Jeremiah 32:17 plene, Nehemiah quoting this telling (1 Kings 8:51's four tokens too)", tape_kind='moses_interceded', tape_verse='Exod 32:11', entry="moses_interceded plea relent — Exod 32:11 ('with great power and a mighty hand'); OH.the_one_god('because_he_loved_your_fathers') by CALL — 4:37's great power"),
]
RB_GRADES = collections.Counter(r['grade'] for r in READBACK)
assert len(READBACK) == 32 and RB_GRADES == collections.Counter({'VERBATIM': 14, 'VARIANT': 12, 'EXPANDED': 4, 'TURNED': 1, 'SUPPLIED': 1}) and not any(r['open'] for r in READBACK), (len(READBACK), RB_GRADES)
assert sum(1 for r in READBACK if r['tape_kind']) == 22 and sum(1 for r in READBACK if r['cell']) == 9 and all(r['cell_found'] for r in READBACK if r['cell']) and [r['verses'] for r in READBACK if r['grade'] == 'SUPPLIED'] == ['Deut 9:20'] and [r['verses'] for r in READBACK if r['stretch']] == ['Deut 9:9', 'Deut 9:11', 'Deut 9:18', 'Deut 9:25'], "the tape rows twenty-two, the kin's cells nine, every cell found; the one SUPPLIED row Aaron's peril with its write; the four stretch rows"
HOLES = [
    {'verses': 'Deut 9:20', 'hole': "AARON'S PERIL — 'and with Aaron the LORD was very angry, to destroy him; and I prayed for Aaron also at that time'", 'why': "TOLD ONLY HERE — Exodus 32:21-24 (Aaron's report) and 32:35 (the plague) hold no anger at Aaron and no prayer for him; no line on the tape's Exodus 24-34 stretch (the recon), no cell in any runner, no entry on aaron (the one database scanned: %r); the milluim's 'take Aaron and his sons' and Leviticus 9:7's re-acceptance the aftermath the ledgers read from this verse" % (AARON_PERIL_SCAN,), 'write': "prayed_for_aaron — the act written ONCE at its own day by the RETROGRADE marker at Deut 9:20 (M['aaron_told'] = M['morrow'], (1, 4, 18)); destruction_halved — a STATUS on aaron (Vayikra Rabbah 10:5: half the edict withheld — two died and two remained) (DA1, DA2)"},
]
OPEN_ROWS = [
    {'name': "the calf's own day", 'verses': 'Exod 32:1-6; Deut 9:8, 9:12, 9:16', 'the_tape': "calf_made (Exod 32:4) and moses_interceded relent (32:11-14) sit on the ascent's day (1, 3, 7) — the last marker's day inherited, the calf's own day UNMARKED", 'the_shelf': "Shabbat 89a:6 — boshesh read ba'u shesh: the fortieth day's sixth hour = the sixteenth of Tammuz (%s by the clock — the ascent + 39); Shabbat 88b:2 the bride under her canopy" % (CLOCK['calf_day'],), 'the_decision': "OPEN TO THE OWNER — no marker this sitting (a change to the Exodus stretch is not this chapter's; the design's decision 3); Shabbat 89a:6 the marker's shelf source if he rules it"},
    {'name': "the second ascent's date", 'verses': 'Exod 34:2-4, 34:28; Deut 9:18, 9:25, 10:10', 'the_tape': "M['second_ascent'] = M['second_tablets'] − 40 = %s (the twenty-ninth of Av by the machine's subtraction from 10 Tishri, CAL_PARAMS second_tablets_given — Ta'anit 30b)" % (CLOCK['second_ascent'],), 'the_shelf': "the tradition's first of Elul (Seder Olam Rabbah 6 — UNREACHABLE in the export at the docket; 'not on the local Babylonian shelf' the parameter's own open row) two days after the machine's (%d days by the calendar)" % (CLOCK['elul_1_minus_second_ascent'],), 'the_decision': "OPEN — the parameter's own row; no retype without the shelf's row (the design's decision 4)"},
]
assert len(HOLES) == 1 and len(OPEN_ROWS) == 2

DATA = {
    'the_readback': {'value': READBACK, 'holes': HOLES, 'open_rows': OPEN_ROWS, 'settings': {'the_form': "THE READBACK'S SIXTH FORM (THE LOOP.md step 6; THE DEUTERONOMY WALK 7b, 2026-09-19): THE RETELLING OF A STRETCH — after T1 the narrative retelling (1b), T2 the retelling that fills a hole (2b, 3b), T3 the retelling inside a law (4b), T4 the laws' form on the kin (5b), T5 the retelling of a state (6b): chapter 9 is Moses telling the calf in his own voice, so its rows are T1's REFERENCE ROWS against the tape's lines by kind and first verse or the kin's cells by CALL (God's word VERBATIM at 9:13, Moses' acts in his own words at 9:17), T2's one hole filled WITH A WRITE (Aaron's peril, 9:20 — the retrograde line and its status), AND a row-kind no chapter had: 'forty days and forty nights' told at 9:9, 9:11, 9:18, 9:25 is not a LINE but a STRETCH between two markers, graded against THE CLOCK'S OWN ARITHMETIC (the days between the markers — 40 and 40, the third forty 10:10's) and the answer sheet's dates (Mishnah Ta'anit 4:6's seventeenth of Tammuz, Ta'anit 28b:9's seventh of Sivan and its 24 + 16 — MATCH): THE CLOCK READ BACK; THIRTY-TWO rows — VERBATIM 14 / VARIANT 12 / EXPANDED 4 / TURNED 1 / SUPPLIED 1; twenty-two on the tape, nine in the kin's cells; four stretch rows; no row OPEN (the two OPEN rows are the clock's — the calf's own day, the second ascent's date); the hole one", 'the_decisions': "(1) Aaron's peril an ACT told only in the retelling — written ONCE at its own day by a RETROGRADE marker (the retelling rules; 3b's form), the write destruction_halved a STATUS on aaron NAMED BY THE DOCKET (Vayikra Rabbah 10:5); (2) the stiff neck a STATE in the first telling — no write, no supplied grade, the rows by CALL; (3) the calf's own day unmarked — OPEN; (4) the second ascent's date — OPEN, the parameter's own", 'the_first_verses': "the tape's lines by kind and first verse: sworn_by_himself Gen 22:16, calf_made Exod 32:4, moses_ascended Exod 24:18 (the first) and 34:2 (the second — its marker at 34:4), tablets_given Deut 4:13 (dated at the breaking), moses_interceded Exod 32:11 (relent) and 32:31 (blot_me), tablets_broken 32:19, calf_destroyed 32:20, fire_of_the_lord_burned Num 11:1, named Exod 17:7, quail_and_plague Num 11:31, congregation_wept Num 14:1, moses_pleaded_on_the_attributes Num 14:11 (the design wrote 14:13 — the line's source begins at 14:11, read at the callees' print: 6b's lesson a second time)"}},
    'the_clock_read_back': {'value': CLOCK, 'settings': {'the_markers': "Exod 24:18 M['ascent'] (1, 3, 7) — Ta'anit 28b:8-9 (R. Yosei's seventh); Exod 32:19 M['breaking'] (1, 4, 17) — Mishnah Ta'anit 4:6; Exod 32:30 M['morrow'] = breaking + 1 (1, 4, 18) — the ink's own day-word; Exod 34:4 M['second_ascent'] = second_tablets − 40 (1, 5, 29) — Ta'anit 30b's Yom Kippur; the three forties 40 / 40 / 40 (the last 10:10's, forward)", 'the_arithmetic': "Ta'anit 28b:9 — twenty-four days remaining in Sivan (the seventh to the thirtieth) plus the first sixteen of Tammuz = forty: REPRODUCED by the calendar (Sivan thirty days that year on the tape's calendar); the two arms of the giving's day (Shabbat 88a:3 — the sixth / the seventh): the tape holds R. Yosei's, the Rabbis' would move every date of the three forties by one day (recorded, not taken)", 'the_grade': "MATCH — the answer sheet's date and the clock agree by the row's own arithmetic; asserted on the running world's markers at DA4 and Q24", 'the_calf_day': "the fortieth day's sixth hour = the sixteenth of Tammuz (Shabbat 89a:6) — the ascent + 39 — the OPEN row's measure; the machine's twenty-ninth of Av two days before the tradition's first of Elul (the second OPEN row)"}},
    'the_offers_three_forms': {'value': {'exodus': "'and I will make of you a great nation' (Exodus 32:10) — 'let Me be'", 'numbers': "'and I will make of you a nation greater and mightier than they' (Numbers 14:12 — the one seat)", 'deuteronomy': "'and I will make of you a nation mightier and more numerous than they' (9:14 — the one seat; 'let Me alone' the second hapax)", 'the_seats': OFFER_FORMS, 'the_fulfillment': "Berakhot 7a:34-36 — every promise of good is fulfilled: Rehaviah's sons 'were very many' (1 Chronicles 23:17) — more than 600,000 by the verbal analogy with Exodus 1:7 (I2): the offer FULFILLED outside the Torah; Shabbat 55a:5 the one retraction (Ezekiel 9:4)"}, 'settings': {'the_cell': "F2 let_me_alone — a DATA row; shelach.decree('offer_second_seat') names the three seats"}},
    'the_tablets_three_spellings': {'value': {'the_forms': TABLETS_FORMS, 'plene_vav': "לוחת — 9:9 twice, 9:10; 10:1 alone elsewhere", 'defective': "לחת — 9:11, 9:15; Exodus's form throughout (twelve in the Torah)", 'second_plene': "לחות — 9:11; 4:13 and 1 Kings 8:9 its kin", 'one_verse_two': "9:11 holds two spellings; the article's form הלחת at 9:17", 'the_erections_count': ER_FORMS['v']}, 'settings': {'the_cell': "F2 the_tablets_of_the_covenant — a DATA row (the 7b box's (h))"}},
    'the_taunts_four_forms': {'value': {'exodus_32_12': "'why should the EGYPTIANS say: for evil He brought them out, to slay them in the MOUNTAINS'", 'numbers_14_16': "'the NATIONS will say: because the LORD was not ABLE [yekholet] … He slaughtered them in the WILDERNESS'", 'deut_1_27': "'in His HATRED of us He brought us out of Egypt, to deliver us into the hand of the Amorite, to DESTROY us'", 'deut_9_28': "'lest THE LAND from which You brought us out say: because the LORD was not able [mibli yekholet] … and because He HATED them, He brought them out to kill them in the WILDERNESS'", 'the_noun': "the feminine noun 'ability' at 9:28 and Numbers 14:16 alone (Berakhot 32a:27) — מבלי here, מבלתי there", 'the_speakers': "the Egyptians / the nations / the people themselves / the land"}, 'settings': {'the_cell': "F6 lest_the_land_say — a DATA row; the readback row 9:28 VARIANT"}},
    'the_three_swaps': {'value': {'israel_jacob': "Exodus 32:13 'Abraham, Isaac and ISRAEL Your servants' / 9:27 'Your servants Abraham, Isaac and JACOB'", 'egyptians_land': "Exodus 32:12 'why should the EGYPTIANS say' / 9:28 'lest THE LAND from which You brought us out say'", 'mountains_wilderness': "Exodus 32:12 'to slay them in the MOUNTAINS' / 9:28 'to kill them in the WILDERNESS' (Numbers 14:16's word)"}, 'settings': {'the_cell': "F6 — the same argument twice on the tape (32:11-14 at Sinai, 14:13-19 at Kadesh) and a third time in the retelling; a DATA row"}},
    'the_fourth_verb_dropped': {'value': {'exodus_32_20': ER_VERBS['v'], 'deut_9_21': "burned (ואשרף), crushed (ואכת), grinding thoroughly (טחון היטב — two infinitive absolutes), threw its dust into the brook (ואשלך) — NO DRINKING", 'the_dispute': "Mishnah Avodah Zarah 3:3 — R. Yosei: grind and scatter; the Rabbis: becomes manure; Avodah Zarah 44a:1 R. Yosei's proof from 9:21's own verbs; 44a:2 the Rabbis' answer from 32:20's fourth verb — a test as the sotah's; Tosefta Avodah Zarah 4:3 the dispute whole", 'the_tape': "calf_destroyed purpose=to_test (from 44a:2); the ruling the Rabbis' — grinding does not nullify", 'the_brook': "'the brook that descends from the mountain' (9:21 — the one seat) for 32:20's 'scattered on the water'; the Kidron's kin (2 Kings 23:6, 23:12 — Josiah; 1 Kings 15:13 — Asa, 44a:3)"}, 'settings': {'the_cell': "F2 the_calf_ground_to_dust — the readback row 9:21 VARIANT's hinge; a DATA row"}},
    'solomon_and_nehemiah': {'value': {'kings': "1 Kings 8:51 — 'for they are Your people and Your inheritance whom You brought out of Egypt' (five tokens with 9:26, four with 9:29): Solomon at the temple's dedication quoting THIS telling", 'nehemiah': "Nehemiah 1:10 — 'they are Your servants and Your people whom You redeemed by Your great power' ('by Your great power' plene; 9:29 defective alone)", 'the_seats': PEOPLE_INHERITANCE}, 'settings': {'the_cell': "F6 — the run outside the Torah; a DATA row"}},
    'the_ten_names_of_prayer': {'value': {'the_ten': "shava, tze'aka, ne'aka, rina, pegia, bitzur, keria, NIPUL, pilul, tachanunim (Devarim Rabbah 2:1; the Sifrei 26:7 read at sitting 7)", 'the_chapters': "9:18 'I THREW MYSELF DOWN' (nipul) and 9:26 'I prayed' (pilul) — two of the ten this chapter's; 3:23's plea (tachanunim) chapter 3's", 'the_seats': FELL_HITH}, 'settings': {'the_cell': "F3 i_fell_down; F6 i_prayed_and_said — a DATA row"}},
    'the_calfs_own_day': {'value': OPEN_ROWS[0], 'settings': {'the_cell': "F2 the_calfs_own_day — OPEN (the design's decision 3); erection.calf('boshesh') by CALL"}},
    'the_second_ascents_date': {'value': OPEN_ROWS[1], 'settings': {'the_cell': "F3 the_third_forty — OPEN (the design's decision 4); Seder Olam Rabbah 6 unreachable in the export"}},
    'the_stiff_necks_six_seats': {'value': {'the_seats': STIFF, 'the_finding': "all six the calf's — Exodus 32:9 (God's word), 33:3, 33:5 (the ornaments), 34:9 (Moses' plea); 9:6 and 9:13 here (Moses' word and God's quoted)", 'the_nape': len(NAPE), 'the_state': "no write, no entry — the one database scanned on israel_people: %r" % (STIFF_SCAN,), 'the_shelf': "Beitzah 25b:7-8 — the stiff neck the REASON the Torah was given (impudence); the three impudent ones", 'onkelos': "'קשי קדל' (hard of neck) at 9:6 and 9:13"}, 'settings': {'the_cell': "F1 stiff_necked — a DATA row; DA6 the assertion on the running world"}},
    'the_three_voices_on_one_pronoun': {'value': {'the_finding': "the second person SINGULAR in twelve verses — 1-6 ISRAEL (Moses to the people), 12 and 14 GOD'S 'you' to Moses (the divine frames), 26-29 MOSES' 'You' to God (the prayer); PLURAL in twelve (8-10, 16-19, 21-25); BOTH at 9:7 alone (the switch inside the verse); NEITHER at 11, 13, 15, 20", 'the_register': (SG_ONLY, PL_ONLY, BOTH, NEITHER)}, 'settings': {'the_cell': "the reading's finding — no cell; a DATA row"}},
    'taberah_outside_the_ten': {'value': {'the_list': ES_TRIALS['v'], 'the_chapters_four': "Massah = the second water (Rephidim, Arakhin 15a:20), Kibroth-hattaavah = the second quail (15a:14), Horeb's calf (9:8) = the calf, Kadesh-barnea (9:23) = Paran — the tenth that sealed the sentence (15a:10)", 'taberah': "9:22's first name — NOT among the ten (Arakhin 15a:14); Berakhot 32a:5's impertinence its row (the al-tikrei ('do not read') el/al)", 'the_finding': "the retelling names a provocation the answer sheet's list does not — the design did not predict it (the docket's find)"}, 'settings': {'the_cell': "F5 taberah, the_ten_trials — a DATA row"}},
    'the_merit_of_the_fathers': {'value': {'the_plea': "9:27 'remember Your servants, Abraham, Isaac and Jacob' — Exodus 32:13's; Berakhot 32a:17 the three-legged chair (the fathers' merit); 32a:24 the oath by the Name endures", 'the_two_arms': "Shabbat 55a:11 — the letter tav: SHMUEL — tama, the merit of the Patriarchs has CEASED; R. YOCHANAN — tachon, He will have mercy by it on the righteous", 'the_four_dates': "55a:13-16 — from when did it cease? Rav: Hosea's days (Hosea 2:12); Shmuel: Hazael's (2 Kings 13:23 — 'His covenant with Abraham, Isaac and Jacob, and would not destroy them': THE LAST TIME); R. Yehoshua ben Levi: Elijah's (1 Kings 18:36); R. Yochanan: Hezekiah's (Isaiah 9:6)", 'the_kin': "2 Kings 13:23's 'would not destroy them … His covenant with Abraham, Isaac and Jacob' the run's kin of 9:26-27"}, 'settings': {'the_cell': "F6 remember_your_servants, the_merit_ceased — a PARAMETER with two arms; the exam's two persons (the pleader accepted, the pleader after Hazael exempt)"}},
    'the_crowns_of_horeb': {'value': {'the_row': "Shabbat 88a:7 — R. Simai: at 'we will do' before 'we will hear' 600,000 angels tied two crowns to each Israelite; AT THE CALF 1,200,000 angels of destruction REMOVED them — 'the children of Israel stripped themselves of their ornaments from Mount Horeb' (Exodus 33:6); R. Chama: at Horeb put on, at Horeb removed", 'the_tape': "Exodus 33:1-6 has NO LINE (the tent pitched outside, 33:7-11, the only Exodus 33 line): the crowns a status the calf removed, never written", 'the_chapter': "9:8 'at Horeb you provoked' — the two Horebs of this row"}, 'settings': {'the_cell': "F2 at_horeb_you_provoked — a DATA row naming a hole outside this chapter's span (the docket's find)"}},
    'the_asymmetry_megillah_4_10': {'value': {'the_rule': "Mishnah Megillah 4:10 — the first calf account (Exodus 32:1-20) read and translated; the SECOND — Aaron's report (32:21-24) — read and NOT translated (Megillah 25b:11 the boundary; 25b:12 'this calf came out' the heretics' opening)", 'the_asymmetry': "Deuteronomy's own telling of Aaron's peril (9:20) IS translated — Onkelos 9:20 read whole at sitting 7: the retelling escapes the rule that guards Aaron's report", 'the_cell': ER_READING['v']}, 'settings': {'the_cell': "F4 aarons_report_untranslated — a DATA row; erection.calf('reading_law') by CALL"}},
    'the_three_requests': {'value': {'the_rows': "Berakhot 7a:23-25 — Moses requested three things after the calf and all were granted (R. Yochanan in R. Yosei's name): the Presence to rest on Israel, not on the nations (33:16), the ways of God revealed (33:13); 7a:29 — R. Meir: two granted, the ways not (33:19)", 'the_tape': "Exodus 33:12-23 has NO LINE (the tent pitched outside the only Exodus 33 line): the three requests inside the second forty's stretch, unwritten", 'the_timing': "Berakhot 7a:5 — do not placate a person in his anger: 'My face will go' (33:14) — the second forty waited out"}, 'settings': {'the_cell': "F6 the_three_requests — a DATA row naming a hole outside this chapter's span"}},
    'the_tablets_size': {'value': {'the_parameter': (6, 6, 3), 'the_row': "Nedarim 38a:8 — the tablets six handbreadths long, six wide, three thick: Moses' might read from 9:17's own verbs ('I took hold … and threw them from my two hands'); Pesachim 87b:22 the letters flew back", 'the_ark': "the fragments in the ark — Menachot 99a:12; Bava Batra 14b:4-7; erection.tablets('fragments_by_call') = %s; the entry OWED to chapter 10" % (ER_FRAGMENTS['v'],)}, 'settings': {'the_cell': "F2 the_breaking_in_my_own_words, the_fragments_in_the_ark — a DATA row"}},
    'the_calfs_debt': {'value': {'the_surcharge': "Sanhedrin 102a:15 — one twenty-fourth of the surplus of a litra of the first calf in every punishment (Exodus 32:34 'on the day when I punish'); 102a:16 — collected after twenty-four generations (Ezekiel 9:1); erection.calf('surcharge') = %s" % (ER_SURCHARGE['v'],), 'the_forgetting': "Berakhot 32b:15-19 — 'THESE too shall be forgotten' (Isaiah 49:15): the sin of the calf; 'I will not forget you' — Sinai", 'the_registers': "two registers on the shelf — the debt OPEN against the sin FORGOTTEN — neither on the tape; the tension recorded, not resolved", 'di_zahav': "Berakhot 32a:8, 32a:13 — the wealth caused it, and God conceded it (Hosea 2:10)"}, 'settings': {'the_cell': "F2 the_calfs_debt — a DATA row"}},
    'the_provocations_order': {'value': {'the_retelling': "Taberah, Massah, Kibroth-hattaavah (9:22 — one verse, three names), Kadesh-barnea (9:23)", 'the_tape': "named 'Massah and Meribah' (Exod 17:7), fire_of_the_lord_burned (Num 11:1 — Taberah), quail_and_plague (11:31 — Kibroth), congregation_wept (14:1 — Kadesh)", 'the_days': "the tape's lines carry their own days — M['taberah'] the march + 3 (Ta'anit 29a:3), M['hazeroth'] (29a:4), M['spies_return'] (2, 5, 9) (29a:5-7): Mishnah Ta'anit 4:6's second list proved as 28b:8-10 proved the first"}, 'settings': {'the_cell': "F5 the_provocations_order — a DATA row (the reading's finding)"}},
    'the_uncited_verses': {'value': [2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 15, 16, 18, 20, 22, 23, 24, 28, 29], 'settings': {'the_scan': "the docket's scan (ch9_docket_scan.py, the writer's computed list): nineteen verses cited by no link row on the shelf — the frame's 2-6, the retelling's narrative 7-8, 11-13, 15-16, 18, 20 (AARON'S PERIL cited by no Babylonian row — Vayikra Rabbah 10:5 the topic row), the provocations 22-24, the plea's end 28-29; 9:1, 9, 10, 14, 17, 19, 21, 25, 26, 27 the ten cited"}},
    'the_credits': {'value': {'the_erection': "the calf's rows credited from the erection's docket (Berakhot 32a:14-24, 7a:5, 7a:23-25; Shabbat 87a:5, 88a:7, 89a:6; Avodah Zarah 44a:2; Sanhedrin 102a:5, 102a:15; Yoma 86b:14; Menachot 99b:1; Ta'anit 28b:9-10, 29a:2) and the Exodus triage ledger", 'the_chapters': "Berakhot 32b:8-19 from chapter 4's docket; Mishnah Avodah Zarah 3:3 and 52a:4 from chapter 7's; Yoma 75b:11 from chapter 8's; Megillah 21a:17 from chapter 1's; Shabbat 88a:3 from chapter 5's", 'the_numbers_walk': "Arakhin 15a:6-20, Berakhot 32a:27-29, Ta'anit 29a:5-7 from the spies' docket; Berakhot 32a:5, Ta'anit 29a:2-4 from the Numbers 11 docket; Shabbat 89a:2 from Korach's", 'the_count': "163 addresses credited (link 7, topic 156) — the writer's computed count"}, 'settings': {'the_rule': "a credit is a credit on the file that was read (chapter 6's lesson); every credited row read whole in the docket"}},
}
assert len(DATA) == 23, len(DATA)


# ===== THE WRAP (D9-iv): the daemon over the cells — the ledger written, no event emitted =====================
def law_not_righteousness(event, world):
    """Deut 9:1-29 (cold_run_not_righteousness.py F1-F6). given_at Deut 9:1 — NOT FOR YOUR RIGHTEOUSNESS, the chapter's frame at the counter's day
    (40, 11, 1); installed_by boot (the Deuteronomy daemons' form). ONE TAPE LINE of its own: prayed_for_aaron (9:20 — Aaron's peril told only here,
    written ONCE at its own day by the RETROGRADE marker at Deut 9:20: destruction_halved a STATUS on aaron — the tape's hole filled with a write). The
    exam's case kind dispatches to the cells in EXPLICIT branches with LITERAL effects per kind (an unnamed effect is a KeyError). No timer; no close; the
    kin's effects (decree_relented, blotted_from_the_book, tablets_delivered, fire_sank, atoned_forgiven) UNMOVED (DA5)."""
    k, src = event['kind'], event['case_source']
    E_ = lambda eff, s, cp=None, amount=None, due=None, law='', value=None: {'effect': eff, 'subject': s, 'counterparty': cp, 'amount': amount, 'due': due, 'value': value if value is not None else True, 'source_law': law, 'case_source': src}
    if k == 'prayed_for_aaron':
        return [E_('destruction_halved', 'aaron', value={'the_word': 'and with Aaron the LORD was very angry, to destroy him; and I prayed for Aaron also at that time (9:20)', 'first_telling': "TOLD ONLY HERE — Exodus 32:21-24 Aaron's report (read and not translated, Mishnah Megillah 4:10), 32:35 the plague 'which Aaron made': no anger at Aaron, no prayer for him — the tape's hole", 'the_name': "HALF THE EDICT — Vayikra Rabbah 10:5: destruction is the eradication of children (Amos 2:9); since Moses prayed, half the edict was withheld — TWO DIED AND TWO REMAINED ('take Aaron and his sons with him', Leviticus 8:2); R. Yehoshua ben Levi: prayer accomplishes half", 'the_two_halves': "on the tape already — Nadab and Abihu's fire (Leviticus 10:1-2, the eighth day's runner); Eleazar and Ithamar the succession at Hor (Numbers 20:26-28 — garments_transferred on aaron)", 'the_day': "the second forty's ascent — 'at that time': M['aaron_told'] = M['morrow'], the morrow of the breaking (1, 4, 18), reading_placed (Sanhedrin 102a:5 a time ordained for calamity)", 'the_asymmetry': "Onkelos 9:20 translated ('anger from before the LORD … and I prayed') where Aaron's report is not — the reading law's rule holds on Exodus alone", 'the_re_acceptance': "Leviticus 9:2's calf for the calf and 9:7's 'approach the altar' (shemini_day by CALL); atoned_forgiven on aaron stands beside this status, no second write"}, law="F4 [INK 9:20 'and with Aaron the LORD was very angry, to destroy him; and I prayed for Aaron also at that time' — AARON'S PERIL TOLD ONLY HERE, THE TAPE'S HOLE filled with a write at THE DEUTERONOMY WALK 7b: a STATUS on aaron at the retrograde line's own day (DA2); the name from the docket's row Vayikra Rabbah 10:5]")]
    if k == 'not_righteousness_case':
        fn = {'frame': the_frame, 'calf': the_calf_retold, 'forty': the_forty_days, 'peril': aarons_peril, 'provocations': the_four_provocations, 'intercession': the_intercession}[event['cell']]
        v, e, _ = fn({'ask': event['ask']}, DATA); L = '%s [%s]' % ({'frame': 'F1', 'calf': 'F2', 'forty': 'F3', 'peril': 'F4', 'provocations': 'F5', 'intercession': 'F6'}[event['cell']], event['ask']); s_ = event['person']
        W = {'accepted': E_('accepted', s_, value=v, law=L), 'exempt': E_('exempt', s_, value=v, law=L)}
        return [W[x] for x in e if x != FX.NONE]
    return []


LINES = [
    ('Deut 9:20 — and with Aaron the LORD was very angry, to destroy him; and I prayed for Aaron also at that time',),
]
CLOSES = "none — no close this chapter: the status destruction_halved on aaron stands (a status has no closer); the kin's effects unmoved (decree_relented, blotted_from_the_book, tablets_delivered, fire_sank, atoned_forgiven — the readback references, no second write); the calf's debt OPEN on the shelf, not on the tape"

PERSONS = [
    ('the-reader-of-fortified-to-the-heavens', 'frame', 'fortified_to_the_heavens', "Chullin 90b:12; Tamid 29a:8 — the exam's row fortified_to_the_heavens"),
    ('the-impudent-people', 'frame', 'not_for_your_righteousness', "Beitzah 25b:7-8 — the exam's row not_for_your_righteousness"),
    ('the-maker-of-the-calf', 'calf', 'at_horeb_you_provoked', "Avodah Zarah 52a:4 — the exam's row at_horeb_you_provoked"),
    ('the-grinder-of-the-idol', 'calf', 'the_calf_ground_to_dust', "Mishnah Avodah Zarah 3:3; Avodah Zarah 44a:1-2; Tosefta Avodah Zarah 4:3 — the exam's row the_calf_ground_to_dust"),
    ('the-breaker-of-the-tablets', 'calf', 'the_breaking_in_my_own_words', "Shabbat 87a:5; Menachot 99b:1; Bava Batra 14b:7 — the exam's row the_breaking_in_my_own_words"),
    ('the-confessor-who-specifies', 'calf', 'the_confession_specified', "Yoma 86b:14 — the exam's row the_confession_specified"),
    ('the-prolonger-of-prayer', 'forty', 'the_second_forty', "Berakhot 32b:8; 34a:11 — the exam's row the_second_forty"),
    ('the-one-who-prolongs-and-expects', 'forty', 'prolong_without_expecting', "Berakhot 32b:9 — the exam's row prolong_without_expecting"),
    ('the-one-who-eats-on-high', 'forty', 'bread_i_did_not_eat', "Yoma 75b:11 — the exam's row bread_i_did_not_eat"),
    ('the-one-who-sat-on-the-mount', 'forty', 'i_sat_on_the_mount', "Megillah 21a:17 — the exam's row i_sat_on_the_mount"),
    ('the-one-who-prays-half', 'peril', 'half_the_edict', "Vayikra Rabbah 10:5 — the exam's row half_the_edict"),
    ('the-counter-of-the-ten-trials', 'provocations', 'the_ten_trials', "Avot 5:4; Arakhin 15a:14 — the exam's row the_ten_trials"),
    ('the-annuller-of-the-vow', 'intercession', 'do_not_destroy_your_people', "Berakhot 32a:19 — the exam's row do_not_destroy_your_people"),
    ('the-pleader-on-the-fathers-merit', 'intercession', 'remember_your_servants', "Berakhot 32a:17, 32a:24; Shabbat 55a:11 — the exam's row remember_your_servants"),
    ('the-pleader-after-hazaels-days', 'intercession', 'the_merit_ceased', "Shabbat 55a:13-16 — the exam's row the_merit_ceased"),
]


def scene():
    """THE SCENE — the exam's rows replayed on the world engine (the exodus epoch): the exam's persons through not_righteousness_case — the reader of
    'fortified to the heavens', the impudent people, the maker of the calf, the grinder of the idol, the breaker of the tablets, the confessor who
    specifies, the prolonger of prayer, the one who prolongs and expects (exempt), the one who eats on high, the one who sat on the mount, the one who
    prays half, the counter of the ten trials, the annuller of the vow, the pleader on the fathers' merit, the pleader after Hazael's days (exempt).
    No lashes person this chapter — the chapter holds no prohibition."""
    with contextlib.redirect_stdout(io.StringIO()):
        w = WE.World(era='Deut 9:1-29: chapter 9 on the shelf — Berakhot, Shabbat, Ta\'anit, Avodah Zarah, Menachot, Bava Batra, Sanhedrin, Beitzah, Arakhin, Yoma, Vayikra Rabbah, Devarim Rabbah on the engine (the exodus epoch)', epoch='exodus')
        w.laws = [law_not_righteousness]
        w.advance(w.clock.day_in('exodus', 40, 11, 1))
        # THE DAEMON GATE READS LITERAL SUBMITS ONLY — the fifteen persons typed out from PERSONS
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-reader-of-fortified-to-the-heavens', 'person': 'the-reader-of-fortified-to-the-heavens', 'cell': 'frame', 'ask': 'fortified_to_the_heavens', 'case_source': "Chullin 90b:12; Tamid 29a:8 — the exam's row fortified_to_the_heavens"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-impudent-people', 'person': 'the-impudent-people', 'cell': 'frame', 'ask': 'not_for_your_righteousness', 'case_source': "Beitzah 25b:7-8 — the exam's row not_for_your_righteousness"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-maker-of-the-calf', 'person': 'the-maker-of-the-calf', 'cell': 'calf', 'ask': 'at_horeb_you_provoked', 'case_source': "Avodah Zarah 52a:4 — the exam's row at_horeb_you_provoked"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-grinder-of-the-idol', 'person': 'the-grinder-of-the-idol', 'cell': 'calf', 'ask': 'the_calf_ground_to_dust', 'case_source': "Mishnah Avodah Zarah 3:3; Avodah Zarah 44a:1-2; Tosefta Avodah Zarah 4:3 — the exam's row the_calf_ground_to_dust"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-breaker-of-the-tablets', 'person': 'the-breaker-of-the-tablets', 'cell': 'calf', 'ask': 'the_breaking_in_my_own_words', 'case_source': "Shabbat 87a:5; Menachot 99b:1; Bava Batra 14b:7 — the exam's row the_breaking_in_my_own_words"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-confessor-who-specifies', 'person': 'the-confessor-who-specifies', 'cell': 'calf', 'ask': 'the_confession_specified', 'case_source': "Yoma 86b:14 — the exam's row the_confession_specified"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-prolonger-of-prayer', 'person': 'the-prolonger-of-prayer', 'cell': 'forty', 'ask': 'the_second_forty', 'case_source': "Berakhot 32b:8; 34a:11 — the exam's row the_second_forty"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-one-who-prolongs-and-expects', 'person': 'the-one-who-prolongs-and-expects', 'cell': 'forty', 'ask': 'prolong_without_expecting', 'case_source': "Berakhot 32b:9 — the exam's row prolong_without_expecting"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-one-who-eats-on-high', 'person': 'the-one-who-eats-on-high', 'cell': 'forty', 'ask': 'bread_i_did_not_eat', 'case_source': "Yoma 75b:11 — the exam's row bread_i_did_not_eat"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-one-who-sat-on-the-mount', 'person': 'the-one-who-sat-on-the-mount', 'cell': 'forty', 'ask': 'i_sat_on_the_mount', 'case_source': "Megillah 21a:17 — the exam's row i_sat_on_the_mount"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-one-who-prays-half', 'person': 'the-one-who-prays-half', 'cell': 'peril', 'ask': 'half_the_edict', 'case_source': "Vayikra Rabbah 10:5 — the exam's row half_the_edict"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-counter-of-the-ten-trials', 'person': 'the-counter-of-the-ten-trials', 'cell': 'provocations', 'ask': 'the_ten_trials', 'case_source': "Avot 5:4; Arakhin 15a:14 — the exam's row the_ten_trials"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-annuller-of-the-vow', 'person': 'the-annuller-of-the-vow', 'cell': 'intercession', 'ask': 'do_not_destroy_your_people', 'case_source': "Berakhot 32a:19 — the exam's row do_not_destroy_your_people"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-pleader-on-the-fathers-merit', 'person': 'the-pleader-on-the-fathers-merit', 'cell': 'intercession', 'ask': 'remember_your_servants', 'case_source': "Berakhot 32a:17, 32a:24; Shabbat 55a:11 — the exam's row remember_your_servants"})
        w.submit({'kind': 'not_righteousness_case', 'subject': 'the-pleader-after-hazaels-days', 'person': 'the-pleader-after-hazaels-days', 'cell': 'intercession', 'ask': 'the_merit_ceased', 'case_source': "Shabbat 55a:13-16 — the exam's row the_merit_ceased"})
    n = lambda eid, eff: len([e for e in w.entity(eid).ledger if e['effect'] == eff])
    tset = len([l for l in w.log if l[0] == 'TIMER-SET']); tfire = len([l for l in w.log if l[0] == 'TIMER-FIRE']); tcan = len([l for l in w.log if l[0] == 'TIMER-CANCEL'])
    closes = len([e for ent in w.entities.values() for e in ent.ledger if e.get('closed_by')])
    return (tuple(n(p, 'accepted') + n(p, 'exempt') for p, _, _, _ in PERSONS), (n('the-one-who-prolongs-and-expects', 'exempt'), n('the-pleader-after-hazaels-days', 'exempt')), sum(n(p, 'lashes') for p, _, _, _ in PERSONS), (tset, tfire, tcan, len(w.timers)), len(w.entities), closes), w
SCENE, _W = scene()
# THE PREDICTION (typed before the first run — the design's arithmetic): every exam person written once; the two exempt arms ONE each; NO lashes (no prohibition
# in the chapter); no timer; ENTITIES the fifteen persons; CLOSES 0.
SCENE_PREDICTED = ((1,) * 15, (1, 1), 0, (0, 0, 0, 0), 15, 0)
assert SCENE == SCENE_PREDICTED, ('THE DEUTERONOMY WALK 7b: the scene moved from its prediction', SCENE, SCENE_PREDICTED)


def narrative():
    """THE DEUTERONOMY WALK 7b (2026-09-19): the chapter's own act AS HISTORY — Aaron's peril (9:20) written ONCE at its own day by a RETROGRADE marker
    at Deut 9:20 (the morrow of the breaking, (1, 4, 18) — 'at that time' the second forty's ascent) on a world at the counter's day (40, 11, 1), the
    stretch ENDED by a forward marker at 9:21 — on a world with this runner's daemon: 1 write (the status on aaron), no timer, ONE entity (aaron the
    written-on party — a line's subject makes no entity, read at the first assembly), the counter at (11, 1) unmoved, no close, no row, ONE dated line. Recorded by the sequential run's recorder and
    stitched onto the tape under the two markers the stitcher types. Not a graded cell: the tuple below is a tripwire typed from the design."""
    with contextlib.redirect_stdout(io.StringIO()):
        w = WE.World(era='Deut 9:20 on the tape — Aaron\'s peril written once at its own day, the retrograde marker at 9:20 and the forward marker at 9:21 (the exodus epoch)', epoch='exodus')
        w.laws = [law_not_righteousness]
        w.advance(w.clock.day_in('exodus', 40, 11, 1))
        # THE DAEMON GATE READS LITERAL SUBMITS ONLY — the one line typed out under its retrograde marker; no field named `until`, `days` or `due`
        w.marker('Deut 9:20', w.clock.day_in('exodus', 1, 4, 18), value="and I prayed for Aaron also at that time (9:20) — Aaron's peril TOLD ONLY HERE, dated at the second forty's ascent: the morrow of the breaking, Exod 32:30's (1, 4, 18): RETROGRADE after the counter's (40, 11, 1)", placement='reading_placed')
        w.submit({'kind': 'prayed_for_aaron', 'subject': 'moses', 'for': 'aaron', 'anger': 'and with Aaron the LORD was very angry, to destroy him (9:20)', 'first_telling': "told only here — Exodus 32:21-24 Aaron's report, 32:35 the plague 'which Aaron made': no anger at Aaron, no prayer for him", 'case_source': LINES[0][0]})
        w.marker('Deut 9:21', w.clock.day_in('exodus', 40, 11, 1), value="and your sin, the calf which you had made (9:21) — the speech resumes at its own day: the retrograde stretch of Aaron's peril ENDED, the counter's day (40, 11, 1) re-asserted; FORWARD at the same day, 4:25's and 5:32's form")
    writes = len([l for l in w.log if l[0] == 'WRITE'])
    closes = len([e for ent in w.entities.values() for e in ent.ledger if e.get('closed_by')])
    rows = len([l for l in w.log if l[0] == 'ROW'])
    dated = len([l for l in w.log if l[0] == 'EVENT' and l[2].get('dated') is not None])
    return (writes, len([l for l in w.log if l[0] == 'TIMER-SET']), len(w.entities), w.clock.eras['exodus'].date(w.clock.day)[1:], closes, rows, len(w.tables['population']), dated), w


NARRATIVE, _WN = narrative()
NARRATIVE_PREDICTED = (1, 0, 1, (11, 1), 0, 0, 0, 1)   # DEUTERONOMY_WALK.md "Sitting 7b": 1 write, no timer, ONE entity (aaron the written-on party — the design wrote 'the entities aaron and moses'; the engine creates no entity for a line's subject, only for a write: read at the first assembly, the tripwire retyped from the print), the counter's day (11, 1), no close, no row, no population row, ONE dated line
assert NARRATIVE == NARRATIVE_PREDICTED, ('THE DEUTERONOMY WALK 7b: the chapter\'s narrative moved from its prediction', NARRATIVE, NARRATIVE_PREDICTED)
_aa = _WN.entity('aaron').ledger
assert [e['effect'] for e in _aa] == ['destruction_halved'] and not any(e.get('closed_by') for e in _aa) and _aa[0].get('dated') is not None and _WN.clock.eras['exodus'].date(_aa[0]['dated']) == (1, 4, 18), [(e['effect'], e.get('dated')) for e in _aa]   # the status dated with its line
_pa = [l for l in _WN.log if l[0] == 'EVENT' and l[2]['kind'] == 'prayed_for_aaron']
assert len(_pa) == 1 and _WN.clock.eras['exodus'].date(_pa[0][2]['dated']) == (1, 4, 18) and _pa[0][2].get('placement') == 'reading_placed', [(l[2].get('dated'), l[2].get('placement')) for l in _pa]
