# THE DEUTERONOMY WALK 22 (LEAN, 2026-09-30): the reading sitting's scripts and prints copied into World/step9/forms_deuteronomy_walk/ as the walk's forms — the
# scratch ROOT line (git rev-parse) replaced by the portable header (_ROOT from the file's own place), the scratch path by a marker, the home path by a marker.
# copy_ch33_forms.py's form (files only at the post-check; the tail's files skipped while absent). RUN FROM THE REPO ROOT.
import os, re, subprocess
ROOT = _ROOT
SP = os.path.dirname(os.path.abspath(__file__))
DST = f'{ROOT}/World/step9/forms_deuteronomy_walk'; os.makedirs(DST, exist_ok=True)
HDR = "import os as _os\n_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place\n"
PY = ['derive_ch34_dump0.py', 'ch34_dump0.py', 'ch34_split.py', 'ch34_ink_head.py', 'ch34_ink_body.py', 'ch34_ink_body_b.py', 'derive_ch34_ink.py', 'ch34_ink.py', 'ch34_measure_lean.py', 'write_ch34_design.py', 'write_ch34_point.py', 'copy_ch34_forms.py', 'assert_driver.py', 'ch34_rows_onkelos.py', 'ch34_rows_outside.py', 'ch34_rows_p357.py', 'ch34_rows_check.py', 'write_ch34_ledger.py', 'write_ch34_manifest.py', 'seat_ch34.py', 'ch34_gates_wrap.sh', 'ch34_chain.sh', 'ch34_fold.sh', 'ch34_gates.sh', 'ch34_vc.sh',
      'ch34_gloss_list.py', 'ch34_patch_probe.py', 'ch34_patch_overrides.py', 'write_ch34_records.py', 'write_ch34_commit_msg.py', 'ch34_tail_facts.py', 'ch34_tail_records.sh', 'write_ch34_postpush.py', 'ch34b_spec.py', 'ch34_exam_rows.py', 'write_ch34_exam.py', 'write_ch34b_design.py', 'patch_probes_ch34.py', 'write_ch34b_point.py',
      'add_types_ch34_a.py', 'add_types_ch34_b.py', 'derive_ch34_seq_tools.py', 'derive_ch34_shells.py', 'seq_record_ch34.py', 'seq_stitch_ch34.py', 'ch34_assemble.py', 'ch34_fastcheck.py', 'ch34_askcheck.py', 'ch34_cases_gen.py', 'ch34_scan_census.py', 'ch34_part1.py', 'ch34_part2.py', 'ch34_part3.py', 'ch34_part4.py', 'ch34_part5.py', 'ch34_part6.py', 'ch34_part7.py', 'parse_ch34_fastcheck.py', 'patch_part1_ch34.py', 'patch_register_ch34.py', 'patch_seq_literals_ch34.py', 'patch_deps_ch34.py', 'ch34_runner_chain.sh', 'ch34_tape_chain.sh', 'ch34_tape_wrap.sh', 'ch34_ask_runner_wrap.sh', 'ch34b_gates.sh', 'ch34b_register_wrap.sh', 'write_ch34b_point2.py', 'ch34_fact_asserts.py', 'retype_moved_literals_ch34.py', 'patch_dp4_class_ch34.py', 'ch34b_register2_wrap.sh', 'ch34_fast_wrap.sh', 'ch34_tape_launch.sh', 'ch34_tape_wrap_b.sh', 'retype_heaven_ch34.py', 'write_ch34b_tail.py', 'ch34b_gates3.sh', 'write_ch34b_interrupt.py']   # 22b RUN B's + the tail's forms
OUT = ['ch34_dump0.out', 'ch34_split.out', 'ch34_measure_lean.out', 'ch34_onkelos.txt', 'ch34_sifrei_outside.txt', 'ch34_sifrei_spine.txt', 'ch34_spine_p357.txt', 'ch34_store_glosses.txt', 'ch34_ink_run1.out', 'ch34_ink_run2.out', 'ch34_ink_run3.out', 'ch34_ink_run4.out', 'ch34_design.txt', 'ch34_rows_check.out', 'ch34_ledger.out', 'ch34_manifest.out', 'ch34_timing.tsv', 'ch34_chain.log', 'ch34_vt_deu_34_moses_death.out', 'ch34_ritual_deu_34_moses_death.out', 'ch34_fold.out', 'ch34_fold_check1.out', 'ch34_truth.out', 'ch34_bake.out', 'ch34_build.out', 'ch34_journal.out', 'ch34_register.out', 'ch34_large_letter.out', 'ch34_home_chain.out', 'ch34_gates_SUMMARY.txt', 'ch34_gates.log', 'ch34_gates.DONE', 'ch34_gates_wrapper.log', 'ch34_point_check.out', 'ch34_point_write.out', 'ch34_forms.out', 'ch34_home.out', 'tstep.sh',
       'ch34_vc.out', 'ch34_labels.out', 'ch34_postpush.out', 'ch34_forms3.out', 'ch34_home3.out', 'ch34b_spec.out', 'ch34_exam_rows.out', 'ch34b_exam.out', 'ch34b_design_check.out', 'ch34b_design_write.out', 'ch34b_design_assembled.md', 'ch34b_probes_patch.out', 'ch34b_probes_fail.out', 'ch34b_point_check.out', 'ch34b_point_write.out', 'ch34b_timing.tsv', 'ch34_gloss_list.out', 'ch34_patch_probe.out', 'ch34_patch.out', 'ch34_asbuilt.txt', 'ch34_facts.out', 'ch34_records_check.out', 'ch34_records_write.out', 'ch34_commit_msg.out', 'commit_msg_ch34.txt', 'ch34_forms2.out', 'ch34_home2.out',
       'ch34b_types_a_check.out', 'ch34b_types_a.out', 'ch34b_types_b_check.out', 'ch34b_types_b.out', 'ch34b_seq_tools.out', 'ch34b_shells.out', 'ch34_fastcheck_run0.out', 'ch34_fastcheck_run1.out', 'ch34_fastcheck_run2.out', 'ch34_tokn_expected.txt', 'ch34_name_bare_expected.txt', 'ch34_neg_expected.txt', 'ch34_twin_expected.txt', 'ch34_scans_expected.txt', 'ch34_askcheck_run1.out', 'ch34_cases_gen.out', 'ch34_runner_chain.out', 'ch34_runner_run1.out', 'ch34_runner_run2.out', 'ch34_ask_runner.DONE', 'ch34b_dependency_first.out', 'ch34b_daemon_first.out', 'ch34b_register_first.out', 'ch34b_register.DONE', 'ch34b_register_wrap.log', 'ch34b_register_patch.out', 'seq_record_ch34.out', 'seq_stitch_ch34.out', 'patch_seq_literals_ch34.out', 'ch34_tape_run1.out', 'ch34_checkpoint_check.out', 'ch34_scan_census.out', 'ch34_tape.DONE', 'ch34_tape_wrap.log', 'ch34b_deps_patch.out', 'ch34b_point2_check.out', 'ch34b_point2_write.out', 'ch34b_cache_clear.out', 'ch34b_gates.log', 'ch34b_gates_SUMMARY.txt', 'ch34b_gates.DONE', 'ch34b_gates_wrapper.log', 'ch34b_forms.out', 'ch34b_home.out', 'ch34b_forms2.out', 'ch34b_home2.out', 'ch34b_register_second.out', 'ch34b_register_patch2.out', 'ch34b_dp4_patch.out', 'ch34b_moved_literals.json', 'ch34b_retype.out', 'ch34b_gates_SUMMARY_pass1.txt', 'ch34b_gates_pass1.log', 'ch34b_cache_clear2.out', 'ch34b_gates_wrapper2.log', 'commit_msg_ch34b.txt', 'ch34b_forms3.out', 'ch34b_home3.out', 'ch34b_gates_SUMMARY_pass2.txt', 'ch34b_gates_pass2.log', 'ch34b_retype2.out', 'ch34b_cache_clear3.out', 'ch34b_gates_wrapper3.log', 'ch34b_tail_check.out', 'ch34b_tail_write.out', 'ch34b_forms4.out', 'ch34b_home4.out', 'commit_msg_ch34b_tail.txt', 'ch34_fast.DONE', 'ch34_fast_wrap.log', 'ch34_lint_asb.txt', 'ch34_lint_d16.txt', 'ch34_lint_idx.txt', 'ch34_lint_note.txt', 'ch34_lint_walk.txt', 'ch34_parse.out', 'ch34_patch_part1.out', 'ch34_tape_launch.log', 'ch34_tape_wrap_b.log', 'ch34b_asbuilt_preview.txt', 'ch34b_gates_SUMMARY_pass3_partial.txt', 'ch34b_gates_pass3_partial.log', 'ch34b_interrupt_check.out', 'ch34b_interrupt_write.out', 'ch34b_register2.DONE', 'ch34b_register2_wrap.log', 'ch34b_tail_check2.out', 'patch_seq_registration_ch34.out', 'commit_msg_ch34b_interrupt.txt', 'ch34b_forms5.out']   # 22b RUN B's + the tail's prints
home = os.path.expanduser('~')
n = 0
def port(src, dst):
    global n
    t = open(src, encoding='utf-8').read()
    t2 = re.sub(r"^ROOT = subprocess\.check_output\(\['git', 'rev-parse', '--show-toplevel'\], text=True\)\.strip\(\)$", "ROOT = _ROOT", t, flags=re.M)
    t2 = re.sub(r"(?:__import__\('subprocess'\)|subprocess|_sp)\.check_output\(\['git', 'rev-parse', '--show-toplevel'\], text=True\)\.strip\(\)", "_ROOT", t2)
    if '_ROOT' in t2 and '_ROOT = _os.path.normpath' not in t2: t2 = HDR + t2
    t2 = t2.replace(SP, '<scratch>').replace(home, '<home>')
    open(dst, 'w', encoding='utf-8').write(t2); n += 1
skipped = []
for f in PY:
    src = f'{SP}/{f}'
    if not os.path.exists(src): skipped.append(f); continue
    port(src, f'{DST}/{f}')
for f in OUT:
    if os.path.exists(f'{SP}/{f}'):
        t = open(f'{SP}/{f}', encoding='utf-8', errors='ignore').read().replace(SP, '<scratch>').replace(home, '<home>')
        open(f'{DST}/{f}', 'w', encoding='utf-8').write(t); n += 1
    else: skipped.append(f)
files = [f for f in os.listdir(DST) if os.path.isfile(f'{DST}/{f}')]
bad = [f for f in files if SP in open(f'{DST}/{f}', encoding='utf-8', errors='ignore').read() or home in open(f'{DST}/{f}', encoding='utf-8', errors='ignore').read()]
assert not bad, bad
print('forms copied:', n, '| skipped (absent, the tail\'s):', len(skipped), skipped, '| the folder holds', len(files), 'files; no scratch or home path in any')
