import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE DEUTERONOMY WALK 15b (2026-09-24; LEAN): the sequence file's literals and checkpoints for chapters 17-18 — the import line (the live registration edge), the
# DAEMON_ORDER entry, RUN (predicted in the design: +8 events, +W writes with W READ FROM THE RUNNER'S NARRATIVE PRINT, +1 daemon fired; the rest unmoved),
# PREVIOUS_RUN (14b's RUN EXACTLY — NO declared delta: the daemon writes only on its own lines), NEWEST_RUNNER, PLACEMENT and CENSUS READ FROM THE STITCHER'S
# PRINT (seq_stitch_ch17.out — the eight own-day lines page_order after the tape's last Deuteronomy 16 line; NO marker), the DI1-DI5 block after DH5 + the
# VERDICTS entries (the D series' ninth name — five checkpoints, the lean block); NO STALE LITERAL — THE GREP DECIDED (the thirty-seven are new names, the references
# unmoved; no count of the registries' sizes in the file). Every replacement anchored on the exact prior text (the CENSUS line by its head — its tuple read from the
# file); the readback's census and writes READ from the runner's print and its part 4, never typed; the file asserted to compile after. patch_seq_literals_ch16.py's form. RUN FROM THE REPO ROOT.
import re, ast, subprocess, sys, os
ROOT = _ROOT
SP = os.path.dirname(os.path.abspath(__file__))
P = ROOT + '/World/step9/cold_run_sequence.py'
s = open(P, encoding='utf-8').read()
assert 'import cold_run_courts_prophet' not in s, 'already patched'
def rep(old, new, n=1):
    global s
    assert s.count(old) == n, (s.count(old), old[:90])
    s = s.replace(old, new)
W = 'THE DEUTERONOMY WALK 15b (2026-09-24; LEAN)'
# 0. THE PRINTS — the placement and the census read from the stitcher's, the writes' count and the readback's census from the runner's print, the rows' writes from part 4
pr = open(SP + '/seq_stitch_ch17.out', encoding='utf-8').read()
PLACEMENT = ast.literal_eval(re.search(r'^PLACEMENT LITERAL: (.*)$', pr, re.M).group(1))
CENSUS = ast.literal_eval(re.search(r'^  CENSUS tuple .*?: (\(.*\))$', pr, re.M).group(1))
RUNF = sorted([f for f in os.listdir(SP) if re.match(r'ch17_runner_run\d+\.out$', f)])[-1]
run_out = open(SP + '/' + RUNF, encoding='utf-8').read()
NARR = ast.literal_eval(re.search(r'^THE NARRATIVE: (\(.*?\)) \(the thirty-seven on Israel', run_out, re.M).group(1)); WN = NARR[0]
RBG = ast.literal_eval(re.search(r'^THE READBACK — THE FORMS ON FILE, NO NEW FORM: 42 rows — (\{.*?\});', run_out, re.M).group(1))
p4 = open(SP + '/ch17_part4.py', encoding='utf-8').read()
ROWS = re.findall(r"^    rb\('(Deut \d+:\d+)', \".*?\", '([A-Z]+)', .*?(?:, write='([a-z_]+)')?\),\n", p4, re.M)
assert len(ROWS) == 42, len(ROWS)
SUP = [v for v, g, w_ in ROWS if g == 'SUPPLIED']; WRITES = [(v, w_) for v, g, w_ in ROWS if w_]
TAPE_ROWS = re.findall(r"^    rb\('(Deut \d+:\d+)', .*?tape_kind='(\w+)', tape_verse='([^']+)'", p4, re.M)
PLACEMENT_PREDICTED = {'markers': {'text_constrained': 108, 'reading_placed': 49}, 'events': {'text_constrained': 110, 'page_order': 1181, 'reading_placed': 58}}   # the design's arithmetic: markers UNMOVED (no marker), the eight own-day lines page_order 1173 -> 1181
print('PLACEMENT read:', PLACEMENT, '| predicted:', PLACEMENT_PREDICTED); print('CENSUS read:', CENSUS); print('the writes W read from the narrative:', WN, '| the readback census read:', RBG, '| SUPPLIED', SUP, '| writes', len(WRITES), '| tape rows', len(TAPE_ROWS))
assert PLACEMENT == PLACEMENT_PREDICTED, ('THE PLACEMENT MOVED FROM THE DESIGN — read the stitcher\'s print', PLACEMENT, PLACEMENT_PREDICTED)
assert CENSUS[2] == 1349 and CENSUS[9] == 172 and CENSUS[10] == 131 and CENSUS[12] == 26 and CENSUS[13] == 894 and CENSUS[14] == 272, ('THE CENSUS MOVED FROM THE DESIGN — read the stitcher\'s print', CENSUS)
assert WN == 37, WN   # the thirty-seven writes on Israel — every one its first entry (the design's thirty-seven; the print decides)
# 1. the import line — the live edge the dependency gate reads
i = s.index('import cold_run_festivals_judges   # THE DEUTERONOMY WALK 14b'); j = s.index('\n', i)
s = s[:j + 1] + "import cold_run_courts_prophet   # %s: chapters 17-18 (Deut 17:1-18:22) in ONE runner over two units — THE BLEMISHED SACRIFICE (the south a dispute, the classes, the three true prohibitions), THE IDOLATER'S TRIAL (found means witnesses, the seven investigations, two witnesses, the witnesses' hand, the purge formula's second seat), THE HIGH COURT AT THE PLACE (the three courts — Mishnah Sanhedrin 11:2, right that is left, the rebel elder — THE COURTS' SECOND DAEMON paid in the lean form), THE KING (a disgrace and a commandment, Agrippas, the three limits by Sanhedrin 2:4, the copy of the law, the heart), THE PRIESTS' DUES (the claim at the slaughter — Chullin 10:4, the fleece — Chullin 11:2), THE LEVITE AT THE PLACE (the floor — Zevachim 2:1, portion as portion — Sukkah 5:7), THE DIVINERS (fire and Molech — Sanhedrin 7:7, the sorcerer's deed, whole with the LORD) and THE PROPHET (Horeb's request retold, the six deaths, THE TEST BY THE EVENT): THE READBACK'S FORMS ON FILE, NO NEW FORM — forty-two rows one per verse (the kin's cells by CALL, the tape's lines by kind and first verse; %d SUPPLIED with their writes; no pointer, no state, no open row; the two receipts behind); no narrative verb — no retrograde marker (18:16-17 REFERENCE rows); EIGHT OWN-DAY LINES at (40, 11, 1), STATUTE by form, NO marker; THIRTY-SEVEN writes on Israel, every one its first entry (fifteen STATUSES, twenty BLOCKS, two HEAVEN entries); THE EXAM the eight Mishnah rows the spine cites (no docket — THE LEAN PASS); law_courts_prophet the 77th daemon, given_at Deut 17:1, installed_by boot; the 72nd runner\n" % (W, len(SUP)) + s[j + 1:]
# 2. DAEMON_ORDER
i = s.index("    ('cold_run_festivals_judges', 'law_festivals_judges'),   # THE DEUTERONOMY WALK 14b"); j = s.index('\n', i)
s = s[:j + 1] + "    ('cold_run_courts_prophet', 'law_courts_prophet'),   # %s; DEUTERONOMY_WALK.md \"Sitting 15b\": chapters 17-18 — EIGHT lines (eight STATUTES on the counter's own day, page_order, NO marker — blemished_sacrifice_barred 17:1, idolater_trial_declared 17:2-7, high_court_declared 17:8-13, king_law_declared 17:14-20, priests_dues_declared 18:1-5, levite_at_the_place_declared 18:6-8, diviners_barred 18:9-14, prophet_law_declared 18:15-22, after the tape's last Deuteronomy 16 line), %d writes (all on Israel — every one new: twenty blocks, fifteen statuses, two heaven entries; NO reuse written — the references unmoved: the daemon writes only on its own lines, THE REST drops them, no declared delta), no timer, no close, no new entity (Israel on the registry; the king and the prophet future entities), no population row; installed_by boot (the Deuteronomy daemons' form), given_at Deut 17:1\n" % (W, WN) + s[j + 1:]
# 3. RUN — the design's prediction with W read
rep("RUN = (1341, 96, 88, 0, 12, 1672, 47, 319,   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): PREDICTED",
    "RUN = (1349, 96, 88, 0, 12, %d, 48, 319,   # %s: PREDICTED in DEUTERONOMY_WALK.md \"Sitting 15b\" (THE PREDICTION'S ARITHMETIC) BEFORE the run — events +8 (the eight own-day lines), timers set +0 and fired +0 (no clock walk; the king's and the prophet's futures on the Prophets' tape), cancels 0, retro-writes 12 UNMOVED, writes +%d (READ FROM THE RUNNER'S NARRATIVE PRINT — the design's thirty-seven, every one its first entry), daemons fired +1 (law_courts_prophet), entities +0 (Israel on the registry; no king, prophet or court an entity on the tape), closes +0 (no debit at the lines); sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): PREDICTED" % (1672 + WN, W, WN))
rep("       127)   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): 127 UNMOVED — no close this sitting (the blocks and the statuses have no closer; the bribe's first entry a block; no debit); sitting 13b's line follows:",
    "       127)   # %s: 127 UNMOVED — no close this sitting (the twenty blocks, the fifteen statuses and the two heaven entries have no closer; no debit); sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): 127 UNMOVED — no close this sitting (the blocks and the statuses have no closer; the bribe's first entry a block; no debit); sitting 13b's line follows:" % W)
# 4. PREVIOUS_RUN — 14b's RUN EXACTLY, no declared delta
rep("PREVIOUS_RUN = (1336, 96, 88, 0, 12, 1656, 46, 319,   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): sitting 13b's RUN EXACTLY",
    "PREVIOUS_RUN = (1341, 96, 88, 0, 12, 1672, 47, 319,   # %s: sitting 14b's RUN EXACTLY, read at the design (DEUTERONOMY_WALK.md \"Sitting 15b\", THE PREDICTION'S ARITHMETIC): THE REST drops chapters 17-18's eight lines (inside the declared span [[Deut,17,1,20],[Deut,18,1,22]]) and the daemon's writes with them — law_courts_prophet writes only on its own lines, NO declared delta; no marker these chapters (172 stand); sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): sitting 13b's RUN EXACTLY" % W)
rep("       127)   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): sitting 13b's 127 — no close this sitting, THE REST keeps 13b's; sitting 13b's line follows:",
    "       127)   # %s: sitting 14b's 127 — no close this sitting, THE REST keeps 14b's; sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): sitting 13b's 127 — no close this sitting, THE REST keeps 13b's; sitting 13b's line follows:" % W)
# 5. NEWEST_RUNNER
rep("NEWEST_RUNNER = 'festivals_judges'   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): chapter 16's five own-day lines",
    "NEWEST_RUNNER = 'courts_prophet'   # %s: chapters 17-18's eight own-day lines (after the tape's last Deuteronomy 16 line, no marker; inside the declared span [[Deut,17,1,20],[Deut,18,1,22]]) the newest joined (was 'festivals_judges'); THE REST drops them and reproduces 14b's RUN exactly; sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): chapter 16's five own-day lines" % W)
# 6. PLACEMENT — READ at the stitcher's print (asserted above)
rep("PLACEMENT = {'markers': {'text_constrained': 108, 'reading_placed': 49}, 'events': {'text_constrained': 110, 'page_order': 1173, 'reading_placed': 58}}   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): READ at the stitcher's print",
    "PLACEMENT = %r   # %s: READ at the stitcher's print (scratchpad seq_stitch_ch17.out) — markers UNMOVED (no marker these chapters: text_constrained 108, reading_placed 49); events page_order 1173 -> 1181 (the eight own-day lines), text_constrained 110 and reading_placed 58 UNMOVED — as the design's arithmetic wrote it; sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): READ at the stitcher's print" % (PLACEMENT, W))
# 7. THE VERDICTS entries — the D series' ninth name (five — the lean block)
rep("            'DH1 MATCH', 'DH2 MATCH', 'DH3 MATCH', 'DH4 MATCH', 'DH5 MATCH',   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): chapter 16's five — the D series' eighth name, the lean block\n",
    "            'DH1 MATCH', 'DH2 MATCH', 'DH3 MATCH', 'DH4 MATCH', 'DH5 MATCH',   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): chapter 16's five — the D series' eighth name, the lean block\n            'DI1 MATCH', 'DI2 MATCH', 'DI3 MATCH', 'DI4 MATCH', 'DI5 MATCH',   # THE DEUTERONOMY WALK 15b (2026-09-24; LEAN): chapters 17-18's five — the D series' ninth name, the lean block over two chapters\n")
# 8. CENSUS — read from the stitcher's print; the prior line found by its head (its tuple read from the file, never typed)
m = re.search(r"^CENSUS = (\(.*?\))   # THE DEUTERONOMY WALK 14b \(2026-09-23; LEAN\): READ from the stitcher's print", s, re.M); assert m, 'the CENSUS line'
OLD_CENSUS = ast.literal_eval(m.group(1)); assert OLD_CENSUS[2] == 1341 and OLD_CENSUS[13] == 886 and OLD_CENSUS[9] == 172, OLD_CENSUS
s = s[:m.start()] + ("CENSUS = %r   # %s: READ from the stitcher's print (scratchpad seq_stitch_ch17.out) after chapters 17-18's EIGHT lines joined after the last Deuteronomy 16 line — on the tape 1341 -> 1349 AS THE DESIGN PREDICTED, markers 172 UNMOVED (F 131, R 26), kinds 886 -> 894 (eight STATUTES by form), subjects 272 UNMOVED (israel), closes 71 unmoved; sitting 14b's line follows:   # THE DEUTERONOMY WALK 14b (2026-09-23; LEAN): READ from the stitcher's print" % (CENSUS, W)) + s[m.end():]
# 9. NO STALE LITERAL — the grep decided (no count in the file names the registries' sizes or the thirty-seven; the references unmoved)
# 10. THE DI BLOCK — five checkpoints after DH5 (the lean block; the literals from the design, the runner's print and its part 4)
OWN37 = ['blemished_offering_barred', 'idolater_inquiry_required', 'two_witnesses_required', 'one_witness_barred', 'witnesses_hand_first_commanded', 'high_court_at_the_place_commanded', 'sentence_binding_commanded', 'turning_from_the_word_barred', 'king_from_the_brothers_commanded', 'foreign_king_barred', 'horses_multiplying_barred', 'return_to_egypt_barred', 'wives_multiplying_barred', 'silver_and_gold_multiplying_barred', 'law_copy_commanded', 'heart_lifting_barred', 'shoulder_cheeks_maw_owed', 'first_fleece_owed', 'priests_standing_chosen', 'levite_service_at_the_place_permitted', 'equal_portions_commanded', 'abominations_learning_barred', 'passing_through_fire_barred', 'diviner_barred', 'soothsayer_barred', 'augur_barred', 'sorcerer_barred', 'charmer_barred', 'ghost_consulting_barred', 'familiar_spirit_barred', 'necromancer_barred', 'wholeness_commanded', 'prophet_like_moses_promised', 'prophet_hearkening_commanded', 'word_required_of_the_hearer', 'false_word_test_declared', 'false_prophet_fear_barred']
FIRSTS = ('Deut 17:1',) * 1 + ('Deut 17:2',) * 4 + ('Deut 17:8',) * 3 + ('Deut 17:14',) * 8 + ('Deut 18:1',) * 3 + ('Deut 18:6',) * 2 + ('Deut 18:9',) * 11 + ('Deut 18:15',) * 5
BLOCKS = [e for e in OWN37 if e.endswith('_barred')]; assert len(BLOCKS) == 20 and len(FIRSTS) == 37
DI = '''    # ---- THE DEUTERONOMY WALK 15b (2026-09-24; LEAN; DEUTERONOMY_WALK.md "Sitting 15b" THE CHECKPOINTS DI1-DI5): chapters 17-18's eight own-day lines — the D series' ninth name, the lean block over two chapters ----
    CP_KINDS = ['blemished_sacrifice_barred', 'idolater_trial_declared', 'high_court_declared', 'king_law_declared', 'priests_dues_declared', 'levite_at_the_place_declared', 'diviners_barred', 'prophet_law_declared']; OWN37_CP = %(OWN37)r
    ev_cp = [(i, l) for i, l in enumerate(w.log) if l[0] == 'EVENT' and l[2]['kind'] in CP_KINDS]
    i_last_d16 = max(i for i, l in enumerate(w.log) if l[0] == 'EVENT' and str(l[2].get('case_source', '')).startswith('Deut 16:'))
    mk_cp = [l for l in markers if str(l[2].get('verse', '')).startswith(('Deut 17:', 'Deut 18:'))]
    cp('DI1 THE LINES — eight events on the tape AFTER the tape\\'s last Deuteronomy 16 line, in the ink\\'s order (17:1, 17:2, 17:8, 17:14, 18:1, 18:6, 18:9, 18:15), all page_order on the counter\\'s day (40, 11, 1), no dated field; NO marker at any Deut 17 or 18 verse — markers 172 UNMOVED; the counter ends at (40, 11, 1)', (8, CP_KINDS, True, ['page_order'], [], 0, [(40, 11, 1)], 172, (40, 11, 1)), (len(ev_cp), [l[2]['kind'] for _, l in ev_cp], bool(ev_cp) and ev_cp[0][0] > i_last_d16, sorted(set(l[2].get('placement') for _, l in ev_cp)), [ex.date(l[2]['dated']) for _, l in ev_cp if l[2].get('dated') is not None], len(mk_cp), sorted({ex.date(l[1]) for _, l in ev_cp}), len(markers), ex.date(w.clock.day)))
    FV_cp = (lambda t_: '%%s %%d:%%d' %% t_ if isinstance(t_, tuple) else str(t_))
    n37_cp = tuple(len([e for e in LG('israel') if e['effect'] == eff]) for eff in OWN37_CP); src_cp = tuple(FV_cp(WE.first_verse(str([e for e in LG('israel') if e['effect'] == eff][0].get('case_source', '')))) if [e for e in LG('israel') if e['effect'] == eff] else None for eff in OWN37_CP)
    blocks_cp = sum(1 for eff in %(BLOCKS)r for e in LG('israel') if e['effect'] == eff and e.get('op') == 'block'); heaven_cp = sum(1 for eff in ('prophet_like_moses_promised', 'word_required_of_the_hearer') for e in LG('israel') if e['effect'] == eff and e.get('op') == 'heaven'); dd_cp = yaml.safe_load(open(os.path.join(HERE, 'daemon_dispositions.yaml'), encoding='utf-8'))
    cp('DI2 THE WRITES — the thirty-seven NEW ONE each on israel_people with their lines\\' first verses (17:1 one, 17:2 four, 17:8 three, 17:14 eight, 18:1 three, 18:6 two, 18:9 eleven, 18:15 five); the twenty blocks; the two heaven entries; law_courts_prophet registered, given_at Deut 17:1, installed_by boot; the eight cells and the table WRAPPED (nine)', ((1,) * 37, %(FIRSTS)r, 20, 2, 'Deut 17:1', 'boot', 9), (n37_cp, src_cp, blocks_cp, heaven_cp, dd_cp['daemons'].get('law_courts_prophet', {}).get('given_at'), dd_cp['daemons'].get('law_courts_prophet', {}).get('installed_by'), sum(1 for v_ in dd_cp['functions'].get('courts_prophet', {}).values() if v_.get('status') == 'WRAPPED')))
    RB_cp = cold_run_courts_prophet.READBACK; EVk_cp = [l[2] for l in events]
    found_tape_cp = sum(1 for r_ in RB_cp if r_['tape_kind'] and any(e['kind'] == r_['tape_kind'] and WE.first_verse(e.get('case_source')) == WE.first_verse(r_['tape_verse']) for e in EVk_cp))
    by_call_cp = sum(1 for r_ in RB_cp if r_['cell'] and r_['cell_found']); sup_cp = [r_ for r_ in RB_cp if r_['grade'] == 'SUPPLIED']
    cp('DI3 THE READBACK — THE FORMS ON FILE, NO NEW FORM: the_readback\\'s rows FORTY-TWO, one per verse (the census from the runner\\'s print: %(RBGS)s), every reference row\\'s entry FOUND: %(NTAPE)d on the tape by kind and first verse (Horeb\\'s mediator_requested Deut 5:23 and stand_here_commanded Deut 5:28, the inciter\\'s law Deut 13:7, the prophet\\'s test Deut 13:2 three times, the portion Num 18:20, the gifts Num 18:8, the kings Gen 35:11, the courts Exod 18:25, the walk whole Gen 17:1), forty-two in the kin\\'s cells by CALL (every row has kin); %(NSUP)d rows SUPPLIED with their writes; no pointer row (the two receipts behind), no state row, no open row, no hole, no stretch, no retrograde row', (42, %(NTAPE)d, 42, %(RBG)r, 0, [], [], %(SUP)r, %(WRITES)r, [], [], []), (len(RB_cp), found_tape_cp, by_call_cp, dict(cold_run_courts_prophet.RB_GRADES), len(cold_run_courts_prophet.HOLES), list(cold_run_courts_prophet.OPEN_ROWS), [r_['verses'] for r_ in RB_cp if r_['open']], [r_['verses'] for r_ in sup_cp], [(r_['verses'], r_['write']) for r_ in RB_cp if r_.get('write')], [r_['verses'] for r_ in RB_cp if r_.get('state')], [r_['verses'] for r_ in RB_cp if r_.get('pointer')], [r_['verses'] for r_ in RB_cp if r_.get('stretch')]))
    def _nall_cp(eff): return sum(1 for ent in w.entities.values() for e in ent.ledger if e['effect'] == eff)
    open_deb_cp = [e for e in LG('israel') if e.get('op') == 'debit' and not e.get('closed_by')]; CPm = cold_run_courts_prophet
    cp('DI4 THE KIN AND THE HOLES — israel_hears_and_fears ONE, false_prophet_hearing_barred ONE, tested_by_the_lord ONE, condemned_city_inquiry_required ONE, courts_established ONE, bribe_barred ONE on israel_people UNMOVED (referenced by CALL, not reused — no second write); judges_charged ONE on the court; inheritance_barred TWO (aaron, the_levites), priestly_dues_granted ONE (aaron), kings_promised ONE (jacob — a heaven entry), prophet_declared ONE (abraham), wholeness_owed ONE (abraham — a debit) anywhere UNMOVED; stoned TWO, put_to_death SEVEN, evil_purged_from_the_midst NONE anywhere UNMOVED (the cases\\' body effects, never a line\\'s write); the open debits on israel_people 10 UNMOVED; the kin\\'s cells by CALL — the false prophet put to death, the three tiers accepted, the Sanhedrin\\'s (71, 23), merit by one and liability by two, the python from the armpit, the passing blemish included, the twenty-four gifts; the thirty-three parameters on file in the runner\\'s DATA (no clock datum); the thirty-seven names absent from the registry before the types step (asserted at add_types_ch17_a.py) and the holes\\' scan EMPTY at the runner\\'s import', ((1, 1, 1, 1, 1, 1), 1, (2, 1, 1, 1, 1), (2, 7, 0), 10, ['put_to_death', 'accepted', (71, 23), 'merit_by_one_liability_by_two', 'the_pitom_speaking_from_the_armpit', 'included', '24'], 33, True, True), (tuple(len([e for e in LG('israel') if e['effect'] == e_]) for e_ in ('israel_hears_and_fears', 'false_prophet_hearing_barred', 'tested_by_the_lord', 'condemned_city_inquiry_required', 'courts_established', 'bribe_barred')), len([e for e in LG('the-court') if e['effect'] == 'judges_charged']), tuple(_nall_cp(e_) for e_ in ('inheritance_barred', 'priestly_dues_granted', 'kings_promised', 'prophet_declared', 'wholeness_owed')), tuple(_nall_cp(e_) for e_ in ('stoned', 'put_to_death', 'evil_purged_from_the_midst')), len(open_deb_cp), [CPm.SE_PDEATH[1][0], CPm.FJ_TIERS[1][0], CPm.ES_SIZES, CPm.OR_ONE_TWO, CPm.SA_DEFS['ov'], CPm.PR_PASS, CPm.KO_24[0][:2]], len(CPm.PARAMETERS), all(p_ in CPm.DATA for p_ in CPm.PARAMETERS), CPm.HOLE_SCAN in ([], None)))
    cp('DI5 THE REST — entities 319 UNMOVED (Israel the written-on party, on the registry; the king and the prophet future entities), closes 127 UNMOVED, the population table 148 UNMOVED, the eight kinds present, markers 172 UNMOVED (no marker these chapters); the other counts 14b\\'s exactly with the eight lines and the daemon\\'s writes dropped (THE REST test below — NO declared delta)', (319, 127, 148, True, 172), (len(w.entities), closes_done, len(w.tables['population']), all(k in {l[2]['kind'] for l in events} for k in CP_KINDS), len(markers)))
''' % dict(OWN37=OWN37, BLOCKS=BLOCKS, FIRSTS=FIRSTS, RBGS=', '.join('%s %d' % kv for kv in RBG.items()), NTAPE=len(TAPE_ROWS), NSUP=len(SUP), RBG=RBG, SUP=SUP, WRITES=WRITES)
anchor = "    print('    the story\\'s dates: Moses born %r"
assert s.count(anchor) == 1, s.count(anchor)
s = s.replace(anchor, DI + anchor)
open(P, 'w', encoding='utf-8').write(s)
import py_compile; py_compile.compile(P, doraise=True)
print('patched: import, DAEMON_ORDER, RUN (writes +%d read), PREVIOUS_RUN (no declared delta), NEWEST_RUNNER, PLACEMENT (read %r), VERDICTS DI, CENSUS (read %r), DI1-DI5 (the readback census %r, %d supplied, %d writes, %d tape rows read from the print and part 4); no stale literal (the grep decided); compiles' % (WN, PLACEMENT, CENSUS, RBG, len(SUP), len(WRITES), len(TAPE_ROWS)))
