#!/usr/bin/env python3
# THE DEUTERONOMY WALK 9b — THE COMPILE OF CHAPTER 11 (2026-09-20; the docket its own run under THE TWO-RUN RULE, on the owner's "Go" after the compaction):
# THE EXAM DOCKET for Deuteronomy 11:1-32, written from the scan's dump (scratchpad/ch11_docket_dump.txt: the LINK rows = every Babylonian Talmud / Mishnah /
# Tosefta segment on the local shelf citing a verse of the chapter — the export's chapter 11 the DB's thirty-two verses; the TOPIC rows = the Mishnah rows,
# the fifteen folio ranges of the 9b box's item (n), Tosefta Sotah 8 and Tosefta Sheviit 4, read WHOLE; the CREDITED marks = addresses already verdicted in an
# earlier ledger — CARRIED here with that ledger's own verdict line by ch11_credit_carry.py, or read whole here where the ledger's form carried no verdict).
# Every address in the dump gets ONE verdict (parts A..C on disk, each a SPEC over the dump's own addresses); the coverage is COMPUTED from the dump, never
# typed; the ranges' sizes are read from the scan's own print (ch11_docket_scan.out). Append-only. 8b's form (write_ch10_docket.py, derived by asserted
# line-based substitutions — derive_ch11_docket_writer.py): every row read WHOLE.
import re, os, sys, importlib.util, subprocess
from collections import Counter
ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'], text=True).strip()   # RUN FROM THE REPO ROOT
SCR = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, SCR)
OUT = f'{ROOT}/logic/oral_triage/deu_11_ekev_reeh_exam_2026-09-20.md'
assert not os.path.exists(OUT), OUT
dump = open(f'{SCR}/ch11_docket_dump.txt', encoding='utf-8').read()
rows = re.findall(r'^## \[(LINK|TOPIC)\] (.+?)  (.*)$', dump, re.M)
ADDR, CRED = [], {}
for k, a, rest in rows:
    m = re.search(r'\{CREDITED: (.*?)\}', rest)
    if m: CRED[a.strip()] = m.group(1)
    ADDR.append((k, a.strip(), re.sub(r'\s*\{CREDITED:.*?\}', '', rest).strip()))
NL = sum(1 for k, _, _ in ADDR if k == 'LINK'); NT = len(ADDR) - NL
hdr_line = dump.split('\n', 1)[0]
assert hdr_line == 'ROWS %d LINK %d TOPIC %d CREDITED %d' % (len(ADDR), NL, NT, len(CRED)), (hdr_line, len(ADDR), NL, NT, len(CRED))
_seen = set(); _dedup = []
for _k, _a, _vs in ADDR:
    if _a in _seen: continue
    _seen.add(_a); _dedup.append((_k, _a, _vs))
NDUP = len(ADDR) - len(_dedup); ADDR = _dedup; NT = len(ADDR) - NL   # an address listed twice in the dump (a link row inside a chapter read whole) is taken once — computed
from ch11_credited_rows import UNRESOLVED as UNRES   # the credited rows the carry could not resolve (read whole here)
V = {}; STATS = []
for p in 'ABC':
    part = f'ch11_docket_{p}'
    spec = importlib.util.spec_from_file_location(part, f'{SCR}/{part}.py'); m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
    STATS.append(m.WHOLE_STATS)
    for addr, verdict, note in m.ROWS:
        if addr in V: assert V[addr] == (verdict, note), ('duplicate verdict differs', addr); continue
        assert verdict in ('LAW', 'DERIVATION', 'DISPUTE', 'CONTEXT', 'OUTSIDE'), (addr, verdict)
        V[addr] = (verdict, note)
missing = [a for _, a, _ in ADDR if a not in V]; extra = [a for a in V if a not in {x[1] for x in ADDR}]
if missing or extra:
    print('MISSING', len(missing), missing); print('EXTRA', len(extra), extra); sys.exit(1)
cnt = Counter(vd for vd, _ in V.values())
cnt_link = Counter(V[a][0] for k, a, _ in ADDR if k == 'LINK'); cnt_topic = Counter(V[a][0] for k, a, _ in ADDR if k == 'TOPIC')
works = Counter(a.rsplit(' ', 1)[0] for k, a, _ in ADDR if k == 'LINK')
scan = open(f'{SCR}/ch11_docket_scan.out', encoding='utf-8').read()
scan_r = scan[scan.index('THE RANGES SIZED:'):]
LONG = [(f'{w.replace("_", " ")} {a}-{z}', int(s), int(l)) for w, a, z, s, l in re.findall(r'^  (\S+)\s+(\d+[ab])-(\d+[ab])\s+(\d+) rows,\s+(\d+) link rows', scan_r, re.M)]   # read from the scan's print
MISH = [a for k, a, _ in ADDR if k == 'TOPIC' and not re.search(r'\d+[ab]:\d+$', a)]   # the Mishnah and midrash rows among the topic rows
assert sum(s - l for _, s, l in LONG) + len(MISH) == NT, (sum(s - l for _, s, l in LONG), len(MISH), NT)   # every range read WHOLE
ncred_link = sum(1 for k, a, _ in ADDR if k == 'LINK' and a in CRED); ncred_topic = sum(1 for k, a, _ in ADDR if k == 'TOPIC' and a in CRED)
verses = Counter(h for k, _, vs in ADDR if k == 'LINK' for h in re.findall(r'Deut 11:\d+', vs)); assert verses, 'no verse hits parsed from the LINK headers'
UNCITED = [v for v in range(1, 33) if f'Deut 11:{v}' not in verses]   # computed, never typed
LAWCELLS = Counter(m.group(1) for vd, note in V.values() if vd == 'LAW' and not note.startswith('CREDITED (') for m in [re.search(r'\b(F[1-6])\b', note)] if m)   # this docket's own notes; a carried note names its own docket's cells
NCARRIED = sum(1 for vd, note in V.values() if note.startswith('CREDITED (') and '; carried) — ' in note[:200]); NREADHERE = len(ADDR) - NCARRIED
TOT = {k: sum(s[k] for s in STATS) for k in STATS[0]}; assert TOT['rows'] == len(ADDR) + NDUP, (TOT, len(ADDR), NDUP)
NWHOLE = sum(1 for vd, note in V.values() if '[whole:' in note and '; carried) — ' not in note[:200]); assert NWHOLE == TOT['corrected'] == 0, (NWHOLE, TOT); assert NCARRIED == len(CRED) - len(UNRES), (NCARRIED, len(CRED), len(UNRES))
NOUT = Counter(a.rsplit(' ', 1)[0] for a, (vd, _) in V.items() if vd == 'OUTSIDE')
hdr = (f'''# THE EXAM DOCKET — Deuteronomy 11:1-32 (the discipline retold — the exodus, the sea, Dathan and Abiram, the wilderness; the land watered by heaven — hills and valleys, the rain of heaven, the eyes of the LORD from the year's beginning to its end; the second paragraph — hearken, the rain in its season, the early and the late, grass for the cattle, eat and be satisfied, take heed lest, the heavens shut, these words on the heart, the sign, the frontlets, the teaching, the doorposts, the days multiplied as the days of the heavens; the borders and the dread — keep and love and walk and cleave, the nations dispossessed, every place the sole treads, the wilderness to Lebanon, the river to the western sea, no man shall stand, the dread and the fear, as He spoke; the blessing and the curse — see, I set before you today, Gerizim and Ebal beyond the Jordan opposite Gilgal by the terebinths of Moreh, cross and possess and dwell, keep to do) — THE DEUTERONOMY WALK sitting 9b, THE DOCKET'S OWN RUN (2026-09-20; DEUTERONOMY_WALK.md "Sitting 9b — THE COMPILE OF CHAPTER 11 … THE DESIGN", THE ORDER)
# DECLARED: the exam docket is the UNION (the standing rule of 2026-09-05) of (1) THE LINK-DRIVEN ROWS — every segment of the local shelf's Babylonian Talmud, Mishnah and Tosefta exports whose English cites a verse of Deuteronomy 11 (the scan ch11_docket_scan.py: {NL} rows in {len(works)} works) — and (2) THE TOPIC ROWS BY ADDRESS, the 9b box's item (n) sized by the scan and read WHOLE: Mishnah Berakhot 2:2, Mishnah Sheviit 6:1, Mishnah Rosh Hashanah 1:2, Mishnah Sotah 7:2-7:4, Mishnah Kiddushin 1:7 and 1:9; the folio ranges {", ".join(n for n, _, _ in LONG)}; Tosefta Sotah 8 (seven rows — the ceremony's form) and Tosefta Sheviit 4 (sixteen rows — the baraita of the borders' towns) whole; the export lacks Mishnah Ta'anit — its rows read through the Gemara's citations (Ta'anit 2a:1-3, 10a:11, 10a:16). {len(CRED)} addresses CREDITED (read whole at an earlier sitting — chapter 6's docket the largest: Berakhot 13a-16a, Menachot 34a-37b, Kiddushin 29a-30b; the Devarim docket's Sanhedrin 90b and Sotah 34a-36a; the Musafim docket's Ta'anit 2b-3a; chapters 5, 7 and 10; the borders', Gad-Reuben's and Shelach's dockets; the Exodus and Genesis triages): {NCARRIED} CARRIED here with their ledgers' own verdict lines (ch11_credit_carry.py — the note begins "CREDITED (<ledger>; carried) —"), {len(UNRES)} whose ledger's form carried no verdict READ WHOLE HERE (the note names the ledger and says so).
# THE TALMUD ADDRESSING: the export's index 0 is folio 1a (a page = index // 2 + 1; measured 2026-09-09); the Mishnah by chapter:mishnah; the Tosefta by chapter:row. One address stands in the dump twice (Tosefta Sotah 8:6 — the link row and the chapter's listing): the same verdict at both, the address taken once ({NDUP} duplicate dropped, computed).
# READ WHOLE (THE WHOLE-ROW RULE, owner-ruled 2026-09-17 — "never ever cut corners with the Talmud"): every uncredited row was printed WHOLE (ch11_docket_uncred.py — the chunk files ch11_uncred_00.txt to ch11_uncred_08.txt; the unresolved credited rows ch11_uncred_09.txt) and read entire before its verdict was typed — no cut, no overlay; the parts' WHOLE dicts empty, apply_whole's counts computed: {TOT["corrected"]} of {TOT["rows"]} rows corrected ({TOT["verdicts_changed"]} verdicts, {TOT["notes_changed"]} notes); {NREADHERE} rows read whole in this run.
# THE VERDICTS: LAW names the cell of cold_run_blessing_and_curse.py (F1 the_discipline_retold, F2 the_land_watered_by_heaven, F3 the_second_paragraph, F4 the_borders_and_the_dread, F5 the_blessing_and_the_curse, F6 the_readback) or the callee's cell by CALL; DERIVATION a hook from the verse to a rule; DISPUTE a parameter row with two arms; CONTEXT; OUTSIDE a declared range's matter on another subject. The link census: LAW {cnt_link.get("LAW", 0)} / DERIVATION {cnt_link.get("DERIVATION", 0)} / DISPUTE {cnt_link.get("DISPUTE", 0)} / CONTEXT {cnt_link.get("CONTEXT", 0)} / OUTSIDE {cnt_link.get("OUTSIDE", 0)}; the topic census: LAW {cnt_topic.get("LAW", 0)} / DERIVATION {cnt_topic.get("DERIVATION", 0)} / DISPUTE {cnt_topic.get("DISPUTE", 0)} / CONTEXT {cnt_topic.get("CONTEXT", 0)} / OUTSIDE {cnt_topic.get("OUTSIDE", 0)}; LAW by cell, this docket's own notes {dict(sorted(LAWCELLS.items()))}. The verses cited by the link rows: {", ".join(f"{v} ({n})" for v, n in sorted(verses.items(), key=lambda kv: int(kv[0].split(":")[1])))}; UNCITED by any row: {UNCITED}.
''')
body = ''
last = None
for k, a, vs in ADDR:
    work = a.rsplit(' ', 1)[0]
    if work != last:
        body += f'\n## {work}\n'; last = work
    vd, note = V[a]
    body += f'- {a} [{k}{(" — " + vs) if vs else ""}{(" — CREDITED: " + CRED[a]) if a in CRED else ""}] — {vd}. {note}\n'
crowns = '''
## The finds (this docket's crowns)
- THE YOKE OF THE COMMANDMENTS NAMED BY THE ANSWER SHEET (Mishnah Berakhot 2:2; Berakhot 14b:11, 14b:12-14, 14b:19, 14b:24; 13a-b credited): the second paragraph after the first — the yoke of the kingdom of Heaven, then THE YOKE OF THE COMMANDMENTS (R. Yehoshua ben Korcha); R. Shimon ben Yochai's typing — the first paragraph learn, teach and perform, the second TEACH AND PERFORM (11:18-20), the third perform only; Rav's practice, the Shema before the tefillin, the yoke's order applied; the Shema without tefillin false testimony against oneself: yoke_of_the_commandments_accepted's NAME AND VALUE CONFIRMED; the paragraph's two directives the design's rows by CALL.
- THE PRAYER FROM THE PARAGRAPH'S OWN CLAUSE, AND THE RAIN ATTACHED TO IT (Ta'anit 2a:11; Berakhot 33a:11, 33a:13, 33a:29; Ta'anit 2a:1-5, 6a:5, 6a:7, 10a:11-16): "to serve Him with all your heart" (11:13) is PRAYER, and "I will give the rain of your land" (11:14) follows it — the request for rain in the service of the heart; the mention in the resurrection blessing (rain a revival), the request in the years' blessing (sustenance), both INDISPENSABLE (omitted, one returns to the beginning); THE DATES, EVERY ONE FROM A ROW: the mention from the last day of the feast (R. Yehoshua; Mishnah Ta'anit 1:1-2 through 2a:1-3) to Passover's first day; the request from the third of Marcheshvan, or the seventh (Rabban Gamliel — the halakha; the last pilgrim to the Euphrates), in the diaspora sixty days into the season (Chananya — the halakha); the early rain in Marcheshvan and the late in Nisan ("in its due time"); the fasts from the seventeenth of Marcheshvan and the New Moon of Kislev: rain_dates' VALUES.
- THE DECREE FIXED AT THE HEAD OF THE YEAR, THE DISTRIBUTION FREE (Rosh Hashanah 17b:11-13, 8a:16, 16b:12, 16b:3; Ta'anit 8b:5-6): "the eyes of the LORD your God are always on it, from the beginning of the year to its end" (11:12) — the year judged at its head (the three books; the New Year for years is for judgment); the rain decreed cannot be added to or reduced, but falls IN SEASON on the land that needs it for good, or OUT OF SEASON on forests and deserts for bad: "IN ITS SEASON" (11:14) THE FREE VARIABLE AFTER THE DECREE — rain_in_its_season's value made precise; the mountains or the fields (8b:5); the year poor at its head rich at its end (the defective spelling, 16b:3).
- THE SHUTTING'S VALUE, THRESHOLD AND CAUSES (Ta'anit 3b:6; 6b:8; 8a:18, 8b:1-3; 7b:5-8a:8, 8a:14, 8b:16; 7b:4): "He will shut up the heavens" (11:17) is THE CLOUDS AND THE WINDS WITHHELD, not rain alone (Rav Yosef's baraita); the threshold — rains that seal a barrel's mouth with mud are not "shut" (Rav Chisda); the shutting verb the wombs' (Reish Lakish in bar Kappara's name — closing, birth, remembering: three analogies to the woman — the Sifrei 306:6 at its Bavli seat); THE CAUSES ON THE SHELF beside 11:16's "serve other gods" — the sentence of destruction (11:17, Ze'iri), the tithes annulled, slander, the impudent, the neglect of Torah, robbery, no whisperers of prayer, false pledges of charity; the remedy prayer and the generation's pious; Solomon's dedication the run's receipt ("heaven shut up and no rain", 1 Kings 8:35-36): heavens_shut_for_turning's VALUE and the exam's cause rows — the cause a PARAMETER with many arms.
- THE LAND WATERED BY HEAVEN, FIRST (Ta'anit 10a:2-3; 9b:10-16, 10a:4-7; Bava Batra 19a:18; Shabbat 85a:3; Berakhot 8a:6; Kiddushin 26a:10): the Land created first and watered by the Holy One Himself, the world by an intermediary, the Land drinking first and the world the residue (Job 5:10 — the Sifrei 37-40's baraita at its Bavli seat); THE SOURCE OF RAIN A DISPUTE — R. Eliezer the ocean sweetened in the clouds, R. Yehoshua the upper waters, 11:11 HIS VERSE; no water channels needed in the Land; "with your foot" a handbreadth; the long days in the Land and not outside; "possess it and dwell in it" (11:31) an act of acquisition.
- THE CATTLE BEFORE THE MAN (Berakhot 40a:1; Gittin 62a:16; Ta'anit 8b:14): "grass in your field for your cattle", then "you shall eat and be satisfied" (11:15) — PROHIBITED TO EAT BEFORE FEEDING ONE'S ANIMALS: a rule from the verse's clause order (Rav Yehuda in Rav's name at two seats); the granary's blessing before the measuring.
- THE PARAGRAPH'S DUTIES GRADED BY THE CLASS RULE (Mishnah Kiddushin 1:7; Kiddushin 34a:2, 34a:8; Yoma 11b:8; Kiddushin 36a:9; Bava Batra 21a:2, 110b:7; Shabbat 32b:4; Rosh Hashanah 17a:10): the mezuzah not time-bound — women obligated, the reward "that your days be multiplied" deciding against the juxtaposition to study; the tefillin time-bound — women exempt, and Isi's baldness bar with them ("between your eyes" / "between your eyes", I2); "you shall teach them" read "you yourselves" — the father, and Yehoshua ben Gamla's schools; "your sons" inclusive at the reward; children die for the mezuzah's neglect or for the study's — the adjacency's reach (E28 from-the-preceding); the skull that never donned tefillin the body's rebellion.
- THE CEREMONY — ITS PLACE THREE WAYS, ITS FORM, ITS TONGUE, ITS ARITHMETIC (Sotah 32a:10-13, 33b:4-12, 36b:4-5, 37a:7-11; Tosefta Sotah 8:1-7; Sotah 32a:6-7, 33a:13-14, 33b:1-2): 11:30's clauses read by R. Yehuda as SHECHEM (the terebinths of Moreh — Genesis 12:6, I2; the Samaritans' forged "Shechem" conceded and refuted, 33b:6), by R. Elazar as TWO MOUNDS BY THE JORDAN (27:4 the same day; the Arabah; Gilgal in sight; Shechem the Hivites', not "the Canaanite's"), by R. Eliezer ben Yaakov as A ROUTE, NOT A PLACE (the way, the settled, the plain — as the cloud showed the way the first time): gerizim_ebal_place's THREE ARMS; the form — six and six, the priests, the Levites and the Ark below, the Levites' placement disputed (the elders below / the fit / all below, "on" the mount meaning beside), the blessing first and the Amen, the general and the particular, to learn, to teach, to keep, to perform — FORTY-EIGHT COVENANTS (and 603,550 per matter); the holy tongue — "speak and say" the source for others' Hebrew, the Levites' own from "voice" / "voice" (Exodus 19:19); the day the crossing's (Tosefta 8:1); the stones and the seventy languages (on the stones / on the plaster — Tosefta 8:5); the dispossession the crossing's condition (Tosefta 8:3): gerizim_ebal_ceremony_owed's value and its closer described.
- THE RECEIPT'S POINTER TAUGHT A SECOND TIME (Tosefta Sotah 8:6; Pesachim 8b:7-9): "no man could stand before them … 'I will send My terror before you' (Exodus 23:27)" — the Tosefta joins 11:25's sentence to Exodus 23:27 as the Sifrei 52:4 did: the design's RUN_CITATION pointer with two teachers; the pilgrimage's guard (Exodus 34:24 — the cow, the rooster; going and returning by 16:7; one who has land ascends) at its Bavli seat, pilgrim_land_guarded's teacher.
- THE DWELLING WEIGHED, AND ITS COUNTER-ARM (Mishnah Ketubot 13:11; Ketubot 110b:7-15, 110b:23-24, 111a:1-8, 111a:13-21): all may force ascent, none removal; residing outside the Land as idolatry — David's "go, serve other gods" (11:16's phrase); against it Rav Yehuda's exile decree (Jeremiah 27:22) and the three (six) oaths — not as a wall; the dead outside not rising (R. Elazar; the tunnels) against Isaiah 26:19 — the resurrection from 11:21's "to them" (Sanhedrin 90b credited) at its Land-bound edge: 11:31's "dwell in it" the exam's row (the Sifrei 80:4-5).
- STUDY GREATER, FOR IT LEADS TO DEED (Kiddushin 40b:5, 40b:8-12): the loft at Lod — the Sifrei 41:12's ruling at its Bavli seat; the Torah's precedence counted on the clock (the dough-portion, the tithes, the sabbatical, the jubilee — the land laws after the conquest and the division); the judgment and the reward begin with Torah.
- THE SHEMA'S LANGUAGE AND ORDER (Sotah 32a:5, 32b:19-33a:4, 33a:5-7): the paragraphs in any language (the Rabbis) or as written (Rabbi); not out of order ("and these words will be"); audible ("hear"); the Amida in any language but not Aramaic for the individual: the exam's rows for the paragraph's recitation.
- WHAT THE DESIGN DID NOT PREDICT (carried to RUN B as DATA rows or values): the shutting's VALUE (the clouds and the winds) and THRESHOLD (the barrel's mud); "in its season" THE FREE VARIABLE AFTER THE DECREE; the cattle-before-the-man rule from the clause order; the receipt's pointer taught a second time by the Tosefta; the ceremony's place a THREE-ARM parameter (Shechem / the Jordan's mounds / a route); the ceremony's day the crossing's, its tongue from "voice" / "voice", its forty-eight covenants; the dispossession as the crossing's condition; the Samaritan "Shechem" conceded by R. Elazar son of R. Yosei; the rain's source a dispute with 11:11 R. Yehoshua's verse; the causes of the shutting a parameter with many arms; the export's empty row Sotah 32a:4; Tosefta Sotah 8:6 listed twice in the dump.
'''
cite = '\n## CITE INDEX — every segment opened, each fully named\n(coverage COMPUTED by write_ch11_docket.py against the scan\'s dump: %d addresses, every one verdicted — missing 0, extra 0)\n' % len(ADDR)
cite += '\n'.join(a for _, a, _ in ADDR) + '\n'
tail = (f'\n**read: {len(ADDR)} of {len(ADDR)} — COMPLETE** (the link-driven rows {NL}: {", ".join(f"{k} {n}" for k, n in sorted(cnt_link.items()))}; '
        f'the topic windows {NT}: {", ".join(f"{k} {n}" for k, n in sorted(cnt_topic.items()))}; all rows: {", ".join(f"{k} {n}" for k, n in sorted(cnt.items()))}; credited {len(CRED)} — {NCARRIED} carried with their ledgers\' own verdict lines and {len(UNRES)} read whole here; {NREADHERE} rows read whole in this run — the counts this script computed from the dump and the verdict lists, never typed; corrections {TOT["corrected"]}; the ranges: {"; ".join(f"{n} {s} rows ({l} link)" for n, s, l in LONG)}; the Mishnah and Tosefta rows {len(MISH)}; OUTSIDE by work: {dict(NOUT)}.)\n')
open(OUT, 'w', encoding='utf-8').write(hdr + body + crowns + cite + tail)
print('WROTE', OUT, os.path.getsize(OUT), 'bytes')
print('rows', len(ADDR), 'link', NL, 'topic', NT, 'credited', len(CRED), '(link', ncred_link, 'topic', ncred_topic, ')', 'carried', NCARRIED, 'unresolved_read_here', len(UNRES), 'read_here', NREADHERE, 'dup_dropped', NDUP)
print('verdicts', dict(sorted(cnt.items())), 'link', dict(sorted(cnt_link.items())), 'topic', dict(sorted(cnt_topic.items())))
print('LAW by cell', dict(sorted(LAWCELLS.items())))
print('OUTSIDE by work', dict(NOUT))
print('verses cited', sorted(verses.items(), key=lambda kv: int(kv[0].split(':')[1])), 'UNCITED', UNCITED)
print('ranges', [(n, s, l) for n, s, l in LONG]); print('mishnah+midrash rows', len(MISH))
