import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE DEUTERONOMY WALK 15b (LEAN): the commit message built from the prints — the reading (15) and the compile (15b) of chapters 17-18 in the lean form, together
# (uncommitted since f730559) — for the owner's word. write_ch16b_commit_msg.py's form. RUN FROM THE REPO ROOT after the records.
import os, re, subprocess, ast, glob
ROOT = _ROOT
SP = os.path.dirname(os.path.abspath(__file__))
def rd(p): return open(p, encoding='utf-8').read()
def R(pat, text, name):
    g = re.search(pat, text, re.M); assert g, (name, pat); return g.group(1)
def RL(pat, text, name):   # the LAST match — the runner's own MATRIX line follows the callees' import-time reports in its print (read at the point's first check: 287/287 the first line, the runner's 66/66 the last)
    g = re.findall(pat, text, re.M); assert g, (name, pat); return g[-1]
summ = rd(f'{SP}/ch17b_gates_SUMMARY.txt'); assert 'ALL GREEN' in summ
STEPS = re.findall(r'^(PASS|FAIL|SKIP) (\w+)(?: rc=\d+)? \((\d+)s\)', summ, re.M); CHAIN_S = sum(int(t) for _, _, t in STEPS)
SWEEP = R(r'(\d+/\d+) runners green', rd(f'{SP}/ch17b_gates/sweep.out'), 'the sweep')
run = rd(sorted(glob.glob(f'{SP}/ch17_runner_run*.out'))[-1]); MATRIX = RL(r'^MATRIX: (\d+/\d+)', run, 'the runner'); W = ast.literal_eval(R(r'^THE NARRATIVE: (\(.*?\)) \(the thirty-seven', run, 'the narrative'))[0]
NPAR = int(R(r'the thirty (\d+) \(in the registry', run, 'the parameters')); tapes = sorted(glob.glob(f'{SP}/ch17_tape_run*.out')); tape = rd(tapes[-1]); NRUN = len(tapes)
TAPE_CP = R(r'(\d+/\d+) checkpoints?', tape, 'the tape') if re.search(r'\d+/\d+ checkpoints?', tape) else R(r'checkpoints[^\n]*?(\d+/\d+)', tape, 'the tape')
seq = rd(f'{ROOT}/World/step9/cold_run_sequence.py'); RUN = R(r"^RUN = \((\d+, \d+, \d+, \d+, \d+, \d+, \d+, \d+),", seq, 'RUN')
CASES = int(R(r'^CASES generated: (\d+)', rd(f'{SP}/ch17_cases_gen.out'), 'the cases'))
tim15 = [l for l in rd(f'{SP}/ch17_timing.tsv').strip().split('\n') if l.split('\t')[1].startswith('15 ')]; tim = [l.split('\t') for l in rd(f'{SP}/ch17b_timing.tsv').strip().split('\n') if l.split('\t')[1].startswith('15b')]
led = rd(f'{ROOT}/logic/oral_triage/deu_17_18_shoftim_2026-09-24.md'); NSRC = len(re.findall(r'^- (?:Onkelos|Sifrei)', led, re.M))
PROBES = re.findall(r'^  (\w+): (\d+/\d+)$', rd(f'{SP}/ch17b_gates/probes.out'), re.M) if os.path.exists(f'{SP}/ch17b_gates/probes.out') else []
MSG = '''CHAPTERS 17-18 READ, FROZEN AND COMPILED IN THE LEAN FORM (SITTINGS 15 AND 15b — THE LEAN PASS'S THIRD AND FOURTH SITTINGS, THE FIRST OVER TWO CHAPTERS: THE SPINE AND ONKELOS WHOLE, THE MISHNAH ROWS THE SPINE CITES AS THE CASES, NO DOCKET, ONE RUNNER AND ONE DAEMON OVER TWO UNITS, THE CHAIN ONCE — THE FULL PROCESS OWED) — THE BLEMISH TRANSGRESSES AND NOT THE SOUTH, THE SEVEN INVESTIGATIONS FROM THE SHARED 'WELL' AT THREE VERSES, TWO WITNESSES FOR EVERY DEATH AND THE DISCIPLE SILENT, THE WITNESSES' HAND FIRST AND THE DOERS OF EVIL PURGED, THE HIGH COURT AT THE PLACE WITH THE THREE COURTS AND THE APPEAL'S FORMULA (SANHEDRIN 11:2 IN THE SPINE'S OWN HEBREW — THE COURTS' SECOND DAEMON PAID IN THE LEAN FORM), RIGHT THAT IS LEFT, THE REBEL ELDER BY THE DEED, THE KING A DISGRACE AND A COMMANDMENT CHOSEN BY A PROPHET WITH AGRIPPAS WEEPING (SOTAH 7:8) AND THE THREE LIMITS SPLIT BY 'FOR HIMSELF' (SANHEDRIN 2:4 — EIGHTEEN WIVES, ONE IDLE HORSE, DAVID AND SOLOMON), THE COPY CORRECTED BY THE SEVENTY-ONE, THE CLAIM BORN AT THE SLAUGHTER'S INSTANT AND THE PROSELYTE'S COW (CHULLIN 10:4), TWO EWES OR FIVE AND R. AKIVA'S FIVE FROM THE VERSE (CHULLIN 11:2), THE LEVITE WHO IS A PRIEST AND THE WATCHES EQUAL AT THE THREE FEASTS (SUKKAH 5:7), THE FLOOR (ZEVACHIM 2:1), THE FATHERS' BARTER ONKELOS WRITES INTO THE VERSE, LEARN TO UNDERSTAND AND NOT TO DO, FIRE AND MOLECH JOINED (SANHEDRIN 7:7), THE SORCERER'S DEED AGAINST THE ILLUSION, HOREB'S REQUEST THE PROPHETS' CAUSE RETOLD AS REFERENCE ROWS, THE SIX DEATHS, AND THE TEST BY THE EVENT — A LAW WHOSE VERDICT WAITS ON THE TAPE'S FUTURE — UNCOMMITTED SINCE f730559.

On the owner's words "Reread and go" (sitting 15, after the compaction at #210) and "Reread go" (sitting 15b, after the compaction at #211 — no "Commit" said, the compile opened on the uncommitted tree), 2026-09-24; World/step9/DEUTERONOMY_WALK.md "Sitting 15 — CHAPTERS 17-18 … LEAN" (the design and the AS BUILT), "Sitting 15b — THE COMPILE OF CHAPTERS 17-18 … LEAN" (the design and the AS BUILT); the state doc's #211, #212. SITTING 15 (the reading): the Sifrei's thirty-two piskaot 147-178 (181 rows, every head in verse order, none headless) and Onkelos's 42 verses whole, eleven outside rows — logic/oral_triage/deu_17_18_shoftim_2026-09-24.md (%d sources, coverage computed); the units deu_17_courts_king and deu_18_levi_prophet FROZEN (8 claims); the fold 232 units / standing 2275 / the hash unmoved; the freeze chain green; the display patch 30 by gloss + 97 by reference; %d timed steps. SITTING 15b (the compile): the design in the map; the probe Q44 to FAIL; the lean exam file logic/oral_triage/deu_17_18_shoftim_exam_2026-09-24.md (the eight Mishnah rows read whole, no segment); the types (eight kinds, thirty-seven effects, the daemon law_courts_prophet the 77th over two chapters, the span two ranges, twenty CALL edges all reference, I5 77); the callees' facts from twenty runners; cold_run_courts_prophet.py the 72nd runner in four parts — %d cases %s on its first graded run (eight cells and the table; %d writes on Israel, every one its first entry; %d parameters); the tape %s on run %d (RUN (%s, the four pairs, 127); DI1-DI5; the scan census extended to the probes' and the tape's substring scans, two callees' seats widened from its print; the daemon's ten diviner writes retyped as literal calls); the dependency gate's four demands filed from its print; THE GATES CHAIN ONCE ALL GREEN in %d s (%d steps; the probes %s; the register gate --strict; the positions at four workers; the sweep %s); %d timed steps. THE LESSONS (in the AS BUILT): the daemon gate reads literal calls; the extended scan census finds the seats at once; two chapters are one runner and one daemon; the gate's live edge is a call; a row's int prints as a string through str(); the lean compile window held for two chapters. THE DEBT (COMPILE_DEBT's lean-pass box, line (3)): the docket whole, the readback's exercise of the king's condition and the prophet's test on the Prophets' tape, the persons and the bench scene, the pointer rows for 19:15, 28:14 and 31:10, the ten deferred records.

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01MiJCE3AxFHu3jksQa2GG21
''' % (NSRC, len(tim15), CASES, MATRIX, W, NPAR, TAPE_CP, NRUN, RUN, CHAIN_S, len(STEPS), PROBES, SWEEP, len(tim))
assert not re.search(r'[֐-׿]', MSG)
open(f'{SP}/commit_msg_ch17b.txt', 'w', encoding='utf-8').write(MSG)
print('commit_msg_ch17b.txt %d bytes' % len(MSG.encode()))
