#!/usr/bin/env python3
# THE DEUTERONOMY WALK sitting 3 — CHAPTER 5 (2026-09-16): THE CLAIMS of Deuteronomy 5:1-33, ONE manifest for the one draft unit, read off
# this sitting's ledger, every claim LABELED (logic/MIDDOT.md's codes; World/step9/CLAIM_LABELS.md), a machine check where the ink allows —
# every he_contains substring CUT FROM THE SNAPSHOT STORE'S OWN BYTES by the word's CONSONANTS: the check is the word's LONGEST PIECE WHOLE
# (never a prefix fragment; the floor four code points). Claim IDs DV05- (5:1-33). Written once (no file may exist; the ID prefix checked
# absent from every existing manifest and unit). Every source cite is checked against the ledger's CITE INDEX before a byte is written, and
# every CITE INDEX name must be used by a claim. Sitting 2's form (write_ch4_manifest.py).
import json, os, re, sqlite3, glob, subprocess
ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'], text=True).strip()
DATE = '2026-09-16'
db = sqlite3.connect(f'file:{ROOT}/torah_grok.SNAPSHOT-main-51801ca.sqlite?mode=ro', uri=True)
def cut(book, ch, v, word, nth=0):
    rows = db.execute("SELECT w.idx, w.he FROM words w JOIN verses v ON w.verse_id=v.id WHERE v.book=? AND v.chapter=? AND v.verse=? ORDER BY w.idx", (book, ch, v)).fetchall()
    plain = lambda h: ''.join(c for c in h if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
    hit = [(i, h) for i, h in rows if plain(h) == word]
    assert len(hit) > nth, (book, ch, v, word, hit)
    idx, he = hit[nth]
    piece = max(he.split('/'), key=len)
    assert len(piece) >= 4, (book, ch, v, word, he.split('/'))
    return idx, piece
def hc(ref, word, note, nth=0):
    b, cv = ref.split(' '); c, v = map(int, cv.split(':'))
    idx, sub = cut(b, c, v, word, nth)
    return {"type": "he_contains", "ref": ref, "idx": idx, "contains": sub, "note": note}
def onk(c, lo, hi): return '; '.join(f'Onkelos Deut {c}:{v}' for v in range(lo, hi + 1))
def sif(*rows): return '; '.join(f'Sifrei Devarim {r}' for r in rows)
led = open(f'{ROOT}/logic/oral_triage/deu_05_vaetchanan_{DATE}.md', encoding='utf-8').read().split('## CITE INDEX')[1]
CI = set(re.findall(r'^(Onkelos Deut \d+:\d+|Sifrei Devarim \d+:\d+)$', led, re.M))
assert len(CI) == 38, len(CI)

M = {}
M['deu_05_decalogue'] = ('DV05', [
 {"id": "DV05-01", "source": onk(5, 1, 5) + '; ' + sif('41:1', '41:4'), "ref": "Deut 5:1-5",
  "claim_en": "THE COVENANT AT HOREB: MOSES CALLED ALL ISRAEL — HEAR THE STATUTES AND THE JUDGMENTS, LEARN THEM, KEEP TO DO THEM; THE LORD OUR GOD MADE A COVENANT WITH US AT HOREB, NOT WITH OUR FATHERS BUT WITH US, ALL OF US ALIVE HERE THIS DAY; FACE TO FACE THE LORD SPOKE WITH YOU FROM THE MIDST OF THE FIRE, I STANDING BETWEEN THE LORD AND YOU, FOR YOU FEARED THE FIRE AND DID NOT GO UP, SAYING. 'And Moses called to all Israel' 5:1 and 29:1; 'hear, O Israel' four seats, the imperative singular; 'in your ears' the Torah's one seat; 'learn them … keep to do them' — THE SIFREI 41:1 and 41:4 (on 11:13) read the order as study before the deed and the deed hanging on the study (41:4 found by the English file alone, its Hebrew citing only Hosea 4:1); 'made a covenant with us' one seat; 'NOT WITH OUR FATHERS' one — the Aramaic keeps the bare negation, the English Onkelos alone brackets '[only]'; 'FACE TO FACE' (face IN face) THE BIBLE'S ONE SEAT of the form — Onkelos 'SPEECH WITH SPEECH' (one seat); 'I STOOD BETWEEN' one — Onkelos 'between THE MEMRA OF THE LORD and you'; 'at that time' fifteen; 'saying' 5:5 the chapter's one seat, opening the ten words. The register: the frame in the third person, then Moses' own voice, then the LORD's speech quoted (5:6-21) — the readback's code inside the retelling.",
  "middah": "ink (the forms' seats censused over the whole DB; the one 'saying' and the one divine frame measured on the morphology; the export's two layers told apart at 5:3); I2's form (41:1 — the doubt on 5:1's order closed by 11:13, a reference the Sifrei draws); E12's kin (41:4 — the order of two verbs read as a dependency, Hosea's verse the weight); the translation's moves named (5:4 speech with speech, 5:5 the Memra)",
  "check": hc("Deut 5:4", "בפנים", "'face IN face' — the Bible's one seat of the form; Onkelos 'speech with speech'")},
 {"id": "DV05-02", "source": onk(5, 6, 11), "ref": "Deut 5:6-11",
  "claim_en": "THE FIRST WORDS: I AM THE LORD YOUR GOD WHO BROUGHT YOU OUT OF EGYPT, THE HOUSE OF BONDAGE; NO OTHER GODS BEFORE ME; NO GRAVEN IMAGE, ANY FORM IN HEAVEN ABOVE, EARTH BENEATH, THE WATERS UNDER THE EARTH — BOW NOT, SERVE NOT, FOR I AM A JEALOUS GOD VISITING THE FATHERS' INIQUITY ON THE THIRD AND THE FOURTH OF THOSE WHO HATE ME, DOING KINDNESS TO THOUSANDS WHO LOVE ME AND KEEP HIS COMMANDMENTS; TAKE NOT THE NAME IN VAIN, FOR THE LORD WILL NOT HOLD HIM GUILTLESS. 5:6 = Exodus 20:2 VERBATIM, 5:7 = 20:3, 5:11 = 20:7 (the diffs empty); 5:8 ONE LETTER from 20:4 ('any form' for 'and any form'); 5:9 'fathers' plene for defective and 'AND upon the third' — 'visiting the iniquity of fathers upon sons' 5:9, Exodus 34:7, Numbers 14:18 and NOT 20:5 (its defective 'fathers' breaks the phrase); THE THIRD GENERATION STARRED by the parser (not thirty — no holam under the lamed; the pointed form at all five seats); 5:10 'HIS commandments' WRITTEN where Exodus 20:6 writes 'MY' — the chapter's one written-and-read pair (the DB's flag, the store's seventh token, Onkelos reading 'my'); 'to thousands' a bare noun; 'in vain' nine seats, 'will not hold guiltless' twelve; THE TEN WORDS IN THE SINGULAR (the morphology: singular only from 5:6 to 5:21). ONKELOS: 'another god EXCEPT ME' (the plural made singular), the visiting made conditional — 'REBELLIOUS sons … WHEN THE SONS COMPLETE TO SIN AFTER THEIR FATHERS' (thirty tokens for twenty-one), 'to thousands OF GENERATIONS', 'swear' for 'lift', the two 'in vain' made 'for nothing' and 'TO A LIE'. The second word's cell owed to the compile (the 2b box).",
  "middah": "ink (the two copies diffed token by token; the parser's star measured with the points; the ketiv flagged in the DB and read in the store; the translation's tokens counted against the verse's); the translation's supplements named (5:7 except me, 5:9 the rebellious sons, 5:11 the lie); the testing shelf routed (Shevuot 3:8-9, the Decalogue exam's rows)",
  "check": hc("Deut 5:7", "אחרים", "'OTHER gods' — 5:7 = Exodus 20:3 verbatim; nineteen Torah seats of the pair, seventeen this book's")},
 {"id": "DV05-03", "source": onk(5, 12, 15) + '; ' + sif('233:1'), "ref": "Deut 5:12-15",
  "claim_en": "THE SABBATH WORD: KEEP THE SABBATH DAY TO SANCTIFY IT, AS THE LORD YOUR GOD COMMANDED YOU — SIX DAYS LABOR, THE SEVENTH A SABBATH TO THE LORD, NO WORK BY YOU, YOUR SON AND DAUGHTER, YOUR SERVANTS, YOUR OX AND YOUR ASS AND ALL YOUR CATTLE, YOUR STRANGER, THAT YOUR SERVANTS REST LIKE YOU; REMEMBER YOU WERE A SLAVE IN EGYPT AND THE LORD BROUGHT YOU OUT WITH A MIGHTY HAND AND AN OUTSTRETCHED ARM — THEREFORE HE COMMANDED YOU THE SABBATH DAY. 'KEEP' for Exodus 20:8's 'REMEMBER' — both INFINITIVE ABSOLUTES (the morphology; 'keep' so at 5:12, 6:17, 16:1); THE SIFREI 233:1: the two were said IN ONE UTTERANCE, beside the mingled stuff and the fringes (the export's footnote naming the Mekhilta, Bahodesh 7 — the first copy's spine, unopened by any ledger); 'AS THE LORD YOUR GOD COMMANDED YOU' the receipt inside the ten words, absent from Exodus — 5:12, 5:16, 20:17; THE REGISTER GATE'S SEAT Deut 5:12; 5:13 = 20:9 verbatim, the parser [6]; 5:14 the ordinal [7], 'AND your servant', 'YOUR OX AND YOUR ASS AND ALL your cattle' (the two beasts here alone in the Bible), 'THAT YOUR SERVANT AND MAIDSERVANT MAY REST LIKE YOU' (Exodus 23:12 the kin) — twenty-six words for eighteen; 5:15 THE GROUND CHANGED WHOLE: the slave in Egypt and the exodus for Exodus 20:11's six days of creation, the diff keeping 'for', 'the LORD', 'therefore', 'the sabbath day'; 'remember that you were a slave' five seats, all this book's; 'a mighty hand and an outstretched arm' 5:15 and 26:8 in this spelling; ONKELOS 'a sabbath BEFORE the LORD', 'the day of the sabbath' (5:12, 5:15). THE DATA: the fourth word's parameter table carries two grounds, one per copy.",
  "middah": "ink (the infinitive absolutes measured on the morphology; the sabbath verses diffed against Exodus 20:8-11 and 23:12; the receipt's three seats censused); I13's kin (233:1 — two verses of one law read as one utterance, the Sifrei's own formula; a reference between the two copies, LR1); the register's seat measured (Deut 5:12 NONE)",
  "check": hc("Deut 5:12", "שמור", "'KEEP the sabbath day' — the infinitive absolute, for Exodus 20:8's 'remember'; the Sifrei 233:1's one utterance")},
 {"id": "DV05-04", "source": onk(5, 16, 21), "ref": "Deut 5:16-21",
  "claim_en": "HONOR AND THE FIVE: HONOR YOUR FATHER AND YOUR MOTHER AS THE LORD YOUR GOD COMMANDED YOU, THAT YOUR DAYS BE LONG AND IT GO WELL WITH YOU ON THE GROUND THE LORD GIVES YOU; YOU SHALL NOT MURDER, AND NOT COMMIT ADULTERY, AND NOT STEAL, AND NOT ANSWER AGAINST YOUR NEIGHBOR A VAIN WITNESS, AND NOT COVET YOUR NEIGHBOR'S WIFE, AND NOT DESIRE HIS HOUSE, HIS FIELD, HIS SERVANTS, HIS OX, HIS ASS, ALL THAT IS HIS. 5:16's 'honor' the infinitive absolute (piel) at both copies; the second receipt 'AS THE LORD YOUR GOD COMMANDED YOU' and 'AND THAT IT MAY GO WELL WITH YOU' added to Exodus 20:12 (twenty-two words for fifteen; 4:40's promise); THE REGISTER GATE'S SEAT Deut 5:16; 5:17 = 20:13 verbatim; 5:18-20 'AND not' for 'not' — the four short words ONE ROW in the export (the map: the DB's 17-20 the export's 17; twelve tokens, four negations); 5:20 'a VAIN witness' for Exodus's 'a FALSE witness' (the one lexical divergence inside a word's body; 'vain' four Torah seats — the Name and the witness in this chapter) — Onkelos levels it to 'false testimony'; 5:21 THE WIFE FIRST (Exodus opens with the house), 'DESIRE' a second root for the second 'covet' (the hitpael's one seat), 'HIS FIELD' added, 'his ox and his ass' one seat; the ten words singular to the last word. ONKELOS 'do not kill A SOUL' (the object supplied), 'AND DO NOT DESIRE' (a second word for the second verb). The copies' counts: 172 tokens and 620 letters (Exodus 20:2-17) against 189 and 708 (5:6-21).",
  "middah": "ink (the diffs of 5:16-21 against Exodus 20:12-17; the export's one row for four verses measured by alignment; the counts of the two copies computed); the translation's moves named (5:17 the soul, 5:20 the false testimony, 5:21 the second verb); the testing shelf routed (Kiddushin 30b-31b, Sanhedrin 86a, Bava Metzia 5b)",
  "check": hc("Deut 5:21", "תתאוה", "'you shall not DESIRE' — the hitpael's one seat, a second root where Exodus 20:17 repeats 'covet'")},
 {"id": "DV05-05", "source": onk(5, 22, 27) + '; ' + sif('306:16'), "ref": "Deut 5:22-27",
  "claim_en": "THE VOICE AND THE REQUEST: THESE WORDS THE LORD SPOKE TO ALL YOUR ASSEMBLY FROM THE FIRE, THE CLOUD AND THE THICK DARKNESS, A GREAT VOICE, AND ADDED NO MORE; HE WROTE THEM ON TWO TABLETS OF STONE AND GAVE THEM TO ME; WHEN YOU HEARD THE VOICE FROM THE DARKNESS YOU CAME NEAR TO ME, THE HEADS OF YOUR TRIBES AND YOUR ELDERS: THE LORD HAS SHOWN US HIS GLORY, WE HEARD HIS VOICE FROM THE FIRE, THIS DAY WE SAW THAT GOD SPEAKS WITH MAN AND HE LIVES; WHY SHOULD WE DIE — THIS GREAT FIRE WILL CONSUME US, IF WE HEAR MORE WE DIE; WHO OF ALL FLESH HEARD THE LIVING GOD FROM THE FIRE AS WE AND LIVED? YOU GO NEAR AND HEAR, AND TELL US, AND WE WILL HEAR AND DO. 'Your assembly' the Bible's one seat; 'these words' — THE SIFREI 306:16 makes 5:22 the definition of 'words' for the Song and the prophet (words are nothing but words of Torah; the row citing the export's 5:19 = the DB's 5:22 through the map); 'AND HE ADDED NO MORE' four seats (Judah, the angel, Samuel and Saul) — Onkelos 'AND DID NOT CEASE' (the tradition's reading, one seat); 'two tablets of stone' six seats, DEFECTIVE here where 4:13 wrote plene; the parser [2]; 'AND YOU CAME NEAR TO ME' 5:23 and 1:22 — the Sifrei 20:1's pair (credited: the mob against the elders); 'and the LORD heard' at 5:28 with 1:34; 'that God speaks with man and he lives' one — 4:33's question answered in the people's mouth; 'this great fire' 5:25 and 18:16; the chapter's one 'if' the people's; 'THE LIVING GOD' five seats; 'WE WILL HEAR AND DO' one — Exodus 24:7's 'we will do and hear' REVERSED, Onkelos 'we will accept and do'; ONKELOS 'the voice of HIS MEMRA' (5:24), 'the voice of the Memra of the LORD' (5:25, 5:26), 'the living LORD'. THE TAPE: the ten words spoken and the tablets given are on the tape since 2b's retrograde markers — 5:22 retells both; the readback's rows graded at the compile.",
  "middah": "ink (the phrases' seats censused; the tablets' spelling against 4:13; the request diffed against Exodus 20:18-21 and 24:3-7; the one 'if' measured); E7 (306:16 — 'words' fixed from 5:22, the Sifrei's 'nothing but'); the translation's moves named (5:22 did not cease, 5:27 accept and do); the testing shelf routed (Sanhedrin 17a, Shabbat 88a)",
  "check": hc("Deut 5:22", "ויכתבם", "'and he wrote them' on two tablets of stone — the tablets defective here, plene at 4:13; on the tape since 2b")},
 {"id": "DV05-06", "source": onk(5, 28, 33) + '; ' + sif('357:40'), "ref": "Deut 5:28-33",
  "claim_en": "THE ANSWER AND THE CHARGE: THE LORD HEARD THE VOICE OF YOUR WORDS AND SAID TO ME: I HAVE HEARD THIS PEOPLE'S WORDS — THEY HAVE DONE WELL IN ALL THEY SPOKE; WHO WOULD GIVE THAT THIS THEIR HEART WERE THEIRS, TO FEAR ME AND KEEP MY COMMANDMENTS ALL THE DAYS, THAT IT GO WELL WITH THEM AND THEIR SONS FOREVER; GO SAY TO THEM, RETURN TO YOUR TENTS; AND YOU, STAND HERE WITH ME, AND I WILL SPEAK TO YOU ALL THE COMMANDMENT, THE STATUTES AND THE JUDGMENTS YOU SHALL TEACH THEM TO DO IN THE LAND I GIVE THEM; KEEP TO DO AS THE LORD YOUR GOD COMMANDED YOU, TURN NOT RIGHT OR LEFT; WALK IN ALL THE WAY HE COMMANDED, THAT YOU MAY LIVE AND IT BE WELL WITH YOU AND YOU PROLONG DAYS IN THE LAND. 'AND THE LORD HEARD THE VOICE OF YOUR WORDS' 5:28 and 1:34 — the same five words, the praise and the wrath; the chapter's one divine frame; 'they have done well' cited at 18:17; 'who would give' seventeen seats; 'to fear me' 4:10 and 5:29; 'forever' defective here and at 32:40, plene at 23:7; 'STAND HERE WITH ME' one seat — THE SIFREI 357:40 (the book's last piska): Moses prophesied only standing, Balaam fallen (the row citing the export's 5:28 = the DB's 5:31); 'all the commandment and the statutes and the judgments' one (6:1 without 'all'); the LORD's 'I will speak', 'I give' inside Moses' report — the code's author; 5:32's PLURAL receipt 'as the LORD your God commanded you' one seat — THE REGISTER GATE'S SEAT Deut 5:32; 'right or left' 5:32 and 17:11; the address plural again at 32-33 (the ten words were singular); 'that you may live' six (4:1); the paragogic 'you shall possess' one. ONKELOS 'IT WAS HEARD BEFORE THE LORD' (1:34, 5:28), 'they have done RIGHTLY' (5:28, 18:8), 'WOULD THAT', 'to fear BEFORE ME', 'stand BEFORE ME'. THE BLOCK'S EDGE: 5:31 the charge that makes 6:1 onward Moses' teaching of what was spoken here.",
  "middah": "ink (1:34's clause found verbatim; the register's plural return measured on the morphology; the promise's forms diffed against 4:40, 6:2, 12:28); E28's kin and E26 (357:40 — Moses against Balaam seat by seat, the king's cook); the register's seat measured (Deut 5:32 NONE); the translation's moves named (5:28 heard before, 5:29 would that)",
  "check": hc("Deut 5:28", "היטיבו", "'THEY HAVE DONE WELL in all they spoke' — one seat, cited back at 18:17 for the prophet; Onkelos 'rightly'")},
])

ALL = ''.join(open(f, encoding='utf-8').read() for f in glob.glob(f'{ROOT}/logic/oral_audit/manifests/*.json')) + ''.join(open(f, encoding='utf-8').read() for f in glob.glob(f'{ROOT}/logic/units/*.yaml'))
total = 0
for uid, (pre, C) in M.items():
    out = f'{ROOT}/logic/oral_audit/manifests/{uid}_claims.json'
    assert not os.path.exists(out), out
    assert f'"{pre}-' not in ALL and f'[claim {pre}-' not in ALL, pre
    assert [c['id'] for c in C] == [f'{pre}-{n:02d}' for n in range(1, len(C) + 1)], uid
    for c in C:
        for s in c['source'].split('; '): assert s in CI, (c['id'], s)
        assert c['middah'] and c['check']['contains'] and len(c['check']['contains']) >= 4
    json.dump(C, open(out, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    total += len(C); print(f'wrote {out}: {len(C)} claims')
USED = {s for _, (pre, C) in M.items() for c in C for s in c['source'].split('; ')}
assert USED == CI, (sorted(CI - USED)[:10], sorted(USED - CI)[:10])
print('claims', total, '| every CITE INDEX name used by a claim:', USED == CI)
