import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE DEUTERONOMY WALK 13b THE TAIL (2026-09-23): the commit message for 13b alone (chapter 15's reading committed at b0eaa56) — 12b's form (commit_msg_ch14b.txt): the
# headline in capitals, the paragraph with the numbers READ FROM THE PRINTS (the same reads as the records writer), the trailers. Built whole, then written. RUN FROM THE REPO ROOT.
import os, re, sys, subprocess
ROOT = _ROOT
SP = os.path.dirname(os.path.abspath(__file__)); G = f'{SP}/gates_ch15b'
def rd(p): return open(p if p.startswith('/') else f'{SP}/{p}', encoding='utf-8', errors='ignore').read()
def newest(pat): return sorted(f for f in os.listdir(SP) if re.match(pat, f))[-1]
run = rd(newest(r'ch15_runner_run\d\.out$')); MX = tuple(int(x) for x in re.search(r'MATRIX: (\d+)/(\d+)', run).groups()); assert MX[0] == MX[1]
tape = rd(newest(r'ch15_tape_run\d\.out$')); assert '10/10 checkpoints' in tape
cc = tuple(int(x) for x in re.search(r'checkpoint_check: (\d+) rows, (\d+) miss, (\d+) raised', rd('ch15_checkpoint_check.out')).groups())
WN = int(re.search(r'the writes W read from the narrative: (\d+)', rd('patch_seq_literals_ch15.out')).group(1))
cg = rd('ch15_cases_gen.out'); CASES_N = int(re.search(r'CASES generated: (\d+)', cg).group(1))
summ = rd(f'{G}/SUMMARY.txt'); assert 'GATES CHAIN DONE — ALL GREEN' in summ, summ[-300:]
rg = tuple(int(x) for x in re.search(r'DECLARED (\d+); DEBT (\d+); FAILS (\d+)', rd(f'{G}/register.out')).groups())
sw = rd(f'{G}/sweep.out'); SW_P = len(re.findall(r'^PASS +cold_run_\w+\.py', sw, flags=re.M)); assert not re.findall(r'^FAIL +cold_run_\w+\.py', sw, flags=re.M)
po = rd(f'{G}/positions.out'); PO = int(re.search(r'(\d+) checkpoints', po).group(1))
dp = rd(f'{G}/dependency.out'); DPE = re.search(r'dispositions on file: (\d+) edges, (\d+) pointers', dp).groups()
dk = open(f'{ROOT}/logic/oral_triage/deu_15_reeh_exam_2026-09-23.md', encoding='utf-8').read(); NROWS = len([l for l in dk.split('\n') if l.startswith('- ') and any(k in l for k in (' — LAW.', ' — DERIVATION.', ' — DISPUTE.', ' — CONTEXT.', ' — OUTSIDE.'))]); assert NROWS == 974
tt = [l.split('\t') for l in rd('ch15b_timing.tsv').split('\n') if l.strip()]; T = [(r[1], int(r[2])) for r in tt if len(r) >= 3 and r[1].startswith('13b')]; TN, TS = len(T), sum(s for _, s in T)
nf = rd(f'{ROOT}/World/step9/forms_deuteronomy_walk/ch14_aramaic_nfkc.out'); NF = re.search(r'(\d+) code points in (\d+) rows', nf).groups()
CHAIN = rd('ch15b_chain_story.txt').strip()
msg = (f"CHAPTER 15 COMPILED AND ON THE TAPE — THE RELEASE, THE HAND, THE HEBREW SLAVE AND THE FIRSTLING COMPILED AS FOUR LAWS AT THE CHAPTER'S OWN DAY: THE RELEASE-YEAR AND THE FIRSTLING'S YEAR CLOCK DATA ON THE CALENDAR'S OWN KEYS (THE BARE WORLD'S 'NO COUNT' ASKED FOR BEFORE THE CLOCK'S METHOD, WHICH PRINTS AND EXITS), THE TWO VERSES 'THERE SHALL BE NO NEEDY' AND 'THE NEEDY SHALL NEVER CEASE' UPHELD BY A CONDITION AS A STATE ROW WITH TWO ARMS, THE RECEIPT'S REFERENT AHEAD (15:6 -> 28:3) A POINTER ROW GRADED H AND THE GATE'S OWED POINTER UNDER A DEBT LINE ALREADY ON FILE, HILLEL'S PROZBUL AND THE RANKS OF THE POOR PARAMETERS FROM THE ANSWER SHEET, THE SEVERANCE GIFT PRICED BY THE ERECTION'S OWN VALUE, EXODUS 21'S TERM CLOCK READ AS A TABLE, 'SANCTIFY' FOR ITS VALUE BY TEMURAH, THE BLEMISH'S CLASS FROM THE LAME AND THE BLIND OVER THE PRIESTHOOD'S LIST, TWO TRANSFERS TAUGHT (THE SEDUCERS' BELIAL BY THE SIFREI 117:3, THE LEPER'S EAR BY THE SIFREI 122:5-6 AND KIDDUSHIN 15a); FOUR REUSES AND EIGHT COUNT SEATS RETYPED BY THE GREP, TWO MORE FOUND BY THE RUNS — THE LINES THE GREP LISTED AND CUT AT TWO HUNDRED CHARACTERS (THE WHOLE-ROW RULE FOR GREPS); THE SCAN OF THE ONE DATABASE MADE TO EXCLUDE ITS OWN DAEMON'S WRITES; 'LAME' THE PASSOVER'S HOMOGRAPH AND 'FOR AN INHERITANCE' THE GIFT FORMULA'S, BOTH COMPUTED; AND SITTING 13'S LESSON 4 CORRECTED BY MEASUREMENT (THE ARAMAIC EXPORT CARRIES NO PRESENTATION-FORM LETTERS). "
       f"On the owner's words \"Go\" (RUN A), \"Reread then go\" and \"Go\" and \"Continue\" (the docket D1, D2a, D2b), \"Reread\" then \"Go\" (RUN B) and \"Go\" (the tail, in RUN B's window at 189k), 2026-09-22/23; World/step9/DEUTERONOMY_WALK.md \"Sitting 13b — THE COMPILE OF CHAPTER 15 … THE DESIGN\", its three \"THE DOCKET — AS RUN\" paragraphs and \"Sitting 13b — THE COMPILE OF CHAPTER 15 — AS BUILT\" — THE TWO-RUN RULE's eighth compile sitting under THE COST RULES with the docket clause applied three times: six clean compaction points (the state doc's #207 and its addenda 1-5). "
       f"THE DOCKET, THREE RUNS: logic/oral_triage/deu_15_reeh_exam_2026-09-23.md — {NROWS} rows (814 read whole here, 160 carried with their ledgers' own verdict lines), 15:15 the one verse no row cites (computed). "
       f"RUN B: cold_run_release_firstborn.py the 70th runner ({CASES_N} cases in seven cells and the readback table; {MX[0]}/{MX[1]} on its first graded run), law_release_firstborn the 75th daemon (given_at Deut 15:1, installed_by boot; eight WRAPPED); FOUR OWN-DAY LINES at (40, 11, 1), NO MARKER; {WN} writes on Israel from the lines (eleven new, four reuses), the case's own debit and statuses beside them; twenty-seven parameters; twenty-one CALL edges (nineteen reference, two transfers taught); the tape 10/10 on its third run (CU5's stale count read from the first run's 9/10 print and retyped; the retype's apostrophes escaped; the scan's ground fixed — bears_sin the first reuse with no prior entry, folded by the first run); checkpoint_check {cc[0]} rows, {cc[1]} miss (the eighteen known), {cc[2]} raised; RUN (1336, 96, 88, 0, 12, 1641 + {WN}, 46, 319, the four pairs, 127), THE REST 12b's exactly; DG1-DG9. "
       f"THE TAIL: {CHAIN} — the register gate --strict DECLARED {rg[0]} / DEBT {rg[1]} / FAILS {rg[2]}; the dependency gate {DPE[0]} edges, {DPE[1]} pointers; the positions table {PO} checkpoints; the sweep {SW_P}/{SW_P}; the home-path gate green. THE NFKC RE-MEASURE at RUN A: {NF[0]} presentation-form code points in the Onkelos export's 956 Deuteronomy rows — sitting 13's lesson 4 corrected in place, the CORRECTION row on the reading's ledger. "
       f"THE RECORDS: the map's AS BUILT with the timing table, COMPILE_DEBT's sitting-13 box PAID and the 13b box, MIDDOT's compile entry, RESEARCH_LOG, THE_STEPS, THE_BRIEFING, THE_LOOP's step-6 row, RESUME, RECORD_FORMS, the state doc's #207 addenda 4-5, the addenda, the recovery page, the memory; the forms in World/step9/forms_deuteronomy_walk/. EVERY STEP TIMED — 13b's {TN} steps, {TS} machine seconds. THE LESSONS (eleven, in the AS BUILT): a cut grep line ends before the answer; a scan of the fold excludes the scanner's own writes; a retype into a single-quoted seat escapes its apostrophes; the clock's era is asked for before its method; the callees' forms are read at the print; a token's homograph is the consonants'; the gate's live edge is a call; a pointer ahead is owed under a debt line on file; the writes are read from the narrative's print; the chain's failures arrive after the clean point; THE TWO-RUN RULE HELD on its eighth compile sitting.\n\n"
       "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_01MiJCE3AxFHu3jksQa2GG21\n")
assert not re.search(r'[֐-׿]', msg) and '/Users/' not in msg
open(f'{SP}/commit_msg_ch15b.txt', 'w', encoding='utf-8').write(msg); print('the commit message written:', len(msg), 'bytes')
