# THE NUMBERS WALK 8b (2026-09-11) — THE EXAM DOCKET, part C: Bava Batra 122a-123a and 143b.
ROWS = [
 ('Bava Batra 122a:2', 'LAW', "the outside teaching: thirteen tribes in the future; initially TWELVE (Levi no portion — 26:62's clause); divided ONLY WITH MONEY 'between the many and the few' (26:56) — the near and far compensated; R. Yehuda: a seah's-space in Judea = five in the Galilee. CELL the_land('tribes_or_skulls'), the_land('compensation'), the_land('thirteen_tribes')."),
 ('Bava Batra 122a:4', 'LAW', "the two texts reconciled: Eleazar wearing the Urim and Tummim, Joshua and all Israel before him, TWO RECEPTACLES — the tribes' names and the boundaries'. CELL the_land('lots_mouth') — the lot's mouth is the oracle's; the priest the reading's Eleazar (26:1, 26:63)."),
 ('Bava Batra 122a:5', 'LAW', "Eleazar by the Divine Spirit: 'Zebulun emerges, and Akko's boundary with it' — then the lots emerge in his hand as said. CELL the_land('lots_mouth') — the procedure as a data row (Joshua 19 the run)."),
 ('Bava Batra 122a:6', 'LAW', "Naphtali and Ginnosar; so for each and every tribe. the_land('lots_mouth')."),
 ('Bava Batra 122a:7', 'CONTEXT', "the future division — every man a portion in mountain, lowland and valley (Ezek 48:31, 48:29): the Holy One distributes personally."),
 ('Bava Batra 122a:8', 'LAW', "conclude: divided by TRIBES, not to each man. CELL the_land('tribes_or_skulls') — the dilemma of 121b:12 resolved; the table's tribe rows the wholes, the counted rows the shares within."),
 ('Bava Batra 122a:9', 'CONTEXT', "the thirteenth portion — the king's (Ezek 48:19, 48:21): a tract, not wages. the_land('thirteen_tribes')."),
 ('Bava Batra 122a:10', 'LAW', "'with money' — not beauty against ugliness (no fools) but NEAR Jerusalem against FAR: the near compensated the far. CELL the_land('compensation') — 26:56's 'between the many and the few' read as value."),
 ('Bava Batra 122a:11', 'DISPUTE', "R. Eliezer: compensated with money; R. Yehoshua: with land. The row compensation_mode."),
 ('Bava Batra 122b:1', 'CONTEXT', "Timnath-serah / Timnath-heres (Josh 24:30, Judg 2:9) — the fruits (R. Elazar and the reverse)."),
 ('Bava Batra 122b:2', 'LAW', "CALEB'S Hebron not by lot — 'they gave Hebron to Caleb as Moses had spoken' (Judg 1:20); a refuge city of the priests? Abaye: its outskirts (Josh 21:12). CELL the_land('only_excludes') — the second of the two 'only' excludes (Sifrei 132:3's Judges 1:20, mistyped Judges 15:13 in the reading's export, read to its verse)."),
 ('Bava Batra 122b:3', 'LAW', "the Mishnah: son and daughter alike in inheritance; the firstborn's double from the father's property, not the mother's; the daughters sustained from the father's. ZL.inheritance_order by CALL — the answer sheet THE TENT graded; the roll's registers the father's."),
 ('Bava Batra 122b:4', 'DERIVATION', "'alike' — together? a son precedes a daughter (115a). ZL.inheritance_order('ladder')."),
 ('Bava Batra 122b:5', 'DERIVATION', "Rav Nachman bar Yitzchak: property DUE the father inherited as property held. the_land('possession_before_assignment') — the mnemonic's first."),
 ('Bava Batra 122b:6', 'DERIVATION', "already taught at 116b — Zelophehad's three portions (the left-Egypt portion, Hepher's, the firstborn's). ZL.the_daughters('three_portions')."),
 ('Bava Batra 122b:7', 'CONTEXT', "then what contrast in the Mishnah's second clause?"),
 ('Bava Batra 122b:8', 'DERIVATION', "Rav Pappa: son and daughter both take the firstborn's portion. ZL.the_daughters('three_portions')."),
 ('Bava Batra 122b:9', 'DERIVATION', "already at 116b's third portion; and the same contrast question."),
 ('Bava Batra 122b:10', 'DERIVATION', "Rav Ashi: 'this child shall inherit all' stands — a son among sons, a daughter among daughters (R. Yochanan ben Beroka's rule, 130a) — the testament's engine, outside this span."),
 ('Bava Batra 122b:11', 'CONTEXT', "in accordance with R. Yochanan ben Beroka? taught later (130a)."),
 ('Bava Batra 122b:12', 'CONTEXT', "an unattributed Mishnah followed by a dispute — the ruling not by the unattributed."),
 ('Bava Batra 122b:13', 'CONTEXT', "the contrast question again."),
 ('Bava Batra 122b:14', 'LAW', "Mar bar Rav Ashi: son and daughter EQUAL in the mother's and the father's property; the firstborn's double from the father's alone; the daughters sustained from the father's alone. ZL.inheritance_order by CALL (the mother's-property row mothers_property in ZL.DATA)."),
 ('Bava Batra 122b:15', 'DERIVATION', "'a double portion of all that he has' (Deut 21:17) — double one heir's share, or two-thirds of the whole? the inference opens. ZL.inheritance_order('firstborn_double') by CALL (Deut 21:17 the forward seat)."),
 ('Bava Batra 123a:1', 'DERIVATION', "with one brother or with five — double ONE heir's, the same in both."),
 ('Bava Batra 123a:2', 'DERIVATION', "or the reverse — double of ALL in both."),
 ('Bava Batra 123a:3', 'LAW', "the verse decides: 'in the day he causes his SONS to inherit' (Deut 21:16) — the Torah INCREASED with the brothers: the firstborn takes twice ONE heir's. ZL.inheritance_order('firstborn_double') by CALL — Deut 21:16-17 a forward seat, the family engine's Bekhorot 8:9 beside it."),
 ('Bava Batra 123a:4', 'DERIVATION', "1 Chr 5:1-2: Reuben the firstborn, his birthright given to Joseph's sons, not reckoned as firstborn; Judah prevailed, the birthright Joseph's. CELL the_roll('reuben_firstborn') — 26:5 'Reuben the firstborn of Israel' kept on the roll (Gen 46:8) against the Chronicler's transfer."),
 ('Bava Batra 123a:5', 'DERIVATION', "'birthright' (1 Chr 5:2) / 'the birthright' (Deut 21:17) — as Joseph's was double one heir's, so the generations'. the_roll('reuben_firstborn'); the_roll('ephraim_manasseh_order')."),
 ('Bava Batra 123a:6', 'DERIVATION', "Gen 48:22 'one portion above your brothers, which I took with my sword and my bow' — prayer and petition (Ps 44:7). The family engine's testament cell (G2) — credited."),
 ('Bava Batra 123a:7', 'DERIVATION', "why the extra proofs: Deut 21:16 might teach R. Yochanan ben Beroka; so 1 Chr 5:1 — Joseph's sons took TWO portions."),
 ('Bava Batra 123a:8', 'DERIVATION', "'birthright' against 'his birthright' — the identical term 'and the birthright was Joseph's'."),
 ('Bava Batra 123a:9', 'DERIVATION', "and Joseph's own double? 'one portion above your brothers' — one more than each (credited)."),
 ('Bava Batra 123a:10', 'LAW', "Rav Pappa: a palm tree? Abaye: 'Ephraim and Manasseh as Reuben and Simeon shall be mine' (Gen 48:5) — two full portions. CELL the_roll('ephraim_manasseh_order') — the roll counts Joseph's two as tribes among the twelve (26:28-37, Manasseh FIRST here against 1:32-35's Ephraim first) while Levi stands apart: Joseph's double on the census's own face (credited)."),
 ('Bava Batra 123a:11', 'CONTEXT', "R. Chelbo: why to Joseph? — the matter explicit at 1 Chr 5:1 (credited)."),
 ('Bava Batra 123a:12', 'CONTEXT', "the orphan parable — Joseph sustained Jacob; R. Chelbo's objection."),
 ('Bava Batra 123a:13', 'CONTEXT', "R. Yonatan: the firstborn fit to come from Rachel (Gen 37:2); Leah's mercy-pleas; Rachel's modesty (credited)."),
 ('Bava Batra 123a:14', 'CONTEXT', "Leah's eyes 'weak' — long-lasting gifts (R. Elazar); the animals not disparaged (Gen 7:8) (credited)."),
 ('Bava Batra 123a:15', 'CONTEXT', "Rav: literally weak — she wept at the crossroads' report."),
 ('Bava Batra 123a:16', 'CONTEXT', "the crossroads' report of the two sons; her eyelashes fell (credited)."),
 ('Bava Batra 123a:17', 'CONTEXT', "'Leah was hated' — Esau's deeds hated by her (Gen 29:31) (credited)."),
 ('Bava Batra 123a:18', 'CONTEXT', "Rachel's modesty — 'her father's brother' (Gen 29:12): the deceit exchange (credited)."),
 ('Bava Batra 123a:19', 'CONTEXT', "'I am his brother in deceit' — 'with the crooked You show Yourself subtle' (2 Sam 22:27); the signs."),
 ('Bava Batra 123a:20', 'CONTEXT', "Rachel gave the signs to Leah — 'behold, it was Leah' (Gen 29:25) (credited)."),
 ('Bava Batra 123a:21', 'DERIVATION', "Abba Chalifa Karoya: seventy in the total (Gen 46:27), sixty-nine by name — R. Chiyya bar Abba: Dinah's twin ('and [et] his daughter Dinah', 46:15); the objection from Benjamin's 'et' (43:29) opens 123b:1. CELL the_levites('jochebed') — CJ3b's five shelf answers, JO.seventy('diverge') by CALL (credited)."),
 ('Bava Batra 143b:1', 'CONTEXT', "fifty tenths in one vessel and fifty in another — the meal-offering's division after the fact; outside the span (the range named for 143b:6)."),
 ('Bava Batra 143b:2', 'CONTEXT', "the meal-offering case distinguished — sixty tenths the vessel's most; outside."),
 ('Bava Batra 143b:3', 'CONTEXT', "the ruling follows Rav Yosef in three matters (the field, the court session, the half) — outside."),
 ('Bava Batra 143b:4', 'CONTEXT', "the silk swaths — sons', daughters', daughters-in-law's — outside."),
 ('Bava Batra 143b:5', 'DERIVATION', "'I leave my property to my SONS' with one son and a daughter — is one son called 'sons'? CELL the_roll('single_son_plural') — the question 143b:6 answers from 26:8 (credited)."),
 ('Bava Batra 143b:7', 'DERIVATION', "'to my sons' with a son and a grandson — is a grandson called a son? Mar bar Rav Ashi: no (the vow's outside teaching). CELL the_roll('single_son_plural') — the roll's own grandsons-as-sons: Ard and Naaman under Bela (26:40) where Gen 46:21 lists them as Benjamin's sons (the reading's 'two moved a generation') (credited)."),
 ('Bava Batra 143b:8', 'CONTEXT', "the Mishnah: adult and minor heirs enhancing the property — to the middle unless declared; the wife likewise — outside."),
 ('Bava Batra 143b:9', 'CONTEXT', "Rava: on account of the property, not their own effort — outside."),
 ('Bava Batra 143b:10', 'CONTEXT', "R. Chanina's objection opens (the segment ends mid-sentence) — outside."),
]
