# THE NUMBERS WALK 11b — THE EXAM DOCKET, part G: the TOPIC rows Sanhedrin 105a:15-17 (Balaam — CREDITED to the Balak docket), Bava Kamma
# 38a:1-16 (the gentile's ox — outside; 38a:16 ULLA: Moses' own a-fortiori from 'harass the Midianites' to Moab, refused by Deuteronomy 2:9 —
# the Balak runner's midian_not_moab cell), Pesachim 66b:1-13 (Hillel's forgetting; ANGER AND FORGETTING — the scholar's wisdom, the prophet's
# prophecy, Eliab lowered: the Sifrei 157:9's three places at their Talmud seat) and Megillah 15a:1-22 (the prophets' names; 'WHOEVER REPORTS A
# SAYING IN THE NAME OF ITS SAYER' — the Sifrei 157:9's closing rule at its seat) — the dump's lines 1195-1355.
ROWS = [
 ('Sanhedrin 105a:15', 'CONTEXT', "CREDITED (the Balak docket) — impudence effective toward Heaven: 'you shall not go' then 'rise up and go' — the lore."),
 ('Sanhedrin 105a:16', 'CONTEXT', "CREDITED (three dockets) — Balaam lame in one leg, blind in one eye — the lore."),
 ('Sanhedrin 105a:17', 'CONTEXT', "CREDITED — Balaam's divination by his member / the bestiality with his ass (Mar Zutra / Mar son of Ravina) — the lore."),
 # ---- Bava Kamma 38a: the gentile's ox; Moses' a-fortiori on Moab
 ('Bava Kamma 38a:1', 'CONTEXT', "CREDITED (the sanctions docket) — 'of another' at the innocuous ox — the goring engine's; outside the span."),
 ('Bava Kamma 38a:2', 'CONTEXT', "the Jew's ox and the gentile's ox — difficult either way — outside the span."),
 ('Bava Kamma 38a:3', 'CONTEXT', "R. Abbahu: 'He beheld and made the nations tremble' (Habakkuk 3:6) — their money permitted — outside the span."),
 ('Bava Kamma 38a:4', 'CONTEXT', "R. Yochanan: 'He appeared from Mount Paran' (Deuteronomy 33:2) — outside the span."),
 ('Bava Kamma 38a:5', 'CONTEXT', "the baraita: the gentile's ox pays full — outside the span."),
 ('Bava Kamma 38a:6', 'CONTEXT', "why 'and another verse states'? — outside the span."),
 ('Bava Kamma 38a:7', 'CONTEXT', "Rav Mattana: the seven mitzvot unkept — exiled — outside the span."),
 ('Bava Kamma 38a:8', 'CONTEXT', "'made tremble' a term of exile by the Aramaic of Leviticus 11:21 — outside the span."),
 ('Bava Kamma 38a:9', 'CONTEXT', "Rav Yosef: their prohibitions permitted to them — outside the span."),
 ('Bava Kamma 38a:10', 'CONTEXT', "a transgressor rewarded? Mar son of Rabbana: no reward for keeping — outside the span."),
 ('Bava Kamma 38a:11', 'CONTEXT', "CREDITED — R. Meir: a gentile who engages in Torah as a High Priest ('a person', Leviticus 18:5) — outside the span."),
 ('Bava Kamma 38a:12', 'CONTEXT', "as one not commanded who performs — R. Chanina — outside the span."),
 ('Bava Kamma 38a:13', 'CONTEXT', "the two Roman officials who studied the Torah — the lore."),
 ('Bava Kamma 38a:14', 'CONTEXT', "'we will not inform the kingdom' — the lore."),
 ('Bava Kamma 38a:15', 'CONTEXT', "Ulla and the Babylonians' consolation — the lore."),
 ('Bava Kamma 38a:16', 'LAW', "CREDITED (the Balak docket) — ULLA'S CONSOLATION: 'do not be at enmity with Moab' (Deuteronomy 2:9) — what entered Moses' mind? MOSES REASONED AN A-FORTIORI BY HIMSELF: if the Midianites, who came only to help, the Torah said 'HARASS THE MIDIANITES AND SMITE THEM' (Numbers 25:17), the Moabites all the more (continued on 38b) — F1 the_vengeance: BK.phinehas_and_midian('midian_not_moab') by CALL — the debit's scope (Midian, never Moab) taught on the shelf from 25:17's own words; the war of chapter 31 the debit's run."),
 # ---- Pesachim 66b: Hillel's forgetting; anger and forgetting
 ('Pesachim 66b:1', 'CONTEXT', "Hillel's burnt offering never misused — consecrated in the courtyard — outside the span."),
 ('Pesachim 66b:2', 'CONTEXT', "consecrating on the Sabbath — the mishna's prohibition — outside the span."),
 ('Pesachim 66b:3', 'CONTEXT', "R. Yochanan: the Paschal lamb consecrated on the Sabbath — outside the span."),
 ('Pesachim 66b:4', 'CONTEXT', "driving a laden animal in an unusual manner — outside the span."),
 ('Pesachim 66b:5', 'CONTEXT', "the sons of Beteira's question; Hillel forgot: 'leave it to Israel — sons of prophets' — the forgetting (66b:6's ground)."),
 ('Pesachim 66b:6', 'LAW', "Rav Yehuda in Rav's name: WHO ACTS HAUGHTILY — a scholar's wisdom departs (Hillel, who rebuked and then forgot), a prophet's prophecy departs (Deborah, Judges 5:7 / 5:12) — F3 the_sentence: mark_of_anger's kin (the haughtiness pair beside the anger pair of 66b:7 — the link row — and 66b:8)."),
 ('Pesachim 66b:8', 'LAW', "the prophet who becomes ANGRY loses his prophecy — Elisha's anger at the king of Israel (2 Kings 3:14) and the minstrel needed (3:15) — F3: the Sifrei 157:9's 'anger begets error at three places' — Moses (31:14 → 31:21) the scholar, Elisha the prophet: the DATA row anger_seats (Moses, Elisha, Eliab on the shelf; the Sifrei's three seats of Moses' anger the reading's — Exodus 16:20, Leviticus 10:16, here — with Meribah's verse carrying no wrath-verb, measured)."),
 ('Pesachim 66b:9', 'LAW', "R. Mani bar Patish: WHOEVER BECOMES ANGRY IS LOWERED FROM HIS GREATNESS — Eliab's anger at David (1 Samuel 17:28) and 'I have rejected him' (16:7) — F3: anger_seats' third (the greatness lowered — Eruvin 63a:24's 'lowered' on Eleazar's relay the same verb: the two readings of 31:14 and 31:21 meet)."),
 ('Pesachim 66b:10', 'CONTEXT', "the Paschal lamb and the daily offering override impurity — the Passover engine's; outside the span."),
 ('Pesachim 66b:11', 'CONTEXT', "R. Yochanan from Numbers 9:10-11 — the individual deferred, the community not — the second Passover's (THE TENT sitting 2's runner); outside the span."),
 ('Pesachim 66b:12', 'CONTEXT', "Reish Lakish: the community has no remedy — outside the span."),
 ('Pesachim 66b:13', 'CONTEXT', "CREDITED (the Naso docket) — Reish Lakish's proof from Numbers 5:2's three sent out — the a-fortiori the verse forestalls — the Naso runner's; outside the span (the inference's refusal the kin of F3's rule)."),
 # ---- Megillah 15a: the prophets' names; in the name of its sayer
 ('Megillah 15a:1', 'CONTEXT', "the eight prophets from Rahab — their fathers — the lore."),
 ('Megillah 15a:2', 'CONTEXT', "Ulla: a name with the father's name — a prophet son of a prophet; with the city — of that city — the lore (the reading rule on names)."),
 ('Megillah 15a:3', 'CONTEXT', "the baraita on the obscured ancestors — Zephaniah, Ishmael son of Nethaniah — the lore."),
 ('Megillah 15a:4', 'CONTEXT', "Malachi is Mordecai? refuted — the lore."),
 ('Megillah 15a:5', 'CONTEXT', "Malachi is Ezra (R. Yehoshua ben Korcha) — the lore."),
 ('Megillah 15a:6', 'CONTEXT', "Ezra and the foreign women — the lore."),
 ('Megillah 15a:7', 'CONTEXT', "the four beauties — the lore."),
 ('Megillah 15a:8', 'CONTEXT', "Rahab by her name — the lore."),
 ('Megillah 15a:9', 'CONTEXT', "Mordecai's cry — Rav / Shmuel — the lore."),
 ('Megillah 15a:10', 'CONTEXT', "'the queen was distressed' — the lore."),
 ('Megillah 15a:11', 'CONTEXT', "Hathach is Daniel — the lore."),
 ('Megillah 15a:12', 'CONTEXT', "CREDITED (the Exodus triage, the erection docket) — 'this... this' (Esther 4:5) and the tablets' two sides (Exodus 32:15) — the lore."),
 ('Megillah 15a:13', 'CONTEXT', "one does not bring back a sad report — the lore."),
 ('Megillah 15a:14', 'CONTEXT', "Esther's fast; 'if I perish, I perish' — the lore."),
 ('Megillah 15a:15', 'CONTEXT', "'Mordecai passed' — the first day of Passover fasted / a stream crossed — the lore."),
 ('Megillah 15a:16', 'CONTEXT', "Esther clothed in royalty — the divine spirit (1 Chronicles 12:19) — the lore."),
 ('Megillah 15a:17', 'CONTEXT', "the blessing of an ordinary person — David and Daniel — the lore."),
 ('Megillah 15a:18', 'CONTEXT', "CREDITED (the Genesis triage) — the curse of an ordinary person — Abimelech and Isaac's eyes — the lore."),
 ('Megillah 15a:19', 'CONTEXT', "the water before the pot — the lore."),
 ('Megillah 15a:20', 'LAW', "R. Elazar in R. Chanina's name: WHOEVER REPORTS A SAYING IN THE NAME OF ITS SAYER BRINGS REDEMPTION TO THE WORLD — 'and Esther reported it to the king in the name of Mordecai' (Esther 2:22) — F3 the_sentence: the Sifrei 157:9's closing rule ('in the name of its sayer') at its Talmud seat — a rules-about-rules row for MIDDOT (the attribution law; the export dropped R. Yoshiyah's name at that very row — the reading's finding)."),
 ('Megillah 15a:21', 'CONTEXT', "the righteous man lost to his generation — the pearl — the lore."),
 ('Megillah 15a:22', 'CONTEXT', "'all this avails me nothing' — Rav Chisda's rich man — the lore."),
]
