# THE NUMBERS WALK 9b — THE EXAM DOCKET, part Q: Shevuot 11b:9-13a:16; Beitzah 12a:1-11, 19a:1-8 (the topic ranges); read whole, one verdict each.
ROWS = [
 ('Shevuot 11b:9', 'CONTEXT', "the dead heifer redeemed for its hide — 'from a camel, even its ear' — outside."),
 ('Shevuot 11b:10', 'LAW', "Abaye's objection from the mishna's INTERCHANGE: a goat consecrated for the Yom Kippur musaf offered at a festival's — R. Shimon: yes, one genus of atonement — F7 the_thirteen_goats' interchange case restated (the second seat)."),
 ('Shevuot 11b:11', 'DISPUTE', "RAV IDI B. AVIN (Rav Amram, R. Yochanan): THE SURPLUS DAILY-OFFERING LAMBS — R. Shimon: NOT redeemed unblemished; the Rabbis: redeemed — the parameter tamid_surplus' two arms named (F1 the_tamid's supply row)."),
 ('Shevuot 11b:12', 'CONTEXT', "who are the Rabbis? — Shekalim 4:5's incense? — outside."),
 ('Shevuot 12a:1', 'CONTEXT', "incense cannot graze — all concede — outside."),
 ('Shevuot 12a:2', 'CONTEXT', "the red heifer's value — outside."),
 ('Shevuot 12a:3', 'CONTEXT', "'they said to him' of the mishna — outside."),
 ('Shevuot 12a:4', 'DERIVATION', "the Rabbis = R. Yehuda? — 'granted by me, the court stipulates, hence the interchange; by you why?' — the interchange's ground under R. Yehuda: the stipulation (F7's interchange case, its second mechanism)."),
 ('Shevuot 12a:5', 'DERIVATION', "or R. Meir? — 'by me one atonement, hence the interchange' — the interchange's ground under R. Meir: the flat tier — no proof."),
 ('Shevuot 12a:6', 'CONTEXT', "R. Yochanan's tradition — outside."),
 ('Shevuot 12a:7', 'LAW', "R. YITZCHAK IN R. YOCHANAN'S NAME: under R. Shimon the surplus tamid lambs SUPPLEMENT THE ALTAR (kayitz ha-mizbeach — 'the altar's dessert'): whenever no obligatory offering stands, supplementary burnt offerings so the altar is not idle — F1 the_tamid's supply row's third arm (the parameter tamid_surplus: redeemed / supplement the altar); the altar's IDLENESS a state the ledger could carry (a note for the effects file: no new effect — the supplementary olah is OFF.dispatch('olah:flock') by CALL)."),
 ('Shevuot 12a:8', 'CONTEXT', "R. Shmuel b. Rav Yitzchak: lost communal sin offerings — supplements bought with their value, not the animals — the chatat engine's."),
 ('Shevuot 12a:9', 'CONTEXT', "olah to olah the animal itself; chatat to olah barred by decree — the chatat engine's."),
 ('Shevuot 12a:10', 'CONTEXT', "the baraita on the lost bull and goat — the yoma runner's."),
 ('Shevuot 12a:11', 'CONTEXT', "the decree inferred — outside."),
 ('Shevuot 12a:12', 'CONTEXT', "CREDITED in substance (Mishnah Yoma 6:1 — the yoma exam) — the superfluous goat grazes — the yoma runner's."),
 ('Shevuot 12a:13', 'CONTEXT', "the decree inferred — outside."),
 ('Shevuot 12a:14', 'CONTEXT', "Mishnah Temurah 3:3 — the guilt offering whose owner died — the asham engine's."),
 ('Shevuot 12a:15', 'CONTEXT', "the decree concluded — outside."),
 ('Shevuot 12a:16', 'CONTEXT', "the baraita: what from the surplus lambs? — (continued)."),
 ('Shevuot 12b:1', 'CONTEXT', "'dessert like white figs for the altar' — Lev 2:11's honey ban; Rav Chanina's simile — the supplement's name (F1's supply row)."),
 ('Shevuot 12b:2', 'CONTEXT', "no bird burnt offering as a supplement — no communal bird olah (Rav Shimi of Nehardea) — a supply datum."),
 ('Shevuot 12b:3', 'LAW', "RAV YEHUDA IN SHMUEL'S NAME: COMMUNAL OFFERINGS' CONSECRATION DEFINES ONLY THE GENUS (sin or burnt); THE KNIFE DEFINES THE SPECIES — the musaf lamb and the tamid lamb ONE STOCK until slaughter: F1 the_tamid / F7 the_calendar's supply model (the parameter communal_consecration: genus-only) — the tables' animals drawn from one herd, named at the knife."),
 ('Shevuot 12b:4', 'LAW', "R. SHIMON CONCEDES: A GOAT CONSECRATED FOR A FESTIVAL'S MUSAF not offered → offered at a NEW MOON; not there → at YOM KIPPUR; not there → at a festival; not this festival → another — the FULL ROTATION: the thirteen goats' interchange ring (F7 the_thirteen_goats' interchange case: the answer sheet's cycle festival → new moon → Yom Kippur → festival; the goat consecrated 'to atone by the outer altar', its species by the knife)."),
 ('Shevuot 12b:5', 'LAW', "the baraita: the sin offering consecrated only to atone by the outer altar — the ring's ground restated."),
 ('Shevuot 12b:6', 'CONTEXT', "the intentional defiling — the inner goat and the day — from where? — the yoma runner's."),
 ('Shevuot 12b:7', 'CONTEXT', "Lev 16:16's 'rebellions' and 'sins' by 2 Kgs 3:7, 8:22, Lev 4:2 — the yoma runner's."),
 ('Shevuot 12b:8', 'CONTEXT', "the scapegoat's row restated — the yoma runner's."),
 ('Shevuot 12b:9', 'CONTEXT', "the mishna repetitious? — outside."),
 ('Shevuot 12b:10', 'CONTEXT', "Rav Yehuda's reading — the uncertain transgressions — outside."),
 ('Shevuot 12b:11', 'CONTEXT', "the positive mitzva — repented or not (Prov 21:27) — outside."),
 ('Shevuot 12b:12', 'CONTEXT', "R. Zeira — (cut)."),
 ('Shevuot 13a:1', 'CONTEXT', "Rebbi: Yom Kippur atones without repentance save three — outside (the yoma runner's)."),
 ('Shevuot 13a:2', 'CONTEXT', "CREDITED (the Shelach exam) — Num 15:31's double verb — the shelach runner's."),
 ('Shevuot 13a:3', 'CONTEXT', "'his sin is upon him' — outside."),
 ('Shevuot 13a:4', 'CONTEXT', "the Rabbis' reading — this world and the next — outside."),
 ('Shevuot 13a:5', 'CONTEXT', "the mishna's clauses' authorship — outside."),
 ('Shevuot 13a:6', 'CONTEXT', "Rav Yosef — outside."),
 ('Shevuot 13a:7', 'CONTEXT', "Abaye's question — outside."),
 ('Shevuot 13a:8', 'CONTEXT', "Rav Yosef's answer — outside."),
 ('Shevuot 13a:9', 'CONTEXT', "the Sifra's baraita — the sin and guilt offerings' comparison — outside."),
 ('Shevuot 13a:10', 'CONTEXT', "'YET (akh) on the tenth' (Lev 23:27) divides — atones for the repentant — the moadim's verse; outside."),
 ('Shevuot 13a:11', 'CONTEXT', "the Sifra's unattributed = R. Yehuda — outside."),
 ('Shevuot 13a:12', 'CONTEXT', "the second Sifra baraita: 'it is' — the day atones without the fast or the rest — the moadim's; outside."),
 ('Shevuot 13a:13', 'CONTEXT', "Abaye's resolution — outside."),
 ('Shevuot 13a:14', 'CONTEXT', "Rava's — karet for violating the day only with repentance — outside."),
 ('Shevuot 13a:15', 'CONTEXT', "labor on the night, died that night — the day's atoning part the DAYTIME (a clocks datum: Yom Kippur's atonement at the day, F5 the_tenth's slot) — outside."),
 ('Shevuot 13a:16', 'CONTEXT', "'rather' — (cut)."),
 ('Beitzah 12a:1', 'CONTEXT', "the hinge — Beit Shammai / Beit Hillel — the festival labor block's."),
 ('Beitzah 12a:2', 'CONTEXT', "MISHNAH BEITZAH 1:5 — carrying out a child, a lulav, a scroll on a festival — Beit Hillel permit — the food-work rule's reach (MO.work_class 'servile_only' by CALL)."),
 ('Beitzah 12a:3', 'CONTEXT', "CREDITED (the Exodus triage) — slaughtering a gift offering on a festival flogged (Exod 12:16) — the leaven block's."),
 ('Beitzah 12a:4', 'LAW', "'SINCE it was permitted for food, it was permitted not for food' (mitokh) — Beit Hillel; Beit Shammai deny — F4 food_work's parameter (food_work_extension: Beit Hillel's 'since' / Beit Shammai's food-only) — the festival's labor class (28:18 'no servile work') EXPOUNDED to its edge: the reading's claim PN28B on the 'servile' token at its exam seat."),
 ('Beitzah 12a:5', 'CONTEXT', "Rabba: perhaps eiruv and carrying out apply to Shabbat, not the festival (Jer 17:22) — the alternative."),
 ('Beitzah 12a:6', 'CONTEXT', "Beit Shammai: carrying out applies to the festival too — outside."),
 ('Beitzah 12a:7', 'CONTEXT', "Beit Hillel: 'on the Sabbath day' (Jer 17:22) — no carrying-out ban on a festival — outside."),
 ('Beitzah 12a:8', 'CONTEXT', "Rav Yosef: stones (muktze) not disputed — all agree carrying out is barred, permitted for sustenance — outside."),
 ('Beitzah 12a:9', 'CONTEXT', "the dispute located at 'since' — the parameter's seat restated."),
 ('Beitzah 12a:10', 'CONTEXT', "R. Yochanan likewise — the sciatic nerve in milk on a festival: five floggings — outside."),
 ('Beitzah 12a:11', 'CONTEXT', "the five enumerated — (cut)."),
 ('Beitzah 19a:1', 'CONTEXT', "immersing a vessel on a festival — the Rabbis — outside."),
 ('Beitzah 19a:2', 'CONTEXT', "no immersion at twilight on the festival's eve — outside."),
 ('Beitzah 19a:3', 'CONTEXT', "R. Shimon Shezuri: even on a weekday — the vessel requires sunset — the clocks engine's (the sunset rule by CALL)."),
 ('Beitzah 19a:4', 'CONTEXT', "'intention evident from actions' — the running man — outside."),
 ('Beitzah 19a:5', 'CONTEXT', "the Rabbis' reading — outside."),
 ('Beitzah 19a:6', 'CONTEXT', "R. Shimon Shezuri's — outside."),
 ('Beitzah 19a:7', 'CONTEXT', "Rava: the lentil-bulk creeping animal — outside."),
 ('Beitzah 19a:8', 'CONTEXT', "from one principle to another — the winepress — outside."),
]
