# THE NUMBERS WALK 9b — THE EXAM DOCKET, part N: Rosh Hashanah 5a:9, 16a:1-17, 32a:1-32b:26 (the topic ranges); read whole, one verdict each.
ROWS = [
 ('Rosh Hashanah 5a:9', 'CONTEXT', "the peace offerings in place of a Paschal lamb and independently — the baraita's repetition; outside."),
 ('Rosh Hashanah 16a:1', 'CONTEXT', "MISHNAH ROSH HASHANAH 1:2 — four judgments: Pesach the grain, Shavuot the tree's fruit, Rosh Hashanah all creatures, Sukkot the water — the year's four seasons (the offerings' rationale below at 16a:14-15)."),
 ('Rosh Hashanah 16a:2', 'CONTEXT', "which grain — the coming year's — outside."),
 ('Rosh Hashanah 16a:3', 'CONTEXT', "two judgments per crop (the baraita) — outside."),
 ('Rosh Hashanah 16a:4', 'CONTEXT', "Rava and Abaye on sowing — outside."),
 ('Rosh Hashanah 16a:5', 'CONTEXT', "whose is the mishna? — outside."),
 ('Rosh Hashanah 16a:6', 'CONTEXT', "R. Meir / R. Yehuda on the judgment and the sealing — outside."),
 ('Rosh Hashanah 16a:7', 'CONTEXT', "R. Yosei daily, R. Natan hourly (Job 7:18) — outside."),
 ('Rosh Hashanah 16a:8', 'CONTEXT', "the mishna as R. Yehuda? — outside."),
 ('Rosh Hashanah 16a:9', 'CONTEXT', "Rava: the school of R. Yishmael — outside."),
 ('Rosh Hashanah 16a:10', 'CONTEXT', "R. Yosei's reason — outside."),
 ('Rosh Hashanah 16a:11', 'CONTEXT', "1 Kgs 8:59 'each day' — outside."),
 ('Rosh Hashanah 16a:12', 'CONTEXT', "the king judged first — aggadah."),
 ('Rosh Hashanah 16a:13', 'CONTEXT', "daily prayer for the sick — R. Yosei or R. Yitzchak — outside."),
 ('Rosh Hashanah 16a:14', 'DERIVATION', "R. Yehuda in R. AKIVA's name: WHY the omer on Pesach — the grain's season; WHY the two loaves on Shavuot — the tree's fruit's — the offerings' reasons by the year's seasons (F4 firstfruits_day's rationale; the moadim's)."),
 ('Rosh Hashanah 16a:15', 'LAW', "WHY POUR WATER ON SUKKOT — 'that the year's rains be blessed for you' — R. AKIVA'S INDUCTION from the seasons (the Sifrei 150:1's first source) ON THE TALMUD'S PAGE: F6 the_water_libation's parameter water_libation_source, the induction arm at its exam seat; the Kingships, Remembrances and Shofarot the prayer's."),
 ('Rosh Hashanah 16a:16', 'CONTEXT', "R. Abbahu: the ram's horn recalls Isaac's binding — aggadah on F5's instrument."),
 ('Rosh Hashanah 16a:17', 'CONTEXT', "R. Yitzchak: tekia and terua sitting and standing — the prayer's practice; 'a memorial of teruah' (Lev 23:24) the ink."),
 ('Rosh Hashanah 32a:1', 'CONTEXT', "an ordinance of Rabban Yochanan b. Zakkai — (the tail of the previous page)."),
 ('Rosh Hashanah 32a:2', 'CONTEXT', "MISHNAH ROSH HASHANAH 4:5 — the order of the additional prayer's blessings (R. Yochanan b. Nuri) — the prayer."),
 ('Rosh Hashanah 32a:3', 'CONTEXT', "the Sanctification of the Day, Remembrances, Shofarot with the blasts — the prayer."),
 ('Rosh Hashanah 32a:4', 'CONTEXT', "R. Akiva's order — the prayer."),
 ('Rosh Hashanah 32a:5', 'CONTEXT', "why mention Kingship without blasts? — ten verses — the prayer."),
 ('Rosh Hashanah 32a:6', 'CONTEXT', "the three opening blessings from Ps 29:1-2 — the prayer."),
 ('Rosh Hashanah 32a:7', 'CONTEXT', "R. Eliezer: Lev 23:24's four terms = the four blessings ('a memorial' Remembrances, 'blasts' Shofarot) — the moadim's verse read for the prayer."),
 ('Rosh Hashanah 32a:8', 'CONTEXT', "R. Akiva's reading of the four terms — the prayer."),
 ('Rosh Hashanah 32a:9', 'CONTEXT', "Rebbi: Kingship from 'I am the LORD your God' (Lev 23:22) beside 'the seventh month' — the prayer."),
 ('Rosh Hashanah 32a:10', 'CONTEXT', "CREDITED (the Beha'alotcha exam) — R. Yosei b. Yehuda: Num 10:10's 'over your burnt offerings... a remembrance... I am the LORD your God' — Kingship with Remembrances; the trumpets' verse the Beha runner's."),
 ('Rosh Hashanah 32a:11', 'CONTEXT', "CREDITED — Rebbi: the Sanctification of the Day in the fourth blessing — the prayer."),
 ('Rosh Hashanah 32a:12', 'CONTEXT', "CREDITED — Rabban Shimon b. Gamliel: with Remembrances, the fifth — the prayer."),
 ('Rosh Hashanah 32a:13', 'CONTEXT', "CREDITED — Usha's two prayer leaders — the prayer's practice."),
 ('Rosh Hashanah 32a:14', 'CONTEXT', "R. Zeira on Rabban Shimon b. Gamliel — the prayer."),
 ('Rosh Hashanah 32a:15', 'CONTEXT', "'the second day' — the next year (Elul never full since Ezra — R. Chanina b. Kahana: a calendar datum)."),
 ('Rosh Hashanah 32a:16', 'CONTEXT', "MISHNAH 4:6 — ten verses each; R. Yochanan b. Nuri three — the prayer."),
 ('Rosh Hashanah 32a:17', 'CONTEXT', "Rebbi: the ten 'praise Him' of Ps 150 — the prayer."),
 ('Rosh Hashanah 32a:18', 'CONTEXT', "CREDITED — Rav Yosef the Ten Commandments; R. Yochanan the ten utterances of creation — the prayer."),
 ('Rosh Hashanah 32a:19', 'CONTEXT', "CREDITED (the creation unit) — nine 'and He said' plus 'in the beginning' (Ps 33:6) — the prayer."),
 ('Rosh Hashanah 32a:20', 'CONTEXT', "R. Yochanan b. Nuri's three — nine or three? — the prayer."),
 ('Rosh Hashanah 32a:21', 'CONTEXT', "seven for the seven firmaments — the prayer."),
 ('Rosh Hashanah 32a:22', 'CONTEXT', "three for the Torah, Prophets, Writings (or priests, Levites, Israelites); the halakhah as R. Yochanan b. Nuri — the prayer."),
 ('Rosh Hashanah 32a:23', 'CONTEXT', "MISHNAH 4:6b — no verses of punishment; begin with the Torah, end with the Prophets; R. Yosei — the prayer."),
 ('Rosh Hashanah 32b:1', 'CONTEXT', "verses of punishment excluded (Ezek 20:33) — the prayer."),
 ('Rosh Hashanah 32b:2', 'CONTEXT', "Ps 78:39, Hos 5:8 — the prayer."),
 ('Rosh Hashanah 32b:3', 'CONTEXT', "the gentiles' punishment permitted — the prayer."),
 ('Rosh Hashanah 32b:4', 'CONTEXT', "CREDITED (the prayerbook block) — no individual's remembrance — the prayer."),
 ('Rosh Hashanah 32b:5', 'CONTEXT', "CREDITED (four dockets) — revisitings as remembrances (R. Yosei) — the prayer."),
 ('Rosh Hashanah 32b:6', 'CONTEXT', "CREDITED — Sarah as many — the prayer."),
 ('Rosh Hashanah 32b:7', 'CONTEXT', "Ps 24:7-10 counted — the prayer."),
 ('Rosh Hashanah 32b:8', 'CONTEXT', "R. Yehuda's count — the prayer."),
 ('Rosh Hashanah 32b:9', 'CONTEXT', "Ps 47:7-9 — the prayer."),
 ('Rosh Hashanah 32b:10', 'CONTEXT', "Lev 23:24 counted for Remembrances and Shofarot (R. Yosei) or Remembrances alone (R. Yehuda) — the moadim's verse in the prayer."),
 ('Rosh Hashanah 32b:11', 'CONTEXT', "CREDITED (the Balak exam) — Num 23:21 'the teruah of a king' — Kingship and Shofarot — the Balak runner's."),
 ('Rosh Hashanah 32b:13', 'CONTEXT', "R. Yosei's 'concluded' — ab initio or after the fact — the prayer."),
 ('Rosh Hashanah 32b:14', 'CONTEXT', "CREDITED — the vatikin concluded with the Torah — the prayer."),
 ('Rosh Hashanah 32b:15', 'CONTEXT', "CREDITED (three dockets) — only three Torah verses of Kingship (Num 23:21, Deut 33:5, Exod 15:18) — the prayer."),
 ('Rosh Hashanah 32b:16', 'CONTEXT', "CREDITED — 'Hear, O Israel' a verse of Kingship (R. Yosei) — the prayer."),
 ('Rosh Hashanah 32b:17', 'CONTEXT', "Deut 4:39, 4:35 — the prayer."),
 ('Rosh Hashanah 32b:18', 'CONTEXT', "MISHNAH 4:7 — THE SECOND PRAYER LEADER (the additional prayer's) SOUNDS THE SHOFAR; the first recites hallel — the shofar at the musaf prayer, the prayer modeled on the musaf offering (Megillah 20b:12): a note for F5's day, the offering's hour mirrored in the prayer."),
 ('Rosh Hashanah 32b:19', 'CONTEXT', "'the splendor of the King in the multitude' — the prayer."),
 ('Rosh Hashanah 32b:20', 'CONTEXT', "the vigilant early — the prayer."),
 ('Rosh Hashanah 32b:21', 'CONTEXT', "R. Yochanan: the persecution's guards — the shofar delayed to the musaf — the prayer's history."),
 ('Rosh Hashanah 32b:22', 'CONTEXT', "no hallel on Rosh Hashanah and Yom Kippur — the books open (R. Abbahu) — the prayer."),
 ('Rosh Hashanah 32b:23', 'CONTEXT', "MISHNAH 4:8 — the shofar's limits: no Shabbat limit, no rubble, no tree, no riding, no swimming, no cutting; water or wine into it permitted — F5's facilitators barred (the Shabbat 131b parameter's mishna)."),
 ('Rosh Hashanah 32b:24', 'CONTEXT', "children not prevented; the unaware sounder — the prayer's intent rule."),
 ('Rosh Hashanah 32b:25', 'CONTEXT', "a positive does not override a positive with a negative — the rule."),
 ('Rosh Hashanah 32b:26', 'CONTEXT', "'this, and it is unnecessary to say that' — the mishna's style."),
]
