# O11 batch B5 — THE SIFRA + LEVITICUS'S TEACHERS + THE FIFTEEN ONKELOS ROWS DEFERRED AT B1, decided 2026-09-09 by reading
# scratchpad o11_b5_p1..p3.txt whole (484 rows: Sifra 450, teachers 19, Onkelos 15).
# The rules: B3's (the headline assertion leads; a catalogued form wins a tie over `plain`) and B4's BUNDLE RULE (a Sifra row
# bundles two to ten readings under one headline: the FIRST leg's form leads, every later leg's catalogued form is named in the
# note). Two riders: where the row NAMES the tradition's own middah (a building principle, a verbal analogy, went-out-to-teach,
# Hermeneutical Principle N) the label takes it; the fifteen Onkelos rows are Sifra bundles whose first leg is a Sifra reading,
# so they take that reading's form and Onkelos's rendering is named in the note as the ink leg.
# The unit's book is Leviticus: a rule of conduct or ritual takes the I code, a narrative reading the E code; E1/E2 carry the
# Sifra's to-include / to-exclude readings at law strength per the vocabulary's note.
import re
BATCH = 'B5'

TEXT = {
    'plain': "plain (a teacher's statement — the Sifra's reading of the verse's own wording as the rule, a definition, a recorded dispute, or the answer sheet's rows on the verse; no catalogued inference form leads)",
    'ink':   "ink (the verse's own written form or count — a token census, a spelling, a paragraph break, the received translation's rendering; no rule moved)",
    'E1':    "E1 (the inclusion read — the Sifra's to-include on the particle or the widening word; law strength)",
    'E2':    "E2 (the restriction read — the Sifra's to-exclude on the particle, the pronoun, or the narrowing word; law strength)",
    'E10':   "E10 (repetition signifies — the doubled, tripled, or re-stated expression read; law strength)",
    'E26':   "E26 (the parable)",
    'E27':   "E27 (symmetry — measure for measure, the mirror at two seats)",
    'E28':   "E28 (from the preceding — the juxtaposition read)",
    'E30':   "E30 (notarikon — the word's letters as an acronym)",
    'E32':   "E32 (earlier that is later — a verse out of its order)",
    'I1':    "I1 (the a-fortiori at law strength)",
    'I2':    "I2 (the equal decree — a rule carried on the shared wording, law strength)",
    'I3':    "I3 (the paradigm case — the building principle: the exemplar generalized into the rule)",
    'I4':    "I4 (the general and the particular — the general holds only what the particular names)",
    'I8':    "I8 (a particular singled out from the general, teaching about the whole general)",
    'I11':   "I11 (a particular that departed for a new teaching is restored to its general only by the verse's own word)",
    'I12':   "I12 (the meaning decided from context)",
    'I13':   "I13 (two verses contradicting, or a resolution, decides — law strength)",
    'M-03':  "M-03 (the comparison — a rule computed by a recorded likeness between two cases)",
    'M-05':  "M-05 (the threshold-parse — a numeric constant read out of the verse's own tokens)",
    'M-09':  "M-09 (the keyword dictionary — the text's own rule for one of its words)",
    'M-10':  "M-10 (the pointer-fetch — a label here, the procedure or the constant at another seat)",
    'M-11':  "M-11 (the word-order read — the sequence of the clauses itself is the rule)",
    'M-12':  "M-12 (the grammatical-number hook — the plural or the number carries the law)",
    'M-13':  "M-13 (the clause-position read — where an operand sits decides what it binds)",
    'M-16':  "M-16 (the revocalization read — the consonants held, re-pointed, and the second reading stands)",
    'M-18':  "M-18 (the freed token — a clause already known is reassigned to a second job)",
    'M-20':  "M-20 (the warning completion — a punishment written in one place armed by a warning written in another)",
    'M-22':  "M-22 (the run read back into the spec — the narrated execution teaches the procedure)",
    'M-23':  "M-23 (the second seat's delta — two writings diffed, the drop, addition, or reversal read)",
}

DEC = {
 # lev_01 — the call, the burnt offering (bird, cattle, flock)
 'LV01A-01': ('I3', "the call before every speaking built from two exemplars, the bush and Sinai — the building principle; the doubled name, E10, beside"),
 'LV01A-02': ('E2', "'to him' excludes Aaron, the elders, the sons, the angels; the voice cut at the tent's boundary"),
 'LV01A-03': ('ink', "the paragraph breaks themselves — the tradition's account of the scroll's pauses as time for reflection"),
 'LV01A-04': ('E1', "proselytes included then heretics excluded on covenant-acceptance — include-then-exclude; the offering-and-Name pairing an ink invariant"),
 'LV01A-05': ('E2', "domesticated only — the species words exclude the paired, the worshipped, the designated, the torn, the killer ox"),
 'LV01A-06': ('plain', "the acceptance gate — unblemished as predicate, the owner transports, the remiss vower compelled; R. Chiyya's caller-layer split"),
 'LV01D-01': ('plain', "the bird spec — the two species' complementary age windows; no sex predicate because the verse carries no sex token"),
 'LV01D-02': ('plain', "the pinch rite as the Sifra's recorded procedure walk"),
 'LV01D-03': ('plain', "the crop removed with its contents; the ash depository east of the ramp; the received translation's 'its food' the ink leg"),
 'LV01D-04': ('plain', "rend with the feathers; the deviation table — dividing valid after the fact, the knife-pinch fatal"),
 'LV01D-05': ('ink', "the compiled run — the verse's four verbs stand as ink, the Mishnah's additions the Sifra's own rows (Zevachim 6:5-7, 7:2, 7:5 verbatim)"),
 'LV01B-01': ('E2', "'his hand' — no delegation: wife, bondsman, messenger excluded; sons not daughters with the recorded dispute"),
 'LV01B-02': ('plain', "the role table read off the verse's own role words — slaughter by anyone, receiving onward priest-only"),
 'LV01B-03': ('plain', "the blood algorithm — two applications that are four; the spill and mixture tables"),
 'LV01B-04': ('plain', "the man-made fire beside the heavenly; the wood species; the two extra afternoon logs from the plural, M-12, beside"),
 'LV01B-05': ('plain', "any-amount water; the altar's no-return; 'the whole' includes attached parts, E1, beside; the intent ladder with the translation's acceptance verb"),
 'LV01C-01': ('E2', "the flock filter — sick, old, malodorous, stolen, hybrid excluded; the seam's conjunction transfers both ways and its pause is the paragraph channel's second witness, ink"),
 'LV01C-02': ('plain', "the north as environment-dependent; the per-role positions; the geometry disputes"),
 'LV01C-03': ('M-12', "one priest per two limbs computed from the two verb-numbers; head and suet a first class"),
 'LV01C-04': ('plain', "the teacher's own gates-versus-advisory sort — valid without flaying, cutting, hand-laying; invalid without the north"),
 # lev_02 — the meal offering
 'LV02-01': ('plain', "the single-caller exception and the standalone-donation menu, closed at incense by Exod 30:9"),
 'LV02-02': ('plain', "oil on all, frankincense on part — placement follows sample participation; any man pours, the priest takes"),
 'LV02-03': ('plain', "the fistful constant not linear; the three-finger measure; sample purity"),
 'LV02-04': ('plain', "the quantity floors on the data channel — any shortfall invalidates"),
 'LV02-05': ('plain', "the vow parser's normalization table with R. Shimon's void-instead reading"),
 'LV02-06': ('plain', "role-differentiated processing — fold-to-quarters on three paths; the vessel taxonomy dispute"),
 'LV02-07': ('I8', "'shall not be baked' — baking singled out from the general teaches per-operation liability"),
 'LV02-08': ('plain', "the salt covenant term — fistful-class only, any salt, overriding Sabbath and impurity; the received translation's covenant-annulment language the ink leg"),
 'LV02-09': ('M-11', "parch-before-grind by the word order; the if-word as intent grading, M-09, beside"),
 'LV02-10': ('plain', "the adjunct matrix closed member by member; the two loaves' schedule"),
 'LV02-11': ('plain', "the answer sheet routed by topic — Menachot 12-13 carrying the Sifra's vow tables; 13:1-2's five the chapter's own census by token, ink, beside"),
 # lev_03 — the peace offering
 'LV03-01': ('M-09', "the name read — peace distributed three ways, altar, priests, owners; the mourner gate; the tithe-miscount asymmetry"),
 'LV03-02': ('plain', "multi-caller hand-laying in turn; the heir excluded by R. Yehudah; the exception list; class propagation"),
 'LV03-03': ('E10', "the tripled slaughter-verb licenses secular slaughter at Deut 12:21 — the cross-book hook, M-07, beside"),
 'LV03-04': ('plain', "the six-field intent vector read off the verse's own terms"),
 'LV03-05': ('plain', "the anatomy predicate defined; the lobe settled by Lev 9:10's run, M-22, beside; the recorded pair"),
 'LV03-06': ('plain', "the fat-tail spec; the expired paschal offering's type conversion"),
 'LV03-07': ('E10', "three smoke-verb variants, each assigned a constraint — valid-only, no mixing, all at once"),
 'LV03-08': ('ink', "law from a hiatus — the goat's paragraph break itself carries the no-fat-tail exemption"),
 'LV03-09': ('plain', "the eating ban's scope — eternal, all generations, all dwellings; the order-equivalence rule"),
 'LV03-10': ('E10', "the tripled tent clause carries the all-sides site rule; the count mechanism; the open-doors condition on the two words' difference, M-09, beside"),
 'LV03-11': ('ink', "the fat inventory per species from Lev 3's own verses; the tail token at 3:9 and 7:3 only — the census; compiled into the offerings dispatcher"),
 # lev_04 — the sin offering's case tree
 'L04-11': ('plain', "aggregation keys — liability counted by the missing knowledge; partial acts; the whole-doer rule with the joint-actor dispute"),
 'L04-12': ('plain', "the blood algorithms of the inner sin offerings"),
 'L04-13': ('M-09', "congregation means the court — the keyword; all-fit composition, unanimity, the ruling-versus-act split, the located error"),
 'L04-14': ('plain', "the per-tribe bulls with four recorded positions"),
 'L04-15': ('M-12', "the elders' quorum computed from the plurals — five (R. Yehudah) against three (R. Shimon)"),
 'L04-16': ('plain', "the epistemic triggers — self-knowledge not report; the witness and credibility disputes"),
 'L04-17': ('plain', "tier fences and ownership locks; the five death-consigned sin offerings"),
 'L04-18': ('plain', "enumeration order is not rank; lost-and-replaced — either, but only one"),
 'L04-19': ('ink', "the censuses at their Talmud seats — 'his God' at 4:22 alone, the domain phrase at five seats, the known-tokens, the three outside-the-camp verses; compiled cold"),
 'L04-20': ('M-10', "the pointer names the species — 4:10's ox and the goats fetched from Lev 3's per-species inventory by live call; the tail token's two seats, ink, beside"),
 # lev_05 — the graded offering and the sacrilege offering
 'LV05A-01': ('plain', "the witness-oath machinery — monetary testimony, the principal's adjuration, fit witnesses, the court forum"),
 'LV05A-02': ('plain', "the impurity trigger's awareness state-machine — aware, hidden, aware"),
 'LV05A-03': ('plain', "the utterance oath — the lips-and-heart boundary, past and future, only the forgotten oath triggers; the received translation's articulation verb the ink leg"),
 'LV05A-04': ('plain', "confession with the offering; the individuation algorithm — R. Meir against R. Yehudah"),
 'LV05A-05': ('plain', "the poverty ladder — the hand-test, transitions both ways, funds carrying across tiers"),
 'LV05A-06': ('E27', "the sin-bird's rite as the burnt-bird's mirror — one sign, the lower wall against the upper"),
 'LV05A-07': ('plain', "the flour tier stripped of adjuncts; the tenth-of-ephah conversion written into the received translation's verse, ink, beside"),
 'LV05A-08': ('plain', "tier orthogonality — the scale rides the offerer's means, never the trigger's gravity"),
 'LV05A-09': ('plain', "the answer sheet's row seated — the quick-exit rule, Mishnah Shevuot 2:3 at exam round 10"),
 'LV05B-01': ('plain', "the sacrilege predicate — damage and benefit together, accumulation, fund-locking, the accessory table; the received translation's falsehood-verb and coin conversion the ink leg"),
 'LV05B-02': ('plain', "fund-addressed restitution; the fifth as the added quarter — principal and fifth are five, M-05, beside; principal and ram independent"),
 'LV05B-03': ('plain', "the suspended guilt offering — per-doubt liability, the doubt interval, R. Akiva's concession"),
 'LV05B-04': ('plain', "the deposit oath's anti-loophole enumeration; the fine-class exclusions, E2, beside; R. Akiva's silent-witness reading; the received translation's unification the ink leg"),
 'LV05B-05': ('plain', "restitution first and in kind; own-act liability; the father-oath matrix"),
 'LV05B-06': ('plain', "the payment algebra — the fifth rides the oath, principal not fines, the recursive fifth to the smallest coin"),
 'LV05B-07': ('plain', "the individuation rule at the deposit tier; the smallest-coin floor seals the trigger — the same rule recurring, not a doubled expression"),
 # lev_06 — the law of the burnt offering, the meal offering, the sin offering
 'LV06-01': ('plain', "the night window — limbs placed at sunset burn all night, the day-pieces riding the comprehensive 'law of the burnt offering'; 'until the morning' freed to the ash removal, M-18, beside; the one-way altar's recorded three-way"),
 'LV06-02': ('plain', "the consecrating surfaces — the altar and the ramp (Exod 29:37), the vessels typed wet and dry (Exod 30:29), inside the courtyard only"),
 'LV06-03': ('plain', "one fire source — the inner altar's fire from the outer clause; the lamp by Exod 27:20; the coal pan sealed by 'from off the altar before the LORD' read as the outer altar, the context read, I12, beside"),
 'LV06-04': ('plain', "the ash-lifting protocol — the linen cut to his size, the keyword 'his measure', M-09, beside; the innermost coals; the fire's claim to midnight"),
 'LV06-05': ('plain', "'other garments' likened to the ones taken off — consecrated but lesser; R. Elazar's blemished priests fit for the carrying"),
 'LV06-06': ('plain', "extinguishing a negative commandment; the morning precedence algorithm read off the doubled 'in the morning', E10, beside; the day bracket; the journeys' dual track; the wood-pile count a recorded number"),
 'LV06-07': ('plain', "one law for all meal offerings; the corner algorithm — 'before the LORD' intersected with 'in front of the altar' resolves to the southwest, R. Eliezer's prefer-both-verses rule, I13, beside; the fistful's vessel rules"),
 'LV06-08': ('plain', "only a valid offering's remainder; the multiplied eating-verbs, E10, permit any manner and mundane food alongside when insufficient; unleavened a commandment; the courtyard's chambers"),
 'LV06-09': ('I8', "'shall not be baked leavened' singles baking out to teach per-operation liability; the double comparison to the sin and guilt offerings, M-03, beside; R. Shimon's partition"),
 'LV06-10': ('E1', "'every male' includes the blemished for apportionment; touch-sanctification requires absorption; what touches becomes like the offering"),
 'LV06-11': ('plain', "the perpetual griddle offering — the tenth-measure gates service, anointing by day, never two high priests; the halving invariant; the received translation of 6:13 the ink leg"),
 'LV06-12': ('plain', "the griddle a ministering vessel; the oil quantity derived by resemblance to the libation meal offering, M-03, beside; 'soaked' scalded — a three-seat census, ink, beside; the baking verb's three-way"),
 'LV06-13': ('plain', "the priest's own meal offering never eaten, his daughter's eaten — the class boundary on the priest; the doubled 'entire', E10, cross-applies the whole-smoking and the eating ban"),
 'LV06-14': ('plain', "one law for all sin offerings — the washing reaches the inner ones, the exempting a-fortiori defeated, I1 refuted, beside; the bird excluded, E2; the north; the eater class; the blood above; the received translation of 6:19 the ink leg"),
 'LV06-15': ('plain', "the washing machine — fit blood with the recorded three-way, its blood, the spot, the sprinkle-fitness case table; the venue extended to breaking and scouring by juxtaposition, E28, beside; the return table"),
 'LV06-16': ('plain', "the vessel purge — earthenware breaks, copper for all metals scours and rinses; the fit-phase criterion; 'every male' closing the blemish ladder, E1, beside; the taste threshold"),
 'LV06-17': ('plain', "the entry boundary — blood even in part entering the tent, E1, beside, burns the offering; directional; the R. Eliezer and R. Shimon dispute; the burn-location matrix"),
}

DEC.update({
 # lev_07 — the guilt offering's procedure, the fat and blood dues, the peace offering's types
 'LV07A-01': ('plain', "the guilt offering's one law — not on a private altar, all blood below the red line, the leper's included; intermixed bloods and animals with R. Shimon's alternative"),
 'LV07A-02': ('M-12', "'shall THEY slaughter' — the plural opens slaughter to proselytes, women, servants; the verb defined as drawing-forth from 1 Kings 10:16's drawn-gold wording, I2 across books, beside; R. Eliezer's north"),
 'LV07A-03': ('M-13', "the restrictive 'it' at the slaughter clause for the sin offering and the paschal, after the smoking for the guilt offering — the position decides what it binds; the exchange excluded"),
 'LV07A-04': ('E1', "'every male' adds the priest born blemished; the thank offering and the Nazirite's ram excluded, E2, beside"),
 'LV07A-05': ('M-03', "as the sin offering so the guilt offering — mundane money, by day, the right hand; 'one law' adds hand-laying; the atoning priest's three exclusions, E2, beside; Rebbi's the-hide-follows-the-flesh"),
 'LV07A-06': ('I13', "'to the priest who offers it' against 'to all the sons of Aaron' resolved to the priestly household of the day; no apportionment trades; the received translation of 7:10 the ink leg"),
 'LV07A-07': ('M-23', "the ram's fat list of 7:3-4 against the lamb's at 3:9-10 part for part — the second seat matched; north and two-that-are-four by call; 'one law' as hand-laying, day, right hand, the atoning priest"),
 'LV07C-01': ('I1', "Israel not the sons of Noah — the a-fortiori from the limb of the living refuted by 'the children of Israel', a recorded negative boundary; proselytes in, unclean species out, the doubtful class inside the exhortation"),
 'LV07C-02': ('plain', "the carrion-fat of the clean beast distinct from its flesh — prohibition and impurity-exemption trade places; the doubled fat-word, E10, beside; 'for all service' answering both doubts"),
 'LV07C-03': ('plain', "the excision criterion — the fat that stands to be sacrificed by Exod 29:13's list, M-10, beside; the excision template's five clauses"),
 'LV07C-04': ('I3', "'of bird and of beast' — the named exemplars supply the criteria, excluding the blood of men, reptiles, eggs, grasshoppers, fish, E2, beside; the lifeblood; in all your habitations"),
 'LV07C-05': ('M-03', "Israel waves not gentiles — the recorded greater-measure comparison with hand-laying; sons not daughters; the stacked hands; the exclusion cascade, E2, beside; the received translation of 7:30 the ink leg"),
 'LV07C-06': ('M-11', "the breast and thigh revert only after the fat smoking by Num 5:31's clause order, the cross-book import, M-07, beside; fit at both services with Abba Shaul's mirror, E27; R. Shimon's acknowledgment gate; the sons of Eli as the violation's ledger"),
 'LV07C-07': ('plain', "the Sinai colophon — the closing list's general rules and particulars given at Sinai, argued from the investiture's own Sinai-issued spec; the received translation of 7:35 the ink leg"),
 'LV07B-01': ('I11', "the school of R. Yishmael names the eleventh middah — the thank offering departed for the loaves and is restored by 'this is the law'; the funding rules from mundane money"),
 'LV07B-02': ('E10', "R. Akiva's doubled 'with oil' by rule — increase after increase decreases; R. Elazar ben Azaryah's dissent self-labels the data channel, a law to Moses at Sinai"),
 'LV07B-03': ('I2', "the leavened measure by the leavened-leavened identity with the two loaves; the count ten off the extra letter's value, E29, beside; one-of-ten by the tithe-gift identity, a second I2"),
 'LV07B-04': ('plain', "the bread's commit point — crusting and the slaughter as such; Rebbi against R. Eliezer ben R. Shimon; loaves per offering; the Nazirite's ram"),
 'LV07B-05': ('plain', "the eating windows read off the verse's own days — one day and a night, two days and one night, by class; the received translation of 7:15 the ink leg"),
 'LV07B-06': ('plain', "the rejection machine — the thought not the deed, R. Eliezer's 'incline your ear' with R. Akiva's proof that unfitness enters at the offering; the received translation of 7:18 the ink leg"),
 'LV07B-07': ('I3', "the named building principle from Exod 29:34 — all leftover burns; touch not carrying with the red-heifer a-fortiori refuted, I1, beside; 'for it is holy' excludes what died outside, E2; the received translation of 7:19 the ink leg"),
 'LV07B-08': ('plain', "liability begins at the sprinkling — everyone clean eats; include what left or overstayed, exclude the rejected, E1 and E2, beside; the time-of-fitness criterion's third seat"),
 'LV07B-09': ('I2', "'his impurity upon him' means the body's — first by the equal decree on the repeated word with Num 19:13; then Rebbi's person-linkage, R. Chiyya's number mismatch, M-12, and the Others' criterion of an impurity that can depart, four routes in parallel; the received translation of 7:20 renders the possessive so, the ink leg"),
 'LV07B-10': ('M-03', "the rejection machine and the impurity machine set side by side — the teacher's recorded comparison of awareness, offering, class, and permitters; blood excluded"),
 # lev_08 — the investiture week
 'LV08-01': ('plain', "'take Aaron' as his re-acceptance after the calf; persons taken with words — the four-verse census of Moses' takings, ink, beside; the received translation of 8:2 the ink leg"),
 'LV08-02': ('plain', "the dressing protocol for its time and the generations; Moses the dresser; the order law clothed then anointed, M-11, beside; the received translation of 8:10 the ink leg"),
 'LV08-03': ('I3', "Aaron and his sons on one bullock — partners' offerings likened to theirs, every partner lays hands; the bullock named the sin offering's at Exod 29:14"),
 'LV08-04': ('E26', "the princess parable makes the rule explicit — the installer officiates until the installed is trained; the altar's atonement against theft with Isaiah 61:8 cited"),
 'LV08-05': ('M-22', "the burnt-offering ram's execution matched verse for verse against Leviticus 1 — the installation narrative as the compiled function's recorded run; flaying the one gap, with the recorded patch"),
 'LV08-06': ('E10', "'the second ram' re-stated to teach atomicity — the investiture one indivisible transaction; the three bloods table; the ear-ridge and the thumb; the received translation of 8:23 the ink leg"),
 'LV08-07': ('plain', "the computed calendar — from the twenty-third of Adar to the first of Nisan; the tabernacle set up and taken apart daily; the received translation of 8:33 the ink leg"),
 'LV08-08': ('I3', "'as He has done this day' exports the week for the generations — seven days' separation for the Day of Atonement's priest and the red heifer's; the vigil; the no-entity-without-a-commandment doctrine and the exchange symmetry, E27, beside; the received translation of 8:35 the ink leg"),
 # lev_09 — the eighth day
 'LV09-01': ('M-03', "eighth to the consecration by the Sinai third-day analogy, landing on the first of Nisan; 'and it was' as creation-day joy"),
 'LV09-02': ('E27', "the calf answers the calf — the species-to-offense atonement map, measure for measure"),
 'LV09-03': ('plain', "approach, and his own offering before the people's; his atones for both, theirs not for priests"),
 'LV09-04': ('M-10', "'like the first' imports the application pattern; the received translation decodes the verb as atoned-with-its-blood, ink, beside"),
 'LV09-05': ('M-10', "'as prescribed' — one word imports the Lev 1 burnt-offering table; the received translation's 'as is fitting', ink, beside"),
 'LV09-06': ('I2', "fill-fill to Lev 2:2 — the fistful's disqualifiers carried on the shared word; two meal offerings that day"),
 'LV09-07': ('plain', "the people's ox and ram seat the communal peace offering's class; the seven services learned in an hour"),
 'LV09-08': ('E32', "9:22 recorded as a transposed verse; the palms-lifting earned forever; standing by the service pairing; the text opened at Num 6:24-26"),
 'LV09-09': ('plain', "the joint entry and the fire — the incense and blessing arms, Aaron's distress, the fire answered by song; the received translation's glory-revealed policy the ink leg"),
 'LV09-10': ('M-22', "the run graded against its spec — Lev 9 as a scene against the Lev 1-8 engines by live call (cold_run_shemini_day.py, 104 of 104); the calf for the bull, the outer blood with the inner carcass, the one unstamped act, the fire formula at two seats"),
 'LV09-11': ('M-22', "the run teaches the spec — the palm, the pointer, the preposition, the blessing, the fork over whether an hour legislates; the claim names the move"),
 # lev_10 — Nadav and Avihu
 'LV10-01': ('plain', "the strange fire — token-per-fault reads; R. Yishmael's uncounseled fire against R. Akiva's stove fire; the two motive arms"),
 'LV10-02': ('plain', "the mode and the where — nostril-threads, the soul not the garments; R. Eliezer against R. Akiva; the rule-before-the-master law"),
 'LV10-03': ('M-22', "the Sinai word 'I will be sanctified through those near Me' understood at the event — the run reading the spec's clause; Aaron's rewarded silence"),
 'LV10-04': ('plain', "the carriers — priests do not defile, the Levites carry; Uzziel paired to Aaron; the received translation's kinship decode the ink leg"),
 'LV10-05': ('plain', "the mourning bans — the hair growth, the transposed weeping clause, no rites for Heaven's executed, the soul-burning export"),
 'LV10-06': ('plain', "the exit ban in service only, extended to the generations by the oil clause; the received translation's oil-of-greatness the ink leg"),
 'LV10-07': ('plain', "the wine machine — the quarter-log of forty-day wine as data, the three arms, in-service scope; the statute-statute sync, I2, beside; the received translation's functional intoxicant the ink leg"),
 'LV10-08': ('plain', "the curriculum verse — the canon layers enumerated; the Targum's status asked on the page; the ruling-death exemptions"),
 'LV10-09': ('plain', "the day's grain and portions — the hour's communal meal offering, the chambers, sons in the share, daughters in the gifts, the three command-verbs"),
 'LV10-10': ('plain', "the goat inquiry — three goats, two inquiries, the mourning-versus-impurity fork, Moses' recorded I-heard-and-forgot; the received translation of 10:19-20 the ink leg"),
 'LV10-11': ('plain', "the wine ban's two jobs at their Talmud seats — 'to distinguish' the drunk's service, 'to teach' the teaching bar; the ban today per Rabbi; the quarter-log's dissipation"),
 'LV10-12': ('plain', "the inquiry at its Talmud seat — Zevachim 101a-b carrying the Sifra verbatim, 'I offered'; the generations' mourner-ban from the tithe's a-fortiori, I1, beside"),
 # lev_11 — the dietary and impurity file
 'LV11A-01': ('plain', "the ostensive registry — the four held-and-shown classes; the cross-book dietary ledger with its per-ban sources"),
 'LV11A-02': ('plain', "both signs required; hybrids and class-inclusion, E1, beside; the land gate excluding the sea-raised, E2"),
 'LV11A-03': ('E1', "the fetus permitted through the mother's slaughter — the inclusion; the hand-returned and head-returned cases meeting the Zerach predicate"),
 'LV11A-04': ('plain', "the pincer — each written exception blocks the other's escape, both signs required; the ink-versus-argument provenance split; the birth-line rules"),
 'LV11A-05': ('plain', "the torn-animal table with its named dispute arms; the survivability predicate paired with carrion"),
 'LV11A-06': ('plain', "the touch clause — the festival-duty resolutions, joining, brine and the taste threshold; the human excluded by 'this', E2, beside"),
 'LV11A-07': ('plain', "the water predicate — waters classified by the creation verses, one fin and one scale, the Leviathan ruling, the belly inversion, the mixture quantities as data; the received translation of 11:9 the ink leg"),
 'LV11A-08': ('I3', "the eagle and the dove as paradigms training the bird predicate; the list-sync analogies; the feeder-liable passive, M-15, beside; the received translation's predicate-bearing names the ink leg"),
 'LV11A-09': ('plain', "the locust predicate — the four-part sign set with the name condition; the forward-read spelling of the negative particle, ink, beside; the fifth-leg arithmetic; R. Tzadok's testimony"),
 'LV11B-01': ('E2', "the limb of the living narrowed to the beast; the three limb definitions; the touch-and-carry paradox pair held by the ink"),
 'LV11B-02': ('plain', "the paws list from ape to elephant; slaughter does not purify the impure; the lattice closed by the ink at each corner"),
 'LV11B-03': ('plain', "the eight — blood like flesh, the half-earth mouse, the salamander, R. Akiva's habitat doxology"),
 'LV11B-04': ('plain', "skins like flesh, the embryonated pierced egg, handles, the lentil measure from the lizard's birth size"),
 'LV11B-05': ('I3', "the sack as the paradigm case — the vessel classifier's forty-seah cutoff, the complement dispute, the land-growth gate, the work test, all-at-once immersion, the twilight split"),
 'LV11B-06': ('plain', "earthenware's interior law with its mirror table against other vessels, E27, beside; nested protection; hole thresholds; R. Akiva's re-reading of the verb form with the recorded future-proofing, M-16, beside"),
 'LV11B-07': ('plain', "the airspace rule — foods yes, vessels no; the human-food gate with intent; the sealed lid"),
 'LV11B-08': ('plain', "the preparation machine — wetting prepares; the seven liquids; vessel-drawn with intent; the Torah-versus-scribes stratum split"),
 'LV11B-09': ('plain', "the seed machine — sown seed purified once rooted; the recorded minimization argument on three axes; the food-handles table"),
 'LV11B-10': ('plain', "the oven machine — cut pure, plastering the switch, R. Akiva's reversal, the firing threshold; 'it shall be broken' gating stone and metal out, E2, beside"),
 'LV11B-11': ('plain', "the immersion pool — Heaven's-hands gate, the purifying assignments, flowing against standing, Hillel's in-water row; the received translation's house-of-gathering the ink leg"),
 'LV11B-12': ('plain', "the carcass file — the slaughtered torn animal clean, the eight-month dispute, the sealed thigh-bone, hide thresholds, the swallowing-house split"),
 'LV11B-13': ('I3', "snake, scorpion, centipede as class exemplars — belly, fours, many feet; the born-inside exemption; the feeder-liable passive, M-15, beside"),
 'LV11B-14': ('ink', "the defective spelling read — 'you shall be made unclean' as 'you shall be dulled', the end is defilement; the received translation's implementing particle; the Egypt yoke-condition; holiness as separation"),
 'LV11B-15': ('M-03', "'the law of the beast and the bird' — bird slaughter from the shared-law comparison with the beast; teach the knower; the whole system's line at a hairbreadth"),
 # lev_12 — childbirth
 'LV12-01': ('ink', "the vocalization seat — two-weeks against seventy argued at the word's own pointing, 'the reading has a mother'; the received translation's fourteen the oldest witness"),
 'LV12-02': ('I1', "the a-fortiori's own case law — sufficiency held against every rephrasing; the stringent-to-lenient inference voided on form"),
 'LV12-03': ('plain', "the count's anchor — seven from the last child, consecutive, birth days as menstrual days, birth not conception, the caesarean excluded with the dissent"),
 'LV12-04': ('E1', "'on the day' — circumcision overrides the Sabbath at its source; day only; the diligent early; certain not doubtful; the born-circumcised dispute"),
 'LV12-05': ('plain', "the five bloods and the market — the source rule, the five-shade table with both houses, one offering per term, the gold-dinar collapse"),
 'LV12-06': ('M-11', "the burnt offering written first with the kind-matching rule, the written order read and set aside for the act — the sin offering first; one withholder; the dignity floor"),
 'LV12-07': ('ink', "the clocks summed — Lev 12's four written numbers add to Niddah 6:14's forty and eighty; the union of the clocks computed; compiled cold"),
 # lev_13 — the skin marks: boil and burn, the garment, the head, the intake, the skin
 'LV13B-01': ('M-09', "fire-caused is a burn, all else a boil — the text's own rule for its two words; the pre-Speaking boil counts"),
 'LV13B-02': ('plain', "the garlic-peel crust defines both; boil precedes the mark; the transmitted quarantine held without its reason"),
 'LV13B-03': ('E2', "'in the boil' — the mark spreads only inside its own region; the two-hair thread; boil and burn never combine"),
 'LV13B-04': ('plain', "the doubt polarity — spread-doubt pure both ways with R. Akiva's arm; each sign its own default; late spread counts"),
 'LV13B-05': ('E10', "three leprosy-tokens and three it-tokens, each assigned a job — the chapter audited by its own repetitions"),
 'LV13D-01': ('plain', "the species and work gate — wool and linen as created, the work-finished thresholds, tents in; the uprooter-of-mountains exchange"),
 'LV13D-02': ('ink', "the reduplicated color forms read — green of greens, red of reds; they combine; at the bean; fringes out"),
 'LV13D-03': ('M-09', "malignant read as cursed-for-loss, the received translation's 'causes loss'; the decided stays banned even shredded; the three spread grades"),
 'LV13D-04': ('plain', "standing burns — the garment-person asymmetry; worn-or-new performed by the received translation, ink, beside; the tear-and-patch grid; the striped-garment exchange"),
 'LV13D-05': ('plain', "the close — the second washing purifies, gone means gone, entry-defilement like the house, abroad alike, one priest for both verdicts"),
 'LV13C-01': ('plain', "regions apart — head and beard never combine or share spread; by Heaven's hands only; only scall impurity there"),
 'LV13C-02': ('plain', "black hair saves — gold-form yellow, the thin-hair dispute, the rescue sign, intake-release, the nested-scall flip"),
 'LV13C-03': ('plain', "the gauge rule — shave around with anything, even the Nazirite; two hairs left as the spread-detector; plucking signs a Torah violation"),
 'LV13C-04': ('plain', "the truth gate — the office cannot invert the fact, Hillel's ascent on this matter; proxy eyes; latching purity"),
 'LV13C-05': ('plain', "the bald spots — the crown's slope divides two regions; two signs, no white hair, two weeks, at the bean; whole-head scall pure"),
 'LV13C-06': ('plain', "the decreed leper — loosed and rent, the man only even a high priest; the doubled warning cry in the received translation, E10, beside; alone; three camps out"),
 'L13-05': ('plain', "the declaration protocol — the sage examines, the office pronounces, even a fool priest; one priest, by day, not before kin"),
 'L13-06': ('plain', "the calibration layer — the middling standard, the reference swatch, the hours table, the dim-eye carve, the expert certification"),
 'L13-07': ('plain', "the shared seventh — thirteen days not fourteen; round trips cancel; the same priest at both looks"),
 'L13-08': ('plain', "order and doubt — spot before hair impure, hair first pure, doubt impure; the root-and-tip grid"),
 'LV13A-01': ('plain', "the state guard — no re-marking a decided state; mixed sentences lawful; seen all as one"),
 'LV13A-02': ('plain', "the geometry row — raw flesh unturned and turned, centered, the bean-square of thirty-six hairs; the Akavya dispute kept"),
 'LV13A-03': ('plain', "the king's decree at the limb tips, self-labeled; the grace-days deferral table; the twenty-four tips"),
 'LV13A-04': ('plain', "the posture protocol — hidden places by fixed postures; the dim-sighted priest barred; interiors out, between-digits in"),
 'LV13A-05': ('E1', "'all his flesh' — bloom purifies in all shades at every stage; blooming from the pure is impure; the pale rash never counts"),
 'LV13A-06': ('plain', "the loop rule — covered pure, uncovered impure, even a hundred times; returning flesh defiles, returning hair does not"),
})

DEC.update({
 # lev_14 — the house mark, the leper's cleansing
 'LV14B-01': ('plain', "the ownership gate — conquered, divided, and known, each token a condition; Jerusalem exempt; on the land only; the good-news reading"),
 'LV14B-02': ('plain', "the humility protocol — the owner himself, the two recorded causes, 'like a mark' even from the expert with the received translation keeping the particle, ink, beside; the dark house never inspected"),
 'LV14B-03': ('plain', "the evacuation — everything out, the earthenware sermon, immediate defilement inside, the grace days"),
 'LV14B-04': ('plain', "the geometry gate — two beans, four walls with round and triangular exempt, the corner spec, stones-wood-dust, the lintel station"),
 'LV14B-05': ('M-12', "'they shall take out' — both neighbors pull and carry, woe to the wicked's neighbor; the plaster his alone; other stones, other dust"),
 'LV14B-06': ('plain', "the ten houses — the complete decision tree numbered by the Sifra itself; return is two beans without spread; the corner-stone asymmetry"),
 'LV14B-07': ('plain', "the entry quantum — head and majority; the half-loaf interval, the Torah's one lenient wash; only the defilable save; the certification and the teacher's license"),
 'LV14A-01': ('plain', "one law, by day, by priest; no delay; Munbaz's regress stopped — 'you would add forever'; a leper purifies no leper"),
 'LV14A-02': ('plain', "the kit specs — equal live pure birds, the cedar billet, good scarlet untried, pure-name hyssop; seven laws off R. Tarfon's staff"),
 'LV14A-03': ('plain', "the coupled fates — the quarter-log visibility ratio, both-ways coupling, slaughtered not pinched, the field-ward release, the returned bird permitted"),
 'LV14A-04': ('M-09', "'his tent' is his wife — the keyword; bathing gates entry, the birds do not; an immersion pool suffices; the counting week's ban; the Jotham datum"),
 'LV14A-05': ('I3', "'his eyebrows' the exemplar — all visible hair by the eyebrow model; razor only, two hairs void it; shave, then sunset, then the offerings"),
 'LV14A-06': ('plain', "the thumbs rite — two priests, vessel and hand, the altar first, the middle ridge, the place causes not the blood; the missing-thumb dead-end with both arms; the advocate parable, E26, beside"),
 'LV14A-07': ('plain', "the poverty scale — both clauses, the guilt offering never scaled, status sampled at it; the wife's lien in the contract's own Aramaic"),
 'LV14A-08': ('ink', "the purity verb at 14:7, 8, 9, 20 as the three purities and the atonement gate; 'the right' at six verses; compiled cold against Negaim 14 whole, 77 of 77"),
 # lev_15 — the discharges
 'LV15B-01': ('plain', "the source and the table — the day-old menstruant, the ten-day discharger; the five bloods at their second seat; inside as outside; all seven"),
 'LV15B-02': ('plain', "the majority grid — designated both directions, the fraction table, the touch-and-carry splitter named"),
 'LV15B-03': ('plain', "the demotion operator stated by the verse — severe to light; his bed as his touch; the loaf case; count from the last lying"),
 'LV15B-04': ('M-05', "'many days' parsed to the minimum — two and three by the minimal-seizure rule; open not lock; the window built inclusion by inclusion, E1, beside; the twenty-five and hundred computations"),
 'LV15B-05': ('plain', "the watcher — day against day only; she defiles her partner, he not his, in clean language; impurity not days; her designation binds"),
 'LV15B-06': ('plain', "the presence clause — separation performed by the received translation, ink, beside; even impure, the Presence among them; the three tiers; the fence"),
 'LV15B-07': ('ink', "the ten-day-old discharger is seven plus three — Niddah 5:3's ten computed from 15:19 and 15:25's own numbers; the Sifra's twenty-five and hundred summed from the same clocks"),
 'LV15A-01': ('plain', "the seven ways — the member only, outside only; seven examination gates before the threshold, none after"),
 'LV15A-02': ('plain', "the clocks and the table — sightings not days, duration as count by the walking clock, the rope parable, E26, beside; white against blood; the nine liquids"),
 'LV15A-03': ('plain', "the stand-up test — designated only, the work test, only the living discharger makes beds, the scribal self-label, the despair criterion"),
 'LV15A-04': ('plain', "the propagation degrees — typed edges, the broken bed pure, the two-stage table, the pressure column through ten seats and the stone"),
 'LV15A-05': ('plain', "the inverted saddle — touch weak, carry strong; the designated rides; under the discharger; the carry list extended, E1, beside; hair and nail in, parted flesh out"),
 'LV15A-06': ('plain', "the hand-washing peg and the airspace-and-shaking earthenware rule; the shelf above, the bed below"),
 'LV15A-07': ('plain', "the count's jurisdiction — self-examination as R. Eliezer; interposition-free; living water written for him alone, E2, beside; instance-bound birds; three bring, two do not"),
 'LV15A-08': ('M-05', "the forty seah read out of 'all his flesh' — a cubit by a cubit by three; the urgency rule; the third-day dispute; semen voids one day; the king's-decree label"),
 'LV15A-09': ('ink', "Mishnah Kinnim whole as the combinatorics of 'one a sin offering and one a burnt offering' at its three seats plus one import; the chain of seven computed and matching"),
 # lev_16 — the Day of Atonement
 'LV16A-01': ('plain', "the graded ban — warning house-wide, death at the cover's face; Moses outside the ban; the warning-and-punishment time split; the open-teaches-the-closed meta-rule"),
 'LV16A-02': ('E10', "linen four times bars the four gold garments; five immersions, ten sanctifications; the five services in their garments; the first immersion in the common area"),
 'LV16A-03': ('plain', "the two-goats spec — public funds, equal required and unequal valid, mutually indispensable, the Nicanor positioning, the bull his own, atonement is words"),
 'LV16A-04': ('plain', "the lottery — any material, equal, one and one, raised from the box; 'for the Name' with the received translation writing exactly that, ink, beside"),
 'LV16A-05': ('plain', "linked failure — stand alive for death, the re-lottery with the second goat's two fates, alive till blood or confession, blood and goat restart together"),
 'LV16A-06': ('plain', "the Sadducee dispute — inside-only incense, the smoke-riser, the missing-spice death rule, the coal-pan quantities, the handful by his size"),
 'LV16A-07': ('plain', "the four-cell grid — the stirrer, the whip-stroke geometry, one-and-seven counting; 'as he did' closing the bull-and-goat table, M-10, beside"),
 'LV16A-08': ('plain', "the restart table and the Presence — sanctuary-defilement scope, three zones each an atonement, restart against resume, the Presence amid impurity"),
 'LV16B-01': ('I3', "'his two hands' here builds two-handed leaning for all leanings; the three confessions with the response; obligations survive the day; the designated dispatcher in the received translation's own word, ink, beside"),
 'LV16B-02': ('plain', "the dispatch geography — the uninhabited land, the era amplification, the three-way clothes window, the impurity-driven wash"),
 'LV16B-03': ('M-11', "the whole section in order except this verse — the written order as the service order with its one recorded exception; the linen stored away in the received translation's verb, ink, beside; the as-commanded frame"),
 'LV16B-04': ('I3', "the inner-blood building block — whose blood is brought in, its body burned; as commanded against not; the one-camp line; the carriers' boundary; the burner defined"),
 'LV16B-05': ('I2', "affliction defined by the shared word — eating and drinking by the hunger analogy with Deut 8:3, the excision-level kind; intent-work from the tabernacle; the rest-ordinance census"),
 'LV16B-06': ('plain', "the day atones without offerings; the fellow gate — appeasement first; the five afflictions; the day alone bears them"),
 'LV16B-07': ('plain', "succession and routing — the son if he fills the place; 'no end to the matter' again; once a year; the knowledge-state routing table"),
 # lev_17 — blood and the one center
 'LV17-01': ('plain', "outside slaughter — Israel liable, gentiles licensed; the geography carve; slaughter not pinching; the dispatched goat excluded, E2, beside"),
 'LV17-02': ('plain', "blood reckoned — no agency, one liable and two exempt, individual only; the Deuteronomy warning completing it, M-20, beside; the received translation's shed-blood verdict the ink leg"),
 'LV17-03': ('plain', "the platform table — eras, burnt and peace offerings only against vow-classes, no priest needed there, rock against built, no fragrance off the altar"),
 'LV17-04': ('plain', "the demons — the identification ruled by the received translation inside the verse, ink, beside; the amplification; the eternal statute without excision"),
 'LV17-05': ('plain', "the completion rule — only service-completing acts liable outside; the ten exempt acts; whole not part; fire-worthy only; the two-raiser disputes"),
 'LV17-06': ('plain', "the blood ban — the lifeblood dispute; 'I will set My face' read as I-turn-from-My-affairs, M-09, beside; one gift atones; warn the great, excision one's own"),
 'LV17-07': ('plain', "the covering machine — flesh by preparation, not with the foot, re-exposed exempt and wind-covered liable, the grows-plants predicate"),
 'LV17-08': ('plain', "the swallow-house — throat-only defilement, the beast carve; sufficiency's third exemplar, I1's own case law, beside; body-excision against garments-forty"),
 'LV17-09': ('ink', "Zevachim 13:7's four-way bird table from 17:3 and 17:8's two verbs with three Sifra rows; Chullin 6 graded on 17:13's three tokens; compiled cold, 241 of 241"),
 # lev_18 — the unions and the land
 'LV18-01': ('plain', "the register of laws — the four-union census as their engraved law; the theater layer; the received translation's Greek loanword naming the register, ink, beside"),
 'LV18-02': ('plain', "the canon channel — laws, expositions, Mishnah, deed each assigned to one of the verse's terms; reason-writable judgments against decreed statutes with both censuses"),
 'LV18-03': ('plain', "'live by them' — eternal life inside the received translation's verse, ink, beside; the private-transgress and public-sanctify threshold; the gentile-as-high-priest census"),
 'LV18-04': ('I4', "the general and the particular closing the class of unions — the Sifra names the structure; gentiles and the woman warned; unions underivable by inference; the court on charge"),
 'LV18-05': ('ink', "the received translation parses the sister clauses into the paternal and maternal cases; the keep-or-send carve from the Sifra beside"),
 'LV18-06': ('plain', "the levirate table — the upon-her bound; fifteen women to the end of the world; the six severer with permitted rivals"),
 'LV18-07': ('plain', "the land ledger — the opened account book, the vomit physics, exile as the land's liability; the reckoning verb in the received translation, ink, beside"),
 'LV18-08': ('ink', "the fifteen women as a kinship computation — Lev 18's relations composed with 'his paternal brother' and normalized by the verse's own identities; compiled cold, 241 of 241"),
 # lev_19 — holiness: the duty ledger, the neighbor, the mixtures and weights
 'LV19L-01': ('plain', "the buffer paid — the received translation of Lev 19 read whole closes the pending buffer; the Sifra's density note grades the thesis"),
 'LV19L-02': ('plain', "the great rule — R. Akiva's neighbor-love against ben Azzai's personhood baseline, a recorded dispute at the statute's card"),
 'LV19L-03': ('M-11', "the five verbs of 19:11-12 in their written order as the escalation; the warnings for Exod 22:3 and Lev 5:21-24, M-20, beside; the wage's two clocks at two seats; the judge is the measurer; compiled cold, 186 of 186"),
 'LV19L-04': ('M-23', "the second half's clauses at their second seats by live call — 19:15 and 19:35, 19:14 and 19:32, 19:18 and 19:34, 19:30 and 26:2 verbatim; the razor as two verses' intersection, I13, beside"),
 'LV19A-01': ('plain', "most Torah bodies — the assembly setting as density note; holy is separate, M-09, beside; the retinue imitates the King"),
 'LV19A-02': ('plain', "three partners — the three links and their reason; equal parents with reasoned precedence; fear and honor defined; the override clause"),
 'LV19A-03': ('plain', "intent at slaughter — the two-day condition binds at the act; the third-day clause freed to wrong-place, M-18, beside; the excision building block, I3"),
 'LV19A-04': ('plain', "the poor-gifts engine — the five predicates, the sixtieth, the dividers and line-of-sight, the four-position grid, doubt to the poor, the scramble protocol"),
 'LV19A-05': ('M-20', "this chapter arms Exodus 22 and Leviticus 5 with their warnings — the warning completion; benign theft banned; the five-verb cascade"),
 'LV19A-06': ('plain', "the wage clock — money-class oppression, the first morning, by-your-will, the shopkeeper carve, the day and night windows"),
 'LV19A-07': ('plain', "the living-only curse class; the corrupt-advice census on 'the blind' read as blind in the matter, M-09, beside; the heart clause naming the unenforceable layer"),
 'LV19A-08': ('plain', "the court file — five effects, equal treatment, procedure and secrecy, the pursuer list, revenge and grudge by exemplar, the great-rule dispute"),
 'LV19A-09': ('ink', "Mishnah Peah whole graded on 19:9-10's four gift-nouns, the leave-verb, the recipient pair, the four reaping-tokens; the corner's quantity a parameter; compiled cold first run"),
 'LV19B-01': ('plain', "the mixture bans — mixture-only breeding, maintaining counts, the three-predicate wool-and-linen, wear and cover banned, the fence labeled fence"),
 'LV19B-02': ('plain', "the maidservant — four readings; the document completes with the received translation writing it in, ink, beside; she lashed, he not; one offering, many acts"),
 'LV19B-03': ('plain', "the intent-defined tree — fence and timber plantings exempt, the total benefit ban, thirty days a year, the fourth year as tithe-holy"),
 'LV19B-04': ('M-12', "'praises' plural — a blessing before and after; taste nothing unblessed; the received translation's holy-of-praises, ink, beside"),
 'LV19B-05': ('plain', "five laws on one clause — the executed court's fast among them; the time-setters as soothsaying"),
 'LV19B-06': ('I13', "the razor as the intersection of 'destroy' here and 'shave' at Lev 21:5 — shaving with destruction; five corners; per gash and per dead; write and engrave both"),
 'LV19B-07': ('E28', "the sanctuary beside the Sabbath — the building never overrides it; awe of the Commander forever; the protocol; the land straying to its fruits"),
 'LV19B-08': ('E30', "the elder's word read as an acronym — this one has acquired wisdom, the received translation ruling it, ink, beside; reach and no cost; the reciprocal duty; the convert's gate"),
 'LV19B-09': ('plain', "measures are judgment — the measurer-judge with five effects; the inspector and cleaning table; the tilt and surcharges; the Exodus condition"),
 'LV19B-10': ('ink', "the mixture noun three times in 19:19, each with its own verb — Kilayim 8:1's taxonomy as the grid; the vineyard and the plowing pair routed to Deut 22:9-10; Kilayim whole, 77 rows"),
 'LV19B-11': ('ink', "the maidservant's hapax tokens — 'designated', 'not redeemed', 'inquest' once each, 'freed' twice; 'which he sinned' twice as the deliberate-as-erring, E10, beside; Keritot 2:4 as the Sifra's rows"),
 'LV19B-12': ('E10', "the uncircumcised root three times at 19:23 as the total-benefit ban; the per-tree timer on the Tishrei year; the intent defines the tree; the 201 ratio as data; 'praises' at Judg 9:27 alone, ink, beside"),
 # lev_20 — the sanctions
 'LV20-01': ('plain', "the Molech predicate — four conjoined conditions; the people assist a weak court; the register meta-rule — human tongue, all expoundable"),
 'LV20-02': ('plain', "the concealment ladder — one to many through the courts to the lost jurisdiction; the family as shielders, the received translation's supporters, ink, beside"),
 'LV20-03': ('plain', "the curse file — after-death liability; by the Name via Lev 24:16 on the shared word, I2, beside; the three-source argument with the freed-token close, M-18; the received translation's death-liable decoder, ink"),
 'LV20-04': ('plain', "the strangulation default — the unspecified death's three routes; the no-mark rationale; the procedure; the doubled clause kept, E10, beside"),
 'LV20-05': ('M-16', "the revocalization twice on the passive warnings; the freed beast clause reassigned, M-18, beside; the marriage-path rule; the received translation on R. Akiva's plural, ink"),
 'LV20-06': ('I1', "the beast as stumbling, the a-fortiori to the misleader; the peace stones; the shortener-lengthener rule"),
 'LV20-07': ('plain', "the fence complete — no punishing and no warning from inference; the disgrace and without-child rulings in the received translation, ink, beside; the levirate window's state simile"),
 'LV20-08': ('plain', "the hair's breadth — most against half the windpipe with its tolerance; I-can-but-Father-decreed; the Land's stomach; the death-liable close"),
 'LV20-09': ('ink', "Lev 20's sanction vocabulary censused, each union located by its kin token; 'their blood is upon them' decoded on 20:27's co-occurrence with named stoning, the equal decree, I2, beside; Sanhedrin 7:4, Makkot 3:1, Keritot 1:1 recomputed; compiled cold"),
 # lev_21 — the priest's blemish, the priest's family
 'LV21B-01': ('plain', "the age ladder — valid at two hairs, admitted at twenty; the service census; liable only for service; Aaron himself; the passing blemish; the received translation of 21:17 the ink leg"),
 'LV21B-02': ('I3', "blind, lame, sunken-nosed, dislocated — each named blemish a class head with its members generalized; the received translation of 21:18 the ink leg"),
 'LV21B-03': ('plain', "the fracture row — bent and twisted; joined fingers to the joint fit, below unfit"),
 'LV21B-04': ('plain', "the eye and skin row defined; the three-way testicle reading with the received translation ruling R. Yishmael's arm, ink, beside"),
 'LV21B-05': ('M-03', "the difference table — man and beast compared with opposite signs; the Kushite class; the three beast-unfits fit in man; the passed blemish fit"),
 'LV21B-06': ('plain', "the blemished eat — of the most holy and of the holy; even in division against the day-immersed; the received translation of 21:22 the ink leg"),
 'LV21B-07': ('plain', "the entry hierarchy — priests, Levites, Israelites, impure, blemished; served is invalid with the death-against-warning dispute; the warning graph; the received translation of 21:23 the ink leg"),
 'LV21B-08': ('ink', "the blemish census on twelve class heads in the ink's order; 'blemish' five times against three; the block written four times; the two lists share exactly three tokens and the transfer runs on two by name, I2, beside; Bekhorot 7 whole"),
 'LV21A-01': ('E2', "'the sons of Aaron' — sons not daughters; the profaned out; the blemished and minors in, E1, beside; blood and departing impurities; the abandoned-corpse override"),
 'LV21A-02': ('plain', "the relative table — the wife in 'his kin'; the betrothed and divorced out; the profaned line against presumption; viable children; the two duty sets; paternal siblings"),
 'LV21A-03': ('plain', "the sister's carve — the minor sister, the any-age brother, the agent-of-loss test; defilement for her a command enforced by force; certain not doubtful; no limbs"),
 'LV21A-04': ('plain', "the husband split — fit wife yes, unfit no; profane while occupied; the received translation's 'great one' against the Sifra's 'husband', a recorded keyword fork, M-09, ink"),
 'LV21A-05': ('plain', "mourning marks — per spot, per gash, whole head; the two-way transfer between priests and Israel on the shared word with Deut 14:1, I2, beside"),
 'LV21A-06': ('plain', "holy by compulsion — not the Levites; the blemished holy; the received translation's offering-for-bread, ink, beside"),
 'LV21A-07': ('plain', "the forbidden wives — the harlot three ways with the received translation on the Sages' arm, ink, beside; the profaned woman; the rival refutes; the husband's hand; the woman warned through the man"),
 'LV21A-08': ('plain', "sanctify him — by force; the court warned; the blemished holy"),
 'LV21A-09': ('plain', "the priest's daughter — by whoring with a husband's bond; all ages and husbands; she burns alone; the received translation's departure from the father's holiness, ink, beside"),
 'LV21A-10': ('plain', "greatness and one hour — five greatnesses, made great from theirs; the office at the pouring; rends below against above; the received translation of 21:10 the ink leg"),
 'LV21A-11': ('plain', "the mourner split — two corpses' blood, two prohibitions, hidden-and-revealed to the gate; valid for the high priest, invalid for the commoner"),
 'LV21A-12': ('plain', "the virgin command — not the king or the Nazirite; the war priest in; the adult disputed; betrothed-then-appointed marries; not a levirate widow"),
 'LV21A-13': ('plain', "the profaned seed — profaned not bastard; exported down the ranks; the menstruant fence; she herself profaned; the profaned man's daughter"),
 'LV21A-14': ('ink', "the six relatives on six tokens — the defile-verb at four seats, the six kin tokens with the wife in 'his kin', the take-verb doubled twice, E10, beside, the burn token's three seats; the razor and the burning by call; Yevamot 9:1-2 as a rank predicate"),
})

DEC.update({
 # lev_22 — the acceptable offering, the holy food
 'LV22B-01': ('E1', "'any man of the house of Israel or of the strangers' — gentiles vow; the class widened by 'all'; the Nazirite out, E2, beside; no public compulsion; beasts whole and male, birds by a lesser bar; the received translation of 22:18-19 the ink leg"),
 'LV22B-02': ('plain', "the five-count — consecrate, slaughter, throw, burn, part, receive; individual not public; the class sweep; fell and broke exempt; the blood-rush arms; the received translation of 22:21 the ink leg"),
 'LV22B-03': ('plain', "the beast's row — tail not rib, the cut, the two-way transfer with the priest's list on the shared tokens, I2, beside; slaughter banned; worked-with permitted; the received translation of 22:22 the ink leg"),
 'LV22B-04': ('plain', "the stretched and the contracted defined — the uncloven hoof; for upkeep not the altar; no whole animal for upkeep; the received translation's extra-and-lacking fork, ink, beside"),
 'LV22B-05': ('plain', "the castration ban — three anatomies; receive-blood the sixth; birds and abroad; humans by revocalization, M-16, beside; no shekels from gentiles; females disputed; the received translation of 22:24-25 the ink leg"),
 'LV22B-06': ('E2', "'an ox or sheep or goat when it is born' excludes the hybrid, the look-alike, the caesarean, the under-age, the orphan; the tithe transfer, I2, beside; one hour with the mother; the eighth-day join"),
 'LV22B-07': ('E2', "'an ox or a sheep' — not wild, not bird; the female alone, the received translation feminizing the verse, ink, beside; it and its mother; the order cases at forty and eighty"),
 'LV22B-08': ('plain', "the four periods — the slaughter carve, the seller informs, the compelled butcher and the buyer's loss; day-after-night by ben Zoma's 'one day' with Gen 1:5, I2, beside"),
 'LV22B-09': ('M-18', "the eating clause already known, freed and re-typed onto the slaughter — slaughter with intent to eat within the day; all one-day offerings; the received translation of 22:29 the ink leg"),
 'LV22B-10': ('M-09', "'keep' is Mishnah, 'do' is deed — the two verbs each assigned; hand yourself over among the many; no conditional miracles; the Exodus on condition; the received translation of 22:32 the ink leg"),
 'LV22B-11': ('ink', "the acceptance root at seven seats; the four tokens of 22:22 assigned; 'and from the day' a Tanakh hapax; 'on one day' the Torah's only seat; Bekhorot 6 whole on the Sifra's members; the female by the received translation's grammar"),
 'LV22A-01': ('plain', "separation — the received translation's separating verb, ink, beside; Israel's not gentiles'; one analogy carrying time, death, and acceptance, M-03; the addressees"),
 'LV22A-02': ('E1', "'the holy things' — all holy things included in the excision; the four-way difference; the readiness threshold; body-impurity by four routes; the received translation of 22:3 the ink leg"),
 'LV22A-03': ('plain', "the measures census — Aaron himself; the tithe as the day-immersed; sunset; contact; the Lev 5:3 measures fetched, M-10, beside; the swallower"),
 'LV22A-04': ('plain', "the mixture grid — one in a hundred both directions; whole-body immersion; sunset gates the priestly gift, atonement does not; the received translation of 22:7 the ink leg"),
 'LV22A-05': ('plain', "the gullet carve — the bird only; the court's charge; not the tithe; the eater's state; the received translation's receive-a-debt, ink, beside"),
 'LV22A-06': ('plain', "the stranger — every non-priest; the olive; the priestly gift; forever against years; the uncircumcised by two routes; the received translation of 22:10 the ink leg"),
 'LV22A-07': ('plain', "the household feeder — wife, slaves, slaves' slaves; the Hebrew and the half-slave out; the son feeds the mother; the dead feed none"),
 'LV22A-08': ('plain', "the daughter to a stranger — to one who feeds; she feeds her mother; the priestly gift and the holy things crossed; the received translation of 22:12 the ink leg"),
 'LV22A-09': ('plain', "the return — no seed to the seed's seed; the grandson high priest; unfit seed counts; not the levirate-bound, not the pregnant; the received translation of 22:13 the ink leg"),
 'LV22A-10': ('plain', "the fifth — non-strangers exempt; nine-and-a-day a man; it and its fifth are five, M-05, beside; payment material; kind for kind; giving sanctifies; the received translation of 22:14 the ink leg"),
 'LV22A-11': ('plain', "the profaners — the anointer and the drinker; raised not untithed; death even on the untithed; the sower and defiler out; the received translation's inserted 'in impurity', ink, beside"),
 'LV22A-12': ('ink', "eating fourteen times; the Name framing 22:2 and 22:32; sunset's one other Tanakh seat; 'its fifth' at two seats; the guilt token a homograph; Yevamot 7-9 whole on the feeder predicate by call"),
 # lev_23 — the festivals, fall and spring
 'LV23B-01': ('plain', "the four-token liturgy — rest, remembrances, horn blasts, the day, each token a liturgical job; kingships adjoined; the order dispute with Usha; the received translation's broken cry, ink, beside"),
 'LV23B-02': ('I2', "the shofar's instrument, plain blasts, three of three all carried from the Jubilee on the shared 'seventh month'"),
 'LV23B-03': ('plain', "the day atones without rites or offerings; only the penitent by the restrictive 'but', E2, beside; warning and punishment for work; the received translation of 23:27 the ink leg"),
 'LV23B-04': ('M-09', "excision is destruction — the verse's own 'I will destroy' as the effect's content; the five afflictions; not the weekly Sabbath; the received translation of 23:30 the ink leg"),
 'LV23B-05': ('plain', "the addition — profane to holy on every rest; no excision or warning on it; the fast's warning from a redundant punishment; the received translation of 23:32 the ink leg"),
 'LV23B-06': ('plain', "the first seven — the booth for the Feast of Booths only; the festival offering for God, the booth for man; sanctify with food, drink, clothing; the received translation of 23:34 the ink leg"),
 'LV23B-07': ('E2', "'it' bounds the work ban to the day itself — the intermediate days; the order rule with invalidity; the do-not-delay timer after three festivals in order; the received translation of 23:36 the ink leg"),
 'LV23B-08': ('plain', "the ingathering — intercalate for the ingathering of most fruits; make up all seven; the received translation of 23:39 the ink leg"),
 'LV23B-09': ('plain', "the four species — bound disputed; yours not stolen, the ship, E2, beside; the first day even on the Sabbath; the identifications and counts; whole taking; the received translation naming them, ink"),
 'LV23B-10': ('plain', "the festival offering — one day with a seven-day make-up, inside the season only; the received translation of 23:41 the ink leg"),
 'LV23B-11': ('M-09', "'dwell' as you live — the keyword; nights by the Lev 8 analogy on the shared 'seven days', I2, beside; women out, minors in; any material by the strict-to-lenient meta-rule; the received translation rules clouds, ink"),
 'LV23B-12': ('plain', "Moses taught — each festival's laws in its season; the season fixed for all public offerings; the received translation's 'order... and taught', ink, beside"),
 'LV23A-01': ('plain', "the court's utterance — proclaimed is a festival, unspoken is none; erring binds; the limits; for need not impurity; the received translation of 23:2 the ink leg"),
 'LV23A-02': ('E28', "the Sabbath written beside the festivals — cross-graded; the liability count disputed; the received translation of 23:3 the ink leg"),
 'LV23A-03': ('plain', "the month — unspoken before dark is full; perjured witnesses still sanctify; never for need; the Sabbath yields to testimony only; the received translation of 23:4 the ink leg"),
 'LV23A-04': ('plain', "the optional seven — six hours onward; this needs unleavened bread; all optional but the first night; edible all seven; the received translation of 23:5 the ink leg"),
 'LV23A-05': ('plain', "the fallback ladder — bulls, rams, lambs; purity to impurity; never lapse"),
 'LV23A-06': ('plain', "the sheaf's field — the particular land; first of reaping; not irrigated or valley; grain not legumes, E2, beside; not a priest's duty; the received translation of 23:10 the ink leg"),
 'LV23A-07': ('plain', "the morrow — four recorded routes to the festival reading; the waving-by-priest building block, I3, beside; the received translation's 'after the festival day', ink"),
 'LV23A-08': ('plain', "the sheaf's lamb independent of the sheaf; by day; two tenths of flour read as written with the libations un-doubled; the received translation of 23:13 the ink leg"),
 'LV23A-09': ('plain', "the new grain — five grains; the sheaf as the gate; immediately, midday, the whole day; three laws with three source labels; the received translation of 23:14 the ink leg"),
 'LV23A-10': ('plain', "the count — reap and count by night, bring by day; forty-nine then sanctify the fiftieth; barley by the freed clause, M-18, beside; the received translation of 23:15 the ink leg"),
 'LV23A-11': ('plain', "the two loaves — from the land; equal; leaven from itself against the measure; one offering across two chapters; the received translation of 23:17 the ink leg"),
 'LV23A-12': ('plain', "the two sets — for the day against for the bread; the waving geometry four ways; lambs without bread with the reason replaced; the received translation of 23:18-20 the ink leg"),
 'LV23A-13': ('E28', "the corner and the gleanings placed among the festivals — the poor-gifts as an offering's equivalent by position; the received translation of 23:22 the ink leg"),
 'LV23A-14': ('ink', "23:18-19's animals compiled by their numerals; 23:20's 'holy to the LORD, for the priest' is Zevachim 5:5's communal row on the verse's own words; the loaves above the lambs; the mutual blocks"),
 # lev_24 — the blasphemer and talion, the lamp and the bread
 'LV24B-01': ('plain', "the origin — out of Moses' court on the camp rule; the explicit Name; not killed on a substitute; the received translation's 'explicitly uttered', ink, beside"),
 'LV24B-02': ('plain', "the court procedure — the substitute in examination, the explicit Name at verdict, the judges rend; two custody cases with two open variables; the received translation of 24:12 the ink leg"),
 'LV24B-03': ('plain', "the stoning protocol — court in, stoning out; witnesses and judges lean; your blood on your head; not his clothing; for generations; the received translation of 24:14 the ink leg"),
 'LV24B-04': ('plain', "the predicate — gentiles by the sword on 'any man', E1, beside; substitutes disputed; bear-sin is excision on the shared phrase, I2; all as litigants; the parent-curser needs the Name; the received translation of 24:15-16 the ink leg"),
 'LV24B-05': ('plain', "the striker — the woman striker, the minor victim, no stillborns; the whole soul; the first blow counts; the beast paid; the received translation of 24:18 the ink leg"),
 'LV24B-06': ('I2', "talion as payment on the shared strike-verb with the beast-striker; Num 35:31's ransom for the murderer alone, E2, beside; the shame class; the hand boundary; the received translation's exchange preposition, ink"),
 'LV24B-07': ('plain', "one judgment — the parent-striker's three parameters; inquiry without the bench of twenty-three; the execution protocol by the as-commanded frame; the received translation of 24:22 the ink leg"),
 'LV24A-01': ('plain', "three olives — nine flows totally ordered; the first for the lampstand; beaten required for the light only; the received translation of 24:2 the ink leg"),
 'LV24A-02': ('plain', "the western lamp — begin and end at it; relit from the outer altar; nearer the veil; one priest; evening to morning exclusive; the received translation of 24:3-4 the ink leg"),
 'LV24A-03': ('plain', "the twelve loaves — wheat bought; equal; one by one; two at a time; three molds; two rows of six by three constraints; the received translation of 24:5 the ink leg"),
 'LV24A-04': ('plain', "the props and frankincense — four props, twenty-eight reeds; both rows; the frankincense as the indispensable permitter in two dishes; two handfuls; the received translation of 24:7 the ink leg"),
 'LV24A-05': ('plain', "the Sabbath exchange — new in, old burned; reeds off on Friday; everything lengthwise but the ark; three and two; the received translation of 24:8 the ink leg"),
 'LV24A-06': ('plain', "the eating — the holy place for eating, kneading, shaping; one broken, all void; Aaron without division; after the fire's gift; the received translation of 24:9 the ink leg"),
 'LV24A-07': ('M-23', "the lamp as Exodus restated with one token dropped — 24:2 is Exod 27:20's thirteen-token tail, 24:3 drops 'and his sons' for one priest; pure four times, continually four times, ink, beside; the doubled Sabbath as the weekly timer, E10; Menachot 11 whole as Chapter 18"),
 # lev_25 — the redeemed poor, the sabbatical and jubilee, the slave and the jubilee
 'LV25B-01': ('M-09', "the perpetuity word glossed as irrevocably by the Sifra and the received translation alike, ink, beside; the strangers clause"),
 'LV25B-02': ('E1', "'in all the land of your possession' includes houses and the Hebrew slave; not slaves, documents, movables, E2, beside; the received translation of 25:24 the ink leg"),
 'LV25B-03': ('plain', "the sale gate — only the impoverished sell, never all; the nearest redeems first; gifts included; the received translation of 25:25 the ink leg"),
 'LV25B-04': ('plain', "four constraints — own means; not far for near, bad for good, borrowed, or by halves; the received translation of 25:26 the ink leg"),
 'LV25B-05': ('plain', "the reckoning — counterpart by favorable price; the lesser figure whether improved or fallen; the received translation of 25:27 the ink leg"),
 'LV25B-06': ('plain', "the inversion — the redeemer by the owner's order; the sanctuary's four constraints inverted, the comparison, M-03, beside; the Jubilee at its start, the seventh at its end; the received translation of 25:28 the ink leg"),
 'LV25B-07': ('plain', "the roster — walled since Joshua, a gazetteer as input; at once; the year from the first sale; the received translation of 25:29 the ink leg"),
 'LV25B-08': ('plain', "the full year — 365 or twelve months; the house-scope and wall disputes; Hillel's repair of the hiding exploit; the sanctuary has no generations; the received translation of 25:30 the ink leg"),
 'LV25B-09': ('plain', "the village — two courtyards of two; the field's Jubilee and deduction with the house's at-once; the received translation of 25:31 the ink leg"),
 'LV25B-10': ('plain', "the Levites — perpetual redemption against the floor, the year-limit, and the forfeit; the received translation of 25:32 the ink leg"),
 'LV25B-11': ('plain', "Levite from Levite — the disqualified sons out; sale not consecration; the heir cases; the received translation of 25:33 the ink leg"),
 'LV25B-12': ('plain', "zoning — three bands fixed for the Levites; one-way upward for Israel; the treasurer's sale barred; the received translation of 25:34 the ink leg"),
 'LV25B-13': ('E26', "the falling load — support before the fall, again and again, the parable of the load; your life first; the received translation of 25:35 the ink leg"),
 'LV25B-14': ('plain', "interest — two terms by two worked cases; the guarantor allowed; the one flask; the Exodus condition; the received translation of 25:36-37 the ink leg"),
 'LV25B-15': ('plain', "the land clause — dwelling as acceptance of kingship; the received translation of 25:38 the ink leg"),
 'LV25A-01': ('I3', "the Sinai-detail rule — the sabbatical year's generalities and details from Sinai generalized to every commandment, read off one place-name; the received translation of 25:1 the ink leg"),
 'LV25A-02': ('plain', "the onset — recognition of one's plot triggers the duty; the dated schedule from the crossing to year sixty-four; the received translation's release before the LORD, ink, beside"),
 'LV25A-03': ('E10', "the doubled six-years — rooted before the New Year gathered in the seventh; the one-third threshold; the pairing arithmetic; the received translation of 25:3 the ink leg"),
 'LV25A-04': ('I8', "pruning and reaping singled out from every field and vineyard labor — went-out-to-teach, the class rule named; the Jubilee outside the cycle; the thirty-day addition and the fruit lag; the received translation of 25:4 the ink leg"),
 'LV25A-05': ('plain', "the changed manner — guarded no, ownerless yes; consumption in a changed manner; the land's clock and the fruit's clock; the received translation's left-alone vine, ink, beside"),
 'LV25A-06': ('plain', "the eaters — resting not guarded; the improved-field dispute with reversed attributions; the rich eat; the post-removal class disputed; the received translation of 25:6 the ink leg"),
 'LV25A-07': ('plain', "the field-clock — the house follows the field; the export border; the season table with the tithe-season import; the quantities as data; the received translation of 25:7 the ink leg"),
 'LV25A-08': ('plain', "the count — the court counts; the two-verse pin; the seventh-Jubilee dependency disputed; the received translation counts releases, ink, beside"),
 'LV25A-09': ('I2', "the shofar exported to the New Year on the shared 'seventh month' with its three-part structure; every individual; the Sabbath override everywhere at the Jubilee, court-only at the New Year; the received translation of 25:9 the ink leg"),
 'LV25A-10': ('plain', "the Jubilee's gates — the release at the Day of Atonement inside a year sanctified from the New Year; ceased with the exile of two and a half tribes, 'to all its inhabitants', E2, beside; validity keyed to sending or blast; the received translation of 25:10 the ink leg"),
 'LV25A-11': ('plain', "the timer's end — holiness to the year's end only; the seventh's labor ban imported whole; the received translation of 25:11 the ink leg"),
 'LV25A-12': ('plain', "the substitution chain — holiness seizes the last payment while the fruit stays bound; the jar dispute with Rabban Gamliel's ruling; the received translation of 25:12 the ink leg"),
 'LV25A-13': ('plain', "the two releases — money to the seventh, slaves to the Jubilee, both cross-inferences refused; the son's redemption returns to the father; the received translation of 25:13 the ink leg"),
 'LV25A-14': ('E2', "'from your neighbor's hand' — four exclusions: land, slaves, documents, the consecrated; monetary here, verbal at 25:17, M-23, beside; the sixth with R. Tarfon's third; the upper hand; coin thresholds; the received translation of 25:14 the ink leg"),
 'LV25A-15': ('M-12', "'years of crops' — the plural's minimum, not less than two produce years; blight and the seventh do not count; three harvests in two years; the received translation of 25:15 the ink leg"),
 'LV25A-16': ('plain', "the heart clause — verbal wronging's cases; the fear clause marks unobservable intent; the received translation of 25:17 the ink leg"),
 'LV25A-17': ('plain', "the aftergrowth ban — Torah by R. Akiva or scribal by the Sages, the provenance fork recorded; the received translation of 25:20 the ink leg"),
 'LV25A-18': ('E10', "the year ladder — three years in two readings; eighth to eleventh counted from the doubled tokens; the received translation of 25:21-22 the ink leg"),
 'LV25A-19': ('plain', "the layer label on the labor census — the derivative labors rabbinic with the verse a support, the four written verbs the Torah's; plowing's lashes disputed on R. Avin's meta-rule; the pre-year addition in three layers (Moed Katan)"),
 'LV25A-20': ('plain', "seventeen Jubilees and the destruction's cycle-year — the cycle run against the chronology, the count begun fourteen years in, both houses' destruction years placed under both recorded cycle models (Arakhin)"),
 'LV25C-01': ('plain', "the self-sale gate — only the impoverished; only to you; brother to him, servant to himself; the slave's work keyed to status; the received translation of 25:39 the ink leg"),
 'LV25C-02': ('plain', "the hireling table — same-day pay; equal fare; craft kept; the household fed on the master's knowledge; the received translation of 25:40 the ink leg"),
 'LV25C-03': ('plain', "the return — not to the former office; the refuge-city exile released by the same return-verb, I2, beside; the received translation of 25:41 the ink leg"),
 'LV25C-04': ('plain', "My deed first — prior title bars the slave market; the received translation of 25:42 the ink leg"),
 'LV25C-05': ('plain', "rigor — needless commands are rigor, judged by the heart clause; the received translation's one word for rigor and hostility, ink, beside"),
 'LV25C-06': ('plain', "the gentile slave — not the land's Canaanites; no betrothal by likeness to the maidservant; the received translation of 25:44 the ink leg"),
 'LV25C-07': ('I2', "acquisition by money, deed, possession carried from land on the shared 'possession'; the received translation's uncircumcised residents, ink, beside"),
 'LV25C-08': ('plain', "inheritance — sons, presumption; no overreaching; work only; both sexes; rigor by status; the received translation of 25:46 the ink leg"),
 'LV25C-09': ('plain', "sold to a gentile — the four buyers down to the idol; only after the sale; at once; paternal first; the received translation of 25:47 the ink leg"),
 'LV25C-10': ('plain', "the ladder read off the verse's own list — uncle, cousin, nearest, self; the tripled redeem-verb generalizes to anyone, E10, beside; the received translation of 25:48-49 the ink leg"),
 'LV25C-11': ('plain', "the reckoning — with the buyer alone; no six-year exit; money only; the received translation of 25:50 the ink leg"),
 'LV25C-12': ('I2', "the deduction's upper hand transferred by the named verbal analogy; the lesser figure either way; the received translation of 25:51-52 the ink leg"),
 'LV25C-13': ('plain', "the sight bound — equal fare under a gentile; the duty ends at what you can see; the received translation of 25:53 the ink leg"),
 'LV25C-14': ('plain', "'by these' — two arms crossed; robbing a gentile is robbery with the ladder; the received translation of 25:54 the ink leg"),
 'LV25C-15': ('plain', "servants to Me — the enslaving below charged above; the received translation of 25:55 the ink leg"),
 # lev_26 — the blessing and the curse
 'LV26-01': ('plain', "the idols ban — image and pillar paired; the road-heaps; bowing on stone barred in the land and permitted in the sanctuary, E2, beside; the received translation of 26:1 the ink leg"),
 'LV26-02': ('I12', "the closing verses read in their context — addressed to the slave of a gentile: the master's ways are no license; the received translation of 26:2 the ink leg"),
 'LV26-03': ('M-09', "'walk in My statutes' is toil in study — the keyword; 'remember' is the mouth across four seats, ink, beside; learn to do; the received translation of 26:3 the ink leg"),
 'LV26-04': ('plain', "the rains — the night schedule with two recorded runs; the blessing scoped to the land; the received translation of 26:4 the ink leg"),
 'LV26-05': ('plain', "the seasons chained without gap; security only in the land; the received translation of 26:5 the ink leg"),
 'LV26-06': ('plain', "peace weighed against all; the beast ceases by R. Shimon and the received translation, ink, beside; no armies in transit"),
 'LV26-07': ('ink', "five-to-a-hundred against a-hundred-to-a-myriad — superlinear by the verse's own arithmetic; the received translation of 26:8 beside"),
 'LV26-08': ('E26', "the long laborer's reckoning — the parable of turning; the covenant not the broken first one; the received translation writes 'to do you good', ink, beside"),
 'LV26-09': ('plain', "old of old — aging as improvement; the clearing anxiety; the received translation of 26:10 the ink leg"),
 'LV26-10': ('plain', "the dwelling — the Temple; no second rejection; the received translation's Presence for the walking, ink, beside"),
 'LV26-11': ('plain', "slaves to kings — not slaves' slaves; the upright measure disputed; the received translation's freedom, ink, beside"),
 'LV26-12': ('plain', "the condition — contempt for the oral layer; the knowing rebel by the preposition; the received translation of 26:14 the ink leg"),
 'LV26-13': ('M-11', "seven states in clause order, each entailing the next — the descent read off the verse's sequence; the received translation of 26:15 the ink leg"),
 'LV26-14': ('plain', "the creditor — anger; the Name as creditor; four worsening states; the two-year sowing; the received translation of 26:16 the ink leg"),
 'LV26-15': ('E27', "one verb in good and in evil — the mirror of 26:9 at 26:17; rulers from among you; the received translation's anger for the face, ink, beside"),
 'LV26-16': ('plain', "sevenfold — warning precedes; seven for seven; the pride of strength's three referents; the received translation of 26:18 the ink leg"),
 'LV26-17': ('M-23', "iron sky against brass sky, the two seats' metals reversed and ordered by sweat; the received translation writes the withheld rain and fruit into the verse, ink, beside"),
 'LV26-18': ('M-09', "casual for casual — the keyword's sense read; the beasts that bite and kill; the received translation's one word with rigor, ink, beside"),
 'LV26-19': ('plain', "the sword — two vengeances; the overnight-corpse law as mechanism; the staff of bread; the received translation expands the vengeance, ink, beside"),
 'LV26-20': ('E10', "synagogues by the doubled token 'your sanctuaries'; good and harsh measures paired; the received translation's congregation's offering, ink, beside"),
 'LV26-21': ('plain', "the Sabbath-debt — missed releases accrue as the land's debt, collected in exile; the received translation names them releases, ink, beside"),
 'LV26-22': ('M-09', "faintness — the word defined; the leaf memory recorded as the verse's fulfillment; the received translation of 26:36 the ink leg"),
 'LV26-23': ('M-09', "'in his brother' — stumbling in a brother's sin, mutual liability from the preposition; the received translation of 26:37 the ink leg"),
 'LV26-24': ('E10', "exile by the doublet — perishing among the nations read as exile, not death; R. Akiva's ten tribes; the received translation of 26:38 the ink leg"),
 'LV26-25': ('plain', "the fathers' sins — judged by them only when held; the received translation writes 'which they hold' into the verse, ink, beside"),
 'LV26-26': ('plain', "confession — mercy at confession and at humbling; the good measure of the enemies' land; the received translation's foolish heart, ink, beside"),
 'LV26-27': ('M-11', "the fathers in reversed order — the fallback chain read off the sequence Jacob, Isaac, Abraham; the remember-token's presence reasoned; the matriarchs by the particle, E1, beside; the received translation of 26:42 the ink leg"),
 'LV26-28': ('plain', "the four eras — one in a hundred; four clauses assigned to four eras; the tribes' covenant; the received translation's curses for blessings, ink, beside"),
 'LV26-29': ('M-12', "'the laws' plural — written and oral, two Torahs; laws, details, explanations from Sinai; the received translation keeps the plural, ink, beside"),
 'LV26-30': ('M-22', "the Sabbath-debt clause quoted by the Writings' log at its discharge, 2 Chronicles 36:21 the run of Lev 26:34; the seventy-year timer run three times from three recorded epochs with two logged failures; Rava's reconciliation (Megillah)"),
 # lev_27 — vows and valuations
 'LV27-01': ('plain', "the split — who values and who is valued, two arms with the widths swapped; the articulate minor; do-not-delay imported; the received translation of 27:2 the ink leg"),
 'LV27-02': ('plain', "standing — what can stand is valued; worth and valuation classes cross; boundary years count below, a month and a day past; the received translation's coin, ink, beside"),
 'LV27-03': ('plain', "four clocks — means by the vower, years and valuation by the valued, at the valuation's time; the received translation names the vower, ink, beside"),
 'LV27-04': ('plain', "limbs — a leg's holiness disputed; only individuals substitute; the tithe went out to teach, I8, beside; the received translation of 27:9 the ink leg"),
 'LV27-05': ('plain', "substitution — not transitive; woman and heir; one for a hundred; kind bounds; the owner's house overruling the argument; holy even blemished, even in error; the received translation of 27:10 the ink leg"),
 'LV27-06': ('plain', "disqualified — blemished consecrated beasts redeemed; the dead by hour-equality; birds, wood, frankincense, vessels not, E2, beside; the received translation of 27:11 the ink leg"),
 'LV27-07': ('plain', "the ladder — no estimate; each retracting bidder liable down to the next standing bid; the received translation of 27:12 the ink leg"),
 'LV27-08': ('plain', "the fifth — the owner adds, others do not; woman and heir count as owners; the received translation of 27:13 the ink leg"),
 'LV27-09': ('plain', "upkeep — the default destination; the owner's precedence with the fifth's ceiling; title on payment; the received translation of 27:14-15 the ink leg"),
 'LV27-10': ('plain', "the decree — fifty per homer of seed regardless of quality, self-labeled a king's decree; the received translation converts homer to kor, ink, beside"),
 'LV27-11': ('M-05', "forty-nine — the per-year rate derived from the verse's fifty over the Jubilee's years; crevices and rocks excluded; the Jubilee year itself; the received translation of 27:17 the ink leg"),
 'LV27-12': ('plain', "the floors — two before, one after; months the sanctuary's option; lump sum; the deduction runs against the sanctuary too; the received translation of 27:18 the ink leg"),
 'LV27-13': ('plain', "redeem — any field size; title on payment; the received translation of 27:19 the ink leg"),
 'LV27-14': ('plain', "son in — the son inherits the father's standing, the brother does not; a purchase from the treasurer stands; the received translation of 27:20 the ink leg"),
 'LV27-15': ('plain', "the abandoned field — three arms on the priests' entry; the redeeming priest holds nothing alone; the received translation of 27:21 the ink leg"),
 'LV27-16': ('plain', "the purchased field — holding by the father's death; worth against the decree rate disputed; paid that day; the received translation of 27:22-23 the ink leg"),
 'LV27-17': ('plain', "the coin — returns to the seller; never under a sela; twenty gerah; the received translation's twenty ma'in at its source, ink, beside"),
 'LV27-18': ('plain', "the firstborn — consecrated from the womb only; value-consecration yes, altar no; holiness not re-assigned; the substitute not offered; the received translation of 27:26 the ink leg"),
 'LV27-19': ('plain', "assessed — any movable, priced in money; it and its fifth are five, M-05, beside; the received translation of 27:27 the ink leg"),
 'LV27-20': ('plain', "devotion — never all; Canaanite slaves; unspecified to upkeep, disputed; priests and Levites split by land and movables; the received translation of 27:28 the ink leg"),
 'LV27-21': ('plain', "the condemned — no valuation after sentence; valued not vowed against full capacity; the received translation of 27:29 the ink leg"),
 'LV27-22': ('E2', "'of the seed' — the partitive restricts the tithe to edible seeds and fruits; redemption's persons and exclusions; five; the received translation of 27:30-31 the ink leg"),
 'LV27-23': ('plain', "the error rule — kinds; two tithes a year; the torn cannot pass; misnamed neighbors sanctified, the twelfth not; the received translation of 27:32 the ink leg"),
 'LV27-24': ('plain', "lashes — no picking; lashes for substituting; the firstborn sold, the tithe neither; a standing command; the received translation of 27:33 the ink leg"),
 'LV27-25': ('plain', "the close — the canon shut against prophetic innovation; all from Sinai; the received translation of 27:34 the ink leg"),
})

RUN = re.compile(r'cold_run_\w+\.py')

def label(code, note=None):
    return '%s (%s)' % (code, note) if note else TEXT[code]

EXCEPTIONS = {}
for k, v in DEC.items():
    EXCEPTIONS[k] = label(*v) if isinstance(v, tuple) else label(v)

RELABEL = {}
DEFER = set()

def DEFAULT(uid, c):
    m = RUN.search(c.get('claim_en', ''))
    if m:  # a compiled-run row not decided by hand: the runner's name read from the claim by script (B1's convention)
        return "ink (the compiled run — %s; the answer sheet's rows as test data)" % m.group(0)
    return None
