# THE NUMBERS WALK 10b — THE EXAM DOCKET, part H: the TOPIC rows Shevuot 21a:9 through 23b:7 (the oath of utterance's own machine: the lashes
# for the past oath, any amount against the olive-bulk, konamot's measure, dirt, drinking inside eating, the breads and the liquids specified —
# the Leviticus 5 runner's shelf; the vows' cells touched only where the konam and the oath are set side by side).
ROWS = [
 ('Shevuot 21a:9', 'CONTEXT', "R. Abbahu: which false oath is flogged? 'I will not eat' and ate — an act; 'I will eat' and did not — no lashes (R. Yochanan and Reish Lakish) — the oath engine's lashes (V5 by reference)."),
 ('Shevuot 21a:10', 'CONTEXT', "the two reasons: no act (R. Yochanan); an uncertain forewarning (Reish Lakish) — the sanctions engine's forewarning by reference."),
 ('Shevuot 21a:11', 'CONTEXT', "R. Abbahu: the flogged false oath is the PAST one ('I ate / did not eat'); Rava: the Torah extended lashes to the false oath LIKE the vain — past — the oath engine."),
 ('Shevuot 21a:12', 'CONTEXT', "R. Yirmeya from 27b's mishna (the thrice-sworn loaf: liable once — the utterance oath, lashes wanton, the sliding scale unwitting) — V5's sliding scale by reference."),
 ('Shevuot 21a:13', 'CONTEXT', "'this is the utterance oath' excludes what? the past oath from lashes? —"),
 ('Shevuot 21a:14', 'CONTEXT', "— no: from the OFFERING (R. Yishmael: an offering for the future only, lashes for the past too) — V5's R. Yishmael arm by reference."),
 ('Shevuot 21b:1', 'CONTEXT', "the vain oath's clause (29a: 'a stone column is gold') excludes what? the past oath from lashes? —"),
 ('Shevuot 21b:2', 'CONTEXT', "— no: the vain oath unwitting is exempt from an offering, the past oath brings one — R. Akiva — V5's R. Akiva arm."),
 ('Shevuot 21b:3', 'CONTEXT', "the whole mishna R. Akiva's; the first clause excludes 'I will eat' and did not — from lashes, not from the offering."),
 ('Shevuot 21b:4', 'CONTEXT', "why preferred? a future-oath clause excludes a future oath — the mishna R. Akiva's throughout."),
 ('Shevuot 21b:5', 'CONTEXT', "R. Akiva's 'any amount' — does he hold with R. Shimon everywhere (any amount flogged; the olive-bulk for offerings)? — the measures."),
 ('Shevuot 21b:6', 'CONTEXT', "if so the Mishnah should teach the general dispute; taught here for the Rabbis' reach — the measures."),
 ('Shevuot 21b:7', 'CONTEXT', "or R. Akiva holds the olive-bulk generally and any amount here because a specified any-amount binds — the measures."),
 ('Shevuot 21b:8', 'CONTEXT', "the Rabbis' question to R. Akiva — he could have answered 'R. Shimon everywhere' —"),
 ('Shevuot 21b:9', 'CONTEXT', "— or he answered on their premise; they refused — the measures."),
 ('Shevuot 21b:10', 'CONTEXT', "CREDITED-class: Mishnah Nazir 34b (the bread soaked in wine combining to an olive-bulk, R. Akiva) — so not any amount generally — NS by reference."),
 ('Shevuot 21b:11', 'CONTEXT', "22b's mishna (the oath not to eat, ate carrion: liable; R. Shimon exempt) — 'sworn from Sinai' — Rav, Shmuel, R. Yochanan: the oath included permitted things — the oath on the forbidden (the oath engine)."),
 ('Shevuot 21b:12', 'CONTEXT', "Reish Lakish: liable only with a specified half-measure by the Rabbis, or unspecified by R. Akiva — the measures."),
 ('Shevuot 21b:13', 'CONTEXT', "so R. Akiva holds the olive-bulk generally, any amount for the unspecified oath — concluded — the measures."),
 ('Shevuot 21b:14', 'CONTEXT', "'where is any amount liable?' — the ant: a whole entity is significant — the measures."),
 ('Shevuot 21b:15', 'CONTEXT', "consecrated food less than an olive — a peruta's worth is its measure — the misuse engine by reference."),
 ('Shevuot 21b:16', 'CONTEXT', "the specified any-amount = a whole entity — the measures."),
 ('Shevuot 21b:17', 'CONTEXT', "Rava's dirt dilemma unresolved by the Rabbis' rule? —"),
 ('Shevuot 22a:1', 'CONTEXT', "— the rule spoke of edibles; dirt apart — the measures."),
 ('Shevuot 22a:2', 'LAW', "KONAMOT — liable for ANY AMOUNT: a konam is as a specified any-amount — F1 vow_support (the vow's measure differs from the oath's: the vow forbids the OBJECT, so any amount; DATA konam_measure)."),
 ('Shevuot 22a:3', 'CONTEXT', "R. Akiva's 'who speaks and brings an offering?' — the blasphemer (speaks and sins, no offering) — the capital engine by reference."),
 ('Shevuot 22a:4', 'CONTEXT', "the nazirite forbids wine by speech and brings an offering — at the term's end, to permit wine — NS by reference."),
 ('Shevuot 22a:5', 'CONTEXT', "consecration by speech with a misuse offering — a prohibition for the whole world, not for himself — the misuse engine."),
 ('Shevuot 22a:6', 'LAW', "konamot: R. Akiva — NO MISUSE OF CONSECRATED PROPERTY applies to a konam — F1 vow_support (the konam is not a consecration: DATA konam_meilah — R. Akiva's arm)."),
 ('Shevuot 22a:7', 'CONTEXT', "Rava: the dispute is the unspecified oath; specified any-amount — all agree — the measures."),
 ('Shevuot 22a:8', 'CONTEXT', "Rava: 'I will not TASTE' — any amount by all — the measures."),
 ('Shevuot 22a:9', 'LAW', "Rav Pappa: the dispute is oaths; KONAMOT — all agree any amount (no 'eating' named, the item itself forbidden 'like an offering') — F1 vow_support (the konam's measure: the object, not the act — the vow-oath difference of Nedarim 13b:4 at its measure seat)."),
 ('Shevuot 22a:10', 'DISPUTE', "the baraita: two konamot COMBINE to a measure, two oaths do not; R. Meir: konamot as oaths — if any amount, why combine? — DATA konam_measure."),
 ('Shevuot 22a:11', 'DERIVATION', "they combine where he said 'EATING from this is konam, eating from that' (eating named — the olive-bulk); one measure when 'eating from both' — the vow's wording sets its measure — F1."),
 ('Shevuot 22a:12', 'DERIVATION', "why do oaths not combine? Rav Pinchas: two items under one oath are distinct for sin offerings — the oath engine."),
 ('Shevuot 22a:13', 'DERIVATION', "R. Meir's clause reversed: oaths as konamot — neither combines; he rejects Rav Pinchas — the measures."),
 ('Shevuot 22a:14', 'DERIVATION', "Ravina: any amount for LASHES; combining for the MISUSE offering (a peruta's benefit) — DATA konam_meilah's other arm."),
 ('Shevuot 22a:15', 'DISPUTE', "the baraita: 'this loaf is consecrated' — he and another liable for misuse, redeemable; 'this loaf is konam to me' — he liable, another not, not redeemable — R. Meir —"),
 ('Shevuot 22b:1', 'DISPUTE', "— the Rabbis: neither liable, no misuse in konamot — DATA konam_meilah (the two arms)."),
 ('Shevuot 22b:2', 'DERIVATION', "reverse the attributions: R. Meir — no misuse; the Rabbis — he is liable, another not — DATA konam_meilah."),
 ('Shevuot 22b:3', 'DERIVATION', "then R. Meir's 'konamot as oaths do not combine' implies misuse applies? —"),
 ('Shevuot 22b:4', 'DERIVATION', "— said on the Rabbis' premise ('by me no misuse at all; by you at least they do not combine')."),
 ('Shevuot 22b:5', 'DERIVATION', "the Rabbis: oaths do not combine by Rav Pinchas; konamot do — the measures."),
 ('Shevuot 22b:6', 'CONTEXT', "Rava: 'I will not eat' and ate DIRT — exempt (not eating); 'I will not eat dirt' — how much? TEIKU — the oath engine's open."),
 ('Shevuot 22b:7', 'CONTEXT', "'I will not eat a grape seed' — an olive-bulk or any amount? TEIKU."),
 ('Shevuot 22b:8', 'CONTEXT', "CREDITED (the Naso docket) — Rav Ashi: the NAZIRITE who swore off a grape seed (already forbidden by 6:4) — any amount or the olive-bulk? — NS by reference."),
 ('Shevuot 22b:9', 'CONTEXT', "from 22b's mishna (carrion under oath) — the oath including permitted things —"),
 ('Shevuot 22b:10', 'CONTEXT', "Reish Lakish's two ways — the measures."),
 ('Shevuot 22b:11', 'CONTEXT', "the carrion is 'sworn from Sinai' like the nazirite's seed — so the nazirite's oath: an olive-bulk — resolved."),
 ('Shevuot 22b:12', 'CONTEXT', "then resolve Rava's dirt too? —"),
 ('Shevuot 22b:13', 'CONTEXT', "— no: dirt is inedible; carrion edible but 'a lion crouches on it' — the oath engine's image."),
 ('Shevuot 22b:14', 'CONTEXT', "MISHNA 3:1 — 'I will not eat' and ate and drank: one; 'not eat and not drink': two; the three breads: one; 'wheat, barley, spelt bread': each; the liquids likewise — V5's oath table by reference."),
 ('Shevuot 22b:15', 'LAW', "3:1's close: inedible food — exempt; carrion under oath — liable (R. Shimon exempt: sworn from Sinai); 'KONAM my wife's benefit if I ate today' and he ate carrion — HIS WIFE IS FORBIDDEN — F1 vow_vs_oath (the vow's condition reads 'eating' plainly where the oath cannot take effect on the forbidden: the vow's and the oath's scopes differ on one page)."),
 ('Shevuot 22b:16', 'CONTEXT', "Shmuel: 'I will not eat' and drank — liable: by reason or by verse —"),
 ('Shevuot 22b:17', 'CONTEXT', "the reason ('let us taste something' — they eat and drink); the verse Deut 14:23 'you shall EAT … your tirosh' (wine) — drinking inside eating — the tithe engine by reference."),
 ('Shevuot 23a:1', 'CONTEXT', "tirosh is wine, 'and you shall eat' — drinking is eating."),
 ('Shevuot 23a:2', 'CONTEXT', "or wine in a stew (anigeron)? —"),
 ('Shevuot 23a:3', 'CONTEXT', "Rav Acha b. Yaakov: Deut 14:26 'for wine or strong drink … and you shall eat' —"),
 ('Shevuot 23a:4', 'CONTEXT', "— a stew again?"),
 ('Shevuot 23a:5', 'CONTEXT', "'strong drink' — intoxicating, not a stew."),
 ('Shevuot 23a:6', 'CONTEXT', "or Keilah's pressed figs (the intoxicated priest's baraita: figs, honey, milk)? — the priesthood's drunk-service by reference."),
 ('Shevuot 23a:7', 'DERIVATION', "CREDITED (the Naso docket) — 'strong drink' by the verbal analogy with the NAZIRITE'S (6:3): wine — NS.DATA nazir_wine_pair by reference (I2)."),
 ('Shevuot 23a:8', 'CONTEXT', "Rava: the Mishnah too — 'ate and drank, one offering' needs saying only if drinking is inside eating."),
 ('Shevuot 23a:9', 'CONTEXT', "Abaye: then 'not eat and not drink — two'? the drinking already forbidden by the first —"),
 ('Shevuot 23a:10', 'CONTEXT', "Rava: he said 'not drink' first, then 'not eat' — eating is not inside drinking."),
 ('Shevuot 23a:11', 'CONTEXT', "then 'not eat and not drink' in that order — one? teach that instead —"),
 ('Shevuot 23a:12', 'CONTEXT', "— rather two: saying 'not drink' after 'not eat' REVEALS the eating meant eating alone — the oath's wording read."),
 ('Shevuot 23a:13', 'CONTEXT', "Rav Ashi: 'inedible food, unpotable drink — exempt' under 'I will not eat' — so drinking is inside eating."),
 ('Shevuot 23a:14', 'CONTEXT', "or he swore both; the Mishnah's interest the inedible."),
 ('Shevuot 23a:15', 'CONTEXT', "the breads specified — separate oaths, or a limit to bread? —"),
 ('Shevuot 23a:16', 'CONTEXT', "he could say 'wheat, barley, spelt' — but that might mean chewing kernels —"),
 ('Shevuot 23a:17', 'CONTEXT', "'bread of wheat or barley or spelt' — might mean wheat bread and kernels of the others —"),
 ('Shevuot 23a:18', 'CONTEXT', "'bread of wheat and of barley and of spelt' —"),
 ('Shevuot 23b:1', 'CONTEXT', "— might mean a bread of the mixture —"),
 ('Shevuot 23b:2', 'CONTEXT', "'bread of wheat and so of barley and so of spelt' would limit; repeating 'bread' each time INDIVIDUATES — the oath's grammar of repetition (E10-class on the answer sheet)."),
 ('Shevuot 23b:3', 'CONTEXT', "the liquids: no surplus word — why three oaths? —"),
 ('Shevuot 23b:4', 'CONTEXT', "Rav Pappa: the three set before him — 'I will not drink these' would limit; but 'these' might mean only these particular ones —"),
 ('Shevuot 23b:5', 'CONTEXT', "'such as these' — might mean the volume —"),
 ('Shevuot 23b:6', 'CONTEXT', "'from these types' — might exclude the particular ones —"),
 ('Shevuot 23b:7', 'CONTEXT', "'these and their types' would limit; naming wine, oil, honey individuates — the oath's grammar."),
]
