#!/usr/bin/env python3
# THE NUMBERS WALK sitting 9 — THE OFFERINGS CALENDAR (2026-09-11): THE CLAIMS of Numbers 28:1-29:39, three manifests for the three draft
# units, read off this sitting's three ledgers, every claim LABELED (World/step9/CLAIM_LABELS.md's vocabulary), a machine check where the ink
# allows — every he_contains substring CUT FROM THE SNAPSHOT STORE'S OWN BYTES by the word's CONSONANTS (sitting 6's form). Claim IDs PN28A-,
# PN28B-, PN29A- (Pinchas, chapters 28 and 29). Written once (the files must not exist; each ID prefix checked absent from every existing
# manifest and unit). Every source cite is checked against its ledger's CITE INDEX before a byte is written.
import json, os, re, sqlite3, glob
ROOT = '<repo-old>'
DATE = '2026-09-11'
db = sqlite3.connect(f'file:{ROOT}/torah_grok.SNAPSHOT-main-51801ca.sqlite?mode=ro', uri=True)
def cut(book, ch, v, word, n, nth=0):
    rows = db.execute("SELECT w.idx, w.he FROM words w JOIN verses v ON w.verse_id=v.id WHERE v.book=? AND v.chapter=? AND v.verse=? ORDER BY w.idx", (book, ch, v)).fetchall()
    plain = lambda h: ''.join(c for c in h if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
    hit = [(i, h) for i, h in rows if plain(h) == word]
    assert len(hit) > nth and (len(hit) == 1 or nth is not None), (book, ch, v, word, hit)
    idx, he = hit[nth]
    piece = max(he.split('/'), key=len)
    n = min(len(piece), max(n, 6))
    assert n >= 6, (book, ch, v, word, piece)
    return idx, piece[:n]
def hc(ref, word, n, note, nth=0):
    b, cv = ref.split(' '); c, v = map(int, cv.split(':'))
    idx, sub = cut(b, c, v, word, n, nth)
    return {"type": "he_contains", "ref": ref, "idx": idx, "contains": sub, "note": note}
def onk(c, lo, hi): return '; '.join(f'Onkelos Num {c}:{v}' for v in range(lo, hi + 1))
def sif(*rows): return '; '.join(f'Sifrei Bamidbar {r}' for r in rows)

UNITS = {
 'num_28_daily_shabbat_rosh': ('PN28A', [
  {"id": "PN28A-01", "source": sif('142:1', '142:2') + '; ' + onk(28, 1, 2), "ref": "Num 28:1-2",
   "claim_en": "THE LORD SPOKE TO MOSES — THE ONE FRAME OF SEVENTY VERSES; COMMAND: MY OFFERING, MY BREAD FOR MY FIRE-OFFERINGS, MY PLEASING AROMA — FOUR POSSESSIVES, THREE HAPAX FORMS; KEEP TO OFFER TO ME IN ITS APPOINTED TIME — THE PESACH'S PHRASE AT ITS THIRD SEAT, THE SIFREI'S IDENTITY. 28:1 is the only frame and the only narrative verb in 28:1-29:39 (computed on the morphology): the two chapters are the LORD's one speech, closed at 30:1 by 'and Moses said... according to all that the LORD commanded Moses'. 'My offering, My bread for My fire-offerings, My pleasing aroma' (28:2) — four first-person possessives on the altar's four nouns; 'My offering', 'for My fire-offerings', 'My pleasing aroma' each ONE seat in the Bible, 'My bread' ten (computed); the Sifrei parses them into the blood, the devoted portions, the fistfuls with the frankincense, and the libations — the Hebrew row: the showbread's dishes (142:2). 'You shall keep to offer to Me IN ITS APPOINTED TIME' — the phrase's three Torah seats are the Pesach's (9:2, 9:3) and this (computed): the Sifrei's identity of expression on a FREED term (28:9 already gives the Sabbath its lambs, so 28:2's 'in its appointed time' is free for the identity) — as the tamid overrides the Sabbath, so the Pesach (R. Yoshiyah answering R. Yonatan; the English drops the speaker, recorded); Pesachim 66a's Hillel the exam's row. The king's parable on the juxtaposition with Joshua's appointment (142:1). ONKELOS: 'My bread' → ARRANGED BREAD (the showbread's word); 'a pleasing aroma' → 'to be accepted with favor' at every one of the eleven seats (cut).",
   "middah": "I2 (the identity of expression on a freed term — 'in its appointed time' at exactly the Pesach's two seats and the tamid's one, computed; the freeing argued from 28:9's redundancy)",
   "check": hc("Num 28:2", "קרבני", 6, "'My offering' — the first of the four possessives, a one-seat form")},
  {"id": "PN28A-02", "source": sif('142:3', '142:4') + '; ' + onk(28, 3, 4), "ref": "Num 28:3-4",
   "claim_en": "TWO PER DAY — THE TAMID'S TWO SEATS (EXODUS 29:38); THE ONE LAMB IN THE MORNING, THE SECOND AT DUSK — EXODUS 29:39 WORD FOR WORD BUT FOR ONE ARTICLE; BEN AZZAI'S 'OPPOSITE THE DAY'. 'Yearling lambs, unblemished, two per day, a continual burnt offering' (28:3) — 'two per day' here and Exodus 29:38 alone (computed): the Exodus tamid restated; the Sifrei: 'say to them' charges the court, and 'two per day' is read 'opposite the day' — the sun fixing the slaughter's corner, the morning lamb at one corner of the altar, the evening at another (the English and Hebrew rows name different corners — 142:3; Tamid 4:1 the exam); 'the lamb, ONE, you shall do in the morning, and the second lamb between the evenings' (28:4) — Exodus 29:39's eleven tokens with 'THE one' losing its article (computed on the tokens); the parser reads 1 and the ordinal 2; the Sifrei: 'the one lamb' — not more than one, though two verses command the tamid (142:4); 'the second' — second to the tamid, not to the Pesach; the evening's depends on the morning's unless the court erred (143:3). ONKELOS: 'between the suns' for 'between the evenings'; 'whole' for 'unblemished' (cut).",
   "middah": "ink (the two-seat phrase and the one-article delta computed on the tokens; the Sifrei's readings the exam's)",
   "check": hc("Num 28:3", "שנים", 6, "'two' — two per day, the tamid's number at its second seat")},
  {"id": "PN28A-03", "source": sif('142:5') + '; ' + onk(28, 5, 5), "ref": "Num 28:5",
   "claim_en": "A TENTH OF THE EPHAH OF FINE FLOUR, MIXED WITH A QUARTER HIN OF BEATEN OIL — THE MEASURE NAMED AT THE SECOND SEAT; ALL FLOURS ARE WHEAT BY THE ONE SPECIFICATION; ONKELOS CONVERTS THE EPHAH TO THREE SEAHS. 28:5 names 'the ephah' where Exodus 29:40 said 'a tenth-part' (computed); 'beaten oil' at the tamid's two seats alone (Exodus 29:40, here), the lamp's oil 'beaten' too (Exodus 27:20, Leviticus 24:2); the parser reads 1/10 and 1/4 — 4b's fraction class at a new seat. THE SIFREI: 'a tenth' — one of ten; 'fine flour' is WHEAT — Exodus 29:2 specifies wheat once and the one specification governs every unqualified 'flour' in the Torah; 'beaten' excludes oil pressed by cooking, and the menorah's the same (142:5). ONKELOS: 'one of ten in THREE SEAHS' — the ephah rendered as its three seahs, the translation's conversion layer at a new seat (cut from the shelf's bytes).",
   "middah": "I3 (the generalization from the one specified case — Exodus 29:2's 'wheat' read onto every 'flour'; the Sifrei's own argument; the ink's two seats of 'beaten oil' computed)",
   "check": hc("Num 28:5", "ועשירית", 6, "'and a tenth of' — the ephah named at the tamid's second seat")},
  {"id": "PN28A-04", "source": sif('143:1', '143:2', '143:3') + '; ' + onk(28, 6, 8), "ref": "Num 28:6-8",
   "claim_en": "THE CONTINUAL BURNT OFFERING MADE AT MOUNT SINAI — THE PARTICIPLE'S ONE SEAT, THE SINAI OLAH LIKENED TO THE TAMID; A LIBATION OF STRONG DRINK IN THE HOLY PLACE — ONE SEAT, THE WATER LIBATION'S FIRST DERIVATION; AS THE MEAL OFFERING OF THE MORNING — EXODUS 29:41 AT ITS SECOND SEAT; BEN AZZAI: THE UNIQUE NAME ON EVERY OFFERING. 'The one made at Mount Sinai' (28:6) — the feminine participle's ONE seat in the Bible (computed); the Sifrei likens Sinai's olah to the tamid for its libations, R. Yossi HaGelili only for its 'sweet savor' (143:1). 'In the holy place pour a libation of STRONG DRINK' (28:7) — 'a libation of strong drink' and 'pour' one seat each; 'strong drink' eight Torah tokens, four the wage-homograph (computed); the Sifrei: undiluted, absorbed in the altar; R. Nathan reads the doubled root 'pour a pouring' for the WATER LIBATION (143:2 — the first of the piskaot's three derivations); 'as the meal offering of the morning' (28:8) — Exodus 29:41 and here alone (computed); the Sifrei's order of the day — nothing before the morning tamid but the incense, nothing after the evening's but the incense, the Pesach and the atonement-lacking; each offering's libation WITH it; the inaugurations of the vessels; and BEN AZZAI: every offering in the Torah names the Tetragrammaton alone — in the two chapters 'to the LORD' at every offering and Elohim never (computed) — 'no eating or drinking before Him' (143:3; the English's inserted inauguration clause and the Hebrew's garbled 'table' recorded). ONKELOS: 'strong drink' → OLD WINE; 'a pleasing aroma' → to be accepted with favor (cut).",
   "middah": "ink (the one-seat forms and the second-seat phrase computed; ben Azzai's Name census computed on the two chapters; the Sifrei's likening and the order of the day the exam's)",
   "check": hc("Num 28:6", "העשיה", 6, "'the one made' — the participle's one seat, the tamid tied to Sinai")},
  {"id": "PN28A-05", "source": sif('144:1', '144:2') + '; ' + onk(28, 9, 10), "ref": "Num 28:9-10",
   "claim_en": "ON THE SABBATH DAY TWO LAMBS AND TWO TENTHS — THE SABBATH'S FIRST OFFERING IN THE TORAH, LEVITICUS 23:3 HAVING GIVEN IT NONE; THE BURNT OFFERING OF THE SABBATH ON ITS SABBATH — ONE SEAT, ITS PAIR AT ISAIAH 66:23; THE SERVICE OVERRIDES THE SABBATH, FOR THE COMMUNAL. Leviticus 23:3's Sabbath is rest and a holy convocation with NO offering (computed on its tokens) — 28:9's two lambs and two tenths are the Sabbath's first offering; the parser reads 2, 2 (the construct 'two of'); 'the burnt offering of the Sabbath ON ITS SABBATH' (28:10) one seat, and the possessive pair 'its Sabbath' / 'its month' (28:14) stands together elsewhere in ONE verse, Isaiah 66:23 (computed). THE SIFREI: the Sabbath was inside 'the one lamb in the morning' and is taken OUT of its class for a stringency — the fixed musaf (the tenth middah); and the Sabbath's musaf proves the Temple service overrides the Sabbath — Leviticus 26:2's two clauses could run either way, 28:9 decides it — for COMMUNAL offerings ('in what does the passage speak?'); 'on its Sabbath' — not the eve's, not another Sabbath's: 'the day passed, its offering passed'; 'besides the continual' — the musafim between the two temidim (144:1-2). ONKELOS unfolds the possessive: 'the burnt offering of the Sabbath THAT IS DONE on the Sabbath' (cut).",
   "middah": "I10 (out of the general class for a stringency — the Sabbath's musaf; the Sifrei's own middah; the ink's absent offering at Leviticus 23:3 and the one-seat form computed)",
   "check": hc("Num 28:10", "בשבתו", 6, "'on its Sabbath' — the one-seat possessive, Isaiah 66:23 its pair")},
  {"id": "PN28A-06", "source": sif('145:1', '145:2') + '; ' + onk(28, 11, 14), "ref": "Num 28:11-14",
   "claim_en": "AT THE BEGINNINGS OF YOUR MONTHS — TWO BULLS, ONE RAM, SEVEN LAMBS: THE NEW MOON'S WHOLE REGISTER, ABSENT FROM LEVITICUS 23; THE MASTER TABLE — THREE, TWO, ONE TENTHS AND HALF, A THIRD, A QUARTER OF THE HIN — 15:4-10 RESTATED PER ANIMAL, CITED BY EVERY LATER DAY; THE HIN'S THREE MARKS; IN ITS MONTH FOR THE MONTHS OF THE YEAR. Leviticus 23 has no new moon (computed) — 28:11-15 is its register; 'at the beginnings of your months' here and 10:10; the parser [2, 1, 7] (the noun between 'one' and 'seven' keeps them apart); 28:12-14's tenths [3, 1, 2, 1], [1, 1] (the distributive 'a tenth, a tenth' as one, spelled defective then plene side by side) and hins [1/2, 1/3, 1/4] restate Numbers 15:4-10's per-animal table (computed at both) — THE MASTER TABLE every Sukkot day cites 'according to the ordinance'; 'a third of the hin' with its conjunction one seat; 'the burnt offering of the month in its month' one seat; 'for the months of the year' here and Exodus 12:2 — the calendar's defining verse and the month-offering's scope (computed). THE SIFREI: the new moon taken out of the tamid's class with ITS OWN NUMBER, not the Sabbath's two (the analogy refused); the HIN in the Temple with marks 'thus far for the bull, the ram, the lamb' (R. Elazar b. R. Tzadok) or no hin but a log-and-a-half (R. Yishmael); 'in its month' — no make-up; 'the months of the year' — not the plural's minimum two (145:1-2). ONKELOS: 'in its month' → AT ITS RENEWAL (cut).",
   "middah": "ink (the register's absence from Leviticus 23, the table's restatement of 15:4-10 and the one-seat forms computed by the parser and the tokens; the Sifrei's hin the exam's)",
   "check": hc("Num 28:14", "בחדשו", 6, "'in its month' — the one-seat possessive, the master table's close")},
  {"id": "PN28A-07", "source": sif('145:3') + '; ' + onk(28, 15, 15), "ref": "Num 28:15",
   "claim_en": "ONE GOAT FOR A SIN OFFERING TO THE LORD — THE ONLY GOAT OF THE TWO CHAPTERS' THIRTEEN THAT SAYS 'TO THE LORD'; THE GRAVE OF THE DEEP; BESIDES THE CONTINUAL. Of the thirteen goats of Numbers 28-29 the new moon's alone reads 'a sin offering TO THE LORD' (28:15); the festivals' say 'to atone for you' (28:22, 28:30, 29:5) or bare 'a sin offering' (29:11-38) — computed on the thirteen heads; the Sifrei: the goat atones for 'a grave of the deep' — the hidden impurity (145:3), the reading the exam's Shevuot 9a gives the words 'to the LORD' ('a sin only He knows'); 'besides the continual burnt offering it shall be done' — the musaf between the temidim. ONKELOS: 'a kid of goats... a sin offering before the LORD' (cut).",
   "middah": "E2 (the restrictor 'to the LORD' read for the goat's object — the Sifrei's and the Talmud's reading; the thirteen heads computed)",
   "check": hc("Num 28:15", "לחטאת", 6, "'for a sin offering' — the new moon's goat, alone 'to the LORD'")},
 ]),
 'num_28_pesach_shavuot': ('PN28B', [
  {"id": "PN28B-01", "source": sif('146:1', '147:1') + '; ' + onk(28, 16, 18), "ref": "Num 28:16-18",
   "claim_en": "IN THE FIRST MONTH ON THE FOURTEENTH DAY — PESACH TO THE LORD; ON THE FIFTEENTH A FESTIVAL, SEVEN DAYS UNLEAVENED BREAD SHALL BE EATEN; ON THE FIRST DAY A HOLY CONVOCATION, NO LABORIOUS WORK — LEVITICUS 23:5-7 AT THEIR SECOND SEAT, THE DELTAS COMPUTED; THE FIVE GRAINS; THE FOOD-WORK BY THE IDENTITY 'HOLY CONVOCATION'. 28:16 = Leviticus 23:5 with 'at dusk' DROPPED (six of eight tokens); 28:17 = 23:6 with 'the festival of unleavened bread to the LORD' shortened to 'a festival' and 'you shall eat' made the passive 'shall be eaten' (nine of ten; the passive at Exodus 13:7, Ezekiel 45:21); 28:18 = 23:7 with 'shall be to you' dropped (nine of nine) — computed per pair; the parser reads 14, 15, 7 and the ordinal 'the first'. THE SIFREI: the date 'fixed as an obligation'; 'unleavened bread shall be eaten' with Deuteronomy 16:3 — only what can leaven: the five grains, not rice or millet (146:1); 'holy convocation' — food, drink and clean clothes; 'laborious work' forbidden and food-work permitted — the Hebrew by the IDENTITY 'holy convocation' with Exodus 12:16, the English by bare citation (147:1; recorded). 'Laborious work' at the six festival days of the two chapters against 'any work' at Yom Kippur (computed).",
   "middah": "M-23 (the second seat's delta — Leviticus 23:5-7 at Numbers 28:16-18 with the dropped and altered tokens computed; the Sifrei's identity at 147:1 noted)",
   "check": hc("Num 28:16", "פסח", 6, "'Pesach' — the fourteenth day at its second seat")},
  {"id": "PN28B-02", "source": sif('147:1') + '; ' + onk(28, 19, 19), "ref": "Num 28:19",
   "claim_en": "YOU SHALL OFFER A FIRE-OFFERING — TWO BULLS, ONE RAM AND SEVEN LAMBS: THE NEW MOON'S TABLE FOR EACH DAY OF PESACH; THE PARSER'S GAP — 'ONE AND SEVEN' READ AS EIGHT ACROSS THE ETNACHTA (THE MID-VERSE PAUSE); 'EVEN ONE'. 28:19's table is 28:11's (2, 1, 7) and 28:27's — but THE PARSER READS [2, 8]: 'one' carries the etnachta (the verse's strongest pause) yet the bar is not emitted before a numeral that carries the conjunction ('and seven'), and the phrase joins one and seven; 28:27's identical 'one' with the etnachta before the BARE 'seven' takes the bar and reads [2, 1, 7]; 'one and-seven' adjacent is 28:19's alone in the Bible (computed on the accents) — GAP (23), owed to the compile: a disjunctive on a numeral closes the phrase before 'and + numeral' too. THE SIFREI: bulls found and no rams, rams and no lambs — offer what is found, 'even one' (the Hebrew's proof-text Leviticus 23:8, the English's the Numbers verse — recorded), and when all are found the full number (147:1 — the rule's first of four seats in the eleven piskaot). 'Unblemished shall they be for you' — three seats (28:19, 28:31, 29:8).",
   "middah": "M-26 (the accent read — the etnachta on 'one' the disjunctive the bar rule does not yet take before a conjoined numeral; the gap measured on the accents of 28:19 against 28:27)",
   "check": hc("Num 28:19", "ושבעה", 6, "'and seven' — the conjoined numeral the parser joins to 'one'")},
  {"id": "PN28B-03", "source": onk(28, 20, 23), "ref": "Num 28:20-23",
   "claim_en": "THEIR MEAL OFFERING BY THE MASTER TABLE; A TENTH, A TENTH FOR THE SEVEN LAMBS; ONE GOAT, A SIN OFFERING, TO ATONE FOR YOU — WITHOUT 'TO THE LORD'; BESIDES THE BURNT OFFERING OF THE MORNING — THE STACK NAMED, 'BESIDES' TWELVE TIMES IN THE TWO CHAPTERS. 28:20-21 restate 28:12-13's rows without 'the one' — [3, 2] and [1, 1, 7], the distributive at its second seat (computed); 28:22's goat 'to atone for you' — the short form 'a goat, a sin offering, one' here and at Sukkot's days 3 and 5-8; 'to atone for you' at Pesach, Shavuot and the day of blowing (computed on the thirteen heads); 28:23 'BESIDES the burnt offering of the morning, which is for the continual burnt offering' — 'besides' twelve times in Numbers 28-29 of the Torah's twenty (computed): the festival offering is a layer on the daily one. ONKELOS adds 'so' to the distributive ('a tenth, a tenth... SO for the seven lambs', cut).",
   "middah": "ink (the tables and the forms computed on the tokens and the parser; 'besides' counted)",
   "check": hc("Num 28:23", "התמיד", 6, "'the continual' — the daily offering the festival's stacks on; 'besides' (the store splits it into prefixes) is the stack's word, twelve of the Torah's twenty in these chapters")},
  {"id": "PN28B-04", "source": sif('147:2') + '; ' + onk(28, 24, 25), "ref": "Num 28:24-25",
   "claim_en": "AS THESE YOU SHALL DO EACH DAY, SEVEN DAYS — ONE SEAT: PESACH'S CONSTANT TABLE IN ONE VERSE WHERE SUKKOT'S DECLINING TABLE TAKES TWENTY-TWO; BREAD, A FIRE-OFFERING; THE SEVENTH DAY WITHOUT ITS OFFERING CLAUSE. 'As these you shall do each day, seven days' (28:24) one seat (computed); Pesach's seven days share one verse, Sukkot's (29:13-34) are written day by day — the Sifrei's refused analogy ('Sukkot's decreases, so should Pesach's' — 'as these': neither add nor subtract, 147:2) is the ink's own two shapes; 'bread, a fire-offering' at Leviticus 3:11, 3:16 and here — 28:2's 'My bread' answered; 'burnt offering' spelled plene at 28:24 against the chapter's defective form (computed); 28:25 = Leviticus 23:8 with its offering clause gone (eight of eleven tokens; computed) — the offerings given at 28:19-24, the day-clause alone.",
   "middah": "ink (the one-seat clause and the two shapes computed; the Sifrei's refused analogy the exam's)",
   "check": hc("Num 28:24", "כאלה", 6, "'as these' — Pesach's constant table, one seat")},
  {"id": "PN28B-05", "source": sif('148:1') + '; ' + onk(28, 26, 26), "ref": "Num 28:26",
   "claim_en": "ON THE DAY OF THE FIRSTFRUITS, WHEN YOU OFFER A NEW MEAL OFFERING TO THE LORD, IN YOUR WEEKS — 'IN YOUR WEEKS' ONE SEAT, 'A NEW MEAL OFFERING' TWO; ONKELOS RENDERS 'IN YOUR WEEKS' AS 'IN YOUR ASSEMBLIES' — SHAVUOT NAMED ATZERET BY THE TRANSLATION; THE FIFTIETH DAY; THE NEWEST OF THE MEAL OFFERINGS. 'A new meal offering' at Leviticus 23:16 and here; 'in your weeks' ONE seat (computed): the festival named by its offering and dated by the count. THE SIFREI: count fifty and offer on the fiftieth, not the fifty-first; the festival the same day — 'in your weeks', not after them; 'new' — the newest of all meal offerings: a new-crop meal offering before the omer is unfit, before the two loaves fit after the fact; R. Tarfon's analogy and Yehudah ben Nachman's answer; R. Akiva's 'your face shines — I doubt you will live long', and he died before Shavuot (148:1). ONKELOS: 'in your weeks' → IN YOUR ASSEMBLIES (the word ATZERET — the tradition's own name for Shavuot in the translation's mouth; the ink gives the word to Sukkot's eighth day and Pesach's seventh; cut from the shelf's bytes).",
   "middah": "ink (the one-seat and two-seat phrases computed; the translation's name cut from the shelf; the Sifrei's fiftieth day the exam's)",
   "check": hc("Num 28:26", "בשבעתיכם", 6, "'in your weeks' — one seat; Onkelos: in your assemblies")},
  {"id": "PN28B-06", "source": sif('149:1') + '; ' + onk(28, 27, 30), "ref": "Num 28:27-30",
   "claim_en": "YOU SHALL OFFER A BURNT OFFERING — TWO BULLS, ONE RAM, SEVEN LAMBS: THE THIRD IDENTICAL TABLE OF THE CHAPTER, READ RIGHT BY THE BAR; A SECOND SET BESIDE LEVITICUS 23:18'S — THE BULLS AND RAMS REVERSED; THE SIFREI'S HEBREW PROOF-TEXT GARBLED TO SUKKOT'S TWELVE BULLS. 28:27's table = 28:11's = 28:19's (2, 1, 7); the parser reads [2, 1, 7] here because the etnachta (the mid-verse pause) on 'one' stands before the BARE 'seven' and takes the bar (28:19's conjoined 'and seven' did not); Leviticus 23:18's Shavuot table is one bull, TWO rams, seven lambs — the two numbers reversed between the two Shavuot tables (computed): the Sifrei's 'these besides those — are they alike?' — two sets (149:1); its Hebrew row quotes 'bulls TWELVE, rams two' — Sukkot's second day (29:17) — for 28:27 (the English right; recorded); 'even one' at its second seat; 28:28-29 the master table's rows, 28:30 'one goat of goats to atone for you' — the princes' form of Numbers 7 (computed).",
   "middah": "ink (the three tables and the reversal computed by the parser at both books; the shelf's garbled row recorded)",
   "check": hc("Num 28:27", "איל", 6, "'ram' — one ram, where Leviticus 23:18's Shavuot has two")},
  {"id": "PN28B-07", "source": sif('149:2') + '; ' + onk(28, 31, 31), "ref": "Num 28:31",
   "claim_en": "BESIDES THE CONTINUAL BURNT OFFERING AND ITS MEAL OFFERING; UNBLEMISHED SHALL THEY BE FOR YOU — AND THEIR LIBATIONS: THE LIBATIONS JOINED TO THE UNBLEMISHED, THE SIFREI'S LIKENING. 'Unblemished shall they be for you' at three seats (28:19, 28:31, 29:8), 28:31 alone adding 'and their libations' after it (computed on the tokens); the Sifrei: the libations likened to the beast — a libation short or over its measure unfit as a blemished animal (149:2; Menachot 87a-b the exam).",
   "middah": "ink (the three seats and the one addition computed; the Sifrei's likening the exam's)",
   "check": hc("Num 28:31", "ונסכיהם", 6, "'and their libations' — joined to the unblemished at this seat alone")},
 ]),
 'num_29_fall_festivals': ('PN29A', [
  {"id": "PN29A-01", "source": onk(29, 1, 6), "ref": "Num 29:1-6",
   "claim_en": "IN THE SEVENTH MONTH ON THE FIRST OF THE MONTH — A DAY OF BLOWING, ONE SEAT (LEVITICUS 23:24'S 'MEMORIAL OF BLOWING'); ONE BULL, ONE RAM, SEVEN LAMBS — THE TISHRI TABLE; BESIDES THE BURNT OFFERING OF THE MONTH AND THE CONTINUAL — THE THREE-LAYER STACK; ACCORDING TO THEIR ORDINANCE — THE POINTER; ONKELOS: A DAY OF WAILING. 'A day of blowing' ONE seat; the blowing-word's five Torah seats (the trumpets' alarm 10:5-6, the Jubilee's, 23:24's memorial, this); 29:1 = Leviticus 23:24 ten of seventeen tokens (computed); the parser [1] and the ordinal 7; 29:2's [1, 1, 7] — the new moon's table less a bull, the same at 29:8 and 29:36 (computed); 29:6 'BESIDES the burnt offering of the MONTH and its meal offering, and the continual burnt offering' — the first of Tishri the one day with two named layers beneath its musaf; 'according to THEIR ordinance' here and 29:33 in the two chapters, the singular at six Sukkot days — the POINTER to the master table (computed). ONKELOS: 'a day of blowing' → A DAY OF WAILING (the teruah a wail — sitting 3's finding at the trumpets, at its third seat); 'according to their ordinance' → 'as is fit for them' (cut).",
   "middah": "ink (the one-seat phrase, the second-seat delta, the table and the stack computed; the translation cut)",
   "check": hc("Num 29:1", "תרועה", 6, "'blowing' — a day of blowing, one seat; Onkelos: a day of wailing")},
  {"id": "PN29A-02", "source": onk(29, 7, 11), "ref": "Num 29:7-11",
   "claim_en": "ON THE TENTH OF THIS SEVENTH MONTH — THE PLENE 'TENTH' THE PARSER'S SECOND GAP; YOU SHALL AFFLICT YOUR SOULS; ANY WORK YOU SHALL NOT DO — AGAINST THE FESTIVALS' 'LABORIOUS WORK'; ONE GOAT BESIDES THE SIN OFFERING OF THE ATONEMENTS — THE PHRASE'S TWO SEATS, LEVITICUS 16'S GOAT BY POINTER; ONKELOS: YOU SHALL FAST. 29:7's 'on the tenth' (spelled plene, with the vav) is SILENT in the parser, as at Leviticus 16:29, 23:27, 25:9; Exodus 12:3's defective form reads 10 — GAP (24), owed to the compile (computed); 'afflict your souls' at Leviticus 16:31, 23:27, 23:32 and here; 'ANY work' — the Sabbath's and 23:31's form, not the six festival days' 'laborious work': the food-work permission withheld in the ink's own two forms (computed); 29:7 = Leviticus 23:27 ten of fifteen with 'the day of atonements' dropped; 29:8-10 the Tishri table and the master table's rows; 29:11 'one goat of goats, a sin offering, BESIDES THE SIN OFFERING OF THE ATONEMENTS' — the phrase at Exodus 30:10 (the incense altar's yearly blood) and here alone: the day's own goat of Leviticus 16:9 named by pointer, the stack the tamid, Leviticus 16's rite, the musaf (computed). ONKELOS: 'afflict' → YOU SHALL FAST (cut).",
   "middah": "ink (the plene form's seats and the parser's silence measured; the two work-forms and the two-seat phrase computed)",
   "check": hc("Num 29:7", "ובעשור", 6, "'and on the tenth' — the plene tenth-day noun the parser does not read")},
  {"id": "PN29A-03", "source": sif('150:1') + '; ' + onk(29, 12, 15), "ref": "Num 29:12-15",
   "claim_en": "ON THE FIFTEENTH DAY OF THE SEVENTH MONTH — A HOLY CONVOCATION, AND YOU SHALL CELEBRATE A FESTIVAL TO THE LORD SEVEN DAYS (ONE SEAT); THIRTEEN BULLS, TWO RAMS, FOURTEEN LAMBS — THE DECLINING TABLE OPENS, THE TEENS READ; THE TABLE MULTIPLIED — THREE TENTHS FOR THE ONE BULL FOR THE THIRTEEN BULLS; 'EVEN ONE' A THIRD TIME. 29:12 = Leviticus 23:34 with 'the festival of booths' DROPPED (eight of nineteen; the festival unnamed here as at 28:17); 'and you shall celebrate a festival to the LORD seven days' one seat (23:41 'celebrate it'); the parser 15, 7; 29:13's [13, 2, 14]; 29:14's [3, 1, 13, 2, 1, 2] — the per-head rate and the head-count in one verse: thirty-nine tenths for the bulls and four for the rams on the first day (computed); 29:15 [1, 1, 14]. THE SIFREI: the date fixed as an obligation; 'even one' at its third seat (Leviticus 23:36 the proof-text) (150:1).",
   "middah": "ink (the second-seat delta, the one-seat clause and the multiplied table computed by the parser)",
   "check": hc("Num 29:12", "וחגתם", 6, "'and you shall celebrate' — a festival seven days, one seat")},
  {"id": "PN29A-04", "source": onk(29, 16, 18) + '; ' + onk(29, 20, 30) + '; ' + onk(29, 32, 34), "ref": "Num 29:16-34",
   "claim_en": "THE SEVEN DAYS — BULLS 13, 12, 11, 10, 9, 8, 7: SEVENTY; RAMS TWO AND LAMBS FOURTEEN EVERY DAY, A GOAT EVERY DAY; THE POINTER LINE SEVEN TIMES — BY THEIR NUMBER, ACCORDING TO THE ORDINANCE; THE GOAT-LINE'S TWO FORMS; 'ELEVEN' BY THE BOUND FORM. The parser reads the bulls 13 to 7 (29:13, 17, 20, 23, 26, 29, 32) — SEVENTY in all (the exam's Sukkah 55b: the seventy nations), the rams fourteen, the lambs ninety-eight, the goats seven (computed); 'eleven' (29:20) by 2b's bound form at its second Torah seat; the pointer line 'their meal offering and their libations for the bulls, for the rams and for the lambs BY THEIR NUMBER, ACCORDING TO THE ORDINANCE' at every day (29:18, 21, 24, 27, 30, 33, 37) — 'by their number' seven seats, all Sukkot's; the measures never restated after the master table — the compile's cross-reference form in the calendar's own text; the goat-line 'a goat of goats, one, a sin offering' at days 1, 2, 4 and 'a goat, a sin offering, one' at days 3, 5, 6, 7, 8 (computed on the tokens); by the master table the seven days take 21 ephahs of flour for the bulls, 2 4/5 for the rams, 9 4/5 for the lambs and 64 1/6 hins of wine — sums the ink never writes, computed and labeled ours. ONKELOS: every count tens-first; 'according to the ordinance' → 'as is fit' (cut).",
   "middah": "ink (every count by the parser, the sums computed and labeled; the forms counted on the tokens)",
   "check": hc("Num 29:20", "עשתי", 6, "'eleven' — the bound form at its second Torah seat, the third day's bulls")},
  {"id": "PN29A-05", "source": sif('150:1') + '; ' + onk(29, 19, 19) + '; ' + onk(29, 31, 31) + '; ' + onk(29, 33, 33), "ref": "Num 29:19-33",
   "claim_en": "THE WATER LIBATION SPELLED IN THREE LETTERS, VERIFIED ON THE INK: THE SECOND DAY'S 'AND THEIR LIBATIONS' (AN EXTRA MEM), THE SIXTH DAY'S 'AND ITS LIBATIONS' (AN EXTRA YOD — THE FORM'S ONE SEAT IN THE BIBLE), THE SEVENTH DAY'S 'ACCORDING TO THEIR ORDINANCE' (AN EXTRA MEM) — WATER; THREE DERIVATIONS OF ONE LAW. The goat-verses of the seven days close 'and its libation' at days 1, 3, 4, 5, 7 and the eighth (29:16, 22, 25, 28, 34, 38) — but the SECOND day closes 'and THEIR libations' (29:19) and the SIXTH 'and its LIBATIONS' (29:31 — the form's ONE seat in the Bible); the pointer-verses read 'according to the ordinance' at six days — but the SEVENTH reads 'according to THEIR ordinance' (29:33): mem, yod, mem — the word 'water' — R. Yehudah ben Beteira's derivation of Sukkot's water libation (the Sifrei 150:1; Taanit 2b-3a; Shabbat 103b the exam) VERIFIED letter for letter on the tokens of all fifteen verses (computed); the Sifrei carries three sources for the one law — R. Akiva's induction from the seasons (the omer for the grain, the firstfruits for the trees, water for the rains), R. Yehudah ben Beteira's letters, R. Nathan's 'pour a pouring' (28:7) — a dispute on the SOURCE with the law agreed (the English shortens the name to 'R. Yehudah'; recorded).",
   "middah": "M-28 (the letter read — three deviant spellings across three verses read as one word by the tradition, verified on the tokens; the Sifrei's own move at 150:1, Taanit 2b's)",
   "check": hc("Num 29:31", "ונסכיה", 6, "'and its libations' — the sixth day's form, one seat in the Bible, the yod of 'water'")},
  {"id": "PN29A-06", "source": sif('151:1', '151:2') + '; ' + onk(29, 35, 38), "ref": "Num 29:35-38",
   "claim_en": "ON THE EIGHTH DAY AN ASSEMBLY SHALL BE FOR YOU — THE WORD'S THREE TORAH SEATS, PESACH'S SEVENTH DAY THE THIRD; WITHHELD FROM LEAVING; ONE BULL, ONE RAM, SEVEN LAMBS — THE TISHRI TABLE, A FESTIVAL OF ITS OWN; 'EVEN ONE' A FOURTH TIME; ONKELOS: A GATHERING. 'Assembly' (the word of 29:35) three Torah seats — Leviticus 23:36 and this for Sukkot's eighth day, Deuteronomy 16:8 for PESACH'S SEVENTH (computed; six in the Bible); 29:35 = 23:36 nine of ten; the eighth day's table [1, 1, 7] is the day of blowing's and the day of affliction's, not the seventh day's (7, 2, 14) continued — the eighth day's own offering ('a festival to itself', Sukkah 48a); 'bull' without 'son of the herd' here alone of the Tishri three; 29:37's pointer in the singular ('for the bull, for the ram'); 29:38's goat (computed). THE SIFREI: 'withheld from leaving' — the pilgrim held in Jerusalem overnight, the word's sense from Jeremiah's 'confined', and the first day the same by the shared 'holy convocation' (151:1); 'even one' at its fourth seat, the Sifrei on Numbers proving Numbers' tables from Leviticus 23:8 each time — a cross-book teacher edge (151:2). ONKELOS: 'assembly' → A GATHERING — the word it gave Shavuot at 28:26 (cut).",
   "middah": "ink (the word's seats and the tables computed; the Sifrei's lexical proof the exam's)",
   "check": hc("Num 29:35", "עצרת", 6, "'assembly' — the eighth day's word, Pesach's seventh day its third seat")},
  {"id": "PN29A-07", "source": sif('152:1') + '; ' + onk(29, 39, 39), "ref": "Num 29:39",
   "claim_en": "THESE YOU SHALL DO TO THE LORD IN YOUR APPOINTED TIMES, BESIDES YOUR VOWS AND YOUR FREEWILL OFFERINGS — THE CALENDAR'S 'THESE' FOOTER, LEVITICUS 23:37-38'S CLOSE REWRITTEN WITH THE FOUR OFFERING-KINDS; THE FESTIVAL'S VOWS; AND MOSES SAID (30:1) THE PARAGRAPH'S CLOSER. 29:39 shares two of its eleven tokens with Leviticus 23:37 — the close rewritten: 23:38's 'besides the Sabbaths of the LORD and besides your gifts and besides all your vows and besides all your freewill offerings' become 'besides your vows and your freewill offerings' with 'your burnt offerings, your meal offerings, your libations and your peace offerings' listed (computed); 'besides your vows' one seat; 'your freewill offerings' here and Deuteronomy 12:6. THE SIFREI: the vows and freewill offerings vowed ON the festival are brought on it — the year's are Deuteronomy 12:5-6's; 'besides your vows' includes the zavim's bird-pairs; and 30:1's 'and Moses said to the children of Israel' CLOSES the matter — without it 'besides your vows... and Moses spoke' (30:2) would not say where the vows' chapter begins (R. Yishmael, 152:1): the frame read as punctuation — the 'these' footer the architecture measurement counted as a register's close. ONKELOS: 'your peace offerings' → the sacrifices of your holy things (cut).",
   "middah": "ink (the rewritten close computed token by token; the Sifrei's structural rule — the frame as a closer — recorded in MIDDOT.md)",
   "check": hc("Num 29:39", "מנדריכם", 6, "'from your vows' — besides your vows, the footer's one-seat phrase")},
 ]),
}
for uid, (pre, C) in UNITS.items():
    out = f'{ROOT}/logic/oral_audit/manifests/{uid}_claims.json'
    assert not os.path.exists(out), out
    for f in glob.glob(f'{ROOT}/logic/oral_audit/manifests/*_claims.json') + glob.glob(f'{ROOT}/logic/units/*.yaml'):
        assert f'{pre}-' not in open(f, encoding='utf-8').read(), (pre, f)
    led = open(f'{ROOT}/logic/oral_triage/{uid}_{DATE}.md', encoding='utf-8').read().split('## CITE INDEX')[1]
    CI = set(re.findall(r'^(Sifrei Bamidbar \d+:\d+|Onkelos Num \d+:\d+)$', led, re.M))
    for c in C:
        assert c['id'].startswith(pre) and c['middah'] and c['check']['contains'], c['id']
        for s in c['source'].split('; '): assert s in CI, (c['id'], s)
    assert [c['id'] for c in C] == [f'{pre}-{i:02d}' for i in range(1, len(C) + 1)]
    json.dump(C, open(out, 'w', encoding='utf-8'), ensure_ascii=False, indent=1); open(out, 'a', encoding='utf-8').write('\n')
    print(f'{uid}: {len(C)} claims ({pre}) -> {out}; cite index {len(CI)}')
