import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE NUMBERS WALK sitting 13 — THE JOURNEYS (2026-09-12): THE CLAIMS of Numbers 33:1-56, one manifest for the one draft unit, read off this
# sitting's ledger, every claim LABELED (World/step9/CLAIM_LABELS.md's vocabulary), a machine check where the ink allows — every he_contains
# substring CUT FROM THE SNAPSHOT STORE'S OWN BYTES by the word's CONSONANTS: the check is the word's LONGEST PIECE WHOLE (never a prefix
# fragment; the floor four code points). Claim IDs MS33A- (Masei, chapter 33). Written once (the file must not exist; the ID prefix checked
# absent from every existing manifest and unit). Every source cite is checked against the ledger's CITE INDEX before a byte is written.
import json, os, re, sqlite3, glob
ROOT = _ROOT
DATE = '2026-09-12'
UID = 'num_33_journeys'; PRE = 'MS33A'
db = sqlite3.connect(f'file:{ROOT}/torah_grok.SNAPSHOT-main-51801ca.sqlite?mode=ro', uri=True)
def cut(book, ch, v, word, nth=0):
    rows = db.execute("SELECT w.idx, w.he FROM words w JOIN verses v ON w.verse_id=v.id WHERE v.book=? AND v.chapter=? AND v.verse=? ORDER BY w.idx", (book, ch, v)).fetchall()
    plain = lambda h: ''.join(c for c in h if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
    hit = [(i, h) for i, h in rows if plain(h) == word]
    assert len(hit) > nth, (book, ch, v, word, hit)
    idx, he = hit[nth]
    piece = max(he.split('/'), key=len)
    assert len(piece) >= 4, (book, ch, v, word, he.split('/'))
    return idx, piece
def hc(ref, word, note, nth=0):
    b, cv = ref.split(' '); c, v = map(int, cv.split(':'))
    idx, sub = cut(b, c, v, word, nth)
    return {"type": "he_contains", "ref": ref, "idx": idx, "contains": sub, "note": note}
def onk(lo, hi): return '; '.join(f'Onkelos Num 33:{v}' for v in range(lo, hi + 1))

C = [
 {"id": "MS33A-01", "source": onk(1, 2), "ref": "Num 33:1-2",
  "claim_en": "THESE ARE THE JOURNEYS OF THE CHILDREN OF ISRAEL WHO WENT OUT OF THE LAND OF EGYPT BY THEIR HOSTS BY THE HAND OF MOSES AND AARON; AND MOSES WROTE THEIR GOINGS OUT BY THEIR JOURNEYS BY THE MOUTH OF THE LORD — THE HEADING OF 10:28 REPEATED, THE FOUR THINGS MOSES WROTE, THE CHIASM. 'These are the journeys of the children of Israel' — 10:28 (closing the march order) and 33:1, the same first four words; the verse-initial 'these' heading sixty-three times in the Torah; 'by their hosts' sixteen seats, every one in Numbers (Exodus 12:51 and 6:26 use another preposition); 'by the hand of Moses and Aaron' — 33:1 and Psalm 77:21, the phrase's two Bible seats ('by the hand of Moses' sixteen Torah seats); 'AND MOSES WROTE' four Torah seats — the covenant's words (Exodus 24:4), THE JOURNEYS, this Torah (Deuteronomy 31:9), this song (31:22); the verb's six Torah seats; 33:2's chiasm 'their goings out by their journeys ... their journeys by their goings out' ('their goings out' two Bible seats, 'their journeys' six — the cloud's stages); 'by the mouth of the LORD' twenty-one Bible seats, eighteen Torah, fifteen in Numbers — Moses wrote by it and Aaron went up by it (33:38); 33:7's 'mouth' Pi-hahiroth's, the homograph (computed). ONKELOS: 'by their armies', 'by the WORD of the LORD' at 33:2 and 33:38 (cut).",
  "middah": "ink (the heading's seats, the four writings, the phrase censuses computed)",
  "check": hc("Num 33:2", "ויכתב", "'and he wrote' — Moses' four writings; the store glosses 'and-grave'")},
 {"id": "MS33A-02", "source": onk(3, 4), "ref": "Num 33:3-4",
  "claim_en": "THEY JOURNEYED FROM RAMESES ON THE FIFTEENTH DAY OF THE FIRST MONTH, ON THE MORROW OF THE PASSOVER, WITH A HIGH HAND IN THE SIGHT OF ALL EGYPT, WHILE EGYPT WAS BURYING ITS FIRSTBORN AND THE LORD EXECUTED JUDGMENTS ON THEIR GODS — THE DEPARTURE'S DATE WRITTEN ONCE, THE RUN OF EXODUS 12:12 RECORDED ONLY HERE. 'On the fifteenth day of the first month' the full phrase one seat; 'on the fifteenth day of the month' six Bible seats; Leviticus 23:6 and 28:17 date the feast of unleavened bread on 'the fifteenth day of THIS month' — the departure's date is the feast's; Exodus 12 gives the fourteenth at evening and 'that selfsame day' (12:41, 51): 33:3 alone writes the fifteenth of the going out (the parser [15] with the ordinals [1, 1]); 'THE MORROW OF THE PASSOVER' two Bible seats — 33:3 (out of Egypt) and Joshua 5:11 (the land's produce first eaten, the manna ceasing on the morrow): the run's two ends on one date-word; 'the morrow' eleven Torah seats; 'WITH A HIGH HAND' three Torah seats (Exodus 14:8 the same going out; 15:30 the soul that acts with a high hand — the Sifrei 112:2's verse; 33:3), ONKELOS 'with bared head' at 15:30 and 33:3 alone and the Sifrei's own gloss on 15:30 'one who bares his face' the same root; 'in the sight of all Egypt' one seat; Rameses five Bible seats. 33:4: 'Egypt was burying' the participle's two Bible seats (Ezekiel 39:14); 'AND ON THEIR GODS THE LORD EXECUTED JUDGMENTS' one seat — THE RUN of Exodus 12:12's 'on all the gods of Egypt I will execute judgments' (the future at Exodus 12:12 and Ezekiel 25:11 alone; the perfect nowhere else): Exodus narrates the firstborn smitten (12:29) and never the judgments on the gods — the itinerary alone records that run (computed). ONKELOS: 'on their idols' — 25:2's word (cut).",
  "middah": "ink (the date phrases, the morrow's two seats, the high hand's three, the judgments' run computed)",
  "check": hc("Num 33:3", "ממחרת", "'on the morrow of' — the morrow of the Passover, two Bible seats with Joshua 5:11")},
 {"id": "MS33A-03", "source": onk(5, 15), "ref": "Num 33:5-15",
  "claim_en": "FROM RAMESES TO THE WILDERNESS OF SINAI — SUCCOTH, ETHAM, PI-HAHIROTH, THROUGH THE SEA, MARAH, ELIM, THE RED SEA, SIN, DOPHKAH, ALUSH, REPHIDIM, SINAI: THE STATIONS RETELL EXODUS ON THE TOKENS, AND THREE OF THEM EXODUS NEVER NAMES. 33:5 opens as Exodus 12:37 opens ('and the children of Israel journeyed from Rameses'), Exodus adding 'to Succoth' with the directional ending and the six hundred thousand; 33:6 IS EXODUS 13:20 with one word added ('in Etham WHICH IS in the edge of the wilderness' — six of seven tokens shared); 33:7 'and TURNED BACK to Pi-hahiroth' — Exodus 14:2's jussive 'let them turn back' fulfilled in the narrative form, the camp singular (computed on the morphology); Pi-hahiroth three seats, Baal-zephon plene here alone, Migdol's two Torah seats; 33:8 'PASSED THROUGH THE MIDST OF THE SEA into the wilderness' — Nehemiah 9:11 the phrase's one other seat; 'a way of three days in the wilderness of ETHAM' — Exodus 15:22 walks the same three days in the wilderness of SHUR (the two names one seat each: the itinerary's own name for Exodus's Shur); 'a way of three days' six Torah seats, Moses' request of Pharaoh (Exodus 3:18, 5:3, 8:23) walked after the sea; 33:9 Elim's twelve springs and seventy palms word for word with Exodus 15:27 (each phrase's two seats; the parser [12, 70] at both); 33:10 THE CAMP BY THE RED SEA — a station Exodus never names (the phrase one seat); 33:11 the wilderness of Sin (Exodus 16:1's dated camp — [15] with the ordinal [2]); 33:12-13 DOPHKAH AND ALUSH named nowhere else; 33:14 Rephidim 'and there was no water there for the people to drink' — Exodus 17:1's clause in another word order (each order one seat); Rephidim five seats, the itinerary's spelling defective with Exodus 17:8's, 17:1 and 19:2 plene; 33:15 'and camped in the wilderness of Sinai' one seat — Exodus 19:2 adds 'and Israel camped there' with the singular verb (computed).",
  "middah": "ink (every station's first telling compared on the tokens; the unnamed stations computed by their seats)",
  "check": hc("Num 33:8", "ויעברו", "'and they passed' — through the midst of the sea, the phrase's one Torah seat (Nehemiah 9:11 the other)")},
 {"id": "MS33A-04", "source": onk(16, 18), "ref": "Num 33:16-18",
  "claim_en": "FROM SINAI TO KIBROTH-HATTAAVAH, HAZEROTH AND RITHMAH — CHAPTER 11'S GRAVES AND THE SPIES' BASE UNDER ITS OTHER NAME. 33:16-17 Kibroth-hattaavah and Hazeroth are 11:34-35's ('from Kibroth-hattaavah the people journeyed to Hazeroth'); the name's four Torah seats (11:34, 35; 33:16, 17) and Deuteronomy 9:22's; Hazeroth's four (11:35, 12:16; 33:17, 18); 33:18 RITHMAH (two seats, here alone) where 12:16 says 'and camped in the wilderness of PARAN' — the itinerary's name for the camp 12:16 calls Paran, the spies' base (13:3 'from the wilderness of Paran', 13:26 'to the wilderness of Paran, to Kadesh') — the ink's two names; Taberah (11:3; Deuteronomy 9:22 with Massah and Kibroth-hattaavah) is NO station of the list (computed). ONKELOS renders Kibroth-hattaavah 'the graves of those who DEMANDED' at all four seats of the name in Onkelos Numbers (cut).",
  "middah": "ink (the names' seats and the two names of one camp computed; Onkelos's rendering counted on the whole book)",
  "check": hc("Num 33:18", "ברתמה", "'in Rithmah' — the station named nowhere else, 12:16's wilderness of Paran")},
 {"id": "MS33A-05", "source": onk(19, 35), "ref": "Num 33:19-35",
  "claim_en": "THE SEVENTEEN STATIONS FROM RIMMON-PEREZ TO EZION-GEBER — ELEVEN OF THE CHAPTER'S STATIONS ARE NAMED NOWHERE ELSE IN THE BIBLE, THREE ARE COMMON WORDS AS NAMES, FOUR ARE DEUTERONOMY 10:6-7'S IN ANOTHER ORDER WITH AARON'S DEATH PLACED ELSEWHERE. ELEVEN stations stand at their two verses alone — Dophkah, Alush, Rithmah, Rissah, Kehelathah, Makheloth, Mithkah, Hashmonah, Abronah, Zalmonah, Punon (computed by every form's seats); THREE names only here whose consonants are common words elsewhere — Mount SHEPHER (the ram's horn of Exodus 19:16), HARADAH ('trembling', Isaac's at Genesis 27:33), TAHATH ('under' — a place by the morphology at 33:26-27); RIMMON-PEREZ shares its first word with Naaman's 'house of Rimmon' (2 Kings 5:18), TERAH carries Abraham's father's name (Genesis 11's eight seats, Joshua 24:2, 1 Chronicles 1:26), LIBNAH a Judah city's (nineteen seats of the name); MOSEROTH, BENE-JAAKAN, HOR-HAGGIDGAD, JOTBATHAH are DEUTERONOMY 10:6-7's four (Moserah; Beeroth-bene-jaakan; Gudgodah; Jotbathah 'a land of brooks of water'); EZION-GEBER Deuteronomy 2:8's and Solomon's and Jehoshaphat's port (1 Kings 9:26, 22:49; 2 Chronicles 20:36). THE DEUTERONOMY DIVERGENCE, OBSERVED: Deuteronomy 10:6 runs 'from Beeroth-bene-jaakan to Moserah; THERE AARON DIED' — the itinerary puts Moseroth BEFORE Bene-jaakan (33:30-31) and Aaron's death at Mount Hor SEVEN camps on (33:30 to 33:37 by index); the declared shelf is silent on the two orders (computed).",
  "middah": "ink (the hapax stations computed by their seats; the divergence read off the tokens and counted by index; no row of the declared shelf)",
  "check": hc("Num 33:30", "במסרות", "'in Moseroth' — Deuteronomy 10:6's Moserah, where Deuteronomy places Aaron's death")},
 {"id": "MS33A-06", "source": onk(36, 37), "ref": "Num 33:36-37",
  "claim_en": "THE WILDERNESS OF ZIN, THAT IS KADESH, AND MOUNT HOR IN THE EDGE OF THE LAND OF EDOM — THE ITINERARY'S OWN GLOSS AND 20:22-23 RETOLD. 'That is Kadesh' — the identity clause at five Bible seats, Genesis 14:7's 'En-mishpat, that is Kadesh' the same idiom; the wilderness of Zin's seats (13:21, 20:1, 27:14, 34:3; Deuteronomy 32:51; Joshua 15:1); 'Mount Hor IN THE EDGE of the land of Edom' one seat beside 20:23's 'ON THE BORDER of the land of Edom' one seat; Mount Hor twelve Torah seats (computed). ONKELOS: REKEM for Kadesh at ten seats of Onkelos Numbers (13:26; 20:1, 14, 16, 22; 27:14; 32:8's Rekem Geah for Kadesh-barnea; 33:36, 37; 34:4) and the Hebrew's own Rekem, the Midianite king of 31:8, the eleventh; 'HOR THE MOUNTAIN' at 33:37-41 and 34:8 (cut).",
  "middah": "ink (the identity idiom's seats, the two prepositions, Onkelos's Rekem counted on the whole book)",
  "check": hc("Num 33:36", "מעציון", "'from Ezion-' — Ezion-geber, Solomon's port; the last departure before Kadesh")},
 {"id": "MS33A-07", "source": onk(38, 39), "ref": "Num 33:38-39",
  "claim_en": "AARON THE PRIEST WENT UP MOUNT HOR BY THE MOUTH OF THE LORD AND DIED THERE IN THE FORTIETH YEAR OF THE GOING OUT, IN THE FIFTH MONTH, ON THE FIRST OF THE MONTH, A HUNDRED AND TWENTY-THREE YEARS OLD — THE TORAH'S ONE FULL DEATH-DATE, THE TAPE'S OWN MARKER, THE INK'S CHECKSUM. The itinerary alone DATES the death — 20:28 has no number; the parser reads the year and the month as ORDINALS [40, 5] (the article-bearing numeral, rule 20 — the Torah's one seat of that form) and the day [1] = (40, 5, 1), and THE TAPE'S MARKER FOR AARON'S DEATH AT 20:28 IS BUILT FROM THIS VERSE (cold_run_sequence.py reads 33:38's ordinals and number into day_in; CM2 checks (40, 5, 1)): the reading's measurement equals the tape's marker; 'in the fortieth year' (the article form) two Bible seats (1 Chronicles 26:31 David's); 'OF THE GOING OUT of the children of Israel from the land of Egypt' three Bible seats — Exodus 19:1 (the third month, Sinai), 33:38 (the fortieth year, Mount Hor), 1 Kings 6:1 (the four hundred and eightieth year, the temple): the era's three stamps in that form; 'in the fifth month' the Torah's one seat; 'on the first of the month' ten Torah seats; Deuteronomy 1:3's 'in the fortieth year, in the eleventh month, on the first' is written in cardinal forms ([40, 11, 1] by the number reader); AARON'S 123 = Exodus 7:7's 83 + 40, Moses' 120 = 80 + 40 (Deuteronomy 34:7) — the brothers three years apart at both ends, by one parser; 'at his death' two Bible seats, Aaron's and Moses'; Deuteronomy 32:50 'as Aaron your brother died in Mount Hor' (computed). ONKELOS: 'by the WORD of the LORD'; 'in the year forty' the cardinal; the hundred first in the age (cut).",
  "middah": "ink (the date parsed and matched to the tape's marker; the era's stamps and the ages computed by the parser)",
  "check": hc("Num 33:38", "הארבעים", "'the fortieth' — the article-bearing year, the Torah's one seat; the tape's marker at 20:28")},
 {"id": "MS33A-08", "source": onk(40, 40), "ref": "Num 33:40",
  "claim_en": "AND THE CANAANITE KING OF ARAD, WHO DWELT IN THE NEGEV IN THE LAND OF CANAAN, HEARD OF THE COMING OF THE CHILDREN OF ISRAEL — 21:1'S HEARING WITHOUT ITS WAR, SET RIGHT AFTER AARON'S DEATH. 'And the Canaanite king of Arad heard' — 21:1 and 33:40 the phrase's two seats; Arad's four (Joshua 12:14 among the thirty-one kings, Judges 1:16); the itinerary keeps the HEARING and drops the war, the captives, the vow and Hormah (21:1-3), adds 'in the land of Canaan' (computed on the tokens); its place is right after Aaron's death and age (33:38-39) — the Sifrei's row on 21:1 (82:1, on 10:33, read at sitting 3: 'when Aaron died they said, their high priest has died, their great scout is gone') reads the hearing as the news of that death — 33:38-40's own order is the ink that reading stands on (OBSERVED; not a row on 33).",
  "middah": "ink (the two tellings compared on the tokens; the Sifrei's reading named as an observation on the chapter's order)",
  "check": hc("Num 33:40", "הכנעני", "'the Canaanite' — the king of Arad's hearing, 21:1's phrase at its second seat")},
 {"id": "MS33A-09", "source": onk(41, 49), "ref": "Num 33:41-49",
  "claim_en": "FROM MOUNT HOR TO THE PLAINS OF MOAB — ZALMONAH, PUNON, OBOTH, IYE-ABARIM, DIBON-GAD, ALMON-DIBLATHAIM, THE MOUNTAINS OF ABARIM, THE PLAINS OF MOAB FROM BETH-JESHIMOTH TO ABEL-SHITTIM: THE LAST STATIONS AGAINST CHAPTER 21, AND THE FORTY-TWO ON THE INK'S OWN COUNT. Zalmonah and Punon named here alone (21:4 leaves Mount Hor 'to compass Edom' and names no camp before Oboth); OBOTH and IYE-ABARIM are 21:10-11's ('in the wilderness before Moab toward the sunrise' there, 'in the border of Moab' here); of chapter 21's stations after Iye-abarim (the Zered, beyond the Arnon, Beer, Mattanah, Nahaliel, Bamoth, the valley of Pisgah) NOT ONE is in the itinerary, and its Dibon-gad, Almon-diblathaim and the mountains of Abarim are not in 21 — the two lists share Oboth, Iye-abarim and Moab's name alone (the name-tokens intersected); 'from Iim' the short form's one seat; DIBON-GAD two seats — Gad built Dibon (32:34), the itinerary's witness to chapter 32; Almon-diblathaim two seats, Jeremiah 48:22's Beth-diblathaim Moab's; 'the MOUNTAINS of Abarim before Nebo' (plural, 33:47-48) beside 'the MOUNTAIN of Abarim' (27:12; Deuteronomy 32:49); 'the plains of Moab' eight Torah seats, 'by the Jordan at Jericho' seven; 33:49 the last camp's extent — Beth-jeshimoth Reuben's (Joshua 13:20) and Moab's glory (Ezekiel 25:9), Abel-shittim one seat, Shittim Peor's (25:1), the spies' and the crossing's (Joshua 2:1, 3:1), Micah's 'from Shittim to Gilgal'. THE FORTY-TWO: forty-two 'journeyed' and forty-two 'camped' tokens in the chapter — the first departure (Rameses, 33:3 and 33:5) and the last camp (the plains of Moab, 33:48 and 33:49) each told twice: forty-two places, Rameses and forty-one camps (thirty-three at 33:5-37, eight at 33:41-48); ninety-three narrative verbs in forty-seven verses, one divine frame (33:50) (computed). ONKELOS: 'the plains' one word at eight seats, 'the plain of Shittim', 'the fords of the Abarim' (cut).",
  "middah": "ink (the two lists intersected on the name-tokens; the verb counts and the places computed; the seats of every name)",
  "check": hc("Num 33:45", "בדיבן", "'in Dibon-' — Dibon-gad, the city Gad built at 32:34, the itinerary's witness")},
 {"id": "MS33A-10", "source": onk(50, 53), "ref": "Num 33:50-53",
  "claim_en": "AND THE LORD SPOKE TO MOSES IN THE PLAINS OF MOAB BY THE JORDAN AT JERICHO: WHEN YOU PASS OVER THE JORDAN INTO THE LAND OF CANAAN, YOU SHALL DRIVE OUT ALL THE INHABITANTS OF THE LAND, DESTROY THEIR FIGURED STONES AND THEIR MOLTEN IMAGES AND DEMOLISH THEIR HIGH PLACES, AND POSSESS THE LAND AND DWELL IN IT — THE CHAPTER'S ONE FRAME, THREE OBJECTS OF ITS OWN, AND LEVITICUS 26'S CURSE ON THE THIRD. The frame 'and the LORD spoke to Moses in the plains of Moab by the Jordan at Jericho' — 33:50 and 35:1, the formula's two seats; 'when you pass over the Jordan' — 33:51, 35:10 (the refuge cities' head), Deuteronomy 11:31; 'you shall drive out all the inhabitants of the land from before you' one seat, 'the inhabitants of the land' five Torah seats (Exodus 23:31's promise among them); 'their FIGURED STONES' — Leviticus 26:1's 'figured stone' the noun's other Torah seat (Psalm 73:7 a plural form); 'their MOLTEN IMAGES' one seat (the calf's 'molten'); 'their HIGH PLACES you shall DEMOLISH' — Leviticus 26:30's curse 'I will demolish your high places' the same verb on the same object, the command and its curse (the verb's form two Bible seats; 'their high places' the consonants of 'at their death', Leviticus 11:31-32, told by the points and the morphology); Exodus 23:24, 34:13, Deuteronomy 7:5 and 12:2-3 name OTHER objects (altars, pillars, asherim, graven images) — 33:52's three are its own; 33:53 'dwell in it' Deuteronomy 11:31's, 'to possess it' Leviticus 20:24's (computed). ONKELOS: 'their houses of worship' for the figured stones (31:10's word); at 33:53 'drive out THE INHABITANTS of the land' where the Hebrew has 'possess the land' — the object supplied from 33:52 (cut).",
  "middah": "ink (the frame's and the case head's seats, the three objects' seats against the other iconoclasm commands, the curse's verb computed)",
  "check": hc("Num 33:52", "תשמידו", "'you shall demolish' — their high places; Leviticus 26:30's curse in the same verb")},
 {"id": "MS33A-11", "source": onk(54, 54), "ref": "Num 33:54",
  "claim_en": "YOU SHALL INHERIT THE LAND BY LOT ACCORDING TO YOUR FAMILIES: TO THE MANY YOU SHALL INCREASE HIS INHERITANCE AND TO THE FEW DIMINISH HIS INHERITANCE; TO WHOM THE LOT GOES OUT, HIS IT SHALL BE; BY THE TRIBES OF YOUR FATHERS YOU SHALL INHERIT — 26:52-56 RESTATED TO THE PEOPLE, THE VERB'S NUMBER SWITCHING INSIDE THE VERSE. 26:54's clause with the first verb turned PLURAL and the object marker added (26:54 'you shall increase', singular, to Moses; 33:54 'you [all] shall increase'), the second verb LEFT SINGULAR in both — the number switches inside 33:54's own verse (computed on the morphology); 'by lot' four Torah seats (26:55, 33:54, 34:13, 36:2); 'to whom the lot goes out, his it shall be' one seat; 'by the tribes of your fathers' one seat (26:55 'their fathers'); 'you shall inherit' (the closing stem) 33:54, 34:13, Ezekiel 47:13; the opening verb 'take as inheritance' Leviticus 25:46's (the slaves held as a possession) and this (computed). ONKELOS renders 26:54 and 33:54 with one pair of verbs (both plural in the Aramaic), 'lot' with one word at all five seats (26:55, 56; 33:54; 34:13; 36:2) (cut).",
  "middah": "ink (the two verses compared on the morphology; the lot's seats; Onkelos's verbs at both)",
  "check": hc("Num 33:54", "והתנחלתם", "'and you shall take as inheritance' — Leviticus 25:46's verb on the land; the store glosses the lot 'in-pebble'")},
 {"id": "MS33A-12", "source": onk(55, 56), "ref": "Num 33:55-56",
  "claim_en": "AND IF YOU DO NOT DRIVE OUT THE INHABITANTS OF THE LAND FROM BEFORE YOU, THOSE YOU LEAVE OVER SHALL BE THORNS IN YOUR EYES AND PRICKS IN YOUR SIDES AND THEY SHALL HARASS YOU; AND AS I THOUGHT TO DO TO THEM I WILL DO TO YOU — THE NEGATIVE ARM, RUN BACK REVERSED BY JOSHUA 23:13, READ BY ONKELOS AS ARMED BANDS. 'If you do not drive out' the form's one seat; 'leave over' three Torah seats (the Passover's 'leave none until morning', Exodus 12:10; Leviticus 22:30; this); 'thorns' one seat; 'pricks' and 'in your sides' each two — the other Joshua 23:13, which runs the pair back REVERSED ('scourges in your sides and pricks in your eyes'); Judges 2:3 'they shall be to you for sides'; 'they shall harass you' the form's one seat (25:18's 'they harass you' Midian's); 'as I thought' Isaiah 14:24's oath against Assyria and this, the phrase's two seats (computed). ONKELOS reads the figure as its referent — 'bands TAKING UP ARMS against you and camps SURROUNDING you' (one seat in Onkelos Numbers); 'as I PLANNED' (cut).",
  "middah": "ink (the arm's words censused; Joshua's reversal read on the tokens; Onkelos's expansion counted on the whole book)",
  "check": hc("Num 33:55", "ולצנינם", "'and as pricks' — in your sides; Joshua 23:13's word, reversed with the eyes")},
]
out = f'{ROOT}/logic/oral_audit/manifests/{UID}_claims.json'
assert not os.path.exists(out), out
for f in glob.glob(f'{ROOT}/logic/oral_audit/manifests/*_claims.json') + glob.glob(f'{ROOT}/logic/units/*.yaml'):
    assert f'{PRE}-' not in open(f, encoding='utf-8').read(), (PRE, f)
led = open(f'{ROOT}/logic/oral_triage/{UID}_{DATE}.md', encoding='utf-8').read().split('## CITE INDEX')[1]
CI = set(re.findall(r'^(Onkelos Num \d+:\d+)$', led, re.M))
for c in C:
    assert c['id'].startswith(PRE) and c['middah'] and c['check']['contains'], c['id']
    for s in c['source'].split('; '): assert s in CI, (c['id'], s)
assert [c['id'] for c in C] == [f'{PRE}-{i:02d}' for i in range(1, len(C) + 1)] and len(CI) == 56
covered = sorted({int(s.split(':')[1]) for c in C for s in c['source'].split('; ')})
assert covered == list(range(1, 57)), 'every verse of the chapter cited by some claim'
json.dump(C, open(out, 'w', encoding='utf-8'), ensure_ascii=False, indent=1); open(out, 'a', encoding='utf-8').write('\n')
print(f'{UID}: {len(C)} claims ({PRE}) -> {out}; cite index {len(CI)}; checks {[c["check"]["contains"] for c in C]}')
