import os as _os
_ROOT = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..', '..', '..'))   # THE PORTABLE REPO (2026-09-15): the repo root from this file's own place
#!/usr/bin/env python3
# THE NUMBERS WALK sitting 3 — BEHA'ALOTCHA (2026-09-10): THE CLAIMS of Numbers 8:1-26 and 10:1-12:16, four manifests (one per draft
# unit), read off the four ledgers of this sitting, every claim LABELED (World/step9/CLAIM_LABELS.md's vocabulary), a machine check
# where the ink allows — every he_contains substring CUT FROM THE SNAPSHOT STORE'S OWN BYTES by the word's CONSONANTS (sitting 2's
# form, write_naso_manifests.py). Claim IDs per unit: BH08A (the lamps and the Levites), BH10A (the trumpets and the march),
# BH11A (Taberah, the elders, the quail), BH12A (Miriam). Written once (the files must not exist). Every source cite is checked
# against its ledger's CITE INDEX before a byte is written.
import json, os, re, sqlite3
ROOT = _ROOT
DATE = '2026-09-10'
UNITS = {'num_08_menorah_levites': 'BH08A', 'num_10_trumpets_depart': 'BH10A', 'num_11_complaint_quail': 'BH11A', 'num_12_miriam': 'BH12A'}
OUT = {u: f'{ROOT}/logic/oral_audit/manifests/{u}_claims.json' for u in UNITS}
for o in OUT.values(): assert not os.path.exists(o), o
CI = {}
for u in UNITS:
    led = open(f'{ROOT}/logic/oral_triage/{u}_{DATE}.md', encoding='utf-8').read().split('## CITE INDEX')[1]
    CI[u] = set(re.findall(r'^(Sifrei Bamidbar \d+:\d+|Onkelos Num \d+:\d+)$', led, re.M))
assert sum(len(v) for v in CI.values()) == 164, {u: len(v) for u, v in CI.items()}
db = sqlite3.connect(f'file:{ROOT}/torah_grok.SNAPSHOT-main-51801ca.sqlite?mode=ro', uri=True)
def cut(book, ch, v, word, n, nth=0):
    rows = db.execute("SELECT w.idx, w.he FROM words w JOIN verses v ON w.verse_id=v.id WHERE v.book=? AND v.chapter=? AND v.verse=? ORDER BY w.idx", (book, ch, v)).fetchall()
    plain = lambda h: ''.join(c for c in h if c != '/' and not (0x0591 <= ord(c) <= 0x05C7))
    hit = [(i, h) for i, h in rows if plain(h) == word]
    assert len(hit) > nth and (len(hit) == 1 or nth is not None), (book, ch, v, word, hit)
    idx, he = hit[nth]
    piece = max(he.split('/'), key=len)
    n = min(len(piece), max(n, 6))
    return idx, piece[:n]
def hc(ref, word, n, note, nth=0):
    b, cv = ref.split(' '); c, v = map(int, cv.split(':'))
    idx, sub = cut(b, c, v, word, n, nth)
    return {"type": "he_contains", "ref": ref, "idx": idx, "contains": sub, "note": note}
def onk(c, lo, hi): return '; '.join(f'Onkelos Num {c}:{v}' for v in range(lo, hi + 1))
def sif(*rows): return '; '.join(f'Sifrei Bamidbar {r}' for r in rows)

C = {}
C['num_08_menorah_levites'] = [
 {"id": "BH08A-01", "source": sif('59:1') + '; ' + onk(8, 2, 3), "ref": "Num 8:2-3",
  "claim_en": "THE LAMPS FACE THE MIDDLE. 'Toward the face of the lampstand shall the seven lamps light' (8:2; the clause at 8:2-3 alone, the lampstand plene at both — computed): the Sifrei reads the six lamps turned to the central shaft — three north, three south, one in the middle, 'the middle one is honored' (R. Nathan) — against Exod 25:37's 'across its face'; 'when you raise' — an ascent of steps; 'from evening to morning' bounds the lighting (Lev 24:3), and the western lamp burns continually (Lev 24:2), the others kindled from it; Onkelos renders the raising as KINDLING at 8:2 and 8:3. The exam: Menachot 98b; Shabbat 22b; Mishnah Tamid 3:9.",
  "middah": "plain (the Sifrei's geometry read off 'toward the face'; the seats computed; the translation's verb read as it stands)",
  "check": hc("Num 8:2", "המנורה", 6, "'the lampstand' — plene, the face the lamps turn to")},
 {"id": "BH08A-02", "source": sif('60:1') + '; ' + onk(8, 3, 3), "ref": "Num 8:3",
  "claim_en": "AARON DID NOT CHANGE; THE SONS EQUATED WITH THE FATHER BY THE THREE-FACET PARADIGM. 'And Aaron did so' (the clause's one seat with his name — computed): his praise, no change; 'as the LORD commanded' — half a log per lamp (the data channel's measure); the sons equated with the father for the lampstand by Lev 24:3, and for the INCENSE by a paradigm of THREE shared terms — service in the tent, golden vestments, 'continually' — the refutations (Yom Kippur's linen; the anointed priest's bull without 'continually') answered by the count: 'I learn from a thing similar in three ways, not in one or two' — the three-facet rule stated a second time (Naso's 6:1 the first; MIDDOT.md).",
  "middah": "I3 (the paradigm graded by shared facets — the Sifrei's own statement of the rule's strength)",
  "check": hc("Num 8:3", "ויעש", 6, "'and he did' — Aaron's unchanged doing")},
 {"id": "BH08A-03", "source": sif('61:1') + '; ' + onk(8, 4, 4), "ref": "Num 8:4",
  "claim_en": "BEATEN FROM THE BAR — WHAT IS VALID FOR THE LAMPSTAND IS INVALID FOR THE TRUMPETS. 'Beaten work of gold, from its base to its flower it is beaten' — the word twice in the verse, at the Torah's eight seats (the cherubim, the lampstand ×4, the trumpets — computed): the Sifrei reads the restatement as INVALIDATING fragments — because the trumpets may be of fragments — and sets the table: the lampstand of silver, iron or lead if no gold (Rebbi; even wood, R. Yehudah), never fragments; the trumpets silver only, fragments allowed — a 2×2 verdict table (material / one piece) inverted between the vessels (the exam's Menachot 28a-b); 'beaten' read as an acronym 'from the hard bar' (E30); the lamps and tongs from the talent but not from the piece (Exod 25:39); 'as the vision He showed' (one seat) — the finished vessels shown. Onkelos 'DRAWN gold', 'to its lily'.",
  "middah": "plain (the Sifrei's verdict table read as it stands; the seats computed; E30 in the note)",
  "check": hc("Num 8:4", "מקשה", 6, "'beaten' — the first of the verse's two", nth=0)},
 {"id": "BH08A-04", "source": onk(8, 6, 15), "ref": "Num 8:6-15",
  "claim_en": "THE LEVITES' RITE ON THE TRANSLATION ALONE. The Sifrei has NO ROW on 8:5-23 (computed by position: 61 on 8:4, 62 on 8:24); Onkelos carries the rite: 'take' → 'BRING NEAR' (8:6, the offering verb); 'water of purification' (one seat; chapter 19 calls the heifer's water 'a purification', 19:9) → 'water of the sin-offering'; the razor (its two Torah seats — the nazirite's 6:5 and here) → 'shears'; the people LAY HANDS on the Levites (8:10) and the Levites on the bulls (8:12) — the offerer's act on men; the waving rendered LIFTING at 8:11, 8:13, 8:15 (and the run's 8:21) — Naso's rendering again, the wave-noun at four seats (computed); 'the Levites shall be Mine' → 'SERVING before Me' (8:14 — a verb inserted, cut from the shelf's bytes); the two bulls with their two subjects kept (8:8). The exam: Menachot 61b-62a; Chullin 24a.",
  "middah": "ink (the translation's renderings and insertions cut from the shelf's bytes; the seats computed; the shelf's silence measured)",
  "check": hc("Num 8:11", "תנופה", 6, "'a wave offering' — the Levites waved")},
 {"id": "BH08A-05", "source": onk(8, 16, 19), "ref": "Num 8:16-19",
  "claim_en": "GIVEN, GIVEN AT TWO SEATS — THE SECOND SEAT'S DELTA. The doubled word stands at 3:9 (spelled with the vav, 'to HIM' — Aaron) AND at 8:16 (spelled with the yod, 'to ME' twice); single at 8:19 and 18:6 (computed on the DB's bytes): the second writing moves the spelling and the person — the Levites given to Aaron at the first seat, to the LORD at the second; Onkelos renders 3:9's pair by two verbs ('handed over, given') and 8:16's by one verb doubled ('separated, separated'), and 8:19's single 'given' by 3:9's 'handed over'; 'instead of the opening of every womb' — the feminine form at 8:16 alone of the eight womb-opener seats; 'I smote' → 'I KILLED' (8:17), 'plague' → 'DEATH' (8:19). THE CORRECTION: the Bamidbar ledger's row on 3:9 and claim NM03A-03 had called 8:16's 'given' single — corrected this sitting (appended to num_03's ledger; the claim amended and the unit re-ritualed).",
  "middah": "M-23 (the second seat's delta — spelling and person diffed seat against seat)",
  "check": hc("Num 8:16", "נתנים", 6, "'given' — the first of the doubled pair at the second seat", nth=0)},
 {"id": "BH08A-06", "source": onk(8, 14, 19), "ref": "Num 8:14, 8:17, 8:19",
  "claim_en": "'UNTO ME' IS FOREVER — TEN SEATS ON THE INK; THE CHILDREN OF ISRAEL FIVE TIMES. The Sifrei's rule at 11:16 ('gather unto Me' — its row 92:1 read in num_11_complaint_quail's ledger, this claim's neighbor): wherever 'unto Me' is written it is forever — the priests (Exod 28:41), the Levites (8:14), Israel (Lev 25:55), the firstborn (8:17), the sanctuary (Exod 25:8), the altar (Exod 20:24), the anointing oil (Exod 30:31), the kings (1 Sam 16:1), the offerings (28:2) — a lexical rule with ten proof-seats, EVERY ONE machine-checked on the ink (computed); and 8:19 writes 'the children of Israel' FIVE TIMES in one verse (one with the prefixed 'among' — computed), the ink's own count, no teaching attached on this shelf.",
  "middah": "plain (the shelf's lexical rule with its proof-seats verified; the count of 8:19 computed)",
  "check": hc("Num 8:19", "בבני", 6, "'among the children of' — the fifth mention, prefixed")},
 {"id": "BH08A-07", "source": sif('62:1', '63:1') + '; ' + onk(8, 24, 26), "ref": "Num 8:24-26",
  "claim_en": "THE LEVITE AGE IS A THREE-SETTING PARAMETER, AND THE RUN REWRITES IT. Twenty-five at 8:24 alone; thirty at chapter 4's seven seats (and 1 Chr 23:3); TWENTY at 1 Chr 23:24, 23:27, 2 Chr 31:17, Ezra 3:8 — every number read by the engine's parser (computed); the Sifrei (62:1, CREDITED — read at num_04_kehat's ledger) reconciles the Torah's two: twenty-five to learn, thirty to serve (the exam's Chullin 24a); 63:1: from fifty he returns to the gates and Gershon's service — 'and serve with his brothers' (one seat) — and in the Temple VOICE, not years, disqualifies; years disqualify Levites, not priests (the mirror a-fortiori refused by 'thus with the Levites'); and CHRONICLES GIVES ITS OWN REASON for the third setting in the ink — 'the Levites need no longer CARRY the tabernacle' (1 Chr 23:26): the burden clause of Num 4 lapsed at the Temple and David's count dropped the age. The flow reversed: a later book's run re-sets the spec's parameter.",
  "middah": "plain (the Sifrei's reconciliation read as it stands; the three settings computed by the parser; Chronicles' reason read off its own verse)",
  "check": hc("Num 8:24", "ועשרים", 6, "'and twenty' — the twenty-five of the Levites' entry")},
]
C['num_10_trumpets_depart'] = [
 {"id": "BH10A-01", "source": sif('72:1', '73:1') + '; ' + onk(10, 2, 4), "ref": "Num 10:2-4",
  "claim_en": "TWO TRUMPETS, BEATEN, BESIDE THE CLOUD; THE WORD SPELLED THREE WAYS. 'Make for yourself two trumpets of silver' — the Sifrei: trumpets are needed even though 9:23 moves the camp by the Word (two verses, both kept); 'for yourself' from what is yours; TWO — not more, not less, alike in look, height and beauty; 'beaten' a solid bar; the two offices — calling the congregation, journeying the camps (the clause's one seat); both trumpets for the congregation, one for the princes — to the door by induction (I3), and the princes addressed first everywhere (Num 30:2); THE INK: the trumpet-word spelled three ways in the chapter (10:2; 10:8-9; 10:10 — computed), the construct 'two of' the parser's gap again (10:2 → []), Onkelos writing the two ('two trumpets') and 'drawn' for beaten.",
  "middah": "ink (the three spellings and the parser's gap computed; the Sifrei's fixed count read as it stands)",
  "check": hc("Num 10:2", "חצוצרת", 6, "'trumpets' — the chapter's first spelling")},
 {"id": "BH10A-02", "source": sif('73:2', '73:3', '74:1') + '; ' + onk(10, 5, 7), "ref": "Num 10:5-7",
  "claim_en": "TEKIAH AND TERUAH ARE TWO SOUNDS; TEKIAH-TERUAH-TEKIAH; ROSH HASHANAH BY THE IDENTITY; THE TERUAH IS A WAIL. From 10:7 'blow, and not a teruah' the plain sound and the broken sound are distinct; tekiah precedes ('blow a teruah'), a tekiah follows — from the superfluous 'SECOND' of 10:6 as a prototype (I3); and Rosh Hashanah by 'teruah' here / 'teruah' there (I2): tekiah-teruah-tekiah for the day's three written teruot — nine sounds, the Torah's and the scribes' split a two-setting parameter (the exam's Rosh Hashanah 33b-34a); the north and the west one set or three (73:3); the assembly with tekiah only (74:1). THE INK: the blow-verb eight tokens and the teruah-word five in 10:3-10 (computed); Onkelos renders the teruah as a WAIL at 10:5, 10:7, 10:9 (cut from the shelf's bytes) — the very rendering the exam uses to fix the sound (Rosh Hashanah 33b on the Targum of Judg 5:28): the translation layer load-bearing again.",
  "middah": "I2 (the identity 'teruah'/'teruah' carrying the desert's blasts to Rosh Hashanah; I3 on 'second' in the note)",
  "check": hc("Num 10:6", "שנית", 6, "'second' — the superfluous word the prototype is built on")},
 {"id": "BH10A-03", "source": sif('75:1') + '; ' + onk(10, 8, 8), "ref": "Num 10:8",
  "claim_en": "THE PRIESTS BLOW — TARFON SAW AND FORGOT, AKIVA EXPOUNDED; THE TRUMPETS NOT FOR THE GENERATIONS. 'The sons of Aaron the priests shall blow' — not Israelites; blemished too (R. Tarfon) or whole only (R. Akiva — 'priests'/'priests' with Lev 3:2, I2); R. Tarfon's TESTIMONY — his lame uncle blowing — answered by R. Akiva: on Rosh Hashanah or the Jubilee's Yom Kippur, the shofar, not the trumpets — 'Tarfon saw and forgot; Akiva expounded of himself and matched the halakhah': a witnessed memory yields to a derivation that reconstructs the forgotten day (the tradition's own memory failure and repair, as at Shevuot 20b); 'for YOU a statute forever' (the clause with its lamed one seat — computed) — a statute, not an heirloom: every vessel Moses made served the generations EXCEPT the trumpets (the exam's Menachot 28b).",
  "middah": "I2 (the identity 'priests'/'priests' deciding the blemished; the memory-repair recorded as the middot's case law in the note)",
  "check": hc("Num 10:8", "לחקת", 6, "'for a statute' — read for you, not the generations")},
 {"id": "BH10A-04", "source": sif('76:1', '77:1') + '; ' + onk(10, 9, 10), "ref": "Num 10:9-10",
  "claim_en": "WAR AND ANY OPPRESSION; THE DAYS OF GLADNESS; A REMEMBRANCE, NOT A VALIDATION; KINGSHIP FROM 'I AM THE LORD'. 'War in your land' — attacking or attacked; 'against the oppressor' — R. Akiva: blast, mildew, hard labor, ships in a tempest (the fast-day trumpets — Mishnah Taanit 3); 'remembered' — as if not remembered if they could blow and did not (Onkelos inserts 'FOR GOOD'); 'the day of your gladness' (one seat — computed) the Sabbaths or the daily offerings, 'your festivals' the three, 'your appointed times' Rosh Hashanah and Yom Kippur; over COMMUNAL peace offerings by context; the trumpets a remembrance — the offering stands without them; 'I am the LORD your God' — the KINGSHIP-verses' seat: with Lev 23:24's remembrance and shofar verses the liturgy's three blessings derived on the trumpets' verse, kingship first (the exam's Rosh Hashanah 32a).",
  "middah": "plain (the Sifrei's readings of each clause recorded; the liturgy derivation the third stratum at a Numbers seat)",
  "check": hc("Num 10:10", "שמחתכם", 6, "'your gladness' — the day's one seat")},
 {"id": "BH10A-05", "source": onk(10, 11, 13), "ref": "Num 10:11-13",
  "claim_en": "THE DATE 10:11 — THE TAPE'S NEXT FORWARD MARKER. 'In the second year, in the second month, on the twentieth of the month the cloud lifted' — the parser reads 20 (computed): the exodus era's (2, 2, 20), nineteen days after 1:1's (2, 2, 1), fifty days after the erection; the whole of 1:1-10:10 sits inside twenty days of tape with 7:1 and 9:5 running backward before it — the compile's stamp; 'by their journeys' (four seats) from Sinai to Paran (10:12 — the arrival written again at 12:16); 'at the first, by the mouth of the LORD by the hand of Moses' — the formula's seats 4:37, 4:45, 9:23, 10:13 and Joshua 22:9 (4:49 splits it — computed), rendered by the WORD (the Memra), the formula the Sifrei 84:5 names as the cloud-and-Moses reconciliation.",
  "middah": "ink (the date parsed from the ink's numerals; the formula's seats computed)",
  "check": hc("Num 10:11", "בעשרים", 6, "'on the twentieth' — the march's date")},
 {"id": "BH10A-06", "source": onk(10, 14, 28), "ref": "Num 10:14-28",
  "claim_en": "THE MARCH RUNS THE CAMP'S ORDER A THIRD TIME, WITH FOUR FATHERS SPELLED OTHERWISE. The twelve princes of 10:14-27 stand in 2:3-31's order = 7:12-83's (Judah, Issachar, Zebulun, Reuben, Simeon, Gad, Ephraim, Manasseh, Benjamin, Dan, Asher, Naphtali — computed; the census list of 1:5-15 differs); against chapter 1 four fathers are spelled otherwise here — Helon and Gideoni with the vav (10:16, 10:24 alone), Zuri-shaddai split in two (10:19 as at 2:12), Pedah-zur split (10:23 as at 7:54, 7:59) — and Deuel keeps the dalet (the resh at 2:14 alone); 'the standard of the camp' at eight Torah seats, four here; 'and over its host' twelve times; the Levites' places: Gershon and Merari between the first two standards with the tabernacle DISMANTLED (10:17, one seat), Kohath after the second, the frame raised 'until their coming' (10:21, one seat); Dan 'the gatherer of all the camps' — Joshua's word for Jericho's rearguard; 'these are the journeys' shared with the itinerary's heading 33:1. Onkelos renders the standard by a Greek ORDER (taxis).",
  "middah": "ink (the order and the spellings computed seat against seat; the translation's loanword read as it stands)",
  "check": hc("Num 10:16", "חלון", 6, "'Helon' — with the vav, this seat alone")},
 {"id": "BH10A-07", "source": sif('78:1', '78:3', '79:1', '80:1', '81:1') + '; ' + onk(10, 29, 32), "ref": "Num 10:29-32",
  "claim_en": "HOBAB IS THE FATHER-IN-LAW, REUEL THE GRANDFATHER; EYES FOR US; THE PROSELYTE'S A-FORTIORI. Judg 4:11 decides the name (Hobab at two seats; 'Moses' father-in-law' at nine — computed): 'Reuel their father' (Exod 2:18) is the grandfather, children calling him father; the seven names expounded, the judges credited to Jethro (Exod 18:21 — 'were these not known from Sinai?'); THE A-FORTIORI (I1): if the proselytes who drew near were drawn near — Rahab, the Gibeonites, Ruth, the midwives — how much more Israel who do His will; 'we are journeying' (one seat) — why Moses included himself (three readings); proselytes have no portion in the land; 'do not leave us' (80:1 — the row on 10:31, its head mistyped '10:30'): 'na' implores; 'you shall be eyes for us' (one seat) → Onkelos 'the mighty deeds done for us you SAW with your eyes' — the metaphor unfolded, the Sifrei's reading in the translation's clause; the Jericho plot 500 by 500 held by his sons (81:1 — the export's '418' for 1 Kgs 6:1's 480, the shelf's text).",
  "middah": "I1 (the a-fortiori of the drawn-near proselyte; the identification by the cross-book seat read as it stands)",
  "check": hc("Num 10:31", "לעינים", 6, "'for eyes' — the clause Onkelos unfolds")},
 {"id": "BH10A-08", "source": sif('82:1', '83:1', '83:2', '83:3') + '; ' + onk(10, 33, 34), "ref": "Num 10:33-34",
  "claim_en": "THE ARK SPIES BEFORE THE SPIES DO; THREE DAYS IN ONE; THE SEVEN CLOUDS A FOUR-SETTING PARAMETER. 'A journey of three days' twice in the verse (seven Torah tokens — computed) against Deut 1:2's eleven: they went three days in one, the Shekhinah before them; the ark before them is the ark of the BROKEN tablets (14:44's stays in the camp); 'to spy out a resting place' — THE INK'S OWN VERB: the ark's 'to spy out' (10:33) is the spies' verb of chapters 13-14 (six seats) and Deut 1:33's 'to seek you out a place' (eight seats — computed); R. Shimon b. Yochai: the spies' request a degradation — 'I looked out the way for you'; Onkelos 'to PREPARE' and 'the mountain on which the glory of the LORD was revealed' for 'the mountain of the LORD' (seven seats); 'the cloud of the LORD' at its two seats (Exod 40:38, here) — the Sifrei's SEVEN CLOUDS from seven verses, or thirteen, four, two: a parameter with four settings; over the lame and the lepers; by day not night.",
  "middah": "plain (the Sifrei's rows read as they stand; the verb's seats and the clouds' verses computed)",
  "check": hc("Num 10:33", "לתור", 6, "'to spy out' — the spies' verb on the ark")},
 {"id": "BH10A-09", "source": sif('84:1', '84:2', '84:3', '84:5') + '; ' + onk(10, 35, 36), "ref": "Num 10:35-36",
  "claim_en": "THE SIGNS — A BOOK IN ITSELF WITH EIGHTY-FIVE LETTERS; TWO VERSES RECONCILED BY A MODEL; THE SHEKHINAH ON TWENTY-TWO THOUSAND. An inverted nun stands after 10:34 and after 10:36 on the Tanakh DB and the XML (nine in the Bible with Psalm 107's seven; the snapshot store carries none — computed): Rebbi — a book in itself, whence a scroll with EIGHTY-FIVE letters left defiles the hands (Shabbat 115b-116a; Mishnah Yadayim 3:5) — AND THE INK PROVES THE NUMBER: 10:35-36 have exactly 85 letters (computed); R. Shimon — not its place (after 10:33, before 11:1's complaint); 'Rise, LORD' against 9:23's 'by the word' reconciled by a MODEL (the cloud folded until Moses spoke; the king and his lover) — two verses without a third; 'by the mouth of the LORD by the hand of Moses' named as the reconciliation; 'Rest, LORD among the myriads of the thousands' — the Shekhinah rests on two myriads and two thousands (Ps 68:18): 22,000 read off two plural nouns the parser leaves silent (10:36 → []; the Levites' 22,000 the same number — the exam's Yevamot 64a); 'Rise, LORD' at eight seats, Ps 68:2 quoting the song; Onkelos 'REVEAL YOURSELF' and 'dwell in Your glory'.",
  "middah": "ink (the signs and the letter count measured on the DB; the Sifrei's rows read as they stand; the model-reconciliation in the note beside I13)",
  "check": hc("Num 10:35", "בנסע", 6, "'when [the ark] journeyed' — the section's first word")},
 {"id": "BH10A-10", "source": sif('84:4') + '; ' + onk(10, 35, 35), "ref": "Num 10:35",
  "claim_en": "THE HATERS OF THE RIGHTEOUS ARE HIS HATERS; SCRIPTURE'S EUPHEMISMS INCLUDE TWO OF THE PORTION'S VERSES. 'Your haters' — those who hate the righteous, as it were (Exod 15:7; Ps 74, 83, 139); 'the pupil of HIS eye' (Zech 2:12) — Scripture's euphemism, and the list: Job 7:20, Ezek 8:17, Hab 1:12, Ps 106:20, NUM 11:15 'let me not see MY evil' (for 'their' — the form 'your evil' stands at 2 Sam 16:8, Isa 47:10, computed), NUM 12:12 'HIS mother's womb... half HIS flesh' (for 'our'): the reading tradition's record of the ink's transmitted euphemisms at two of this portion's verses — RECORDED as the tradition's claim about the ink; the Shekhinah in every exile, returning 'WITH your captivity' (Deut 30:3's 'and He will return'); Pharaoh, Sisera, Sennacherib, Nebuchadnezzar, Haman. Onkelos keeps 11:15's pronoun and resolves 12:12's ('our sister... in her').",
  "middah": "plain (the tradition's record of the euphemisms read as it stands; the ink's forms computed)",
  "check": hc("Num 10:35", "משנאיך", 6, "'Your haters' — the clause the euphemism list opens on")},
]
C['num_11_complaint_quail'] = [
 {"id": "BH11A-01", "source": sif('85:1', '86:1') + '; ' + onk(11, 1, 3), "ref": "Num 11:1-3",
  "claim_en": "THE MURMURERS; 'THE PEOPLE' ARE THE WICKED; THE FIRE SANK IN ITS PLACE; NAMES BY THE EVENT. 'And the people were as murmurers' (the word's one seat — computed) — seekers of a pretext (2 Kgs 5:7; Judg 14:4) or blows or self-affliction or idolatry (four readings); 'THE PEOPLE' everywhere the wicked, 'MY PEOPLE' the upright — a lexical rule with proof-seats (Exod 17:4; Num 14:11; Jer 13:10 / Exod 7:16; Mic 6:3); 'in the ears of the LORD' — they meant Him to hear (Onkelos 'before the LORD'); 'the fire of the LORD' (11:1, 11:3 and Elijah's 1 Kgs 18:38) at the edge of the camp (Gideon's phrase) — the proselytes or the officers; 'the people cried to Moses' — the intercessor; 'the fire SANK' (the verb's one Torah seat) — in its place, not to heaven nor sideways; TABERAH named FOR THE EVENT, not before — as Massah-Meribah and the graves of lust: a naming rule read off 'because' (Onkelos renders the name: 'burning').",
  "middah": "plain (the Sifrei's lexical rule and readings recorded; the seats computed)",
  "check": hc("Num 11:2", "ותשקע", 6, "'and it sank' — the fire's verb, one seat")},
 {"id": "BH11A-02", "source": sif('86:1', '87:1') + '; ' + onk(11, 4, 5), "ref": "Num 11:4-5",
  "claim_en": "THE RABBLE IS THE MIXED MULTITUDE; THEY HAD FLOCKS; FREE OF COMMANDMENTS; THE FIVE FOODS. 'The rabble' (the word's one seat) — the proselytes 'added on' (Onkelos: 'the MIXED MULTITUDE', Exod 12:38's word — the translation's identification) or the elders (R. Shimon b. Menassia, from 'gather' 11:16) — the a-fortiori to the commoners either way; 'lusted a lust' (Ps 106:14 quotes it) — a thing they HAD: Exod 12:38's flocks, Num 32:1's cattle — a pretext; 'also the children of Israel wept again' — the first weepers Israel; 'the fish free' — no straw was free (Exod 5:18): free of MITZVOT; the manna took every taste EXCEPT the five named (R. Shimon — harmful to a nursling) or every taste unseen (the sages); THE INK: cucumbers, melons, onions, garlic at ONE SEAT EACH in the Bible, 'leeks' the homograph of 'grass' (computed); Onkelos' word for the cucumbers is 8:2's word for the LAMPS.",
  "middah": "plain (the Sifrei's readings recorded; the translation's identification read as it stands; the seats computed)",
  "check": hc("Num 11:4", "והאספסף", 6, "'and the rabble' — the word's one seat")},
 {"id": "BH11A-03", "source": sif('88:1') + '; ' + onk(11, 6, 7), "ref": "Num 11:6-7",
  "claim_en": "THE SPEAKER SPLIT — ONE VERSE, TWO SPEAKERS, SEVEN PARALLELS. 'Only to the manna are our eyes' (11:6) is ISRAEL'S; 'and the manna was like coriander seed, like bdellium' (11:7) is GOD'S ANSWER to the generations — the Sifrei assigns adjacent clauses to two voices, with parallels: Gen 38:25-26 (Judah / Scripture), Deut 25:18 (Israel faint / Amalek unfearing), Judg 5:28-31 (Sisera's mother / her ladies / Deborah), 1 Sam 4:8 (the righteous / the wicked), Jer 26:16-24, Ruth 3:13 (Boaz to his inclination / to Ruth): a teacher's attribution rule the catalog did not hold — REGISTERED as M-27 THE SPEAKER SPLIT (MOVE_CATALOG.md); the manna never expelled (Ps 78:25); the ink: 'coriander seed' at Exod 16:31 and here, 'bdellium' at Gen 2:12 and here (computed).",
  "middah": "M-27 (the speaker split — the clauses of one verse assigned to two voices by the teacher's recorded rule)",
  "check": hc("Num 11:7", "הבדלח", 6, "'the bdellium' — the narrator's clause, Gen 2:12's word")},
 {"id": "BH11A-04", "source": sif('89:1') + '; ' + onk(11, 8, 9), "ref": "Num 11:8-9",
  "claim_en": "THE MANNA CONVERTED TO EVERYTHING; LESHAD AS AN ACRONYM; THE TWO TASTES. 'They strolled and gathered' (one seat) — at the door before the sun; the mill, the mortar (one seat), the pot, the oven — 'it never descended to them': CONVERTED to their products, and to all the field's gatherings (Deut 2:7); Onkelos inserts 'whoever WISHED' twice (cut from the shelf's bytes) — the Sifrei's 'to whatever they wished' is the translation's clause; 'the moist cake of oil' (one seat) read as an acronym — dough, oil, honey (E30) — and the breast's five likenesses; THE INK'S TWO TASTES: Exod 16:31's honey wafer and 11:8's oil cake, one seat each (computed; the exam's Yoma 75b); the dew above and below; daily so hearts turn to their Father (R. Shimon), warm and light (R. Dostai).",
  "middah": "E30 (the notarikon on the moist cake; the conversion homilies plain in the note)",
  "check": hc("Num 11:8", "לשד", 6, "'the moist cake' — the word's one seat, the acronym")},
 {"id": "BH11A-05", "source": sif('90:1', '91:1') + '; ' + onk(11, 10, 15), "ref": "Num 11:10-15",
  "claim_en": "THE FAMILIES WEEP FOR THE FAMILY LAW; WHY HAVE YOU DEALT ILL — MOSES TWICE, ELIJAH ONCE; KILL ME FIRST. 'Weeping by its families' (one seat — computed): R. Nehorai — grief over the forbidden relations (a man had married his sister or aunt; the exam's Yoma 75a); 'at the door of his tent' — Exod 33:8-10's standing; God attenuates and Moses exacerbates here, the reverse at the calf; 'why have You dealt ill' — Exod 5:22 and here, Elijah at 1 Kgs 17:20: three forms, three seats (computed); the burden laid at Exod 32:34 and 6:13 'on the understanding they will curse and stone you'; 'did I conceive... beget' → Onkelos 'am I a FATHER... are they my CHILDREN', 'in your bosom' → 'in your STRENGTH'; 'the nursing-father' (the masculine form's one seat); 'I am not able alone' retold at Deut 1:9; 'kill me, kill' (one seat) — R. Shimon's executioner: die first, not Zedekiah's fate; 'MY evil' — the euphemism (84:4), the pronoun kept by Onkelos.",
  "middah": "plain (the Sifrei's readings recorded; the seats and the forms computed)",
  "check": hc("Num 11:10", "למשפחתיו", 6, "'by its families' — the weeping's one seat")},
 {"id": "BH11A-06", "source": sif('92:1', '93:1') + '; ' + onk(11, 16, 17), "ref": "Num 11:16-17",
  "claim_en": "SEVENTY UNTO ME; THE ELDERS HONORED AT EVERY SEAT; THE LORD GOING DOWN — ELEVEN TOKENS, THE SHELF SAYS TEN; THE LAMP THAT LOSES NOTHING. 'Gather unto Me seventy men' — the Sanhedrin in My name (seventy-one with Moses — Mishnah Sanhedrin 1:6); 'seventy men' at 11:16, 11:24, 11:25, the earlier seventy at Exod 24:1, 24:9 (computed); wise, strong, senior, versed; the elders honored at every seat (Exod 3:16, 24:1, 24:14; Lev 9:1) — the a-fortiori (I1) to flesh and blood; 'its officers' — the officers beaten in Egypt share the honor; 'I will come down' — 'one of the ten descents written in the Torah': THE INK CARRIES ELEVEN tokens of the LORD going down (Gen 11:5, 11:7, 18:21; Exod 3:8, 19:11, 19:18, 19:20, 34:5; Num 11:17, 11:25, 12:5 — computed); the Sifrei's list is not on this shelf — DIVERGE by one, recorded; Onkelos renders each in the portion 'revealed'; 'I will set apart of the spirit' (the verb at Gen 27:36, 11:17, 11:25) — a lamp lighting lamps, nothing lost: Onkelos 'I will MAKE GREATER' agrees; 'with you, not with them'.",
  "middah": "plain (the shelf's count against the ink's count recorded as a divergence; the rows read as they stand)",
  "check": hc("Num 11:17", "וירדתי", 6, "'and I will come down' — the eleventh of the ink's descents")},
 {"id": "BH11A-07", "source": sif('94:1', '95:1') + '; ' + onk(11, 18, 23), "ref": "Num 11:18-23",
  "claim_en": "ONE PLAGUE, TWO TIMERS; THE DAY-LADDER; SIX HUNDRED THOUSAND WITHOUT THE 'ABOUT'; IS THE WORD HELD BACK. 'Sanctify yourselves for tomorrow' — prepare for calamity (Jer 12:3; the imperative's one Torah seat, Joshua running the formula at the Jordan, Josh 3:5 — computed; Onkelos 'PREPARE'); the ladder — one day, two days (the dual the parser leaves silent), five, ten, twenty, a month of days (Gen 29:14's phrase); 'until a month' — the MEDIOCRE languished thirty days, the wicked died with the flesh between their teeth (11:33): one act, two timers by desert — a verdict table; 'you despised the LORD among you' → Onkelos 'the WORD of the LORD whose SHEKHINAH dwells among you' (two insertions); 'six hundred thousand on foot' — the parser reads 600,000; Exod 12:37 writes 'ABOUT six hundred thousand', 11:21 drops the 'about' (computed); R. Akiva plain, R. Shimon b. Yochai two ways (the flocks, the well's fish — a pretext; 'give and kill?'); 'is the LORD's hand short' (Isa 50:2, 59:1 the hand's other seats) → Onkelos 'shall the WORD of the LORD be held back'.",
  "middah": "plain (the Sifrei's two-tier verdict and readings recorded; the numbers and seats computed)",
  "check": hc("Num 11:20", "לזרא", 6, "'loathsome' — the word's one seat, the month's end")},
 {"id": "BH11A-08", "source": sif('95:2', '96:1') + '; ' + onk(11, 24, 30), "ref": "Num 11:24-30",
  "claim_en": "THE LOTS — SEVENTY-TWO BALLOTS; THE SAME MACHINE FOR THE 273; DID NOT CONTINUE / DID NOT CEASE; ELDAD AND MEDAD; WOULD THAT ALL WERE PROPHETS. 'Two men remained in the camp' (the construct 'two of' the parser's gap; Onkelos writes the two): their ballots remained — six per tribe is seventy-two, seventy marked 'elder', two blank; and for the 273 firstborn over the Levites (3:46) the same machine — 22,000 'Levite' and 273 'five shekels': THE LOT IS THE SELECTION MECHANISM of Bamidbar's redemption cell (the exam's Sanhedrin 17a) — routed to the compile's docket; or they hid and were exalted (R. Shimon): 'Moses dies and Joshua brings them in'; 'they prophesied and did not continue' (the clause's one seat; the idiom 'no more' at six other seats — computed) — the Sifrei's 'no more' against Onkelos' 'did NOT CEASE' (cut from the shelf's bytes): the spine disagrees with itself, DUAL-TRACK; 'among the written', 'from his youth', 'restrain them' one seat each — 'end them' or 'confine them' (Rebbi; Onkelos 'BIND them'); 'would that all the LORD's people were prophets' (one seat) — by direct inspiration; the calamity waited for the righteous.",
  "middah": "plain (the Sifrei's two readings and the translation's third recorded dual-track; the lots as the mechanism routed to the compile)",
  "check": hc("Num 11:25", "יספו", 6, "'[did not] continue' — the clause read two ways")},
 {"id": "BH11A-09", "source": sif('97:1', '98:1') + '; ' + onk(11, 31, 35), "ref": "Num 11:31-35",
  "claim_en": "THE QUAIL TWO CUBITS HIGH; TEN HOMERS — TEN ASSES; SLAUGHTERED OR IN LAYERS; THE GRAVES OF LUST AND HAZEROTH PLENE IN THE STORY, DEFECTIVE IN THE ITINERARY. 'It swept up quails' (the verb's one Torah seat; the quail at Exod 16:13, here, 11:32, Ps 105:40); a day's journey north and south (or above and below); 'about two cubits' — the dual at the ark's and table's seven seats and here (the parser silent; Onkelos 'a HEIGHT of two cubits'): hovering for easy gathering; 'he who gathered least' — the manna's word (Exod 16:17-18) — 'the least among them' ten kor (the homer as the kor; 'ten homers' the consonants of Joseph's 'ten asses', Gen 45:23 — computed; Onkelos 'heaps'); 'spread them a spreading' (the root's two Torah tokens both here) read 'SLAUGHTERED' (R. Yehudah — the exam's Chullin 27b) or 'in layers' (Rebbi); 'the flesh between their teeth' — the wicked's timer; 'a very great plague' (one seat); KIBROTH-HATTAAVAH named for the event (plene at 11:34-35, DEFECTIVE at 33:16-17, Deut 9:22 — computed; Onkelos renders the name); TWO HAZEROTHS in 11:35 — they set out, heard of Miriam, turned back (98:1); plene in the story, defective at 33:17-18, Deut 1:1.",
  "middah": "plain (the Sifrei's readings recorded; the dual, the spellings and the seats computed)",
  "check": hc("Num 11:32", "הממעיט", 6, "'he who gathered least' — the manna's word on the quail")},
]
C['num_12_miriam'] = [
 {"id": "BH12A-01", "source": sif('99:1') + '; ' + onk(12, 1, 1), "ref": "Num 12:1",
  "claim_en": "MIRIAM SPOKE FIRST; THE CUSHITE WOMAN IS THE BEAUTIFUL WOMAN, DISTANCED; THE A-FORTIORI OF SLANDER. 'And Miriam spoke, and Aaron' — the FEMININE SINGULAR verb before two subjects (Vpw3fs — computed): Miriam first, not her practice (Baruch before Jeremiah); 'dibbur' is harsh speech, 'amirah' imploration — a lexical rule with proof-seats (Gen 42:30; Num 21:5 / Gen 19:7; Num 12:6); how she knew — Zipporah unadorned; THE A-FORTIORI (I1): Miriam meant praise, increase and privacy and was punished — how much more one who defames, diminishes, in public (the exam's Arakhin 15a-16b; Deut 24:9); 'the Cushite woman' with the article, 'a Cushite woman' without (one seat each) — CUSHITE = EXCEPTIONAL as a Cushite in his skin (Saul, Israel, Baruch — a lexical rule): beautiful in appearance AND in deed; Onkelos renders both 'the BEAUTIFUL woman' and inserts 'he had DISTANCED' (cut from the shelf's bytes) — the spine agrees with itself twice on this verse.",
  "middah": "I1 (the Sifrei's a-fortiori from Miriam's punishment to the defamer; the grammar and the translation's moves computed and cut)",
  "check": hc("Num 12:1", "ותדבר", 6, "'and she spoke' — feminine singular, Miriam first")},
 {"id": "BH12A-02", "source": sif('100:1', '101:1') + '; ' + onk(12, 2, 3), "ref": "Num 12:2-3",
  "claim_en": "ONLY, ONLY WITH MOSES? — THE FOREFATHERS DID NOT SEPARATE; HUMBLE WRITTEN WITHOUT THE YOD. 'Is it only, only with Moses' (the doubled restrictive) — and not with the forefathers, who did not separate from their wives, and with us; 'and the LORD heard' — no one else there (R. Nathan: to Moses' face too, suppressed) — the clause opening both punishments, 11:1 and 12:2 (computed); 'humble' — in mind, not in wealth (Exod 11:3; the sapphire chips — 'work'/'work' Exod 32:16 / 24:10, I2); more than any man, not than the forefathers; THE INK: 'humble' WRITTEN without the yod and READ with it — the portion's one written-and-read pair (the Tanakh DB's bare token with its variant note; the snapshot store carries both tokens side by side, as at 1:16 — computed); Onkelos 'very meek'.",
  "middah": "ink (the written-and-read pair measured on both stores; the Sifrei's readings in the note with I2 on the tablets)",
  "check": hc("Num 12:3", "ענו", 6, "'humble' — the written form, without the yod")},
 {"id": "BH12A-03", "source": sif('102:1') + '; ' + onk(12, 4, 5), "ref": "Num 12:4-5",
  "claim_en": "SUDDENLY; THE THREE BY ONE UTTERANCE; AARON AND MIRIAM — THE ORDER REVERSED; A MAN IS NOT PRAISED TO HIS FACE. 'Suddenly' (three Torah seats with the nazirite's 6:9 — computed) — Moses feared it, God spoke it; 'the three of you' (one seat) — called by one utterance (Ps 62:12; Jer 23:29); 'in a pillar of cloud' (four seats; the descent one of the eleven) — to peace with myriads; 'He called Aaron and Miriam' — draw the one near, do not send the other away; THE INK'S REVERSAL: 'Miriam and Aaron' at 12:1, 'Aaron and Miriam' at 12:5; three then two (computed); why not Moses — so Israel not think him rebuked; so he not hear Aaron's; A MAN IS NOT PRAISED TO HIS FACE — R. Elazar b. Azaryah: part of his praise to his face — Noah 7:1 'righteous' before him against 6:9 'righteous, whole' behind him: THE STANDING SEAT — the Genesis unit read exactly this off the 6:9/7:1 ink-delta (gen_16_ark_spec G16-18), the Sifrei's own statement of the seated rule — CREDITED.",
  "middah": "plain (the Sifrei's conduct rules recorded; the Genesis seat credited by reference; the orders and seats computed)",
  "check": hc("Num 12:4", "שלשתכם", 6, "'the three of you' — the one utterance's word")},
 {"id": "BH12A-04", "source": sif('103:1') + '; ' + onk(12, 6, 8), "ref": "Num 12:6-8",
  "claim_en": "VISION AND DREAM FOR PROPHETS, MOUTH TO MOUTH FOR MOSES; NO MAN SEES AND LIVES; THE LIKENESS NO ONE MAY MAKE IS WHAT MOSES BEHOLDS. 'Hear, I pray, My words' — 'na' implores: the a-fortiori of conduct, and do not interrupt (R. Shimon b. Yochai); 'in a vision... in a dream' (the dream-word at six seats — Abimelech's, Jacob's, Solomon's; computed) — not so Moses, faithful in all My house (above the angels, R. Yossi); 'mouth to mouth' (one seat) — I told him to separate from his wife; 'in a vision' — of His WORDS, not the Shekhinah: 'no man shall see Me and live' (Exod 33:20) — the angels too (R. Akiva), the holy creatures (R. Shimon); 'not in riddles' — the riddle-word's one Torah seat; 'the likeness of the LORD he beholds' — His BACK (Exod 33:23): THE INK'S COUNTERPOINT — the likeness-word's eight Torah seats are SEVEN BANS on making one (Exod 20:4; Deut 4:12, 4:15, 4:16, 4:23, 4:25, 5:8) and ONE BEHOLDING (12:8 — computed); Onkelos 'SPEECH with speech', 'the likeness of the GLORY of the LORD', visions and dreams plural; 'against My servant, against Moses' (the doubled preposition, one seat) — against Me.",
  "middah": "plain (the Sifrei's rows read as they stand; the likeness-word's seats computed as the ink's own counterpoint)",
  "check": hc("Num 12:8", "ותמנת", 6, "'and the likeness of' — the one beholding among seven bans")},
 {"id": "BH12A-05", "source": sif('104:1', '105:1') + '; ' + onk(12, 9, 12), "ref": "Num 12:9-12",
  "claim_en": "HE TOLD THEM THEIR OFFENSE, THEN DEPARTED; THE CLOUD LEFT FIRST; LEPROUS AS SNOW; AARON TURNED FROM HIS OWN; A PRIEST DOES NOT INSPECT HIS KIN; THE COVERED THREE. 'The LORD's anger burned against THEM and He went' (the portion's fourth anger clause; 'them' plural — the exam's Shabbat 97a: Aaron too; Onkelos 'departed'): He apprised them, then decreed — the a-fortiori of anger (I1); 'the cloud departed' (one seat) — the pedagogue after the father leaves; 'leprous as snow' — Moses' hand (Exod 4:6), Miriam, Gehazi (2 Kgs 5:27 — computed; Onkelos 'WHITE as snow', then 'SHUT UP' — the leper's quarantine verb); 'Aaron turned' — was turned from HIS leprosy; R. Yehudah b. Beteira: who says Aaron was stricken, ZELOPHEHAD WAS THE WOOD-GATHERER, or Akavya was banned 'will pay' — against R. Akiva at 113:1: the shelf disagrees with itself on the record, the tent's num_15 unit carrying the dispute unresolved (NM15-01); 'as one dead' (Ps 31:13 the other seat) — the leper defiles by entry as the corpse by tent (I3); 'our sister loses on all accounts: I cannot quarantine, declare unclean or clean' — A PRIEST DOES NOT INSPECT HIS KIN (the exam's Zevachim 101b-102a); 'his mother', 'his flesh' — the euphemisms for 'our', RESOLVED by Onkelos ('for she is our sister; pray for this dead flesh in her, and let it be healed' — 12:12 rewritten, cut from the shelf's bytes).",
  "middah": "I3 (the leper-by-entry as the corpse-by-tent paradigm; the a-fortiori of anger and the kin rule plain in the note)",
  "check": hc("Num 12:10", "מצרעת", 6, "'leprous' — as snow, the phrase's three seats", nth=0)},
 {"id": "BH12A-06", "source": sif('105:1') + '; ' + onk(12, 13, 13), "ref": "Num 12:13",
  "claim_en": "THE SHORTEST PRAYER, COUNTED. 'God, I pray, heal, I pray, her' — FIVE WORDS, ELEVEN LETTERS, two 'I pray' (computed): two or three words of imploration before a request; 'saying' = answer me — the four places Moses asked to be answered (Exod 6:12; Num 27:15; Deut 3:23; here — R. Elazar b. Azaryah); why so short — Israel not say 'his sister in distress and he prolongs'; or the righteous decree (Job 22:28); R. Eliezer: not longer than Moses' forty days (Deut 9:18), not shorter than this — a time to be short and a time to be long (the exam's Berakhot 34a); Moses' four cries to the LORD (Exod 8:8, 15:25, 17:4; here — computed); Onkelos 'PRAYED' for 'cried', 'in entreaty' for 'I pray'.",
  "middah": "ink (the prayer's words and letters counted on the ink; the Sifrei's rows in the note)",
  "check": hc("Num 12:13", "רפא", 6, "'heal' — the prayer's third word")},
 {"id": "BH12A-07", "source": sif('106:1') + '; ' + onk(12, 14, 14), "ref": "Num 12:14",
  "claim_en": "DAYO — THE A-FORTIORI'S CAP STATED ON ITS HOME VERSE. 'If her father had spat in her face, would she not be ashamed seven days?' — R. Achi b. R. Yoshiyah: two rebukes — the father's seven would give Him who spoke and made the world FOURTEEN — 'BUT IT SUFFICES THAT WHAT IS DERIVED FROM AN A-FORTIORI BE AS THAT FROM WHICH IT IS DERIVED': seven — the tradition's own ceiling on I1, stated on the verse the Talmud derives it from (Bava Kamma 25a; Mishnah Bava Kamma 2:5 — the exam); the Holy One quarantined her, declared her unclean, declared her clean; THE INK: 'spat, spat' (the cognate's one seat) — the spit-root's Torah seats Lev 15:8, here, Deut 25:9's halitzah 'in his face' / 'in her face' (computed); 'would she not be ashamed' one seat; Onkelos renders the spitting as REBUKING — the Sifrei's 'two rebukes' is the translation's word.",
  "middah": "I1 (the a-fortiori with its dayo cap — the middot's own case law on this verse)",
  "check": hc("Num 12:14", "ירק", 6, "'spat' — the first of the doubled pair", nth=0)},
 {"id": "BH12A-08", "source": sif('106:1') + '; ' + onk(12, 14, 16), "ref": "Num 12:14-16",
  "claim_en": "MEASURE FOR MEASURE; THE QUARANTINE VERB ON THE PROPHETESS; AFTERWARD, TO PARAN. 'Shut up seven days outside the camp, and after she shall be gathered' (the parser reads 7, 7; 7): THE QUARANTINE VERB of Lev 13-14's nine leper seats at Miriam's two (computed) — the leper law's own word; 'the people did not journey until Miriam was gathered in' (one seat) — WITH THE MEASURE A MAN MEASURES: Miriam waited a short while for Moses at the river (Exod 2:4), so the Shekhinah, the ark, the priests, the Levites and the seven clouds waited seven days — Mishnah Sotah 1:9's row on this clause (E27 symmetry; the exam's Sotah 9b-13a); Joseph buried Jacob, Moses buried Joseph, the Holy One buried Moses — in Gad's portion though he died in Reuben's (four mils in His hand); 'afterward' at 12:14 and 12:16; from Hazeroth (plene) to the wilderness of Paran (six seats) — the arrival written at 10:12 and again here; the itinerary's 33:18 names Rithmah. THE TIMER for the compile: seven days, the camp held.",
  "middah": "E27 (measure for measure — the symmetry the Mishnah's own row states on this clause)",
  "check": hc("Num 12:15", "האסף", 6, "'the gathering in' — of Miriam, the camp's wait")},
]
n_claims = sum(len(v) for v in C.values())
assert n_claims == 34, n_claims
for u, claims in C.items():
    for c in claims:
        assert c['id'].startswith(UNITS[u]) and c['middah'] and c['check']['contains'], c['id']
        for s in c['source'].split('; '): assert s in CI[u], (c['id'], s)
    json.dump(claims, open(OUT[u], 'w', encoding='utf-8'), ensure_ascii=False, indent=1); open(OUT[u], 'a', encoding='utf-8').write('\n')
    print(f'{u}: {len(claims)} claims -> {OUT[u]}')
print(f'BEHA\'ALOTCHA: {n_claims} claims across {len(C)} manifests')
