#!/usr/bin/env python3
# THE NUMBERS WALK, sitting 11 — MIDIAN (2026-09-12; the owner: "ok go" after the recovery-file rereads, on the ruling READ THEN COMPILE): THE
# READING of Numbers 31:1-54 — ONE append-only ledger for the one draft (num_31_midian), written by one script from one reading pass. The
# spine: Onkelos Numbers 31 whole (54) + the Sifrei on Numbers piskaot 157-158 BY POSITION (12 rows; NO row on 31:25-54 — the shelf silent
# to 35:8). COVERAGE COMPUTED; THE INK FACTS computed (midian_ink.py, every fact an assert run by assert_driver.py — fourteen fell on the
# first typed pass, one on the second, each a measurement retyped from the leg print); every quotation CUT by consonants (the misses
# collected, asserted empty). Sitting 10's form.
import sys, os
SP = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, SP)
from midian_ink import *
from midian_rows_onkelos_b import R
from midian_rows_sifrei import S
assert not os.path.exists(OUT), f'ledger exists — append, never overwrite: {OUT}'
assert FAIL == [], FAIL
assert sorted(R) == SPAN and sorted(S) == [(p, r) for p in PISKAOT for r in range(1, SIF_ROWS[p] + 1)], (len(R), len(S))

SHELF = ('- THE SHELF BY POSITION (computed on the export\'s rows): the Sifrei on Numbers has TWO piskaot on chapter 31 — 157 (31:1, nine rows) and 158 (31:22, three rows) — TWELVE rows; every row\'s first citation is its own verse in order (no mistyped head in this chapter); the next head, 159, is 35:9: THE SHELF IS SILENT FROM 31:25 TO 35:8 — the division, the tribute, the census of the spoil and the officers\' gold, then chapters 32, 33 and 34 whole (165 verses, computed) — the reading form holding on the translation alone for the fifth stretch of the walk. THE ROWS\' OWN DEFECTS, read to their verses in BOTH files (RESEARCH_LOG.md): 157:3\'s English drops "the words of R. Yishmael", REVERSES R. Akiva\'s arm ("to exclude the tribe of Levi" for the Hebrew\'s "to include") and swaps his proof phrase; 157:4\'s English inserts "(Yithro, viz. Shemot 2:16)" as Phinehas\'s mother\'s father where the Hebrew\'s proof is Genesis 37:36 — Joseph, sold by "the MEDANITES" (Keturah\'s other son\'s name, 25:2; 37:28 has the Midianites); 157:5\'s English supplies the Talmud\'s "four judicial death penalties" for the Hebrew\'s "by a court" (R. Natan), names "R. Eliezer" for the Hebrew\'s R. Elazar, and puts the idolatry on the castles (Onkelos\'s assignment) where the Hebrew puts it on the cities; 157:6\'s English cites "(31:7)" for 31:17\'s second "kill" and DROPS THE HEBREW\'S SECOND READING — "we do not punish by inference" — with R. Yishmael\'s name; 157:7\'s English replaces the conclusion with "(see Chukath #126)"; 157:8\'s Hebrew runs the freed-word identity\'s first leg backward ("as the garment THERE has goat-work like sack, so HERE" — goat-work is 31:20\'s word), the English the way the ink allows; 157:9\'s English drops R. Yoshiyah\'s name; 158:2\'s English supplies the Mishnah\'s whitening-and-boiling split (Avodah Zarah 5:12) for the Hebrew\'s one list, and one a-fortiori for the Hebrew\'s two; 158:3\'s Hebrew misquotes 31:24 in the Levites\' form (8:7) and cites 19:16\'s "slain by the sword" as 19:19, the English citing "Vayikra 19:19" for Bamidbar. No prior ledger had read an Onkelos row of 31 or a Sifrei row of 157-158 (eight ledgers NAME verses of the chapter as cross-references — a name is not a read; the Chukat ledger\'s rows 126:1, 127:1, 130:1 speak of the Midian vessels and the sword from chapter 19\'s side, quick-looked, credit guard 1); FRESH throughout.')
PARSER = ('- THE ENGINE\'S PARSER ON THE CHAPTER (measured on cold_run_sequence.ink_numbers and ink_ordinals after 10b, BEFORE any claim was typed): RIGHT on the muster (31:4 "a thousand to a tribe, a thousand to a tribe" read as two thousands [1000, 1000] — the distributive; 31:5 [1000, 12000]; 31:6 [1000]), on the five kings (31:8 [5]), on the schedule (31:19 [7] with the ordinals [3, 7]; 31:24 [7]), on THE SPOIL\'S CENSUS (675,000 / 72,000 / 61,000 / 32,000), THE HALVES (337,500 / 36,000 / 30,500 / 16,000 at both seats), THE TRIBUTES (675 / 72 / 61 / 32) and THE SHEKELS (16,750); the captains of "the thousands and the hundreds" (31:14, 48, 52, 54) rightly no number (census_probes G3 — the old [2100] retired at 5b); no starred homograph in fifty-four verses; and SILENT ON THE RATIO\'S DENOMINATOR — THE FRACTION CLASS "one of the N": 31:28 "one soul of the five hundred" [1], 31:30 and 31:47 "one held of the fifty" [1] — the class NAMED AND LEFT at census_probes R29; its Bible seats SIX (the three here; Ecclesiastes 7:28 "one of a thousand"; Ezekiel 45:15 "one of the flock of the two hundred"; Nehemiah 11:1 "one of the ten", read [1, 9] — the nine parts read, the ten not) — the compile\'s probe list; the zaqef closes "one soul" and the denominator stands in the next phrase (computed on the accents). 32:1 empty.')
REGISTER = ('- THE FRAMES AND THE REGISTER: THIRTY narrative verbs in twenty-seven verses (computed on the morphology) — a RUN chapter: two divine frames (31:1 "and the LORD spoke to Moses saying"; 31:25 "and the LORD said to Moses saying" — the said-saying frame\'s five Torah seats), Moses\' relay (31:3 "and Moses spoke to the people saying" — one Bible seat), Eleazar\'s law (31:21 "and Eleazar the priest said" — one seat: the priest speaks the heifer\'s statute), the officers\' first person (31:50 "and WE have brought"), and FOUR RECEIPTS "as the LORD commanded Moses" (31:7, 31, 41, 47) — the most of any Numbers chapter (Exodus 39 and 40 seven each, Leviticus 8 five; 41 seats of the form) — the register gate\'s four seats, with the four count lines (31:35, 36, 40, 46), declared NONE now and paid by the compile; "and Moses was wroth" — the wrath-verb with Moses as its subject at three Torah seats (Exodus 16:20, Leviticus 10:16, 31:14), the Sifrei 157:9\'s three anger-and-error places (Leviticus 10:16, Numbers 20:10, 31:14) sharing two of them, Meribah\'s verse carrying no wrath-verb; the store\'s own glosses read back: the wrath-verb "and-crack-off", the sword "in-drought", the prey "the-jaws", the purify-verb "sin", the washing "and-trample", the tent of meeting "seasons" — Strong\'s homonyms at six words (the display layer\'s override file, RESEARCH_LOG.md).')
INK = [
 '- THE COMMAND AND ITS RUN SHARE THE WORD (computed): "the Midianites" with the article stands at TWO Bible seats — the command "harass the Midianites" (25:17) and "avenge the vengeance of the children of Israel from the Midianites" (31:2); "avenge the vengeance" the doubled root\'s one seat; Moses\' relay turns Israel\'s vengeance into "the vengeance of the LORD" (31:3 — the phrase\'s three other seats Babylon\'s, Jeremiah 50:15, 28; 51:11); "afterward you shall be gathered to your people" one seat — the death of 27:13 sequenced after the war; "arm yourselves" one seat, the root\'s Torah seats all in chapters 31-32 (Gad and Reuben\'s seven "armed" the next chapter\'s) and Deuteronomy 3:18; "a thousand to a tribe" three seats all here, the doubled phrase one — 1,000 × 12 = 31:5\'s twelve thousand, the ink\'s own product; "were delivered" and "to commit" the deliver-root\'s two Torah seats, both in this chapter; the trumpets\' ONE narrative seat in the Torah (10:8-10 the law; 2 Chronicles 13:12 the phrase\'s other seat) — 10:9\'s war clause run, the beha runner\'s open trumpets debit.',
 '- THE WAR (computed): "they warred" one seat; "and they killed every male" — Shechem\'s the only other seat (Genesis 34:25); "the kings of Midian" four Bible seats, Gideon\'s two the others (Judges 8:5, 12, 26); "the five kings of Midian" one; the five names retold at Joshua 13:21 as "the princes of Midian... the princes of Sihon, dwelling in the land", and 13:22 adds "the soothsayer" to Balaam and writes "to their slain" for "upon their slain" (the word\'s three seats); Zur is Cozbi\'s father (25:15); "Balaam son of Beor" five seats; "they killed by the sword" with Elijah\'s (1 Kings 19:10, 14); the sword in Balak\'s chapter thrice (22:23, 31 the angel\'s; 22:29 "would there were a sword in my hand" — the ass\'s clause the compile closes at 31:8); THE BOOTY\'S FOUR NOUNS — the spoil (two), THE PREY (five of the word\'s six Bible seats this chapter\'s), the captives (three), the plunder (four) — and THE TRIBUTE-WORD\'S SIX BIBLE SEATS ALL HERE (31:28, 37, 38, 39, 40, 41); "their castles" four Bible seats, Onkelos "their houses of worship"; "the plains of Moab by the Jordan of Jericho" (the bare form one seat; the book\'s eight and seven).',
 '- THE WRATH AND THE WOMEN (computed): "the officers of thousands and the officers of hundreds" — Jethro\'s grades (Exodus 18:21, 25; Deuteronomy 1:15) as the army\'s ranks, the pair\'s two seats both here (31:14, 48); "the appointed of the host" here and Jehoiada\'s (2 Chronicles 23:14); "have you let every female live" the midwives\' verb (Exodus 1:17-18), one seat; "keep alive" one; "by the word of Balaam" one — Onkelos "by the counsel"; "the matter of Peor" two (25:18, 31:16); "treachery against the LORD" the guilt offering\'s and the suspected wife\'s phrase (Leviticus 5:21, Numbers 5:6); Peor\'s plague named five times (25:8, 9, 18, 19; 31:16); "in the congregation of the LORD" here and Joshua 22:17 — PHINEHAS HIMSELF retelling the clause; 31:17 opens and closes on "kill"; "lying with a male" — the phrase\'s Bible seats this chapter\'s three (31:17, 18, 35) and JABESH-GILEAD\'S TWO (Judges 21:11-12): twelve thousand sent (31:5\'s number), every male and every woman who knew a man devoted, four hundred virgins kept — the sentence RUN in Judges with its number and its phrase; Deuteronomy 20:13-14 spares "the women and the little ones" — this chapter stricter on both.',
 '- THE PURIFICATION (computed): "on the third day and on the seventh day" three seats (19:12, 19:19, 31:19 — the heifer\'s schedule quoted); the purify-verb\'s six Torah tokens all in chapters 19 and 31; "whoever has killed a soul", "whoever has touched a slain one", "you and your captives" one seat each; 19:16\'s "slain by the sword" the Sifrei 158:3\'s sword unclean seven days (Chukat\'s rows 127:1, 130:1); THE FOUR MATERIALS against Leviticus 11:32\'s four — wood, garment, skin shared, SACK there against GOAT-WORK here ("work of goats" one seat; "sack" two Torah seats) — the freed-word identity of 157:8; THE SIX METALS in one verse — tin\'s one Torah seat (its look-alikes the verb "separated", 16:9 and Deuteronomy 10:8), lead\'s two (Exodus 15:10 and this); "only" twice; "the water of sprinkling" four seats all in 19 and 31; "pass through the fire", "pass through water" one each; "wash your garments on the seventh day and be clean... and afterward come into the camp" against 19:19\'s "wash his clothes and bathe in water and be clean AT EVENING" — the Sifrei 158:3 likening both ways; "afterward he shall come into the camp" the leper\'s and the heifer-priest\'s (Leviticus 14:8, Numbers 19:7); Onkelos makes the purifying the SPRINKLING ("you shall sprinkle on him", "it shall be sprinkled").',
 '- THE DIVISION AND THE TRIBUTE (computed): "take the sum" the census formula\'s singular imperative, one seat (Exodus 30:12 "when you take the sum" — the ransom\'s verse); "the heads of the fathers of the congregation" one seat — the census staff; THE HALF-ROOT EIGHT TOKENS IN FIVE SPELLINGS (31:27, 29, 30, 36, 42 ×2, 43, 47) — "the half" the noun\'s one seat, "half" in the HALF-SHEKEL\'s spelling (Exodus 30:13, 38:26) at 31:29 and 31:42; "those who took the war" one, "who went out to the host" two, "the men of war" (Deuteronomy 2:14, 16 — the generation that died; 31:28, 49); "the LORD\'s heave-offering" eleven seats — THE HALF-SHEKEL\'S (Exodus 30:14, 15), the tabernacle donation\'s (35:5, 21, 24), the tithe\'s tithe (18:26, 28, 29), this chapter\'s two, Hezekiah\'s; "the Levites who keep the charge of the tabernacle of the LORD" two seats both here — 1:53\'s charge; 31:30 adds "of all the beasts" to 31:28\'s four classes; the priest\'s rate one of five hundred, the Levites\' one of fifty — ten times; the equal halves — David\'s statute at Ziklag (1 Samuel 30:24-25 "they shall share alike... a statute and an ordinance for Israel") and Joshua 22:8\'s "divide the spoil of your enemies with your brothers" (Gad and Reuben\'s return) are the ink\'s kin, and NO ROW OF THE DECLARED SHELF LINKS THEM to 31:27: observed, not linked (THE LINK REVIEW LAW).',
 '- THE ARITHMETIC IS EXACT (computed on the parser\'s own reads): the four totals 675,000 / 72,000 / 61,000 / 32,000 (840,000 heads; every total a multiple of a thousand); the warriors\' half 337,500 / 36,000 / 30,500 / 16,000 = the totals ÷ 2; the tribute 675 / 72 / 61 / 32 = the halves ÷ 500 (840 heads to the priest); the congregation\'s half the same four numbers (31:43-46); THE LEVITES\' SHARE STATED AS A RATE AND NEVER AS A NUMBER — 337,500 ÷ 50 = 6,750 sheep, 720 cattle, 610 donkeys, 320 persons: 8,400 heads, ten times the priest\'s, computed by this reading and never written; "the rest of the booty which the people of the host had plundered" — the soldiers\' private plunder (31:53 "each for himself") outside the count; 16,750 shekels of gold (Onkelos: selas — the conversion layer); Gideon\'s Midianite gold the word\'s second count (1,700 shekels of earrings, Judges 8:26).',
 '- THE OFFICERS\' GOLD IS THE RANSOM OF EXODUS 30 RUN AT A COUNT (computed): "your servants have taken the sum of the men of war... and not one man of us is missing" (Nabal\'s shepherds\' word for the missing, 1 Samuel 25:7, 21); "the LORD\'s offering" the second Passover\'s phrase (9:7, 13); THE FIVE ORNAMENTS — the armlet (Saul\'s, 2 Samuel 1:10), the bracelet (Rebekah\'s, Genesis 24:22; the heifer chapter\'s "a cover BOUND on it", 19:15, its homograph), the ring (fifteen seats), the earring (Ezekiel 16:12), the kumaz (the tabernacle donation\'s, Exodus 35:22 — the two gold lists share the ring and the kumaz and the words "articles of gold"); "to atone for our souls" one seat — the half-shekel\'s "TO ATONE FOR YOUR SOULS" (Exodus 30:15, 16; Leviticus 17:11 the blood\'s); "a memorial for the children of Israel before the LORD" one seat — EXODUS 30:16\'S SIX WORDS in another order; the trumpets\' "you shall be REMEMBERED before the LORD" (10:9) at the war\'s opening and "a MEMORIAL before the LORD" at its close, one root; the sum, none missing, the atonement, the memorial: Exodus 30:11-16\'s spec run — a REFERENCE by the shared words, the compile\'s CALL into the half-shekel engine.',
 '- ONKELOS\' MOVES (cut from the shelf\'s bytes): "the vengeance of the LORD" rendered "the vengeance of the JUDGMENT of the people of the LORD" (31:3 — the buffer); "were delivered" rendered "were chosen" (31:5); "the trumpets of alarm" "the trumpets of the wailing-blast"; "their castles" "their houses of worship" (31:10); "by the word of Balaam" "by the COUNSEL of Balaam" (31:16); "purify yourselves" rendered "you shall SPRINKLE on him" (31:19, 20) and "it shall be sprinkled" (31:23); "the water of sprinkling"; tin and lead by their Aramaic names; "take the sum" "receive the account" (31:26); "halve" "divide"; the tribute "a levy", the heave-offering "a separation"; "one held" "one that is held"; "missing" rendered "strayed" (31:49); the five ornaments in Aramaic; "shekel" rendered "sela" (31:52); "the tent of meeting" "the tabernacle of time".',
 '- THE SHELF\'S CITATIONS READ TO THEIR VERSES (computed): 22:4 and 22:7 (Moab first); Genesis 36:35 (Hadad who smote Midian in the field of Moab); Deuteronomy 3:18 ("armed shall you pass over"); Nahum 1:2; Exodus 17:4 ("a little more and they will stone me"); Genesis 37:36 (the Medanites sold Joseph) against 37:28 and 25:2; 4:20 (the holy covered); 21:26 and Genesis 24:10 ("from his hand", "in his hand"); Joshua 13:22 (Balaam the soothsayer); Exodus 14:7, 14:14; Isaiah 63:10; Lamentations 2:5; Joshua 7:1 (Achan); 19:14 (the tent); Leviticus 11:32 (skin or sack); Leviticus 10:16 and 20:10 (the anger); Esther 2:22 (in the name of its sayer); 19:16 and 19:19 (the sword, the evening).',
]
CROWNS = [
 '- THE COMMAND AND ITS RUN SHARE THE WORD: "the Midianites" with the article at two Bible seats — 25:17 "harass the Midianites" and 31:2 "avenge... from the Midianites" — the Balak runner\'s open debit on Israel and the line that closes it (computed).',
 '- THE INK\'S OWN PRODUCT: "a thousand to a tribe, a thousand to a tribe" (31:4) and "twelve thousand" (31:5) — 1,000 × 12; R. Yishmael\'s 24,000 reads the doubling twice, R. Akiva\'s 12,000 once — the parser\'s distributive read [1000, 1000] and the Sifrei\'s dispute on one seat (the English reversing R. Akiva\'s Levi arm) (computed).',
 '- THE TRUMPETS\' ONE NARRATIVE SEAT IN THE TORAH: "the trumpets of alarm in his hand" (31:6) — the war clause of 10:9 ("you shall sound an alarm... and be remembered before the LORD") run, the phrase\'s other seat Abijah\'s war (2 Chronicles 13:12) (computed).',
 '- JOSHUA 13:21-22 RETELLS 31:8 WITH THREE DELTAS: the five kings as "the princes of Sihon, dwelling in the land", Balaam "the soothsayer", "to their slain" for "upon their slain"; and the sword Balaam wished against the ass (22:29) is the sword he dies by (computed).',
 '- THE TRIBUTE-WORD\'S SIX BIBLE SEATS ARE ALL THIS CHAPTER\'S, and five of the prey-word\'s six (computed): the chapter\'s own vocabulary of the spoil.',
 '- PHINEHAS RETELLS 31:16: "and there was the plague in the congregation of the LORD" stands here and in Phinehas\'s own speech at Joshua 22:17 (computed); Peor\'s plague named five times.',
 '- JABESH-GILEAD RUNS THE SENTENCE OF 31:17-18: "lying with a male" at this chapter\'s three seats and Judges 21:11-12 alone in the Bible — twelve thousand sent (31:5\'s number), the men and the women who knew a man devoted, four hundred virgins kept — the demonstrate-by-RUN form in the Prophets (computed).',
 '- THE SIX METALS IN ONE VERSE — tin\'s one Torah seat, lead\'s two; and the four materials of 31:20 against Leviticus 11:32\'s four with SACK for GOAT-WORK the delta the Sifrei\'s freed-word identity works (computed).',
 '- ELEAZAR SPEAKS THE HEIFER\'S STATUTE: "this is the statute of the Torah" at 19:2 and 31:21 alone; the purify-verb\'s six Torah tokens and "the water of sprinkling"\'s four seats all in chapters 19 and 31; "and Moses was wroth" — the verb with Moses as subject at three Torah seats, the Sifrei\'s three anger-and-error places sharing two (computed).',
 '- THE ARITHMETIC EXACT AND THE LEVITES\' SHARE UNWRITTEN: totals ÷ 2 = the halves, the halves ÷ 500 = the tributes (675, 72, 61, 32 — 840 heads), and the Levites\' one-of-fifty never given as a number — 6,750 / 720 / 610 / 320, 8,400 heads, computed; THE FRACTION CLASS "one of the N" the parser leaves silent at 31:28, 30, 47 — six Bible seats (computed).',
 '- THE OFFICERS\' GOLD RUNS THE HALF-SHEKEL\'S SPEC: the sum taken and none missing (31:49), "to atone for our souls" (31:50 — Exodus 30:15-16\'s words), "a memorial for the children of Israel before the LORD" (31:54 — Exodus 30:16\'s six words), the kumaz and the ring shared with the tabernacle donation\'s list (Exodus 35:22) (computed).',
 '- THE HALF-ROOT\'S FIVE SPELLINGS in eight tokens, "half" at 31:29 and 31:42 in the half-shekel\'s form; "the LORD\'s heave-offering" at the half-shekel\'s two seats, the donation\'s three, the tithe\'s three, this chapter\'s two (computed).',
 '- THE EXPORT\'S DEFECTS, READ IN BOTH FILES: an attribution dropped three times (R. Yishmael twice, R. Yoshiyah), R. Akiva\'s arm REVERSED, an ancestor INSERTED against the row\'s own proof, the Talmud and the Mishnah SUPPLIED at two rows, a rule about rules ("we do not punish by inference") DROPPED, a name garbled (Elazar/Eliezer), a citation (31:7) and a book (Vayikra) wrong, a lemma misquoted, an identity\'s leg run backward — thirteen defects read to their verses (computed on the bytes).',
 '- THE SIFREI\'S OWN CASE LAW on this chapter: the freed-word identity (157:8) run two ways; the a-fortiori refused on a penalty — WE DO NOT PUNISH BY INFERENCE (157:6); the doubled verb closing a paragraph (R. Yishmael, 157:6); anger begets error at three places (157:9); "in the name of its sayer" (157:9); "only" divides (158:1); the two-way likening of the camp and the evening (158:3); the shelf silent on thirty verses of law and count.',
]
TESTING = ('THE TESTING SHELF routed to Step 5 (the compile sitting\'s docket, per gap): Mishnah Avodah Zarah 5:12 with Avodah Zarah 75b-76b (THE VESSELS OF MIDIAN — the whole kashering sugya\'s seat: the fire, the boiling, the immersion, "everything that comes into the fire"); Pesachim 30b and 44b (the absorptions); Mishnah Kelim 11:1 and 15:1 (metal vessels; the ass\'s girth), Shabbat 64a-b (the work of goats — spun and woven; the five ornaments and the kumaz; the officers\' atonement "for our souls"); Nazir 53b-54b, Pesachim 14b, Chullin 3a (the sword as the slain — seven days), Mishnah Ohalot 1:2-3 (vessels, man and vessels); Yevamot 60b (the proselyte under three — R. Shimon ben Yochai), Kiddushin 78a; Sanhedrin 106a-b (Balaam\'s death), Sanhedrin 105a (the two dogs), Bava Kamma 38a (Midian and Moab), Sotah 43a (Putiel — Joseph and Jethro; Phinehas the anointed for war), Sanhedrin 54a and Makkot 5b (we do not punish by inference), Pesachim 66b (anger and forgetting), Megillah 15a (in the name of its sayer), Sifrei Zuta and Numbers Rabbah outside scope; the division and the tribute — Mishnah Terumot 4:3 with Jerusalem Talmud Terumot 4:3 ("one of fifty" — the Levites\' tribute the terumah\'s middling rate), Bekhorot and Menachot silent; the half-shekel engine (Exodus 30:11-16) by CALL for the ransom at a count; the heifer runner by CALL for the water of sprinkling; the Balak runner\'s open debit and Balaam\'s death row; the beha runner\'s trumpets debit.')
DECL = ('the portion Matot\'s second chapter read as ONE draft, num_31_midian 31:1-54 (the chapter whole; the next draft, num_32_gad_reuben, opens at 32:1); chapter 30 frozen and compiled at sittings 10 and 10b')
SITTING = 'THE NUMBERS WALK sitting 11 — MIDIAN'
verses = list(range(1, 55))
sif_cites = [f'Sifrei Bamidbar {p}:{r}' for p in PISKAOT for r in range(1, SIF_ROWS[p] + 1)]
cites = [f'Onkelos Num 31:{v}' for v in verses] + sif_cites
N_ALL = len(cites); NS = len(sif_cites); NO = len(verses)
cnt = Counter(R[(31, v)][0] for v in verses); scnt = Counter(S[(p, r)][0] for p in PISKAOT for r in range(1, SIF_ROWS[p] + 1))
heads_txt = ', '.join(f'{p} on {head(p)[0]}:{head(p)[1]} ({SIF_ROWS[p]} row{"s" if SIF_ROWS[p] > 1 else ""})' for p in PISKAOT)
hdr = (f'# Numbers 31:1-54 derivation — Onkelos + the Sifrei on Numbers as the spine (its piskaot found BY POSITION), '
       f'{SITTING}, {TITLE} ({DATE}; the owner: "ok go" after the recovery-file rereads, on the ruling NUMBERS IN ORDER FROM 1:1 and READ THEN COMPILE). '
       f'DECLARED (THE_STEPS Step 2, the spine default of 2026-08-27, read at the PARASHAH GRAIN — speed ruling (a): {DECL}): scope = Onkelos Numbers 31:1-54 ({NO} verses, fresh) '
       f'+ the Sifrei on Numbers piskaot {heads_txt} BY POSITION ({NS} rows at the shelf\'s row grain; the rows\' own defects read to their verses in both files — RESEARCH_LOG.md; every head asserted between its neighbors and against its rows\' own citations; NO row on 31:25-54 — the shelf silent to 35:8, {SILENT} verses computed). {TESTING} OUTSIDE DECLARED SCOPE, enumerated and unread (the shelf\'s other works on Numbers, {len(outside)} directories): {", ".join(outside)}.\n\n')
body = f'## Sifrei Bamidbar piskaot 157-158 ({NS} rows, read whole — the heads by position: {heads_txt}; no row from 31:25 to 35:8)\n'
for p in PISKAOT:
    for r in range(1, SIF_ROWS[p] + 1):
        verdict, prose = S[(p, r)]
        body += f'- Sifrei Bamidbar {p}:{r} — {verdict}. {prose}\n'
body += f'\n## Onkelos Numbers 31:1-54 ({NO} verses, read whole)\n'
for v in verses:
    verdict, prose = R[(31, v)]
    body += f'- Onkelos Num 31:{v} — {verdict}. {prose}\n'
body += '\n## The ink beside the shelf (computed by this script from the Tanakh DB, the snapshot store and the shelf — never recited)\n'
body += SHELF + '\n' + PARSER + '\n' + REGISTER + '\n'
for line in INK: body += line + '\n'
body += '\n## The finds (this ledger\'s crowns)\n' + '\n'.join(CROWNS) + '\n'
body += (f'\n## CITE INDEX — every source opened, each fully named\n(one name per line; coverage COMPUTED against the shelf by the ledger script write_midian_ledger.py: Onkelos Numbers 31:1-54 {NO} verses — missing 0, extra 0; the Sifrei on Numbers piskaot 157-158, {NS} rows at the shelf\'s own row counts — missing 0, extra 0)\n')
body += '\n'.join(cites) + '\n'
body += f'({NO} Onkelos verses fresh + {NS} Sifrei Bamidbar rows fresh = {N_ALL} sources in this ledger.)\n\n'
body += (f'**read: {N_ALL} of {N_ALL} — COMPLETE** ({NO} Onkelos verses and {NS} Sifrei rows opened and verdicted this sitting at the shelf\'s row grain, coverage computed by script — missing 0, extra 0; '
         f'verdicts MATERIAL {cnt["MATERIAL"]} Onkelos, CONTEXT {cnt["CONTEXT"]} Onkelos, MATERIAL {scnt["MATERIAL"]} Sifrei, CONTEXT {scnt["CONTEXT"]} Sifrei — the counts the script\'s own Counter measured)\n')
assert FAIL == [], FAIL
open(OUT, 'w', encoding='utf-8').write(hdr + body)
print(f'wrote {OUT}: {N_ALL} sources, Onkelos MATERIAL {cnt["MATERIAL"]} / CONTEXT {cnt["CONTEXT"]}; Sifrei {NS} rows MATERIAL {scnt["MATERIAL"]} / CONTEXT {scnt["CONTEXT"]}; bytes {len((hdr + body).encode())}')
